### PR TITLE
Slug: allow unicode characters

### LINKED ISSUE #12546: Permalink: Slug input field strips unicode characters
## Bug Description

The permalink slug field does not show foreign language special characters when using it as a title or when entering it in the slug field.

<details>
<summary>AMP Bug (out of scope for this project)</summary>

The story bookend is being displayed with HTML markup when the story title or permalink slug contains language special characters.

Example story URL: https://feignednorth.s4-tastewp.com/web-stories/%e0%b0%87%e0%b0%82%e0%b0%a1%e0%b0%bf%e0%b0%af%e0%b0%be-%e0%b0%b8%e0%b0%bf%e0%b0%ae%e0%b1%86%e0%b0%82%e0%b0%9f%e0%b1%8d%e0%b0%b8%e0%b1%8d-%e0%b0%aa%e0%b1%88%e0%b0%a8-%e0%b0%95%e0%b1%87%e0%b0%b8/

</details>

## Expected Behaviour

The slug should display the language characters. 

## Steps to Reproduce

1. Create a new story
2. Use “ఇండియా-సిమెంట్స్-పైన-కేస” as title
3. Publish the story.
4. Note Permalink Slug field.

-> Compare the same with Gutenberg where this just works.

## Additional Context

Screen Shot 2022-10-25 at 9 41 28 AM

Support Topic: https://wordpress.org/support/topic/doesnt-tech-url

- Plugin Version: 1.25.1
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by miina**
## Summary
Allows unicode characters in the slug. Also, adds using `remove-accents` package.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open the editor Document panel and go to the Permalink section
2. Paste in a unicode slug, for example హల-వరలడ or Γειά σου Κόσμε
3. Verify a slug is created and characters not removed.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12546

### CODE REVIEW

**Comment by swissspidy** [comment]
While we're at it:

In WordPress, when you publish a post with the title `Kanji (漢字)`, the slug field looks like this:

Screenshot 2022-11-02 at 10 38 52

Whereas we show the encoded slug:

Screenshot 2022-11-02 at 10 39 31

Can we align this as well?

Otherwise looks good

File: packages/story-editor/src/utils/cleanForSlug.js [hunk 1]
```diff
@@ -15,18 +15,23 @@
  */
```
Comment (spacedmonkey) [inline packages/story-editor/src/utils/cleanForSlug.js:15]: Wonder if this function should live in the url package?

File: packages/story-editor/src/utils/test/cleanForSlug.js [hunk 2]
```diff
@@ -58,10 +58,15 @@ describe('cleanForSlug', () => {
...
   it('should remove all illegal characters', () => {
-    const result = cleanForSlug('Hello-?,:;!"World');
+    const result = cleanForSlug('Hello-?-,:;!"World');
     expect(result).toBe('hello-world');
   });
 
+  it('should allow using unicode characters', () => {
+    const result = cleanForSlug('హల-వరలడ');
+    expect(result).toBe('హల-వరలడ');
+  });
```
Comment (spacedmonkey) [inline packages/story-editor/src/utils/test/cleanForSlug.js]: Lets add a data set of different slugs and expected return. Maybe test [Cyrillic script](https://en.wikipedia.org/wiki/Cyrillic_script), Arabic, Other [unicode characters](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin_Extended_Additional), accented characters like È, hindi characters and mandarin chinese.

File: packages/story-editor/src/utils/cleanForSlug.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/utils/cleanForSlug.js:15]: Don't see a need right now, since it's editor-specific. But we can discuss in a separate ticket.

File: packages/story-editor/src/utils/test/cleanForSlug.js (hunk 2 above)
Comment (miina) [reply packages/story-editor/src/utils/test/cleanForSlug.js]: Added a few more in [7565ca8](https://github.com/GoogleForCreators/web-stories-wp/pull/12603/commits/7565ca80014e8417df5fb0132b745752847b38b0). Accented characters are already handled in a previous test (see the first test of the file).

File: packages/story-editor/src/utils/test/cleanForSlug.js [hunk 3]
```diff
@@ -58,10 +58,28 @@ describe('cleanForSlug', () => {
   });
 
   it('should remove all illegal characters', () => {
-    const result = cleanForSlug('Hello-?,:;!"World');
+    const result = cleanForSlug('Hello-?-,:;!"World');
     expect(result).toBe('hello-world');
   });
 
+  it('should allow using unicode characters', () => {
```
Comment (swissspidy) [inline packages/story-editor/src/utils/test/cleanForSlug.js]: Nit: could use [`it.each`](https://jestjs.io/docs/api#testonlyeachtablename-fn-2)

File: packages/url/src/test/safeDecodeUriComponent.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * Internal dependencies
+ */
+import safeDecodeURIComponent from '../safeDecodeUriComponent';
+
+describe('safeDecodeURIComponent', () => {
+  it('should decode the URI correctly', () => {
```
Comment (swissspidy) [inline packages/url/src/test/safeDecodeUriComponent.js]: Nit: could use [`it.each`](https://jestjs.io/docs/api#testonlyeachtablename-fn-2)

File: packages/story-editor/src/utils/test/cleanForSlug.js (hunk 3 above)
Comment (spacedmonkey) [reply packages/story-editor/src/utils/test/cleanForSlug.js]: +1

File: packages/url/src/test/safeDecodeUriComponent.js (hunk 4 above)
Comment (spacedmonkey) [reply packages/url/src/test/safeDecodeUriComponent.js]: +1

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Tested this via https://stories-qa-wordpress-amp.pantheonsite.io/web-stories/%d8%aa-%e4%b8%b2-%d1%8f-%e0%b2%8e-%cf%89-%e3%81%98-%e1%84%8a-%c9%97-%e2%b4%95-%c9%90-%e0%bb%92/

Note: the encoded slug shows up properly in the address bar within Chrome and within the story editor link display





Verified with Kanji characters as well https://stories-qa-wordpress-amp.pantheonsite.io/web-stories/kanji-%e6%bc%a2%e5%ad%97-2/
