### PR TITLE
Move Selection + change z-index to display selection on top of other layers.

### LINKED ISSUE #2463: Selection handlers should take precedence over page actions
## Bug Description

_Follow-up issue for #2042_

See comment: https://github.com/google/web-stories-wp/issues/2042#issuecomment-643923137

When an element is rotated outside of the page such that the handles are on top of any of the page actions of the left and right nav buttons, the selection box handles should take precedence. Currently that is not the case:
image

Figma flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9488%3A1796)

## Expected Behaviour

The selection box handles should take precedence.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Changes z-index to display selection on top of other layers.

## To-do

- [x] Display selection under the Page carousel

## User-facing changes
The selection is now displayed on top of page actions.

## Testing Instructions
1. Add any element
2. Drag it to the bottom of the page.
3. Resize it so that part of the element goes on top of the Page actions but under the Page carousel
4. Verify the selection is still fully visible on top of the Page Actions and the element can be resized from the handles outside of the Page / on top of the Page Actions.

---

Fixes #2463

### CODE REVIEW

File: assets/src/edit-story/components/canvas/layout.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ import useCanvas from './useCanvas';
  */
 
 export const Z_INDEX = {
-  NAV: 1,
+  NAV: 0,
```
Comment (miina) [inline assets/src/edit-story/components/canvas/layout.js]: @dvoytenko Pinging you here in case you see in issues with changing this to 0.

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/layout.js]: Hmm. The reason it was set to `1` is to definitely show it on top of the selection. Also what happens here with the frame itself? Would the frame block actions too with the new z-index? Or is it just the selection?

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/layout.js]: I asked for confirmation on the issue itself, but let's first confirm the current behavior. We basically have two elements here: an element's frame and a moveable control box. Both could be blocking the page menu if we change the z-index. I think the control box (selection) is ok either way and up to the product decision, but a frame should never block the page menu because it's not even visible unless you hover on it.

Comment (miina) [reply assets/src/edit-story/components/canvas/layout.js]: Looks like the behavior was confirmed.

Hmm, so the frame should be not allowed to overflow but the selection yes. The z-index would still need a change then I suppose, and the frame needs hiding though somehow.

File: assets/src/edit-story/components/canvas/pagemenu/index.js [hunk 2]
```diff
@@ -52,7 +52,7 @@ const Wrapper = styled.div`
 `;
 
 const Box = styled.div`
-  background-color: ${({ theme }) => theme.colors.bg.v1};
+  background-color: transparent;
```
Comment (miina) [inline assets/src/edit-story/components/canvas/pagemenu/index.js:55]: This is for displaying the frame through the page actions but not being on top of it.

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/pagemenu/index.js:55]: Makes sense. Initially I was trying to prevent any notion that a selection box can be manipulated when it collides with the page menu. But now we change this requirement. So the styling has to change as well.

**Comment by dvoytenko** [comment]
This is a realistic example of what Percy reports as a delta for this pull request:

image

/cc @barklund @swissspidy

**Review by dvoytenko — APPROVED** [review]
