### PR TITLE
Unable to use scrollbar in dropdown, use popup

### LINKED ISSUE #973: Unable to use scrollbar in dropdown
## Bug Description
There is some weird styling and I am unable to use scrollbar in dropdown. 

Note: scroll wheel does work. 

## Expected Behaviour

TBC

## Steps to Reproduce

Use any dropdown. 

## Screenshots

https://www.youtube.com/watch?v=bAtAwzVRYE8

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ndev1991**
Fixes #973 

Unable to scroll dropdown, and some styling issue inside panel. Mainly refactoring by using popup.

### CODE REVIEW

File: assets/src/edit-story/components/form/dropDown/list.js [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+import { useKeyDownEffect } from '../../keyboard';
+
+const ListContainer = styled.div`
+  float: right;
+  display: flex;
+  flex-direction: column;
+  flex-wrap: wrap;
+  min-width: 160px;
+  max-height: 370px;
+  overflow-y: auto;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dropDown/list.js:40]: Quick nit. I don't want to block this review on my timing. But if we do overflow-y here, it'd also be nice to set [overscroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior).

Comment (ndev1991) [reply assets/src/edit-story/components/form/dropDown/list.js:40]: used `overscroll-behaviour: none auto`

File: assets/src/edit-story/components/form/dropDown/list.js [hunk 2]
```diff
@@ -0,0 +1,258 @@
...
+    background-color: ${({ theme }) => theme.colors.bg.v12};
+  }
+
+  &:focus {
+    background-color: ${({ theme }) => theme.colors.bg.v12};
+    outline: none;
+  }
+`;
+
+const availableKeysForSearch = [
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/form/dropDown/list.js]: Nit pic. Wouldn't be clearer to do something like, `const availableKeysForSearch = "abcdefghijklmnopqrstuvwxyz123456789".split()`

**Comment by spacedmonkey** [comment]
Should the scrolls in the dropdowns use the same scrollbars in https://github.com/google/web-stories-wp/pull/946 @pbakaus ?

**Comment by spacedmonkey** [comment]
Screenshot from 2020-04-06 12-58-25
Screenshot from 2020-04-06 12-58-09

The width of the dropdown seems wrong here. So one of dropdown has a rounded corner and that other does not.

**Comment by spacedmonkey** [comment]
Screenshot from 2020-04-06 13-06-03
Screenshot from 2020-04-06 13-05-40
Some weird things happen if the window is resized.

**Comment by spacedmonkey** [comment]
Related #991

**Comment by ndev1991** [comment]
@spacedmonkey Resize mode is actually broken. I think that supposed to be default behavior of popup. I think we need to have extra popup for dropdown itself.

File: assets/src/edit-story/components/form/dropDown/list.js (hunk 2 above)
Comment (ndev1991) [reply assets/src/edit-story/components/form/dropDown/list.js]: Good one! Thanks, fixed from the last commit.

**Comment by ndev1991** [comment]
> Should the scrolls in the dropdowns use the same scrollbars in #946 @pbakaus ?

Popup is outside of Editor and added custom scrollbar style to popup itself.

**Comment by spacedmonkey** [comment]
We are looking much better now. But still seeing some styling issues.
Screenshot from 2020-04-07 12-47-13
Alignment issues here ^
Screenshot from 2020-04-07 12-47-13
Multiple scrollbars ^

**Comment by spacedmonkey** [comment]
I could not manage to replicate the scrollbar. I think this must have been fixed elsewhere. 

But I am still seeing issues of width. 

Screenshot from 2020-04-08 16-31-53
Screenshot from 2020-04-08 16-32-22

**Comment by ndev1991** [comment]
> I could not manage to replicate the scrollbar. I think this must have been fixed elsewhere.
> 
> But I am still seeing issues of width.
> 
> Screenshot from 2020-04-08 16-31-53
> Screenshot from 2020-04-08 16-32-22

@spacedmonkey do you think we need to have fixed the width of dropdown? currently it has minimum width, but the actual width determined by the contents.

File: assets/src/edit-story/components/form/dropDown/index.js [hunk 3]
```diff
@@ -178,23 +88,11 @@ function DropDown({
   lightMode = false,
   placeholder,
 }) {
-  DropDown.wrapperRef = useRef(null);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dropDown/index.js:181]: Not directly related to this PR, but such cases need to be found and changed to `const x = useRef()`. This is potentially pretty harmful.

File: assets/src/edit-story/components/form/dropDown/list.js [hunk 4]
```diff
@@ -0,0 +1,222 @@
...
+  return (
+    <ListContainer ref={listContainerRef}>
+      <List
+        aria-multiselectable={false}
+        aria-required={false}
+        aria-activedescendant={value || ''}
+        aria-labelledby={ariaLabel}
+      >
+        {options.map(({ name, value: optValue }) => {
+          return (
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dropDown/list.js]: Nit: can be inlined.

File: assets/src/edit-story/components/popup/index.js [hunk 5]
```diff
@@ -29,9 +34,37 @@ const Container = styled.div.attrs(({ x, y }) => ({
 }))`
   position: fixed;
   z-index: 2147483646;
-  width: ${({ width }) => width}px;
+  width: ${({ width }) => (width === 'auto' ? width : `${width}px`)};
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: We shouldn't allow `auto` here without some sort of `max-width`.

File: assets/src/edit-story/components/popup/index.js [hunk 6]
```diff
@@ -29,9 +34,37 @@ const Container = styled.div.attrs(({ x, y }) => ({
...
   max-height: ${MAX_HEIGHT}px;
   overflow: auto;
+
+  /*
+   * Custom dark scrollbars for Chromium & Firefox.
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Don't want to bikeshed this here, but imho the dark scrollbars look a bit wrong to me here. I like all other customizations for them though.

File: assets/src/edit-story/components/form/dropDown/list.js [hunk 7]
```diff
@@ -0,0 +1,222 @@
...
+    }
+  }, [focusedValue, options, focusedIndex, arrayOfOptionsRefs]);
+
+  const handleItemClick = (option) => {
+    handleCurrentValue(option);
+  };
+
+  const setOptionRef = (element) => {
+    if (element !== null) {
+      arrayOfOptionsRefs.push(element);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dropDown/list.js]: This will be pushing the same element over and over into the array. At the very least we should dedupe this array. But best yet we should see if this can be done some other way. And the order of this array is likely not stable either. I'm also noticing that you have IDs available there and maybe that will be useful. But on a very basic level, you couldl always do `listRef.current.children[index]`.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/form/dropDown/list.js (hunk 4 above)
Comment (ndev1991) [reply assets/src/edit-story/components/form/dropDown/list.js]: Fixed!

File: assets/src/edit-story/components/popup/index.js (hunk 5 above)
Comment (ndev1991) [reply assets/src/edit-story/components/popup/index.js]: Removed `auto` from popup and used default scrollbar width instead.

File: assets/src/edit-story/components/popup/index.js (hunk 6 above)
Comment (ndev1991) [reply assets/src/edit-story/components/popup/index.js]: Created gray style scrollbar. I think at least we need to have same size and the scrollbar format. So instead of remove it used gray style scrollbar.

File: assets/src/edit-story/components/form/dropDown/list.js (hunk 7 above)
Comment (ndev1991) [reply assets/src/edit-story/components/form/dropDown/list.js]: Yes, 🤦‍♂ Actually bad practice. Updated using listRef on parent level of listitems.

File: assets/src/edit-story/components/popup/index.js (hunk 5 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/popup/index.js]: That's not a scrollbar width though, right? Shouldn't this (at least optimally) try to follow the anchor's width?

**Review by dvoytenko — APPROVED** [review]
Still some minor questions with width sizing. But I believe this is good to merge now and can be addressed in followup.
