### PR TITLE
Floating Menu: Fix "Saved Color" (gradient) as border color causes crash (Again)

### LINKED ISSUE #11019: Floating Menu: Apply "Saved Color" as border color causes crash
## Bug Description

Found by @LuckynaSan  during bug bash, confirmed by Brittany 

> Editor crashes when you add a masked border to an element & select a saved color on the floating menu bar.

Note, this isn't an issue if you apply color for a border in the panel because saved colors aren't available there for border colors. Furthermore, it seems like it's just gradients causing the crash. Makes sense. 

## Steps to Reproduce

1) Insert element 2) Apply border from floating menu bar 3) open color picker 4) Select saved color (green in this case) 5) Editor crashes with error message below
## Screenshots

Screen Shot 2022-03-22 at 10 42 00 AM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Re-adding #11025 which had changes that were overwritten in a rebase that are necessary to avoid crashing the editor. 

## Summary

See that these are the same changes as previously added: https://github.com/GoogleForCreators/web-stories-wp/pull/11025/files#diff-3e101509bd8aebce46f213f43dc1e13358fabc6f9cccef75d7d4cce88f8de35c

## User-facing changes

Adding border colors via floating menu no longer crashes editor

## Testing Instructions

Give elements borders and border colors and see that it doesn't crash.

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11019

### CODE REVIEW

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 1]
```diff
@@ -134,8 +134,11 @@ function BorderWidthAndColor() {
             value={border.color || BLACK}
             onChange={handleColorChange}
             hasInputs={false}
-            hasEyeDropper={false}
+            hasEyedropper={false}
             allowsOpacity={canHaveBorderOpacity}
+            allowsGradient={false}
+            pickerHasEyedropper={false} // override shared floating menu Color component TODO https://github.com/GoogleForCreators/web-stories-wp/issues/11024
+            allowsSavedColors={false}
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: same set of updates as found here: https://github.com/GoogleForCreators/web-stories-wp/pull/11025/files#diff-3e101509bd8aebce46f213f43dc1e13358fabc6f9cccef75d7d4cce88f8de35c

File: packages/story-editor/src/components/form/color/color.js [hunk 2]
```diff
@@ -56,7 +56,7 @@ const Container = styled.section`
 `;
 Container.propTypes = {
   isInDesignMenu: PropTypes.bool,
-  width: PropTypes.string,
+  width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/form/color/color.js]: this is just silencing a console warning pre release while i'm here.

Comment (swissspidy) [reply packages/story-editor/src/components/form/color/color.js]: Is this because we're now passing an empty string to `width`? Can't we pass `null` instead?

Edit: or is it because of `MIXED_VALUE`?

**Comment by swissspidy** [comment]
Can we add tests to prevent this in the future?

File: packages/story-editor/src/components/form/color/color.js (hunk 2 above)
Comment (merapi) [reply packages/story-editor/src/components/form/color/color.js]: Not sure why it was `string` before, but changing that to `width: PropTypes.number,` seems to work for all cases.

File: packages/story-editor/src/components/form/color/color.js [hunk 3]
```diff
@@ -141,7 +141,7 @@ const Color = forwardRef(function Color(
     <Container
       aria-label={containerLabel}
       isInDesignMenu={isInDesignMenu}
-      width={!ignoreSetWidth && width}
+      width={!ignoreSetWidth && width ? width : ''}
```
Comment (merapi) [inline packages/story-editor/src/components/form/color/color.js]: With `width: PropTypes.number,` this is no longer needed.

**Review by merapi — APPROVED** [review]
Fixes the crash ✅ 
Karma test won't hurt I guess.

Nit: The color picker should be smaller?

image

image

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: Also same as #11075 it seems?

File: packages/story-editor/src/components/form/color/color.js (hunk 3 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/color/color.js]: linter was complaining about it becoming a boolean, happy to return it back to how it was.

**Comment by BrittanyIRL** [comment]
> Nit: The color picker should be smaller?
> 
> image
> 
> image

I don't really see how the color picker size is impacted by this PR - would you make a new ticket for it and reference the intended size?

File: packages/story-editor/src/components/form/color/color.js (hunk 3 above)
Comment (swissspidy) [reply packages/story-editor/src/components/form/color/color.js]: Or just return null instead of an empty string?

Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/color/color.js]:
```
  ["Warning: Received `%s` for a non-boolean attribute `%s`.·
    If you want to write it to the DOM, pass a string instead: %s=\"%s\" or %s={value.toString()}.·
    If you used to conditionally omit it with %s={condition && value}, pass %s={condition ? value : undefined} instead.%s", "false", "width", "width", "false", "width", "width", "width", "
```

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: that one actually reenables the color picker, i noticed that my hotfix to avoid crashing was gone when i rebased that PR. Felipe identified an (unrelated) issue where the eyerdropper in the sidepanel outside of the color picker is out of sync with updating the canvas which took that PR back into in progress, so it's not going to make the release. Whereas this is just eliminating saved colors and eyedropper from floating menu color picker in the mean time.

File: packages/story-editor/src/components/form/color/color.js (hunk 3 above)
Comment (swissspidy) [reply packages/story-editor/src/components/form/color/color.js]: Is the width only needed for CSS or also in the DOM?
If the former then we might want to use transient props.

**Review by maxyinger — APPROVED** [review]

**Comment by merapi** [comment]
> I don't really see how the color picker size is impacted by this PR - would you make a new ticket for it and reference the intended size?

| Before this PR | After this PR |
|----------------|---------------|
| image | image |

image

You have just hidden those buttons? 🤔
