### PR TITLE
Dashboard: Incorporate the rest of the filters into FiltersProvider

### LINKED ISSUE #11668: Dashboard: Status filter + author filter not working well together
## Bug Description

If you have a story status filter set and then you filter by author, if that author does not have a anything in that status, then story status should reset to all or something. 

See video. 

## Steps to Reproduce

1. Open dashboard. 
2. Filter by pending. 
3. Filter by author ( author must not have pending story ). 
4. See status filter not highlighted. 

## Screenshots

https://user-images.githubusercontent.com/237508/173048393-24a5300f-5809-4fb0-bb48-ac71f7d8012b.mov

## Additional Context

- Plugin Version: 1.22.0
- WordPress Version: 6.0
- Operating System:
- Browser:

### LINKED ISSUE #11780: Dashboard: Stories resorted when switching from grid view to list view
## Bug Description

On the Dashboard, when switching from the stories 'grid view' to 'list view' the stories sort is always set to ascending, which is causing a re fetch of the stories in some cases.

## Expected Behaviour

The stories should not be 're fetched' or 're sorted' when changing between the Dashboard grid view and list view.

## Steps to Reproduce

1. Go to the Dashboard
2. Click the 'Switch to List View' toggle
3. Click the 'Switch to Grid View' toggle
- Notice no 're fetch' no 're sort'
4.  Click the 'Switch to List View' toggle
5. Sort the stories descending by any column by clicking the column name
6. Click the 'Switch to Grid View' toggle
- Notice no 're fetch' or 're sort'
7.  Click the 'Switch to List View' toggle
- Notice a 're fetch' and 're sort'.  See clip below.

## Screenshots

https://images.zenhubusercontent.com/235435637/da306c2a-e205-4a36-8575-1553823318a7/2022_06_22_14_18_51.mp4
## Additional Context
Found while working on #11767.
https://github.com/GoogleForCreators/web-stories-wp/issues/11767#issuecomment-1162380467

The issue is caused in `useStoryView.js` by the `toggleViewStyle` function.  For some reason we are intentionally setting the story sort to ascending.  The intent is not known and needs to be removed to eliminate re fetching and re sorting the stories.

- Plugin Version: 1.22.0-alpha.0
- WordPress Version: Version: 6.0
- Operating System: Windows 10
- Browser: Chrome 102.0.5005.115

### LINKED ISSUE #11789: Dashboard: Incorporate all filtering state into the FiltersProvider
## Feature Description
Currently only the taxonomy filters and the author filter utilize the FiltersProvider.  Any state that can update which stories are shown (ie Taxonomy filters, Author filter, Sort, Status Filter, Keyword search) should utilize the FiltersProvider.

Currently we are handling 'filtering' in multiple different places `FiltersProvider`, `mystories/index`, and `useStoryView`.  This makes it hard to debug issues on the dashboard and to update filtering logic on the dashboard.  Moving all filtering logic into one place will remove complexity in this area and should increase DX while working on the dashboard.

As part of this work, we should expect that https://github.com/GoogleForCreators/web-stories-wp/issues/11668 should be resolved as a test case to get this consolidated.

## Alternatives Considered

Let the filtering logic be in multiple places.  This would lead to ambiguity on how to add / update the logic surrounding dashboard filters and the complexity in this area will continue to rise.

## Additional Context

Filters Improvement

### PR DESCRIPTION
**Pull request by mwritter**
## Context

Move all filters/sorting logic into one place.

## Summary

Incorporates the 'status', 'keyword search', and 'sort' in the FiltersProvider.

## Relevant Technical Choices

Moving all the filters/sort into one place and using a hook to tap into them is more maintainable than prop drilling.

## To-do

The way we use 'tracking' when 'searching' may need to be updated now that the logic has been moved.  Possibly more refactoring to remove old/unnecessary logic.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to the Dashboard
2. Test all filters and sort on the Grid View and the List View
- Notice these should be working: Taxonomy filters, author filter, status filter, keyword search, and sort
3. Also test #11668 - this ticket deals with that issue as well

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?

Possibly - I do believe we'll need to update the search tracking

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11668
Fixes #11789 
Fixes #11780

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@mwritter There seems to be valid test failures here. Let's get those fixed.

**Comment by mwritter** [comment]
> @mwritter There seems to be valid test failures here. Let's get those fixed.

@spacedmonkey For sure, I was off for the 4th and 5th 🇺🇸 - Im looking into them 👍

**Comment by spacedmonkey** [comment]
Lints are now failing.

File: packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ describe('Publish panel in document tab', () => {
     await page.keyboard.type('auth');
 
     // wait for search results
-    await page.waitForTimeout(200);
+    await page.waitForTimeout(500);
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js]: This is being addressed in #11782

**Comment by mwritter** [comment]
> Not sure if this related to this PR. But I am seeing no options on search. But there are results.

@spacedmonkey - That search "dropdown" is populated with story titles, based on your screenshot none of those stories have titles so there are 'No options available' to select in that "dropdown".

File: packages/dashboard/src/app/views/exploreTemplates/filters/test/templateFiltersProvider.js [hunk 2]
```diff
@@ -0,0 +1,215 @@
...
+      result.current.actions.updateFilter('status', { filterId: 'New' });
+    });
+
+    statusFilter = result.current.state.filters.find(
+      ({ key }) => key === 'status'
+    );
+    expect(statusFilter.filterId).toBe('New');
+  });
+
+  it('should be able to update the sortObject if the acceptable keys are use', () => {
```
Comment (sblinde) [inline packages/dashboard/src/app/views/exploreTemplates/filters/test/templateFiltersProvider.js]: Nit: Probably missing a letter for `used` here

File: packages/dashboard/src/app/views/filters/test/reducer.js [hunk 3]
```diff
@@ -56,17 +57,49 @@ describe('reducer', () => {
...
         value: { filterId: 117 },
       },
     };
 
-    const state = reducer(initial_state, args);
-    const filter = state.filters.find((f) => f.key === 'officers');
+    let state = reducer(initial_state, args);
+    let filter = state.filters.find((f) => f.key === 'officers');
     expect(filter.filterId).toBeNull();
+
```
Comment (sblinde) [inline packages/dashboard/src/app/views/filters/test/reducer.js:72]: It might be helpful to have some more comments in these tests to indicate what you're trying to test / do in each case

Comment (sblinde) [reply packages/dashboard/src/app/views/filters/test/reducer.js:72]: Or, alternatively, separate the use cases of these tests instead of all in one

**Comment by swissspidy** [comment]
> On the QA instance, with this PR enabled, I'm not able to replicate the same that you're seeing.

Need to wait until the bot leaves a comment saying that the PR is available for testing.

Right now this doesn't happen when a draft PR is set to ready for review. It's only triggered when pushing some changes to a non-draft PR.

I just merged main into this branch, so in a few minutes the bot will leave a comment and only then will this PR begin to be available for testing on the QA site.

Hope that makes sense.

**Comment by sblinde** [comment]
> 

 hadn't realized that the bot didn't update its initial commenting in picking up on the latest changes, makes sense. Thanks for that!

**Review by sblinde — APPROVED** [review]
Initial look at the PR and the functionality in the QA environment looks good so far. I had some super small pieces of feedback but looks good to me.

**Comment by swissspidy** [comment]
> I hadn't realized that the bot didn't update its initial commenting in picking up on the latest changes, makes sense. Thanks for that!

Ah, my bad for not realizing that the bot did add comments earlier but then the PR was converted to a draft again, which means the ZIPs were never updated. That's indeed very confusing! I'll try to think of a good way to address that.
