### PR TITLE
KSES: also sanitize story data for page templates

### LINKED ISSUE #11647: Contributors Template creation is not working as expected
## Bug Description

As a contributor I am permitted to create templates, however when the template is created, there is no content within the newly created template

## Expected Behaviour

I am not sure if template creation by a contributor is considered acceptable.

## Screenshots

https://images.zenhubusercontent.com/235435637/0e886897-7ce5-49ed-86e4-86d86963cabb/screen_recording_2022_06_07_at_4_05_28_pm.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

It was reported that contributors sometimes were unable to save custom page templates.

Turns out this was because the story_data JSON was not slashed properly (or too often), causing the data to be lost during save.

## Summary

This PR updates the KSES class so that it also runs for the `web-story-page` post type, so that the story data in `post_content_filtered` is preserved as expected. (`\Google\Web_Stories\KSES::filter_story_data()` is relevant here)

## Relevant Technical Choices

Created a couple of helper methods to reduce complexity, avoiding PHPMD warnings.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. As a **Contributor** user, create a new story
2. Add some text and images to the page
3. Save page as a custom page template
4. Verify that the template is saved correctly and can be inserted to the story as expected

### Does this PR have a security-related impact?

Updates the KSES class to run also for another post type, but that's it.

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11647

### CODE REVIEW

File: includes/KSES.php [hunk 1]
```diff
@@ -74,7 +86,55 @@ public function register(): void {
...
+	 * Provides simple sanity check to ensure story data is valid JSON.
+	 *
+	 * @since 1.22.0
+	 *
+	 * @param string $story_data JSON-encoded story data.
+	 * @return string Sanitized & slashed story data.
+	 */
+	private function filter_story_data( string $story_data ): string {
+		$decoded = json_decode( (string) wp_unslash( $story_data ), true );
+		return null === $decoded ? '' : wp_slash( (string) wp_json_encode( $decoded ) );
```
Comment (spacedmonkey) [inline includes/KSES.php:137]: This feels like witchcraft atm. Can you provide a unit test with invalid data to proof this works as expected.

Comment (swissspidy) [reply includes/KSES.php:137]: I'll look into it. There should be test coverage for KSES already though.

Note that this is not new code. This was just moved around.

**Review by spacedmonkey — APPROVED** [review]

**Review by timarney — APPROVED** [review]
