### PR TITLE
Media Upload Queue

### LINKED ISSUE #6088: Media: Local previews when uploading unsupported file type
## Feature Description

When uploading videos and images, we try to display them on the canvas or on the library so the user can already interact with it while uploading.

When uploading unsupported file types, it is currently not possible to do that. There can even be errors (see #6310)

To solve this, we will do three things, in this order:

1. Display video placeholder
2. Try to generate a resource from the local file (`getResourceFromLocalFile`, using `createObjectURL`)
3. If that fails (i.e. the file type is unsupported), try poster generation using ffmpeg

**Important:** this is not just useful for video optimization, as (1) and (2) are relevant even when uploading MP4s.

###  Video Placeholder (new)

This is the fallback solution when uploading videos. The first thing we do. We display a gray rectangle with a disabled play button. A tooltip explains the user why it is grayed out.

**Example:**

Screenshot 2021-02-12 at 12 51 09

**Note:** Exact implementation TBD. Whether this should be an actual gray rectangle with an icon, or an actual video tag with some styling & missing `source` needs to be tested/discovered.

### Display video/poster using blobs (existing)

This is the current solution we have **today**. Try to load the video and a poster using `createObjectURL` and `getFirstFrameOfVideo`

**Note:** Exact implementation TBD. Whether this should be an actual gray rectangle with an icon, or an actual video tag with some styling & missing `source` needs to be tested/discovered.

### Display poster using `ffmpeg` (new)

**Handled in #6399**

<details>
<summary>Details</summary>

This is a fallback solution in case the above doesn't work.

Use `ffmpeg` to generate a poster image from the video that can be showed instead of the placeholder.

We show the poster image  with a disabled play button

Docs: https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video

**Example:**

Screenshot 2021-02-12 at 13 04 02

</details>

### Tooltip (new)

As the screenshot above shows, we display a tooltip when the user hovers over the video while the video is being progressed.

This tooltip is shown regardless of whether we display a placeholder or a poster.

This can also be implemented in a separate ticket.

## Additional Context

As a reminder, the flow is like this:

User drops video -> `useUploadMedia` -> `useUploader` (calls `useTranscode`) -> upload to WordPress

The logic for displaying local files in the library is handled in `useUploadMedia` (`assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js`). Seems like something there needs to be adjusted to make it work for video optimization.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6427: Media: TypeError in useAverageColor when uploading video
The following error is generated when uploading files that need to be transcoded. 
```
TypeError: Cannot read property 'complete' of null
    in InnerElement (at mediaElement.js:246)
    in div (created by mediaElement__InnerContainer)
    in mediaElement__InnerContainer (at mediaElement.js:245)
    in div (created by mediaElement__Container)
    in mediaElement__Container (at mediaElement.js:231)
    in MediaElement
    in MediaElement (at mediaGallery.js:49)
    in div (created by Gallery)
    in div (created by Gallery)
    in Gallery
    in Gallery (at mediaGallery.js:65)
    in div (at mediaGallery.js:64)
    in MediaGallery (at paginatedMediaGallery.js:141)
    in div (at paginatedMediaGallery.js:140)
    in div (created by styles__MediaGalleryInnerContainer)
    in styles__MediaGalleryInnerContainer (at paginatedMediaGallery.js:173)
    in div (created by styles__MediaGalleryContainer)
    in styles__MediaGalleryContainer (at paginatedMediaGallery.js:169)
    in PaginatedMediaGallery (at mediaPane.js:313)
    in div (created by styles__PaneInner)
    in styles__PaneInner (at mediaPane.js:266)
    in section (created by styles__StyledPane)
    in styles__StyledPane (at mediaPane.js:265)
    in MediaPane (at libraryPanes.js:32)
    in LibraryPanes (at libraryLayout.js:85)
    in div (created by libraryLayout__LibraryPaneContainer)
    in libraryLayout__LibraryPaneContainer (at libraryLayout.js:84)
    in section (created by libraryLayout__Layout)
    in libraryLayout__Layout (at libraryLayout.js:73)
    in LibraryLayout (at library.js:28)
    in div (created by dropTarget__Content)
    in dropTarget__Content (at dropTarget.js:112)
    in Unknown (at dropTarget.js:111)
    in div (created by dropTarget__DropTargetComponent)
    in dropTarget__DropTargetComponent (at dropTarget.js:96)
    in UploadDropTarget (at libraryUploadDropTarget.js:43)
    in LibraryUploadDropTarget (at library.js:27)
    in Unknown (at libraryProvider.js:108)
    in LibraryProvider (at library.js:26)
    in Library (at layout/index.js:86)
    in div (created by layout__Area)
    in layout__Area (at layout/index.js:85)
    in Unknown (at unitsProvider.js:56)
    in UnitsProvider (at canvasProvider.js:223)
    in Unknown (at canvasProvider.js:222)
    in CanvasProvider (at layout/index.js:84)
    in section (created by layout__Editor)
    in layout__Editor (at withOverlay.js:47)
    in Unknown (at withOverlay.js:46)
    in ForwardRef(WithOverlay) (at layout/index.js:83)
    in Unknown (at provider.js:91)
    in HighlightsProvider (at layout/index.js:82)
    in PrepublishChecklistProvider (at layout/index.js:81)
    in Unknown (at layoutProvider.js:47)
    in LayoutProvider (at layout/index.js:80)
    in Layout (at editorApp.js:80)
    in Unknown (at provider.js:232)
    in DropTargetsProvider (at editorApp.js:72)
    in Unknown (at transformProvider.js:82)
    in TransformProvider (at editorApp.js:71)
    in Unknown (at mediaProvider.js:40)
    in MediaProvider (at editorApp.js:69)
    in Unknown (at currentUserProvider.js:55)
    in CurrentUserProvider (at editorApp.js:68)
    in Unknown (at fontProvider.js:159)
    in FontProvider (at editorApp.js:67)
    in Unknown (at storyProvider.js:179)
    in StoryProvider (at editorApp.js:66)
    in Unknown (at metaBoxesProvider.js:69)
    in MetaBoxesProvider (at editorApp.js:65)
    in Unknown (at snackbarProvider.js:73)
    in SnackbarProvider (at editorApp.js:64)
    in Unknown (at historyProvider.js:83)
    in HistoryProvider (at editorApp.js:63)
    in Unknown (at media3pApiProvider.js:163)
    in Media3pApiProvider (at editorApp.js:62)
    in Unknown (at provider.js:43)
    in FileProvider (at editorApp.js:61)
    in Unknown (at apiProvider.js:350)
    in APIProvider (at editorApp.js:59)
    in Unknown (at configProvider.js:28)
    in ConfigProvider (at editorApp.js:58)
    in ErrorBoundary (at editorApp.js:57)
    in Ge (at editorApp.js:56)
    in ye (at editorApp.js:55)
    in App (at edit-story/index.js:55)
    in StrictMode (at edit-story/index.js:54)
    in FlagsProvider (at edit-story/index.js:53)
```

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Videos that need to be transcoded during upload cannot be previewed in the editor/library until they have been processed by FFmpeg. In that scenario, we currently don't display anything until transcoding is finished, which means the user has to wait a long time for feedback.

For improved UX around video optimization during upload, we want to display a placeholder image first and replace it with an actual preview as soon as it gets available—all while the upload is still progressing behind the scenes.

Unfortunately, the current media upload queue is not very stateful in that regard and does not allow for such updates in the middle of the process, nor does the consumer even know what state an individual file is currently in.

## Summary

This PR introduces a new hook to act as a queue for media uploads where we know the state (e.g. pending/transcoding/uploading/finished/cancelled) of each file being uploaded at all times.

Not only does this allow us to update media resources mid-progress, but we can now also do things like displaying tooltips for items still being processed (#6089).

**Regular image and video uploads should not be affected by this change**

The most significant change is when uploading video files that need to be transcoded, for example a MOV file from iPhone.

For such files, the process looks a bit like follows:

1. Drop video into editor
2. A placeholder gray square is displayed on the editor (because we don't know its dimensions yet)
3. Video is being transcoded
4. Two things now happen in parallel:  
    1. Try to replace placeholder with an actual preview of the image and update its dimensions once they become known
    2. Upload video and replace any placeholder or preview with the uploaded file

## Relevant Technical Choices

* **Media Provider:** new `prependMedia` action to add items to the beginning of the media library. This avoids having to replace the whole list of items with `setMedia`, which is error prone if using outdated items
* **Media Provider:** update `updateMediaElement` to allow overriding the resource's ID. This is necessary because local resources (i.e. still being uploaded) now have an ID already, but after upload they will have a WordPress attachment ID.
* **Resource Type:** a `resource` now has a new `isPlaceholder` property to identify whether it's a blank
* **Story Provider:** adds a new `deleteElementsByResourceId` action to delete elements by resource ID _across all pages_ (`deleteElementsById` only works on the current page) in case upload failed. This is needed because the user could have duplicated/copied elements/pages while upload was in progress.
* **useTranscodeVideo:**  moves the time & error tracking closer to the source
* **Canvas:** do not display video playback button for placeholders
* **useUploader:** separate file validation and actual uploads into two separate  `validateFileForUpload` and `uploadFile` functions
* **useUploader:** move the `useTranscodeVideo` usage to `useUploadMedia` because it's actually only used and needed by that. `useUploader` should not be concerned with transcoding.
* **useUploadMedia:** validate files for upload before doing anything, so the user has more instant feedback
* **useUploadMedia:** try to generate preview once at the beginning (as it works for most files) and again once transcoding has finished

## To-do

* More tests for the media upload queue
* Improve/clarify position and behavior for placeholder resources on canvas / in media library
* Testing & bug fixes as we go

## User-facing changes

**Uploading a regular image**

(no visible change)

https://user-images.githubusercontent.com/841956/109307413-e6c76780-7840-11eb-8b66-53f2c0498bfb.mov

**Uploading a regular video**

(no visible change)

https://user-images.githubusercontent.com/841956/109325776-9e1aa900-7856-11eb-8f25-ad37c8af2a95.mov

**Uploading a video requiring additional transcoding**

(see placeholder element before preview later on)

https://user-images.githubusercontent.com/841956/109307458-f941a100-7840-11eb-914d-c2585fa721cb.mov

**Uploading a video requiring additional transcoding but with poster**

(see poster image before preview later on)

https://user-images.githubusercontent.com/841956/109325859-b7235a00-7856-11eb-9237-7fa45ed28790.mov

### QA

- [ ] This is a non-user-facing change and requires no QA

**Prerequisites**

1. Download some test files here: 
[test files.zip](https://github.com/google/web-stories-wp/files/6050945/test.files.zip)

2. Turn on video optimization experiment and enable video optimization in settings

**ZIP file, dropped on media library**

1. Drop ZIP file onto media library
2. See snackbar message saying that the file type is not supported

**ZIP file, dropped on editor**

1. Drop ZIP file onto editor
2. See snackbar message saying that the file type is not supported

**PNG image, dropped on editor**

1. Drop PNG image onto editor
2. See an instant preview of the image on the canvas **and** in the media library
3. See a progress bar for the image in the media library while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

**PNG image, dropped on media library**

1. Drop PNG image onto editor
2. See an instant preview of the image in the media library
3. See a progress bar for the image in the media library  while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

**MP4 video, dropped on editor**

1. Drop MP4 video onto editor
2. See an instant preview of the video on the canvas **and** in the media library
3. Verify that you can play the video on the canvas while it's being uploaded
4. See a progress bar for the video in the media library while it's being uploaded
5. Verify that you get a warning trying to close the window while upload is in progress

**MP4 video, dropped on media library**

1. Drop MP4 video onto editor
2. See an instant preview of the video in the media library
3. See a gray, rectangular placeholder element on the canvas
3. See a progress bar for the video in the media library  while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

**MOV video (H.264), dropped on editor**

1. Drop MOV video onto editor
2. See an instant preview of the video in the media library
3. See a progress bar for the video in the media library while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

**MOV video (H.264), dropped on media library**

1. Drop MOV video onto editor
2. See an instant preview of the video in the media library
3. See a progress bar for the video in the media library  while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

**MOV video (HEVC), dropped on editor**

1. Drop MOV video onto editor
2. See a gray, rectangular placeholder element on the canvas **and** in the media library
3. Verify that you **cannot** play the video on the canvas (no play button)
3. See a progress bar for the video in the media library while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress
5. See how the placeholder gets replaced with an actual preview after some time, and that its dimensions and position on the canvas change.

**MOV video (HEVC), dropped on media library**

1. Drop MOV video onto editor
2. See a gray placeholder element in the media library
3. See a progress bar for the video in the media library while it's being uploaded
4. Verify that you get a warning trying to close the window while upload is in progress

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6088

Also partially addresses #6400 by using `URL.revokeObjectURL()` as needed

Also fixes #6427

### CODE REVIEW

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 1]
```diff
@@ -120,21 +129,48 @@ const getVideoResource = async (file) => {
   });
 };
 
+const createPlaceholderResource = (properties) => {
+  return createLocalResource({ ...properties, isPlaceholder: true });
+};
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:134]: What the point of having this as another function here?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 2]
```diff
@@ -120,21 +129,48 @@ const getVideoResource = async (file) => {
...
+
+const getPlaceholderResource = (file) => {
+  const type = getTypeFromMime(file.type);
+  const mimeType = type === 'image' ? 'image/png' : 'video/mp4';
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:139]: Why can't we use the real mimeType here?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 3]
```diff
@@ -120,21 +129,48 @@ const getVideoResource = async (file) => {
...
+
+  // The media library requires resources with valid mimeType and dimensions.
+  return createPlaceholderResource({
+    type: type || 'image',
+    mimeType: mimeType,
+    src: '',
+    width: PAGE_WIDTH,
+    height: PAGE_HEIGHT,
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:147]:
```suggestion
    height: PAGE_HEIGHT,
    alt: fileName,
    title: fileName,
```

Why not some default alt and titles as well.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 4]
```diff
@@ -101,17 +104,23 @@ const getImageResource = async (file) => {
...
-  const src = window.URL.createObjectURL(
-    new window.Blob([reader.result], { type: mimeType })
-  );
+
+  const src = createBlob(new Blob([reader.result], { type: mimeType }));
+
+  const videoEl = document.createElement('video');
+  const canPlayVideo = '' !== videoEl.canPlayType(mimeType);
+
   const frame = await getFirstFrameOfVideo(src);
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:115]: Why not wrap `getFirstFrameOfVideo` in a check if `canPlayVideo` is true?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 5]
```diff
@@ -101,17 +104,23 @@ const getImageResource = async (file) => {
...
+
   const reader = await createFileReader(file);
-  const src = window.URL.createObjectURL(
-    new window.Blob([reader.result], { type: mimeType })
-  );
+
+  const src = createBlob(new Blob([reader.result], { type: mimeType }));
+
+  const videoEl = document.createElement('video');
+  const canPlayVideo = '' !== videoEl.canPlayType(mimeType);
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: Very cool!

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue.js [hunk 6]
```diff
@@ -0,0 +1,356 @@
...
+        resource,
+        onUploadStart,
+        onUploadProgress,
+        onUploadError,
+        onUploadSuccess,
+      },
+    }
+  ) => {
+    const id = uuidv4();
+    const newItem = {
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue.js]: Not for now, but would we use this to have a progress bar? So a bit of state for percentage complete?

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue.js [hunk 7]
```diff
@@ -0,0 +1,356 @@
...
+            } finally {
+              trackTiming();
+            }
+
+            return;
+          }
+
+          // TODO: Only transcode & optimize video if needed (criteria TBD).
+          // Probably need to use FFmpeg first to get more information (dimensions, fps, etc.)
+          startTranscoding({ id });
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue.js]: Should we track the how long it takes to transcode a file. Were we not tracking this before?

File: assets/src/edit-story/utils/blobs.js [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+/**
+ * Create a blob URL from a file.
+ *
+ * @param {File} file File object.
+ * @return {string} Blob URL.
+ */
+export function createBlob(file) {
+  const url = window.URL.createObjectURL(file);
+
+  blobCache[url] = file;
```
Comment (spacedmonkey) [inline assets/src/edit-story/utils/blobs.js:33]: So this is a cache for blob used before? We are just using a variable as a cache. Is there any risk this? Wouldn't some state make sense here?

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue.js [hunk 9]
```diff
@@ -0,0 +1,356 @@
+/*
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue.js]: This file is a little long. An chance of breaking into multiple files and it's own directory?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:134]: This is kept in the same style as `createLocalResource` which is also a separate dedicated reason.

Describes quite explicitly what it does, which is what I like about it.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 5 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: Can we pass the codex of the file here? What if the file returns `maybe`?

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue.js (hunk 7 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useMediaUploadQueue.js]: This is done in `useTranscodeVideo` directly now, as mentioned in the PR description.

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue.js (hunk 6 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useMediaUploadQueue.js]: Yeah maybe. Progress could be tracked here, but that would result in lots and lots of state updates every time progress is updated (which could easily be dozens of times). Using callbacks might be more performant.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 4 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:115]: Funnily enough, `getFirstFrameOfVideo()` can still work, even though `canPlayVideo` is `false`.

So for MOV files with MP4 codec, Chrome will happily let us create a poster image, but the video itself cannot be played.

Hence no wrapping.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:139]: `file.type` can be empty, or something like `video/quicktime` which the browser won't support.

The exact mime type used here is irrelevant as it is merely a placeholder without a `src`, not a real media item.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 10]
```diff
@@ -120,21 +129,48 @@ const getVideoResource = async (file) => {
...
+
+const getPlaceholderResource = (file) => {
+  const type = getTypeFromMime(file.type);
+  const mimeType = type === 'image' ? 'image/png' : 'video/mp4';
+
+  // The media library requires resources with valid mimeType and dimensions.
+  return createPlaceholderResource({
+    type: type || 'image',
+    mimeType: mimeType,
+    src: '',
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:145]: Would the source here be an blob of transparent 1x1 pixel?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js [hunk 11]
```diff
@@ -120,21 +129,48 @@ const getVideoResource = async (file) => {
...
+    width: PAGE_WIDTH,
+    height: PAGE_HEIGHT,
+  });
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:150]: Should there be a poster attribuate if type is video? Maybe the source of the poster be an blob of transparent 1x1 pixel?

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 5 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: `canPlayType` only supports 1 parameter, the mime type.

Possible return values are `''` (empty string), `maybe` and `probably`.

An empty string means the file definitely can't be played on the current device. But the other two values are no guarantees either way. But that's OK, as those values are not being relied upon.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 10 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:145]: Placeholders were implemented in a way that they explicitly do not have a source.

Resources without a source (placeholders) won't have any video playback button, no poster generation, etc. They're just "blank".

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 11 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:150]: Placeholder resources don't need sources and shouldn't require a poster either. They're just gray rectangles essentially.

File: assets/src/edit-story/utils/blobs.js (hunk 8 above)
Comment (swissspidy) [reply assets/src/edit-story/utils/blobs.js:33]: No risk really. This variable is a simple key value store that doesn't need something fancy.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:147]: I've kept it pretty minimal because these values will get overridden during upload anyway.

**Comment by spacedmonkey** [comment]
I am seeing this bug more while testing this - https://github.com/google/web-stories-wp/issues/6427

**Comment by spacedmonkey** [comment]
I think we need to change these lines 

https://github.com/google/web-stories-wp/blob/b851f3ca8c24d50ec327b4c5121d338d64ef7cbc/assets/src/edit-story/components/library/panes/media/common/innerElement.js#L107-L112

With this PR, we are adding a state where we know that poster is going to be null. This just makes the averageColor issue worse.

File: assets/src/edit-story/utils/blobs.js (hunk 8 above)
Comment (spacedmonkey) [reply assets/src/edit-story/utils/blobs.js:33]: Is there chance the browser clear the variable, maybe when the browser does it's garbage collection to clear memory? We are talking about a browser window with the editor maybe open for 30+ minutes.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 5 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: > canPlayType only supports 1 parameter, the mime type.

You can pass codex in that one param. [See](https://www.w3schools.com/tags/av_met_canplaytype.asp).

```
var vid = document.createElement('video');
isSupp = vid.canPlayType(vidType+';codecs="'+codType+'"');
```

Doing a little research, it is not easy to read codex from a file...

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:115]: Which is why I asked the question regarding the codec - https://github.com/google/web-stories-wp/pull/6541#discussion_r584801907

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 3 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:147]: For the most part I agree, but an alt is useful for accessibility. It stop an image tag for updating it's alt value.

File: assets/src/edit-story/utils/blobs.js (hunk 8 above)
Comment (swissspidy) [reply assets/src/edit-story/utils/blobs.js:33]: As long as a variable is still being used a browser would not simply discard it.

Comment (swissspidy) [reply assets/src/edit-story/utils/blobs.js:33]: Also note that every blob is removed again from this cache once upload is finished. So they're not in this array forever.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 5 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: I'm a bit skeptic about this not being documented on MDN...

And yeah we don't know the codec here.

`canPlayType` should be good enough here.

**Comment by swissspidy** [comment]
> I am seeing this bug more while testing this - #6427



> I think we need to change these lines
> 
> https://github.com/google/web-stories-wp/blob/b851f3ca8c24d50ec327b4c5121d338d64ef7cbc/assets/src/edit-story/components/library/panes/media/common/innerElement.js#L107-L112
> 
> With this PR, we are adding a state where we know that poster is going to be null. This just makes the averageColor issue worse.

While I am not seeing the bug at the moment, I've made `useAverageColor` more robust now in 75f2d752738ec8890f8da4d0d907810ac98f8669, fixing this once and for all.

File: assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js (hunk 5 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/utils/getResourceFromLocalFile.js:113]: The MDN docs are weird here. Look [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) it does document codecs, but not on this [page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType).

> Given a string specifying a MIME media type (potentially with the codecs parameter included)

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue/reducer.js [hunk 12]
```diff
@@ -0,0 +1,270 @@
+/*
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue/reducer.js:1]: You could even break each action into it's own files like the story provider. https://github.com/google/web-stories-wp/tree/main/assets/src/edit-story/app/story/useStoryReducer/reducers

File: assets/src/edit-story/app/uploader/useUploader.js [hunk 13]
```diff
@@ -108,40 +97,37 @@ function useUploader() {
         throw createError('SizeError', file.name, message);
       }
 
-      const additionalData = {
-        post: storyId,
-        media_source: 'editor',
-        ..._additionalData,
-      };
+      // The file is too large for the site anyway, abort.
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/uploader/useUploader.js]: This chuck is repeated from the lines above. Let's remove it.

File: assets/src/edit-story/app/uploader/useUploader.js [hunk 14]
```diff
@@ -108,40 +97,37 @@ function useUploader() {
...
+      if (!isFileSizeWithinLimits(file)) {
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/uploader/useUploader.js]: I think we need to add a check for `&& !canTranscodeFile) {` here. I was unable to upload a 164MB mp4.

**Comment by spacedmonkey** [comment]
Screenshot 2021-03-02 at 10 54 05

I was unable to upload a 164MB MP4. This should be have been transcoded.

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
I found a regreation and some repeated code. I also have some other feedback.

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 14 above)
Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Not so sure about that.

In your screenshot, your upload limit is 100MB and the file is 164MB.

Yes, the file could be easily transcoded, _but_ there is no guarantee that transcoding will make the file < 100 MB (we simply don't know). So it makes sense to just abort because of the upload limit.

I'd think this is also what happens on `main`

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 13 above)
Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Whoops, looks like I accidentally duplicated this 🤦

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue/reducer.js (hunk 12 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useMediaUploadQueue/reducer.js:1]: IMO here it's still manageable to have all in one file. Can be reconsidered once the list of reducers is growing.

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 14 above)
Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Confirmed that this is the same behavior as on `main`:

https://github.com/google/web-stories-wp/blob/7ea172b9292455e1e86ee2b0ac71a23e5cddfb49/assets/src/edit-story/app/uploader/useUploader.js#L97-L141

I would not want to change this in this PR.

Comment (spacedmonkey) [reply assets/src/edit-story/app/uploader/useUploader.js]: As we have seen, transcoding brings the file size down by a lot. Can we take the file that is too large, transcode it and then try and upload it? If a 162mb becomes at 16mb file, then there is no problem. This would need a new error, of "We tried to transcode your file but it was too big to upload after it was transcoded". This discussion may need to be moved out another ticket.

Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Yeah I can create a new ticket for that. Would be good to have UX feedback on it.

My worry there is just that we'll spend multiple minutes trying to transcode & upload file only to tell the user that it won't work.

But with the right messaging it might work.

Comment (spacedmonkey) [reply assets/src/edit-story/app/uploader/useUploader.js]: > My worry there is just that we'll spend multiple minutes trying to transcode & upload file only to tell the user that it won't work.

Also my worry as well, it might be a waste. But we do cap about at 2GB, so if you try and upload star wars, that limitation should kick in. Marking this as resolved for now, let's chat on the new ticket.

**Review by spacedmonkey — APPROVED** [review]
LGTM. Excited on doors this opens in the future.

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 14 above)
Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Ticket created: #6580
