### PR TITLE
Classic Editor: Prevent TinyMCE button from being loaded on frontend

### LINKED ISSUE #7127: TinyMCE Button JS loaded on frontend
## Bug Description

TinyMCE button scripts are inadvertently loaded on the frontend, causing a ton off JS to be loaded on the frontend.

They are also loaded on the story editor itself!

## Expected Behaviour

TinyMCE button scripts should only load for the classic editor.

## Steps to Reproduce

1. Activate plugin

## Screenshots

Screenshot 2021-04-07 at 15 40 50

Screenshot 2021-04-07 at 17 43 53

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Follow up from https://github.com/google/web-stories-wp/pull/6906. Tinymce's init method was hooked on `admin_enqueue_scripts` not `init`. This PR returns this. 

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7127

### CODE REVIEW

**Comment by swissspidy** [comment]
As mentioned in https://github.com/google/web-stories-wp/issues/7127#issuecomment-815263537, it's still loaded on the story editor, which we also don't want.

**Comment by spacedmonkey** [comment]
> As mentioned in #7127 (comment), it's still loaded on the story editor, which we also don't want. 

It didn't in my testing. There is a check in the class for if it is the block editor 

https://github.com/google/web-stories-wp/blob/623e68bd0f3fc558b8c676e571fdc676fe99d694/includes/TinyMCE.php#L57-L60

**Comment by swissspidy** [comment]
> > As mentioned in #7127 (comment), it's still loaded on the story editor, which we also don't want.
> 
> It didn't in my testing. There is a check in the class for if it is the block editor
> 
> https://github.com/google/web-stories-wp/blob/623e68bd0f3fc558b8c676e571fdc676fe99d694/includes/TinyMCE.php#L57-L60

It does in my testing. The story editor is not a block editor, we filter that accordingly.

When I run this PR, I see this in the page source:

Screenshot 2021-04-09 at 11 51 20

**Comment by spacedmonkey** [comment]
I don't know how I missed that. This would have been an issue before my issue. 

I reviewed code and added a little refactor to this PR. There was LOTS of repeated logic for working with `get_current_screen`. Created a new trait helper methods to get current screen and workout if you are in block or story editor.

File: includes/Traits/Screen.php [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+	/**
+	 * Is this the editor screen.
+	 *
+	 * @since 1.6.0
+	 *
+	 * @param WP_Screen|false $screen Screen value, defaults to null.
+	 *
+	 * @return bool
+	 */
+	protected function is_edit_screen( $screen = null ) {
```
Comment (swissspidy) [inline includes/Traits/Screen.php:65]: The param is just for testing, or...? Why not just use `$this->get_current_screen()` directly?

File: includes/Traits/Screen.php [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+		if ( is_null( $screen ) ) {
```
Comment (swissspidy) [inline includes/Traits/Screen.php]: Nit: `null === $screen` checks should be preferred.

File: includes/Traits/Screen.php [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+	 * Check if current screen is block editor.
+	 *
+	 * @since 1.6.0
+	 *
+	 * @param WP_Screen|false $screen Screen value, defaults to null.
+	 *
+	 * @return bool
+	 */
+	protected function is_block_editor( $screen = null ) {
+		if ( is_null( $screen ) ) {
```
Comment (swissspidy) [inline includes/Traits/Screen.php]: Nit: `null === $screen` checks should be preferred.

**Review by swissspidy — APPROVED** [review]
Just a couple of nits, otherwise looks good.

Like the cleanup you did 👍

File: includes/Traits/Screen.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/Traits/Screen.php:65]: There are a couple of places in the code that `$this->get_current_screen()` is called before `is_edit_screen`. It seemed a little wasteful to call `this->get_current_screen()`. I can remove it you don't like it. 

Example 
```
public function admin_body_class( $class ) {
		$screen = $this->get_current_screen();
		if ( ! $screen ) {
			return $class;
		}

		if ( ! $this->is_edit_screen( $screen ) ) {
			return $class;
		}
```

File: includes/Traits/Screen.php (hunk 2 above)
Comment (spacedmonkey) [inline includes/Traits/Screen.php]:
```suggestion
		if ( null === $screen ) {
```

File: includes/Traits/Screen.php (hunk 3 above)
Comment (spacedmonkey) [inline includes/Traits/Screen.php]:
```suggestion
		if ( null === $screen ) {
```

**Comment by spacedmonkey** [comment]
> Like the cleanup you did 👍

Wow was there a lot of repeated logic. Really happy with the clean up.

File: includes/Traits/Screen.php (hunk 1 above)
Comment (swissspidy) [reply includes/Traits/Screen.php:65]: > There are a couple of places in the code that `$this->get_current_screen()` is called before `is_edit_screen`. It seemed a little wasteful to call `this->get_current_screen()`. I can remove it you don't like it.
> 
> Example
> 
> ```php
> public function admin_body_class( $class ) {
> 		$screen = $this->get_current_screen();
> 		if ( ! $screen ) {
> 			return $class;
> 		}
> 
> 		if ( ! $this->is_edit_screen( $screen ) ) {
> 			return $class;
> 		}
> ```

Well this would be equivalent to

```php
public function admin_body_class( $class ) {
	if ( ! $this->is_edit_screen() ) {
		return $class;
	}
}
```

So yeah I think we can remove it **_and_** simplify the code in these places.
