### PR TITLE
Frontend: HTML markers not always replaced 

### LINKED ISSUE #5589: Frontend: HTML markers not always replaced
## Bug Description

The HTML markup generated by the story editor contains some placeholders (`<meta name="web-stories-replace-head-start"/>` and `<meta name="web-stories-replace-head-end"/>`) in the `<head>` that are then replaced on the frontend with dynamic content as generated by WordPress:

https://github.com/google/web-stories-wp/blob/2388bf101d8c88be2dc952d2a237cb146dda33f9/includes/Story_Renderer/HTML.php#L204-L216

This uses `str_replace` instead of regexes for performance reasons.

Now, it appears that the placeholders sometimes have a space at the end before the closing `/>`. Not sure yet why (just React doing its thing I guess), but it looks like this:

* `<meta name="web-stories-replace-head-start "/>`
* `<meta name="web-stories-replace-head-end" />`

This obviously won't be replaced by those `str_replace` calls as it doesn't expect a spae.

## Expected Behaviour

`<meta name="web-stories-replace-head-start "/>` and `<meta name="web-stories-replace-head-end" />` should also get replaced.

## Steps to Reproduce

Not clear yet.

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.5
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Extend `replace_html_head()` to detect these markers with trailing space as well.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Sometimes a space gets added in weird places in meta tags. 

## Relevant Technical Choices

Do a simple preg_replace to reset meta tags back to what they should be. 

## Testing Instructions

---

Fixes #5589

### CODE REVIEW

File: includes/Story_Renderer/HTML.php [hunk 1]
```diff
@@ -205,6 +205,10 @@ protected function replace_html_head( $content ) {
 		$start_tag = '<meta name="web-stories-replace-head-start"/>';
 		$end_tag   = '<meta name="web-stories-replace-head-end"/>';
 
+		// Replace malformed meta tags with correct tags.
+		$content = (string) preg_replace( '/<meta name="web-stories-replace-head-start\s?"\s?\/>/i', $start_tag, $content );
+		$content = (string) preg_replace( '/<meta name="web-stories-replace-head-end\s?"\s?\/>/i', $end_tag, $content );
```
Comment (swissspidy) [inline includes/Story_Renderer/HTML.php:210]: Don't need to check for whitespace within the attribute value.

```suggestion
		$content = (string) preg_replace( '/<meta name="web-stories-replace-head-start"\s?\/>/i', $start_tag, $content );
		$content = (string) preg_replace( '/<meta name="web-stories-replace-head-end"\s?\/>/i', $end_tag, $content );
```

File: tests/phpunit/tests/Story_Renderer/HTML.php [hunk 2]
```diff
@@ -90,6 +90,33 @@ public function test_replace_html_head() {
 		$this->assertSame( 1, did_action( 'web_stories_story_head' ) );
 	}
 
+	/**
+	 * @covers ::replace_html_head
+	 * @covers ::get_html_head_markup
+	 */
+	public function test_replace_html_head_invalid() {
+		$start_tag = '<meta name="web-stories-replace-head-start " />';
```
Comment (swissspidy) [inline tests/phpunit/tests/Story_Renderer/HTML.php:98]: Don't need to cater for whitespace within the attribute value
```suggestion
		$start_tag = '<meta name="web-stories-replace-head-start" />';
```

**Review by swissspidy — APPROVED** [review]
Approved with one nit 👍

File: includes/Story_Renderer/HTML.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/Story_Renderer/HTML.php:210]: > Not sure yet why (just React doing its thing I guess), but it looks like this:

`<meta name="web-stories-replace-head-start "/>`
`<meta name="web-stories-replace-head-end" />`

From [here](https://github.com/google/web-stories-wp/issues/5589#issue-758695705)

This isn't a mistake, this is from the description of the ticket.

File: tests/phpunit/tests/Story_Renderer/HTML.php (hunk 2 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/Story_Renderer/HTML.php:98]: Again, not a mistake, valid test case.

File: includes/Story_Renderer/HTML.php (hunk 1 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:210]: My apologies, I think I simply made a typo in the ticket.

Since it doesn't really hurt we can also just leave this as-is.

Comment (spacedmonkey) [reply includes/Story_Renderer/HTML.php:210]: I agree, leave it in, more error handling never heart anyway
