### PR TITLE
Dashboard: Checkbox cursor updated to pointer

### LINKED ISSUE #6688: Design System: checkbox hover cursor should be pointer
## Bug Description

On hover of a checkbox cursor remains 'default'. Since it can be clicked it should be a pointer. 
Discovered on dashboard/settings however stems from design system. Should be fixed at the root of the issue. 

## Expected Behaviour

On hover of checkbox, cursor should be a pointer. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Checkbox cursor was default when hovering over a checkbox. 

## Summary

Updates checkbox in design system to allow cursor to be pointer on hover. Updates telemetry banner and dashboard settings to have cursor pointer on checkbox labels as well. 

## User-facing changes

Cursor should be pointer on hover of checkbox and checkbox labels (the areas you can click to change the value of the checkbox) 
pointer

## Testing Instructions

Hover over a checkbox and see a pointer cursor.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6688

### CODE REVIEW

**Review by samwhale — APPROVED** [review]

**Review by maxyinger — APPROVED** [review]

File: assets/src/design-system/components/checkbox/index.js [hunk 1]
```diff
@@ -37,7 +37,6 @@ const Border = styled.div(
     width: ${CONTAINER_WIDTH}px;
     border-radius: ${theme.borders.radius.small};
     border: ${BORDER_WIDTH}px solid ${theme.colors.border.defaultNormal};
-    pointer-events: none;
```
Comment (embarks) [inline assets/src/design-system/components/checkbox/index.js:40]: I've seen `pointer-events: none` as a fix to make inner elements clickable when they are wrappedby elements that don't typically have onChange or onClick events. I'm sure you tested this in storybook so it probably won't be an issue. Didn't look like the DS checkbox is used yet though in dashboard/edit-story so I just wanted to flag it. :)

**Review by embarks — APPROVED** [review]

File: assets/src/design-system/components/checkbox/index.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/design-system/components/checkbox/index.js:40]: i was wary of removing this, but it's working just fine and all tests are passing! The checkbox is used on the telemetry banner as well as the dashboard settings page. I tested chrome, firefox, safari and everything is as it should be. I'll keep an eye out for anything being amiss here, but for now i think all is well! Thanks for flagging it!
