### PR TITLE
Changed exit to be on pointerdown, not click

### LINKED ISSUE #1186: Drag-out of component (color picker, text editing) closes component
## Bug Description

When you click to select/navigate inside one of these components, then if you accidentally leave the component with your cursor before your release the mouse button, you'll exit the component without wanting to:

* Drag-to-select text in text edit component
* Drag-to-modify hue/saturation/alpha in color picker component

## Expected Behaviour

If you drag-to-select text in text edit or drag-to-modify color in color picker and accidentally leave the component before mouse up, component should remain in its original state and not close/exit.

## Steps to Reproduce

**For text edit:**
1. Add text field
1. Click to enter edit mode for text field
1. Start drag inside text field to mark some text
1. Keep dragging until mouse complete leaves text field
1. Let go of mouse and see element leave edit mode.

**For color picker:**
1. Add text field
1. Open color picker for text color
1. Start drag inside saturation selector to change color
1. Keep dragging until mouse complete leaves color picker component
1. Let go of mouse and see color picker close.

## Screenshots

Text field exiting edit mode:
drag-exits-editmode

Color picker closing:
drag-exits-colorpicker

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
This changes how the mouse-based exit detection works for both edit mode and color picker.

If you _mouse-down_ inside the component, but subsequently _mouse-up_ outside the component, the component should not treat this as an exit signal.

This is done by changed the listener to be a `pointerdown` listener rather than a `click` listener in both instances (and nothing else actually).

This might have unexpected consequences, so heavy testing is required.

Fixes #1186.

#### Text edit

| Before | After |
|-|-|
| drag-exits-editmode | drag-editmode-fixed |

#### Color picker

| Before | After |
|-|-|
| drag-exits-colorpicker |  drag-colorpicker-fixed |

### CODE REVIEW

**Comment by miina** [comment]
@barklund Tested and didn't notice any issues so far.
Should this be applied also to the calendar? And dropdown selection?

**Comment by wassgha** [comment]
@barklund @miina do you think it's possible to move this to the `Popup` component for the calendar and color picker (since we have #1060 )?

File: assets/src/edit-story/utils/useFocusOut.js [hunk 1]
```diff
@@ -19,7 +19,7 @@
  */
 import { useLayoutEffect } from 'react';
 
-function useFocusOut(ref, callback, deps) {
+function useFocusOut(ref, callback, deps, clickEvent = 'click') {
```
Comment (dvoytenko) [inline assets/src/edit-story/utils/useFocusOut.js]: Can we confirm that a focus is lost on pointerdown? If so, we should just make it default.

**Review by dvoytenko — APPROVED** [review]
Approved, but with the question on what should be a default value.

File: assets/src/edit-story/utils/useFocusOut.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/utils/useFocusOut.js]: Yeah, that was my question. It seems like a good default - I can't think of a case where you mouse-down outside the component and keep it open. Maybe if you were to drag something in - but we don't have a such a component as far as I can see actually.  I'm okay with making `pointerdown` default.

Comment (barklund) [reply assets/src/edit-story/utils/useFocusOut.js]: When we implement #1041, we'll need to do something clever here, but other than that, I can't see a need to ever click outside.

Comment (dvoytenko) [reply assets/src/edit-story/utils/useFocusOut.js]: Found [this simple example](https://codepen.io/mudassir0909/pen/eIHqB) and did some manual checking. From what I can tell, "focusout" is fired right after the pointer down and before anything else. So I think this will be true to the order of the events if we just do pointer down.

File: assets/src/edit-story/utils/useFocusOut.js [hunk 2]
```diff
@@ -43,11 +43,11 @@ function useFocusOut(ref, callback, deps) {
     };
 
     node.addEventListener('focusout', onFocusOut);
-    node.ownerDocument.addEventListener('click', onDocumentClick);
+    node.ownerDocument.addEventListener('pointerdown', onDocumentClick);
```
Comment (barklund) [inline assets/src/edit-story/utils/useFocusOut.js:46]: `useFocusOut` is currently used for:

* Text edit
* Dropdown
* Color picker
* Date picker

They all still work as intended with this change.

**Review by merapi — APPROVED** [review]
LG, should we also change `dashboard/utils/useFocusOut.js`?

**Comment by barklund** [comment]
> LG, should we also change `dashboard/utils/useFocusOut.js`?

Let's just ping @carlos-kelly for now and leave it up to him.

**Comment by carloskelly13** [comment]
@barklund @merapi This seems like a reasonable change we can make since if they do mouse-up outside then the event won't fire.
