### PR TITLE
Publisher Logos: Fix race condition on multi-upload

### LINKED ISSUE #9499: Settings: publisher logo upload button uploads one less image
## Bug Description

When uploading more than one images for publisher logo under dashboard settings, the first image doesn't get saved.

## Expected Behaviour

It should save all the uploaded images.

## Steps to Reproduce

1. Go to dashboard settings 
2. Click on "Upload Logo" button and choose more than 1 images.
3. Refresh the page and see

## Screenshots

https://imgur.com/TcG0bp1

## Additional Context

- Plugin Version: 1.14.0-alpha.0
- WordPress Version: 5.8.1
- Operating System: Mac
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

There's a race condition when uploading multiple publisher logos, causing some items to be dropped from the logos list.

## Summary

This PRs updates the publisher logo multi-upload so that multiple logos are added to the list together. This fixes the race condition.

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Upload multiple publisher logos
2. Refresh the page
3. Verify all newly uploaded logos are still there

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9499

### CODE REVIEW

File: includes/REST_API/Publisher_Logos_Controller.php [hunk 1]
```diff
@@ -218,35 +220,59 @@ public function get_items( $request ) {
...
-		if ( in_array( $post->ID, $publisher_logos, true ) ) {
-			return new WP_Error(
-				'rest_publisher_logo_exists',
-				__( 'Publisher logo already exists', 'web-stories' ),
-				[ 'status' => 400 ]
-			);
+		// Could be a single attachment ID or an array of attachment IDs.
+		$posts = (array) $request['id'];
+
+		foreach ( $posts as $post_id ) {
```
Comment (BrookeGraham) [inline includes/REST_API/Publisher_Logos_Controller.php:234]: 🎉

**Review by BrookeGraham — APPROVED** [review]
Looks good to me.

File: includes/REST_API/Publisher_Logos_Controller.php [hunk 2]
```diff
@@ -218,35 +220,59 @@ public function get_items( $request ) {
...
-
-		if ( in_array( $post->ID, $publisher_logos, true ) ) {
-			return new WP_Error(
-				'rest_publisher_logo_exists',
-				__( 'Publisher logo already exists', 'web-stories' ),
-				[ 'status' => 400 ]
-			);
+		// Could be a single attachment ID or an array of attachment IDs.
+		$posts = (array) $request['id'];
+
```
Comment (spacedmonkey) [inline includes/REST_API/Publisher_Logos_Controller.php:225]: Add a check to see if `$posts` is an empty array.

**Review by spacedmonkey — APPROVED** [review]
