### PR TITLE
Media: Add support for VideoPress

### LINKED ISSUE #6909: Jetpack VideoPress Compatibility
## Bug Description

A [support user reported that](https://wordpress.org/support/topic/wp-video-files-not-appearing-in-image-browser/) .MP4 videos are not able to be selected or inserted properly in the Editor:

1. Uploaded videos from the Media Library display in the media tab with the All Types filter applied, but when added to a Story, they do not display a play button and cannot be played as videos. 
2. When the Video filter is applied, no videos from the Media Library display.
3. Videos that are uploaded within the Story Editor using the Upload button have the same issues as videos that have already been uploaded via the Media Library.

This user's website is hosted on WordPress.com hosting, which auto-enables Jetpack's VideoPress feature. I was able to replicate the issue in the WordPress.com hosting environment. I was **not** able to replicate this issue on any other hosting environments, even with VideoPress turned on via Jetpack, so this conflict is specifically occurring with VideoPress on WordPress.com hosting. 

## Expected Behaviour

1. Uploaded videos (via Media Library or the Upload button) auto-play when added to a Story
2. When the user clicks away and then re-selects the video and hovers over it, a play button should appear
3. When the user presses the play button, the video should play

## Steps to Reproduce

1. On a WordPress.com-hosted website (requires Business Plan or above to install plugins), install the Web Stories plugin
2. Upload a .MP4 video via the Media Library or Upload button in the Editor
3. In the media tab of the Editor filtered by All Types, click the video screenshot to insert it into the Story. Note that it does not auto-play and clicking and hovering on the image later does not produce a play button.
4. Filter the media tab by Videos and note that the video does not appear.

## Screenshots

Video: https://jumpshare.com/v/KBRRwiK8rcKJHs9qqLIR

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version: 5.7
- Operating System: MacOS Big Sur 11.2.3
- Browser: Replicated in both Chrome 89 and Safari 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary
Add support for videopress by tweak rest api / admin ajax requests, so that type returns video/mp4 and not video/videopress. 

## Relevant Technical Choices

Adding a source to the media picker query, so is is possible to filter requests by this. 

## User-facing changes

https://user-images.githubusercontent.com/237508/118165084-cc526280-b41b-11eb-8bbf-e4eb0e861c48.mov

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6909

### CODE REVIEW

File: includes/Integrations/Jetpack.php [hunk 1]
```diff
@@ -28,11 +28,23 @@
...
 class Jetpack extends Service_Base {
+
+	/**
+	 * VideoPress Mime type.
+	 *
+	 * @since 1.8.0
+	 *
+	 * @var string
+	 */
+	const MIME_TYPE = 'video/videopress';
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]: Let's call this `VIDEOPRESS_MIME_TYPE`

File: includes/Integrations/Jetpack.php [hunk 2]
```diff
@@ -68,6 +83,76 @@ public function add_to_jetpack_sitemap( $post_types ) {
...
+	 * Add VideoPress to allowed mime types. If the site does not support videopress, this allow will be filtered out.
+	 *
+	 * @since 1.8.0
+	 *
+	 * @param array $mime_types Associative array of allowed mime types per media type (image, audio, video).
+	 *
+	 * @return array
+	 */
+	public function add_videopress( array $mime_types ) {
+		$mime_types['video'][] = self::MIME_TYPE;
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]: Is there any harm in not adding a `Jetpack_Plan::supports( 'videopress' )` check?

Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]: What would be the benefit?

Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]: My issue with using a class from another plugin, is we have to check it exists first. Also this class is removed and changed, it break things for us...

Comment (swissspidy) [reply includes/Integrations/Jetpack.php]: Yeah it would need safety guards of course. (Alternatively could be contributed to Jetpack instead)

I am asking because a) you had that in your example code snippet on the ticket and b) there could be issues if support is added but the module isn't actually active on the site. And I want to avoid such issues if there are any :-)

For some reason Jetpack checks the availability in the Gutenberg integration as well:

https://github.com/Automattic/jetpack/blob/86e408280b255d78f69b3584d1ab2e14b49d9d26/projects/plugins/jetpack/modules/videopress/class.videopress-gutenberg.php#L61-L136

Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]: Why don't we merge this as is now. I will create a PR on jetpack's side. Once that is merged, I will remove this line. Is that fair?

File: includes/Integrations/Jetpack.php [hunk 3]
```diff
@@ -68,6 +83,76 @@ public function add_to_jetpack_sitemap( $post_types ) {
...
+			return $response;
+		}
+
+		// Get data from post, so we filter out requests from other locations.
+		$post_data = $_POST; // phpcs:ignore WordPress.Security.NonceVerification.Missing
+		if ( ! isset( $post_data['action'] ) || 'query-attachments' !== $post_data['action'] ) {
+			return $response;
+		}
+
+		if ( ! isset( $post_data['query'] ) && ! isset( $post_data['query']['source'] ) || 'web_stories_editor' !== $post_data['query']['source'] ) {
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]: `isset()` can be simplified like this:

```php
! isset( $post_data['query']['source'] )
```

Comment (swissspidy) [reply includes/Integrations/Jetpack.php]:
```suggestion
		if ( ! isset( $post_data['query']['source'] ) || 'web_stories_editor' !== $post_data['query']['source'] ) {
```

File: tests/phpunit/tests/Integrations/Jetpack.php [hunk 4]
```diff
@@ -59,7 +59,73 @@ public function test_register_is_wpcom() {
...
+
+		unset( $_POST ); // phpcs:ignore WordPress.Security.NonceVerification.Missing
+	}
+
+	/**
+	 * @return \Google\Web_Stories\Integrations\Jetpack
+	 */
+	protected function get_jetpack_object() {
+		return new \Google\Web_Stories\Integrations\Jetpack();
+	}
```
Comment (swissspidy) [inline tests/phpunit/tests/Integrations/Jetpack.php]: What's the benefit of this?

If we really care to save some bytes, I'd probably just do `use \Google\Web_Stories\Integrations\Jetpack as Jetpack_Integration` and then everywhere `$jetpack = new Jetpack_Integration()`.

File: includes/Integrations/Jetpack.php (hunk 3 above)
Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]:
```suggestion
		if ( ! isset( $post_data['query'], $post_data['query']['source'] ) || 'web_stories_editor' !== $post_data['query']['source'] ) {
```

Or maybe even.

File: tests/phpunit/tests/Integrations/Jetpack.php (hunk 4 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/Integrations/Jetpack.php]: I just personally find it easier to read. I reviewed the tests again and thought this was nice improvement. I have taken your feedback.

File: includes/Integrations/Jetpack.php (hunk 3 above)
Comment (swissspidy) [reply includes/Integrations/Jetpack.php]: No, that's not needed. `isset( $post_data['query']['source'] )` handles both cases without errors or notices.

File: includes/Integrations/Jetpack.php (hunk 2 above)
Comment (swissspidy) [reply includes/Integrations/Jetpack.php]: Alright, let's leave as-is and then see how it works before proceeding further.

**Comment by swissspidy** [comment]
Re-running e2e tests now as there are failing ones. If they still fail, please double check whether these scenarios still work or if there's a bug introduced by this.

**Review by swissspidy — APPROVED** [review]
There are some test failures but otherwise LGTM

**Comment by swissspidy** [comment]
@spacedmonkey Before I forget: can we make sure VideoPress videos are marked as `isOptimized` in the API responses too?

**Comment by spacedmonkey** [comment]
> @spacedmonkey Before I forget: can we make sure VideoPress videos are marked as isOptimized in the API responses too?

@swissspidy Good idea. Added in https://github.com/google/web-stories-wp/pull/7520/commits/8be3d3160fe33ab5a9865eee42112f91b6679553

As for the E2E I don't understand why the media e2e are failing. It doesn't make sense, it works locally.

**Comment by swissspidy** [comment]
We just agreed on backporting this to 1.7.2, let‘s update the `@since` annotations accordingly.

As for the e2e tests, I suppose the flakiness is increasing everywhere 😕

**Comment by swissspidy** [comment]
Hmm there's still something confusing with the videos in the editor media library.

Here's the WP media library

Screenshot 2021-05-17 at 12 39 05 

In the editor media library, the videos aren't necessarily marked/recognizable as such.

Screenshot 2021-05-17 at 12 39 42

There's no duration and no playback on hover. When I insert the second Lego video/image on the canvas, only then I'll see that it's actually a video.

On the other hand, the Bunny video is displayed correctly in the media library.

**Comment by spacedmonkey** [comment]
The video preview is working. 

https://user-images.githubusercontent.com/237508/118477470-9dcbd480-b706-11eb-88ba-e256d099b6cd.mov

Maybe it is slow to load as it coming from another domain. 

As for the duration being missing, this is missing in the api. The expected field needs to be `media_details.length_formatted`. There is a field we maybe able to use. 

Screenshot 2021-05-17 at 11 53 11
 
However, I don't understand what that format duration is in, millisecond?

**Comment by swissspidy** [comment]
Ah, that explains it! I guess I was a bit impatient with the preview loading.

Yeah `duration` seems to be in milliseconds. If we could use that for `length_formatted`, that would be great.

----

It also seems like VideoPress generates video posters, but hides them on `wp-admin/upload.php`. Hence we see the poster _and_ the video in the editor. See this screenshot & code:

Screenshot 2021-05-17 at 14 42 25

https://github.com/Automattic/jetpack/blob/e754e80326402bce81f3e8aee8e6a58940dd0b9f/projects/plugins/jetpack/modules/videopress/editor-media-view.php#L113-L141

Perhaps we could do the same in the REST API here?

https://github.com/google/web-stories-wp/blob/1436581ffd3faf8799465916e088d9f69810fe9d/includes/Media/Media.php#L319-L336

Thoughts?

**Comment by spacedmonkey** [comment]
> Yeah duration seems to be in milliseconds. If we could use that for length_formatted, that would be great.

I was already working on this. I have a fix in https://github.com/google/web-stories-wp/pull/7520/commits/84782b8e48e46d3d8c09122755e8c5b214a0b356

Here is it working. 

Screenshot 2021-05-17 at 13 58 46

Sadly the admin ajax does not have this data so I can't easily backfill this data. I don't think it is needed. 

Screenshot 2021-05-17 at 13 57 02

As for hiding the videopress's generated poster image, I am not sure that is the expected behavior to hide these in our editor. Is the expected behaviour for videopress to make these posters. I am not sure we should mess with that.

File: includes/Integrations/Jetpack.php [hunk 5]
```diff
@@ -68,6 +83,114 @@ public function add_to_jetpack_sitemap( $post_types ) {
...
+	/**
+	 * Format milliseconds into seconds.
+	 *
+	 * @since 1.7.2
+	 *
+	 * @param int $milliseconds Milliseconds
+	 *
+	 * @return string
+	 */
+	protected function format_milliseconds( $milliseconds ) {
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php:226]: Does WP perhaps offer a function for this?

Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php:226]: I did look for one, I didn't think anything that outputted something useful. The closest that we came to is [human_time_diff](https://github.com/WordPress/wordpress-develop/blob/2382765afa36e10bf3c74420024ad4e85763a47c/src/wp-includes/formatting.php#L3726). If there is something that I am missing, let me know.

File: includes/Integrations/Jetpack.php [hunk 6]
```diff
@@ -68,6 +83,114 @@ public function add_to_jetpack_sitemap( $post_types ) {
...
+
+		if ( $seconds >= 1 ) {
+			$minutes = floor( $seconds / 60 );
+			$seconds = $seconds % 60;
+		} else {
+			$seconds = 0;
+			$minutes = 0;
+		}
+		$format = '%d:%02u';
+		$time   = sprintf( $format, $minutes, $seconds );
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]: Do we need to care about hours?

File: includes/Integrations/Jetpack.php (hunk 5 above)
Comment (swissspidy) [reply includes/Integrations/Jetpack.php:226]: Just felt like something WP would have a function for, but seems like there indeed isn't a super nice one.

In core, the `length_formatted` formatted string is coming from `getid3_lib::PlaytimeString()`, a static method which accepts seconds and returns `H:M:S` as a string.

**Comment by spacedmonkey** [comment]
https://user-images.githubusercontent.com/237508/118501090-49cde980-b720-11eb-9d65-823724637f7f.mov

I noticed a weird behaviour. After a video is upload and while it processing with videopress, the video is not usable.

File: includes/Integrations/Jetpack.php (hunk 6 above)
Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]: Is there a case where someone would upload a video that was more than 60 minutes here? Would be a problem that is shows as `61:00`

**Comment by swissspidy** [comment]
> Sadly the admin ajax does not have this data so I can't easily backfill this data. I don't think it is needed.
> 
> Screenshot 2021-05-17 at 13 57 02

Quick question, it seems like `length` isn't available either on a regular WP site (no VideoPress) in admin-ajax. Is that correct? That might explain #5030...

Length is needed to calculate media length in story output, so it's kinda important to have it.

> As for hiding the videopress's generated poster image, I am not sure that is the expected behavior to hide these in our editor. Is the expected behaviour for videopress to make these posters. I am not sure we should mess with that.

Yeah so VideoPress generates the poster images during upload, just like we do.
But it hides the poster images from the media library, just like we do.
So showing the VideoPress poster image in the editor is quite confusing.

**Comment by swissspidy** [comment]
>  Screen.Recording.2021-05-17.at.14.52.45.mov 
> I noticed a weird behaviour. After a video is upload and while it processing with videopress, the video is not usable.

Weird indeed. Is there anything in the REST API response that we can use to determine whether it's still processing or not? Would be good to hide this "blank" video in the editor.

**Comment by spacedmonkey** [comment]
> Weird indeed. Is there anything in the REST API response that we can use to determine whether it's still processing or not? Would be good to hide this "blank" video in the editor.

Added a workaround in https://github.com/google/web-stories-wp/pull/7520/commits/dc2f464767693d95034b65724cd90c800dca0cdf

Here is a video of how it works now. 

https://user-images.githubusercontent.com/237508/118513223-67ed1700-b72b-11eb-8569-d89e402094a1.mov

It is not perfect, to be sure, but once the poster image is generated and updated, it kicks in nicely. 

This issues only comes up while the video is processing. So it is a little edge case. It fixes itself after the video is processed / poster is generated.

File: includes/Integrations/Jetpack.php (hunk 6 above)
Comment (swissspidy) [reply includes/Integrations/Jetpack.php]: Not a big deal, but someone could certainly upload such a long video.

And `length_formatted` usually contains hours I think.

But I don't expect this to happen frequently.

So should be OK to leave this as-is.

**Comment by swissspidy** [comment]
Neat!

Then I think the only two things left are hiding the VideoPress poster image & getting the length/duration in admin-ajax.

Would these both be easily achievable?

**Comment by spacedmonkey** [comment]
> Would these both be easily achievable?

I got length in admin ajax in https://github.com/google/web-stories-wp/pull/7520/commits/aca013b8da8eaeafa36edafbe62e98c05b54a856. 

As for hiding poster image generated by videopress, it was not possible. I could maybe add to new poster when generated but not existing poster images, of video uploaded before this change. I also am not sure about hiding the poster image here. Poster images are expected and can be viewed in the media library. It is a bit of a over reach to hide these poster images here. 

I found one more bug in my testing. 

Screenshot 2021-05-17 at 18 47 47

In the media picker here, you can see the message overlayed in the media element. I can't work this one at, as the url here is correct when I open in a browser.

**Comment by spacedmonkey** [comment]
Fix the issue with video tag in media picker. https://github.com/google/web-stories-wp/pull/7520/commits/0bf5e64c65097ae6111e4251feb97315a782d4cb

It is a valid error, as the video tag did not have the cross origin attribute on it.

**Comment by swissspidy** [comment]
> As for hiding poster image generated by VideoPress, it was not possible. I could maybe add to new poster when generated but not existing poster images, of video uploaded before this change. I also am not sure about hiding the poster image here. Poster images are expected and can be viewed in the media library. It is a bit of a over reach to hide these poster images here.

Jetpack hides the poster image in the media library. See:

Screenshot 2021-05-17 at 21 57 44

I just pushed a change to do the same in the editor for consistent user experience:

1f4af816d9caec6bce2d8b7bdf01351307819b49

| Before        | After       |
| ------------- |-------------|
| Screenshot 2021-05-17 at 21 56 06        | Screenshot 2021-05-17 at 21 56 40       |

File: includes/Admin/Cross_Origin_Isolation.php [hunk 7]
```diff
@@ -135,6 +135,10 @@ protected function replace_in_dom( $html ) {
 		];
 
 		$processed = [];
+
+		// Workaround for hardcoded underscore references to video shortcode.
+		$html = str_replace( 'class="wp-video-shortcode', 'crossorigin="anonymous" class="wp-video-shortcode', $html );
```
Comment (swissspidy) [inline includes/Admin/Cross_Origin_Isolation.php]: Let's make sure we address this thoroughly in #7560 👍

**Comment by swissspidy** [comment]
@googlebot I consent

**Review by swissspidy — APPROVED** [review]

**Comment by spacedmonkey** [comment]
Screenshot 2021-05-18 at 10 55 09

I don't know what screen you are looking, here is example I just took. As you as see, it is video / poster all the way along. Nothing hidden. If there are examples where there is no poster, is likely either I deleting them as part of testing or wasn't generate yet.

File: includes/REST_API/Stories_Media_Controller.php [hunk 8]
```diff
@@ -197,6 +198,34 @@ protected function prepare_items_query( $prepared_args = [], $request = null ) {
...
+		$response = parent::prepare_item_for_response( $post, $request );
+
+		/**
+		 * Filters an attachment returned from the REST API.
+		 *
+		 * Allows modification of the attachment right before it is returned.
+		 *
+		 * Note the filter is run after rest_prepare_attachment is run. This filter is designed to only target web stories rest api requests.
+		 *
+		 * @since 1.8.0
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Media_Controller.php]:
```suggestion
		 * @since 1.7.2
```

**Comment by spacedmonkey** [comment]
@swissspidy As noted above, poster images are not hidden in the media library. But I don't see why they can't be our in editor. I added a very simple workaround that add the correct poster generation term to videopress generate posters. So it should work now. This is a improvement on meta query that was in use, as this should be avoided at all costs. Meta queries were removed in https://github.com/google/web-stories-wp/pull/5635/ for serious performance issues. 

One other interesting thing to note, videopress generated poster images, are at the mid point. 

Screenshot 2021-05-18 at 11 47 12

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+		$post_ids = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
+			$wpdb->prepare(
+				"SELECT post_id FROM $wpdb->postmeta WHERE meta_key = %s",
+				Jetpack::VIDEOPRESS_POSTER_META_KEY
+			)
+		);
+
+		if ( is_array( $post_ids ) && ! empty( $post_ids ) ) {
+			foreach ( $post_ids as $post_id ) {
+				wp_set_object_terms( (int) $post_id, 'poster-generation', Media::STORY_MEDIA_TAXONOMY );
```
Comment (spacedmonkey) [inline includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: Not sure we need to exactly match how we save data, like adding other post meta, setting featured image, post parent etc.

**Comment by swissspidy** [comment]
> @swissspidy Please can we avoid doing a meta query like this at **ALL** costs. If we most to do this, let's run a migration to add the correct term to these attachments and add the term when this post meta is created.

> As noted above, poster images are not hidden in the media library. But I don't see why they can't be our in editor. I added a very simple workaround that add the correct poster generation term to videopress generate posters. So it should work now. This is a improvement on meta query that was in use, as this should be avoided at all costs. Meta queries were removed in #5635 for serious performance issues.

I was just following Jetpack's lead here since their (unfortunately) using post meta and meta queries for that:

https://github.com/Automattic/jetpack/blob/b06bcc8134759f13b28ec4611a18b2c14d33723f/projects/plugins/jetpack/modules/videopress/editor-media-view.php#L83-L141

This way we could easily contribute the code to Jetpack.

I first thought about doing the meta query only when VideoPress is enabled. It hadn't occurred to me to just write a migration for adding terms to them. Thanks for going ahead and updating the code. 

Feels like something Jetpack should do out of the box.

> Screenshot 2021-05-18 at 10 55 09
> 
> I don't know what screen you are looking, here is example I just took. As you as see, it is video / poster all the way along. Nothing hidden. If there are examples where there is no poster, is likely either I deleting them as part of testing or wasn't generate yet.

As said before, I was looking at the standard WP media library at [`/wp-admin/upload.php`](https://cmsdevrel.wpcomstaging.com/wp-admin/upload.php), not the WP.com-customized media library. There, Jetpack is hiding the VP poster images—just like we hide ours. So they're not missing, but actually hidden.

File: includes/Integrations/Jetpack.php [hunk 10]
```diff
@@ -68,6 +95,153 @@ public function add_to_jetpack_sitemap( $post_types ) {
...
+		} else {
+			$seconds = 0;
+			$minutes = 0;
+		}
+
+		return sprintf( '%d:%02u', $minutes, $seconds );
+	}
+
+	/**
+	 * Hook into add term.
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]:
```suggestion
	 * Hook into added_post_meta.
```

Maybe? A bit confusing otherwise.

**Comment by spacedmonkey** [comment]
> As said before, I was looking at the standard WP media library at /wp-admin/upload.php, not the WP.com-customized media library. There, Jetpack is hiding the VP poster images—just like we hide ours. So they're not missing, but actually hidden.

Right, that is where we are getting confusion here. I was looking at the WP.com media library not the core one. As this is what is linked to in the sidebar and should is what wp.com expects you should do, we should ignore the core media library and look at wp.com one.

**Comment by spacedmonkey** [comment]
As for contribuing this term query instead of meta query. I agree, this is horrible and should removed asap, meta queries are performance nightmare and should avoided at all costs.

**Comment by swissspidy** [comment]
> > As said before, I was looking at the standard WP media library at /wp-admin/upload.php, not the WP.com-customized media library. There, Jetpack is hiding the VP poster images—just like we hide ours. So they're not missing, but actually hidden.
> 
> Right, that is where we are getting confusion here. I was looking at the WP.com media library not the core one. As this is what is linked to in the sidebar and should is what wp.com expects you should do, we should ignore the core media library and look at wp.com one.

Jetpack/VideoPress users on regular WordPress sites won't have this WP.com media library, so we can't ignore this.

**Comment by spacedmonkey** [comment]
> As said before, I was looking at the standard WP media library at /wp-admin/upload.php, not the WP.com-customized media library. There, Jetpack is hiding the VP poster images—just like we hide ours. So they're not missing, but actually hidden.

Worth noting, you did not mention that anyway. This is all that was said. 

> Jetpack hides the poster image in the media library. See:

No way in that line did you mention you had to go to a special link to see the documented page.

**Comment by swissspidy** [comment]
> > As said before, I was looking at the standard WP media library at /wp-admin/upload.php, not the WP.com-customized media library. There, Jetpack is hiding the VP poster images—just like we hide ours. So they're not missing, but actually hidden.
> 
> Worth noting, you did not mention that anyway. This is all that was said.

I was referring to my comment from yesterday where I mentioned that page: https://github.com/google/web-stories-wp/pull/7520#issuecomment-842295706

> > Jetpack hides the poster image in the media library. See:
> 
> No way in that line did you mention you had to go to a special link to see the documented page.

Apologies, I thought it was clear from the screenshot that it's the standard WP library, and that not all users don't have this WP.com media library

File: includes/Integrations/Jetpack.php [hunk 11]
```diff
@@ -49,6 +72,10 @@ public function register() {
 		}
 
 		add_filter( 'jetpack_is_amp_request', [ $this, 'force_amp_request' ] );
+		add_filter( 'web_stories_allowed_mime_types', [ $this, 'add_videopress' ] );
+		add_filter( 'web_stories_rest_prepare_attachment', [ $this, 'filter_api_response' ], 10, 2 );
+		add_filter( 'wp_prepare_attachment_for_js', [ $this, 'filter_admin_ajax_response' ], 10, 2 );
+		add_filter( 'added_post_meta', [ $this, 'add_term' ], 10, 3 );
```
Comment (swissspidy) [inline includes/Integrations/Jetpack.php]:
```suggestion
		add_action( 'added_post_meta', [ $this, 'add_term' ], 10, 3 );
```

This should fix the lint errors below

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+	 * @since 1.7.2
+	 *
+	 * @global \wpdb $wpdb WordPress database abstraction object.
+	 *
+	 * @return void
+	 */
+	public function migrate() {
+		global $wpdb;
+
+		wp_insert_term( 'poster-generation', Media::STORY_MEDIA_TAXONOMY );
```
Comment (swissspidy) [inline includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: That shouldn't be needed, as this was done by the `Add_Poster_Generation_Media_Source` migration way back.

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php (hunk 9 above)
Comment (swissspidy) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: Not sure what you mean here?

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php [hunk 13]
```diff
@@ -0,0 +1,67 @@
...
+
+use Google\Web_Stories\Integrations\Jetpack;
+use Google\Web_Stories\Media\Media;
+
+/**
+ * Class Add_VideoPress_Poster_Generation_Media_Source
+ *
+ * @package Google\Web_Stories\Migrations
+ */
+class Add_VideoPress_Poster_Generation_Media_Source extends Migrate_Base {
```
Comment (swissspidy) [inline includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: We can probably copy most of the `Add_Poster_Generation_Media_Source` tests for this one

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php (hunk 9 above)
Comment (spacedmonkey) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: Our poster attachments has parent id set and feature image set on the video. I believe videopress does this has this as well.

File: includes/Integrations/Jetpack.php (hunk 11 above)
Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php]: Good catch! Fixed.

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php (hunk 12 above)
Comment (spacedmonkey) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: Removed.

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php (hunk 13 above)
Comment (spacedmonkey) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: I don't like copying and pasting tests. I have refactored to use an abstract class.

Comment (swissspidy) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: This new class needs test coverage though

File: includes/Admin/Cross_Origin_Isolation.php (hunk 7 above)
Comment (spacedmonkey) [reply includes/Admin/Cross_Origin_Isolation.php]: @swissspidy Should we make https://github.com/google/web-stories-wp/pull/7605 part of 1.7.2 as well?

File: includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php (hunk 13 above)
Comment (swissspidy) [reply includes/Migrations/Add_VideoPress_Poster_Generation_Media_Source.php]: So basically a `Add_VideoPress_Poster_Generation_Media_Source` test file is what I meant here.

**Comment by swissspidy** [comment]
There's now a tiny merge conflict due to #7603.

This and https://github.com/google/web-stories-wp/pull/7520#discussion_r634810154 should be the only things left.

**Comment by spacedmonkey** [comment]
> There's now a tiny merge conflict due to #7603.

Is this going to make this hard to cherry pick this into a 1.7.2 release?

**Comment by swissspidy** [comment]
> > There's now a tiny merge conflict due to #7603.
> 
> Is this going to make this hard to cherry pick this into a 1.7.2 release?

I think it should be possible to easily resolve this when manually cherry-picking changes into that branch.

**Review by swissspidy — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
