### PR TITLE
Prevent click event propagation from resize handle

### LINKED ISSUE #6122: Resizing the Layer Panel is not working
## Bug Description
Resizing the layer panel is not working, it seems to collapse the panel instead.

## Expected Behaviour
Resizing the layer panel should work

## Steps to Reproduce
1. Add some elements
2. Open the layer panel
3. Try to resize it
4. See the layer panel collapsing

## Screenshots
Feb-01-2021 12-04-26

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Context
Click event propagated from the resize handle in a resizeable panel will trigger `onClick` in the panel header which results in collapsing the panel, as in case of the Layer Panel for example.

This PR will prevent click propagation from the resize handle since this should only handle dragging and double clicks.

## Relevant Technical Choices
An alternative could be rewriting the panel header so that it would not be a button and instead, the panel header would consist of wrapper, resize handle (if resizeable), and the clickable header part. Just stopping the propagation is a simpler solution, however, and seems to fill the purpose in this case.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add some elements
2. Try resizing the layer panel
3. Verify it's working as expected

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6122

### CODE REVIEW

File: assets/src/edit-story/karma/fixture/containers/designPanel/layers.js [hunk 1]
```diff
@@ -39,4 +39,8 @@ export class Layers extends AbstractPanel {
   get layers() {
     return getAllByTestId(this.layersList, 'layer-option');
   }
+
+  get resizeHandle() {
+    return getByLabelText(this.node.ownerDocument, /Set panel height/i);
```
Comment (barklund) [inline assets/src/edit-story/karma/fixture/containers/designPanel/layers.js]: Wouldn't all resizable panels have a handle? We don't have a lot, but this could fail. Maybe we could just go up a parent or two to find it?

**Review by barklund — APPROVED** [review]
Works for me - and excellent regression test coverage.

File: assets/src/edit-story/karma/fixture/containers/designPanel/layers.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/karma/fixture/containers/designPanel/layers.js]: Hm, I removed the `ownerDocument` part and left just `this.node`- it looks just from this specific panel and should work as expected like this.
