### PR TITLE
Story progress bar not aligned with top of content

### LINKED ISSUE #5322: Story progress bar not aligned with top of content
## Bug Description

On tall devices (e.g. iPhone X) in the Discover carousel, WP stories show a gap between the story progress bar and the top of the 9:16 content.

Impact: The progress bar gap and partially overlapping volume icon look bad. It's particularly jarring when swiping between stories that don't have this visual artifact (generated by other tools).

## Expected Behavior

There are at least two ways to fix this issue:
1. Long-term, add aspect ratio flexibility: https://github.com/ampproject/amphtml/issues/31032
2. Short-term, add a media query that top-aligns the 9:16 content area if the size of the gap is not too large.
  - One definition of "not too large" is "progress bar + icons overlap with 9:16 content area"

## Steps to Reproduce

View WP stories in Discover carousel on a tall device.

## Screenshots

Image from iOS (1)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Add media queries that cuts the top gap when it is too large. Or specific for the ratio between (435 / 874) and (490 / 874)

## Relevant Technical Choices

Use media queries to control the styling for thee class page-fullbleed-area.

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

- Go to the story page on Chrome.
- Under device, choose `responsive`, check the style for the ratio between  (435 / 874) and (490 / 874).
- Make sure the `progress bar + icons overlap with 9:16 content area` will not happen.

---

Fixes #5322

### CODE REVIEW

**Comment by zidianlyu** [comment]
After the fix:

For the ratio that accept top gap (< 435 / 874): 
Screen Shot 2020-11-19 at 11 26 27 PM


For the ratio that remove top gap (435 / 874 < ratio < 490 / 874):
Screen Shot 2020-11-19 at 11 25 31 PM

**Comment by zidianlyu** [comment]
Here is a sample screenshot after the `id` tag injection approach: 

Screen Shot 2020-11-23 at 8 55 51 AM

File: assets/src/edit-story/output/page.js [hunk 1]
```diff
@@ -78,7 +78,11 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
         <StoryAnimation.AMPAnimations />
 
         {backgroundElement && (
-          <amp-story-grid-layer template="vertical" aspect-ratio={ASPECT_RATIO}>
+          <amp-story-grid-layer
+            id="amp-story-grid-layer-bg"
```
Comment (swissspidy) [inline assets/src/edit-story/output/page.js]: `id` attributes should be unique in a given HTML document. This element will exists dozens of times though, so it should really use `class`.

File: assets/src/edit-story/output/page.js [hunk 2]
```diff
@@ -95,7 +99,11 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
           </amp-story-grid-layer>
         )}
 
-        <amp-story-grid-layer template="vertical" aspect-ratio={ASPECT_RATIO}>
+        <amp-story-grid-layer
+          id="amp-story-grid-layer-fullbleed-area"
```
Comment (swissspidy) [inline assets/src/edit-story/output/page.js]: Ditto, should use `class` instead of `id`

File: assets/src/edit-story/output/utils/styles.js [hunk 3]
```diff
@@ -48,6 +48,15 @@ function CustomStyles() {
                 overflow: visible;
               }
 
+              @media (max-aspect-ratio: 9 / 16)  {
+                @media (min-aspect-ratio: 1 / 2) {
+                  amp-story-grid-layer#amp-story-grid-layer-bg,
+                  amp-story-grid-layer#amp-story-grid-layer-fullbleed-area {
+                    margin-top: calc((${FULLBLEED_RATIO} * 100% / 2) - ${SAFE_ZONE_HEIGHT}px);
```
Comment (swissspidy) [inline assets/src/edit-story/output/utils/styles.js]: Since `SAFE_ZONE_HEIGHT` and `FULLBLEED_RATIO` are imported from elsewhere we won't notice here if they should change to something problematic. We're using `dangerouslySetInnerHTML` here, so it might be a good idea to sanitize them at the top of the function just to be safe - like for the other variables.

File: assets/src/edit-story/output/page.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/output/page.js]: Also, maybe drop the `amp-story-` prefix for our custom class names.

File: assets/src/edit-story/output/utils/styles.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Got it.

File: assets/src/edit-story/output/page.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/page.js]: Sure, will try.

File: assets/src/edit-story/output/page.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/page.js]: Got it.

File: assets/src/edit-story/output/page.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/page.js]: Resolved by using `body.amp-mode-mouse amp-story-grid-layer`

File: assets/src/edit-story/output/page.js [hunk 4]
```diff
@@ -95,7 +99,11 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
           </amp-story-grid-layer>
         )}
 
-        <amp-story-grid-layer template="vertical" aspect-ratio={ASPECT_RATIO}>
+        <amp-story-grid-layer
+          template="vertical"
+          aspect-ratio={ASPECT_RATIO}
+          class="grid-layer-fullbleed-area"
```
Comment (dreamofabear) [inline assets/src/edit-story/output/page.js]: Why use two different classes instead of one? Let's just name the class `grid-layer`.

File: assets/src/edit-story/output/utils/styles.js [hunk 5]
```diff
@@ -52,7 +52,8 @@ function CustomStyles() {
 
               @media (max-aspect-ratio: 9 / 16)  {
                 @media (min-aspect-ratio: 1 / 2) {
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: How did you come up with the values `9/16` and `1/2`?

File: assets/src/edit-story/output/page.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/page.js]: Got it. It is actually cleaner in this way. We don't need two classes.

File: assets/src/edit-story/output/utils/styles.js (hunk 5 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Got the lower bound (1 / 2) ratio by testing on UI. (Anything that is bellow 1 / 2 looks good at it is for now)

And got the upper bound (9 / 16) ratio by following the styling on the fullbleed area. (anything that is above 9 / 16 will be handled nicely by the default style)

I will wrap the ratio text into variables and add some comments.

Comment (dreamofabear) [reply assets/src/edit-story/output/utils/styles.js]: Can you add screenshots for the upper/lower bound scenarios?

File: assets/src/edit-story/output/utils/styles.js [hunk 6]
```diff
@@ -27,6 +27,13 @@ function isHexColorString(s) {
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const fullBleedHeight = FULLBLEED_RATIO / 2;
+  const safeZoneHeight = SAFE_ZONE_HEIGHT;
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: No need to duplicate this. Just use `SAFE_ZONE_HEIGHT` directly.

File: assets/src/edit-story/output/utils/styles.js [hunk 7]
```diff
@@ -27,6 +27,13 @@ function isHexColorString(s) {
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const fullBleedHeight = FULLBLEED_RATIO / 2;
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: This name doesn't make sense to me. `FULLBLEED_RATIO` == 9/16, so why is "height" == 9/18?

File: assets/src/edit-story/constants.js [hunk 8]
```diff
@@ -27,6 +27,7 @@ export const INSPECTOR_MAX_WIDTH = 280;
 export const PAGE_NAV_PADDING = 60;
 export const PAGE_NAV_BUTTON_SIZE = 40;
 export const PAGE_NAV_WIDTH = PAGE_NAV_PADDING + PAGE_NAV_BUTTON_SIZE;
+export const SAFE_ZONE_HEIGHT = 68;
```
Comment (dreamofabear) [inline assets/src/edit-story/constants.js]: Is this the height of the story's system UI (e.g. share icon + progress bar)? Why "safe zone"?

File: assets/src/edit-story/output/utils/styles.js [hunk 9]
```diff
@@ -48,6 +55,14 @@ function CustomStyles() {
                 overflow: visible;
               }
 
+              @media (max-aspect-ratio: ${gridLayerExpandUpperBound})  {
+                @media (min-aspect-ratio: ${gridLayerExpandLowerBound}) {
+                  amp-story-grid-layer.grid-layer {
+                    margin-top: calc(${fullBleedHeight} * 100% - ${safeZoneHeight}px);
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: I don't quite follow the logic here.

Let's review: `amp-story-grid-layer` is 2:3 (`PAGE_RATIO`), and has a 9:16 "full-bleed" child with that overflows it (`FULLBLEED_RATIO`). 

So we know that setting `margin-top: 0` is too small, since we'd be truncating half of (<full_bleed_height> - <safe_area_height>). So what value should we set `margin-top`?

File: assets/src/edit-story/output/utils/styles.js (hunk 6 above)
Comment (swissspidy) [reply assets/src/edit-story/output/utils/styles.js]: It was my suggestion to sanitize the constant here just to be safe - like for the other variables. Since we're using `dangerouslySetInnerHTML` here.

Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Fixed with another calculation method.

File: assets/src/edit-story/constants.js (hunk 8 above)
Comment (zidianlyu) [reply assets/src/edit-story/constants.js]: Ditto.

File: assets/src/edit-story/output/utils/styles.js (hunk 9 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Fixed with the new calculation method. Thanks for the explanation to the `pageHeight = 100vw / PAGE_RATIO` part!

File: assets/src/edit-story/output/utils/styles.js (hunk 7 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Fixed with the new calculation method.

File: assets/src/edit-story/output/utils/styles.js [hunk 10]
```diff
@@ -27,6 +27,14 @@ function isHexColorString(s) {
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const safeRatio = PAGE_RATIO;
+  const fullRatio = FULLBLEED_RATIO;
+
+  // The grid layer should stick to the top when the device ratio is between
+  // 493 / 1000 and 9 / 16. The ratio 493 / 1000 can guarantee the grid layer
+  // will respond and not having overlaps with the share button.
+  const gridLayerExpandLowerBound = '493 / 1000';
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: Why 493 (e.g. not 492 or 494)? 

Since icon height is static, this ratio will only work for certain screen widths. What is icon height? What is the minimum screen width that this ratio will work for?

File: assets/src/edit-story/output/utils/styles.js [hunk 11]
```diff
@@ -27,6 +27,14 @@ function isHexColorString(s) {
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const safeRatio = PAGE_RATIO;
+  const fullRatio = FULLBLEED_RATIO;
+
+  // The grid layer should stick to the top when the device ratio is between
+  // 493 / 1000 and 9 / 16. The ratio 493 / 1000 can guarantee the grid layer
+  // will respond and not having overlaps with the share button.
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: This comment is better! Let's make it even better:

"Make the story content aligned with top of viewport between aspect ratios 493:1000 and 9:16. This ensures that the story's system UI (progress bar, share button) is either completely overlapping or not overlapping the story content (i.e. never partially overlapping)."

Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Updated.

File: assets/src/edit-story/output/utils/styles.js (hunk 10 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Got it and updated.

File: assets/src/edit-story/output/utils/styles.js (hunk 11 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Thanks for the example!

**Review by dreamofabear — COMMENTED** [review]
Please add screenshots for each boundary case (lower than range, within range, greater than range).

**Comment by zidianlyu** [comment]
Here are the screenshots for the fix:

Lower than range (375 x 812):
lower

Within range (411 x 823):
within

Greater than range (360 x 620): 
greater

File: assets/src/edit-story/output/utils/styles.js [hunk 12]
```diff
@@ -27,6 +27,17 @@ function isHexColorString(s) {
...
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const safeRatio = PAGE_RATIO;
+  const fullRatio = FULLBLEED_RATIO;
+
+  // Make the story content aligned with top of viewport between aspect ratios
+  // 320:678 and 9:16. This ensures that the story's system UI (progress bar,
+  // share button) is either completely overlapping or not overlapping the story
+  // content (i.e. never partially overlapping). The icon height is 48px. Based
+  // on research, the smallest screen size in active use is 320 pixels wide. In
+  // this caes, the minimum screen width that this ratio will work for it 320px.
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: case

**Review by dreamofabear — APPROVED** [review]

File: assets/src/edit-story/output/utils/styles.js [hunk 13]
```diff
@@ -48,6 +59,14 @@ function CustomStyles() {
                 overflow: visible;
               }
 
+              @media (max-aspect-ratio: ${gridLayerExpandUpperBound})  {
+                @media (min-aspect-ratio: ${gridLayerExpandLowerBound}) {
+                  amp-story-grid-layer.grid-layer {
+                    margin-top: calc((100vw / ${fullRatio} - 100vw / ${safeRatio}) / 2);
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: Let's use 100% instead of 100vw.

File: assets/src/edit-story/output/utils/styles.js (hunk 12 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Fixed typo.

File: assets/src/edit-story/output/utils/styles.js (hunk 13 above)
Comment (zidianlyu) [reply assets/src/edit-story/output/utils/styles.js]: Updated.
