### PR TITLE
Load text sets one at a time to prevent blocking Editor from use

### LINKED ISSUE #4815: Text Sets are taking too long time to load
## Bug Description
Currently, when the text sets feature is turned on, the editor takes a long time to become active, there are also tests failing due to timing out (see also https://github.com/google/web-stories-wp/pull/4613#issuecomment-703718564)

## Expected Behaviour
- It should be possible to use the editor right away, instead of it becoming responsive once all the text sets are loaded.

## Steps to Reproduce
- Enable the text sets feature from Experiments
- Reload the editor, try to do something right away, e.g. adding a text element.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR updates the way text sets are loaded so they don't block the Editor from loading and becoming functional.

## Relevant Technical Choices

In order to progressively load the text sets in, I use a `setTimeout` loop to load each one, one-by-one.

## User-facing changes

None.  Hidden behind feature flag.

## Testing Instructions

1.) Open up the Editor with a new or existing story.
2.) Notice that the Editor becomes responsive to user input quickly.
3.) Open up the text tab (click on "T").
4.) See that text sets are loading in one by one.
5.) Notice that you can still use the Editor as the text sets load (including dragging/clicking on a loaded text set to apply to current page)>
6.) Also change filters for text sets and see that you can change filters and see the correct text sets
begin to load too.

---

Fixes #4815

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 1]
```diff
@@ -66,13 +64,13 @@ const CATEGORIES = {
 function TextSets() {
   const [textSets, setTextSets] = useState([]);
   const [selectedCat, setSelectedCat] = useState(null);
+  const [filteredTextSets, setFilteredTextSets] = useState([]);
+  const [renderedTextSets, setRenderedTextSets] = useState([]);
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: I needed both `filteredTextSets` and `renderedTextSets` to change states at roughly the same time so I converted `filteredTextSets` into a state variable (instead of `useMemo`) so they both can be updated within the same `useEffect`.

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 2]
```diff
@@ -101,17 +130,12 @@ function TextSets() {
         />
       </CategoryWrapper>
       <TextSetContainer ref={ref} role="list" aria-labelledby={sectionId}>
-        <UnitsProvider
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js:104]: This `UnitsProvider` is unneeded because the `TextSetElements` (which actually renders the text sets) has its own `UnitsProvider` within it.

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 3]
```diff
@@ -83,7 +82,34 @@ function TextSets() {
...
+          ...renderedTextSets,
+          filteredTextSets[renderedTextSets.length],
+        ]);
+      }, 10);
+    }
+  }, [renderedTextSets, filteredTextSets]);
+
+  useEffect(() => {
+    window.clearTimeout(loadingTimeoutRef.current);
+    isLoadingRef.current = false;
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: I'm not following what this is for?

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 4]
```diff
@@ -83,7 +82,34 @@ function TextSets() {
...
+
+      loadingTimeoutRef.current = window.setTimeout(() => {
+        isLoadingRef.current = false;
+        setRenderedTextSets([
+          ...renderedTextSets,
+          filteredTextSets[renderedTextSets.length],
+        ]);
+      }, 10);
+    }
+  }, [renderedTextSets, filteredTextSets]);
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: I think we can get rid of the refs if we do something like this:
```
  const numRendered = renderedTextSets.length;
  useEffect(() => {
    if (numRendered >= filteredTextSets.length) {
      return () => {};
    }

    const loadingTimeoutId = window.setTimeout(() => {
      setRenderedTextSets((rendered) => [
        ...rendered,
        filteredTextSets[rendered.length],
      ]);
    }, 10);

    return () => {
      window.clearTimeout(loadingTimeoutId);
    };
  }, [numRendered, filteredTextSets]);
```

Should also make the timeout logic specific to this effect.

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 5]
```diff
@@ -83,7 +82,34 @@ function TextSets() {
   );
 
   useEffect(() => {
-    getTextSets().then(setTextSets);
+    window.clearTimeout(loadingTimeoutRef.current);
+    isLoadingRef.current = false;
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: I think we can get rid of these if we contain the async stuff to that one effect

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js (hunk 4 above)
Comment (maxyinger) [reply assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: Would also make it easy to swap out with `requestIdleCallback` if we wanted to go down that route

**Review by maxyinger — APPROVED** [review]
Really smart idea. Below is just some suggestions on how we could possibly clean it up a bit, but also great as is!

This kinda got the juices flowin and have a couple ideas where we could take this:
- Render placeholder containers with loading states until we actually render the text set so the scroll doesn't grow.
- Could also add an intersection observer and only render once they appear on screen.
- Last thing is we could alter the data structure a bit to persist text set common between `filteredTextSet` updates.

These are just enhancements that come to mind if we want to implement them on later PRs.

Combining the intersection observer approach with the `requestIdleCallback` approach would basically make these idle until active which was an idea I was saying we could do on the dashboard for perf wins

💭 **Amortization** - that's the word I was looking for that describes approaches we're using rn

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js (hunk 4 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: Thanks for the refactor!  Works like a charm.  When I was first writing this out, my intention was to not use any refs but then I ran into a bug that was causing the useEffect to trigger more than it should, so I put in the loading ref and then when I actually fixed the bug, things smoothed out but I didn't back out of the decision.  Thanks for the second eyes, this is much cleaner!!

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js (hunk 3 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: It's gone, your refactor cleaned up all the kruft 🎉

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 6]
```diff
@@ -53,19 +55,20 @@ function LibraryProvider({ children }) {
     () => [
       MEDIA,
       MEDIA3P,
-      TEXT,
+      ...(tab === TEXT.id ? [TEXT] : [{ icon: TextIcon, id: 'text' }]),
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/libraryProvider.js:58]: So we don't load up all the text sets right away and so we don't hold all of them in memory all the time, this logic will mount/unumount text pane based on whether the text tab is active or not.

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 7]
```diff
@@ -82,10 +88,35 @@ function TextSets() {
     [textSets]
   );
 
-  useEffect(() => {
-    getTextSets().then(setTextSets);
+  const handleSelectedCategory = useCallback((selectedCategory) => {
+    setSelectedCat(selectedCategory);
+    setItemByKey(`${LOCAL_STORAGE_PREFIX.TEXT_SET_SETTINGS}`, {
+      selectedCategory,
+    });
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js:116]: Since the text pane unmounts and mounts based on its active state, I'm saving off the selected category to local storage so if someone switches tabs, their selected category will persist.

**Comment by mariano-formidable** [comment]
@littlemilkstudio I think you suggestion to use the intersection observer to only load visible text sets would be a great thing to do (or at least test out).  I see this as just the first iteration in getting text sets to load quickly, but definitely not the final "best" solution.

File: assets/src/edit-story/utils/localStore.js [hunk 8]
```diff
@@ -0,0 +1,35 @@
+/*
```
Comment (mariano-formidable) [inline assets/src/edit-story/utils/localStore.js:1]: Moved our localStorage calls to one file to wrap the calls to get/set around general functionality we always want to do (like wrapping `getItem` for `try/catch` and stuff).

File: assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js [hunk 9]
```diff
@@ -79,9 +77,7 @@ describe('Text Sets Library Panel', () => {
       expect((await getTextElements()).length).toBeGreaterThan(0);
     });
 
-    // Disable reason: timing out in CI, need investigation into async loading of text sets
-    // eslint-disable-next-line jasmine/no-disabled-tests
-    xit('should allow user to drag and drop text set onto page', async () => {
+    it('should allow user to drag and drop text set onto page', async () => {
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/panes/text/textSets/karma/textSets.karma.js:95]: Re-enabled tests now that text sets load quicker, should work okay in CI 🤞

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js (hunk 1 above)
Comment (carloskelly13) [reply assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: Would using a `useReducer` for filtered and rendered buy us anything here?

Comment (mariano-formidable) [reply assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: Good call, let me look, I think it would 🤔

**Review by carloskelly13 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/text/textSets/textSetElements.js [hunk 10]
```diff
@@ -39,14 +39,27 @@ function getElementContent(content, isForDisplay) {
   };
 }
 
+function TextSetContainer({ pageSize, children }) {
+  return pageSize ? (
+    <UnitsProvider pageSize={pageSize}>{children}</UnitsProvider>
+  ) : (
+    children
+  );
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetElements.js:47]: Only render `UnitsProvider` if a pageSize is provided.

File: assets/src/edit-story/components/library/libraryProvider.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/components/library/libraryProvider.js:58]: That's actually against WAI-ARIA recommendations for [a tab panel with automatic display](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html) (pressing the arrow keys while focus is in the tab list instantly shows the new tab). The tab panel should be in the DOM all the time.

Rather, use the `isActive` property being sent to the individual pane to load things conditionally inside the component.

In particular, however, we should never unload the pane once it's been loaded. That's bad for accessibility. Of course, unless it's a huge memory concern, but then we should really be fixing that underlying problem.

I recommend that we keep that tab panel and the general DOM for it in the document from the start, but I'm open to only loading the text set list on the first switch to that tab and then conditionally hiding the text set list when the tab is inactive if it's a concern.

File: assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+export const TEXT_SET_ACTIONS = {
+  RESET: 'reset',
+  RENDER_NEXT_TEXT_SET: 'render_next_text_set',
+};
+
+export function getTextSetReducer(textSets, allTextSets, size = 10) {
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js:22]: Why is this not a "real" `useReducer` hook? Just to use existing React patterns and cause less confusion.

You can also use the util [`useReduction`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/utils/useReduction.js) which tends to greatly simplify this type of simple reducer boilerplate.

`useReduction` is similar to how `redux-toolkit` reduces `redux` boilerplate, if you have experience with that

**Review by barklund — COMMENTED** [review]
I know I'm a bit late for this one but have a few follow-up comments.

File: assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js (hunk 11 above)
Comment (carloskelly13) [reply assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js:22]: I can update this in the next filter PR. Good idea.

Comment (carloskelly13) [reply assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js:22]: Oh nevermind, we are using `useReducer`.

Comment (carloskelly13) [reply assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js:22]:
```
const [{ filteredTextSets, renderedTextSets }, dispatch] = useReducer(
    textSetReducer,
    {
      filteredTextSets: [],
      renderedTextSets: [],
    }
  );
```

Comment (carloskelly13) [reply assets/src/edit-story/components/library/panes/text/textSets/getTextSetReducer.js:22]: As for the unloading of DOM, I agree, I think we are going to have to rethink how we do render preview components as this will only become a bigger problem with layout sets as well.
