### PR TITLE
Dashboard: Prevent focus on menu separator lines 

### LINKED ISSUE #4197: Dashboard A11y: Story Menus - prevent focus on separators
## Bug Description
Right now, using a keyboard in a story context menu on the dashboard, you can focus on the separator "lines" that break apart menus. These should not be focusable. 

## Expected Behaviour

Separator lines should not be focusable in story context menus. 

## Steps to Reproduce

Open a story's context men (the menu that pops open if you click on the three dots below a story in the grid or list view) and use the keyboard to go through menu items, see that separator lines are focusable.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Summary
Updates structure of story context menu items so that separators are borders not line items to prevent them being focusable. 

## Relevant Technical Choices

- moving separator lines to menu items as top border to prevent them becoming list items (also tightens up the space a little bit on the menu)

## User-facing changes

-The separator line items in story context menus are no longer focusable. 

## Testing Instructions

- Open a story's context menu and use the arrow keys to select an item, notice that the focus never disappears (where it would focus on the separator line itself). 
- Updated popover menu in storybook too: `story/dashboard-components-popovermenu--default`

context menu keyboard nav

---

Addresses #4197

### CODE REVIEW

**Review by dmmulroy — APPROVED** [review]
Looks good to me, and works.  One thing you might consider is removing the option for a bottom separator and passing the prop as a boolean rather a string containing `top` or `bottom`.

File: assets/src/dashboard/components/popoverMenu/menu.js [hunk 1]
```diff
@@ -65,6 +65,22 @@ export const MenuItem = styled.li`
     &:focus, &:active, &:hover {
       color: ${isDisabled ? theme.colors.gray400 : theme.colors.gray700};
     }
+    
+    ${
+      separator === 'top'
+        ? `
+        border-top: 1px solid ${theme.colors.gray50};
+      `
+        : ''
```
Comment (carloskelly13) [inline assets/src/dashboard/components/popoverMenu/menu.js]: Little nit but we can short circuit this and do
```
separator === 'top' && `border-top: 1px solid ${theme.colors.gray50};`
```

File: assets/src/dashboard/components/popoverMenu/menu.js [hunk 2]
```diff
@@ -65,6 +65,22 @@ export const MenuItem = styled.li`
...
+    }
+
+    ${
+      separator === 'bottom'
+        ? `
+        border-bottom: 1px solid ${theme.colors.gray50};
```
Comment (carloskelly13) [inline assets/src/dashboard/components/popoverMenu/menu.js]: Same here!

**Review by carloskelly13 — APPROVED** [review]

File: assets/src/dashboard/components/popoverMenu/menu.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/components/popoverMenu/menu.js]: I actually had that at first but was bothered by the `false:false` that's rendered as a style when the separator isn't present in the list item. 
Screen Shot 2020-08-31 at 8 55 29 AM
Instead I decided to take this nit and Dillon's suggestion for a boolean instead of a string and just add a className to the list items that need the border top or bottom so that it's easier to tell what the `item.separator` does inside the map and eliminates the conditional rendering inside the styles. 

Thoughts?
