### PR TITLE
Try to fix some stale element updates

### LINKED ISSUE #9000: Design Panel: Changes do not save when clicking back into main story editor area
## Bug Description

A [forum user reported](https://wordpress.org/support/topic/new-bugs-image-size-validation-more/) that when a user adds or changes text in the Accessibility field for an image and then clicks back into the main editor area, the Accessibility text is not saved.

## Expected Behaviour

Accessibility text should be saved by default after the user clicks back into the main editor area.

## Steps to Reproduce

1. Click on an image in the editor
2. In the right sidebar, enter text in the Accessibility field
3. Click anywhere in the main editor area
4. Click on the original image and see that Accessibility text was not added/updated

## Screenshots

Video: https://jmp.sh/FwLr6y5

## Additional Context

- Plugin Version: v1.110
- WordPress Version: v5.8.1
- Operating System: macOS Big Sur
- Browser: Chrome v93

### LINKED ISSUE #11062: Text box not resizing when changing font weight
## Bug Description

I just got informed about an edge case where changing font weight causes the text to overflow its bounding box.

## Expected Behaviour

If changing font weight (or perhaps also font size or other properties) causes the text to overflow the text box, the text box should be resizes

## Steps to Reproduce

1. Create a new text element with some text in it
2. Resize it to be very narrow, almost causing line wrap
3. Make font bold
4. See how text wraps, now exceeding text box

## Screenshots

https://user-images.githubusercontent.com/841956/159799534-9da76b37-70ba-4528-b67c-a73a912f986f.mov

https://user-images.githubusercontent.com/841956/159799540-2cff361c-700d-4817-8e6e-06e15a74b157.mov

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9
- Operating System: macOS Monterey
- Browser: Chrome

### LINKED ISSUE #13072: Floating Menu: Changing selection while editing element causes changes to be applied to new element
## Bug Description

Follow-up to #13071, where I noticed this.

When editing an element, e.g. through the floating menu or the style panel, and selecting an other element on the canvas before hitting Enter, the changes will be applied to the new element

This can cause quite some unintended side effects when selecting an element from a different type.

For example, #13071 was caused by changing selection from text to shape (the default bg), and the `onChange` handler calling `getUpdatedSizeAndPosition()` on the selected element IDs, which then leads to `calculateTextHeight()` rendering `<TextOutputWithUnits>` with a shape element rather than the intended text element.

803ae7bc510e154392e9a5e33cc3db61e75a3a25 and 93292ac84ddcf6210ce51755f1b1abb7191be530 added some hardening to avoid some crashes, but there can be more edge cases like this that need a proper solution.

## Expected Behaviour

Either the changes to the previous element should be applied to it or they should be ignored. But they should not be applied to the newly selected element.

For comparison, in the style panel, `useDesignPanels()` uses `updateElementsById({ elementIds: selectedElementIds, ... })` rather than `updateSelectedElements()`, which avoids this issue. This could be a solution for the floating menu as well.

Though the style panel is not bulletproof either, as for example the `StoryFontPicker` in `FontControls` seems to be rendered with the wrong `selectedElements` as well.

That could be solved by having `FontControls` pass `selectedElements` down to the font picker, instead of the font picker itself using `useStory()` (where it gets the new selection instead of the previous one).

## Steps to Reproduce

1. Add two text elements, A and B
2. Select element A
3. In the floating menu, type a different number in the font size dropdown
4. Do not hit enter, but instead immediately select element B on the canvas
5. Notice that the font size of element B was updated, not A

## Screenshots

https://user-images.githubusercontent.com/841956/221167970-3df96a00-dc74-460d-ae45-68c2a17fc515.mov

## Additional Context

- Plugin Version: 1.30.0
- WordPress Version: 6.2
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
See #13072 for context.

Ensure element is properly updated when:

* Changing font size in floating menu and then clicking on canvas
* Changing element dimensions in style panel and then clicking on canvas
	* Includes resizing text elements depending on aspect ratio lock

Reverts 93292ac84ddcf6210ce51755f1b1abb7191be530 as it’s no longer needed.

Also ensures that text box resizes when changing font weight.

Fixes #11062
Fixes #13072
Fixes #9000

### CODE REVIEW

File: packages/story-editor/src/components/style/designPanel.js [hunk 1]
```diff
@@ -118,6 +120,21 @@ function DesignPanel({
     )
   );
 
+  const internalSubmitRef = useRef();
+  useEffect(() => {
+    internalSubmitRef.current = internalSubmit;
+  }, [internalSubmit])
```
Comment (swissspidy) [inline packages/story-editor/src/components/style/designPanel.js]:
```suggestion
  }, [internalSubmit]);
```

File: packages/story-editor/src/components/style/designPanel.js [hunk 2]
```diff
@@ -118,6 +120,21 @@ function DesignPanel({
...
+
+  const elementUpdatesRef = useRef();
+  useEffect(() => {
+    elementUpdatesRef.current = elementUpdates;
+  }, [elementUpdates])
```
Comment (swissspidy) [inline packages/story-editor/src/components/style/designPanel.js]:
```suggestion
  }, [elementUpdates]);
```
