### PR TITLE
Use Moveable in Library for Media

### LINKED ISSUE #1930: Dragging media from library: The clone displays more than media
## Bug Description

When dragging media from media library, the clone being dragged displays some parts of the library as well instead of just the image being dragged. This makes it quite disturbing sometimes when trying to drop to a target precisely.

## Expected Behaviour
Only the image clone should be visible when dragging.

## Steps to Reproduce

1. Drag image from media so that the dragged image is on the first row, just below the filters.

2. See the filters included to the clone.

## Screenshots
Screenshot 2020-05-21 at 14 25 20

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #5057: GIFs not animated while dragging onto canvas
## Bug Description

When dragging a Tenor GIF onto the canvas, the GIF is not animated.

Possibly related: #1930, #1979, #5006

## Expected Behaviour

GIF should stay animated while dragging.

## Steps to Reproduce

1. Drag GIF from Tenor 3P Media tab onto canvas
1. Notice it isn't animated anymore

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #5335: Use Moveable for dragging Media from Library
## Feature Description

Use Moveable for dragging Media from the library instead of the default drag. This way we can display the snapping lines, display the element as it is added to the canvas.

This issue should fix #1979, #5057 and #1930.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Uses Moveable in Library instead of default dragging.

EDIT: Snapping will be addressed separately!
This is currently used for images and videos only -- shapes and text sets will be handled separately.

## Relevant Technical Choices
- Adds an overlay to `Editor` which will contain the Moveable that's being dragged.
- Adds a clone image that will be added to the DOM if the user hovers on media -- this clone will then be dragged. We can't move the original element itself since it wouldn't be visible -- it would be under the Workspace layer.
- Adds a frame with the size of the element in the library that will be the target for the Moveable and dragged together with the clone. We need this for the snapping to work.

## To-do

- [x] Fix base-color calculation for new dragging.
- [x] Update tests where necessary

## Testing Instructions
I
1. Add an image or a video.
2. Now drag an image or video to the canvas
3. While dragging verify that it displays information about drop targets
4. Verify that dropping into the existing image/video is possible

II
1. Drag a GIF to the canvas, verify the gif is animating while dragging.

III
1. Verify that dragging image/video from both local/3rd party media work.

---

Fixes #5335 
Fixes #5057 
Fixes #1930 
~Fix for #1979~  will be implemented separately!

### CODE REVIEW

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 1]
```diff
@@ -160,6 +160,10 @@ function getElementProperties(
   if (!isNum(y)) {
     y = 0;
   }
+
+  // When dragging an element to canvas, this means that the element will always be
+  // positioned inside the design space, even if the user drags it partially outside.
+  // @todo Is this intended behavior?
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/useInsertElement.js]: I don't think so, no (that this is intended behavior). I think it's fair to say that it should at least be partially on canvas, but not fully. Removing `- width` and `- height` respectively would fix that.

**Review by barklund — COMMENTED** [review]
Overall it seems to work excellently.

One thing I noted: something is breaking the layout of the media elements in the library currently - this goes for both local library and Unsplash:

Screen Shot 2020-12-01 at 14 28 14
See the weird spacing between the rows?

Screen Shot 2020-12-01 at 14 28 22
And here there's just a bunch of space added to the top of each row - which happens to be the same size as the credit overlay, so probably related.

**Comment by miina** [comment]
> One thing I noted: something is breaking the layout of the media elements in the library currently - this goes for both local library and Unsplash:

Ah, yes, saw that, too, forgot to mention it's an issue currently.

Thanks for the sanity-check!

File: assets/src/edit-story/app/layout/layout.js [hunk 2]
```diff
@@ -72,11 +74,13 @@ const Area = styled.div`
 function Layout() {
   return (
     <LayoutProvider>
-      <Editor>
-        <Area area="lib">
-          <Library />
-        </Area>
-        <Workspace />
+      <Editor zIndex={3}>
+        <CanvasProvider>
```
Comment (swissspidy) [inline assets/src/edit-story/app/layout/layout.js:78]: Since you add `CanvasProvider` here, need to remove it from its prior location in `Workspace` (`workspace.js`)?

Comment (miina) [reply assets/src/edit-story/app/layout/layout.js:78]: It is removed there as far as I can see: https://github.com/google/web-stories-wp/pull/5512/files#diff-cc8f92173d9a285323c8490a7626429e4f8270ab26428d73eac9e52048401f0dR27

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 3]
```diff
@@ -35,7 +35,7 @@ import InnerElement from './innerElement';
 
 const AUTOPLAY_PREVIEW_VIDEO_DELAY_MS = 600;
 
-const Container = styled.button.attrs((props) => ({
+const Container = styled.div.attrs((props) => ({
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js:38]: I guess we can remove the button-focused style if this is not a button anymore.

File: assets/src/edit-story/components/canvas/utils/useSnapping.js [hunk 4]
```diff
@@ -27,7 +27,12 @@ import { useGlobalIsKeyPressed } from '../../keyboard';
 import { useDropTargets } from '../../dropTargets';
 import useCanvas from '../useCanvas';
 
-function useSnapping({ isDragging, canSnap, otherNodes }) {
+function useSnapping({
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/utils/useSnapping.js:30]: I don't think snapping here works correctly, but not sure why. It can snap to the canvas and to the design style guide, but not to other elements (in this case some shapes):

snapping-bug

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 5]
```diff
@@ -0,0 +1,228 @@
...
+import InOverlay from '../../../overlay';
+import isTargetOutOfContainer from '../../../../utils/isTargetOutOfContainer';
+
+const TargetBox = styled.div`
+  position: absolute;
+  width: ${({ width }) => `${width}px`};
+  height: ${({ height }) => `${height}px`};
+`;
+
+function LibraryMoveable({
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:44]: I think this is missing a transform handler similar to [the frame element](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/frameElement.js#L105-L107) (and actually [the display element too](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/displayElement.js#L133-L135)) - if the dragged element hovers a drop-target, the dragged element should be hidden while the hovered clone is shown:

droptarget-bug

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 6]
```diff
@@ -0,0 +1,228 @@
...
+        height: h,
+      } = cloneRef.current.getBoundingClientRect();
+      const { x: pageX, y: pageY } = pageContainer.getBoundingClientRect();
+
+      insertElement(type, {
+        ...elementProps,
+        x: editorToDataX(x - pageX, pageSize.width),
+        y: editorToDataY(y - pageY, pageSize.height),
+        width: editorToDataX(w, pageSize.width),
+        height: editorToDataY(h, pageSize.height),
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:195]: If you get these from the `UnitsProvider` via `useUnits()`, you don't need the page size argument - it's implicit. If it's possible to use that context of course?

File: assets/src/edit-story/components/library/panes/media/common/innerElement.js [hunk 7]
```diff
@@ -165,15 +139,14 @@ function InnerElement({
...
       />
     );
+    cloneProps.src = thumbnailURL;
   } else if (type === 'video') {
-    const { lengthFormatted, poster, mimeType } = resource;
     const displayPoster = poster ? poster : newVideoPosterRef.current;
-    return (
+    media = (
       <>
         <Video
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/common/innerElement.js:151]: I would expect this video element to stop playing, once I start dragging it (a clone of it, that is) in - that it keeps playing seem weird:

video-drag-playing

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 5 above)
Comment (barklund) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:44]: For this component, I would also expect pressing <kbd>esc</kbd> would completely abort the drag - as it does for native drag'n'drop and as [per WCAG recommendations](https://www.w3.org/wiki/PF/ARIA/BestPractices/DragDrop#Step_4:_Configure_your_script_for_AT_drag-and-drop_operations:~:text=If%20at%20any%20time%20during%20the%20drag%20process%2C%20the%20user%20pressed%20the%20Escape%20key%20to%20cancel%20drag%20operations).

**Review by barklund — COMMENTED** [review]
Found a couple of "bugs" - or at least some edge-cases that don't work counter to (my) expectations.

I didn't go into nits in the actual code - just the overall functionality for now.

File: assets/src/edit-story/components/library/panes/media/common/innerElement.js (hunk 7 above)
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/common/innerElement.js:151]: Found another weird thing for this element. 🤷 

When you abort dragging a video (by dropping the element while the mouse is still over the original element), the dragged clone static element seems to return to the original position on top of the video, but not with the exact same dimension - notice the right-most 1px of the image still animating and also the round corner disappearing (because the clone doesn't have that).

You have to move the mouse out of the element again to reset it.

abort-video-bug

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:44]: Ah, I thought it felt weird but since previously the dragging worked like this, left it in. However, true that now we're using Moveable and can actually hide it. _Checking_

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 6 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:195]: `useUnits()` is not available here, it seemed more straightforward to just use the available page size instead of reorganizing the structure for making `useUnits` available.

File: assets/src/edit-story/components/canvas/utils/useSnapping.js (hunk 4 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/utils/useSnapping.js:30]: Apparently, that was just not added -- should be there now.

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 8]
```diff
@@ -0,0 +1,260 @@
...
+      });
+    }
+    resetMoveable();
+    return undefined;
+  };
+
+  const { offsetX: snappingOffsetX } = getTargetOffset();
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: I think this doesn't work correctly for local library images (but works for third-party content):

local-library-snap-bug

**Review by barklund — COMMENTED** [review]
Found another thing...

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 8 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: Hmm, I'm actually not seeing this issue -- is it possible that you scrolled while dragging for this to happen? In this case, it would be related to #2785.

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 9]
```diff
@@ -0,0 +1,260 @@
...
+  const resetMoveable = useCallback(() => {
+    targetBoxRef.current.style.transform = null;
+    cloneRef.current.style.transform = null;
+    // Hide the clone, too.
+    cloneRef.current.style.opacity = 0;
+    setIsDragging(false);
+    setDraggingResource(null);
+  }, [setDraggingResource]);
+
+  useGlobalKeyDownEffect(
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: This is actually interfering with other esc handlers and can't be used here...

Tried using `useKeyDownEffect` -- checking the `document.activeElement` while dragging then it's `document.body` -- however, this would also interfere with the global `esc` handlers so not sure what would be the approach here to implement the keyhandler. 🤔

Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: Found a potential fix for this.

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 8 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: Resolving since snapping will be addressed separately for all elements together.

**Review by barklund — APPROVED** [review]
Not considering snapping, as we've actively removed that for now, this works excellently!
