### PR TITLE
E2E Tests: Add test for pre-publish checklist for contributors

### LINKED ISSUE #9232: Checklist: Empty state not showing with contributor role
## Bug Description

The empty state of the checklist is not being shown to a user with the `contributor` role. When the checklist items are complete, the publish button tooltip still says the user should review the checklist.

## Expected Behaviour

Empty state of the checklist should be displayed when all checklist issues that the user can fix are fixed.

## Steps to Reproduce

1. Sign in as a contributor
2. Create a new story
3. Keep editing until all checklist items are completed
4. See that there is no empty state (checkmark icon with some nice text)

## Screenshots

image
image

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8.1
- Operating System: MacOSX Big Sur
- Browser: Chrome

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Found a little while back where contributors were seeing the wrong UI: #9232. Couldn't reproduce, so we added a quick e2e test to make sure there is no regression.

## Summary

Adds a quick publishing flow test for a user with the `Contributor` role. 

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

n/a

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

Tests should pass

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9232

### CODE REVIEW

File: packages/e2e-tests/src/specs/editor/publishingFlow.js [hunk 1]
```diff
@@ -25,8 +25,55 @@ import {
   withPlugin,
   publishStory,
   getEditedPostContent,
+  withUser,
 } from '@web-stories-wp/e2e-test-utils';
 
+describe('Contributor User', () => {
+  let stopRequestInterception;
+
+  beforeAll(async () => {
```
Comment (BrittanyIRL) [inline packages/e2e-tests/src/specs/editor/publishingFlow.js]: 🤔  since this is to verify proper messaging for contributors, should it live in the `prepublishChecklist` file instead since this is to verify the publishing flow?

File: packages/e2e-tests/src/specs/editor/publishingFlow.js [hunk 2]
```diff
@@ -25,8 +25,55 @@ import {
...
+        });
+      } else {
+        request.continue();
+      }
+    });
+  });
+
+  afterAll(async () => {
+    await page.setRequestInterception(false);
+    stopRequestInterception();
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/publishingFlow.js]: Can remove beforeAll & afterAll here. Not relevant for this test

File: packages/e2e-tests/src/specs/editor/prepublishChecklist.js [hunk 3]
```diff
@@ -51,4 +53,29 @@ describe('Pre-Publish Checklist', () => {
...
+
+      await insertStoryTitle('Publishing Flow: Contributor');
+
+      const checklistToggle = await page.$(
+        'button[aria-owns="checklist_companion"]',
+        { text: 'Checklist' }
+      );
+
+      // verify no issues are present
+      await checklistToggle.click();
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/prepublishChecklist.js]: Could also just do it like the test above:

```js
await expect(page).toClick('button[aria-label^="Checklist: "]');
await expect(page).toMatchElement(
  '#pre-publish-checklist[data-isexpanded="true"]'
);
```

Any reason why this test would need to do it differently?

Comment (samwhale) [reply packages/e2e-tests/src/specs/editor/prepublishChecklist.js]: Nope that's a good catch. Just moved this over, so I can update that here

File: packages/e2e-tests/src/specs/editor/prepublishChecklist.js [hunk 4]
```diff
@@ -51,4 +53,27 @@ describe('Pre-Publish Checklist', () => {
...
+        '#pre-publish-checklist[data-isexpanded="true"]'
+      );
+
+      // verify no issues are present
+      await expect(page).toMatchElement('p', {
+        text: 'You are all set for now. Return to this checklist as you build your Web Story for tips on how to improve it.',
+      });
+
+      // verify that publish button is disabled
+      await page.$('button:disabled', { text: 'Publish' });
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/prepublishChecklist.js]:
```suggestion
      await expect(page).toMatchElement('button:disabled', { text: 'Publish' });
```

This needs an `expect` so that the test would fail if the element isn't found

Comment (samwhale) [reply packages/e2e-tests/src/specs/editor/prepublishChecklist.js]: oh oops 🤦 good catch

**Review by swissspidy — APPROVED** [review]
