### PR TITLE
Fix keyboard navigation on library tabs

### LINKED ISSUE #2272: Library tabs: keyboard navigation is broken
## Bug Description

It used to be possible to navigate between library tabs using arrow left/right. It got broken at some point.

## Expected Behaviour

The tabs in the library tabs should switch using key left/right.

## Steps to Reproduce

1. Click <kbd>tab</kbd> a few times
2. Once you land on the media-panel tab, it will be highlighted in blue.
3. Press <kbd>right</kbd>

Observe: you are still on the Media tab.
Expected: you will switch to the Text tab.

## Screenshots

image

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dvoytenko**
## Summary

A simple oversight: instead of passing a key handler, it passes a closure resolving to a handler.

## To-do

n/a

## User-facing changes

User can navigate library tabs using arrows left and right.

## Testing Instructions

See #2272

---

Fixes #2272

### CODE REVIEW

File: assets/src/edit-story/karma/fixture.js [hunk 1]
```diff
@@ -230,6 +230,24 @@ export class Fixture {
...
+  /**
+   * @param {Element} element
+   * @return {Promise} Yields when the element is displayed on the screen.
+   */
+  waitOnScreen(element) {
+    return new Promise((resolve) => {
+      const io = new IntersectionObserver((records) => {
+        records.forEach((record) => {
+          if (record.isIntersecting) {
+            resolve();
```
Comment (barklund) [inline assets/src/edit-story/karma/fixture.js]: Can this resolve twice (two records intersecting)? And would that be a problem?

File: assets/src/edit-story/components/library/karma/libraryTabs.karma.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+      await fixture.waitOnScreen(
+        fixture.container.querySelector('#library-pane-media')
+      );
+      await fixture.snapshot();
+    });
+
+    fit('should switch tabs on left and right keys', async () => {
+      await fixture.events.keyboard.press('ArrowRight');
+
+      // @todo: what's the best way to confirm switching of a tab?
```
Comment (barklund) [inline assets/src/edit-story/components/library/karma/libraryTabs.karma.js:60]: You can check the pane's `aria-expanded` attribute:

```js
      const textPane = fixture.container.querySelector('#library-pane-text');
      expect(textPane.getAttribute('aria-expanded')).toBe(true);
```

Comment (barklund) [reply assets/src/edit-story/components/library/karma/libraryTabs.karma.js:60]: Or that `hidden` is not present or false on the pane, but I prefer the other method for this one.

The `hidden` check could however be made to be a generic matcher such as `expect(textPane).not.toBeHidden();`.

File: assets/src/edit-story/karma/fixture.js (hunk 1 above)
Comment (dvoytenko) [reply assets/src/edit-story/karma/fixture.js]: We can resolve many times. Only the first one will take. Several records intersecting or intersecting/non-intersecting in this case, I don't think that's important for this specific question.

File: assets/src/edit-story/components/library/karma/libraryTabs.karma.js (hunk 2 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/library/karma/libraryTabs.karma.js:60]: I see. I do like the idea of `aria-expanded`. Though there could be a bug where aria-expanded is set, but we forgot to show it. That being said, `toBeHidden` is also good. However, some implementation could keep elements off screen instead of "hidden". What's the safest from integration point of view?

Comment (dvoytenko) [reply assets/src/edit-story/components/library/karma/libraryTabs.karma.js:60]: Added `aria-expanded` test, but also kept `waitOnScreen`. IMHO that one is still less ambiguous than `toBeHidden`.

**Comment by dvoytenko** [comment]
@barklund changes made. ptal.

**Review by barklund — APPROVED** [review]
