### PR TITLE
3P Media: Misc fixes

### LINKED ISSUE #3651: SELECT_CATEGORY and DESELECT_CATEGORY actions should be clearing out pageToken and nextPageToken
Currently it's not cleared out, which results in incorrect requests sent to the API.

### LINKED ISSUE #3652: When searching for a term that returns no results (eg: sdfhskjdfh), the media gallery is not updated
Probably the empty results being interpreted as falsey

### LINKED ISSUE #3728: Pagination triggered incorrectly when scrollbar is close to the end
If the gallery scrollbar is close to the end in, let's say, page 3, and the user enters a search term, the scrollbar is somehow "kept" between these 2 states. This causes the scrollbar to be close to the end of the list, and several pages be fetched.

f8899ee8-84e5-4304-b515-38f275df0db9

### PR DESCRIPTION
**Pull request by diegovar**
## Summary

- fix error when no media is returned, properly handle the empty API response
- reset pageToken when searchTerm and selected category Id change.
- Ensure we propagate actions to all provider reducers if the payload has no provider (this allows us to do the above)
- scroll to the top of the gallery whenever the search term or category id change.
- Properly hide the categories chevron by using 'inherit' visibility (it currently shows even though that provider's pane has visibility: hidden).
- Fix Percy test to ensure we wait for media before taking the screenshot.

Fixes #3652
Fixes #3651 
Fixes #3728

### CODE REVIEW

File: assets/src/edit-story/app/media/pagination/reducer.js [hunk 1]
```diff
@@ -122,6 +124,26 @@ function reducer(state = INITIAL_STATE, { type, payload }) {
       };
     }
 
+    case media3pTypes.MEDIA3P_SET_SEARCH_TERM: {
```
Comment (ezxyz) [inline assets/src/edit-story/app/media/pagination/reducer.js]: As per offline discussion, this should be moved to media3p/providerReducer.js rather than depending on pagination/reducer.

Currently this won't affect local state but since pagination/reducer is used for both local state and media3p provider states, having this here makes it unclear that it only affects media3p state.

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js [hunk 2]
```diff
@@ -108,6 +110,11 @@ function PaginatedMediaGallery({
     }
   }, [hasMore, isMediaLoaded, isMediaLoading, setNextPage]);
 
+  // Scroll to the top when the searchTerm or selected category changes.
+  useEffect(() => {
```
Comment (ezxyz) [inline assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js:114]: is it possible to test this in karma?

**Review by ezxyz — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/app/media/pagination/reducer.js (hunk 1 above)
Comment (diegovar) [reply assets/src/edit-story/app/media/pagination/reducer.js]: Done.

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js (hunk 2 above)
Comment (diegovar) [reply assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js:114]: Added a test for when a category is selected.

**Review by diegovar — COMMENTED** [review]
Done

File: assets/src/edit-story/app/media/pagination/test/reducer.js [hunk 3]
```diff
@@ -183,4 +185,62 @@ describe('reducer', () => {
       expect.objectContaining({ pageToken: 'page2', nextPageToken: 'page3' })
     );
   });
+
+  it('should reset {next}pageToken when the search term changes', () => {
```
Comment (ezxyz) [inline assets/src/edit-story/app/media/pagination/test/reducer.js]: shouldn't these tests be in media/media3p/test/providerReducer.js

File: includes/Experiments.php [hunk 4]
```diff
@@ -402,6 +403,7 @@ public function get_experiments() {
 				'label'       => __( 'Coverr', 'web-stories' ),
 				'description' => __( 'Enable the Coverr tab in the Third-party media tab.', 'web-stories' ),
 				'group'       => 'editor',
+				'default'     => true,
```
Comment (ezxyz) [inline includes/Experiments.php]: please remove.

**Review by ezxyz — CHANGES_REQUESTED** [review]

File: includes/Experiments.php (hunk 4 above)
Comment (diegovar) [reply includes/Experiments.php]: oops

File: assets/src/edit-story/app/media/pagination/test/reducer.js (hunk 3 above)
Comment (diegovar) [reply assets/src/edit-story/app/media/pagination/test/reducer.js]: I believe this comment is outdated

**Review by ezxyz — APPROVED** [review]
