### PR TITLE
Shortcode: Properly handle case where no attributes are passed

### LINKED ISSUE #13431: Shortcode: Fatal error when passing empty string `$attribute`
## Bug Description

```
Fatal error: Uncaught TypeError: Google\Web_Stories\Shortcode\Embed_Shortcode::render_shortcode(): Argument #1 ($attributes) must be of type array, string given at /web-stories-wp/includes/Shortcode/Embed_Shortcode.php on line 60.
```

## Expected Behaviour

No fatal error. Fix is similar to the issue #13262.

## Steps to Reproduce

1. Insert shortcode block in post editor
2. Insert [web_stories_embed /]
3. Try to save post
4. Get errors

## Screenshots

Not required.

## Additional Context

- Plugin Version: 1.33.0
- WordPress Version: 6.2
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by AnuragVasanwala**
## Context

This PR fixes #13431 by adding initialization check for the attributes as described in the issue.

## Summary

When no argument is passed to the shortcode raises following error:
```
Fatal error: Uncaught TypeError: Google\Web_Stories\Shortcode\Stories_Shortcode::render_stories(): Argument #1 ($attrs) must be of type array, string given, called in /wp-includes/shortcodes.php on line 355 and defined in /wp-content/plugins/web-stories/includes/Shortcode/Stories_Shortcode.php on line 67
```

## Testing Instructions

1. Insert shortcode block in post editor
2. Insert [web_stories_embed /]
3. Try to save post
4. Get errors

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #13431

### CODE REVIEW

**Comment by swissspidy** [comment]
Besides the failed status checks the change looks reasonable 👍

File: includes/Shortcode/Embed_Shortcode.php [hunk 1]
```diff
@@ -53,11 +53,16 @@ public function register(): void {
 	 *
 	 * @since 1.1.0
 	 *
-	 * @param array<string, string|int> $attributes Shortcode attributes.
+	 * @param array<string, string|int>|string $attributes Shortcode attributes.
 	 * @param string                    $content Shortcode content.
```
Comment (swissspidy) [inline includes/Shortcode/Embed_Shortcode.php]:
```suggestion
	 * @param array<string, string|int>|string $attributes Shortcode attributes.
	 * @param string                                          $content Shortcode content.
```

**Review by swissspidy — APPROVED** [review]
