### PR TITLE
Fix pasting for search inputs

### LINKED ISSUE #4710: Cannot paste text in dialog inputs
## Bug Description

If you try to paste some text into a text field in a modal dialog (anything that opens "above" the editor such as font picker search input), it fails. No paste in the input is performed. Instead, pasting creates a new text element.

## Expected Behaviour

I should be able to paste text in the font picker search input and similar modal inputs

## Steps to Reproduce

1. Create a new text element
1. Open font picker
1. Paste text

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Adds `search` and some other inputs which allow pasting into to the list of inputs that should handle copying/pasting natively.

## Testing Instructions
- Copy some text
- Open the font family picker and paste into the search field
- Verify that the text is pasted into the input.

---

Fixes #4710

### CODE REVIEW

File: assets/src/edit-story/utils/nativeCopyPasteExpected.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ function nativeCopyPasteExpected() {
     'true' === contentEditable ||
     'textarea' === tagName.toLowerCase() ||
     ('input' === tagName.toLowerCase() &&
-      ('text' === type || 'number' === type))
+      ['text', 'number', 'search', 'email', 'tel', 'url'].includes(type))
```
Comment (barklund) [inline assets/src/edit-story/utils/nativeCopyPasteExpected.js:32]: Ah, it was the type, that was the trigger. I thought it was the dialog and the portal to a different section of the document... clever!

**Review by barklund — APPROVED** [review]
