### PR TITLE
Fix date and time

### LINKED ISSUE #5089: Date: Issues with certain date / time formats
## Bug Description

As reported in #5087 and #5050, there seem to be issues with certain date format and time format settings. Depending on the configuration in WordPress, our date package cannot transform the format and causes an error, crashing the document panel.

While we don't yet know all formats are causing this, there's definitely a need to make `convertFormatString()`  / `format()` more robust. 

One of the formats was `G \h h \m\i\n`

## Expected Behaviour

Document panel should not crash on unexpected formats.

Date library should be more robust

## Steps to Reproduce

Use a date format like `G \h h \m\i\n` to crash the editor.

Add & run tests

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Fixes some of the recurring date/time issues users have been reporting

## Relevant Technical Choices

* Fixes issue with incorrect character escaping in `convertFormatString`
* Adds fallback date and time formats if none is provided by WordPress
* Adds a ton of tests
* Fixes some existing tests

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

1. Under Settings -> General, try various different date formats and time formats (including leaving the box empty)
1. Go to editor / dashboard
1. Verify that time and date is showing correctly everywhere
1. Verify that document sidebar is not crashing

(Note: the publish time picker in the document sidebar uses its own custom date format and cannot be customized this way).

---

Fixes #5089

### CODE REVIEW

File: includes/Locale.php [hunk 1]
```diff
@@ -42,10 +42,26 @@ class Locale {
 	public function get_locale_settings() {
 		global $wp_locale;
 
+		/* translators: Date format, see https://www.php.net/date */
+		$default_date_format = __( 'd/m/Y', 'web-stories' );
+
+		/* translators: Date format, see https://www.php.net/date */
+		$default_time_format = __( 'g:i a', 'web-stories' );
+
+		$date_format = get_option( 'date_format' );
```
Comment (spacedmonkey) [inline includes/Locale.php]:
```suggestion
		$date_format = get_option( 'date_format', $default_date_format );
```

File: includes/Locale.php [hunk 2]
```diff
@@ -42,10 +42,26 @@ class Locale {
...
+		if ( empty( trim( $date_format ) ) ) {
+			$date_format = $default_date_format;
+		}
+
+		$time_format = get_option( 'time_format' );
```
Comment (spacedmonkey) [inline includes/Locale.php]:
```suggestion
		$time_format = get_option( 'time_format', $default_time_format );
```

File: includes/Locale.php (hunk 1 above)
Comment (swissspidy) [reply includes/Locale.php]: That doesn't cover the case where the option is an empty string though, does it?

Comment (spacedmonkey) [reply includes/Locale.php]: Nope, it doesn't.

**Review by spacedmonkey — APPROVED** [review]
SGTM with 2 small nic pic.

**Review by BrittanyIRL — APPROVED** [review]
LGTM, tested locally and everything is working as expected
