### PR TITLE
Fix: Adding text presets crashes editor

### LINKED ISSUE #1990: Adding text presets crashes editor
## Bug Description

Opted to add text by clicking the "+" symbol. On doing so, display turned blank

## Expected Behaviour

Text field should appear on canvas

## Steps to Reproduce

- create/open story
- select page (if applicable)
- select "+" symbol beside "T"

## Screenshots

Selected + Symbol:
image
On selection, page turned blank:
image

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
Fixes #1990

What's causing the issue is data that "shouldn’t belong to textStyles at all. That’s the format for textColors and fillColors only".

It's just affecting the QA env.

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by barklund** [comment]
@merapi, can you add relevant test instructions in the original ticket (#1990) and assign to QA? If you cannot add any test instructions, that make sense, then just close and merge.

**Comment by merapi** [comment]
> @merapi, can you add relevant test instructions in the original ticket (#1990) and assign to QA? If you cannot add any test instructions, that make sense, then just close and merge.

Personally, I can't merge, but when we do I will notify Claudio and he will be [more than happy](https://xwp.slack.com/archives/CCCAUAH6F/p1591039406176900) to proceed with testing.

**Review by spacedmonkey — DISMISSED** [review]
Don't you need to change this line to `3.0.0` - https://github.com/google/web-stories-wp/blob/master/web-stories.php#L45

File: includes/Database_Upgrader.php [hunk 1]
```diff
@@ -59,6 +59,7 @@ public function init() {
 		$routines = [
 			'1.0.0' => 'upgrade_1',
 			'2.0.0' => 'v_2_replace_conic_style_presets',
+			'3.0.0' => 'v_3_remove_old_text_styles',
```
Comment (spacedmonkey) [inline includes/Database_Upgrader.php]: We are trying to use [Semantic Versioning](https://semver.org/). 3.0.0 would be breaking change. Why not 2.0.1 or 2.1.0?

Comment (merapi) [reply includes/Database_Upgrader.php]: I just followed the previous migration logic because it does something similar.
But maybe 2.0.1 will be better because we primarily want to fix the data.
