### PR TITLE
Editor: Fixed zoomed scroll in RTL

### LINKED ISSUE #9807: Zoom + RTL: Horizontal scroll not working with 200%
## Bug Description
Originally reported by @BrittanyIRL 

Horizontal scrolling is not working in RTL mode when zoomed in 200% (see [Brittany's comment](https://github.com/google/web-stories-wp/issues/9807#issuecomment-981812506) below).

image3

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

This fixed the scroll bug while zoomed in RTL.

NB: This PR is towards #10127 until that gets merged, as it impacts this PR.

## User-facing changes

_Notice the scrollbar being all the way to the left side, but the canvas is only following along correctly in the latter screenshot._

| Before | After |
|-|-|
| Screen Shot 2022-01-07 at 16 40 43 | Screen Shot 2022-01-07 at 16 40 17 |

## Testing Instructions

This PR can be tested by following these steps:

1. Switch to RTL
2. Zoom to 200%
3. Scroll horizontally
4. Observe the canvas does not follow while scrolling horizontally (only vertically)

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9807

### CODE REVIEW

File: packages/story-editor/src/components/canvas/layout.js [hunk 1]
```diff
@@ -356,8 +356,8 @@ function useLayoutParamsCssVars() {
     '--viewport-height-px': `${viewportHeight}px`,
     '--overflow-x': hasHorizontalOverflow ? 'scroll' : 'visible',
     '--overflow-y': hasVerticalOverflow ? 'scroll' : 'visible',
-    '--scroll-left-px': `-${scrollLeft}px`,
-    '--scroll-top-px': `-${scrollTop}px`,
+    '--scroll-left-px': `${-scrollLeft}px`,
+    '--scroll-top-px': `${-scrollTop}px`,
```
Comment (barklund) [inline packages/story-editor/src/components/canvas/layout.js:360]: It was actually pretty obvious.

When scrolling horizontally in RTL, `scrollLeft` becomes negative, so this should have been a positive number, but ended up a double negative, which of course didn't work. Easy fix.

The fix for the `scrollTop` is actually irrelevant for now, but why not.

**Review by miina — APPROVED** [review]
Works like a charm!
