### PR TITLE
Apply visibility: inherit to dropdown arrow so there's no 'ghost' arrow

### LINKED ISSUE #4416: Media (category) dropdown arrow floating in space
## Bug Description

There is a second dropdown arrow that appears to be floating in space.

## Expected Behaviour

There should only be one dropdown arrow.

## Steps to Reproduce

1. Make sure to enable all third-party media related feature flags (also gifs and videos)
1. Go to the Third-party Media tab and observe that images will be default category
1. Click on the category dropdown button to expand the category list
1. Change the third-party media category to gifs or videos
1. Observe that the category collapse button from the images list persists (potentially behind new media elements, but it's lurking back there)

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by joannag6**
## Summary

Apply visibility: inherit to dropdown arrow so there's no 'ghost' arrow

## User-facing changes

This affects the Media3P pane (which is behind a feature flag).

## Testing Instructions
1. Make sure to enable all third-party media related feature flags (also gifs and videos)
2. Go to the Third-party Media tab and observe that images will be default category
3. Click on the category dropdown button to expand the category list
4. Change the third-party media category to gifs or videos
5. Category collapse button from the images list should **not** persist (potentially behind new media elements)

---

Fixes #4416

### CODE REVIEW

**Review by ezxyz — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js [hunk 1]
```diff
@@ -78,6 +78,7 @@ const ExpandButton = styled(ArrowDown)`
   height: 32px;
   border-radius: 16px;
   ${({ isExpanded }) => isExpanded && 'transform: matrix(1, 0, 0, -1, 0, 0);'}
+  visibility: inherit;
```
Comment (ezxyz) [inline assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js:81]: Can you add a screenshot test?
