### PR TITLE
Generate video posters in parallel to transcoding and uploading

### LINKED ISSUE #6399: Video Optimization: Use ffmpeg to generate poster during upload
## Feature Description

_(split out from #6088)_

This is a fallback solution in case the default method of showing a video preview doesn't work.

Use `ffmpeg` to generate a poster image from the video that can be showed instead of the placeholder.

We show the poster image  with a disabled play button.

Docs: https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video

**Example:**

Screenshot 2021-02-12 at 13 04 02

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

We want to reduce the timeframe we display a placeholder resource while uploading is in progress.

## Summary

This PR enables generating video posters in parallel to transcoding and uploading to improve UX.

## Relevant Technical Choices

* Use FFmpeg to generate video poster during upload
* Improve size of placeholder on canvas and disallow selection

## To-do

In the future, upload this FFmpeg-generated poster image to WordPress if available instead of extracting the poster once again.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6399

### CODE REVIEW

**Comment by spacedmonkey** [comment]
In my tests, I was getting 3.3 second poster generation times and 4 minute video transcode time. That is a very big difference, which is great!

I can so some more testing tomorrow.

File: assets/src/edit-story/app/media/utils/useFFmpeg.js [hunk 1]
```diff
@@ -45,38 +45,123 @@ const isDevelopment = process.env.NODE_ENV === 'development';
...
+      const data = ffmpeg.FS('readFile', tempFileName);
+      return new File(
+        [new Blob([data.buffer], { type: 'image/jpeg' })],
+        outputFileName,
+        {
+          type: 'image/jpeg',
+        }
+      );
+    } catch (err) {
+      trackError('video_transcoding', err.message);
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/utils/useFFmpeg.js]:
```suggestion
      trackError('poster_generation_ffmpeg', err.message);
```

File: assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js [hunk 2]
```diff
@@ -191,7 +191,7 @@ function MultiSelectionMoveable({ selectedElements }) {
       ...selectedElements.map((element) => element.id),
       backgroundElement.id,
     ])
-  ).filter(({ isBackground }) => !isBackground);
+  );
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/multiSelectionMoveable/index.js:194]: Removing this after discussion with @miina 

These are HTML elements/nodes not "our" elements, so they don't have `isBackground` properties.

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js [hunk 3]
```diff
@@ -85,12 +89,59 @@ function useMediaUploadQueue() {
...
   }, [state.queue, replacePlaceholderResource]);
 
+  // Try to get dimensions and poster for placeholder resources.
+  // This way we can show something more meaningful to the user before transcoding has finished.
+  useEffect(() => {
+    async function updateItems() {
+      await Promise.all(
+        state.queue.map(async (item) => {
+          const { id, file, state: itemState, resource } = item;
+          if ('PENDING' !== itemState || !resource.isPlaceholder) {
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js:99]: _Maybe_ change it to this. Needs testing.

```js
          if ('PENDING' !== itemState || resource.poster) {
```

File: assets/src/edit-story/elements/video/icon.js [hunk 4]
```diff
@@ -14,18 +14,28 @@
...
 
+/**
+ * External dependencies
+ */
+import { __ } from '@web-stories-wp/i18n';
+
 /**
  * Internal dependencies
  */
+import { Video } from '../../icons';
```
Comment (miina) [inline assets/src/edit-story/elements/video/icon.js]: Should this use the icon from the new design-system instead?

File: assets/src/edit-story/components/canvas/selection.js [hunk 5]
```diff
@@ -51,6 +51,12 @@ function Selection() {
     return null;
   }
 
+  // No need for displaying non-functional frame for selected background.
+  const isVideoPlaceholder = selectedElements[0]?.resource?.isPlaceholder;
```
Comment (miina) [inline assets/src/edit-story/components/canvas/selection.js:55]: The comment probably needs updating :)

Is this possible to happen for multi-selection as well, or is it always single-selection in case of a placeholder? Currently, it's checking for just the first selected element.

Comment (miina) [reply assets/src/edit-story/components/canvas/selection.js:55]: (Ok, seeing now that it can only be in the single selection)

Comment (miina) [reply assets/src/edit-story/components/canvas/selection.js:55]: Should the video placeholder be removed from the `otherNodes` as well from the elements that can be snapped to for `useSnapping` ?

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/selection.js:55]: Hmm good question. Since the dimensions are the same as the canvas, perhaps it doesn't really make a difference?

**Comment by spacedmonkey** [comment]
https://user-images.githubusercontent.com/237508/110940754-4ccae900-832f-11eb-86e8-ab0229f96be9.mov

I am seeing a weird behaviour where poster is clearly generated by not displayed. Still seeing grey placeholder. Is the element is not updated?

**Comment by spacedmonkey** [comment]
https://user-images.githubusercontent.com/237508/110944344-3e330080-8334-11eb-801b-a95224d2723b.mov

More testing, it is weirder behaviour on drag into media library, see video

**Comment by swissspidy** [comment]
> I am seeing a weird behaviour where poster is clearly generated by not displayed. Still seeing grey placeholder. Is the element is not updated?

The issue is that there's a poster, but no video `src`. Unfortunately in this case the browser does not (reliably) display the poster as a fallback, just a gray placeholder.

> More testing, it is weirder behaviour on drag into media library, see video

Probably the same issue.

**Comment by spacedmonkey** [comment]
Could we change these bits of code.
 
https://github.com/google/web-stories-wp/blob/e42c3033f0f4db8f433540013f62bb2af393b8f3/assets/src/edit-story/elements/video/display.js#L87-L95

https://github.com/google/web-stories-wp/blob/b08951852ecfe21d19cc4838c05d1b41d7c307f8/assets/src/edit-story/elements/media/edit.js#L227-L230

https://github.com/google/web-stories-wp/blob/b08951852ecfe21d19cc4838c05d1b41d7c307f8/assets/src/edit-story/elements/media/edit.js#L235-L239

To render a image instead of a video tag if the url is empty. Similar to how we generate an image in the media library until you hover over the video and changed to video tag.

**Comment by swissspidy** [comment]
> Could we change these bits of code.
> To render a image instead of a video tag if the url is empty. Similar to how we generate an image in the media library until you hover over the video and changed to video tag.

Way ahead of you :-) the answer is yes.

**Comment by swissspidy** [comment]
@spacedmonkey ^ that bot message is for you

**Comment by spacedmonkey** [comment]
@googlebot I consent.

File: assets/src/edit-story/elements/media/edit.js [hunk 6]
```diff
@@ -224,11 +225,18 @@ function MediaEdit({ element, box }) {
           srcSet={calculateSrcSet(resource)}
         />
       )}
-      {isVideo && (
+      {isVideo && resource.src && (
         <FadedVideo {...fadedMediaProps}>
           <source src={resource.src} type={resource.mimeType} />
         </FadedVideo>
       )}
+      {isVideo && !resource.src && (
```
Comment (spacedmonkey) [inline assets/src/edit-story/elements/media/edit.js]:
```suggestion
      {isVideo && !resource.src && resource.poster && (
```

You also need to check the poster is set here. Otherwise, you get an invalid image tag. If poster also not set, should we put the placeholder grey in?

**Comment by spacedmonkey** [comment]
Screenshot 2021-03-15 at 15 12 02
I was seeing invalid image tags if poster has not generated yet.

**Comment by spacedmonkey** [comment]
```
 {isVideo && (
            <CropVideo {...cropMediaProps}>
              <source src={resource.src} type={resource.mimeType} />
            </CropVideo>
          )}
```

I believe we also need to tweak these line as well.

File: assets/src/edit-story/elements/video/display.js [hunk 7]
```diff
@@ -84,7 +84,7 @@ function VideoDisplay({ previewMode, box: { width, height }, element }) {
       showPlaceholder
       previewMode={previewMode}
     >
-      {previewMode ? (
+      {previewMode || !resource.src ? (
```
Comment (spacedmonkey) [inline assets/src/edit-story/elements/video/display.js]: What if poster is not set yet? Should we put a placeholder?

File: assets/src/edit-story/app/media/utils/useFFmpeg.js [hunk 8]
```diff
@@ -45,38 +45,123 @@ const isDevelopment = process.env.NODE_ENV === 'development';
...
+      const ffmpeg = await getFFmpegInstance(file);
+
+      const tempFileName = uuidv4() + '.jpeg';
+      const outputFileName = getFileName(file) + '.jpeg';
+
+      await ffmpeg.run(
+        // Desired position.
+        // Using as an input option (before -i) saves us some time by seeking to position.
+        '-ss',
+        '00:00:01.000',
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useFFmpeg.js:114]: Should this time match, [this](https://github.com/google/web-stories-wp/blob/ffe309081f0f58c44dac47b856c9e15149e3ba5a/assets/src/edit-story/app/media/utils/getFirstFrameOfVideo.js#L40-L46), so that a poster image would not change.

Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useFFmpeg.js:114]: Both FFmpeg and browsers will only take it as a hint and might adjust the number. Anything around the 1s mark is OK, so no need for changing.

**Comment by swissspidy** [comment]
> I was seeing invalid image tags if poster has not generated yet.

@spacedmonkey can you upload the original video file here for testing? thanks.

**Comment by spacedmonkey** [comment]
>  can you upload the original video file here for testing? thanks.

this happened with every video I tested with, including the one I already sent to you on slack

**Comment by spacedmonkey** [comment]
There is a weird regression that I can't workout. If the file is a playable file, like an mp4, it is now not play about. 

Before ( it works fine ) 

https://user-images.githubusercontent.com/237508/111195033-b9eeb080-85b3-11eb-9f36-a977d75a9f2a.mov

After ( does work )

https://user-images.githubusercontent.com/237508/111195144-dc80c980-85b3-11eb-8909-e1b67040b904.mov

I am guessing this is a bug and not by design. 

Original video can be found [here](https://archive.org/download/5-mar-2021-video-1-1-1/5Mar2021%20Video-1%281%29-1.mp4).

**Comment by spacedmonkey** [comment]
I also found this issue in main while looking at this PR. https://github.com/google/web-stories-wp/issues/6776

**Comment by spacedmonkey** [comment]
This PR is now acting as I would expect and the UX Is sooo much better than it was. I am happy to approve as is. I would really like to see some test of some kind here, what test coverage can we add here?

**Comment by spacedmonkey** [comment]
Found another weird bug. 

If you can a transcoding video into a background, I get a grey background.

Screenshot 2021-03-16 at 10 32 05

**Comment by miina** [comment]
Should drop-targeting perhaps be disabled for the time of transcoding -- both as a target and the source?

**Comment by miina** [comment]
Two more notes:
- Mb not related to this PR: Currently, when uploading a larger file via dropping, it seems to take the original width/height directly. Should we limit these to the width/height of the Page? E.g. ended up with these W and H, the selection line wasn't visible at all due to the huge size which was a bit confusing:
Screenshot 2021-03-16 at 16 13 20
- Maybe it would be good to add something like "Saving is disabled during the process" here, too:
Screenshot 2021-03-16 at 16 06 12

**Comment by swissspidy** [comment]
> * Mb not related to this PR: Currently, when uploading a larger file via dropping, it seems to take the original width/height directly. Should we limit these to the width/height of the Page? E.g. ended up with these W and H, the selection line wasn't visible at all due to the huge size which was a bit confusing:
> 
> Screenshot 2021-03-16 at 16 13 20

Yeah I think it was different in 1.4.0 or so, before we started work on video optimization. The inserted elements seemed smaller there. But not sure where/how that changed 😕  Any inputs welcome

> - Maybe it would be good to add something like "Saving is disabled during the process" here, too:
> Screenshot 2021-03-16 at 16 06 12

I added a note about this in #6717 to get UX feedback, but might need a separate ticket.

File: packages/tracking/src/enableTracking.js [hunk 9]
```diff
@@ -45,9 +45,14 @@ async function loadTrackingScript(sendPageView = true) {
...
 
-  await loadScriptTag(
-    `https://www.googletagmanager.com/gtag/js?id=${config.trackingId}&l=${DATA_LAYER}`
-  );
+  try {
+    await loadScriptTag(
+      `https://www.googletagmanager.com/gtag/js?id=${config.trackingId}&l=${DATA_LAYER}`
+    );
+  } catch {
+    // Loading was not possible, probably because of an ad blocker.
```
Comment (swissspidy) [inline packages/tracking/src/enableTracking.js:53]: Not related to media, but fixed an issue I was seeing while testing in Firefox.

**Comment by spacedmonkey** [comment]
There seems to be two outstanding issues. 

1. https://github.com/google/web-stories-wp/pull/6738#issuecomment-800144746 
2. https://github.com/google/web-stories-wp/pull/6738#issuecomment-800288792

I believe that 1 should handled in this PR as it should be simple enough to fix. 
However, I believe that 2 should be handled in a different PR / ticket

**Comment by swissspidy** [comment]
> There seems to be two outstanding issues.
> 
> 1. [#6738 (comment)](https://github.com/google/web-stories-wp/pull/6738#issuecomment-800144746)
> 2. [#6738 (comment)](https://github.com/google/web-stories-wp/pull/6738#issuecomment-800288792)
> 
> I believe that 1 should handled in this PR as it should be simple enough to fix.
> However, I believe that 2 should be handled in a different PR / ticket

1) is setting a video as the page background you mean? Might be complex enough to warrant its own ticket

**Comment by spacedmonkey** [comment]
> is setting a video as the page background you mean? Might be complex enough to warrant its own ticket

@miina Can you advise how hard you think this might be / how it will be done?

**Comment by miina** [comment]
> setting a video as the page background you mean? Might be complex enough to warrant its own ticket

> @miina Can you advise how hard you think this might be / how it will be done?

It seems to be generally an issue with drop-targeting and not related to the background specifically. It might be quite simple fix -- it's possible that[ `combineElements` ](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js)is not bringing along the `isPlaceholder` (or some other necessary atts). If that's the case, it's about just ensuring that `combineElements` takes the necessary values from the transcoding video element.

**Review by spacedmonkey — APPROVED** [review]
As these two maining issues  are related / will be fixed in other tickets. I am going to approve.

**Comment by swissspidy** [comment]
> Found another weird bug.
> 
> If you can a transcoding video into a background, I get a grey background.
> 
> Screenshot 2021-03-16 at 10 32 05

I was able to fix this in the last couple of commits.

What happened is this:

1. You upload a video that needs to be transcoded
2. Placeholder is added to page, cannot be selected or moved
3. Transcoding is finished, now there is a poster image, but not video yet
4. You drop video to page background
5. `onDropHandler` tries to play the video on drop, but there is no video to play, just the poster!

This caused this gray background.

Fixed this by not trying to play the video.
