### PR TITLE
Dashboard: Now with Poster Images and Faster Content Rendering

### LINKED ISSUE #5147: Improve story preview performance on the dashboard
## Bug Description

Improve story preview performance on the dashboard. There are multiple images of a story being loaded on page load.

## Related topic

https://wordpress.org/support/topic/loading-images-all-the-time-in-the-dashboard/#post-13622589

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Part of performance sprint. 

## Summary

The Dashboard was loading the entire story for each of a user's stories. THIS IS SO MUCH TO RENDER. 
Swapping it out for poster images. This makes the presentation consistent with the block view in posts and helps allows us to avoid rendering a gluttony of nodes. 

Downside is on hover you don't get to "preview" any animation or see the story, feel like this is a fine trade off. If we feel like that's being missed by users we can either add a story detail view (like the templates) or find a way to draw attention to the preview button in the context menus. 

## Further ideas for improvement
- Possibly use `srcset` for poster images 
- There's gotta be a way to kill the `usePageView` that's running on resize to calculate the grid size if we can just make the images use `aspect-ratio` or something, i'm not sure this is a massive win. 
- I'm curious if there's more we can do for first paint, as this focuses on additional renders in the dashboard. 

## Relevant Technical Choices

- Cut the rendering time of StoryGridView from 8.6ms (Main) to 2.7ms (or 1.4ms on various runs) (This Branch) when throttled to use Slow 3G network connection. 
- Cut out an entire extra fetch of stories when toggling between Grid and List views, there's no need to go get that data again. That saves us about 0.8ms render time in slow 3G network connections 

| Updated & Slow 3G | Main No Throttle | Main 3G Slow | 
| --- | --- | --- |
| Screen Shot 2021-07-13 at 11 55 51 AM | Screen Shot 2021-07-13 at 10 35 15 AM | Screen Shot 2021-07-13 at 10 43 51 AM |

- I pulled apart the Story Grid components a little bit so that they could be smaller and we could memoize some of the data, like the context menus. This doesn't do a lot, but i think it makes sense and really doesn't hurt. The directory structure here was out of date anyways since these grids aren' "shared". 
- Since this grid is no longer shared with templates (which still have to use the amp structure and all the providers) I gutted the unnecessary parts of the layout so we're not rendering excess DOM nodes for each grid item. 
- Added a new height to the `usePageView` hook so that we can get poster images rendered as `3:4`. 

## To-do

- [x] Make sure I didn't kill the templates views 
- [x] Clean up the list view with same changes 
- [x] Fix what I broke on the grid focus trap
- [x] Organize analytics of perf improvements 
- [x] Organize further improvements 
- [x] Updates to tests

## User-facing changes

- Dashboard loads story posters instead of story previews - new ratio of 3:4 
- A11y update to grid navigation, which I think is more straight forward. There's nothing on the story poster to interact with that isn't already in the context menu. Now, navigating the grid, because there's no 'active preview mode' to deal with we can just use a list and arrow through the context menus and get all the info we need. 
Screen Shot 2021-07-13 at 11 49 56 AM

## Testing Instructions

Verify that the dashboard still works as expected with a mouse
Verify the above a11y keyboard nav changes - should be way less complicated now. 
Make sure that the templates view and list views work. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5147

### CODE REVIEW

File: assets/src/dashboard/app/views/myStories/content/index.js [hunk 1]
```diff
@@ -31,7 +30,6 @@ import {
 /**
  * Internal dependencies
  */
-import { TransformProvider } from '../../../../../edit-story/components/transform';
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/myStories/content/index.js:34]: I particularly love getting rid of this dependency on `edit-story` 🎉

Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: I'm not sure yet what to do about templates, but this will at least help with my stories.

**Comment by swissspidy** [comment]
We should probably do that for animations too

File: assets/src/dashboard/app/views/myStories/content/index.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: We should probably do that for templates too. We could host the preview images on the CDN.

**Comment by BrittanyIRL** [comment]
> We should probably do that for templates too

swap to images or gut the `TransformProvider`? 

Either way, we should do templates separately to avoid this from getting massive. Doing grid and list story views at once is already quite large.

**Comment by swissspidy** [comment]
> > We should probably do that for templates too
> 
> swap to images or gut the `TransformProvider`?
> 
> Either way, we should do templates separately to avoid this from getting massive. Doing grid and list story views at once is already quite large.

Both :-) But yeah absolutely a separate PR. Related ticket: #7985

File: assets/src/dashboard/app/views/myStories/content/listView/index.js [hunk 2]
```diff
@@ -56,36 +55,30 @@ import {
...
   SORT_DIRECTION,
   STORY_SORT_OPTIONS,
   STORY_STATUS,
   STORY_PREVIEW_WIDTH,
   VIEWPORT_BREAKPOINT,
-} from '../../../constants';
-import {
-  PreviewPage,
-  PreviewErrorBoundary,
-} from '../../../../edit-story/components/previewPage';
```
Comment (spacedmonkey) [inline assets/src/dashboard/app/views/myStories/content/listView/index.js:71]: Removed another dependency!

File: assets/src/dashboard/app/views/myStories/content/index.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: It's a matter of how we're generating the preview images, since the related image rendering for thumbnails is still being researched.

File: assets/src/dashboard/app/views/myStories/content/stories/index.js [hunk 3]
```diff
@@ -77,9 +77,18 @@ const storyActions = {
   updateStory: action('update story clicked'),
 };
 
-const longerListOfStories = formattedStoriesArray
-  .concat(formattedStoriesArray)
-  .concat(formattedStoriesArray);
+// Prevents storybook from shouting a bunch of console warnings about duplicate ids
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/myStories/content/stories/index.js:80]: just silencing some storybook warnings

File: assets/src/dashboard/components/cardGrid/index.js [hunk 4]
```diff
@@ -65,7 +65,9 @@ const CardGrid = forwardRef(function CardGrid(
       tabIndex={0}
       aria-label={ariaLabel}
       columnWidth={pageSize.width}
-      columnHeight={pageSize.containerHeight}
+      columnHeight={
```
Comment (BrittanyIRL) [inline assets/src/dashboard/components/cardGrid/index.js:68]: kinda gross but this lets the height get set based on what the ratio should be, since templates are sharing this and they need the story ratio. Story poster images are a 3 : 4 ratio and stories are a 2 : 3.

File: assets/src/dashboard/components/cardGridItem/stories/index.js [hunk 5]
```diff
@@ -67,6 +67,7 @@ export const _default = () => {
           onEditCancel={() => {}}
           onEditComplete={() => {}}
           tabIndex={0}
+          id="8787"
```
Comment (BrittanyIRL) [inline assets/src/dashboard/components/cardGridItem/stories/index.js:70]: more storybook warnings i got tired of seeing

File: assets/src/dashboard/components/cardGridItem/storyCardPreview.js [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+const getActionAttributes = (targetAction) =>
+  typeof targetAction === 'string'
+    ? {
+        href: resolveRoute(targetAction),
+        isLink: true,
+        as: 'a',
+      }
+    : { onClick: targetAction };
+
+const StoryCardPreview = ({
```
Comment (BrittanyIRL) [inline assets/src/dashboard/components/cardGridItem/storyCardPreview.js:79]: this became different enough from the shared `CardPreview` that I moved it to its own version.  Cleaned out everything that we have moved away from on the hover/focus of the card image too.

File: assets/src/dashboard/components/scrollToTop/index.js [hunk 7]
```diff
@@ -78,7 +78,7 @@ const ScrollToTop = () => {
 
   return (
     <StyledButton
-      aria-hidden={isVisible}
+      aria-hidden={!isVisible}
```
Comment (BrittanyIRL) [inline assets/src/dashboard/components/scrollToTop/index.js:81]: should hide when it's not visible

File: assets/src/dashboard/components/storyMenu/index.js [hunk 8]
```diff
@@ -74,27 +73,31 @@ MenuContainer.propTypes = {
 export default function StoryMenu({
   contextMenuId,
   onMoreButtonSelected,
-  story,
```
Comment (BrittanyIRL) [inline assets/src/dashboard/components/storyMenu/index.js:77]: only the story id is getting used ever, no need to pass the entire story in

File: packages/design-system/src/theme/colors.js [hunk 9]
```diff
@@ -101,7 +101,8 @@ const standard = {
 };
 
 const gradient = {
-  loading: `linear-gradient(270deg, #4285f4 0%, #0f0bc8 57%, #4285f4 110%)`,
+  loading: 'linear-gradient(270deg, #4285f4 0%, #0f0bc8 57%, #4285f4 110%)',
+  placeholder: 'linear-gradient(180deg, #fff0, #000c)',
```
Comment (BrittanyIRL) [inline packages/design-system/src/theme/colors.js:105]: stole this from the blocks implementation.

File: assets/src/dashboard/app/views/myStories/content/index.js [hunk 10]
```diff
@@ -65,69 +62,58 @@ function Content({
...
+                size={BUTTON_SIZES.MEDIUM}
+                as="a"
+                href={resolveRoute(APP_ROUTES.TEMPLATES_GALLERY)}
+              >
+                {__('Explore Templates', 'web-stories')}
+              </Button>
+            )}
+          </EmptyContentMessage>
+        )}
+      </StandardViewContentGutter>
```
Comment (maxyinger) [inline assets/src/dashboard/app/views/myStories/content/index.js:116]: 😍

File: assets/src/dashboard/app/views/myStories/content/storyGridView/index.js [hunk 11]
```diff
@@ -94,19 +77,20 @@ const StoryGridView = ({
...
       !activeGridItemId &&
-      returnStoryFocusId.value &&
+      returnStoryFocusId?.value &&
       !activeGridItemIdRef.current
     ) {
       const newFocusId = returnStoryFocusId?.value;
-      itemRefs.current?.[newFocusId]?.children?.[0]?.focus();
+      setActiveGridItemId(newFocusId);
+      // grab the menu button and refocus
+      itemRefs.current?.[newFocusId]?.lastChild?.lastChild?.firstChild?.focus();
```
Comment (maxyinger) [inline assets/src/dashboard/app/views/myStories/content/storyGridView/index.js]: could always just add a classname to the menu button and do something like:
```
itemRefs.current?.[newFocusId]?.querySelector('.story-card-menu-button')?.focus()
```

But I'm fine with this too. just may cause regressions if there's ever any update to the order of dom nodes in the card. that being said, I don't think that order has been changed in like a year and some change so 🤷

File: assets/src/dashboard/app/views/myStories/content/storyGridView/index.js [hunk 12]
```diff
@@ -146,108 +130,52 @@ const StoryGridView = ({
...
-                    menuItemActions: modifiedStoryMenu.menuItemActions,
-                    menuItems: modifiedStoryMenu.menuItems,
-                    story,
-                  })}
-                />
-              </DetailRow>
-            </CardGridItem>
-          );
-        })}
+        {memoizedStoryGrid}
```
Comment (maxyinger) [inline assets/src/dashboard/app/views/myStories/content/storyGridView/index.js:177]: ooolala

File: assets/src/dashboard/app/views/myStories/karma/myStories.karma.js [hunk 13]
```diff
@@ -72,33 +72,20 @@ describe('Grid view', () => {
...
     for (let i = 0; i <= storyIndex; i++) {
-      const expectedStory = storyCards[i];
+      const expectedStory = storyButtons[i];
       // eslint-disable-next-line no-await-in-loop
       await fixture.events.keyboard.press('right');
       expect(expectedStory).toEqual(document.activeElement);
     }
 
-    // we should have focused the indicated story in the grid
+    // // we should have focused the indicated story in the grid
```
Comment (maxyinger) [inline assets/src/dashboard/app/views/myStories/karma/myStories.karma.js]:
```suggestion
    // we should have focused the indicated story in the grid
```

**Review by maxyinger — APPROVED** [review]
Ah so much cleaner and less work going on here. love it.

Awesome PR, Great Job!

File: assets/src/dashboard/app/views/myStories/content/storyGridView/index.js (hunk 11 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridView/index.js]: great idea, got too deep in the weeds - thanks for suggesting

File: assets/src/dashboard/app/views/myStories/content/index.js (hunk 1 above)
Comment (dreamofabear) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: For templates, I imagine poster generation is a matter of flattening/rasterizing the first page after removing [elements that are duplicative with the story preview](https://developers.google.com/search/docs/advanced/appearance/enable-web-stories#google-discover) (i.e. title text/author/publisher logo). For example:

Before:
Screen Shot 2021-07-13 at 3 25 25 PM

After (removed title, author, logo):
Screen Shot 2021-07-13 at 3 25 37 PM

In many cases this might just be the background image of the first page, but some templates have stickers/scrims that may still be desired. I took screenshots of the editor above, but actual posters should be exported from Figma.

/cc @o-fernandez

Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: i suppose if we want to just export this from figma we could do this pretty quickly.

**Comment by BrittanyIRL** [comment]
@choumx I just want to do a sanity check here that it's ok that I'm updating the images in the grid for stories to be a 3:4 ratio instead of a 2:3 ratio. I figure keeping the ratio consistent with what we recommend for poster images in the editor via checklist as well as the ratio used on the block implementation with poster images was the way to go. I just don't want to shock anyone with the grid is a little different. 

Screen Shot 2021-07-13 at 11 49 56 AM

**Comment by BrittanyIRL** [comment]
@littlemilkstudio when you get a chance will you consent to the googlebot, i committed your suggestion.

**Comment by dreamofabear** [comment]
> I just want to do a sanity check here that it's ok that I'm updating the images in the grid for stories to be a 3:4 ratio instead of a 2:3 ratio.

Yup, that's expected.

Not sure if this was planned to be in-scope, but can we render the story title on top of the poster to match the [story preview on Discover/Search](https://developers.google.com/search/docs/advanced/appearance/enable-web-stories)? This would also help reclaim the vertical real estate lost to a taller story preview. 

Note there's also a translucent scrim between the text and the poster. You can see the canonical example by viewing with mobile emulation: https://www.google.com/search?q=things+to+do+in+nyc

Screen Shot 2021-07-13 at 6 08 49 PM

We can refine the display of draft state, last modified date, and other metadata in the future once we get UX support.

**Comment by BrittanyIRL** [comment]
> > I just want to do a sanity check here that it's ok that I'm updating the images in the grid for stories to be a 3:4 ratio instead of a 2:3 ratio.
> 
> Yup, that's expected.
> 
> Not sure if this was planned to be in-scope, but can we render the story title on top of the poster to match the [story preview on Discover/Search](https://developers.google.com/search/docs/advanced/appearance/enable-web-stories)? This would also help reclaim the vertical real estate lost to a taller story preview.
> 
> Note there's also a translucent scrim between the text and the poster. You can see the canonical example by viewing with mobile emulation: https://www.google.com/search?q=things+to+do+in+nyc
> 
> Screen Shot 2021-07-13 at 6 08 49 PM
> 
> We can refine the display of draft state, last modified date, and other metadata in the future once we get UX support.

I'll make a follow up ticket for these! Thank you for the links and specifics, super helpful.

File: assets/src/dashboard/components/cardGridItem/storyCardPreview.js [hunk 14]
```diff
@@ -0,0 +1,129 @@
...
+  return (
+    <CardWrapper>
+      <Poster
+        src={storyImage}
+        alt={sprintf(
+          /* translators: %s: Story title. */
+          __('%s Poster image', 'web-stories'),
+          storyTitle.length > 0 ? storyTitle : __('(no title)', 'web-stories')
+        )}
+        as={!storyImage ? 'div' : 'img'}
```
Comment (swissspidy) [inline assets/src/dashboard/components/cardGridItem/storyCardPreview.js]: Wouldn't this cause the `alt` attribute to be added to a `div`?

Comment (BrittanyIRL) [reply assets/src/dashboard/components/cardGridItem/storyCardPreview.js]: good catch, thanks!

File: assets/src/dashboard/app/views/myStories/content/listView/index.js [hunk 15]
```diff
@@ -347,11 +338,17 @@ export default function StoryListView({
                 data-testid={`story-list-item-${story.id}`}
               >
                 <TablePreviewCell>
-                  <PreviewContainer>
-                    <PreviewErrorBoundary>
-                      <PreviewPage page={story.pages[0]} pageSize={pageSize} />
-                    </PreviewErrorBoundary>
-                  </PreviewContainer>
+                  <PreviewImage
+                    as={!story.featuredMediaUrl ? 'div' : 'img'}
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/myStories/content/listView/index.js]: @BrittanyIRL same thing here with the `div`.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js [hunk 16]
```diff
@@ -0,0 +1,149 @@
...
+    story?.status === STORY_STATUS.DRAFT
+      ? story?.modified_gmt
+      : story?.created_gmt
+  );
+  return (
+    <CustomCardGridItem
+      data-testid={`story-grid-item-${story.id}`}
+      ref={(el) => {
+        itemRefs.current[story.id] = el;
+      }}
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js:94]: 💭 if we default `itemRefs` to be an empty object, then maybe this should use optional chaining since `itemRefs.current` would be `undefined`?
```suggestion
      ref={(el) => {
        itemRefs?.current?.[story.id] = el;
      }}
```

File: assets/src/dashboard/app/views/myStories/content/listView/index.js (hunk 15 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/listView/index.js]: yup, i realized i forgot that, i'll circle back and update this later today. appreciate the eyes

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js [hunk 17]
```diff
@@ -0,0 +1,149 @@
...
+      </DetailRow>
+    </CustomCardGridItem>
+  );
+};
+
+StoryGridItem.propTypes = {
+  bottomActionLabel: PropTypes.string,
+  handleFocus: PropTypes.func,
+  isActive: PropTypes.bool,
+  itemRefs: PropTypes.shape({}),
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js]: 💭 Maybe we could make this type a little more specific since we know this will be a reference to an element type?
```suggestion
  itemRefs: PropTypes.shape({
    current: PropTypes.oneOfType([
        PropTypes.func, 
        PropTypes.shape({ current: PropTypes.instanceOf(Element) })
      ])
  }),
```

File: assets/src/dashboard/app/views/myStories/content/storyGridView/index.js [hunk 18]
```diff
@@ -94,19 +77,22 @@ const StoryGridView = ({
...
-      returnStoryFocusId.value &&
+      returnStoryFocusId?.value &&
       !activeGridItemIdRef.current
     ) {
       const newFocusId = returnStoryFocusId?.value;
-      itemRefs.current?.[newFocusId]?.children?.[0]?.focus();
+      setActiveGridItemId(newFocusId);
+      // grab the menu button and refocus
+      itemRefs.current?.[newFocusId]
+        ?.querySelector('.context-menu-button')
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/content/storyGridView/index.js]: 💭 I'm guessing this class is also used on the button somewhere else. Maybe we should make `context-menu-button` a constant and share it just in case it is changed in the future?

File: assets/src/dashboard/app/views/myStories/karma/myStories.karma.js [hunk 19]
```diff
@@ -326,7 +313,7 @@ describe('Grid view', () => {
   });
 
   describe('CUJ: Creator can view their stories in grid view: Sort their stories (last modified / date created / author / title)', () => {
-    it('should should search/filter using the Search Stories search input', async () => {
+    it('should search/filter using the Search Stories search input', async () => {
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/karma/myStories.karma.js:312]: 🔥

File: assets/src/dashboard/utils/usePagePreviewSize.js [hunk 20]
```diff
@@ -44,15 +44,16 @@ import {
  * This means things like the unitsProvider and displayElements that we import to the Dashboard from the editor
  * It's maintaining a 2:3 aspect ratio.
```
Comment (samwhale) [inline assets/src/dashboard/utils/usePagePreviewSize.js:45]: Is this maintaining the 2:3 ratio still?

**Review by samwhale — APPROVED** [review]
This is great! Left some comments and questions

File: assets/src/dashboard/components/cardGridItem/storyCardPreview.js [hunk 21]
```diff
@@ -0,0 +1,135 @@
...
+                /* translators: %s: Story title. */
+                __('%s Poster image', 'web-stories'),
+                storyTitle.length > 0
+                  ? storyTitle
+                  : __('(no title)', 'web-stories')
+              ),
+              as: 'img',
+            }
+          : { as: 'div' })}
+      />
```
Comment (swissspidy) [inline assets/src/dashboard/components/cardGridItem/storyCardPreview.js:101]: Might be more readable to just write

```jsx
{!storyImage && <Poster />}
{storyImage && <Poster src={storyImage} alt={..} />}
```

Although not sure the extra div is needed when there's no poster. In the block we used `::before` on the parent to add the gradient overlay.

**Comment by maxyinger** [comment]
@googlebot I consent.

File: assets/src/dashboard/components/cardGridItem/storyCardPreview.js (hunk 21 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/components/cardGridItem/storyCardPreview.js:101]: Kinda need the `div` atm for how the grid is displayed, will reassess when working on the follow up here #8325 - we might be able to get away from some of the rigid grid implementation with that.

File: assets/src/dashboard/utils/usePagePreviewSize.js (hunk 20 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/utils/usePagePreviewSize.js:45]: you're right, this is confusing now. updated for better context. hopefully we can ditch the 2:3 and fullBleedHeight here soon.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js (hunk 17 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js]: thank you great idea!

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js (hunk 16 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/index.js:94]: ~doesn't hurt - this structure's been here for a while now, i'll reinforce it though. thanks!~

Actually, no because this is assigning so we don't want to do optional chaining.  this will always be ok because itemRefs.current exists here as the ref's already established and no story without an id is getting rendered thanks to the serializer earlier. 

`Invalid left-hand side in assignment expression.`

File: assets/src/dashboard/app/views/myStories/content/storyGridView/index.js (hunk 18 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridView/index.js]: made it a constant :)

File: assets/src/dashboard/app/views/myStories/content/index.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/index.js:34]: @choumx @swissspidy following up on this, should we just export from figma and add asset paths to the templates for poster images and use those here or should we put a pin in this until later when we deal with text sets and page layouts?
