### PR TITLE
Hotlinking: Allow Link icon to be hotlinked

### LINKED ISSUE #11777: Hotlinking: Allow Link icon to be hotlinked
## Feature Description

Allow Link icon to be hotlinked.

### LINKED ISSUE #11847: Page Attachment: Link icon not displayed on canvas
## Bug Description
The link icon is not displaying on the canvas besides the Call to Action (page attachment). Note that it renders when previewing the [story](https://testsite.cmsdevrel.com/web-stories/1442/). 

## Expected Behaviour

The link icon should pull through and display on the page attachment. 

## Steps to Reproduce

1. Add Call to Action to page (https://www.wikipedia.org)
2. See link icon load
3. Note the image logo does not pull through beside the Learn More text.

## Screenshots

Screen Shot 2022-06-30 at 11 05 31 AM

Screen Shot 2022-06-30 at 11 05 20 AM

## Additional Context

Related Support topic: https://wordpress.org/support/topic/link-fetching-icon-not-working/

- Plugin Version: 1.22.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

### LINKED ISSUE #11848: Links: Icon displays as broken image on the element
## Bug Description

The link icon displays as a broken site icon on the element it was applied to. 

## Expected Behaviour

The link icon should render the image on the element. 

## Steps to Reproduce

1. Add element to the page
2. Add a link to the element
3. See the icon image on the panel but on hover of the element the icon image is broken

## Screenshots

Screen Shot 2022-06-30 at 11 06 57 AM

## Additional Context

- Plugin Version: 1.22.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Allow Link icon to be hotlinked.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Enable icon hotlink experiment. 
2. Create a story. 
3. Select page. 
4. Change to style tab.
5. Add url to call to action url input. 
6. After icon option appears, click on pencil icon. 
7. Click on link to file. 
8. Use this URL - https://images.unsplash.com/photo-1656523267493-31b9b2cfdc47?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=96&q=60&h=96
9. See icon appear. 

###  Element Icon visible

1. Add element to the page
2. Add a link to the element
3. See the icon image on the panel and on hover of the element.

### Page attachment

1. Add Call to Action to page (https://www.wikipedia.org)
2. See link icon load
3. Note the image logo does pull through beside the Learn More text.

 

Please test other urls, see if they error because of incorrect size. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11777 
Fixes #11847
Fixes #11848

### CODE REVIEW

File: packages/story-editor/src/components/form/linkIcon.js [hunk 1]
```diff
@@ -36,6 +37,7 @@ const StyledMedia = styled(Media)`
 `;
 
 function LinkIcon({ handleChange, icon, isLoading = false, ...rest }) {
+  const enablePosterHotlinking = useFeature('posterHotlinking');
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/form/linkIcon.js]: @swissspidy Do we need a new feature flag here as well?

Comment (swissspidy) [reply packages/story-editor/src/components/form/linkIcon.js]: Yes, I prefer separate feature flags for all of these so that we can roll them out separately if needed.

File: packages/story-editor/src/components/canvas/pageAttachment/index.js [hunk 2]
```diff
@@ -110,15 +110,12 @@ const Tooltip = styled.div`
...
+const LinkImage = styled.img`
   height: 24px;
   width: 24px;
   vertical-align: middle;
-  background-size: cover;
-  background-repeat: no-repeat;
-  background-position: 50%;
   border-radius: 50%;
-  background-image: url('${({ icon }) => icon}') !important;
+  border: 0 none;
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/canvas/pageAttachment/index.js:118]:
```suggestion
  border: 0 none;
  object-fit: contain;
```

File: packages/story-editor/src/components/canvas/pageAttachment/index.js [hunk 3]
```diff
@@ -155,7 +153,12 @@ function PageAttachment({ pageAttachment = {} }) {
             <ArrowBar fill={bgColor} />
             <OutlinkChip bgColor={bgColor} $factor={dataToEditorY}>
               {icon ? (
-                <LinkImage icon={icon} />
+                <LinkImage
+                  src={icon}
+                  alt={__('Attachment Icon', 'web-stories')}
```
Comment (swissspidy) [inline packages/story-editor/src/components/canvas/pageAttachment/index.js]:
```suggestion
                  alt={__('Site Icon', 'web-stories')}
```

For consistency

**Review by swissspidy — COMMENTED** [review]
Works like a charm!

**Comment by swissspidy** [comment]
The QA instructions don't seem to cover #11847 and #11848

**Review by swissspidy — APPROVED** [review]
