### PR TITLE
Load newly uploaded videos without a delay

### LINKED ISSUE #1126: Poster image not displayed / jumps in.
## Bug Description

After video preview completes update, the poster image disappears and is replaced after a couple of seconds with a real poster image from WP. 

## Expected Behaviour

This should not be soo jumpy and the poster image replacement should happen seamlessly. 

## Screenshots

https://youtu.be/nEWXcRzzdbo

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

Tracks newly uploaded video and loads that without a delay.

## Testing Instructions

Upload a new video by dragging it to the Page and verify that its loaded without a delay in the library after the uploading has finished.

See the expected before and after [here](https://github.com/google/web-stories-wp/pull/4395#issuecomment-689360386).

---

Fixes #1126

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 1]
```diff
@@ -370,10 +381,13 @@ function getInnerElement(
     onClick,
     showVideoDetail,
     dropTargetsBindings,
+    newVideoRef,
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Could this be turned into an actual component rather than "just" a function? And maybe moved to a separate file?

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 2]
```diff
@@ -388,24 +402,26 @@ function getInnerElement(
...
         loading={'lazy'}
         onClick={onClick(thumbnailURL)}
-        onLoad={makeImageVisible}
+        onLoad={makeMediaVisible}
         {...dropTargetsBindings(thumbnailURL)}
       />
     );
   } else if (type === 'video') {
     const { lengthFormatted, poster, mimeType } = resource;
+    const displayPoster = poster ? poster : newVideoRef.current;
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Hm, I feel like the video is playing for a split-second before the poster is generated and the static image takes over? Or maybe the issue is, that when the poster is generated, the video stops playing even though it shouldn't?

At least the result is: When I drag a video straight from my desktop to the canvas, the video plays for a short while (a few seconds) and then stops playing. Shouldn't it either not play at all or keep playing?

**Review by barklund — COMMENTED** [review]
A few comments - and if you could refactor this monster file even slightly smaller, it would be awesome!

**Comment by diegovar** [comment]
Could you perhaps add a video of the behaviour before and after? I'm not sure I understand what this change looks like

**Comment by miina** [comment]
@diegovar Sure!
Before:
before


Now:
now

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Hmm, I'm actually not seeing this -- the video doesn't have `autoplay` set and the default value is `false`. It starts playing on hovering though -- could it be that it happens when you're hovering over the uploaded video at the same time?

Comment (merapi) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: I observe the same thing as @barklund (but I think it's not this PR fault, it happens also on main?)

You need a long but small in size video like [this one](https://xwp.slack.com/files/USWHNEUHH/F016TR9SN7K/timecode.mp4).
When dropped it auto-plays (like it should, right?) but it stops (resets) when the poster is generated/replaced.

Now I can also see it on your gif, the video is 10s but it stops after ~4s?

Comment (miina) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Ah, okay, now I see, you mean the dropped video on the Page plays, I thought that the video in the library started playing for some reason when you tested...

This seems to happen in main as well, yes, we can create a separate issue if it needs a fix.

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Changed in 28714f906386bfcdf7971350b5f344b91b637eb7, PTAL

File: assets/src/edit-story/elements/text/display.js [hunk 3]
```diff
@@ -46,10 +46,8 @@ const HighlightWrapperElement = styled.div`
   ${elementFillContent}
   ${elementWithFont}
   ${elementWithTextParagraphStyle}
-  line-height: ${({
-    lineHeight,
-    verticalPadding,
-  }) => getHighlightLineheight(lineHeight, verticalPadding)};
+  line-height: ${({ lineHeight, verticalPadding }) =>
```
Comment (miina) [inline assets/src/edit-story/elements/text/display.js]: Note: this is just a linter fix.

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Alright, nothing to do with this one, then. Please file a new issue and close let's get on with this one :)

File: assets/src/edit-story/components/library/panes/media/common/InnerElement.js [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+  letter-spacing: ${({ theme }) => theme.fonts.duration.letterSpacing};
+  padding: 0 6px;
+  border-radius: 10px;
+`;
+
+const HiddenPosterImage = styled.img`
+  display: none;
+`;
+
+function InnerElement({
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/common/InnerElement.js]: It seems this file is named `InnerElement.js` with a capital `I`. It should be a lowercase first letter in filenames.

**Review by barklund — APPROVED** [review]
Looks great - just needs a file renaming.

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 5]
```diff
@@ -154,6 +118,14 @@ const MediaElement = ({
...
   } = resource;
 
+  const newVideoRef = useRef(null);
+
+  useEffect(() => {
+    if (resource.poster && resource.poster.includes('blob')) {
+      newVideoRef.current = resource.poster;
+    }
+  }, [resource.poster]);
+
```
Comment (diegovar) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: Shouldn't this go in innerElement?

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 6]
```diff
@@ -154,6 +118,14 @@ const MediaElement = ({
     alt,
   } = resource;
 
+  const newVideoRef = useRef(null);
```
Comment (diegovar) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js]: should this be called newVideoPosterRef?

**Review by diegovar — COMMENTED** [review]
Personal preference: I would've preferred the refactor to be in a separate PR as now this PR is harder to review.
