### PR TITLE
Prepublish Text Contrast Check

### LINKED ISSUE #5380: Prepublish checklist is missing a text contrast check
## Bug Description

 In this page, I don’t get any text contrast issues in the checklist even though you can’t read the text. (there’s black text on top of the gray at the top left)

Screen Shot 2020-11-20 at 4 21 34 PM source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13581#page=%25225c4f2f9d-21ea-4ffa-a45d-f0707fa3da0f%2522

Funny enough, this triggers the text contrast check issue. So it seems that we are only checking within a specific element, not an element on top of another element, but not sure this merits the low contrast error. 

Screen Shot 2020-11-20 at 4 27 54 PM
source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13581#page=%25226357900a-5dca-42db-be57-01e066ca78f3%2522

## Expected Behaviour

Error message should be presented in this case

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Summary
I added a text contrast check which checks the contrast/readability between the color palette provided by the part of the background image the text is sitting on and the text color. 

Here's it working: 

ezgif-7-d5fa3b5f26af

## Relevant Technical Choices
- add an async calls section to `getPrepublishErrors` so I can use promises to put stuff on the DOM. Update the tests and implementations of `getPrepublishErrors` so it's async.
- Move the layout provider up to `app` so that prepublish can use the page size, important for getting data from the background images
- add helper functions and a text contrast check to `accessibility` in `prepublish` to do background image contrast checking. The helper functions create images based on text placement on the background, and also get the color palettes of the image to compare its luminosity to the font color. Then the colors are compared for contrast issues using the `contrastUtils`. They also help clean up the DOM after the calculations are made.
- refactored `getMediaBaseColor` module a bit to allow custom `onload` so I wasn't duplicating code in `accessibility`

## To-do

- [x] fix CORS issue, thanks Max and Pascal. 🙏
- [x] generalize for other layers (shapes, images, etc.) in between the text and bg image
- [x] generalize for different editor scales
- [x] refactor checklist run for async calls

## User-facing changes
When a user adds a background image to the page and places text on it, it should show a warning if the contrast is too low between the text and the image where the text sits. Same with shapes.

## Testing Instructions
1. Create a new story
2. Add a background image
3. Add text to the page
4. Place the text where it is hard to see, or change the color of the text to match the colors of the image
5. A warning should show in the prepublish checklist that the text contrast is too low
6. Repeat with a shape as a layer behind the text
7. Repeat with an image as a layer behind the text (it can be masked, rotated, flipped or not)

---

Fixes #5380

### CODE REVIEW

File: assets/src/edit-story/utils/getMediaBaseColor.js [hunk 1]
```diff
@@ -31,43 +31,68 @@ const STYLES = {
...
-      reject(new Error('Base color image error: ' + e.message));
+      reject(new Error('Set image error: ' + e.message));
     };
-    img.width = 10;
-    img.height = 'auto';
+    img.width = width;
+    img.height = height;
     img.src = src;
     imgNode.appendChild(img);
   });
```
Comment (swissspidy) [inline assets/src/edit-story/utils/getMediaBaseColor.js]: Instead of passing callbacks like this, why not rely on promises all the way:

```js
export function setOrCreateImage(imageData) {
  const { src, id, height, width } = imageData;
  return new Promise((resolve, reject) => {
    // ...

    const img = new Image();
    img.addEventListener('load', () => resolve(img));
    img.addEventListener('error', (err) => reject(err));

    // ...
  });
}

// ...

export function getMediaBaseColor(resource, onBaseColor) {
  const { type, src, poster } = resource;
  setOrCreateImage({
    src: type === 'video' ? poster : src,
    width: 10,
    height: 'auto',
  }).then(
    (img) => onBaseColor(thief.getColor(img),
    () => onBaseColor([255, 255, 255]) // Fallback color is white.
  );
}

```

File: assets/src/edit-story/app/prepublish/warning/accessibility.js [hunk 2]
```diff
@@ -95,6 +160,112 @@ export function textElementFontLowContrast(element) {
...
+/**
+ * Check story for a background image and text elements.
+ * Check the luminosity of the dominant color of the background image part where the text element is.
+ * Check the contrast of that luminosity against the luminosity of the text color.
+ * If the contrast is too low, return guidance. Otherwise return undefined.
+ *
+ * @param {Page} page
+ * @return {Guidance|undefined} The guidance object for consumption
+ */
+
```
Comment (swissspidy) [inline assets/src/edit-story/app/prepublish/warning/accessibility.js]: Errant space

File: assets/src/edit-story/app/prepublish/getPrepublishErrors.js [hunk 3]
```diff
@@ -120,7 +120,54 @@ function getPrepublishErrors(story) {
...
     })
     .flat();
-  return checklistResult;
+
+  const asyncResult = await getPrepublishErrorsAsync(story);
+
+  return [...checklistResult, ...asyncResult];
+}
+
+async function getPrepublishErrorsAsync(story) {
```
Comment (swissspidy) [inline assets/src/edit-story/app/prepublish/getPrepublishErrors.js]: At first glance I find it a bit odd to have `getPrepublishErrors()` and `getPrepublishErrorsAsync()`, and `warnings and `asyncWarnings`. Especcially since the former two are both `async` functions. Doesn't seem like a very dev-friendly API. Can't everything be async and unified in 1 place?

File: assets/src/edit-story/app/index.js [hunk 4]
```diff
@@ -70,16 +70,18 @@ function App({ config }) {
...
-                                  <DevTools />
-                                  <DefaultMoveableGlobalStyle />
-                                  <CropMoveableGlobalStyle />
-                                  <ModalGlobalStyle />
-                                  <CalendarStyle />
-                                  <KeyboardOnlyOutlines />
-                                  <Layout />
-                                </PrepublishChecklistProvider>
+                                <LayoutProvider>
+                                  <PrepublishChecklistProvider>
```
Comment (swissspidy) [inline assets/src/edit-story/app/index.js]: This begs the question: why is `PrepublishChecklistProvider` defined up here, and not for example within `Workspace` (`assets/src/edit-story/components/workspace/index.js`)?

Comment (embarks) [reply assets/src/edit-story/app/index.js]: I'll move it.

File: assets/src/edit-story/app/prepublish/getPrepublishErrors.js (hunk 3 above)
Comment (embarks) [reply assets/src/edit-story/app/prepublish/getPrepublishErrors.js]: I can refactor, I was working on the image stuff for a long time so I wanted to be able to follow the flow without getting myself confused.

Comment (embarks) [reply assets/src/edit-story/app/prepublish/getPrepublishErrors.js]: The main thing was I didn't want to rewrite the reduce or change the data structures. But spreading the guidance message doesn't let me resolve promises with `promise.all` very easily.

Comment (embarks) [reply assets/src/edit-story/app/prepublish/getPrepublishErrors.js]: I think what's there now is much better :) thank you

**Comment by swissspidy** [comment]
I asked for some clarification of the scope of this at https://github.com/google/web-stories-wp/issues/5380#issuecomment-740662360:

> text contrast should check the text color vs. the text surrounding color, be it a bg image colors, text fill/highlight color, shapes colors, etc.

So this needs way more than a check against the bg image's base color, and would greatly benefit from a technical design doc/brief, taking into account all the previous work on this area, as well as the potential applications of this architecture (carousel previews, eyedropper, contrast check)

**Comment by embarks** [comment]
> I asked for some clarification of the scope of this at [#5380 (comment)](https://github.com/google/web-stories-wp/issues/5380#issuecomment-740662360):
> 
> > text contrast should check the text color vs. the text surrounding color, be it a bg image colors, text fill/highlight color, shapes colors, etc.
> 
> So this needs way more than a check against the bg image's base color, and would greatly benefit from a technical design doc/brief, taking into account all the previous work on this area, as well as the potential applications of this architecture (carousel previews, eyedropper, contrast check)

I have checking shapes and other layer types in the TODO. :) Working on it now.

I'll write something up. Do y'all happen to have a technical doc template? If not I'll just start a new shared Google doc.

I'm not super clear on how we would apply this elsewhere yet from where my perspective is now, but I'll leave that for the doc when my head's not buried in it.

**Comment by swissspidy** [comment]
> I'll write something up. Do y'all happen to have a technical doc template? If not I'll just start a new shared Google doc.

I don't have one handy, but https://www.industrialempathy.com/posts/design-docs-at-google/ and https://docs.google.com/document/d/1S9jTh6Lz3UEhj9Wkb7S7x_kJGvRVpEaNOqk2aCyb4y8/edit might serve as inspiration.

**Comment by dreamofabear** [comment]
+1 to the usefulness of a technical one-pager. 

However, I suspect this may balloon the scope and timeline of this feature and, for the purposes of the checklist, just calculating average background image color may be good enough for now. Let's discuss on #5380.

**Comment by embarks** [comment]
> +1 to the usefulness of a technical one-pager.
> 
> However, I suspect this may balloon the scope and timeline of this feature and, for the purposes of the checklist, just calculating average background image color may be good enough for now. Let's discuss on #5380.

It is pretty complicated when you take other image layers into account. I thought I could deal with scaled/focused images that were also rotated today but I didn't get very far. :( Although, I did learn some things and find better ways to test. I will detail further in the technical document because it will be easier for others to follow. I'll work on that on Friday this week.

I know this one is moving slow so I appreciate the visibility.

As of this iteration (which I pushed Thursday night), contrast checking works pretty well with background images and shape layers. It also works if there is an image between the background and the background image, as long as that image is not rotated (scaling it is fine). It has to do with the way I'm calculating the overlap. I'll come up with better visuals and screenshots in the doc to explain and hopefully that will help flesh out the solution, as well.

So, in its current iteration, I expect this solution would work with many stories, but unfortunately you get very unintuitive results if you used rotated images. There's ways we could bypass more complicated checks to avoid false positives. But of course, it's not complete without accounting for all the different layer types. :)

**Comment by embarks** [comment]
I wrote an explainer [here](https://docs.google.com/document/d/1qdwI900Ku7XOnqejXxs8c_bjvP9KwXXGqUpCBVFfumk/edit?usp=sharing). I'm stuck on rotating images on the canvas and I'm going to step away from it for a bit. I feel like it's almost there but I'm having trouble breaking down that part of the problem...

**Comment by embarks** [comment]
Rotated/scaled images seem to work now. 👍

File: assets/src/edit-story/app/prepublish/warning/accessibility.js [hunk 5]
```diff
@@ -49,6 +58,236 @@ function getSpansFromContent(content) {
...
+  const textPos = getBox(textElement, pageSize?.width, pageSize?.height);
+  const textBox = getBoundRect([textPos]);
+  const textBoxArea = textBox.width * textBox.height;
+
+  const elementOverlaps = [...potentialBackgroundElements]
+    .filter(({ isBackground }) => !isBackground)
+    .map((element, index) => {
+      const bgPos = getBox(element, pageSize?.width, pageSize?.height);
+      const bgBox = getBoundRect([bgPos]);
+      const overlappingArea = getOverlappingArea(textBox, bgBox);
```
Comment (carloskelly13) [inline assets/src/edit-story/app/prepublish/warning/accessibility.js:88]: This is great but I wonder if we should account for padding in text boxes. This can shift metrics for what is overlapping, but I would suggest we account for that as an iterative improvement—not necessarily in this PR.

Comment (embarks) [reply assets/src/edit-story/app/prepublish/warning/accessibility.js:88]: yeah, I wanna be able to do stuff like this:
Screen Shot 2020-12-16 at 3 04 03 PM

..without being warned about contrast. Using ~50% overlap was a too high per Will's feedback (only one element will be checked if we go for 50% overlap) but going to 25-30% was a little too low for some of my experiments which I felt were reasonable amounts of "low contrast". I'm gonna go with a middle ground (33%) and see how that feels to everyone. After playing with it a bit, this would be a really good addition to avoid false positives. We have some work coming up around textbox padding, too, so I agree about the iterative improvement.

**Comment by embarks** [comment]
Paying it forward to my next ticket which is to be able to select the offending element. I refactored to return an array of contrast issues for elements taking >=33% of the text box area (taking occluded area/layer order into account).

**Review by carloskelly13 — APPROVED** [review]
This looks great. I'd love to get this to QA and get a spot check on the feel from a user standpoint. I agree mathematically with the thresholds, but I suspect some adjustment might be necessary.
