### PR TITLE
Ignore looping media when getting the longest video

### LINKED ISSUE #1795: Story Not Auto-Advancing When Video Set To Loop
## Bug Description

Story is not auto-advancing to the next frame if it contains a video set to "Loop"

## Expected Behaviour

If set to auto-advance, story should advance based on user defined setting regardless of "loop"

## Steps to Reproduce

- create a story (2+ pages)
- set page advance to "auto" for the Document
- add a video to a page
- set video to "Loop" in design panel
- preview page

Note that page doesn't auto-advance past the page with the "loop" video

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

Ignores looping videos when detecting the longest video.

## Relevant Technical Choices

Filters the looping videos out before detecting the longes by length.

## To-do
-

## User-facing changes
Looping videos are ignored for auto-advance purposes and auto-advance works again when the looping video of the page is also the longest.

## Testing Instructions
 
1. Add a Page
2. Add 2 videos on the page
3. Check which video is longer and assign looping for the longer video
4. Add a second page and add another looping video to the second page.
5. Add one more Page, a third page (OK to leave empty).
6. View the Story
7. Verify that the first Page auto-advances based on the length of the shorter video.
8. Verify that the second Page auto-advances based on the default value (7 seconds by default).

---

Fixes #1795

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

File: assets/src/edit-story/output/utils/getLongestMediaElement.js [hunk 1]
```diff
@@ -27,9 +27,10 @@ import { getDefinitionForType } from '../../elements';
  */
 function getLongestMediaElement(elements) {
   return elements
-    .filter(({ type }) => {
+    .filter(({ type, loop }) => {
       const { isMedia } = getDefinitionForType(type);
-      return isMedia;
+      // Ensure looping media is not considered.
+      return isMedia && !loop;
```
Comment (barklund) [inline assets/src/edit-story/output/utils/getLongestMediaElement.js:33]: Should we also just discount images here or is that to support gifs (which can be non-looping too)?

**Review by barklund — APPROVED** [review]
Looks good - just a minor question.

File: assets/src/edit-story/output/utils/getLongestMediaElement.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/output/utils/getLongestMediaElement.js:33]: It could be used for audio in the future as well, the check for `resource.length` below will discard the media without length.
