### PR TITLE
Quick Actions: Reset Element Broken w/ Border Width & Radius

### LINKED ISSUE #11379: Quick actions: Reset Element for image borders broken
## Bug Description

When an image has borders, if you try to reset the element using quick actions the app blows up. 

## Expected Behaviour

App shouldn't explode, and borders should be removed. 

## Steps to Reproduce

Add an image and put some borders on it. 
Using the quicks actions, reset the element. 
💥
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by sblinde**
## Context

See: https://github.com/googleforcreators/web-stories-wp/issues/11379 for reported bug.

Video of issue:
(thank you @BrookeGraham for report and video shown below!)

Video of fix:
https://user-images.githubusercontent.com/7110244/166057948-f52b7829-6345-413f-b9de-fbfbdccd1e45.mov

## Summary

This fixes a bug that happens when one attempts to reset an element in the editor that has a border and/or border radius.

## Relevant Technical Choices

This PR adds optional chaining for the `border` object, as resetting the element results in `border` being null and implodes the application with an error.

## To-do

None.

## User-facing changes

No user-facing changes, only removing a bug that existed.

## Testing Instructions

This PR can be tested by following these steps:

1. Go to any element in the editor
2. Add a border
3. Click on the Reset Element button
4. You should expect the element to be reset and not result in an error.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [X] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [X] I have tested this code to the best of my abilities
- [X] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [X] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11379

### CODE REVIEW

**Review by maxyinger — COMMENTED** [review]
Looks like this is still broken with borderRadius too. Maybe there's a deeper issue with the reset styles functionality 🤷 

https://user-images.githubusercontent.com/35983235/166562940-de050912-92ee-4edd-b7c1-03cda27bb1af.mp4

**Comment by sblinde** [comment]
> Looks like this is still broken with borderRadius too. Maybe there's a deeper issue with the reset styles functionality 🤷
> 
>  Kapture.2022-05-03.at.15.42.29.mp4

Thanks for checking this out, let me see what I can do!

**Comment by sblinde** [comment]
> Looks like this is still broken with borderRadius too. Maybe there's a deeper issue with the reset styles functionality 🤷
> 
>  Kapture.2022-05-03.at.15.42.29.mp4

Should be fixed now with the new push, should tackle the border reset as well as border radius for shapes (and thank you for the feedback!)

**Review by mwritter — COMMENTED** [review]
It seems like the border should be set to the `DEFAULT_BORDER` 🤔 could there be an underlying issue with how we're setting the `border`?

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 1]
```diff
@@ -78,13 +78,13 @@ function BorderWidthAndColor() {
   );
   // We only allow editing the current border width, if all borders are identical
   const hasUniformBorder =
-    border.left === border.right &&
```
Comment (mwritter) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:81]: It seems like the border should be set to the `DEFAULT_BORDER` 🤔 could there be an underlying issue with how we're setting the `border`?

Comment (sblinde) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:81]: Potentially, yes. I think the error here is basically in regards to `border` being null at this point, hence it blows up the editor with an error when it happens, but it could be a deeper core issue. This resolves, for now, the issue at hand with the error, but might be worth taking a deeper look at.

**Review by mwritter — APPROVED** [review]
