### PR TITLE
Fix disabling background reordering for layer panel

### LINKED ISSUE #2339: Layer Panel: Dragging background displays indicators even though the bg can't be dragged
## Bug Description
When trying to drag the background element, it still shows visible drag indicators as if it would be possible, it's not though.

## Expected Behaviour
Drag indicators should not be shown for background element.

## Steps to Reproduce
1. Add a few elements
2. Try to drag the background in the layer panel
3. See the indicators visible.

## Screenshots
dragging

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Disables reodering for background element in the layer panel, it was previously using incorrect value.

## Testing Instructions
1. Add a few elements
2. Try to reorder the background element in the layer section in the design panel.
3. Verify that no blue lines appear when trying to drag it.

---

Fixes #2339

### CODE REVIEW

File: assets/src/edit-story/components/panels/layer/layerList.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ function LayerPanel({ layers }) {
           <ReorderableItem
             position={layer.position}
             onStartReordering={handleStartReordering(layer.id)}
-            disabled={layer.type === 'background'}
+            disabled={layer.isBackground}
```
Comment (barklund) [inline assets/src/edit-story/components/panels/layer/layerList.js:98]: 🙄

**Review by barklund — APPROVED** [review]
