### PR TITLE
Editor: Update behavior of consecutive snackbars

### LINKED ISSUE #12845: Snackbar: Nice to have one notification  instead of multiple
## Description

When we add page template multiple times we are showing multiple notification at the same time.

## Expected Behaviour
Nice to have one notification instead of multiple for same action

## Steps to Reproduce
 Please see the video video for steps 

## Video 

https://user-images.githubusercontent.com/12577046/207974227-46045f78-a6fb-43e7-8d20-66c55e9978c0.mp4

## Additional Context

- Plugin Version: v1.28.0
- WordPress Version: 
- Operating System: MAC
- Browser: Chrome

### PR DESCRIPTION
**Pull request by ayushnirwal**
## Context

Updates consecutive snack bar behavior to be more inline with [Material design guidelines](https://m3.material.io/components/snackbar/guidelines#84cd5bb6-354f-4fd0-bdd9-daf9684ba4bf)
  
## Summary

- `SnackbarProvider`'s `remove` function was removing notifications on the basis of `key` which was not a valid key. This was causing all snack bars to be removed when the `notifications` list hit its max limit.
- Fix ref handling in `SnackbarContainer` which was causing enter animation not to apply.
- Update `SnackbarContainer` to show only one snack bar at a time.

## User-facing changes

Before - 

https://user-images.githubusercontent.com/53055971/230868014-8702d875-3fba-434f-b639-ded2aea92be9.mov

After - 

https://user-images.githubusercontent.com/53055971/230868046-406d3f4b-82ba-4dfd-8916-70c050698862.mov

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12845

### CODE REVIEW

File: packages/design-system/src/components/snackbar/snackbarContainer.tsx [hunk 1]
```diff
@@ -157,57 +151,50 @@ function SnackbarContainer({
...
-              nodeRef={{ current: nodeRefs.current?.[id] }}
-              classNames="react-snackbar-alert__snackbar-container"
-            >
-              <ChildContainer
-                ref={(el) => {
-                  if (el) {
-                    nodeRefs.current[id] = el;
-                  }
-                }}
+        {orderedNotifications[0] &&
```
Comment (swissspidy) [inline packages/design-system/src/components/snackbar/snackbarContainer.tsx]: For readability I think we should just keep the `.map()` here.

Makes it easier to use in case we change `max` again for some reason (even if just for debugging)

File: packages/design-system/src/contexts/snackbar/snackbarProvider.tsx [hunk 2]
```diff
@@ -42,15 +42,15 @@ function SnackbarProvider({
...
+        | Pick<SnackbarNotification, 'id'>[]
     ) => {
       setNotifications((currentNotifications) =>
         currentNotifications.filter((item) => {
           if (Array.isArray(toRemove)) {
-            return !toRemove.find(({ key }) => key === item.key);
+            return !toRemove.find(({ id }) => id === item.id);
           }
-          return item.key !== toRemove.key;
+          return item.id !== toRemove.id;
```
Comment (swissspidy) [inline packages/design-system/src/contexts/snackbar/snackbarProvider.tsx:53]: `key` is actually used in at least one place:

https://github.com/GoogleForCreators/web-stories-wp/blob/be47067e36ec9d7c2b2d5092006953d3937fa9f1/packages/story-editor/src/app/media/useUploadMedia.js#L106-L116

Should we just remove `key` there because we only show 1 notification now anyway?

If so, we should probably remove `key` entirely from the `SnackbarNotification` type.

**Review by swissspidy — COMMENTED** [review]
The new behavior looks good to me 👍 

Just one question about the `key` attribute

File: packages/design-system/src/contexts/snackbar/snackbarProvider.tsx (hunk 2 above)
Comment (ayushnirwal) [reply packages/design-system/src/contexts/snackbar/snackbarProvider.tsx:53]: instead of using `key` here we can pass `id` in `showSnackbar`. This will overwrite the default `id` given using `uuid`.
In case we want to show more than one snack bar in the future, notifications can be still deleted using `removeSnakbar` and a known id.

**Review by swissspidy — APPROVED** [review]
