### PR TITLE
Fix focus colour in the design and library panels

### LINKED ISSUE #6858: Redesign: Update the inner box shadow for all focus used in the panel/library
## Bug Description
The focus line is using `bg.primary` as the default box-shadow between the blue line and the input edge, making it seem transparent, however, the panels have different background color and many (or most) of the inputs are having visibly different colour due to that.

We should update the colours in the panel for all inputs.

## Screenshots
Screenshot 2021-03-19 at 20 21 40

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
The focus outline assumes that the colour should be set based on the background of the element. This PR aims to do that for most of the focusable elements in the library and design panel.

## User-facing changes
|Before|After|
|----|----|
| Screenshot 2021-05-07 at 14 58 47 | Screenshot 2021-05-07 at 14 57 43 |

## Testing Instructions
- Go through the design panel / library and verify that the inputs' focus shadow inner area looks the same colour as the background (see the difference between Before & After on the screenshots above).

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6858

### CODE REVIEW

File: assets/src/edit-story/components/panels/shared/styles.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import { css } from 'styled-components';
+
+/**
+ * Internal dependencies
+ */
+import { themeHelpers } from '../../../../design-system/theme';
+
+export const focusStyle = css`
+  ${({ theme }) =>
+    themeHelpers.focusableOutlineCSS(
```
Comment (barklund) [inline assets/src/edit-story/components/panels/shared/styles.js:29]: Would it be an issue if this helper outputted `:focus, :focus-within {...}`, which would make these two constants the same? Would that simplify things?

**Review by barklund — APPROVED** [review]
Damn, that's a lot of work to make those outlines work correctly. Super annoying that we can't use do transparent, but I understand why.

File: assets/src/edit-story/components/panels/shared/styles.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/panels/shared/styles.js:29]: Hm, perhaps, but not sure if this could cause some issue. E.g. if there are cases where a focusable element can be inside another focusable element. Anyway, I'll leave it as it is currently, we can investigate it later in a separate PR.
