### PR TITLE
PHP: Remove return types from filter callbacks

### LINKED ISSUE #8713: Renderer: Remove return types from filter callbacks
## Bug Description

There can be fatal errors if some other plugin does filter values in unexpected ways.

Reported a few times on the forums:

* https://wordpress.org/support/topic/fatal-php-error-22/
* https://wordpress.org/support/topic/wordpress-critical-error-5/
* https://wordpress.org/support/topic/critical-error-caused-by-webstories-plugin/

Need to remove the return type declarations here (for both methods!):

https://github.com/google/web-stories-wp/blob/cc48e898fb72927854cea135a132524a2a7a4412/includes/Renderer/Single.php#L52-L84

And update the PHPDoc to include `mixed` as the param/return type.

## Expected Behaviour

No fatal errors

## Additional Context

- Plugin Version: 1.10
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Remove all type hint for filter callback and update phpdocs on these function

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8713

### CODE REVIEW

File: includes/Media/Image_Sizes.php [hunk 1]
```diff
@@ -122,8 +122,6 @@ protected function add_image_sizes() {
 			self::STORY_THUMBNAIL_IMAGE_DIMENSIONS[1],
 			false
 		);
-
-		add_filter( 'wp_prepare_attachment_for_js', [ $this, 'wp_prepare_attachment_for_js' ], 10, 2 );
```
Comment (swissspidy) [inline includes/Media/Image_Sizes.php:126]: Good catch!

File: includes/Admin/TinyMCE.php [hunk 2]
```diff
@@ -118,11 +119,12 @@ public function tinymce_web_stories_button( array $buttons ): array {
...
 	 * @since 1.5.0
 	 *
-	 * @param array $plugins Array of TinyMCE plugin scripts.
+	 * @param array|mixed $plugins Array of TinyMCE plugin scripts.
 	 *
 	 * @return array
 	 */
-	public function web_stories_mce_plugin( array $plugins ): array {
+	public function web_stories_mce_plugin( $plugins ) {
+		$plugins                = (array) $plugins;
```
Comment (swissspidy) [inline includes/Admin/TinyMCE.php]: Here you cast to an array, but not in other places like `action_links()`. Any specific reason?

Comment (spacedmonkey) [reply includes/Admin/TinyMCE.php]: Nope, I just missed them. 😄

File: includes/Admin/PluginActionLinks.php [hunk 3]
```diff
@@ -63,13 +63,14 @@ public static function get_registration_action(): string {
...
+	 * @param  array|mixed $links Plugin action links.
 	 *
-	 * @return array
+	 * @return array|mixed
 	 */
-	public function action_links( $links ): array {
+	public function action_links( $links ) {
 		$slug    = sprintf( 'edit.php?post_type=%s&page=stories-dashboard#/editor-settings', Story_Post_Type::POST_TYPE_SLUG );
 		$url     = get_admin_url( null, $slug );
+		$links   = (array) $links;
```
Comment (swissspidy) [inline includes/Admin/PluginActionLinks.php]: Since `$links` is cast to an array, the return type will always be an array, so we could actually now retain the return type.

File: includes/Admin/Editor.php [hunk 4]
```diff
@@ -174,12 +174,12 @@ public function replace_editor( $replace, $post ): bool {
 	 *
 	 * @since 1.0.0
 	 *
-	 * @param bool   $use_block_editor  Whether the post type can be edited or not. Default true.
-	 * @param string $post_type         The post type being checked.
+	 * @param bool|mixed $use_block_editor  Whether the post type can be edited or not. Default true.
+	 * @param string     $post_type         The post type being checked.
 	 *
-	 * @return bool Whether to use the block editor.
+	 * @return bool|mixed Whether to use the block editor.
```
Comment (swissspidy) [inline includes/Admin/Editor.php]:
```suggestion
	 * @return false|mixed Whether to use the block editor.
```

To be more specific

File: includes/Admin/Cross_Origin_Isolation.php [hunk 5]
```diff
@@ -216,13 +216,13 @@ public function get_avatar( $avatar, $id_or_email, $size, $default, $alt, array
...
-	 * @param string $url URL.
+	 * @param string|mixed $html HTML string.
+	 * @param string       $attribute Attribute to check for.
+	 * @param string       $url URL.
 	 *
-	 * @return string
+	 * @return string|mixed
 	 */
-	protected function add_attribute( string $html, string $attribute, string $url ): string {
+	protected function add_attribute( $html, string $attribute, string $url ) {
```
Comment (swissspidy) [inline includes/Admin/Cross_Origin_Isolation.php:225]: Does `$html` need to be cast to a string here?

Since `$new_html` is always a string, the return type will always be a string, so we could actually retain the return type.

File: includes/Admin/Cross_Origin_Isolation.php [hunk 6]
```diff
@@ -194,20 +194,20 @@ public function script_loader_tag( $tag, $handle, $src ): string {
...
+	 *                                  'gravatar_default'. Default is the value of the 'avatar_default' option, with a
+	 *                                  fallback of 'mystery'.
+	 * @param string       $alt         Alternative text to use in the avatar image tag. Default empty.
+	 * @param array        $args        Arguments passed to get_avatar_data(), after processing.
 	 *
-	 * @return string
+	 * @return string|mixed
 	 */
-	public function get_avatar( $avatar, $id_or_email, $size, $default, $alt, array $args ): string {
+	public function get_avatar( $avatar, $id_or_email, $size, $default, $alt, array $args ) {
```
Comment (swissspidy) [inline includes/Admin/Cross_Origin_Isolation.php:210]: If we retain the return type in `add_attribute()`, we could also retain it here.

File: includes/Admin/Cross_Origin_Isolation.php [hunk 7]
```diff
@@ -183,9 +183,9 @@ public function style_loader_tag( $tag, $handle, $href ): string {
 	 * @param string $handle The script's registered handle.
 	 * @param string $src    The script's source URL.
 	 *
-	 * @return string
+	 * @return string|mixed
 	 */
-	public function script_loader_tag( $tag, $handle, $src ): string {
+	public function script_loader_tag( $tag, $handle, $src ) {
```
Comment (swissspidy) [inline includes/Admin/Cross_Origin_Isolation.php:188]: Ditto here about possibly retaining return types

File: includes/Admin/Cross_Origin_Isolation.php (hunk 5 above)
Comment (spacedmonkey) [reply includes/Admin/Cross_Origin_Isolation.php:225]: Yes, but $new_html is the only thing that can be returned here 

```
if ( $this->starts_with( $url, $site_url ) ) {
			return $html;
		}
		if ( $this->starts_with( $url, '/' ) ) {
			return $html;
		}
```

File: includes/Admin/Cross_Origin_Isolation.php (hunk 6 above)
Comment (spacedmonkey) [reply includes/Admin/Cross_Origin_Isolation.php:210]: As noted before, `add_attribute` doesn't always return a string

File: includes/Admin/Cross_Origin_Isolation.php (hunk 7 above)
Comment (spacedmonkey) [reply includes/Admin/Cross_Origin_Isolation.php:188]: If you filter `script_loader_tag` to return boolean, that would be passed to `add_attribute`. It would return early like this, 

```
if ( $this->starts_with( $url, $site_url ) ) {
			return $html;
		}
```

returning a boolean.

File: includes/Admin/Cross_Origin_Isolation.php (hunk 5 above)
Comment (swissspidy) [reply includes/Admin/Cross_Origin_Isolation.php:225]: Argh, missed that. Nevermind then.

File: includes/Admin/PluginActionLinks.php (hunk 3 above)
Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: Same probably applies to more places.

Comment (spacedmonkey) [reply includes/Admin/PluginActionLinks.php]: This is true of a lot of places. But I think it is cleaner to have a hard rule of not having a type hint on any filter callback. If we start doing this in same places and not others, it would get confusing. Thoughts?

File: includes/Admin/Site_Health.php [hunk 8]
```diff
@@ -230,11 +231,12 @@ public function add_extensions( array $core_extensions ): array {
...
 	 *
-	 * @param array $test_result Site Health test result.
+	 * @param array|mixed $test_result Site Health test result.
 	 *
-	 * @return array Modified test result.
+	 * @return array|mixed Modified test result.
 	 */
-	public function modify_test_result( array $test_result ): array {
+	public function modify_test_result( $test_result ) {
+		$test_result = (array) $test_result;
```
Comment (swissspidy) [inline includes/Admin/Site_Health.php]: The downside of blindly casting everything to an array is that if `$test_result` is `false` (if some plugin returned that for some reason), `$test_result` becomes

```
array(1) {
  [0]=>
  bool(false)
}
```

Same goes for other places with type casting.

File: includes/Admin/PluginActionLinks.php (hunk 3 above)
Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: I'd like our type declarations to be as specific as possible.

When we are certain about the return type, it's clear to specify this with a return type.

The alternative would be to not do type casting at all because of the drawbacks as per https://github.com/google/web-stories-wp/pull/8724/files#r692021032.

So instead of `$links = (array) $links;` we would do `if ( ! is_array( $links ) ) { return $links; }`

Then we can't add a return type obviously.

Comment (spacedmonkey) [reply includes/Admin/PluginActionLinks.php]: > So instead of $links = (array) $links; we would do if ( ! is_array( $links ) ) { return $links; }

So instead of casting, should I replace that with type checking?

Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: Well that depends on whether it makes sense or not. I would like to hear your opinion on it so we can outweigh pros and cons of the three different approaches (`no return types + casting`, `return types + casting`, `no return types + no casting`).

Comment (spacedmonkey) [reply includes/Admin/PluginActionLinks.php]: #### return types + casting
In my cases, there are mixed return types, as casting is not possible. We could add it in some places or cast the return. But there we will have to make a note of where this casting should and should not be. 

#### no return types + casting
No return types means we can have mixed returned values, which most of these filters are likely to be. Casting ensure, that we do, say a array_merge, that we don't get e fatal error. 

#### no return types + no casting
This can result in fatal errors, as noted above. This is the one that most likely to generate problems.

Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: > But there we will have to make a note of where this casting should and should not be.

I think the code itself and the PHPDoc documentation will make this quite clear. Plus PHPStan and PHPCS would yell at us otherwise.

> no return types + no casting

To clarify, with this I meant not doing casting, _but_ doing type checks like `is_array()` instead. To avoid fatal errors.

Comment (spacedmonkey) [reply includes/Admin/PluginActionLinks.php]: > but doing type checks like is_array() instead.

If we do this, our filters will do nothing...

Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: Doing nothing if another plugin does bad things is better than crashing or causing notices due to unexpected behavior.

Comment (swissspidy) [reply includes/Admin/PluginActionLinks.php]: After letting this sink in for a bit, I think we should proceed with the `if ( ! is_array( $links ) ) { return $links; }` approach.

If a plugin filters `$links` to be something else, then something is really broken and we should not bother trying to cast to an array. Especially because of the unintended side effects casting could have (as per https://github.com/google/web-stories-wp/pull/8724/files#r692021032)

**Review by swissspidy — APPROVED** [review]
