### PR TITLE
Fix Color Picker positioning

### LINKED ISSUE #6719: Colour picker panel is cut off from window
## Bug Description

If window is not high enough, color picker panel gets cut off at the bottom and doesn’t allow users to scroll through it.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
- Sets max height to popup so that it can't be more than 100% of th viewport height, in case of overflow, scroll!
- Repositions the popup if its height has changed.

## User-facing changes
|Before|After|
|------|-------|
| Screenshot 2021-03-23 at 17 15 58 | Screenshot 2021-03-23 at 17 13 58 |
| scrolling | scrolling |

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:
I
1. Resize the screen so that the color picker would not fit into the screen fully and then refresh the page.
2. Add a shape.
3. Open the color picker
4. Verify it's possible to scroll around inside the color picker.

II
1. Resize the screen sho that the color picker would fit into the screen but not with a lot of extra room.
2. Add a shape, make sure you have at least 6 saved colours.
3. Scroll in the design panel so that the Style panel would be visible but as low on the screen as possible.
4. Now open the colour picker for the Style.
5. Verify the saved colors are all visible.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6719

### CODE REVIEW

File: assets/src/edit-story/components/popup/index.js [hunk 1]
```diff
@@ -93,11 +101,22 @@ function Popup({
...
 
+  useEffect(() => {
+    // If the popup height changes meanwhile, let's update the popup, too.
+    if (
+      popupState?.height &&
+      popupState.height !== popup.current?.getBoundingClientRect()?.height
+    ) {
+      positionPopup();
+    }
+  }, [popupState?.height, positionPopup]);
```
Comment (barklund) [inline assets/src/edit-story/components/popup/index.js:118]: This (obviously) doesn't trigger if the popup resizes itself. E.g. if the popup is shown at the very bottom of the screen and you switch to "All stories" in the dropdown with multiple lines of colors. Then the popup will be cut off until you scroll in the design panel.

It's of course hard to fix that generally, but maybe we could add a manual function, that the popup could invoke from within asking the parent to reposition it?

It's just a nit - this PR already solves 99% of the existing problems so it's quite the edge case:

colorpicker-resizing-bug

**Review by barklund — APPROVED** [review]
Looks great. Just found a single edge-case but not a high priority.

File: assets/src/edit-story/components/popup/index.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/popup/index.js:118]: Added a fix in 4bc2c8e. It feels a bit hacky since it's for this case specifically but it seems to work. Let me know what you think 🐾
