### PR TITLE
Taxonomies: keyboard functionality

### LINKED ISSUE #9059: Taxonomies: Misc Keyboard Functionality
## Bug Description

1) Hitting `Enter` in the 'new category' input doesn't submit the form
Hitting the `Enter` key in the 'new category' input or 'parent category' dropdown should submit the form.

However the dropdown grabs the focus instead of submitting the form. Update the dropdown so that the dropdown doesn't hijack the submission event.

2) clicking/entering `Add new category` should focus the input field. 

## Expected Behaviour

Hitting `Enter` when the input is filled should submit the form.

And expanding the add new category section should focus the input there to add a new category.

## Steps to Reproduce

Wait for #9048 to be merged

1. Enable taxonomies experiment
2. Go to documents panel
3. Expand the new category section by clicking `Add new Category` button
4. Type into input and hit `Enter`. This will focus the dropdown

## Screenshots

enter

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Summary

Expanding the `add new category` section should move focus to the input where you can begin to type a new category.

Hitting `Enter` while the input is in focus should submit the form.

https://user-images.githubusercontent.com/1820266/134193092-faeabe74-51bb-45aa-8a0f-80e936d08441.mov

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.  Click the `Add New Category` text. This should expand the form. 
2. Focus should now be on the input. 
3. Type a new category to add hit `Enter` and the form should submit. 
4. Similarly navigating through the `Parent Categories` via the keyboard arrows highlight desired parent category and hit `Enter` to submit with selected parent. 

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9059

### CODE REVIEW

**Comment by BrookeGraham** [comment]
https://user-images.githubusercontent.com/1820266/134193092-faeabe74-51bb-45aa-8a0f-80e936d08441.mov

File: packages/design-system/src/components/input/index.js [hunk 1]
```diff
@@ -158,7 +159,7 @@ export const Input = forwardRef(
   ) => {
     const inputId = useMemo(() => id || uuidv4(), [id]);
 
-    const [isFocused, setIsFocused] = useState(false);
+    const [isFocused, setIsFocused] = useState(hasFocus);
```
Comment (BrittanyIRL) [inline packages/design-system/src/components/input/index.js:162]: 🕺

**Review by BrittanyIRL — CHANGES_REQUESTED** [review]
This is a massive improvement to keyboard usability on this! 😅 

If I can add scope creep now that we can test out adding a category with the keyboard more effectively, when you use the keyboard 'add' or 'cancel' on a new category, the focus shifts to the canvas. Thoughts on sending the user back to the 'add new category` button here instead since that's essentially a toggle? This allows the user to either go back and add another category or easily get to the rest of taxonomy without getting focus shifted.

Will you also add a karma test in components/panels/document/taxonomies/karma/taxonomies.karma.js for adding a new category by keyboard?

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js [hunk 2]
```diff
@@ -221,14 +260,23 @@ function HierarchicalTermSelector({ noParentId = NO_PARENT_VALUE, taxonomy }) {
...
         noOptionsText={taxonomy.labels.not_found}
       />
+      <LinkButton
+        ref={toggleRef}
+        aria-expanded={false}
+        onClick={handleToggleNewCategory}
+        _showAddNewCategory={showAddNewCategory}
+      >
+        {taxonomy.labels.add_new_item}
+      </LinkButton>
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: Since we wanted to move focus back to this, I had to leave it mounted when `showAddNewCategory` changes otherwise the ref becomes null. This meant I had to hide with css. I am sure there are other ways, but I figured a button wasn't too big a deal to leave mounted, thoughts?

File: packages/story-editor/src/components/panels/document/taxonomies/karma/taxonomies.karma.js [hunk 3]
```diff
@@ -103,9 +103,12 @@ describe('Categories & Tags Panel', () => {
 
         // open the new category section
         await fixture.events.click(categoriesAndTags.addNewCategoryButton);
+        // Input should be focused
+        expect(document.activeElement).toBe(
+          categoriesAndTags.newCategoryNameInput
+        );
 
         // Add new category
-        await fixture.events.focus(categoriesAndTags.newCategoryNameInput);
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/panels/document/taxonomies/karma/taxonomies.karma.js:108]: Focus now happens when `addNewButton` is selected. No need to manually focus.

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js [hunk 4]
```diff
@@ -71,6 +77,8 @@ const ButtonContainer = styled.div`
 const LinkButton = styled(Button).attrs({
   variant: BUTTON_VARIANTS.LINK,
 })`
+  ${(props) => props._showAddNewCategory && 'display: none;'}
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: nit: Let's use a [transient prop](https://styled-components.com/docs/api#transient-props) here instead 
```suggestion
  display: ${({$isVisible}) => $isVisible ? 'none' : 'block')};
```

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js [hunk 5]
```diff
@@ -221,14 +260,23 @@ function HierarchicalTermSelector({ noParentId = NO_PARENT_VALUE, taxonomy }) {
         onChange={handleClickCategory}
         noOptionsText={taxonomy.labels.not_found}
       />
+      <LinkButton
+        ref={toggleRef}
+        aria-expanded={false}
+        onClick={handleToggleNewCategory}
+        _showAddNewCategory={showAddNewCategory}
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: (part 2 of nit re transient props)
```suggestion
        $isVisible={showAddNewCategory}
```

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js (hunk 2 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: this makes sense to me, totally fine.

**Review by BrittanyIRL — APPROVED** [review]
Yah test additions! Thank you for those. Having keyboard karma tests saves us from regressions a lot :) 

1 nit for styled components to fix, approving ahead of that :)

File: packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js (hunk 4 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/panels/document/taxonomies/HierarchicalTermSelector.js]: For sure!
