### PR TITLE
Editor: Remove errant 'Edit' option from media menu

### LINKED ISSUE #12555: Link Icon Menu Shows Edit Option
## Bug Description

The Call to Action link icon pencil menu displays an option to "Edit" which functions the same as "Upload a file".

## Expected Behaviour

To have 1 option to "Upload a file".

## Steps to Reproduce

1. Add link in the Call to Action section
2. Click pencil on Link Icon 
3. Notice menu option: Edit

## Screenshots

Screen Shot 2022-10-27 at 11 14 34 AM

-->

## Additional Context

- Plugin Version: 1.26.0
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by timarney**
## Context

The Call to Action link icon pencil menu displays an option to "Edit" which functions the same as "Upload a file".

**Expected Behaviour**
To have 1 option to "Upload a file".

## Summary

Removed edit link --- noting the same behaviour was happening for shape, image links etc...

https://github.com/GoogleForCreators/web-stories-wp/issues/12555#issuecomment-1294901351

|   before	|   	after |  
|---	|---	|
|   before	|   after	|  

 

## To-do

Might be worth looking at why clicking the pencil icon multiple times (click (keep menu opne) click pencil again) positions the menu at a different spot - click the menu either ends up off to the left or centered.
 
Screen Shot 2022-10-29 at 6 06 48 AM

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add link in the Call to Action section
2. Click pencil on Link Icon
3.  Notice menu option: Upload without edit

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12555

### CODE REVIEW

File: packages/story-editor/src/components/form/linkIcon.js [hunk 1]
```diff
@@ -68,7 +68,6 @@ function LinkIcon({ handleChange, icon, isLoading = false, ...rest }) {
 
   const options = [
```
Comment (swissspidy) [inline packages/story-editor/src/components/form/linkIcon.js:69]: The same issue still exists in the `VideoAccessibilityPanel` component as well.

Also, these options are passed to `MediaInput` and `MediaInputField` in `packages/story-editor/src/components/form/media.js`, which still have logic for 'edit'. We should remove those as well as they're otherwise unused.

**Comment by swissspidy** [comment]
Looks like some tests now need updating, please check

**Comment by timarney** [comment]
yes just taking a look now

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Verified the issue exists on `main branch`

Changed to `12561 branch` and confirmed that the extra menu option to "Edit" is no longer present when clicking the link icon pencil.


Did mini regression testing of call-to-action functionality, linking multiple types of 96x96 px images, removing and adding other images, changing to dark theme, observing results in final web story etc.

@timarney - I tried multiple clicks of the pencil icon but did NOT see the menu change positions. I was on Chrome/win10 and Firefox/Mac
