### PR TITLE
Prevent endless loop on empty font array in `FontProvider`

### LINKED ISSUE #10596: FontProvider creating endless loop
Standalone editor, font provider calling getFonts function and creating endless loop.
This code block creating endless loop.

https://github.com/GoogleForCreators/web-stories-wp/blob/2f73bb644cf2313672e344891c02c7c838be08d4/packages/story-editor/src/app/font/fontProvider.js#L54-L85

## Steps to Reproduce
https://codesandbox.io/s/laughing-heyrovsky-eefv2

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by mohdsayed**
## Context

See https://github.com/GoogleForCreators/web-stories-wp/issues/10596

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes https://github.com/GoogleForCreators/web-stories-wp/issues/10596

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/textStyle/fontPicker.js [hunk 1]
```diff
@@ -57,18 +64,33 @@ const FontPicker = forwardRef(function FontPicker(
...
   }));
 
+  useEffect(() => {
+    mounted.current = true;
+
+    getCustomFonts(mounted);
+    getCuratedFonts(mounted);
+
+    return () => {
+      mounted.current = false;
```
Comment (swissspidy) [inline packages/story-editor/src/components/panels/design/textStyle/fontPicker.js]: This mounted ref is not needed here

Comment (mohdsayed) [reply packages/story-editor/src/components/panels/design/textStyle/fontPicker.js]: Oh yes, it's no longer needed because the state update happens in `FontProvider` which doesn't unmount. 👍

File: packages/story-editor/src/app/font/fontProvider.js [hunk 2]
```diff
@@ -51,73 +45,51 @@ function FontProvider({ children }) {
...
-          }
-
-          const formattedFonts = _customFonts.map((font) => ({
-            id: font.family,
-            name: font.family,
-            value: font.family,
-            ...font,
-          }));
+  const getCustomFonts = useCallback(async () => {
+    if (customFonts || !getFonts || !isCustomFontsEnabled) {
```
Comment (swissspidy) [inline packages/story-editor/src/app/font/fontProvider.js:49]: The `getFonts` checks here and below might not be needed anymore. I now recall that I originally added it because of `storyPageToDataUrl`, which uses `FontProvider` to load fonts, but doesn't need custom fonts or curated fonts.

So with this effect gone, this safeguard would be not needed anymore.

Comment (mohdsayed) [reply packages/story-editor/src/app/font/fontProvider.js:49]: So if `getFonts` is not provided, we will not render `FontPicker` component dropdown at all?

Comment (mohdsayed) [reply packages/story-editor/src/app/font/fontProvider.js:49]: Like this https://github.com/GoogleForCreators/web-stories-wp/pull/10643/commits/a27975166e512bd5494e5876fb28c60b1581811c

Comment (swissspidy) [reply packages/story-editor/src/app/font/fontProvider.js]: No I meant

```diff
-if (customFonts || !getFonts || !isCustomFontsEnabled) {
+if (customFonts || !isCustomFontsEnabled) {
```

Comment (swissspidy) [reply packages/story-editor/src/app/font/fontProvider.js:49]: I meant just removing the `|| !getFonts` check but I suppose it makes sense like this 👍

Comment (mohdsayed) [reply packages/story-editor/src/app/font/fontProvider.js:49]: https://github.com/GoogleForCreators/web-stories-wp/commit/a27975166e512bd5494e5876fb28c60b1581811c looks wrong because if we remove `getFonts` condition, the standalone editor will throw an error when `getFonts` isn't provided. To prevent this I had added `fonts.length > 0` so that `FontPicker` doesn't get rendered and `getFonts` is never called, but actually, that was a mistake because `fonts` will not have any value until `FontPicker` is rendered so font picked will not render in any case. Reverting the commit changes.

**Review by swissspidy — APPROVED** [review]
