### PR TITLE
Fix: Border radius not respected while animating

### LINKED ISSUE #7356: Preview: Border radius not respected while animating
**Summary**
If an animation is applied to an element with a border radius, the border radius is not respected in the story preview while animating:

https://images.zenhubusercontent.com/235435637/05894e6c-4e79-4668-a462-a854fa8fc94d/balldropanimation.mov

**Successful completion of this ticket**
Border radius of elements in preview should be maintained while animating

### PR DESCRIPTION
**Pull request by embarks**
## Context
Adding a border radius to shapes was not being respected on the output.

https://user-images.githubusercontent.com/41136059/117073438-be4b6600-ace6-11eb-8df0-c0d5f6c69b21.mp4

This PR should fix this issue.

## Summary
- Added `will-change: transform` to the mask's CSS.

## Relevant Technical Choices
From the MDN Docs
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
> will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.

Originally I had `will-change: transform` on the `.mask` style, but I didn't want it applied to every mask, just shapes, which were the only elements I could find which had this issue. So I went with the change to `shape/output` to minimize the usage of `will-change` per recommendations.

## To-do
NA

## User-facing changes

Now adding a border radius and animation to any element should retain its border radius.

https://user-images.githubusercontent.com/41136059/117075408-9c9fae00-ace9-11eb-8962-87df9cf6183a.mp4

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a square shape element to the canvas
2. Add a border radius > 1, either all the same or different
3. Add any animation to the shape.
3. Click `Preview` or update a published story and view the updated story
4. The animated element should retain the border radius.

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7356

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
Wow great find. Thanks for the informative PR description too. Really helps!

**Review by swissspidy — APPROVED** [review]

File: assets/src/edit-story/elements/shape/output.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ function ShapeOutput({ element: { backgroundColor, isDefaultBackground } }) {
   const style = isDefaultBackground
     ? null
     : generatePatternStyles(backgroundColor);
-  return <div className="fill" style={style} />;
+  return <div className="fill" style={{ ...style, willChange: 'transform' }} />;
```
Comment (swissspidy) [inline assets/src/edit-story/elements/shape/output.js:35]: Nit: some comment here would be good.

**Review by BrittanyIRL — APPROVED** [review]
Super interesting!

**Review by maxyinger — APPROVED** [review]
🙌

**Comment by dreamofabear** [comment]
Interesting bug. I can't easily reproduce this on a simple AMP story animations demo page, so it must be particular to our usage.
