### PR TITLE
prevent browser's context menu when right clicking on our ContextMenu

### LINKED ISSUE #8936: Repeatedly right-clicking shows the browser context menu instead of our editor's right-click menu
## Bug Description

Originally reported by @choumx 
Repeatedly right-clicking shows the browser context menu instead of our editor's right-click menu

## Expected Behaviour

Right clicking in the editor should always bring up the right-click menu (?)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

When right clicking on our custom ContextMenu, the browser's default menu pops up. We want to prevent the browser's context menu if the user already has the ContextMenu open. 

## User-facing changes

Nothing will happen if you right-click on the right-click menu.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. In the editor, right-click on the canvas to open our `ContextMenu`
2. Right click anywhere on that menu
3. Nothing happens 🎉

### Does this PR have a security-related impact?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8936

### CODE REVIEW

File: packages/story-editor/src/components/canvas/rightClickMenu.js [hunk 1]
```diff
@@ -41,10 +41,17 @@ const RightClickMenu = () => {
     onCloseMenu,
     maskRef,
   } = useRightClickMenu();
+  const ref = useRef();
+  // If ContextMenu is already rendered prevent browser's context menu when right clicking on ContextMenu
+  useEffect(() => {
+    const node = ref.current;
+
+    node.addEventListener('contextmenu', (evt) => evt.preventDefault(), false);
```
Comment (swissspidy) [inline packages/story-editor/src/components/canvas/rightClickMenu.js]: Probably need to `removeEventListener` on unmount

**Comment by spacedmonkey** [comment]
Have we tested this functionality with accessibility tools? Many accessibility tools, add extra options to context menu.

**Comment by BrittanyIRL** [comment]
> Have we tested this functionality with accessibility tools? Many accessibility tools, add extra options to context menu.

This feels separate :) 

Everything that can happen in the right click menu has a shortcut listed in the shortcuts menu for the keyboard. If you happen to open the context menu and then use your keyboard everything announces fine and passes aXe testing. 

Designs didn't list an additional keyboard control to open a context menu for an element when selected - it wasn't in the spec. Feels like a good add at this point. So I'll make a ticket for that to follow up. 

https://github.com/google/web-stories-wp/issues/8993

**Review by BrittanyIRL — COMMENTED** [review]
🚀  LGTM!

**Review by BrittanyIRL — APPROVED** [review]

**Review by samwhale — APPROVED** [review]
Nice, this works great
