### PR TITLE
Infer User Capabilities from REST API Responses

### LINKED ISSUE #8269: Dashboard: author shown links to open in editor, when they should not
## Bug Description

While logged in as an author, I am shown "open in editor" links, for story I do not have access to edit.

Follow on from https://github.com/google/web-stories-wp/pull/8268

## Expected Behaviour

Options to edit stories that I, an author should be hidden are disabled. 

## Steps to Reproduce

1. Create a story as a admin. 
2. Login as author. 
3. Try to edit the story you just created as an admin. 

## Screenshots

https://user-images.githubusercontent.com/237508/125115186-e25e6580-e0e2-11eb-9a4a-c7233a791207.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #8276: Infer User Capabilities from REST API Responses
## Feature Description

In the editor and dashboard, we currently pass the current user's capabilities that we need in the app via inline JS / the `ConfigProvider`. This works OK-ish, but does not really scale well.

* Just checking for `can user edit stories` does not work for cases like the dashboard where we need to individually check for capabilities for the stories being displayed.  
  The user could be allowed to edit story X but not Y, so the checks would not be accurate.
* Every enhancement to the React apps requires PHP changes to pass the necessary capability information.

Lucky for us, the [WordPress REST API incorporates hyperlinking](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/) throughout the API to allow discoverability and browsability, loosely based on the [HAL standard](https://en.wikipedia.org/wiki/Hypertext_Application_Language).

For example, the `_links` property of the response object contains a map of links to other API resources, grouped by “relation”. The relation specifies how the linked resource relates to the primary resource.

This includes capabilities! For each story, there is a `wp:action-assign-author` entry under `_links` if the user has the capability. So instead of passing `hasAssignAuthorAction` manually from PHP we can simply look for this entry.

**Note:** the WP Rest API does not currently add links for all actions that we need ([see this example](https://core.trac.wordpress.org/ticket/50388), but extending the REST API to do that is trivial.

So my suggestion:

1. Add new actions to `_links` for things we need
2. When fetching stories from the REST API, check for the `_links` to get the user's capability for each story
3. Use that information to have more granular capability checks

## Alternatives Considered

* [`targetHints`](https://tools.ietf.org/id/draft-handrews-json-schema-hyperschema-00.html#rfc.section.6.5.5) are an interesting idea as well, but not yet available.

## Additional Context

Gutenberg has implemented a really neat [approach](https://github.com/WordPress/gutenberg/tree/a6908dcc4cde747ee2879317597f73179bf6e4d1/packages/core-data#canUser) for this.
  Essentially, one calls a Redux selector to see whether the current user can perform the given action on the given REST resource.
  If the information hasn't been fetched yet, an `OPTIONS` request to the REST API is triggered via the `canUser()` resolver (basically a middleware that only runs once).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #8603: Dashboard Context Menu Actions
In the latest bugbash, Jonny brought up a potential regression that wasn't noticed where some users don't have the ability to do all menu actions but those actions are still available in the context menu for stories. Let's look at that and make sure we've got tests set up to catch that moving forward. 

(Screen grab from bug bash for context)

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Instead of using capabilities loaded from config provider, use hyperlinks in the rest api to workout permissions. 

## User-facing changes

Remove menu items if you do have access to edit them.
Screenshot 2021-08-05 at 13 04 19

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a story as an admin. Save Story.
2. Login as contributor / author, 
3. Go to dashboard. 
4. See limited options in menu and title of the story is not a hyperlink. 

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8276 
Fixes #8269
Fixes #8603

### CODE REVIEW

File: includes/REST_API/Stories_Base_Controller.php [hunk 1]
```diff
@@ -215,4 +215,27 @@ protected function prepare_links( $post ): array {
...
+	 * @since 1.10.0
+	 *
+	 * @param WP_Post         $post    Post object.
+	 * @param WP_REST_Request $request Request object.
+	 * @return array List of link relations.
+	 */
+	protected function get_available_actions( $post, $request ) {
+		$rels = parent::get_available_actions( $post, $request );
+
+		if ( $this->check_delete_permission( $post ) ) {
```
Comment (swissspidy) [inline includes/REST_API/Stories_Base_Controller.php:231]: How convenient that this method exists!

File: assets/src/edit-story/components/panels/document/publish/publish.js [hunk 2]
```diff
@@ -182,7 +184,7 @@ function PublishPanel() {
       <PanelTitle>{__('Publishing', 'web-stories')}</PanelTitle>
       <PanelContent>
         <PublishTime />
-        {capabilities && capabilities.hasAssignAuthorAction && users && (
+        {capabilities && capabilities?.hasAssignAuthorAction && users && (
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/document/publish/publish.js]:
```suggestion
        {capabilities?.hasAssignAuthorAction && users && (
```

**Comment by swissspidy** [comment]
I know it's still a draft but this looks amazing 😻

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js [hunk 3]
```diff
@@ -127,20 +127,25 @@ export const CardDetailsColumn = styled.div`
...
   display: -webkit-box;
   -webkit-line-clamp: 3;
   /* stylelint-disable-next-line */
   -webkit-box-orient: vertical;
+`;
+
+export const Title = styled(StoryTitle).attrs({
+  as: 'a',
+})`
+  color: ${({ theme }) => theme.colors.inverted.fg.primary};
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: Hmm it's not super obvious that one is a link and the other isn't.

Can we rename them to something like `Title` and `TitleLink` to make that more clear?

**Review by swissspidy — APPROVED** [review]
LGTM with just one nit

**Comment by swissspidy** [comment]
Just realized there are some failing tests

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js [hunk 4]
```diff
@@ -128,19 +128,24 @@ export const CardDetailsColumn = styled.div`
 // If it fails, max-height will catch so that really long titles
 // don't leave their designated space, just no ellipsis.
 export const Title = styled(Headline).attrs({
-  as: 'a',
   size: THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.X_SMALL,
 })`
   overflow: hidden;
   text-overflow: ellipsis;
-  color: ${({ theme }) => theme.colors.inverted.fg.primary};
+  color: ${({ theme }) => theme.colors.inverted.fg.tertiary};
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: Not 100% sure about this change. Perhaps we might just want to keep this primary at all times.

File: assets/src/dashboard/app/serializers/stories.js [hunk 5]
```diff
@@ -33,11 +33,23 @@ export default function reshapeStoryObject(originalStoryData) {
       'wp:lock': lock = [{ locked: false }],
       'wp:lockuser': lockUser = [{ id: 0, name: '', avatar_urls: {} }],
     } = {},
+    _links: links = {},
   } = originalStoryData;
   if (!Array.isArray(storyData.pages) || !id || storyData.pages.length === 0) {
     return null;
   }
 
+  const capabilities = {
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/serializers/stories.js]: dig this set up

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js (hunk 4 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: I'd like to leave this as primary and then just adjust the cursor instead. If it's an anchor tag it should show the `pointer` and if it's just a headline it should be `default` - which i believe is how it's set up since you separated the styled component based on if it's got a link or not.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js [hunk 6]
```diff
@@ -122,17 +123,21 @@ const StoryDisplayContent = ({
...
+              aria-label={sprintf(
+                /* translators: %s: title*/
+                __('Open %s in editor', 'web-stories'),
+                title
+              )}
+            >
+              {formattedTitle}
+            </TitleLink>
+          ) : (
+            <Title>{formattedTitle}</Title>
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: this needs to be given the proper headline hierarchy (otherwise it defaults to h1):
```suggestion
            <Title as='h3'>{formattedTitle}</Title>
```

**Review by BrittanyIRL — CHANGES_REQUESTED** [review]
This is so great! 

One request re the heading in the dashboard. 

I'm curious your thoughts about creating constants for the capabilities so that if someone else is trying to check these in the future for a new feature there's a place to note what these are rather than typing the string out fresh every time: `wp:action-edit`, `wp:action-delete`, `wp:action-publish`, `wp:action-assign-author`, `wp:action-unfiltered-html`

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js (hunk 6 above)
Comment (swissspidy) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: Should that be done in `components.js` as part of the `attrs()` call?

```js
export const Title = styled(Headline).attrs({
  as: 'h3',
  size: THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.X_SMALL,
})`
....
`;
```

Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: it does the same thing either way.  Since size is getting set in attrs then that's good too.

**Comment by spacedmonkey** [comment]
> I'm curious your thoughts about creating constants for the capabilities so that if someone else is trying to check these in the future for a new feature there's a place to note what these are rather than typing the string out fresh every time:

I am not sure what you mean here. In both editor and dashboard, the capability is stored with the story, making it easy to get later. What do you mean by a const here?

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: I originally had this way and there was no way to see it wasn't a link. As a user, I would just try and click on the link and then nothing happens, which is confusing. Here is what it looks like. 

Screenshot 2021-08-09 at 19 07 13

I would also say, the title's isn't super clear it is a link in the first place. This makes it more confusing. 

We also have to compare it to WordPress, where the links are a different colour. 

Screenshot 2021-08-09 at 19 09 40

Can we have some styling the denote this is not a link?

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js (hunk 6 above)
Comment (spacedmonkey) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: See https://github.com/google/web-stories-wp/pull/8591#discussion_r685414122

**Comment by swissspidy** [comment]
> > I'm curious your thoughts about creating constants for the capabilities so that if someone else is trying to check these in the future for a new feature there's a place to note what these are rather than typing the string out fresh every time:
> 
> I am not sure what you mean here. In both editor and dashboard, the capability is stored with the story, making it easy to get later. What do you mean by a const here?

I _think_ Brittany means extracting the strings like `'wp:action-edit'` and `'wp:action-delete'` into constants.

For example, in `serializers/stories.js` you do:

```js
  const capabilities = {
    hasEditAction: Object.prototype.hasOwnProperty.call(
      links,
      'wp:action-edit'
    ),
    hasDeleteAction: Object.prototype.hasOwnProperty.call(
      links,
      'wp:action-delete'
    ),
  };
```

So this could become something like:

```js
const REST_LINKS = {
  EDIT: 'wp:action-edit',
  DELETE: 'wp:action-delete',
};

  const capabilities = {
    hasEditAction: Object.prototype.hasOwnProperty.call(
      links,
      REST_LINKS.EDIT,
    ),
    hasDeleteAction: Object.prototype.hasOwnProperty.call(
      links,
      REST_LINKS.DELETE
    ),
  };
```

But of course `REST_LINKS` could be used in more places than just `serializers/stories.js`, for example also in `formattedStoriesArray.js`

But tbh not sure how useful it is to extract this into a const

**Comment by BrittanyIRL** [comment]
yup, i was asking how useful you thought it would be to do what Pascal outlined. i don't really care either way, just having this set up is nice. It's just the only bit of clean up that I could think of that would make this more readable than what you have so i wanted to ask.

**Comment by spacedmonkey** [comment]
> But of course REST_LINKS could be used in more places than just serializers/stories.js, for example also in formattedStoriesArray.js

Fixed.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js (hunk 6 above)
Comment (swissspidy) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: Regardless of link color discussed in https://github.com/google/web-stories-wp/pull/8591#discussion_r685414122, can you add the `h3` as per the above?

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js (hunk 4 above)
Comment (swissspidy) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: Changing color decreases contrast quite a bit, especially when there is no poster image, so it's grey on dark grey. That's also not ideal.

I think we should stick with primary for now & create a new ticket to come up with something suitable if needed.

Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: well, really the link as a title is a relic of the old structure and you can open the link in the context menu just fine. 

so maybe we just cut to the chase and make it a plain ol title and you use the menu to open a story.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js (hunk 6 above)
Comment (spacedmonkey) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/storyDisplayContent.js]: Good point. Changed to h3 - https://github.com/google/web-stories-wp/pull/8591/commits/38f6a81caf5ed67b82478e2aa5655cec42680116

**Comment by spacedmonkey** [comment]
@swissspidy What are the next steps for this PR?

**Comment by swissspidy** [comment]
> @swissspidy What are the next steps for this PR?

@spacedmonkey Discussion at https://github.com/google/web-stories-wp/pull/8591/files#r685444348 is still unresolved. Let's change the color back to `primary` for now and track possible a11y/UI enhancements in a new ticket.

After that it needs QA.

**Comment by spacedmonkey** [comment]
> Let's change the color back to primary for now and track possible a11y/UI enhancements in a new ticket.

I want to ensure that if I do this, that ticket will be action in the release. This is a UX that NEEDS to be fixed. Not denoting when something is and is not a link, is horrible UX.

File: assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/dashboard/app/views/myStories/content/storyGridItem/components.js]: I have created a breakout issue https://github.com/google/web-stories-wp/issues/8652

**Comment by spacedmonkey** [comment]
Follow up issue for styling - https://github.com/google/web-stories-wp/issues/8652

**Review by swissspidy — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
Thanks for the updates. I'll grab your follow up ticket for the title issue.
