### PR TITLE
Explore Templates: Restore Story Creation From Template

### LINKED ISSUE #10966: Templates: Unable to create templates
## Bug Description

After https://github.com/GoogleForCreators/web-stories-wp/pull/10452, users are unable to create stories from a template. 

I seeing the following error in the console. 

```
Warning: Failed prop type: The prop `story.title` is marked as required in `OutputStory`, but its value is `undefined`.
    at OutputStory (http://localhost:8899/wp-content/plugins/web-stories/assets/js/packages_story-editor_src_index_js.js:161999:7)
```

## Screenshots

https://user-images.githubusercontent.com/237508/158848840-5b0e8912-cfa3-4e21-b6ac-68a0b7464526.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Unable to create stories from templates! 

## Summary

in #10452 elements were moved and now we need to register types at the app root. this wasn't added to the dashboard. causing issues for creating stories from templates.

Should eliminate need for #10967 

## Relevant Technical Choices

Since I was in `dashboard.js` I removed the setAppElement there - following this comment from a little bit ago so that that redundancy is gone https://github.com/GoogleForCreators/web-stories-wp/pull/10469#discussion_r800825893 

## User-facing changes

Functionality to create stories from templates should be restored. 

## Testing Instructions

See that e2e tests for creating story from template are passing.
Make story from template using 'use template' button in both explore templates and in the template modal. 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10966

### CODE REVIEW

File: packages/dashboard/src/dashboard.js [hunk 1]
```diff
@@ -49,10 +51,10 @@ function Dashboard({ config, children }) {
     ...externalDesignSystemTheme,
     colors: lightMode,
   };
-  // Set up modal focus trap on app's mount
 
-  document.body.setAttribute('id', 'dashboardWrapper');
-  setAppElement('#dashboardWrapper > div:first-of-type');
+  useEffect(() => {
```
Comment (BrittanyIRL) [inline packages/dashboard/src/dashboard.js:55]: mirroring https://github.com/GoogleForCreators/web-stories-wp/pull/10452/files#diff-47e7830ca8c2d9c95c192f6b39f5e873fed86b2c627d8fe0498e9b14f535980f

File: packages/wp-dashboard/src/api/story.js [hunk 2]
```diff
@@ -160,7 +160,13 @@ export const createStoryFromTemplate = async (config, template) => {
       status: 'auto-draft',
       featuredMedia: {
         id: 0,
+        height: 0,
+        width: 0,
+        url: '',
       },
+      publisherLogo: {},
+      terms: {},
+      title: '',
```
Comment (BrittanyIRL) [inline packages/wp-dashboard/src/api/story.js:169]: silencing warnings

**Review by BrookeGraham — APPROVED** [review]
Nice. I can create stories again!

**Review by maxyinger — APPROVED** [review]
