### PR TITLE
Color Picker: use '000000' instead of 'transparent'.

### LINKED ISSUE #7896: Transparency filter shows the word "#transparent" in the filter control
## Bug Description

When you set apply a filter to an object, and open the color picker to to set the gradient curves, and colour picker is in the bottom left color #00000 and the opacity is set to 100% (ie transparent), it displays the word "transparent" instead of showing the color hex code

## Expected Behaviour

Should probably just still show the color hex code regardless

## Steps to Reproduce

1. Select an object in the canvas that is eligible to have a filter applied
2. Select the Linear filter
3. open the color picker to set the curves for the gradient
4. ensure that the color selected is bottom left corner ie: #000000
5. set the transparency slider to 0%

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Uses '000000' as the display value instead of `transparent` which is used by default by the color picker library.

## Testing Instructions
1. Add a shape.
2. Open the color picker and go to the Custom Color picker.
3. Set the color to black ('000000')
4. Now set the opacity to 0.
5. Verify that '000000' is displayed in the hex input of the Color Picker. Click on the value to enter edit mode of the input and verify it displays '000000' there, too.

- [ ] This is a non-user-facing change and requires no QA

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7896

### CODE REVIEW

File: packages/story-editor/src/components/colorPicker/editablePreview.js [hunk 1]
```diff
@@ -131,11 +131,14 @@ function EditablePreview({ label, value, width, format, onChange }) {
     );
   }
 
+  // The value is set to 'transparent' by the library if it's black with 0 opacity.
```
Comment (barklund) [inline packages/story-editor/src/components/colorPicker/editablePreview.js:134]: Is that the underlying `react-color` library, that does this? Is that a breaking change?

**Review by barklund — APPROVED** [review]

File: packages/story-editor/src/components/colorPicker/editablePreview.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/components/colorPicker/editablePreview.js:134]: Yep, that's the underlying `react-color`, it displays `transparent` by default if it's `000000` and opacity `0`. Shouldn't be a breaking change, all seems to work well. If that's what you mean :)
