### PR TITLE
FTUE: Fix Nav button padding

### LINKED ISSUE #6257: Tighten padding on previous and next buttons
Per @tmagalhaes-huge during bug bash
> Padding between “Previous” and “Next” buttons should be tighter, 16px

Also while here, make sure focus state isn't cut off anywhere: 
>  Focus state of “all tips”, “previous” and “next” buttons is cut off at the bottom, see below:
Screen Shot 2021-02-08 at 11 19 58 AM

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Found in Bug Bash 1.4.0

## Summary
Adjusts the padding so nav buttons have the correct spacing. Also makes it so the focus outline is presented better.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
Updated Focus Styles & spacing on FTUE nav buttons
Screen Shot 2021-02-09 at 9 27 56 AM

## Testing Instructions
-> Enable quick tips
-> visit editor
-> expand help center
-> see that the next/prev button spacing looks like image above
-> tab onto button and see that focus styles look correct

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.Follow Testing instructions above

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6257

### CODE REVIEW

File: assets/src/edit-story/components/helpCenter/navigator/components.js [hunk 1]
```diff
@@ -35,6 +35,13 @@ export const NavBar = styled.div`
 
 export const NavButton = styled(Button)`
   ${themeHelpers.expandTextPreset(({ label }, { MEDIUM }) => label[MEDIUM])}
+  ${({ theme }) =>
+    themeHelpers.focusableOutlineCSS(
+      theme.colors.border.focus,
+      theme.colors.bg.secondary
+    )}
+  padding: 2px 6px;
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/helpCenter/navigator/components.js:43]: makes sense!

**Review by BrittanyIRL — APPROVED** [review]
Looks good.

Sorry for not catching this edge case - makes sense though with the plain version of the button and needing the secondary background. Glad @samwhale got that update for focus done last week. 

good focus

**Review by samwhale — APPROVED** [review]
Bravo 👏
