### PR TITLE
Fix Toggle space and Rotation Angle exceeding 360

### LINKED ISSUE #891: Lack of margin on aspect ratio lock button
## Bug Description

The lock icon could use some breathing here:

Screenshot 2020-03-31 at 16 40 01

Compare with Figma:

Screenshot 2020-03-31 at 16 41 46

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #892: Rotation angle exceeding 360 degrees
## Bug Description

Let's keep this within 0 and 360:

image (4)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by obetomuniz**
Fixes #892
Fixes #891

### CODE REVIEW

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 1]
```diff
@@ -47,10 +47,20 @@ const BoxedNumeric = styled(Numeric)`
...
+    margin: 0 10px;
+  }
+`;
+
 function isNum(v) {
   return typeof v === 'number' && !isNaN(v);
 }
 
+function formatRotationAngleField(v) {
+  return v >= 360 ? 360 : v;
```
Comment (wassgha) [inline assets/src/edit-story/components/panels/sizePosition.js]: is it this or `v % 360`?

Comment (dvoytenko) [reply assets/src/edit-story/components/panels/sizePosition.js]: It's definitely mod.

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 2]
```diff
@@ -199,7 +209,9 @@ function SizePositionPanel({
           suffix={__('Rotate', 'web-stories')}
           symbol={_x('°', 'Degrees, 0 - 360. ', 'web-stories')}
           value={rotationAngle}
-          onChange={(value) => pushUpdate({ rotationAngle: value })}
+          onChange={(value) =>
+            pushUpdate({ rotationAngle: formatRotationAngleField(value) })
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js]: `value === MUTLIPLE_VALUE` and `value === ''` are valid values here. I recommend something like `typeof value === 'number' ? value % 360 : value`

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/masks/output.js [hunk 3]
```diff
@@ -84,8 +84,9 @@ export default function WithMask({
         ...(!isBackground
           ? {
               clipPath: `url(#${maskId})`,
-              // stylelint-disable-next-line property-no-vendor-prefix
+              /* stylelint-disable */
               WebkitClipPath: `url(#${maskId})`,
+              /* stylelint-enable */
```
Comment (wassgha) [inline assets/src/edit-story/masks/output.js]: This is already fixed in master

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 4]
```diff
@@ -47,10 +47,20 @@ const BoxedNumeric = styled(Numeric)`
...
+    margin: 0 10px;
+  }
+`;
+
 function isNum(v) {
   return typeof v === 'number' && !isNaN(v);
 }
 
+function formatRotationAngleNumber(v) {
+  return v > 360 ? v % 360 : v;
```
Comment (ndev1991) [inline assets/src/edit-story/components/panels/sizePosition.js]: Maybe better limit the input to 359 for example? This means when the user input 38 and then 0, it will changed to 20. Maybe it confusing users? @dvoytenko

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 5]
```diff
@@ -47,10 +47,20 @@ const BoxedNumeric = styled(Numeric)`
   border-radius: 4px;
 `;
 
+const StyledToggle = styled(Toggle)`
+  + span {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js]: What does "+" do here? Is that for the sibling selector? Can we instead place margin on the right styled element instead? Siblings selectors are rather fragile and perform really poorly.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 4 above)
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js]: Just `v % 360` is enough.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 6]
```diff
@@ -47,6 +47,14 @@ const BoxedNumeric = styled(Numeric)`
   border-radius: 4px;
 `;
 
+const StyledLocked = styled(Locked)`
+  margin: 0 10px;
+`;
+
+const StyledUnlocked = styled(Unlocked)`
+  margin: 0 10px;
+`;
```
Comment (barklund) [inline assets/src/edit-story/components/panels/sizePosition.js]: Wouldn't a single wrapper be DRY'er here?

```js
const Wrapper = styled.span`
  margin: 0 10px;
`;
```

And then further down:
```js
icon={<Wrapper><Locked /></Wrapper>}
uncheckedIcon ={<Wrapper><Unlocked /></Wrapper>}
```

It's of course an unnecessary DOM element, which I'm also not in favor of.

Alternatively it could be a `styled.css` declaration:

```js
const withMargin = css`margin: 0 10px;`;
const StyledLocked = styled(Locked)`${withMargin}`;
const StyledUnlocked = styled(Unocked)`${withMargin}`;
```

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 7]
```diff
@@ -199,7 +207,11 @@ function SizePositionPanel({
           suffix={__('Rotate', 'web-stories')}
           symbol={_x('°', 'Degrees, 0 - 360. ', 'web-stories')}
           value={rotationAngle}
-          onChange={(value) => pushUpdate({ rotationAngle: value })}
+          onChange={(value) =>
+            pushUpdate({
+              rotationAngle: isNum(value) ? value % 360 : value,
+            })
+          }
```
Comment (barklund) [inline assets/src/edit-story/components/panels/sizePosition.js]: Should a non-num value also be pushed upstream? Would that not make the element jump weirdly around on screen if typing something like `33.3` when you reach the decimal point?

Comment (barklund) [reply assets/src/edit-story/components/panels/sizePosition.js]: We've solved this elsewhere by controlling the value internally and only pushing valid values upstream (plus updating local value from upstream in a `useEffect`). However, we might get away with limiting this input completely to digits only and completely circumvent the need for an `isNum` check all together.

**Review by barklund — COMMENTED** [review]
A couple of comments.

**Comment by wassgha** [comment]
This does close those two issues, no? Why is it just related?

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 7 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/panels/sizePosition.js]: Yeah. I think it does push it upstream here.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 4 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/panels/sizePosition.js]: It's a good point on the iterative editing. We could pass the value as is, but instead use `usePresubmitHandler` to do `x % 360` to "normalize" it for submit.

Comment (dvoytenko) [reply assets/src/edit-story/components/panels/sizePosition.js]: That will mean that the `pushUpdate` could simply be: `pushUpdate({rotationAngle: value})`. Which might also be simpler.

Comment (obetomuniz) [reply assets/src/edit-story/components/panels/sizePosition.js]: So we should allow the user input 1000, and only on submit, get 1000 % 360 (280), right? Just push this case using `usePresubmitHandler` / `pushUpdate({ rotationAngle: value })`.

Comment (obetomuniz) [reply assets/src/edit-story/components/panels/sizePosition.js]: Kapture 2020-04-02 at 0 59 46

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 8]
```diff
@@ -131,6 +131,12 @@ function SizePositionPanel({
   );
 
   usePresubmitHandler(({ rotationAngle: newRotationAngle }) => {
+    const isRotationAngle = Boolean(newRotationAngle);
+
+    if (!isRotationAngle) {
+      return null;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js]: Nit: this is correct, but feels a bit fragile because it will trigger also on `newRotationAngle === 0`. Perhaps we can keep this as is. Or we can document it in comments that 0 value is expected here and doesn't need update. Or even simpler, we can send `0` to the code below, which works just as well for zeros.

**Review by dvoytenko — APPROVED** [review]
Approved with one nit to consider.

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 4 above)
Comment (wassgha) [reply assets/src/edit-story/components/panels/sizePosition.js]: Yup looks good!

**Review by wassgha — APPROVED** [review]
