### PR TITLE
Fix useLoadStory to load the publish date in UTC time

### LINKED ISSUE #1216: A new post is by default scheduled in the future if user is ahead of UTC
## Bug Description

When you create a new post, it is by default scheduled in the future (at least if you're in the US).

It seems to be scheduled 4 hours in the future when in EST, which corresponds to UTC.

## Expected Behaviour

The initial timestamp for a new post should be created and/or interpreted in the correct timezone.

## Steps to Reproduce

* Change your timezone on your computer to be ahead of UTC (e.g. EST at UTC-04)
* Create a new post
* See that the "publish" button is actually labelled "schedule".
* Go to the document panel
* See that the publish date is set to 4 hours ahead of now.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by cvolzke4**
When a new story is created, getStoryById is called to return the story using a wordpress API, which uses the server time for the publish 'date' field (usually expressed in UTC) without a timezone qualifier.

This change instead uses the 'date_gmt' field with a timezone qualifier.

See also:
https://developer.wordpress.org/rest-api/reference/posts#schema-date

### CODE REVIEW

File: assets/src/edit-story/app/api/testUtils/story.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+/*
```
Comment (dvoytenko) [inline assets/src/edit-story/app/api/testUtils/story.js]: We've been doing `test/_utils.js` for testing helpers.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/**
+ * External dependencies
+ */
+import { mount } from 'enzyme';
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/effects/test/useLoadStory.js]: /to @swissspidy to decide if we're ok using enzyme for this. So far we've been using https://testing-library.com/ which i think has lots of the same things.

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Mostly LGTM. Just punting this to @swissspidy to decide on test library.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: We should definitely not start mixing testing libraries here.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+jest.mock('../../../', () => ({
+  useHistory: jest.fn(),
+  useAPI: jest.fn(),
+}));
+
+function TestComponent({ restore }) {
+  useLoadStory({ storyId: 11, shouldLoad: true, restore });
+  return null;
+}
```
Comment (barklund) [inline assets/src/edit-story/app/story/effects/test/useLoadStory.js]: To test a hook, please use `renderHook` from `@testing-library/react-hooks`. This function can also take another component as `wrapper` in order to [setup the required mock contexts](https://github.com/testing-library/react-hooks-testing-library/blob/master/docs/usage/advanced-hooks.md#context).

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+ * Internal dependencies
+ */
+import useLoadStory from '../useLoadStory';
+import { createStory } from '../../../api/testUtils/story';
+import { useAPI, useHistory } from '../../../';
+
+jest.mock('../../../', () => ({
+  useHistory: jest.fn(),
+  useAPI: jest.fn(),
+}));
```
Comment (barklund) [inline assets/src/edit-story/app/story/effects/test/useLoadStory.js]: To mock these, we normally create a valid context provider as a wrapper for the component, with mock functions. In this case, you don't even need the response from `clearHistory`, so it doesn't need to be a mock function, just a dummy function.

See for instance [`library/test/_utils/index.js`](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/components/library/test/_utils/index.js).

File: assets/src/edit-story/app/api/testUtils/story.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/api/testUtils/story.js]: We've [explicitly excluded `_utils`](https://github.com/google/web-stories-wp/blob/master/tests/js/jest.config.js#L44) from the test runner for this purpose.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+          date_gmt: '2020-01-01T20:20:20',
+        })
+      )
+    );
+
+    const restore = jest.fn();
+    await mount(<TestComponent restore={restore} />);
+    expect(restore.mock.calls[0][0].story.date).toStrictEqual(
+      '2020-01-01T20:20:20Z'
+    );
```
Comment (barklund) [inline assets/src/edit-story/app/story/effects/test/useLoadStory.js]: IMHO, this reads cleaner:

```js
    expect(restore).toHaveBeenCalledWith(
      expect.objectContaining(
        { story: { date: '2020-01-01T20:20:20Z' } },
      ),
    );
```

**Review by barklund — CHANGES_REQUESTED** [review]
Some notes on testing hooks using react testing library.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 2 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: +1, updated to use @testing-library/react-hooks instead.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 3 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: Updated.

File: assets/src/edit-story/app/api/testUtils/story.js (hunk 1 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/api/testUtils/story.js]: Done.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 4 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: Done, thanks :)

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 5 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: Updated to use objectContaining.
objectContaining doesn't seem to work with nested levels, so I used it for the attributes under 'story', but not including 'story' itself.

File: assets/src/edit-story/app/story/effects/test/useLoadStory.js (hunk 4 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/story/effects/test/useLoadStory.js]: I've also mocked clearHistory, since it calls a reducer dispatch which seems to prevent the  getStoryWithId await from finishing.

**Review by dvoytenko — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@barklund mind taking another look, since you requested changes before?

**Review by barklund — APPROVED** [review]
LGTM
