### PR TITLE
Pre-Publish Checklist: Update selectors in checks

### LINKED ISSUE #8289: Code Quality: Update Selectors in checks PPCv2.0
Porting over PPC to the new structure in PPCv2.0 we were just trying to get all the old code into the new structure. The old code took the entire story when seeing if a check was passing and failing. When we moved everything over to the new structure, we were trying to alter everything as little as possible because there were a lot of moving pieces and we didn't want to introduce more surface area for there to be regressions.

Because of the approach above, a lot of the checks are still pulling the entire story object:
```
const story = useStory();
const isCheckRendered = checkStoryForSomething(story);
```

However, with the new structure, we have better access to the context selector, so we can fine tune these `useStory()` uses to have a more fine tuned selector and only perform the check on the part of the story it needs vs the whole story object.

This should increase performance of the checks because they should only be re-rendering when parts of the story they're checking against update.

Completion of this task includes going through every check and making sure each check only re-renders and runs its check of the necessary parts of the story.

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Part of perf sprint

## Summary
Just updates the selectors to be more specific and run only when the necessary parts of the story change.

## Relevant Technical Choices
If it was a simple boolean check like `someString.length > SOME_NUMBER` I didn't memoize because I figured the memoize check would be just as expensive.

Also removed any checks within the useStory like:
```
const violatingPages = useStory(({ state: { pages } }) => filterPages(pages, someFilter));
```
because this run the check every time the story changes. Updated to something like this so the check only ran when `pages` updates:
```
const pages = useStory(({ state: { pages } }) => pages);
const violatingPages = useMemo(() => filterPages(pages, someFilter), [pages]);
```

## To-do
NA

## User-facing changes
NA

## Testing Instructions
Check the unit tests and see that they're good. Also run the editor and open up the checklist and see that nothings failing within the checklist.

### QA
NA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8289

### CODE REVIEW

File: assets/src/edit-story/components/checklist/checks/storyPosterAttached.js [hunk 1]
```diff
@@ -29,15 +29,15 @@ import { PRIORITY_COPY } from '../constants';
...
+export function storyHasNoPosterAttached(featuredMedia) {
   return (
-    typeof story.featuredMedia?.url !== 'string' || hasNoFeaturedMedia(story)
+    typeof featuredMedia?.url !== 'string' ||
+    hasNoFeaturedMedia({ featuredMedia })
   );
 }
 
 export function StoryPosterAttached() {
-  //@TODO refine this context selector and storyHasNoPosterAttached to run more selectively
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/checklist/checks/storyPosterAttached.js:39]: ✅

**Review by BrittanyIRL — APPROVED** [review]
Awesome! 
| Before | After |
| --- | --- | 
| Screen Shot 2021-07-13 at 3 02 11 PM | Screen Shot 2021-07-13 at 3 01 57 PM |
