### PR TITLE
Bugfix: Fix RTL toggle 

### LINKED ISSUE #6548: Design System: RTL toggle button
## Bug Description

Previously this was just in storybook and we had no way to really know what it would do in RTL within wordpress, this was bound to happen to some of the components. Just needs minor tweaking.

## Expected Behaviour

Toggle should stay in bounds.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Toggle was lookin at us funny in RTL (this is not in main yet): 

## Summary

Fixes RTL styling for toggle.

## Relevant Technical Choices

I guess the stylis rtl plugin doesn't change the `transform: translate3d(...)` attribute when changing from LTR to RTL. Unfortunately I had to remove that.

We lose some performance but it isn't noticeable.

## To-do

none

## User-facing changes

|Before|After|
|--|--|
|broken|fix|

## Testing Instructions

1. Storybook -> Design System -> Toggle
2. switch to RTL
3. use the toggle and verify that it doesn't look wonky anymore

### QA

- [x] This is a non-user-facing change and requires no QA

### UAT

- [x] UAT should use the same steps as above.

1. Storybook -> Design System -> Toggle
2. switch to RTL
3. use the toggle and verify that it doesn't look wonky anymore

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6548

### CODE REVIEW

File: assets/src/design-system/components/toggle/stories/index.js [hunk 1]
```diff
@@ -78,55 +79,13 @@ export const _default = () => {
...
-            label={text('Toggle 4 Label', 'Disabled')}
-            disabled
-          />
-        </Row>
-      </Container>
-      <DarkThemeProvider>
-        <Container darkMode>
+    <StyleSheetManager
+      stylisPlugins={boolean('isRTL', false) ? [stylisRTLPlugin] : []}
+    >
```
Comment (samwhale) [inline assets/src/design-system/components/toggle/stories/index.js]: diff is weird but this is all I added here

File: assets/src/design-system/components/toggle/index.js [hunk 2]
```diff
@@ -143,7 +141,7 @@ const ToggleContainer = styled.div(
         }
 
         ~ ${Circle}:after {
-          transform: translate3d(${CIRCLE_FINAL_POSITION}px, 0, 0);
+          left: ${CIRCLE_FINAL_POSITION}px;
```
Comment (samwhale) [inline assets/src/design-system/components/toggle/index.js:144]: 😭

File: assets/src/design-system/components/toggle/stories/index.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/design-system/components/toggle/stories/index.js]: See also #6544. Basically, we should rather wrap everything in `<StyleSheetManager>` globally. (not in this PR)

File: assets/src/design-system/components/toggle/index.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/design-system/components/toggle/index.js:144]: Why was this needed? Is the property otherwise not automatically flipped?

Comment (samwhale) [reply assets/src/design-system/components/toggle/index.js:144]: Yeah exactly, the property was not automatically flipped so it looked like this:


The initial position flips correctly but the transform did not 😕

**Review by BrittanyIRL — APPROVED** [review]
👍  thanks for fixing this!

**Review by embarks — APPROVED** [review]
it was a joy to review

**Review by maxyinger — APPROVED** [review]

**Comment by samwhale** [comment]
This is not easy to test since it is not visible in storybook or the application yet. It will be testable when either:
1. We add a way to switch to RTL in storybook: https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6544
2. This PR gets merged:https://github.com/google/web-stories-wp/pull/6549. It has a toggle component in the panel
