### PR TITLE
Media Hotlinking: Improve the logic in case of empty value

### LINKED ISSUE #8847: Media hotlinking error handling
## Bug Description

Noticed while testing #8806

When clicking into the input field and then moving out of it, `https://` is inserted in the input field and subsequently flagged as invalid URL.

I am then unable to clear the input field, so it's impossible for me to see the list of allowed file types.

I can not even select the text below the input field due to this.

## Expected Behaviour

If the input field is empty, this should not be happening.

## Steps to Reproduce

See video below

## Screenshots

https://user-images.githubusercontent.com/841956/131357539-8c34bfdd-a1cc-4f7a-94db-ac4018dbfb13.mov

## Additional Context

- Plugin Version: 1.11.0-alpha
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by miina**
## Summary
Improves how the messages are handled in case of empty link values.
- When link is empty, Insert button doesn't do anything
- When there's an error and the user changes the link, the informative message about file types to use is displayed again
- When the input is empty and the users tabs away from it, nothing happens.

## User-facing changes
empty-link

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8847

### CODE REVIEW

**Comment by miina** [comment]
@swissspidy Let me know if you think this new logic makes sense -- I've added a gif and description of how it works now.

File: packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js [hunk 1]
```diff
@@ -75,12 +75,24 @@ function HotlinkModal({ isOpen, onClose }) {
...
+        setErrorMsg(__('Invalid link.', 'web-stories'));
+      }
     }
   }, [link]);
 
+  const onChange = useCallback(
+    (value) => {
+      if (!value?.length) {
+        setErrorMsg(null);
+      }
```
Comment (barklund) [inline packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js]: Why only clear the message if empty? I think the message should always be cleared on change.

If you enter a bad URL, try to submit, see the error message, select everything and then paste a valid URL into the input, it still shows the message, which is misleading.

So, perhaps just always clear the error on change?

File: packages/story-editor/src/components/library/panes/media/local/hotlink/useInsert.js [hunk 2]
```diff
@@ -111,6 +111,9 @@ function useInsert({ link, setLink, setErrorMsg, onClose }) {
   );
 
   const onInsert = useCallback(() => {
+    if (!link?.length) {
```
Comment (barklund) [inline packages/story-editor/src/components/library/panes/media/local/hotlink/useInsert.js]: Isn't this just `if (!link)`?

File: packages/story-editor/src/components/library/panes/media/local/karma/hotlink.karma.js [hunk 3]
```diff
@@ -54,12 +54,25 @@ describe('Embedding hotlinked media', () => {
...
+    await waitFor(() => expect(dialog.textContent).toContain('Invalid link'));
+
+    // Delete the value, verify now the informative message show instead again.
+    await fixture.events.click(input, { clickCount: 3 });
+    await fixture.events.keyboard.press('Del');
+    dialog = screen.getByRole('dialog');
+    await waitFor(() => expect(dialog.textContent).toContain('You can insert'));
+
     await fixture.events.click(input);
     await fixture.events.keyboard.type('https://example.jpg');
```
Comment (barklund) [inline packages/story-editor/src/components/library/panes/media/local/karma/hotlink.karma.js:71]: But that's not a valid link? 😱

Comment (miina) [reply packages/story-editor/src/components/library/panes/media/local/karma/hotlink.karma.js:71]: No, it's not a valid image link, that's why it will display an error (including `Media failed to load`).

File: packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js]: Hm, yep, makes sense.

**Review by barklund — APPROVED** [review]
🌐
