### PR TITLE
Media: Ensure duration is always present on resources

### LINKED ISSUE #5030: Media: Duration not always present on resources
## Bug Description

Upon saving we use `getLongestMediaElement` to find the longest-playing, non-looping video on a page and change page advancement to be based on that video instead of the user's selection.

`getLongestMediaElement` uses `element.resource.length` for its calculation, which holds the duration in seconds.

Oddly enough, that field is not always present, while `lengthFormatted` is. Which means the advance-after-video-plays logic is not always working as intended and there's no way to fix it as a user.

Perhaps it's because the video was uploaded or inserted in a different way?

**To-do:**

* [x] Figure out why `length` is sometimes missing
* [ ] Fix it

Here's an example JSON blob of a story where `length` is sometimes missing from resources:

```json
{"version":24,"pages":[{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":-167,"y":-118,"width":412,"height":736,"mask":{"type":"rectangle"},"isBackground":true,"id":"d10ff0fb-1ad9-49be-9bac-7829850221bb","type":"image","scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":412,"height":736,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}}},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"x":1,"y":-57,"width":412,"height":732,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"910df1f0-97f6-4e43-bc16-8e1c7d77b9b5","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72.png","width":720,"height":1077,"id":20,"title":"Group 72","alt":"Group 72","local":true,"sizes":{"medium":{"file":"Group-72-201x300.png","width":201,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-201x300.png"},"large":{"file":"Group-72-685x1024.png","width":685,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-685x1024.png"},"thumbnail":{"file":"Group-72-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-150x150.png"},"web-stories-poster-portrait":{"file":"Group-72-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-640x853.png"},"web-stories-poster-landscape":{"file":"Group-72-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-720x640.png"},"web-stories-poster-square":{"file":"Group-72-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-640x640.png"},"web-stories-publisher-logo":{"file":"Group-72-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-96x96.png"},"web-stories-thumbnail":{"file":"Group-72-150x224.png","width":150,"height":224,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72-150x224.png"},"full":{"file":"Group-72.png","width":720,"height":1077,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-72.png"}}},"x":1,"y":37,"width":413,"height":618,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"6a6a8fb9-8802-48c8-ba67-38a731b3c7ec","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T10:16:40","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia.png","width":174,"height":179,"posterId":0,"id":481,"title":"cover_paul_paris_ia","alt":"cover_paul_paris_ia","local":false,"sizes":{"medium":{"file":"cover_paul_paris_ia-292x300.png","width":292,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia-292x300.png"},"thumbnail":{"file":"cover_paul_paris_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia-150x150.png"},"web-stories-publisher-logo":{"file":"cover_paul_paris_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia-96x96.png"},"web-stories-thumbnail":{"file":"cover_paul_paris_ia-150x154.png","width":150,"height":154,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia-150x154.png"},"full":{"file":"cover_paul_paris_ia.png","width":348,"height":357,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/cover_paul_paris_ia.png"}}},"type":"image","x":27,"y":15,"width":359,"height":359,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"e1768136-971c-4b59-a5c8-2c932bf18055"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Logo-web-stories-circle.png","width":80,"height":78,"id":16,"title":"Logo web stories circle","alt":"Logo web stories circle","local":true,"sizes":[]},"x":327,"y":44,"width":44,"height":42,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"e69b5798-ae40-46e0-8363-d3117b2a7ab5","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":24,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"initial","padding":{"locked":true,"horizontal":1,"vertical":1},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">&nbsp;Editorial Patterns:<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">&nbsp;An Overview<\/span>","width":238,"height":66,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"3a315532-8e98-4c23-9430-c730990a0164","x":45,"y":284,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-2.png","width":90,"height":40,"id":22,"title":"Group 2","alt":"Group 2","local":true,"sizes":[]},"x":50,"y":249,"width":64,"height":29,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"57dd6734-c512-4ad0-9606-915de15695f2","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; font-style: italic; color: #030028\">NO.8<\/span>","fontWeight":400,"width":80,"height":21,"scale":100,"focalX":50,"focalY":50,"marginOffset":1.7000000000000028,"basedOn":"dab2b1ff-74cf-4c06-9d91-dd295f5715ea","id":"7df3a31a-ba64-440e-8bba-9d175479eef9","x":42,"y":253,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5.png","width":240,"height":80,"id":14,"title":"Rectangle 5","alt":"Rectangle 5","local":true,"sizes":{"thumbnail":{"file":"Rectangle-5-150x80.png","width":150,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-150x80.png"},"web-stories-publisher-logo":{"file":"Rectangle-5-96x80.png","width":96,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-96x80.png"},"web-stories-thumbnail":{"file":"Rectangle-5-150x50.png","width":150,"height":50,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-150x50.png"},"full":{"file":"Rectangle-5.png","width":240,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5.png"}}},"x":133,"y":592,"width":136,"height":45,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"483f10d8-f5bc-421a-9fdb-f8df507a3942","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":20,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; color: #030028\">OH, L\u00c0, L\u00c0<\/span>","fontWeight":400,"x":120,"y":601,"width":160,"height":27,"scale":100,"focalX":50,"focalY":50,"id":"48173a80-d155-4ec4-9ccd-e22b1306bb02","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":12,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"x":177,"y":550,"id":"54c12bfc-2de1-4635-9c3a-e83430f81b09","basedOn":"ebb63877-d8bd-4e4a-990e-1d198626e327","content":"<span style=\"font-weight: 700; font-style: italic; color: #0bdffe; letter-spacing: 0.2em\">WITH PAUL BAKAUS<\/span>","fontWeight":400,"width":159,"height":17,"scale":100,"focalX":50,"focalY":50,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1.png","width":467,"height":280,"id":15,"title":"Group 1","alt":"Group 1","local":true,"sizes":{"medium":{"file":"Group-1-300x180.png","width":300,"height":180,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1-300x180.png"},"thumbnail":{"file":"Group-1-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1-150x150.png"},"web-stories-publisher-logo":{"file":"Group-1-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1-96x96.png"},"web-stories-thumbnail":{"file":"Group-1-150x90.png","width":150,"height":90,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1-150x90.png"},"full":{"file":"Group-1.png","width":467,"height":280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-1.png"}}},"x":60.5,"y":380,"width":275,"height":165,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"65ba8018-64f2-457c-aff6-f40e000bd2e4","alt":"Storytime","type":"image"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"ad7c3f43-37cc-4541-8f9c-692fb1ff1dcd","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"6ec67e44-8d6a-434b-92ac-2215a5bfad28","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":72,"y":216,"width":167,"height":299,"mask":{"type":"rectangle"},"isBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"image","scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":167,"height":299,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}}},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","id":"9343764a-7052-4763-903a-4c6a12b2b115","content":"<span style=\"font-weight: 600; font-style: italic; color: #fff; letter-spacing: 0.02em\">Finding the right story and the right way to tell it,<\/span>","x":26,"y":40,"width":370,"height":71,"scale":100,"focalX":50,"focalY":50},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"type":"video","x":-2,"y":261,"width":414,"height":414,"scale":100,"focalX":50,"focalY":50,"mask":{"type":"rectangle"},"id":"4da0e385-8303-4e76-bb6d-e68fc1163b74","resource":{"type":"video","mimeType":"video\/mp4","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_2.mp4","width":330,"height":330,"posterId":0,"id":440,"lengthFormatted":"0:03","title":"WST008_for Webstories_2","alt":"WST008_for Webstories_2","local":false,"sizes":[]},"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/poster_2-300x300.png"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; font-style: italic; color: #de1aad; letter-spacing: 0.02em\">is 90% of your job.<\/span>","fontWeight":400,"x":26,"y":111,"width":385,"height":54,"scale":100,"focalX":50,"focalY":50,"id":"4b61a6d7-2e0e-47c5-9f1f-6cda9da8d371"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"a2ad410a-cf09-4f32-9e03-6e757540689b","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"32878375-9ccc-4ccc-8b29-04bca5a91160","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true,"horizontal":true},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg","width":330,"height":586,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium":{"width":169,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"width":576,"height":1024,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"full":{"width":1440,"height":2560,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":-28,"y":-43,"width":406,"height":720,"mask":{"type":"rectangle"},"isBackground":true,"id":"47d798cf-aadb-4d7b-8c4d-f71d808ff519","alt":null,"type":"image","backgroundOverlay":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1.png","width":253,"height":288,"id":19,"title":"GettyImages-1164835900-Converted-1","alt":"GettyImages-1164835900-Converted-1","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1-150x150.png"},"medium":{"width":264,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1-264x300.png"},"full":{"width":506,"height":576,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1.png"}}},"type":"image","x":17,"y":277,"width":485,"height":552,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"1dc63c19-a65c-44d6-a878-5dfdf86b4a8f"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">THERE ARE<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">THREE STORY<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">DIMENSIONS<\/span>","width":425,"height":161,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"c9617af6-6e91-461f-b1ad-8eaf0df1a4f5","x":35,"y":41,"marginOffset":0,"type":"text","isBold":true},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":false,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-2-1.png","width":76,"height":36,"id":29,"title":"Group-2-1","alt":"Group-2-1","local":false,"sizes":{"thumbnail":{"width":150,"height":72,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-2-1-150x72.png"},"full":{"width":152,"height":72,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-2-1.png"}}},"type":"image","x":24.5,"y":6,"width":107,"height":48,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"aec4136e-5f02-476a-8fff-115620d0e7c5"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 800; font-style: italic; color: #030028\">OUTLINE<\/span>","fontWeight":400,"x":-26,"y":15.5,"width":206,"height":21,"scale":100,"focalX":50,"focalY":50,"id":"1b5dc3c4-1a8c-44ff-806d-8676a8b5f16c"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":2,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">by Perspective<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">by Function<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">and by Content<\/span>","fontWeight":400,"x":113,"y":232,"width":372,"height":137,"scale":100,"focalX":50,"focalY":50,"id":"73f4797d-bc36-4dc1-bb67-1d5aca7cfa31","marginOffset":12.796875},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_magenta.png","width":60,"height":20,"id":434,"title":"dot_magenta","alt":"dot_magenta","local":false,"sizes":{"full":{"width":120,"height":40,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_magenta.png"}}},"type":"image","x":35,"y":238,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"d265839b-dc2d-4263-888a-b30b2056cb62"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T02:36:57","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan.png","width":60,"height":20,"posterId":0,"id":432,"title":"dot_cyan","alt":"dot_cyan","local":false,"sizes":{"web-stories-publisher-logo":{"file":"dot_cyan-96x40.png","width":96,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan-96x40.png"},"full":{"file":"dot_cyan.png","width":120,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan.png"}}},"type":"image","x":35,"y":289,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"bca782af-aeac-4729-a437-eb0d3dc891e4"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T02:36:58","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau.png","width":60,"height":20,"posterId":0,"id":435,"title":"dot_hellblau","alt":"dot_hellblau","local":false,"sizes":{"web-stories-publisher-logo":{"file":"dot_hellblau-96x40.png","width":96,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau-96x40.png"},"full":{"file":"dot_hellblau.png","width":120,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau.png"}}},"type":"image","x":35,"y":340,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"961ee6b4-2258-45c3-8d92-4dbfc1cea990"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"774d288b-cf37-4616-b64e-0e60a9fb2ff5","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"d3bb973f-ae38-4d7b-a507-c64f77f43e20","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">PERSPECTIVE<\/span>","width":425,"height":54,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"5e4bdc95-e391-4f5d-999a-0fa06c45915e","x":39,"y":403,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T02:36:58","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_magenta.png","width":60,"height":20,"posterId":0,"id":434,"title":"dot_magenta","alt":"dot_magenta","local":false,"sizes":{"web-stories-publisher-logo":{"file":"dot_magenta-96x40.png","width":96,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_magenta-96x40.png"},"full":{"file":"dot_magenta.png","width":120,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_magenta.png"}}},"type":"image","x":40,"y":380,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"0e3e708d-ffab-4567-9f5c-be659f366ec6"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; font-style: italic; color: #030028\">1<\/span>","fontWeight":400,"x":-33,"y":380,"width":206,"height":21,"scale":100,"focalX":50,"focalY":50,"id":"6742881a-55d0-4ca0-ad81-4b542ebb63f5","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #07e1fe; letter-spacing: 0.02em\">First Person<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\"> Narrative<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">vs.<\/span>\n<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">Third Person<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\"> Narrative<\/span>","fontWeight":400,"x":38,"y":457,"width":372,"height":106,"scale":100,"focalX":50,"focalY":50,"id":"acda0dc2-f978-4327-8a1c-431de9683b0a","marginOffset":12.796875,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":41,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2.png","width":70,"height":141,"id":41,"title":"GettyImages-1164835900-Converted-03-2","alt":"GettyImages-1164835900-Converted-03-2","local":false,"sizes":{"thumbnail":{"width":140,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2-140x150.png"},"full":{"width":140,"height":282,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2.png"}}},"x":166,"y":333,"width":278,"height":558,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"9f199da5-0172-4c13-af15-a69d6c60397c","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"type":"video","x":0,"y":-58,"width":414,"height":414,"scale":100,"focalX":50,"focalY":50,"mask":{"type":"rectangle"},"id":"9623d18c-085d-4234-ab8e-aca721b6ce29","resource":{"type":"video","mimeType":"video\/mp4","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_4.mp4","width":330,"height":330,"posterId":0,"id":444,"lengthFormatted":"0:06","title":"WST008_for Webstories_4","alt":"WST008_for Webstories_4","local":false,"sizes":[]},"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/poster_4-300x300.png"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"961304b7-6195-4b03-aaca-5ab4aab5f727","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"3d13729b-832c-4ab7-97aa-71e706e23884","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau.png","width":330,"height":411,"id":436,"title":"drei_karten_blau","alt":"drei_karten_blau","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-150x150.png"},"medium":{"width":241,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-241x300.png"},"large":{"width":580,"height":723,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-821x1024.png"},"full":{"width":862,"height":1075,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau.png"}}},"type":"image","x":-142,"y":-73,"width":448,"height":560,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"325a4a8d-2bc1-4247-83b0-5a58fd035542"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_5.mp4","width":330,"height":586,"posterId":0,"id":451,"lengthFormatted":"0:05","title":"WST008_for Webstories_5","alt":"WST008_for Webstories_5","local":false,"sizes":[]},"controls":false,"loop":false,"autoPlay":true,"type":"video","x":-17,"y":-57,"width":242,"height":462,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"70056147-7698-4123-92f4-766bb6f40952","poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/poster_5-169x300.png"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Okay,<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">that<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">works<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">...<\/span>","fontWeight":400,"x":275,"y":3,"width":346,"height":215,"scale":100,"focalX":50,"focalY":50,"id":"7af4dbb1-1c54-4327-98e2-57c730aee837"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T07:12:24","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia.png","width":330,"height":562,"posterId":0,"id":446,"title":"mockup_what_to_do_paris_ia","alt":"mockup_what_to_do_paris_ia","local":false,"sizes":{"medium":{"file":"mockup_what_to_do_paris_ia-176x300.png","width":176,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-176x300.png"},"large":{"file":"mockup_what_to_do_paris_ia-600x1024.png","width":600,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-600x1024.png"},"thumbnail":{"file":"mockup_what_to_do_paris_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-150x150.png"},"medium_large":{"file":"mockup_what_to_do_paris_ia-768x1311.png","width":768,"height":1311,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-768x1311.png"},"1536x1536":{"file":"mockup_what_to_do_paris_ia-900x1536.png","width":900,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-900x1536.png"},"web-stories-poster-portrait":{"file":"mockup_what_to_do_paris_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-640x853.png"},"web-stories-poster-landscape":{"file":"mockup_what_to_do_paris_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-853x640.png"},"web-stories-poster-square":{"file":"mockup_what_to_do_paris_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-640x640.png"},"web-stories-publisher-logo":{"file":"mockup_what_to_do_paris_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-96x96.png"},"web-stories-thumbnail":{"file":"mockup_what_to_do_paris_ia-150x256.png","width":150,"height":256,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia-150x256.png"},"full":{"file":"mockup_what_to_do_paris_ia.png","width":1012,"height":1727,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_what_to_do_paris_ia.png"}}},"type":"image","x":192,"y":295,"width":210,"height":362,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"8a2b5470-cd90-443f-a368-76a3cbc69a37"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"6e94681d-97a6-4ddd-bade-229326bdf6fa","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"b4f55a6d-cece-471a-883e-65f06c24d3b9","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":true,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau.png","width":330,"height":411,"id":436,"title":"drei_karten_blau","alt":"drei_karten_blau","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-150x150.png"},"medium":{"width":241,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-241x300.png"},"large":{"width":580,"height":723,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau-821x1024.png"},"full":{"width":862,"height":1075,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/drei_karten_blau.png"}}},"x":91,"y":185,"width":448,"height":560,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"bda4885a-f40c-48a8-bb08-c2f647de972c","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_7.mp4","width":1080,"height":1920,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-86.jpeg","posterId":454,"id":453,"lengthFormatted":"0:11","title":"WST008_for Webstories_7","alt":"WST008_for Webstories_7","local":false,"sizes":[]},"controls":false,"loop":false,"autoPlay":true,"x":174,"y":271,"width":242,"height":462,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"83d98c4e-533e-4809-b431-a1cdb624aaa4","type":"video"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Better:<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">A story<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">about<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">you!<\/span>","fontWeight":400,"x":252,"y":3,"width":346,"height":215,"scale":100,"focalX":50,"focalY":50,"id":"faef16e1-cdf3-4af7-8e20-1187a359ab9b","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T07:20:05","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia.png","width":330,"height":552,"posterId":0,"id":447,"title":"mockup_how_i_paris_ia","alt":"mockup_how_i_paris_ia","local":false,"sizes":{"medium":{"file":"mockup_how_i_paris_ia-179x300.png","width":179,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-179x300.png"},"large":{"file":"mockup_how_i_paris_ia-612x1024.png","width":612,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-612x1024.png"},"thumbnail":{"file":"mockup_how_i_paris_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-150x150.png"},"medium_large":{"file":"mockup_how_i_paris_ia-768x1286.png","width":768,"height":1286,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-768x1286.png"},"1536x1536":{"file":"mockup_how_i_paris_ia-918x1536.png","width":918,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-918x1536.png"},"web-stories-poster-portrait":{"file":"mockup_how_i_paris_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-640x853.png"},"web-stories-poster-landscape":{"file":"mockup_how_i_paris_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-853x640.png"},"web-stories-poster-square":{"file":"mockup_how_i_paris_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-640x640.png"},"web-stories-publisher-logo":{"file":"mockup_how_i_paris_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-96x96.png"},"web-stories-thumbnail":{"file":"mockup_how_i_paris_ia-150x251.png","width":150,"height":251,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia-150x251.png"},"full":{"file":"mockup_how_i_paris_ia.png","width":1037,"height":1736,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/mockup_how_i_paris_ia.png"}}},"type":"image","x":20,"y":-31,"width":210,"height":352,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"13ab3c3d-8240-4749-aefd-176ffc1e5dd6"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"374b974f-4057-452a-baf0-5fff15a08815","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-26T07:41:24","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1.jpg","width":304,"height":540,"posterId":0,"id":449,"title":"bg_pattern_teil1","alt":"bg_pattern_teil1","local":false,"sizes":{"medium":{"file":"bg_pattern_teil1-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-169x300.jpg"},"large":{"file":"bg_pattern_teil1-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-576x1024.jpg"},"thumbnail":{"file":"bg_pattern_teil1-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-150x150.jpg"},"web-stories-poster-portrait":{"file":"bg_pattern_teil1-608x853.jpg","width":608,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-608x853.jpg"},"web-stories-poster-landscape":{"file":"bg_pattern_teil1-608x640.jpg","width":608,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-608x640.jpg"},"web-stories-poster-square":{"file":"bg_pattern_teil1-608x640.jpg","width":608,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-608x640.jpg"},"web-stories-publisher-logo":{"file":"bg_pattern_teil1-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-96x96.jpg"},"web-stories-thumbnail":{"file":"bg_pattern_teil1-150x266.jpg","width":150,"height":266,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1-150x266.jpg"},"full":{"file":"bg_pattern_teil1.jpg","width":608,"height":1080,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/bg_pattern_teil1.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":48,"y":0,"width":304,"height":540,"mask":{"type":"rectangle"},"isBackground":true,"id":"3b11cc20-98b4-4a84-ba82-be290119988d","alt":null,"type":"image","backgroundOverlay":{"color":{"r":0,"g":0,"b":0,"a":0.3}}},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">DIFFERENT<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">FUNCTIONAL&nbsp;<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">PATTERNS<\/span>","width":425,"height":161,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"fa486ff3-034a-4df1-9e29-0ea6330e5e1f","x":39,"y":23,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T02:36:57","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan.png","width":60,"height":20,"posterId":0,"id":432,"title":"dot_cyan","alt":"dot_cyan","local":false,"sizes":{"web-stories-publisher-logo":{"file":"dot_cyan-96x40.png","width":96,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan-96x40.png"},"full":{"file":"dot_cyan.png","width":120,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_cyan.png"}}},"x":40,"y":0,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"0449f403-4325-41d6-b1c8-2c9e2f5484c9","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; font-style: italic; color: #030028\">2<\/span>","fontWeight":400,"x":-33,"y":0,"width":206,"height":21,"scale":100,"focalX":50,"focalY":50,"id":"0ebfe8be-24bc-4604-8cc1-446e09042c7a","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Evergreen or<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">updating stories&nbsp;<\/span>","fontWeight":700,"x":175,"y":231,"width":206,"height":61,"scale":100,"focalX":50,"focalY":50,"id":"66f6e72b-4dff-403d-a714-b87d7e273e91"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Live<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">stories<\/span>","fontWeight":400,"x":233,"y":333,"width":160,"height":61,"scale":100,"focalX":50,"focalY":50,"id":"191e68b7-f3b2-4bda-8812-f27611d82d58"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Quizzes &amp;<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">&nbsp;Polls<\/span>","fontWeight":400,"x":292,"y":436,"width":178,"height":61,"scale":100,"focalX":50,"focalY":50,"id":"ec884c49-f8e4-4c11-b42d-42268c36cd65"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T10:07:22","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia.png","width":330,"height":567,"posterId":0,"id":478,"title":"smartphone_diary_ia","alt":"smartphone_diary_ia","local":false,"sizes":{"medium":{"file":"smartphone_diary_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-174x300.png"},"large":{"file":"smartphone_diary_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-595x1024.png"},"thumbnail":{"file":"smartphone_diary_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-150x150.png"},"medium_large":{"file":"smartphone_diary_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-768x1322.png"},"1536x1536":{"file":"smartphone_diary_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_diary_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_diary_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_diary_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_diary_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_diary_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia-150x258.png"},"full":{"file":"smartphone_diary_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_diary_ia.png"}}},"type":"image","x":35,"y":221,"width":127,"height":219,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"58272cb6-0ffe-44f2-92f0-7475cf52b935"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T08:55:17","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png","width":330,"height":567,"posterId":0,"id":462,"title":"smartphone_rahmen_weiss_ia","alt":"smartphone_rahmen_weiss_ia","local":false,"sizes":{"medium":{"file":"smartphone_rahmen_weiss_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-174x300.png"},"large":{"file":"smartphone_rahmen_weiss_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-595x1024.png"},"thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x150.png"},"medium_large":{"file":"smartphone_rahmen_weiss_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-768x1322.png"},"1536x1536":{"file":"smartphone_rahmen_weiss_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_rahmen_weiss_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_rahmen_weiss_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_rahmen_weiss_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_rahmen_weiss_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x258.png"},"full":{"file":"smartphone_rahmen_weiss_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png"}}},"type":"image","x":29,"y":215,"width":138,"height":234,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"0fc91744-a6c4-441f-b5c3-1e8a83bf11c5"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_live_stories_ia.png","width":330,"height":567,"id":456,"title":"smartphone_live_stories_ia","alt":"smartphone_live_stories_ia","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_live_stories_ia-150x150.png"},"medium":{"width":174,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_live_stories_ia-174x300.png"},"large":{"width":580,"height":998,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_live_stories_ia-595x1024.png"},"full":{"width":997,"height":1716,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_live_stories_ia.png"}}},"type":"image","x":87,"y":316,"width":130,"height":224,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"11b8d449-ef69-441b-9c67-70da4afaf530"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-27T03:44:52","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia.png","width":330,"height":567,"posterId":0,"id":493,"title":"smartphone_animal_quiz_ia","alt":"smartphone_animal_quiz_ia","local":false,"sizes":{"medium":{"file":"smartphone_animal_quiz_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-174x300.png"},"large":{"file":"smartphone_animal_quiz_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-595x1024.png"},"thumbnail":{"file":"smartphone_animal_quiz_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-150x150.png"},"medium_large":{"file":"smartphone_animal_quiz_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-768x1322.png"},"1536x1536":{"file":"smartphone_animal_quiz_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_animal_quiz_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_animal_quiz_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_animal_quiz_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_animal_quiz_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_animal_quiz_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia-150x258.png"},"full":{"file":"smartphone_animal_quiz_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_animal_quiz_ia.png"}}},"type":"image","x":150,"y":416,"width":130,"height":223,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"fca708db-0e8f-4f80-a966-65953e09f3e2"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"43f73327-001d-427e-a327-d6bef9cf192c","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":330,"height":586,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":48,"y":0,"width":330,"height":586,"mask":{"type":"rectangle"},"isBackground":true,"id":"db241e9d-aeb5-4155-afbf-2fa22282d761","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png","width":320,"height":440,"id":437,"title":"blaue_boxen","alt":"blaue_boxen","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-150x150.png"},"medium":{"width":218,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-218x300.png"},"full":{"width":640,"height":880,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png"}}},"type":"image","x":18,"y":-1,"width":320,"height":440,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"e4b7fe4a-0b57-4ac0-9fb2-e0bf22b0044a"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Evergreen Stories<\/span>","fontWeight":700,"x":31,"y":10,"width":237,"height":71,"scale":100,"focalX":50,"focalY":50,"id":"b6d5ccfd-4e56-4e7a-81c2-623ecb8813e5"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Kind of <\/span><span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">never ending <\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">stories that are <\/span><span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">always updated<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\"> with new content.<\/span>","fontWeight":400,"x":30,"y":158,"width":295,"height":120,"scale":100,"focalX":50,"focalY":50,"id":"f97b4e8a-1944-45e2-91a0-45291aecd08e"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","id":"3b0c66b6-846e-438c-ac6f-e4e2f45de73c","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">e.g. public<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">diary<\/span>","x":31,"y":368,"width":206,"height":61,"scale":100,"focalX":50,"focalY":50},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T13:05:33","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST0008_ANIMATION_01_STORYASSET-02__2mbit_jk.mp4","width":330,"height":586,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-96.jpeg","posterId":489,"id":488,"length":15,"lengthFormatted":"0:15","title":"WST0008_ANIMATION_01_STORYASSET-02__2mbit_jk","alt":"WST0008_ANIMATION_01_STORYASSET-02__2mbit_jk","local":false,"sizes":[],"provider":"local"},"controls":false,"loop":false,"autoPlay":true,"type":"video","x":178,"y":266,"width":205,"height":365,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"1bef20e1-6416-4ea7-9540-d25264dff847","alt":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T08:55:17","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png","width":330,"height":567,"posterId":0,"id":462,"title":"smartphone_rahmen_weiss_ia","alt":"smartphone_rahmen_weiss_ia","local":false,"sizes":{"medium":{"file":"smartphone_rahmen_weiss_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-174x300.png"},"large":{"file":"smartphone_rahmen_weiss_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-595x1024.png"},"thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x150.png"},"medium_large":{"file":"smartphone_rahmen_weiss_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-768x1322.png"},"1536x1536":{"file":"smartphone_rahmen_weiss_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_rahmen_weiss_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_rahmen_weiss_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_rahmen_weiss_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_rahmen_weiss_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x258.png"},"full":{"file":"smartphone_rahmen_weiss_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png"}}},"type":"image","x":172,"y":255,"width":225,"height":386,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"6a12a389-682c-4bae-98ac-df4c66d055af"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"2676efbc-01cb-42f3-9f06-0e7e56f5e6bf","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":330,"height":586,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":48,"y":0,"width":330,"height":586,"mask":{"type":"rectangle"},"isBackground":true,"id":"f13fb10f-8a3a-4b00-8ccc-4aa127d1ca09","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png","width":320,"height":440,"id":437,"title":"blaue_boxen","alt":"blaue_boxen","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-150x150.png"},"medium":{"width":218,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-218x300.png"},"full":{"width":640,"height":880,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png"}}},"x":16,"y":176,"width":320,"height":440,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"05800d1d-29fd-41a1-bb97-825bf8b248a6","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Live<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Stories<\/span>","fontWeight":700,"x":29,"y":187,"width":237,"height":71,"scale":100,"focalX":50,"focalY":50,"id":"2441fdc0-1c6b-429d-ada3-d014ce2712e5","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">Add new&nbsp;<\/span>\n<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">story pages in real time<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">,<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">while a reader has<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">the story open.<\/span>","fontWeight":400,"x":28,"y":335,"width":295,"height":123,"scale":100,"focalX":50,"focalY":50,"id":"429d3dd8-8906-415e-b9ac-cb77cf156e50","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"id":"9f5a0e85-d838-49ed-9173-9e1e1381892c","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">e.g. public<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">diary<\/span>","x":29,"y":545,"width":206,"height":61,"scale":100,"focalX":50,"focalY":50,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_10_2.mp4","width":1080,"height":1920,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-88.jpeg","posterId":461,"id":460,"lengthFormatted":"0:10","title":"WST008_for Webstories_10_2","alt":"WST008_for Webstories_10_2","local":false,"sizes":[]},"controls":false,"loop":false,"autoPlay":true,"type":"video","x":192,"y":2,"width":199,"height":348,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"e6497715-c539-42ab-89ab-66c5112349e9"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png","width":330,"height":567,"id":462,"title":"smartphone_rahmen_weiss_ia","alt":"smartphone_rahmen_weiss_ia","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x150.png"},"medium":{"width":174,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-174x300.png"},"large":{"width":580,"height":998,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-595x1024.png"},"full":{"width":997,"height":1716,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png"}}},"type":"image","x":179,"y":-16,"width":220,"height":379,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"766a907d-51b7-4e77-a384-df2351b9e912"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"82effbdd-38a1-44aa-a7fa-5705c38c9b71","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":330,"height":586,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":48,"y":0,"width":330,"height":586,"mask":{"type":"rectangle"},"isBackground":true,"id":"84f922c6-deaf-4c70-8d22-97f6cb0bded0","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png","width":320,"height":440,"id":437,"title":"blaue_boxen","alt":"blaue_boxen","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-150x150.png"},"medium":{"width":218,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen-218x300.png"},"full":{"width":640,"height":880,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blaue_boxen.png"}}},"x":72,"y":-1,"width":320,"height":440,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"2dbddcba-17b0-4f95-9b4e-e7f5dd6ee33e","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Quizzes<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">and polls<\/span>","fontWeight":700,"x":85,"y":10,"width":237,"height":71,"scale":100,"focalX":50,"focalY":50,"id":"41c70030-39ad-41b8-8dba-e77ea44cc9c3","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">A cool interactive way to <\/span><span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">engage the audience<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">.<\/span>","fontWeight":400,"x":84,"y":158,"width":295,"height":61,"scale":100,"focalX":50,"focalY":50,"id":"aafe187e-f556-4330-b0ae-70260cb7521c","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-27T04:02:04","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_Sheep_Quiz_s.mp4","width":330,"height":550,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-98.jpeg","posterId":495,"id":494,"length":11,"lengthFormatted":"0:11","title":"WST008_Sheep_Quiz_s","alt":"WST008_Sheep_Quiz_s","local":false,"sizes":[],"provider":"local"},"controls":false,"loop":false,"autoPlay":true,"type":"video","x":27,"y":267,"width":200,"height":348,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"6fb4fbb7-6cfb-4e06-abc7-02f6af758e0a"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T08:55:17","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png","width":330,"height":567,"posterId":0,"id":462,"title":"smartphone_rahmen_weiss_ia","alt":"smartphone_rahmen_weiss_ia","local":false,"sizes":{"medium":{"file":"smartphone_rahmen_weiss_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-174x300.png"},"large":{"file":"smartphone_rahmen_weiss_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-595x1024.png"},"thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x150.png"},"medium_large":{"file":"smartphone_rahmen_weiss_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-768x1322.png"},"1536x1536":{"file":"smartphone_rahmen_weiss_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_rahmen_weiss_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_rahmen_weiss_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_rahmen_weiss_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_rahmen_weiss_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_rahmen_weiss_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia-150x258.png"},"full":{"file":"smartphone_rahmen_weiss_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_rahmen_weiss_ia.png"}}},"type":"image","x":17,"y":253,"width":220,"height":378,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"c84a20d0-e68d-48fd-824a-ea979266a627","link":{"url":"https:\/\/webstoriesinteractivity-beta.web.app\/animals-polls-backend.html","icon":null,"desc":null}}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"6ea41eb3-3e5d-4019-bab1-b812f9431e76","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true,"horizontal":true},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"35b8f3f5-85fb-4250-84a0-b829538521c3","alt":null,"type":"image","backgroundOverlay":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">DIFFERENT TYPES<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">OF CONTENT&nbsp;<\/span>","width":425,"height":108,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"03f2d930-115d-463b-9ce3-f67711278cb5","x":39,"y":23,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T02:36:58","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau.png","width":60,"height":20,"posterId":0,"id":435,"title":"dot_hellblau","alt":"dot_hellblau","local":false,"sizes":{"web-stories-publisher-logo":{"file":"dot_hellblau-96x40.png","width":96,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau-96x40.png"},"full":{"file":"dot_hellblau.png","width":120,"height":40,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/dot_hellblau.png"}}},"x":40,"y":1.5,"width":60,"height":20,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"bdacc6ca-62a8-41e7-8213-648fcc991ffb","type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; font-style: italic; color: #030028\">3<\/span>","fontWeight":400,"x":-33,"y":1,"width":206,"height":21,"scale":100,"focalX":50,"focalY":50,"id":"9e20b30a-f030-4b79-837a-fa69a4b77440","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blauer_faecher_bildern.png","width":330,"height":633,"id":450,"title":"blauer_faecher_bildern","alt":"blauer_faecher_bildern","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blauer_faecher_bildern-150x150.png"},"medium":{"width":156,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blauer_faecher_bildern-156x300.png"},"large":{"width":534,"height":1024,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blauer_faecher_bildern-534x1024.png"},"full":{"width":1087,"height":2086,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/blauer_faecher_bildern.png"}}},"type":"image","x":0,"y":200,"width":414,"height":792,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"0673345d-84c5-40b0-9119-3e779c57c0c9"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Experiential<\/span>","fontWeight":400,"x":41,"y":227,"width":265,"height":36,"scale":100,"focalX":50,"focalY":50,"id":"2461c91d-985b-4a56-a682-7480300d00a2"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Educational<\/span>","fontWeight":400,"x":40,"y":360,"width":266,"height":35,"scale":100,"focalX":50,"focalY":50,"id":"b25fb826-7449-4da7-96b7-91a41265c99e"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Listicles<\/span>","fontWeight":400,"x":41,"y":493,"width":160,"height":36,"scale":100,"focalX":50,"focalY":50,"id":"3f6afe7a-78e0-413f-93db-a90c33921f69"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"c20ef148-1724-449e-ab35-d1db87e3c9cb","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":true,"horizontal":true},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":330,"height":586,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":48,"y":0,"width":330,"height":586,"mask":{"type":"rectangle"},"isBackground":true,"id":"ba7cac20-0826-4079-99f1-78eed8b82505","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Experiential<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">stories<\/span>","width":425,"height":108,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"796eff00-a534-41fb-9f6e-01a6b1ae1973","x":40,"y":0,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">The user can <\/span><span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">experience<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">a place, event or simply<\/span>\n<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">a moment in time<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">.<\/span>","fontWeight":400,"x":40,"y":129,"width":318,"height":90,"scale":100,"focalX":50,"focalY":50,"id":"7d0f8639-c24e-41f5-8105-e9d9f2f9ddee"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/blob.png","width":272,"height":260,"id":18,"title":"blob","alt":"blob","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/blob-150x150.png"},"medium":{"width":300,"height":286,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/blob-300x286.png"},"full":{"width":544,"height":519,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/blob.png"}}},"type":"image","x":207,"y":41,"width":337,"height":321,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"483f5d76-8de8-410a-91f7-776a9ac59966"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_dogs_ia.png","width":330,"height":567,"id":467,"title":"smartphone_dogs_ia","alt":"smartphone_dogs_ia","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_dogs_ia-150x150.png"},"medium":{"width":174,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_dogs_ia-174x300.png"},"large":{"width":580,"height":998,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_dogs_ia-595x1024.png"},"full":{"width":997,"height":1716,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_dogs_ia.png"}}},"type":"image","x":105,"y":286,"width":195,"height":334,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"afbc3add-cfb4-4d08-bead-75814f696e29"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T09:29:44","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia.png","width":330,"height":567,"posterId":0,"id":466,"title":"smartphone_lonelyplanet_ia","alt":"smartphone_lonelyplanet_ia","local":false,"sizes":{"medium":{"file":"smartphone_lonelyplanet_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-174x300.png"},"large":{"file":"smartphone_lonelyplanet_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-595x1024.png"},"thumbnail":{"file":"smartphone_lonelyplanet_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-150x150.png"},"medium_large":{"file":"smartphone_lonelyplanet_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-768x1322.png"},"1536x1536":{"file":"smartphone_lonelyplanet_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_lonelyplanet_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_lonelyplanet_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_lonelyplanet_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_lonelyplanet_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_lonelyplanet_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia-150x258.png"},"full":{"file":"smartphone_lonelyplanet_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_lonelyplanet_ia.png"}}},"type":"image","x":-59,"y":362,"width":150,"height":258,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"ac8d6f00-65d7-4779-af71-dc33c9a9b942"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","creationDate":"2020-10-26T09:29:20","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia.png","width":330,"height":567,"posterId":0,"id":465,"title":"smartphone_washington_ia","alt":"smartphone_washington_ia","local":false,"sizes":{"medium":{"file":"smartphone_washington_ia-174x300.png","width":174,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-174x300.png"},"large":{"file":"smartphone_washington_ia-595x1024.png","width":595,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-595x1024.png"},"thumbnail":{"file":"smartphone_washington_ia-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-150x150.png"},"medium_large":{"file":"smartphone_washington_ia-768x1322.png","width":768,"height":1322,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-768x1322.png"},"1536x1536":{"file":"smartphone_washington_ia-892x1536.png","width":892,"height":1536,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-892x1536.png"},"web-stories-poster-portrait":{"file":"smartphone_washington_ia-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-640x853.png"},"web-stories-poster-landscape":{"file":"smartphone_washington_ia-853x640.png","width":853,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-853x640.png"},"web-stories-poster-square":{"file":"smartphone_washington_ia-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-640x640.png"},"web-stories-publisher-logo":{"file":"smartphone_washington_ia-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-96x96.png"},"web-stories-thumbnail":{"file":"smartphone_washington_ia-150x258.png","width":150,"height":258,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia-150x258.png"},"full":{"file":"smartphone_washington_ia.png","width":997,"height":1716,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/smartphone_washington_ia.png"}}},"type":"image","x":314,"y":362,"width":150,"height":258,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"6a629bf8-3e32-428f-bc2a-d2db1e290f94"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"919501f4-60b3-4e18-9e49-0fe4ac981849","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T13:05:33","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_14_1_jk.mp4","width":330,"height":586,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-97.jpeg","posterId":490,"id":487,"length":14,"lengthFormatted":"0:14","title":"WST008_for-Webstories_14_1_jk","alt":"WST008_for-Webstories_14_1_jk","local":false,"sizes":[],"provider":"local"},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":3,"y":-57,"width":411,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"b1bf3677-2e27-42fe-ac66-fd5b6d139ffe","alt":null,"type":"video"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"2d51ff25-763e-4d68-96f8-a75a7b905f27","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"},"pageAttachment":{"url":"https:\/\/www.vice.com\/stories\/how-to-make-dumplings-recipe\/","ctaText":"See full example"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"d0631255-d7d8-4f9d-a0cd-3d50170a6951","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Educational<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">stories<\/span>","width":425,"height":108,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"4fcac55f-669d-4673-8b0b-f99539166d0e","x":40,"y":0,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":22,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">Teach<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\"> us something and<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">have often a <\/span><span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">clear end<\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">.<\/span>","fontWeight":400,"x":40,"y":129,"width":318,"height":61,"scale":100,"focalX":50,"focalY":50,"id":"668cbb62-6903-44f9-97f5-a4de98dc8059","type":"text"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"type":"video","x":0,"y":262,"width":414,"height":414,"scale":100,"focalX":50,"focalY":50,"mask":{"type":"rectangle"},"id":"7c33300c-9be5-4caa-930a-5ef03ffeb3ad","resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T09:35:57","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstory_15.mp4","width":1080,"height":1080,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-91.jpeg","posterId":471,"id":470,"length":11,"lengthFormatted":"0:11","title":"WST008_for-Webstory_15","alt":"WST008_for-Webstory_15","local":false,"sizes":[]}},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-1.png","width":168,"height":303,"id":32,"title":"GettyImages-1164835900-Converted-03-1-1","alt":"GettyImages-1164835900-Converted-03-1-1","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-1-150x150.png"},"medium":{"width":167,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-1-167x300.png"},"full":{"width":336,"height":605,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-1.png"}}},"type":"image","x":1,"y":83,"width":219,"height":394,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"9c114744-6114-4296-97e0-275713dcee9e"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"cbbe7ac6-d7dd-46f0-bbd4-a47cd07f504b","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T10:01:18","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstory_16.mp4","width":167,"height":299,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-94.jpeg","posterId":477,"id":476,"length":15,"lengthFormatted":"0:15","title":"WST008_for Webstory_16","alt":"WST008_for Webstory_16","local":false,"sizes":[],"provider":"local"},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":3,"y":-57,"width":411,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"b2f2bddb-b518-494b-8eb5-2adc1c943c8d","alt":null,"type":"video"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"322da6c6-7fcd-4f88-a142-f7a7f2163b8b","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"},"pageAttachment":{"url":"https:\/\/gadgets.ndtv.com\/webstories\/tech\/what-makes-gaming-laptops-different-and-do-you-need-one-462","ctaText":"See full example"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":167,"height":299,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":144,"y":319,"width":167,"height":299,"mask":{"type":"rectangle"},"isBackground":true,"id":"3f8a1c6c-cfed-4256-8c3e-9c00d8bf635e","alt":null,"type":"image"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Listicles<\/span>","width":425,"height":54,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"6a7bf60b-b91c-4178-b297-16241115f721","x":40,"y":0,"marginOffset":0,"isBold":true,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #07e1fe; letter-spacing: 0.02em\">Generic lists:<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Usually have no end<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">or beginning<\/span>","fontWeight":400,"x":39,"y":129,"width":318,"height":105,"scale":100,"focalX":50,"focalY":50,"id":"c6104680-b9b4-4e28-bc55-592b648107c6","type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #de1aad; letter-spacing: 0.02em\">\u201cBest\u201d or \u201cWorst of\u201d lists:<\/span><span style=\"font-weight: 600; color: #07e1fe; letter-spacing: 0.02em\"> <\/span><span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Create suspense<\/span>","fontWeight":400,"x":39,"y":294,"width":337,"height":70,"scale":100,"focalX":50,"focalY":50,"id":"3b5e48af-3ad0-48fb-a4ef-f052c85d6a89"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":26,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; color: #79b3ff; letter-spacing: 0.02em\">Shoppable lists:&nbsp;<\/span>\n<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Perfect for affiliate links<\/span>","fontWeight":400,"x":39,"y":424,"width":346,"height":70,"scale":100,"focalX":50,"focalY":50,"id":"294d79a6-5a2b-47a3-9c6d-506b89343fb9"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":314,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1.png","width":253,"height":288,"id":19,"title":"GettyImages-1164835900-Converted-1","alt":"GettyImages-1164835900-Converted-1","local":false,"sizes":{"thumbnail":{"width":150,"height":150,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1-150x150.png"},"medium":{"width":264,"height":300,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1-264x300.png"},"full":{"width":506,"height":576,"source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-1.png"}}},"type":"image","x":239,"y":-123,"width":244,"height":279,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"f77c84f9-fd2c-460a-b054-52d499632870"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"473818fd-3ba3-4a8a-87ad-50bbfe8ae7d1","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T09:41:34","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstory_18_2.mp4","width":330,"height":586,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-92.jpeg","posterId":473,"id":472,"length":7,"lengthFormatted":"0:07","title":"WST008_for-Webstory_18_2","alt":"WST008_for-Webstory_18_2","local":false,"sizes":[],"provider":"local"},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":3,"y":-57,"width":411,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"74563a59-a8ce-4ef1-87c5-41b2e9cc19ff","alt":null,"type":"video"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"d15e7440-7840-437e-9b0d-c2fd26be46c8","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"},"pageAttachment":{"url":"https:\/\/www.forbes.com\/stories\/amp\/the-10-cities-with-the-most-billionaires-2020\/","ctaText":"See full example"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/jpeg","creationDate":"2020-10-18T23:38:43","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg.jpg","width":109,"height":194,"posterId":0,"id":312,"title":"pattern_bg","alt":"1920x1080","local":false,"sizes":{"medium":{"file":"pattern_bg-169x300.jpg","width":169,"height":300,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-169x300.jpg"},"large":{"file":"pattern_bg-576x1024.jpg","width":576,"height":1024,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-576x1024.jpg"},"thumbnail":{"file":"pattern_bg-150x150.jpg","width":150,"height":150,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x150.jpg"},"medium_large":{"file":"pattern_bg-768x1365.jpg","width":768,"height":1365,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-768x1365.jpg"},"1536x1536":{"file":"pattern_bg-864x1536.jpg","width":864,"height":1536,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-864x1536.jpg"},"2048x2048":{"file":"pattern_bg-1152x2048.jpg","width":1152,"height":2048,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1152x2048.jpg"},"post-thumbnail":{"file":"pattern_bg-1200x2133.jpg","width":1200,"height":2133,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-1200x2133.jpg"},"web-stories-poster-portrait":{"file":"pattern_bg-640x853.jpg","width":640,"height":853,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x853.jpg"},"web-stories-poster-landscape":{"file":"pattern_bg-853x640.jpg","width":853,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-853x640.jpg"},"web-stories-poster-square":{"file":"pattern_bg-640x640.jpg","width":640,"height":640,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-640x640.jpg"},"web-stories-publisher-logo":{"file":"pattern_bg-96x96.jpg","width":96,"height":96,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-96x96.jpg"},"web-stories-thumbnail":{"file":"pattern_bg-150x267.jpg","width":150,"height":267,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-150x267.jpg"},"full":{"file":"pattern_bg-scaled.jpg","width":1440,"height":2560,"mime_type":"image\/jpeg","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/pattern_bg-scaled.jpg"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":-54,"y":392,"width":109,"height":194,"mask":{"type":"rectangle"},"isBackground":true,"id":"e30198df-e087-4805-b3df-0930d3c85567","alt":null,"type":"image"},{"opacity":100,"flip":[],"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"type":"video","x":0,"y":-57,"width":414,"height":414,"scale":100,"focalX":50,"focalY":50,"mask":{"type":"rectangle"},"id":"78946696-ec80-4cfa-91f3-b7e1fe8f99f0","resource":{"type":"video","mimeType":"video\/mp4","creationDate":"2020-10-26T09:43:42","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/WST008_for-Webstories_19.mp4","width":330,"height":330,"poster":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/10\/image-93.jpeg","posterId":475,"id":474,"length":4,"lengthFormatted":"0:04","title":"WST008_for-Webstories_19","alt":"WST008_for-Webstories_19","local":false,"sizes":[],"provider":"local"}},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":39,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"left","padding":{"locked":true,"horizontal":0,"vertical":0},"type":"text","content":"<span style=\"font-weight: 600; font-style: italic; color: #fff; letter-spacing: 0.02em\">Which type of content will you use first?<\/span>","fontWeight":400,"x":25,"y":403,"width":363,"height":161,"scale":100,"focalX":50,"focalY":50,"id":"fac76887-200e-4309-b091-b8dbbe11f73d"}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"f39e4ccc-e666-47a0-9f11-0ed3b951c2c0","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"c808a30c-9f5c-4acf-aa6f-503f48f02aa8","type":"shape"}},{"backgroundOverlay":"none","elements":[{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png","width":720,"height":1280,"id":12,"title":"Vector","alt":"Vector","local":true,"sizes":{"medium":{"file":"Vector-169x300.png","width":169,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-169x300.png"},"large":{"file":"Vector-576x1024.png","width":576,"height":1024,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-576x1024.png"},"thumbnail":{"file":"Vector-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x150.png"},"web-stories-poster-portrait":{"file":"Vector-640x853.png","width":640,"height":853,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x853.png"},"web-stories-poster-landscape":{"file":"Vector-720x640.png","width":720,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-720x640.png"},"web-stories-poster-square":{"file":"Vector-640x640.png","width":640,"height":640,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-640x640.png"},"web-stories-publisher-logo":{"file":"Vector-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-96x96.png"},"web-stories-thumbnail":{"file":"Vector-150x267.png","width":150,"height":267,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector-150x267.png"},"full":{"file":"Vector.png","width":720,"height":1280,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Vector.png"}}},"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":124,"y":45,"width":412,"height":732,"mask":{"type":"rectangle"},"isBackground":true,"id":"9f11cb74-d723-4b24-8d11-9d54ac882e9a","type":"image","alt":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":29,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"initial","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 600; color: #fff; letter-spacing: 0.02em\">Subscribe for more.<\/span>","width":299,"height":40,"scale":100,"focalX":50,"focalY":50,"basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","id":"ed08ffa3-65c6-4091-a715-d25ace9401f3","x":56,"y":413,"marginOffset":0,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726.png","width":684,"height":553,"id":43,"title":"Group 5726","alt":"Group 5726","local":true,"sizes":{"medium":{"file":"Group-5726-300x243.png","width":300,"height":243,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-300x243.png"},"thumbnail":{"file":"Group-5726-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-150x150.png"},"web-stories-poster-portrait":{"file":"Group-5726-640x553.png","width":640,"height":553,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-640x553.png"},"web-stories-poster-square":{"file":"Group-5726-640x553.png","width":640,"height":553,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-640x553.png"},"web-stories-publisher-logo":{"file":"Group-5726-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-96x96.png"},"web-stories-thumbnail":{"file":"Group-5726-150x121.png","width":150,"height":121,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726-150x121.png"},"full":{"file":"Group-5726.png","width":684,"height":553,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Group-5726.png"}}},"type":"image","x":30,"y":92,"width":366,"height":295,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"c3767225-e130-4596-bcbd-02d6f1110971","alt":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2.png","width":280,"height":628,"id":40,"title":"GettyImages-1164835900 [Converted]-03 1 (2)","alt":"GettyImages-1164835900 [Converted]-03 1 (2)","local":true,"sizes":{"medium":{"file":"GettyImages-1164835900-Converted-03-1-2-134x300.png","width":134,"height":300,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2-134x300.png"},"thumbnail":{"file":"GettyImages-1164835900-Converted-03-1-2-150x150.png","width":150,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2-150x150.png"},"web-stories-publisher-logo":{"file":"GettyImages-1164835900-Converted-03-1-2-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2-96x96.png"},"web-stories-thumbnail":{"file":"GettyImages-1164835900-Converted-03-1-2-150x336.png","width":150,"height":336,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2-150x336.png"},"full":{"file":"GettyImages-1164835900-Converted-03-1-2.png","width":280,"height":628,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-1-2.png"}}},"type":"image","x":0,"y":135,"width":179,"height":401,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"9073c1d0-923d-4b43-a7a4-31458fbb7577","alt":null},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2.png","width":140,"height":282,"id":41,"title":"GettyImages-1164835900 [Converted]-03 2","alt":"GettyImages-1164835900 [Converted]-03 2","local":true,"sizes":{"thumbnail":{"file":"GettyImages-1164835900-Converted-03-2-140x150.png","width":140,"height":150,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2-140x150.png"},"web-stories-publisher-logo":{"file":"GettyImages-1164835900-Converted-03-2-96x96.png","width":96,"height":96,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2-96x96.png"},"full":{"file":"GettyImages-1164835900-Converted-03-2.png","width":140,"height":282,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/GettyImages-1164835900-Converted-03-2.png"}}},"type":"image","x":321,"y":-27,"width":91,"height":183,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"4b56ccbf-e5b4-446c-89ee-d946810743b4","alt":null},{"x":43,"y":470,"id":"e9b6459c-00f9-47ea-b763-f7bed99eb6b9","basedOn":"821eb25b-75b4-4515-8c50-7e834d6557c3","opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":16,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.4,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"color: #fff; letter-spacing: 0.02em\">Rewatch this Web Story on YouTube. Subscribe to the blog &amp; channel for the latest and greatest.<\/span>","width":312,"height":66,"scale":100,"focalX":50,"focalY":50,"marginOffset":0,"type":"text"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"scale":100,"focalX":50,"focalY":50,"resource":{"type":"image","mimeType":"image\/png","src":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-1.png","width":286,"height":80,"id":42,"title":"Rectangle 5 (1)","alt":"Rectangle 5 (1)","local":true,"sizes":{"thumbnail":{"file":"Rectangle-5-1-150x80.png","width":150,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-1-150x80.png"},"web-stories-publisher-logo":{"file":"Rectangle-5-1-96x80.png","width":96,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-1-96x80.png"},"web-stories-thumbnail":{"file":"Rectangle-5-1-150x42.png","width":150,"height":42,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-1-150x42.png"},"full":{"file":"Rectangle-5-1.png","width":286,"height":80,"mime_type":"image\/png","source_url":"https:\/\/stories-labs.dev\/webcreators\/wp-content\/uploads\/sites\/66\/2020\/09\/Rectangle-5-1.png"}}},"type":"image","x":126,"y":578,"width":157,"height":44,"mask":{"type":"rectangle","showInLibrary":true,"name":"Rectangle","path":"M 0,0 1,0 1,1 0,1 0,0 Z","ratio":1},"id":"ce976ded-f288-44db-958e-61e925cadbfd"},{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundTextMode":"NONE","font":{"family":"Poppins","service":"fonts.google.com","fallbacks":["sans-serif"],"weights":[100,200,300,400,500,600,700,800,900],"styles":["italic","regular"],"variants":[[0,100],[0,200],[0,300],[0,400],[0,500],[0,600],[0,700],[0,800],[0,900],[1,100],[1,200],[1,300],[1,400],[1,500],[1,600],[1,700],[1,800],[1,900]],"metrics":{"upm":1000,"asc":1050,"des":-350,"tAsc":1050,"tDes":-350,"tLGap":100,"wAsc":1135,"wDes":627,"xH":548,"capH":698,"yMin":-572,"yMax":1065,"hAsc":1050,"hDes":-350,"lGap":100}},"fontSize":20,"backgroundColor":{"color":{"r":196,"g":196,"b":196}},"lineHeight":1.5,"textAlign":"center","padding":{"locked":true,"horizontal":0,"vertical":0},"content":"<span style=\"font-weight: 800; color: #030028\">VISIT NOW<\/span>","fontWeight":400,"width":181,"height":28,"scale":100,"focalX":50,"focalY":50,"link":{"url":"https:\/\/www.youtube.com\/channel\/UCXZNlYNefXV3iMcyzszt_9Q","icon":"https:\/\/yt3.ggpht.com\/a\/AATXAJztU38EuQpWxlkXwYb6pKofsVKAqt7aYx5zD-FU=s900-c-k-c0xffffffff-no-rj-mo","desc":"Google Web Creators - YouTube"},"type":"text","basedOn":"5aa7d62d-eeb5-490d-a35b-f156cd9bdb03","id":"e1bccf41-949a-4d68-8674-806f96eff186","x":115,"y":587}],"backgroundColor":{"color":{"r":11,"g":12,"b":23}},"type":"page","id":"33ae8af6-3ec6-4231-a730-7f38a8c8a11f","defaultBackgroundElement":{"opacity":100,"flip":{"vertical":false,"horizontal":false},"rotationAngle":0,"lockAspectRatio":true,"backgroundColor":{"color":{"r":255,"g":255,"b":255}},"x":1,"y":1,"width":1,"height":1,"mask":{"type":"rectangle"},"isBackground":true,"isDefaultBackground":true,"id":"2e4ef0ff-dfbb-4639-ab11-fb6321d6b6d3","type":"shape"}}],"autoAdvance":true,"defaultPageDuration":7}
````

## Expected Behaviour

The `length` field should be always present.

## Steps to Reproduce

Not sure yet how to reproduce...

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

When media picker is used, it does not current return length as a field in the admin ajax call. 

In this PR, I added media_details key to the response. This contains meta data that is useful in the editor. The REST API already returns this data. So keep admin ajax / rest api, I returned the data in the exact same format. This makes the code a little simpler in a number of places and keep the data the same, in case more data is needed in the future. 

I also noticed another issue with VideoPress. Length was never being returned here, as the field was not present in the api. The tweaks the videopres integration, make the code simplier, as media details are also used here, but also makes sure that length is returned. 

There is a migration used to populate missing data and this includes a unit test. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new story with a few pages
2. Set page advancement duration to something like 2s
2. On the first page, insert a pre-existing video via the WP media modal (click on the "Upload" button)
3. Preview the story on the frontend
4. Verify that the page with the video on it advances only after video has finished, not after 2s

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5030

### CODE REVIEW

File: assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js [hunk 1]
```diff
@@ -45,20 +43,16 @@ const getResourceFromMediaPicker = (mediaPickerEl) => {
...
-  const sizes = Object.fromEntries(
-    Object.entries(mediaPickerSizes || {}).map(([k, size]) => [
-      k,
-      {
-        width: size.width,
-        height: size.height,
-        source_url: size.url,
-      },
-    ])
-  );
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/getResourceFromMediaPicker.js:61]: This is really nice we can remove this. This is inline with `getResourceFromAttachment`

File: includes/Integrations/Jetpack.php [hunk 2]
```diff
@@ -131,7 +131,7 @@ public function filter_ajax_query_attachments_args( array $args ) {
 		$allowed_mime_types = $this->get_allowed_mime_types();
 		$allowed_mime_types = array_merge( ...array_values( $allowed_mime_types ) );
 		if ( in_array( self::VIDEOPRESS_MIME_TYPE, $args['post_mime_type'], true ) && ! array_diff( $allowed_mime_types, $args['post_mime_type'] ) ) {
-			add_filter( 'wp_prepare_attachment_for_js', [ $this, 'filter_admin_ajax_response' ], 10, 2 );
+			add_filter( 'wp_prepare_attachment_for_js', [ $this, 'filter_admin_ajax_response' ], 15, 2 );
```
Comment (spacedmonkey) [inline includes/Integrations/Jetpack.php:135]: Load after https://github.com/google/web-stories-wp/blob/ff201b1be19e5903a31bea40a3b0bfd9a83e15e1/includes/Media/Media.php#L230

File: includes/Integrations/Jetpack.php [hunk 3]
```diff
@@ -155,22 +155,8 @@ public function filter_admin_ajax_response( array $response, WP_Post $attachment
...
-			// If videopress has finished processing, use the duration in millions to get formatted seconds and minutes.
-			if ( isset( $videopress['duration'] ) && $videopress['duration'] ) {
-				$response['fileLength'] = $this->format_milliseconds( $videopress['duration'] );
-
-			}
-			// If video has not finished processing, reset request to original url.
-			if ( isset( $videopress['finished'], $videopress['original'] ) && ! $videopress['finished'] ) {
-				$response['url'] = $videopress['original'];
-			}
-		}
```
Comment (spacedmonkey) [inline includes/Integrations/Jetpack.php:173]: Removing code 🎉

File: includes/Integrations/Jetpack.php [hunk 4]
```diff
@@ -202,16 +207,16 @@ public function filter_api_response( WP_REST_Response $response, WP_Post $post )
 			// If videopress has finished processing, use the duration in millions to get formatted seconds and minutes.
 			if ( isset( $videopress['duration'] ) && $videopress['duration'] ) {
 				$data['media_details']['length_formatted'] = $this->format_milliseconds( $videopress['duration'] );
+				$data['media_details']['length']           = (int) floor( $videopress['duration'] / 1000 );
```
Comment (spacedmonkey) [inline includes/Integrations/Jetpack.php:211]: Make sure that length is present in rest api and admin ajax.

File: packages/migration/src/migrations/v0026_videoDuration.js [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+  if (
+    element.type === 'video' &&
+    element.resource &&
+    element.resource?.lengthFormatted &&
+    !element.resource?.length
+  ) {
+    const times = element.resource.lengthFormatted.split(':');
+    const timesNumbers = times.map(Number);
+    const [minutes, seconds] = timesNumbers;
+    const length = 60 * minutes + seconds;
```
Comment (swissspidy) [inline packages/migration/src/migrations/v0026_videoDuration.js]: Nit: this won't work for videos with duration >= 1 hour.

File: includes/Integrations/Jetpack.php (hunk 2 above)
Comment (swissspidy) [reply includes/Integrations/Jetpack.php:135]: Could you add this explanation as an inline comment perhaps? So we don't accidentally change it again.

**Review by swissspidy — COMMENTED** [review]
At first glance this looks really good! Will do a proper review tomorrow.

File: packages/migration/src/migrations/v0026_videoDuration.js (hunk 5 above)
Comment (spacedmonkey) [reply packages/migration/src/migrations/v0026_videoDuration.js]: Good catch! I have fix, including a unit test. https://github.com/google/web-stories-wp/pull/7691/commits/02a5891c1a6da6be3a881b7ee640bba662e4eed3

File: includes/Integrations/Jetpack.php (hunk 2 above)
Comment (spacedmonkey) [reply includes/Integrations/Jetpack.php:135]: Added comment https://github.com/google/web-stories-wp/pull/7691/commits/b6640130f238ca998caf061cbfc53c2091a97650

File: packages/migration/src/migrations/test/v0026_videoDuration.js [hunk 6]
```diff
@@ -0,0 +1,227 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * Internal dependencies
+ */
+import videoDuration from '../v0026_videoDuration';
+
+describe('videoDuration', () => {
+  it('should migrate videoId to id', () => {
```
Comment (swissspidy) [inline packages/migration/src/migrations/test/v0026_videoDuration.js]: wrong test name

**Review by swissspidy — APPROVED** [review]
just one nit

File: packages/migration/src/migrations/test/v0026_videoDuration.js (hunk 6 above)
Comment (spacedmonkey) [inline packages/migration/src/migrations/test/v0026_videoDuration.js]:
```suggestion
  it('should migrate lengthFormatted to length', () => {
```

**Comment by swissspidy** [comment]
Possible to add some QA instructions? I suppose this can be easily verified via the story devtools or by verifying that auto advance correctly takes the video length into account when inserting videos via the media modal.

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@spacedmonkey FYI There's now a tiny merge conflict due to another migration being added in the meantime.

**Comment by spacedmonkey** [comment]
@swissspidy Fixed.
