### PR TITLE
Fonts: Add logic for getting proper font variants

### LINKED ISSUE #1900: Inconsistencies with font display between the editor and FE
## Bug Description

There are some odd inconsistencies happening between the editor and the FE.
Font weight doesn't seem to be added correctly, additionally, for some unknown reasons, only `italic` font is pulled in sometimes for a font even though it's not used. Displays correctly in the editor.

## Expected Behaviour

Fonts should always use consistent font weight and style in the editor and in the FE

## Steps to Reproduce

1. Add 2 Pages
2. Add some text to both pages with Open Sans Condensed.
3. Assign Light on one page as the font weight and bold on the other page, for the same font family
4. Now see the FE -- the fonts are in italic, in the editor not.

The [loaded font src](https://fonts.googleapis.com/css2?display=swap&family=Open+Sans+Condensed%3Aital%2Cwght%401%2C300) in the FE.

## Screenshots
Not italic in the editor:

Italic in the editor:

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #2234: Text: Wrapping (line breaks) sometimes inconsistent
## Bug Description

Wrapping of text is sometimes inconsistent between desktop vs. mobile or Chrome vs. Safari. This can result in truncated text due to unexpected extra line breaks.

I've encountered at least two distinct causes of this bug. The repro steps below describe one.

This case appears to be fixed by making sure the font stylesheet in the published story includes the all font weights used in the story (in this case, the bold/700 font weight). My guess is Chrome and Safari interpolate unprovided font weight differently.
```html
<!-- Before -->
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

<!-- After -->
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700&amp;display=swap" rel="stylesheet">
```

Possibly related to #743.

## Expected Behaviour

Text wrapping observed in edit mode should be consistent with text wrapping on the published story (desktop/mobile, and on all supported browsers).

## Steps to Reproduce

Example: View the last page of [this story](https://stories-new-wordpress-amp.pantheonsite.io/stories/wills-test-story/) on Chrome vs. Safari.

1. Create a text element that enough text to wrap once or more.
2. Set the font family to "Roboto" and font weight to bold.
3. Reduce the width of the text box to the smallest width that preserves the current wrapping.
4. Publish the story.
5. View the story on Chrome and Safari (desktop Safari in responsive mode with can emulate iPhone screens).

Expected: The edit mode view, Chrome, and Safari all have the same text wrapping.
Actual: Safari has a different text wrapping.

### Chrome desktop
Screen Shot 2020-06-03 at 9 20 10 PM

### Safari desktop
Screen Shot 2020-06-03 at 9 20 16 PM

## Additional Context

- Plugin Version: 1.0.0-alpha+d606fa7
- Operating System: macOS 10.15.4
- Browser: Chrome 83 and Safari 13.1
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

Updates the logic of font variants to be up to date with the inline formatting logic.

## Relevant Technical Choices

- Creates a new util file for RichText for getting an array of unique font variants for the HTML.

## To-do

- [x] Tests

## User-facing changes

The fonts variants are now loaded correctly which should remove the differences between the editor vs preview vs the story in different browsers.

## Testing Instructions
I
1. Create a text element with text "Lorem ipsum dolor amet".
2. Set the font family to "Roboto" and font weight to bold.
3. Reduce the width of the text box to the smallest width that preserves the current wrapping.
4. Publish the story.
5. View the story on Chrome and Safari
6. Verify that the line breaks are in the same place

II
1. Add 2 Pages
2. Add some text to both pages with Open Sans Condensed.
3. Assign Light on one page as the font weight and bold on the other page, for the same font family
4. Verify that the text looks the same in the editor and in the front-end.

---

Fixes #2234
Fixes #1900

### CODE REVIEW

File: assets/src/edit-story/output/utils/getFontDeclarations.js [hunk 1]
```diff
@@ -60,30 +60,34 @@ const getFontDeclarations = (pages) => {
...
-        // Keeps list unique.
-        if (!fontObjHasVariant && isValidVariant) {
-          fontObj.variants.push(newVariant);
+        for (const [italic, weight] of contentVariants) {
+          // A variant ("axis tuple" in Google Fonts terms) is a combination
+          // of font style and weight for a given font.
+          // The first item is a flag for italic.
+          // The second item is the numeric font weight.
+          // Example: [1, 700] for italic + bold
+          const variant = [Number(italic), weight || 400];
```
Comment (swissspidy) [inline assets/src/edit-story/output/utils/getFontDeclarations.js]: No need for this as `contentVariants` already contains the variants in the right format, no?

So you could do `for (const variant of contentVariants) {`

Comment (miina) [reply assets/src/edit-story/output/utils/getFontDeclarations.js]: Yes, true. Left it in for ensuring the `Number` + the `weight || 400` and the informative comment you left there! Can move the things around to use the `variant` directly though.

Comment (swissspidy) [reply assets/src/edit-story/output/utils/getFontDeclarations.js]: We can move the comment above the `for` 👍 
I think it's fine to expect the right format from `contentVariants`

File: assets/src/edit-story/components/richText/getFontVariants.js [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+  return [...styles];
+}
+
+export default function getFontVariants(html) {
+  const htmlState = getSelectAllStateFromHTML(html);
+  const variants = getVariants(htmlState)
+    .filter((variant) => variant.length)
+    .map((variant) => {
+      const weight = variant.find((val) => val.startsWith(WEIGHT));
+      const italic = variant.find((val) => val.startsWith(ITALIC));
```
Comment (barklund) [inline assets/src/edit-story/components/richText/getFontVariants.js]: Nit: As `ITALIC` is not a prefixed style, but a simple boolean flag, this could simply be `variant.includes(ITALIC)`.

File: assets/src/edit-story/components/richText/getFontVariants.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+ * Gets font styles for a characters, considers italic and weight only.
+ *
+ * @param {Object} styles Set of styles.
+ * @return {[]} Array of found styles for the character.
+ */
+function getFontStylesForCharacter(styles) {
+  return styles
+    .toArray()
+    .map((style) => style.style ?? style)
+    .filter((style) => style.startsWith(ITALIC) || style.startsWith(WEIGHT));
```
Comment (barklund) [inline assets/src/edit-story/components/richText/getFontVariants.js]: Similarly here, as style will be identical to `ITALIC` if anything.

```suggestion
    .filter((style) => style === ITALIC || style.startsWith(WEIGHT));
```

**Review by barklund — APPROVED** [review]
Two minor nits, otherwise looks good to me!

File: assets/src/edit-story/components/richText/getFontVariants.js [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+}
+
+export default function getFontVariants(html) {
+  const htmlState = getSelectAllStateFromHTML(html);
+  const variants = getVariants(htmlState)
+    .filter((variant) => variant.length)
+    .map((variant) => {
+      const weight = variant.find((val) => val.startsWith(WEIGHT));
+      const italic = variant.find((val) => val.startsWith(ITALIC));
+      return [italic ? 1 : 0, weight ? styleToNumeric(WEIGHT, weight) : 400];
```
Comment (swissspidy) [inline assets/src/edit-story/components/richText/getFontVariants.js]: When doing `variant.includes(ITALIC)`, you could then do:

```suggestion
      return [Number(italic), weight ? styleToNumeric(WEIGHT, weight) : 400];
```

Comment (swissspidy) [reply assets/src/edit-story/components/richText/getFontVariants.js]: Might then want to rename `italic` to `hasItalic` to make it clearer that it's a bool.

Comment (miina) [reply assets/src/edit-story/components/richText/getFontVariants.js]: Or perhaps using just `Number(variant.includes(ITALIC))` is self-explanatory enough?

Comment (swissspidy) [reply assets/src/edit-story/components/richText/getFontVariants.js]: even simpler 👍

**Review by swissspidy — APPROVED** [review]
