### PR TITLE
Media: Check URL before encoding

### LINKED ISSUE #11334: Encoding on encoded url for image
## Bug Description
Image url  is getting encoded without checking whether the url is already encoded while adding image url in the element. 

Note: This may not be a bug  for wordpress case

## Expected Behaviour
Would be good if we check the url before encoding.

## Steps to Reproduce
`Used storybook`
1. Use firebase storage image url 
2. Add image url in `getDummyMedia` list 
3. Go to  stories editor and add image from media section to the story card.

For more details please see below video 

Sample : 
```
    createDummyImageData({
      mimeType: 'image/jpeg',
      src: 'https://firebasestorage.googleapis.com/v0/b/c-dashboard-d4a82.appspot.com/o/media%2FNurUn5ekSeOkSCfk1yPIkg17buI3%2Fimages%2F1650068451121-omid-armin-nACf6L_pXq8-unsplash.jpeg?alt=media&token=edc4dfd7-6ac1-44a0-83b7-1aa99a3adad3',
      width: 5262,
      height: 7981,
      id: 1,
      title: 'dummy image',
    })
```
Actual image url : 
```
https://firebasestorage.googleapis.com/v0/b/c-dashboard-d4a82.appspot.com/o/media%2FNurUn5ekSeOkSCfk1yPIkg17buI3%2Fimages%2F1650068451121-omid-armin-nACf6L_pXq8-unsplash.jpeg?alt=media&token=edc4dfd7-6ac1-44a0-83b7-1aa99a3adad3
```

Encoded srcSet url : 
```
https://firebasestorage.googleapis.com/v0/b/c-dashboard-d4a82.appspot.com/o/media%252FNurUn5ekSeOkSCfk1yPIkg17buI3%252Fimages%252F1650068451121-omid-armin-nACf6L_pXq8-unsplash.jpeg?alt=media&token=edc4dfd7-6ac1-44a0-83b7-1aa99a3adad3 412w
```

## Screenshots
Screen Shot 2022-04-21 at 11 01 29 PM

## Video
https://user-images.githubusercontent.com/12577046/164589464-08e291c7-f0b3-4ea8-a918-0ba55045a78c.mov

## Additional Context
https://github.com/GoogleForCreators/web-stories-wp/blob/925e8057d693f05c3803740d8634617f2825ce7b/packages/media/src/calculateSrcSet.js#L50

- Branch : main branch 
- WordPress Version: Not applicable 
- Operating System: mac
- Browser: chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Firebase storage URLs contain a URL-encoded `/` (`%2F`). If it gets double-encoded, URLs won't work anymore.

## Summary

This PR simply checks for the existence of `%` within the string to determine whether the URL should be URI-encoded or not.

## User-facing changes

N/A

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. TBD (need to find a good test URL that works)

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11334

### CODE REVIEW

File: packages/media/src/calculateSrcSet.js [hunk 1]
```diff
@@ -19,6 +19,23 @@
...
+/**
+ * Encodes a text string as a valid Uniform Resource Identifier (URI)
+ *
+ * Only encodes strings that do not look like they're already encoded,
+ * by first looking for the percentage sign character.
+ *
+ * @param {string} str A value representing an encoded URI.
+ * @return {string} Encoded URI
+ */
+function maybeEncodeURI(str) {
```
Comment (spacedmonkey) [inline packages/media/src/calculateSrcSet.js:31]: Should we add `replaceAll(',', '%2C')` to this function and add some unit tests?

Comment (swissspidy) [reply packages/media/src/calculateSrcSet.js:31]: You mean like this?

```js
function maybeEncodeURI(str) {
  if (str.includes('%')) {
    return str.replaceAll(',', '%2C');
  }

  return encodeURI(str).replaceAll(',', '%2C');
}
```

That's a bit repetitive and less readable IMHO.

I don't see an issue with the current location of the `.replaceAll()` call.

We already have a unit test for the comma handling.

**Review by spacedmonkey — APPROVED** [review]
