### PR TITLE
Fix multi-select bug including background element

### LINKED ISSUE #363: Background element should not be allowed to be moved as part of multi-selection
**To reproduce**

1. Select background element
1. Cmd-click on other element to start multi-selection
1. Move elements around

**Actual behavior**

* The background element moves as part of the selection
* As soon as moving stops, it goes back to its background element position, but it keeps the changed coordinates

**Expected behavior**

The background element should not move as part of the multi-selection, and coordinates should be unchanged

### PR DESCRIPTION
**Pull request by barklund**
Multi-selection can never include the background-element, but if you selected the bg first, it was possible. This PR fixes that.

Fixes #363.

### CODE REVIEW

File: assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js [hunk 1]
```diff
@@ -37,6 +37,14 @@ function selectElement(state, { elementId }) {
     return state;
   }
 
+  // If bg element was already the (only) selection, set selection to new element only
+  if (state.selection.includes(currentPage.backgroundElementId)) {
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js:41]: Nit: `state.selection.includes` doesn't read as "the only". Are you concerned that other elements would somehow creep in?

**Review by dvoytenko — APPROVED** [review]
LGTM with one nit.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/selectElement.js:41]: That background element either has to be the only selected element or not selected at all is an invariant of the system (that this specific line of code in fact maintains), so it should not need validation as it should now be impossible to get to that situation.
