### PR TITLE
Fix lazy loading fonts preview by reducing re-renders

### LINKED ISSUE #7507: Font preview is no longer working
## Bug Description

Font preview in the drop down selector for fonts is no longer working as it was

## Expected Behaviour

Fonts should be presented with the name in the font.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
## Context

Lazy loading fonts preview was not working in all cases (initial view and search worked, but when scrolled down the preview was not loading).

## Summary & Relevant Technical Choices

There are few ways to fix that but the key point is that since we don't use (render) the information about what fonts the user saw (in that component [Dropdown]) there is no need to store them in state. That approach reduces re-renders and fixes issues caused by losing the connection to original nodes.

## User-facing changes

Font preview will always work now.

## Testing Instructions & QA & UAT

Insert text, open font picker, scroll down.
Before: only the initially visible list of fonts is loaded (preview of them).
Now: new fonts are also lodaded.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7507

### CODE REVIEW

**Comment by miina** [comment]
@merapi A conflict needs resolving FYI

File: assets/src/edit-story/components/form/advancedDropDown/list/list.js [hunk 1]
```diff
@@ -125,19 +125,23 @@ function OptionList({
...
-          entries.forEach((entry) => {
-            if (entry.isIntersecting) {
-              setUserSeenOptions(addUniqueEntry(entry.target.dataset.option));
-            }
-          });
+          if (onObserve) {
+            const newlySeenOptions = entries
+              .filter((entry) => entry.isIntersecting)
+              .map((entry) => entry.target.dataset.option);
+            userSeenOptions.current = addUniqueEntries(...newlySeenOptions)(
```
Comment (miina) [inline assets/src/edit-story/components/form/advancedDropDown/list/list.js]: Maybe change the function so that it could be just used `addUniqueEntries(...newlySeenOptions, userSeenOptions.current)`?

File: .github/workflows/plugin-release.yml [hunk 2]
```diff
@@ -54,23 +54,23 @@ jobs:
...
-#            exit 1
-#          fi
-#
-#          git checkout --track origin/$BRANCH
-#
-#          if ! git describe --abbrev=0 --tags --match "$TAG_NAME-rc.*" &>/dev/null; then
-#            echo "No RC exists for this planned stable release"
-#            exit 1
-#          fi
+      #      - name: Ensure RC exists for stable release
```
Comment (miina) [inline .github/workflows/plugin-release.yml]: Unintentional change?

File: assets/src/edit-story/components/form/advancedDropDown/list/list.js (hunk 1 above)
Comment (merapi) [reply assets/src/edit-story/components/form/advancedDropDown/list/list.js]: Yeah, I will do that, the curried version played nice with the useState, but now it's just used in this one place.

File: .github/workflows/plugin-release.yml (hunk 2 above)
Comment (merapi) [reply .github/workflows/plugin-release.yml]: ✅

**Review by miina — APPROVED** [review]
