### PR TITLE
Change amp-story-page background color to match editor preview

### LINKED ISSUE #3133: Letterboxing when viewing story via Instagram in-app browser
## Bug Description

I'm attempting to use web stories as my Instagram profile link to house various links. The stories work great in my browser on both desktop and mobile, but when I open with Instagram specifically (I'm not sure what they use as a browser) it creates a margin at the top of the page that cuts off the stories, and I can't seem to replicate anywhere else. It very well may just be something on Instagram's side, but my technical knowledge is very limited and wanted to throw it out there- if this is not a fixable bug, I understand.

## Expected Behaviour

If I open the link on a regular mobile browser, it works perfectly, but it is creating an extra margin when opened on Instagram and cutting off content.

## Steps to Reproduce

Opening a story link through the website URL option in an Instagram profile. (Not currently live on my page but can add it back if needed)

## Screenshots

Instagram viewing:
C6BF9886-4417-41D7-B5E9-9CC2A3717F2E_1_105_c

Mobile browser viewing:
7C1A096C-DEAD-4BDD-BA24-EC558FFB8EC6_1_105_c

## Additional Context

- Plugin Version: 1.0 Beta
- Operating System: iOS 13.5.1
- Browser: Instagram (does not happen in Facebook's mobile browser)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dreamofabear**
## Summary

Changes the background color of `amp-story-page` (behind the 9:16 authored content) to a dark gray. 

This color matches what users see in the editor preview and is close to what other platforms (IG/Snap) use too.

## Relevant Technical Choices

N/A

## To-do

N/A

### Before

Screen Shot 2020-09-28 at 5 12 08 PM

### After

Screen Shot 2020-09-28 at 5 35 42 PM

## Testing Instructions

- Open a story in Chrome with mobile emulation on iPhone X (or a similarly tall device). 
- Observe the color of the background above/below the actual story content.

---

Fixes #3133

### CODE REVIEW

**Comment by dreamofabear** [comment]
@samitron7 PTAL at screenshots above and let me know what you think.

**Comment by samitron7** [comment]
@choumx It's hard to tell in the screenshot but the runtime preview bg color is #202125. Can I ask why we are doing this versus ensuring that the page bg color or image/video stretches to cover the page?

**Comment by dreamofabear** [comment]
> It's hard to tell in the screenshot but the runtime preview bg color is #202125.

Hmm the code shows the color is `#1b1d1c` which is rgb(27,29,28). Also confirmed with macOS's eyedropper tool.

> Can I ask why we are doing this versus ensuring that the page bg color or image/video stretches to cover the page?

I thought about that but pages with full-screen image/video backgrounds may not have an appropriate page background color set (e.g. even our templates set a white background color). 

Also users don't have a way to easily preview this scenario (where viewport size is taller than 9:16), so IMO making the background color match what users see in the editor is, if not ideal, better than status quo.

Screen Shot 2020-09-30 at 10 32 34 AM

**Comment by dreamofabear** [comment]
Chatted with Sam offline and we're good to go. 👍

File: assets/src/edit-story/output/utils/styles.js [hunk 1]
```diff
@@ -22,11 +22,16 @@ import { FULLBLEED_RATIO, PAGE_RATIO } from '../../constants';
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+  const pageBackgroundColor = '#1b1d1c'; /* theme.colors.bg.workspace */
```
Comment (barklund) [inline assets/src/edit-story/output/utils/styles.js]: You can import the default export from `../../theme` and load it from there - then it would just be:

```js
import theme from '../../theme';
...
  const pageBackgroundColor = theme.colors.bg.workspace;
```

Comment (dreamofabear) [reply assets/src/edit-story/output/utils/styles.js]: Thanks! Sorry for the delay, I'll fix this today.

File: assets/src/edit-story/output/utils/styles.js [hunk 2]
```diff
@@ -18,15 +18,40 @@
...
+
+function isHexColorString(s) {
+  return (
+    s[0] == '#' &&
+    s
+      .substr(1)
+      .split('')
+      .every((char) => HEX_CHARS.includes(char))
+  );
+}
```
Comment (barklund) [inline assets/src/edit-story/output/utils/styles.js]: I think a regular expression is cleaner here:

```js
function isHexColorString(s) {
  // only allow `#XXX` or `#XXXXXX` with `X` being any hexadecimal character.
  return Boolean(s.match(/^#(?:[a-f0-9]{3}){1,2}$/i));
}
```

Though I'm not fully sure why we need to do this. Can the theme context be XSS'ed?

Comment (barklund) [reply assets/src/edit-story/output/utils/styles.js]: Also, what if we change it to `rgba(0, 255, 0, 0.5)` ? That's a perfectly legal CSS string too, that we suddenly can't use. Probably not an issue, but still a weird restriction.

File: assets/src/edit-story/output/utils/styles.js [hunk 3]
```diff
@@ -18,15 +18,40 @@
...
 
 function CustomStyles() {
   const safeToFullRatio = PAGE_RATIO / FULLBLEED_RATIO;
   const fullToSafeRatio = 1 / safeToFullRatio;
+
+  // Match page background color to the workspace background color.
+  // Validate since we're using dangerouslySetInnerHTML with imported variable.
+  const workspaceColor = theme.colors.bg.workspace;
+  let pageBackgroundColor = isHexColorString(workspaceColor)
```
Comment (barklund) [inline assets/src/edit-story/output/utils/styles.js]: Why `let`? We generally use `const` unless actually variable.

File: assets/src/edit-story/output/utils/styles.js (hunk 2 above)
Comment (dreamofabear) [reply assets/src/edit-story/output/utils/styles.js]: Cool, regex SGTM. The concern is if unsanitized user input somehow sneaks into variables. Probably low risk but these things can creep in over time.

**Review by swissspidy — APPROVED** [review]

**Comment by csossi** [comment]
Verified in QA
