### PR TITLE
Text Sets:  Bugfix - text sets toggle crashing app

### LINKED ISSUE #7394: Text Set Toggle Crashing App
Think we missed this in our last bug bash! 

Toggling the text sets to use the story fonts is crashing the app.

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Clicking the toggle would crash the app

## Summary

Looks like the shape of text sets changed. This updates the `getTextSetsForFonts` function so that it doesn't crash the app.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

n/a

## Testing Instructions

1. Open editor
2. Go to text sets in the library
3. Click the toggle. App should not crash and all text sets should use the current font on the story

### QA

- [ ] This is a non-user-facing change and requires no QA

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7394

### CODE REVIEW

File: assets/src/edit-story/utils/getInUseFonts.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ export function getInUseFontsForPages(pages) {
 export function getTextSetsForFonts({ fonts, textSets }) {
   return textSets
     .map((currentTextSet) => {
-      const hasFontInUse = currentTextSet.reduce(
+      const hasFontInUse = currentTextSet.elements.reduce(
```
Comment (samwhale) [inline assets/src/edit-story/utils/getInUseFonts.js:54]: Looks like the shape of text sets now looks like this:

image

`textSets` is no longer an array of 'arrays of elements' but rather an array of objects. Each object has the elements on the `elements` property.

**Review by maxyinger — APPROVED** [review]
looks good! I guess something must of flown under the radar recently that changed the structure of this 🤷

**Review by BrittanyIRL — APPROVED** [review]
Thank you for fixing this so fast. Pretty sure it's from adding in labels for text sets. That got merged last week, so this hasn't been around too long.
