### PR TITLE
Karma: ensure Google Fonts are loaded for tests and snapshots

### LINKED ISSUE #5396: Karma: ensure Google Fonts are loaded for tests and snapshots
## Task Description

Percy often fails because the web fonts haven't been loaded completely, showing everything in Times New Roman. Let's make this more robust.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Testing Instructions

---

Fixes #5396

### CODE REVIEW

File: assets/src/edit-story/karma/fixture/fixture.js [hunk 1]
```diff
@@ -291,6 +291,14 @@ export class Fixture {
       }
     });
 
+    // Check to see if Roboto font is loaded.
+    await waitFor(async () => {
+      await document.fonts.load('0 Roboto', '');
+      if (!document.fonts.check(' 0 Roboto', '')) {
+        throw new Error('Not ready: Roboto font could not be loaded');
+      }
+    });
```
Comment (swissspidy) [inline assets/src/edit-story/karma/fixture/fixture.js]: Can we do a similar check for Google Sans on the dashboard fixture?

File: karma-edit-story.config.cjs [hunk 2]
```diff
@@ -143,6 +143,8 @@ module.exports = function (config) {
       jasmine: {
         timeoutInterval: 10000,
       },
+      useIframe: false,
+      runInParent: true,
```
Comment (swissspidy) [inline karma-edit-story.config.cjs:147]: Could you elaborate on the reason for this change?

Looks reasonable as it seems to fix some issues with tooltip positioning, but curious to know how this relates to this PR.

---

Adding the [docs](http://karma-runner.github.io/5.2/config/configuration-file.html) for reference:

> useIframe (default: `true`)
> If true, Karma runs the tests inside an iFrame. If false, Karma runs the tests in a new window. Some tests may not run in an iFrame and may need a new window to run.

> runInParent (default: `false`)
> If true, Karma runs the tests inside the original window without using iframe. It will load the test scripts dynamically.

Comment (swissspidy) [reply karma-edit-story.config.cjs:147]: I see now that if `runInParent` is `true`, `customClientContextFile	` needs to be used instead of `customContextFile`.

So it sounds like using `customContextFile` did not work?

Comment (spacedmonkey) [reply karma-edit-story.config.cjs:147]: `customContextFile` didn't work. I couldn't work out why. Using `runInParent` and `useIframe` forces the use of `customClientContextFile`

File: assets/src/edit-story/karma/fixture/fixture.js (hunk 1 above)
Comment (spacedmonkey) [reply assets/src/edit-story/karma/fixture/fixture.js]: Done https://github.com/google/web-stories-wp/pull/5597/commits/92b9ddcf87dc629b38fbbbae44c1732bdd28d51f

File: assets/src/edit-story/karma/fixture/fixture.js [hunk 3]
```diff
@@ -291,6 +291,14 @@ export class Fixture {
       }
     });
 
+    // Check to see if Roboto font is loaded.
+    await waitFor(async () => {
+      await document.fonts.load('0 Roboto', '');
+      if (!document.fonts.check(' 0 Roboto', '')) {
```
Comment (swissspidy) [inline assets/src/edit-story/karma/fixture/fixture.js]: Just to confirm, is `0 Roboto` the right syntax? I haven't tested it in the browserr when I wrote that comment.

Also, there's an errant leading space.

File: assets/src/dashboard/karma/fixture.js [hunk 4]
```diff
@@ -196,9 +196,13 @@ export default class Fixture {
     this._container = container;
     this._screen = screen;
 
-    // @todo: find a stable way to wait for the story to fully render. Can be
-    // implemented via `waitFor`.
-    return Promise.resolve();
+    // Check to see if Google Sans font is loaded.
+    await waitFor(async () => {
+      await document.fonts.load('0 Google Sans', '');
+      if (!document.fonts.check(' 0 Google Sans', '')) {
```
Comment (swissspidy) [inline assets/src/dashboard/karma/fixture.js]: Same question about syntax here. Just want to confirm that it's correct.

Also, there's an errant leading space.

File: assets/src/edit-story/karma/fixture/fixture.js (hunk 3 above)
Comment (spacedmonkey) [reply assets/src/edit-story/karma/fixture/fixture.js]:
```suggestion
      const font = '12px Roboto';
      await document.fonts.load(font, '');
      if (!document.fonts.check(font, '')) {
```

I don't think we need the space or the empty string. We could try and check to see if a special character here is loaded, like this, 

```
document.fonts.check("12px Roboto", "ß");
```

But this maybe overkill. 

You may also notice that I changed it to 12px from 0. Why not render a reasonable size to see if it works.

Comment (swissspidy) [reply assets/src/edit-story/karma/fixture/fixture.js]: Cool. Let's do `'12px Roboto', ''` and `'12px "Google Sans"', '')` then. (note the quotes for `Google Sans`)

File: assets/src/dashboard/karma/fixture.js (hunk 4 above)
Comment (swissspidy) [inline assets/src/dashboard/karma/fixture.js]:
```suggestion
      const font = '12px "Google Sans"';
      await document.fonts.load(font, '');
      if (!document.fonts.check(font, '')) {
```

**Review by swissspidy — CHANGES_REQUESTED** [review]
Just two small changes needed before we can ship this 👍
