### PR TITLE
Pre-Publish Checklist: Include font size in text contrast check

### LINKED ISSUE #5913: Page Layouts - Prepublish checklist low contrast warning triggered by font colours
## Bug Description

orginally reported by @embarks:

The font colors for many of the simple templates trigger the low contrast warning which are to w3 standards. Could be addressed with checking font size as well, but the smaller fonts will always trigger.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Context
- We are currently not using the text element's `fontSize` value to determine if the contrast is great enough between itself and its background element. This fix should reduce the number of false positives when using decorative text that is still readable due to its large size.

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

## Summary
- The accessibility standards allow for larger fonts to have a lower contrast ratio. We should let rules of this standard drive the accessibility standards of the editor.
- Do this by providing the normalized font size to the accessibility checking library

## Relevant Technical Choices

When the contrast checking was initially implemented we relied on a library that used the element font size to determine if the contrast was acceptable to w3 standards. Due to a lack of support, we swapped out for the current dependency `@ap.cx/hues` which does not document their support of font size [in their README](https://github.com/thierryc/hues#readme), although it makes mention of the standard. The `aa` check does support font size upon observing the source code, however, so I'm leveraging that here.

Hopefully the new unit tests for `contrastUtils` illustrate how the font size impacts the rating. A lower ratio between color luminosities is acceptable with a larger font size. The minimum font size values used there are according to the w3 standard:
https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

I attempted to convert the element's font size number with the font size that would be displayed by sharing code between `text/output` and `accessibility` through the `units` module. I am intending to comply with the accessibility standards so rather than passing in the font size value from the element raw, I'm trying to convert it to its "pt" size... I _think_ I have it right but would love some input there.

## To-do
- N/A

## User-facing changes
N/A this is a bug fix

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. create a new story
2. add default text (size 12)
3. change the color of that text to `#777777` (a medium gray)
4. There should be a contrast warning in the checklist
5. change the size to a large font size, >83
6. the contrast warning should not be in the checklist

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5913

### CODE REVIEW

File: assets/src/edit-story/utils/contrastUtils.js [hunk 1]
```diff
@@ -48,14 +48,19 @@ export function calculateLuminanceFromStyleColor(styleColor) {
...
+ * https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
+ */
 /**
  * Check contrast ratios from luminances for WCAG guidelines
  *
  * @param  {number} luminanceA Luminance A
  * @param  {number} luminanceB Luminance B
+ * @param  {number} fontSize Font size
  * @return {Object} WCAG contrast ratio checks
  */
```
Comment (swissspidy) [inline assets/src/edit-story/utils/contrastUtils.js:62]: This could be easily part of the docblock.

```suggestion
/**
 * Check contrast ratios from luminances for WCAG guidelines.
 *
 * 18 point text or 14 point bold text is judged to be large enough to require a lower contrast ratio.
 * See https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
 *
 * @param  {number} luminanceA Luminance A
 * @param  {number} luminanceB Luminance B
 * @param  {number} fontSize Font size
 * @return {Object} WCAG contrast ratio checks
 */
```

**Review by BrittanyIRL — APPROVED** [review]
Warning disappears with a larger font! LGTM.

**Review by samwhale — APPROVED** [review]
The tests are rad

**Review by maxyinger — APPROVED** [review]
