### PR TITLE
Use the 'scroll' event to load more media results

### LINKED ISSUE #3182: Investigate flakiness of mediaFetching Karma tests.
The `assets/src/edit-story/components/library/panes/media/media3p/karma/mediaFetching.karma.js` test seems to be very flakey.
On CI I see tons of messages like this:
`ERROR: 'Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.` as well as `Error: Not ready errors from expectMediaElements`

### PR DESCRIPTION
**Pull request by cvolzke4**
## Summary

Fix the flakey media3p pagination test, by using the 'scroll' event instead of useIntersectionEffect:
* Call setNextPage when the 'scroll' event indicates the user is near the bottom.
* Call setNextPage if the scrollbar is not visible, with empty space available for more results.
This can happen if the user has a large monitor or zooms out.

The test was flakey because <Gallery> has multiple layout cycles, and so useIntersectionEffect would erroneously think that the user is near the bottom of the page during one of these cycles.

Fixes: https://github.com/google/web-stories-wp/issues/3182

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js [hunk 1]
```diff
@@ -92,7 +92,9 @@ function PaginatedMediaGallery({
         !isMediaLoaded ||
         isMediaLoading ||
         !hasMore ||
-        !entry.isIntersecting
+        !entry.isIntersecting ||
+        // Avoid loading the next page while <Gallery> is rendering.
+        entry.boundingClientRect.y < ROOT_MARGIN + 50
```
Comment (joannag6) [inline assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js]: Let's define 50 as a constant so it's clear what it represents.

**Review by joannag6 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js [hunk 2]
```diff
@@ -77,30 +83,61 @@ function PaginatedMediaGallery({
...
     },
-    [hasMore, isMediaLoading, isMediaLoaded, setNextPage]
+    500,
+    [hasMore, isMediaLoaded, isMediaLoading, setNextPage]
   );
 
+  useEffect(() => {
+    const node = refContainer.current;
+    if (!node) {
+      return undefined;
```
Comment (joannag6) [inline assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js]: Can you just `return;`?

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js [hunk 3]
```diff
@@ -77,30 +83,61 @@ function PaginatedMediaGallery({
...
+    if (!hasMore || !isMediaLoaded || isMediaLoading) {
+      return;
+    }
+
+    //eslint-disable-next-line @wordpress/react-no-unsafe-timeout
+    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
+
+    async function setNextPageIfCurrentPageNotFull() {
+      // Wait for <Gallery> to finish rendering first.
+      await sleep(50);
```
Comment (joannag6) [inline assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js:122]: Should we do another `isLoading` etc check after this sleep? (would it be possible for both `setNextPage()`s to be triggered?)

**Review by joannag6 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js (hunk 3 above)
Comment (cvolzke4) [reply assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js:122]: Done.

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js (hunk 2 above)
Comment (cvolzke4) [reply assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js]: This isn't allowed by the linter, as there shouldn't be a mix of 'return;' and 'return xxx' in the same function.

**Review by joannag6 — APPROVED** [review]
