### PR TITLE
Fixing a number of a11y problems with design panel components

### LINKED ISSUE #737: Side panel: buttons, toggles, switches have no keyboard-focusable outline or highlight
## Bug Description

image

In this screenshot, the "Flip horizontally" button has been focused by keyboard, but it's impossible to tell.

[figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9396%3A400304)

## Expected Behaviour

An outline or a highlight of some sort is shown.

## Steps to Reproduce

Navigate through side panel fields using <kbd>tab</kbd>.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #2084: Input fields are inconsistently styled when focused
## Bug Description

Some input fields turn alternate color scheme on focus, others do not. This must be synchronized, awaiting UX to clarify in which direction.

[figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9396%3A400304)

## Expected Behaviour

UX to clarify

## Steps to Reproduce

1. Select a text field
1. Click inside layer opacity input field
1. Then click inside text color opacity input field and observe the difference

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Summary

This fixes a number of design panel accessibility issues, including:

* Adds always-visible focus border to text inputs (both numeric and alphanumeric)
* Adds keyboard-only-visible focus border to drop downs, buttons and toggles
* Changes dropdown button to be an actual button
* Re-focus dropdown button when drop down closes when using keyboard (to not revert focus to canvas)
* Internal changes to padding control, so focus stays on the toggle when toggled (doesn't replace component)

## Relevant Technical Choices

* Some technical changes to color input structure and padding control necessitated by the above

## To-do

- [x] Improve keyboard accessibility for range slider (grid view, image editor, page advancement)
- [x] Improve keyboard accessibility for color input component (only design panel element, not color picker)
- [x] Improve keyboard accessibility for drop down (font family, font weight, author)
- [x] Improve keyboard accessibility for radio group (post status)
- [x] Improve keyboard accessibility for small toggle buttons (alignment, justification, bold/italic/underline, etc)
- [x] Improve keyboard accessibility for large toggle button/switch (video loop, auto page advancement)
- [x] Improve keyboard accessibility for number input component (multiple uses)
- [x] Improve keyboard accessibility for text input component (alt text, video title)
- [x] Improve keyboard accessibility for "edit color presets" button (keeps same button focused when pressed)
- [x] Improve keyboard accessibility for "toggle locked vertical/horizontal padding" button (keeps same button focused when pressed)
- [x] Move to new structure for annotating CUJ tests
- [x] Update existing tests to new CUJ test annotation structure
- [x] Add integration tests with screenshots of alignment panel
- [x] Add integration tests with screenshots of background overlay panel
- [x] Add integration tests with screenshots of link panel

## TODO in future PR's
- [ ] Add integration tests with screenshots of position & size panel
- [ ] Add integration tests with screenshots of background position & size panel
- [ ] Add integration tests with screenshots of shape style panel
- [ ] Add integration tests with screenshots of page style panel
- [ ] Add integration tests with screenshots of layer style panel
- [ ] Add integration tests with screenshots of image accessibility panel
- [ ] Add integration tests with screenshots of video accessibility panel
- [ ] Add integration tests with screenshots of video options panel
- [ ] Add integration tests with screenshots of text style panel
- [ ] Add integration tests with screenshots of style preset panel
- [ ] Add integration tests with screenshots of document page advancement panel
- [ ] Add integration tests with screenshots of document publish panel
- [ ] Add integration tests with screenshots of document slug panel
- [ ] Add integration tests with screenshots of document status panel

## User-facing changes

Compare how navigating with keyboard vs mouse looks now:

| With keyboard | With mouse
|-|-|
| designpanel_keyboard | designpanel_mouse |
| All elements have focus border | Only inputs have focus border |

## Testing Instructions

Tab through fields and observe that focus is always visible.

---

Fixes #737
Fixes #2084

### CODE REVIEW

**Comment by miina** [comment]
@barklund The document panel seems to be crashing on this PR.

Also, assuming the fixes should go for the Document panel as well? Based on the issues it seems so, however, the PR mentions only "design panel components". Thoughts?

**Comment by barklund** [comment]
> @barklund The document panel seems to be crashing on this PR.

@miina, hm, that's not good. Will fix!

> Also, assuming the fixes should go for the Document panel as well? Based on the issues it seems so, however, the PR mentions only "design panel components". Thoughts?

Yes, the changes also impact the document panel and any other location using panels and panel elements. I'll create similar videos for the document panel, though the changes are very similar there. Will have to do something about the radio group first though, as it's acting a bit weird when keyboard-only navigating it.

File: assets/src/edit-story/components/form/dropDown/index.js [hunk 1]
```diff
@@ -160,20 +186,12 @@ function DropDown({
...
-  options: PropTypes.array.isRequired,
   onChange: PropTypes.func.isRequired,
+  options: PropTypes.array,
   disabled: PropTypes.bool,
   lightMode: PropTypes.bool,
   placeholder: PropTypes.string,
   labelledBy: PropTypes.string,
 };
 
-DropDown.defaultProps = {
```
Comment (swissspidy) [inline assets/src/edit-story/components/form/dropDown/index.js:173]: What's the reason for not using defaultProps anymore?

Comment (barklund) [reply assets/src/edit-story/components/form/dropDown/index.js:173]: This component was using a mix of `defaultProps` and default values in component definition, which is a mess!

I decided to switch to only the latter, as it seems to be the recommended approach these days (and [`defaultProps` will get deprecated at some point for functional components](https://twitter.com/dan_abramov/status/1133878326358171650?lang=en) anyway).

File: assets/src/edit-story/components/form/radioGroup/index.js [hunk 2]
```diff
@@ -71,8 +72,14 @@ const Helper = styled.div`
 
 function RadioGroup({ onChange, value: selectedValue, options }) {
   const radioGroupId = useMemo(() => uuidv4(), []);
+
+  // We need manual arrow key navigation here, as we have a global listener for those keys
+  // preventing default functionality.
```
Comment (miina) [inline assets/src/edit-story/components/form/radioGroup/index.js:78]: Maybe we should instead just remove `radio` from the `NON_EDITABLE_INPUT_TYPES`? This would allow the default behavior which would make sense in case of radios. WDYT?

File: assets/src/edit-story/components/rangeInput/index.js [hunk 3]
```diff
@@ -58,4 +64,52 @@ export default styled.input.attrs(({ min, max, step, value, onChange }) => ({
...
+
+    &::-ms-thumb {
+      ${focusedRangeThumb}
+    }
+  }
 `;
+
+function RangeInput({ minorStep, majorStep, handleChange, value, ...rest }) {
+  const ref = useRef();
+  const update = useCallback(
```
Comment (miina) [inline assets/src/edit-story/components/rangeInput/index.js:113]: Is this respecting the min-max values?

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+      padding: {
+        ...rest,
+        horizontal: clamp(horizontal, MIN_MAX.PADDING),
+        vertical: clamp(vertical, MIN_MAX.PADDING),
+      },
+    }),
+    []
+  );
+
+  const firstInputProperties = lockPadding
```
Comment (miina) [inline assets/src/edit-story/components/panels/textStyle/padding.js:86]: Curious, what was the reason for combining the padding files? DRY? Or accessibility reasons, too?
It's reducing the readability a bit but perhaps the benefits have more weight.

File: assets/src/edit-story/components/panels/stylePreset/header.js [hunk 5]
```diff
@@ -80,36 +107,35 @@ function PresetsHeader({
...
+        )}
+        {!isEditMode && (
+          <Button
+            Icon={AddColorPresetButton}
+            onClick={handleAddColorPreset}
+            aria-label={__('Add preset', 'web-stories')}
           >
-            <EditPencil />
-          </EditModeButton>
+            <AddPage />
```
Comment (miina) [inline assets/src/edit-story/components/panels/stylePreset/header.js]: `AddPage`? Let's rename to something more accurate, for example `AddPreset`?

Maybe generally the icon should be renamed to `Add` and then used as `Add*` as needed in different contexts? Thoughts?

File: assets/src/edit-story/components/panels/stylePreset/header.js [hunk 6]
```diff
@@ -80,36 +107,35 @@ function PresetsHeader({
   const hasPresets = colors.length > 0;
 
   const getActions = () => {
-    return !isEditMode ? (
+    return (
```
Comment (miina) [inline assets/src/edit-story/components/panels/stylePreset/header.js:110]: Same question here, was DRY the main reason for combining the two buttons into one, or also accessibility-related?

File: assets/src/edit-story/components/rangeInput/index.js [hunk 7]
```diff
@@ -58,4 +64,52 @@ export default styled.input.attrs(({ min, max, step, value, onChange }) => ({
...
+      ${focusedRangeThumb}
+    }
+
+    &::-ms-thumb {
+      ${focusedRangeThumb}
+    }
+  }
 `;
+
+function RangeInput({ minorStep, majorStep, handleChange, value, ...rest }) {
```
Comment (miina) [inline assets/src/edit-story/components/rangeInput/index.js]: The `majorStep` is basically the default step, is that correct? The naming feels a bit odd as if there would be no option to do a "normal" step -- it's always either minor or major. WDYT if it would be just `step` and `minorStep`?
Or perhaps alternatively just leave a comment for clarity that `majorStep` is the default step?

**Comment by miina** [comment]
There are various console errors, it's still WIP, assuming that's expected currently?

A few more notes from testing:
- The color presets don't seem to be functional for text element currently, getting this error:
Screenshot 2020-07-06 at 11 41 55

- The focus isn't visible when the color preset is white -- is this expected?

File: assets/src/edit-story/components/panels/panel/shared/title.js [hunk 8]
```diff
@@ -106,6 +107,32 @@ const Collapse = styled.button`
   }
 `;
 
+function Toggle({ children, toggle, ...rest }) {
+  // We unfortunately have to manually assign this listener, as it would be default behaviour
+  // if it wasn't for our listener further up the stack interpreting enter as "enter edit mode"
```
Comment (miina) [inline assets/src/edit-story/components/panels/panel/shared/title.js:112]: I wonder if instead, the "enter edit mode" could be adjusted so that it would be ignored when relevant input is in focus. E.g. in a similar way as `isEditableTarget` or `nativeCopyPasteExpected` are working. Thoughts?

File: assets/src/edit-story/components/form/switch.js [hunk 9]
```diff
@@ -120,9 +121,16 @@ function Switch({ value, disabled, onChange, onLabel, offLabel }) {
     },
     [onChange]
   );
+  const ref = useRef();
+  useKeyDownEffect(
+    ref,
+    ['space', 'enter', 'left', 'right'],
```
Comment (miina) [inline assets/src/edit-story/components/form/switch.js:127]: Is it expected that if the value is already on the "right" then clicking `right` will still toggle it? Thoughts?

File: assets/src/edit-story/components/form/radioGroup/index.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/form/radioGroup/index.js:78]: Hm, not a bad idea, will look into it.

File: assets/src/edit-story/components/rangeInput/index.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/rangeInput/index.js:113]: Good question!

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/textStyle/padding.js:86]: Accessibility - I wanted keyboard focus to stay on the lock icon button when clicking it (so when tabbing through and pressing enter on the button, you could keep tabbing from that same button). Thus it had to be a single component and had to return the same object, but with slightly different properties for the button, so React would treat it as the same DOM element and the browser would not move focus around.

I actually first tried manually refocusing the "new" button, but it was horrible.

File: assets/src/edit-story/components/panels/stylePreset/header.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/stylePreset/header.js:110]: Focus management again.

File: assets/src/edit-story/components/panels/stylePreset/header.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/stylePreset/header.js]: Didn't even consider that, but it makes sense. Will look into it.

File: assets/src/edit-story/components/rangeInput/index.js (hunk 7 above)
Comment (barklund) [reply assets/src/edit-story/components/rangeInput/index.js]: `majorStep` is the default when using keyboard, however when using the actual range, the "default" step (the smallest interval you can move with the mouse) would be the `minorStep`. I thought it was fairly self-explanatory but clearly not - will add some commentary.

**Comment by barklund** [comment]
> There are various console errors, it's still WIP, assuming that's expected currently?

There shouldn't be any console errors, no. I believe I've fixed everything fully (pending comments) up until this point.

> * The color presets don't seem to be functional for text element currently, getting this error:

Sounds troubling, will look into it. Probably only tested with a shape.

> * The focus isn't visible when the color preset is white -- is this expected?

Ah yeah, that's an issue. Might need to check color brightness and swap focus color based off of that.

File: assets/src/edit-story/components/form/switch.js (hunk 9 above)
Comment (barklund) [reply assets/src/edit-story/components/form/switch.js:127]: Good question - I debated it with myself and thought that it didn't matter that this happened. It was slightly unexpected, but not a huge deal IMO.

File: assets/src/edit-story/components/panels/panel/shared/title.js (hunk 8 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/panel/shared/title.js:112]: That would be an option too - but not easy to do. I don't think I'll look into that option in this PR, but it's definitely an option for improvement.

File: assets/src/edit-story/components/rangeInput/index.js (hunk 7 above)
Comment (miina) [reply assets/src/edit-story/components/rangeInput/index.js]: Oh, right, I was only focusing on the keyboard part and didn't even think about the mouse while reviewing.

File: assets/src/edit-story/components/form/radioGroup/index.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/form/radioGroup/index.js:78]: So this actually didn't work - and the same for the buttons. Not completely sure why, maybe something about the events not bubbling up correctly.

Comment (miina) [reply assets/src/edit-story/components/form/radioGroup/index.js:78]: Hmm, odd, when I test locally (on the main branch), it seems to work when just removing `radio` from `NON_EDITABLE_INPUT_TYPES`. E.g. I remove this, click on "Status and Visibility" Panel, tab into the radio button, use the arrow keys and the values change.

Is it not working at all when you try or it working in an unexpected way?

**Review by merapi — COMMENTED** [review]
Should this radio group have a focus border when navigating with the mouse?

image

**Review by merapi — COMMENTED** [review]
If the first color is not applicable to text and you have text element selected - you will not be able to focus and change colors via keyboard.

Should we file a separate issue for it (since it was not introduced here) or it can be quickly fixed here?

image

**Review by merapi — APPROVED** [review]
Overall: great improvement, now the design panel is so much nicer when navigating with the keyboard ⌨️ 👍

**Comment by swissspidy** [comment]
> If the first color is not applicable to text and you have text element selected - you will not be able to focus and change colors via keyboard.

Sounds like the button is `disabled` there. So it won't get focus. To fix this, we can do:

1. no-op the button
1. use `aria-disabled` to communicate the button inert state
1. style the button as it was disabled
