### PR TITLE
prepublish checklist - missing critical metadata

### LINKED ISSUE #4910: Pre-Publish Checklist: Missing Critical Metadata Logic
## Feature Description

Implement the logic to throw an error if one or more of the critical issues are present:

- Missing title
- Missing story portrait cover
- Story portrait cover size too small (less than 640 x 853) or wrong aspect ratio (not 3:4) ← we should try to prevent this
- Publisher logo is too small (less than 96x96) ← we should just prevent this. 
- Link and page attachment conflicts: there’s a link in the page attachment region, and page attachment is enabled for that page. ← we will try to prevent this in most cases, but capturing a final check to avoid edge cases. 

These are critical issues and a story should not be publishable with these present.

https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Summary

- adds tests and logic for the critical story metadata checks for the prepublish checklist.

## Relevant Technical Choices
- I kept the `publisherLogo`/`featuredMedia` tests and logic in, even though it's not supported yet. We might want to eliminate the publisher logo logic for clarity as that will be prevented per #5107. Featured media will be supported after #5105. 

## To-do
- [x] unit tests
- [x] add comment/adjust tests to refer to changes mentioned [here](https://github.com/google/web-stories-wp/issues/5105)

## User-facing changes

None.
## Testing Instructions

- Run unit tests.
---

Fixes #4910

### CODE REVIEW

**Review by BrittanyIRL — APPROVED** [review]
LGTM 🚀

File: assets/src/edit-story/app/story/effects/useLoadStory.js [hunk 1]
```diff
@@ -48,8 +48,10 @@ function useLoadStory({ storyId, shouldLoad, restore }) {
           excerpt: { raw: excerpt },
           link,
           story_data: storyDataRaw,
+          // todo: get featured_media_url original dimensions for prepublish checklist
           featured_media: featuredMedia,
           featured_media_url: featuredMediaUrl,
+          // todo: get publisher_logo_url image dimensions for prepublish checklist
```
Comment (zachhale) [inline assets/src/edit-story/app/story/effects/useLoadStory.js:54]: Are these `todo` comments relevant still?

File: assets/src/edit-story/app/prepublish/errors/metadata.js [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+ * Check that the story's publisher logo resource has sufficient dimensions.
+ * If the resource is too small in either dimension, return an error message.
+ * Otherwise, return undefined.
+ *
+ * @param {Story} story The story being checked for critical metadata
+ * @return {Guidance|undefined} Guidance object for consumption
+ */
+export function publisherLogoSize(story) {
+  if (
+    story.publisherLogo.height < PUBLISHER_LOGO_MIN_HEIGHT ||
```
Comment (zachhale) [inline assets/src/edit-story/app/prepublish/errors/metadata.js:125]: Is `story.publisherLogo` the right path for this? I see `featuredMedia` gets sent down, but I don't see any reference to `publisherLogo` getting passed through for testing.

File: assets/src/edit-story/app/story/effects/useLoadStory.js (hunk 1 above)
Comment (embarks) [reply assets/src/edit-story/app/story/effects/useLoadStory.js:54]: yes, will be handled by #5105 & #5107

File: assets/src/edit-story/app/prepublish/errors/metadata.js (hunk 2 above)
Comment (embarks) [reply assets/src/edit-story/app/prepublish/errors/metadata.js:125]: yeah check out the update story calls [here for featuredMedia](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/inspector/document/publish/index.js#L95) and [here for publisherLogo](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/inspector/document/publish/index.js#L107) (`updateStory` reducer is implemented [here](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/app/story/useStoryReducer/reducers/updateStory.js). They both live on the top-level story and will probably be migrated to objects in a similar way, e.g. https://github.com/google/web-stories-wp/issues/5105

We may end up removing this check entirely in favor of [just preventing the upload of a logo that is too small](https://github.com/google/web-stories-wp/issues/5107)

**Review by zachhale — APPROVED** [review]

File: assets/src/edit-story/app/prepublish/errors/metadata.js [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+  if (isLinkInPageAttachmentArea) {
+    return {
+      type: PRE_PUBLISH_MESSAGE_TYPES.ERROR,
+      storyId: story.storyId,
+      message: __(
+        'Story has a link in the page attachment region',
+        'web-stories'
+      ),
+    };
+  }
```
Comment (swissspidy) [inline assets/src/edit-story/app/prepublish/errors/metadata.js]: Don't we care more about the page ID where this is happening rather than the story ID?

What if this happens on multiple pages?

As a user I would want to quickly find & fix the page with this issue.

File: assets/src/edit-story/app/prepublish/errors/metadata.js [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+ * Otherwise, return undefined.
+ *
+ * @param {Story} story The story being checked for critical metadata
+ * @return {Guidance|undefined} Guidance object for consumption
+ */
+export function linkInPageAttachmentRegion(story) {
+  const { pages } = story;
+  const isLinkInPageAttachmentArea = pages.some((page) => {
+    const { elements } = page;
+    const isLinkAttached = Boolean(page?.pageAttachment?.url.length);
```
Comment (swissspidy) [inline assets/src/edit-story/app/prepublish/errors/metadata.js]: nit: `hasPageAttachment` sounds clearer

File: assets/src/edit-story/app/prepublish/errors/metadata.js (hunk 3 above)
Comment (embarks) [reply assets/src/edit-story/app/prepublish/errors/metadata.js]: yes! I'll have to return an array of page IDs

File: assets/src/edit-story/app/prepublish/errors/metadata.js [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+      elements.filter(({ link }) => link?.url?.length).some(isElementBelowLimit)
+    );
+  });
+
+  if (isLinkInPageAttachmentArea) {
+    return {
+      type: PRE_PUBLISH_MESSAGE_TYPES.ERROR,
+      storyId: story.storyId,
+      message: __(
+        'Story has a link in the page attachment region',
```
Comment (swissspidy) [inline assets/src/edit-story/app/prepublish/errors/metadata.js]:
```suggestion
        'Page has a link in the page attachment region',
```
