### PR TITLE
Disallow closing story takeover dialog

### LINKED ISSUE #12430: User is able to click outside take over notification and continue editing the story
## Bug Description

A user who is editing a web story, can have her story editing taken over by another user. When this happens, there is a notification seen on both parties: for the new/takeover author, there is a popup that says "Story is locked" while for the initial author, the message says "Someone else has taken over the story"

Issue: It is possible for both the initial author and the takeover author to click outside the popup message and continue editing the web story as if they had full access.

## Expected Behaviour

Since story locking is supposed to allow user to "lock" the story, the fact that a take over attempt can be ignored is not expected.

Compared to the behavior in a WP Post workflow, if the story is being taken over, the original author can _only_ go to the dashboard. Similarly, the takeover author has to explicitly choose to Take Over, instead of clicking outside somewhere and automagically take over the story editing.

Compare with the workflow for WP Posts

## Steps to Reproduce

1. Open a story in the editor after logging in as user-A
2. Open an incognito window or a separate browser and login as user-B
3. Try to edit/take over the story being edited in step 1.
4. There is a popup shown about take over attempt
5. Click anywhere outside the popup
6. Similarly for the user-A, there is a message that shows up
7. Click anywhere outside the popup

Issue: In all cases, it is possible to continue editing.

## Additional Context

If as user-A,  you wait for some time on the takeover context, and make some local changes WITHOUT SAVING, then there is a possibility that when user-B takes over the there are two popups showing up !!

- Plugin Version: 2022 Google Version 1.26.0-alpha.0+c65fc66
- WordPress Version: 6.0.2
- Operating System: win10
- Browser: Chrome/Firefox

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Found during bug bash

## Summary

Prevent closing the takeover dialog in any way.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

**Post Locking:**

1. Open a locked story
2. Try to close the story locking dialog by pressing ESC or by clicking outside the dialog
3. It should not be possible

**Post Takeover:**

1. Wait for your story to be taken over by someone else
2. Try to close the takeover dialog by pressing ESC or by clicking outside the dialog
3. It should not be possible

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12430

### CODE REVIEW

File: packages/wp-story-editor/src/components/postLock/postTakeOverDialog.js [hunk 1]
```diff
@@ -59,6 +59,8 @@ function PostTakeOverDialog({ isOpen, user, dashboardLink, onClose }) {
       title={dialogTile}
       contentLabel={dialogTile}
       onClose={onClose}
+      shouldCloseOnEsc={false}
```
Comment (spacedmonkey) [inline packages/wp-story-editor/src/components/postLock/postTakeOverDialog.js:62]: We need to add these values [here](https://github.com/GoogleForCreators/web-stories-wp/blob/31d01788be3a19732f0fc03085183cb6223260ca/packages/wp-story-editor/src/components/postLock/postLockDialog.js#L75) as well.

**Review by spacedmonkey — APPROVED** [review]
LGTM! :shipit:

**Review by barklund — APPROVED** [review]

**Comment by kkalarickal** [comment]
Confirmed on stories-qa-wordpress-amp.pantheonsite.io running the `12440` branch

1. When attempting to take over a story, the user doing take over is given the dialog and cannot click anywhere on the editor space.


2. On the other end, after a significant time, the original editor is presented with another dialog. She cannot click outside or escape from the dialog. 

Permutations:
- Confirmed that the dashboard/preview buttons work
- Verified that the auto-save entry made in session storage is deleted when the take over is completed.
