### PR TITLE
Fix author dropdown

### LINKED ISSUE #12842: Editor/Authors unable to list users for dropdown
## Bug Description

While editing a Story with an editor user role and navigating to the Document tab, the Author drop down is always stuck on an infinite load. This is accompanied by constant console errors and network errors (see screenshots below).

This happens no matter what the author value is set to and there is no way for the editor to amend this. This was initially raised in the support forum [here](https://wordpress.org/support/topic/user-compatibility-issue-while-changing-author-of-a-web-story/). 

This happens when both trying to edit an existing Story and creating a new Story.

## Expected Behaviour

Users with the editor role should be able to update the Author drop down and it should not be stuck on an infinite loop.

## Steps to Reproduce

1. Log into a site with the latest Web Stories with the editor role.
2. Create a new Story or edit a Story
3. Go to the Document tab 

## Screenshots

Console errors:
image

Network errors:
image

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Fix loading of the author dropdown for non-admin users.

Adds some hardening to the component so that it won't cause an infinite loop when loading fails.

## User-facing changes

If loading fails for some reason, the dropdown is now properly disabled:

Screenshot 2022-12-16 at 15 47 34

Before there was an infinite loop

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Log in as user with author role
2. Visit dashboard
3. Verify that user dropdown works
4. Log in as editor user
5. Create a new story
6. Go to Document tab
7. Verify that user dropdown works

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12842

### CODE REVIEW

File: includes/REST_API/Stories_Users_Controller.php [hunk 1]
```diff
@@ -94,6 +94,28 @@ public static function get_registration_action_priority(): int {
...
+	 *
+	 * @param WP_REST_Request $request Full details about the request.
+	 * @return true|WP_Error True if the request has read access, otherwise WP_Error object.
+	 */
+	public function get_items_permissions_check( $request ) {
+		if (
+			! empty( $request['capabilities'] ) &&
+			[ $this->story_post_type->get_cap_name( 'edit_posts' ) ] === $request['capabilities']
+		) {
+			unset( $request['capabilities'] );
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Users_Controller.php]: `capabilities` can be an array right? Should we not just unset the element in array. For example if you request this. 

/web-stories/v1/users?capabilities[]=test&capabilities[]=edit_posts

What about that case?

File: includes/REST_API/Stories_Users_Controller.php [hunk 2]
```diff
@@ -94,6 +94,28 @@ public static function get_registration_action_priority(): int {
...
+		}
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Users_Controller.php]:
```suggestion
		/**
		 * Capabilities.
		 *
		 * @var string[]|null $capabilities
		 */
		$capabilities = $request['capabilities'];
		if ( ! empty( $capabilities ) ) {
			$request['capabilities'] = array_filter(
				$capabilities,
				fn( $cap ) => $cap !== $this->story_post_type->get_cap_name( 'edit_posts' )
			);
		}
```

This might work better, as it would remove web stories capability check from any array.

File: packages/design-system/src/components/datalist/datalist.js [hunk 3]
```diff
@@ -239,6 +239,7 @@ const Datalist = forwardRef(function Datalist(
         selectButtonStylesOverride={highlightStylesOverride || focusStyle}
         aria-label={dropdownButtonLabel}
         isOpen={isOpen}
+        disabled={disabled}
```
Comment (spacedmonkey) [inline packages/design-system/src/components/datalist/datalist.js:242]: We may have to check other places in the codebase. It is a good fix.

**Comment by spacedmonkey** [comment]
Looking good apart from a nitpic. Once addressed, I will approve.

File: packages/design-system/src/components/datalist/datalist.js (hunk 3 above)
Comment (swissspidy) [reply packages/design-system/src/components/datalist/datalist.js:242]: I hope TS will help catch this kind of stuff

File: includes/REST_API/Stories_Users_Controller.php (hunk 1 above)
Comment (swissspidy) [reply includes/REST_API/Stories_Users_Controller.php]: > `capabilities` can be an array right?

Right, which is why `[ $this->story_post_type->get_cap_name( 'edit_posts' ) ] === $request['capabilities']` compares an array with an array (note the brackets)

If any other caps are in the array, this will continue to return a permission error.

It does exactly the same as your suggestion, no?

```
$request['capabilities'] = [ 'edit_web-story' ] // Allowed.
$request['capabilities'] = [ 'edit_web-story', 'foo' ] // Disallowed.
$request['capabilities'] = [ 'foo' ] // Disallowed.
```

**Review by spacedmonkey — APPROVED** [review]

**Comment by kkalarickal** [comment]
Confirmed that author dropdown shows up for an editor-user, and admin-user.


As an author-user, the drop down within the dashboard shows the various authors

**Comment by kkalarickal** [comment]
@swissspidy - Wanted to note that the stories-editor seems to enforce a hierarchy that prevents author-user from being visible to other authors or editors !

So if I login as an admin-user, I can see authors listed in the dashboard and re-assign author users to stories


However, if I login as editor or as another author, I am UNABLE to see author-users listed !!


This shows up as a "-" in the List view within stories editor

Not sure why we suppress author-users for editors/authors.

**Comment by swissspidy** [comment]
@kkalarickal Good catch. This is a bug in WordPress where it doesn't allow non-admins to see other users who have not published a post yet (yours was only a draft). I just added a workaround for this.

@spacedmonkey please test again, thanks!

File: includes/REST_API/Stories_Users_Controller.php [hunk 4]
```diff
@@ -94,6 +95,80 @@ public static function get_registration_action_priority(): int {
...
+		if (
+			! isset( $request['has_published_posts'] ) &&
+			! empty( $request['capabilities'] ) &&
+			[ $edit_posts ] === $request['capabilities'] &&
+			current_user_can( $edit_posts )
+		) {
+			$filter_user_query_args = static function ( $prepared_args ) {
+				unset( $prepared_args['has_published_posts'] );
+				return $prepared_args;
+			};
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Users_Controller.php]: Instead of a static function we have use a method on a class. 

https://github.com/GoogleForCreators/web-stories-wp/blob/a8b3261145020266209195f8ba31be80ddd8438e/includes/REST_API/Stories_Controller.php#L388

File: includes/REST_API/Stories_Users_Controller.php [hunk 5]
```diff
@@ -94,6 +95,80 @@ public static function get_registration_action_priority(): int {
...
+	public function get_items( $request ) {
+		/**
+		 * The edit_posts capability.
+		 *
+		 * @var string $edit_posts
+		 */
+		$edit_posts = $this->story_post_type->get_cap_name( 'edit_posts' );
+
+		if (
+			! isset( $request['has_published_posts'] ) &&
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Users_Controller.php:152]: When and why are we setting this? I can't see it in the request. `has_published_posts`

Comment (swissspidy) [reply includes/REST_API/Stories_Users_Controller.php:152]: The parent `WP_Rest_Users_Controller::get_items()` method is setting it here:

https://github.com/WordPress/wordpress-develop/blob/008277583be15ee1738fba51ad235af5bbc5d721/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L308-L312

File: includes/REST_API/Stories_Users_Controller.php (hunk 4 above)
Comment (swissspidy) [reply includes/REST_API/Stories_Users_Controller.php]: There's no post_type, the filter name is hardcoded `rest_user_query`.

https://github.com/WordPress/wordpress-develop/blob/008277583be15ee1738fba51ad235af5bbc5d721/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L333

But yeah I can add this as a class method.

**Review by spacedmonkey — APPROVED** [review]

**Comment by kkalarickal** [comment]
@swissspidy - confirmed that editor-user is able to see author-user in the drop down list and within dashboard >list view

However, there is a corner case where [on stories-qa](https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard) an editor-user cannot see one of the admin-users only within the List view !!



Same list view when logged in as admin-user is like this:

**Comment by kkalarickal** [comment]
For some reason my KK-Editor role user cannot list KK-Admin  role user :(

**Comment by swissspidy** [comment]
Good find. It's because editors don't have as many permissions.

I will create a new ticket for this.

**Comment by swissspidy** [comment]
Created #12866 as a follow-up
