### PR TITLE
Fix issues with uploading and hotlinking story poster

### LINKED ISSUE #12029: Continued issues with story poster in v1.23.1
## Bug Description

This is a follow-up to #11980

Apparently #11982 didn't fully address all issues with story posters, so we need to look into this again.

Related: #12028

## Expected Behaviour

Setting/updating/removing the story poster should "just work".

## Steps to Reproduce

1. Create story with some poster image, publish.
2. Refresh editor, change poster image, save
3. Refresh editor (or go to dashboard), see old poster image
4. Repeat with a hotlinked image

## Additional Context

- Plugin Version: 1.23.1
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Apparently #11982 / v1.23.1 didn't completely fix all issues with story posters, see #12029

## Summary

This PR attempts to consolidate logic for (hotlinked) story posters to ensure expected behavior is met.

## Relevant Technical Choices

Move the relevant logic to the REST controller so that the JS code does not have to deal with it. Adds a new `story_poster` field to the API response.

Updates `getStoryPropsToSave` in `story-editor` to not return any `meta` object. `getStorySaveData` in `wp-story-editor` already handles that.

## To-do

* [x] Add tests
* [x] Check that REST API preloading still works

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new story
2. Add a new poster image from the media library, publish.
3. Save story
4. Refresh editor (or go to dashboard), see new poster image reflected in both editor and dashboard
5. Repeat with a hotlinked image
6. In general, saving should still work as expected

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12029

### CODE REVIEW

File: packages/story-editor/src/app/story/utils/getStoryPropsToSave.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ import objectPick from '../../../utils/objectPick';
 import getAllProdcuts from './getAllProducts';
```
Comment (miina) [inline packages/story-editor/src/app/story/utils/getStoryPropsToSave.js:25]: Not related to this PR at all but there's a typo when importing.

File: packages/story-editor/src/app/story/utils/getStoryPropsToSave.js [hunk 2]
```diff
@@ -49,19 +50,7 @@ function getStoryPropsToSave({ story, pages, metadata, flags }) {
...
-      web_stories_poster: featuredMedia.isExternal
-        ? {
-            url: featuredMedia.url,
-            width: featuredMedia.width,
-            height: featuredMedia.height,
-            needsProxy: featuredMedia.needsProxy,
-          }
-        : undefined,
-    },
+    products,
```
Comment (miina) [inline packages/story-editor/src/app/story/utils/getStoryPropsToSave.js:53]: Does this influence the API, too?

**Review by miina — APPROVED** [review]
Seems to work as expected now! Checked the JS files only.

File: packages/story-editor/src/app/story/utils/getStoryPropsToSave.js (hunk 2 above)
Comment (swissspidy) [reply packages/story-editor/src/app/story/utils/getStoryPropsToSave.js:53]: No, because `getStorySaveData`, which is called with the results of this function, still returns the data in the same format (with `meta: { .... }`)

**Review by timarney — APPROVED** [review]
Tested as per instructions --- worked locally
