### PR TITLE
Animations: Copy and Paste Support

### LINKED ISSUE #5424: Animations not preserved when copying elements
## Bug Description

When duplicating an element with animation (either by copy-pasting or Cmd+d), the duplicate element has no animation.

## Steps to Reproduce

1. On a page copy an element such as shape/text that have an animation applied to them
2. Copy the element
3. Paste the element back into the editor
4. Observe that the animation on the first element is not applied to the newly created copy of it.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds support to relevant element animations with copy and paste. now when copy and pasting elements, all animations should be retained with the newly pasted element.

## Relevant Technical Choices
- Had to modify copy and paste method signatures to support animations.
- Added a wholesale addAnimations action to the reducer that allows us to append new animations to the current pages animation structure.

## To-do
**Follow Up Changes:**
Add karma tests around copy and pasting elements with animations. I don't think any copy and paste stuff has karma tests currently (at least I couldn't find any, please point me in that direction if they exist and I couldn't find them)
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/5564

## User-facing changes
Now if animations are enabled, copy and paste should retain animations.

## Testing Instructions
enable animations:
- Create an element and go through each possible animation, apply it, and copy and paste the new element to another page. see that the animation is on the newly pasted element
- Create a BG image element and go through the process above with all BG animations
- Test out copy and paste with multiple elements that have animations

disable animations:
- do a couple general copy and paste executions and see that copy and paste still behaves the same as before.

---

Fixes #5424

### CODE REVIEW

File: assets/src/edit-story/app/story/useStoryReducer/reducer.js [hunk 1]
```diff
@@ -20,6 +20,7 @@
 import * as types from './types';
 import * as reducers from './reducers';
 
+/* eslint-disable complexity */
```
Comment (littlemilkstudio) [inline assets/src/edit-story/app/story/useStoryReducer/reducer.js:23]: I think this is fine for a reducer that's just coordinating actions with types

Comment (maxyinger) [inline assets/src/edit-story/app/story/useStoryReducer/reducer.js:23]: I think this is fine for a reducer that's just coordinating actions with types

File: assets/src/edit-story/app/story/useStoryReducer/reducers/utils.js [hunk 2]
```diff
@@ -125,3 +125,36 @@ export function updateAnimations(oldAnimations, animationUpdates) {
...
+ */
+export function removeDuplicates(entries = []) {
+  // Use only last of multiple elements with same id by turning into an object and getting the values.
+  return Object.values(
+    Object.fromEntries(entries.map((entry) => [entry.id, entry]))
+  );
+}
+
+/**
+ * Takes to sets of entries and returns unique entries
```
Comment (zachhale) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/utils.js:151]: I think this description should mention that this does exclusion based off `id`

**Review by carloskelly13 — APPROVED** [review]

**Review by carloskelly13 — APPROVED** [review]
Animations now copy-paste and their attributes are retained. Elements without animations look good too.

**Comment by carloskelly13** [comment]
Also existing templates seem to work with copy paste and retain their animations too

**Review by zachhale — APPROVED** [review]
I don't fully understand the code, but it seems to work in the editor correctly and things look generally good. 🤷‍♂️

**Comment by miina** [comment]
@littlemilkstudio Should this PR also include support for element duplication (`⌘`+`D`, see the `cloneHandler`) or will this be addressed separately?

**Comment by maxyinger** [comment]
> cloneHandler

Ahh good call! Will add in this PR

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 3]
```diff
@@ -194,19 +201,31 @@ function useCanvasKeys(ref) {
...
+        ...animation,
+        id: uuidv4(),
+        targets: animation.targets
+          .map((id) => elementIdTransferMap[id])
+          .filter((v) => v),
+      }))
+      .filter((animation) => animation.targets.length > 0);
+
+    addPastedElements(clonedElements, clonedAnimations);
+  }, [addPastedElements, selectedElements, selectedElementAnimations]);
```
Comment (maxyinger) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js:228]: This file has the all the new changes since the last review. Adds duplication (command + D) support to this PR.
