### PR TITLE
Carousel: Refactor to adhere to new design

### LINKED ISSUE #5077: Carousel: scrollIntoView causes unexpected vertical scrolling
## Bug Description

Reported at #5053 and also https://github.com/google/web-stories-wp/issues/4517#issuecomment-694743971

We use `scrollIntoView` in the carousel so that the current page in the carousel is always centered. Whenever the current page changes, `scrollIntoView()` is called:

https://github.com/google/web-stories-wp/blob/c8df85e53ba824bb22e9a7ad05817eac48adee1f/assets/src/edit-story/components/canvas/carousel/index.js#L298-L311

This can cause issues on smaller screens (#4517) or when the admin menu is excessively long (#3053)

## Expected Behaviour

We should prevent vertical scrolling caused by `scrollIntoView`. Let's use [`scrollLeft`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) or something instead of `scrollIntoView`.

## Steps to Reproduce

1. Make screen smaller to trigger #4517 or install lots of plugins to trigger #5053 
1. Change the current page
1. Notice vertical scrolling

## Screenshots

Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #5692: Update page carousel to new layout
## Feature Description

Update page carousel in the following ways:

1. Make thumbnails one-size only (not scalable):
-> 36x64px with 16px spacing if workspace width <700px
-> 40x72px with 16px spacing if workspace width >=700px
-> Carousel is still a regular scrollable container

1. Add arrows to the ends of the carousel. 
-> 32px button area with regular arrow icon inside spaced 16px from the carousel itself.
-> Pressing an arrow does not change the current page, it just offsets the carousel by a full page in the chosen direction.
-> Arrow color is FG Dark Primary, unless inactive, then FG Dark Tertiary.

1. Make the page carousel container fit the center of the footer of the workspace such that there's 167px of space gap on each side of the arrows (so `maxWidth = canvasWidth - 2 * (167 + arrowWidth + arrowSpacing)` with arrows being 32px and arrow spacing 16px) but make sure it shows a whole number of pages (so that the width matches the following for some page count, `n`: `actualWidth = n * thumbnailWidth + (n - 1) * spacingWidth`, where thumbnail width varies as listed above and spacing width is always 16px).
-> On a very-wide workspace (>=1000px) the gap increases by 8px to 175px.

1. Position right-side icons (_keyboard shortcuts_ + _grid mode_) horizontally rather than vertically
-> Right-most icon (_keyboard shortcuts_) is placed 16px from right edge
-> On a very-wide workspace (>=1000px) the right gap is increased by 8px to 24px from right edge

1. Do **not** implement any of the following (will come with future design implementation):
-> New arrows
-> New icons for buttons
-> New selection outline for thumbnails

See designs in [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4560).

Current design:
Screen Shot 2020-12-15 at 21 12 30

New design for wide (>=700px) workspace:
Workspace

New design for narrow (<700px) workspace:
Group 5751

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Summary

This is a complete overhaul of the carousel components (code-wise) as well as adding a new structure for it.

I decided to update the thumbnail highlight to the new design (with a full thin border rather than just a fat top border) as the old design looked weird with the new changes.

## To-do

* [x] Refactor carousel
* [x] Change thumbnail sizing and layout
* [x] Retire old compact indicator
* [x] Change scroll arrow behavior
* [x] Change carousel menu layout
* [x] Update thumbnail highlight to new design
* [x] Make sure tests still run

## Testing Instructions

* Make sure thumbnail carousel, grid view and keyboard shortcuts still work as intended.

---

Fixes #5692
Fixes #5077

### CODE REVIEW

**Comment by miina** [comment]
@barklund Seems to work great. One question from testing:
- If there is only one Page, or generally very few pages so that the scrolling is disabled from both sides, should the arrows be shown at all?

File: assets/src/edit-story/components/keyboard/index.js [hunk 1]
```diff
@@ -0,0 +1,403 @@
+/*
+ * Copyright 2020 Google LLC
```
Comment (miina) [inline assets/src/edit-story/components/keyboard/index.js]: Isn't all this a duplicate from `design-system/components/keyboard/index.js`? Shouldn't it be used directly from there instead? Or what's the idea of having it in both places? Thoughts?

Comment (swissspidy) [reply assets/src/edit-story/components/keyboard/index.js]: Looks like a leftover file from fixing merge conflicts after my refactoring.

File: assets/src/edit-story/components/carousel/useCarouselSizing.js [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+/**
+ * External dependencies
+ */
+import { useMemo } from 'react';
+
+function useCarouselSizing({ availableSpace, numPages }) {
+  return useMemo(() => {
+    const isWideWorkspace = availableSpace >= 700;
+    const spaceForCarousel = availableSpace - 2 * 167 - 2 * 32;
```
Comment (miina) [inline assets/src/edit-story/components/carousel/useCarouselSizing.js]: Can we use constants here instead of magic numbers?

File: assets/src/edit-story/components/carousel/useCarouselScroll.js [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+ */
+import { useCallback, useState, useLayoutEffect } from 'react';
+
+/**
+ * Internal dependencies
+ */
+import { useConfig } from '../../app';
+
+function useCarouselScroll({ listElement, carouselWidth, hasOverflow }) {
+  const [scrollPercentage, setScrollPercentage] = useState(0);
```
Comment (miina) [inline assets/src/edit-story/components/carousel/useCarouselScroll.js]: Nit: this value doesn't seem to be in percentage actually. Not sure what would be a better name either so unless you have a more accurate one, can probably stay as is.

File: assets/src/edit-story/components/carousel/gridview/index.js [hunk 4]
```diff
@@ -321,7 +321,7 @@ function GridView() {
                     }
                     tabIndex={isCurrentPage && isInteractive ? 0 : -1}
                     isActive={isCurrentPage && isInteractive}
-                    index={index}
+                    page={page}
                     width={width}
                     height={height}
                     dragIndicatorOffset={GRID_GAP / 2}
```
Comment (miina) [inline assets/src/edit-story/components/carousel/gridview/index.js]: Is this used anywhere btw?

File: assets/src/edit-story/components/carousel/carouselProvider.js [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+      pageThumbMargin,
+      availableSpace,
+      carouselWidth,
+      hasOverflow,
+      pages,
+      pageIds,
+      numPages,
+      currentPageId,
+      canScrollBack,
+      canScrollForward,
```
Comment (miina) [inline assets/src/edit-story/components/carousel/carouselProvider.js:107]: Left a separate comment as well but if both `canScroll*`s are `false`, should the buttons be displayed at all?

File: assets/src/edit-story/components/carousel/carouselProvider.js [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+    const currentPageRef = pageRefs.current[currentPageId];
+
+    if (!currentPageRef || !currentPageRef.scrollIntoView) {
+      return;
+    }
+
+    currentPageRef.scrollIntoView({
+      inline: 'center',
+      behavior: 'smooth',
+    });
```
Comment (swissspidy) [inline assets/src/edit-story/components/carousel/carouselProvider.js]: While we're at it, might be a good time to address #5077 by using `scrollBy` with an offset instead of `scrollIntoView`.

Is that easily possible?

File: assets/src/edit-story/components/carousel/useCarouselSizing.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/useCarouselSizing.js]: Haha, yes, I was going to do that. They're constants elsewhere, will move them to a central location.

File: assets/src/edit-story/components/keyboard/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/keyboard/index.js]: Ah, I thought I fixed all the merge problems - will delete this too.

File: assets/src/edit-story/components/carousel/useCarouselScroll.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/useCarouselScroll.js]: `scrollRatio`?

File: assets/src/edit-story/components/carousel/gridview/index.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/gridview/index.js]: No idea, will check.

File: assets/src/edit-story/components/carousel/carouselProvider.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/carouselProvider.js]: Hm, it should be. I should be able to calculate all the numbers quite easily.

File: assets/src/edit-story/components/carousel/carouselProvider.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/carouselProvider.js:107]: Hm, the design isn't clear on that. I'll ask, thanks!

File: assets/src/edit-story/components/carousel/carouselProvider.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/carouselProvider.js]: Done in 72843dd80 - and it looks freaking nice, if I can say so myself. I actually [ended up using `scrollTo` rather than `scrollBy`](https://github.com/google/web-stories-wp/pull/5941/files#diff-60efa86d6d8735e06b04393cb877f4fa0242b75724db8c071b4d135da09b2692R100-R153) though 🤷

File: assets/src/edit-story/components/carousel/carouselProvider.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/carouselProvider.js:107]: Forwarded to Sam

File: assets/src/edit-story/components/carousel/gridview/index.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/gridview/index.js]: Was unused - removed in 57ef174a1.

File: assets/src/edit-story/components/carousel/useCarouselScroll.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/useCarouselScroll.js]: Fixed in b1d4e1472.

File: assets/src/edit-story/components/carousel/useCarouselSizing.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/useCarouselSizing.js]: Fixed in 26ccacdc4.

File: assets/src/edit-story/components/keyboard/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/keyboard/index.js]: Removed in eb983d560.

**Comment by miina** [comment]
@barklund One more finding:
When deleting a page via keyboard, the focus "gets lost" and is not in the carousel anymore.
Steps:
- Add a bunch of pages
- Use arrows to select one of the pages and hit "Delete"
- Try to delete another page via "Delete" -- not happening, the focus is not in the carousel anymore.

Thoughts?

**Comment by barklund** [comment]
> @barklund One more finding:
> When deleting a page via keyboard, the focus "gets lost" and is not in the carousel anymore.

Good find! Fixed in d063d7423.

File: assets/src/edit-story/components/carousel/carouselProvider.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/carousel/carouselProvider.js:107]: We'll hide completely if no overflow. Fixed in d05008525.

**Review by miina — APPROVED** [review]

**Comment by swissspidy** [comment]
This is a lot of new code, are we're confident it works as intended without any new tests? (Where's the code coverage report when you need it?)

-----

Aside:

> `assets/js/stories-dashboard.js`	466 kB	+3.78 kB (+1%)

Sounds like I'll need to do some digging into bundle generation again 🤔
