### PR TITLE
Video Optimization: Improve snackbar message upon failure

### LINKED ISSUE #8315: Failed thumbnail video optimization snackbar message
## Bug Description

If poster fails to generate and then the video optimization fails, the snackbar message looks broken. 

## Screenshots

Screenshot 2021-07-13 at 12 44 13

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

If poster fails to generate and then the video optimization fails, the snackbar message looks broken.

## User-facing changes

Before

Screenshot 2021-07-13 at 12 44 13

After

Screenshot 2021-07-14 at 17 01 47

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8315

### CODE REVIEW

File: assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js [hunk 1]
```diff
@@ -157,7 +157,7 @@ function useMediaUploadQueue() {
     async ({ newResource, posterFileName, newPosterFile, resource, id }) => {
       try {
         const { poster, posterId } = await uploadVideoPoster(
-          newResource.id,
+          newResource?.id,
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js]: What's the rationale for this?

If `newResource` does not exist, then we have a bigger problem. It means `uploadVideoPoster()` could be called with `null`, which would not work and probably cause some HTTP errors.

So if `newResource.id` does not exist we should not be calling `uploadVideoPoster`

Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useMediaUploadQueue/index.js]:
```suggestion
          newResource.id,
```

**Review by swissspidy — APPROVED** [review]
