### PR TITLE
Use 3:4 ratio for displaying poster image

### LINKED ISSUE #8323: Document Panel: Story poster displayed with wrong aspect ratio
## Bug Description

Story portrait posters are at least 640x853 and maintain a 4:3 aspect ratio.

Yet, in the document panel we display the story poster image in 9:16 aspect ratio, which means the image is stretched.

## Expected Behaviour

1. The story poster image is displayed with 4:3 aspect ratio
2. The `` has `width` and `height` attributes

## Steps to Reproduce

1. Add story poster image
2. Inspect thumbnail in dev tools
3. See image is stretched

## Screenshots

Screenshot 2021-07-13 at 19 17 40
Screenshot 2021-07-13 at 19 17 46

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

See #8323.

### QA

This PR can be tested by following these steps:

- Add story poster in the Document panel
- See the source and verify the poster image is displayed in 4:3 ratio.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8323

### CODE REVIEW

File: packages/design-system/src/components/mediaInput/index.js [hunk 1]
```diff
@@ -164,6 +164,7 @@ export const MediaInput = forwardRef(function Media(
     onMenuOption,
     openMediaPicker,
     menuProps = {},
+    resource = {},
```
Comment (swissspidy) [inline packages/design-system/src/components/mediaInput/index.js]: Perhaps call it `imgProps`?

**Review by barklund — APPROVED** [review]

File: packages/design-system/src/components/mediaInput/index.js [hunk 2]
```diff
@@ -184,7 +185,13 @@ export const MediaInput = forwardRef(function Media(
     <StyledMedia className={className} {...rest}>
       <ImageWrapper variant={variant}>
         {value ? (
-          <Img src={value} alt={alt} crossOrigin="anonymous" />
+          <Img
+            src={value}
+            alt={alt}
```
Comment (spacedmonkey) [inline packages/design-system/src/components/mediaInput/index.js:190]: Maybe we could use the alt in resource here? 
```
alt={imgProps?.alt || alt}
```
