### PR TITLE
Media: Improve "No media found" message

### LINKED ISSUE #3899: Make "No media found" match the mocks (style and wording)
## Bug Description

There is a big padding above the "No media found" empty result search screen.

## Screenshots

download (1)

### PR DESCRIPTION
**Pull request by ezxyz**
## Summary

Fix "no media found" error message to fit mocks. 

For MediaSubheading "visibility:hidden" only "hides" the content, but the actual padding/height of the content remains. Hence, changing that to "display:none" fixes the alignment issue for "no media found" message.

## User-facing changes

Screen Shot 2020-08-20 at 3 29 14 PM

---

Fixes #3899

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/common/styles.js [hunk 1]
```diff
@@ -71,8 +71,14 @@ export const MediaGalleryLoadingPill = styled.div`
 
 export const MediaGalleryMessage = styled.div`
   color: ${({ theme }) => theme.colors.fg.white};
-  font-size: 16px;
   padding: 1em;
+  font-family: ${({ theme }) => theme.fonts.mediaError.family};
```
Comment (cvolzke4) [inline assets/src/edit-story/components/library/panes/media/common/styles.js:75]: Have you checked to see what this looks like for locally uploaded media?

**Review by cvolzke4 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/styles.js (hunk 1 above)
Comment (ezxyz) [reply assets/src/edit-story/components/library/panes/media/common/styles.js:75]: Screen Shot 2020-08-21 at 10 28 37 AM

Here's what it looked like for locally uploaded media.

Comment (winterDroid) [reply assets/src/edit-story/components/library/panes/media/common/styles.js:75]: The top padding there like somewhat tiny compared to the media3p pane.
