### PR TITLE
Semantic Headings: Fix text with regular font weight displayed bold

### LINKED ISSUE #11063: Semantic Headings: Text with regular font weight displayed bold
## Bug Description

Looks like because we display elements as h1, h2, etc. the browser's default styles for headings can cause text elements to be displayed bold

## Expected Behaviour

If not explicitly made bold, the text shouldn't be bold.

To fix this, we should add `h1, h2, h3 { font-weight: normal; }` to the default CSS in `packages/output/src/utils/styles.js`.

Basically a CSS reset

## Steps to Reproduce

1. Insert Paragraph text preset
2. Make font size quite large
3. Preview story
4. Notice the text is bold in the preview but not in the editor

## Screenshots

Screenshot 2022-03-23 at 22 43 00
Screenshot 2022-03-23 at 22 43 10

## Additional Context

- Plugin Version: 1.18.0
- WordPress Version:  5.9
- Operating System: macOS Monterey
- Browser: Chrome

### PR DESCRIPTION
**Pull request by timarney**
## Context

If not explicitly made bold, the text shouldn't be bold.

More details: https://github.com/GoogleForCreators/web-stories-wp/issues/11063#issue-1178705220

## Summary

Updates CSS to ensure heading tags (text) reset to "normal" font weight 

## Testing Instructions

This PR can be tested by following these steps:

From the `main` branch
1) Insert Paragraph text preset
2) Make font size quite large
3) Preview story
4) Notice the text is bold in the preview but not in the editor

From the `fix/11033` branch
1) Insert Paragraph text preset
2) Make font size quite large
3) Preview story
4) Notice the text is **not** bold in the preview but not in the editor

Screen Shot 2022-03-24 at 7 19 18 AM

- [ ] This is a non-user-facing change and requires no QA

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11063

### CODE REVIEW

File: packages/output/src/utils/styles.js [hunk 1]
```diff
@@ -49,6 +49,8 @@ function CustomStyles() {
       dangerouslySetInnerHTML={{
         __html:
           `
+              h1, h2, h3 { font-weight: normal; }
```
Comment (timarney) [inline packages/output/src/utils/styles.js:52]: @swissspidy 

1) is this the correct spot to add these styles
2) should I see these classes applied if I `npm run build` or is some other step required 

Trying to gain some understanding as to how this file works for future reference

Comment (swissspidy) [reply packages/output/src/utils/styles.js:52]: Yes this is the correct spot.

These styles are used for generating the AMP output that you see when previewing the story on the frontend.

To test that it works correctly, follow the reproduction steps from the ticket itself.

**Review by swissspidy — APPROVED** [review]
Works like a charm
