### PR TITLE
Style Presets: Fix edit mode for Text Style Presets

### LINKED ISSUE #4481: Unable to delete saved styles
## Bug Description

Under some circumstances it's impossible to edit/delete saved styles.

## Expected Behaviour

I should be able to delete saved styles at all times.

## Steps to Reproduce

**Note:** the issue only appears when there are **no saved _colors_**.

1. Ensure there are no saved colors
1. Save style
1. Try to edit saved styles
1. Nothing happens

## Screenshots

image (8)

## Additional Context

- Plugin Version: 1.0.0-rc.1
- Operating System: macOS
- Browser: Browser

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fix edit mode.

## To-do

- [x] Karma tests for colors edit mode, too.

## Testing Instructions

---

Fixes #4481

### CODE REVIEW

File: assets/src/edit-story/components/panels/preset/presetPanel.js [hunk 1]
```diff
@@ -90,7 +90,7 @@ function PresetPanel({
     [colors, isColor, textStyles, updateStory]
   );
 
-  const hasPresets = colors.length > 0;
+  const hasPresets = colors.length > 0 || textStyles.length > 0;
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/preset/presetPanel.js]: Should we do this instead?

```suggestion
  const hasPresets = 'color' === presetType ? colors.length > 0 : textStyles.length > 0;
```

Otherwise the effect below to exit edit mode when there are no presets left doesn't work.

Could be tested easily I think.

Comment (miina) [reply assets/src/edit-story/components/panels/preset/presetPanel.js]: Yep, good point, `presets` as the set of relevant presets is used below as well actually for header, was thinking of perhaps doing something like
`const presets = isColor ? colors : textStyles` as is used below and then we could use just `presets.length`.

File: assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+
+  const addText = async () => {
+    const insertElement = await fixture.renderHook(() => useInsertElement());
+    await fixture.act(() =>
+      insertElement('text', {
+        font: TEXT_ELEMENT_DEFAULT_FONT,
+        content: 'Hello, presets!',
+      })
+    );
+  };
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js]: Should we just use `fixture.editor.library.textAdd` here? So the text style actually matches what the users will experience?

File: assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+    fixture.restore();
+  });
+
+  describe('CUJ: Creator can Apply or Save a Color from/to Their Preset Library: Display Panel', () => {
+    it('should display color presets panel for a text element', async () => {
+      await addText();
+      const addButton = fixture.screen.getByRole('button', {
+        name: ADD_BUTTON,
+      });
+      expect(addButton).toBeTruthy();
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js]: I would really love for these - and all other node access - to go through `fixture.editor`. We don't have a container for the `stylePreset` panel, but it should be easy to add.

File: assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+  });
+
+  describe('CUJ: Creator can Apply or Save a Color from/to Their Preset Library: Manage Color Presets', () => {
+    it('should allow deleting a color preset', async () => {
+      // Add text element and a color preset.
+      await addText();
+      const addButton = fixture.screen.getByRole('button', {
+        name: ADD_BUTTON,
+      });
+      await addButton.click();
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js]: If we use `await fixture.events.click(node)`, karma will also make sure that the target is actually clickable (on-screen, has a size, etc). That will make the tests more "real-world".

Also, the regular `node.click()` doesn't return a promise, so no `await` necessary anyway.

**Review by barklund — COMMENTED** [review]
Some comments on tests, otherwise good catch on the bug!

File: assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js]: Yep, in this file makes sense, will change. In the text styles tests the `addText` is used for more things, will keep it there.

**Comment by miina** [comment]
> Some comments on tests, otherwise good catch on the bug!

Main props go to @swissspidy for finding the way how to reproduce this bug!

File: assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/components/panels/preset/karma/colorPresets.karma.js]: Changed, PTAL: 468501b

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js [hunk 5]
```diff
@@ -112,15 +106,13 @@ describe('Panel: Style Presets', () => {
...
-        name: ADD_BUTTON,
-      });
-      await addButton.click();
-      const applyPresetButton = fixture.screen.queryByRole('button', {
-        name: APPLY_BUTTON,
-      });
+      await fixture.events.click(
+        fixture.editor.inspector.designPanel.textStylePreset.add
+      );
+      const applyButton = await fixture.editor.inspector.designPanel
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: What are we `await`'ing for? There are a few of these, where you're awaiting something non-promised.

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js [hunk 6]
```diff
@@ -135,46 +127,99 @@ describe('Panel: Style Presets', () => {
...
+      expect(deletePresetButton).toBeTruthy();
       await fixture.events.click(deletePresetButton);
-      await waitForElementToBeRemoved(deletePresetButton);
+
+      // Verify the edit mode was exited (due to removing all elements).
+      expect(
+        fixture.screen.queryByRole('button', {
+          name: 'Exit edit mode',
+        })
+      ).toBeFalsy();
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: I think you can do this with `.toThrow()` instead like:

```js
      expect(
        () => fixture.editor.inspector.designPanel.textStylePreset.exit
      ).toThrow();
```

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js [hunk 7]
```diff
@@ -135,46 +127,99 @@ describe('Panel: Style Presets', () => {
...
+      );
+
+      // Verify being in edit mode.
+      const exitEditButton = fixture.screen.getByRole('button', {
+        name: 'Exit edit mode',
+      });
+      expect(exitEditButton).toBeTruthy();
       const deletePresetButton = fixture.screen.getByRole('button', {
         name: 'Delete style preset',
       });
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: These should be updated too.

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js [hunk 8]
```diff
@@ -34,7 +29,7 @@ describe('Panel: Style Presets', () => {
   let frame;
 
   const ADD_BUTTON = 'Add style preset';
-  const APPLY_BUTTON = 'Apply style preset';
+  const EDIT_BUTTON = 'Edit style presets';
 
   const addText = async (extraProps = null) => {
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: This one should use the `library.textAdd` button as well (though I know it doesn't work with the position props - but anything testing that something is placed at a certain position like this is not doing things in the same way a user does anyway).

Comment (miina) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: Ah, okay, now I understand -- you mean that we should get to the point via user actions where the Text element has different props by actually changing these in the design panel instead of adding it directly?

There are quite a few tests that do that -- create the preconditions for testing a specific part instead of getting there via actions -- should we create an issue for rewriting those, too? Thoughts?

Comment (barklund) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: Yeah, let's do that for later, it's not a priority now. But a test using some API not available to "real" users is not really testing anything, as it's kind of cheating. But I'm good with postponing that a bit.

Comment (miina) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js]: (I did change it for this PR, btw)

**Review by barklund — APPROVED** [review]
LGTM

**Review by swissspidy — APPROVED** [review]
