### PR TITLE
Video: Update right click menu

### LINKED ISSUE #9184: Video Trimming: Add video trim to right-click menu
## Bug Description

Add video trim to right-click menu

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #9185: Video Trimming: Update context menu copy to include video
## Bug Description

Since we will be adding video trimming to the right click context menu (see https://github.com/google/web-stories-wp/issues/9184), we will need to update the verbiage of that menu to be inclusive of video assets (ie: change Image to <something else>) 

## Expected Behaviour

Right click context menu copy is updated to include video assets as well as image, as it currently only references "image(s)"

## Screenshots

image9

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

Updated right-click menu option wording to include "video" rather than "image" for video elements and also added "Trim video" as a new option.

## User-facing changes

| | Background element | Non-background element |
|-|-|-|
| Image | right_bg_image | right_image |
| Video | right_bg_video | right_video |

## Testing Instructions

This PR can be tested by following these steps:

1. Test right-click menu of both image and video while both being background and non-background elements.
2.  Observe that menu option wording includes "image" when image, and "video" when video
3. Observe that video, in either case, has "trim video", which enters trim mode

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9184
Fixes #9185

### CODE REVIEW

File: packages/story-editor/src/app/rightClickMenu/provider.js [hunk 1]
```diff
@@ -781,20 +789,36 @@ function RightClickMenuProvider({ children }) {
...
         ...menuItemProps,
       },
       {
-        label: RIGHT_CLICK_MENU_LABELS.SCALE_AND_CROP_BACKGROUND,
+        label: scaleLabel,
         onClick: handleOpenScaleAndCrop,
         disabled: disableBackgroundMediaActions,
         ...menuItemProps,
       },
+      ...(isVideo && hasTrimMode
```
Comment (miina) [inline packages/story-editor/src/app/rightClickMenu/provider.js:814]: `hasTrimMode` is now `true` while `isTrimming` or `isMuting` etc. as well.
It would probably need `disabled: !canTranscodeResource(resource);` here to disable it for the time of any video processing.

File: packages/story-editor/src/app/rightClickMenu/provider.js [hunk 2]
```diff
@@ -863,42 +904,52 @@ function RightClickMenuProvider({ children }) {
         ...menuItemProps,
       },
       {
-        label: RIGHT_CLICK_MENU_LABELS.SCALE_AND_CROP_IMAGE,
+        label: scaleLabel,
         onClick: handleOpenScaleAndCrop,
         ...menuItemProps,
       },
+      ...(isVideo && hasTrimMode
```
Comment (miina) [inline packages/story-editor/src/app/rightClickMenu/provider.js:912]: Same here with `hasTrimMode` and `disabled`

**Review by miina — APPROVED** [review]
Had just one comment about disabling the menu items.

Otherwise LGTM.

(Some tests are failing now as well)

**Review by maxyinger — APPROVED** [review]
Looks good to me. Looks like fixing the failing unit tests shouldn't be bad either. Nice!

File: packages/story-editor/src/app/rightClickMenu/test/useRightClickMenu.js [hunk 3]
```diff
@@ -256,14 +274,103 @@ describe('useRightClickMenu', () => {
...
+        RIGHT_CLICK_MENU_LABELS.SCALE_AND_CROP_BACKGROUND_VIDEO,
+        RIGHT_CLICK_MENU_LABELS.CLEAR_STYLE,
+        RIGHT_CLICK_MENU_LABELS.ADD_NEW_PAGE_AFTER,
+        RIGHT_CLICK_MENU_LABELS.ADD_NEW_PAGE_BEFORE,
+        RIGHT_CLICK_MENU_LABELS.DUPLICATE_PAGE,
+        RIGHT_CLICK_MENU_LABELS.DELETE_PAGE,
+      ]);
+    });
+
+    describe('if video transcoding is possible', () => {
```
Comment (samwhale) [inline packages/story-editor/src/app/rightClickMenu/test/useRightClickMenu.js:308]: May be overkill but if transcoding is not possible we could check if the `trim video` button is missing?

File: packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js [hunk 4]
```diff
@@ -412,6 +424,43 @@ describe('Right Click Menu integration', () => {
...
+      await rightClickOnTarget(
+        fixture.editor.canvas.framesLayer.frame(video.id).node
+      );
+
+      // background: click 'scale and crop video' button
+      await fixture.events.click(scaleAndCropBackgroundVideo());
+
+      // Verify element is being edited
+      expect(fixture.screen.getByTestId('edit-panel-slider')).toBeDefined();
+    });
```
Comment (samwhale) [inline packages/story-editor/src/components/canvas/karma/rightClickMenu.karma.js:463]: 🤔 Maybe this wouldn't need to be duplicated if the karma fixture was searching for either 
- `/^Scale & Crop Background (Video|Image)/i`
- `/^Scale & Crop (Video|Image)/i`,

But if we want to keep these separate that's fine too

**Review by samwhale — APPROVED** [review]
Love it. Thinking we should add a karma test to see if the trim UI opens when clicking the trim video button

Thanks for updating all of those strings!
