### PR TITLE
Fix Karma tests

### LINKED ISSUE #12621: Fix main branch Karma tests
## Bug Description

The current main branch Karma tests are not in a good condition, in this ticket I will try to fix them all.
I started fixing them in https://github.com/GoogleForCreators/web-stories-wp/pull/12557 but now I will move those changes and add more fixes here so all other PRs can merge in the latest fixed main.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by merapi**
## Summary

This also includes a general fix for `html-to-image` - seems like last time I fixed Safari images but broke other stuff.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12621

### CODE REVIEW

File: packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js [hunk 1]
```diff
@@ -119,7 +119,7 @@ function PageAttachment({ ctaText, theme }) {
   }));
 
   return (
-    <Wrapper role="presentation">
+    <Wrapper role="presentation" tabIndex={-1}>
```
Comment (merapi) [inline packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js:122]: Notice the difference when tabbing - the first part is without a product and works as expected, then the issue occurs when there is a product on the Canvas.
`Shop Now` is causing the issues, I think it doesn't need to be focusable at all and this change fixes the issue but PTAL @barklund.

https://user-images.githubusercontent.com/21036224/199951874-34bca72b-7684-4a7c-a729-17fa272a060e.mp4

Comment (merapi) [reply packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js:122]: Looks like there is a bigger issue with focusing via tab.
The first time you load the editor and cycle all elements via tab it will focus on the Canvas container - all good.
When you add/select an element and do that cycle again, it will not focus on the Canvas container but on the first and next elements instead (and you will be stuck there, not like in the first cycle).
So at 00:26 it should focus on the container, right?

https://user-images.githubusercontent.com/21036224/199968876-9f577ed3-321e-45d5-836b-7b2d676c48ee.mp4

Comment (barklund) [reply packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js:122]: Hmm, this sounds mysterious and definitely like a bug. This was originally implemented by Pea Pod, so I don't know all the details of the canvas tabbing container, but I'll look into it.

Comment (barklund) [reply packages/story-editor/src/components/canvas/shoppingPageAttachment/index.js:122]: It works if you get to the canvas container going backwards (so start focusing the story title input, then tab backwards, and you're good. Tab past the canvas container, and start tabbing forward, and it breaks!)

**Comment by merapi** [comment]
I disabled the failing test, follow-up here: https://github.com/GoogleForCreators/web-stories-wp/issues/12650
One Karma chunk is still failing, but only because of the Percy "can only finalize pending builds" exit code. I did a follow-up here: https://github.com/GoogleForCreators/web-stories-wp/issues/12651

**Review by swissspidy — APPROVED** [review]
