### PR TITLE
Fix aria attributes for the category expand button

### LINKED ISSUE #3398: 3P Media Categories Accessibility
The Media3p categories list as it exists today is not fully accessible by keyboard.

Thankfully @jhtin added some `aria-*` attributes, which is great. However, there are still issues.

* The pills themselves are just `<span>` elemens, and need to be proper `button` elements so they can receive focus.
* Since the categories list is a **tablist**, navigation within the list should happen via arrow keys, and pressing <kbd>tab</kbd> would navigate out of the list to the next focusable element (the arrow button in this case)  
  See the tabs at the top of the library panel for inspiration.
* The wrapping element (`CategorySection`) has an `aria-expanded` attribute, but is not a `section`. However, since it's actually controlled by the arrow button, the `aria-expanded` attribute should be on the button
* The arrow button needs an `aria-controls` attribute that contains the ID of `CategorySection`

**How can this be tested?**

We have `jest-axe` in the repo, so for Jest tests we could do something like this:

```js
import { axe } from 'jest-axe';

it('should render categories without accessibility violations', async () => {
  const { container } = renderWithTheme(
    <Media3pCategories
      categories={categories}
      selectedCategoryName={undefined}
      selectCategory={selectCategoryMock}
      deselectCategory={deselectCategoryMock}
    />
  );

  const results = await axe(container);
  expect(results).toHaveNoViolations();
});
```

Note: we might need to [tweak the axe configuration](https://github.com/nickcolley/jest-axe#axe-configuration).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by cvolzke4**
## Summary

Fix aria attributes for the category expand button.

---

Fixes #3398

### CODE REVIEW

**Review by joannag6 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js [hunk 1]
```diff
@@ -53,7 +58,9 @@ const CategoryPillInnerContainer = styled.div`
 // Flips the button upside down when expanded;
 // Important: the visibily is 'inherit' when props.visible because otherwise
 // it gets shown even when the provider is not the selectedProvider!
-const ExpandButton = styled(ArrowDown)`
+const ExpandButton = styled(ArrowDown).attrs({
+  'aria-label': __('Expand Categories', 'web-stories'),
```
Comment (swissspidy) [inline assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js]: If you'd add the attribute below you could do:

```js
aria-label={isExpanded ? __('Collapse Categories', 'web-stories') :  __('Expand Categories', 'web-stories')}
```

Comment (cvolzke4) [reply assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js]: Done.
