### PR TITLE
Fix user switching in E2E tests and ensure general robustness

### LINKED ISSUE #7790: E2E Tests: Login as different user not working
## Bug Description
Contributor e2e test failing as failed to login as contributor and test runs as admin. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

As we've discovered, the non-admin e2e tests were not actually running as expected.

Besides the users not actually having been created initially, there was also an issue with not the right user being logged in and not detecting that in the tests.

## Summary

I went down the rabbit hole of debugging these tests for the better part of my day, trying to strengthen them piece by piece.

The main area I found to be fragile is how the `@wordpress/e2e-test-utils` utils like `visitAdminPage` tried to log in as the current user. They were not really made for how we want to switch users constantly between tests.

## Relevant Technical Choices

On top of #7803, this implements the following changes:

**Do not lock stories if experiment is disabled**

This adds a check in `\Google\Web_Stories\Admin\Editor::setup_lock()` to see whether the experiment is enabled. Without this, one could edit a story, and on "All Stories" it would have been shown as locked, but the locked modal was not shown in the editor.

The whole post locking should only work if the experiment is enabled.

**`publishStory` util**

This makes some repeated code a bit more DRY by moving the statements to publish a story and dismissing dialogs into a shared util.

**`withPlugin` util**

Just a small util that activates a plugin before tests & deactivates it afterwards.

**`withUser` util**

Just a small util that logs in as a user before tests and switches back to admin afterwards.

This is done with `withUser('admin', 'password')` in `bootstrap.js`, but also at the top of every test for extra safety.

(Doing `withUser('admin', 'password')` when already logged in as admin is a no-op)

**Consolidates Site Kit e2e tests**

Just to keep this a bit more dry and have them in one place.

**Improve cleanup in `publisherLogo.js`**

Moving the file deletion to `afterEach` ensures it happens even if a test fails.

**Improve `trashAllPosts`**

Copies the util from Gutenberg, but removes an XPath query to reduce flakiness.

**Improve `visitAdminPage`**

Copies the util from Gutenberg, but removes any user login logic from it.

**New `setCurrentUser` util**

This is used by `withUser` and other utils to switch the current user in a robust way.

**Improve `loginUser`**

Fixes typing into the login form input fields to prevent errors and making login more robust.

Puppeteer appears to sometimes have issues with typing,  where the first 1-2 characters are simply not typed. This will of course make the login fail.

Hence not using `page.type()` anymore.  Should be OK since there are no event listeners on the login form.

See https://github.com/puppeteer/puppeteer/issues/1648

## To-do

- Maybe implement `activatePlugin` and `deactivatePlugin` ourselves as well, because these Gutenberg utils use `switchUserToAdmin`/`switchUserToTest`, which might break with our setup.

## User-facing changes

None

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7790

### CODE REVIEW

File: includes/Admin/Editor.php [hunk 1]
```diff
@@ -353,9 +353,14 @@ public function get_editor_settings() {
 	 * @return void
 	 */
 	protected function setup_lock( $story_id ) {
+		if ( ! $this->experiments->is_experiment_enabled( 'enablePostLocking' ) ) {
+			return;
+		}
```
Comment (spacedmonkey) [inline includes/Admin/Editor.php:358]: What is this change?

File: packages/e2e-test-utils/src/loginUser.js [hunk 2]
```diff
@@ -0,0 +1,55 @@
+/*
```
Comment (spacedmonkey) [inline packages/e2e-test-utils/src/loginUser.js:1]: Should we contribute this back to gutenberg / WordPress?

File: packages/e2e-test-utils/src/visitAdminPage.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+  await page.goto(createURL(join('wp-admin', adminPath), query));
+
+  // Handle upgrade required screen
+  if (isCurrentURL('wp-admin/upgrade.php')) {
+    // Click update
+    await page.click('.button.button-large.button-primary');
+    // Click continue
+    await page.click('.button.button-large');
+  }
+
```
Comment (spacedmonkey) [inline packages/e2e-test-utils/src/visitAdminPage.js:47]: Why is this missing ?
https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/e2e-test-utils/src/visit-admin-page.js#L31-L34

File: packages/e2e-tests/src/specs/wordpress/tinymce.js [hunk 4]
```diff
@@ -14,34 +14,28 @@
...
-  });
+  withUser('admin', 'password');
+  withPlugin('classic-editor');
 
   it('should allow inserting shortcode via modal', async () => {
     await visitAdminPage('post-new.php');
 
     // Ensure we're in the visual editor.
     await expect(page).toClick('#content-tmce');
+    await expect(page).toMatchElement('.mce-tinymce.mce-container', {
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/wordpress/tinymce.js:31]: Neat!

File: includes/Admin/Editor.php (hunk 1 above)
Comment (swissspidy) [reply includes/Admin/Editor.php:358]: This prevents marking a story as locked if the experiment is not enabled.

Without this, one could edit a story, and on "All Stories" it would have been shown as locked, but the locked modal was not shown in the editor.

The whole post locking should only work if the experiment is enabled.

File: packages/e2e-test-utils/src/visitAdminPage.js (hunk 3 above)
Comment (swissspidy) [reply packages/e2e-test-utils/src/visitAdminPage.js:47]: User login/switching is now solely done in `user.js` (`setCurrentUser`) / `withUser.js` and this side effect in `visitAdminPage` has been removed.

It now works under the prerequisite that the user has been already logged in when using `visitAdminPage`

File: packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js [hunk 5]
```diff
@@ -22,9 +23,12 @@ import {
   insertStoryTitle,
   uploadMedia,
   deleteMedia,
+  withUser,
 } from '@web-stories-wp/e2e-test-utils';
 
 describe('Inserting WebM Video', () => {
+  withUser('admin', 'password');
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js]: Why do we need these anywhere now?

File: packages/e2e-tests/src/specs/wordpress/tinymce.js (hunk 4 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/wordpress/tinymce.js:31]: Added this to reduce flakiness in the test. It sometimes failed because `.mce-web-stories button` was missing, which can happen when the visual editor hasn't fully loaded yet.

File: packages/e2e-tests/src/specs/editor/authorUser.js [hunk 6]
```diff
@@ -75,9 +49,6 @@ describe('Author User', () => {
   //eslint-disable-next-line jest/no-disabled-tests
   it.skip('should be able to publish a story without markup being stripped', async () => {
     await createNewStory();
-    await expect(page).toMatchElement('.display-name', {
-      text: 'author',
-    });
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/editor/authorUser.js]: await expect(page).toMatch('Howdy, author');

File: packages/e2e-tests/src/specs/editor/authorUser.js [hunk 7]
```diff
@@ -99,9 +70,6 @@ describe('Author User', () => {
   //eslint-disable-next-line jest/no-disabled-tests
   it.skip('should be able to publish and preview a story without markup being stripped', async () => {
     await createNewStory();
-    await expect(page).toMatchElement('.display-name', {
-      text: 'author',
-    });
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/editor/authorUser.js]: await expect(page).toMatch('Howdy, author');

File: packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js (hunk 5 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js]: Theoretically they shouldn't be needed, as `bootstrap.js` already does this. Added to every test for extra safety though.

I can try to see whether it can be safely removed again though. Would make the tests a bit cleaner 👍

File: packages/e2e-tests/src/specs/editor/authorUser.js (hunk 6 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/editor/authorUser.js]: IIRC this didn't work in your testing, but happy to try again. Definitely a cleaner assertion 👍

File: packages/e2e-tests/src/config/bootstrap.js [hunk 8]
```diff
@@ -118,7 +118,7 @@ if ('true' === process.env.CI) {
 }
 
 // Set default timeout for individual expect-puppeteer assertions. (Default: 500)
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/config/bootstrap.js:120]:
```suggestion
// Set default timeout for individual expect-puppeteer assertions. (Default: 1000)
```

File: packages/e2e-tests/src/config/bootstrap.js [hunk 9]
```diff
@@ -118,7 +118,7 @@ if ('true' === process.env.CI) {
...
-setDefaultOptions({ timeout: EXPECT_PUPPETEER_TIMEOUT || 500 });
+setDefaultOptions({ timeout: EXPECT_PUPPETEER_TIMEOUT || 1000 });
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/config/bootstrap.js:121]: This is a big change. I like it, but can explain the reasoning behind it.

File: packages/e2e-tests/src/config/bootstrap.js (hunk 8 above)
Comment (swissspidy) [reply packages/e2e-tests/src/config/bootstrap.js:120]: The default in `expect-puppeteer` is `500`, so this is a reference to that.

**Comment by spacedmonkey** [comment]
Seems like we are following a `with*` pattern. Should we also add `withRTL`. 

> Maybe implement activatePlugin and deactivatePlugin ourselves as well, because these Gutenberg utils use switchUserToAdmin/switchUserToTest, which might break with our setup. 

I agree, let's do this.

**Comment by swissspidy** [comment]
> Seems like we are following a `with*` pattern. Should we also add `withRTL`.

Good idea 👍

**Comment by spacedmonkey** [comment]
I also wonder. We are now only using `@wordpress/e2e-test-utils` in 4 places in the e2e tests. The utils that are used are 

- activatePlugin
- deactivatePlugin
- getEditedPostContent
- visitAdminPage
- createNewPost
- setPostContent

In postLocking.js
```
/**
 * WordPress dependencies
 */
import {
  activatePlugin,
  deactivatePlugin,
  visitAdminPage,
} from '@wordpress/e2e-test-utils';
```

This should be changed to use our new `visitAdminPage`.

Wondering, as we are only using a couple of utils for WordPress, we just expose those via `@web-stories-wp/e2e-test-utils` and remove then package from e2e package.json

**Comment by spacedmonkey** [comment]
I think we will need to implement our own version of `createNewPost` as this use gutenberg / WordPress version uses `visitAdminPage`.

**Comment by spacedmonkey** [comment]
@swissspidy Should we merge this into my PR and I can look at the rest of the tweaks?

File: packages/e2e-tests/src/config/bootstrap.js (hunk 9 above)
Comment (swissspidy) [reply packages/e2e-tests/src/config/bootstrap.js:121]: In my testing this drastically reduced flakiness when running the tests, even locally.

A bump to a 1s timeout seems justifiable.

File: packages/e2e-test-utils/src/withRTL.js [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+ * Internal dependencies
+ */
+import activateRTL from './activateRTL';
+import deactivateRTL from './deactivateRTL';
+
+/**
+ * Establishes test lifecycle to enable RTL mode
+ * for the duration of the test.
+ */
+export default function withPlugin() {
```
Comment (spacedmonkey) [inline packages/e2e-test-utils/src/withRTL.js]: withRTL

**Comment by swissspidy** [comment]
> @swissspidy Should we merge this into my PR and I can look at the rest of the tweaks?

Since tests are passing and seem stable now, let's merge this PR & your PR already and do the tweaks in a new PR. Sounds good?
