### PR TITLE
Use DropDown for MediaType filter

### LINKED ISSUE #1844: Filter Library by Media Type should be a dropdown
## Bug Description

The filters All, Images and Video should be rolled into a dropdown. 

## Expected Behaviour

[See designs in Figma ](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2731%3A1757)

## Steps to Reproduce

Look at filters in media gallery

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by winterDroid**
## Summary

Replace media type filter tabs with DropDown menu

## Relevant Technical Choices

Reused form drop down as the styles should be the same according to Figma

## To-do

Styling should be done as part of the restyling

## User-facing changes

Screen Shot 2020-08-13 at 4 43 56 pm

## Testing Instructions

Can be verified on the local media pane

---

Fixes #1844

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/local/mediaPane.js [hunk 1]
```diff
@@ -196,6 +179,17 @@ function MediaPane(props) {
...
+  const isNullOrUndefined = (item) => item === null || item === undefined;
+  const activeItem = useMemo(
+    () =>
+      FILTERS.find(
+        (item) =>
+          !isNullOrUndefined(mediaType) &&
+          item.value.toString() === mediaType.toString()
+      ) ?? FILTERS[0],
+    [mediaType]
+  );
```
Comment (swissspidy) [inline assets/src/edit-story/components/library/panes/media/local/mediaPane.js]: Since the Dropdown component does this check already, can't you just pass `value={mediaType?.toString() ||  FILTERS[0]}` to it?

Comment (winterDroid) [reply assets/src/edit-story/components/library/panes/media/local/mediaPane.js]: Good catch. It works with `value={mediaType?.toString() || FILTERS[0].value}`. Changed.

**Review by cvolzke4 — APPROVED** [review]

**Comment by winterDroid** [comment]
All of the failing karma tests are unrelated. Will merge as is.
