### PR TITLE
Animations: Page Duplication Support

### LINKED ISSUE #5501: Duplicating a page with an animation on it causes the editor to crash
## Bug Description

When duplicating a page with an animation on it, the editor crashes. This happens for bg image with zoom effect as well

## Expected Behaviour

not this, that's for sure

## Steps to Reproduce

This was noted by @o-fernandez  on this page here specifically: https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=13900&action=edit#page=%25221bf764b1-48ba-4b35-bfa3-db93c6e87240%2522

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds animation compatibility to page duplication.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
Behind animation experiment: animations now retained on page duplication.

## Testing Instructions
Enable Animations:
- Create a Page with elements with every animation type
- Duplicate the page and see that all animations are on the duplicated page
- Create a story from a template
- Duplicate a page & see that animations are retained.

Disable Animations:
- Duplicate a page and see that it still functions as normal

---

Fixes #5501

### CODE REVIEW

**Review by carloskelly13 — APPROVED** [review]

File: assets/src/edit-story/elements/index.js [hunk 1]
```diff
@@ -73,14 +74,29 @@ export const createPage = (pageProps = null) => {
...
   // Ensure all existing elements get new ids
-  const elements = oldElements.map(({ type, ...attrs }) =>
-    createNewElement(type, attrs)
-  );
+  let elementIdTransferMap = {};
+  const elements = oldElements.map(({ type, ...attrs }) => {
+    const id = uuidv4();
+    elementIdTransferMap[attrs.id] = id;
+    return createNewElement(type, attrs, { id });
+  });
```
Comment (swissspidy) [inline assets/src/edit-story/elements/index.js]: Instead of this whole overrides thing, can't we do:

```suggestion
  const elements = oldElements.map(({ type, ...attrs }) => {
    const newElement = createNewElement(type, attrs, { id });
    elementIdTransferMap[attrs.id] = newElement.id;
    return newElement
  });
```

Comment (maxyinger) [reply assets/src/edit-story/elements/index.js]: ah yeaup. that works too and we wouldn't need to edit the signature. Will update now, thanks!

**Review by swissspidy — APPROVED** [review]

**Review by zachhale — APPROVED** [review]
Works well for me
