### PR TITLE
Workspace: Fix grammar of error messages that use lists

### LINKED ISSUE #1347: Poor grammar in media upload failure message
## Feature Description

Currently the wording in the media upload file type error snackbar message reads as the following
```
Please choose only jpg, png, webm, mp4 to upload.
```

But grammatically it should read.

```
Please choose only jpg, png, webm or mp4 to upload.
```
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Old ticket where a snackbar message was grammatically incorrect.

## Summary

Fixes grammar of a snackbar message.

## Relevant Technical Choices

n/a

## To-do

n/a

## Testing Instructions

TBD

### QA

- [ ] This is a non-user-facing change and requires no QA

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #1347

### CODE REVIEW

File: assets/src/edit-story/app/uploader/useUploader.js [hunk 1]
```diff
@@ -99,17 +99,37 @@ function useUploader() {
...
+            __('%1$s, or %2$s', 'web-stories'),
+            allowedFileTypes.slice(0, allowedFileTypes.length - 1).join(
+              /* translators: delimiter used in a list */
+              __(', ', 'web-stories')
+            ),
+            allowedFileTypes.slice(allowedFileTypes.length - 1)
+          );
+        } else if (allowedFileTypes.length === 1) {
+          options = allowedFileTypes[0];
+        }
```
Comment (swissspidy) [inline assets/src/edit-story/app/uploader/useUploader.js]: Nice job 👍 

Lists like that are hard in i18n because languages have very different rules for that stuff.

If you search for `delimiter used in a list` in the whole code base you'll find many more places where we would need such a solution.

Extracting such a logic into its own function would be great, so we could use it in all these places. It would also need to account for the case where there are exactly 2 items in the list.

See the [`wp_sprintf_l()`](https://developer.wordpress.org/reference/functions/wp_sprintf_l/) PHP function for an example. Note the useful translator comments and how the translatable strings contains both `%1$s` and `%2$s`

Comment (samwhale) [reply assets/src/edit-story/app/uploader/useUploader.js]: I'll whip something up!

Comment (spacedmonkey) [reply assets/src/edit-story/app/uploader/useUploader.js]: You maybe able to just copy and paste the php code from `wp_sprintf_l` and turn it into javascript. 

If a `sprintf_l` is created, then it should live in the [i18n](https://github.com/google/web-stories-wp/tree/main/packages/i18n) package.

Comment (swissspidy) [reply assets/src/edit-story/app/uploader/useUploader.js]: Not a huge fan of the `wp_sprintf_l` API tbh, especially as in WordPress it needs to be used via `wp_sprintf`. Also, please don't just copy code for copyright reasons :-)

But adding such a list function to the `i18n` package sounds like the right place 👍

File: packages/i18n/src/translateToExclusiveList.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        options.slice(0, options.length - 1).join(
+          /* translators: delimiter used in a list */
+          __(', ', 'web-stories')
+        ),
+        options[options.length - 1]
+      );
+  }
+}
+
+export default translateToExclusiveList;
```
Comment (samwhale) [inline packages/i18n/src/translateToExclusiveList.js:54]: This is the same code as the `inclusive` function but it uses an `or` rather than an `and` conjunction. I can combine these into one function but I didn't know if the translations can handle the conjunction being dynamically changed.

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 1 above)
Comment (samwhale) [reply assets/src/edit-story/app/uploader/useUploader.js]: Just updated the code - let me know what y'all think about the functions I created. Happy to change it however you feel is best.

**Review by BrittanyIRL — APPROVED** [review]
This is such a nice improvement and will come in handy! Thanks for going above and beyond the ticket description.

**Review by swissspidy — APPROVED** [review]
Neat!
