### PR TITLE
Adding a persistent scrollbar for media gallery to fix flickering.

### LINKED ISSUE #4311: Jittering items in media library
## Bug Description

As mentioned on Slack, I am experiencing some jittering in the media library at certain window sizes. Happens for me when it’s around 900px tall.

## Expected Behaviour

No jittering.

## Steps to Reproduce

Resize browser to try to reproduce this

## Screenshots

https://cloudup.com/cTN7CkWDnpo

## Additional Context

- Plugin Version: beta 2 / current `main`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ezxyz**
## Summary
Adding a persistent scrollbar to local media to stop the jittering. More info in #4311

## Relevant Technical Choices
Also removed logic around calculating padding size based on whether or not there is a scrollbar (because there will always be a scrollbar)

## User-facing changes

There is now a scrollbar in the local gallery even when there is no overflow. (See the very faint scrollbar in this screenshot)
Screen Shot 2020-09-08 at 4 10 42 PM

Fixes #4311

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js [hunk 1]
```diff
@@ -61,33 +61,7 @@ function PaginatedMediaGallery({
   setNextPage,
 }) {
   // TODO(#1698): Ensure scrollbars auto-disappear in MacOS.
```
Comment (joannag6) [inline assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js]: We can remove this TODO as well (That issue has also been closed)

**Review by joannag6 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js (hunk 1 above)
Comment (ezxyz) [reply assets/src/edit-story/components/library/panes/media/common/paginatedMediaGallery.js]: Done.

**Review by joannag6 — APPROVED** [review]
