### PR TITLE
All links are two-tap links

### LINKED ISSUE #646: Links: Restricted/safe zones
Part of #253 

- [ ] Implement visual aid for safe/prohibited zones where links can't be dragged.
- [ ] Make sure safe zones and 1-tap/2-tap areas respect transforms (more specifically rotation)

### LINKED ISSUE #1000: Broken positioning for one-tap links
## Bug Description

When adding a 1-tap link (aka element within `amp-story-cta-layer`), the absolute positioning is somehow broken and not based on the bottom 20% of the page.

This used to work (after it was once broken), but seems like it regressed again.

Only change that seems relevant is #916.

## Expected Behaviour

1-tap links should be positioned correctly on the page.

## Steps to Reproduce

Add text element with link in the bottom of the (second) page and check the frontend output.

The element is nowhere to be seen.

## Screenshots

Editor:

Screenshot 2020-04-03 at 10 40 55

Frontend:

Screenshot 2020-04-03 at 10 41 12

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
Closes #1000
Closes #646 

- Deprecates one-tap links

### CODE REVIEW

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/migration/migrations/v0014_oneTapLinkDeprecate.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+function reducePage({ elements, ...rest }) {
+  return {
+    elements: elements.map(updateElement),
+    ...rest,
+  };
+}
+
+function updateElement(element) {
+  if (element.link && element.link.type) {
```
Comment (obetomuniz) [inline assets/src/edit-story/migration/migrations/v0014_oneTapLinkDeprecate.js]: nit: `element.link?.type`
