### PR TITLE
Animation: Fixed Delta for Background Zoom Animations

### LINKED ISSUE #7752: Animation: Update BG Zoom to Zoom Delta of 50% (Exploration)
### Brief
Background images can be statically placed anywhere between 100% -> 300% scale. The goal of this ticket is to only make it travel 50% in either direction with regard to zoom in/out.

### Expected Behavior

**Fixed Delta**
Here are some scenarios the behavior should follow:
-> BG Image is 100% scale: Zoom out equates to animating from 150% to 100%
-> BG Image is 200% scale: Zoom in equates to animating from 150% to 200%
-> BG Image is 300% scale: Zoom in equates to animating from 250% to 300%

**Duration and Ease**
Easing and duration of BG Zoom should still follow ones outlined in these slides:
https://docs.google.com/presentation/d/1Ny9o8qAiVmiQiJ4_wSIOhInBM_h2_O5p_IlfZT-xi0E/edit#slide=id.gdc9155b87c_1_0

Defaults:
- `duration: 2000ms`
- `ease: cubic-bezier(.3, 0, .55 ,1)`

### Edge Cases
What do we want to happen if the background image is set to `110%` and the user chooses `ZOOM IN` ?

Options:
- We could just make the background animate from `100% -> 110%` (would look small)
- We could disable `ZOOM IN` as an option unless the image's scale is greater than `150%`
- Other Ideas or options for behavior here?

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
This is an exploration ticket in the work to make animation defaults nicer for users.

## Summary
This PR sets a fixed delta of 50% fo the Background zoom animations. The math is a little hairy to accommodate and translate the fixed delta into the inherited coordinate space of the elements static scale.

## Relevant Technical Choices
Just added moar maths.

## To-do
NA

## User-facing changes
Zoom should now not look so jarring when animating as we only animate 50% in either direction instead of from the largest/smallest the bg image can be scaled.

currently looks like:
https://user-images.githubusercontent.com/35983235/120692871-f375e000-c46d-11eb-9745-113059468ec2.mp4

## Testing Instructions
In the editor, add a background element and checkout the `zoom in` and `zoom out` animations as well as the `pan and zoom` animation. Also change the background images static scale and see that the zoom animations are never jarring.

### QA
Follow testing instructions above. (apologies there's not much to test here beyond the animations should "look better" which is a little open ended/subjective)

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7752

### CODE REVIEW

File: assets/src/animation/effects/backgroundZoom/index.js [hunk 1]
```diff
@@ -29,13 +35,22 @@ export function EffectBackgroundZoom({
   easing = 'cubic-bezier(.3,0,.55,1)',
   transformOrigin,
 }) {
-  // Define the range based off the element scale
+  // Define the min/max range based off the element scale
   // at element scale 400, the range should be [1/4, 1]
   // at element scale 100, the range should be [1, 4]
   const range = [BG_MIN_SCALE / element.scale, BG_MAX_SCALE / element.scale];
 
+  // Compute what a 50% difference is relative to [0%, 400%]
```
Comment (BrittanyIRL) [inline assets/src/animation/effects/backgroundZoom/index.js:43]: these comments are great

**Review by BrittanyIRL — APPROVED** [review]
You do a great job explaining this update which is rather complicated!! 

Zooms look better to me, though as you well put - it is subjective. 🙃

**Review by embarks — APPROVED** [review]
the way I understand it is like this:

use `progress` to calculate the 50% difference for any element's scale. You provide 50 (halfway) as the "progress" arg and then the range using min and max constants (0 and BG_MAX_SCALE).

you interpolate between where the element is on the scale range (the element's actual scale relative to the minimum and maximum scales) and this normalized scale to determine a delta to apply to the `zoomFrom`.

The zoom will always "end" on the state where the user places/scales the element, so the delta is essentially reducing the "amount" of zooming to make it smoother and less jarring, based on **how much** the user has already scaled the element.

**Comment by maxyinger** [comment]
> based on how much the user has already scaled the element.

Yup exactly. We're basically dynamically answering the question of:
_what percentage of `x` is `x +/- 50`_ ?
