### PR TITLE
Fix popup stacking with modals

### LINKED ISSUE #1082: Modals and popups should always be on top of all other layers
## Bug Description

Link overlay is stacked on top of Modal.

Note that this also applies to the (external non-React) media selector that opens when pressing "upload" in media library.

## Expected Behaviour

Link overlay shouldn't display on top of Modal.

## Steps to Reproduce

1. Click on the element with Link
2. Trigger any action that will display Modal (e.g. (i) icon for Link)

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
1. Add a link to any element and select it (link popup should be visible).
2. Click Upload to open "Upload to Story" (WP Uploader).
3. Verify that link popup is under the Upload dialog (is not obstructing the view).

### PR DESCRIPTION
**Pull request by wassgha**
@miina to confirm behavior with calendar

Fixes #1082

### CODE REVIEW

File: assets/src/edit-story/components/popup/index.js [hunk 1]
```diff
@@ -67,9 +67,8 @@ const Container = styled.div.attrs(
 )`
   max-height: ${({ maxHeight }) =>
     maxHeight > 0 ? maxHeight + 'px' : 'initial'};
-  overflow-y: auto;
```
Comment (miina) [inline assets/src/edit-story/components/popup/index.js:70]: @wassgha If this is removed, the scrolling isn't enabled if the height of the content exceeds the height of the popup, resulting in part of the content of the popup being not visible.

This can be seen with calendar:
1. Open the calendar.
2. Scroll up (so that the calendar would be in the bottom of the viewport, resize the window if needed to achieve that)
3. Now click on the month (May 2020) to open the month view - this will change the content height.
4. See part of the months not visible and not scrollable either.
Screenshot 2020-05-28 at 16 38 01

File: assets/src/edit-story/components/popup/index.js [hunk 2]
```diff
@@ -67,9 +67,8 @@ const Container = styled.div.attrs(
...
   position: fixed;
-  z-index: 2147483646;
+  z-index: 2;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js:72]: Shouldn't popup be absolutely definitely above all else? Maybe with an exception of snackbar?

**Comment by wassgha** [comment]
Blocked by #1931

**Comment by merapi** [comment]
> Blocked by #1931

Should we just handle the zIndex part here? it fixes the issue in question.

File: assets/src/edit-story/components/popup/index.js (hunk 1 above)
Comment (wassgha) [reply assets/src/edit-story/components/popup/index.js:70]: Deferred to #1931

**Comment by wassgha** [comment]
> > Blocked by #1931
> 
> Should we just handle the zIndex part here? it fixes the issue in question.

Reverted! See https://github.com/google/web-stories-wp/pull/2306 for the height change.

File: assets/src/edit-story/components/popup/index.js (hunk 2 above)
Comment (wassgha) [reply assets/src/edit-story/components/popup/index.js:72]: Both popup and modals are using the react portals, hence the issue...

**Review by miina — APPROVED** [review]

**Review by merapi — APPROVED** [review]
