### PR TITLE
Media Hotlinking: Improve parsing of `Content-Type` header 

### LINKED ISSUE #11134: Media Hotlinking: Issues with parsing `Content-Type` header
## Bug Description

While testing #11122 I noticed that I was unable to hotlink a caption file such as https://wp.stories.google/stories/how-to-optimize-videos-for-web-stories/tracks/wst024_page2_my_captions.vtt

This is because of how `Hotlinking_Controller` tries to get the mime type here:

https://github.com/GoogleForCreators/web-stories-wp/blob/ea564d5fd09f38f66aae84538cdda595e88d4b3b/includes/REST_API/Hotlinking_Controller.php#L212
https://github.com/GoogleForCreators/web-stories-wp/blob/ea564d5fd09f38f66aae84538cdda595e88d4b3b/includes/REST_API/Hotlinking_Controller.php#L228

For the above URL, `$mime_type` is actually `text/vtt; charset=utf-8`, so the whole mime type / file extension check does not work.

## Expected Behaviour

For `Content-Type` headers such as `text/vtt; charset=utf-8` we need to strip everything after the mime type before trying to guess the file extension.

Needs tests.

## Steps to Reproduce

Either test caption hotlinking with an URL such as the above, or access `wp-json/web-stories/v1/hotlink/validate/?url=https%3A%2F%2Fwp.stories.google%2Fstories%2Fhow-to-optimize-videos-for-web-stories%2Ftracks%2Fwst024_page2_my_captions.vtt` directly while debugging `\Google\Web_Stories\REST_API\Hotlinking_Controller::parse_url()`.

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Fix case where content type returns as `text/vtt; charset=utf-8,`, meaning the hotlink validator fails. 

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Enable caption hotlinking. 
2. Insert video. 
3. Click Link to file ( captions ). 
4. Try to embed - https://wp.stories.google/stories/how-to-optimize-videos-for-web-stories/tracks/wst024_page2_my_captions.vtt. 
5. See it work correctly. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11134

### CODE REVIEW

File: tests/phpunit/integration/tests/REST_API/Hotlinking_Controller.php [hunk 1]
```diff
@@ -119,6 +120,16 @@ public function mock_http_request( $preempt, $r, $url ) {
 			];
 		}
 
+		if ( self::URL_MALFORMED_MIME === $url ) {
```
Comment (swissspidy) [inline tests/phpunit/integration/tests/REST_API/Hotlinking_Controller.php]: Malformed is the wrong word.

`image/png; charset=utf-8` is a totally legitimate `Content-Type` header. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type.

I'd rename it to something like "content-type with mime type" or so

**Comment by timarney** [comment]
Tested this --- looks good outside of the existing comment + a rebase / lint

**Review by swissspidy — APPROVED** [review]

**Review by timarney — APPROVED** [review]
