### PR TITLE
Fixed replacement flip

### LINKED ISSUE #6643: Background droptarget replacement image wrong when flipped
## Bug Description

If you drag a non-flipped image over a flipped background image droptarget, the replacement image shown while dragging over the droptarget edge is also flipped, but once dropped, the actual image is not flipped.

## Expected Behaviour

1. Replacement image shown while dragging should not be flipped

## Steps to Reproduce

1. Add an image to the background
2. Flip the background (any direction)
3. Add another image to canvas
4. Drag image to background droptarget
5. Observe that temporary replacement image shown while dragging over the background droptarget zone is flipped
6. Drop image on background droptarget zone
7. Observe that new background image is not actually flipped

## Screenshots

droptarget-replacement-bug

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

This fixes the replacement image on drop hover on both background elements and regular elements.

When dropping into a background element, the flip of the dropped image is preserved, so the replacement image also reflects this.

When dropping into a regular element (masked or not), the flipped of the existing element is preserved, so the replace image also reflects this.

### QA

This PR can be tested by following these steps:

#### Dragging flipped image to background
1. Drag an image into the background
2. Drag another image onto the canvas
3. Flip the second image
4. Drag it into the background
5. Observe that both the preview image before dropping and the background after drop is **flipped**

#### Dragging non-flipped image into flipped image
1. Drag two images onto the canvas
2. Flip image A
3. Drag (non-flipped) image B into (flipped) image A
5. Observe that both the preview image before dropping and the image after drop is **flipped**

#### Dragging flipped image into non-flipped image
1. Drag two images onto the canvas
2. Flip image A
3. Drag (flipped) image A into (non-flipped) image B
5. Observe that both the preview image before dropping and the image after drop is **not flipped**

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6643

### CODE REVIEW

File: assets/src/edit-story/masks/display.js [hunk 1]
```diff
@@ -85,10 +82,10 @@ export default function WithMask({
 
   return (
     <div
+      className="this-is-foo"
```
Comment (miina) [inline assets/src/edit-story/masks/display.js]: Leftovers from testing?

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js [hunk 2]
```diff
@@ -367,6 +363,121 @@ describe('Background Drop-Target integration', () => {
...
+          // Verify that non-flipped element has the correct transform (flip) before doing anything
+          let target = fixture.editor.canvas.displayLayer.display(imageData.id)
+            .node;
+          let rep = fixture.editor.canvas.displayLayer.display(imageData.id)
+            .replacement;
+          const targetImg = target.querySelector('img');
+          const transformBefore = getAllTransformsBetween(targetImg, target);
+          expect(transformBefore).toBe('');
+
+          // Drag the image element to the background
```
Comment (miina) [inline assets/src/edit-story/components/dropTargets/karma/background.karma.js]: Comment is for the background here, should be for the non-flipped image.

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js [hunk 3]
```diff
@@ -367,6 +363,121 @@ describe('Background Drop-Target integration', () => {
           expect(combinedBgTransform2).toBe('matrix(-1, 0, 0, 1, 0, 0)');
         });
       });
+
+      describe('when there is a third flipped image on the canvas', () => {
```
Comment (miina) [inline assets/src/edit-story/components/dropTargets/karma/background.karma.js:367]: Hm, shouldn't these belong to a separate file? It's a bit confusing that something that has nothing to do with background is under the background Karma. Maybe rename the file if it's mainly for drop-targeting and not for background specifically?

File: assets/src/edit-story/components/canvas/displayElement.js [hunk 4]
```diff
@@ -107,19 +115,12 @@ function DisplayElement({ element, previewMode, isAnimatable = false }) {
         scale: replacement.scale,
         focalX: replacement.focalX,
         focalY: replacement.focalY,
-        flip: replacement.flip,
+        // Okay, this is a bit weird, but... the flip property is taken from the drop-image if
```
Comment (miina) [inline assets/src/edit-story/components/canvas/displayElement.js]:
```suggestion
        // Okay, this is a bit weird, but... the flip property is taken from the target image if
```

File: assets/src/edit-story/components/canvas/displayElement.js [hunk 5]
```diff
@@ -107,19 +115,12 @@ function DisplayElement({ element, previewMode, isAnimatable = false }) {
...
+        // target is background, but from the original image if target is non-background
```
Comment (miina) [inline assets/src/edit-story/components/canvas/displayElement.js]:
```suggestion
        // target is background, but from the origin image if target is non-background
```

**Review by miina — APPROVED** [review]
🌴

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/dropTargets/karma/background.karma.js:367]: I know, I was a bit conflicted about this too. I'll rename the test file to better reflect the test suites contained therein.

File: assets/src/edit-story/components/canvas/displayElement.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/displayElement.js]: Clarified comment in 7eacdbb8d.

File: assets/src/edit-story/components/canvas/displayElement.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/displayElement.js]: Clarified comment in 7eacdbb8d.

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/dropTargets/karma/background.karma.js:367]: Renamed in 61002303e.

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/dropTargets/karma/background.karma.js]: Fixed in 61002303e.

File: assets/src/edit-story/masks/display.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/masks/display.js]: Fixed in 76e11581e.
