### PR TITLE
Fix incorrect `<meta charset>` tags

### LINKED ISSUE #12758: Charset issues on PHP 8.1+
## Bug Description

It was reported to us a couple of times that there are character issues on PHP 8.1.

I noticed it has to do with `DOMDocument` not recognizing `<meta charSet="utf-8"/>` (with uppercase S, as output by React) properly and thus assuming an incorrect encoding.

## Expected Behaviour

UTF-8 characters should be displayed as expected.

## Steps to Reproduce

1. Use PHP 8.1
2. Create a story with content like
	```
	హలో
	â, î ñ ô ü
	español
	गईं।
	English
	தமிழ்
	```
3. Preview story

## Screenshots

Incorrect:
Screenshot 2022-11-30 at 11 40 02

Correct:

Screenshot 2022-11-30 at 11 40 09

## Additional Context

- Plugin Version: 1.27.0
- WordPress Version: 6.1
- Operating System: macOS
- Browser: Chrome
- PHP Version: 8.1

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

It was reported to us a couple of times that there are character issues on PHP 8.1.

I noticed it has to do with `DOMDocument` not recognizing `<meta charSet="utf-8"/>` (with uppercase S, as output by React) properly and thus assuming an incorrect encoding.

## Summary

Enforce lowercase `charset` attribute name.

This fixes the issue for me.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Use PHP 8.1
2. Create a story with content like
	```
	హలో
	â, î ñ ô ü
	español
	गईं।
	English
	தமிழ்
	```
3. Preview story
4. Characters should not be mangled

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12758

### CODE REVIEW

File: includes/AMP/Output_Buffer.php [hunk 1]
```diff
@@ -237,10 +238,12 @@ public function prepare_response( string $response ): string {
...
-	 *
-	 * @todo Improve error message.
 	 */
 	private function render_error_page( Throwable $throwable ): string {
-		return esc_html__( 'There was an error generating the web story, probably because of a server misconfiguration. Try contacting your hosting provider or open a new support request.', 'web-stories' );
+		return esc_html__( 'There was an error generating the web story, probably because of a server misconfiguration. Try contacting your hosting provider or open a new support request.', 'web-stories' ) .
+			"\n" .
+			"\n" .
+			// translators: 1: error message. 2: location.
+			sprintf( esc_html__( 'Error message: %1$s (%2$s)' ), $throwable->getMessage(), $throwable->getFile() . ':' . $throwable->getLine() );
```
Comment (spacedmonkey) [inline includes/AMP/Output_Buffer.php]:
```suggestion
			sprintf( esc_html__( 'Error message: %1$s (%2$s)', 'web-stories' ) ), $throwable->getMessage(), $throwable->getFile() . ':' . $throwable->getLine() );
```

File: tests/phpunit/integration/tests/Renderer/Story/HTML.php [hunk 2]
```diff
@@ -218,6 +218,20 @@ public function test_print_social_share_filter(): void {
...
+	 */
+	public function test_fix_incorrect_charset(): void {
+		$source = '<html><head><meta charSet="utf-8" /></head><body><amp-story></amp-story></body></html>';
+
+		$story    = new Story();
+		$renderer = new \Google\Web_Stories\Renderer\Story\HTML( $story );
+
+		$actual = $this->call_private_method( $renderer, 'fix_incorrect_charset', [ $source ] );
+
+		$this->assertStringNotContainsString( '<meta charset="utf-8"/>', $actual );
```
Comment (spacedmonkey) [inline tests/phpunit/integration/tests/Renderer/Story/HTML.php]:
```suggestion
		$this->assertStringContainsString( '<meta charset="utf-8"/>', $actual );
```

**Comment by spacedmonkey** [comment]
Valid unit test and lint errors.

**Review by spacedmonkey — APPROVED** [review]
