### PR TITLE
Fix poster on drop upload

### LINKED ISSUE #1001: Video poster images disappearing
## Bug Description

The video poster image doesn't seem to persist.

## Expected Behaviour

Once set, the poster image should stay

## Steps to Reproduce

1. Upload video by dragging it onto the page, maybe make it a background
2. After upload is finished, see poster image appearing in the design panel
3. After a short time, the poster image disappears again

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
This one will fix #1001 and maybe some more (anything related to drop upload -> video posters/video on page preview).

In recent days, the `id` has been removed (replaced with `videoId`) from Media items. It is needed for poster generation (also used in `UPDATE_MEDIA_ELEMENT`).

It would be nice to remove `videoId` (currently also on image elements) and just stick to `id`. Will check the impact of that (do we need migration?).

We now generate the video poster right after drop upload.

Still checking some edge cases.

### CODE REVIEW

File: assets/src/edit-story/app/media/utils/createResource.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ function createResource({
   height,
   poster,
   posterId,
+  id,
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/utils/createResource.js:63]: Please update type definition above with the ID.

File: assets/src/edit-story/app/media/mediaProvider.js [hunk 2]
```diff
@@ -126,9 +126,14 @@ function MediaProvider({ children }) {
   );
 
   const processor = useCallback(
-    ({ mimeType, posterId, id, src, videoId }) => {
+    ({ mimeType, posterId, id, src, videoId, local }) => {
       const process = async () => {
-        if (allowedVideoMimeTypes.includes(mimeType) && !posterId && videoId) {
+        if (
+          allowedVideoMimeTypes.includes(mimeType) &&
+          !local &&
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/mediaProvider.js:133]: Same question as on the other pull request: how do we upload posters for an uploaded video? In theory we have poster in hand right away and can push it almost right away, or at least as soon as we have `videoId`.

File: assets/src/edit-story/app/media/utils/getResourceFromAttachment.js [hunk 3]
```diff
@@ -27,7 +27,7 @@ import createResource from './createResource';
  */
 function getResourceFromAttachment(attachment) {
   const {
-    id: videoId,
+    id,
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/utils/getResourceFromAttachment.js:30]: We need to do the same for other functions in that package: `getResourceFromMediaPicker` and `getResourceFromUpload`. TBH I'm not sure if all three are at all different, we've been just keeping them in sync.

File: assets/src/edit-story/app/media/mediaProvider.js [hunk 4]
```diff
@@ -126,9 +126,14 @@ function MediaProvider({ children }) {
   );
 
   const processor = useCallback(
-    ({ mimeType, posterId, id, src, videoId }) => {
+    ({ mimeType, posterId, id, src, videoId, local }) => {
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/mediaProvider.js]: So, in this new state, is `id === videoId`?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 4 above)
Comment (merapi) [reply assets/src/edit-story/app/media/mediaProvider.js]: Right now - yes. But I will remove `videoId` because it doesn't make sense (on image) and we will just have `id` like a few days earlier.

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 2 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/mediaProvider.js:133]: You have to await videoId to exist before upload the poster, as we need to link the two other. 
Remember, this this upload, is not our only touch point into the media library. The backbone based media picker also integrates.

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 4 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/mediaProvider.js]: Yeah, videoId should be removed here.

File: assets/src/edit-story/components/canvas/canvasUploadDropTarget.js [hunk 5]
```diff
@@ -59,16 +60,28 @@ function CanvasUploadDropTarget({ children }) {
...
+      };
       updateElementById({
         elementId: element.id,
         properties: {
-          resource,
-          type: element.resource.type,
+          resource: updatedResource,
         },
       });
+      await uploadVideoPoster(resource.videoId, resource.src);
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/canvas/canvasUploadDropTarget.js]: So on upload trigger the videoPoster generation? This make sense, as we now have a processing queue, that should mean there are not processing.

Comment (spacedmonkey) [reply assets/src/edit-story/components/canvas/canvasUploadDropTarget.js]: I would still add a check for upload ( attachment ) type.

**Comment by spacedmonkey** [comment]
I believe if we are going to trigger poster upload, this should also be done on the media selector. If you need help with this, then let me know and I can point you in the right direction.

**Comment by spacedmonkey** [comment]
We also need to tweak this logic https://github.com/google/web-stories-wp/blob/f688826f5043f9619d7e8fde7ab31bb21e1a0e95/assets/src/edit-story/components/canvas/useInsertElement.js#L42-L57  

As this `uploadVideoPoster` function no longer take `elementId, resource` as args anymore. CC @ndev1991 
✅ Done /merapi

File: assets/src/edit-story/app/media/utils/getResourceFromAttachment.js (hunk 3 above)
Comment (merapi) [reply assets/src/edit-story/app/media/utils/getResourceFromAttachment.js:30]: I gathered them all in one place, so now I can compare them without losing sanity (and maybe improve it in another PR?):
https://gist.github.com/merapi/b08644a37f8ee302ed6d8ca8162a0abc
_pre = argument
post = result_

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 4 above)
Comment (merapi) [reply assets/src/edit-story/app/media/mediaProvider.js]: Replacing `videoId` with `id` (globally) is done here: https://github.com/google/web-stories-wp/pull/1037/commits/f7e7d82b2f3620d40d3e1523eb604a6ddc3c1896 and next commit with migration file.

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 6]
```diff
@@ -65,15 +65,15 @@ function useInsertElement() {
...
       addElement({ element });
       if (resource) {
-        backfillResource(resource, elementId);
+        backfillResource(resource);
       }
       // Auto-play on insert.
       if (type === 'video') {
         setTimeout(() => {
-          const videoEl = document.getElementById(`video-${elementId}`);
+          const videoEl = document.getElementById(`video-${id}`);
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/canvas/useInsertElement.js:76]: If we are using the video's id now, what if there are two element with same id on one page?

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 7]
```diff
@@ -45,12 +45,12 @@ function useInsertElement() {
...
   const backfillResource = useCallback(
-    (resource, elementId) => {
-      const { type, src, videoId, posterId } = resource;
+    (resource) => {
+      const { type, src, id, posterId } = resource;
 
       // Generate video poster if one not set.
-      if (type === 'video' && videoId && !posterId) {
-        uploadVideoPoster(videoId, src, elementId, resource);
+      if (type === 'video' && id && !posterId) {
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/canvas/useInsertElement.js:52]: Think we should check that the resource isn't local, just in case.

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 6 above)
Comment (merapi) [reply assets/src/edit-story/components/canvas/useInsertElement.js:76]: This is just a rename, it's the element UUID.

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 7 above)
Comment (merapi) [reply assets/src/edit-story/components/canvas/useInsertElement.js:52]: We already have 2 JIC checks: id is not set for local resource & we have this processing array.

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 6 above)
Comment (spacedmonkey) [reply assets/src/edit-story/components/canvas/useInsertElement.js:76]: Oh I see. Nevermind.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 8]
```diff
@@ -32,10 +37,22 @@ export default function useMediaPicker({
...
+  const {
+    actions: { uploadVideoPoster },
+  } = useMedia();
   useEffect(() => {
     // Work around that forces default tab as upload tab.
     wp.media.controller.Library.prototype.defaults.contentUserSetting = false;
   });
+  useEffect(() => {
+    try {
+      wp.Uploader.prototype.success = ({ attributes }) => {
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js:49]: Why not just extract the properties you need here.

Comment (merapi) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js:49]: I wanted to do it, but then I saw `type` above... (`no-shadow`), so it's this vs renaming, no strong preference.

**Comment by merapi** [comment]
There is still improvement left: drop to media library, right now poster generation is not triggered because media.length doesn't change, so it's generated on insert (or if you switch tabs). I will trigger the generation on drop (maybe unify the code with canvas drop?) - but that can also be a separate PR (already a lot of files changed here).

**Comment by merapi** [comment]
I also think we should change `updateVideoElementsById` (which I already renamed from `updateVideoElementsByVideoId`) because it is not tied with `Video`.

`updateElementsByResourceId`?

**Comment by spacedmonkey** [comment]
> I also think we should change `updateVideoElementsById` (which I already renamed from `updateVideoElementsByVideoId`) because it has nothing to do with `Video`, it’s the same as `updateElements` just for all pages instead of the current page.
> 
> Any suggestions for names?
> `updateElements` really is `updateCurrentPageElements`
> `updateVideoElementsById` should be `updateAllPagesElements`?
> or maybe just `updateElements` with `allPages` flag?

`updateVideoElementsById` still uses the video id to update the elements, so it is still heavily related to video, as I can see.

**Comment by spacedmonkey** [comment]
Where as this PR been left? Is it still a WIP?

**Comment by spacedmonkey** [comment]
> right now poster generation is not triggered because media.length doesn't change, so it's generated on insert (or if you switch tabs). 

Should we just change it to `media` instead of `media.length`

**Comment by merapi** [comment]
> `updateVideoElementsById` still uses the video id to update the elements. 

Yes (if we are talking about usage in useUploadVideoFrame).

> , so it is still heavily related to video, as I can see.  

No, I can update images too.

It should be named ~`updateElementsByResourceId`

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 7 above)
Comment (spacedmonkey) [reply assets/src/edit-story/components/canvas/useInsertElement.js:52]: I guess a local video would not have an id, so would not pass. Just trying to be careful.

**Comment by spacedmonkey** [comment]
> It should be named ~`updateElementsByResourceId`

Works for me :+1: 

> Should we just change it to media instead of media.length

I remembered why I did this, because updating the media by adding a poster meant that it would trigger another reprocess. Even with the process queue, it did mean that the browser would start to really slow down.

**Comment by merapi** [comment]
`updateElementsByResourceId` done.

Media Library drop upload - fixed, for now, we can go back and improve the processing part later (so we don't loop over all items on every page fetch).

File: assets/src/edit-story/app/media/utils/getResourceFromAttachment.js (hunk 3 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/media/utils/getResourceFromAttachment.js:30]: There's definitely no doubt in my mind that all three should be the same shape object. Whether or not this is possible or desirable with the current WP setup, I'll have to leave to @swissspidy. But at the moment, we definitely need to file an issue to unify them if possible (including your gist, thanks!) and just make sure that we update all `getResourceFrom*` for now. It's a slight duplication, but refactoring is a bigger deal and might better wait a bit.

**Comment by dvoytenko** [comment]
> I also think we should change `updateVideoElementsById` (which I already renamed from `updateVideoElementsByVideoId`) because it is not tied with `Video`.
> 
> `updateElementsByResourceId`?

Good idea.

File: assets/src/edit-story/migration/migrations/v0013_videoIdToId.js [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+
+function reducePage({ elements, ...rest }) {
+  return {
+    elements: elements.map(updateElement),
+    ...rest,
+  };
+}
+
+function updateElement(element) {
+  if (element.resource && 'videoId' in element.resource) {
```
Comment (dvoytenko) [inline assets/src/edit-story/migration/migrations/v0013_videoIdToId.js:32]: This is important part. But just like with reducers, this system requires always to clone things if they change. E.g. this should be:

```
if (doesNotNeedToChange) {
  return element;
}
return {
  ...element,
  resource: {
    ...element.resource,
    id: element.resource.videoId,
    videoId: undefined,
  },
};
```

Note that undefines instead of deletes are totally ok in most of cases here b/c they are auto-deleted on serialization.

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Mostly LG, but one important nuance.

File: assets/src/edit-story/app/media/utils/getResourceFromAttachment.js (hunk 3 above)
Comment (merapi) [reply assets/src/edit-story/app/media/utils/getResourceFromAttachment.js:30]: Filed in https://github.com/google/web-stories-wp/issues/1097

File: assets/src/edit-story/migration/migrations/v0013_videoIdToId.js (hunk 9 above)
Comment (merapi) [reply assets/src/edit-story/migration/migrations/v0013_videoIdToId.js:32]: I was thinking about it.
If this was in the reducer - no doubt. Because we want to re-render if you ever change something in the e.g. resource.

But this is in a simple `migrate` function that needs to preprocess the data, then we restore the story from that data (and this will be the baseline for change detection, no need for re-renders before that).

It's like useState initial value:
```jsx
const storyDataRaw = {
  version: 1,
  pages: [{ elements: [{ resource: { count: 1, toDelete: true } }] }]
};
const migrate = data => {
  // It's ok, less code than cloning
  data.pages[0].elements[0].resource.count = 2;
  data.pages[0].elements[0].resource.toDelete = undefined;
  return data;
};

...
const [storyData] = useState(
  storyDataRaw && migrate(storyDataRaw)
);
```
Is that correct thinking?
I can still follow reducer-style, just want to know is there anything wrong with it?

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 8 above)
Comment (spacedmonkey) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js:49]: I would rename the property. That is me.

File: assets/src/edit-story/migration/migrations/v0013_videoIdToId.js (hunk 9 above)
Comment (spacedmonkey) [reply assets/src/edit-story/migration/migrations/v0013_videoIdToId.js:32]: Is this really even needed? We are not even in alpha yet and all this MIGHT break is if the existing video elements on dev boxes right?

Comment (merapi) [reply assets/src/edit-story/migration/migrations/v0013_videoIdToId.js:32]: Correct, we can only break our (dev+staging) meticulously made stories.

For me, it was pre-production training 😉

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Review by spacedmonkey — APPROVED** [review]
I have one small nit pick about object using properties of an object. 

In my testing, this is working well now.

File: assets/src/edit-story/migration/migrations/v0013_videoIdToId.js (hunk 9 above)
Comment (dvoytenko) [reply assets/src/edit-story/migration/migrations/v0013_videoIdToId.js:32]: Yeah, I took a look and not seeing anywhere `preMigration === postMigration` checks. So your path is probably ok. Though I still feel weird about reusing objects and the level of effort is very similar.

**Comment by spacedmonkey** [comment]
@dvoytenko Is this PR good to merge then?

**Review by dvoytenko — APPROVED** [review]
