### PR TITLE
Stories block: Fix story selector screen styling issue

### LINKED ISSUE #7526: Stories block: Story selector screen styling issue.
## Bug Description

Styling issues with WordPress 5.3.6

## Screenshots

Screenshot 2021-05-14 at 11 40 12

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.3.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Story selector screen styling issue. This happened when design system change, making the CSS wrong. 

## Relevant Technical Choices

Adding a E2E and screenshot, should mean this doesn't happen again. 

## User-facing changes

Screenshot 2021-06-25 at 14 06 26
### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new post.
2. Create a web stories block. 
3. Select, selected stories. 
4. Select a layout type ( type is not important ). 
5. Click selected stories button. 
6. See select stories model. 

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7526

### CODE REVIEW

File: packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js [hunk 1]
```diff
@@ -102,6 +108,25 @@ describe('Web Stories Block', () => {
...
+    await expect(page).toClick('div.components-card__body', {
+      text: 'Selected Stories',
+    });
+    await expect(page).toClick('div.components-card__body', {
+      text: 'Box Carousel',
+    });
+    await expect(page).toClick('button', { text: 'Select Stories' });
+    await page.waitForSelector('.components-modal__screen-overlay');
+    await expect(page).toMatchElement('.components-modal__screen-overlay');
+    await percySnapshot(page, 'Story select model');
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js]:
```suggestion
    await percySnapshot(page, 'Story select modal');
```

File: packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js [hunk 2]
```diff
@@ -41,9 +41,14 @@ const EMBED_BLOCK_CONTENT = `
 describe('Web Stories Block', () => {
   let stopRequestInterception;
   let removeErrorMessage;
+  let removeError404Message;
 
   beforeAll(async () => {
+    // TODO, look into why this error is happening.
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js]: Creating a ticket for this would be good

Comment (spacedmonkey) [reply packages/e2e-tests/src/specs/wordpress/webStoriesBlock.js]: Fixed.

**Review by swissspidy — APPROVED** [review]
