### PR TITLE
Editor: Make text selectable in Checklist and Shortcuts panels

### LINKED ISSUE #11540: Unable to select text in pre-publish checklist
## Bug Description

I noticed that users are currently unable to select text in the pre-publish checklist (and the keyboard shortcuts menu).

This is because they're part of the canvas layer where selection is disabled somewhere higher up

For the quick tips panel we solved this by adding `*{ user-select: text; }` 

## Expected Behaviour

It would be nice if text could be selected.

## Steps to Reproduce

1. Open checklist or keyboard shortcuts dialog
2. Try to select text

## Screenshots

Cannot select text:
Screenshot 2022-05-23 at 21 40 16

Screenshot 2022-05-23 at 21 40 20

But here it is possible:

Screenshot 2022-05-17 at 10 24 06

## Additional Context

- Plugin Version: 1.21.0
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by mflorida**
## Context

Text in 'Checklist' and 'Keyboard Shortcuts' panels should be user-selectable.

## Summary

'Checklist' and 'Keyboard Shortcuts' panels now have selectable text.

## Relevant Technical Choices

CSS rule `user-select: text` was applied to ancestor of the affected elements.

## To-do

None

## User-facing changes

image

image

image

## Testing Instructions

Click the 'Checklist' or 'Keyboard Shortcuts' buttons on the left side (LTR) of the canvas footer to open the respective panels. Drag mouse cursor to select text in the body of the panel. Text should be selected and able to be copied.

- [ ] This is a non-user-facing change and requires no QA

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11540

### CODE REVIEW

File: packages/story-editor/src/components/keyboardShortcutsMenu/landmarkShortcuts.js [hunk 1]
```diff
@@ -31,11 +31,12 @@ const LandmarksWrapper = styled.dl`
   padding: 16px 24px;
   display: flex;
   justify-content: space-between;
+  user-select: text;
 `;
 
 const Landmark = styled.div`
   display: flex;
-  flex-direction: column-reverse;
+  flex-direction: column;
```
Comment (mflorida) [inline packages/story-editor/src/components/keyboardShortcutsMenu/landmarkShortcuts.js:39]: This had to be changed to allow proper top-left to bottom-right selections.

File: packages/story-editor/src/components/keyboardShortcutsMenu/landmarkShortcuts.js [hunk 2]
```diff
@@ -53,10 +54,10 @@ function LandmarkShortcuts() {
     <LandmarksWrapper>
       {landmarks.map(({ label, shortcut }) => (
         <Landmark key={label}>
+          <ShortcutLabel keys={shortcut} />
```
Comment (mflorida) [inline packages/story-editor/src/components/keyboardShortcutsMenu/landmarkShortcuts.js:57]: This change renders the `<dt>` element **_after_** the `<dd>` element. I'm not sure how strict the standard is about their order in the markup (if `<dt>` must absolutely come _before_ `<dd>`). This change was necessary to allow correct text selection from top-left to bottom-right.

File: packages/story-editor/src/components/keyboardShortcutsMenu/shortcutMenuSection.js [hunk 3]
```diff
@@ -79,10 +79,10 @@ function ShortcutMenuSection({ title, commands }) {
       <List title={title}>
         {commands.map(({ label, shortcut }) => (
           <ListRow key={label}>
+            <ShortcutLabel keys={shortcut} alignment={'left'} />
```
Comment (mflorida) [inline packages/story-editor/src/components/keyboardShortcutsMenu/shortcutMenuSection.js:82]: This puts the `<dt>` element _**after**_ the `<dd>` element in order for text selection to work properly. If reordering the elements like this is invalid markup and causes accessibility or other issues, another element can be used (`<div>` or `<span>`) and appropriate `aria-*` attributes can be added if needed.

**Review by sblinde — APPROVED** [review]
🐝

Talked about this in standup and I think this is a good approach to get it working!

**Review by mwritter — APPROVED** [review]
