### PR TITLE
Fix text selection in panels and library

### LINKED ISSUE #5407: Unable to properly select text in panels
## Bug Description

When a creator tries to select the text in the prepublish checklist, something prevents this from happening. Selecting from the bottom captures a different set of text than selecting from the top

Screen Shot 2020-11-23 at 2 52 46 PM

Screen Shot 2020-11-23 at 2 53 10 PM

## Steps to Reproduce
1.  open an existing story with some recommendations
2. use the standard click drag to select text from the Prepublish checklist recommendations
3. note the inability to select all text as expected

Screen Shot 2020-11-23 at 2 53 10 PM

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Enable user to properly select text in panels 

## Relevant Technical Choices

Use global.getSelection to identify the section scope from the user. Prevent preventScroll setting on focusout event that is outside the canvas container. 

## To-do

N/A

## User-facing changes

User will be able to select text on both the left sidebar and the right sidebar (checklist panel, document panel, ... etc)

## Testing Instructions

User should be able to select text properly outside the canvas container.

---

Fixes #5407

### CODE REVIEW

**Comment by zidianlyu** [comment]
Just a reference for some technical research about the focus preventScroll document:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus#Focus_with_focusOption

Also to recap, here is the scenario that should trigger the focusout event in before the fix:
1. Select a text in the canvas, highlight some text, like this:
Screen Shot 2020-12-29 at 3 47 55 PM

2. Multi-select the 2nd text, move the 2nd text, the 1st text shouldn't move:
Screen Shot 2020-12-29 at 3 48 28 PM
 
We shouldn't break the logic above while allow user to properly select text outside the canvas container:
Screen Shot 2020-12-29 at 3 52 16 PM

The text selection should no longer get block by the 300ms timer.

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 1]
```diff
@@ -100,6 +100,17 @@ function useCanvasKeys(ref) {
 
     const doc = container.ownerDocument;
 
+    const isDescendant = (parent, child) => {
```
Comment (dreamofabear) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]: Could we use [Node.contains](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) here?

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 2]
```diff
@@ -113,6 +124,17 @@ function useCanvasKeys(ref) {
             currentSelectedIds?.length === 1
               ? getNodeForElement(currentSelectedIds[0])
               : null;
+
+          // Check if the selection event happends outside the canvas container,
+          // i.e Checklist panel, Document panel... etc.
+          const selectedAnchor = global.getSelection().anchorNode;
+          const inCanvasContainer = isDescendant(selectedAnchor, container);
+          if (!inCanvasContainer) {
```
Comment (dreamofabear) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]: Instead of checking ancestry, why not simply check if there is any text selection i.e. anchorOffset is non-zero?

Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Ah, thanks for sharing! That is exactly what I was looking for!

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Use the anchorOffset approach, no longer need this helper function.

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 3]
```diff
@@ -113,6 +113,17 @@ function useCanvasKeys(ref) {
             currentSelectedIds?.length === 1
               ? getNodeForElement(currentSelectedIds[0])
               : null;
+
+          // Check if the selection event happends outside the canvas container,
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]:
```suggestion
          // Check if the selection event happend outside the canvas container,
```

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 4]
```diff
@@ -113,6 +113,17 @@ function useCanvasKeys(ref) {
...
+          // i.e Checklist panel, Document panel... etc. If there is any text
+          // selection, we should not add the preventScroll setting, so that
+          // user can select the text properly.
+          if (global.getSelection().anchorOffset !== 0) {
+            return;
+          }
+
+          // If there is a multiple selection happene inside the canvas
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]:
```suggestion
          // If there is a multi-selection happening inside the canvas
```

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 5]
```diff
@@ -113,6 +113,17 @@ function useCanvasKeys(ref) {
             currentSelectedIds?.length === 1
               ? getNodeForElement(currentSelectedIds[0])
               : null;
+
+          // Check if the selection event happends outside the canvas container,
+          // i.e Checklist panel, Document panel... etc. If there is any text
+          // selection, we should not add the preventScroll setting, so that
+          // user can select the text properly.
+          if (global.getSelection().anchorOffset !== 0) {
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]: Are we sure this works?

If the selection begins with the first character in the `anchorNode`, `anchorOffset` returns `0`. So `0` is a legitimate value and does _not_ indicate that there isn't a selection.

In other words:

* No selection on page: `anchorOffset` returns `0`
* Selection(s) on page, starting at the beginning, `anchorOffset` can also return `0`

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: As per my other comment, `anchorOffset === 0` does _not_ mean there is _no_ selection.

Comment (dreamofabear) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Yea, maybe check `getSelection().type` or compare `toString()` to empty string instead.

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Updated

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Updated.

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 5 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Got it, so my understand is, we want to make sure the logic skip only when a `text object` is selected, then: 
1.  `anchorNode` is not null
2. `anchorOffset` is not 0

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 6]
```diff
@@ -113,6 +113,18 @@ function useCanvasKeys(ref) {
             currentSelectedIds?.length === 1
               ? getNodeForElement(currentSelectedIds[0])
               : null;
+
+          // Check if the selection event happend outside the canvas container,
+          // i.e Checklist panel, Document panel... etc. If there is any text
+          // selection, we should not add the preventScroll setting, so that
+          // user can select the text properly.
+          const sel = global.getSelection();
+          if (sel.anchorNode && sel.anchorOffset !== 0) {
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js]: I think `sel.anchorNode` will always return an element. So I don't think this works.

If I run `window.getSelection().anchorNode` in dev tools it's  never `null`/`undefined`

File: assets/src/edit-story/components/canvas/useCanvasKeys.js (hunk 5 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Per my other comment, I don't see how `anchorNode` is ever `null`.

Please test again.

Comment (zidianlyu) [reply assets/src/edit-story/components/canvas/useCanvasKeys.js]: Got it!
By doing some researches, both `sel.type` and `sel.toString()` are good ways to identify the selection type.
For `sel.type`:
If we select a text, the type should be `Range`; if we choose from the editor, the type will be `Caret`

For `sel.toString`:
If we select a text, the method should return the selected string; whereas from the editor, it will return an empty string.

I am thinking to go with the 2nd way and think the check will be enough.

**Review by swissspidy — APPROVED** [review]

**Review by dreamofabear — APPROVED** [review]
