### PR TITLE
Dashboard: Migrate templates on load to latest version

### LINKED ISSUE #2120: Handle Template Migrations
## Bug Description

Currently when the schema for stories changes, the built-in templates do not get automatically updated.

A couple options include running templates through `migrate(templateData, templateData.version)` when they are used or automating template upgrades via PR. The challenge is templates use the PreviewElement component which always works on the latest template version. It may be better to run the template migrator when template data is loaded into the Provider to prevent blank previews.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR migrates our template data to the latest version when they're first loaded into the app.

## Relevant Technical Choices

Since we load all 8 templates at once, I couldn't really migrate them one at a time, so instead I save off migrated results into a hash.  This way each template will only be processed once (on load) and won't be re-processed until the app is fully reloaded by the user.

## User-facing changes

- None

## Testing Instructions

- Go to the "Explore Templates" and make sure the page loads.

---

Fixes #2120

### CODE REVIEW

File: assets/src/dashboard/templates/index.js [hunk 1]
```diff
@@ -14,6 +14,14 @@
  * limitations under the License.
  */
 
+/**
+ * External dependencies
```
Comment (swissspidy) [inline assets/src/dashboard/templates/index.js]: remove?

Comment (mariano-formidable) [reply assets/src/dashboard/templates/index.js]: Good catch, I fixed it, not sure how that got in there.

File: assets/src/dashboard/templates/index.js [hunk 2]
```diff
@@ -26,16 +27,56 @@ import getFitnessStoryData from './data/fitness';
 import getTravelStoryData from './data/travel';
 import getWellbeingStoryData from './data/wellbeing';
 
+const migrationCache = {};
```
Comment (carloskelly13) [inline assets/src/dashboard/templates/index.js]: Should we use a `Map` here since it's more geared towards quickly looking up data and as a cache?

Comment (mariano-formidable) [reply assets/src/dashboard/templates/index.js]: Oh yeah, I can dig it.  I'll update.

File: assets/src/dashboard/templates/index.js [hunk 3]
```diff
@@ -26,16 +27,56 @@ import getFitnessStoryData from './data/fitness';
 import getTravelStoryData from './data/travel';
 import getWellbeingStoryData from './data/wellbeing';
 
+const migrationCache = new Map();
```
Comment (mariano-formidable) [inline assets/src/dashboard/templates/index.js]: @carlos-kelly Updated to a `Map` 👍

**Review by carloskelly13 — APPROVED** [review]

**Review by maxyinger — APPROVED** [review]
