### PR TITLE
Frontend: Improve Twitter Card markup

### LINKED ISSUE #5918: Frontend: Twitter Card markup incorrect and incomplete
## Bug Description

Our Twitter card markup currently consists two meta tags:

https://github.com/google/web-stories-wp/blob/13f1a40966d5213ba7ec6832777b317d84a29e8e/includes/Discovery.php#L266-L279

**First**, the latter tag is incorrect, as it should be `<meta name="twitter:image"`, not `<meta property="twitter:image"`.

Because of that, Twitter is actually falling back to the `og:image` version, so it _seems_ like it works as expected.

**Second**, I think we should also implement `twitter:image:alt` as there's no `og:*` fallback for that.

Documentation for reference:

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

**On that note...**

I think it might be worth adding filters to `Discovery::print_open_graph_metadata()` and `Discovery:: print_twitter_metadata()`, just like `Discovery::get_schemaorg_metadata()` has a filter already as well.

This way devs could extend the markup to include things like their twitter username, or different descriptions for Twitter, etc. if they're not already using another plugin for this, of course.

## Additional Context

- Plugin Version: 1.2.1 / `main`
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Copied the format of schema's methods and filter, broke twitter and og into print and get methods, adding a filter a long the way. 

## Relevant Technical Choices

- New filters also pass post object, like schema filter so keep consistency. 
- EscapeOutput is ignored as this is done upstream. 
- Added some simple tests. 

## Testing Instructions

---

Fixes #5918

### CODE REVIEW

File: includes/Discovery.php [hunk 1]
```diff
@@ -262,22 +298,64 @@ public function print_twitter_metadata() {
...
 		}
-		?>
-		<meta name="twitter:card" content="summary_large_image" />
-		<?php
+		$metadata = $this->get_twitter_metadata();
 
-		if ( ! has_post_thumbnail() ) {
-			return;
+		foreach ( $metadata as $name => $value ) {
+			printf( '<meta name="%s" content="%s" />', $name, $value );  // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (swissspidy) [inline includes/Discovery.php]: That's dangerous, because output is not escaped when I add additional stuff through the `web_stories_story_twitter_metadata` filter.

Should use `esc_attr()` here (for both name **and** value), and remove `esc_attr()` from `get_twitter_metadata`.

-> basically escaping as late as possible

File: includes/Discovery.php [hunk 2]
```diff
@@ -262,22 +298,64 @@ public function print_twitter_metadata() {
...
+
+		if ( $post instanceof WP_Post ) {
+			if ( has_post_thumbnail( $post ) ) {
+				$poster_id = (int) get_post_thumbnail_id( $post );
+				if ( $poster_id ) {
+					$poster = wp_get_attachment_image_url( $poster_id, Media::POSTER_PORTRAIT_IMAGE_SIZE );
+
+					if ( $poster ) {
+						$metadata['twitter:image'] = esc_url( $poster );
+						$image_alt                 = get_post_meta( $poster_id, '_wp_attachment_image_alt', true );
```
Comment (swissspidy) [inline includes/Discovery.php]: I doubt that the featured image will have good alt text, especially when it was uploaded through the editor, since its alt text cannot be edited there.

So I think we should — at least for now — just use the story title directly instead, and don't bother with the alt text.

Comment (spacedmonkey) [reply includes/Discovery.php]: Fixed in https://github.com/google/web-stories-wp/pull/5919/commits/11ab8119541426348958a72ec412460d410e3c0d

File: includes/Discovery.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/Discovery.php]: Fair point. Fixed in https://github.com/google/web-stories-wp/pull/5919/commits/11ab8119541426348958a72ec412460d410e3c0d

File: includes/Discovery.php [hunk 3]
```diff
@@ -161,7 +161,12 @@ protected function get_schemaorg_metadata() {
 				[
 					'@type'            => 'Article',
 					'mainEntityOfPage' => get_permalink( $post ),
-					'headline'         => get_the_title( $post ),
+					'headline'         => the_title_attribute(
```
Comment (spacedmonkey) [inline includes/Discovery.php]: Unrelated, so that all titles comes from the same place and are escaped.

File: includes/Discovery.php [hunk 4]
```diff
@@ -262,22 +303,58 @@ public function print_twitter_metadata() {
...
+		 */
+		$post = get_queried_object();
+
+		if ( $post instanceof WP_Post ) {
+			if ( has_post_thumbnail( $post ) ) {
+				$poster = wp_get_attachment_image_url( (int) get_post_thumbnail_id( $post ), Media::POSTER_PORTRAIT_IMAGE_SIZE );
+
+				if ( $poster ) {
+					$metadata['twitter:image']     = esc_url( $poster );
+					$metadata['twitter:image:alt'] = the_title_attribute(
```
Comment (swissspidy) [inline includes/Discovery.php]: Doesn't this cause double escaping?

Comment (spacedmonkey) [reply includes/Discovery.php]: Is that a problem?

Comment (spacedmonkey) [reply includes/Discovery.php]: It was used [here](https://github.com/google/web-stories-wp/blob/7a9fe66c83713c5877bcbc4fc9855d86f4bf150b/includes/Discovery.php#L217)

Comment (swissspidy) [reply includes/Discovery.php]: It might cause problems.

If everything is passed through `esc_attr()`, we can safely use `get_the_title()` here instead.

Comment (spacedmonkey) [reply includes/Discovery.php]: Fixed in https://github.com/google/web-stories-wp/pull/5919/commits/78329de9f2793bc25961b6326446d19a6c76e0fd

**Review by swissspidy — APPROVED** [review]
LGTM! 👍
