### PR TITLE
Fix Firefox alignment issues on numeric fields.

### LINKED ISSUE #873: Layout issues on Firefox
## Bug Description

Input fields and tooltips are currently totally out of place in Firefox.

We need to fix this & get better at cross browser testing.

A good opportunity to add all these components to the storybook if missing, so we can more easily test them in isolation in different browsers.

## Screenshots

Screenshot 2020-03-30 at 21 55 58

v72.02, Mac
image

v74, Windows 10
image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by obetomuniz**
Fixes #873.
 
Screen Shot 2020-03-31 at 14 37 59

cc @swissspidy I was not able to reproduce the tooltip alignment issue, can you add some steps to reproduce that on the Issue? Thanks.

### CODE REVIEW

File: assets/src/edit-story/components/form/numeric.js [hunk 1]
```diff
@@ -91,45 +91,47 @@ function Numeric({
...
-            }
-          }
-        }}
-        onBlur={(evt) => {
-          if (evt.target.form) {
-            evt.target.form.dispatchEvent(new window.Event('submit'));
-          }
-          if (onBlur) {
-            onBlur();
+      <div>
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: Not a big fan of random divs. No better semantic element? It's just the `<input />` that needs a wrapping div alone? Seems arbitrary.

Comment (obetomuniz) [reply assets/src/edit-story/components/form/numeric.js]: Just pushed a better fix proposal. Take a look 😄

File: assets/src/edit-story/components/form/numeric.js [hunk 2]
```diff
@@ -37,7 +37,8 @@ import MULTIPLE_VALUE from './multipleValue';
 const DECIMAL_POINT = (1.1).toLocaleString().substring(1, 2);
 
 const StyledInput = styled(Input)`
-  width: 100%;
+  flex: 1 1 auto;
+  width: 0;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/numeric.js]: Why is `width=0`  here? What happens with `width=auto`?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

**Comment by swissspidy** [comment]
@obetomuniz cannot reproduce  the tooltip issue anymore either 👍

File: assets/src/edit-story/components/form/numeric.js (hunk 2 above)
Comment (obetomuniz) [reply assets/src/edit-story/components/form/numeric.js]: It's a CSS Hack to make Firefox work with inputs controlled by `display: flex` correctly. `auto` doesn't work, but I replace it by `min-width: 0` to avoid set `width` with non-sense value.

**Review by dvoytenko — APPROVED** [review]
