### PR TITLE
Suppress key listener when on clickable target

### LINKED ISSUE #4239: A11y: Always allow enter to activate links and buttons
## Bug Description

We have a global listener for <kbd>enter</kbd> that disables pressing links and buttons as default browser behavior. 

In the editor, we have circumvented this by manually listening for <kbd>enter</kbd> keypress, but this happens in too many places and we can't do this for WP built-in functionality.

We need to make the <kbd>enter</kbd> keypress listener conditional upon whether the current focus is on a link or a button.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Summary

This fixes the global <kbd>enter</kbd> listener on the canvas to ignore instances where the focus is on a clickable target - in such a case we need browser default behaviour to kick in instead.

Also, this behaviour was manually re-implemented in a number of components using an explicit listener - this has now been removed (leading to a net reduction of code in this PR - yay 🎉 ).

This makes sure that all clickable targets can be correctly clicked using the keyboard - and, in particular, ensures that all WP links (in the menu and topbar) can be correctly navigated.

**NB:** @miina did [suggest this](https://github.com/google/web-stories-wp/pull/2879#discussion_r450094108) when I implemented the feature in the first place, but I somehow assumed it to be harder to do than it was. 🙇  

## Relevant Technical Choices

* Add new `clickable` flag to event listener logic, defaulting to `true`
* If false, ignore clickable targets (buttons, links, some inputs) when assigning the listener

## To-do

* We could potentially add checks for clickable roles (`button`, `option`, `menuitem`), but I'm not sure it's necessary.

## User-facing changes

* WP menu options in can now be navigated to using keyboard

## Testing Instructions

1. Tab to a menu item in the WP left-hand menu.
1. Press enter to navigate to the link target and observe that something actually happens (whereas before, nothing happened)

Fixes #4239

### CODE REVIEW

File: assets/src/edit-story/components/keyboard/index.js [hunk 1]
```diff
@@ -39,6 +39,15 @@ const NON_EDITABLE_INPUT_TYPES = [
   'reset',
   'hidden',
 ];
+const CLICKABLE_INPUT_TYPES = [
```
Comment (miina) [inline assets/src/edit-story/components/keyboard/index.js:42]: Should the `NON_EDITABLE_INPUT_TYPES` perhaps just be `[ ...CLICKABLE_INPUT_TYPES, 'hidden']`?

File: assets/src/edit-story/components/form/switch.js [hunk 2]
```diff
@@ -124,12 +124,10 @@ function Switch({ value, disabled, onChange, onLabel, offLabel }) {
     [onChange]
   );
   const ref = useRef();
-  useKeyDownEffect(
-    ref,
-    ['space', 'enter', 'left', 'right'],
-    () => handleChange(!value),
-    [handleChange, value]
-  );
+  useKeyDownEffect(ref, ['left', 'right'], () => handleChange(!value), [
```
Comment (miina) [inline assets/src/edit-story/components/form/switch.js]: This now wouldn't change the value on `Enter`/`Space`, is that intended?

**Review by miina — COMMENTED** [review]
One thing I noticed when testing:
The bold-italic-underline do not work with `Space` nor `Enter`, also seeing this in console:
Screenshot 2020-08-27 at 14 01 22

Perhaps not related to this PR though.

File: assets/src/edit-story/components/keyboard/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/keyboard/index.js:42]: Hm, not sure. Is it an either/or - either an input field is clickable or it's editable (or none of them, `hidden`)? Can that be considered a _universal truth_ about inputs?

File: assets/src/edit-story/components/form/switch.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/form/switch.js]: <kbd>space</kbd> already worked even without this handler as it was default behavior. After this fix, <kbd>enter</kbd> also works by browser default behavior. This is according to my tests at least, are you experiencing otherwise?

Comment (miina) [reply assets/src/edit-story/components/form/switch.js]: Correct, neither of these seem to work when testing in Chrome.

Comment (barklund) [reply assets/src/edit-story/components/form/switch.js]: You're right, reverted in 78a23aec4.

File: assets/src/edit-story/components/keyboard/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/keyboard/index.js:42]: Looking further into this, a counter-example would be `<input type="date" />` - it seems to me to be both _clickable_ and _editable_.

So I'll leave this as-is for now.

File: assets/src/edit-story/components/form/toggleButton.js [hunk 3]
```diff
@@ -110,12 +110,8 @@ function ToggleButton({
   ...rest
 }) {
   const toggle = () => onChange(!value);
-
-  // We unfortunately have to manually assign this listener, as it would be default behaviour
-  // if it wasn't for our listener further up the stack interpreting enter as "enter edit mode"
-  // for text elements. For non-text element selection, this does nothing, that default beviour
-  // wouldn't do.
   const inputRef = useRef();
+  // <enter> doesn't normally toggle checkboxes, but we'd like it to
```
Comment (barklund) [inline assets/src/edit-story/components/form/toggleButton.js:114]: @miina, TIL that checkboxes aren't normally toggled by pressing <kbd>enter</kbd>. But we'd like it to with our buttons (as they're more like _buttons_ than _inputs_), so re-adding the handler here.

**Comment by barklund** [comment]
> The bold-italic-underline do not work with `Space` nor `Enter`

@miina, I'm pretty sure they worked with <kbd>space</kbd>. At least they do for me. Regarding <kbd>enter</kbd>, see [this comment](https://github.com/google/web-stories-wp/pull/4250#discussion_r478731088).

> Also seeing this [error] in console

Hm, not able to reproduce. I don't think it's related to this PR.

**Review by miina — APPROVED** [review]

**Comment by miina** [comment]
>>The bold-italic-underline do not work with Space nor Enter

>@miina, I'm pretty sure they worked with space. At least they do for me

Working ok for me now, too.

**Comment by csossi** [comment]
Verified in QA
