### PR TITLE
FTUE: Find missing 'done' svg

### LINKED ISSUE #6850: FTUE: Done SVG has disappeared
## Bug Description

The SVG that shows up in the help center when all tips are read has disappeared. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Done checkmark was missing in the FTUE help center.

## Summary

Updates the colors for the paths in the svg.

## Relevant Technical Choices

Importing the svg changes all the `stroke` and `fill` attributes to `currentColor`, so each part of the svg was inheriting the same `color`.
Screen Shot 2021-03-19 at 1 32 46 PM

I couldn't figure out how to import the svg without the svg having its `stroke` and `fill` changed to `currentColor`, so I decided to style it directly through the styled component.

If somebody knows how to change this lmk!

## To-do

none

## User-facing changes

|Before|After|
|--|--|
|image|image|

## Testing Instructions

1. go to editor
2. open help center for ftue
3. click the last tip, then click through until you get to the end. Should see the svg

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. go to editor
2. open help center for ftue
3. click the last tip, then click through until you get to the end. Should see the svg

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6850

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
lgtm. this is the only way I could think of doing it too. I think it's one of the limitations of using `.svg` files with the loader vs just making them react components manually 🤷

**Review by embarks — APPROVED** [review]
oops! nice one.

**Comment by swissspidy** [comment]
> I couldn't figure out how to import the svg without the svg having its stroke and fill changed to currentColor, so I decided to style it directly through the styled component.
> 
> If somebody knows how to change this lmk!

If they are in an `images` folder this won't happen.

So `icons` -> colors are  normalized to `currentColor`
`images` -> colors are kept.

Styling via styled component is preferred though :)

`images` folder is more a workaround to support colors and gradients in SVGs like the Web Stories logo.

See #6361 #6357 for context

File: assets/src/edit-story/components/helpCenter/quickTip/index.js [hunk 1]
```diff
@@ -73,8 +73,14 @@ const DoneContainer = styled.div`
...
   height: 180px;
   margin-bottom: ${GUTTER_WIDTH}px;
+  color: #f4f2ef;
+
   svg {
     display: block;
+
+    path {
+      color: #4285f4;
+    }
```
Comment (swissspidy) [inline assets/src/edit-story/components/helpCenter/quickTip/index.js:83]: Should these come from the theme?

Comment (samwhale) [reply assets/src/edit-story/components/helpCenter/quickTip/index.js:83]: These colors don't exist anywhere else except for this svg 😞. I don't think we should add these to the design system until they're needed more than once.

This is why I wanted these colors to be applied to the svg without styled components since the colors are strange and don't belong in the design system 🤔 Happy to do either way though.

Comment (swissspidy) [reply assets/src/edit-story/components/helpCenter/quickTip/index.js:83]: Worth clarifying with UX then to see whether this is expected or if this is an oversight and the color should be changed to something that already exists.

Comment (swissspidy) [reply assets/src/edit-story/components/helpCenter/quickTip/index.js:83]: At least `#4285f4` is/was used/defined in `edit-story` in a few places, so perhaps it needs to be replaced with something newer.
