### PR TITLE
Performance & aesthetic improvements for drop targets

### LINKED ISSUE #634: Elements with links stop being drop targets
## Bug Description

As soon as you attach a link to an element, it stop being a drop target.

## Expected Behaviour

Elements with links should be drop targets, just as others.

## Steps to Reproduce

Add a link to a shape. Try dragging an image into it now.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #635: Fix flickery behavior for clicked elements in the workspace
## Bug Description

More and more, we have a problem with the "mousedown" state of elements in the workspace. Clicking on an element results in flickery UX, because you see the guidelines (and now help text for drop targets) for a split second, and then they're gone again. 

## Expected Behaviour

When clicking an element, none of the UI around it should flicker (show for a split second).

We can solve this in two ways: Add a delay (~100-200ms?) to not have them appear immediately, or only show them after dragging for ~1px. in jQuery UI's draggables, I usually resorted to a combination of both, but often the 'distance' based option (1px) is enough.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #642: Drop Targets: the blue indication area prevails after dropping
## Bug Description

After dropping into a target, the blue indication area remains until the block is selected/moved.

## Expected Behaviour

The indication area should stop displaying once the dropping is done.

## Steps to Reproduce

1. Add a Shape
2. Add an Image
3. Drop the Image to the Shape
4. See the Image displaying blue borders (the wide borders, see gif below).

## Screenshots

borders

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #645: Drop Targets: Outline of the selected element visible even if not a target
## Bug Description

When drop targets are displayed on a Page with a note that drop targets have blue outline around them, the selected element displays the blue outline regardless of being a drop target or not.

## Expected Behaviour

Only drop targets should have blue outline when dragging.

## Steps to Reproduce

1. Add a Text block.
2. Select the Text block.
3. Start dragging an Image from the Media Library onto the Page.
4. See the blue outline around the Text (which is not a drop target).
 

## Screenshots
deceiving-outline

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #647: Media not always entering the edit mode
## Bug Description

In some cases (seems to depend on the size of the image element since the edges seem to not react to double-click) the image does not go into edit mode.

Might be related to Drop Target indicator highlights (the blue wide outline on top of media)

## Expected Behaviour

Media should always enter edit mode on double-click

## Steps to Reproduce

1. Add on image
2. Resize it to be quite small.
3. Try to go to edit mode via double click

## Screenshots

See how resizing the image to be larger enables the edit mode again.
edit-mode

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
Closes #645 
Closes #642 
Closes #635
Closes #647 
Closes #634 

### Changes
- Improves the styling of the text hint as discussed with @samitron7 (centered, more transparent, hides 
- Prevent the hint from showing unless there are drop targets on the page #645
- Fixes an error that caused the blue outline to prevail after dropping #642
- Fixes warning about updating the state of an unmounted element (temporary workaround)
- Fixes styling issue that prevented media from entering the edit mode #647 
- Smoother transitions while dropping images, prevents flicker as the element gets replaced
- Fix drop targets and editing not working on elements that have links #634 
- Fix flickery behavior for clicked elements in the workspace #635

### CODE REVIEW

**Comment by miina** [comment]
@wassgha 
From testing:
Still seeing #645 -- when dragging an image, a previously selected Text box still has the selection outline which is also blue and isn't distinguished from the drop targets.

642 and 647 seem to work well now 👍

File: assets/src/edit-story/components/canvas/displayElement.js [hunk 1]
```diff
@@ -112,9 +116,13 @@ function DisplayElement({ element }) {
         }}
       >
         <Display element={element} box={box} />
-        {replacementElement && (
-          <Replacement element={replacementElement} box={box} />
-        )}
+        <ReplacementContainer
+          style={{ opacity: Boolean(replacementElement) ? 1 : 0 }}
```
Comment (miina) [inline assets/src/edit-story/components/canvas/displayElement.js]: Could we add the style to the styled `ReplacementContainer` above?

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 2]
```diff
@@ -161,6 +161,10 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
       resizable={actionsEnabled && !isDragging}
       rotatable={actionsEnabled && !isDragging}
       onDrag={({ target, beforeTranslate, clientX, clientY }) => {
+        if (!isDragging) {
```
Comment (miina) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js:177]: Curious, why didn't setting it `onDragStart` work?

File: assets/src/edit-story/masks/frame.js [hunk 3]
```diff
@@ -91,10 +81,14 @@ function WithDropTarget({ element, children, hover }) {
         width="100%"
         height="100%"
         preserveAspectRatio="none"
+        style={{
+          // Fixes issue where the outline prevents double-clicks from
+          // reaching the frame:
+          zIndex: activeDropTargetId === element.id ? 1 : -1,
```
Comment (miina) [inline assets/src/edit-story/masks/frame.js]: Let's assign style in `styled` `DropTargetSVG` above.

File: assets/src/edit-story/masks/frame.js [hunk 4]
```diff
@@ -121,6 +115,9 @@ function WithDropTarget({ element, children, hover }) {
           strokeLinecap="round"
           strokeLinejoin="round"
           d={mask?.path}
+          style={{
+            opacity: activeDropTargetId === element.id ? 0.3 : 0,
```
Comment (miina) [inline assets/src/edit-story/masks/frame.js]: Ditto.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 2 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js:177]: It does but `onDragStart` is called when the element is clicked without dragging which causes the dnd UI to preemptively show up (see #635), it's more like an `onMouseDown` rather than `onMouseUp`

File: assets/src/edit-story/components/canvas/framesLayer.js [hunk 5]
```diff
@@ -88,20 +93,15 @@ function FramesLayer() {
...
-                  'web-stories'
-                ),
-                prettifyShortcut('mod')
-              )}
-            </Hint>
-          </FrameSidebar>
-        )}
+        {Boolean(draggingResource) &&
+          isDropSource(draggingResource.type) &&
+          Object.keys(dropTargets).length && (
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/framesLayer.js]: That needs to be `length > 0`, otherwise we will end up with `0` in the output. TBH I can never remember those rules beyond a basic `false` value, so I think this is just safer.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 6]
```diff
@@ -190,9 +190,11 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
           };
           updateSelectedElements({ properties });
           if (selectedElement.resource) {
-            handleDrop(selectedElement.resource, selectedElement.id);
+            await handleDrop(selectedElement.resource, selectedElement.id);
           }
         }
+        setIsDragging(false);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js]: Hmm. So, these are happening outside the event phase? Each of the ones below will force rerender thrashing. I recommend to create a simple reset callback using the `useBatchingCallback` and call it from `handleDrop().then()` to make it obvious.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 6 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: Done.

**Review by dvoytenko — APPROVED** [review]
