### PR TITLE
Skip AMP sanitization for missing video posters, accepting AMP invalidation

### LINKED ISSUE #5218: AMP Sanitization: Videos with missing poster images removed
## Bug Description

Splitting this out from #5142. We don't want to remove videos with missing poster images.

## Additional Context

- Plugin Version:  1.1
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Better to have an invalid AMP document rather than the video being stripped from the page

## To-do

* [x] Unit tests

## User-facing changes

Videos without posters should not be removed

## Testing Instructions

1. Upload new video via "Upload" button or by dragging
1. Preview story right away
1. Notice that there is a video visible
1. Check source code and noticed that the `<amp-video>` element does not have a `poster` attribute

---

Fixes #5218

### CODE REVIEW

File: includes/Story_Post_Type.php [hunk 1]
```diff
@@ -523,6 +526,11 @@ public function filter_amp_story_element_validation_error_sanitized( $sanitized,
 			return false;
 		}
 
+		// Skip sanitization for missing vide posters.
```
Comment (dreamofabear) [inline includes/Story_Post_Type.php]: Nit: video

File: includes/Story_Post_Type.php [hunk 2]
```diff
@@ -523,6 +526,11 @@ public function filter_amp_story_element_validation_error_sanitized( $sanitized,
...
+		if ( isset( $error['node_name'] ) && 'amp-video' === $error['node_name'] ) {
```
Comment (dreamofabear) [inline includes/Story_Post_Type.php:530]: As a follow-up, we should at least extend this to all `amp-*` elements.

It's ok for sanitization to remove HTML added by other plugins, but it should never remove elements added by our own editor.

**Review by dreamofabear — APPROVED** [review]

File: includes/Story_Post_Type.php (hunk 2 above)
Comment (swissspidy) [reply includes/Story_Post_Type.php:530]: I will create a new ticket for discussing this.

Comment (swissspidy) [reply includes/Story_Post_Type.php:530]: #5226
