### PR TITLE
Use SAT for detecting lasso collision with elements

### LINKED ISSUE #1481: Lasso selection not accurate with rotated elements
## Bug Description

Lasso selection doesn't seem to select the elements accurately when the elements are rotated.
This can sometimes become quite tricky to select specific elements among multiple elements if some of those are rotated -- unexpected elements are selected and expected elements can sometimes be left out.

## Expected Behaviour

Lasso selection should select the elements that visually get covered by the lasso selection.

## Steps to Reproduce
1. Add a text element, with background color for better visibility.
2. Rotate the element.
3. Use lasso selection in the uncovered place where the element would be in case of not being rotated
4. See the element being selected even though based on what's visually seen, it shouldn't.
5. Try the same with selecting the tip of the rotated element (e.g. place that would be empty if the element wouldn't be rotated)
6. See the element not getting selected even though based on what's visually seen, it should.

See the gifs below

## Screenshots
lasso2
lasso

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #2215: Unclear lasso selection, not sure how to select the elements.
## Bug Description

See video, it's unclear to me why sometimes the top text element is being selected and in others it is not, even if my lasso selection in both cases touches the element. Unclear why it works sometimes and sometimes it doesn't. 

Related: #1782

## Expected Behaviour

It should consistently select the element if in the lasso selection area.

## Screenshots

[Lasso selection not clear.zip](https://github.com/google/web-stories-wp/files/4725108/Lasso.selection.not.clear.zip)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Improves lasso selection by using the Separating Axis Theorem for detecting if an element was inside the lasso selection or not.

## User-facing changes
- Lasso selection now works correctly for rotated elements, too.

## Testing Instructions
1. Add a few elements, rotate some of those, too.
2. Now test out selecting different combinations of elements using lasso selection
3. Verify that the elements are selected correctly, e.g. even if only a corner of a rotated element stays inside the lasso selection.

---

Fixes #2215 
Fixes #1481

### CODE REVIEW

File: assets/src/edit-story/components/canvas/selectionCanvas.js [hunk 1]
```diff
@@ -171,6 +172,21 @@ function SelectionCanvas({ children }) {
...
+      bottomRightPoint,
+      bottomLeftPoint,
+    } = getCorners(rotationAngle, x, y, width, height);
+    return new SAT.Polygon(new SAT.Vector(), [
+      new SAT.Vector(topLeftPoint.x, topLeftPoint.y),
+      new SAT.Vector(bottomLeftPoint.x, bottomLeftPoint.y),
+      new SAT.Vector(bottomRightPoint.x, bottomRightPoint.y),
+      new SAT.Vector(topRightPoint.x, topRightPoint.y),
+    ]);
+  }, []);
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/selectionCanvas.js]: This can just be moved out to a helper function - doesn't need to be inlined and redefined here every time this component initializes.

File: assets/src/edit-story/components/canvas/canvasProvider.js [hunk 2]
```diff
@@ -121,21 +121,6 @@ function CanvasProvider({ children }) {
...
-        .filter(({ x, y, width, height }) => {
-          return (
-            x <= lx + lw && lx <= x + width && y <= ly + lh && ly <= y + height
-          );
-        })
-        .map(({ id }) => id);
-      setSelectedElementsById({ elementIds: newSelectedElementIds });
-    },
-    [currentPage, setSelectedElementsById]
-  );
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/canvasProvider.js]: Hm, I still think it would be nicer to have the function defined here - or in a reusable hook. This function signature still has all the information needed to do the calculation here, no?

**Review by barklund — COMMENTED** [review]
Do we need to move it to the canvas component?

File: assets/src/edit-story/components/canvas/canvasProvider.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/canvasProvider.js]: @barklund PTAL again.

**Comment by swissspidy** [comment]
> **Size Change:** +4.69 kB (0%)
> 
> **Total Size:** 1.56 MB
> 
> Filename	Size	Change
> `assets/js/edit-story.js`	598 kB	+2.5 kB (0%)
> `assets/js/stories-dashboard.js`	683 kB	+2.18 kB (0%)
> ℹ️ **View Unchanged**
> [compressed-size-action](https://github.com/preactjs/compressed-size-action)

Why does this new dependency affect the dashboard too? 🤔

**Comment by miina** [comment]
> Why does this new dependency affect the dashboard too?

Hm, I suppose Dashboard is importing something from the Workspace that is using `useCanvas` which makes it importing `sat`. Tried to check quickly but didn't see right away what it could be.

File: package.json [hunk 3]
```diff
@@ -66,6 +66,7 @@
     "react-transition-group": "^4.4.1",
     "react-virtual": "^2.3.2",
     "resize-observer-polyfill": "^1.5.1",
+    "sat": "^0.8.0",
```
Comment (barklund) [inline package.json:69]: I just want @swissspidy's 👍   on [this package](https://github.com/jriecken/sat-js). It's MIT-licensed and seems respectable.

**Review by barklund — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
