### PR TITLE
KSES: Extend allowlist to fix templates usage

### LINKED ISSUE #9227: Templates: Elements stripped by KSES
## Bug Description

I was notified that some of the templates, for example the Summer Fashion one, are broken for users without `unfiltered_html` capabilities. KSES is stripping lots of content there.

## Expected Behaviour

The templates should be usable for authors.

## Steps to Reproduce

1. Log in as author
2. Create a new story from the Summer Fashion template
3. Preview story
4. See broken content

## Screenshots

<table>
<tr>
	<td>Actual
	<td>Expected
<tr>
	<td>Actual result
	<td>Expected appearance
</table>

## Additional Context

- Plugin Version: 1.11.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Templates like the Summer Fashion one were broken when used by a user without `unfiltered_html` capabilities.

## Summary

Extend KSES allowlist to fix templates usage for these users.

## User-facing changes

<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td>Actual result
	<td>Expected appearance
</table>

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Log in as author
2. Create new story from Summer Fashion template
3. Preview story
4. Verify that the preview looks (roughly?) like in the screenshots and there are no broken elements or animations
5. Repeat with 2-3 other templates from the newer ones

### Does this PR have a security-related impact?

Hardening KSES

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9227

### CODE REVIEW

File: includes/KSES.php [hunk 1]
```diff
@@ -289,6 +290,8 @@ public function safecss_filter_attr( $css ) {
 				'overflow',
 				'vertical-align',
 				'list-style-type',
+
+				'z-index',
```
Comment (spacedmonkey) [inline includes/KSES.php:297]:
```suggestion
				'z-index',
```

Comment (swissspidy) [reply includes/KSES.php:297]: All the entries in this array are grouped. The extra newline is on purpose.

**Review by spacedmonkey — APPROVED** [review]
Approved with one nicpic.
