### PR TITLE
Help Center: Fix Arrow/All Tips style

### LINKED ISSUE #6348: FTUE: Update arrow color
## Bug Description

The arrow color in the main menu has been updated to `fg.secondary` in figma, currently they are white.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Context
The colors for the arrow/all tips button on the companion has been updated to `fg.secondary`

## Summary
- Adds the secondary text color to the All Tips button and arrow as shown in Figma

## Relevant Technical Choices
⌨️

## User-facing changes

**figma**
Screen Shot 2021-02-23 at 4 37 28 PM

**before**
Screen Shot 2021-02-23 at 4 29 27 PM
**after**
Screen Shot 2021-02-23 at 4 30 10 PM

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open a new story or edit a story
2. Open the quick tips menu and select any tip
3. Assure that the All Tips button and arrow have the color `#ADB1B3` 

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6348

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]

File: assets/src/edit-story/components/helpCenter/navigator/bottomNavigation.js [hunk 1]
```diff
@@ -113,7 +117,7 @@ export function BottomNavigation({
           <ArrowWrap isRTL={isRTL}>
             <Icons.ArrowLeft />
           </ArrowWrap>
-          <span>{__('All Tips', 'web-stories')}</span>
+          <span css={secondaryTextStyle}>{__('All Tips', 'web-stories')}</span>
```
Comment (samwhale) [inline assets/src/edit-story/components/helpCenter/navigator/bottomNavigation.js:120]: should this be `style`? I've never seen the css prop before. Does it work similarly?

Comment (BrittanyIRL) [reply assets/src/edit-story/components/helpCenter/navigator/bottomNavigation.js:120]: nit for sure but this feels like it might as well be `ArrowText` or something and then just 
```
const ArrowText = styled.span`color: theme.color...
```
 just for continuity.
