### PR TITLE
Autosave: trigger autosave regardless of being idle

### LINKED ISSUE #12809: Autosave triggers only after idling, not during editing
## Bug Description
When creating test stories, it happened a few times with various people that the editor crashed and no autosave had been created meanwhile, even though enough time had passed.

~It's not clear why / when this happens~

Autosave seems to wait for idling the specified autosave interval instead of triggering while editing. 

## Expected Behaviour
Auto-save should trigger every 60 seconds for drafts and published stories, regardless of idling.

## Steps to Reproduce
1. Continue making some changes to a story and avoid idling for 60 seconds 
2. See the autosave not happening even when there are new changes

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by miina**
## Summary
Removes autosave deps from `story` and `pages` which resulted in autosave being triggered only when idle for the time of the interval.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a story
2. Continue making edits for 60 seconds
3. Verify the autosave triggers without having to be idle for 60 seconds
4. Try once more (without refreshing) to ensure it triggers more than once.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12809

### CODE REVIEW

File: packages/story-editor/src/components/autoSaveHandler/index.js [hunk 1]
```diff
@@ -30,13 +30,9 @@ function AutoSaveHandler() {
   const {
     state: { hasNewChanges },
   } = useHistory();
-  const { autoSave } = useStory(({ actions }) => ({
+  const { autoSave, isAutoSaving } = useStory(({ actions }) => ({
     autoSave: actions.autoSave,
   }));
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/autoSaveHandler/index.js]: `isAutoSaving` is not returned in story provider. If it was in would likely be in state right? So this should look like this. 

```
const { autoSave, isAutoSaving } = useStory(({ actions, state }) => ({
    autoSave: actions.autoSave,
    isAutoSaving: state.isAutoSaving
  }));
```

File: packages/story-editor/src/components/autoSaveHandler/index.js [hunk 2]
```diff
@@ -58,7 +54,7 @@ function AutoSaveHandler() {
     );
 
     return () => clearTimeout(timeout);
-  }, [autoSaveInterval, hasNewChanges, isUploading, story, pages]);
+  }, [autoSaveInterval, hasNewChanges, isUploading, isAutoSaving]);
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/autoSaveHandler/index.js]: Why do we need isUploading here?

Comment (swissspidy) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: Because we prevent saving while any upload is in progress. Always has been the case. Avoids saving data with half-finished uploads.

Comment (spacedmonkey) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: So to confirm, if a user uploads a video and it is transcoding, there will be no autosaves? If you upload say 5 videos, that could take a while. Maybe we could add a check to see if there an process media element on them. If not do an autosave.

Comment (swissspidy) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: Yes, but IIRC only if the video is uploaded to the canvas and not just the library.

Comment (spacedmonkey) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: Just asking, as if you transcoding video takes say, 5 minutes, then blocking autosaves for that time, that could be a serious problem.

Comment (swissspidy) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: Totally. We can discuss improving this in a new ticket if we can find a way to avoid saving data with half-finished uploads.

File: packages/story-editor/src/components/autoSaveHandler/index.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/components/autoSaveHandler/index.js]: Indeed 🤦

**Review by barklund — APPROVED** [review]

**Comment by swissspidy** [comment]
FYI there are some legit failing tests

**Review by spacedmonkey — APPROVED** [review]

**Comment by kkalarickal** [comment]
@miina @swissspidy - I could NOT see the autosaves triggering while doing edits under the 60 sec window.

There were 60 sec regular autosaves happening, but any changes made in bewteen those 60 secs were lost when I went back to dashboard and reopened the draft story.

I am checking the autosave frequency by looking for the following network call

Request URL: https://stories-qa-wordpress-amp.pantheonsite.io/wp-json/web-stories/v1/web-story/21254/autosaves/?_locale=user

In this screen shot the three times this was called was at exactly 60 sec intervals, even though I was making edits to the story in between.

**Comment by kkalarickal** [comment]
@miina -- could you confirm if I should be seeing more frequent network calls like this one each time I make an edit to the story? What other indicators are there to verify that autosaves are happening?

Request URL: https://stories-qa-wordpress-amp.pantheonsite.io/wp-json/web-stories/v1/web-story/21254/autosaves/?_locale=user

**Comment by miina** [comment]
> @miina -- could you confirm if I should be seeing more frequent network calls like this one each time I make an edit to the story? What other indicators are there to verify that autosaves are happening?

@kkalarickal The autosaves should be happening every 60 seconds only, not more frequently. However, they should happen while editing as well. Previously, every new edit delayed autosaving, meaning that the autosaving happened only after 60 seconds of being idle. Now, it should fire every 60 seconds if there are new changes.

Is that not what you are seeing when testing? 🤔

**Comment by kkalarickal** [comment]
No. I am not seeing the `wp-json/web-stories/v1/web-story/21254/autosaves/?_locale=user` firing less than 60 sec interval. Also, if I make some edits and before the 60 sec autosave, if I go to dashboard and come back to the story, I am not seeing my last changes.

**Comment by swissspidy** [comment]
@kkalarickal The interval should not change, it's still 60 seconds (or whatever has been configured)

What changed here is that you should see autosaves _while making changes_.

**Before:** Autosave happens only after 60 seconds of doing nothing

**Now:** Autosave happens every 60 seconds _even if you continuously make edits_

**Review by swissspidy — APPROVED** [review]

**Comment by miina** [comment]
> No. I am not seeing the `wp-json/web-stories/v1/web-story/21254/autosaves/?_locale=user` firing less than 60 sec interval. Also, if I make some edits and before the 60 sec autosave, if I go to dashboard and come back to the story, I am not seeing my last changes.

This is all expected. As Pascal mentioned, there is no change to the 60 seconds interval. Let me know if there's still more information needed.
