### PR TITLE
Alignment text element while editing

### LINKED ISSUE #1483: Aligning element while editing text crashes the editor
## Bug Description

Clicking on an element alignment trigger while in text edit mode crashes the editor. 

## Expected Behaviour

Element should be properly aligned within the page. Editor should not crash. 

## Steps to Reproduce

1. Add a text element to the page
2. Double click to enter text editing mode, maybe select a word/subset of the text, not sure if it matters. 
3. Click on the element align options (e.g., alight right)

## Screenshots

Video attached
[Align element while in text edit mode crashes editor.zip](https://github.com/google/web-stories-wp/files/4576950/Align.element.while.in.text.edit.mode.crashes.editor.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ndev1991**
## Summary

Fixes #1483 
Fix crashes of alignment text element while editing.

## Relevant Technical Choices

Updatecontent has x and y as it's dependency which causing endless looping while the x or y updated through outside like element alignment. Removed x and y dependency.

## To-do

---
- [X] Alignment text element while editing should work.
- [X] Other features with design panel should work while editing text.
- [X] Edit text should work for content and height update.

Fixes #1483

### CODE REVIEW

File: assets/src/edit-story/elements/text/edit.js [hunk 1]
```diff
@@ -121,9 +121,14 @@ function TextEdit({
   const wrapperRef = useRef(null);
   const textBoxRef = useRef(null);
   const editorRef = useRef(null);
+  const boxRef = useRef();
   const contentRef = useRef();
   const editorHeightRef = useRef(0);
 
+  useEffect(() => {
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/text/edit.js:130]: Can you add a comment why this is done. That's an acceptable fix for a loop. We just need to make it clear. Also, wouldn't we need to do the same for `height`? It's also updated right next to `x` and `y`.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/elements/text/edit.js (hunk 1 above)
Comment (ndev1991) [reply assets/src/edit-story/elements/text/edit.js:130]: Correct. `x`, `y`, `height`, `rotationAngle` should be included. `updateContent` needs to be called on unmount. To prevent unnecessary `updateContent` calling move the dependency values to `boxRef`

**Review by dvoytenko — APPROVED** [review]
