### PR TITLE
Links: ability to clear link and brand icon

### LINKED ISSUE #711: Links: Cannot remove brand icon
## Bug Description

If I accidentally add the wrong image as the brand icon for a link, I can only replace the image, but not remove it again.

## Expected Behaviour

I'd expect a way to remove the brand icon again because it is optional and I might not have a suitable icon.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #911: Unable to remove a link added previously
## Bug Description

Clear actions of the `Web address` field in the Link Panel is not removing the link from the Workspace and not persisting the data if you save.

## Expected Behaviour

Pressing the clear button (e.g. X button) or deleting all text content of the `Web address` field should clear the link metadata from the Link panel and Canvas. If the user saves the Story after clear a link of a given element, the user should not see that link again anywhere.

## Steps to Reproduce

1. Create a Story
2. Add an Image to the Story workspace
3. Select the image added in step 2 and go to the Link panel
4. Add a VALID link in the the `Web address` field and Save the Story
5. Clear the `Web address` field in the Link panel pressing the X button or deleting all content of the field.
6. Save the Story and reload the page. The link still will be there. 

## Screenshots

Kapture-2020-03-31-at-16 30 13

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
## Merge after #1152 

Closes #711
Closes #911

### Changes
- Fixes bug that used to prevent clearing links
- Adds a button to clear the link brand icon

### CODE REVIEW

File: assets/src/edit-story/components/panels/link/index.js [hunk 1]
```diff
@@ -150,73 +154,61 @@ function LinkPanel({ selectedElements, pushUpdateForObject }) {
...
 
-      {Boolean(link.url) && link.type === LinkType.TWO_TAP && (
+      {Boolean(link.url) && (
         <Row>
           <ExpandedTextInput
             placeholder={__('Optional description', 'web-stories')}
             disabled={!canLink}
-            onChange={(value) => handleChange({ desc: value })}
+            onChange={(value) =>
+              handleChange({ desc: value }, !value /* submit */)
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/link/index.js:181]: Hmm. Do we really need this for `desc`?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/panels/link/index.js (hunk 1 above)
Comment (wassgha) [reply assets/src/edit-story/components/panels/link/index.js:181]: I think it makes sense to see the description cleaned immediately, no?

Comment (dvoytenko) [reply assets/src/edit-story/components/panels/link/index.js:181]: Yeah. I think you're right.

**Review by dvoytenko — APPROVED** [review]
