### PR TITLE
Media: Don't set transcoding state for non-videos

### LINKED ISSUE #10301: Media: Transcoded asset hang and never complete
## Bug Description

Found as part of testing https://github.com/google/web-stories-wp/pull/10001. 

Transcoded videos, sometimes hang and never complete. The save button does is disable as well. 

Possibly related to https://github.com/google/web-stories-wp/pull/9999

## Steps to Reproduce

1. Create story. 
2. Drag 5 images into canvas. 
3. Drag 5 videos into canvas. 

See video 

## Screenshots

https://user-images.githubusercontent.com/237508/150521275-dd2e9b09-eb9f-484a-a36f-2dc921525586.mov

## Additional Context

- Plugin Version: 17.0.0-alpha
- WordPress Version: 5.8/5.9RC3
- Operating System: Mac OS
- Browser: Chrome / Safari

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

When uploading asset, you upload images first and the video, videos will never process. This is because, images are added to the `currentTranscodingItem` ref and NEVER cleared. It would always hang. 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create story.
2. Drag 5 images into canvas.
3. Wait for images to upload complete. 
4. Drag 5 videos into canvas.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10301

### CODE REVIEW

File: packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js [hunk 1]
```diff
@@ -482,24 +482,26 @@ function useMediaUploadQueue() {
...
                 return;
               }
 
               if (muteVideo) {
+                currentTranscodingItem.current = id;
                 muteVideoItem(item);
                 return;
               }
 
+              currentTranscodingItem.current = id;
```
Comment (swissspidy) [inline packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js]: Just having it once here on line 492 would work too, instead of repeating this 3 times.

```suggestion
            if (canTranscodeFile(file)) {
              currentTranscodingItem.current = id;

              if (trimData) {
                trimVideoItem(item);
                return;
              }

              if (muteVideo) {
                muteVideoItem(item);
                return;
              }

```

**Review by swissspidy — APPROVED** [review]
The part about uploading images first was key! Good catch!

Some tests to prevent regressions would be a bonus, but not a requirement

File: packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js (hunk 1 above)
Comment (spacedmonkey) [reply packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js]: That would not include gif conversion?

Comment (spacedmonkey) [reply packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js]: I find this version much more readable. 

If you want a one line fix. This would work as well. 

```
          currentTranscodingItem.current = null;
          uploadItem(item);
```

Comment (swissspidy) [reply packages/story-editor/src/app/media/utils/useMediaUploadQueue/index.js]: No, your change for gif conversion above would stay.

This is just for video optimization.

So two lines changed in total.
