### PR TITLE
Use portal for Calendar

### LINKED ISSUE #788: Document Panel: Calendar partly hidden for narrow screens
## Bug Description
Follow up from #667 

On narrow screens, the calendar displayed for the Publish date is partly not visible.

## Expected Behaviour

The calendar should be fully visible on narrow screens.

## Screenshots

Screenshot 2020-03-26 at 11 17 21

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fixes #788

### CODE REVIEW

File: assets/src/edit-story/components/form/dateTime/index.js [hunk 1]
```diff
@@ -18,12 +18,11 @@ import DatePicker from './datePicker';
 const DateTimeWrapper = styled.div`
   position: absolute;
   top: 0;
-  left: -15px;
+  left: 0;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dateTime/index.js]: Is a `position:absolute` wrapper still useful here with a popup?

File: assets/src/edit-story/components/inspector/document/publish/index.js [hunk 2]
```diff
@@ -183,14 +179,14 @@ function PublishPanel() {
         </StyledButton>
       </Row>
       {showDatePicker && (
-        <DateTimeWrapper>
+        <Popup root={dateFieldNode.current}>
```
Comment (dvoytenko) [inline assets/src/edit-story/components/inspector/document/publish/index.js]: This is often called `anchor` and we should pass the `ref` itself here.

File: assets/src/edit-story/components/popup/index.js [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+import styled from 'styled-components';
+
+/**
+ * Internal dependencies
+ */
+import { ADMIN_TOOLBAR_HEIGHT } from '../../constants';
+
+const DEFAULT_WIDTH = 270;
+
+const PopUp = styled.div`
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Nit: let's call this a `Container` or a `Wrapper`.

File: assets/src/edit-story/components/popup/index.js [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+  position: absolute;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: `position:fixed`?

File: assets/src/edit-story/components/popup/index.js [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+  z-index: 999;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Let's up to the max. Or max-1.

File: assets/src/edit-story/components/popup/index.js [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+  top: ${({ y }) => `${y}px`};
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Sometimes it's more convenient to do `right` and `bottom` - it depends on the caller's preference and current screen position. Let's go with the most convenient method for your case and just keep in mind that this may need to be expanded.

File: assets/src/edit-story/components/popup/index.js [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+  left: ${({ x }) => `${x}px`};
+  width: ${({ width }) => width}px;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js:32]: There always has to be a max-height. For now we can start with a constant.

File: assets/src/edit-story/components/popup/index.js [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+`;
+
+function Popup({ root, children, width = DEFAULT_WIDTH }) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Let's rename `root` to anchor or such and do `ref`.

File: assets/src/edit-story/components/popup/index.js [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+  const nodeRect = root.getBoundingClientRect();
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: This should be done via layout effect. We have to options: either putting the placement params into the state, or just updating inline style manually. Either is ok for portals, imho, b/c this is purely side-effect function. For instance:

```
useLayoutEffect(() => {
  function positionPopup() {
    const anchorRect = anchor.current.getBoundingClientRect();
    const bodyRect = document.body.getBoundingClientRect();
    // ... the math
    popupRef.current.style.width = `...`;
    // or 
    setPopupState({width: ...});
  };
  positionPopup();

  // But you will also need resize handler and ideally also scroll handler.
  window.addEventListener('resize', positionPopup);
  // Scroll handler here does "capture". This will reposition popup if the design panel is scrolled.
  document.addEventListener('scroll', positionPopup, true);
  return () => {
    window.removeEventListener('resize', positionPopup);
    document.removeEventListener('scroll', positionPopup, true);
  };
}, [anchor, width, ...])
```

File: assets/src/edit-story/components/popup/index.js [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+  const bodyRect = document.body.getBoundingClientRect();
+
+  // Note: This displays the popup right under the node, currently no variations implemented.
+  const nodeOffset = {
+    x: nodeRect.left - bodyRect.left - width + nodeRect.width,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: I think with position:fixed this will be different/simpler. Something like this:

```
x = Math.min(desiredX, maxX)
desiredX = nodeRect.left
maxX = bodyRect.right - width
```

File: assets/src/edit-story/components/popup/index.js [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+    y: nodeRect.top - bodyRect.top + nodeRect.height + ADMIN_TOOLBAR_HEIGHT,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: I think with `position:fixed` you won't need `ADMIN_TOOLBAR_HEIGHT`.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/popup/index.js (hunk 11 above)
Comment (miina) [reply assets/src/edit-story/components/popup/index.js]: Indeed!

File: assets/src/edit-story/components/popup/index.js (hunk 6 above)
Comment (miina) [reply assets/src/edit-story/components/popup/index.js]: The `right` value from `getBoundingClientRect` from the `anchor` seems a bit unexpected, I might be missing something of course since I've mostly been using `top` and `left` as a preference.

The `anchorRect.right` value gives me quite a large value which sends the popup to the left edge of the screen. I can look into it again tomorrow to understand why it is as it is, but left it currently using `top` and `left` until then.

**Comment by miina** [comment]
Note: this PR would supersede #935

File: assets/src/edit-story/components/popup/index.js (hunk 6 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/popup/index.js]: The `DOMRect.right != css.right`. The `DOMRect.right == DOMRect.left + DOMRect.width`. So it's kind of useless. But `css.right` can be calculated simply as `css.right = bodyRect.right - nodeRect.right`, I think.

File: assets/src/edit-story/components/popup/index.js [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+    function positionPopup() {
+      const anchorRect = anchor.current.getBoundingClientRect();
+      const bodyRect = document.body.getBoundingClientRect();
+
+      // Note: This displays the popup right under the node, currently no variations implemented.
+      setPopupState({
+        width,
+        offset: {
+          x: anchorRect.left - bodyRect.left - width + anchorRect.width,
+          y: anchorRect.top + anchorRect.height,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Nit: this is `anoncrRect.bottom`

File: assets/src/edit-story/components/popup/index.js [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+  useLayoutEffect(() => {
+    function positionPopup() {
+      const anchorRect = anchor.current.getBoundingClientRect();
+      const bodyRect = document.body.getBoundingClientRect();
+
+      // Note: This displays the popup right under the node, currently no variations implemented.
+      setPopupState({
+        width,
+        offset: {
+          x: anchorRect.left - bodyRect.left - width + anchorRect.width,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Are you trying to align by the right edge? In either case, we still need to make sure that the resulting `x + width` does not go beyond `bodyRect.right`, otherwise it'll get clipped off on the right edge of the viewport.

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Looks great, but one more important nuance.

File: assets/src/edit-story/components/popup/index.js (hunk 12 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/popup/index.js]: Oops, this also might have a problem. The resulting `y + MAX_HEIGHT > bodyRect.bottom` - that would clip off the popup at the bottom of the screen. We probably have to switch to showing drop down above the anchor element in this case?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/popup/index.js (hunk 12 above)
Comment (miina) [reply assets/src/edit-story/components/popup/index.js]: Right, good point! _Checking..._

File: assets/src/edit-story/components/popup/index.js [hunk 14]
```diff
@@ -0,0 +1,75 @@
...
+import { useLayoutEffect, useState } from 'react';
+
+const DEFAULT_WIDTH = 270;
+const MAX_HEIGHT = 370;
+
+const Container = styled.div`
+  position: fixed;
+  z-index: 2147483646;
+  top: ${({ y }) => `${y}px`};
+  right: ${({ x }) => `${x}px`};
```
Comment (barklund) [inline assets/src/edit-story/components/popup/index.js]: As these values are continuously changing on scroll, they should be set using `style` rather than CSS class. Just moving them to an `.attrs()` above, should work:

```js
const Container = styled.div.attrs((x,y}) => ({
  style: { right: `${x}px`, top: `${y}px` },
}))`
```

**Review by barklund — COMMENTED** [review]
I tried limiting the popup to fit inside the viewport in #991, but not sure I like the result.

Otherwise, this looks good and works perfectly!

File: assets/src/edit-story/components/popup/index.js [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+function Popup({ anchor, children, width = DEFAULT_WIDTH, isOpen }) {
+  const [popupState, setPopupState] = useState(null);
+
+  useLayoutEffect(() => {
+    function positionPopup() {
+      const anchorRect = anchor.current.getBoundingClientRect();
+      const bodyRect = document.body.getBoundingClientRect();
+
+      // Note: This displays the popup right under the node, currently no variations implemented.
+      // @todo Needs to display above the anchor instead if possible in case of not having room below!
```
Comment (barklund) [inline assets/src/edit-story/components/popup/index.js:51]: Above wouldn't necessarily help. What if window height is less than `2*MAX_HEIGHT`? In #991 I tried keeping the overlay inside the viewport, but not sure I like it.

Comment (miina) [reply assets/src/edit-story/components/popup/index.js:51]: Hmm, not sure what's the best approach here. Should we perhaps consider the minimum supported height and ignore the issue if the window height is less?

Comment (dvoytenko) [reply assets/src/edit-story/components/popup/index.js:51]: There's a larger thread going here: https://github.com/google/web-stories-wp/pull/991#issuecomment-608090323. I think we should merge this PR and complete that discussion there. This is very mergeable already.

File: assets/src/edit-story/components/popup/index.js [hunk 16]
```diff
@@ -0,0 +1,75 @@
...
+          x: bodyRect.right - anchorRect.right,
+          y: anchorRect.bottom,
+        },
+      });
+    }
+    positionPopup();
+
+    // Adjust the position when scrolling or resizing.
+    window.addEventListener('resize', positionPopup);
+    document.addEventListener('scroll', positionPopup, true);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js:64]: An important optimization: with scroll we should ignore the target inside the popup itself because it doesn't affect the popup's position. Otherwise it could get very large number of events and re-renderings, since scrolling inside the popup is often exactly what we want. You can just declare `evt` inside the `positionPopup` and check that `!popupContainer.contains(evt.target)` when `evt` is available.

**Review by dvoytenko — APPROVED** [review]
I'm pretty much at LGTM. Just one more ask for optimization in scrolling. And @barklund's suggestion for the style is the right one as well. I think the responsive popup positioning should be deferred to a followup PR.
