### PR TITLE
Story Events:  propTypes typo

### LINKED ISSUE #11015: Code Quality: Invalid `propTypes` used in `storyEvents` components
## Bug Description

1.  `OutputStory` story component is being used as a prop type here

https://github.com/GoogleForCreators/web-stories-wp/blob/70c01146c40f8de8e36bd55ac8c44bc8ed949bb7/packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js#L24-L30

It doesn't throw any warnings/errors because of a typo in `propTypes` where `registerPropTypes` is being used

https://github.com/GoogleForCreators/web-stories-wp/blob/70c01146c40f8de8e36bd55ac8c44bc8ed949bb7/packages/story-editor/src/app/story/storyTriggers/storyEvents/onPageAddedRegister.js#L60

https://github.com/GoogleForCreators/web-stories-wp/blob/70c01146c40f8de8e36bd55ac8c44bc8ed949bb7/packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js#L49

If we try to fix this by passing `OutputStory.propTypes` as `currentStory` and `previousStory` in `registerPropTypes` and fix typo, we would see prop type warnings like these.

```js
Warning: Failed prop type: The prop `currentStory.story.title` is marked as required in `OnInitialElementAddedRegister`, but its value is `undefined`.

Warning: Failed prop type: The prop `currentStory.story.title` is marked as required in `OnPageAddedRegister`, but its value is `undefined`.

Warning: Failed prop type: The prop `isRequired` is marked as required in `OutputStory`, but its value is `undefined`.

Warning: Failed prop type: The prop `currentStory.metadata` is marked as required in `OnInitialElementAddedRegister`, but its value is `undefined`.
```

## Expected Behaviour

No warnings when `propTypes` typo is fixed

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

Proptype warnings were never showing due to a typo in propType vs propTypes. 

## Relevant Technical Choices
 Instead of reusing the `OutputStory` proptypes we only need a few props. So let's just check those ones instead.

## To-do
n/a

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11015

### CODE REVIEW

File: packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js [hunk 1]
```diff
@@ -17,7 +17,7 @@
  * External dependencies
  */
 import PropTypes from 'prop-types';
-import { OutputStory as storyPropType } from '@googleforcreators/output'; // @todo See issue #11015
+import { OutputStory as storyPropType } from '@googleforcreators/output';
```
Comment (maxyinger) [inline packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: are we using this file anywhere anymore? should we just delete this file if not?

File: packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js [hunk 2]
```diff
@@ -46,6 +46,18 @@ function OnInitialElementAddedRegister({ currentStory, dispatchStoryEvent }) {
...
+      pages: PropTypes.array,
+    }),
+  }),
+  prevStory: PropTypes.shape({
+    story: PropTypes.shape({
+      pages: PropTypes.array,
+    }),
+  }),
+  dispatchStoryEvent: PropTypes.func.isRequired,
+};
```
Comment (maxyinger) [inline packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js]: nit: should we maybe check that each page has an elements array since we're referencing that in the `isNewStory(...)` function?

**Review by maxyinger — APPROVED** [review]

File: packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js (hunk 1 above)
Comment (swissspidy) [inline packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: Why remove the todo? This still is incorrectly using a React component as a prop type.

Comment (BrittanyIRL) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: Looks like it's still getting used through `getStoryMarkup` which is in turn used in the `wp-story-editor` for status check as well as in the dashboard.

Comment (BrookeGraham) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: Oh yep I missed that.

Comment (maxyinger) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: ah bummer

Comment (BrookeGraham) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/propTypes.js]: These proptypes were only used in the two registers, `onInitialElementAddRegister` and `onPageAdded` so I removed this file since I updated those propTypes locally.

File: packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js [hunk 3]
```diff
@@ -46,6 +47,18 @@ function OnInitialElementAddedRegister({ currentStory, dispatchStoryEvent }) {
   return null;
 }
 
-OnInitialElementAddedRegister.propType = registerPropTypes;
+OnInitialElementAddedRegister.propTypes = {
+  currentStory: PropTypes.shape({
+    story: PropTypes.shape({
+      pages: PropTypes.arrayOf(StoryPropTypes.page),
```
Comment (BrittanyIRL) [inline packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js]: i think Max's idea of checking for elements array here would still be nice: https://github.com/GoogleForCreators/web-stories-wp/pull/11246#discussion_r847784158

Comment (BrookeGraham) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js]: 🤦‍♀️  I totally I thought I added that it's early.

Comment (BrookeGraham) [reply packages/story-editor/src/app/story/storyTriggers/storyEvents/onInitialElementAddedRegister.js]: Oh yeah `StoryPropTypes.page` has it. 
```
StoryPropTypes.page = PropTypes.shape({
  id: PropTypes.string.isRequired,
  animations: PropTypes.arrayOf(PropTypes.shape(AnimationProps)),
  elements: PropTypes.arrayOf(PropTypes.shape(StoryPropTypes.element)),
  overlay: PropTypes.oneOf(Object.values(OverlayType)),
  backgroundAudio: PropTypes.shape({
    resource: BackgroundAudioPropType,
    loop: PropTypes.bool,
    tracks: PropTypes.arrayOf(ResourcePropTypes.trackResource),
  }),
});
```

But since we only need `elements` I'll do that.

**Review by BrittanyIRL — APPROVED** [review]
