### PR TITLE
Embed Block: Fix center alignment 

### LINKED ISSUE #2374: Embed Block: Fix center alignment
## Bug Description

The block cannot be properly centered. Seems like some CSS is missing for that.

## Expected Behaviour

Center-aligning a block should work

## Steps to Reproduce

1. Insert block
1. Try to align center

## Screenshots

Screenshot 2020-06-11 at 18 08 32

## Additional Context

- Plugin Version:  `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary
Super simple fix, using `margin: auto`.

## Testing Instructions

1. Insert block to embed a story
1. Align block centered
1. Verify block is centered both on the frontend and in the editor

---

Fixes #2374

### CODE REVIEW

File: includes/Embed_Block.php [hunk 1]
```diff
@@ -169,7 +169,8 @@ protected function render_block_html( array $attributes ) {
 		$title        = (string) $attributes['title'];
 		$poster       = ! empty( $attributes['poster'] ) ? esc_url( $attributes['poster'] ) : '';
 		$align        = sprintf( 'align%s', $attributes['align'] );
-		$player_style = sprintf( 'width: %dpx; height: %dpx', absint( $attributes['width'] ), absint( $attributes['height'] ) );
+		$margin       = ( 'center' === $attributes['align'] ) ? 'auto' : '0';
```
Comment (swissspidy) [inline includes/Embed_Block.php:172]: Should we perhaps consider creating a stylesheet file with the following?

```css
.wp-block-web-stories-embed.aligncenter {
  margin-left: auto;
  margin-right: auto;
}
```

Comment (spacedmonkey) [reply includes/Embed_Block.php:172]: I did think about it, but is there any point in loading another stylesheet on page just for 3 lines of css?

**Review by swissspidy — APPROVED** [review]
