### PR TITLE
Floating Menu: Render Depth Resolved

### LINKED ISSUE #10636: UI Simplification: Floating menu: Render depth
## Bug Description

The floating menu does not render at the correct depth relative to other popups.

## Expected Behaviour

The floating menu should be below other popups.

## Steps to Reproduce

1. Select an element and observe the floating menu appear
2. Open the keyboard shortcuts menu and observe that it opens below the floating menu

## Screenshots

Note that this is a problem for the first three screenshots only, and not for the canvas size dropdown.
| Section | Works correctly? | Screenshot |
|-|-|-|
| Help center | ❌  | Screen Shot 2022-02-18 at 13 50 09 |
| Keyboard shortcuts | ❌  | Screen Shot 2022-02-18 at 13 50 20 |
| Checklist | ❌  | Screen Shot 2022-02-18 at 13 50 15 |
| Canvas size dropdown | ✅  | Screen Shot 2022-02-18 at 13 50 33 |

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Floating menus should be behind the Footer popups.

## Summary

Put simply, the initial layout of the canvas wasn't anticipating this many popups and the natural order of zindexing got weird. 

## Relevant Technical Choices

- Don't set `z-index` on the navLayer `Layer` so that the contents of that layer have a fighting chance at claiming their own positioning. The sidebar menu and the footer are both children of this layer, so if the z-index is set on the `Layer` (the parent) then we can't get the floating menu (which is at the same level as the `Layer` to be under the footer popovers and over the sidebar menu.  
It looks like this: 
```
Layout Layer
  > PageMenu Area > Side Menu
  > Footer > Help Center/Checklist/KeyboardNav 
Floating Menu
```

- Also bringing the `SideMenu` `z-index` down from 999 to 3 to make it more manageable.
- Move `z-index` for layers to a constant file so that its easier to tell the ordering and we don't have to hunt around for another 4 hours in the future for all of these 👯 

## To-do

N/A

## User-facing changes

`z-index` is one of those things that usually just gets updated when one specific thing is wrong, I tried hard to not mess with the order any more than I had to. There should be no user facing changes.

Behind the floating menu feature flag we get the following: 

| View | New | Old | 
| -- | -- | -- |
| Help Center | Screen Shot 2022-03-08 at 5 33 11 PM | Screen Shot 2022-03-08 at 5 34 34 PM |
| Checklist | Screen Shot 2022-03-08 at 5 13 37 PM | Screen Shot 2022-03-08 at 5 34 28 PM | 
| Keyboard Nav | Screen Shot 2022-03-08 at 5 33 18 PM | Screen Shot 2022-03-08 at 5 34 21 PM |

## Testing Instructions

Now the floating menus seen when an element is selected in the canvas should be _behind_ the checklist/help center/ keyboard nav when any of those are open while still remaining _in front_ of the side bar menu. 

Please also consider the other ways the z index is used here, I check drag and tooltips and zoom and the layers panel but I appreciate any heads up from people who have different context about regressions. 

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10636

### CODE REVIEW

File: packages/story-editor/src/components/keyboardShortcutsMenu/index.js [hunk 1]
```diff
@@ -46,12 +46,7 @@ const StyledToggleButton = styled(ToggleButton)`
 `;
 
 const Wrapper = styled.div`
-  /**
-    * sibling inherits parent z-index of Z_INDEX.EDIT
-    * so this needs to be placed above that while still
-    * retaining its position in the DOM for focus purposes
-    */
```
Comment (samwhale) [inline packages/story-editor/src/components/keyboardShortcutsMenu/index.js:53]: 🤔 Should this comment move with the value too?

**Review by samwhale — APPROVED** [review]
👍

File: packages/story-editor/src/components/keyboardShortcutsMenu/index.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/keyboardShortcutsMenu/index.js:53]: yes

File: packages/story-editor/src/constants/zIndex.js [hunk 2]
```diff
@@ -16,3 +16,17 @@
...
+// Floating element menu (a context menu) should be behind other popopups
+export const Z_INDEX_FLOATING_MENU = 4;
+
+// Edit Layer holds footer, popups in footer need to be in front of floating menu
+export const Z_INDEX_EDIT_LAYER = Z_INDEX_FLOATING_MENU + 1;
+
+// sibling inherits parent z-index of Z_INDEX_EDIT_LAYER
+// so popups nested in footer need to be placed above that
+// while still retaining position in the DOM for focus purposes
+export const Z_INDEX_FOOTER_POPUP = Z_INDEX_EDIT_LAYER + 1;
```
Comment (BrookeGraham) [inline packages/story-editor/src/constants/zIndex.js]: Nice. Think these will end up being very helpful.

**Review by BrookeGraham — APPROVED** [review]
🎪  I didn't find any regressions. Looked great to me.

File: packages/story-editor/src/constants/zIndex.js [hunk 3]
```diff
@@ -16,3 +16,20 @@
...
+export const Z_INDEX_HEAD_AREA = 3;
+
+// Floating menu lays on top of side menu
+export const Z_INDEX_CANVAS_SIDE_MENU = 3;
+
+// Floating element menu (a context menu) should be behind other popopups
+export const Z_INDEX_FLOATING_MENU = 4;
+
+// Edit Layer holds footer, popups in footer need to be in front of floating menu
+export const Z_INDEX_EDIT_LAYER = Z_INDEX_FLOATING_MENU + 1;
```
Comment (miina) [inline packages/story-editor/src/constants/zIndex.js:30]: If the floating menu is behind the edit menu, using the floating menu in text edit mode is not possible, it should still be in top of it. Perhaps there needs to be another layer for footer / popups?

File: packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js [hunk 4]
```diff
@@ -96,7 +96,10 @@ describe('Design Menu: Text Styles', () => {
       );
     });
 
-    it('should allow changing text color for a selection from the design menu', async () => {
+    // This is failing due to keyboard problems
+    // TODO #10872 https://github.com/GoogleForCreators/web-stories-wp/issues/10872
+    // eslint-disable-next-line jasmine/no-disabled-tests
+    xit('should allow changing text color for a selection from the design menu', async () => {
```
Comment (miina) [inline packages/story-editor/src/components/floatingMenu/elements/karma/text.karma.js:102]: Note: this is also failing due to the same layering issue mentioned [here](https://github.com/GoogleForCreators/web-stories-wp/pull/10861/files#r824902184) that prevents usage of the toolbar in edit mode (not related to keyboard issues).

File: packages/story-editor/src/constants/zIndex.js (hunk 3 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/constants/zIndex.js:30]: this is a big bummer. we have to completely reorg the flow of the canvas grid and layers to separate out the layers.  Hot fix is here: https://github.com/GoogleForCreators/web-stories-wp/pull/10893 and I made a ticket for follow up. https://github.com/GoogleForCreators/web-stories-wp/issues/10892
