### PR TITLE
Fix selecting media creating history entries

### LINKED ISSUE #2664: Selecting Media creates a new history entry
## Bug Description

`hasNewChanges` is `true` after I select something.
https://drive.google.com/file/d/1ZePEpYtQvUGyF0UueZgaYG9izuiyciFM/view?usp=sharing

## Expected Behaviour

Selecting the element shouldn't affect history.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Testing Instructions
1. Add Media element and save to disable "Save draft" button.
2. Now click on media.
3. Verify that the "Save draft" button did not change to active.
4. Try a few times just in case.

---

Fixes #2664

### CODE REVIEW

File: assets/src/edit-story/elements/media/index.js [hunk 1]
```diff
@@ -81,4 +81,5 @@ export const MEDIA_PANELS = [
   PanelTypes.LAYER_STYLE,
   PanelTypes.SIZE_POSITION,
   PanelTypes.ANIMATION,
+  PanelTypes.LINK,
```
Comment (miina) [inline assets/src/edit-story/elements/media/index.js:85]: This is an unrelated change but just noticed while debugging to find the issue that the link panel is added to both elements separately as opposed to media generally.

File: assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js [hunk 2]
```diff
@@ -94,7 +94,7 @@ function useSingleSelectionDrag({
 
     // When dragging finishes, set the new properties based on the original + what moved meanwhile.
     const [deltaX, deltaY] = frame.translate;
-    if (deltaX !== 0 || deltaY !== 0 || isDropSource(selectedElement.type)) {
+    if (deltaX !== 0 || deltaY !== 0) {
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js:97]: Hm, what is the reason for this test existing in the first place and can it really safely be removed?

Comment (miina) [reply assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js:97]: I believe it was incorrectly added, doesn't seem to be any reason why to add this check to this `if`, it can be done below as well. If the dragging didn't result in any movement (deltas both 0) then there is no dropping happening anyway.

**Review by barklund — APPROVED** [review]
