### PR TITLE
Hide blue indicator when there is only one page

### LINKED ISSUE #1179: Page Carousel - Remove Blue Indicator When Only One Page
## Bug Description

When there is only one page there shouldn't be a blue indicator on the page thumbnails in the carousel 

## Expected Behaviour

The blue line shouldn't be there.
See [figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2683%3A260) for examples

## Steps to Reproduce

1. View a single page story

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #1179.

Screenshot 2020-04-23 at 11 07 02
Screenshot 2020-04-23 at 11 07 07

### CODE REVIEW

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 1]
```diff
@@ -372,7 +374,7 @@ function Carousel() {
                             index + 1
                           )
                     }
-                    isActive={page.id === currentPageId}
+                    isActive={isCurrentPage && pages.length > 1}
```
Comment (miina) [inline assets/src/edit-story/components/canvas/carousel/index.js]: Should it perhaps be the same in case of hovering as well -- not display the blue indicator when there's only one page?

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Unsure. Asked for clarification on the issue.

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Looks like it needs to be hidden on hover as well. Will probably add a new prop for that.

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Done!

**Review by miina — APPROVED** [review]
LGTM!
