### PR TITLE
Fixed tooltips for element links

### LINKED ISSUE #12834: Link tooltip preview innacurate
## Bug Description

Two issues I noticed with link tooltips in the editor:

1. The tail position is sometimes completely off. It should be more or less in the center of the element
2. The preview does not match the frontend.
  - If there is no icon, don't show it.
  - Show "external link" icon to the right

## Expected Behaviour

More WYSIWYG :) 

## Steps to Reproduce

1. Add link to element
2. Move element around
3. Compare with story preview

## Screenshots

Screenshot 2022-12-13 at 10 45 43

Screenshot 2022-12-13 at 10 45 38
 
Screenshot 2022-12-13 at 10 45 15
Screenshot 2022-12-13 at 10 45 00
Screenshot 2022-12-13 at 10 44 04

## Additional Context

- Plugin Version: 1.28
- WordPress Version: 6.1
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by barklund**
## Context

This is an attempt at fixing the tooltips.

## To-do

- [x] Make URL icon rounded
- [x] Hide URL icon if missing
- [x] Add external link icon
- [x] Remote protocol if raw url displayed
- [x] Fix tail position - see comment below

## User-facing changes

| Has icon? | Element size | Before | After |
|-|-|-|-|
| ✅ | Wide | Screen Shot 2022-12-19 at 14 54 52 | Screen Shot 2022-12-19 at 14 51 41 |
| ✅ | Medium | Screen Shot 2022-12-19 at 14 54 56 | Screen Shot 2022-12-19 at 14 51 45 |
| ✅ | Narrow | Screen Shot 2022-12-19 at 14 55 00 | Screen Shot 2022-12-19 at 14 51 49 |
| 🚫  | Wide | Screen Shot 2022-12-19 at 14 55 07 | Screen Shot 2022-12-19 at 14 51 28 |
| 🚫 | Medium | Screen Shot 2022-12-19 at 14 55 10 | Screen Shot 2022-12-19 at 14 51 31 |
| 🚫 | Narrow | Screen Shot 2022-12-19 at 14 55 14 | Screen Shot 2022-12-19 at 14 51 35 |

## Testing Instructions

This PR can be tested by following these steps:

1. Add elements with links in various sizes and positions
2. Observe the link hover preview

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12834

### CODE REVIEW

**Comment by barklund** [comment]
I cannot get the annoying tail to sit correctly. I am not even sure where it is actually supposed to go? Middle of the tooltip  or middle of the element? Is the tooltip even in the correct location in all of these?

| Element | Icon | Raw URL | Screenshot |
|-|-|-|-|
| Wide image | ✅  | 🚫 | Screen Shot 2022-12-14 at 12 36 27 |
| Medium image | ✅  | 🚫 |Screen Shot 2022-12-14 at 12 36 32 |
| Narrow image | ✅  | 🚫 | Screen Shot 2022-12-14 at 12 36 43 |
| Text | 🚫 | ✅  | Screen Shot 2022-12-14 at 12 36 50 |
| Shape | 🚫 | ✅  | Screen Shot 2022-12-14 at 12 36 54 |

File: packages/url/src/url.ts [hunk 1]
```diff
@@ -47,3 +47,7 @@ export function withProtocol(
     ? url
     : `${protocol}://${url}`;
 }
+
+export function withoutProtocol(url: string): string {
+  return url.replace(/^(http:\/\/|https:\/\/|tel:|mailto:)/, '');
```
Comment (miina) [inline packages/url/src/url.ts:52]: Would be nice to have some tests for this.

**Review by miina — APPROVED** [review]

File: packages/url/src/test/url.ts [hunk 2]
```diff
@@ -35,14 +35,16 @@ describe('isValidUrl', () => {
...
-    );
-    expect(withProtocol('http://foo-bar.com/test.jpg')).toBe(
-      'http://foo-bar.com/test.jpg'
-    );
-    expect(withProtocol('foo-bar.com/test.jpg')).toBe(
-      'https://foo-bar.com/test.jpg'
-    );
+    expect(withProtocol('https://foo.com/test')).toBe('https://foo.com/test');
+    expect(withProtocol('http://foo.com/test')).toBe('http://foo.com/test');
+    expect(withProtocol('foo.com/test')).toBe('https://foo.com/test');
```
Comment (barklund) [inline packages/url/src/test/url.ts:40]: The only reason for this change is to make each fit on a single line because it's prettier 😂

File: packages/url/src/url.ts (hunk 1 above)
Comment (barklund) [reply packages/url/src/url.ts:52]: Added in 913d5718cda313916412358a4e13098b4e23f722.

**Comment by kkalarickal** [comment]
Confirmed that element links attached to the following different types of elements yields favorable results with the `12840_branch` code on https://stories-qa-wordpress-amp.pantheonsite.io/

- image
- gif
- video file
- sticker
- gif
- text element
- shapes

I also tried this on a mobile device, and desktop browsers.

**Comment by kkalarickal** [comment]
@swissspidy @barklund - the observation I wanted to share with you is that if I attach a link to a text element, then the tail of the tool tip is sometimes difficult to see since the color of the tool tip matches the (default) background color -- white
