### PR TITLE
Convert `design-system` package to TypeScript

### LINKED ISSUE #11257: Code Quality: Undefined panel type for shape element
## Bug Description

One of the values of `panels` array is not defined here
https://github.com/GoogleForCreators/web-stories-wp/blob/7722b81051310337bfd0cb186f14a21a143438e6/packages/element-library/src/shape/constants.js#L51

https://github.com/GoogleForCreators/web-stories-wp/blob/7722b81051310337bfd0cb186f14a21a143438e6/packages/design-system/src/utils/panelTypes.js#L34-L51

image

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #12251: Floating Toolbar - Lock Placement - Icon to show menu impacts the carousel thumbnail location
## Bug Description

Selecting the “Always hide option” presents an icon along the bottom that bumps the carousel thumbnails to the left and they are no longer centered in the canvas

image6

****
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #12659: TypeScript: Convert design system theme
The theme is heavily used throughout the app and would greatly benefit from improved typing support when using styled components everywhere.

Some previous attempts:

* https://github.com/GoogleForCreators/web-stories-wp/blob/c3b5eec59b0bb79dc096260f5c9614cffc3b3778/packages/masks/src/typings/styled-components.d.ts
* https://github.com/GoogleForCreators/web-stories-wp/blob/c3b5eec59b0bb79dc096260f5c9614cffc3b3778/packages/moveable/src/typings/styled-components.d.ts

See also https://styled-components.com/docs/api#typescript

### PR DESCRIPTION
**Pull request by barklund**
## Context

Conversion of design-system to TypeScript

## Relevant Technical Choices

* Too many to count

## To-do

* [x] Convert something
* [x] Convert the rest
* [x] Fix unit tests
* [x] Fix SVG imports
* [x] Fix lints
* [x] Make sure it actually compiles
* [x] Fix Storybook
* [x] Fix dashboard karma tests
* [x] Fix editor karma tests
* [x] Fix visual inconsistencies as found by Percy

## User-facing changes

_None(?)_

## Testing Instructions

This PR can be tested by following these steps:

1. Smoke-test the entire plugin, from dashboard to editor.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12659
Fixes #12251
Fixes #11257

### CODE REVIEW

File: packages/design-system/src/typings/svg.d.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+declare module '*.svg' {
+  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
+  export default content;
+}
```
Comment (barklund) [inline packages/design-system/src/typings/svg.d.ts]: @swissspidy, this works partially. It works fine in my editor, but when running the TS workflow, I get these errors:

```
packages/design-system/dist-types/icons/index.d.ts:4:40 - error TS2307: Cannot find module './align_bottom.svg' or its corresponding type declarations.

4 export { default as AlignBottom } from './align_bottom.svg';
                                         ~~~~~~~~~~~~~~~~~~~~

packages/design-system/dist-types/icons/index.d.ts:5:40 - error TS2307: Cannot find module './align_center.svg' or its corresponding type declarations.

5 export { default as AlignCenter } from './align_center.svg';
                                         ~~~~~~~~~~~~~~~~~~~~
```

Etc for all 140 SVG's in the design system. Any idea how to make it work correctly?

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Does it work with a config like https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/story-editor/src/typings/svg-imports.d.ts?

Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: Still only in editor, workflow reports the some problem. Just pushed with this changed typing.

And it's actually not just the workflow that fails. The actual imports fail as well when running the editor. Webpack seems to be missing a loader or can't find the right one:

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
| <path d="M8.5 21H23.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
| <path fill-rule="evenodd" clip-rule="evenodd" d="M15.5 10.5C14.6716 10.5 14 11.1716 14 12V17C14 17.8284 14.6716 18.5 15.5 18.5H16.5C17.3284 18.5 18 17.8284 18 17V12C18 11.1716 17.3284 10.5 16.5 10.5H15.5Z" fill="currentColor"/>
```

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Ah, the loader issue was fixed by #12907, so should work when merging latest changes from main

Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: Hmm, it compiles with:

```ts
declare module '*.svg' {
  const content: string;
  export default content;
}
```

But then other things break, because they aren't actually string and we need to treat them like React elements (e.g. by adding class names and other properties to them elsewhere in the codebase).

If I do this:

```ts
/**
 * External dependencies
 */
import type { ReactElement, SVGProps } from 'react';

declare module '*.svg' {
  const Icon: (props: SVGProps<SVGElement>) => ReactElement;
  export default Icon;
}
```

It just fails without any errors or warnings (just that no corresponding type can be found). Not really sure why?

I also tried to swap in `SVGAttributes` for `SVGProps` (as it seems more correct), but no luck either.

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Hmm then I am not sure either 😕

File: packages/dashboard/src/icons/svg-imports.d.ts [hunk 2]
```diff
@@ -14,7 +14,14 @@
  * limitations under the License.
  */
 
+<<<<<<<< HEAD:packages/design-system/src/contexts/popup/types.ts
+export interface PopupState {
```
Comment (miina) [inline packages/dashboard/src/icons/svg-imports.d.ts]: Merging issues here

File: packages/design-system/src/utils/useMouseDownOutsideRef.ts [hunk 3]
```diff
@@ -50,8 +49,11 @@ function useMouseDownOutsideRef(onMouseDownOutside = noop) {
 
     // create and attach listeners with new node
     if (node) {
-      handleDocumentClickCaptureRef.current = (evt) => {
-        if (node === evt.target || node.contains(evt.target)) {
+      handleDocumentClickCaptureRef.current = (evt: Event) => {
```
Comment (miina) [inline packages/design-system/src/utils/useMouseDownOutsideRef.ts]: Same here, should these be `MouseEvent`s instead?

File: packages/design-system/src/utils/useMouseDownOutsideRef.ts [hunk 4]
```diff
@@ -26,19 +26,18 @@ import { noop } from './noop';
...
  * to attach to the desired element you want to detect outside
  * mouse down events
- *
- * @param {Function} onMouseDownOutside handler for mousedown outside
- * @return {Object} ref to pass to desired element
  */
-function useMouseDownOutsideRef(onMouseDownOutside = noop) {
-  const targetRef = useRef(null);
+function useMouseDownOutsideRef<E extends HTMLElement>(
+  onMouseDownOutside: (evt: Event) => void = noop
```
Comment (miina) [inline packages/design-system/src/utils/useMouseDownOutsideRef.ts]: `MouseEvent`?

File: packages/design-system/src/utils/pointerEventsCss.ts [hunk 5]
```diff
@@ -19,7 +19,7 @@
  */
 import { css } from 'styled-components';
 
-const pointerEventsCss = css`
+const pointerEventsCss = css<{ pointerEvents?: string }>`
   ${({ pointerEvents }) => {
     if (pointerEvents && typeof pointerEvents === 'string') {
```
Comment (miina) [inline packages/design-system/src/utils/pointerEventsCss.ts]: Does it still need this check for `string`?

File: packages/dashboard/src/icons/svg-imports.d.ts (hunk 2 above)
Comment (barklund) [reply packages/dashboard/src/icons/svg-imports.d.ts]: Fixed in 0623bd5bc9

File: packages/design-system/src/components/textArea/index.ts [hunk 6]
```diff
@@ -0,0 +1,17 @@
+/*
+ * Copyright 2021 Google LLC
```
Comment (miina) [inline packages/design-system/src/components/textArea/index.ts:2]: Not related to this PR but this should be 2023 probably? cc @swissspidy

File: packages/design-system/src/components/snackbar/types.ts [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+  Error = 'error',
+}
+
+export interface SnackbarNotificationThumbnail {
+  src: string;
+  alt?: string;
+  status?: ThumbnailStatus;
+}
+
+export interface SnackbarNotification {
```
Comment (miina) [inline packages/design-system/src/components/snackbar/types.ts:41]: We also have (had?) [`src/types/snackbar.ts`](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/design-system/src/types/snackbar.ts).

**Review by miina — COMMENTED** [review]
Maybe merge `main` meanwhile?

File: packages/design-system/src/components/snackbar/types.ts (hunk 7 above)
Comment (barklund) [reply packages/design-system/src/components/snackbar/types.ts:41]: Merged in https://github.com/GoogleForCreators/web-stories-wp/pull/12929/commits/87c76d99be8cb6bb12309b4df2ac4242ef15c094.

File: packages/design-system/src/utils/useMouseDownOutsideRef.ts (hunk 3 above)
Comment (barklund) [reply packages/design-system/src/utils/useMouseDownOutsideRef.ts]: Yeah, it could be. Doesn't change much because we don't use `MouseEvent` specific properties on the event object, but it is a bit more specific.

File: packages/design-system/src/utils/pointerEventsCss.ts (hunk 5 above)
Comment (barklund) [reply packages/design-system/src/utils/pointerEventsCss.ts]: Hmm, why do we even have this util? It's for adding a single line of CSS with an util which is almost identical to the CSS you would write anyway? We actually even have this stupid util in two different packages! I mean, why? I'll kill both, they're only ever used once and twice respectively!!! It's too stupid to keep as an util!

File: packages/design-system/src/components/textArea/index.ts (hunk 6 above)
Comment (barklund) [reply packages/design-system/src/components/textArea/index.ts:2]: Yes, I noticed that somewhere by the end. I should update all the new headers, but I mostly just copy-paste it from some other file. Can I automate updating for all new files in this PR, @swissspidy?

File: packages/design-system/src/utils/pointerEventsCss.ts (hunk 5 above)
Comment (barklund) [reply packages/design-system/src/utils/pointerEventsCss.ts]: Removed in 8a04a9d497.

File: packages/design-system/src/utils/useMouseDownOutsideRef.ts (hunk 3 above)
Comment (barklund) [reply packages/design-system/src/utils/useMouseDownOutsideRef.ts]: Fixed in 3bccfe791f

File: packages/design-system/src/components/popup/popup.tsx [hunk 8]
```diff
@@ -53,24 +71,31 @@ function Popup({
...
+    offset: Offset;
+    height: number;
+  } | null>(null);
   const isMounted = useRef(false);
-  const popup = useRef(null);
+  const popup = useRef<HTMLDivElement | null>(null);
 
   const positionPopup = useCallback(
-    (evt) => {
+    (evt?: unknown) => {
```
Comment (miina) [inline packages/design-system/src/components/popup/popup.tsx:89]: Can it be anything else than `Event` or `undefined`? 🤔

File: packages/design-system/src/components/pill/pillGroup.tsx [hunk 9]
```diff
@@ -33,7 +33,19 @@ const Container = styled.div.attrs({
...
+interface PillOption {
+  id: string;
+  label: string;
+}
+
+interface PillGroupProps
+  extends Omit<ComponentPropsWithoutRef<'button'>, 'onSelect' | 'onClick'> {
+  options: PillOption[];
+  value: string;
+  onSelect: (id: string) => void;
```
Comment (miina) [inline packages/design-system/src/components/pill/pillGroup.tsx:45]: No need to add `onClick` back?

File: packages/design-system/src/components/menu/list/defaultListItem.tsx [hunk 10]
```diff
@@ -37,34 +37,30 @@ const ActiveIcon = styled(CheckmarkSmall)`
...
-        width={32}
-        height={32}
-      />
-    )}
-    <ListItemDisplayText
-      forwardedAs="span"
-      size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL}
+const DefaultListItem = forwardRef(function DefaultListItem(
+  { option, isSelected, ...rest }: DefaultListItemProps,
+  ref: ForwardedRef<HTMLLIElement>
```
Comment (miina) [inline packages/design-system/src/components/menu/list/defaultListItem.tsx:42]: `HTMLLIElement`? Because of `value`?

File: packages/design-system/src/components/input/useNumericInput.tsx [hunk 11]
```diff
@@ -52,7 +55,7 @@ export const useNumericInput = ({
    * Call external `onChange`
    */
   const handleBlur = useCallback(
-    (ev) => {
+    (ev: unknown) => {
```
Comment (miina) [inline packages/design-system/src/components/input/useNumericInput.tsx:58]: Why unknown, shouldn't it be an event?

File: packages/design-system/src/components/datalist/types.ts [hunk 12]
```diff
@@ -0,0 +1,143 @@
...
+  value: string;
+  onChange: (value: string) => void;
+}
+
+// Either you specify options, or you specify a callback returning a promise. Not both, not neither.
+export type DataListPropsOptions<O> =
+  | { options: O[]; getOptionsByQuery: never }
+  | { options: never; getOptionsByQuery: (query: string) => Promise<O[]> };
+
+export type DataListProps<O extends AbstractOption> =
```
Comment (miina) [inline packages/design-system/src/components/datalist/types.ts:114]: Uh, that's a bunch of props!

File: packages/design-system/src/components/datalist/list/list.tsx [hunk 13]
```diff
@@ -262,44 +267,34 @@ const OptionList = forwardRef(function OptionList(
                   <OptionRenderer
                     key={option.id || ''}
                     role={'option'}
-                    tabIndex="-1"
+                    tabIndex={-1}
```
Comment (miina) [inline packages/design-system/src/components/datalist/list/list.tsx:270]: Why this change? 🤔

File: packages/design-system/src/components/datalist/list/list.tsx [hunk 14]
```diff
@@ -262,44 +267,34 @@ const OptionList = forwardRef(function OptionList(
...
-  priorityOptionGroups: PropTypes.array,
-  searchResultsLabel: PropTypes.string,
-  renderer: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
-  onObserve: PropTypes.func,
-  listId: PropTypes.string.isRequired,
-  focusSearch: PropTypes.func,
-  listStyleOverrides: PropTypes.array,
-  noMatchesFoundLabel: PropTypes.string,
-};
+const OptionList = memo(forwardRef(OptionListWithRef)) as <
```
Comment (miina) [inline packages/design-system/src/components/datalist/list/list.tsx:295]: 🤯

File: packages/design-system/src/components/contextMenu/contextMenuProvider/provider.tsx [hunk 15]
```diff
@@ -17,23 +17,29 @@
...
+  onDismiss: (evt?: Event) => void;
+}
+
 export default function ContextMenuProvider({
   children,
   isIconMenu = false,
   isHorizontal = false,
   onDismiss,
-}) {
-  const [focusedId, setFocusedId] = useState(-1);
```
Comment (miina) [inline packages/design-system/src/components/contextMenu/contextMenuProvider/provider.tsx:33]: Was there a reason for the `-1` before?

File: packages/design-system/src/components/contextMenu/contextMenuProvider/context.ts [hunk 16]
```diff
@@ -0,0 +1,41 @@
...
+import type { ContextMenuProvider } from '../types';
+
+const ContextMenuContext = createContext<ContextMenuProvider>({
+  state: {
+    focusedId: null,
+    isIconMenu: false,
+    isHorizontal: false,
+  },
+  actions: {
+    onDismiss: () => undefined,
```
Comment (miina) [inline packages/design-system/src/components/contextMenu/contextMenuProvider/context.ts:34]: `noop`?

File: packages/design-system/src/components/contextMenu/components/subMenuTrigger.tsx [hunk 17]
```diff
@@ -100,20 +112,20 @@ function SubMenuTrigger({
     if (!isSubMenuOpen || !node) {
       return undefined;
     }
-    const onPointerMove = (e) => {
-      // Track the pointer when moving inside the menu while the submenu is open.
-      pointerTracker.current.x = e.clientX;
-      pointerTracker.current.y = e.clientY;
-      maybeCloseSubMenu();
+    const onPointerMove = (e: Event) => {
```
Comment (miina) [inline packages/design-system/src/components/contextMenu/components/subMenuTrigger.tsx:118]: Should it just be `PointerEvent` directly perhaps?

File: packages/design-system/src/components/banner/index.tsx [hunk 18]
```diff
@@ -0,0 +1,17 @@
+/*
```
Comment (miina) [inline packages/design-system/src/components/banner/index.tsx]: ^ => `index.ts`

File: packages/design-system/src/components/textArea/index.ts (hunk 6 above)
Comment (swissspidy) [reply packages/design-system/src/components/textArea/index.ts:2]: Sure

**Review by miina — APPROVED** [review]
Since I'll be off for the next two weeks, approving assuming the remaining issues get resolved with the SVG fix.

File: packages/design-system/src/components/datalist/list/list.tsx [hunk 19]
```diff
@@ -118,46 +119,50 @@ const OptionList = forwardRef(function OptionList(
...
-            );
-            onObserve(userSeenOptions.current);
-          }
-        },
-        {
-          root: listRef.current,
-          // Gets ~2 extra items below scroll container BoundingBox
-          rootMargin: '60px',
+  const observer = useMemo(() => {
+    if (!listRef) {
```
Comment (swissspidy) [inline packages/design-system/src/components/datalist/list/list.tsx]: Should this be

```suggestion
    if (!listRef.current) {
```

?

Comment (barklund) [reply packages/design-system/src/components/datalist/list/list.tsx]: Yes, it should be. Fixing.

File: packages/design-system/src/components/contextMenu/components/subMenuTrigger.tsx (hunk 17 above)
Comment (barklund) [reply packages/design-system/src/components/contextMenu/components/subMenuTrigger.tsx:118]: This is a native HTML event listener - it is only typed as dispatching a generic event, not typed specifically for each individual event type. Putting `PointerEvent` would result in this error a few lines below.

```
Argument of type '(e: PointerEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.

File: packages/design-system/src/components/contextMenu/contextMenuProvider/context.ts (hunk 16 above)
Comment (barklund) [reply packages/design-system/src/components/contextMenu/contextMenuProvider/context.ts:34]: I actually don't see the benefit of using the `noop` util anywhere. It's not a lot of memory saved, and it's even extra bytes typed importing it. I won't remove it if used, but probably won't use it myself.

File: packages/design-system/src/components/contextMenu/contextMenuProvider/provider.tsx (hunk 15 above)
Comment (barklund) [reply packages/design-system/src/components/contextMenu/contextMenuProvider/provider.tsx:33]: I couldn't find any reference to it at all actually. I think it was just a placeholder that would never match a real id.

File: packages/design-system/src/components/datalist/list/list.tsx (hunk 14 above)
Comment (barklund) [reply packages/design-system/src/components/datalist/list/list.tsx:295]: Yeah, I know. It sucks. I should probably repeat the comment about why this is necessary when having generically typed components.

File: packages/design-system/src/components/datalist/types.ts (hunk 12 above)
Comment (barklund) [reply packages/design-system/src/components/datalist/types.ts:114]: Yeah, it's pretty bloated, because it's used by many different components. However, it is never used directly, I think, only indirectly through other components, so I think it's okay.

File: packages/design-system/src/components/datalist/list/list.tsx (hunk 13 above)
Comment (barklund) [reply packages/design-system/src/components/datalist/list/list.tsx:270]:
```
Type 'string' is not assignable to type 'number'.

File: packages/design-system/src/components/menu/list/defaultListItem.tsx (hunk 10 above)
Comment (barklund) [reply packages/design-system/src/components/menu/list/defaultListItem.tsx:42]: Because it's a list item? Not sure I understand the question?

File: packages/design-system/src/components/input/useNumericInput.tsx (hunk 11 above)
Comment (barklund) [reply packages/design-system/src/components/input/useNumericInput.tsx:58]: It is invoked both from a native DOM event listener with a DOM KeyboardEvent (through `useKeyDownEffect`), and through a React event listener (through `onBlur`). So it's either a DOM event or a React event, but we don't actually care, we just pass it on to the `onChange` function (which probably doesn't care either).

It could be typed as `KeyboardEvent | FocusEvent`, which the latter being imported from React, but I found that a bit confusing.

It could also be solved by having a wrapper listener for the React event that invoked it the other with `evt.nativeEvent` ensure it would always receive a proper DOM event, but still, I didn't see a purpose, because we don't actually consume the event.

File: packages/design-system/src/components/pill/pillGroup.tsx (hunk 9 above)
Comment (barklund) [reply packages/design-system/src/components/pill/pillGroup.tsx:45]: We manually assign an `onClick` handler to the element in question and we don't want a consumer to override that by specifying their own `onClick`, so we just don't allow one to be passed in.

File: packages/design-system/src/components/popup/popup.tsx (hunk 8 above)
Comment (barklund) [reply packages/design-system/src/components/popup/popup.tsx:89]: Can be `Event` from `addEventListener`, `{ width: number; height: number }` from `useResizeEffect`, or `undefined` when invoked directly. We could circumvent the resize effect dimension thingy by wrapping it in another function that just discarded the argument, but I didn't see a strong reason.

File: packages/design-system/src/typings/svg.d.ts (hunk 1 above)
Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: @swissspidy, any idea how to resolve this? My only other option, ChatGPT, doesn't know either 😭

Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: I fixed it! Well, [this answer](https://stackoverflow.com/questions/39040108/import-class-in-definition-file-d-ts) fixed my knowledge:

> Basically, TypeScript has two kind of module types declaration: "local" (normal modules) and ambient (global). The second kind allows to write global modules declaration that are merged with existing modules declaration. What are the differences between this files?
> `d.ts` files are treated as an ambient module declarations only if they don't have any imports. If you provide an import line, it's now treated as a normal module file, not the global one, so augmenting modules definitions doesn't work.

So this works (but stinks):

```ts
declare module '*.svg' {
  const Icon: (
    props: import('react').SVGAttributes<SVGElement>
  ) => import('react').ReactElement;
  export default Icon;
}
```

Alternatively we re-create this declaration in every folder that has SVG's, but there's actually quite a few, as several components have their own icons and graphics, and I'm still not convinced it would work.

So let's just keep this?

Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: Ah, it's actually as simple as just:

```ts
declare module '*.svg' {
  const Icon: (props: React.SVGAttributes<SVGElement>) => React.ReactElement;
  export default Icon;
}
```

The problem now is, that it doesn't work fully.

Yes, I can build the design system package correctly by running `npx tsc --build` inside the package. It runs correctly (with this file in place) and not without it.

But I cannot build the whole system, because `*.d.ts` files aren't copied to the `dist-types` output (they're only considered necessary **for** the build, not **part of** the build), so once the types have been summarized in dist-types, they're no longer "complete".

If I run `npm run workflow:bundle-packages:types` I get errors like:

```
packages/design-system/dist-types/images/index.d.ts:7:37 - error TS2307: Cannot find module './desert_bw.svg' or its corresponding type declarations.

  export { default as DesertBw } from "./desert_bw.svg";
```

And that makes sense, because once moved to the dist-types folder, then yes, the import no longer has a type for the SVG file. But how do we fix that? I have no clue...

Please halp, @swissspidy, you're my only hope! 🙏

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Unfortunately I'm at loss right now as well 😞 

I tried including the definition via `typeRoots` rather than `include`, and the only difference is that the error message is now for the source file and not for the one in `dist-types`. Progress I guess? But to me that sounds like it's not really an issue with copying over `d.ts` file.

The file I used:

```json5
{
  "extends": "../../tsconfig.shared.json",
  "compilerOptions": {
    "rootDir": "src",
    "declarationDir": "dist-types",
    "typeRoots": ["./src/typings", "../../node_modules/@types"]
  },
  "references": [
    { "path": "../i18n" },
    { "path": "../patterns" },
    { "path": "../react" },
    { "path": "../tracking" }
  ],
  "include": [
    "src/components",
    "src/contexts",
    "src/icons",
    "src/images",
    "src/theme",
    "src/types",
    "src/utils"
  ]
}
```

Then I also stumbled upon https://duncanleung.com/typescript-module-declearation-svg-img-assets/ and subsequently tried to move the type definition to a subfolder of `typings`, but to no avail.

I think I need to look at this again later with fresh eyes.

----

Aside: there are a couple of type errors related to `useDebouncedCallback` in `useDropDown` and `useSearch`

Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: I had an idea about creating a global `typings/` folder at the root and `/// <reference />` that, but it didn't seem to work. Almost, but then not again.

Another idea though: We create a new `svg` package with all the SVG files, and all other packages, that need SVG's import that package. Then we can use whatever hacks we need to make that package work, including perhaps manually crafting a `*.d.ts` if need be. Does that sound stupid?

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Can't believe that 6148ff51d589c96d7df5252b5bef189901b6cad8 solves the issue 😭 

The incorrect `declare module` definitions in `story-editor` were breaking this 🤷

File: packages/react/tsconfig.json [hunk 20]
```diff
@@ -2,7 +2,8 @@
   "extends": "../../tsconfig.shared.json",
   "compilerOptions": {
     "rootDir": "src",
-    "declarationDir": "dist-types"
+    "declarationDir": "dist-types",
+    "baseUrl": "."
```
Comment (swissspidy) [inline packages/react/tsconfig.json]:
```suggestion
    "declarationDir": "dist-types"
```

**Comment by swissspidy** [comment]
Hmm looks like c2a69d12244548e1354a7c252bdf1a6a360df390 was not fully correct, need to look into it.

File: packages/design-system/src/typings/svg.d.ts (hunk 1 above)
Comment (barklund) [reply packages/design-system/src/typings/svg.d.ts]: Oh wow, good find! But I thought the `inline-icons` were actually imported as strings as used in various packages? But hey, if it works!

Comment (swissspidy) [reply packages/design-system/src/typings/svg.d.ts]: Inline-icons is only used in the moveable package IIRC, so we could move that special case there

File: packages/design-system/src/components/popup/popup.tsx [hunk 21]
```diff
@@ -85,50 +110,62 @@ function Popup({
...
-        ? popup.current.getBoundingClientRect()
-        : {};
+        : EMPTY_OFFSET;
+      const popupRect = popup.current?.getBoundingClientRect();
 
-      const updatedXOffset = () => {
+      const updatedXOffset = (): Offset | null => {
+        if (!popupRect) {
+          return null;
+        }
```
Comment (barklund) [inline packages/design-system/src/components/popup/popup.tsx:119]: Damn, this bug took me all day to find. Basically, the old code destructured an empty object into DOMRect attributes in case of the popup not showing yet and depended on `undefined < someLimit === NaN`, which is falsey. I used a default value of 0 in the destructuring to make TS happy, but that actually made the statement true, because suddenly it _was_ smaller than the limit value, which `undefined` _"isn't"_. So with the proper checks for the missing DOMRect just skipping this whole section of code, and everything works again.

**Comment by swissspidy** [comment]
Some observations from Percy (also left comments there):

- Title input is smaller
- Undo/Redo/Preview/Save buttons lack border
- Redo button has different disabled state
- Help center button lacks icon
- Popup positions are off (color picker, saved styles editing)
- Help center: Text for "All Tips" and Previous and Next is smaller
- Help center: Tip title is slightly larger
- The shortcuts in keyboard shortcuts popup have different font (monospace vs sans-serif) — though I have to say I actually like it this way

**Comment by barklund** [comment]
> Some observations from Percy (also left comments there):
> 
> * Title input is smaller
> * Undo/Redo/Preview/Save buttons lack border
> * Redo button has different disabled state
> * Help center button lacks icon
> * Popup positions are off (color picker, saved styles editing)
> * Help center: Text for "All Tips" and Previous and Next is smaller
> * Help center: Tip title is slightly larger
> * The shortcuts in keyboard shortcuts popup have different font (monospace vs sans-serif) — though I have to say I actually like it this way

I think I found all the same (a bunch of them were for the same reasons - e.g. all the font ones because of a missing font size replacement, popups because of placement enum typo, buttons because of button type enum typo) and quite a few more, and I've fixed it all now.

I've actually also made some design decisions, making the buttons in the right footer identical to all the other footer buttons, just because it looks better IMO. Feel free to disagree :D

| | Screenshot |
|-|-|
| Before | Screen Shot 2023-01-27 at 13 17 58 |
| After | Screen Shot 2023-01-27 at 13 20 49 |

**Comment by swissspidy** [comment]
SGTM 👍  Let's have @kkalarickal do some smoke testing on this.

**Comment by kkalarickal** [comment]
@swissspidy @barklund - I did a full run through the `12929-branch` and compared it with the `master-branch` instance on another server. Here are some observations

- (as noted) help center button lacks icon. Also, I could not see the "show elements" tool at the lower part of the editor 

- when I clicked on the 3rd-party media, I could not see the "stock content disclaimer" pop up
- within the stadard text elements, the ordering of the different text sets has changed -- 
- font size of the page advancement buttons is different
- similarly the font size on the dsahboard page is also different
- there seem to be fewer preview pages visible
- for some reason, in the `12929-branch`, I am seeing more number of revisions for a new story as compared to creating the same story within the `main-branch`!
- the AM/PM and UTC elements are missing
- for some reason, I was not able to add a newly created story to a post while on the `12929-branch` on stories-qa server.

Apart from these observations, I was able to do a full end-to-end story creation and publishing workflow. I used different image formats, tested the creation and embedding of video/audio/shapes/colors/color-picker/background audio/closed-caption and did this via direct file upload and linking to an external URL.

I feel that the missing font size differences and some of the missing elements are the most important to fix in the `12929-branch` before it can be merged.

**Comment by barklund** [comment]
> * (as noted) help center button lacks icon. Also, I could not see the "show elements" tool at the lower part of the editor !

Can't reproduce, this should have been fixed.

> * when I clicked on the 3rd-party media, I could not see the "stock content disclaimer" pop up

I can see this dialog, if I try the plugin in an incognito browser window, so can't repro this either.

> * within the standard text elements, the ordering of the different text sets has changed 

I think the order is actually fairly random. If I view the main branch on QA and do a hard reload, the items are in slightly different order almost every time.

> * font size of the page advancement buttons is different!

I don't see that. Looks identical to me.

> * similarly the font size on the dashboard page is also different!

This one I do see. Fixed.

> * there seem to be fewer preview pages visible

Can't see this. Example?

> * for some reason, in the `12929-branch`, I am seeing more number of revisions for a new story as compared to creating the same story within the `main-branch`!

Hm, I don't fully understand this one? Where do you see this?

> * the AM/PM and UTC elements are missing!

The presence of AM/PM and UTC offset depend on WP settings. I see them fine on the new branch if settings allow it, and not if they don't.

> * for some reason, I was not able to add a newly created story to a post while on the `12929-branch` on stories-qa server.

Ah yes, this one is fixed now. Good find!

@kkalarickal can I get you to re-test just the above, and let's make sure you test the right version (it sounds a bit like you checked an earlier version of the PR).

**Comment by swissspidy** [comment]
Another Percy finding, the color picker seems to have disappeared in RTL mode:

Screenshot 2023-01-31 at 10 16 35

**Comment by barklund** [comment]
> Another Percy finding, the color picker seems to have disappeared in RTL mode:

Yeah, I noticed the karma failure for same seemed inconsistent, so checking it out.

**Comment by kkalarickal** [comment]
Hello @barklund - I tested with the updated PR and the differences in font are sorted out. Also, publish into a WP post works.

https://stories-qa-wordpress-amp.pantheonsite.io/re-test-12929-from-template/

I get your point about "The presence of AM/PM and UTC offset depend on WP settings" ... @swissspidy - on the https://stories-qa-wordpress-amp.pantheonsite.io/ test bed, it is NOT visible (either on Main branch or on 12929 branch)

The issue with more revisions seems to have resolved itself. Basically I was following the same steps on main branch and 12929 branch, but the 12929 branch story was showing double the number of revisions ! This is no longer happening.

I also see the issue with the color picker not appearing.

**Comment by kkalarickal** [comment]
Hello @barklund - I tested with the updated PR and the differences in font are sorted out. Also, publish into a WP post works.

https://stories-qa-wordpress-amp.pantheonsite.io/re-test-12929-from-template/

I get your point about "The presence of AM/PM and UTC offset depend on WP settings" ... @swissspidy - on the https://stories-qa-wordpress-amp.pantheonsite.io/ test bed, it is NOT visible (either on Main branch or on 12929 branch)

The issue with more revisions seems to have resolved itself. Basically I was following the same steps on main branch and 12929 branch, but the 12929 branch story was showing double the number of revisions ! This is no longer happening.

I also see the issue with the color picker not appearing.

**Review by swissspidy — APPROVED** [review]
