### PR TITLE
Pre-Publish Checklist: Bring back warning for Update button

### LINKED ISSUE #5972: Prepublish checklist tooltip on "publish" and "update" button disappeared
## Bug Description

This was fixed with #5532 in PR #5548 but it seems to have resurfaced. We need to bring back the tooltip as specified in the PR description, please reference that. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zachhale**
## Summary

Both Publish and Update buttons should trigger and show tooltip and warning icon if there are prepublish checklist errors.

image-1
image

## Relevant Technical Choices

This seemed to have gone away because of a feature flag being deprecated. I consolidated the logic between the update and publish icons in this PR to make this logic even more centralized.

## Testing Instructions

Test with both a draft and published story:

1. Create/open story with prepublish checklist errors
2. Hover over publish/update button and both a tooltip ("There are items in the checklist to resolve") and icon should show
3. Fix errors and re-hover over button. Icon and tooltip should go away.

---

Fixes #5972

### CODE REVIEW

File: assets/src/edit-story/components/header/buttons/update.js [hunk 1]
```diff
@@ -51,11 +48,7 @@ function Update() {
     state: { hasNewChanges },
   } = useHistory();
 
-  const { checklist, refreshChecklist } = usePrepublishChecklist();
-  const {
-    showPrePublishTab,
```
Comment (swissspidy) [inline assets/src/edit-story/components/header/buttons/update.js]: Ah, so this was forgotten in #5585?

File: assets/src/edit-story/components/header/buttons/update.js [hunk 2]
```diff
@@ -99,28 +92,13 @@ function Update() {
...
-  const tooltip = showPrePublishTab
-    ? checklist.some(({ type }) => PRE_PUBLISH_MESSAGE_TYPES.ERROR === type) &&
-      __('There are items in the checklist to resolve', 'web-stories')
-    : null;
-
-  const button = (
-    <Primary
-      onPointerEnter={refreshChecklist}
+  return (
+    <ButtonWithPrepublishChecklistWarning
```
Comment (swissspidy) [inline assets/src/edit-story/components/header/buttons/update.js]: This is a very explicitly named, yet quite a long component & file name.

Could we perhaps use something shorter like `ButtonWithWarning`?

Or maybe `Primary` / `prrimary.js` because it's the primary button in this section?

**Review by swissspidy — APPROVED** [review]
LGTM with one nit regarding naming

File: assets/src/edit-story/components/header/buttons/update.js (hunk 1 above)
Comment (zachhale) [reply assets/src/edit-story/components/header/buttons/update.js]: Appears so.

File: assets/src/edit-story/components/header/buttons/update.js (hunk 2 above)
Comment (zachhale) [reply assets/src/edit-story/components/header/buttons/update.js]: I had a hard time naming this. The one I was working with originally was `ButtonWithChecklistWarning` but didn't seem specific enough. That (preferably) or `ButtonWithWarning` like you suggest would be good.

Comment (zachhale) [reply assets/src/edit-story/components/header/buttons/update.js]: I named it `ButtonWithChecklistWarning`

**Review by embarks — APPROVED** [review]
LGTM, thanks Zach
