### PR TITLE
Background Audio: Do not always loop audio in the editor

### LINKED ISSUE #11046: Background Audio: Audio always loops when playing in the editor
## Bug Description

Originally reported by @BrookeGraham 
 in the design panel, if I uncheck the loop box, then hit the play button, the audio still loops until I hit the stop button. The loop checkbox does not impact the preview functionality as one would expect

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Ensure that the looping checkbox is respected by audio player. Ensure that play / pause button is reset when the audio player is finished. 

This change, also improves browser compatibility, as browsers like chrome allow for audio to be paused via media control or by media buttons on the keyboard.  

## User-facing changes

https://user-images.githubusercontent.com/237508/159926210-88ee5f41-4cbf-4f31-8cb3-d9d0bee499c5.mov

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a story
2. Add background audio to a page.
3. Set looping to disabled.
4. Play audio. 
5. When audio is finished, it should not loop and play / pause button should reset. 

#### Media controls
1. Create a story
2. Add background audio to a page.
3. Set looping to disabled.
4. Play audio. 
5. Use media controls in Chrome to pause audio. 
6. Play / pause button should reset. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11046

### CODE REVIEW

File: packages/story-editor/src/components/audioPlayer/index.js [hunk 1]
```diff
@@ -115,41 +144,21 @@ function AudioPlayer({ title, src, mimeType, tracks = [], audioId }) {
...
-              variant={BUTTON_VARIANTS.SQUARE}
-              aria-label={__('Play', 'web-stories')}
-              onClick={handlePlayPause}
-            >
-              <Icons.PlayFilled />
-            </StyledButton>
-          </Tooltip>
-        )}
-      </div>
+      <Tooltip
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/audioPlayer/index.js:147]: This part is not needed, but it a nice refactor, to stop lots of repeated code.

File: packages/story-editor/src/components/audioPlayer/index.js [hunk 2]
```diff
@@ -86,19 +91,43 @@ function AudioPlayer({ title, src, mimeType, tracks = [], audioId }) {
 
     if (isPlaying) {
       player.pause();
-      setIsPlaying(false);
     } else {
-      player
-        .play()
-        .then(() => setIsPlaying(true))
-        .catch(() => {});
+      player.play();
```
Comment (swissspidy) [inline packages/story-editor/src/components/audioPlayer/index.js]: `.play()` returns a Promise, which means it can get rejected. Which is why we'd need the `catch(() => {})` here to avoid throwing errors.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play

**Review by BrookeGraham — APPROVED** [review]
Looks great. Sounds even better 🔈

**Comment by timarney** [comment]
Nice -- works well

**Review by timarney — APPROVED** [review]
