### PR TITLE
Floating Menu: Fix Overlapping Section between 'colors' and 'more'.

### LINKED ISSUE #11018: Floating Menus: Overlapping 'Mixed' Input
## Bug Description

Found in bug bash by @samwhale  and confirmed by @BrittanyIRL 

Screen Shot 2022-03-22 at 10 34 49 AM

If a text element has more than 1 color it gets the 'mixed' input, this input overlaps with the 'more' button. If the input swaps to 'mixed' it should expand the allowed input space. This needs to happen for other languages too! 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Bug identified in bugbash today where if a color input is 'mixed' (2 colors or more in an element) then that color input overlaps the 'more' button. 

## Summary

Checks for multiple color value in color input to override set width, allowing input to expand when needed.

## Relevant Technical Choices

When color value is `MULTIPLE_VALUE` override the asked for width in the input so that 'mixed' (or whatever the translated version of that is) can take up its needed space. 

## User-facing changes

| Broken | Fixed | 
| --- | --- | 
| Screen Shot 2022-03-22 at 2 45 37 PM | Screen Shot 2022-03-22 at 2 46 28 PM | 

## Testing Instructions

This Color section I removed width from is shared by all the color inputs so some regression testing around the color inputs in the various areas of the editor will be necessary. The ones I checked and am aware of before submitting this for review: Floating menu elements, style panel for borders, background color, foreground color, text color combos.

color input change size

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11018

### CODE REVIEW

File: packages/story-editor/src/components/form/color/colorInput.js [hunk 1]
```diff
@@ -275,7 +275,10 @@ const ColorInput = forwardRef(function ColorInput(
                 {/* We display Mixed value even without inputs */}
                 {isMixed && (
                   <MixedLabel>
-                    <Text size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL}>
+                    <Text
+                      size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL}
+                      as="span"
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/form/color/colorInput.js:277]: no reason for a paragraph tag to live here, just updating to pass as a span.

File: packages/story-editor/src/components/form/color/color.js [hunk 2]
```diff
@@ -52,7 +52,6 @@ const containerCss = css`
 const Container = styled.section`
   ${containerCss}
   gap: ${({ isInDesignMenu }) => (isInDesignMenu ? 6 : 8)}px;
-  width: ${({ width }) => (width ? `${width}px` : `100%`)};
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/form/color/color.js:55]: If we remove the `width` override here, `width` should no longer be needed as a prop. BUT I added this because we were getting weird sizing on the input on other use cases in the floating menu without it.
Screen Shot 2022-03-22 at 4 03 52 PM

**Review by BrookeGraham — DISMISSED** [review]
This leaves the input as the wrong size in other places.

File: packages/story-editor/src/components/form/color/color.js (hunk 2 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/color/color.js:55]: ah drag!

File: packages/story-editor/src/components/form/color/color.js [hunk 3]
```diff
@@ -132,8 +135,17 @@ const Color = forwardRef(function Color(
       ? TOOLTIP_PLACEMENT.BOTTOM
       : TOOLTIP_PLACEMENT.BOTTOM_START;
 
+  // Sometimes the value of the set color is "(MULTIPLE)", this is the only time the color comes back a string not an object.
+  // When there's multiple colors the input displays "Mixed" (in english) and takes up a different amount of space.
+  // By checking here to ignore that value based on mixed colors we prevent overlaps in any language too.
+  const ignoreSetWidth = typeof value === 'string';
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/form/color/color.js]: 🤔 could we do the check in the floating menu  > elements > shared > color. Then just set the width appropriately for when value === string

Comment (BrookeGraham) [reply packages/story-editor/src/components/form/color/color.js]: 💭 would still have to account for translations though 🤔

Comment (swissspidy) [reply packages/story-editor/src/components/form/color/color.js]: We should directly compare with the `MULTIPLE_VALUE` / `MULTIPLE_DISPLAY_VALUE` constant in the editor, not just checking the type.

There's plenty of precedence in the editor for this kind of comparison.

File: packages/story-editor/src/components/form/color/color.js [hunk 4]
```diff
@@ -52,7 +52,8 @@ const containerCss = css`
 const Container = styled.section`
   ${containerCss}
   gap: ${({ isInDesignMenu }) => (isInDesignMenu ? 6 : 8)}px;
-  width: ${({ width }) => (width ? `${width}px` : `100%`)};
+  width: ${({ width, ignoreWidth }) =>
+    (ignoreWidth && 'inherit') || (width ? `${width}px` : `100%`)};
```
Comment (samwhale) [inline packages/story-editor/src/components/form/color/color.js]: 🤔  So this feels a little strange to me. The `Color` component takes a `width` prop, but if there's a "multiple" value then the component needs to ignore the passed in width.

I tried removing lines 55 and 56, as well as removing lines 145 (so that `width` isn't passed to the div. Seems to me like everything worked as intended? The color input looks the same in the floating menu and in the style pane.

It seems to me like letting the container decide its own width would work here, but lmk if I'm missing a case.

Comment (samwhale) [inline packages/story-editor/src/components/form/color/color.js]: If the `containerCss` has `display: flex` then I think `width: 100%` is redundant since flexbox will stretch the section to fill the parent too?

**Review by samwhale — APPROVED** [review]
Works locally for me. Just left a question about implementation

File: packages/story-editor/src/components/form/color/color.js (hunk 4 above)
Comment (maxyinger) [reply packages/story-editor/src/components/form/color/color.js]: no I think you're right. I think the width stuff within the floating menu is a little wonky. I think it's there for calculating the bounds of where we can place it, but then we also explicitly set it? I'm not sure what the purpose of explicitly setting the width is. also feels diffferent to need all the mutation observers we have there to gather this info, but I think I'm lacking some context 🤷

**Review by maxyinger — APPROVED** [review]

File: packages/story-editor/src/components/form/color/color.js (hunk 4 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/form/color/color.js]: >I tried removing lines 55 and 56, as well as removing lines 145 (so that width isn't passed to the div. Seems to me like everything worked as intended? The color input looks the same in the floating menu and in the style pane. 

Without exciplty setting it, the flex extends both containers where color is used. So we end up with extra wide `more` button and and extra wide opacity input. 

But, we could still use `inherit` instead of the extra prop. 

something like 
```
  width: ${({ width }) => (width ? `${width}` : `inherit`)};

```
Where `width` is string that contains units. eg. `width = "128px"`  or `width='inherit"` depend on if it is mixed or not. 

Screen Shot 2022-03-24 at 9 39 23 AM

Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/color/color.js]: ok, i think we're good here - removed the `100%` fallback and need for an extra prop.
