### PR TITLE
Reset opacity for newly added background elements

### LINKED ISSUE #1404: Opacity must be removed/reset when image is set as background
## Bug Description

When the user triggers "Set as Background" in the design panel, the opacity of the element should be reset to 100%. Unfortunately, that's not happening when using the "Set as Background" function. 

Note: It **does** work properly if I drag the the image to the blue-zone border to set as background. Just not when triggering the same function via the Design panel. 

## Expected Behaviour

Expected: image should be set as background without any opacity, opacity is not supported for backgrounds. 

## Steps to Reproduce

Steps to reproduce: 
- Add image to a story
- Change opacity to a <100% value (e.g., 50%)
- Click on "Set as Background" option

## Screenshots

Actual result: seeing background with weird transparency grid going on.

image
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ezxyz**
## Summary

setBackgroundElement also sets opacity to 100.

## Relevant Technical Choices

- Explained above.

Fixes #1404

### CODE REVIEW

File: assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js [hunk 1]
```diff
@@ -87,11 +87,13 @@ function setBackgroundElement(state, { elementId }) {
...
     }
 
-    // Reorder elements
+    // Reorder elements and set element opacity to 100% because backgrounds
+    // cannot be transparent.
     const newElements = moveArrayElement(pageElements, elementPosition, 0).map(
       (element) => {
         // Set isBackground for the element.
         if (element.id === elementId) {
+          element.opacity = 100;
```
Comment (swissspidy) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js]: Why not just

```js
return {
  ...element,
  opacity: 100,
  isBackground: true,
};
```

below?

**Review by swissspidy — APPROVED** [review]
LGTM with one nit

File: assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js (hunk 1 above)
Comment (ezxyz) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js]: Done.
