### PR TITLE
Adjust zoom

### LINKED ISSUE #4022: Zoom in/out of Canvas in editor
## Task Description

Allowing users to zoom in and out on the canvas area was previously mentioned when discussing accessibility requirements for the editor.

## Design
[Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2241%3A2)

## QA

1. Validate that without new experiment enabled, the canvas works as before with one exception: Lasso selection is off by a few pixels. All of this should be working: Dragging in elements, moving and resizing elements, dropping in drop target frames, dragging out of canvas to remove, text edit (also partially outside the canvas), media edit (also partially outside the canvas), canvas resize on browser resize, and more.

2. Validate that with the next experiment enabled, the canvas has a new fancier zoom functionality. This still has missing features to be done in upcoming PR's, but it generally works.

### PR DESCRIPTION
**Pull request by barklund**
This is per Slack convo to adjust zoom functionality as follows:

> We video chatted and summary:
> * Enforce top/btm padding to page for Fit
> * Remove 300% (can add later if users complain)
> * Add min padding to the thumbnail

This is a partial PR towards main PR to make it easier to review just the changes.

Fixes #4022

### CODE REVIEW

File: assets/src/edit-story/components/canvas/layout.js [hunk 1]
```diff
@@ -112,6 +121,21 @@ const PageAreaFullbleedContainer = styled(Area).attrs({
   }
 `;
 
+const ZOOM_PADDING = '72px';
```
Comment (miina) [inline assets/src/edit-story/components/canvas/layout.js:124]: Is this related to the `horizontalPaddingForFit` above?

File: assets/src/edit-story/components/canvas/layout.js [hunk 2]
```diff
@@ -171,7 +196,12 @@ function useLayoutParams(containerRef) {
     // space for the page is:
     const maxWidth = width;
     const maxHeight =
-      height - HEADER_HEIGHT - HEADER_SPACE - MENU_HEIGHT - CAROUSEL_HEIGHT;
+      height -
+      HEADER_HEIGHT -
+      HEADER_SPACE -
+      MENU_HEIGHT -
+      MENU_SPACE -
```
Comment (miina) [inline assets/src/edit-story/components/canvas/layout.js]: On naming: The `MENU_SPACE` is basically the extra margin the menu needs? Reading it at first it felt like `HEADER_SPACE` would be the full space the header takes and `MENU_SPACE` would be the full space the menu takes. But `HEADER_HEIGHT` could also mean the full height -- so the "space" must actually mean the extra margin/room that's needed?

Could we perhaps use `*_MARGIN` or `*_PADDING` instead of `*_SPACE` or/and create constants for the full heights of these two and use those instead here (e.g. `HEADER_SPACE = HEADER_HEIGHT + HEADER_MARGIN` or sth like that)?

File: assets/src/edit-story/app/layout/useZoomSetting.js [hunk 3]
```diff
@@ -59,12 +59,17 @@ function useZoomSetting() {
...
+          maxPageWidth =
+            (workspaceSize.height - verticalPaddingForFit) * FULLBLEED_RATIO;
         } else {
-          // workspace is limited in the width, so use the width
-          maxPageWidth = workspaceSize.width;
+          // workspace is limited in the width, so use the width - padding
+          maxPageWidth = workspaceSize.width - horizontalPaddingForFit;
         }
         break;
       }
```
Comment (miina) [inline assets/src/edit-story/app/layout/useZoomSetting.js:75]: The `TRIPLE` option is still here, should it be removed per the description of the issue?

**Comment by miina** [comment]
From testing:
- In case of size `100%`, on a smaller screen, it's still hard to understand when the page is ending:
- Same goes for `Fill`.

scrolling

Should there be some padding for those cases, too?

File: assets/src/edit-story/components/canvas/layout.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/layout.js]: Renamed to `_GAP`, good call. And the reason for the split is that they're not used together in the grid, so we need separate constants for it anyway.

File: assets/src/edit-story/components/canvas/layout.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/layout.js:124]: Actually not, not. This is the inner spacing added inside the scrollable element to make edges "stand out". And I'm checking with Sam if this is the proper value here.

File: assets/src/edit-story/app/layout/useZoomSetting.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/app/layout/useZoomSetting.js:75]: Removed in 8dfc43d.

**Comment by barklund** [comment]
> From testing:
> 
> * In case of size `100%`, on a smaller screen, it's still hard to understand when the page is ending:
> * Same goes for `Fill`.

Asked @samitron7 for direction.
