### PR TITLE
Editor: Fixed bugs when panning flipped background image

### LINKED ISSUE #10723: RTL: Background image - flip horizontally not working as expected
## Bug Description
Originally reported by  @BrookeGraham:
When selecting flip background horizontally, and you attempt to move the background, the image is backwards. 

## Additional Context

- Plugin Version:
background-flip

- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Summary

There was a weird bug when you had a flipped image and trying to pan it. It seemed a bit inconsistent and was reported as only a bug in RTL, but was actually a bug also in LTR.

The main confusion arises from the fact, that the problem only occurs on the second drag inside the pan- container. The problem occured with both vertical and horizontal flips.

This PR fixes this, by updating as soon as the contain loads (and removes the double-flipping of coordinates).

This also fixes a related issue, which occurred if flipping while already editing a background media element. The flipped image would only actually appear flipped once dragged at least one time after pressing the flip toggle.

## User-facing changes

| Direction | Before | After |
|-|-|-|
| LTR | bg-pan-ltr-before | bg-pan-ltr-after |
| RTL | bg-pan-rtl-before | bg-pan-rtl-afte |

## Testing Instructions

This PR can be tested by following these steps:

#### Panning a flipped background image
1. Add a background image (preferably landscape format)
2. Flip it (either and both directions)
3. Double-click the image to enter edit-mode
4. Pan the image right and left. Make sure to pan multiple times. Observe that panning works correctly
5. Do the above in both LTR and RTL writing modes

#### Flipping a background image while editing
1. Add a background image
2. Double-click the image to enter edit-mode
3. Click the flip-toggles in either the style panel or the floating design menu
4. Observe that flipping looks correct while in edit-mode
5. Do the above in both LTR and RTL writing modes

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10723

### CODE REVIEW

File: packages/element-library/src/media/editPanMoveable.js [hunk 1]
```diff
@@ -102,14 +104,7 @@ function EditPanMoveable({
...
       throttleDrag={0}
       onDrag={({ dist }) => {
-        let [tx, ty] = dist;
-        if (flip?.vertical) {
-          ty = -ty;
-        }
-        if (flip?.horizontal) {
-          tx = -tx;
-        }
-        translateRef.current = [tx, ty];
```
Comment (barklund) [inline packages/element-library/src/media/editPanMoveable.js:112]: Note that the flip toggles was taken into consideration twice in this file - once in `onDrag` and again in `onDragEnd`. By making sure to apply the correctly transform from the start, this stuff here is not necessary.

File: packages/element-library/src/media/editPanMoveable.js [hunk 2]
```diff
@@ -61,6 +61,8 @@ function EditPanMoveable({
     moveableRef.current?.updateRect();
   });
 
+  useEffect(update, [update]);
```
Comment (barklund) [inline packages/element-library/src/media/editPanMoveable.js:64]: This runs on load, but also if the flip toggles change while the edit-mode is mounted, which fixes the second bug mentioned.

**Review by merapi — APPROVED** [review]
It works flawlessly now, I tried to break it in every possible way - still strong 💪🏻  (can we skip QA if I did "Testing Instructions" and even more?).
