### PR TITLE
Workspace: SafeZone Toggle/Button A11y Improvements

### LINKED ISSUE #4245: A11Y: Safezone toggle should be a checkbox
## Bug Description

When using a screenreader and clicking the safe-zone toggle button, no information is given to the user, as this is "just" a button and not a real toggle. If it is instead implemented with a checkbox (like bold/italic/underline in the design panel), the user will be informed of the current state and changed state.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dmmulroy**
## Summary

Switch the SafeZone toggle from a Button to a Checkbox to improve A11y for screen readers. (Validated using WAVE extension for parity with other ToggleButton (checkbox buttons) in the editor)

## Relevant Technical Choices

Swapped using our default `Button` component to using our `ToggleButton` component (the same which is used in the design panel for bold/italic/underline toggles - thanks for the suggestion @barklund)

## User-facing changes

None

## Testing Instructions

- Validate that the toggle works correctly

---

Fixes #4245

### CODE REVIEW

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 1]
```diff
@@ -122,12 +123,7 @@ const buttonDimensions = { width: '24', height: '24' };
 
 const StyledGridViewButton = styled(GridViewButton).attrs(buttonDimensions)``;
 
-const SafeZoneButton = styled(SafeZone).attrs(buttonDimensions)`
-  ${({ active, theme }) =>
-    active &&
-    css`
-      background: ${rgba(theme.colors.bg.white, 0.1)};
-    `}
+const SafeZoneToggle = styled(ToggleButton).attrs(buttonDimensions)`
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js]: Percy is [detecting a slight difference](https://percy.io/google/web-stories-wp/builds/6678009/view/382686082?browser=chrome&mode=base&width=1600) between the button before and now - it's a bit bigger and differently aligned with respect to the button below.

Compare:

| Before | After |
|-|-|
| Screen Shot 2020-08-27 at 16 11 53 | Screen Shot 2020-08-27 at 16 11 59 |

I don't know which is right (if either), so please check with Figma.

Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js]: Also, the `buttonDimensions` here don't appear to make sense anymore, given that `ToggleButton` expects `iconWidth` and `iconHeight` props instead of `width` and `height`. The common object probably isn't necessary anymore and the two definitions should just be inlined:

```js
const StyledGridViewButton = styled(GridViewButton).attrs({ width: 24, height: 24 })``;
const SafeZoneToggle = styled(ToggleButton).attrs({ iconWidth: 24, iconHeight: 24 })` ...
```

Or alternatively, make the `ToggleButton` use the same props, but that requires refactoring a bunch more stuff I guess.

If changed either way, they can be removed [below](https://github.com/google/web-stories-wp/pull/4262/files#diff-9ca2523a045442855dbdd7218d0095acR479-R480).

Comment (dmmulroy) [reply assets/src/edit-story/components/canvas/carousel/index.js]: image

This should be resolved, the original was okay'd by Sam and the current implementation should now match.

**Review by BrittanyIRL — APPROVED** [review]
LGTM. Works as expected. Validated accessibility with axe as well as the dev tools accessibility tab.

**Review by barklund — APPROVED** [review]
Works perfectly, great effort!
