### PR TITLE
Nest page menu inside the canvas and support more return-to-canvas scenarios

### LINKED ISSUE #1852: Delete doesn't work immediately after undo
## Bug Description

If you undo a deletion, then press the del key right after, the element is not deleted. 

## Expected Behaviour

It should delete as usual.

## Steps to Reproduce

1. Add text element to page
2. Click on page to deselect the text element
3. Re-select the text element
4. Press delete key, see element get deleted
5. Press cmd+z or ctrl+z to undo, element reappears and is shown as selected
6. Press delete key again -- notice that the element is not deleted. 

Workaround: Need to deselect and re-select the item in order to delete. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dvoytenko**
Fixes #1852

Possibly an alternative to #2189 for #1781 (TBD).

Two main changes:
1. I moved page menu inside the frames layer. I judged that the affinity of the page menu is closer to the canvas, e.g. comparing to carousel.
2. The focus trapping code is a bit more aggressive now. The main reason for that is that DOM removals often result in somewhat unstable "focusout" events.

Notes on tests:
1. I had to remove "faux" body from the test. It was nice to have it, but with focus work, too many DOM APIs would need to be patched to keep it up.
2. There's an added nuance on `waitFor` in the test. This is necessary because a lot of our focusing logic is timer based. I don't see a way around this yet.
3. I noticed that the `fixture.renderHook` was unmounting/remounting the components it was rendering the hook for. It's completely unnecessary (and likely harmful), so I fixed that here as well.

### CODE REVIEW

File: assets/src/edit-story/karma/fixture.js [hunk 1]
```diff
@@ -303,9 +307,10 @@ class ComponentStub {
       );
 
       return (
-        <HookExecutor key={refresher} hooks={hooks}>
+        <>
+          <HookExecutor key={refresher} hooks={hooks} />
```
Comment (barklund) [inline assets/src/edit-story/karma/fixture.js:311]: Ah great - I actually ran into this many times and thought it was unavoidable, but awesome that you were able to fix it!

File: assets/src/edit-story/karma/fixture.js [hunk 2]
```diff
@@ -337,10 +342,12 @@ class ComponentStub {
   }
 }
 
-function HookExecutor({ hooks, children }) {
+/* eslint-disable react/prop-types, react/jsx-no-useless-fragment */
+function HookExecutor({ hooks }) {
   hooks.forEach((func) => func());
-  return children;
+  return <></>;
```
Comment (barklund) [inline assets/src/edit-story/karma/fixture.js:348]: Can't you just return `null`?

**Review by barklund — COMMENTED** [review]
Hm, I fail to see how this addresses the overall problem of returning focus to selected elements? Can you point more specifically to how it does that?

File: assets/src/edit-story/karma/fixture.js (hunk 2 above)
Comment (dvoytenko) [reply assets/src/edit-story/karma/fixture.js:348]: Yes, but there are warnings all over the place. So I figured an extra fragment is better than dozens of warnings in the console.

**Comment by dvoytenko** [comment]
> Hm, I fail to see how this addresses the overall problem of returning focus to selected elements? Can you point more specifically to how it does that?

`useCanvasKey`: I removed an extra check before returning focus. It's only incrementally aggressive for now - just to support obvious cases like DOM removals. So this pull request is NOT a fix for #1781 - just a preparation for it.

**Comment by dvoytenko** [comment]
@barklund 

>  So this pull request is NOT a fix for #1781 - just a preparation for it.

But it does fix #1852.

File: assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+
+      it('using page menu', async () => {
+        // Delete.
+        await fixture.events.keyboard.shortcut('del');
+        expect(getFrame()).toBeNull();
+        expect(await getSelection()).toEqual([]);
+
+        // Restore.
+        // @todo: Use either `workspace.pageMenu.undoButton` or
+        // `byRole('button', {name: 'Undo Changes'})` APIs.
```
Comment (miina) [inline assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js:108]: Is this todo for later or for this PR?

**Review by miina — APPROVED** [review]
Generally LGTM, makes sense that the Page menu belongs more to the Page than the carousel area.

File: assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js (hunk 3 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/karma/pageMenuActions.karma.js:108]: Yeah. I'm leaving the trail to do a follow up on all queries in the Karma tests.
