### PR TITLE
Embed block missing component ToolbarGroup in WP 5.3 

### LINKED ISSUE #5447: Embed block missing component ToolbarGroup in WP 5.3
## Bug Description

In WordPress 5.3, there is a missing component called `ToolbarGroup`. 

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.3
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

See https://github.com/google/web-stories-wp/issues/5447#issuecomment-734874801

## Testing Instructions

- Downgrade to WordPress 5.3
- Create post
- Create web stories block. 
- Input https://stories-new-wordpress-amp.pantheonsite.io/web-stories/auto-draft-9/ to field. 
- Click embed.

---

Fixes #5447

### CODE REVIEW

File: assets/src/story-embed-block/block/embedControls.js [hunk 1]
```diff
@@ -42,6 +35,12 @@ import { createRef, useCallback } from '@wordpress/element';
 
 const POSTER_ALLOWED_MEDIA_TYPES = ['image'];
 
+// eslint-disable-next-line react/jsx-no-useless-fragment
+const FallbackComponent = ({ children }) => <>{children}</>;
```
Comment (swissspidy) [inline assets/src/story-embed-block/block/embedControls.js]: Could even do just `const FallbackComponent = ({ children }) => children;` I suppose?

File: assets/src/story-embed-block/block/embedControls.js [hunk 2]
```diff
@@ -42,6 +35,12 @@ import { createRef, useCallback } from '@wordpress/element';
...
+
+const { Button, BaseControl, TextControl, PanelBody, PanelRow } = Components;
+const ToolbarGroup = Components.ToolbarGroup || FallbackComponent;
```
Comment (swissspidy) [inline assets/src/story-embed-block/block/embedControls.js:42]:
```suggestion
// ToolbarGroup is only available in Gutenberg 7.0 or later, so it does not exsit in WP 5.3.
const ToolbarGroup = Components.ToolbarGroup || FallbackComponent;
```

File: assets/src/story-embed-block/block/embedControls.js [hunk 3]
```diff
@@ -39,6 +39,7 @@ const POSTER_ALLOWED_MEDIA_TYPES = ['image'];
 const FallbackComponent = ({ children }) => <>{children}</>;
 
 const { Button, BaseControl, TextControl, PanelBody, PanelRow } = Components;
+// ToolbarGroup is only available in Gutenberg 7.0 or later, so it does not exsit in WP 5.3.
```
Comment (swissspidy) [inline assets/src/story-embed-block/block/embedControls.js]: Whoops I made a typo, apologies!

```suggestion
// ToolbarGroup is only available in Gutenberg 7.0 or later, so it does not exist in WP 5.3.
```

**Review by swissspidy — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
