### PR TITLE
Visual revamp: second pass (pills, slider, more)

### LINKED ISSUE #4058: 3P Media: Category background colour is incorrect
## Bug Description

When viewing categories within the 3P integration panel the background is blue

## Expected Behaviour

BG should be same (black)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
## Summary

Addresses [comments from the first pass](https://github.com/google/web-stories-wp/pull/3622#issuecomment-669222773) and continues implementing the new design.

## Relevant Technical Choices

N/A

## To-do

In future PRs: Icons, masonry design, moving the toolbar, background media changes.

#### Corrected colors
Corrected colors in multiple places to reflect [Sam's comments](https://github.com/google/web-stories-wp/pull/3622#issuecomment-669222773)

Screen Shot 2020-08-10 at 11 15 05 PM

#### Switch + Slider
Screen Shot 2020-08-10 at 11 15 19 PM

#### Pills + Tabs + Search
Screen Shot 2020-08-11 at 12 20 11 AM

#### Outlined shapes
Screen Shot 2020-08-11 at 12 53 53 AM

#### Text presets: more options
Screen Shot 2020-08-11 at 12 30 51 AM

## Testing Instructions

Visual changes should be present on the editor as well as on Storybook

---

Partial for #3641

See #4058
See #4061
See #4060

### CODE REVIEW

**Comment by carloskelly13** [comment]
Visually this looks good. 

image

Controls have clear focus elements

image

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js [hunk 1]
```diff
@@ -50,9 +52,22 @@ const CategoryPillContainer = styled.div`
...
+  position: absolute;
+  bottom: -12px;
+  background: ${({ theme }) => theme.colors.fg.gray16};
+  border-radius: 50px;
+  min-width: 32px;
+  min-height: 32px;
+  max-width: 32px;
+  max-height: 32px;
+  width: 32px;
+  height: 32px;
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js]: nit: since width and height are the same as their min/max you could just use width/height and eliminate the min/max unless there is a use case I am not aware of here :)

File: assets/src/edit-story/components/rangeInput/index.js [hunk 2]
```diff
@@ -30,14 +30,19 @@ const rangeThumb = css`
...
-  background-color: ${({ theme }) => theme.colors.fg.v1};
+  background-color: ${({ theme }) => theme.colors.fg.primary};
   cursor: pointer;
   border-radius: 50px;
   box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
 `;
 
 const focusedRangeThumb = css`
-  background-color: ${({ theme }) => theme.colors.action};
+  border: 2px solid #8ab4f8;
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/rangeInput/index.js]: Does this color have a theme value?

File: assets/src/edit-story/components/rangeInput/index.js [hunk 3]
```diff
@@ -47,7 +52,7 @@ const Input = styled.input.attrs({
   min-width: 100px;
   cursor: pointer;
   outline: none;
-  background: #fff4;
+  background: #2f3131;
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/rangeInput/index.js]: same here, is there a reason for not using `theme`?

**Review by BrittanyIRL — COMMENTED** [review]
This is looking great! One small nit/general question about theme process.

**Comment by barklund** [comment]
@googlebot I consent.

File: assets/src/edit-story/components/rangeInput/index.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/rangeInput/index.js]: Fixed in bfc43f74a. It's the ["Gray 8" foreground color](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Book?node-id=1286%3A457075), but it was missing in the theme, now added.

File: assets/src/edit-story/components/rangeInput/index.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/rangeInput/index.js]: Fixed in bd83ceeaa. It's the [secondary accent color, _"Biru"_](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Book?node-id=1286%3A457075).

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js]: Cleaned it up in 6d47912c4.

The `max-height` is necessary to overrule the `max-height: 30px` from [the base button class](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/button/index.js#L51). I think @wassgha just added them all to be safe in his frustration over the button insisting on having the wrong size 😂

Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js]: ah, that's good context! 

Since this is foundational work for the new design system, is it worth considering eliminating the max-height on the base if it's going to be consistently overridden?

File: assets/src/edit-story/components/library/text/fontPreview.js [hunk 4]
```diff
@@ -35,15 +35,15 @@ const PREVIEW_EM_SCALE = ALLOWED_EDITOR_PAGE_WIDTHS[0] / PAGE_WIDTH;
...
+  padding: 12px 16px;
   margin-bottom: 12px;
   border-radius: 4px;
   display: flex;
-  justify-content: center;
   align-items: center;
   width: 100%;
   border: none;
   cursor: pointer;
+  text-transform: unset;
```
Comment (miina) [inline assets/src/edit-story/components/library/text/fontPreview.js]: Curious what's this for here?

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js [hunk 5]
```diff
@@ -58,14 +55,20 @@ const CategoryPillInnerContainer = styled.div`
...
-}))`
-  ${(props) => props.isExpanded && 'transform: matrix(1, 0, 0, -1, 0, 0);'};
-  visibility: ${(props) => (props.visible ? 'inherit' : 'hidden')};
+const ExpandButton = styled(ArrowDown)`
+  display: flex;
+  position: absolute;
+  bottom: -12px;
+  background: ${({ theme }) => theme.colors.fg.gray16};
+  max-height: none;
+  width: 32px;
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js:75]: Width and height are also params for `ArrowDown` directly.

Same goes for `visibility` which could be used via `isHidden`.

File: assets/src/edit-story/components/library/panes/media/media3p/providerTab.js [hunk 6]
```diff
@@ -26,11 +26,20 @@ import { useKeyDownEffect } from '../../../../keyboard';
...
-  border-bottom: ${({ theme, active }) =>
-    active ? `solid 4px ${theme.colors.accent.primary};` : 'none'};
+  text-align: center;
+  opacity: 0.86;
+  cursor: pointer;
+  white-space: nowrap;
+  text-overflow: ellipsis;
+  padding: 6px 16px;
+  color: ${({ active, theme }) =>
+    active ? theme.colors.bg.workspace : theme.colors.bg.divider};
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/media/media3p/providerTab.js]: These pills don't really seem to match the design:
In the editor:
Screenshot 2020-08-20 at 18 15 17

From Figma:
Screenshot 2020-08-20 at 18 15 06

The category pills seem to be smaller (should be higher) in the implementation compared to Figma.

Also, would it make sense to use the same base component for these two? The text part at least seems to partially match (line-height, default color, etc.)

File: assets/src/edit-story/components/library/panes/shapes/shapePreview.js [hunk 7]
```diff
@@ -34,13 +34,28 @@ const PREVIEW_SIZE = 36;
 
 const ShapePreviewContainer = styled.button`
   background: transparent;
-  border: 0;
+  border: 1px solid ${({ theme }) => theme.colors.fg.gray16};
+  border-radius: 4px;
   position: relative;
-  padding: 0.8em 0.5em;
+  margin: 0.8em 0.5em;
   flex: 0 0 25%;
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/shapes/shapePreview.js]: I assume 25% means there should be 4 shapes in a row (per old design it should be so, couldn't find the new design for that, where could that be?) -- however, currently there's other stuff (such as the scrollbar sometimes / margin) taking room and it ends up being 3 on a row with extra room on the right side:
Screenshot 2020-08-20 at 18 32 48

File: assets/src/edit-story/components/library/text/fontPreview.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/library/text/fontPreview.js]: Removed irrelevant css in 96d61f2ee.

File: assets/src/edit-story/components/library/panes/shapes/shapePreview.js (hunk 7 above)
Comment (barklund) [reply assets/src/edit-story/components/library/panes/shapes/shapePreview.js]: Fixed layout in 6008c7504. Used hard pixel values as we don't have proper responsive layout anyway.

File: assets/src/edit-story/components/library/panes/media/media3p/providerTab.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/media3p/providerTab.js]: Fixed the CSS in 422d83444 to better reflect the design. Actually the two pills are annoyingly different, but based them off a common css component now.

File: assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/media3p/media3pCategories.js:75]: Actually this couldn't really be done much better - both because `visibility` has to be `inherit` and not `visible` and as it makes sense to have width and height defined here rather than elsewhere.

**Review by merapi — APPROVED** [review]
It's not yet pixel perfect, but given it's just a second pass and we want to merge often - ✅ 

Some of the clear visual differences in sliders:
Figma:
image
image

Editor:
image

**Review by miina — APPROVED** [review]
Much better now. As Marcin mentioned, the sliders need some changes indeed but OK to defer to the next iteration.

File: assets/src/edit-story/components/library/panes/text/textPresets.js [hunk 8]
```diff
@@ -88,6 +103,30 @@ const PRESETS = [
...
+      x: DEFAULT_LEFT_MARGIN,
+      y: (PAGE_HEIGHT - dataFontEm(1)) / 2,
+      font: TEXT_ELEMENT_DEFAULT_FONT,
+      width: DEFAULT_ELEMENT_WIDTH,
+    },
+  },
+  {
+    title: __('OVERLINE', 'web-stories'),
+    element: {
+      content: __('OVERLINE', 'web-stories'),
```
Comment (swissspidy) [inline assets/src/edit-story/components/library/panes/text/textPresets.js:121]: Ideally these strings aren't capitalized themselves but styled via CSS. Something for the next iteration.

**Review by swissspidy — APPROVED** [review]
Let's get this in!
