### PR TITLE
Restore Global Keyboard Workspace Focus Shortcut

### LINKED ISSUE #10793: Canvas elements cannot be focused/selected
## Bug Description

Elements on the Canvas cannot be selected via keyboard shortcut (Workspace) or via tabing.

image

## Steps to Reproduce

Insert any element and press ESC to deselect it, try to re-select the element with keyboard only.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

We have a global keyboard shortcut for `mod+option+2` that should focus the canvas. 

## Summary

Global keyboard shortcut to focus canvas/workspace broke, this fixes it. 

## Relevant Technical Choices

Move global keyboard shortcut into `canvas/frameLayers` from `canvas/useCanvasFocus` because frameLayers is where the canvas focus otherwise lives. 

Add a karma test to avoid future regressions of the same. 

## To-do

Noticed while working on this that the `mod+option-1` shortcut that should go to the `Element Library Selection` doesn't work every time. Probably something to do with the sidePanel updates. Will verify and make a new ticket if one doesn't already exist. 

## User-facing changes

Should restore `mod+option+1` shortcut to focus canvas

Kapture 2022-04-22 at 12 01 49

## Testing Instructions

Check that focusing workspace (canvas) from global keyboard shortcut is restored. 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10793

### CODE REVIEW

File: packages/story-editor/src/components/canvas/useFocusCanvas.js [hunk 1]
```diff
@@ -37,13 +37,6 @@ function useFocusCanvas() {
     });
   }, []);
 
-  // Globally listen for Cmd+Option+2 / Ctrl+Alt+2 for focus
-  useGlobalKeyDownEffect(
-    { key: 'mod+option+2', editable: true },
-    () => focusCanvas(true),
-    [focusCanvas]
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/canvas/useFocusCanvas.js:44]: remove from import

Comment (BrittanyIRL) [reply packages/story-editor/src/components/canvas/useFocusCanvas.js:44]: oh whoops!
