### PR TITLE
Fix Page menu and Page nav button focus

### LINKED ISSUE #7813: Page menu / navigation buttons' focus outline cut off
## Bug Description
There isn't enough space currently for displaying the focus outline for the buttons below the Page / Page navigation buttons.

## Expected Behaviour
Focus outline should be fully visible

## Steps to Reproduce
Tab into Page buttons / navigation

## Screenshots
Screenshot 2021-06-03 at 10 16 27
Screenshot 2021-06-03 at 10 16 10

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Adds extra space for the buttons surrounding the Page so that when the buttons are in focus state, the focus outline is fully visible and not cut off.

## User-facing changes
| Before | After |
| -------|----- |
| Screenshot 2021-09-23 at 15 21 51 | Screenshot 2021-09-23 at 15 20 59 |
| Screenshot 2021-09-23 at 15 21 45 | Screenshot 2021-09-23 at 15 20 49 |

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Focus on the Page navigation arrows using keyboard. Verify the focus outline is fully visible.
2. Focus on the Page menu buttons below the page. Verify the focus outline is fully visible.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7813

### CODE REVIEW

File: packages/story-editor/src/components/canvas/layout.js [hunk 1]
```diff
@@ -49,10 +49,12 @@ export const Z_INDEX = {
 };
 
 const HEADER_GAP = 16;
-const MENU_HEIGHT = THEME_CONSTANTS.ICON_SIZE;
+// 8px extra is for the focus outline to display.
+const MENU_HEIGHT = THEME_CONSTANTS.ICON_SIZE + 8;
```
Comment (barklund) [inline packages/story-editor/src/components/canvas/layout.js:53]: Doesn't that increase the gap between the page and the menu icons and similar between the menu icons and the carousel? Don't we need to reduce the gap on either side of the menu by 4 then?

Comment (miina) [reply packages/story-editor/src/components/canvas/layout.js:53]: Changed.

**Review by merapi — APPROVED** [review]
🚢
