### PR TITLE
Design System: Fix commented out tests (Dropdown)

### LINKED ISSUE #5764: Design System: Set up ability to test global keyboard hook events
## Feature Description

As we make progress on implementing the new design system that can be a source of truth for UI of editor and dashboard, we are pulling in some existing utils that have served the project extremely well the last year. One of these is the global keyboard hook that handles events and helps manage focus given the complexity of the editor. 

In the design system we need a way to be able to unit test keyboard events that utilize these hooks. Currently, we can't. 

This ticket is to create a mock of `useKeyDownEffect` in src/design-system and implement the three commented out tests in `src/design-system/components/dropDown/tests/dropDown`. 

## Alternatives Considered

Karma testing for keyboard events using the global hook would also serve us well, but since this hook is currently only used in storybook in the design system, I feel like we would benefit from a way to mock this in our unit tests before getting to the point where Karma tests can be implemented. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Cleaning up some tests.

## Summary

Enables commented out tests for the dropdown menu.

## Relevant Technical Choices

Ticket says:

>This ticket is to create a mock of useKeyDownEffect in src/design-system and implement the three commented out tests in src/design-system/components/dropDown/tests/dropDown.

Turns out we don't need a mock to make it work. [The fix was to include the keycode as well under the `which` property.](https://spectrum.chat/testing-library/help-react/fireevent-keypress-not-working-with-mousetrap~b002b180-6ad5-4363-b6d3-b4a1479d056c)

## To-do

n/a

## User-facing changes

n/a

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5764

### CODE REVIEW

File: packages/design-system/src/components/dropDown/test/dropDown.js [hunk 1]
```diff
@@ -250,137 +250,121 @@ describe('DropDown <DropDown />', () => {
...
+      expect(menu).toBeInTheDocument();
+
+      const menuItems = screen.getAllByRole('option');
+      expect(menuItems).toHaveLength(12);
+
+      // first element in menu should have focus
+      expect(menuItems[0]).toHaveFocus();
+
+      // focus second element in menu
+      fireEvent.keyDown(menuItems[1], { key: 'ArrowDown', which: 40 });
```
Comment (samwhale) [inline packages/design-system/src/components/dropDown/test/dropDown.js:283]: Very subtle but the fix for these tests was to include `which: {keycode}` so that the `MouseTrap` picked up the event.

Comment (BrookeGraham) [reply packages/design-system/src/components/dropDown/test/dropDown.js:283]: Awesome find.

**Review by BrookeGraham — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
hurray! glad this turned out to be so straightforward
