### PR TITLE
Saved Page Templates: fix repeated image uploads

### LINKED ISSUE #10787: Saved Page Templates: Multiple images uploaded to WordPress
## Bug Description

We've received two reports in the support forum about multiple images for saved page templates being uploaded in `/wp-content/uploads/ `folder on the server. The purpose of this ticket is to track the reports and begin investigating the issue. 

## Expected Behaviour

Multiple images should not be generated.

## Steps to Reproduce

The steps to reproduce this issue are not clear at the moment.

## Additional Context

https://wordpress.org/support/topic/template-images-duplicates-in-uploads-folder/
https://wordpress.org/support/topic/duplicate-custom-template-images-in-uploads-folder/#post-15420708

- Plugin Version: 1.18.0
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

As per #10787, the list of saved templates in the `LibraryProvider` is not updated after uploading the featured image for a saved page template.

That causes the repeated image uploads due to stale data.

## Summary

Fix repeated image uploads by uploading state in the provider after uploading the featured image.

## Relevant Technical Choices

* Added a new `updateSavedTemplate` callback to allow updating a single saved template in the existing state.

## To-do

* Maybe add tests? Not sure how best to test this.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go the Templates tab
2. Save current page as template
3. Observe HTTP requests to `wp-json/web-stories/v1/media`, notice image being uploaded
4. Go to another tab, e.g. Media
5. Switch back to Templates tab
6. There should be no new HTTP requests due to media uploads

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10787

### CODE REVIEW

File: packages/story-editor/src/components/library/libraryProvider.js [hunk 1]
```diff
@@ -80,6 +80,21 @@ function LibraryProvider({ children }) {
...
+    _setSavedTemplates((_savedTemplates) => {
+      return _savedTemplates.map((t) => {
+        if (t.templateId === template.templateId) {
+          return {
+            ...t,
+            ...template,
+          };
+        } else {
+          return t;
+        }
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/library/libraryProvider.js]: Nit pic

```suggestion
        }
        return t;
```

**Review by spacedmonkey — APPROVED** [review]

**Review by merapi — APPROVED** [review]
Felipe asked some questions about this fix, in the process of checking the answer I did my own QA round - it works as expected 👍🏻
