### PR TITLE
E2E Tests: Fix flakey Web Stories widget block test

### LINKED ISSUE #8402: Web Stories widget block e2e test is very flakey
## Bug Description
```
  ● Web Stories Widget Block › should insert a new web stories block

    TimeoutError: Element div.components-card__body (text: "Story URL") not found

      waiting for function failed: timeout 1000ms exceeded
```

https://github.com/google/web-stories-wp/runs/3107827213?check_suite_focus=true#step:13:13

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8402

### CODE REVIEW

File: packages/e2e-tests/src/specs/wordpress/blockWidget.js [hunk 1]
```diff
@@ -36,18 +36,16 @@ describe('Web Stories Widget Block', () => {
...
-  it.skip('should insert a new web stories block', async () => {
+  it('should insert a new web stories block', async () => {
     await visitBlockWidgetScreen();
     await expect(page).toClick('button[aria-label="Add block"]');
     await page.type('.block-editor-inserter__search-input', 'Web Stories');
     await expect(page).toClick('button span', { text: 'Web Stories' });
 
     await page.waitForSelector('.web-stories-block-configuration-panel');
-    await expect(page).toMatchElement('.web-stories-block-configuration-panel');
+    await expect(page).toClick('.web-stories-block-configuration-panel');
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/wordpress/blockWidget.js:46]: The reason this works, is the block inserter in widget edit, doesn't auto focus to newly inserted blocks. This click on the block, forces focus on the block.

File: packages/e2e-tests/src/specs/wordpress/blockWidget.js [hunk 2]
```diff
@@ -36,18 +36,16 @@ describe('Web Stories Widget Block', () => {
...
 
-    await expect(page).toClick('button', { text: 'Story URL' });
+    await expect(page).toClick('button[aria-label="Embed a visual story."]');
```
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/wordpress/blockWidget.js:48]: This changed after https://github.com/google/web-stories-wp/pull/8339

**Review by swissspidy — APPROVED** [review]
Nice! Thanks for fixing.

Fingers crossed that it doesn't flake on us again 🤞
