### PR TITLE
Make background overlay editable

### LINKED ISSUE #1207: Change pattern for background media overlay
## Feature Description

It is currently possible to add a (semitransparent) overlay to a background image or video, but you cannot control this overlay in terms of color, opacity, color stops or gradient direction.

This will be partially solved by #403 allowing users to directly manipulate gradients on the canvas using handles (will allow manipulating size, position and rotation), but color changes has to be done using a color picker.

This feature is about adding a color picker for the background overlay, when an overlay is selected. It will be possible to change the type of overlay (solid, linear, radial) from inside the color picker, and the overlay display must react to this.

With no background overlay, no color picker is shown:
Screen Shot 2020-04-14 at 2 56 49 PM

With background overlay set to something other than "none", color picker is shown:
Screen Shot 2020-04-14 at 2 56 45 PM

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Change `backgroundOverlay` on a page to be of type `Pattern` rather than the current Overlay enum.
* When clicking either of the buttons to select an overlay type, select a preset pattern similar to what is currently rendered for the overlay types.
* When a background overlay is set, add a color input component, that will open a color picker to update the color.
* Make sure to reflect the current pattern type in the select button in the overlay panel (might need to add a conic overlay type **or** configure color picker to not have conic gradient type for this specific value)
* The tricky thing here is when the user changes overlay type by pressing the buttons directly in the overlay panel. I suggest the following logic:
* * when switching from gradient to solid, use first color stop as solid color and gradient alpha as solid color alpha component (multiplied with any alpha already present on first color).
* * when switching from gradient to gradient, reuse stops,
* * when switching from solid to gradient, use solid color at alpha=0 as pos=0 and solid color at alpha=1 pos=1 color for gradient, and use solid color alpha component as gradient alpha.

### Migration
1. Before applying this PR, create a new story with 3 pages each with a background image, one with solid overlay, one with linear overlay and one with radial overlay
1. Migrate to this PR
1. See that all three pages still have the correct overlays
1. Do notice, that the radial overlay has changed slightly to a smoother and more round vignette.

### Edit overlay
1. Add a non-none background overlay to an image
1. Observe that you now can fully edit the color (and/or gradient) of the background overlay

Please report any errors that occur when playing around with overlays switching between types, etc. Note that the rules for switching between types are a bit complex, but very specifically designed to be exactly the way they are now (barring bugs).

### LINKED ISSUE #1214: Fix Radial Overlay
## Bug Description

@samitron7 to add prototype

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

See #1207.

### LINKED ISSUE #1653: Improve default radial gradient overlay
Can we make the radial gradient look more like this or a vignette filter. 

Desired CSS for default radial gradient:

```css
background-image: radial-gradient(80% 50% at center, #0000 25%, #000)
```

## QA Instructions
See #1207.

### PR DESCRIPTION
**Pull request by barklund**
## Summary

This PR makes the background overlay editable.

This PR also reorganizes the background overlay to belong to the background element rather than page. This change is in order to allow a background element to be copied to another page and keep its overlay.

## To-do

- [x] Convert background overlay to a pattern rather than enum
- [x] Make migration from old enum to new pattern
- [x] Use better default radial style
- [x] Make quick buttons work with new pattern
- [x] Associate background overlay with background element rather than page
- [x] Use new background overlay structure for display and output components
- [x] Make color input show "transparent" color behind current swatch
- [x] ~Copy background overlay to new background element when applicable~
- [x] Reset background overlay when switching background element
- [x] Remove any trace over background overlay from element when detached from background
- [x] Unit test overlay conversion functions
- [x] Integration test background overlay functionality
- [x] Add QA testing instructions

## User-facing changes

1. Nicer default radial overlay
1. Overlay never persists when changing background image (and is removed when removing background image)
1. If overlay is set, then an option to edit the overlay color and gradient structure is shown

## Testing Instructions

---

Solves #1207
Solves #1214
Solves #1653

### CODE REVIEW

**Comment by miina** [comment]
It would be awesome do have color presets for overlays, too. Thoughts? Needs a UX decision, I suppose.

**Comment by miina** [comment]
It's a bit odd that unsetting a background removes the overlay of the page. It feels like the overlay belongs to a Page (if Media would allow Overlay without being a background, too, it would be another story)

Otherwise, if I create an overlay and then remove that background media (without replacing it immediately), the overlay disappears, too.

Also, it's a bit unexpected that if I remove an element as background, previously having set the overlay, then copy it to some other page as a non-background element (and perhaps forget about it for a few hours or days) and then assign it as background, it suddenly has the overlay with it.

Another case: if I create an overlay, remove the 1st media as background -> add 2nd media, add a new overlay. Then unset 2nd Media (via the button) and set the 1st Media again, the 1st Overlay is added. However, in case of drag-drop background switch (or switching immediately), the 2nd overlay would remain.

I tried to find UX information about it but couldn't find detailed information currently, nor from the product spec, perhaps it's actually defined already and it's just me finding it unexpected.

_Read [the specs](https://docs.google.com/document/d/1EQ12sD4a1plmMeBu7YMWOdUSg0FeegB9qi2_OlV3Tp0/edit?pli=1#) meanwhile_

... and saw that the overlay should not display at all for an empty Page.

The cases above still seem unexpected though.

 Thoughts?

**Comment by barklund** [comment]
> It's a bit odd that unsetting a background removes the overlay of the page. It feels like the overlay belongs to a Page (if Media would allow Overlay without being a background, too, it would be another story)
> 
> Otherwise, if I create an overlay and then remove that background media (without replacing it immediately), the overlay disappears, too.

Non-media backgrounds cannot have overlays. It's a bug that it's an option to be fixed in #1177.

> Also, it's a bit unexpected that if I remove an element as background, previously having set the overlay, then copy it to some other page as a non-background element (and perhaps forget about it for a few hours or days) and then assign it as background, it suddenly has the overlay with it.
> 
> Another case: if I create an overlay, remove the 1st media as background -> add 2nd media, add a new overlay. Then unset 2nd Media (via the button) and set the 1st Media again, the 1st Overlay is added. However, in case of drag-drop background switch (or switching immediately), the 2nd overlay would remain.

I haven't fully implemented this feature yet - including removing overlay property from element when unset as background and copying overlay from old background to new background when changing background.

Once those are done, these scenarios disappear.

**Comment by barklund** [comment]
> It would be awesome do have color presets for overlays, too. Thoughts? Needs a UX decision, I suppose.

Let's leave that as a future optimization if desired.

**Comment by miina** [comment]
> Once those are done, these scenarios disappear

Alright, the 2. point made me think these scenarios would happen:
> Overlay persists when changing background image (but is removed when removing background image)

**Comment by barklund** [comment]
> > Once those are done, these scenarios disappear
> 
> Alright, the 2. point made me think these scenarios would happen:

The attribute exists on the element, but follow the page - unless the element is copied to another page, then it'll follow the element. It's a bit complex, but the best possible way to do it IMHO.

**Comment by miina** [comment]
> The attribute exists on the element, but follow the page - unless the element is copied to another page, then it'll follow the element. It's a bit complex, but the best possible way to do it IMHO.

An alternative could be always following the Page by the overlay but having a special Copy-Paste handler if the copied element is a background element (it'll need some special handling anyway).

**Comment by barklund** [comment]
> An alternative could be always following the Page by the overlay but having a special Copy-Paste handler if the copied element is a background element (it'll need some special handling anyway).

I thought about that, but wasn't confident that I could actually make that work. I intended to actually only special-handling the paste event, not the copy/cut event. But if that's possible (inserting background overlay on copy/cut), that's a much better solution actually.

Is that possible? Do we do something similar today?

**Comment by miina** [comment]
> Is that possible? Do we do something similar today?

We have `addElementsToClipboard` which generates what's being saved into ~pasted~ copied data, and then we have `processPastedElements` used by `elementPasteHandler` which processes the elements to be pasted. We should be able to add any extra overlay data to the clipboard when copying and use it to add the overlay when pasting. Thoughts?

**Comment by barklund** [comment]
> We have `addElementsToClipboard` which generates what's being saved into pasted data, and then we have `processPastedElements` used by `elementPasteHandler` which processes the elements to be pasted. We should be able to add any extra overlay data to the clipboard when copying and use it to add the overlay when pasting. Thoughts?

Hm interesting. I'll see what I can use here - it would make a lot more sense for the background overlay to be a property of the page. I only did this because of the copy-paste thing.

File: assets/src/edit-story/output/page.js [hunk 1]
```diff
@@ -59,21 +64,19 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
         <amp-story-grid-layer template="vertical">
           <div className="page-background-area" style={backgroundStyles}>
             {backgroundElements.map((element) => (
-              <OutputElement key={'el-' + element.id} element={element} />
+              <OutputElement key={element.id} element={element} />
+            ))}
+            {backgroundOverlays.map((element) => (
+              <div
+                key={element.id}
```
Comment (dvoytenko) [inline assets/src/edit-story/output/page.js]: This looks to be making duplicate keys. Not super critical for output, but perhaps we should still give them prefix?

**Review by dvoytenko — APPROVED** [review]
LGMT with one ask.

File: assets/src/edit-story/output/page.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/output/page.js]: Keys are a react thing, they are never going in the DOM. And React keeps track of the keys of the items of each list separately. So there's nothing to worry about here.

Comment (dvoytenko) [reply assets/src/edit-story/output/page.js]: Sure. But React expects them to be unique across the children of a component, and in this case they are not?

Comment (barklund) [reply assets/src/edit-story/output/page.js]: I'm pretty sure they only have to be unique within their respective arrays. After JSX this become 

```js
React.createElement('div', {attrs}, [{key: 1, ....}, {key: 2, ....}], [{key: 1, ....}, {key: 2, ....}]);
```

So React knows fully well, that each array is a separate set of children - and only uses the keys within each array to make sure they are reused when relevant. I could be wrong here, but I've never seen any errors with this.

See e.g. [this example](https://codepen.io/barklund/pen/RwWvBWx?editors=0010) modified from [this React guide](https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings) where no warnings are given in my pen even though the keys of the two arrays are "direct" siblings (but in separate lists of nodes).

Comment (dvoytenko) [reply assets/src/edit-story/output/page.js]: oh yeah. that makes sense. thanks!

**Comment by barklund** [comment]
I've updated this with the new rules about background overlay persistence as agreed upon. Beware there's some conflicts between this one and #1878. I recommend merging #1878 first, then updating this one.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js [hunk 2]
```diff
@@ -55,11 +54,12 @@ function setBackgroundElement(state, { elementId }) {
 
     const defaultBackgroundElement = page.defaultBackgroundElement;
 
-    // Unset isBackground for the element, too.
+    // Unset isBackground and backgroundOverlay for the element, too.
```
Comment (miina) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js:58]: Is it confirmed that the overlay should not be stored for the media at all? With this logic, when the user clicks "Remove as background" and then "Set as background" right after, the overlay is gone. Is that the expected behavior?

Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/setBackgroundElement.js:58]: Sorry, forgot to reply here, but yes that is the expected behaviour. It would be weird if the overlay stuck around while not visible.

File: assets/src/edit-story/migration/migrations/v0022_convertOverlayPattern.js [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+  return {
+    pages: pages.map(convertPage),
+    ...rest,
+  };
+}
+
+function convertPage({ elements, backgroundOverlay, ...rest }) {
+  const hasNonTrivialOverlay =
+    backgroundOverlay &&
+    ['solid', 'linear', 'radial'].includes(backgroundOverlay);
```
Comment (miina) [inline assets/src/edit-story/migration/migrations/v0022_convertOverlayPattern.js]: Hmm, which would be the values here for trivial overlays? Just `none`?

Comment (miina) [reply assets/src/edit-story/migration/migrations/v0022_convertOverlayPattern.js]: Or is this for the case if there should for some odd reason be an invalid background overlay value present?

File: assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+      // use "opaque'st" stop as primary color, but fix alpha at .3
+      const { stops } = currentOverlay;
+      const stopsByAlpha = stops.sort(
+        (x, y) => (y.color.a ?? 1) - (x.color.a ?? 1)
+      );
+      const {
+        color: { r, g, b },
+      } = stopsByAlpha[0];
+      return {
+        color: { r, g, b, a: 0.3 },
```
Comment (miina) [inline assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js:42]: Why do we fix alpha at .3?
In this case, the following would happen:
1. The user sets solid overlay with opacity 80%.
2. Then the user clicks on "radial".
3. The user changes her mind, clicks "Solid" again -- suddenly the opacity is 30% instead of the original 80%.

Shouldn't the same overlay type stay as it was before when clicking through different overlay types?

Thoughts?

Comment (barklund) [reply assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js:42]: I felt it was an appropriate handling when playing with it. But it's an open question. Let's punt that for future discussion once we get some feedback.

File: assets/src/edit-story/migration/migrations/v0022_convertOverlayPattern.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/migration/migrations/v0022_convertOverlayPattern.js]: Yeah, it's because any other value than those three would make other stuff misbehave. But yes, `'none'` is the only other legal option, that should be possible.

File: assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js (hunk 4 above)
Comment (miina) [reply assets/src/edit-story/components/panels/backgroundOverlay/convertOverlay.js:42]: Could we bring this up with UX for post-beta?
It feels very unexpected to me.

**Review by miina — APPROVED** [review]
