### PR TITLE
Auto-advancement: use media length over default duration

### LINKED ISSUE #7053: Default duration time overrules when using a shorter video
## Bug Description
When auto-advance is selected the default page duration setting is overridden by the video element and will auto-advance after the video has finished playing. However, if that video is shorter than the default page duration time, then the page does not advance until the default duration time has completed. If the video is shorter than the default page duration time, should the video duration still override and auto-advance?

## Expected Behaviour

The default page duration is automatically overridden by video.

## Steps to Reproduce
- Add a short video to the story
- Set the default page duration to a time that is longer than the video duration
- Preview the story and notice video has finished playing but the page has not advanced

## Screenshots
This [example story](https://testsite.cmsdevrel.com/web-stories/testing-duration/) uses a 6-second video and has the default page duration set to 9 seconds. 
https://user-images.githubusercontent.com/66372350/113608959-3277e880-9619-11eb-86b0-93dbc85cf42a.mov

## Additional Context

Related support topic: https://wordpress.org/support/topic/frame-duration/

- Plugin Version: 1.5.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Relevant Technical Choices
- If there is are videos on page, the longest media is taken as the page advancement, even if the longest media is very short
- If there is animation, the longest animation takes priority over the media if applicable.
- If there is animation shorter than the default duration, default duration is used.

## Testing Instructions
1. Add a few pages
2. Add short video on a page (e.g. 2 seconds)
3. To another page add a short animation
4. To another page add a short video and some animations longer than the video
5. Verify that if there's only a video on page, the page advances right after the video ends, even if very short (previously the default page duration was used instead)
6. Verify that in case of just a short animation on the page, the default page duration is used for advancing
7. Verify that if a short video and long animation are on the page, the page advances after the animation.

### QA
See steps above.

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7053

### CODE REVIEW

File: assets/src/edit-story/output/page.js [hunk 1]
```diff
@@ -57,6 +48,18 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
         ...generatePatternStyles(backgroundColor),
       };
 
+  const animationDuration = getTotalDuration({ animations }) / 1000;
+  // If the page doesn't have media, take either the animations time or the configured default duration time.
+  const nonMediaPageDuration = Math.max(
```
Comment (miina) [inline assets/src/edit-story/output/page.js:53]: @swissspidy I'm leaving the animation vs default duration logic the same, assuming the default page duration still has priority over the animations. Thoughts?

File: assets/src/edit-story/output/page.js [hunk 2]
```diff
@@ -57,6 +48,18 @@ function OutputPage({ page, autoAdvance, defaultPageDuration }) {
...
+    animationDuration || 0,
+    defaultPageDuration
+  );
+  // If we have media, take the media time for advancement time and ignore the default,
+  // but still consider animation time as the minimum, too.
+  const longestMediaElement = getLongestMediaElement(
+    elements,
+    animationDuration || 1
+  );
```
Comment (barklund) [inline assets/src/edit-story/output/page.js:62]: Hm, can you confirm, that this is the result?

| Video | Animation | Default | Actual page advancement time |
|-|-|-|-|
| 1s | - | 4s | 1s |
| - | 2s | 4s | 4s |
| 1s | 2s | 4s | 2s |

I don't find this intuitive, but any combination is pretty weird in my opinion anyway, so I'm not really challenging this, just asking to confirm...

**Review by barklund — APPROVED** [review]
(that was supposed to be a 👍 )

File: assets/src/edit-story/output/page.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/output/page.js:53]: I'll defer to @o-fernandez on this one.

The logic as per Morten's table below is a bit weird currently.

File: assets/src/edit-story/output/page.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/output/page.js:62]: Yep, this is the intended result as per current logic.

The origin issue doesn't mention animations, just a change for how it behaves with media, however, it shouldn't advance before the animations stop either, so 🤷 

Let's wait for @o-fernandez to confirm before moving forward.

Comment (swissspidy) [reply assets/src/edit-story/output/page.js:62]: Perhaps ping on Slack just in case

**Review by merapi — APPROVED** [review]
Works as expected ([current spec](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.wstk3e487ewk)).

Those rules make sense most of the time, just the short animation case is not intuitive (vs short video) and if somebody uses short non-looping video (just for e.g. introduction purpose) it might not work as they expect. The only solution would be to override it per page. 
Also, maybe we should put more info in the Auto-advance option explaining how it works?

File: assets/src/edit-story/output/page.js (hunk 2 above)
Comment (o-fernandez) [reply assets/src/edit-story/output/page.js:62]: I think that this works well most of the time. 

One caveat, if there's an animation that delays the start of a video, then the calculation for video time should include that. For example, video length is 1s, but we apply an animation so that the video fades in and starts playing after 2s, then the video won't finish playing until 3s from the page start time. That should be factored in. So it's not really just video length, but time until video plays once through. 

@miina @swissspidy @barklund @choumx thoughts on this? I think it's an edge case, but if y'all agree I can add that scenario to the spec and account for it.

Comment (miina) [reply assets/src/edit-story/output/page.js:62]: Since I'll be on time off for two weeks then would be great if we could create a new issue for that edge case (unless anyone else has capacity to pick it up meanwhile, moving this issue to QA meanwhile as it addresses the original issue).

Comment (barklund) [reply assets/src/edit-story/output/page.js:62]: @o-fernandez, let's file that as a follow-up ticket. I actually think we have a bug with videos with animation - at least it doesn't work at all locally for me?

Comment (swissspidy) [reply assets/src/edit-story/output/page.js:62]: > So it's not really just video length, but time until video plays once through.

That‘s how it‘s currently implemented.

**Comment by dreamofabear** [comment]
> Also, maybe we should put more info in the Auto-advance option explaining how it works?

+1 to updating the copy.
