### PR TITLE
Editor: Add alignment buttons to design menu

### LINKED ISSUE #10489: Element alignment keyboard shortcuts conflict with browser control
## Bug Description

In #625 (2 years ago!) we added functionality to the design panel to more easily align and distribute elements on the canvas (see screenshot below)

Some of these buttons were also made accessible as keyboard shortcuts:

<table>
<tr>
	<td><b>Shortcut
	<td><b>macOS
	<td><b>Windows
<tr>
	<td>Align left
	<td><kbd><kbd>⌘</kbd>+<kbd>{</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>{</kbd></kbd>
<tr>
	<td>Align center
	<td><kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>H</kbd></kbd>
<tr>
	<td>Align right
	<td><kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd>
	<td><kbd><kbd>Ctrl</kbd>+<kbd>}</kbd></kbd>
</table>

Unfortunately these shortcuts clash with keyboard shortcuts provided by the browser itself.

For example, <kbd><kbd>⌘</kbd>+<kbd>H</kbd></kbd> hides the current browser window.

And when I try to press  <kbd><kbd>⌘</kbd>+<kbd>{</kbd></kbd> on my US keyboard (for which I need to press <kbd>⌘</kbd> <kbd>⇧</kbd> and <kbd>[</kbd>), that actually triggers the "Select previous tab" shortcut in Chrome.

**That means these shortcuts might have never actually worked!**

**NB:** the keyboard shortcuts are not displayed in the keyboard shortcuts modal either.

## Expected Behaviour

Conclusion: For now, we will remove the shortcuts, see comments thread below.

Element alignment shortcut should not clash with browser.

Alternatively, we should consider just removing the shortcuts.

For context, here are the keyboard shortcuts Figma uses for similar actions:

Action | Shortcut
-- | --
Align left | <kbd><kbd>⌥ </kbd><kbd>A</kbd></kbd>
Align right | <kbd><kbd>⌥</kbd> <kbd>D</kbd></kbd>
Align top | <kbd><kbd>⌥ </kbd><kbd>W</kbd></kbd>
Align bottom | <kbd><kbd>⌥ </kbd><kbd>S</kbd></kbd>
Align centers | <kbd><kbd>⌥</kbd><kbd>H</kbd></kbd> and <kbd><kbd>⌥</kbd><kbd>V</kbd></kbd>
Distribute spacing | <kbd><kbd>⌃</kbd><kbd>⌥</kbd><kbd>H</kbd></kbd> and <kbd><kbd>⌃</kbd><kbd>⌥</kbd><kbd> V</kbd></kbd>

## Steps to Reproduce

Try using the keyboard shortcuts in the editor

## Screenshots

Screenshot 2022-02-07 at 10 57 10

## Additional Context

- Plugin Version: 1.17.0
- WordPress Version: 5.9
- Operating System: macOS or Windows
- Browser: all?

### LINKED ISSUE #10627: UI Simplification: Floating menu: Element alignment
## Feature Description

Make the element alignment options in the floating design menu functional.

Design: [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=11394%3A457271)
Menus: Multiple elements
Optional rendering: Distribution icons could be displayed for 3+ element selection. Please coordinate with UX whether this is desired.
Notes: Refactor the existing logic from the existing element alignment panel.

## Additional information

Screen Shot 2022-02-18 at 18 41 37

### PR DESCRIPTION
**Pull request by barklund**
## Context

This adds functional alignment buttons to the multi-selection design menu.

Note that this uses the exact same functionality as the alignment panel in the design menu uses.

I also completely rewrote the test for the `useAlignment` hook, as it was testing way more than necessary. I boiled it down to the bare minimum, and everything still works.

## Non-user-facing changes

| Selection | Screenshot |
|-|-|
| Two elements | Screenshot 2022-03-16 at 16 05 27 |
| Three elements | Screenshot 2022-03-16 at 16 05 17 |

## Testing Instructions

This PR can be tested by following these steps:

### Single element
1. Select a single element
2. Verify that the alignment panel in the design menu still correctly aligns the element relative to the canvas
3. Verify that the distribution buttons are disabled

### Two elements
1. Select two elements
2. Verify that the alignment panel in the design menu still correctly aligns the elements relative to each other
4. Verify that the new design menu does the same
5. Verify that distribution is not possible either way

### Three or more elements
1. Select three or more elements
2. Verify that the alignment panel in the design menu still correctly aligns the elements relative to each other
3. Verify that the new design menu does the same
4. Verify that distribution is possible and works correctly both using the design panel and design menu

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10627
Fixes #10489

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/alignment/useAlignment.js [hunk 1]
```diff
@@ -17,17 +17,68 @@
...
+          frameX,
+          frameY,
+          frameWidth,
+          frameHeight,
+        };
+      }),
+    [selectedElements]
+  );
+
+  // Set boundRect with pageSize when there is only element selected
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/alignment/useAlignment.js]:
```suggestion
  // Set boundRect with pageSize when there is only one element selected
```

File: packages/story-editor/src/components/panels/design/alignment/useAlignment.js [hunk 2]
```diff
@@ -138,14 +189,17 @@ function useAlignment() {
...
     });
-    pushUpdate(({ id }) => updatedY[id], true);
+    updateElements(({ id }) => updatedY[id]);
   };
 
   return {
-    setUpdatedSelectedElementsWithFrame,
-    handleAlign,
+    isDistributionEnabled,
+    handleAlignLeft: () => handleAlign('left'),
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/alignment/useAlignment.js]: Would be great to move these into constants, now that these are used more than once, e.g.
`ALIGNMENT: { LEFT: 'left', ... }` etc.

File: packages/story-editor/src/components/panels/design/alignment/useAlignment.js [hunk 3]
```diff
@@ -17,17 +17,68 @@
...
+  endY: PAGE_HEIGHT,
+  width: PAGE_WIDTH,
+  height: PAGE_HEIGHT,
+};
 
-  const handleAlign = (direction, boundRect, pushUpdate) => {
-    pushUpdate((properties) => {
+function useAlignment({ selectedElements, updateElements }) {
+  const isDistributionEnabled = selectedElements.length > 2;
+  const updatedSelectedElementsWithFrame = useMemo(
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/alignment/useAlignment.js]: Nit: I know this variable existed before already but it seems like these are not _updated_ elements here, these are just `selectedElementsWIthFrame`?

File: packages/story-editor/src/components/panels/design/alignment/alignment.js [hunk 4]
```diff
@@ -176,32 +115,27 @@ function ElementAlignmentPanel({ selectedElements, pushUpdate }) {
...
 
-  useKeyDownEffect(
-    ref,
-    { key: 'mod+}', shift: true },
-    () => handleAlign('right'),
-    [handleAlign]
-  );
+  useKeyDownEffect(ref, { key: 'mod+}', shift: true }, handleAlignRight, [
+    handleAlignRight,
+  ]);
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/alignment/alignment.js]: Just FI: The modifiers here aren't actually working, we have an issue to remove these as well: #6595 
(Unrelated to this PR)

File: packages/story-editor/src/components/panels/design/alignment/useAlignment.js [hunk 5]
```diff
@@ -17,17 +17,68 @@
...
+          frameWidth,
+          frameHeight,
+        };
+      }),
+    [selectedElements]
+  );
+
+  // Set boundRect with pageSize when there is only element selected
+  const boundRect =
+    selectedElements.length === 1 ? PAGE_RECT : getBoundRect(selectedElements);
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/alignment/useAlignment.js:85]: This menu is for multi-selection only, is it needed to check for `selectedElements.length === 1 ? PAGE_RECT ...`?
Could be just `getBoundRect(selectedElements)`?

File: packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js [hunk 6]
```diff
@@ -23,15 +23,80 @@ import { __ } from '@googleforcreators/i18n';
...
+  } = useAlignment({ selectedElements, updateElements });
   return (
-    <IconButton
-      Icon={Icons.AlignLeft}
-      title={__('Align elements', 'web-stories')}
-      onClick={() => {}}
-    />
+    <>
+      <IconButton
+        Icon={Icons.AlignLeft}
```
Comment (miina) [inline packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js:70]: The order of the alignment buttons differs in the design menu differs from the order in the design panel.
Design panel:
Screenshot 2022-03-15 at 11 03 31

Design menu:
Screenshot 2022-03-15 at 11 04 04

Maybe a design oversight but probably would make sense for these to match. WDYT?

File: packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js [hunk 7]
```diff
@@ -23,15 +23,80 @@ import { __ } from '@googleforcreators/i18n';
...
+        Icon={Icons.AlignBottom}
+        title={__('Align bottom', 'web-stories')}
+        onClick={handleAlignBottom}
+      />
+      {isDistributionEnabled && (
+        <>
+          <Separator />
+          <IconButton
+            Icon={Icons.DistributeHorizontal}
+            title={__('Distribute elements horizontally', 'web-stories')}
```
Comment (miina) [inline packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js]: Nit: In the design menu it's just `Distribute horizontally`. Same for the vertical.

**Review by miina — APPROVED** [review]
Works great!

Left a few comments, mostly nits.

File: packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js (hunk 6 above)
Comment (barklund) [reply packages/story-editor/src/components/floatingMenu/elements/elementAlignment.js:70]: Well, that's how they looked in Figma for the new menu, so just implemented as-is. But yeah, it might confuse users. I'll confirm with UX.

**Comment by BrookeGraham** [comment]
I think this needs to be rebased. When I pulled it down I am seeing this:
Screen Shot 2022-03-15 at 4 32 20 PM

**Review by BrittanyIRL — APPROVED** [review]
I agree with what Miina said. I'm seeing the editor just fine on this branch 🤔

**Comment by miina** [comment]
Took this over from Morten, just waiting for UX decision about the order of the buttons now.

Note: also removed the tooltips of the modifiers from the design panel that were not working, for consistency between the two alignment bars (#10489).

**Comment by miina** [comment]
@BrittanyIRL The remaining issues have been addressed now, since these were mostly my own comments, would be great if you could take another look just in case.

**Review by maxyinger — APPROVED** [review]
looks and works great!
