### PR TITLE
Design Panel: Bugfix - reset stored height of saved colors panel

### LINKED ISSUE #6740: Minimum height of the saved colours panel is incorrect
## Bug Description

When I initially opened up the saved colours panel I was unable to see all the panel content and had to manually use the drag handles to resize the panel to be able to see that. 

image11

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

>The issue is, that before the 1.5 release (so in 1.4), the saved color panel height was only a single line of color circles, so it was much smaller. And yes, that height was saved in local settings. When a user upgrades, the saved height persists, ignoring that the panel now should never be this tiny.

https://xwp.slack.com/archives/CCCAUAH6F/p1616176802029600?thread_ts=1616176594.029300&cid=CCCAUAH6F

## Summary

Changes the `presetType` for the colors panel. This changes the local storage name and resets the saved sizing values.

## Relevant Technical Choices

n/a

## To-do

none

## User-facing changes

Opening the colors panel will ignore the current saved sizing data. This can then be overwritten.

1. In this gif I set the height in this panel. This sets the value in local storage
2. I reload the page, but the presetType has been changed in my local code
3. You see that the height does not persist
4. Changing the height and reloading again persists the new height (since the data has a different key in local storage)

## Testing Instructions

1. Open the editor
2. Click on the background or an element with color
3. Open the dev tools. There should now be two keys in local storage for colors:
    - `web_stories_ui_panel_settings:stylepreset-colors` (new)
    - `web_stories_ui_panel_settings:stylepreset-color` (old)
4. Expanding the panel should update the new key's value

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open the editor
2. Click on the background or an element with color
3. Open the dev tools. There should now be two keys in local storage for colors:
    - `web_stories_ui_panel_settings:stylepreset-colors` (new)
    - `web_stories_ui_panel_settings:stylepreset-color` (old)
4. Expanding the panel should update the new key's value
**note** if you don't see the `Saved Colors` panel, try clicking on a different element or adding a new text element to get the panel to show up in the design tab.

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

This pr changes the way we store the sizing data for the saved colors panel.

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6740

### CODE REVIEW

**Comment by miina** [comment]
@samwhale I'm looking at the gif in the description and wondering how come the Saved Styles and Saved Colors have exactly the same content -- is this a bug happening for you? (Note: I haven't checked the PR yet!)

Screenshot 2021-03-19 at 20 57 58

**Comment by samwhale** [comment]
> @samwhale I'm looking at the gif in the description and wondering how come the Saved Styles and Saved Colors have exactly the same content -- is this a bug happening for you? (Note: I haven't checked the PR yet!)

Oh haha, I think I added both of the same colors to each panel while I was playing with the panels 😅. Sorry, that's a little confusing to watch

**Comment by miina** [comment]
> Oh haha, I think I added both of the same colors to each panel while I was playing with the panels 😅. Sorry, that's a little confusing to watch

The Saved Styles looks very different from the Save Colors content (it has square preview with text inside) -- so even if you'd add similar colours, it would still look very different 😛 

Screenshot 2021-03-19 at 21 03 53

**Comment by samwhale** [comment]
> > Oh haha, I think I added both of the same colors to each panel while I was playing with the panels 😅. Sorry, that's a little confusing to watch
> 
> The Saved Styles looks very different from the Save Colors content (it has square preview with text inside) -- so even if you'd add similar colours, it would still look very different 😛

OH YOU'RE RIGHT I remember what happened 🤦🤦🤦. I had the `presetType` for both as `color` when I took this gif

I realized that they weren't different right as I pushed this up. I'm sorry!

Here's a screenshot of the panels from the current changes:

**Review by barklund — APPROVED** [review]
Looks good. Are you sure there aren't more references to the types? @miina?

File: assets/src/edit-story/components/panels/design/preset/presetPanel.js [hunk 1]
```diff
@@ -35,9 +35,14 @@ import StyleGroup from './stylePreset/styleGroup';
 import useApplyColor from './colorPreset/useApplyColor';
 import useApplyStyle from './stylePreset/useApplyStyle';
 
+export const PRESET_TYPES = {
```
Comment (miina) [inline assets/src/edit-story/components/panels/design/preset/presetPanel.js]: Let's move this to a local constants file perhaps if we use these constants? Otherwise, we would create circular dependencies once we use the `PRESET_TYPES` everywhere.

There are quite a few more references to replace, for example:
https://github.com/google/web-stories-wp/blob/89d0995cdd3c1a3a4259c27a8e713d284dd7cf22/assets/src/edit-story/components/panels/design/preset/useDeletePreset.js#L42-L43

https://github.com/google/web-stories-wp/blob/89d0995cdd3c1a3a4259c27a8e713d284dd7cf22/assets/src/edit-story/components/panels/design/preset/utils.js#L140

Comment (samwhale) [reply assets/src/edit-story/components/panels/design/preset/presetPanel.js]: Can do!

**Review by miina — APPROVED** [review]
LGTM!
