### PR TITLE
Unskip tests

### LINKED ISSUE #536: Invalid AMP due to clip-path for masks
## Bug Description

Splitting this out from https://github.com/google/web-stories-wp/pull/500#issuecomment-596745077 and https://github.com/google/web-stories-wp/pull/530#pullrequestreview-372723984:

We need to fix the `clip-path` AMP validation issue, either by waiting on the upstream fix (https://github.com/ampproject/amphtml/issues/27239) to be approved, or by adding a workaround.

No matter what we end up with, we should add some tests to `output/story` that confirm complex stories to be valid AMP.

**Marked as blocked because of the pending upstream discussion.**

cc @dvoytenko @wassgha 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #536.

### CODE REVIEW

File: assets/src/edit-story/masks/test/output.js [hunk 1]
```diff
@@ -125,41 +125,41 @@ describe('WithMask', () => {
...
+  describe('AMP validation', () => {
+    it('should produce valid AMP output', async () => {
+      const props = {
+        element: {
+          id: '123',
           type: 'image',
           mimeType: 'image/png',
-          src: 'https://example.com/image.png',
+          scale: 1,
+          origRatio: 9 / 16,
```
Comment (wassgha) [inline assets/src/edit-story/masks/test/output.js:136]: I don't think this exists anymore, I'd confirm

**Review by wassgha — APPROVED** [review]

File: assets/src/edit-story/masks/test/output.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/masks/test/output.js:136]: Yup, good catch!

Need to find a good way to catch these things...
