### PR TITLE
Widget: Skip flakey customizer e2e test

### LINKED ISSUE #6879: Widget: Fix flakey customizer e2e test
## Task Description

This test often fails.

```
Web Stories Widget › Customizer › should be able to add widget

Node is either not visible or not an HTMLElement
```

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Unable to fix test, skip it for now. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

See #6879

### CODE REVIEW

File: packages/e2e-tests/src/specs/wordpress/widget.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ describe('Web Stories Widget', () => {
     });
   });
 
-  describe('Customizer', () => {
+  describe.skip('Customizer', () => {
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/wordpress/widget.js:81]: you'll need to `// eslint-ignore-next-line jest/no-disabled-tests` and provide a reason why it was disabled.

Ideally with a link to the ticket to address it.

```js
// Disable reason: Flakey test that needs to be investigated.
// See https://github.com/google/web-stories-wp/issues/6879
// eslint-disable-next-line jest/no-disabled-tests
```

**Review by swissspidy — CHANGES_REQUESTED** [review]
lint error

File: packages/e2e-tests/src/specs/wordpress/widget.js (hunk 1 above)
Comment (spacedmonkey) [inline packages/e2e-tests/src/specs/wordpress/widget.js:81]:
```suggestion
  // Disable reason: Flakey test that needs to be investigated.
  // See https://github.com/google/web-stories-wp/issues/6879
  // eslint-disable-next-line jest/no-disabled-tests
  describe.skip('Customizer', () => {
```

**Review by swissspidy — APPROVED** [review]
