### PR TITLE
Editor: Updated close icon and fixed input text overlap

### LINKED ISSUE #1874: Truncate text in input fields with close icon
## Bug Description

We need to truncate the text and not let it bleed into the remove icon

This input field is used in  various places. Let's make sure we updated it everywhere.

Also, we need to replace the "close" icon with this one: https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=10350%3A10

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR updates the text input used in the Editor.  It updates the clear text icon, and prevents the text from being clipped by the icon.

## User-facing changes

The text input component used in the "Link" panel and the "Accessibility" panel has been updated.

## Testing Instructions

1.) Open a story in the Editor.
2.) Add an image to the page.
3.) Click on the image and type in really long text into the "Link" and/or "Accessibility" panel and notice that the "clear text" icon is a nice big X, and notice that the input text does _not_ get overlapped by the icon (it gets clipped).

Fixes #1874 

## Screenshot 

long_text

### CODE REVIEW

File: .storybook/main.cjs [hunk 1]
```diff
@@ -19,6 +19,7 @@ module.exports = {
     './stories/**/*.js',
     '../assets/src/dashboard/**/stories/*.@(js|mdx)',
     '../assets/src/edit-story/**/stories/*.@(js|mdx)',
+    '../assets/src/animation/**/stories/*.@(js|mdx)',
```
Comment (mariano-formidable) [inline .storybook/main.cjs:22]: Added our effect/part animations back to storybook.

File: assets/src/animation/parts/index.js [hunk 2]
```diff
@@ -100,7 +100,7 @@ export function AnimationPart(type, args) {
       [ANIMATION_EFFECTS.ZOOM.value]: EffectZoom,
       [ANIMATION_EFFECTS.DROP.value]: EffectDrop,
       [ANIMATION_EFFECTS.ROTATE_IN.value]: EffectRotateIn,
-    }[type] || throughput;
+    }[type?.value || type] || throughput;
```
Comment (mariano-formidable) [inline assets/src/animation/parts/index.js:103]: Small fix so storybook effect animations get back to working.

**Review by BrittanyIRL — APPROVED** [review]
👍 
Text is now clipped on link and assistive inputs. Tested chrome, firefox, safari. 

Also verified that the animations are working again in storybook.

**Review by maxyinger — APPROVED** [review]
