### PR TITLE
Autoplay video on drop

### LINKED ISSUE #1892: Automatically Play Video if it is a background
## Bug Description

I drag a video to set as BG. The video should automatically play once it’s set to the BG. 

Figma:
[Set video as bg
](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7941%3A7809)
[Playback behavior
](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A304435)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #2090: Replacing background while bg video is playing causes weird interim state
## Bug Description

Replacing background while bg video is playing causes weird interim state, see video for detail. There's a time in which the newly dragged in bg video isn't reflected, even though thumbnail and preview show the new video the canvas shows the old one in landscape (not zoomed as bg)

## Steps to Reproduce

1. add video as bg
2. play bg video
3. while bg video play, drag new video as background (using drop zones)

## Screenshots

[Replace background while playing video causes weirdness.zip](https://github.com/google/web-stories-wp/files/4697501/Replace.background.while.playing.video.causes.weirdness.zip)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
## Summary

This PR will make autoplay work as described below.

## Testing Instructions / User-facing changes

> If you click on video in Library -> insert and auto-play
> If you drag it from Library into bg or shape as drop target -> auto-play
> If you drag it from Canvas into bg or shape as drop target -> auto-play

---

Fixes #1892
Fixes #2090

### CODE REVIEW

File: assets/src/edit-story/elements/video/karma/autoplay.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+    // TODO: After #1948 is merged we can check if video is paused during a drag
+    const safezone = fixture.screen.getAllByTestId('safezone')[0];
+    await fixture.events.mouse.seq(({ moveRel, down, up }) => [
+      moveRel(videoFrame, '50%', '50%', { steps: 12 }),
+      down(),
+      moveRel(safezone, 10, 10, { steps: 12 }),
+      up(),
+    ]);
+    const backgroundId = await getBackgroundElementId(fixture);
```
Comment (merapi) [inline assets/src/edit-story/elements/video/karma/autoplay.js:68]: This line will break this test because the fixture is rerendered so the video is no longer playing. I can see that behavior breaking other places so we need to watch out.
I will move it to line 42 and it will be all fine.

File: assets/src/edit-story/elements/video/karma/autoplay.js [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+  });
+
+  it('should autoplay on insert and on drop', async () => {
+    // TODO: Switch to role selector after they are merged
+    const videoFilter = fixture.screen.getByText('Video', {
+      exact: true,
+      selector: 'button',
+    });
+    await fixture.events.mouse.clickOn(videoFilter);
+    const videos = fixture.screen.getAllByTestId('mediaElement');
```
Comment (merapi) [inline assets/src/edit-story/elements/video/karma/autoplay.js]: Not sure how we want to utilize `@testing-library` but that's one easy way. @dvoytenko @barklund

File: assets/src/edit-story/components/dropTargets/provider.js [hunk 3]
```diff
@@ -172,6 +172,23 @@ function DropTargetsProvider({ children }) {
...
+            `video-${activeDropTargetId}`
+          );
+          if (videoEl) {
+            videoEl.load();
+            const playPromise = videoEl.play();
+            if (playPromise) {
+              playPromise.catch(() => {});
+            }
+          }
+        }, 0);
```
Comment (miina) [inline assets/src/edit-story/components/dropTargets/provider.js]: Nit: `0` is the default anyway.

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 4]
```diff
@@ -75,9 +75,12 @@ function useInsertElement() {
         setTimeout(() => {
           const videoEl = document.getElementById(`video-${id}`);
           if (videoEl) {
-            videoEl.play();
+            const playPromise = videoEl.play();
+            if (playPromise) {
+              playPromise.catch(() => {});
+            }
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/useInsertElement.js]: I think all browsers, that we care about, return a promise here, so this can just be:

```suggestion
            videoEl.play().catch(() => {});
```

File: assets/src/edit-story/components/dropTargets/provider.js [hunk 5]
```diff
@@ -172,6 +172,23 @@ function DropTargetsProvider({ children }) {
...
+          );
+          if (videoEl) {
+            videoEl.load();
+            const playPromise = videoEl.play();
+            if (playPromise) {
+              playPromise.catch(() => {});
+            }
+          }
+        });
+      }
```
Comment (barklund) [inline assets/src/edit-story/components/dropTargets/provider.js]: Could we perhaps move this to the video element definition? As some kind of `onDropHandler` returned by `getDefinitionForType`?  This feels a bit dirty and malplaced here.

File: assets/src/edit-story/components/dropTargets/provider.js [hunk 6]
```diff
@@ -172,6 +172,23 @@ function DropTargetsProvider({ children }) {
...
+          const videoEl = document.getElementById(
+            `video-${activeDropTargetId}`
+          );
+          if (videoEl) {
+            videoEl.load();
+            const playPromise = videoEl.play();
+            if (playPromise) {
+              playPromise.catch(() => {});
+            }
+          }
```
Comment (barklund) [inline assets/src/edit-story/components/dropTargets/provider.js]: What do we do if there's no element? Try again in x millis? Ignore it? Explode?

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/useInsertElement.js]: (similarly in the other copies of these lines below)

File: assets/src/edit-story/elements/video/karma/autoplay.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/elements/video/karma/autoplay.js]: Give the video element `role="application"` ([the only allowed role for video](https://www.w3.org/TR/html50/embedded-content-0.html#the-video-element)) and put the `alt` attribute from the media query on the video element as `aria-label`.

Then you should be able to find it by `getByRole('application', { name: 'alt value' });`.

I'm not sure if it has any negative consequence to put this role on the element though.

File: assets/src/edit-story/elements/video/karma/autoplay.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/elements/video/karma/autoplay.js:68]: Hm, this shouldn't be an issue since [this fix](https://github.com/google/web-stories-wp/pull/2261/files#diff-8ced9a717a92882ca8bd360f336ad948R310-R313), but perhaps that didn't fix it in all instances? Ping @dvoytenko

File: assets/src/edit-story/elements/video/karma/autoplay.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/elements/video/karma/autoplay.js]: But other than this, this is a nice and simple way to introduce the selectors from RTL. Do we need to pre-configure it with `container` as the target or is there nothing else to target?

**Review by barklund — COMMENTED** [review]
Various comments.

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 4 above)
Comment (merapi) [reply assets/src/edit-story/components/canvas/useInsertElement.js]: Fair enough 👍

File: assets/src/edit-story/elements/video/karma/autoplay.js (hunk 1 above)
Comment (merapi) [reply assets/src/edit-story/elements/video/karma/autoplay.js:68]: Correct, it is now fixed 🎉

File: assets/src/edit-story/elements/video/karma/autoplay.js (hunk 2 above)
Comment (merapi) [reply assets/src/edit-story/elements/video/karma/autoplay.js]: I didn't find any relevant information about video element a11y, in practice, they mostly don't have roles assigned. So adding that might be unnecessary, but I did it and we will see how it plays out.

Screen:
We should be good with it, even with direct import from RTL. I just added that to fixture in case we want to do something extra there. No additional setup is needed.
BTW: more on screen and container [here](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library).

File: assets/src/edit-story/components/dropTargets/provider.js (hunk 6 above)
Comment (merapi) [reply assets/src/edit-story/components/dropTargets/provider.js]: Not sure if we want some kind of retry mechanism here ATM, if that part will ever fail (bug report?) then we can do it.

File: assets/src/edit-story/components/dropTargets/provider.js (hunk 5 above)
Comment (merapi) [reply assets/src/edit-story/components/dropTargets/provider.js]: Done in https://github.com/google/web-stories-wp/pull/2286/commits/121d8a6781a396c04a8349dd6007a260f1c59cfc

File: assets/src/edit-story/components/library/panes/media/mediaElement.js [hunk 7]
```diff
@@ -260,14 +260,20 @@ const MediaElement = ({
 
   const { lengthFormatted, poster, mimeType } = resource;
   return (
-    <Container onPointerEnter={onPointerEnter} onPointerLeave={onPointerLeave}>
+    <Container
+      data-testid="mediaElement"
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/media/mediaElement.js:264]: Do we still need the `testid`?

**Review by barklund — APPROVED** [review]
Looks great to me - and seems to work excellent!

File: assets/src/edit-story/components/library/panes/media/mediaElement.js (hunk 7 above)
Comment (merapi) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js:264]: At least one old e2e test is using it. Should be removed when we fully transition to getByRole/Label.

**Comment by merapi** [comment]
Moving to QA Passed since all related issues are Verified in QA.

File: assets/src/edit-story/components/library/panes/media/mediaElement.js [hunk 8]
```diff
@@ -275,6 +275,8 @@ const MediaElement = ({
         width={width}
         height={height}
         preload="none"
+        role="application"
```
Comment (swissspidy) [inline assets/src/edit-story/components/library/panes/media/mediaElement.js]: That's a big role for a video... I don't think we should do that.

> The `application` role indicates to assistive technologies that an element and all of its children should be treated similar to a desktop application, and no traditional HTML interpretation techniques should be used. This role should only be used to define very dynamic and desktop-like web applications.

Source: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/application_role

Comment (merapi) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: That's right, but we want to use getByRole if possible and it's the only role applicable to video tag (and I didn't find any argument against it), so we need to find something equally good for a replacement. Anything better than testid? WDYT @barklund ?

Comment (swissspidy) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: I think the above is a pretty big argument against it 🙂 

The `figure` role would be more appropriate, but still feels wrong, as `figure` usually means video/image/audio + caption, plus a `video` is already quite semantic. No roles should be added to already semantic elements.

I'd stress your "getByRole if possible" point and say that if there's no suitable role, use a test ID

Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: The only allowed role for video is `application` or no role. I did suspect that `application` might be dangerous though, but it was my suggestion. But could we perhaps put it in a `<figure>` and still access the `<video>` tag with simple RTL selectors - `getByRole` or `getByLabelText`?

Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: I have [summoned the gods of RTL](https://twitter.com/barklund/status/1271461392575598593)...

Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: Let's try just `byLabel` here. I'll fix and see if it works.

Comment (barklund) [reply assets/src/edit-story/components/library/panes/media/mediaElement.js]: Remember to remove the role here too!

**Review by barklund — DISMISSED** [review]
Awesome that you found a solution.

**Review by barklund — APPROVED** [review]
Great job!
