### PR TITLE
Remove all illegal characters from slug

### LINKED ISSUE #6480: Permalink: special characters URL-encoded in slug
## Bug Description

Special characters like commas or colons are URL encoded in the permalink slug. 

## Expected Behaviour
Special characters should be stripped.

Example:
“Hello, World” becomes “hello-world”
“Foo: Bar” becomes “foo-bar”

## Steps to Reproduce
1. Create a new story with a comma or colon
2. See characters in permalink field URL-encoded 

## Screenshots

image

image

Expected slug: 
image

## Additional Context

Related topic: 
https://wordpress.org/support/topic/error-in-linking-with-special-characters-in-title-url/

- Plugin Version: 1.4.0
- WordPress Version: 5.6.1
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Remove all illegal characters from the permalink with blurring, similar behaviour to what WP is doing generally.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open the Permalink panel in the Document tab.
2. Type in a URL with illegal characters, e.g.`hello!:;world`.
3. Tab out of the input.
4. Verify that all illegal characters have been removed.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6480

### CODE REVIEW

File: assets/src/edit-story/utils/cleanForSlug.js [hunk 1]
```diff
@@ -45,6 +45,7 @@ export default function cleanForSlug(string, isEditing = false) {
     .map((s) => (isEditing ? s : s.replace(/--+/g, '-')))
     .map((s) => s.normalize('NFD'))
     .map((s) => s.replace(/[\u0300-\u036f]/g, ''))
+    .map((s) => (isEditing ? s : s.replace(/[^a-zA-Z0-9-_ ]/g, '')))
```
Comment (barklund) [inline assets/src/edit-story/utils/cleanForSlug.js]: Haven't whitespace already been replaced at this point - so spaces aren't there anyway?

```suggestion
    .map((s) => (isEditing ? s : s.replace(/[^a-zA-Z0-9-_]/g, '')))
```

**Review by barklund — APPROVED** [review]
I'd like @swissspidy's approval too, but looks good to me!

**Review by swissspidy — APPROVED** [review]
Slug cleanup can be quite tricky as it needs to match with what WP is doing both in Gutenberg and on the server. In my testing this PR looks like a good change in the right direction 👍
