### PR TITLE
Storybook: Fix right-click menu for nested menu

### LINKED ISSUE #10454: Storybook: Right-Click static menu with submenu is not displaying
## Bug Description
For some reason, the right-click menu with submenu is not displaying anymore in Storybook:
Screenshot 2022-02-03 at 13 43 12

Let's bring it back :)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by miina**
## Summary
Fixes the Storybook for right-click menu including a submenu: "Right click menu on top of shape and background"

## User-facing changes
See the Storybook: Design System -> Context Menu -> Static menus -> "Right click menu on top of shape and background"
Verify the menu with Select Layer will appear again.

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10454

### CODE REVIEW

File: packages/design-system/src/components/contextMenu/stories/index.js [hunk 1]
```diff
@@ -768,11 +768,8 @@ export const RightClickMenu = (args) => {
 export const RightClickMenuStaticValues = (args) => {
   return (
     <Grid>
-      <RightClickMenuOnShapeAndBackground>
+      <RightClickMenuOnShapeAndBackground {...args}>
```
Comment (miina) [inline packages/design-system/src/components/contextMenu/stories/index.js:771]: @BrookeGraham Requesting your review since looks like the recent file changes are from you.

`RightClickMenuOnShapeAndBackground` already includes a `ContextMenu` inside so there's no need to pass another `ContextMenu` separately. It just got broken at some point since `args` wasn't passed to it :) Should work as expected now again.

**Review by BrookeGraham — APPROVED** [review]
Nice catch. Thanks @miina
