### PR TITLE
Ensure raw story title is used for prefilling post title

### LINKED ISSUE #2822: Embedded Story - Title
## Bug Description

Title (with hyphen) wasn't appearing correctly in Post Editor after opting to embed in post on publishing a Story - html appearing

## Expected Behaviour

Story title should transfer to post display

## Steps to Reproduce

- create a story
- enter a story title, using a hyphen ("Story - Test")
- Publish story
- select option to add it to a post
- see post display title

Note title error

## Screenshots

In Stories:
image

In Posts:
image

## Additional Context

- Plugin Version:
- Operating System: Win10
- Browser:Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Ensures that the story title is used as-is for prefilling the post title, so that the titles match.

## Relevant Technical Choices

Uses `$post->post_title` as originally planned instead of `get_the_title()`.

Avoids the `the_title` filter and thus `wptexturize ` and the like from running.

## User-facing changes

No texturized post titles.

Users will get `Story - Test`, not `Story &#8211; Test`

## Testing Instructions

---

Fixes #2822

### CODE REVIEW

File: includes/Admin.php [hunk 1]
```diff
@@ -174,6 +174,14 @@ public function prefill_post_title( $title ) {
 			return $title;
 		}
 
-		return (string) get_the_title( $post_id );
+		$post = get_post( $post_id );
```
Comment (spacedmonkey) [inline includes/Admin.php:177]: Why this every not be a `WP_Post`? Surely the above line `Story_Post_Type::POST_TYPE_SLUG !== get_post_type( $post_id )` would check this?

File: includes/Admin.php [hunk 2]
```diff
@@ -174,6 +174,14 @@ public function prefill_post_title( $title ) {
...
+
+		if ( ! $post instanceof WP_Post ) {
```
Comment (spacedmonkey) [inline includes/Admin.php]:
```suggestion
		if ( ! $post instanceof WP_Post || Story_Post_Type::POST_TYPE_SLUG !== get_post_type( $post ) ) {
```
Maybe?

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
Smaller tweaks

File: includes/Admin.php (hunk 2 above)
Comment (swissspidy) [reply includes/Admin.php]: Went with something very similar

**Review by spacedmonkey — APPROVED** [review]
LGTM
