### PR TITLE
Publish Modal: Scrollbar consistency

### LINKED ISSUE #10619: Story Details Modal: Consistent Scrollbar Visibility
## Bug Description

The scrollbar visibility between the 2 document panes (editor vs modal) are inconsistent (see screenshot).

## Expected Behaviour

There should be consistent visibility between the document pane in the editor and the one used in the story details modal. 

## Steps to Reproduce

Open the document pane in the editor and some panels so that there's overflow. 
Click "publish" story and expand some panels in the modal's version of the pane and see that the scrollbar in the modal disappears when not in use but the one in the editor sticks around.

## Screenshots

Screen Shot 2022-02-18 at 1 43 10 PM

During bugbash @barklund was seeing the below, so while fixing this test different scroll bar settings to see if it can't be prevented. 
Screen Shot 2022-02-22 at 11 13 05 AM

(Scrollbars are set in general system preferences) 
Screen Shot 2022-02-22 at 11 14 50 AM

## Additional Context

Relates to #10115 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context
Scroll bars on panels should always be present if the content is scrollable. Additionally if a user's settings have show scrollbars set to "always" we want to override those styles so that the scroll bar styling is consistent. 

## Summary
Add our scrollbar styles from theme to the publish panel.

## Relevant Technical Choices
Changed the overflow to be in the y orientations specifically since we don't expect the content to be scrollable horizontally, only vertically. 
Added our scrollableCss from theme. 

## To-do
n/a

## User-facing changes

||before|after|
|--|--|--|
|With browser scroll bars always on|image|Screen Shot 2022-02-23 at 1 28 59 PM
|highlighting both scrollable panels|image|Screen Shot 2022-02-23 at 1 33 01 PM

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. In system setting (or browser settings) enable scrollbars to always show 
image
2. open publish modal 
3. open all panels on the side
4. click outside the side panel and check that the scrollbar remains visible
5. ensure no weird default scrollbars are present  

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10619

### CODE REVIEW

File: packages/story-editor/src/components/publishModal/content/index.js [hunk 1]
```diff
@@ -52,7 +53,9 @@ const _MainStoryInfo = styled.div`
   display: flex;
   flex-direction: column;
   padding: 0 16px;
-  overflow: scroll;
+  overflow-y: scroll;
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/publishModal/content/index.js:56]: We currently don't have enough content in here to warrant it scrolling, but I am not sure what v2 will look like, since it doesn't hurt to have it here I left it. But can definitely just remove all together if y'all prefer.

Comment (maxyinger) [reply packages/story-editor/src/components/publishModal/content/index.js:56]: > since it doesn't hurt to have it here I left it

yea this is kinda my train of thought too. I'm cool with leaving it in there

**Review by maxyinger — APPROVED** [review]
nice catch!

**Review by samwhale — APPROVED** [review]
Awesome
