### PR TITLE
Test fix: Re-enable poster image test for keyboard

### LINKED ISSUE #6629: Fix flaky test: should allow user to edit and reset poster image using keyboard
## Bug Description
The test `should allow user to edit and reset poster image using keyboard` is flaky and fails, needs to be fixed.

Note: The test is skipped in #6608 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Context
Fixes previously flaky test for poster image.

## User-facing changes
N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6629

### CODE REVIEW

File: assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js [hunk 1]
```diff
@@ -48,4 +48,8 @@ export class VideoPoster extends AbstractPanel {
       name: /reset/i,
     });
   }
+
+  get panelTitle() {
+    return this.getByRole('button', { name: 'Poster' });
+  }
```
Comment (barklund) [inline assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js:54]: There is a yet [unimplemented](https://github.com/google/web-stories-wp/blob/7e6e9e0a90ba301b567b5efe4674c5338d26011c/assets/src/edit-story/karma/fixture/containers/designPanel/abstractPanel.js#L31-L34) `get title() {}` in `AbstractPanel`, but it would require passing the panel title in the constructor - something like changing the `super` call in the video poster panel constructor to `super(node, path, 'Poster');` and storing that argument locally in `AbstractPanel`. And similarly for all the other panels.

Or you can set it from `DesignPanel`, where the title is already used to find the individual panels to avoid duplicating it - e.g. something like:

```js
  get videoPoster() {
    const title = 'Poster';
    const panel = this._get(
      this.getByRole('region', { name: title }),
      'poster',
      VideoPoster
    );
    panel._title = title;
    return panel;
  }
```

It's just a _nice-to-have_ if you can find a clean solution for it.

**Review by barklund — APPROVED** [review]
Good effort. Just a single nit. 🦓

File: assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/karma/fixture/containers/designPanel/videoPoster.js:54]: Looked a bit into this but I think I'll do this the next time it becomes relevant to a PR (or if there's time left from the issues of this sprint). Thanks for bringing this up!
