### PR TITLE
Story Editor: Improve Keyboard Navigation on Carousel

### LINKED ISSUE #4240: A11y: Improve keyboard interaction on carousel
## Bug Description

There are two issues with the page carousel:

1. Only the current page should be in the tab order - otherwise, if you have a 20-page story, you'll tab for a long to get from the canvas to the design panel, as you have to go through all the pages in the process.
2. The current page should have a clear focus indicator if focused - and this should be implemented in both collapsed carousel, regular carousel, and in the page grid view.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
- Adds a focus border around page thumb in collapsed carousel, regular carousel, and page grid view.
- Updates collapsed carousel so only active page thumb is focusable.

## Relevant Technical Choices
Just made the uncollapsed page indicator behave the same as the collapsed page indicator for tabIndex. I think this offloads a little work to the browser instead of doing it manually. Happy to revert tho if there's a preference.

## User-facing changes
- Page indicators in collapsed carousel, uncollaped carousel & grid view now have a blue outline when focused
- Only active page indicator can be focused as long as there's more than 1 page indicator.

## Testing Instructions
- In story editor, tab through page and see that only active page indicator is focusable out of the page indicators, also that it's visually clear that the page indicator is focused.
- In the story editor, click the grid view. In the grid view tab through the page and see that only the active page indicator is focusable out of the page indicators and that it's visually clear that the page indicator is focused.

## Screenshots
Screen Shot 2020-08-26 at 2 55 56 PM
Screen Shot 2020-08-26 at 4 00 39 PM
Screen Shot 2020-08-26 at 4 02 07 PM

---

Fixes #4240

### CODE REVIEW

**Review by barklund — APPROVED** [review]
Works perfectly - and even reduces code complexity!

**Review by mariano-formidable — APPROVED** [review]
LGTM 👍

**Comment by dmmulroy** [comment]
This also resolves #3653 in a better way than my PR #4106 does.  I'm happy to close that.

**Comment by dmmulroy** [comment]
This also resolves #3653 in a better way than my PR #4106 does. I'm happy to close that.

**Review by dmmulroy — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
LGTM! dig the simplification - applying this update to my PR for keyboard usability in the dashboard.

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 1]
```diff
@@ -78,25 +83,14 @@ function PagePreview({ index, gridRef, ...props }) {
...
-
-  const onFocus = () => {
-    setTabIndex(0);
-  };
 
   return (
     <UnitsProvider pageSize={{ width, height }}>
       <TransformProvider>
-        <Page tabIndex={tabIndex} onBlur={onBlur} onFocus={onFocus} {...props}>
+        <Page tabIndex={tabIndex} {...props}>
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: Given that `tabIndex` is just passed as-is to the `<Page />`, I think you can completely remove any notion of it in this component and just let it pass through via `props`.

Comment (barklund) [reply assets/src/edit-story/components/canvas/pagepreview/index.js:93]: You still need to rename [`ariaLabel` to `aria-label`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/carousel/index.js#L418) in the parent <Carousel /> component (yeah, [React is a bit inconsistent with these props](https://reactjs.org/docs/accessibility.html#wai-aria:~:text=Note%20that%20all%20aria%2D*%20HTML%20attributes,as%20they%20are%20in%20plain%20HTML%3A)) to make it pass correctly through.

File: assets/src/edit-story/components/canvas/carousel/compactIndicator.js [hunk 2]
```diff
@@ -27,14 +27,18 @@ import { forwardRef } from 'react';
  */
 import { COMPACT_THUMB_WIDTH, COMPACT_THUMB_HEIGHT } from '../layout';
 
-function CompactIndicatorWithRef({ onClick, isActive, ariaLabel, role }, ref) {
+function CompactIndicatorWithRef(
+  { onClick, isActive, ariaLabel, role, tabIndex },
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/compactIndicator.js:31]: With the renaming of `ariaLabel` to `aria-label` in `<Carousel />` (as mentioned in the previous comment), you can completely delete this component altogether and just make `Indicator` default export directly!

This component has zero function anymore, that the simple `styled.button` doesn't also have. The sole purpose right now is basically to rename the property, but without that purpose (which is silly anyway), it really doesn't do a thing.

That'll significantly reduce the complexity of this file - all the forward-ref and proptype-stuff can just go out the door!

**Review by barklund — CHANGES_REQUESTED** [review]
Just a single nit to optimize a bit.

File: assets/src/edit-story/components/canvas/pagepreview/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/pagepreview/index.js]: Sorry, I mixed up the two PR's and added some irrelevant comments here. I've removed them and am in the process of re-applying them to #4260, where they belong.

**Review by barklund — APPROVED** [review]
