### PR TITLE
Base64-encode HTML markup over the wire

### LINKED ISSUE #4805: Conflict with Cloudflare Web Application Firewall
**If you are coming from the support forums or encounter the following issue, please read carefully.**

This is a tracking ticket for the work on ensuring Web Stories for WordPress does not cause issues with the [Cloudflare Web Aplication Firewall (WAF)](https://support.cloudflare.com/hc/en-us/articles/200172016-Understanding-the-Cloudflare-Web-Application-Firewall-WAF-) or similar solutions.

Rules that so far have been identified as possibly causing conflicts:

* Cloudflare Specials > 100173 XSS, HTML Injection - Script Tag
* OWASP mod_security ruleset 981176

A similar conflict exists with Sucuri's WAF.

**Who's affected?**

The Cloudflare WAF is available to Pro, Business, and Enterprise plans.

**How do I know I am affected?**

You are likely affected when using Cloudflare's WAF offering and you are unable to save or publish stories using Web Stories for WordPress.

**Workaround**

Cloudflare:

Add a custom [Firewall rule](https://developers.cloudflare.com/firewall/cf-firewall-rules) to disable the WAF for any Web Stories-related REST API requests, like so:

Screen Shot 2020-10-02 at 12 34 56 PM

Sucuri:

Add `wp-json/web-stories` to the allowlist in the "Whitelist URL Paths" section.

**What is being done to fix this?**

We are still investigating this issue and will update this thread with any new findings.

* [ ] Check if REST API is fully functioning when opening the editor (#4790)
* [ ] Improved error messages if REST API requests fail (#1033)
* [x] Implement experimental workaround in the plugin (#4859, #5038)

**How can I follow progress on this issue?**

Subscribe to this issue using the "Subscribe" button in the sidebar:

Screenshot 2020-09-25 at 11 06 42

-----

**User reports so far**

* https://wordpress.org/support/topic/failed-to-save-the-story/
* https://wordpress.org/support/topic/cloudflare-waf-block-json-issues/
* https://wordpress.org/support/topic/failed-to-save-the-story-2/
* https://wordpress.org/support/topic/failed-to-save-the-story-error/

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

This is an attempt to solve conflicts with Web Application Firewalls that block requests to due HTML being sent. WAFs like the one from Cloudflare or Sucuri even scan JSON objects to find HTML in there, and of course they treat a full blown HTML document (the AMP markup we create) as suspicious due to containing script tags etc.

So my thought here was simple: if no HTML is found, nothing can be blocked.

And the easiest way that came to mind here was simple base64-encoding the markup before sending it in the client, and then decoding it again on the server-side.

## Relevant Technical Choices

* Encoded content is prefixed with `__WEB_STORIES_ENCODED__` so that we can easily detect this in PHP.  
  It _might_ not be needed because we decode it right away upon receival, but I think it's safer to keep.
* Uses a method like described at https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa to enable base64-encoding Unicode strings.

## To-do

* [x] Fix tests 🤔 
* [ ] Further testing with WAFs

## User-facing changes

N/A

## Testing Instructions

Using templates and publishing stories should still work as expected. Especially when behind a WAF.

---

Fixes #4805

### CODE REVIEW

**Comment by dreamofabear** [comment]
Neat but seems kinda brittle. Did we reach out or receive any guidance from Cloudflare or other WAF providers about this?

**Comment by swissspidy** [comment]
Not yet. But read #4805 for some context. The landscape is quite broad with many different vendors. And getting changes into something like the OWASP ruleset is going to take a long time. Whatever some vendor would do, it would end up being some cat and mouse game.

File: includes/Traits/Decoder.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+	/**
+	 * Decodes string if encoded.
+	 *
+	 * @param string $string String to decode.
+	 * @return string Decoded string.
+	 */
+	protected function base64_decode( $string ) {
+		if ( 0 === strpos( $string, '__WEB_STORIES_ENCODED__' ) ) {
+			$string = str_replace( '__WEB_STORIES_ENCODED__', '', $string );
+			return mb_convert_encoding( base64_decode( $string ), 'UTF-8', 'UTF-16LE' );
```
Comment (spacedmonkey) [inline includes/Traits/Decoder.php:58]: Don't we need to check if `mb_convert_encoding` exists like this. 
https://github.com/google/web-stories-wp/blob/df921610c406898a98fa4112f1c0eb44f37b345b/includes/Story_Renderer/HTML.php#L152

This makes this a requirement for https://github.com/google/web-stories-wp/issues/4791

File: includes/Traits/Decoder.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+ */
+trait Decoder {
+	/**
+	 * Decodes string if encoded.
+	 *
+	 * @param string $string String to decode.
+	 * @return string Decoded string.
+	 */
+	protected function base64_decode( $string ) {
+		if ( 0 === strpos( $string, '__WEB_STORIES_ENCODED__' ) ) {
```
Comment (spacedmonkey) [inline includes/Traits/Decoder.php:55]: Nit: make `__WEB_STORIES_ENCODED__` a trait const?

**Comment by spacedmonkey** [comment]
Screenshot 2020-10-12 at 11 32 25

This request is pretty hard to debug. Is there any chance we could turn this off if `WEBSTORIES_DEV_MODE` is `true`. Or generally have an option to turn this off.

File: assets/src/edit-story/app/api/test/base64Encode.js [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+  }
+  return String.fromCharCode(...new Uint16Array(bytes.buffer));
+}
+
+describe('base64Encode', () => {
+  it('prefixes encoded content', () => {
+    expect(base64Encode('Hello World')).toStartWith('__WEB_STORIES_ENCODED__');
+  });
+
+  it('converts Unicode characters', () => {
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/api/test/base64Encode.js:55]: This test appears be failing.

Comment (swissspidy) [reply assets/src/edit-story/app/api/test/base64Encode.js:55]: It's a known issue, see PR description

File: includes/Traits/Decoder.php (hunk 1 above)
Comment (swissspidy) [reply includes/Traits/Decoder.php:58]: Yep, needs a check, good catch.

At the same time, wondering if it would make sense to use a polyfill like https://github.com/symfony/polyfill-mbstring...

**Comment by spacedmonkey** [comment]
@swissspidy This PR is still in draft. But I think it is good to go. Is it blocked by anything? Like #4898?

**Comment by swissspidy** [comment]
> This PR is still in draft. But I think it is good to go. Is it blocked by anything? Like #4898?

#4898 would be nice to have, but not a blocker.

The biggest blocker here is alignment on the approach, and verification by users & support team that this does indeed work.

**Review by spacedmonkey — APPROVED** [review]
I have tested this locally and it works great! 👍
