### PR TITLE
Drop targeting: preserve origin element link if available.

### LINKED ISSUE #641: Image Link not brought over when dropping into target
## Bug Description

Image link disappears when dropping into a target.

Note: Might be good to confirm with @samitron7 to understand the behavior if drop target/dropped element has a link.

## Steps to Reproduce

1. Add a shape.
2. Create an Image
3. Add a link.
4. Drop the image into the shape.
5. The link wasn't brought over.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Adjusts `combineElements` logic so that the origin elements link would be preserved.

## Testing Instructions
I
1. Add a shape and an image.
2. Add links to both (different links)
3. Drag the image into the shape
4. Verify that the link set to the image has been preserved.

II
1. Add a shape and a video
2. Add link to the shape
3. Now drag the video into the shape
4. Verify that the link of the shape has been preserved.

III
1. Add a video as a background
2. Add an image and assign link to it
3. Drag the image into the background
4. Unselect the background and then hover over it -- verify it doesn't display any link information.

---

Fixes #641

### CODE REVIEW

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js [hunk 1]
```diff
@@ -81,15 +81,20 @@ function combineElements(state, { firstId, firstElement, secondId }) {
...
     'resource',
     'scale',
     'focalX',
     'focalY',
     'flip',
     'backgroundOverlay',
-  ]);
+  ];
+  // If the element we're dropping into is not background, maintain link, too.
+  if (secondElementPosition !== 0) {
```
Comment (barklund) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Could we do `!secondElement.isBackground` here instead?  That should work too, right?

File: assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js [hunk 2]
```diff
@@ -228,6 +228,97 @@ describe('combineElements', () => {
...
+      restore(getDefaultState4());
+
+      // Combine element 456 into 789
+      const result = combineElements({ firstId: '007', secondId: '789' });
+
+      expect(result.pages[0].elements[2]).toStrictEqual({
+        height: 10,
+        id: '789',
+        link: {
+          url: 'https://link789.com/',
```
Comment (barklund) [inline assets/src/edit-story/app/story/useStoryReducer/test/combineElements.js]: That domain actually exists 😲 !

[gTLD `.example`](https://en.wikipedia.org/wiki/.example) is recommended for this kind of usage.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: We could even do:

```js
  const propsFromFirst = [
    'type',
    'resource',
    'scale',
    'focalX',
    'focalY',
    'flip',
    'backgroundOverlay',
    // If the element we're dropping into is not background, maintain link, too.
    ...(!secondElement.isBackground && ['link']),
  ];
```

to simplify - not sure if it's cleaner though.

**Review by barklund — APPROVED** [review]
Seems to work great - with excellent test coverage. Just a few nits.
