### PR TITLE
Shapes: Simplified circle path

### LINKED ISSUE #11579: A circle shape with a specified W value doesn't have the same width as that of a square with the same value
## Bug Description

A circle that has a specified width is not appearing in the editor as a square with the same width

In this example the user has placed a circle of 275 W on top of a square also set to 275, and you can clearly see that the square is wider than the circle

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

This would change every story with a circle in it, making it slightly larger than it was when originally designed. Not sure this is undesirable.

We can merge this as-is or do an alternative:
1. ~Merge as-is impacting every story and template with a circle mask~
2. ~Make a migration slightly reducing the size of all circle masks already used in a story (would probably be imprecise, but could come close)~
3. Keep the old circle as it was, retire the mask, and a new circle (`CIRCLE2`) with the proper dimensions, only show the new circle in the mask library. All old stories would remain unchanged and all new stories would only use the new "proper" circle.

## Todo

- [x] Resolve migration issue

## User-facing changes

| Before | After |
|-|-|
| Screen Shot 2022-12-20 at 23 26 43 | Screen Shot 2022-12-20 at 23 22 20 |

## Testing Instructions

This PR can be tested by following these steps:

1. Add a circle to the story from the mask library
2. Observe that the circle fills up the maximum amount of space inside the frame of the shape

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11579

### CODE REVIEW

File: packages/masks/src/constants.ts [hunk 1]
```diff
@@ -95,8 +95,7 @@ const ICON_CLIP_PATHS = {
 
 const CLIP_PATHS = {
   [MaskTypes.RECTANGLE]: 'M 0,0 1,0 1,1 0,1 0,0 Z',
-  [MaskTypes.CIRCLE]:
-    'M 0.972222 , 0.500000 c 0.000000 , 0.261111 -0.211111 , 0.472222 -0.472222 , 0.472222 S 0.027778 , 0.761111 , 0.027778 , 0.500000 S 0.238889 , 0.027778 , 0.500000 , 0.027778 S 0.972222 , 0.238889 , 0.972222 , 0.500000 z',
+  [MaskTypes.CIRCLE]: 'M 0,0.5 a 0.5,0.5 0 1,0 1,0 a 0.5,0.5 0 1,0 -1,0',
```
Comment (barklund) [inline packages/masks/src/constants.ts]: (repeating my comment from the PR description to allow for an inline conversation)

This would change every story with a circle in it, making it slightly larger than it was when originally designed. Not sure this is undesirable.

We can merge this as-is or do an alternative:

1. Merge as-is impacting every story and template with a circle mask
2. Make a migration slightly reducing the size of all circle masks already used in a story (would probably be imprecise, but could come close)
3. Keep the old circle as it was, retire the mask, and a new circle (CIRCLE2) with the proper dimensions, only show the new circle in the mask library. All old stories would remain unchanged and all new stories would only use the new "proper" circle.

WDYT, @miina, @swissspidy?

Comment (miina) [reply packages/masks/src/constants.ts]: Option 3 seems the safest/cleanest to me.

Comment (swissspidy) [reply packages/masks/src/constants.ts]: Yeah let's go with option 3. We already have `showInLibrary` so adding this as a new `CIRCLE_2` should be pretty straightforward.

Can add a comment to the old one pointing to the ticket.

<table>
<tr>
	<td>Old
	<td>New
<tr>
	<td>Screenshot 2022-12-22 at 09 36 48
	<td>Screenshot 2022-12-22 at 09 36 56
</table>

Comment (barklund) [reply packages/masks/src/constants.ts]: Done in e7b6ff2f00.

**Comment by kkalarickal** [comment]
Recreated the problem on `main_branch`: circle and square of 275 size are not co-located


I saved the recreated problem in a story and opened the same story in the `12869_branch` to see if the fix applies to old/existing circles or not.

Verified that with `12869_branch` any *new* circles/squares of the same dimensions a collocated, but the previous circle/square combos remain disjointed:



On front end:

**Review by swissspidy — APPROVED** [review]
