### PR TITLE
Checklist: Add check for elements with links that take up > 80% screen

### LINKED ISSUE #6735: Pre-Publish Checklist: Warn if element with link is too large
## Feature Description

AMP ignores links if the target element covers > 80% of the page.

See https://github.com/ampproject/amphtml/issues/31108 / https://github.com/raxsha/amphtml/blob/8823d1feffdeaa85b1cc3d96474846cddacb77b6/extensions/amp-story/1.0/page-advancement.js#L574-L596 for context.

Users will get the following console error:

> [AMP-STORY-PAGE] Link was too large; skipped for navigation. For more information, see https://github.com/ampproject/amphtml/issues/31108

We could add a checklist item to warn users about this.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Elements with links that take up more than 80% of the screen will have the link ignored in the story (https://github.com/ampproject/amphtml/issues/31108) so we're adding a checklist issue to help prevent this ahead of publishing stories.

## Summary

Issue mirrors the check for elements with links that are too small to tap and follows this structure: https://github.com/raxsha/amphtml/blob/8823d1feffdeaa85b1cc3d96474846cddacb77b6/extensions/amp-story/1.0/page-advancement.js#L574-L596

Looks like this: 
Screen Shot 2021-11-08 at 11 21 49 AM

## Relevant Technical Choices

- Grabbing the canvas size from `useLayout`
- Everything else is pretty standard checklist stuff

## User-facing changes

If you have an element with a link that takes up 80% or more of the canvas you'll see a new accessibility warning like the one screenshot above.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.Make a story
2. Add an element
3. Give it a link
4. Now make it really big and see the new issue pop up in the accessibility part of the checklist (make sure the a11y section is available first by either early attempt publish or add more than 2 pages)

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6735

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]

File: packages/story-editor/src/components/checklist/constants.js [hunk 1]
```diff
@@ -93,6 +93,13 @@ export const ACCESSIBILITY_COPY = {
       'web-stories'
     ),
   },
+  linkTappableRegionTooBig: {
+    title: __('Reduce link size', 'web-stories'),
+    footer: __(
+      'Links cannot cover a large majority of the page. Use smaller elements for links.',
```
Comment (samwhale) [inline packages/story-editor/src/components/checklist/constants.js:99]: 💭 this copy feels a little confusing to me. Maybe something more along the lines of

`Elements with links must not cover over 80% of the page. Decrease the size of elements with links.`

**Review by samwhale — APPROVED** [review]
Nice, this works well and matches the rest of the already established patterns.

File: packages/story-editor/src/components/checklist/constants.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/checklist/constants.js:99]: @choumx  ^^ thoughts on copy update?

File: packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+import { useIsChecklistMounted } from '../popupMountedContext';
+
+const MAX_LINK_SCREEN_PERCENT = 80;
+
+export function isElementLinkTappableRegionTooBig(element, pageSize) {
+  if (
+    !['text', 'image', 'shape', 'gif', 'video'].includes(element.type) ||
+    !element.link?.url?.length
+  ) {
+    return false;
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js:46]: Love an early return.

**Review by BrookeGraham — APPROVED** [review]
🕺🏻

File: packages/story-editor/src/components/checklist/constants.js (hunk 1 above)
Comment (dreamofabear) [reply packages/story-editor/src/components/checklist/constants.js:99]: Not sure we should use "80%", how about:

> Elements with links must not cover most of the page. Decrease the size of elements with links.

Sorry for the late reply! Not a big deal either way IMO.

Comment (BrittanyIRL) [reply packages/story-editor/src/components/checklist/constants.js:99]: Sure! new ticket here: https://github.com/google/web-stories-wp/issues/9712
