### PR TITLE
Reduce timing difference for entering text edit mode.

### LINKED ISSUE #729: Text edit mode often conflicts with dragging operation
## Bug Description

Try to randomly drag text elements around. Especially short moves. Regularly, instead of completing the dragging behavior, the element goes into the edit mode. In such cases it often shows a misaligned frame:

## Expected Behaviour

That should practically never happen.

## Steps to Reproduce

Do short drag operations with a text element: short moves and quick delay between grab and release.

## Screenshots

Broken state:
image

Screencast:

capture

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fixes #729 

Reduces timing difference to stop entering edit mode when dragging.

In my testing, even a bit slower than normal click almost never exceeded 150, however, very short dragging was around 250.

Changed the value to 150 which seems to be short enough not to trigger when dragging but long enough even for a bit "slower" click.

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
SGTM

**Review by barklund — APPROVED** [review]

**Comment by swissspidy** [comment]
Added to alpha branch

File: assets/src/edit-story/elements/text/frame.js [hunk 1]
```diff
@@ -100,7 +100,7 @@ function TextFrame({ element: { id, content, ...rest }, wrapperRef }) {
     const handleMouseUp = (evt) => {
       const timingDifference = window.performance.now() - clickTime;
 
-      if (timingDifference > 300) {
+      if (timingDifference > 150) {
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/text/frame.js:103]: 150ms is a VERY short click. It was increased to 300ms due to a reported bug that it was too small. I think our problem is more related to the "drag" than speed of click. The coordinates have moved too far and that could be a better indicator.

Comment (miina) [reply assets/src/edit-story/elements/text/frame.js:103]: Hmm, interesting.

When I was testing then the number was mostly under `10` actually, when clicking and holding down (for a moment) then around `100`.

However, might be just how it is for me locally. Will reopen the issue then to investigate more.

Comment (dvoytenko) [reply assets/src/edit-story/elements/text/frame.js:103]: I think it has a lot to do with the type of pointer: mouse vs touchpad vs touch.
