### PR TITLE
Fix scroll reset on zoom setting change

### LINKED ISSUE #6181: Viewport inconsistent when switching zoom level
## Bug Description

In the current zoom implementation, the viewport jumps inconsistently when switching zoom level.

## Expected Behaviour

One of these three things could happen, which would make it consistent and logical. Each has its drawbacks though.

1. Always reset the viewport to a certain fixed position when changing the zoom level. This could be the top left corner or the page center.
2. Keep the same center as the old viewport - so when switching from FIT to any other zoom, the scroll will always be at the center. When switching from 200% to 300%, the current center will also be the center in the new zoom.
3. Keep the currently selected element(s) in the center of the viewport as well as possible. This would mean that being on FIT, selecting an element in the bottom right corner, and switching zoom to 300% would update the viewport to be in the bottom right corner.

## Steps to Reproduce

1. Zoom to 300%
1. Scroll somewhere to the middle
1. Change zoom to 200%
1. Observe that the resulting viewport is somewhere in the bottom of the page, not anywhere near where it was before.

## Screenshots
zoom-viewport-bug

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6920: Reset zoom scroll when changing view
## Bug Description

When having scrolled the canvas to the bottom right corner and changing the zoom setting to one, that doesn't require scroll, the canvas still appears scrolled and off-center.

## Expected Behaviour

* Canvas scroll should be fully reset on zoom setting change

## Steps to Reproduce

1. Enable canvas zoom experiment
2. Change zoom setting to 200%
3. Scroll to the bottom right corner
4. Change zoom setting to Fit
5. Observe canvas being (partially) hidden.

## Screenshots
image (16)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

This makes sure to correctly reset scroll offset on zoom change and also apply updated scroll offset to scrollable layer.

## Relevant Technical Choices

* Refactored layout state to use reduction and a single hook.
* This was required to make sure to update zoom setting and scroll offset in a single update once zoom setting changes.

## User-facing changes

Never again should it happen that changing to Fit will result in a wrongly offset page (perhaps even fully blank).

### QA

_See #6920_

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6181
Fixes #6920

### CODE REVIEW

File: assets/src/edit-story/app/layout/useZoomSetting.js [hunk 1]
```diff
@@ -31,143 +31,178 @@ import {
...
-    return {
+    case ZOOM_SETTING.SINGLE: {
+      maxPageWidth = PAGE_WIDTH;
+      break;
+    }
+    case ZOOM_SETTING.DOUBLE: {
+      maxPageWidth = 2 * PAGE_WIDTH;
+      break;
+    }
+    case ZOOM_SETTING.TRIPLE: {
```
Comment (miina) [inline assets/src/edit-story/app/layout/useZoomSetting.js]: Nit: This can be removed, it seems, doesn't look like the `TRIPLE` is defined nor in use.

File: assets/src/edit-story/components/canvas/layout.js [hunk 2]
```diff
@@ -19,7 +19,7 @@
  */
```
Comment (miina) [inline assets/src/edit-story/components/canvas/layout.js:19]: Might be good to split this file up a bit in a future PR, it's growing quite big.

**Review by miina — APPROVED** [review]
LGTM! 🐳

File: assets/src/edit-story/app/layout/useZoomSetting.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/layout/useZoomSetting.js]: Thanks, removed in db2be66a0.

File: assets/src/edit-story/components/canvas/layout.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/layout.js:19]: Yeah, it's due for an overhaul for sure.

**Comment by csossi** [comment]
Unable to scroll down (as per QA instructions in 6920).

https://share.getcloudapp.com/yAuDL9oZ
