### PR TITLE
Pre-Publish Checklist: Remove hover on + X more thumbnail

### LINKED ISSUE #9956: Checklist: 'X more' is not a button
Right now, when you hover over the overflow card for issues that aren't displayed (see screenshot) the cursor changes to a pointer! While we originally did this honoring past design wishes, I think it's wrong and that maybe there was a miscommunication.  Current design team is working on improved UX for this (#9350), in the meantime to help avoid further confusion let's just have a hover effect (cursor to remain default) on this overflow.

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

The +X more thumbnail currently looks like it is a button since the cursor changes to a hand when hovering. Let's remove this until ux/design is updated. 

## User-facing changes

Kapture 2021-12-14 at 14 32 27

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add several pages that will trigger the checklist to show the +X more thumbnail. eg. Add 5 or more pages with poor text color contrast, or 5 or more pages with little to no text on them
2. Open checklist and hover over the + more thumbnail. It should no longer change to a hand.

### Does this PR have a security-related impact?

no
### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9956

### CODE REVIEW

File: packages/story-editor/src/components/checklistCard/styles.js [hunk 1]
```diff
@@ -52,6 +52,9 @@ export const Container = styled.div`
   ${({ gridVariant }) => css`
     grid-template-areas: ${GRID_TEMPLATE_AREA[gridVariant]};
   `}
+
+    grid-template-areas: ${GRID_TEMPLATE_AREA[gridVariant]};
+  `}
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/checklistCard/styles.js]: oops not sure how that got there. Removing.

File: packages/story-editor/src/components/checklistCard/styles.js [hunk 2]
```diff
@@ -112,11 +115,19 @@ export const ThumbnailWrapper = styled.div`
       overflow: hidden;
       grid-auto-flow: column;
     `}
+
+      display: grid;
+      grid-gap: 8px;
+      grid-template-columns: repeat(${$colCount}, 52px);
+      overflow: hidden;
+      grid-auto-flow: column;
+    `}
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/checklistCard/styles.js]: Ok clearly I did something weird as this _should_ be a one line pr.

Comment (BrookeGraham) [reply packages/story-editor/src/components/checklistCard/styles.js]: oh it is that stupid linter in the pre-commit stage! ugh.

**Review by BrittanyIRL — APPROVED** [review]
great hold over, thank you!

**Review by maxyinger — APPROVED** [review]

**Review by samwhale — APPROVED** [review]
✨
