### PR TITLE
Bug: Fix Inconsistent Secondary Menu Popup Toggles

### LINKED ISSUE #8538: Inconsistent toggling on Popups
## Bug Description

The toggle behavior on the popups in the editor for help center, checklist and keyboard menu should be consistent. They are not. 

## Steps to Reproduce

Try toggling menus. See inconsistent open/close patterning.

## Screenshots

https://images.zenhubusercontent.com/235435637/12e01379-7df9-4e98-9071-d7e21aac11d7/inconsistent_toggle.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

There was an inconsistent toggle in the popup menus of the secondary carousel menu (helpcenter, checklist, keyboard shortcuts)

## Summary

control toggle more closely now that there are 3 potential popups expanded. 

## Relevant Technical Choices

Decided to use refs to control when popups are told to close more closely. There is potential that say, the checklist `isOpen` is still `true` when the keyboard shortcut menu becomes true, then the checklist closes the keyboard. Refs prevent that. 

## User-facing changes

Should have a consistent toggle experience now. 

**Before**

https://user-images.githubusercontent.com/10720454/127924152-9d153166-4c8f-4548-9ef3-bdc1256dcd9d.mp4

**After**

https://user-images.githubusercontent.com/10720454/127924165-24eb9ae2-34c1-4a08-bda9-27912e1fcf50.mp4

## Testing Instructions

Toggling these buttons should work like the video above now.

### QA

When you have a popup expanded and you click on another popup toggle, it should open the one you asked it to open and close the existing expanded popup. 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8538

### CODE REVIEW

File: assets/src/edit-story/components/carousel/secondaryMenu.js [hunk 1]
```diff
@@ -63,6 +63,10 @@ const Space = styled.span`
 `;
 
 function SecondaryMenu() {
+  const isHelpCenterOpenRef = useRef(false);
+  const isChecklistOpenRef = useRef(false);
+  const isKeyboardShortcutsMenuOpenRef = useRef(false);
```
Comment (samwhale) [inline assets/src/edit-story/components/carousel/secondaryMenu.js]: I feel like we could use one ref to track the open state 🤔 

```js
const openPopup = useRef(null);

...
openPopup.current = 'helpCenter'; // or any string
```

Then we have one piece of state where we track this instead of 3 (or more if we add more popups)

File: assets/src/edit-story/components/carousel/secondaryMenu.js [hunk 2]
```diff
@@ -106,28 +110,42 @@ function SecondaryMenu() {
...
+      isChecklistOpenRef.current = false;
+      isKeyboardShortcutsMenuOpenRef.current = false;
     }
   }, [closeChecklist, closeKeyboardShortcutsMenu, isHelpCenterOpen]);
 
   useEffect(() => {
-    if (isKeyboardShortcutsMenuOpen) {
+    if (
+      isKeyboardShortcutsMenuOpen &&
+      !isKeyboardShortcutsMenuOpenRef.current
```
Comment (samwhale) [inline assets/src/edit-story/components/carousel/secondaryMenu.js]: These feel like redundant state 🤔 If we are adding a ref here I think we should remove the other state.

I think I'm still confused about why we would get stuck before 🤔

**Review by samwhale — COMMENTED** [review]
I think we only need one piece of state to track this instead of 3!

File: assets/src/edit-story/components/carousel/secondaryMenu.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/carousel/secondaryMenu.js]: 🤦  yup, thank you!

File: assets/src/edit-story/components/carousel/secondaryMenu.js (hunk 2 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/carousel/secondaryMenu.js]: It's because it's all async, so there's cases where one menu would still be open when another is asked for and it results in the asked for menu not actually expanding. The easiest way to see it is either in the before video or toggle between checklist and keyboard shortcuts on any other branch.

Comment (samwhale) [reply assets/src/edit-story/components/carousel/secondaryMenu.js]: Ah gotcha. So we need another piece of state just to tell us what the plan is with opening/closing panels

**Review by samwhale — APPROVED** [review]

**Review by maxyinger — APPROVED** [review]
dope.
