### PR TITLE
Auto-select entire input field on focus

### LINKED ISSUE #736: Side panel: select all on input focus
## Bug Description

The inputs in the side panel (and likely elsewhere) should consistently do "select all" on keyboard focus. Currently it's not consistent. In my tests, the "width" and "height" fields do "select all", but "rotation angle" and "opacity" do not. The only thing I notice different about these fields is that some non-auto-select-all fields have suffixes (e.g. "%").

## Steps to Reproduce

Press <kbd>tab</kbd> and observe.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
Fixes #736.

This ensures selection of entire text field on focus. This makes it work for symbol-postfixed inputs when tabbing to them.

But more than that, it actually also selects the entire text field when mouse clicking into a text field. I think this is actually good behaviour.

If desired, we can loosen this effect to only occur on keyboard focus changes and not mouse focus changes.

**Demo** – first focusing by mouse, then by pressing (<kbd>shift</kbd> +) <kbd>tab</kbd>:
focusselect

### CODE REVIEW

File: assets/src/edit-story/components/form/numeric.js [hunk 1]
```diff
@@ -79,6 +79,13 @@ function Numeric({
   const placeholder = isMultiple ? __('multiple', 'web-stories') : '';
   const [focused, setFocus] = useState(false);
   const [dot, setDot] = useState(false);
+  const ref = useRef();
+
+  useEffect(() => {
+    if (focused && ref.current) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/numeric.js]: So, mouse focusing also does select-all?

**Comment by miina** [comment]
@barklund From testing:

It currently doesn't seem to work for opacity fields which go together with `<Color>`:
opacity

File: assets/src/edit-story/components/form/numeric.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/form/numeric.js]: Yes, as mentioned in PR description. It's "by design" 😉.

**Comment by barklund** [comment]
> It currently doesn't seem to work for opacity fields which go together with `<Color>`:

Ah yes, that's a different component that `Numeric`. Will re-implement here.

**Comment by barklund** [comment]
> > It currently doesn't seem to work for opacity fields which go together with `<Color>`:
> 
> Ah yes, that's a different component that `Numeric`. Will re-implement here.

Done. @miina, PTAL.

File: assets/src/edit-story/utils/useFocusAndSelect.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+/**
+ * External dependencies
+ */
+import { useEffect, useState, useCallback } from 'react';
+
+function useFocusAndSelect(ref) {
+  const [isFocused, setIsFocused] = useState(false);
+
+  const handleFocusIn = useCallback(() => setIsFocused(true), []);
+  const handleFocusOut = useCallback(() => setIsFocused(false), []);
```
Comment (wassgha) [inline assets/src/edit-story/utils/useFocusAndSelect.js]: Can we rename these to `handleFocus` and `handleBlur` ? That's more standard

**Review by wassgha — APPROVED** [review]
nits

**Comment by wassgha** [comment]
@googlebot I consent

**Comment by swissspidy** [comment]
Added to alpha branch
