### PR TITLE
Fixed template layer order

### LINKED ISSUE #12128: Template Layer showing only when expanded
## Bug Description

Originally reported by @timarney 
The template titled Sun Protection Done Right has a layer called Brush Stroke 1 that is only visible when you open the the Rectangle layer above it.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

Moved element to keep grouped layers together

## User-facing changes

| Before | After |
|-|-|
| Screen Shot 2022-12-20 at 23 01 56 | Screen Shot 2022-12-20 at 23 01 42 |

#### Original bug
1. Go to the page templates tab
2. Find the third template "Sun protection" and add it to the current story
3. Expand the layers panel
4. Expand the "Info" layer group
5. Observe that all the elements in the layer group are located correctly in the layer panel

##### Related bugs
1. Create a new story from each of these templates
a-day-in-the-life
ace-hotel-kyoto-review
all-about-cars
almodos-films
baking-bread-guide
belly-fat-workout
celebrity-q-and-a
doers-get-more-done
elegant-travel-itinerary
experience-thailand
fashion-inspiration
fashion-on-the-go
food-and-stuff
fresh-and-bright
how-video-calls-saved-the-day
indoor-garden-oasis
kitchen-stories
los-angeles-city-guide
no-days-off
plant-based-dyes
sangria-artichoke
self-care-guide
skin-care-at-home
sleep
street-style-on-the-go
summer-adventure-guide
summer-fashion-collection
tv-show-recap
ultimate-comparison
weekly-entertainment
2. Observe that on every page, the grouped layers are correctly displayed when the group is opened

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12128

### CODE REVIEW

**Review by miina — APPROVED** [review]

**Comment by swissspidy** [comment]
I'm a bit confused. How was this allowed to happen? Should this be caught in the story reducer when grouping layers?

If the order matters, are we certain this is not the only template with this issue? Would be a great opportunity to add a test to `packages/templates/src/test/raw.js` ensuring the right order.

**Comment by swissspidy** [comment]
The last page of the "Fresh & Bright" template definitely has this issue as well:

https://user-images.githubusercontent.com/841956/208997825-2ca1461a-e349-4d04-80ae-0d20f6865eca.mov

So there's a bigger issue at hand here.

**Comment by miina** [comment]
@swissspidy I think these issues might actually come from manually changing the template files to adopt groups -- I took over that PR of manual changes and fixed a bunch of these issues, however, looks like I might have missed some (can't find the PR right now). AFAIK it's not possible to create that situation in the editor.

**Comment by swissspidy** [comment]
OK that's a bit of a relief then!

Some late night WIP Jest test found more occasions where we could fix these situations manually:

```js
    it.only('should list elements in the same group after each other', () => {
      for (const { elements, groups = {} } of templateData.pages) {
        const existingGroupIds = Object.keys(groups);

        const seenGroupIds = [];

        let lastGroupId = null;
        for (const { groupId } of elements) {
          // eslint-disable-next-line jest/no-conditional-in-test
          if (groupId) {
            seenGroupIds.push(groupId);

            // eslint-disable-next-line jest/no-conditional-expect
            expect(existingGroupIds).toContain(groupId);
          }

          // eslint-disable-next-line jest/no-conditional-in-test
          if (lastGroupId && groupId && lastGroupId !== groupId && seenGroupIds.includes(groupId)) {
          console.log(lastGroupId, groupId);
            console.log('errr');
          }

          lastGroupId = groupId;
        }
      }
    });
```

**Comment by barklund** [comment]
> Some late night WIP Jest test found more occasions where we could fix these situations manually:

I fixed the test up and ran it on the `getTemplates()` output and **every single template** (so far - 4 out of 59) has at least one failing page. Looks like I know what I'm doing today. 😴

**Comment by barklund** [comment]
> > Some late night WIP Jest test found more occasions where we could fix these situations manually:
> 
> I fixed the test up and ran it on the `getTemplates()` output and **every single template** (so far - 4 out of 59) has at least one failing page. Looks like I know what I'm doing today. 😴

Uh, found a bonus in the fifth template I'm testing. The animations are wrong (refer to an element ID, that doesn't exist), so the whole template fails to load in the editor (because the TS-converted animations package throw an error in that case=! Guess I need to add a test for that too, then! It's gonna be a long day... 😩

**Comment by kkalarickal** [comment]
Recreated the problem on stories-qa:


Verified the fix on `12868_branch`

@barklund @swissspidy - note that the fix is only for new instances of the page template being applied. Existing pages will still show the misaligned layers.

**Comment by kkalarickal** [comment]
@swissspidy @barklund - I reviewed all the theme templates listed in your instructions and found a couple where it was possible to see the misaligned layers. But to get to that state, you need to open and close the layers a few times in random order:

experience-thailand:



how-video-calls-saved-the-day:



indoor-garden-oasis:



plant-based-dyes:



street-style-on-the-go:



summer-fashion-collection:



Note: There were no layers in any page of no-days-off
Note: There was no template called "sangria-artichoke"

Another thing I noticed is that if a page has many layers with lots of elements, it is often NOT possible to scroll down and see all the layers if the upper layers are expanded. Example: Page 13 of fashion-inspiration

File: packages/migration/src/migrate.ts [hunk 1]
```diff
@@ -69,12 +69,13 @@ import removeTagNames from './migrations/v0043_removeTagNames';
...
 import globalPageAdvancement from './migrations/v0045_globalPageAdvancement';
 import removeRedundantScalingProperties from './migrations/v0046_removeRedundantScalingProperties';
+import fixBrokenTemplates from './migrations/v0047_fixBrokenTemplates';
 
 type MigrationFn<T, S> = (storyData: T) => S;
 
 // eslint-disable-next-line @typescript-eslint/ban-ts-comment -- See below.
 // @ts-ignore Reason: Temporary (hopefully). Don't have a good solution for this yet as it accepts all story types.
-const MIGRATIONS: Record<number, MigrationFn<any, any>[]> = { // eslint-disable-line @typescript-eslint/no-explicit-any,prettier/prettier -- See above.
+const MIGRATIONS: Record<number, MigrationFn<any, any>[]> = {
```
Comment (barklund) [inline packages/migration/src/migrate.ts]: Hmm, I didn't do this? Must have been something `--fix`, because I actively made sure to keep this line the same (my formatter wanted to wrap it).

**Comment by barklund** [comment]
> note that the fix is only for new instances of the page template being applied. Existing pages will still show the misaligned layers.

@kkalarickal, could I get you to test this part again? I think I've fixed that too.

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
@barklund - I confirmed via this [web-story](https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=21450&action=edit#page=%2522fc463495-d279-4f27-8834-d7f340ebc08f%2522) that:
- on `main-branch`, the page built using Sun protection template has misaligned layers
- when i switch to the `12828-branch`, the existing page no longer shows the misaligned layers
- i also confirmed that any new story pages built using the sun protection templae don't show misaligned layers

**Comment by kkalarickal** [comment]
@barklund @swissspidy - I re-tested on the `12828-branch` a few of the templates which I listed previously as showing misaligned layers in some of the inner pages. 

Unfortunately, the misalignment still shows up.

For example: plant-based-dyes template, 6th page



So I reckon, we still have to contend with other such templates which show misaligned layers in some of the pages.

**Comment by swissspidy** [comment]
@kkalarickal Can you try it again? I can't seem to reproduce with that specific template & page

Screenshot 2023-01-24 at 12 06 20

File: packages/migration/src/migrations/v0047_fixBrokenTemplates.ts [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+}
+
+function fixBrokenPage({ elements, animations, ...rest }: PageV46): PageV47 {
+  const elementIds = elements.map(({ id }) => id);
+
+  return {
+    elements: fixElementOrder(elements),
+    ...(animations
+      ? {
+          animations: (animations as AnimationV0[]).filter((animation) =>
```
Comment (swissspidy) [inline packages/migration/src/migrations/v0047_fixBrokenTemplates.ts]: `[@typescript-eslint/no-unnecessary-type-assertion] This assertion is unnecessary since it does not change the type of the expression.`

**Comment by kkalarickal** [comment]
@swissspidy I tested the various templates once again. It is rather difficult to find a consistent way to create the out of order situation. I think the original issue has been sorted and we should merge this fix to address that concern.

Just to confirm, I too was not able to see the out of order template layers for plant-based-dyes.

**Comment by swissspidy** [comment]
Excellent! @barklund let‘s fix the remaining tsc error & then merge this
