### PR TITLE
Disable Update button if there are no changes to be saved

### LINKED ISSUE #3548: Update button not disabled despite no changes
## Bug Description

In `assets/src/edit-story/components/header/buttons.js` there is some logic to disable the "Update" button if there are no new changes.

However, that does not seem to be working. The Update button is always visible & enabled, allowing me to update the story despite there being no new changes.

If there are no changes, the button should be disabled.

## Expected Behaviour

1. Publish story
1. Don't make any changes
1. The Update button is disabled

## Steps to Reproduce

1. Publish story
1. The Update button is not disabled
1. Click on Update
1. The Update button is still not disabled

## Screenshots

Screenshot 2020-07-30 at 10 29 30

https://github.com/google/web-stories-wp/blob/9f6927743e52c9dd37254e1b7c504a6144f13116/assets/src/edit-story/components/header/buttons.js#L248-L271

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by amovar18**
## Context

Before this PR the update button would stay enabled even though there werent new changes. It was because the update button was meant to be disabled only if there was any `uploading` or any `saving` action happening.

## Summary

This PR changes the condition and adds a unit test to check the update button works properly.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open a published story or any draft story in story-editor
2. Dont make any changes you should see that the Update button is disabled.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #3548

### CODE REVIEW

File: packages/story-editor/src/components/header/buttons/test/update.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ function arrange({
 }
 
 describe('UpdateButton', () => {
-  const FUTURE_DATE = '2022-01-01T20:20:20Z';
+  const FUTURE_DATE = '2022-01-10T20:20:20Z';
```
Comment (miina) [inline packages/story-editor/src/components/header/buttons/test/update.js]: Maybe change the year here instead? Seem like this might not be accurate quite soon.

Comment (amovar18) [reply packages/story-editor/src/components/header/buttons/test/update.js]: I dont think it would matter because `Mockdate` actually manipulates the `now` date so anytime test is run the system is at `2020-07-15T12:00:00+00:00`

Comment (miina) [reply packages/story-editor/src/components/header/buttons/test/update.js]: Ah, okay, why the change at all then?

Comment (amovar18) [reply packages/story-editor/src/components/header/buttons/test/update.js]: sorry forgot to remove thought it was the reason the test failed will revert the change

**Comment by miina** [comment]
@amovar18 Saw you requested a review but the PR is still a draft. Is this final now and can be marked ready for review?
Could you also merge `main`?

**Review by swissspidy — APPROVED** [review]
