### PR TITLE
Use single input for locked paddings

### LINKED ISSUE #1110: Use single input field for Text Padding Lock
## Bug Description

After locking the horizontal/vertical padding, the fields for H and V should merge but they aren't.

## Steps to Reproduce

1. lock padding

## Screenshots

Staging screenshot of locked padding with both fields:
image

[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1) screenshot:
image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by winterDroid**
### Summary

Use new `LockedPaddingControls` or `UnlockedPaddingControls` depending on whether the field is locked or not

Screen Shot 2020-05-01 at 3 16 33 pm

Fixes #1110

### CODE REVIEW

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 1]
```diff
@@ -103,14 +164,22 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
...
       />
-    </Row>
+    </>
   );
 }
 
-PaddingControls.propTypes = {
-  selectedElements: PropTypes.array.isRequired,
+UnlockedPaddingControls.propTypes = {
+  padding: PropTypes.shape().isRequired,
```
Comment (ndev1991) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: In case of shape, I think we need particular format of this shape object.
`.shape({ vertical: PropTypes.number, horizontal: PropTypes.number })` for example?

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 2]
```diff
@@ -56,45 +59,103 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
...
+        <UnlockedPaddingControls
+          padding={padding}
+          pushUpdateForObject={pushUpdateForObject}
+        />
+      )}
+    </Row>
+  );
+}
+
+PaddingControls.propTypes = {
```
Comment (obetomuniz) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: I would highly recommend splitting this file into small files to contain the 3 components (`PaddingControls`, `LockedPaddingControls `, and `UnlockedPaddingControls`) declared here. WDYT?

Comment (winterDroid) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Done.

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 1 above)
Comment (winterDroid) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Done.

File: assets/src/edit-story/components/panels/textStyle/padding/padding.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+  const lockPadding =
+    padding.locked === MULTIPLE_VALUE ? false : padding.locked;
+
+  return (
+    <Row>
+      <Label>{__('Padding', 'web-stories')}</Label>
+      {lockPadding ? (
+        <LockedPaddingControls
+          padding={padding}
+          pushUpdateForObject={pushUpdateForObject}
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding/padding.js]: IMHO it'd be better to redefine the pusher as a `useCallback` here. It can take care of the `DEFAULT_PADDING`, field names, etc. The sub-components will be slightly simpler in that case.

File: assets/src/edit-story/components/panels/textStyle/padding/locked.js [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+        onChange={() =>
+          pushUpdateForObject('padding', { locked: false }, DEFAULT_PADDING)
+        }
+      />
+    </>
+  );
+}
+
+LockedPaddingControls.propTypes = {
+  padding: PropTypes.shape({
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding/locked.js]: This should go to the `types.js` as a top-level const and used here and for element itself. See for instance, `FontPropType`.

File: assets/src/edit-story/components/panels/textStyle/padding/unlocked.js [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+            DEFAULT_PADDING
+          )
+        }
+      />
+    </>
+  );
+}
+
+UnlockedPaddingControls.propTypes = {
+  padding: PropTypes.shape({
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding/unlocked.js]: Ditto

**Review by dvoytenko — CHANGES_REQUESTED** [review]

**Comment by winterDroid** [comment]
@samitron7 wdyt?

File: assets/src/edit-story/components/panels/textStyle/padding/locked.js (hunk 4 above)
Comment (winterDroid) [reply assets/src/edit-story/components/panels/textStyle/padding/locked.js]: done

File: assets/src/edit-story/components/panels/textStyle/padding/padding.js [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+    'padding',
+    DEFAULT_PADDING
+  );
+
+  // When multiple element selected with padding locked value combined, it treated as false, reversed behavior with aspect lock ratio.
+  const lockPadding =
+    padding.locked === MULTIPLE_VALUE ? false : padding.locked;
+
+  const handleChange = useCallback(
+    (newPadding, submit = false) => {
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/textStyle/padding/padding.js:50]: Looks like some test assertions need to be updated now that `false` is passed by default (vs. nothing before)

**Review by dvoytenko — APPROVED** [review]
