### PR TITLE
Disable ESM modules in AMP optimizer

### LINKED ISSUE #7516: Preview development/ debug mode missing
## Bug Description
The preview link goes straight to the story view.

## Expected Behaviour

Development modal should display before the story view when previewing. 

## Steps to Reproduce
Preview story. 
Notice preview/debug screen skipped and the story view displays.

## Screenshots

Current view:

https://user-images.githubusercontent.com/66372350/118154314-e58bec80-b3e4-11eb-8c1c-ff3ff6a48067.mov

Previous view:
Screen Shot 2021-05-13 at 11 32 14 AM

## Additional Context

- Plugin Version: 1.7.1
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dreamofabear**
## Context

#7516. 

STAMP preview mode (`#development=1`) doesn't work in AMP's ESM modules output, which I believe was enabled in the latest version of AMP WP plugin bundled with v1.7.

## Summary

Disable ESM module rewriting in the AMP optimizer.

## Relevant Technical Choices

- We could consider keeping ESM module rewriting in the published story (and non-ESM in preview).

## To-do

N/A

## User-facing changes

The STAMP preview mode should work again if the WP AMP plugin is not also installed.

### QA

This PR can be tested by following these steps:

1. Open a story and click the preview button.
2. The multiple device emulation preview mode should be displayed (not just the story itself).

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7516.

### CODE REVIEW

**Comment by swissspidy** [comment]
Is the idea behind this to publish a patch release with this change?

Given that https://github.com/ampproject/amphtml/pull/34372 is in progress already and that this doesn't really have a negative impact on publishers, as well as ESM usage having a positive impact, I would clearly say no.

> * This PR unfortunately doesn't fix the issue for users that have the AMP WP plugin active.

It should.

It's easy enough to add, just need to hook into the `amp_optimizer_config` filter and amend the configuration in a similar way (of course using class names in the `AmpProject\AmpWP` namespace). 

> * We could consider keeping ESM module rewriting in the published story (and non-ESM in preview).

This should also be easy enough to add. Just checking for `is_preview()` and only changing the configuration if it's true could work (assuming that the configuration is not loaded too early)

**Comment by dreamofabear** [comment]
Yea, I was thinking of a point release. Depends on how long we'd be ok with the preview mode regression -- the AMP change will take 2-3 weeks to roll out to prod. 

/cc @o-fernandez

**Comment by o-fernandez** [comment]
> Yea, I was thinking of a point release. Depends on how long we'd be ok with the preview mode regression -- the AMP change will take 2-3 weeks to roll out to prod.
> 
> /cc @o-fernandez

Preview mode is critical to avoid the cropped stories issues that we've had in the past, and has gotten better recently, so I'd hate for us to have to wait 3 weeks for the fix. If possible to do a point release without too many changes/work and get the fix out soon I'd favor that. 

If it'd be too much work to get a fix like this out, can we work to make releases easier so it's not such a high burden?

**Comment by swissspidy** [comment]
> If possible to do a point release without too many changes/work and get the fix out soon I'd favor that.
> 
> If it'd be too much work to get a fix like this out, can we work to make releases easier so it's not such a high burden?

Releasing is easy and automated, that‘s not the problem.

**Comment by dreamofabear** [comment]
> It's easy enough to add, just need to hook into the amp_optimizer_config filter and amend the configuration in a similar way (of course using class names in the AmpProject\AmpWP namespace).

Oh neat, done.

**Review by swissspidy — APPROVED** [review]

**Review by spacedmonkey — APPROVED** [review]
👍  I would say this needs to be QAed. Maybe install different version of the amp plugin to check nothing breaks.

File: includes/Integrations/AMP.php [hunk 1]
```diff
@@ -242,6 +244,22 @@ public function filter_amp_skip_post( $skipped, $post ) {
...
+	 * @since 1.7.2
+	 *
+	 * @link https://github.com/ampproject/amphtml/issues/34364
+	 *
+	 * @param array $configuration The AMP Optimizer configuration.
+	 *
+	 * @return array The modified configuration.
+	 */
+	public function filter_amp_optimizer_config( $configuration ) {
+		$configuration[ Optimizer\Transformer\RewriteAmpUrls::class ][ Optimizer\Configuration\RewriteAmpUrlsConfiguration::ESM_MODULES_ENABLED ] = false;
```
Comment (westonruter) [inline includes/Integrations/AMP.php:259]: Follow-up: #7704
