### PR TITLE
Fix opacity and hue sliders of color picker

### LINKED ISSUE #1901: Color picker: sliders are not draggable without focusing first
## Bug Description

The color picker sliders are not draggable unless the user focuses on the slider first.

## Expected Behaviour

The color picker sliders should always be draggable.

## Steps to Reproduce

1. Add a shape
2. Open the color picker
3. Try to use the opacity slider.
4. Not happening!

## Screenshots
sliders

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Relevant Technical Choices
- Adds margin between the color picker sliders and the footer since otherwise the color picker pointers are partially below the footer area and can't be dragged.

## Testing Instructions
- Add a text element
- Open color picker for the color
- Drag hue and opacity sliders from the pointer, verify it drags right away.

---

Fixes #1901

### CODE REVIEW

File: assets/src/edit-story/components/colorPicker/currentColorPicker.js [hunk 1]
```diff
@@ -92,6 +92,7 @@ const Footer = styled.div`
   font-size: ${CONTROLS_WIDTH}px;
   line-height: 19px;
   position: relative;
+  margin-top: 7px;
```
Comment (miina) [inline assets/src/edit-story/components/colorPicker/currentColorPicker.js:95]: @barklund Apparently the issue came just from the footer partially being on top of the slider pointers...

**Review by barklund — APPROVED** [review]
Excellent!
