### PR TITLE
Disable cross-origin isolation for contributors

### LINKED ISSUE #8163: Cross-Origin Isolation enabled for users without upload permissions
## Bug Description

Contributor users don't have permission to upload media.

Still, we needlessly enable cross-origin isolation for these users.

## Expected Behaviour

In order to prevent issues caused by cross-origin isolation, we should not enable it when user does not have permission to upload media anyway.

Without media upload it's an irrelevant setting.

## Steps to Reproduce

1. Log in as contributor user
2. Check `window.crossOriginIsolated` value in console

## Additional Context

- Plugin Version: 1.8.1
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Cross-origin isolation is currently needlessly enabled even if user cannot upload media.

## Summary

This PR adds a capability check to short-circuit this logic.

## Relevant Technical Choices

Updated `Cross_Origin_Isolation::is_needed()`, extended tests.

## User-facing changes

N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Log in as contributor user
2. Open editor
3. Check `window.crossOriginIsolated` value in console, see that it's `false`

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8163

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Should we also make the default value here false? 

https://github.com/google/web-stories-wp/blob/aba042904a3d612ae5ea24e279743ea8e22fd65f/includes/User/Preferences.php#L81-L92

Maybe we could even item the user from being able to update the user meta here?

If we did that we would not even need to change the logic in `is_needed`?

**Comment by spacedmonkey** [comment]
I think it is important the value loaded into the editor is false in this case.

**Comment by swissspidy** [comment]
> Should we also make the default value here false?

But video optimization should be enabled by default for users. How would you do that then?

**Comment by spacedmonkey** [comment]
> But video optimization should be enabled by default for users. How would you do that then?

Here is what I had in mind.

https://github.com/google/web-stories-wp/commit/d41d9ffcab7780c9f004a5b254e3c4696719142e

File: assets/src/edit-story/app/media/utils/useFFmpeg.js [hunk 1]
```diff
@@ -236,8 +240,10 @@ function useFFmpeg() {
   );
 
   return {
-    isFeatureEnabled,
-    isTranscodingEnabled,
+    isTranscodingEnabled:
+      hasUploadMediaAction &&
+      isTranscodingEnabled &&
+      isCrossOriginIsolationEnabled,
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useFFmpeg.js]: I find this a little hard to read. Can we set it to a const for readability.

Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useFFmpeg.js]: Done

File: assets/src/edit-story/app/media/utils/useFFmpeg.js [hunk 2]
```diff
@@ -231,12 +235,23 @@ function useFFmpeg() {
...
   );
 
+  /**
+   * Whether transcoding as a whole is supported.
+   *
+   * Considers user opt-in, cross-site isolation, and upload permissions.
+   *
+   * @type {boolean}
+   */
+  const isTranscodingEnabled =
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/utils/useFFmpeg.js:248]: Friendly reminder, this will effect - https://github.com/google/web-stories-wp/pull/7528

Comment (swissspidy) [reply assets/src/edit-story/app/media/utils/useFFmpeg.js:248]: @spacedmonkey noted! I'll happily resolve any conflicts that should emerge.

Anything else to be done here or is this good to go otherwise?

**Comment by swissspidy** [comment]
^ @spacedmonkey that's for you

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Review by spacedmonkey — APPROVED** [review]
This looks good. I still personally think that this https://github.com/google/web-stories-wp/pull/8166/commits/1932c57e342a8dbf445243b004cf3a1272c7fadb is a useful change and makes things a lot cleaner. But I understand why you removed it.
