### PR TITLE
Inspector: Update tertiary color in the design system (dark mode)

### LINKED ISSUE #7575: Inspector Tabs: Insufficient color contrast
## Bug Description

WCAG AA requirement for color contrast is a minimum of 4.5.

The inspector tabs (Design / Document / Checklist) do not meet this requirement, with a contrast ratio of only 3.53.

This is due to `theme.colors.fg.tertiary` using `gray[40]` (`#767E80`), whereas a lighter gray would be needed.

https://github.com/google/web-stories-wp/blob/4c891bd2b6b10815c72b06d7bbccd15718da79b1/assets/src/edit-story/components/tabview/index.js#L72-L73

## Expected Behaviour

Color contrast is increased and meets a11y requirements

## Screenshots

Current situation:

Screenshot 2021-05-18 at 23 26 31

Using `brand.gray[40]` (`#767E80`), color contrast ratio is only 3.53 ❌ 

Suggested change:

Screenshot 2021-05-18 at 23 26 44

Using `brand.gray[30]` (`#919899`), color contrast ratio increases to 4.99 ✅ 

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Summary

Increase color contrast in header buttons in the inspector.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

|Before|After|
|--|--|
|image|image|
|image|image|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Look at how pretty it is
2. You can do a contrast check if you'd like to as well. It's a little tricky since the header is _inheriting_ the color, so you'll have to manually add the color to the element in the dev tools and then check the color picker for the contrast data.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7575

### CODE REVIEW

File: packages/story-editor/src/components/tabview/index.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ const TabElement = styled.li.attrs(({ isActive }) => ({
   position: relative;
   transition: color 0.2s ease;
   color: ${({ theme, isActive }) =>
-    isActive ? theme.colors.fg.primary : theme.colors.fg.tertiary};
+    isActive ? theme.colors.fg.primary : theme.colors.gray[30]};
```
Comment (samwhale) [inline packages/story-editor/src/components/tabview/index.js]: No named property with `gray[30]` yet. If we start using it more we could consider adding one here:
image

Comment (BrittanyIRL) [reply packages/story-editor/src/components/tabview/index.js]: 🤔 should `tertiary` just be updated to `gray[30]` for consistency?

Comment (samwhale) [reply packages/story-editor/src/components/tabview/index.js]: >🤔 should tertiary just be updated to gray[30] for consistency?

That's a good question. I'm not sure what that would mean for the rest of the codebase. It's used in many other places


I can do a dive real quick to see if it would make anything lose contrast too

Comment (BrittanyIRL) [reply packages/story-editor/src/components/tabview/index.js]: yeah that would be good. my suspicion is that if this tertiary is currently too light for contrast here then it will be the case elsewhere. And since these headers were meant to be in line with the other spots using tertiary gray on the editor then those should also be updated - kinda the purpose of having the colors laid out like this. Sorry for being a nuisance about it - we're just almost a year into using this palette and have yet to have to add a billion grays in and i would love to keep it that way.

**Comment by samwhale** [comment]
Checked all the tertiary grays in the editor - the change was good for all but one. The date-time picker needed a darker gray:
Screen Shot 2021-10-28 at 5 27 22 PM
Screen Shot 2021-10-28 at 5 10 50 PM
Screen Shot 2021-10-28 at 5 11 14 PM
Screen Shot 2021-10-28 at 5 13 46 PM
Screen Shot 2021-10-28 at 5 18 25 PM
Screen Shot 2021-10-28 at 5 21 48 PM
Screen Shot 2021-10-28 at 5 22 53 PM

File: packages/story-editor/src/components/form/dateTime/timeZone.js [hunk 2]
```diff
@@ -37,7 +37,7 @@ const Wrapper = styled.div`
 `;
 
 const StyledText = styled(Text)`
-  color: ${({ theme }) => theme.colors.fg.tertiary};
+  color: ${({ theme }) => theme.colors.fg.disable};
```
Comment (samwhale) [inline packages/story-editor/src/components/form/dateTime/timeZone.js:40]: This needed a darker gray:
Screen Shot 2021-10-28 at 5 11 14 PM

Comment (BrittanyIRL) [reply packages/story-editor/src/components/form/dateTime/timeZone.js:40]: thank you soooo much for digging into this!!!

**Review by BrittanyIRL — APPROVED** [review]
really appreciate the extra checks here to see if swapping out the tertiary 40 for 30 would work. Given these all have the same background color i think it's a great way to solve this problem at the source.

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js [hunk 3]
```diff
@@ -25,9 +25,13 @@ import { clickButton, visitSettings } from '@web-stories-wp/e2e-test-utils';
 import { monetizationDropdownSelector } from '../../../../utils';
 
 describe('Admin User', () => {
-  it('should let me see and update all settings', async () => {
+  it('should let me see and update monetization settings', async () => {
     await visitSettings();
 
+    // Small trick to ensure we scroll to this input.
+    const monetizationDropdown = await page.$(monetizationDropdownSelector);
+    await monetizationDropdown.focus();
```
Comment (samwhale) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js:33]: this e2e test was failing because the page wasn't scrolled to this input

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js [hunk 4]
```diff
@@ -25,9 +25,13 @@ import { clickButton, visitSettings } from '@web-stories-wp/e2e-test-utils';
 import { monetizationDropdownSelector } from '../../../../utils';
 
 describe('Admin User', () => {
-  it('should let me see and update all settings', async () => {
+  it('should let me see and update monetization settings', async () => {
```
Comment (samwhale) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js:28]: this matches another test name. Updating this name so it's easier to find this test if if ever fails.

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js (hunk 3 above)
Comment (BrookeGraham) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/monetization.js:33]: 🚂

**Review by BrookeGraham — APPROVED** [review]
🌚

**Comment by miina** [comment]
> Checked all the tertiary grays in the editor - the change was good for all but one. The date-time picker needed a darker gray:

@samwhale Thanks for verifying all the uses! I didn't go through all the conversation / design channel in Slack so likely you already did that but if not, it would be good to let @agingoldseco know as well that the tertiary color of the Design System changed in the codebase so that she could use the updated color in Figma as well.

**Comment by samwhale** [comment]
> > Checked all the tertiary grays in the editor - the change was good for all but one. The date-time picker needed a darker gray:
> 
> @samwhale Thanks for verifying all the uses! I didn't go through all the conversation / design channel in Slack so likely you already did that but if not, it would be good to let @agingoldseco know as well that the tertiary color of the Design System changed in the codebase so that she could use the updated color in Figma as well.

Ah good shout, will do that right now

**Comment by samwhale** [comment]
@agingoldseco agrees with this change and we can merge this 🥳 https://xwp.slack.com/archives/C01ESBB8ZN1/p1635777929041500?thread_ts=1635773084.040900&cid=C01ESBB8ZN1
