### PR TITLE
Masks: avoid passing flip prop down to div element

### LINKED ISSUE #6564: Masks: `flip` attribute inadvertently added to DOM
## Bug Description

There's `flip="[object Object]"` in the DOM caused by the `WithMask` layer.

## Expected Behaviour

No `flip` attribute, certainly not with such a value.

## Screenshots

Screenshot 2021-03-01 at 17 50 52

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

I spotted `flip="[object Object]"` in the DOM and thought I'd fix it.

Screenshot 2021-03-01 at 17 50 52

## Summary

Fixes a small bug by not passing down `flip`.

## User-facing changes

N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6564

### CODE REVIEW

File: assets/src/edit-story/masks/frame.js [hunk 1]
```diff
@@ -163,11 +163,11 @@ export default function WithMask({
   style,
   children,
   eventHandlers = null,
+  flip,
```
Comment (miina) [inline assets/src/edit-story/masks/frame.js:166]: Needs props validation now, too.

Comment (swissspidy) [reply assets/src/edit-story/masks/frame.js:166]: Fixed!

**Review by barklund — APPROVED** [review]
In this case, it's not needed by S-C and we can just remove the prop, but in many other instances, S-C needs it for some styling + it's a valid DOM prop name (at least somewhere). For those cases, we really should start using [transient props with $-prefixing](https://styled-components.com/docs/api#transient-props). 

See e.g. `x` and `y` in your original screenshot on several elements. These props don't belong in the DOM, yet we output them because we're not using transient props (or a similar workaround).

screenshot
