### PR TITLE
Moveable: Update all elements together after group actions.

### LINKED ISSUE #1657: Group drag-resize-rotate actions go to history as multiple entries
## Bug Description

Currently, when multiple elements are selected and dragging, resizing, rotation applied, each element will create its own entry to history.

This comes from `updateElementsById` being applied in a loop to each element instead of collecting all the information and then applying it for all the elements together.

https://github.com/google/web-stories-wp/blob/7c22f4c2f1d021fcfc8cd38f76325c22220ad563/assets/src/edit-story/components/canvas/multiSelectionMovable.js#L146-L174

## Expected Behaviour

- One user interaction should go to history as one combined entry, too.

## Steps to Reproduce

1. Add a few elements
2. Select all and drag
3. Click undo
4. See the elements undoing one by one instead of together

## Screenshots
history

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

Adds group actions of Moveable to the history as one entry.

## Relevant Technical Choices

Uses `updateElementsById` with an updater to update all the elements at the same time instead of using it inside loop.

## To-do

Integration test would be good in the future.

## User-facing changes

When the user resizes/drags/rotates a group and then clicks Undo/Redo, the Undo/Redo will be applied to all the elements together now instead of one by one.

## Testing Instructions

1. Add a few elements.
2. Multi-select.
3. Drag these elements around
4. Use Undo-Redo
5. Verify that Undo-Redo applies to all the elements at the same time in the multi-selection (as opposed to first Undoing the action for one element, then for the second, etc.)
6. Verify the same for Resizing.
7. Verify the same for Rotation.

---

Fixes #1657

### CODE REVIEW

**Comment by swissspidy** [comment]
There are already some Jest tests for this in `assets/src/edit-story/components/canvas/test/multiSelectionMovable.js`. They now need to be updated as they currently expect multiple `updateElementsById` calls.

**Comment by miina** [comment]
> They now need to be updated as they currently expect multiple updateElementsById calls.

Yep, I'm actually not sure how to test this now, looking into it.

**Review by merapi — APPROVED** [review]
Works as expected ✅ 

At some point we can have tests that actually verify if one history record is created or if it works as expected in the UI.

File: assets/src/edit-story/components/canvas/test/multiSelectionMovable.js [hunk 1]
```diff
@@ -122,17 +122,19 @@ describe('multiSelectionMovable', () => {
     'should rotate %p',
     (_, { rotateTo, expectedRotationAngle }) => {
       arrange();
+
       performRotatation(rotateTo);
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/test/multiSelectionMovable.js]: Can you please rename this while you're here? _"rota**ta**tion"_?

**Review by barklund — APPROVED** [review]
Works as expected! 🎉

File: assets/src/edit-story/components/canvas/test/multiSelectionMovable.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/test/multiSelectionMovable.js]: Will do, it sounds nice though.

**Comment by barklund** [comment]
> At some point we can have tests that actually verify if one history record is created or if it works as expected in the UI.

The easiest way would be to click the undo button after multi-element transformation - if both are returned to old transform, it works.

**Comment by miina** [comment]
@merapi Note that this issue had already been moved to Ready for QA previously. Per new QA process once a PR is approved it doesn't get merged right away but just moves to "Ready for QA".
It's currently failing Travis now, could you please fix Travis and consent to Google to make CLA sign positive, too?

**Comment by merapi** [comment]
> @merapi Note that this issue had already been moved to Ready for QA previously. Per new QA process once a PR is approved it doesn't get merged right away but just moves to "Ready for QA".
> It's currently failing Travis now, could you please fix Travis and consent to Google to make CLA sign positive, too?

Sorry I missed the status (Update: I guess it was changed after my push?). On the bright side, it doesn't affect QA work (if it was already started). I will clean up the tests.

**Comment by merapi** [comment]
@googlebot I consent.

**Comment by miina** [comment]
> Sorry I missed the status (Update: I guess it was changed after my push?). On the bright side, it doesn't affect QA work (if it was already started). I will clean up the tests.

It was moved to QA yesterday already, however, for some reason only the issue updated and not the PR so it wasn't visible on the PR. (Did some additional changes to update it on the PR later, after your push) Oh, well... Next time.

File: assets/src/edit-story/components/canvas/multiSelectionMovable.js [hunk 2]
```diff
@@ -170,7 +171,19 @@ function MultiSelectionMovable({ selectedElements }) {
...
+      updates[element.id] = properties;
+    });
+    updateElementsById({
+      elementIds: Object.keys(updates),
+      properties: (currentProperties) => {
+        if (!updates[currentProperties.id]) {
+          return currentProperties;
+        }
+        return {
+          ...currentProperties,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/multiSelectionMovable.js]: I think the `updateElementsById()` does this `{...current, ...new}` for you anyway. The `currentProperties` here are only available to (a) give you an ID, and (b) to allow you to calculate a new value based on the previous. E.g. to apply an aspect ratio. But I think here your updates are just an override, so you can just do `return updates[currentProperties.id]`

File: assets/src/edit-story/elements/karma/multipleElementsHistory.js [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+    fullBleed: generateHelpersForBB(fullBleedBB),
+    safeZone: generateHelpersForBB(safezoneBB),
+  };
+};
+
+// eslint-disable-next-line no-unused-vars
+function sleep(ms) {
+  return new Promise((resolve) => setTimeout(resolve, ms));
+}
+jasmine.DEFAULT_TIMEOUT_INTERVAL = 60 * 1000;
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/karma/multipleElementsHistory.js]: This will be removed, right?

File: assets/src/edit-story/karma/_init.js [hunk 4]
```diff
@@ -119,6 +119,21 @@ beforeEach(() => {
   document.body.appendChild(rootEl);
   const body = rootEl.querySelector('test-body');
 
+  let clientX = -100;
+  let clientY = -100;
+  const innerCursor = document.body.appendChild(document.createElement('div'));
+  innerCursor.style =
+    'width:0px; height:0px; border-left: 10px solid red; border-bottom: 10px solid transparent; position:absolute; top:0; left:0; z-index:999; pointer-events:none;';
+  document.addEventListener('mousemove', (e) => {
```
Comment (dvoytenko) [inline assets/src/edit-story/karma/_init.js]: This should probably be `pointermove` and it should probably be with capture?

File: assets/src/edit-story/karma/_init.js [hunk 5]
```diff
@@ -119,6 +119,21 @@ beforeEach(() => {
   document.body.appendChild(rootEl);
   const body = rootEl.querySelector('test-body');
 
+  let clientX = -100;
```
Comment (dvoytenko) [inline assets/src/edit-story/karma/_init.js]: I like this idea, but I think we should separate it for now. Could you pls post this snippet in the feedback doc we have? I'll see the best way to instrument it.

**Review by dvoytenko — DISMISSED** [review]

File: assets/src/edit-story/elements/karma/multipleElementsHistory.js (hunk 3 above)
Comment (merapi) [reply assets/src/edit-story/elements/karma/multipleElementsHistory.js]: Yes, it will be removed when I push fixed for small canvas.

File: assets/src/edit-story/karma/_init.js (hunk 4 above)
Comment (merapi) [reply assets/src/edit-story/karma/_init.js]: This virtual cursor was just a test (helped me with debugging where the cursor is on small canvas), if we like it then I will apply comments and we can make it better (indicate which button was clicked/are we dragging etc.)

File: assets/src/edit-story/karma/_init.js (hunk 5 above)
Comment (merapi) [reply assets/src/edit-story/karma/_init.js]: Ok, I will remove it from here and post the idea.

File: assets/src/edit-story/elements/karma/multipleElementsHistory.js (hunk 3 above)
Comment (dvoytenko) [reply assets/src/edit-story/elements/karma/multipleElementsHistory.js]: K. The new tools for debugging are also now available. See https://github.com/google/web-stories-wp/blob/master/karma/README.md#debugging-karma-tests

File: assets/src/edit-story/karma/_init.js (hunk 4 above)
Comment (dvoytenko) [reply assets/src/edit-story/karma/_init.js]: I think I saw a Puppeteer plugin like this somewhere. I'll look.
