### PR TITLE
Fix the padding/alignment issues in highlight mode

### LINKED ISSUE #1980: Justify right behavior is off
## Bug Description

The “e” in the “one” is the only letter flushed to the right. This seems off. 

## Expected Behaviour

all letters and lines should be equally justified to the right

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #2089: Padding should be added to text element size
## Bug Description

When a 100x100 text element is added a 10px padding, it should be changed to a 120x120 text element (and move 10x10 pixel up), so the text will have identical location before and after.

Remember to do this correctly for rotated text fields too.

## Expected Behaviour

* Text field size and location should update as per above.

## Steps to Reproduce

1. Create a new text field
1. Add 20px padding both vertical and horizontal
1. Observe the text field size not increase, but rather shrink the actual text area

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Things to consider:

* Text fields placed on edge of canvas
* Multi-selection
* Rotated text fields

### LINKED ISSUE #2201: Text: Fill-highlight + padding = incorrect alignment
## Bug Description

Center- and right- text alignment are incorrect with "fill: highlight" and non-zero padding.

## Steps to Reproduce

1. Create a new text element
2. Set "Fill: Highlight" and padding: 20.
3. Set text alignment to "right" or "center".

Expected: The text is aligned to the right or center as expected.
Actual: The text is slightly offset to the left of its expected position.

## Screenshots

Screen Shot 2020-06-02 at 9 37 04 PM

## Additional Context

- Plugin Version: 1.0.0-alpha+edfbf49
- Operating System: macOS 10.15.4
- Browser: Chrome 83

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #3531: Padding should increase the line height in highlight mode
This is happening now, but it is not correctly implemented.

more details in this doc:
https://docs.google.com/document/d/1wchYL4ZClv6b7kSadOR0mQuOZmFAHu9F3klKiFRkGYs/edit#

### PR DESCRIPTION
**Pull request by merapi**
## Summary

There is still one issue with `box-decoration-break: clone + padding + center/right text alignment`, that looks like a browser bug and should be fixed there.
Open [this pen](https://codepen.io/merapi/pen/abNqeZB) on Chrome/Edge and compare it with Firefox/Safari.

Of course, we can shift the text element contents to the left by half of the padding only on Chrome/Edge, but that would require a small script in the output part and constant monitoring of the bugfix (once it's fixed - it will be broken on our side with this hack).

I've reported the issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1131880
https://bugs.chromium.org/p/chromium/issues/list?q=box-decoration-break&can=2

## Testing Instructions

---

Fixes #2201
Fixes #3531
Fixes #1980
Almost fixes #2089 (width is not changed and text not moved yet)

### CODE REVIEW

File: assets/src/edit-story/components/panels/preset/stylePreset/panel.js [hunk 1]
```diff
@@ -62,6 +62,8 @@ const PresetButton = styled.button`
 const HighLight = styled.span`
   padding: 0 2px;
   ${({ background }) => generatePatternStyles(background)}
+  /* stylelint-disable-next-line */
+  -webkit-box-decoration-break: clone;
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/stylePreset/panel.js]: Is this needed and not automatically added where relevant?

File: assets/src/edit-story/elements/text/edit.js [hunk 2]
```diff
@@ -316,16 +326,22 @@ function TextEdit({
       onClick={onClick}
       data-testid="textEditor"
       backgroundColor={wrapperBackgroundColor}
+      textPadding={textProps.padding}
     >
       {editorContent && backgroundTextMode === BACKGROUND_TEXT_MODE.HIGHLIGHT && (
-        <TextBox ref={highlightRef} {...textProps}>
+        <TextBox ref={highlightRef} {...textProps} padding={null}>
```
Comment (barklund) [inline assets/src/edit-story/elements/text/edit.js]: Can we unset the value in `textProps` instead? Or cloning `textProps` to a new `highlightTextProps` omitting the value?

File: assets/src/edit-story/elements/text/edit.js [hunk 3]
```diff
@@ -60,6 +60,15 @@ import {
 const Wrapper = styled.div`
   ${elementFillContent}
   ${elementWithBackgroundColor}
+
+  span[data-text="true"] {
```
Comment (barklund) [inline assets/src/edit-story/elements/text/edit.js]: This depends on a feature of `draftjs`, right? So if they happened to change this annotation, this would break?

**Review by barklund — COMMENTED** [review]
This works well - except for the weird jump in padding when moving in and out of edit mode (in Chrome on Mac), but if it's a browser bug, it's hard to do anything about at this point.

**Comment by merapi** [comment]
> This works well - except for the weird jump in padding when moving in and out of edit mode (in Chrome on Mac), but if it's a browser bug, it's hard to do anything about at this point.

Yep, something similar was [reported on Dec 6, 2019](https://bugs.chromium.org/p/chromium/issues/detail?id=1031719&q=box-decoration-break&can=2) and it's still not fixed, so maybe that workaround is not the worst option (or if somebody can put a higher priority on that bug - that would be awesome).

File: assets/src/edit-story/elements/text/edit.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/elements/text/edit.js]: Oh no, I completely broke this. Try having a text field with padding and mixed inline styling (some bold, some non-bold) - each separately styled sequence of characters will be wrapped in its own `<span data-text="true" />` and the sentence will thus have inline padding in-between characters:

broken-text-padding

File: assets/src/edit-story/components/panels/preset/stylePreset/panel.js (hunk 1 above)
Comment (merapi) [reply assets/src/edit-story/components/panels/preset/stylePreset/panel.js]: It enlightened me now, it's only needed in the output.js (without stylelint-disable, the prefixed version will be replaced with the non-prefixed version and it will break the output style [something is not right with stylelint in that matter]).

File: assets/src/edit-story/elements/text/edit.js (hunk 2 above)
Comment (merapi) [reply assets/src/edit-story/elements/text/edit.js]: Done, it's cleaner now.

File: assets/src/edit-story/elements/text/edit.js (hunk 3 above)
Comment (merapi) [reply assets/src/edit-story/elements/text/edit.js]: Yes, that's the downside, not sure if there is a clean/easy way to really future proof it (maybe we could add a class to every span with text contents in DraftJS and then target it here?).

Comment (merapi) [reply assets/src/edit-story/elements/text/edit.js]: @barklund That complicates things, I will look into it, but the worst part is that `box-decoration-break: clone;` doesn't work for multiple/nested span elements (combining them into one).

**Comment by barklund** [comment]
@carlos-kelly, remember to [consent to our robot overlords](https://github.com/google/web-stories-wp/pull/4675#issuecomment-703838890)! 🤖 👑

**Comment by carloskelly13** [comment]
@googlebot I consent.

**Comment by carloskelly13** [comment]
image

@barklund I think this PR should get us a lot closer. There will always be slight discrepancies between our display layer and DraftJS, but the highlights, paddings and margins seem to be very similar now between the two modes.

**Review by barklund — APPROVED** [review]
Yeah, this is probably as good as it gets with an external library for rich text editing. And we're not going to build our own library for that anytime soon!

Excellent effort here. 🎉
