### PR TITLE
Pre-Publish Checklist: Fix background contrast check giving false positives

### LINKED ISSUE #5905: Prepublish Checklist - background contrast check giving false positives
## Bug Description

Originally reported by @barklund 
Text contrast calculation is ignoring background image overlay. It’s not uncommon to use the overlay to make the bottom or top of the image bright or dark to give contrast, but this isn’t used for the calculation, it seems.

## Screenshots

image9

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Context
I'm noting that there are/may be other issues because of this particular check's potentiality for failing edge cases and I want to keep each PR scoped to known and tractable issues. 

The intention of this fix is to address a more obvious bug where the accessibility check is not using the correct background color for shape/background overlays and the color of the text wasn't getting picked out at all. 

## Summary
- use the `page` object's background color instead of the background color of the background `shape` element. 
- add the default black text color to be compared to background colors

## Relevant Technical Choices
- The `backgroundColor` for shape backgrounds was replaced with the page's background color because the `backgroundColor` property for [shape backgrounds never gets updated and is inactive](https://github.com/google/web-stories-wp/issues/5905#issuecomment-771227657):
> But the deprecated (and utterly inactive) backgroundColor property on the default background element is definitely making things harder to spot. We should probably address that at some point...

- Text elements aren't always have a `span` or a `style.color`. This meant in the original implementation we were seeing no text color associated with the default text element, for example, or text elements that do not have color styles on their spans. By default the color of this text is black. I fixed the logic to push the default text color into the array to be compared to the background colors.

## To-do
- [x] make a techdebt ticket for addressing the inactive `backgroundColor` property on the background element (done [here](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6315))
- [x] unit test for regression

## User-facing changes
N/A

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new story
2. Add a black background
3. Click the + symbol to add the default text element
4. The text contrast check should appear in the prepublish checklist where it didn't before

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5905

### CODE REVIEW

File: assets/src/edit-story/app/prepublish/warning/test/accessibility.js [hunk 1]
```diff
@@ -101,6 +102,64 @@ describe('Pre-publish checklist - accessibility issues (warnings)', () => {
     });
   });
 
+  describe('pageBackgrounTextLowContrast', () => {
```
Comment (BrittanyIRL) [inline assets/src/edit-story/app/prepublish/warning/test/accessibility.js]:
```suggestion
  describe('pageBackgroundTextLowContrast', () => {
```

**Review by BrittanyIRL — APPROVED** [review]
Works as you outlined, thanks for keeping scope tight on this and adding a test!

**Review by maxyinger — APPROVED** [review]
