### PR TITLE
Fix file drag & drop crash for unsupported media types

### LINKED ISSUE #1342: Dropping an unsupported file on Media Library crashes the editor
## Bug Description

Dropping an unsupported file on Media Library crashes the editor (Page works fine).

## Expected Behaviour

Should just show the error message (snackbar).

## Steps to Reproduce

Drop e.g. PDF file on **Media Library**

## Screenshots
image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ezxyz**
##  Summary
Fixes the drag and drop crash issue when an unsupported file type is dragged into the media pane (for example a .txt file). 

## Relevant Technical Choices

The issue was originally happening because "filterResources" in media pane was being called with 'null". I made changes so that:
1) Null should never be put inside the "media" context (via. uploadMedia).
2) Filter resources can handle null argument (just in case null is being passed into media context in some other way)
3) Made the "processor" function in mediaProvider, be skipped if there is a null (this results in a warning if there is a null value in the media file).

This meant I had to filter out unsupported filetypes from uploadMedia. This part was unit tested.

Fixes #1342

### CODE REVIEW

File: assets/src/edit-story/app/media/mediaProvider.js [hunk 1]
```diff
@@ -126,15 +126,19 @@ function MediaProvider({ children }) {
...
+      const { mimeType, posterId, id, src, local } = el;
+      const process = () => {
         if (
           allowedVideoMimeTypes.includes(mimeType) &&
           !local &&
           !posterId &&
           id
         ) {
-          await uploadVideoPoster(id, src);
+          uploadVideoPoster(id, src);
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/mediaProvider.js]: If we don't await this promise here, does it not run?

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js [hunk 2]
```diff
@@ -62,6 +62,8 @@ function useUploadMedia({ media, pagingNum, mediaType, fetchMedia, setMedia }) {
             localResource: await getResourceFromLocalFile(file),
             file,
           }))
+        ).then((newLocalFiles) =>
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Can you use await and then together like this?

Comment (ezxyz) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: https://codesandbox.io/s/nostalgic-meitner-6g4e3?file=/src/index.js

I tried something similar here to show what happens.

Then only gets run after the promise gets fulfilled.  The promise will only get fulfilled after the getResourceFromLocalFile gets resolved.

See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 1 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/mediaProvider.js]: I removed this one because uploadVideoPoster() was not async as far as I can tell. If you look above, the callback isn't an asynchronous function and hence doesn't return a promise. (It does create an asynchronous function inside the callback and then call it, but it doesn't await on the response of that promise).

Hence I thought putting await here wasn't doing anything.

Comment (ezxyz) [reply assets/src/edit-story/app/media/mediaProvider.js]: On second thought, I decided to change this back to the previous version (with an async await) since I'd prefer to keep this PR related to just the File drag and drop crash issue.

File: assets/src/edit-story/app/media/test/useUploadMedia.test.js [hunk 3]
```diff
@@ -0,0 +1,110 @@
+/*
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/test/useUploadMedia.test.js]: Nit: No need for the `.test` suffix in the file name

File: assets/src/edit-story/app/media/mediaProvider.js [hunk 4]
```diff
@@ -126,7 +126,11 @@ function MediaProvider({ children }) {
   );
 
   const processor = useCallback(
-    ({ mimeType, posterId, id, src, local }) => {
+    (el) => {
+      if (!el) {
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/mediaProvider.js]: Alternatively do something like `return accumulatorPromise.then(() => el && processor(el));` below? And let `processor` assume it always gets passed a valid element

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: It works, although it could just as well be:

```js
localFiles = await Promise.all(
  files.reverse().map(async (file) => ({
    localResource: await getResourceFromLocalFile(file),
    file,
  }))
);
localFiles = localFiles.filter((f) => f.localResource != null)
```

edit: fixed code sample as per Jon's comment

Comment (ezxyz) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: So the actual code for that will be

`localFiles = localFiles.filter((...))` since filter actually returns the filtered array and doesn't change the actual array itself.

I personally prefered using "then" as it shows that its tied to the promise. However if you feel strongly about this, I'm happy to change it.

File: assets/src/edit-story/app/media/mediaProvider.js (hunk 4 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/mediaProvider.js]: SGTM. I've added that implementation.

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 2 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: I think it is confusing to have an await and a then. In my mind, it is one of the other. I don't think either way, just pick one.

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Comment by spacedmonkey** [comment]
This PR was 134 commits behind master. So the code coverage tests failed.

**Comment by ezxyz** [comment]
@googlebot I consent

File: assets/src/edit-story/app/media/test/useUploadMedia.test.js (hunk 3 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/media/test/useUploadMedia.test.js]: That came from me. I'm ok to drop that pattern if others are feeling strongly.

File: assets/src/edit-story/components/library/panes/media/mediaPane.js [hunk 5]
```diff
@@ -212,7 +212,11 @@ function MediaPane(props) {
   };
 
   const filterResource = useCallback(
-    ({ mimeType, width, height }) => {
+    (resource) => {
+      if (!resource) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/library/panes/media/mediaPane.js]: This seems like hiding a problem. Why would we have `null` resources? I'd rather we fix at the source.

**Review by dvoytenko — DISMISSED** [review]

File: assets/src/edit-story/components/library/panes/media/mediaPane.js (hunk 5 above)
Comment (ezxyz) [reply assets/src/edit-story/components/library/panes/media/mediaPane.js]: Fixed it so we don't have null resource.

File: assets/src/edit-story/app/media/test/useUploadMedia.test.js (hunk 3 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/test/useUploadMedia.test.js]: Done.

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 2 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Chose the localFiles = localFiles.filter version.

File: assets/src/edit-story/app/media/test/useUploadMedia.js [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+      })
+    );
+
+    const { uploadMedia } = result.current;
+
+    await act(() => uploadMedia(newFiles));
+
+    expect(setMedia).toHaveBeenCalledTimes(1);
+
+    const sortedMediaArgs = setMedia.mock.calls[0][0].media.sort(sortBySrc);
```
Comment (barklund) [inline assets/src/edit-story/app/media/test/useUploadMedia.js]: With [`toIncludeSameMembers()` from `jest-extended`](https://github.com/jest-community/jest-extended#toincludesamemembersmembers), you could avoid all this sorting both here and above. It's cleaner, IMHO.

Comment (ezxyz) [reply assets/src/edit-story/app/media/test/useUploadMedia.js]: Done.

**Review by spacedmonkey — APPROVED** [review]
LGTM

**Review by swissspidy — APPROVED** [review]
