### PR TITLE
Dates: Fix timezone inconsistencies

### LINKED ISSUE #5522: Dates: editor and dashboard not using WordPress timezone
## Bug Description
The time stamped in the editor displays the user's local time instead of the timezone set in WordPress. Notice the timestamps in the below screenshots:
- User 1 who drafted the story in PST: https://jmp.sh/XPocoVG
- User 2 who accessed the story in EST: https://jmp.sh/Lk6FPC2
Both users' timezone was [set to Los Angeles in WordPress settings](https://jmp.sh/Cn6oZ0x).

## Expected Behaviour

The editor should use the timezone from the WordPress timezone.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Addresses some unexpected behavior when the site's timezone differs from the user's timezone.

Overall I tried to compare this to how dates are handled in the "All Stories" view (aka classic WP list view) and the Gutenberg block editor, ensuring that the results are the same everywhere.

## Relevant Technical Choices

* Does not use the REST API response's `date_gmt` anywhere anymore, but `date` itself instead
* Dates aren't immediately parsed as such when loading the story, but instead only when needed for formatting or comparison.  
  This was previously the case in the dashboard.
* Do not use relative date formatting if the date is today, but in the future.  
  Otherwise you'll get "Published in an hour", which is verry misleading.

## User-facing changes

No user-facing changes, just dates that now should be displayed correctly.

### Scenario A: Timezone Moscow

1. Set your site's timezone to Moscow
2. Create a new story
3. In the Document panel, see that the publish date is displayed in Moscow timezone
4. The "Publish" button should read "Publish", not "Schedule"
5. Publish the story
6. Go to "My Stories" and see that the date says "x minutes ago"
7. Go to "All Stories" and see that story date is in Moscow timezone

To double check, publish a new blog post as well, and see how dates are displayed there.

### Scenario B: Timezone Honolulu

1. Set your site's timezone to Honolulu
2. Create a new story
3. In the Document panel, see that the publish date is displayed in Honolulu timezone
4. The "Publish" button should read "Publish", not "Schedule"
5. Publish the story
6. Go to "My Stories" and see that the date says "x minutes ago"
7. Go to "All Stories" and see that story date is in Honolulu timezone

To double check, publish a new blog post as well, and see how dates are displayed there.

---

Fixes #5522

### CODE REVIEW

**Comment by spacedmonkey** [comment]
+1 to this. Seems WordPress core doesn't use gmt by local to display post date. See [get_post_time](https://github.com/WordPress/wordpress-develop/blob/c19f56747fba5f880c42050955e41fc894dccd32/src/wp-includes/general-template.php#L2686-L2728).

File: assets/src/edit-story/components/header/buttons/publish.js [hunk 1]
```diff
@@ -65,7 +68,11 @@ function Publish() {
     : null;
 
   const refreshPostEditURL = useRefreshPostEditURL(storyId);
-  const hasFutureDate = Date.now() < Date.parse(date);
+  // Offset the date by one minute to accommodate for network latency.
+  const hasFutureDate = isAfter(
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/header/buttons/publish.js:70]: Should this be wrapped in `useMemo`? This comparison feels like it might be expensive.

File: assets/src/date/convertFormatString.js [hunk 2]
```diff
@@ -19,6 +19,7 @@
  */
 import { getDaysInMonth, isLeapYear, format } from 'date-fns';
 import { format as formatWithTZ, zonedTimeToUtc, toDate } from 'date-fns-tz';
+
```
Comment (spacedmonkey) [inline assets/src/date/convertFormatString.js]: ?

File: assets/src/dashboard/app/serializers/savedTemplates.js [hunk 3]
```diff
@@ -22,16 +22,15 @@ import { __ } from '@wordpress/i18n';
  * Internal dependencies
  */
 import { migrate, DATA_VERSION } from '../../../edit-story/migration/migrate';
-import { toUTCDate } from '../../../date';
```
Comment (spacedmonkey) [inline assets/src/dashboard/app/serializers/savedTemplates.js:25]: Do we need the function `toUTCDate` ? It is being used for anything?

File: assets/src/edit-story/components/header/buttons/publish.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/header/buttons/publish.js:70]: is it likely that `hasFutureDate` needs to be checked anywhere else, this could be moved to /date and imported.

File: assets/src/edit-story/components/header/buttons/publish.js [hunk 4]
```diff
@@ -39,6 +40,8 @@ import { usePrepublishChecklist } from '../../inspector/prepublish';
 import { PRE_PUBLISH_MESSAGE_TYPES } from '../../../app/prepublish';
 import { ButtonContent, WarningIcon } from './styles';
 
+export const ONE_MINUTE_IN_MS = 60 * 1000;
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/header/buttons/publish.js]: Should this live here https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/constants.js

**Comment by spacedmonkey** [comment]
This is looking good. A couple of questions and tweaks.

File: assets/src/edit-story/components/header/buttons/publish.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/components/header/buttons/publish.js:70]: I'll see if I can perhaps just use `isFuture` from date-fns here

File: assets/src/dashboard/app/serializers/savedTemplates.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/dashboard/app/serializers/savedTemplates.js:25]: Good point, I think it is now unused.

File: assets/src/edit-story/components/header/buttons/publish.js (hunk 4 above)
Comment (swissspidy) [reply assets/src/edit-story/components/header/buttons/publish.js]: As long is as it's only used by this one component it's probably easier to just keep here so it's not accidentally forgotten with a refactoring.

**Review by BrittanyIRL — COMMENTED** [review]
I guess I just want to make sure I'm understanding what we want to happen accurately. 

In this situation, is this accurate? 
- My timezone is set to Moscow and I've published a new story at 7:22 PM. 
- I update my timezone to be in honolulu and return to my dashboard, my moscow story still reads that it was published at 7:22 PM. 

Really it's been 2 minutes and I've just changed my timezone so shouldn't it say 6:22 AM since the story has been published the same amount of time?

**Comment by swissspidy** [comment]
> Really it's been 2 minutes and I've just changed my timezone so shouldn't it say 6:22 AM since the story has been published the same amount of time?

In theory, yes. But since WP does not store date information with timezones, all we know is that is was published at 7:22 PM. That's what we show to the user.

What I am aiming for here is mainly consistency. If the "All Stories" page says 7:22 PM, so should we. Otherwise users will be very confused.

**Comment by BrittanyIRL** [comment]
> > Really it's been 2 minutes and I've just changed my timezone so shouldn't it say 6:22 AM since the story has been published the same amount of time?
> 
> In theory, yes. But since WP does not store date information with timezones, all we know is that is was published at 7:22 PM. That's what we show to the user.
> 
> What I am aiming for here is mainly consistency. If the "All Stories" page says 7:22 PM, so should we. Otherwise users will be very confused.

ahhh I see now, ok thank you for elaborating.

**Comment by BrittanyIRL** [comment]
Sorry, one more clarification. 

I'm in Honolulu still, which is 3 hours behind MST where I actually am, which is known by my browser (not WordPress). My relative time for this shows "published 3 hours ago" for my honolulu stories that I just created. 

I don't think anything is wrong with your logic, the 3 hours matches the time displayed in all stories, it just seems like the relative time display has potential for adding confusion here/ if continuity is the goal, should we abandon the relative timing and just display the true time?  

(It's also causing my sort on dashboard for "last modified" to be weird, the initial moscow story which is published 7:22pm is showing up as the most recently modified even though i've made honolulu stories after the moscow story- which is probably an edge case we don't need to worry about)

**Comment by swissspidy** [comment]
@BrittanyIRL What‘s your timezone in WP? It is all relative to that

edit: I see what you mean now

**Comment by swissspidy** [comment]
> Sorry, one more clarification.
> 
> I'm in Honolulu still, which is 3 hours behind MST where I actually am, which is known by my browser (not WordPress). My relative time for this shows "published 3 hours ago" for my honolulu stories that I just created.
> 
> I don't think anything is wrong with your logic, the 3 hours matches the time displayed in all stories, it just seems like the relative time display has potential for adding confusion here/ if continuity is the goal, should we abandon the relative timing and just display the true time?
> 
> (It's also causing my sort on dashboard for "last modified" to be weird, the initial moscow story which is published 7:22pm is showing up as the most recently modified even though i've made honolulu stories after the moscow story- which is probably an edge case we don't need to worry about)

@BrittanyIRL we could perhaps continue to use date_gmt for the relative time?

**Review by BrittanyIRL — APPROVED** [review]
Thanks for the updates! This makes sense swapping timezones, stories appear to have been created for the relative same amount of time regardless of timezone.
