### PR TITLE
Floating Menu: Fix "Saved Color" (gradient) as border color causes crash

### LINKED ISSUE #11019: Floating Menu: Apply "Saved Color" as border color causes crash
## Bug Description

Found by @LuckynaSan  during bug bash, confirmed by Brittany 

> Editor crashes when you add a masked border to an element & select a saved color on the floating menu bar.

Note, this isn't an issue if you apply color for a border in the panel because saved colors aren't available there for border colors. Furthermore, it seems like it's just gradients causing the crash. Makes sense. 

## Steps to Reproduce

1) Insert element 2) Apply border from floating menu bar 3) open color picker 4) Select saved color (green in this case) 5) Editor crashes with error message below
## Screenshots

Screen Shot 2022-03-22 at 10 42 00 AM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Saved colors can include gradients, but gradients shouldn't be border colors - that was causing the crash noted in bug bash.

## Summary

I chose to fix this by not showing saved colors in the border color popup of the floating menu because the border color popup in the style pane doesn't show saved colors either and this felt more consistent to me. 

That said, we should discuss (if this hasn't happened yet and I am just unaware) allowing saved styles for borders. I tried that first and it's fine as long as `allowsGradient` is false. There's be an update necessary in `useAddPreset` to grab a color from a border - right now that doesn't exist so adding a new saved color doesn't work. 

## Relevant Technical Choices

- Fixes a casing typo that doesn't really matter because it's false but still `hasEyeDropper` not `hasEyedropper`
- `pickerHasEyedropper` is set to false on the border color level to override the shared eyedropper setting in the floating menu color component.
- `allowsSavedColors` is overridden also so that it doesn't show by default. 

## To-do

While debugging this found that the eyedropper in the border color popup isn't actually getting the border color. I set `pickerHasEyedropper` to false so it's hidden for now but we should fix it. https://github.com/GoogleForCreators/web-stories-wp/issues/11024

## User-facing changes

| Broken | Fixed | 
| --- | --- | 
| https://user-images.githubusercontent.com/10720454/159569958-a9704fd0-ccc2-43e4-aa85-2770587d6b0f.mp4 | https://user-images.githubusercontent.com/10720454/159570083-84cdc6c2-1ce3-4bf8-8cea-a7208c76230a.mp4 |

## Testing Instructions

Give elements borders and border colors and see that it doesn't crash. 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11019

### CODE REVIEW

File: packages/story-editor/src/components/colorPicker/basicColorPicker.js [hunk 1]
```diff
@@ -197,41 +197,40 @@ function BasicColorPicker({
...
-                allowsOpacity={allowsOpacity}
-                allowsGradient={allowsGradient}
-                aria-labelledby="colorpicker-saved-colors-title"
-                isEditMode={isEditMode}
-                changedStyle={changedStyle}
-              />
-            </>
-          )}
-        </SavedColors>
+        {allowsSavedColors && (
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/colorPicker/basicColorPicker.js:200]: Check for allowing saved colors before rendering the container to avoid an orphaned border when its just default colors showing.

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 2]
```diff
@@ -137,8 +137,10 @@ function BorderWidthAndColor() {
           value={border.color || BLACK}
           onChange={handleColorChange}
           hasInputs={false}
-          hasEyeDropper={false}
+          hasEyedropper={false}
```
Comment (samwhale) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:140]: nice catch

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 3]
```diff
@@ -137,8 +137,10 @@ function BorderWidthAndColor() {
...
           allowsOpacity={canHaveBorderOpacity}
+          pickerHasEyedropper={false} // override shared floating menu Color component TODO https://github.com/GoogleForCreators/web-stories-wp/issues/11024
+          allowsSavedColors={false} // if this changes to true, need to change allowsGradient to false because borders cannot be gradient.
```
Comment (samwhale) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js]: 💭 if one of `allowGradient` or `allowSavedColors` must be false, then we should add that in here:
```suggestion
          pickerHasEyedropper={false} // override shared floating menu Color component TODO https://github.com/GoogleForCreators/web-stories-wp/issues/11024
          // Borders cannot be gradients.
          // One of `allowSavedColors` or `allowGradient` must be false.
          allowsSavedColors={!allowGradient} 
          allowGradient={allowGradient}
```

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 4]
```diff
@@ -137,8 +137,10 @@ function BorderWidthAndColor() {
           value={border.color || BLACK}
           onChange={handleColorChange}
           hasInputs={false}
-          hasEyeDropper={false}
+          hasEyedropper={false}
           allowsOpacity={canHaveBorderOpacity}
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: I think this is gonna need to be false as well 🤔 Since I can go to custom colors, it will show gradient as an option then 💥 

Screen Shot 2022-03-22 at 2 50 28 PM
Screen Shot 2022-03-22 at 2 48 11 PM

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js (hunk 3 above)
Comment (samwhale) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js]: Also - can we add a small unit test here?

**Review by samwhale — APPROVED** [review]
This works great! Would be nice if we could add a small unit test to prevent future regressions.

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js (hunk 4 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: Or rather, `allowsGradient` should be false as well

**Review by BrookeGraham — CHANGES_REQUESTED** [review]
gradient

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js (hunk 4 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:141]: oh yup, you're super right. i completely ignored that button.

**Comment by BrittanyIRL** [comment]
> This works great! Would be nice if we could add a small unit test to prevent future regressions.

I think this is going to need follow up (see #11024 so I'm going to hold on that to make sure design has time to figure out what they want where)

**Comment by BrittanyIRL** [comment]
Thanks for the catch, Brooke!
All fixed
Screen Shot 2022-03-22 at 2 02 03 PM

**Comment by samwhale** [comment]
Oh heck yeah, Brooke! Great catch there.

**Comment by BrookeGraham** [comment]
Only caught it cause I swear I had already fixed it. 🤷

**Review by BrookeGraham — APPROVED** [review]
🌈
