### PR TITLE
Fix some of the skipped tests + Use visible page as the fullbleed container

### LINKED ISSUE #6948: Fix Failing Copy Image Karma Tests
These tests have been disabled: 

- should correctly copy pattern background to page with image
- should correctly copy image to page without image
- should correctly copy image to page with existing image 

They should be fixed and enabled.

### LINKED ISSUE #6949: Fix Failing edit/delete menu karma test
These tests have been disabled: 

- should open the edit/delete menu

They should be fixed and enabled.

### LINKED ISSUE #6951: Fix failing focus border test
This test if failing and has been disabled 
- should correctly show focus border only when using keyboard

Test should be fixed and enabled

### LINKED ISSUE #6952: Fix failing overlay karma tests
These tests are failing and have been disabled
- should not render an overlay when there is none
- should render panel when there is an image in the background
- should render correct overlay when clicking "solid"
- should render correct overlay when clicking "linear"
- should render correct overlay when clicking "radial"
- should replace top image when bg image is set and another one is on top

Tests should be fixed and enabled

### LINKED ISSUE #6954: Fix failing image resource loading integration karma test
This test is failing and has been disabled. It should be fixed and enabled. 
`should use cached thumbnail then switch to fullsize` 
`TypeError: Cannot read property 'type' of undefined`

### PR DESCRIPTION
**Pull request by miina**
## Summary
- Refactors the layers a bit so that the fullbleed container would match the visible Page size. The fullbleed ref now refers to the previous `PageWithOverflow`.
- Fixes the tests by starting dragging the elements from media considering some margin, previously it started dragging from the very edge of the media element but apparently that's not working in the CI anymore.
- Removes the 3 different versions of defining if an area has overflow (`canOverflow`, `overflow`, `showOverflow`) and keeps one only.

## User-facing changes
N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6952 
Fixes #6948 
Fixes #6949 
Fixes #6951 
Fixes #6954

### CODE REVIEW

File: assets/src/edit-story/components/canvas/layout.js [hunk 1]
```diff
@@ -346,12 +340,8 @@ const PageArea = forwardRef(function PageArea(
     })
   );
   return (
-    <PageAreaFullbleedContainer
-      ref={fullbleedRef}
-      data-testid="fullbleed"
-      aria-label={__('Fullbleed area', 'web-stories')}
-      role="region"
-      overflow={overflow}
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/layout.js:354]: I think a reference to this one is still needed in some places, but I'll fix that when merged. Good job here!

**Review by barklund — APPROVED** [review]
Good effort - I think this can safely be merged without QA.
