### PR TITLE
Editor: Fix issue with changing text height due to line breaks

### LINKED ISSUE #2218: Text height changing
## Bug Description

See video. When I have a text for which I inserted a line before and after the text (by pressing the enter key), I get the right effect I wanted. However, when I enter edit mode for that text element the before and after lines are removed. This shouldn't be happening. 

## Expected Behaviour

Lines should not be removed when I re-enter text edit mode for that text element.

## Screenshots

[See video](https://drive.google.com/open?id=1Xyg5LbP35mxcGX88luHWBJ_v_wHdM0SH)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dmmulroy**
## Summary

This fixes the bug where if a text box has line breaks and use activates edit mode the line breaks were being removed and appearing as if the text box was resizing.

## Relevant Technical Choices

Removed the lookahead regex to correctly replace all linebreaks when importing the content of the text box into DraftJS.

## User-facing changes

Users should no longer see text boxes with linebreaks "resize"/remove the linebreaks when entering into edit mode

## Testing Instructions

1. Create or open an existing story
2. Create a textbox with some dummy text
3. Include a linebreak as the first character and as the last
4. Click off the canvas to exit Edit Mode
5. Double back on the text box to enter Edit Mode
6. See that the text height remains the same and the linebreaks are preserved

### Before
2218-before

### After
2218-after

---

#2218

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
😎

**Review by carloskelly13 — DISMISSED** [review]
This does what it says. The lines on top and bottom were preserved.

**Comment by swissspidy** [comment]
Sounds like a good opportunity to add tests to prevent this from regressing in the future. WDYT?

File: assets/src/edit-story/components/richText/customImport.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ function customInlineFn(element, { Style }) {
 function importHTML(html) {
   const htmlWithBreaks = (html || '')
     // Re-insert manual line-breaks for empty lines
-    .replace(/\n(?=\n)/g, '\n<br />')
+    .replace(/\n/g, '\n<br />')
```
Comment (barklund) [inline assets/src/edit-story/components/richText/customImport.js]: The old regex was there for a reason - this now duplicates newlines between existing lines of text:

newline-multiplier

**Review by barklund — CHANGES_REQUESTED** [review]
This unfortunately breaks with in-text new lines - see comment.

Please add karma tests with screenshots of text editing with newlines both trailing, in-between text and leading - and both before leaving, after leaving **and** after re-entering edit mode to verify, that it all works correctly.

Also make sure at least one test works as a regression test of this particular bug.

File: assets/src/edit-story/components/richText/customImport.js (hunk 1 above)
Comment (merapi) [reply assets/src/edit-story/components/richText/customImport.js]: +1
nls

Comment (carloskelly13) [reply assets/src/edit-story/components/richText/customImport.js]: This was my concern that the regex was there. Perhaps the solution here is to not trim trailing and leading line breaks rather than internal ones. Then we can unit test the function to verify that.

Comment (dmmulroy) [reply assets/src/edit-story/components/richText/customImport.js]: This should be fixed now.

**Comment by dmmulroy** [comment]
@barklund @merapi The above issues should be resolved

2218-fixed

File: package.json [hunk 2]
```diff
@@ -207,7 +207,7 @@
     "test:js:watch": "npm run test:js -- --watch",
     "test:karma": "npm-run-all --parallel test:karma:*",
     "test:karma:edit-story": "karma start karma-edit-story.config.cjs --single-run",
-    "test:karma:edit-story:watch": "karma start karma-edit-story.config.cjs",
+    "test:karma:edit-story:watch": "karma start karma-edit-story.config.cjs --debug",
```
Comment (merapi) [inline package.json]: Should we remove it? (you can always add that when running the command if needed)

**Review by merapi — APPROVED** [review]
Looks good now 👍

**Comment by swissspidy** [comment]
@dmmulroy @barklund Seems like this one can be merged once Morten's requested changes have been addressed. Morten, wanna re-review?

**Comment by merapi** [comment]
@googlebot I consent.

**Comment by merapi** [comment]
Pushed a potential fix for https://github.com/google/web-stories-wp/issues/1952.
I think they should be tested together.

There are other ways, but more convoluted because of those WordPress global styles:
image

File: assets/src/edit-story/elements/text/karma/edit.karma.js [hunk 3]
```diff
@@ -136,4 +136,70 @@ describe('TextEdit integration', () => {
...
+      let textElement;
+      let initialHeight;
+
+      beforeEach(async () => {
+        await fixture.events.click(frame);
+        textElement = fixture.querySelector('[data-testid="textEditor"]');
+        initialHeight = textElement.getBoundingClientRect()?.height;
+      });
+
+      it('should not change height when entering and exiting edit mode', async () => {
```
Comment (barklund) [inline assets/src/edit-story/elements/text/karma/edit.karma.js:174]: Could we add a snapshot here both before and after entering edit mode and after leaving it again? Just to make sure it looks correctly too.

It's just inserting `await data.fixture.snapshot('Trailing and leading newlines, before editmode');` or similar description in three different places here (and confirming the snapshots on Percy).

**Review by barklund — APPROVED** [review]
This works perfectly now - awesome attention to detail here. Great result, @dmmulroy!

(just one ask regarding snapshots)

File: assets/src/edit-story/elements/text/karma/edit.karma.js (hunk 3 above)
Comment (dmmulroy) [reply assets/src/edit-story/elements/text/karma/edit.karma.js:174]: Done 👍
