### PR TITLE
Reverted to older popup logic

### LINKED ISSUE #6496: Redesign: Tooltips misplaced
## Bug Description

Tooltips are weirdly misplaced in the carousel menu.

## Expected Behaviour

Tooltips should be placed next to the hovered item.

## Steps to Reproduce

1. Hover the page grid button
2. Observe tooltip completely out of place at the top of the workspace

## Screenshots

tooltip-bug

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

Reverting to (maybe?) older popup logic, as the previous logic was broken in the editor.

### QA

This PR can be tested by following these steps:

1. Hover the grid view icon in the carousel menu
2. Observe tooltip appearing just over button and not at the top of the browser

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6496

### CODE REVIEW

File: assets/src/design-system/components/popup/utils/getOffset.js [hunk 1]
```diff
@@ -106,12 +105,8 @@ export function getOffset(placement, spacing, anchor, dock, popup) {
   // Vertical
   const offsetY = getYOffset(placement, spacingV, anchorRect);
 
-  // use window.pageYOffset instead of bodyRect.height to account for scroll
   const maxOffsetY =
-    window.pageYOffset +
-    bodyRect.y -
-    height -
-    getYTransforms(placement) * height;
+    bodyRect.height + bodyRect.y - height - getYTransforms(placement) * height;
```
Comment (barklund) [inline assets/src/design-system/components/popup/utils/getOffset.js]: @BrittanyIRL, can you check what exactly was the reason for switching to `window.pageYOffset` and just how it can replace `bodyRect.height` - for a non-scrolled window, the former is 0 but the latter is most certainly not.

This fixes my issue, but might reintroduce issues in the dashboard. Could you please try to check this out locally and see if it recreates issues in the dashboard, please?

And if it does, can you see if you can fix that while not breaking this tooltip in the editor (see #6496 for example)?

Thanks!

File: assets/src/karma-fixture/init.js [hunk 2]
```diff
@@ -369,6 +369,11 @@ beforeEach(async () => {
     margin: 0;
   `;
   document.body.appendChild(rootEl);
+  document.body.cssText = `
+    height: 100vh;
+    width: 100vw;
+    margin: 0;
+  `;
```
Comment (barklund) [inline assets/src/karma-fixture/init.js:379]: As can be seen a few lines above, the actual editor app is embedded in a fixed-position custom element, so the body height is never updated to incorporate the editor. This updates the document height to just be the entire window regardless of the actual editor app size. It's not perfect, but it'll make the modal calculations work correctly at least.

File: assets/src/design-system/components/popup/utils/getOffset.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/design-system/components/popup/utils/getOffset.js]: I was a little worries this might come up! I tested in storybook but that doesn't have the same structure as the editor. Thank you for catching and flagging this.

I think this splits the difference and I can live with it. I feel like this is just some weeds to get stuck in. 
This is what happens on this branch to a dropdown that requires scroll:
updated popup results on dashboard

I'd updated this to take into consideration the scroll height of the view but if it's causing problems for the editor by all means let's keep it how it was. I'd like to also draw attention to the other part of this file that I updated - line 114: 
`  const trueMaxOffsetY = maxOffsetY > 0 ? maxOffsetY : offsetY;` 

I kept seeing the maxOffsetY by less than 0 which was hijacking the popup to way higher on the page than it needs to be. I think this check combined with the older logic that you've restored keeps the scrolled into view dropdowns (below the fold) in the right place.

File: assets/src/karma-fixture/init.js (hunk 2 above)
Comment (BrittanyIRL) [reply assets/src/karma-fixture/init.js:379]: This might be worth summarizing as a comment in the file so that whoever looks at this file in 3 months - be it yourself or someone else, the reason it's here makes sense.

File: assets/src/design-system/components/popup/utils/getOffset.js (hunk 1 above)
Comment (barklund) [reply assets/src/design-system/components/popup/utils/getOffset.js]: (just updated the comment - some typos made the meaning a bit garbled and the ticket link was wrong)

**Review by BrittanyIRL — COMMENTED** [review]
Spent a bit of time this am trying to the positioning that happens with `bodyRect.height` is used instead of `window.pageYOffset`. We don't need the window pageYoffset, that update was right that you made, @barklund. I think we can further simplify it though so that when a user scrolls the popup stays put next to its anchor. I have this PR (#6536) that branches of your work in this branch (#6533) that I feel pretty good about? Will you check it out?

File: assets/src/karma-fixture/init.js (hunk 2 above)
Comment (barklund) [reply assets/src/karma-fixture/init.js:379]: Oh, good idea! Will add that as a comment as well!

**Comment by barklund** [comment]
@miina, could I get you to look things over after this and see if it performs well for you? Not sure if we have other design-system popups in use in the editor actually...?

**Review by BrittanyIRL — APPROVED** [review]
looks good to me! I tested chrome, firefox, and safari at various viewport sizes and it looks like popup is positioning accurately for all tooltips that have been converted in the editor as well as the dropdown in settings and the storybook demos for everything else.

**Review by miina — APPROVED** [review]

**Comment by miina** [comment]
> Not sure if we have other design-system popups in use in the editor actually...?

Not yet, will have some dropdowns soon!
