### PR TITLE
Borders: Remove inner and center border

### LINKED ISSUE #5529: Remove Inside and Center border options
## Bug Description

We don’t need the 3 options for borders (inside, center, outside). Remove and keep to just “outside” as the default/only option. 

## Expected Behaviour

Borders should now only permit outside as an option

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Removes inner and center border, keeping only the outside border as the default.

## User-facing changes
- Inner and center border have been removed, the border is displayed only as outside-border.
- Moved the logic from making page carousel preview responsive to the outside border as well.

## Testing Instructions
- Add an element, e.g. media.
- Add some border, verify there is no option for choosing border type.
- Verify the border is displayed outside of the selection line
- Verify it works as expected with radius, color, etc.

---

Fixes #5529

### CODE REVIEW

File: assets/src/edit-story/components/elementBorder/utils.js [hunk 1]
```diff
@@ -34,7 +32,13 @@ export function shouldDisplayBorder(element) {
...
     return false;
   }
+  return true;
+}
 
+export function shouldDisplayBorder(element) {
+  if (!hasBorder(element)) {
+    return false;
+  }
   return canMaskHaveBorder(element);
```
Comment (barklund) [inline assets/src/edit-story/components/elementBorder/utils.js]: Is this not just `return hasBorder(element) && canMaskHaveBorder(element);`?

**Review by barklund — APPROVED** [review]
LGTM
