### PR TITLE
Do not print title tags for classic themes

### LINKED ISSUE #12487: SEO: <title> tag duplicated when using SEO plugin
## Bug Description

When using the latest Web Stories and the latest released Yoast SEO plugin (v19.8) I noticed that the `<title>` tag behaves incorrectly.
The page has a single `<title>` only when using Twenty Twenty Two theme, while in these others: Twenty Twenty, Twenty Twenty One, Hello Elementor, Astra, GeneratePress, OceanWP - I see **two** titles in the page source.

This is a continuation of #12139, which was fixed in #12162 but (according to test instructions in PR) has been tested only with the 2022 theme.

## Expected Behaviour

There should always be only one `<title>` tag in the page source, regardless of plugins/themes activated.

## Steps to Reproduce

1. Activate Yoast SEO plugin
1. Activate not a Twenty-Twenty Two theme, for example: Astra, OceanWP, GeneratePress, etc.
1. View a single story
1. Verify the <title> tag is added

## Screenshots

Note the two search results when searching for `<title>`:
image

## Additional Context

- Plugin Version: 1.25.1
- Yoast SEO: 19.8 (default settings)
- WordPress Version: 6.0.2
- Operating System: MacOS Monterey
- Browser: Safari/Chrome/Firefox

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Stories can end up having duplicate title tags under some conditions.

## Summary

Disables default title tag output for classic themes

## To-do

- [x] Tests

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Activate Yoast SEO plugin
2. Activate a theme like Astra, OceanWP, GeneratePress, etc.
3. View a single story
4. Verify there is only one `<title>` tag in the source code
5. Activate a theme like Twenty Twenty Two
6. Verify there is  _still_ only one `<title>` tag in the source code

Repeat with a plugin like Rank Math SEO

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12487

### CODE REVIEW

File: includes/Discovery.php [hunk 1]
```diff
@@ -101,23 +101,26 @@ public function register(): void {
 	/**
 	 * Prints document title for stories.
 	 *
-	 * Works both for classic themes and block themes without any conditionals.
+	 * Works both for classic themes and block themes.
```
Comment (spacedmonkey) [inline includes/Discovery.php:104]: Should this comment be updated.

File: includes/Discovery.php [hunk 2]
```diff
@@ -101,23 +101,26 @@ public function register(): void {
...
 	 *
 	 * @since 1.25.0
 	 *
 	 * @link https://github.com/GoogleForCreators/web-stories-wp/issues/12139
+	 * @link https://github.com/GoogleForCreators/web-stories-wp/issues/12487
 	 * @see _wp_render_title_tag()
 	 * @see _block_template_render_title_tag()
 	 */
 	public function print_document_title(): void {
+		$enable_metadata = function_exists( 'wp_is_block_theme' ) && wp_is_block_theme();
```
Comment (spacedmonkey) [inline includes/Discovery.php:114]: How does this work with [Title Tag](https://codex.wordpress.org/Title_Tag).

File: includes/Discovery.php (hunk 1 above)
Comment (swissspidy) [reply includes/Discovery.php:104]: I updated it already, do you have a recommendation to further update/clarify it?

File: includes/Discovery.php (hunk 2 above)
Comment (swissspidy) [reply includes/Discovery.php:114]: Since we're not relying on theme support and don't use built-in functions like `_wp_render_title_tag` or `_block_template_render_title_tag`, this shouldn't really affect us at all.

The problem with block themes is just that plugins like Yoast SEO behave differently for them, which is why we're having these issues.

You can verify this by testing a theme like Twenty Ten (does not add `title-tag` support) and Twenty Fifteen (_does_ add `title-tag` support)

**Review by spacedmonkey — APPROVED** [review]

**Comment by kkalarickal** [comment]
Recreated the problem on `main branch` by applying Astra theme and using Yoast SEO version Version 19.8. I set a specific title tag within the story yoast meta box and searched for that title in the published story AMP. Detected two instances of the <title> .... </title>

(Note: I also changed it to the modern Twenty-Twenty theme and confirmed that the problem was NOT occuring on `master branch`)

Verified the fix by shifting to `12507 branch` and applying Astra theme with Yoast SEO plugin active. With this change, there is only one <title>...</title> entry in the published story AMP

Next deactivated the Yoasst SEO and installed & activated Rank Math SEO plugin. Confirmed that only single <title>...</title> is present in the published story AMP.

Finally, I also changed the theme selection to Steam Punk lite, Twenty-TwentyOne, Twenty-Twenty and confirmed that only one <title>...</title> is present in the published story AMP when Yoast SEO plugin is activated.
