### PR TITLE
Resize elements by edges

### LINKED ISSUE #964: Unable to Scale Elements from all Sizes
## Bug Description

Currently, you have to hover over the handles to scale and you're not able to scale from the top side of the element.

image

## Expected Behaviour

1. You should be able to scale width and height anywhere along the side of the element and not just the handles. 
2. You should be able to scale from all sides. 

## Steps to Reproduce

1. Add an element to the page
2. Try to scale the height or width not using the handles
3. Try to scale from the top side of the element

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
Fixes #964

Resize by dragging edges (exception for text horizontal sides).

handles

### CODE REVIEW

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 1]
```diff
@@ -175,10 +175,13 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
 
   return (
     <Movable
-      className={`default-movable ${hideHandles ? 'hide-handles' : ''}`}
+      className={`default-movable ${hideHandles ? 'hide-handles' : ''} ${
+        selectedElement.type === 'text' ? 'type-text' : ''
+      }`}
```
Comment (merapi) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js:180]: Looks like we don't need to print type for all elements.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 2]
```diff
@@ -175,10 +175,13 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
...
       zIndex={0}
       ref={moveable}
       target={targetEl}
+      edge={true}
```
Comment (miina) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js:184]: Hmm, would have assumed that the `edge` would also respect the directions defined for the handles.
Perhaps it would be good to ask in the Moveable repo if that's purposefully not so.

**Review by miina — APPROVED** [review]
LGTM, would be good to confirm with the Moveable author about `edge` not respecting the render directions though, perhaps handling that part could be removed in the future then.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 2 above)
Comment (merapi) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js:184]: To be really flexible (and work for our cases) it should accept (also? `true=respect handles def|array=custom`) array of directions, for our 1st use case we need `top edge` but not `top handle` and 2nd: `vertical edges only`.
Not sure if they would like to add it because it can be solved with CSS.
