### PR TITLE
Use DOMDocument for rendering full story

### LINKED ISSUE #3434: Incorrect portrait poster size saved
## Bug Description

When a story is saved, the `poster-portrait-src` is incorrectly using the `medium` size instead of the actual portrait poster size we generate.

This will raise warnings in Search Console.

Why does this happen?

In `Stories_Base_Controller` and `Stories_Autosaves_Controller` we set `featured_media_url` like this.

In the story provider, the URL is then used as-is without further ado.

Then, in the `Story_Renderer`, we actually do get the poster, but only for the landscape & square sizes. The portrait poster is not overridden though because it's already available.

To fix this:

1. Override portrait poster in `Story_Renderer`
2. Use correct portrait poster image size for `featured_media_url`

## Expected Behaviour

The portrait poster should use the correct image size.

## Steps to Reproduce

Add featured image, preview story, check the source code.

## Additional Context

User reports: #3401, #3409

Image sizes need updating: #3297 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #3435: Use DOMDocument in Story Renderer
## Feature Description

The current search & replace method in `Story_Renderer` is fragile and can lead to errors when the wrong tags are being replaced.

It would be more robust to parse the original story HTML (which we control / build in JS) using `DOMDocument`, do the replacements in that document, and print it again as HTML.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Uses DOMDocument for rendering stories to make the parsing & rendering more robust.

## Relevant Technical Choices

* Increased code coverage for
* Added `@coversDefaultClass` and `@covers` annotations to make code coverage report more precise.
* Partially resolves #3434 by making sure the correct portrait poster image is added

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

N/A

---

Fixes #3435
See #3434

### CODE REVIEW

File: includes/Story_Renderer.php [hunk 1]
```diff
@@ -213,44 +286,39 @@ protected function replace_body_end_tag( $content ) {
...
-		$markup = $this->replace_body_end_tag( $markup );
-		return $markup;
+		$new_content = $this->string_to_doc( $output );
+
+		if ( ! $new_content->documentElement ) {
+			return;
+		}
+
+		/* @var DOMElement $body The <body> element. */
+		$body = $this->document->getElementsByTagName( 'body' )[0];
```
Comment (spacedmonkey) [inline includes/Story_Renderer.php]: A line that looks like this is repeated 7 times. How about a protected method. 
Something like 
```
protected function get_tag_by_name( $tag_name ){
      return $this->document->getElementsByTagName( $tag_name )[0];
}
```

**Comment by spacedmonkey** [comment]
I personally try and avoid `DOMDocument` has performance issues. But if it is required, then we should go ahead and use it.

**Review by spacedmonkey — APPROVED** [review]
One small nitpick.
