### PR TITLE
Video: Combine "title" and "assistive text" fields

### LINKED ISSUE #4708: Unexpected alt attribute added to amp-video
## Bug Description

I added a video to an story page and it resulted in this markup:

```html
<amp-video
    autoplay="autoplay" poster="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" 
    artwork="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" 
    title="Title text" 
    alt="Alt text" 
    layout="fill" 
    loop="loop" 
    id="el-b8f30411-37f5-4e4e-ace6-8b2666470bd2-media"
>
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200907_180100-trimmed.mp4"></source>
</amp-video>
```

Note the `amp-video` here has both a `title` and an `alt` attribute. 

In the documentation for [`amp-video`](https://amp.dev/documentation/components/amp-video/?format=stories), there is no reference to `alt`. 

The `alt` attribute is likewise not copied onto the `video` child element by the `amp-video` extension:

```html
<video class="i-amphtml-pool-media i-amphtml-pool-video i-amphtml-fill-content i-amphtml-replaced-content" id="i-amphtml-pool-media-5" playsinline="" webkit-playsinline="" preload="auto" poster="https://wordpressdev.lndo.site/content/uploads/2020/09/image-1.jpeg" muted="">
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200908_112624.mp4">
</video>
```

There is no mention of `alt` on the MDN [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) for `video`, nor is there any reference in the [HTML spec](https://html.spec.whatwg.org/multipage/media.html#the-video-element).

So, even though the `alt` attribute is allowed on `amp-video` according to the [validator spec](https://github.com/ampproject/amphtml/blob/6aad5c748b3034916e3523fa5ce2fe5585ba5616/extensions/amp-video/validator-amp-video.protoascii#L37), it appears that this attribute serves no purpose and it may have been a bug to allow it in the first place.

To this end, the "Assistive text" field should probably be omitted from the UI since it doesn't actually aide in accessibility:

image

## Expected Behaviour

The `alt` attribute shouldn't be added to the `amp-video` element since it appears to not serve any purpose.

## Steps to Reproduce

Add a video to a story page and provide assistive text.

## Additional Context

- Plugin Version: 1.1.0-alpha
- Operating System: MacOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #5405: Prepublish checklist error message on Video Alt text missing is incorrect.
## Bug Description

As Videos don't have Alt text (see #5332 ) we should not be presenting prepublish checklist messages about missing Alt text
Screen Shot 2020-11-23 at 2 47 10 PM
source - https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?action=edit&post=13619#page=%2522b1abc9e1-6802-4027-a3eb-7782cf5ceca5%2522

Instead this message should be updated to display the following when no video description has been provided:

Video missing description 
Add a video description. Descriptions help with indexability and accessibility (for videos without captions). Include any burned-in text inside of the video.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Previously there were two separate fields to set the video's `title` and `alt` attribute, and one pre-publish check for each.

Now there is only one input field for the video description, which sets both `title` and `alt` under the hood.

## Relevant Technical Choices

* Remove the text input for `title`.
* Keep `title` in amp-video tag.
* Use the `alt` update logic to update both `title` and `alt`.
* Updated wording in media edit dialog
* Removed pre-publish check for `title`

## To-do

N/A

## User-facing changes

In the design panel, there is only 1 text field for the video description, which sets both `alt` and `title`.

Also, wording in the media edit dialog is updated

## Testing Instructions

1. Edit video via three dots menu in the media library
1. Change video description in the edit dialog
1. Insert video onto page
1. Verify that the "Accessibility" section in the design panel has only one field that shows that new video description.
1. Preview story on frontend
1. Verify that the video's `alt` and `title` attributes are both set and contain the video description.

After creating the video and updating the video's assistive text, the `alt` attribute should show up under the `<amp-video>` tag, with the same value as `title`.

---

Fixes #4708 
Fixes #5405

### CODE REVIEW

File: assets/src/edit-story/components/panels/videoAccessibility.js [hunk 1]
```diff
@@ -97,22 +96,14 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
         <ExpandedTextInput
           placeholder={__('Title', 'web-stories')}
           value={title || ''}
-          onChange={(value) => pushUpdate({ title: value || null })}
+          onChange={(value) =>
+            pushUpdate({ title: value || null, alt: value || null })
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/videoAccessibility.js]: I think a better way would be to just update the title (`pushUpdate({ title: value || null })`) and then in `vide/output.js` simply do `title={title} alt={title}`

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: Ah, good call, that's even better.

File: assets/src/edit-story/elements/video/test/output.js [hunk 2]
```diff
@@ -74,19 +73,8 @@ describe('Video output', () => {
     await expect(<VideoOutput {...props} />).toBeValidAMPStoryElement();
   });
 
-  it('an undefined alt tag in the element should fall back to the resource', async () => {
```
Comment (swissspidy) [inline assets/src/edit-story/elements/video/test/output.js]: Note that now none of the tests check for neither `title` or `alt` anymore.

What I'd expect:

* `it('uses the element's title for the title attribute')`
* `it('should fall back to the resource's title if the element's title is undefined')`
* `it('should not fall back to the resource's title if the element's title is an empty string')`
* `it('should element's title for the alt attribute')`

File: assets/src/edit-story/elements/video/test/output.js [hunk 3]
```diff
@@ -74,19 +73,8 @@ describe('Video output', () => {
...
-      ...baseProps,
-      element: { ...baseProps.element, alt: undefined },
-    };
-    const output = <VideoOutput {...props} />;
-    await expect(output).toBeValidAMPStoryElement();
-    const outputStr = renderToStaticMarkup(output);
-    await expect(outputStr).toStrictEqual(expect.stringMatching('alt text'));
-  });
-
   it('an empty string alt tag in the element should not fall back to the resource', async () => {
```
Comment (swissspidy) [inline assets/src/edit-story/elements/video/test/output.js]: Pointless test now because the `alt` attribute on the element does not exist anymore. Only `title`

**Review by swissspidy — COMMENTED** [review]
Needs tests, but otherwise LGTM

File: assets/src/edit-story/elements/video/test/output.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/edit-story/elements/video/test/output.js]: Got it, added those 4 tests.

File: assets/src/edit-story/elements/video/test/output.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/elements/video/test/output.js]: Remove the pointless test.

**Comment by swissspidy** [comment]
There are some unrelated/unnecessary changes to `package-lock.json` here. Please undo those and CI should run smoothly again.

**Comment by zidianlyu** [comment]
> There are some unrelated/unnecessary changes to `package-lock.json` here. Please undo those and CI should run smoothly again.



> There are some unrelated/unnecessary changes to `package-lock.json` here. Please undo those and CI should run smoothly again.

Done, and sorry for the force push; I have done some research on the follow up commit. Since I accidentally messed up the first commit (by using force push) the following commit might be affected and might need to use force push as well. I will keep in mind and keep making multiple commits in my coming PR.

**Review by swissspidy — APPROVED** [review]

File: assets/src/edit-story/components/panels/videoAccessibility.js [hunk 4]
```diff
@@ -103,16 +101,6 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
...
-          placeholder={__('Assistive text', 'web-stories')}
-          value={alt || ''}
-          onChange={(value) => pushUpdate({ alt: value || null })}
-          clear
-          aria-label={__('Edit: Assistive text', 'web-stories')}
-          maxLength={MIN_MAX.ALT_TEXT.MAX}
-        />
-      </Row>
       <Row>
         <Note>{__('Text for visually impaired users.', 'web-stories')}</Note>
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/videoAccessibility.js]: Let's change this to "Description for indexability and accessibility."

See discussion here: https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?disco=AAAAHST_gmM

**Review by dreamofabear — COMMENTED** [review]
Let's also change the placeholder for the `title` text field to "Describe the video and include any burned-in text". 

/cc @o-fernandez

**Comment by spacedmonkey** [comment]
Related: #5353

File: assets/src/edit-story/components/panels/videoAccessibility.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: Got it! Just check the discussion. That's a good point! Also, I find that the note text for imageAccessibility component is also 'Text for visually impaired users.', do we want to update that part as well?

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: Also, for the placeholder text, I think it might be too long, do we want to shorten it a bit?

Screen Shot 2020-11-20 at 9 15 42 AM

Comment (dreamofabear) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: "Include any burned-in text."

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: Got it!

**Comment by zidianlyu** [comment]
Here is the updated screenshot:

Screen Shot 2020-11-20 at 10 24 34 AM

**Comment by zidianlyu** [comment]
Just a heads up🤣, really not meant to do the force push. Because previously messed up the git, just did it for the fix. I will for sure do the normal commit in any of my other coming PRs.

**Review by swissspidy — APPROVED** [review]

**Review by dreamofabear — APPROVED** [review]

**Review by swissspidy — CHANGES_REQUESTED** [review]
I don't see the change to `assets/src/edit-story/elements/video/output.js` anymore, where `props.alt` is set to the element title.

**Comment by swissspidy** [comment]
@zidianlyu Two suggestions after QA feedback in https://github.com/google/web-stories-wp/issues/4708#issuecomment-736657668

1. use `alt` for the combined field, not `title`
1. Update wording in media edit dialog (`assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js`) to say "Video description" (or "Image description", respectively) instead of "Alt text"

Note: to see `mediaEditDialog.js` in action, click on "edit" here:

Screenshot 2020-12-01 at 19 34 00

**Comment by spacedmonkey** [comment]
There is a merge conflict.

File: assets/src/edit-story/components/panels/videoAccessibility.js [hunk 5]
```diff
@@ -71,7 +70,6 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
       resource: {
         ...newResource,
         title: newResource.title?.slice(0, MIN_MAX.TITLE.MAX),
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/videoAccessibility.js]:
```suggestion
        alt: newResource.alt?.slice(0, MIN_MAX.TITLE.MAX),
```

File: assets/src/edit-story/components/panels/videoAccessibility.js [hunk 6]
```diff
@@ -95,7 +93,7 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
       </Row>
       <Row>
         <ExpandedTextInput
-          placeholder={__('Title', 'web-stories')}
+          placeholder={__('Video description', 'web-stories')}
           value={title || ''}
           onChange={(value) => pushUpdate({ title: value || null })}
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/videoAccessibility.js]:
```suggestion
          value={alt || ''}
          onChange={(value) => pushUpdate({ alt: value || null })}
```

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@zidianlyu FYI, took the liberty to expand on the PR to cater for the pre-publish checklist and the media edit dialog. Updated the description accordingly.
