### PR TITLE
Design System: Popup clean up

### LINKED ISSUE #11201: Layers Panel Using Wrong Tooltip
## Bug Description

Layers panel is getting negative values for some of the positioning because it's using the Tooltip outside of story-editor. 

Use Tooltip from Story-Editor, and update the placement to bottom-end since we are at the left edge of the screen anyways.

### LINKED ISSUE #11303: Insert Media Popup not getting correct `isRTL` placement
## Bug Description

On the Insert Media Side Panel,  you click the + icon on an image and it opens a `Popup` to "insert the image" or add it as the background. When in RTL mode, the Popup is cutoff. Probably cause we are not sending `isRTL` to the Popup and thus not changing the placement. 

## Expected Behaviour

Popups shouldn't get cutoff, or layered underneath the admin sidebar. 
## Steps to Reproduce
Open Editor
Switch to RTL
Open Media panel
Click on the + icon that is shown over any image

## Screenshots
Screen Shot 2022-04-15 at 3 37 45 PM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context
This is some follow up work related to the Layers Panel `Tooltip` getting negative valued x-offsets. Since the Layers Panel has some very nested absolute positioning the `getOffset` util thinks the `Tooltip` should be based off somewhere that the panel isn't. `Tooltip` offset updates, edge cases, etc where fixed in #11280. However, we still needed to address the `getOffset` to account for edge cases in `Popups` that were a work-around for those Tooltips.    

We had a special prop flag `resetXOffset`, to know when to look for the edge cases where this was an issue. Now that `Tooltip` is separate we can remove the `resetXOffset` flag and better handle any off screen issues directly in the `Popup` component. 

## Summary

`Popup` now updates the x-offset in cases where it would either collide with admin side nav, or otherwise get cutoff screen in x. 

## Relevant Technical Choices
Removed `resetXOffset` from the shared util `getOffset`. Both `Tooltip` and `Popup` use this function to grab offset values for portals. I wanted to keep this portion straightforward.  Since `Tooltip` and `Popup` have varied `placement` considerations I wanted to keep any special offset updates or edge case logic specific to each component. The `getOffset` will still give us `maxOffsetX` to prevent us from cutoff on the right edge, however,  `Popup` now takes `leftOffset` into consideration for RTL mode. `leftOffset` is also being utilized for LTR sidenav bar consideration. 

~~The bulk of these files was just adding `isRTL` and `leftOffset` to all uses of `Popup`.~~

New `usePopup` hook and `PopupProvider`. This provider now gives us access to `leftOffset`, `topOffset` and `isRTL` so we no longer need to pass these as props to `Tooltip` or `Popup` 🎉
 

## User-facing changes

Now that `Insertion Menu` is receiving `isRTL` the popup placement is correct in the RTL view as seen below. 
|Before|After|
|--|--|
|Screen Shot 2022-04-21 at 8 31 11 AM|Screen Shot 2022-04-21 at 8 29 54 AM|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. In RTL, open the Insert panel and hover over an image. 
2. Click the `+` icon  to open the `Insertion Menu`
3. The Popup should no longer be cutoff by the wp-admin bar
4. While we are here, let/s check for Popup regressions. 
5. Select / add text on the canvas and open the `Style` Panel
6. Open the color picker, (any version of it),  save styles, Font dropdown
7. We can also check the dropdowns in Document tab and the Publish Time Popup. 
8. Double check Dropdowns in the Dashboard and Dashboard settings as well.  

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11201 
Fixes #11303

### CODE REVIEW

File: packages/design-system/src/components/popup/index.js [hunk 1]
```diff
@@ -68,21 +69,61 @@ function Popup({
...
+            case PLACEMENT.RIGHT:
+              // These should only matter in the case of isRTL so we'll need the entire width of the popup as the offset
+              return { ...offset, x: width };
+            default:
+              return { ...offset, x: width / 2 + (isRTL ? 0 : leftOffset) };
+          }
+        }
+
+        if (isRTL && right > offset.bodyRight - leftOffset) {
+          // maxOffset should keep us inbounds, expect in the case of RTL due to the admin-sidebar nav we could use another
```
Comment (BrookeGraham) [inline packages/design-system/src/components/popup/index.js]: spelling `except`

File: packages/design-system/src/components/popup/utils/getOffset.js [hunk 2]
```diff
@@ -134,12 +129,7 @@ export function getOffset({
   const { x: spacingH = 0, y: spacingV = 0 } = spacing || {};
 
   // Horizontal
-  const offsetX = () => {
-    if (resetXOffset && popupRect?.left <= 0) {
-      return isRTL ? width : 0;
-    }
```
Comment (BrookeGraham) [inline packages/design-system/src/components/popup/utils/getOffset.js:140]: Previously, this was to handle the color picker in the floating menu when in RTL. We couldn't directly update the offsets since `Tooltip` can sometimes come back with `popupRect?.left` being in the negative. This happen in the layers panel due to the nested absolute positioning. Now, Tooltip handles its own updated offset logic to deal account for this possibility.

**Review by BrittanyIRL — DISMISSED** [review]
Makes sense to me ⭐

**Review by BrittanyIRL — DISMISSED** [review]

**Comment by felipebochehin87** [comment]
Open question on #11201.

File: packages/design-system/src/components/popup/utils/getOffset.js [hunk 3]
```diff
@@ -152,7 +142,7 @@ export function getOffset({
 
   // Clamp values
   return {
-    x: Math.max(0, Math.min(offsetX(), maxOffsetX)),
+    x: Math.max(0, Math.min(offsetX, maxOffsetX)),
```
Comment (maxyinger) [inline packages/design-system/src/components/popup/utils/getOffset.js:145]: Heads up, we got this util to take care of this math. The util was probably created after the initial popup was made:
https://github.com/GoogleForCreators/web-stories-wp/blob/9404d909d2cda1afc17e00570944f72e9ff630a9/packages/units/src/range.js#L60-L62

File: packages/wp-story-editor/src/components/documentPane/publish/publishTime.js [hunk 4]
```diff
@@ -133,6 +134,7 @@ function PublishTime() {
       </Row>
       <Popup
         topOffset={TOOLBAR_HEIGHT}
+        leftOffset={leftOffset}
```
Comment (maxyinger) [inline packages/wp-story-editor/src/components/documentPane/publish/publishTime.js]: So we're passing all of this through props cus we don't have access to the config provider in the Design System right?

I'm wondering if it maybe helps just to have a `PopupProvider` exported from the design system that takes care of these props. something we can use in the app like:
```js
import { PopupProvider } from '@googleforcreators/design-system';

function StoryEditor() {
  const { styleConstants: { leftOffset } = {} } = useConfig();
  // ...
  return (
    <PopupProvider value={{
        // pass whatever else we want here that we want from
        // providers in `story-editor` that we don't want to have 
        // to pass explicitly through props in every `Popup` Instance
        leftOffset,
        // ...
      }}>
      // ...
    </PopupProvider>
  );
}
```

then in the popup implementation we can just do something like this and not have to pass a prop to every instance:
```
function Popup(props) {
  const leftOffset = usePopupContext(({ leftOffset }) => leftOffset);
  // ...
}
```

Comment (maxyinger) [reply packages/wp-story-editor/src/components/documentPane/publish/publishTime.js]: could also use this approach to pass in things like `isRTL` & `topOffset`

**Review by maxyinger — DISMISSED** [review]

File: packages/wp-story-editor/src/components/documentPane/publish/publishTime.js (hunk 4 above)
Comment (BrookeGraham) [reply packages/wp-story-editor/src/components/documentPane/publish/publishTime.js]: Smart

File: packages/design-system/src/contexts/popup/popupProvider.js [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+
+PopupProvider.propTypes = {
+  children: PropTypes.node,
+  value: PropTypes.shape({
+    isRTL: PropTypes.bool,
+    leftOffset: PropTypes.number,
+  }),
+};
+
+export default PopupProvider;
```
Comment (maxyinger) [inline packages/design-system/src/contexts/popup/popupProvider.js]:
```suggestion
import Context from './context';

export default Context.Provider;
```

File: packages/story-editor/src/components/form/color/colorInput.js [hunk 6]
```diff
@@ -205,13 +206,14 @@ const ColorInput = forwardRef(function ColorInput(
...
   );
-  const { isRTL, styleConstants: { topOffset } = {} } = useConfig();
   const [dynamicPlacement, setDynamicPlacement] = useState(pickerPlacement);
 
   const {
     refs: { sidebar },
   } = useSidebar();
 
+  const { topOffset } = usePopup();
+
```
Comment (maxyinger) [inline packages/story-editor/src/components/form/color/colorInput.js]: I would just pull `topOffset` off of `useConfig` since this can access it directly. Also prevents some bleeding of functionality into other things (makes `PopupProvider` solely part of the `Popup` implementation and not needed for anything else)

**Review by maxyinger — DISMISSED** [review]
looks good!

File: packages/story-editor/src/components/form/color/colorInput.js (hunk 6 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/form/color/colorInput.js]: That were I was leaning too. Will do!

File: packages/design-system/src/components/popup/utils/getOffset.js (hunk 3 above)
Comment (BrookeGraham) [reply packages/design-system/src/components/popup/utils/getOffset.js:145]: I decided against grabbing this from the units package since we don't already have that package as a dep for the design system package. Seemed like a lot to pull in for this one simple func. 🤷

**Review by maxyinger — APPROVED** [review]

**Review by mwritter — APPROVED** [review]
Looks good to me 👍
