### PR TITLE
Hotfix: Validate hex color string in `SkeletonPage`

### LINKED ISSUE #9888: Editor crashing due to `baseColor` usage in `SkeletonPage`
## Bug Description

We received [an error report via the forums](https://wordpress.org/support/topic/the-editor-has-crashed-please-try-reloading-the-page-and-report-the-error/#post-15132130) with the following stack trace:

```
Error: An error occurred. See https://github.com/styled-components/polished/blob/main/src/internalHelpers/errors.md#7 for more information.
at SkeletonPage (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:175:455)
at div
at j (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:1:33997)
at https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:234:3019258
at Reorderable (https://MY-WEBSITE.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=1d1f606301213e85c081ee9e74f22ba4:133:3602)
...
```

https://github.com/styled-components/polished/blob/main/src/internalHelpers/errors.md#7 says:

> Passed invalid arguments to rgba, please pass multiple numbers e.g. rgb(255, 205, 100, 0.75) or an object e.g. rgb({ red: 255, green: 205, blue: 100, alpha: 0.75 }).

`rgba()` is called in `generatePatternStyles()` here:

https://github.com/google/web-stories-wp/blob/b76635df44d0532f20de573675abf6b4549e96a2/packages/story-editor/src/components/footer/carousel/skeletonPage.js#L61-L77

So I suspect it's either a broken `baseColor` on the background element's resource causing this, or an incorrect background color on the background element itself.

## Expected Behaviour

No crash

## Steps to Reproduce

Unclear

## Additional Context

- Plugin Version: 1.15.0
- WordPress Version: 5.8
- Operating System: ?
- Browser: ?

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

There were lots of reports about editor crashes, all related to `baseColor` somehow still not being a string.

## Summary

This is a hotfix for preventing editor crashes due to unexpected format of `baseColor` in carousel

## To-do

We'll have to follow up with additional changes to make this more robust and fix the root cause

## User-facing changes

N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Modify story data to have a resource with baseColor being an array (e.g. using the hidden dev tools)
2. Save story and refresh page
3. Editor should not crash

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9888

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]

File: packages/story-editor/src/components/footer/carousel/skeletonPage.js [hunk 1]
```diff
@@ -58,8 +59,10 @@ function SkeletonPage({ pageId, index }) {
 
   const bgElement = page.elements[0];
   const { isMedia } = getDefinitionForType(bgElement.type);
+  // Using isHexColorString for extra hardening.
+  // See https://github.com/google/web-stories-wp/issues/9888.
   const bgColor =
-    isMedia && bgElement.resource?.baseColor
+    isMedia && isHexColorString(bgElement.resource?.baseColor)
```
Comment (miina) [inline packages/story-editor/src/components/footer/carousel/skeletonPage.js:65]: Hm, I suppose migration wasn't fully working that for some elements it's still not hex?

**Review by miina — APPROVED** [review]

File: packages/story-editor/src/components/footer/carousel/skeletonPage.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/footer/carousel/skeletonPage.js:65]: Still trying to figure that one out

See https://github.com/google/web-stories-wp/issues/9888#issuecomment-986664131 and #9897
