### PR TITLE
Media: Improve list of supported file types for image pickers

### LINKED ISSUE #5124: Filter image picker to only supported image types
## Feature Description

There are a number of image picker that use the WordPress media picker. These include 
- Cover image. 
- Publisher image.
- Video poster image. 

These picker should be limited only image mime types that the story editor supports. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Related: #5118 #4931

### LINKED ISSUE #6011: SVG Uploads: Disallow as publisher logo or poster image
## Bug Description

[Guidelines](https://amp.dev/documentation/components/amp-story/#publisher-logo-src-guidelines) for the poster image and publisher logo are clear:

Provide a raster file, such as .jpg, .png, or .gif. Avoid vector files, such as .svg or .eps.
Avoid animated images, such as animated gifs.

## Expected Behaviour

SVGs should not be allowed as poster image or publisher logo

## Steps to Reproduce

1. Enable SVG experiment
2. Go to Settings
3. Upload a new SVG as publisher logo
4. See that it works

Same happens when you go to the editor and try to add an SVG  as the publisher logo or poster image

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Context

Add supported mime types to file upload and media pickers to only support gif, png and jpg files. This means that an SVG can not be selected. 

## Relevant Technical Choices

Add a new php method with a filter, so developers, can add mime types if they need to, but I am not sure if this should be in place. 

## To-do

- [ ] PHP unit tests

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Dashboard settings.
2. Upload publisher logo. 
3. The file dialog should not allow you to select another other than a gif, jpg or png. 

In editor
1. Document tab
2. Select a Publisher logo or cover image. 
3. The file dialog should not allow you to select another other than a gif, jpg or png.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5124
Fixes #6011

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy Love your thoughts on what we should do to test this change. As other the fileupload and media dialog support passing mime types, it just able getting the array loaded in the correct place. Willing to add some tests, if I can think of any that really add value.

File: includes/Traits/Types.php [hunk 1]
```diff
@@ -108,4 +108,34 @@ public function get_allowed_mime_types() {
...
+	/**
+	 * Returns a list of image mime types.
+	 *
+	 * @since 1.4.0
+	 *
+	 * @return array List of allowed mime types.
+	 */
+	public function get_allowed_image_mime_types() {
+		$mime_type         = $this->get_allowed_mime_types();
+		$allowed_mime_type = $mime_type['image'];
```
Comment (swissspidy) [inline includes/Traits/Types.php:121]: If the SVG flag is enabled, this will add SVGs to this list, which is what we don't want.

Comment (spacedmonkey) [reply includes/Traits/Types.php:121]: What is what the `array_intersect` is for 😄

Comment (spacedmonkey) [reply includes/Traits/Types.php:121]: https://github.com/google/web-stories-wp/pull/6074/files/570cef5bf94c51b37b298e8ffdddcdd2c1decb72#diff-f44eb7e6dbedc04516997b6e79d04e2b3e72388ca59d3a76c39ee19d90f6a70eR139

**Comment by swissspidy** [comment]
> @swissspidy Love your thoughts on what we should do to test this change. As other the fileupload and media dialog support passing mime types, it just able getting the array loaded in the correct place. Willing to add some tests, if I can think of any that really add value.

Maybe an e2e test verifying that users **cannot** add SVGs as publisher logos or poster images? (even if the SVG flag is enabled)

File: includes/Traits/Types.php (hunk 1 above)
Comment (swissspidy) [reply includes/Traits/Types.php:121]: Ah, seeing it now!

So if someone removes support for PNG via the `web_stories_allowed_mime_types` filter, it would also be removed here?

And if someone wants to add support for more images they'd need to use both filters?

Comment (spacedmonkey) [reply includes/Traits/Types.php:121]: > And if someone wants to add support for more images they'd need to use both filters?

Yes, this is by design. If you add support for svg yourself for example, we don't want that filter down to allow images. You need to manually add it. It is basically a whitelist of allowed image types. We easily be flipped to be a black list. What do you think is the best developer expereience here?

**Comment by spacedmonkey** [comment]
> Maybe an e2e test verifying that users cannot add SVGs as publisher logos or poster images? 

E2E test has been added.

File: includes/Traits/Types.php (hunk 1 above)
Comment (swissspidy) [reply includes/Traits/Types.php:121]: Not sure what the best experience would be, but the current solution seems reasonable for sure.

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Verified on https://stories-qa-wordpress-amp.pantheonsite.io/ as follows:

1. Enabled Safe SVG plugin to be able to upload SVG to wordpress media library
2. Uploaded a sample svg file to Media Library
3. Open a story in stories-editor and go to Documents tab
4. Pick selector for Publisher Logo and go to Media Library

SUCCESS: The sample SVG image that was uploaded is NOT VISIBLE and cannot be selected.

5. Go to Upload Files tab in the "Select a Publisher Logo" modal
6. Select a sample svg from disk and upload
7. Click the "Select as publisher logo" button

FAILURE: The sample SVG image is uploaded and selected as the publisher logo
* Same is the case with Cover Image & Stories > Editor Settings > Publisher Logo



Note: If user tries to insert a non supported image format into the stories via Media Gallery, the stories editor rejects the action. However, this is NOT the case with Publisher/Cover Image for a story.



@swissspidy : Since the user can still pick SVG but via manual Upload, I feel this ticket fails QA.

**Comment by spacedmonkey** [comment]
@kkalarickal I have pushed a fix https://github.com/google/web-stories-wp/pull/6074/commits/038e0bb3abdfeb6072260738a69741b58cff55fa Can you retest. 

@swissspidy Can you review my fix.

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
@spacedmonkey : Retested the Image filtering and image upload actions for non-supported formats (SVG, EPS, PDF) as well as  supported gif, png and jpg files. 

Following was observed:

Adding Publisher Logo or Cover Image via Stories > My Story Editor > Document panel

1. Adding supported image works for existing and newly uploaded image. (PASS)
2. Adding unsupported image: you cannot see any unsupported image files in the Media file picker (PASS)
3. Uploading unsupported image via Upload files pane: File is uploaded, and user can click the button to "Select as cover image". But the unsupported image is *silently* rejected. (PASS)

Adding default publisher logo via Stories > Settings panel

1. Adding supported image - uploading and setting as default works (PASS)
2. Uploading unsupported image is possible but image is ignored if another image is the defaults (PASS)
3. Uploading unsupported image when there is no other image OR by manually setting it as default (FAIL)

For example:
- upload an svg file, and there is no other default publisher logo OR if you manually set it as default
- then you create a new web stories entry OR go to an existing story without a publisher logo selected
- the svg will still show up as the default Publisher logo -- FAIL

Screenshot of SVG can be made default publisher logo


Screenshot of new web story with the default SVG publisher logo


@spacedmonkey - not sure if you want to handle the edge case of Publisher logo default being able to set as SVG in this ticket or another ticket.

**Comment by spacedmonkey** [comment]
> Uploading unsupported image when there is no other image OR by manually setting it as default (FAIL)

I could not replicate this locally and I am still a little unclear. Can you provide me a video / steps to reproduce locally?

**Comment by kkalarickal** [comment]
@spacedmonkey - here is a screencapture that I made showing how there exists a path for user to upload a default publisher logo with an unsupported image, and then new stories will pick up this logo silently. I tried this test case since the ticket QA instructions specifically said to test uploading via the Dashboard settings.

https://share.getcloudapp.com/llu9yvyp

**Comment by spacedmonkey** [comment]
@kkalarickal 

I can't replicate the issue my mac or linux box, using chrome or firefox. Can you confirm what OS you are running in that screenshot. 

It is worth noting that, we do not currently support chrome OS ( chromebooks ) with this editor. 

Here is a screen cast of what I see. ( not the greyed out of unsupported file types ). 

https://user-images.githubusercontent.com/237508/107064627-a5104780-67d3-11eb-80a3-8cbcf53d2393.mov

**Comment by swissspidy** [comment]
@spacedmonkey I see the same issue

1. Remove all publisher logos
2. Drag SVG logo into publisher logo area
3. SVG logo is uploaded

**Comment by spacedmonkey** [comment]
>I see the same issue

> Remove all publisher logos
Drag SVG logo into publisher logo area
SVG logo is uploaded

Sorry, I was just testing with upload dialog and not drag and drop. I have added a fix now in https://github.com/google/web-stories-wp/pull/6074/commits/3796a11c67ca36aa9eece0c690a0b0f70733b238

We may want to work on the wording here.

File: assets/src/dashboard/app/views/editorSettings/index.js [hunk 2]
```diff
@@ -240,6 +248,20 @@ function EditorSettings() {
         return setMediaError(errorText);
       }
 
+      if (!allFileTypeSupported) {
+        const errorText =
+          files.length === 1
+            ? __(
+                'Sorry, this file type is not supported. Please upload another file. ',
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/editorSettings/index.js]:
```suggestion
                'Sorry, this file type is not supported. Please upload another file.',
```

File: assets/src/dashboard/app/views/editorSettings/index.js [hunk 3]
```diff
@@ -240,6 +248,20 @@ function EditorSettings() {
...
+                'web-stories'
+              )
+            : __(
+                'Sorry, one or more of these files are not a supported file type. Make sure your logos are the correct file type.',
```
Comment (swissspidy) [inline assets/src/dashboard/app/views/editorSettings/index.js]:
```suggestion
                'Sorry, one or more of these files are of an unsupported file type. Make sure your logos are of the correct file type.',
```

Comment (kkalarickal) [reply assets/src/dashboard/app/views/editorSettings/index.js]: @swissspidy @spacedmonkey : As a novice end user, I might benefit from a recommendation of which file types are supported in this error message. Either an explicit list, or if the image types might change in future, a link to the current list supported image types.

Suggestion: 
'Sorry, one or more of these files are of an unsupported file type. Only jpg, png, and static gifs are supported for publisher logos'

Comment (spacedmonkey) [reply assets/src/dashboard/app/views/editorSettings/index.js]: Wording as been updated with 
`Sorry, this file type is not supported. Only jpg, png, and static gifs are supported for publisher logos.`
`Sorry, one or more of these files are of an unsupported file type. Only jpg, png, and static gifs are supported for publisher logos.`

**Review by swissspidy — APPROVED** [review]
