### PR TITLE
Fix history bug

### LINKED ISSUE #286: Broken history management
Undo/Redo in the editor is broken at the moment and doesn't work at all.

This might stem from the refactoring to use reducers under the hood and needs some investigation.

Related: #67

### PR DESCRIPTION
**Pull request by barklund**
This fixes an issue with the history management.

- [x] Fix bug that prevents history from working at all

Fixes #286.

### CODE REVIEW

File: assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ function restore(state, { pages, current, selection, story, capabilities }) {
   const newCurrent = pages.some(({ id }) => id === current)
     ? current
     : pages[0].id;
-  const newSelection = Array.isArray(selection) ? [...new Set(selection)] : [];
+  const newSelection = Array.isArray(selection) ? selection : [];
```
Comment (barklund) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js:41]: `restore` is basically only an internal API used when history is replayed or a story is reloaded from a saved state. There's no need to ensure the array is unique at these points, because the array must have been created by other methods in the API previously, which all makes sure the array was unique at that time and thus still is.

I think it's fair to remove this requirement from this function (and the corresponding test).

Another option here would be to check if the array was unique, and if not, only then re-create the array with a unique'd list, but I don't think it'll ever happen.

**Comment by barklund** [comment]
I'll move the "proper history management" part to a new ticket, as it might be a lot more complicated than expected.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/restore.js:41]: The bug here was, that the history manager expected the exact same variables (by reference) to be re-entered as a history state when replaying an old state. The old line changed the selection array by reference (though not by content). Even for empty arrays!

**Review by dvoytenko — APPROVED** [review]
LGTM. As a "grumble" I still feel like there would be some benefits from history with other reducers. The `useEffect` triggering scares me a bit. But perhaps for a later discussion.

**Comment by barklund** [comment]
NB: Add regression test.

Full test suite for history will follow in follow up PR with new functionality.

**Comment by swissspidy** [comment]
@barklund Do you need a new issue for those tests or is it on your radar?

**Comment by barklund** [comment]
> @barklund Do you need a new issue for those tests or is it on your radar?

@swissspidy it's on my radar for follow-up issue on history management fixes. It's not as complex as "feared" as we won't do any compacting/grouping of related updates, so it's fairly straight-forward. I'll add an issue for it.
