### PR TITLE
Editor: Hide upload buttons for users without upload capabilities

### LINKED ISSUE #7755: Lack of upload permission checks for contributors
## Bug Description

When clicking on select poster image no error message is shown and user is able select poster image to dismiss prepublish check list item. See video 

## Expected Behaviour

UX to confirm.

## Steps to Reproduce

See video. 

## Screenshots

https://user-images.githubusercontent.com/237508/119808421-028fe780-bedc-11eb-8eb5-176bddc3beb3.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Context

When clicking on select poster image no error message is shown and user is able select poster image to dismiss prepublish check list item. See video on #7755

## Summary

This PR hides all upload buttons and media editing capabilities if the user doesn't have upload capabilities (typically the "Contributor" user role in WordPress).

## User-facing changes

| Before                | After                    |
| --------------- | --------------- |
| Screenshot 2021-08-23 at 15 16 38 | Screenshot 2021-08-23 at 15 08 16 | 
| Screenshot 2021-08-23 at 15 16 54 | Screenshot 2021-08-23 at 15 09 26 | 
| Screenshot 2021-08-23 at 15 17 00 | Screenshot 2021-08-23 at 15 09 33 |
|   Screenshot 2021-08-23 at 15 17 13 | Screenshot 2021-08-23 at 15 09 47 |
| Screenshot 2021-08-23 at 15 20 44 | Screenshot 2021-08-23 at 15 10 08 |

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Login as contributor.
2. Open editor. 
3. Ensure that upload button does not appear in media library. 
4. Switch to documents tab. Edit icon for publisher logo and poster logo. 
5. Insert video into canva. 
6. Ensure that poster does not have edit icon. 
7. Ensure that there is no caption upload button appears. 
8. Add link to video. 
9. Ensure that there is no edit icon on link icon. 

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7755

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/captions/captions.js [hunk 1]
```diff
@@ -153,6 +157,12 @@ function CaptionsPanel({ selectedElements, pushUpdate }) {
   const buttonRef = useRef();
   const highlight = useFocusHighlight(states.CAPTIONS, buttonRef);
 
+  if (!hasUploadMediaAction) {
+    return null;
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/captions/captions.js:164]: Shouldn't the user still be able to clear out the inputs? 🤔

File: packages/story-editor/src/components/panels/design/link/link.js [hunk 2]
```diff
@@ -250,19 +254,21 @@ function LinkPanel({ selectedElements, pushUpdateForObject }) {
...
-              isLoading={fetchingMetadata}
-              disabled={fetchingMetadata}
-            />
-            <IconInfo>
-              <IconText size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL}>
-                {__('Optional brand icon', 'web-stories')}
-              </IconText>
-            </IconInfo>
-          </Row>
+          {hasUploadMediaAction && (
```
Comment (miina) [inline packages/story-editor/src/components/panels/design/link/link.js]: Hm, the icon is by default loaded from the inserted link (if available), that doesn't require upload permissions.

However, if the fetched icon link is not working/displays broken/is not suitable, the user should be able to remove it.

If the icon is loaded from the site meta (the value received is not empty), perhaps then the media input should be displayed with the option to remove it only?

File: packages/story-editor/src/components/panels/design/captions/captions.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/panels/design/captions/captions.js:164]: Good question.

I think we can still show the current items & allow removing. Only upload needs to be hidden.

File: packages/story-editor/src/components/panels/document/publish/publish.js [hunk 3]
```diff
@@ -185,62 +189,67 @@ function PublishPanel() {
...
-                variant={MEDIA_VARIANTS.CIRCLE}
-              />
-            </MediaWrapper>
-            <LabelWrapper>
-              <Label>{__('Publisher Logo', 'web-stories')}</Label>
-              <Required />
-            </LabelWrapper>
-          </MediaInputWrapper>
-        </HighlightRow>
+        {hasUploadMediaAction && (
```
Comment (swissspidy) [inline packages/story-editor/src/components/panels/document/publish/publish.js]: I think we should make it so that we still display the poster, but we just not allow uploading one.

File: packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js [hunk 4]
```diff
@@ -123,46 +151,27 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
...
-                true
-              )
-            }
-            aria-label={__('Assistive text', 'web-stories')}
-            maxLength={MIN_MAX.ALT_TEXT.MAX}
-            rows={2}
-            isIndeterminate={alt === MULTIPLE_VALUE}
-          />
-        </InputsWrapper>
+        {hasUploadMediaAction ? (
```
Comment (swissspidy) [inline packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js]: Can we display the current poster but just not allow uploading a new one?

File: packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js [hunk 5]
```diff
@@ -115,6 +119,30 @@ function VideoAccessibilityPanel({ selectedElements, pushUpdate }) {
     };
   }
 
+  const altTextarea = (
```
Comment (swissspidy) [inline packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js]: I'd make this a proper component.

```js
const TextAreaContent = () => (...)
```

File: packages/story-editor/src/components/panels/design/captions/captions.js (hunk 1 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/panels/design/captions/captions.js:164]: Fixed.

File: packages/story-editor/src/components/panels/design/link/link.js (hunk 2 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/panels/design/link/link.js]: Fixed.

**Comment by spacedmonkey** [comment]
@swissspidy / @miina Can you test again and make sure you happy with functionality. I will fix test / lints after that.

File: packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js (hunk 4 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js]: Fixed

**Comment by swissspidy** [comment]
> @swissspidy / @miina Can you test again and make sure you happy with functionality. I will fix test / lints after that.

Current status looks good 👍

**Review by swissspidy — APPROVED** [review]
I'd really love to see some tests (probably e2e, but perhaps also integration) with this, but otherwise looks good.

**Comment by spacedmonkey** [comment]
Added tests.

**Comment by swissspidy** [comment]
This existing Karma test is failing and needs to be updated:

https://github.com/google/web-stories-wp/blob/40da0158c86c4a659ac2c35a5c44318e0701c4fe/packages/story-editor/src/components/checklist/karma/checklist.karma.js#L602-L631

The problem is that `addPosterImageWithIssues()` is simply not possible without having upload permission.

We would need to add a poster image by passing some custom mocks as per the docs:

https://github.com/google/web-stories-wp/blob/40da0158c86c4a659ac2c35a5c44318e0701c4fe/packages/story-editor/src/karma/fixture/fixture.js#L134-L136

https://github.com/google/web-stories-wp/blob/40da0158c86c4a659ac2c35a5c44318e0701c4fe/packages/story-editor/src/components/checklist/karma/checklist.karma.js#L579-L585

So maybe something like this (untested):

```js
fixture = new Fixture({ mocks: {
getStoryById: Promise.resolve({
    title: { raw: '' },
    status: 'draft',
    author: 1,
    slug: '',
    date: '2020-05-06T22:32:37',
    date_gmt: '2020-05-06T22:32:37',
    modified: '2020-05-06T22:32:37',
    excerpt: { raw: '' },
    link: 'http://stories.local/?post_type=web-story&p=1',
    preview_link: 'http://stories.local/?post_type=web-story&p=1',
    story_data: {
      version: DATA_VERSION,
      pages: this._pages,
    },
    featured_media: 0, // TODO TODO TODO
    featured_media_url: '', // TODO TODO TODO
    publisher_logo_url:
      'http://stories.local/wp-content/plugins/web-stories/assets/images/logo.png',
    permalink_template: 'http://stories3.local/stories/%pagename%/',
    style_presets: { textStyles: [], colors: [] },
    password: '',
    _embedded: { author: [{ id: 1, name: 'John Doe' }] },
    _links: {
      'wp:action-assign-author': {
        href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
      },
      'wp:action-delete': {
        href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
      },
      'wp:action-publish': {
        href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
      },
      'wp:action-unfiltered-html': {
        href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
      },
    },
  }),
}}
```

**Comment by miina** [comment]
> @swissspidy / @miina Can you test again and make sure you happy with functionality. I will fix test / lints after that.

Sorry for the late feedback here, feel free to ignore if @swissspidy already has approved the approach.

Currently, if the user doesn't have permissions, the field is visible but the button doesn't do anything -- is that intended?
clicking
Q: If there is no previously existing value, should we then hide the field fully and only display it _if_ there is a value before, for removal?

If there is a value, then "Edit" option is available but doesn't do anything.
menu

Q: Couldn't we change the menu options so that the user can only see "Remove"

Thoughts?

**Comment by miina** [comment]
We could also perhaps edit the media input directly so that if there are no permissions, it will display a warning message instead of opening the Media Library? Then it would happen anywhere where the media input is used and wouldn't need to be handled per use.

This could of course be considered in a follow-up issue.

Thoughts?

**Comment by swissspidy** [comment]
Thanks for chiming in!

> Currently, if the user doesn't have permissions, the field is visible but the button doesn't do anything -- is that intended?

We should definitely hide that button

> Q: If there is no previously existing value, should we then hide the field fully and only display it if there is a value before, for removal?

Makes sense 👍 

> Couldn't we change the menu options so that the user can only see "Remove"

Makes sense 👍 

> We could also perhaps edit the media input directly so that if there are no permissions, it will display a warning message instead of opening the Media Library? Then it would happen anywhere where the media input is used and wouldn't need to be handled per use.

We had a similar warning for the Upload button previously, which was quite confusing.
We should not offer options if they don't have permissions, not display warnings.

**Comment by swissspidy** [comment]
^ Those are also good cases to clearly document in QA instructions FWIW

**Comment by miina** [comment]
> We had a similar warning for the Upload button previously, which was quite confusing.
We should not offer options if they don't have permissions, not display warnings.

Ok, makes sense. It might still be possible to hide the `Edit` value and not display the field at all (if no value) directly from the [Media Input component](https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/components/form/media.js) instead -- then this could be done from one place only. In case the behaviour is consistent throughout the editor anyway.

**Comment by miina** [comment]
@spacedmonkey I was looking at this again and now the button is hidden (not sure how to repro the previous case where the button was visible but not doing anything 🤔 ):
Screenshot 2021-08-20 at 14 24 40

(This should still have the `Remove` option available in the menu though).

**Comment by spacedmonkey** [comment]
> Q: Couldn't we change the menu options so that the user can only see "Remove"

In gutenberg a user without upload permissions can't even see the featured image, let alone remove it. Upload capability is also means editing media of any kind. So in this case, we are following gutenberg. 

Screenshot 2021-08-20 at 14 27 29

I think what is currently implemented is fine and better than what we currently have. 

Edit:

I also think, allowing someone to remove something and not add a new one, is a little crazy. All it will do it make the story worse without anyway of fixing it / undoing.

**Comment by miina** [comment]
@spacedmonkey When the user adds a link, it will automatically fetch the icon as well which in some cases may be a broken link. The user should be able to remove that.

**Comment by miina** [comment]
> When the user adds a link, it will automatically fetch the icon as well which in some cases may be a broken link. The user should be able to remove that.

Alternatively, the icon should not be automatically fetched in case of users without upload permissions 🤷

**Comment by swissspidy** [comment]
It sounds like we're all talking about a few different things here. Miina was talking about the link icon, not the story poster. Those have slightly different options.

(Edit: also seems like some screenshots were from an old version of the PR, so that adds a bit to the confusion)

Anyways, let's press pause for a second to summarize this.

So, there are multiple areas with media buttons:

* Story poster image
* Publisher logo
* Video poster
* Link icons

Each area has different options. For example, video posters can be **reset** to their original value (basically removes the poster and tries to fetch the original one IIRC), and link icons are retrieved automatically and can be **replaced** or **removed**. Story poster and publisher logo can **only be edited**, not removed.

Speaking of this, what would be **extremely** helpful here is some before/after comparison in the PR description with screenshots so that we're all on the same page and know what's changing.

Now, we don't want to allow users to remove video posters as they would not have permissions to upload a new poster, which would cause AMP invalidation (bad)

Allowing resetting or removing the video poster without being able to undo this by uploading a new poster would be weird UX as well and could also cause invalidation (band).

So those options should not be visible.

The link icon is a bit different, because it is fetched externally, optional, and could be replaced by an uploaded one. No AMP invalidation since it's optional (fine).
And if it's accidentally removed by the user, there's an undo button, so no big deal.

So what we can do:

* Story poster: display thumbnail, but no button/menu
* Publisher logo: display thumbnail, but no button/menu
* Video poster: display thumbnail, but no button/menu
* Story poster: display icon, with button to remove

To achieve this, only little change is needed in this PR.

I actually tried this now real quick, see c92060657182730c19063ab9a0d0ba3910a38e47

Here's the change:

Story poster / publisher logo:

Screenshot 2021-08-20 at 16 01 40

Link icon:

Screenshot 2021-08-20 at 16 01 35


Video poster:

Screenshot 2021-08-20 at 16 01 10


Does this make sense to everybody?

**Comment by spacedmonkey** [comment]
Okay so there are 4 ways of the link icon can render. 

#### With upload, no icon
Screenshot 2021-08-20 at 15 35 47
Option shows option to pick new media. 

#### With upload, with icon
Screenshot 2021-08-20 at 15 36 02
Shows options to edit / remove ( as it is now ). 

#### Without upload, without icon
Screenshot 2021-08-20 at 15 36 49
No options and there is nothing to preview. This user can do nothing. This is what happens when a contributor adds a link currently, as can not upload an icon. 

#### Without upload, with icon
Screenshot 2021-08-20 at 15 36 42
Only shows an option to remove icon. This only happens, if a user with uploaded / picker an icon for the link. A user with access to the post and without upload can then come along remove icon, if they want. Does this functionality make sense?

**Comment by swissspidy** [comment]
> No options and there is nothing to preview. This user can do nothing. This is what happens when a contributor adds a link currently, as can not upload an icon.

Worth noting that there _can_ be a preview if linking to a site and we fetch the favicon.

> A user with access to the post and without upload can then come along remove icon, if they want. Does this functionality make sense?

IMO yes. Removing doesn‘t cause AMP invalidation, can be undone using the undo button and an icon can still be fetched remotely.
If the fetched icon looks bad, they should be able to remove.

So yes, it does make sense.

**Comment by spacedmonkey** [comment]
Two other places, that upload that a little different are 
- Captions 
- Audio background. 

Background audio is handled in #8374 . But both captions and audio have a similar behavior. 

Captions have the following behaviour

#### With upload, no captions
Screenshot 2021-08-20 at 16 17 28
Upload button is shown

#### With upload, with captions
Screenshot 2021-08-20 at 16 20 27

#### Without upload, no captions 
Screenshot 2021-08-20 at 16 02 04
Nothing shows. Should this show a message or something?

#### With upload, with captions
Screenshot 2021-08-20 at 16 20 27

**Comment by swissspidy** [comment]
I think the current captions behavior is fine 👍

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js [hunk 6]
```diff
@@ -612,12 +612,6 @@ describe('Checklist integration - Card visibility', () => {
         checkIfCardDoesNotExist
       );
 
-      // add poster image to see new problems
-      await addPosterImageWithIssues();
-      posterIssuesRequiringMediaUploadPermissions.forEach(
-        checkIfCardDoesNotExist
-      );
-
```
Comment (swissspidy) [inline packages/story-editor/src/components/checklist/karma/checklist.karma.js]: As per https://github.com/google/web-stories-wp/pull/8697#issuecomment-901934149, this won't work.

If you remove this, the test does not suppose what it's to do.

What the test ought to do:

* Add a poster image, verify that no checklist check is added for contributors

What it now does:

* Verify that no checklist check is added (which of course it never will, because there is no poster image)

I provided some suggestion on how it might be solved in the comment.

If that doesn't work, perhaps sync with Prometheus pod to get advice.

File: packages/story-editor/src/components/form/linkIcon.js [hunk 7]
```diff
@@ -53,6 +57,8 @@ function LinkIcon({ handleChange, icon, isLoading = false, ...rest }) {
     return message;
   }, [allowedImageFileTypes]);
 
+  const options = hasUploadMediaAction ? ['edit', 'remove'] : ['remove'];
```
Comment (swissspidy) [inline packages/story-editor/src/components/form/linkIcon.js:60]: This capability check might be better handled directly in `StyledMedia` itself. Otheriwse every caller component has to check this, which is easily forgotten (see c92060657182730c19063ab9a0d0ba3910a38e47 for reference)

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js (hunk 6 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: > If that doesn't work, perhaps sync with Prometheus pod to get advice.

None of the solutions did work. I do see the problem, the test is no longer valid, as can't set poster image like this. Not sure how did test ever worked.

File: packages/story-editor/src/components/form/linkIcon.js (hunk 7 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/form/linkIcon.js:60]: Where else is the is a problem?

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js (hunk 6 above)
Comment (swissspidy) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: > Not sure how did test ever worked.

It worked because on `main` the edit button is visible and can be used to mock adding a poster image:

Screenshot 2021-08-23 at 22 18 02

Please post a message on Slack, I'm sure Pea pod folks can help advise on this test.

We should either fix the test or remove it.

File: packages/story-editor/src/components/form/linkIcon.js (hunk 7 above)
Comment (swissspidy) [reply packages/story-editor/src/components/form/linkIcon.js:60]: Not necessarily saying it _is_ a problem, but it _could_ be, for example if someone adds a new feature using `MediaInput` and does not know that they need to add such a capability check.
It's also a bit repetitive because every consumer needs to add this check, whereas it could be done _just once_ within `MediaInput` itself.

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js (hunk 6 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: I removed the test, because I believe the test was invalid in the first place. In the editor, you can not set poster image, if you can upload media. But this test allows you set the poster image anyone. This would not work in the real editor. I think these lines should be removed, as they were never validly mocked.

File: packages/story-editor/src/components/form/linkIcon.js (hunk 7 above)
Comment (spacedmonkey) [reply packages/story-editor/src/components/form/linkIcon.js:60]: The reason it done here, is that it is valid to allow for removal of link icons. This is one example where we want to allow this behaviour, this is an edge case. In most cases we want to hide the icon. So the existing behaviour is correct.

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js (hunk 6 above)
Comment (swissspidy) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: > I removed the test [..]

You haven't removed the entire test though? If we can't find a solution, then the _entire test_ would need to be removed, as it's otherwise useless.

> [...]  because I believe the test was invalid in the first place. In the editor, you can not set poster image, if you can upload media. But this test allows you set the poster image anyone.

Yeah it was cheating a bit to set a poster image. Now we need to find a better way to mock it.

Let's wait for the feedback from the team on that one.

Do you recall what part of the example in https://github.com/google/web-stories-wp/pull/8697#issuecomment-901934149 did not work? Mocking the API provider like that in the fixture _should_ work?

Comment (samwhale) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: I played with it and I altered the snippet a little. The following will make the test run but we'd need to set the poster image on one of these properties. `publisher_logo_url` works but poster media  is still showing blank for me  after setting setting `featured_media_url` 🤔 

```js
fixture = new Fixture({
        mocks: {
          getStoryById: () =>
            Promise.resolve({
              title: { raw: '' },
              status: 'draft',
              author: 1,
              slug: '',
              date: '2020-05-06T22:32:37',
              date_gmt: '2020-05-06T22:32:37',
              modified: '2020-05-06T22:32:37',
              excerpt: { raw: '' },
              link: 'http://stories.local/?post_type=web-story&p=1',
              preview_link: 'http://stories.local/?post_type=web-story&p=1',
              story_data: {
                version: DATA_VERSION,
                pages: [],
              },
              featured_media: 0, // TODO TODO TODO
              featured_media_url: 'http://localhost:9876/__static__/earth.jpg',
              publisher_logo_url: 'http://localhost:9876/__static__/earth.jpg',
              permalink_template: 'http://stories3.local/stories/%pagename%/',
              style_presets: { textStyles: [], colors: [] },
              password: '',
              _embedded: { author: [{ id: 1, name: 'John Doe' }] },
              _links: {
                'wp:action-assign-author': {
                  href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
                },
                'wp:action-delete': {
                  href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
                },
                'wp:action-publish': {
                  href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
                },
                'wp:action-unfiltered-html': {
                  href: 'http://stories.local/wp-json/web-stories/v1/web-story/1',
                },
              },
            }),
        },
      })
```

Comment (swissspidy) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: `publisher_logo_url` is the publisher logo, as the name suggests. `feautred_media_url` would be the poster image (hence I added the `// TODO TODO TODO` comments there)

**Review by swissspidy — APPROVED** [review]

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js (hunk 6 above)
Comment (swissspidy) [reply packages/story-editor/src/components/checklist/karma/checklist.karma.js]: Glad to see that my suggestion from https://github.com/google/web-stories-wp/pull/8697#issuecomment-901934149 _did_ work as expected.

File: packages/story-editor/src/components/checklist/karma/checklist.karma.js [hunk 8]
```diff
@@ -577,7 +578,62 @@ describe('Checklist integration - Card visibility', () => {
 
   describe('hasUploadMediaAction=false', () => {
     beforeEach(async () => {
-      fixture = new Fixture();
+      fixture = new Fixture({
```
Comment (samwhale) [inline packages/story-editor/src/components/checklist/karma/checklist.karma.js:581]: Nice this works great! Just tested this locally. I think it'd be good to add a check in the `should not show cards that require the hasUploadMediaAction permission` test that checks to see that the `edit` button isn't rendered

```js
await fixture.events.click(fixture.editor.inspector.documentTab);
expect(fixture.screen.queryByTestId('test-id-here').toBeNull();
```

But the fixture works great 🎉 !

**Review by samwhale — APPROVED** [review]
