### PR TITLE
Editor: Hidden Padding for Text Fill & Highlight Elements

### LINKED ISSUE #4972: Add default value for padding to BG textfill
## Bug Description

Text is wrapped very tightly inside the textbox. When I add a text bg fill, the results are quite ugly.

1. Can we add a behind the scene default padding of 6px horizontal and 4px vertical for fill
2. Add a corner radius of 2px (this should be visible to users)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds a padding to text elements with bg fill and highlight that appears on the element, but is not visible in the inspector. The hidden padding is currently set to 6x2 in editor coordinates.

## Relevant Technical Choices
Applied the extra padding to the elements padding in the story data so that we didn't have to alter our positioning system at all, then added a flag that hidden padding is present on the element data so we can subtract it out in the padding input.

Wanted to maintain backwards compatibility, so if users have an existing story before this change with `0` padding on bg fill text that's pixel perfect, this doesn't alter it, but if they reapply fill or highlight to the text, the updated hidden padding will be present.

## To-do
NA

## User-facing changes
Text with bg fill or highlight should now have a little extra spacing around the text to be visually pleasant to user. Other than that there should be no visible changes to the inspector panel behavior.

## Testing Instructions
-> Go to story editor
-> Add text element
-> Apply BG Fill to text and see that the bounding box grows a little bit, but still has a value of `0` in the padding input
-> Apply BG highlight from BG Fill an see that element retains the same size and `0` for input padding.
-> Mess with different combinations of selected elements (locked, unlocked, same padding, different padding) and see that the padding input has not changed (There's a lot of combinations of scenarios you can create here, but don't worry if you don't think of all of them because the unit tests are pretty thorough going through these scenarios)

---

Fixes #4972 
See #4980

### CODE REVIEW

File: assets/src/edit-story/components/panels/design/textStyle/color.js [hunk 1]
```diff
@@ -96,6 +96,50 @@ function ColorControls({ selectedElements, pushUpdate }) {
...
+                  (element.padding.hasHiddenPadding
+                    ? HIDDEN_PADDING.horizontal
+                    : 0),
+                vertical:
+                  (element.padding.vertical || 0) -
+                  (element.padding.hasHiddenPadding
+                    ? HIDDEN_PADDING.vertical
+                    : 0),
+              },
+        }),
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/design/textStyle/color.js]: Nit: This is a lot of ternaries. Thoughts on something like `includes(mode) ? getHiddenPadding(element) : getTruePadding(element)` to make it easier to read though?

File: assets/src/edit-story/components/panels/design/textStyle/color.js [hunk 2]
```diff
@@ -96,6 +96,50 @@ function ColorControls({ selectedElements, pushUpdate }) {
...
+          backgroundTextMode: mode,
+          padding: [
+            BACKGROUND_TEXT_MODE.FILL,
+            BACKGROUND_TEXT_MODE.HIGHLIGHT,
+          ].includes(mode)
+            ? {
+                ...(element.padding ?? {}),
+                hasHiddenPadding: true,
+                horizontal:
+                  (element.padding.horizontal || 0) +
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/design/textStyle/color.js]: the calcs for horizontal and vertical are the same for both true/false of if mode is included in background. Would it be helpful to separate these out like `horizontal: getHorizontalElementPadding(element.padding)`?

File: assets/src/edit-story/components/panels/design/textStyle/padding.js [hunk 3]
```diff
@@ -65,38 +71,60 @@ function PaddingControls({
   pushUpdateForObject,
   pushUpdate,
 }) {
-  const padding = useCommonObjectValue(
-    selectedElements,
+  const displayPadding = useCommonObjectValue(
+    // Map over all elements and update display
+    // values to not include hidden padding
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/design/textStyle/padding.js:77]:
```suggestion
    // values do not include hidden padding
```

File: assets/src/edit-story/components/panels/design/textStyle/padding.js [hunk 4]
```diff
@@ -65,38 +71,60 @@ function PaddingControls({
...
+      },
+    })),
     'padding',
     DEFAULT_PADDING
   );
 
   // Only if true for all selected elements, will the toggle be true
   // (Note that this behavior is different from aspect lock ratio)
-  const lockPadding = padding.locked === true;
+  const lockPadding = displayPadding.locked === true;
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/design/textStyle/padding.js]: this is a nice update for readability of padding types.

**Review by BrittanyIRL — APPROVED** [review]
This works great!  Way to come up with something straightforward for this. Few suggestions just to decrease complexity of the push update but this is awesome.

File: assets/src/edit-story/components/panels/design/textStyle/color.js (hunk 1 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/design/textStyle/color.js]: agreed. yea good call. I'll clean it up a bit

File: assets/src/edit-story/components/panels/design/textStyle/padding.js [hunk 5]
```diff
@@ -130,32 +164,42 @@ function PaddingControls({
...
+                  }
+                : {
+                    locked: true,
+                    // When setting the lock, set both dimensions to the value of horizontal
+                    horizontal: el.padding.horizontal,
+                    vertical:
+                      el.padding.horizontal +
+                      (el.padding.hasHiddenPadding
+                        ? HIDDEN_PADDING.vertical - HIDDEN_PADDING.horizontal
+                        : 0),
```
Comment (carloskelly13) [inline assets/src/edit-story/components/panels/design/textStyle/padding.js]: If we could chop this up a bit too that would be great!

File: assets/src/edit-story/components/panels/design/textStyle/padding.js [hunk 6]
```diff
@@ -65,38 +71,52 @@ function PaddingControls({
   pushUpdateForObject,
   pushUpdate,
 }) {
-  const padding = useCommonObjectValue(
-    selectedElements,
+  const displayPadding = useCommonObjectValue(
```
Comment (miina) [inline assets/src/edit-story/components/panels/design/textStyle/padding.js]: Perhaps `displayedPadding`? `displayPadding` sounds like a boolean. WDYT?

**Review by miina — COMMENTED** [review]
Q: Is there any expected behavior for the previously existing elements? E.g. should there be migration to include the hidden padding to existing elements as well when opening a story? Or is it purposefully for the newly added elements only? So a story could have mixed logic -- some previously existing elements without padding and some with. Thoughts?

**Comment by maxyinger** [comment]
> Q: Is there any expected behavior for the previously existing elements? E.g. should there be migration to include the hidden padding to existing elements as well when opening a story? Or is it purposefully for the newly added elements only? So a story could have mixed logic -- some previously existing elements without padding and some with. Thoughts?

Yup, purposefully for the newly added elements only. I figured this makes it more backwards compatible for someone who has an existing story that uses text with bg fill and has it pixel perfect. Didn't want to break that work the user has already done. And it will update to have hidden padding as soon as they toggle any modes, but figured at that point they're already editing their story, so if they need to realign at all it wouldn't be as bad.

File: assets/src/edit-story/components/panels/design/textStyle/padding.js (hunk 6 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/design/textStyle/padding.js]: yea I like it. Added!

**Comment by carloskelly13** [comment]
@googlebot I consent.

**Comment by embarks** [comment]
Tests are nice and illustrative. LGTM!

**Review by embarks — APPROVED** [review]

File: assets/src/edit-story/components/panels/design/textStyle/utils.js [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+ *
+ * @param {Object} element - story element.
+ * @return {Object} element.padding with hidden padding properties removed
+ */
+export function removeHiddenPadding(element) {
+  return {
+    ...(element.padding ?? {}),
+    hasHiddenPadding: false,
+    ...['vertical', 'horizontal'].reduce((padding, axis) => {
+      padding[axis] =
```
Comment (miina) [inline assets/src/edit-story/components/panels/design/textStyle/utils.js]: Could this skip modifying anything if there was no hidden padding to begin with, to improve readability? And perhaps the same above in `applyHiddenPadding` -- to only add it if there is no hidden padding. Thoughts?
e.g. something like doing the calculation only if has hidden padding:
```
if (element?.padding?.hasHiddenPadding) {
        padding[axis] = (element?.padding?.[axis] || 0) - HIDDEN_PADDING[axis];
}
```

File: assets/src/edit-story/constants.js [hunk 8]
```diff
@@ -76,3 +76,8 @@ export const FONT_WEIGHT = {
   MEDIUM: 500,
   BOLD: 700,
 };
+
+export const HIDDEN_PADDING = {
+  horizontal: 6,
+  vertical: 2,
```
Comment (miina) [inline assets/src/edit-story/constants.js]: I'm actually seeing `4` for vertical in the [issue description](https://github.com/google/web-stories-wp/issues/4972). Was this requirement changed outside of the issue description?

**Review by miina — CHANGES_REQUESTED** [review]
Mainly requesting changes since it looks like the requirement padding values in the issue differs from what's implemented (2px vs 4px). LMK if it's just the issue that hasn't been updated and will revert the review.

~One more note on the requirements: it looks like the origin issue also requires adding border-radius 2px for Fill mode (visible to the user, not a hidden one) -- will this be added in a separate PR? Or again -- perhaps it's just the issue that's outdated?~

EDIT: I can see now that the 2px radius will be added in another PR.

For reference:
Screenshot 2021-01-08 at 11 34 06

File: assets/src/edit-story/constants.js (hunk 8 above)
Comment (maxyinger) [reply assets/src/edit-story/constants.js]: I've seen both 6x4 & 6x2 in ticket descriptions. I'll verify which one sam wants

File: assets/src/edit-story/components/panels/design/textStyle/utils.js (hunk 7 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/design/textStyle/utils.js]: yea I think that's a good call. should make it a bit more legible

**Comment by csossi** [comment]
Verified in QA

**Review by miina — APPROVED** [review]
LGTM!

There's still the `2px` vs `4px` pending, approving not to block you from merging once you get the answer from UX.

File: assets/src/edit-story/constants.js (hunk 8 above)
Comment (maxyinger) [reply assets/src/edit-story/constants.js]: Sam clarified and upddated the request to 8x4
