### PR TITLE
Document Sidebar UI & functionality fixes

### LINKED ISSUE #504: Document Panel - Metadata UI
## Feature Description

#405 was for the functionality of the Metadata. This ticket is a placeholder for when designs are added to figma.

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=5837%3A99)**

**[Feature Brief - Epic: Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit#heading=h.epbi26vaa94r)**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fixes #504 and partial for #405

This PR will:
- Port over date picker from Gutenberg and add some relevant functionality
- Hide password protected option until FE design ready
- Refactor Inspector component to use separate Panels
- Use radio buttons for Status/Visibility
- Other style fixes.

NOTE: Image handling (such as selecting between multiple publisher logos) and dropping to select an image will be done in a follow-up PR.

### CODE REVIEW

File: includes/REST_API/Stories_Controller.php [hunk 1]
```diff
@@ -140,20 +206,19 @@ public function get_item_schema() {
...
-			'description' => __( 'URL to enqueue the image', 'web-stories' ),
+			'description' => __( 'URL for the story\'s poster image (portrait)', 'web-stories' ),
 			'type'        => 'string',
 			'format'      => 'uri',
 			'context'     => [ 'view', 'edit', 'embed' ],
 			'readonly'    => true,
 			'default'     => '',
 		];
 
-		$schema['properties']['poster_portrait_url'] = [
```
Comment (miina) [inline includes/REST_API/Stories_Controller.php:151]: Removed this since featured media URL was used for this anyway, it was just duplicating the same value field.

File: includes/Story_Post_Type.php [hunk 2]
```diff
@@ -774,7 +721,6 @@ public static function get_schemaorg_metadata() {
 			'publisher' => [
 				'@type' => 'Organization',
 				'name'  => $publisher['name'],
-				'logo'  => $publisher['logo'],
```
Comment (miina) [inline includes/Story_Post_Type.php]: Removed publisher logo from config since now we can actually update this field and it has to be up to date when creating output for a Story. Using the assigned URL directly now.

File: package.json [hunk 3]
```diff
@@ -29,12 +29,14 @@
     "draft-js-import-html": "^1.4.1",
     "draftjs-filters": "^2.3.0",
     "history": "^4.10.1",
+    "moment": "^2.24.0",
```
Comment (miina) [inline package.json:32]: These two packages come with porting over the logic used in Gutenberg.

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 4]
```diff
@@ -0,0 +1,109 @@
+// eslint-disable-next-line eslint-comments/disable-enable-pair
+/* eslint-disable header/header */
+/* Disable reason: This file is based on Gutenberg Datepicker */
```
Comment (miina) [inline assets/src/edit-story/components/form/dateTime/datePicker.js:3]: Note that the files in `dateTime` are currently mainly based on the Gutenberg dateTime picker. We might want to leave improvements/customizing this for a separate PR.

File: assets/src/edit-story/components/form/dateTime/calendarStyle.js [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+.CalendarDay__default:hover {
+  border: 1px solid transparent;
+}
+.CalendarDay__selected {
+  background: #0085ba;
+}
+.CalendarDay__selected:hover {
+  background: rgb(0, 113, 158);
+}
+body.admin-color-sunrise .CalendarDay__selected {
```
Comment (miina) [inline assets/src/edit-story/components/form/dateTime/calendarStyle.js]: Should we ignore these and perhaps choose a static color that fits our editor instead?

File: assets/src/edit-story/components/panels/publish/index.js [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+  useKeyDownEffect(
+    dateFieldNode,
+    { key: ['space', 'enter'] },
+    () => {
+      setShowDatePicker(!showDatePicker);
+    },
+    [showDatePicker]
+  );
+
+  useOutSideClickHandler([dateTimePickerNode, dateFieldNode], () =>
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/publish/index.js]: Could we use the existing `useFocusOut` instead?

File: includes/Story_Post_Type.php (hunk 2 above)
Comment (swissspidy) [reply includes/Story_Post_Type.php]: This affects schema.org metadata output when rendering the story.

We could use [`react-schemaorg`](https://www.npmjs.com/package/react-schemaorg) to print the schema.org metadata (at least parts of it) on the client-side.

Then, we could update `Story_Renderer` / `Story_Post_Type::print_schemaorg_metadata` to merge the generated data with the one provided by PHP, and to make it filterable by plugins.

Thoughts?

File: assets/src/edit-story/components/panels/publish/index.js (hunk 6 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Done in 48dd6ec.

File: includes/Story_Post_Type.php (hunk 2 above)
Comment (miina) [reply includes/Story_Post_Type.php]: Hmm, good point.

This might not be a problem on the server-side actually, just restoring it should be enough. It was a problem while creating the markup for the Story since the story markup is using the previously saved value that came from the server, however, when generating schema.org metadata on the server-side, the value should be up to date already, it's displayed dynamically anyway. Will just restore this.

**Comment by miina** [comment]
Will still add tests but otherwise ready for review.

File: includes/REST_API/Stories_Controller.php [hunk 7]
```diff
@@ -122,6 +120,24 @@ public function prepare_item_for_response( $post, $request ) {
...
+	 * @param WP_REST_Request $request Full details about the request.
+	 * @return WP_REST_Response|WP_Error Response object on success, or WP_Error object on failure.
+	 */
+	public function update_item( $request ) {
+		$response = parent::update_item( $request );
+		if ( ! is_wp_error( $response ) ) {
+			// If publisher logo is set, let's assign that.
+			$publisher_logo_id = $request->get_param( 'publisher_logo' );
+			if ( $publisher_logo_id ) {
+				set_theme_mod( 'custom_logo', $publisher_logo_id );
```
Comment (swissspidy) [inline includes/REST_API/Stories_Controller.php]: Updating the custom logo sounds very unexpected from a user perspective. The custom logo is used for many things, for example by the currently active theme. We don't want to deface the website by replacing the logo everywhere.

Should we perhaps rather use post meta for this? Or just store the ID as part of the story JSON blob?

File: assets/src/edit-story/components/panels/publish/index.js [hunk 8]
```diff
@@ -0,0 +1,246 @@
...
+        >
+          <DateWrapper>
+            <Date>{getReadableDate(date)}</Date>{' '}
+            <Time>{getReadableTime(date)}</Time>
+          </DateWrapper>
+          <StyledToggleIcon />
+        </BoxedText>
+        {showDatePicker && (
+          <DateTimeWrapper>
+            {/* @todo get the actual value for is12Hour */}
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/publish/index.js]: For reference, this is what Gutenberg does:

https://github.com/WordPress/gutenberg/blob/f63053cace3c02e284f00918e1854284c85b9132/packages/editor/src/components/post-schedule/index.js#L10-L20

(with explanation: https://github.com/WordPress/gutenberg/blob/c0e4f538ad2ed96eed064b39657b35f5645238a1/packages/components/src/date-time/README.md#usage)

Since WordPress already localizes Moment.js, we might be able to get the date time setting from there.

File: includes/REST_API/Stories_Controller.php (hunk 7 above)
Comment (miina) [reply includes/REST_API/Stories_Controller.php]: Ha, this was based on the logic in `get_publisher_logo` since that was the first value used there, however, now thinking about, I suppose `get_publisher_logo` was just with the purpose trying to get some kind of existing image and not assuming it would be used later :)

Yep, makes sense that we should use something else, especially since it seems to be story-based and not a global value.

Will change to use meta 👍

Comment (miina) [reply includes/REST_API/Stories_Controller.php]: I wonder if we should create a new image size for the publisher logo src, with a fallback to thumbnail size, and then fallback to original size. Thoughts?

**Comment by spacedmonkey** [comment]
Screenshot from 2020-03-23 13-33-15
Seeing some weird styling issues on Linux

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 9]
```diff
@@ -0,0 +1,367 @@
...
+import moment from 'moment';
+import styled, { css } from 'styled-components';
+
+/**
+ * WordPress dependencies
+ */
+import { __ } from '@wordpress/i18n';
+import PropTypes from 'prop-types';
+
+const TIMEZONELESS_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: This line is repeated. I think it should be global constant file.

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 10]
```diff
@@ -0,0 +1,367 @@
...
+  border-color: #7e8993;
+  box-shadow: none;
+  border-radius: 3px;
+  padding: 3px 24px 3px 8px;
+  min-height: 28px;
+  max-width: 25rem;
+  vertical-align: middle;
+  appearance: none;
+  background: #fff
+    url(data:image/svg+xml;charset=US-ASCII,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M5%206l5%205%205-5%202%201-7%207-7-7%202-1z%22%20fill%3D%22%23555%22%2F%3E%3C%2Fsvg%3E)
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Is this the best way to bring in a SVG? Should be a file in our codebase?

File: includes/Story_Post_Type.php [hunk 11]
```diff
@@ -312,7 +311,6 @@ public static function admin_enqueue_scripts( $hook ) {
 					'allowedMimeTypes' => self::get_allowed_mime_types(),
 					'allowedFileTypes' => self::get_allowed_file_types(),
 					'postType'         => self::POST_TYPE_SLUG,
-					'postThumbnails'   => $post_thumbnails,
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php:315]: The api will fail if post thumbnail is submitted and the theme support it. So I think we need this still.

File: includes/REST_API/Stories_Controller.php (hunk 7 above)
Comment (spacedmonkey) [reply includes/REST_API/Stories_Controller.php]: But a logo should be a global setting IMO. So it should be stored in an web stories option.

File: assets/src/edit-story/components/panels/publish/index.js (hunk 8 above)
Comment (spacedmonkey) [reply assets/src/edit-story/components/panels/publish/index.js]: Or we should just pass all the date settings in the config?

File: assets/src/edit-story/components/panels/slug.js [hunk 12]
```diff
@@ -0,0 +1,78 @@
...
+`;
+
+function SlugPanel() {
+  const {
+    state: {
+      story: { slug, link },
+    },
+    actions: { updateStory },
+  } = useStory();
+  const handleChangeValue = useCallback(
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/panels/slug.js]: I would add some sanitation to the slug update similar this. 
https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/components/header/title.js#L67-L73

File: assets/src/edit-story/components/panels/status.js [hunk 13]
```diff
@@ -0,0 +1,181 @@
...
+    },
+    {
+      value: 'private',
+      name: __('Private', 'web-stories'),
+      helper: __('Visible to site admins & editors only', 'web-stories'),
+    },
+  ];
+
+  const passwordProtected = 'protected';
+  // @todo Add this back once we have FE implementation, too.
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/panels/status.js]: :+1:

File: assets/src/edit-story/components/panels/publish/index.js [hunk 14]
```diff
@@ -0,0 +1,246 @@
...
+  const handleChangeValue = useCallback(
+    (prop) => (value) => updateStory({ properties: { [prop]: value } }),
+    [updateStory]
+  );
+
+  const authorLabel = __('Author', 'web-stories');
+  return (
+    <SimplePanel name="publishing" title={__('Publishing', 'web-stories')}>
+      <Row>
+        <FieldLabel>{__('Publish', 'web_stories')}</FieldLabel>
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/panels/publish/index.js]: This label field should have correct aria and clicking on should open the date time picker. Even if dont do this now, maybe add a todo for later.

File: assets/src/edit-story/components/panels/publish/index.js [hunk 15]
```diff
@@ -0,0 +1,246 @@
...
+          ref={dateFieldNode}
+        >
+          <DateWrapper>
+            <Date>{getReadableDate(date)}</Date>{' '}
+            <Time>{getReadableTime(date)}</Time>
+          </DateWrapper>
+          <StyledToggleIcon />
+        </BoxedText>
+        {showDatePicker && (
+          <DateTimeWrapper>
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/publish/index.js]: Should we use `SidebarProvider` / `useSidebar` to show the date picker?

File: includes/REST_API/Stories_Controller.php (hunk 7 above)
Comment (miina) [reply includes/REST_API/Stories_Controller.php]: @spacedmonkey Seems like [you're right](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#).

File: includes/Story_Post_Type.php (hunk 11 above)
Comment (swissspidy) [reply includes/Story_Post_Type.php:315]: But this was just used to pass the current post thumbnail to `ConfigProvider`. `postThumbnails` is nowhere used anymore, so I don't see the need for it.

Comment (miina) [reply includes/Story_Post_Type.php:315]: Perhaps we should then either always add the theme support for story post, or use another field for this value -- this (cover image) will be a mandatory field and always needs to be available.

**Review by spacedmonkey — DISMISSED** [review]
There are some styling issues, as I have noted in _screenshot_. I also think we need some validation on the slug. I also think the logo should be stored in an option. Apart from that, this is good for alpha

File: package.json (hunk 3 above)
Comment (barklund) [reply package.json:32]: Uh, `moment` is huge. If you in anyway can switch to `date-fns` it would be a lot leaner!

Comment (barklund) [reply package.json:32]: Yeah, `58.4 kB` is a lot, and `moment` is probably the main culprit.

File: assets/src/edit-story/components/panels/index.js [hunk 16]
```diff
@@ -32,6 +32,9 @@ import NoSelectionPanel from './noSelection';
 import VideoOptionsPanel from './videoOptions';
 export { default as LayerPanel } from './layer';
 export { default as ColorPresetPanel } from './colorPreset';
+export { default as PublishPanel } from './publish';
+export { default as SlugPanel } from './slug';
+export { default as StatusPanel } from './status';
```
Comment (barklund) [inline assets/src/edit-story/components/panels/index.js]: Maybe group these in a "document" parent folder to set them even more apart from the regular design panels? And they can even be removed from this file (`panels/index.js`) and just be imported from this documents folder directly where used.

File: assets/src/edit-story/components/panels/publish/index.js [hunk 17]
```diff
@@ -0,0 +1,246 @@
...
+
+  const [showDatePicker, setShowDatePicker] = useState(false);
+  const dateTimePickerNode = useRef();
+  const dateFieldNode = useRef();
+
+  useKeyDownEffect(
+    dateFieldNode,
+    { key: ['space', 'enter'] },
+    () => {
+      setShowDatePicker(!showDatePicker);
```
Comment (barklund) [inline assets/src/edit-story/components/panels/publish/index.js]:
```suggestion
      setShowDatePicker((val) => !val);
```

Then you can remove `showDatePicker` from the deps array below.

File: assets/src/edit-story/components/panels/publish/index.js [hunk 18]
```diff
@@ -0,0 +1,246 @@
...
+    },
+    [showDatePicker]
+  );
+
+  useFocusOut(dateTimePickerNode, () => setShowDatePicker(false), [
+    showDatePicker,
```
Comment (barklund) [inline assets/src/edit-story/components/panels/publish/index.js]: Is this dep necessary here?

File: assets/src/edit-story/components/panels/publish/utils.js [hunk 19]
```diff
@@ -0,0 +1,39 @@
...
+ * External dependencies
+ */
+import moment from 'moment';
+
+export function getReadableDate(date, is12Hours = true) {
+  const displayDate = date ? moment(date) : moment();
+  if (is12Hours) {
+    return `${displayDate.format('MM')}/${displayDate.format(
+      'DD'
+    )}/${displayDate.format('YYYY')}`;
```
Comment (barklund) [inline assets/src/edit-story/components/panels/publish/utils.js]: `prettier`, u ok? 😟

File: assets/src/edit-story/components/panels/publish/index.js [hunk 20]
```diff
@@ -0,0 +1,246 @@
...
+  letter-spacing: ${({ theme }) => theme.fonts.body2.letterSpacing};
+  display: flex;
+  flex-direction: row;
+  background-color: ${({ theme }) => rgba(theme.colors.fg.v1, 0.1)};
+  flex: 1;
+  padding: 2px;
+  border-radius: 4px;
+  :focus {
+    outline: -webkit-focus-ring-color auto 5px;
+  }
```
Comment (barklund) [inline assets/src/edit-story/components/panels/publish/index.js]: Is this necessary? Doesn't it circumvent our "no-focus-ring-on-mouse-click"-thingy? Also, does this look correct on non-webkit?

File: assets/src/edit-story/components/panels/publish/index.js [hunk 21]
```diff
@@ -0,0 +1,246 @@
...
+
+const FieldLabel = styled(Label)`
+  flex-basis: ${({ width }) => (width ? width : '64px')};
+`;
+
+const MediaWrapper = styled.div`
+  flex-basis: 134px;
+`;
+
+const BoxedText = styled.div.attrs({ role: 'button', tabIndex: '0' })`
```
Comment (barklund) [inline assets/src/edit-story/components/panels/publish/index.js]: Can't it just be a real button?

File: assets/src/edit-story/components/panels/publish/index.js (hunk 15 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/publish/index.js]: The design calls for showing it floating over the panel, but displaying it next to the panel like the color picker would work well, I think.

File: assets/src/edit-story/components/panels/test/publish.js [hunk 22]
```diff
@@ -0,0 +1,92 @@
...
+
+    expect(publishPanel).toBeDefined();
+    expect(publisherLogo).toBeDefined();
+  });
+
+  it('should display Author field if authors available', () => {
+    const { getByText } = setupPanel();
+    const element = getByText('Author');
+    expect(element).toBeDefined();
+  });
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/publish.js]: Shouldn't this also test that it's not there when not allowed?

File: assets/src/edit-story/components/inspector/document/documentInspector.js [hunk 23]
```diff
@@ -14,217 +14,17 @@
...
-          <Button onClick={openMediaPicker} fullWidth>
-            {featuredMediaUrl
-              ? __('Replace image', 'web-stories')
-              : __('Set featured image', 'web-stories')}
-          </Button>
-        )}
-      </SimplePanel>
+      <StatusPanel />
+      <PublishPanel />
+      <SlugPanel />
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/documentInspector.js:29]: Noice! 😎

File: assets/src/edit-story/components/form/required.js [hunk 24]
```diff
@@ -19,12 +19,30 @@
...
+  flex-direction: row;
+  justify-content: flex-start;
   align-items: center;
-  margin-bottom: 5px;
-  opacity: ${({ disabled }) => (disabled ? 0.7 : 1)};
 `;
 
-export default Group;
+const Text = styled.span`
+  font-size: 12px;
```
Comment (barklund) [inline assets/src/edit-story/components/form/required.js:36]: Needs `line-height: 14px`?

File: assets/src/edit-story/components/form/required.js [hunk 25]
```diff
@@ -19,12 +19,30 @@
...
+  font-style: italic;
+  color: ${({ theme }) => theme.colors.required};
```
Comment (barklund) [inline assets/src/edit-story/components/form/required.js]: Notice that the whole element is tinted down to .55 opacity, so this should be `rgba(theme.colors.required, 0.55)`

File: assets/src/edit-story/components/form/radioGroup.js [hunk 26]
```diff
@@ -0,0 +1,121 @@
...
+      {options.map(({ value, name, helper }) => (
+        <RadioButton key={`radio-${value}`}>
+          <Radio
+            id={`radio-${value}`}
+            onChange={onChange}
+            value={value}
+            type="radio"
+            checked={value === selectedValue}
+          />
+          {name && (
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: When would it not have a `name`?

File: assets/src/edit-story/components/form/radioGroup.js [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+  line-height: ${({ theme }) => theme.fonts.label.lineHeight};
+`;
+
+function RadioGroup({ onChange, value: selectedValue, options }) {
+  return (
+    <div>
+      {options.map(({ value, name, helper }) => (
+        <RadioButton key={`radio-${value}`}>
+          <Radio
+            id={`radio-${value}`}
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: That's not document-level unique enough. You need to generate a component-specific pre- or postfix to apply to all id's. Use `uuid` package.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 28]
```diff
@@ -0,0 +1,121 @@
...
+const Helper = styled.div`
+  margin-left: ${TEXT_OFFSET}px;
+  color: ${({ theme }) => rgba(theme.colors.fg.v1, 0.54)};
+  font-size: 12px;
+  line-height: ${({ theme }) => theme.fonts.label.lineHeight};
+`;
+
+function RadioGroup({ onChange, value: selectedValue, options }) {
+  return (
+    <div>
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js:75]: This could actually be a `<label />` - and then `<Label />` could just be a `<span />`. Then you'd not need the id at all.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 29]
```diff
@@ -0,0 +1,121 @@
+/*
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js:1]: Unit test? Storybook story?

File: assets/src/edit-story/components/form/dropDown/index.js [hunk 30]
```diff
@@ -162,7 +165,14 @@ const availableKeysForSearch = [
...
 ];
 
-function DropDown({ options, value, onChange, disabled, ariaLabel }) {
+function DropDown({
+  options,
+  value,
+  onChange,
+  disabled,
+  ariaLabel,
+  isDocumentPanel,
```
Comment (barklund) [inline assets/src/edit-story/components/form/dropDown/index.js]: Could this not be a `darkMode` flag instead? We'll need it in light mode for the media library too.

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 31]
```diff
@@ -0,0 +1,367 @@
...
+  margin-right: -1px;
+  border-radius: 3px 0 0 3px;
+`;
+
+const PMButton = styled(Button)`
+  margin-left: -1px;
+  border-radius: 0 3px 3px 0;
+`;
+
+function TimePicker({ currentTime, onChange, is12Hour }) {
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Why is it called `TimePicker` when you can select both date and time? 🤔

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 32]
```diff
@@ -0,0 +1,367 @@
...
+          <option value="09">{__('September', 'web-stories')}</option>
+          <option value="10">{__('October', 'web-stories')}</option>
+          <option value="11">{__('November', 'web-stories')}</option>
+          <option value="12">{__('December', 'web-stories')}</option>
+        </SelectInput>
+      </div>
+    );
+  };
+
+  const renderDayMonthFormat = (is12HourFormat) => {
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Technically, it's not the same localisation setting, that says 12 hour format and big-endian date format. Egypt for instance (like most of NE Africa) uses little-endian date format (DMY) but 12 hour time format.

Compare [this map of date formats](https://en.wikipedia.org/wiki/Date_format_by_country) with [this map of time formats](https://en.wikipedia.org/wiki/Date_and_time_representation_by_country#/media/File:12_24_Hours_World_Map.svg).

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 33]
```diff
@@ -0,0 +1,367 @@
...
+    isToggled &&
+    `
+		background: #edeff0;
+    border-color: #8f98a1;
+    box-shadow: inset 0 2px 5px -3px #555d66;
+	`}
+`;
+
+const AMButton = styled(Button)`
+  margin-left: 8px;
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Isn't this better dealt with using flexbox to just distribute the elements?

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 34]
```diff
@@ -0,0 +1,367 @@
...
+              aria-label={__('Hours', 'web-stories')}
+              type="number"
+              step={1}
+              min={getMinHours()}
+              max={getMaxHours()}
+              value={state.hours}
+              onChange={onChangeEvent('hours')}
+              onBlur={updateHours}
+            />
+            <DateTimeSeparator aria-hidden="true">{':'}</DateTimeSeparator>
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Why hidden?

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 35]
```diff
@@ -0,0 +1,367 @@
+// eslint-disable-next-line eslint-comments/disable-enable-pair
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: I know it's a big component, but some unit tests would be awesome here!

File: assets/src/edit-story/components/form/dateTime/index.js [hunk 36]
```diff
@@ -0,0 +1,46 @@
...
+  left: -255px;
+  box-shadow: 0 3px 30px rgba(25, 30, 35, 0.1);
+  border: 1px solid ${({ theme }) => rgba(theme.colors.bg.v0, 0.2)};
+  background-color: ${({ theme }) => theme.colors.fg.v1};
+  z-index: 1;
+  width: 270px;
+  padding: 4px;
+`;
+
+function DateTimePicker({ value, onChange, is12Hour = true, forwardedRef }) {
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/index.js]: Sometimes clicking inside this component on the background closes the overlay, sometimes not. I haven't really figured out when it happens, but it seems weird.

File: assets/src/edit-story/components/panels/slug.js [hunk 37]
```diff
@@ -0,0 +1,78 @@
...
+          label={__('URL Slug', 'web-stories')}
+          value={slug}
+          onChange={handleChangeValue('slug')}
+          placeholder={__('Enter slug', 'web-stories')}
+        />
+      </Row>
+      <HelperText>
+        <Permalink rel="noopener noreferrer" target="_blank" href={link}>
+          {link}
+        </Permalink>
```
Comment (barklund) [inline assets/src/edit-story/components/panels/slug.js]: So this doesn't actually show the slug, that I've input. But that's due to some other WP setting, or?
Screen Shot 2020-03-23 at 3 39 40 PM

File: assets/src/edit-story/components/form/radioGroup.js [hunk 38]
```diff
@@ -0,0 +1,121 @@
...
+
+const RadioButton = styled.div`
+  min-height: 30px;
+  margin: 10px 0;
+`;
+
+const Radio = styled.input`
+  opacity: 0;
+  position: absolute;
+  :focus + label {
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: Should use:
```suggestion
  :focus + ${Label} {
```

To make sure it's updated if the label ever change class/element.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 39]
```diff
@@ -0,0 +1,121 @@
...
+    outline: -webkit-focus-ring-color auto 5px;
+  }
+`;
+
+const RADIO_SIZE = 20;
+const DOT_SIZE = 10;
+const TEXT_OFFSET = 30;
+
+const Label = styled.label`
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: This doesn't look correct to me - the dot is off-center:

Screen Shot 2020-03-23 at 3 36 15 PM

**Review by barklund — COMMENTED** [review]
Huge improvement. Looks great and works awesome. A lot of stuff in here though, so a lot of minor (and some bigger) comments.

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 40]
```diff
@@ -0,0 +1,367 @@
...
+const TIMEZONELESS_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
+
+const DateTimeWrapper = styled.div`
+  margin-bottom: 1em;
+`;
+
+const Fieldset = styled.fieldset`
+  margin-top: 0.5em;
+  position: relative;
+`;
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js]: Overall design is not correct here. Compare design:

Screen Shot 2020-03-23 at 3 53 42 PM

With actual component:

Screen Shot 2020-03-23 at 3 53 34 PM

Some discrepancies:

* Rounded corners on overall shape
* Padding in date-time picker
* Text inputs should be centered
* Input (30px), buttons (28px) and dropdown (28px) should be same height

And I now see that the "design" is just a screenshot - probably of the GB component. But it should then just be sharpened up a bit 😉

File: includes/REST_API/Stories_Controller.php [hunk 41]
```diff
@@ -122,6 +122,27 @@ public function prepare_item_for_response( $post, $request ) {
...
+	 * @return WP_REST_Response|WP_Error Response object on success, or WP_Error object on failure.
+	 */
+	public function update_item( $request ) {
+		$response = parent::update_item( $request );
+		if ( ! is_wp_error( $response ) ) {
+			// If publisher logo is set, let's assign that.
+			$publisher_logo_id = $request->get_param( 'publisher_logo' );
+			if ( $publisher_logo_id ) {
+				// @todo This option can keep track of all available publisher logo IDs in the future, thus the array.
+				$publisher_logo_settings           = get_option( self::PUBLISHER_SETTINGS_OPTION, [] );
```
Comment (miina) [inline includes/REST_API/Stories_Controller.php]: @spacedmonkey @swissspidy Added this instead of using the custom logo now.
Using this here as an array since based on Figma, the user can store more than one images as possible publisher logos and then choose among those. Didn't seem like having a separate category for this would make sense so perhaps we can store the logo options like this in an array, e.g. `['ids' => [1,2,3...], 'active' => 1]`, thoughts?

File: includes/Story_Post_Type.php (hunk 11 above)
Comment (miina) [reply includes/Story_Post_Type.php:315]: @spacedmonkey Doesn't look like this causes a failure even if the theme doesn't support thumbnails, leaving this as is.

File: assets/src/edit-story/components/panels/publish/index.js (hunk 15 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Just tested it out and it looks like I'm going to follow the design and not use `useSidebar` for now. It would need some other adjustments as well, such replacing the selection-like arrow in the field and looks a bit odd.

We need to get this merged before feature freeze tomorrow so can follow up in a future PR.

File: assets/src/edit-story/components/form/dateTime/timePicker.js (hunk 40 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/timePicker.js]: This is currently how the original component looks like in my browser, quite similar to the one in this PR:
Screenshot 2020-03-24 at 09 56 53

I'll add some small fixes but we can leave the actual designing for when we have one, will keep it mostly as-is since it's just a screenshot in Figma files currently.

Comment (swissspidy) [reply assets/src/edit-story/components/form/dateTime/timePicker.js]: Note that the screenshot is likely out of date as WordPress/GB has made tons of changes to its components in recent time.

File: assets/src/edit-story/components/form/radioGroup.js (hunk 39 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Are you by any chance zoomed in/out when the dot is off-center. I couldn't see the issue until I zoomed in and now can see this.

I suppose using an SVG would solve the issue.

File: assets/src/edit-story/components/form/dateTime/timePicker.js (hunk 35 above)
Comment (swissspidy) [reply assets/src/edit-story/components/form/dateTime/timePicker.js]: Note that the whole datepicker stuff is ported over from Gutenberg and should be removed again after alpha. Doesn't really make sense to add tests for it under these circumstances.

File: assets/src/edit-story/components/panels/slug.js (hunk 37 above)
Comment (spacedmonkey) [reply assets/src/edit-story/components/panels/slug.js]: Yeah, shouldn't this live update?

File: package.json (hunk 3 above)
Comment (spacedmonkey) [reply package.json:32]: I seem to remember that moment was used as it was better at translations. But I am not sure if I am miss remembering this.

Comment (swissspidy) [reply package.json:32]: We can reconsider this after alpha, as we'll have to replace the GB date picker anyway.

File: assets/src/edit-story/components/form/dateTime/timePicker.js (hunk 10 above)
Comment (swissspidy) [reply assets/src/edit-story/components/form/dateTime/timePicker.js]: We'll have to replace the GB date picker anyway, no need to modify copied files

File: assets/src/edit-story/components/panels/slug.js [hunk 42]
```diff
@@ -0,0 +1,78 @@
...
+    actions: { updateStory },
+  } = useStory();
+  const handleChangeValue = useCallback(
+    (prop) => (value) => updateStory({ properties: { [prop]: value } }),
+    [updateStory]
+  );
+  return (
+    <SimplePanel name="permalink" title={__('Permalink', 'web-stories')}>
+      <Row>
+        <BoxedTextInput
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/panels/slug.js]: Should we allow this box to be empty. Should we show an error, if published and the input is empty.

File: includes/REST_API/Stories_Controller.php (hunk 41 above)
Comment (spacedmonkey) [reply includes/REST_API/Stories_Controller.php]: This setting should have an array of allow ids and the picked logo should be stored in post meta on the story. Is that what you mean?

Comment (spacedmonkey) [reply includes/REST_API/Stories_Controller.php]: What if that image is removed from the media library, should be remove it from the array and fallback?

File: includes/Story_Post_Type.php [hunk 43]
```diff
@@ -685,6 +683,44 @@ public static function filter_template_include( $template ) {
...
+
+		// Get metadata for finding a square image.
+		$metadata = wp_get_attachment_metadata( $image_id );
+		if ( empty( $metadata ) ) {
+			return $logo_image_url;
+		}
+		// First lets check if the image is square by default.
+		$fullsize_img = wp_get_attachment_image_src( $image_id, 'full', false );
+		if ( $metadata['width'] === $metadata['height'] ) {
+			return $fullsize_img[0];
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php]:
```suggestion
			return array_shift( $fullsize_img );
```

File: includes/Story_Post_Type.php [hunk 44]
```diff
@@ -685,6 +683,44 @@ public static function filter_template_include( $template ) {
...
+
+		if ( empty( $metadata['sizes'] ) ) {
+			return $logo_image_url;
+		}
+
+		// Loop through other size to find a square image.
+		foreach ( $metadata['sizes'] as $size ) {
+			if ( $size['width'] === $size['height'] && $size['width'] >= 96 ) {
+				$logo_img = wp_get_attachment_image_src( $image_id, $size, false );
+				return $logo_img[0];
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php]:
```suggestion
				return array_shift( $logo_img );
```

File: includes/Story_Post_Type.php [hunk 45]
```diff
@@ -685,6 +683,44 @@ public static function filter_template_include( $template ) {
...
+			}
+		}
+
+		// If a square image was not found, return the full size nevertheless,
+		// the editor should take care of warning about incorrect size.
+		return $fullsize_img[0];
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php]:
```suggestion
		return array_shift ( $fullsize_img );
```

File: assets/src/edit-story/components/panels/publish/index.js (hunk 20 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Yep, not necessary when using button, removing.

File: assets/src/edit-story/components/panels/publish/index.js (hunk 18 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Yes, it seems so, otherwise, it doesn't seem to make the check every time.

File: assets/src/edit-story/components/panels/slug.js (hunk 37 above)
Comment (miina) [reply assets/src/edit-story/components/panels/slug.js]: The link of the post doesn't display "pretty" if the post isn't published. However, currently, it doesn't live update the link anyway, only upon saving, since the link might change after saving (if there are duplicates). So if you have the post published and pretty permalink turned on then it should display the correct link after saving.

(Perhaps it should live update the estimated link assuming there are no duplicates though.)

File: package.json (hunk 3 above)
Comment (miina) [reply package.json:32]: Yep, however, I'm thinking that perhaps we could remove/replace this when adjusting the calendar in general post-alpha.

Will look into `date-fns` a bit later when the rest of the things have been fixed.

File: includes/Story_Post_Type.php [hunk 46]
```diff
@@ -693,34 +729,34 @@ public static function filter_template_include( $template ) {
...
-		$logo_height = 512;
-
-		// Use the Custom Logo if set, but only if it is square.
-		$custom_logo_id = get_theme_mod( 'custom_logo' );
-		if ( has_custom_logo() && $custom_logo_id ) {
-			$custom_logo_img = wp_get_attachment_image_src( $custom_logo_id, [ $logo_width, $logo_height ], false );
-			if ( $custom_logo_img && ( $custom_logo_img[2] === $custom_logo_img[1] ) ) {
-				$logo_image_url = $custom_logo_img[0];
+		$publisher_logo_settings = get_option( 'web_stories_publisher_settings', [] );
+		$has_publisher_logo      = ! empty( $publisher_logo_settings['active'] );
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php:749]: So will this reactivity change on older stories? What if you want different logo for different times of the year, like a christmas / pride logo or something. Is that the point of multiple logos.

File: includes/Story_Post_Type.php [hunk 47]
```diff
@@ -685,6 +683,44 @@ public static function filter_template_include( $template ) {
...
 
+	/**
+	 * Gets a valid publisher logo URL. Loops through sizes and looks for a square image.
+	 *
+	 * @param {int} $image_id Attachment ID.
+	 *
+	 * @return string|false Either the URL or false if error.
+	 */
+	private static function get_valid_publisher_image( $image_id ) {
+		$logo_image_url = false;
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php:705]: There this is a fallback? Like the WP logo

File: assets/src/edit-story/components/form/radioGroup.js (hunk 26 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Ha! I guess that's very unlikely. Removed this check.

File: assets/src/edit-story/components/form/dropDown/index.js (hunk 30 above)
Comment (miina) [reply assets/src/edit-story/components/form/dropDown/index.js]: Added a `lightMode` flag since dark is the default right now.

File: assets/src/edit-story/components/form/dateTime/timePicker.js (hunk 31 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/timePicker.js]: Since DateTimePicker was taken already 😄 Changed now.

File: assets/src/edit-story/components/form/radioGroup.js (hunk 39 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Using SVGs now.

File: includes/REST_API/Stories_Controller.php (hunk 41 above)
Comment (miina) [reply includes/REST_API/Stories_Controller.php]: I'm actually a bit confused now about if the publisher logo should be global or not.

@pbakaus Could you chime in here? Based [on the document](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#), it seems like the publisher logo is a global setting.

Could you confirm if each story can have its own publisher logo or is the publisher logo a global setting (stories sharing one logo)?

@spacedmonkey Note that having multiple publisher logos will not be resolved within this PR, within this PR just one ID will be used for the relevant story, however, I want to set up the option or meta or setting so that it could be later used [with multiple publisher logos](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6123%3A2310) without having to do a migration.

File: includes/Story_Post_Type.php (hunk 46 above)
Comment (miina) [reply includes/Story_Post_Type.php:749]: > What if you want different logo for different times of the year, like a christmas / pride logo or something. Is that the point of multiple logos.

I guess so! Or perhaps each story can have their own publisher logo, e.g. a Story about Christmas has a different publisher logo than the others 🤷‍♀ 

The behavior of publisher logos should be addressed in a separate issue, likely in #570.

File: includes/Story_Post_Type.php (hunk 47 above)
Comment (miina) [reply includes/Story_Post_Type.php:705]: I'm not certain actually if there should be a fallback if the publisher logo is set. If the logo is set but it's not correct then the editor should notify about it, since it's marked as `required`.

Currently, the fallback is used only if the publisher logo is not set.

IDK what's the ideal behavior here until the editor enforces the correct size image. Thoughts?

File: assets/src/edit-story/components/form/radioGroup.js (hunk 29 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js:1]: Added

File: assets/src/edit-story/components/panels/slug.js (hunk 42 above)
Comment (miina) [reply assets/src/edit-story/components/panels/slug.js]: It's not being saved if empty, will just keep the previous value.

File: includes/Story_Post_Type.php (hunk 47 above)
Comment (miina) [reply includes/Story_Post_Type.php:705]: OK, always adding a fallback for now, this should be changed later though.

File: assets/src/edit-story/components/panels/publish/index.js (hunk 8 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Added using the `time_format` option for detecting the time format. 8cbf880

File: assets/src/edit-story/components/panels/slug.js (hunk 12 above)
Comment (miina) [reply assets/src/edit-story/components/panels/slug.js]: Added `cleanForSlug`. 

@swissspidy Any reason for `cleanForSlug` removing `-` from the value? Is that purposefully not allowed?

File: assets/src/edit-story/components/panels/slug.js (hunk 37 above)
Comment (miina) [reply assets/src/edit-story/components/panels/slug.js]: Live update added: 1bbd3f9

File: assets/src/edit-story/components/panels/publish/index.js (hunk 14 above)
Comment (miina) [reply assets/src/edit-story/components/panels/publish/index.js]: Will create an issue for it, this seems to be a general issue for the `Label` component.

**Comment by miina** [comment]
The PR is updated other than confirming the global publisher logo behavior, please re-review.

File: assets/src/edit-story/components/form/dropDown/index.js [hunk 48]
```diff
@@ -162,7 +164,14 @@ const availableKeysForSearch = [
...
 ];
 
-function DropDown({ options, value, onChange, disabled, ariaLabel }) {
+function DropDown({
+  options,
+  value,
+  onChange,
+  disabled,
+  ariaLabel,
+  lightMode,
```
Comment (barklund) [inline assets/src/edit-story/components/form/dropDown/index.js]: I've come to accept that directly default'ing in the component definition rather than using `defaultProps` is okay.
```suggestion
  lightMode = false,
```

File: assets/src/edit-story/components/form/radioGroup.js [hunk 49]
```diff
@@ -0,0 +1,98 @@
...
+  color: ${({ theme }) => rgba(theme.colors.fg.v1, 0.54)};
+  font-size: 12px;
+  line-height: ${({ theme }) => theme.fonts.label.lineHeight};
+`;
+
+function RadioGroup({ onChange, value: selectedValue, options }) {
+  return (
+    <div>
+      {options.map(({ value, name, helper }) => (
+        <RadioButton key={`radio-${value}`}>
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: `value` is fine here - it's just a JS thing used by react, not printed to DOM.
```suggestion
        <RadioButton key={value}>
```

File: assets/src/edit-story/components/form/radioGroup.js [hunk 50]
```diff
@@ -0,0 +1,98 @@
...
+          <Radio
+            onChange={onChange}
+            value={value}
+            type="radio"
+            checked={value === selectedValue}
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js:82]: Should have an `aria-labelledby` referring to the `<Name />` element only (and then you need some id generation) - as the helper text should not be considered part of the label for the input element.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 51]
```diff
@@ -0,0 +1,98 @@
...
+`;
+
+const Helper = styled.div`
+  margin-left: ${TEXT_OFFSET}px;
+  color: ${({ theme }) => rgba(theme.colors.fg.v1, 0.54)};
+  font-size: 12px;
+  line-height: ${({ theme }) => theme.fonts.label.lineHeight};
+`;
+
+function RadioGroup({ onChange, value: selectedValue, options }) {
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js:72]: Was about to comment that we need keyboard arrow navigation here, but browsers do that magically for radio groups. Neat!

File: assets/src/edit-story/components/form/required.js [hunk 52]
```diff
@@ -18,13 +18,33 @@
...
+  font-size: 12px;
+  line-height: 14px;
+  font-style: italic;
+  color: ${({ theme }) => rgba(theme.colors.required, 0.55)};
+`;
+
+function Required() {
+  return (
+    <RequiredWrapper>
+      <Text>{__('required', 'web-stories')}</Text>
```
Comment (barklund) [inline assets/src/edit-story/components/form/required.js]: Should we explicitly lowercase this, in case translators translate with initial uppercase letter? @swissspidy, what's best practice here?

File: assets/src/edit-story/components/form/stories/radioGroup.js [hunk 53]
```diff
@@ -0,0 +1,68 @@
...
+      value: 'c',
+      name: __('Option C without description', 'web-stories'),
+    },
+  ];
+  const [value, setValue] = useState('a');
+
+  return (
+    <RadioGroup
+      options={options}
+      onChange={(evt) => setValue(evt.target.value)}
```
Comment (barklund) [inline assets/src/edit-story/components/form/stories/radioGroup.js:64]: Hm, should the `onChange` always do this internally in the component - extract the target value? Or is it okay to return the event object and let the handler deal with it? Most importantly I think it's valuable to make our API's consistent.

File: assets/src/edit-story/components/form/test/radioGroup.js [hunk 54]
```diff
@@ -0,0 +1,93 @@
...
+      />,
+      {
+        wrapper: ThemeProviderWrapper,
+      }
+    );
+
+    const optionA = getByText('Option A');
+    const optionB = getByText('Option B');
+
+    expect(optionA).toBeInTheDocument();
```
Comment (barklund) [inline assets/src/edit-story/components/form/test/radioGroup.js:73]: Remember that we have [all the awesome `jest-dom` selectors](https://github.com/testing-library/jest-dom) too - including [`toBeChecked()`](https://github.com/testing-library/jest-dom#tobechecked):

```js
expect(getByLabel(/option a/i)).toBeChecked();
```

File: assets/src/edit-story/components/form/test/radioGroup.js [hunk 55]
```diff
@@ -0,0 +1,93 @@
...
+      <RadioGroup
+        onChange={onChange}
+        options={options}
+        value={options[0].value}
+      />,
+      {
+        wrapper: ThemeProviderWrapper,
+      }
+    );
+    const optionB = getByText(/Option B/i).closest('label');
```
Comment (barklund) [inline assets/src/edit-story/components/form/test/radioGroup.js]: This should work:

```suggestion
    const optionB = getByLabel(/Option B/i);
```

File: assets/src/edit-story/components/form/test/radioGroup.js [hunk 56]
```diff
@@ -0,0 +1,93 @@
...
+    fireEvent.click(optionB);
+    expect(onChange).toHaveBeenCalledTimes(1);
```
Comment (barklund) [inline assets/src/edit-story/components/form/test/radioGroup.js:92]: Also need to confirm the call argument:

```suggestion
    expect(onChange).toHaveBeenCalledWith({ target: { value: 'b' }});
```

File: includes/REST_API/Stories_Controller.php (hunk 41 above)
Comment (pbakaus) [reply includes/REST_API/Stories_Controller.php]: The publisher logo is global. On Figma, you'll see that it is connected to a global Settings page for the plugin. /cc @samitron7

File: assets/src/edit-story/components/inspector/document/publish/utils.js [hunk 57]
```diff
@@ -0,0 +1,53 @@
...
+  const hourFormat = is12Hours ? 'hh' : 'HH';
+  const am = is12Hours ? displayTime.format('A') : '';
+  return `${displayTime.format(hourFormat)}:${displayTime.format('mm')}${am}`;
+}
+
+export function is12Hour(timeFormat) {
+  if (!timeFormat) {
+    return true;
+  }
+  return /a(?!\\)/i.test(
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/publish/utils.js]: The `/i` is a superfluous when using `.toLowerCase()` anyway. Can be skipped for a micro-optimization 🚀!

File: assets/src/edit-story/components/inspector/document/status.js [hunk 58]
```diff
@@ -0,0 +1,181 @@
...
+  // @todo Add this back once we have FE implementation, too.
+  /*visibilityOptions.push({
+    name: __('Password Protected', 'web-stories'),
+    value: passwordProtected,
+  });*/
+
+  // @todo this should still allow showing the moment where the warning is red, currently just doesn't allow adding more.
+  const handleChangePassword = useCallback(
+    (value) => {
+      if (value.length <= 20) {
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/status.js]: Use `isValidPassword`?

File: assets/src/edit-story/components/inspector/document/test/slug.js [hunk 59]
```diff
@@ -0,0 +1,71 @@
...
+describe('SlugPanel', () => {
+  it('should render Slug Panel', () => {
+    const { getByText } = setupPanel();
+    const element = getByText('Permalink');
+    expect(element).toBeDefined();
+  });
+
+  it('should display permalink', () => {
+    const { getByText } = setupPanel();
+    expect(getByText('https://example.com/foo')).toBeDefined();
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/test/slug.js:68]: `getByText` will throw if target doesn't exist, so this will fail pretty hard. But failure is failure, I guess. 🤷‍♂

File: assets/src/edit-story/components/inspector/document/test/status.js [hunk 60]
```diff
@@ -0,0 +1,109 @@
...
+    const { getByText, updateStory } = setupPanel();
+    const publishOption = getByText(/Public/i).closest('label');
+    fireEvent.click(publishOption);
+    expect(updateStory).toHaveBeenCalledWith({
+      properties: {
+        status: 'publish',
+        password: '',
+      },
+    });
+  });
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/test/status.js:109]: Needs a test for deleting story too.

**Review by barklund — COMMENTED** [review]
Awesome work! Let's get this in very soon!

File: assets/src/edit-story/components/form/stories/radioGroup.js (hunk 53 above)
Comment (miina) [reply assets/src/edit-story/components/form/stories/radioGroup.js:64]: Hmm, it looks like after the refactoring PR of the design panel, the text and number inputs seem to pass both the `evt.target.value` and `evt` to `onChange`.

File: assets/src/edit-story/components/inspector/document/test/status.js (hunk 60 above)
Comment (miina) [reply assets/src/edit-story/components/inspector/document/test/status.js:109]: The delete button is not actually in Figma and it's not clear yet where it should be but I guess it doesn't harm to add a test nevertheless :) Added in 2feebc3

File: assets/src/edit-story/components/form/required.js (hunk 52 above)
Comment (miina) [reply assets/src/edit-story/components/form/required.js]: @barklund All the comments except for this should be addressed (mostly in 22a2759).

Will keep this open.

File: assets/src/edit-story/components/form/stories/radioGroup.js (hunk 53 above)
Comment (miina) [reply assets/src/edit-story/components/form/stories/radioGroup.js:64]: Changed to pass both `evt.target.value` and `evt`.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 61]
```diff
@@ -0,0 +1,101 @@
...
+  return (
+    <div>
+      {options.map(({ value, name, helper }) => (
+        <RadioButton key={value}>
+          <Radio
+            onChange={(evt) => onChange(evt.target.value, evt)}
+            value={value}
+            type="radio"
+            checked={value === selectedValue}
+            aria-labelledby={`label-${name}-${radioGroupId}`}
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js]: If `name` has a space, that'll break the id. Just use the generated id alone, should work fine.

File: assets/src/edit-story/components/inspector/document/test/status.js [hunk 62]
```diff
@@ -0,0 +1,120 @@
...
+
+  it('should trigger deleting the story when clicking on delete button', () => {
+    const { deleteStory, queryByText } = setupPanel();
+
+    const deleteButton = queryByText('Move to trash');
+    expect(deleteButton).toBeDefined();
+
+    fireEvent.click(deleteButton);
+    expect(deleteStory).toHaveBeenCalledTimes(1);
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/document/test/status.js:118]: I think it's okay to test it's been called without arguments too:

```suggestion
    expect(deleteStory).toHaveBeenCalledWith();
```

File: assets/src/edit-story/components/form/radioGroup.js (hunk 61 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Right, didn't think about that. 💡

Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Hmm, it should still need something unique for this specific Radio though, since `radioGroupId` is for the whole group of radios, shouldn't it?

File: assets/src/edit-story/components/inspector/document/test/status.js (hunk 62 above)
Comment (miina) [reply assets/src/edit-story/components/inspector/document/test/status.js:118]: It is called with the event object though.

File: assets/src/edit-story/components/form/radioGroup.js (hunk 61 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Perhaps just the combination of index and the id.

Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: Changed in ec6596f.

**Comment by miina** [comment]
@spacedmonkey @swissspidy PTAL at this commit: 26ad326

It was confirmed that the publisher logo is global and should change for all the stories when changing. This commit makes the changes to render it dynamically by replacing a static placeholder in the content. Let me know what you think. That should be the last part to get the PR ready.

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 63]
```diff
@@ -0,0 +1,108 @@
...
+
+/**
+ * External dependencies
+ */
+import moment from 'moment';
+// Needed to initialise the default datepicker styles.
+// See: https://github.com/airbnb/react-dates#initialize
+import 'react-dates/initialize';
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/dateTime/datePicker.js:11]: /cc @swissspidy to look out for conflicts with `react-with-styles`.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 64]
```diff
@@ -0,0 +1,101 @@
...
+
+const Helper = styled.div`
+  margin-left: ${TEXT_OFFSET}px;
+  color: ${({ theme }) => rgba(theme.colors.fg.v1, 0.54)};
+  font-size: 12px;
+  line-height: ${({ theme }) => theme.fonts.label.lineHeight};
+`;
+
+function RadioGroup({ onChange, value: selectedValue, options }) {
+  const radioGroupId = uuidv4();
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/radioGroup.js]: This will regen new ID on every render. I don't think we want that. Let's use `useMemo`.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 65]
```diff
@@ -0,0 +1,101 @@
...
+          <Radio
+            onChange={(evt) => onChange(evt.target.value, evt)}
+            value={value}
+            type="radio"
+            checked={value === selectedValue}
+            aria-labelledby={`${i}-${radioGroupId}`}
+          />
+          <Label isActive={value === selectedValue}>
+            {value === selectedValue ? <Selected /> : <UnSelected />}
+            <Name id={`${i}-${radioGroupId}`}>{name}</Name>
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/radioGroup.js]: We can move `id` to `Label` here. The screen reader would do the right thing. And it'd be more canonical to have label linked for this.

File: assets/src/edit-story/components/form/radioGroup.js [hunk 66]
```diff
@@ -0,0 +1,101 @@
...
+  return (
+    <div>
+      {options.map(({ value, name, helper }, i) => (
+        <RadioButton key={value}>
+          <Radio
+            onChange={(evt) => onChange(evt.target.value, evt)}
+            value={value}
+            type="radio"
+            checked={value === selectedValue}
+            aria-labelledby={`${i}-${radioGroupId}`}
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/radioGroup.js]: ID should not start with a number. Let's prefix it here, e.g. "radio-${i}..."

**Review by dvoytenko — DISMISSED** [review]

File: assets/src/edit-story/components/form/radioGroup.js (hunk 65 above)
Comment (miina) [reply assets/src/edit-story/components/form/radioGroup.js]: The id is there to ensure that only this part would be considered the actual label and to exclude the description/helper which should not be part of the label.

See also https://github.com/google/web-stories-wp/pull/667#discussion_r397295750

File: assets/src/edit-story/components/form/required.js (hunk 52 above)
Comment (swissspidy) [reply assets/src/edit-story/components/form/required.js]: Don't think we need to explicitly lowercase, but adding some context for translators would certainly be useful.

Something like `_x('required', 'required form input', 'web-stories')` perhaps

File: includes/Story_Post_Type.php (hunk 46 above)
Comment (spacedmonkey) [reply includes/Story_Post_Type.php:749]: Why isnt this be tackelled here?

File: tests/js/jest.config.js [hunk 67]
```diff
@@ -28,6 +28,7 @@ module.exports = {
     '<rootDir>/tests/js/setup-globals',
     '<rootDir>/tests/js/setup-mocks',
     'jest-canvas-mock',
+    'core-js',
```
Comment (swissspidy) [inline tests/js/jest.config.js:31]: Curious: why is that needed? Because of the datepicker component?

File: tests/phpunit/tests/Story_Renderer.php [hunk 68]
```diff
@@ -198,8 +202,33 @@ public function test_maybe_add_analytics_remove_with_filter() {
...
+	 * @covers \Google\Web_Stories\Story_Renderer::add_publisher_logo
+	 */
+	public function test_add_publisher_logo() {
+		$post_with_publisher_logo = self::factory()->post->create_and_get(
+			[
+				'post_content' => '<html><head></head><body><amp-story publisher-logo-src=""' . Story_Post_Type::PUBLISHER_LOGO_PLACEHOLDER . '"></amp-story></body></html>',
+			]
+		);
+
+		$attachment_id = self::factory()->attachment->create_upload_object( __DIR__ . '/REST_API/attachment.jpg', 0 );
```
Comment (swissspidy) [inline tests/phpunit/tests/Story_Renderer.php]: Could we move the JPG to `tests/phpunit/data`?

File: assets/src/edit-story/output/story.js [hunk 69]
```diff
@@ -49,16 +49,16 @@ function OutputStory({
...
         <meta name="web-stories-replace-head-end" />
       </head>
       <body>
         <amp-story
           standalone="standalone"
           publisher={publisher.name}
-          publisher-logo-src={publisher.logo}
-          title={story.title}
-          poster-portrait-src={story.posterPortraitUrl || fallbackPoster}
+          publisher-logo-src={logoPlaceholder}
```
Comment (swissspidy) [inline assets/src/edit-story/output/story.js:59]: Is this still valid AMP when it's just a placeholder?

File: includes/REST_API/Stories_Controller.php [hunk 70]
```diff
@@ -122,6 +122,27 @@ public function prepare_item_for_response( $post, $request ) {
...
+				$publisher_logo_settings['active'] = $publisher_logo_id;
+				update_option( self::PUBLISHER_SETTINGS_OPTION, $publisher_logo_settings, false );
```
Comment (swissspidy) [inline includes/REST_API/Stories_Controller.php]: So now there's an option named `web_stories_publisher_settings` with the following content:

```
[
  'active' => 123
]
```

I'd either change the name to something like `web_stories_publisher_logos` or change the data structure, e.g.:

```
[
  'publisherLogos': {
    'active' => 123
  }
]
```

See also #754. We don't have to worry about that too much.

**Comment by spacedmonkey** [comment]
Bug: If the site has more than 10 users, the dropdown doesn't have a scrollbar. 
Screenshot from 2020-03-25 13-03-21
Tip to test locally. 
Run the following command. 
```docker-compose -f bin/local-env/docker-compose.yml exec cli wp user generate --count=200```

**Comment by spacedmonkey** [comment]
Related https://github.com/google/web-stories-wp/issues/756

**Comment by spacedmonkey** [comment]
Screenshot from 2020-03-25 13-12-28
Still seeing some date picker issues in the smaller version of the sidebar.

File: tests/js/jest.config.js (hunk 67 above)
Comment (miina) [reply tests/js/jest.config.js:31]: Yep, `flat` fails otherwise somewhere, for me at least.

File: assets/src/edit-story/output/story.js (hunk 69 above)
Comment (miina) [reply assets/src/edit-story/output/story.js:59]: Nope, we can use WP fallback logo instead of that to make it valid but always static value. Just answered in Slack, too :)

File: includes/REST_API/Stories_Controller.php (hunk 70 above)
Comment (miina) [reply includes/REST_API/Stories_Controller.php]: Okay, will change to `web_stories_publisher_logos`.

The idea is to have it something like for when there are multiple logos later.
```
[
 'active' => 123,
 'ids' => [1,2,3,4],
]
```

**Comment by spacedmonkey** [comment]
UX question, should the publisher logo and cover image be clickable? It seems like the dialog only shows when the edit icon is displayed.

**Comment by miina** [comment]
> Bug: If the site has more than 10 users, the dropdown doesn't have a scrollbar.

@spacedmonkey Thanks for testing this. 👍 Please file a bug for the dropdown component, out of scope for this PR.

**Comment by spacedmonkey** [comment]
> > Bug: If the site has more than 10 users, the dropdown doesn't have a scrollbar.
> 
> @spacedmonkey Thanks for testing this.  Please file a bug for the dropdown component, out of scope for this PR.

I was about to delete this comment. I created a ticket https://github.com/google/web-stories-wp/issues/756

File: includes/REST_API/Stories_Controller.php (hunk 70 above)
Comment (miina) [reply includes/REST_API/Stories_Controller.php]: Changed in 1b012f3

File: assets/src/edit-story/output/story.js (hunk 69 above)
Comment (miina) [reply assets/src/edit-story/output/story.js:59]: Changed in 1b012f3, PTAL

**Comment by miina** [comment]
@spacedmonkey The style should be improved a bit. It should be better but still not ideal -- with a very narrow screen, the right side of the calendar goes out of the screen a little bit, however, it can be scrolled out to be visible which seems to be the default behavior currently for the sidebar. Can you check how do you see it now?

**Comment by dvoytenko** [comment]
@miina  LG from me, but i've only done a top-level review. So pls finish the review with others.

File: assets/src/edit-story/components/inspector/document/slug.js [hunk 71]
```diff
@@ -0,0 +1,87 @@
...
+    (value) => {
+      updateStory({
+        properties: { slug: cleanForSlug(value) },
+      });
+    },
+    [updateStory]
+  );
+
+  const displayLink = slug
+    ? permalinkConfig.prefix + slug + permalinkConfig.suffix
```
Comment (swissspidy) [inline assets/src/edit-story/components/inspector/document/slug.js]: When using ugly permalinks this results in `https://web-stories.local/?web-story=test-storytest-storyundefined` for me.

Comment (miina) [reply assets/src/edit-story/components/inspector/document/slug.js]: Added a check for if permalink settings were found in the template.

However, now, in case of ugly permalinks, it's not live updating. We could follow up in a separate PR for this or otherwise can look into it tomorrow. (Running out of time today)

**Review by swissspidy — APPROVED** [review]
Approving for now as discussed. New smaller PRs will be created to iterate on it.

**Comment by miina** [comment]
@spacedmonkey I actually wrote a longer text for dismissing your review but for some reason it didn't add it 😕 

Dismissed your review to get this merged and unblock some other issues since almost all the comments are addressed, will follow up for the remaining ones (such as the style oddities on narrow screens) with separate issues.

**Comment by miina** [comment]
Follow-up issues: #787 #788 #789
