### PR TITLE
Dashboard: Add support for Private stories on Dashboard

### LINKED ISSUE #5650: Stories set to Status:Private, cannot be found in My Stories Dashboard
## Bug Description

While it is possible to set the status of a web story to Private (as visible to admin/editors), once this is done, the Dashboard > My Stories stops showing the newly Private story. The user has to go to Classic WP List view to find stories marked Private. 

## Expected Behaviour

This is a shortcoming that needs to be addressed - either the ability to mark as Private should be disabled, OR a filter for Private stories enabled in the My Stories Dashboard, similar to Published and Draft stories.

## Steps to Reproduce

- Go to a web story that you have authored and change the Document > Status & Visibility to Private
- Go back to the My Stories  Dashboard and look for the story
- It will not be possible to find or search for the private story in the dashboard
- 

## Screenshots

image12
image3

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by carloskelly13**
## Summary

Adds support for Private Stories in Dashboard

If there are private stories show the tab. If there are not, show nothing. Private stories can be marked in the classic WP list view when you quick edit or the Document panel.

Screen Shot 2021-01-05 at 3 38 36 PM

## User-facing changes

A new Private tab for private stories in the Dashboard My Stories view.

## Testing Instructions

1. Create a new Story
2. Visit the Classic WordPress View and Quick Edit a story
3. Select the Private checkbox on the right.
4. Refresh the Dashboard and see the Private tab

---

Fixes #5650

### CODE REVIEW

File: includes/REST_API/Stories_Controller.php [hunk 1]
```diff
@@ -343,6 +343,7 @@ public function get_items( $request ) {
 			'publish' => 'publish',
 			'future'  => 'future',
 			'draft'   => 'draft',
+			'private' => 'private',
```
Comment (swissspidy) [inline includes/REST_API/Stories_Controller.php:346]: Shouldn't this be part of `all` above as well?

File: assets/src/dashboard/constants/stories.js [hunk 2]
```diff
@@ -116,6 +116,7 @@ export const STORY_STATUS = {
   DRAFT: 'draft',
   FUTURE: 'future',
   PUBLISH: 'publish',
+  PRIVATE: 'private',
```
Comment (swissspidy) [inline assets/src/dashboard/constants/stories.js:119]: Should also add this to `ALL` above, no?

**Comment by swissspidy** [comment]
> If there are not, show nothing. Private stories can only be marked in the classic WP list view when you quick edit.

FWIW one can directly mark stories as private in the editor. It's just so that currently they won't be visible in the dashboard, but only the classic list view.

File: includes/REST_API/Stories_Controller.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/REST_API/Stories_Controller.php:346]: Can we add a check in this test for this property [here](https://github.com/google/web-stories-wp/blob/main/tests/phpunit/tests/REST_API/Stories_Controller.php#L187).

**Comment by spacedmonkey** [comment]
Screenshot 2021-01-06 at 11 43 13

I was able to see the private tab, including the count when logged as an author. You need to add a check for read_private_posts capability. This could look like this. 

```
$post_type_object = get_post_type_object( Story_Post_Type::POST_TYPE_SLUG );
$read_private_posts = current_user_can( $post_type_obj->cap->read_private_posts );
```

We do something similar in [get_editor_settings](https://github.com/google/web-stories-wp/blob/c7d31e1c6d360c96693e5eb878ab47bba38dde93/includes/Story_Post_Type.php#L495-L576). You can copy and paste much of it. 

I would add a similar test for user without that capability. Maybe an e2e test.

**Comment by swissspidy** [comment]
@carlos-kelly let us know if you need help with any of the above, happy to assist!

File: includes/REST_API/Stories_Controller.php (hunk 1 above)
Comment (carlos-kelly) [reply includes/REST_API/Stories_Controller.php:346]: It should not because we do not want private stories to show in the all list. It's the exception to the rule.

File: assets/src/dashboard/constants/stories.js (hunk 2 above)
Comment (carlos-kelly) [reply assets/src/dashboard/constants/stories.js:119]: Nope, like above, private stores are not part of all, but a separate group. Now this could change and it would be easy to add.

**Comment by carlos-kelly** [comment]
@swissspidy If one of you wanted to add the PHP code that would be great, it's not my area of expertise and I can manage any front-end changes. As for private being part of all, the current definition is no, but I don't have strong feelings either way.

**Review by BrittanyIRL — APPROVED** [review]
LGTM! Thanks for the directions on how to make stories private.

File: assets/src/dashboard/app/views/myStories/header/test/header.js [hunk 3]
```diff
@@ -137,6 +137,33 @@ describe('My Stories <Header />', function () {
...
+            pageSize: { width: 200, height: 300 },
+          }}
+          wpListURL="fakeurltoWordPressList.com"
+        />
+      </LayoutProvider>
+    );
+    expect(getByText('All Stories (19)')).toBeInTheDocument();
+    expect(getByText('Drafts (9)')).toBeInTheDocument();
+    expect(getByText('Published (10)')).toBeInTheDocument();
+    expect(queryByText('Private')).not.toBeInTheDocument();
```
Comment (spacedmonkey) [inline assets/src/dashboard/app/views/myStories/header/test/header.js:163]: Can we also have a test for when `canReadPrivatePosts: false` and make sure that Private does not display.

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
There needs to be a test for Private post being hidden if capability is disabled.

**Comment by swissspidy** [comment]
> LGTM! Thanks for the directions on how to make stories private.

I was actually confused by these instructions. What's wrong with just doing that in the editor?

Screenshot 2021-01-08 at 16 43 41

So this:

> Private stories can only be marked in the classic WP list view when you quick edit.

Is not really true

**Comment by carloskelly13** [comment]
@swissspidy That's fine! That was how it was mentioned in the ticket. I'm not sure everyone knows about that but I can update it!

**Comment by carloskelly13** [comment]
@spacedmonkey Good call on the negative case for permissions. Added that test!

File: assets/src/dashboard/app/views/myStories/header/test/header.js [hunk 4]
```diff
@@ -191,6 +191,39 @@ describe('My Stories <Header />', function () {
     expect(getByText('Private (2)')).toBeInTheDocument();
   });
 
+  it('should not show the private tab even if there are private stories when the user does not have permission.', function () {
```
Comment (spacedmonkey) [inline assets/src/dashboard/app/views/myStories/header/test/header.js:194]: 👍

**Review by spacedmonkey — APPROVED** [review]
👍 Thanks for adding the tests.
