### PR TITLE
History: ensure user stays on the page where the change was applied.

### LINKED ISSUE #1030: History not managing the current page correctly
## Bug Description

Undo and Redo seem to change the current page, incorrectly.

## Expected Behaviour
The current page should be handled properly by history.
Undo should not switch the page unexpectedly.

## Steps to Reproduce
1. Create at least 2 Pages.
2. Go to some Page other than the first.
3. Add an element.
4. Make a change, e.g. width
5. Click "Undo"
6. See the current page being changed, too

## Screenshots
history

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fixes #1030 

Description edited based on Paul's comments below.

~It looks like it might make sense to store the current page change in history.~

When the user undoes or redoes a change, then the user expects:
- staying on the same Page where the change happens as opposed to undoing the change + jumping to a different page at the same time.
- ~moving to a different page first and then clicking again undo/redo as opposed to undoing/redoing something on a different page + switching the Page at the same time without the user being able to see what changed during that move.~

This PR overrides the history replay via ignoring the current page stored in the entries in some cases and using a current page that's relevant to where the changed happened instead.

The current page will be overridden if:
- There is a change in one of the pages (excluding adding new pages)
- The change includes switching the page.

### CODE REVIEW

**Comment by miina** [comment]
Perhaps we could track the current page change as a separate history entry for alpha to avoid unexpected page switches and for post-alpha figure out a more sophisticated history tracking which could for example

a) Track the current page as a separate history entry but only if the previous history entry changed more than just the current page. (e.g. not to save more than one page change in a row as a separate history entry)
b) Not track the current page as a separate history entry but adjust the Replay logic so that the expected page would be displayed instead of what's actually written in the history.
c) ... or something else

Thoughts?

cc @barklund @dvoytenko

**Comment by swissspidy** [comment]
So this partially undoes #627?

**Comment by miina** [comment]
> So this partially undoes

Correct.

**Comment by barklund** [comment]
> We've previously talked about squashing multiple history entries if related like this. But it's a bit tricky to do, so we've avoided it so far.

We could consider applying a very simple squashing mechanism in the history reducer if we keep the old reference of the story's state. This could work by going up the changed object chain and if only one object/property appear to have changed, the history can be replaced instead of pushed. This is rather naive, but could get us through alpha.

**Comment by miina** [comment]
> Not sure what you mean here.

What I meant was putting the responsibility of figuring out the correct page to display in "Replay" instead of just replaying, however, that would get messy and a) would be a better option anyway.

**Review by barklund — COMMENTED** [review]
i think this makes sense for alpha.

@pbakaus, WDYT? Try changing things on one page, changing page, changing things, change page and then start undoing - both in master and in this branch. I think this is the better experience for now, but yes if you change page a lot, it's a lot of history entries "wasted" on that.

**Comment by pbakaus** [comment]
I'm confused - currently, undo/redo seems to work on a per-page level only (?!?!). Meaning, I can't undo past the point where I switched pages. That's super weird.

Here's what I would like:

1. When I undo or redo, the editor automatically switches to the page of concern
2. This does *not* mean that navigations are added to the history stack. If I just click around between pages, pressing undo would *not* undo the navigation - it would undo the last actual action, and automatically jump to the page of concern.

Can we please make that a reality?

**Comment by miina** [comment]
@pbakaus 
> I'm confused - currently, undo/redo seems to work on a per-page level only (?!?!). Meaning, I can't undo past the point where I switched pages. That's super weird.

It looks like a new bug and more critical than the one in this issue, checking.

> it would undo the last actual action, and automatically jump to the page of concern.

That's how it should be happening currently (well, was, before the new bug), however, this behavior (not having page switch as a separate entry) causes some unexpected happenings (see the video in the description of https://github.com/google/web-stories-wp/issues/1030).

For example, if the user makes a change, then clicks around between Pages and then clicks Undo, the initial Page is restored + the change undone at the same time, so the user might not even know that something changed back on the Page.

One suggestion was that if the user clicks `Undo` (e.g. after clicking between pages), first, the relevant page to the previous page would show and then, the next `Undo` would actually make the change.

Thoughts?

**Comment by pbakaus** [comment]
> @pbakaus
> 
> > I'm confused - currently, undo/redo seems to work on a per-page level only (?!?!). Meaning, I can't undo past the point where I switched pages. That's super weird.
> 
> It looks like a new bug and more critical than the one in this issue, checking.
> 
> > it would undo the last actual action, and automatically jump to the page of concern.
> 
> That's how it should be happening currently (well, was, before the new bug), however, this behavior (not having page switch as a separate entry) causes some unexpected happenings (see the video in the description of #1030).
> 
> For example, if the user makes a change, then clicks around between Pages and then clicks Undo, the initial Page is restored + the change undone at the same time, so the user might not even know that something changed back on the Page.
> 
> One suggestion was that if the user clicks `Undo` (e.g. after clicking between pages), first, the relevant page to the previous page would show and then, the next `Undo` would actually make the change.
> 
> Thoughts?

I'm trying to grasp my head around this, but here's the behavior I'd expect:

1. I create a second page, add a new image, then resize the image.
2. I do undo once: The resize is undone, I'm still on the page 2, as the element of concern was the image on page 2.
3. I do undo twice: The image I added to page 2 is deleted, I'm still on page 2, as the element of concern was the image (doesn't matter that it is gone now - that change happened on page 2)
4. I undo thrice: Page 2 is deleted, and I jump back to page 1.

**Comment by miina** [comment]
> I'm trying to grasp my head around this, but here's the behavior I'd expect:
>- I create a second page, add a new image, then resize the image.
>- I do undo once: The resize is undone, I'm still on the page 2, as the element of concern was the image on page 2.
>- I do undo twice: The image I added to page 2 is deleted, I'm still on page 2, as the element of concern was the image (doesn't matter that it is gone now - that change happened on page 2)
>- I undo thrice: Page 2 is deleted, and I jump back to page 1.

Yep, that all makes sense!

What would you expect in case of the following:
- The user has 3 pages
- The user adds an image to the 1st page.
- The user clicks on the 2nd page
- The user clicks on the 3rd page
- The user clicks Undo

Would you expect to jump to the 1st page, already blank and without the image (since the action of adding an image was reverted by clicking "Undo")?

**Comment by pbakaus** [comment]
> What would you expect in case of the following:
> 
> * The user has 3 pages
> * The user adds an image to the 1st page.
> * The user clicks on the 2nd page
> * The user clicks on the 3rd page
> * The user clicks Undo
> 
> Would you expect to jump to the 1st page, already blank and without the image (since the action of adding an image was reverted by clicking "Undo")?

Yep, that's what I would expect. I can definitely see how that might confuse people, but I'd say let's implement this way for now, and let's closely monitor user feedback. We can change this in the future.

File: assets/src/edit-story/app/history/useHistoryReducer.js [hunk 1]
```diff
@@ -42,9 +42,35 @@ const reducer = (size) => (state, { type, payload }) => {
         );
 
         if (isReplay) {
+          const currentEntry = state.entries[state.offset];
```
Comment (miina) [inline assets/src/edit-story/app/history/useHistoryReducer.js]: @barklund 
The logic is rewritten based on [Paul's comment](https://github.com/google/web-stories-wp/pull/1065#issuecomment-611904360).

Haven't written the tests yet since would be good to get some feedback first.

Ignoring the current page of the original entry seemed to be the cleanest way to achieve always landing on the page where the recent history action happened, this, however, will override the `replayState` if the originally attempted replay didn't have the "correct" current page saved.

Thoughts?

File: assets/src/edit-story/app/history/useHistoryReducer.js [hunk 2]
```diff
@@ -42,9 +42,35 @@ const reducer = (size) => (state, { type, payload }) => {
...
+          // If a page has changed and it was not an added page, and if the page is about to change with replay,
+          // Ensure the user stays on the page where the latest change happened.
+          if (
+            currentEntry.pages !== state.replayState.pages &&
+            currentEntry.pages.length === state.replayState.pages.length &&
+            currentEntry.current !== state.replayState.current
+          ) {
+            const changedPage = currentEntry.pages.filter((page, index) => {
+              return page !== state.replayState.pages[index];
+            });
```
Comment (barklund) [inline assets/src/edit-story/app/history/useHistoryReducer.js]:
```suggestion
            const changedPage = currentEntry.pages.find((page, index) => page !== state.replayState.pages[index]);
```

File: assets/src/edit-story/app/history/useHistoryReducer.js [hunk 3]
```diff
@@ -42,9 +42,35 @@ const reducer = (size) => (state, { type, payload }) => {
...
+            // If a changed page was found.
+            if (changedPage.length === 1) {
+              // Ensure we stay on the changed page by overriding the previously saved current page.
+              const current = changedPage[0].id;
```
Comment (barklund) [inline assets/src/edit-story/app/history/useHistoryReducer.js]:
```suggestion
            if (changedPage) {
              // Ensure we stay on the changed page by overriding the previously saved current page.
              const current = changedPage.id;
```

**Review by barklund — APPROVED** [review]
It's a bit messy rewriting history like that - almost Orwellian 😉.

But as it works, let's keep it for now.

**Edit**: you can ignore my suggestions as they don't consider the case where there's more than one changed page. More than one changed page will only happen if pages are reordered though.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: It should only do the thing if there was only one page changed, thus the check for the length.

Comment (barklund) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: I think I got a little confused by the variable being named in singular while being an array. But that's a i tiny nit, so I'm good.

**Review by barklund — APPROVED** [review]
Works for me.

**Comment by miina** [comment]
> It's a bit messy rewriting history like that

It's rewriting the history only in this very specific case when the page is changing with Undo/Redo but should stay on the same page. I was wondering initially if we should always get the current page dynamically and not save it to the history at all, however, the one case where rewriting is needed is not that common. Not sure.
Thoughts on always getting the current page dynamically vs addressing an edge case separately?

File: assets/src/edit-story/app/history/useHistoryReducer.js [hunk 4]
```diff
@@ -42,9 +42,35 @@ const reducer = (size) => (state, { type, payload }) => {
...
+              const replayState = { ...state.replayState, current };
+              const entries = state.entries;
+              Object.assign([], entries, { [offset]: replayState });
```
Comment (dvoytenko) [inline assets/src/edit-story/app/history/useHistoryReducer.js]: What's the meaning of this line?

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 1 above)
Comment (dvoytenko) [inline assets/src/edit-story/app/history/useHistoryReducer.js]: Not very familiar with history system, so apologies if I'm wildly off base. But the bug describes the problem with UNDO, while the fix here is for the `ADD_ENTRY`?

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Overall, this looks all good (just two questions). Let's confirm the path first. But then we should also add a unit test or two.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 4 above)
Comment (miina) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: Oh!
Unless that was a philosophical question then this line seems to have no meaning and should be removed.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: When replay is happening, `ADD_ENTRY` is triggered as well, which will then check if it's a replay or actually adding a new entry.

Dynamically assigning the page in `REPLAY` would give `false` for `isReplay` in `ADD_ENTRY` (as far as I understand) and create a new entry even if it shouldn't.

I guess that by name doing all this in `REPLAY` is more logical when reading the code, I could def look into it to check if that would work out well.

Thoughts, @barklund ?

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 4 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: That's what I though. Unless you actually wanted to merge new `[offset]` value. Then it'd have to be rewritten.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 1 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: I think this is very confusing. Ideally we would not trigger `ADD_ENTRY` in replay. E.g. maybe in our side effect we can skip it somehow and do all the work in the actual replying reducer?

I think that'd mean that [here](https://github.com/google/web-stories-wp/blob/47663f405f36f1466248db2341817645ef10c1fa/assets/src/edit-story/app/story/effects/useHistoryEntry.js#L40), we'd need add `isReplaying` boolean to the deps and call `appendToHistory()` only when `isReplaying === false`.

Comment (miina) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: Hmm, looks like currently the offset is also set in the `ADD_ENTRY` although I suppose it should be done in `REPLAY` then.

File: assets/src/edit-story/app/story/effects/useHistoryEntry.js [hunk 5]
```diff
@@ -27,25 +27,34 @@ import { useHistory } from '../../';
...
-    appendToHistory({
-      story,
-      current: currentPageIndexRef.current,
-      selection: selectedElementIdsRef.current,
-      pages,
-      capabilities,
-    });
-  }, [capabilities, story, pages, appendToHistory]);
+    // If the change was applied by replay, clear the replay flag.
+    if (replayStateRef.current) {
```
Comment (miina) [inline assets/src/edit-story/app/story/effects/useHistoryEntry.js]: @barklund @dvoytenko This now keeps the `appendToHistory` true to its name by having a separate action for clearing the `replayState` and doing appending only if it actually appends.

An alternative to this change would be keeping the logic as it was before and instead, rename `ADD_ENTRY` to something more accurate, e.g. `REGISTER_STATE_CHANGE` or something similar -- which reflects more accurately the previous logic.

Let me know your thoughts.

File: assets/src/edit-story/app/history/test/reducer.js [hunk 6]
```diff
@@ -137,6 +137,14 @@ describe('reducer', () => {
 
       expect(result.replayState).toBeNull();
     });
+
+    it('should not modify the state is replayState is not set', () => {
```
Comment (swissspidy) [inline assets/src/edit-story/app/history/test/reducer.js]:
```suggestion
    it('should not modify the state if replayState is not set', () => {
```

File: assets/src/edit-story/app/history/test/reducer.js [hunk 7]
```diff
@@ -0,0 +1,250 @@
...
+        versionNumber: 1,
+      };
+
+      const result = reducer(initialState, {
+        type: CLEAR_HISTORY,
+      });
+
+      Object.keys(result).forEach((k) => {
+        expect(result[k]).toStrictEqual(EMPTY_STATE[k]);
+      });
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: Couldn't this be done with a regular `.toMatchObject`?

**Review by barklund — DISMISSED** [review]
Great tests and and acceptable result.

Technically I don't feel that any inside knowledge about what actually constitutes a history state belongs inside the history provider (it was meant to be generalized history provider not specific to a story), but for now it's an okay solution.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: So, the history provider is a little complex. A successful replay consists of two things happening in order:

* First a `REPLAY` request asking the history provider to tell you, what was in a previous (or future) history state relative to the current offset.
* Second, an `ADD_ENTRY` event with the **exact same state** as was returned by the `REPLAY` event (not returned though, but set in another object).

It is this object equality that is used to recognize, that replay has actually been effectuated in the history consumer and wasn't ignored.

The underlying idea is, that the history provider cannot force the consumer (here: the story provider) to go to a certain state, it can only ask it to try to, and then when the story provider (the history consumer) confirms this state is now the current state by calling `ADD_ENTRY`, only then does the history provider recognize, that the replay event was successful (by updating `offset`).

`ADD_ENTRY` could be renamed to `SET_CURRENT_STATE` or similar to clear up this minor confusion. `ADD_ENTRY` doesn't actually necessarily add an entry, it just says "this is my current state" and the history provider reacts accordingly (either confirming a successful replay or adding it as a new entry).

File: assets/src/edit-story/app/history/test/reducer.js (hunk 7 above)
Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js]: Yes, it can! Changed.

File: assets/src/edit-story/app/history/useHistoryReducer.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/app/history/useHistoryReducer.js]: @barklund: I'm personally more in favor of just changing the name (as also suggested below) instead of `useHistoryEntry` having to be aware and decide if to add an entry or clear the `replayState`. It feels like that shouldn't be a concern for `useHistoryEntry` which is basically just reacting to any relevant change.

Happy to change that part of the logic back and just adjust the name to be more accurate if everyone else is OK with it!

Thoughts, @dvoytenko?

File: assets/src/edit-story/app/story/effects/useHistoryEntry.js (hunk 5 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/story/effects/useHistoryEntry.js]: I definitely like this way since it's more explicit and less ambiguous w.r.t. add vs replay. However, I'm still not quiet clear w.r.t.

1. Why do we need to have `replayStateRef` for this? E.g. why can't this just be part of the history state `isReplay`. I.e. no matter how time we'd apply the replay - it will always be the same, right?
2. Why do we need `clearReplayState`?

**Review by dvoytenko — DISMISSED** [review]

File: assets/src/edit-story/app/story/effects/useHistoryEntry.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/app/story/effects/useHistoryEntry.js]: 1. Using `replayStateRef` to avoid triggering the effect due to the changes of `replayState`. `replayState` is currently like `isReplay` -- if there is an ongoing replay, then `replayState` is truthy, if there isn't, then it's `null`. `replayState` is perhaps not the best naming since it's (in the current implementation) showing the replay pending to be applied, not the static replay that was applied.
The offset reflects the entry that is currently active.
2. `clearReplayState` is used when the replay was already replayed and there is no ongoing replay happening. If we would not clear it out then `appendToHistory` would never be reached since the `replayState` would always be truthy.

Perhaps it would make more sense if `replayState` would be renamed to `replayInProcess` or something similar. Thoughts?

Comment (barklund) [reply assets/src/edit-story/app/story/effects/useHistoryEntry.js]: ~`requestedState` could also work. It's like asking for an old revision and getting it returned (but not touching current state) - and then latter in an unrelated event saying "restore state to this old revision, that you gave me".~ EDIT: Realizing everything has changed, this doesn't apply.

Comment (barklund) [reply assets/src/edit-story/app/story/effects/useHistoryEntry.js]: Hm, now replay is a single step process, right? That kind of changes it a lot compared to before.

The reason for the two step process was, that `useHistoryEntry` always just reported the current state to the history provider ignoring whether it was a replay or not. I thought that made the nicest and cleanest api in the history consumer and made "replay or not" an internal detail of the history provider

Now the two things are very tightly coupled and the story provider and history provider knows a lot of details about each other. The separation of concerns is not at all clear anymore, and basically the two things could just straight up merge, as neither can be used without being used **directly** with the other.

Before there were only two interactions between the two:

1. When history says state changes, story changes to whatever history says.
1. When story changes, story reports the change to history.

That's it! That was the entire interface and I actually spend quite some time making such a simple interface work. None of those involve any details about replay, pages, story contents or anything else. There was no interdependency between those, and you could have taken the history provider and apply it to the dashboard or a completely different project and it would still work. Also, you could have exchanged the history provider for some dummy, that only had the current state (if you wanted to save memory on mobile devices by not having history e.g.) and the story provider would work happily without history actually doing anything.

Neither of those things are possible now. The two are tightly coupled and interdependent.

It might work "simpler" at first, but it's a lot more complex to maintain and it's a lot more fragile to changes in the future. If we change how current page works, we suddenly need to change how the history provider works?

I'm not keen on these changes - taking two separate concerns and mashing them together like this is not good software design. IMHO.

**Review by barklund — COMMENTED** [review]
I'm not a big fan of where this is going. Where taking two big chunks of code and making them _more_ interdependent? That's the wrong direction!

File: assets/src/edit-story/app/story/effects/useHistoryEntry.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/app/story/effects/useHistoryEntry.js]: > Hm, now replay is a single step process, right?

Well, it's still two-step process -- the first step is setting the replay and the second step is clearing the replay -- it's just split up now and the history user has to execute the steps instead of this happening internally.

I agree that it was simpler before -- there was either a request for a replay or a reaction to state changes, history would then know what to do internally. It was definitely convenient that the history users didn't have to be aware of the internal life of the history, whereas now they do need to know when to clear replay and when to add an entry.

It does seem that the original naming needs improving (`ADD_ENTRY` and `replayState` specifically, e.g to `SET_CURRENT_ENTRY` and to `requestEntry` respectively, maybe also `appendToHistory` could be replaced with something like `sendStateChangeToHistory`), and perhaps a design doc would be helpful here, however, the original logic makes more sense to me as well.

**Comment by dvoytenko** [comment]
Ok, I apologize for maybe confusing things. Generally, @barklund has a clearer view of this system and I'd rather defer to him. Maybe we should discuss it online, but my intuition simply was that we sort of have "push" vs "replace" operations in the history and it'd be good to (a) make them explicit, (b) make them cleanly separated. The "replace" (replay) can only be done via API: undo and redo. The "push" is done for everything else, except undo/redo. Is my understanding here wrong?

**Comment by barklund** [comment]
> The "replace" (replay) can only be done via API: undo and redo. The "push" is done for everything else, except undo/redo. Is my understanding here wrong?

The "push" always happens when the state changes, regardless of it changing from a user interaction or a replay event. The "push" is actively used by the history provider to validate, that the history consumer has correctly replayed the old state. The consumer has no idea that it has just replayed an old state at this point.

**Comment by miina** [comment]
@barklund @dvoytenko 

The previous logic is now restored with changed naming instead for better accuracy, PTAL if it's more clear this way.

File: assets/src/edit-story/app/history/historyProvider.js [hunk 8]
```diff
@@ -30,8 +30,9 @@ import Context from './context';
 
 function HistoryProvider({ children, size }) {
   const {
-    replayState,
-    appendToHistory,
+    requestedState,
+    clearReplayState,
```
Comment (dvoytenko) [inline assets/src/edit-story/app/history/historyProvider.js]: Is this gone now?

**Review by dvoytenko — COMMENTED** [review]
Ok. This looks good to me then. I'll leave the final approval to @barklund

File: assets/src/edit-story/app/history/historyProvider.js (hunk 8 above)
Comment (miina) [reply assets/src/edit-story/app/history/historyProvider.js]: Ah, right, left-over. Removing.

File: assets/src/edit-story/app/history/test/reducer.js [hunk 9]
```diff
@@ -0,0 +1,273 @@
...
+  it('should throw error if unknown action given', () => {
+    expect(() =>
+      reducer(EMPTY_STATE, {
+        type: 'UNKNOWN_ACTION',
+        payload: {},
+      })
+    ).toThrow(/Unknown history reducer action: UNKNOWN_ACTION/i);
+  });
+
+  describe('addEntry', () => {
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: Well, it's not called `addEntry` anymore ;)

File: assets/src/edit-story/app/history/test/reducer.js [hunk 10]
```diff
@@ -0,0 +1,273 @@
...
+        entries: [{ id: 1 }],
+        offset: 2,
+      };
+      const newEntry = { id: 2 };
+      const result = reducer(initialState, {
+        type: SET_CURRENT_STATE,
+        payload: newEntry,
+      });
+
+      expect(result.versionNumber).toStrictEqual(4);
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js:86]: I think we just want to check, that it's greater than 3 - we don't really care how much, as long as it's ever-increasing.

File: assets/src/edit-story/app/history/test/reducer.js [hunk 11]
```diff
@@ -0,0 +1,273 @@
...
+        requestedState,
+      };
+
+      const result = reducer(initialState, {
+        type: SET_CURRENT_STATE,
+        payload: requestedState,
+      });
+
+      expect(result.requestedState).toBeNull();
+    });
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: I'd combine this to a single test - and also in that test verify, that the list of entries is not growing (the replayed state is not added as a new state).

File: assets/src/edit-story/app/history/test/reducer.js [hunk 12]
```diff
@@ -0,0 +1,273 @@
...
+
+    it('should set replay the current page relevant to the latest replayed change', () => {
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: What's the purpose of this test again?

File: assets/src/edit-story/app/history/test/reducer.js [hunk 13]
```diff
@@ -0,0 +1,273 @@
...
+        payload: requestedState,
+      });
+
+      expect(result.requestedState).toBeNull();
+      expect(result.offset).toStrictEqual(1);
+    });
+  });
+
+  describe('clearHistory', () => {
+    it('should set initial state when clearing history', () => {
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: Given the test content, it's setting an empty state, not initial state, no?

File: assets/src/edit-story/app/history/test/reducer.js [hunk 14]
```diff
@@ -0,0 +1,273 @@
...
+        payload: 2,
+      });
+
+      expect(result1.versionNumber).toStrictEqual(5);
+
+      const result2 = reducer(initialState, {
+        type: REPLAY,
+        payload: 5,
+      });
+      expect(result2.versionNumber).toStrictEqual(2);
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js:256]: Why is version number reduced here? Do we use the version number like that?

**Review by barklund — COMMENTED** [review]
A few comments on tests, otherwise looks good and thorough!

File: assets/src/edit-story/app/history/test/reducer.js (hunk 12 above)
Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js]: To test dynamically setting the current page so that the user would always stay on the page where the relevant change happened.

E.g. if the user is on page 1, then goes to page 2, makes a change, and clicks undo, even though the previous replay state has current: 1, we'll display 2 dynamically for staying on the same page.

This test basically tests that this would actually happen.

File: assets/src/edit-story/app/history/test/reducer.js (hunk 14 above)
Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js:256]: Yes, the version number is adjusted when undo/redo happens -- otherwise, the `versionNumber` would not be really useful. The `versionNumber` was added in #877, however the #877 was not a complete implementation -- it did not consider the undo/redo at all which still allowed the user leave without notice from unsaved state. `versionNumber` was adjusted in #1361 to also consider undo/redo.

File: assets/src/edit-story/app/history/test/reducer.js (hunk 10 above)
Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js:86]: Doesn't harm to check for exact version though -- e.g. to ensure it's not running more than once for some reason in the future. Thoughts?

Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js:86]: Well, I suppose that this test would not discover it anyway ;)

Anyway -- since it's expected to increase by exactly 1 in this case then probably doesn't harm to test exactly that, too.

File: assets/src/edit-story/app/history/test/reducer.js (hunk 12 above)
Comment (barklund) [reply assets/src/edit-story/app/history/test/reducer.js]: It's just that the test description is hard to read. Maybe some missing words or maybe some half-completed editing?

File: assets/src/edit-story/app/history/test/reducer.js (hunk 14 above)
Comment (barklund) [reply assets/src/edit-story/app/history/test/reducer.js:256]: Isn't `versionNumber` only used to check, if there's a new version of history? It's simple a _"if version number changed, something has changed"_ check?

- Is it ever used as a number anywhere?
- Who checks the actual value of it?
- Does anyone check if it's bigger than, lower than or equal to something anywhere?

Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js:256]: > Isn't versionNumber only used to check, if there's a new version of history? It's simple a "if version number changed, something has changed" check?

It was like that, however, it wasn't working as expected when using undo-redo. For example.
1. User does something
2. User Saves
3. User clicks "Undo"

-> It used to show as if there were no changes with the original implementation in #877 since with undo and redo the version number was not adjusted. However, actually there are new changes -- compared to the saved version.

> Does anyone check if it's bigger than, lower than or equal to something anywhere?

Yes:
https://github.com/google/web-stories-wp/blob/37fa4af305141754fc34271a1852ce6b9487f538/assets/src/edit-story/app/history/historyProvider.js#L53-L55

File: assets/src/edit-story/app/history/test/reducer.js (hunk 12 above)
Comment (miina) [reply assets/src/edit-story/app/history/test/reducer.js]: Oops, the description is very confusing indeed. Changed now in fb0b4539.

**Comment by miina** [comment]
@barklund All the comments should be addressed now, please re-review when you have time.

File: assets/src/edit-story/app/history/test/reducer.js [hunk 15]
```diff
@@ -0,0 +1,259 @@
...
+      expect(result.entries[1].id).toStrictEqual(3);
+      expect(result.entries[0].id).toStrictEqual(4);
+    });
+
+    it('should set correct state values when adding new entry', () => {
+      const initialState = {
+        ...EMPTY_STATE,
+        versionNumber: 3,
+        entries: [{ id: 1 }],
+        offset: 2,
```
Comment (barklund) [inline assets/src/edit-story/app/history/test/reducer.js]: This is a non-sensical setup, no? Offset 2, but only 1 state in history? I know it's not relevant for this test, but it seems to be an unreachable state?

File: assets/src/edit-story/app/history/useHistoryReducer.js [hunk 16]
```diff
@@ -19,63 +19,15 @@
...
+ */
+import reducer, {
+  SET_CURRENT_STATE,
+  CLEAR_HISTORY,
+  REPLAY,
+  EMPTY_STATE,
+} from './reducer';
 
 function useHistoryReducer(size) {
   // State has 3 parts:
```
Comment (barklund) [inline assets/src/edit-story/app/history/useHistoryReducer.js]: Well, not anymore. But again, a minor detail.

**Review by barklund — APPROVED** [review]
Looks good to me. Just two micro-nits, but good to merge!
