### PR TITLE
Reduced delay before displaying clone when dragging from library

### LINKED ISSUE #6027: Dragging from library doesn't respond instantly
## Bug Description
Originally reported by Paul:
"try dragging a picture, and release right away, then drag again...every second drag doesn't register."

## Expected Behaviour
When dragging from the library, the dragging should start immediately.

## Steps to Reproduce
1. Open Media tab in the library
2. Drag and release quickly multiple times in a row -- see the image not always being visually dragged.

## Screenshots
dragging

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

What is says in the title.

## User-facing changes

Notice the delay before the clone shows before and after:

| Before | After |
|-|-|
| drag-slow-before | drag-slow-after |

Notice what happens for a quick drag-and-hold slightly off the original location before and after as well:

| Before | After |
|-|-|
| drag-fast-before | drag-fast-after |

### QA

This PR can be tested by following these steps:

1. Drag an image from the local library and observe how quickly the dragged clone appears (much faster than before - 50ms versus 300ms).

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6027

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 1]
```diff
@@ -158,7 +158,7 @@ function LibraryMoveable({
     // Don't display the clone right away since otherwise it will be triggered for a click as well.
     if (
       cloneRef.current &&
-      inputEvent.timeStamp - eventTracker.current.timeStamp > 300
+      inputEvent.timeStamp - eventTracker.current.timeStamp > 50
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: I think `50` might be a bit too low value, when I click an image "lazily" using a mouse, then sometimes nothing seems to happen, in practice, a clone is displayed on top of the image for a split second but it doesn't insert an image since the dragging logic was triggered. This should probably stay a bit higher, e.g. `100`.

Perhaps we should add here a distance tracker as well? E.g. if the mouse has moved for more than 1-2 pixels in both directions, only then start the dragging (so, a combination of time + distance to determine as elsewhere in the code, similar to the `isMouseUpAClick` util):
https://github.com/google/web-stories-wp/blob/491a4156770e081eea177c1b2b0e46a446cd5710/assets/src/edit-story/utils/isMouseUpAClick.js#L32-L34

Edit: Maybe the distance tracker is even much more relevant for the case of library and we should only use that 🤔

Comment (barklund) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js]: Ah yes, I'll rename that utility function and use that to see whether it's a drag or not. Completely forgot about that one - thanks!

File: assets/src/edit-story/utils/areEventsDragging.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+/**
+ * Determine if two mouse events are part of a dragging action or not.
+ *
+ * It can be any two mouse event such as down and up or dragstart and drag.
+ *
+ * @param {Object} firstEvent   First mouse event object.
+ * @param {Object} secondEvent  Second mouse event object.
+ * @return {boolean} Returns true iff the events are considered part of dragging
+ */
+function areEventsDragging(firstEvent, secondEvent) {
```
Comment (miina) [inline assets/src/edit-story/utils/areEventsDragging.js:26]: Hm, maybe `isDragEvent` or something like that? `areEventsDragging` would mean that the events are dragging which feels a bit confusing. Basically we're determining here if the event should be considered dragging or not. Thoughts?

**Review by miina — APPROVED** [review]
Works so much better now.

Had a suggestion to change the naming of the util but otherwise lgtm!

File: assets/src/edit-story/utils/areEventsDragging.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/utils/areEventsDragging.js:26]: Yeah, I struggled a lot with naming this one. First I called it `isDragging` but that conflicted with local variables all over. And it's not about whether one event is a drag event, but whether the two events, seen in sequence, indicates that the gesture is a drag gesture.

Maybe `isDragGesture` is a better name then, as it describes the overall action taken by the user rather than any individual event? Or even `isPartOfDragGesture`? Or actually as we're testing two events: `arePartsOfDragGesture`, but that's quite a mouthful.

Comment (miina) [reply assets/src/edit-story/utils/areEventsDragging.js:26]: It can still be considered one event that's being determined to be dragging or not, it's just determined looking at the other event, too (dragging itself consists of different events anyway).

We discussed the naming a long time ago as well with Dima and at that point, `isMouseUpAClick` came up as the one that was the easiest to understand since the idea was that after a mouseup, it's determined if it was a click or not.

If you feel like this should be changed now, I'd vote for `isDragEvent` or `isDragGesture` -- since independent of what the input is and what we're doing inside, the goal is to figure out if what's happening is dragging or not. Thoughts?
