### PR TITLE
Dashboard: Fix conflicting min-width

### LINKED ISSUE #6689: Dashboard: Content below header, above grid not resizing right
## Bug Description

The filter bar with results listed is not resizing correctly with the rest of the page. 

Screen Shot 2021-03-09 at 1 16 50 PM

## Expected Behaviour

Content should remain justified. 
Search should have an enforced larger min-width. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

The issue identified in bug bash on Tuesday was that between 1020 and 1000 or so, a 20px ish difference in viewport width, the dashboard `bodyViewOptions` wasn't in sync with the rest of the page. Turns out that that container wasn't really the problem. This PR is to fix the inconsistency in the min width that was causing this difference in justification. 

## Summary
Consolidates where width is getting forced to 1098px in the dashboard. Small improvement to util for grid to let calculation be aware of the actual grid space regardless of window space.

## Relevant Technical Choices

- Gut old detail view gutter component, that isn't in use and I was cleaning up to make sense of the issue. 
- Move forced width minimum to the highest level of the dashboard possible so that everything inside the dashboard is aware of it. When the dashboard hits 1098px it will not shrink past this. This width is based on the entire viewport, so it's inclusive of whatever the wordPress menu is doing.  
- The hamburger button that controls the toggle of the dashboard side nav was using deprecated media queries that was getting it out of sync with the new min width stuff
- Tweak to how the current "breakpoint" in the util to figure out responsive grid size. If our min width is 1098px and our ref that tells us how much of that space belongs to the dashboard and is available for the grid, but our min width is getting locked in at 1098px  and our window.innerWidth is actually larger than that, the grid gets all weird. 

## User-facing changes

The right edge of content of the dashboard should now always be aligned. 

This is how it is on staging, as reported during bugbash: 

https://user-images.githubusercontent.com/10720454/110826150-05baf600-8252-11eb-947c-c5b1bbfb7b29.mp4

This is the update - focus on the right edge, where the filtering dropdown is and the line of stories in the grid. 

https://user-images.githubusercontent.com/10720454/110823836-b5db2f80-824f-11eb-8e08-0149b4396456.mp4

https://user-images.githubusercontent.com/10720454/110823840-b70c5c80-824f-11eb-9a8e-c2de803c8bbf.mp4

## Testing Instructions

Resize the dashboard and see the page respond. The story previews sometimes have a little delay because they are recalculating but they should adjust and the right line should be consistent. This is only an issue on 'my stories' since it's the only view currently with a sort.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6689

### CODE REVIEW

**Review by embarks — APPROVED** [review]
THANK YOU for the explanation and removing the dead code. It looks good to me, any reason it's a Draft?

**Comment by samwhale** [comment]
I think I'm still seeing it 🤔 This is with my wordpress nav expanded, I see the filter bar in the grid shrink past the `My Stories` title bar from 1120px to 1098px

thing

**Comment by BrittanyIRL** [comment]
I'm keeping this a draft for a bit to see if we can't figure out a more robust responsive solution to the header. The reason the small gap between header and the rest of the page surfaces for like 20px worth or resizing around 1120px to 1098px is because the search input's min width is longer than the available page. At 1098px the minwidth kicks in so it fixes itself.  

This is only a solution for english translations and dashboards that have smaller numbers of stories. If the pills to filter were to get longer this issue would be more apparent. 

I think we should consider allowing the header contents to wrap when content needs to for it to remain readable. This would enable us to have a min width on the search that's usable and filters that will be easy to read in whatever translation. 

This PR does solve some loose threads of the min width for the nav hamburger button getting exposed at the proper time and proper resize of story previews, so if the header wrapping starts to feel like scope creep we can separate it. I just would rather it not get lost. 
Screen Shot 2021-03-11 at 5 05 10 PM

File: assets/src/dashboard/utils/usePagePreviewSize.js [hunk 1]
```diff
@@ -101,23 +101,27 @@ const sizeFromWidth = (
 };
 
 const getContainerWidth = (windowWidth) => {
-  return windowWidth > MIN_DASHBOARD_WIDTH ? windowWidth : MIN_DASHBOARD_WIDTH;
+  // Because the dashboard has a min width (MIN_DASHBOARD_WIDTH) check to see if that min should be used or the actual space of the dashboard
+  const isWindowSmallerThanMinDashboardWidth =
+    window.innerWidth < MIN_DASHBOARD_WIDTH;
+  return isWindowSmallerThanMinDashboardWidth
+    ? MIN_DASHBOARD_WIDTH
+    : windowWidth;
```
Comment (maxyinger) [inline assets/src/dashboard/utils/usePagePreviewSize.js:109]: Looks like a good use case for `window.matchMedia()`

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

**Review by maxyinger — APPROVED** [review]
lgtm

**Comment by BrittanyIRL** [comment]
> I think we should consider allowing the header contents to wrap when content needs to for it to remain readable. This would enable us to have a min width on the search that's usable and filters that will be easy to read in whatever translation.

After talking to design, adding in the collapse of the header here by tweaking how padding and margin apply to the spacing of the header. This fixes the weird 20px gap between the header and the rest of the page seen between 1120px and 1098px

File: assets/src/dashboard/utils/usePagePreviewSize.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/utils/usePagePreviewSize.js:109]: TIL! thanks, i'll implement this on Monday!

**Comment by samwhale** [comment]
It's perfect 😍 image

**Review by samwhale — APPROVED** [review]

File: assets/src/dashboard/utils/usePagePreviewSize.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/utils/usePagePreviewSize.js:109]: Spent a little time reworking the hook for this and I don't think we should replace our current resize hook with this because limiting to use `.matchMedia` doesn't allow for the dynamic resize we need for larger viewports, it just kicks in for screens smaller than our min width. Perhaps something to circle back to another time, for now I think what we have is ok.

Comment (maxyinger) [reply assets/src/dashboard/utils/usePagePreviewSize.js:109]: ooh yeaup. good call. sounds good 👍

**Comment by BrittanyIRL** [comment]
With the collapse of the header as space changes it'll look like this: 

https://user-images.githubusercontent.com/10720454/111226220-0929e680-859e-11eb-8e03-3b2112d6ca79.mp4


https://user-images.githubusercontent.com/10720454/111226230-0cbd6d80-859e-11eb-9ba1-40bc07d56317.mp4
