### PR TITLE
Bug: Fix stickers horizontal drag handle

### LINKED ISSUE #7164: Sticker object drag handle doesn't do anything
## Bug Description

Selecting and moving a sticker's drag handle doesn't do anything.

## Expected Behaviour

It should alter the presentation of the sticker

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Noticed while working with stickers. Although we're only using the diagonal render directions for stickers, the edges of the selection box are still draggable. It was noticed that the horizontal edge dragging/resizing behavior didn't alter the sticker, this is to fix that.

## Summary
Maintains aspect ratio when doing vertical or horizontal resizing on sticker selection moveable box.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
now the sticker should get larger while respecting aspect ratio if you're doing solely horizontal resizing on it.

https://user-images.githubusercontent.com/35983235/131393897-0f9729d5-c344-43de-a0e9-4c6eed771f4b.mp4

## Testing Instructions
- Open the editor
- Open up the shapes & stickers panel in the library
- Add a sticker to your story and resize
- see that no matter how you resize it (horizontally, vertically or diagonally) the sticker maintains aspect ratio while resizing.
- Verify that it works for multi-selection too

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7164

### CODE REVIEW

File: packages/story-editor/src/components/canvas/singleSelectionMoveable/useResize.js [hunk 1]
```diff
@@ -176,7 +176,7 @@ function useSingleSelectionResize({
     onResize,
     onResizeStart,
     onResizeEnd,
-    keepRatio: isResizingFromCorner,
+    keepRatio: isResizingFromCorner || selectedElement?.type === 'sticker',
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/canvas/singleSelectionMoveable/useResize.js:179]: 🤝

**Review by BrittanyIRL — APPROVED** [review]
LGTM! Glad this was an easy fix.

**Review by miina — APPROVED** [review]
