### PR TITLE
E2E Tests: Add tests for deleting/renaming/duplicating stories

### LINKED ISSUE #5043: E2E Tests: Story Actions on Dashboard
## Feature Description

To avoid regressions like #5020 and #5031 we should add e2e tests, as flagged by @swissspidy 

Let's add e2e tests for these actions

* Delete story
* Rename story
* Duplicate story

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by amovar18**
## Context

This PR addresses the issue where e2e tests for actions:
1. Delete story
2. Rename story
3. Duplicate story

Above tests were requested to avoid regressions.

## Summary
This PR has 3 files which will test the 3 dashboard actions individually.

## Testing Instructions
- [x] This is a non-user-facing change and requires no QA
This PR can be tested by following these steps:

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes [#5043](https://github.com/google/web-stories-wp/issues/5043)

### CODE REVIEW

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    await publishStory();
+    await visitDashboard();
+
+    await expect(page).toMatchElement('h2', { text: 'Dashboard' });
+    await page.hover('div[data-testid^=story-grid-item]');
+    const story = await page.evaluate(
+      'document.querySelector("div[data-testid^=story-grid-item]").getAttribute("data-testid")'
+    );
+    //need to get story id to click on the context menu of the story
+    const storyId = story.split('-');
```
Comment (BrittanyIRL) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: Definitely works as is, but you could isolate the id here and not have to specify which index it is on line 43 
`story.split('-')[3]`

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    const [deleteMenuButton] = await page.$x(
+      "//button[contains(.,'Delete Story')]"
+    );
+    await page.waitForTimeout(100);
+    await deleteMenuButton.click();
+    const [deleteButton] = await page.$x("//button[text()='Delete']");
+    await deleteButton.click();
+    await expect(page).not.toMatchElement('h3', {
+      text: 'Delete this story',
+    });
```
Comment (BrittanyIRL) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: What do you think about after this confirming that the story is gone by looking for the matching story title?

**Review by BrittanyIRL — COMMENTED** [review]
Thanks for jumping into this, @amovar18

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js (hunk 2 above)
Comment (amovar18) [reply packages/e2e-tests/src/specs/dashboard/deleteStory.js]: @BrittanyIRL yes I am deleting the story after that I am checking that the story should not exist by looking for matching story title. I guess it would perform correctly since there is only one story being created in this test.

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+ * External dependencies
+ */
+import {
+  createNewStory,
+  publishStory,
+  visitDashboard,
+  insertStoryTitle,
+} from '@web-stories-wp/e2e-test-utils';
+
+describe('Stories Dashboard', () => {
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: I feel like we could just combine all three tests into 1 file, e.g. `specs/dashboard/myStories.js`.

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+  it('should delete story', async () => {
+    //need to create new story as all stories are deleted before test runs.
+    await createNewStory();
+    await insertStoryTitle('Delete this story');
+    await publishStory();
+    await visitDashboard();
+
+    await expect(page).toMatchElement('h2', { text: 'Dashboard' });
+    await page.hover('div[data-testid^=story-grid-item]');
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: Maybe selecting based on the `aria-label` is a bit more specific / self-documenting? Since there could be multiple grid items on the page.

`page.hover('[role="listitem"][aria-label="Details about Delete this story"]')`

WDYT?

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+    const story = await page.evaluate(
+      'document.querySelector("div[data-testid^=story-grid-item]").getAttribute("data-testid")'
+    );
+    //need to get story id to click on the context menu of the story
+    const contextMenuId = story.split('-');
+    const storyId = contextMenuId[3];
+    //contextMenuId= ['story', 'grid', 'item', 'storyId']
+    await expect(page).toClick(
+      `button[data-testid="story-context-button-${storyId}"]`
+    );
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: Could simplify like this:

```js
await expect(page).toClick('button[aria-label="Context menu for Delete this story"]');
```

This has the advantage that we don't have to fiddle with testid, `page.evaluate`, etc. and can do it in a a more self-documenting way that also better reflects what a user would do.

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+    const [deleteMenuButton] = await page.$x(
+      "//button[contains(.,'Delete Story')]"
+    );
+    await page.waitForTimeout(100);
+    await deleteMenuButton.click();
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: Could simplify:

```js
await expect(page).toClick('button', { text: 'Delete Story' });
```

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+    const [deleteButton] = await page.$x("//button[text()='Delete']");
+    await deleteButton.click();
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/deleteStory.js]: Similarly, could use `expect(page).toClick()` here.

File: packages/e2e-tests/src/specs/dashboard/deleteStory.js (hunk 4 above)
Comment (amovar18) [reply packages/e2e-tests/src/specs/dashboard/deleteStory.js]: @swissspidy  yes we could do that too, but i dont think there will be multiple grid items on the page since before every test all the stories are deleted. Still would make this change to make it simple

File: packages/e2e-tests/src/specs/dashboard/myStories.js [hunk 8]
```diff
@@ -0,0 +1,95 @@
+/*
+ * Copyright 2020 Google LLC
```
Comment (BrittanyIRL) [inline packages/e2e-tests/src/specs/dashboard/myStories.js]:
```suggestion
 * Copyright 2021 Google LLC
```

File: packages/e2e-tests/src/specs/dashboard/myStories.js [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+  insertStoryTitle,
+} from '@web-stories-wp/e2e-test-utils';
+
+describe('Stories Dashboard', () => {
+  it('should delete story', async () => {
+    //need to create new story as all stories are deleted before test runs.
+    await createNewStory();
+    await insertStoryTitle('Delete this story');
+    await publishStory();
+    await visitDashboard();
```
Comment (BrittanyIRL) [inline packages/e2e-tests/src/specs/dashboard/myStories.js]: you can simplify this since it's the same series before each action you're testing by adding 
```
beforeEach(async () => {
    await createNewStory();
    await insertStoryTitle('Delete this story');
    await publishStory();
    await visitDashboard();
}); 
```

then you can don't need to have it within each individual test.

I know you're naming the story specific to the action but if you wanted to, you could make it something generic, store it as a constant and then reference that value where you're finding by labels with some interpolation to decrease potential typos. 

So like: 

`const storyName = 'Test Story';`

`'[role="listitem"][aria-label="Details about ${storyName}"]'`

**Review by BrittanyIRL — COMMENTED** [review]
Looks good! Left a few suggestions to clean this up further but really appreciate the effort.

**Review by swissspidy — APPROVED** [review]
