### PR TITLE
Editor: Fixed empty story state when there is an attachment

### LINKED ISSUE #10700: A page with Page Attachment should not be considered empty state
## Bug Description

Originally reported by @samwhale 

A Page with Page Attachment (CTA) is currently considered empty state.

## Expected Behaviour
If a Story has 1 page and that Page has a Page Attachment with no other changes, it is currently considered empty state and displays the empty state menu.
If Page Attachment is present, it shouldn't be considered empty state.

## Steps to Reproduce
1. Add a new Story
2. Select Background from the Layer Panel
3. Add Page Attachment
4. See the empty state UX still present.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by marianakyrkosh**
## Context

An empty Story text and icon should disappear when an attachment is added to a Story.

## Summary

Currently, even if the Page Attachment is added, the Empty State helper is still shown — but it shouldn’t, since the Page is already changed really.

You can add the Page Attachment locally by:
1. Create a new story.
2. Click on the “Background” list item in the right bottom corner of the screen (The one under “Layers”).
3. Now the Page gets selected and you should be able to see the “Page Attachment” section in the right-side panel.

## User-facing changes

Before: 
Screenshot 2022-03-09 at 15 32 19
After:

image

## Testing Instructions

This PR can be tested by following these steps:

1. Create 1 Story.
2. Add a link in the Attachments.
3. Empty story text and icon should disappear.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10700

### CODE REVIEW

File: packages/story-editor/src/app/story/utils/isEmptyStory.js [hunk 1]
```diff
@@ -40,6 +40,11 @@ const isEmptyStory = (pages) => {
     return false;
   }
 
+  const hasNoAttachment = pages[0].pageAttachment?.length === 0;
```
Comment (miina) [inline packages/story-editor/src/app/story/utils/isEmptyStory.js]: Nit: we usually prefer "positive" variable names for readability, e.g.
`const hasPageAttachment` and then just check for `if (hasPageAttachment)`.

The page attachment is actually an object that consists of different props, e.g. if we remove a Page Attachment from a Page, it will still stay as a prop but with empty values:
```
"pageAttachment": {
        "url": "",
        "icon": "",
        "needsProxy": false
      }
```

It can also be `null` if not set.

We should probably check here for the length of the `url` instead.

Comment (merapi) [reply packages/story-editor/src/app/story/utils/isEmptyStory.js]: ➕  for the "positive" variable names (in most cases), I'm first to blame here (see `hasNoExtraElements` and `hasNoBackgroundMedia` although this one is tricky)

image

File: packages/story-editor/src/app/story/utils/test/isEmptyStory.js [hunk 2]
```diff
@@ -54,4 +54,12 @@ describe('isEmptyStory', () => {
     storyWithExtraElements[0].elements.push({});
     expect(isEmptyStory(storyWithExtraElements)).toBeFalse();
   });
+
+  it('should not count story with an attachment as empty', () => {
+    const storyWithAttachment = [createPage()];
+    const testUrl = 'https://testurl.com';
+
+    storyWithAttachment[0].pageAttachemnt.push({ url: testUrl });
+    expect(isEmptyStory(storyWithAttachment)).toBeFalse();
```
Comment (miina) [inline packages/story-editor/src/app/story/utils/test/isEmptyStory.js:64]: Would be good to test that it returns `true` correctly as well, for example when `pageAttachment` is `null` (or not set) and also when it was set but then deleted, then the `pageAttachment` value would be:
```
    {
        url: '',
        icon: '',
        needsProxy: false,
      }
```

**Review by barklund — APPROVED** [review]
Pending the extra tests @miina asked for, this looks good to me! :shipit:

File: packages/story-editor/src/app/story/utils/test/isEmptyStory.js (hunk 2 above)
Comment (marianakyrkosh) [reply packages/story-editor/src/app/story/utils/test/isEmptyStory.js:64]: @miina thanks for the suggestion! I've added the tests

**Review by miina — APPROVED** [review]
