### PR TITLE
Dashboard: Remove Saved Templates Related Code

### LINKED ISSUE #8746: Dashboard: Clean up or Delete  "Saved Templates"
With grid updates for performance improvements to My Stories and Explore Templates, the saved templates view is increasingly obsolete. It doesn't make sense to take time to keep this up to date if we're not going to use it any time soon.

As it is not coming up soon on the roadmap, I think we should just clear out the code for it in the dashboard. When we are ready to implement, very little of the current code is relevant anymore so we'd really not be missing anything.

If this is wrong and we are wanting to implement this feature soon then instead we should take the time to catch the components up.

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Last summer we had scaffolded out the 'saved templates' view in the dashboard ahead of getting data flowing. There's still questions out about what all a saved template is and how to handle them. The dashboard has changed since then and maintaining this code is not worth it since it's out of date and getting saved templates working is not a current priority. At this point, it'll be easier to just add in what we need when we need it rather than try to update all of this.

## Summary

Remove all references to saved templates (bookmark, create template from story, in progress story actions) in dashboard as well as 3 defunct experiments (`enableInProgressStoryActions` and `enableBookmarkActions`, `enableInProgressViews`). 

Now the only reason we need `@web-stories-wp/story-editor` is to create a story from a template (`getStoryPropsToSave`). 

## Relevant Technical Choices

Just removing relevant code. 

## To-do

None.

## User-facing changes

Just removing experiments.

## Testing Instructions

Just some regression testing here. Make sure that all actions expected are present in the dashboard for stories and templates, and when you go to `wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/saved-templates` (saved templates route) you just get the same empty page you would if you went anywhere without a defined route in the dashboard.

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8746

### CODE REVIEW

**Comment by swissspidy** [comment]
> Now the only reason we need `@web-stories-wp/story-editor` is to create a story from a template (`getStoryPropsToSave`).

We're so close! #8778 and/or #7196 will help us eliminate this one eventually.

File: includes/Experiments.php [hunk 1]
```diff
@@ -274,17 +252,6 @@ public function get_experiments(): array {
 				'description' => __( 'Enable in-progress template actions', 'web-stories' ),
 				'group'       => 'dashboard',
 			],
-			/**
-			 * Author: @brittanyirl
-			 * Issue: 2292
-			 * Creation date: 2020-06-11
-			 */
-			[
-				'name'        => 'enableBookmarkActions',
```
Comment (swissspidy) [inline includes/Experiments.php:284]: Looks like we used that experiment name for a PHP unit test which now fails because it was removed 😅 

https://github.com/google/web-stories-wp/blob/64bc19d15741ec175ca7a8121ce2db8ad1153499/tests/phpunit/tests/Experiments.php#L237-L244

Can you update that test to use a name that still exists?

**Comment by swissspidy** [comment]
Some editor Karma tests seem to be failing? If they're flakey and completely unrelated, feel free to skip & file a ticket as usual.

**Comment by BrittanyIRL** [comment]
> Some editor Karma tests seem to be failing? If they're flakey and completely unrelated, feel free to skip & file a ticket as usual.

I hadn't actually seen this test fail until today. I'll check in with prometheus and see if something's up.

File: packages/dashboard/src/app/font/fontProvider.js [hunk 2]
```diff
@@ -1,96 +0,0 @@
...
- * External dependencies
- */
-import PropTypes from 'prop-types';
-import { useCallback, useEffect, useState } from '@web-stories-wp/react';
-import {
-  FontContext as Context,
-  useLoadFontFiles,
-} from '@web-stories-wp/story-editor';
-
-function FontProvider({ children }) {
```
Comment (samwhale) [inline packages/dashboard/src/app/font/fontProvider.js:27]: 🥳

File: packages/dashboard/src/types.js [hunk 3]
```diff
@@ -51,7 +49,7 @@ export const TemplatePropType = PropTypes.shape({
   id: PropTypes.number.isRequired,
   status: DashboardStatusesPropType,
   title: PropTypes.string.isRequired,
-  pages: PropTypes.arrayOf(StoryPropTypes.page),
+  pages: PropTypes.array,
```
Comment (samwhale) [inline packages/dashboard/src/types.js:52]: Did this type change?

**Review by samwhale — APPROVED** [review]
Awesome!

File: packages/dashboard/src/types.js (hunk 3 above)
Comment (BrittanyIRL) [reply packages/dashboard/src/types.js:52]: `pages` is just used to get the length of a template now.  I wanted to limit the imports of `@web-stories-wp/story-editor` so i opted to just swap it to an array since the content of that array is ditched in the serializer as soon as data's retrieved.

Comment (samwhale) [reply packages/dashboard/src/types.js:52]: 🤔 Probably not worth the trouble but maybe we should update that to `numPages`?

**Comment by spacedmonkey** [comment]
Wow the `chunk-getStoryPropsToSave` is massive. Can't wait for https://github.com/google/web-stories-wp/issues/8778

**Review by spacedmonkey — APPROVED** [review]

File: packages/dashboard/src/types.js (hunk 3 above)
Comment (BrittanyIRL) [reply packages/dashboard/src/types.js:52]: well we still need the pages so that we can generate stories from templates at this point.  I can add back in the dependency if this is confusing. it feels like maybe it's confusing given this thread. it just seemed redundant since it's not getting used in any component it's just getting passed.
