### PR TITLE
Media3P: Add hardening for missing media URLs

### LINKED ISSUE #12083: Media3P: GIFs Tab not working
## Bug Description

Something I noticed during yesterday's demo call and am still experiencing today: the GIF tab does not work.

There's some error loading the GIFs and unfortunately the error message is swallowed.

I suspect there's some error in `getGifResourceFromMedia3p` / `getResourceFromMedia3p` or similar, because the HTTP request is working just fine.

## Expected Behaviour

The GIF tab should work just fine

## Steps to Reproduce

1. Open editor
2. Go to third-party media tab
3. Go to GIFs tab
4. See error snackbar message

## Screenshots

Screenshot 2022-08-09 at 14 46 59

## Additional Context

- Plugin Version: 1.24.0-alpha
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by timarney**
## Context

The third part media / Gif tab is failing to load -- it throws a snackbar error.

## Summary

Updates `sortMediaBySize` to early return if media urls don't get passed to the parameters.

In this case after filtering we can end up with an empty array 
```
const webmSizes = sortMediaBySize(
    m,
    m.videoUrls.filter(({ mimeType }) => mimeType === 'image/webm')
  );
 ```
 
 causing the eventual width / height check to fail
 
 ```
originalWidth: mediaUrls[0].width,
originalHeight: mediaUrls[0].height,
 ```

See: https://github.com/GoogleForCreators/web-stories-wp/issues/12083#issuecomment-1209827399

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. "fresh load of the page" (full reload)
2. Visit the Gif tab
3. Scroll to load images - note the tab loads and doesn't throw an error.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

Added [error tracking](https://github.com/GoogleForCreators/web-stories-wp/pull/12091/files#diff-362408cc6041a2dba24390bc644b5653d35faa4539ea86ef2bbe33221797b9c0R102) for for fetch media 

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12083

### CODE REVIEW

File: packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js [hunk 1]
```diff
@@ -197,6 +197,10 @@ function getVideoUrls(m) {
 }
 
 function sortMediaBySize(m, mediaUrls) {
+  if (mediaUrls.length < 1) {
```
Comment (swissspidy) [inline packages/story-editor/src/app/media/utils/getResourceFromMedia3p.js:201]:
```suggestion
  // https://github.com/GoogleForCreators/web-stories-wp/issues/12083
  if (mediaUrls.length < 1) {
```

Otherwise this looks good 👍

**Comment by timarney** [comment]
@swissspidy added a [trackError](https://github.com/GoogleForCreators/web-stories-wp/pull/12091/commits/866d23b8c47b510f5bac28f758ae498b8784e4a9#diff-362408cc6041a2dba24390bc644b5653d35faa4539ea86ef2bbe33221797b9c0R103) to help surface anything that might come up in the future.

File: packages/story-editor/src/app/media/media3p/useFetchMediaEffect.js [hunk 2]
```diff
@@ -99,6 +100,9 @@ export default function useFetchMediaEffect({
           nextPageToken,
         });
       } catch (e) {
+        // eslint-disable-next-line no-console -- We want to surface this error.
+        console.error(e);
+        trackError('fetch_media', e.message);
```
Comment (swissspidy) [inline packages/story-editor/src/app/media/media3p/useFetchMediaEffect.js]:
```suggestion
        trackError('fetch_media3p', e.message);
```

**Review by swissspidy — APPROVED** [review]
Just one nit, otherwise LGTM
