### PR TITLE
Text style: adjust margin calculation

### LINKED ISSUE #9940: Text not adhering to line-height from version 1.15 onwards
## Bug Description

Text is not adhering to the set line-height from Web Stories version 1.15.0 onwards. This has been pointed out by a user of the plugin and confirmed with testing of my own. 

In the screenshots section you will see an image of versions 1.14 and 1.15.1 both using a 'Title 1' text box with a line-height value of 4 set.

## Expected Behaviour

Line height should display as seen in 1.14 screenshot. 

## Steps to Reproduce

1. While editing a story add a new text box to a page.
2. From the text options set a line-height value of 4.

## Screenshots

WS-line-height

## Additional Context

This is the behaviour as of version 1.15.0.

### PR DESCRIPTION
**Pull request by miina**
## Summary
15.1 introduced a regression where margin is not properly calculated when assigning line-height.

## Relevant Technical Choices
Margin was incorrectly calculated inside `generateParagraphTextStyle` (without units), and the generated `margin` was not actually used anywhere at all, and was always calculated again in `elementWithTextParagraphStyle`.

This PR calculates the margin correctly the first time, and removes the additional calculation from `elementWithTextParagraphStyle`.

## To-do

- [x] Additional tests

## User-facing changes

| Before | After |
|-------|-------|
| Screenshot 2021-12-09 at 13 10 21 | Screenshot 2021-12-09 at 13 08 48 |
## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a text element so that it would have one line only.
2. Add line-height, e.g. 4. Verify the text element looks similar to as it was before (line-height is not visibly applied).
3. Now make the text element two rows.
4. Verify that line-height is properly added between the two lines but not to the top and bottom of the element iself.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9940

### CODE REVIEW

File: packages/story-editor/src/elements/shared/index.js [hunk 1]
```diff
@@ -95,16 +96,13 @@ export const elementWithFont = css`
...
-    margin: ${-dataToEditorY(marginOffset / 2)}px 0;
-    padding: ${({ padding }) => padding || 0};
-    line-height: ${({ lineHeight }) => lineHeight};
-    text-align: ${({ textAlign }) => textAlign};
-    overflow-wrap: break-word;
-  `;
-};
+export const elementWithTextParagraphStyle = css`
+  margin: ${({ margin }) => margin};
+  padding: ${({ padding }) => padding || 0};
```
Comment (barklund) [inline packages/story-editor/src/elements/shared/index.js:101]: Margin doesn't need a fallback here as padding has?

**Review by Trapsta — APPROVED** [review]
✅   Line-height looks fine in both editor and preview

**Review by barklund — APPROVED** [review]
Looks good. Surprised that this bug snuck in there without anyone noticing.

File: packages/story-editor/src/elements/shared/index.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/elements/shared/index.js:101]: It shouldn't really since it's always calculated in the paragraph style generation, even if 0.
