### PR TITLE
Performance: Story carousel integrate with page canvas provider

### LINKED ISSUE #9958: Editor: Carousel thumbnails not consistently updating
There are a couple of issues I have been able to consistently create with the editor page thumbnail images. 

**Issue 1:** 
When first creating a new story you are given a blank page. If you add a new background image to that page the thumbnail image for the page below remains blank. If you then add a new page or duplicate that page then the page 1 thumbnail will stay blank until you click on it to go back to page 1 which then seems to refresh the thumbnail and the image shows. 

I presume that this should not be happening because from any newly added page after the first the thumbnail image updates straight after adding a background image to the page. 

**Issue 2:** 
The thumbnail image of a duplicated page reverts back to it's previous background image if it has been changed prior to duplicating the page once more. If you duplicate page 1 for page 2, update the page 2 background image and duplicate page 2 for page 3 then the thumbnail image for page 2 reverts back to the original image from the duplicated page 1.  

When going back to page 2 the background image is correct on the page but the thumbnail is wrong. If you double-click the background image on the page and move it slightly then the thumbnail corrects itself.

## Expected Behaviour

**Issue 1:** Background image added to page 1 should update on thumbnail image.

**Issue 2:** The page 2 thumbnail image does not revert back to the original duplicated image and remains as the updated background image.

## Steps to Reproduce

**Issue 1:** 
1. Create a new Web Story.
2. Add a background image to the first page.

**Issue 2:**
1. Create a New Story.
2. Add a Background image to page1.
3. Duplicate page 1 to create page 2.
4. Change the Background image for page 2.
5. Duplicate page 2 to create page 3.

## Video recording

The following video shows both issues which I am able to reproduce consistently:
https://user-images.githubusercontent.com/91896826/145550008-71b9f115-e295-40fb-9df3-7e8577047085.mp4

### LINKED ISSUE #10822: Performance: Story carousel integrate with page canvas provider
Following [this ticket 10730](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/googleforcreators/web-stories-wp/10730) We should have infrastructure, to integrate the generation of story pages for page carousels into the page canvas provider. 

Should help cut down on expensive calls to generate images. Should also be pretty simple to integrate with the background task api like the current behavior.

More context: https://github.com/googleforcreators/web-stories-wp/issues/9749

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Part of this perf epic #11121 

## Summary
Updates page previews to just use the page canvas provider for obtaining generated images.

Should also fix this issue as a byproduct of integrating the new approach:
#9958 

## Relevant Technical Choices
Utilizes the background task queue and integrates canvas generation with smart colors. So... if the smart colors generate a canvas for their task, the carousel can use it. Also, there should never be more than one background task request to generate a page canvas at a time.

Also updates all image thumbnails to just use an image if it's available. This should work fine in both the grid & the checklist and should come at no additional cost. Should honestly help by cutting down on number of rendered nodes in both those places

## To-do
NA

## User-facing changes
Fixes stale carousel image issue

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

(original bug reproduction scenario)

**Issue 1:**

1. Create a new Web Story.
2. Add a background image to the first page.

**Issue 2:**

1. Create a New Story.
2. Add a Background image to page1.
3. Duplicate page 1 to create page 2.
4. Change the Background image for page 2.
5. Duplicate page 2 to create page 3.

**Other Testing Area**
This PR also updates the thumbnails in the story grid view & the checklist, so ensure that you don't see regressions in any of those places either.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10822 
Fixes #9958

### CODE REVIEW

File: packages/story-editor/src/utils/storyPageToCanvas.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ async function storyPageToCanvas(page, { width = 400, ...options }) {
   const canvas = await htmlToImage.toCanvas(node, {
     ...options,
     fontEmbedCss: '',
-    pixelRatio: 1,
+    pixelRatio: window.devicePixelRatio,
```
Comment (swissspidy) [inline packages/story-editor/src/utils/storyPageToCanvas.js]: This is the default value: https://github.com/bubkoo/html-to-image/blob/30000f088ef94878e2fa67dfcf89a09c13a0e14c/src/util.ts#L140

Comment (maxyinger) [reply packages/story-editor/src/utils/storyPageToCanvas.js]: ahh. right on. will update

Comment (BrittanyIRL) [reply packages/story-editor/src/utils/storyPageToCanvas.js]: so it should be `pixelRatio: window.devicePixelRatio || 1`?

File: packages/story-editor/src/components/footer/pagepreview/index.js [hunk 2]
```diff
@@ -92,61 +89,52 @@ const PreviewWrapper = styled.div`
...
+  position: absolute;
   width: 100%;
+  left: 0;
+
+  // image will always be vertically centered
+  // so we don't need to alter height of image
+  // when it's in the fullbleed ratio and the
+  // thumbnail is in the smaller ratio
+  top: 50%;
+  transform: translateY(-50%);
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/footer/pagepreview/index.js:103]: 👍

File: packages/story-editor/src/utils/storyPageToCanvas.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/utils/storyPageToCanvas.js]: Since that is the default, my understanding is that this line can be removed

Comment (maxyinger) [reply packages/story-editor/src/utils/storyPageToCanvas.js]: we can just omit passing in the `pixelRatio` arg completely cus the package defaults to the behavior we want

**Review by BrittanyIRL — APPROVED** [review]
This is so great, I'm glad that you made time to make this update after it was talked about so long ago and then put aside. Getting to just reuse the page canvas provider here is awesome. 

Working locally for me.

I just triggered a rerun for the[ 1 failing karma test ](https://github.com/GoogleForCreators/web-stories-wp/runs/5856833275?check_suite_focus=true#step:7:773)but there might be something that needs updating there?  As well as in unit tests,[ here](https://github.com/GoogleForCreators/web-stories-wp/runs/5856829572?check_suite_focus=true#step:6:71).

**Comment by swissspidy** [comment]
The one thing that stands out in the Percy snapshots is that all the carousel images now have a focus outline, because that's what the active pages have on the canvas. Sounds like a bug to me.
Otherwise the carousel images now finally look correct 🎉

**Review by merapi — APPROVED** [review]
It's great you did it. I can't see any issues with thumbnails generation now 🧙🏻🪄

BTW: Does anybody know why we crop the thumbnail like this:
image

**Comment by littlemilkstudio** [comment]
@merapi 
> BTW: Does anybody know why we crop the thumbnail like this:

I think just to match the ratio that the story thumbnails display at in the dashboard & out in the wild? @BrittanyIRL & @swissspidy might be able to elaborate on this better 🤷

**Comment by merapi** [comment]
Most devices look like this:
image

In the Dashboard, we have a poster image, not a thumbnail generated from the story, right?
I will forward this to UX.

**Review by samwhale — APPROVED** [review]

File: packages/story-editor/src/app/pageCanvas/usePageCanvas.js [hunk 3]
```diff
@@ -23,8 +23,8 @@ import { useContextSelector, identity } from '@googleforcreators/react';
  */
 import Context from './context';
 
-function useCalculateAccessibleTextColors(selector) {
+function usePageCanvas(selector) {
   return useContextSelector(Context, selector ?? identity);
 }
 
-export default useCalculateAccessibleTextColors;
+export default usePageCanvas;
```
Comment (samwhale) [inline packages/story-editor/src/app/pageCanvas/usePageCanvas.js:30]: haha nice catch

**Review by samwhale — COMMENTED** [review]
Nice this is way simpler. Good job dude!

**Comment by BrittanyIRL** [comment]
> @merapi
> 
> > BTW: Does anybody know why we crop the thumbnail like this:
> 
> I think just to match the ratio that the story thumbnails display at in the dashboard & out in the wild? @BrittanyIRL & @swissspidy might be able to elaborate on this better 🤷

yeah dashboard is poster images so this would be separate. Seems like the top and bottom safe area aren't getting cut on the thumbnail vs in the preview.

**Comment by agingoldseco** [comment]
> > @merapi
> > > BTW: Does anybody know why we crop the thumbnail like this:
> > 
> > 
> > I think just to match the ratio that the story thumbnails display at in the dashboard & out in the wild? @BrittanyIRL & @swissspidy might be able to elaborate on this better 🤷
> 
> yeah dashboard is poster images so this would be separate. Seems like the top and bottom safe area aren't getting cut on the thumbnail vs in the preview.

I think this cropping maximizes the amount of useful detail you see in the thumbnails to differentiate pages while saving some space at the bottom of the screen by not including the very top and bottom. It makes sense to me.

File: packages/story-editor/src/app/pageCanvas/usePageCanvas.js (hunk 3 above)
Comment (maxyinger) [reply packages/story-editor/src/app/pageCanvas/usePageCanvas.js:30]: 🙈

Comment (maxyinger) [reply packages/story-editor/src/app/pageCanvas/usePageCanvas.js:30]: 🤫

**Comment by merapi** [comment]
> I think this cropping maximizes the amount of useful detail you see in the thumbnails to differentiate pages while saving some space at the bottom of the screen by not including the very top and bottom. It makes sense to me.

@agingoldseco Alright, if we ever decide to show full canvas - we don't have to sacrifice the vertical space, we can just make the thumbnails a little bit more narrow to keep the same ratio, like this:
thumbs-ratio

File: packages/story-editor/src/components/footer/pagepreview/index.js (hunk 2 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/footer/pagepreview/index.js:103]: great comment

**Review by BrookeGraham — APPROVED** [review]

File: packages/story-editor/src/utils/storyPageToCanvas.js [hunk 4]
```diff
@@ -43,7 +43,6 @@ async function storyPageToCanvas(page, { width = 400, ...options }) {
   const canvas = await htmlToImage.toCanvas(node, {
     ...options,
     fontEmbedCss: '',
-    pixelRatio: 1,
```
Comment (barklund) [inline packages/story-editor/src/utils/storyPageToCanvas.js:46]: Hm, I think we needed this one for some reason. Or is it removed because it has now been included up-stream in the original library? CC @merapi

Comment (BrittanyIRL) [reply packages/story-editor/src/utils/storyPageToCanvas.js:46]: For reference: https://github.com/GoogleForCreators/web-stories-wp/pull/11207#discussion_r844165130

Comment (maxyinger) [reply packages/story-editor/src/utils/storyPageToCanvas.js:46]: we want `window.devicePixelRatio || 1` here so the images we generate don't look blurry in the grid or thumbnails, this is the what the library defaults to so we can omit it. Currently this is only used for thumbnails and smart colors and doesn't cause regressions in either.
