### PR TITLE
Media: Fix conflict with Safe SVG plugin

### LINKED ISSUE #6003: SVG Upload: Conflict with Safe SVG
## Bug Description

It was mentioned by rtCamp folks that there are issues when both our SVG experiment and the Safe SVG plugin are active.

Let's verify this and ensure that there are no conflicts.

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: 
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Both [safe svg](https://github.com/darylldoyle/safe-svg) and [svg support](https://wordpress.org/plugins/svg-support/) do not filter `mime_types`, which makes uploading via the editor fail. 

## Testing Instructions

---

Fixes #6003

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
3 test failures: https://github.com/google/web-stories-wp/pull/6017/checks?check_run_id=1751273079#step:15:47

File: includes/SVG.php [hunk 1]
```diff
@@ -161,7 +162,7 @@ public function mime_types_add_svg( array $mime_types ) {
 		// allow SVG files.
 		$mime_types['svg'] = self::MIME_TYPE;
 
-		return $mime_types;
+		return array_unique( $mime_types );
```
Comment (spacedmonkey) [inline includes/SVG.php:165]: Not required, but just nice not to have two of the same in this array.

File: includes/SVG.php [hunk 2]
```diff
@@ -105,6 +105,7 @@ public function init() {
 
 		// Check if svg uploads, already enabled.
 		if ( $this->svg_already_enabled() ) {
+			add_filter( 'mime_types', [ $this, 'mime_types_add_svg' ] );
```
Comment (swissspidy) [inline includes/SVG.php:108]: Just to clarify, we only want to add this filter if SVG uploads are already enabled by some other plugin?

Comment (spacedmonkey) [reply includes/SVG.php:108]: Basically, we are adding this to make sure that mime_type is in this list, safe svg does not add it, it only adds it to upload_types. So just add it to be safe and if it is already there, the array unique will remove the duplicate.

Comment (swissspidy) [reply includes/SVG.php:108]: Now we're only calling `add_filter( 'mime_types', [ $this, 'mime_types_add_svg' ] );` if Safe SVG is active, but not when it is absent.

So if Safe SVG is absent, mime type list will not be filtered. Is that expected?

Comment (spacedmonkey) [reply includes/SVG.php:108]: So if `svg_already_enabled` is true then we add mime_types just to be sure. We can't add it before the check, because it would make the check always pass. This is an ordering issue, which is why the test were before. 

This line is still place. 
https://github.com/google/web-stories-wp/blob/ea1da0345f3e87f0092645b0c35dc0fdd0f8661d/includes/SVG.php#L111

Comment (swissspidy) [reply includes/SVG.php:108]: I guess I am confused then about the purpose of `upload_mimes` vs `mime_types`

Comment (spacedmonkey) [reply includes/SVG.php:108]: I think it is confusing, as it is confusing in core. From what I can workout, `upload_mimes` are just support mime types you are allowed to upload. Adding to `mime_types` also seems to also add it to [get_allowed_mime_types](https://github.com/WordPress/wordpress-develop/blob/176a1f53f04cde92e7297b5214c03beb9e2ba5c8/src/wp-includes/functions.php#L3241-L3262) function. 

For some reason safe svg doesn't add to `mime_types` just some reason `upload_mimes`.  The reason it is adding after the check on `svg_already_enabled`, adding before, will make the `svg_already_enabled` check always return as true. 

TDLR, safe svg is doing something weird, this is a workaround for it.
