### PR TITLE
Shape previews in the layers panel

### LINKED ISSUE #735: Layers panel: the shape element should show the mask outline/fill preview and label should reflect the name
## Bug Description

Currently, the layer display just says "Shape" and the label is some generic shape message.

## Expected Behaviour

1. The layer icon should be "shape" icon.
2. The layer display should show the actual shape (possibly with fill and shadow for blending fills as we do for images now).
3. The label should reflect the shape/mask name. E.g. "Heart" and not just "Shape".

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @wassgha @pbakaus @barklund

### PR DESCRIPTION
**Pull request by wassgha**
Closes #735

Screen Shot 2020-03-30 at 12 28 55 AM

### Changes
- Shows the correct icon for shape layers
- Adds the shape's preview and name next to the icon

### CODE REVIEW

File: assets/src/edit-story/elements/shape/layer.js [hunk 1]
```diff
@@ -15,12 +15,76 @@
...
+
+function ShapeLayerContent({ element: { mask, backgroundColor } }) {
+  const maskDef = getMaskByType(mask.type);
+
+  const isTooBright = useMemo(() => {
+    const darkestDimension = Math.max.apply(
+      null,
+      Object.values(backgroundColor?.color || {})
+    );
+    return darkestDimension >= 230;
```
Comment (swissspidy) [inline assets/src/edit-story/elements/shape/layer.js]: Maybe define it as `const TOO_BRIGHT = 230` like in `visibleImage.js`? Otherwise we might miss one instance in case we'd have to change this value.

Or perhaps extract this function so it can be shared

File: assets/src/edit-story/elements/shape/layer.js [hunk 2]
```diff
@@ -15,12 +15,76 @@
...
+  }, [backgroundColor]);
+
+  return (
+    <Container>
+      <ShapePreview alt={maskDef.name}>
```
Comment (swissspidy) [inline assets/src/edit-story/elements/shape/layer.js]: I think we need to revisit the usage of `alt` for shape previews, `alt` on a `div` doesn't really do anything. Just saw that we do this in `ShapesPane` as well.

To properly describe inline SVGs we should use `<title>` within the `svg` element

**Review by swissspidy — APPROVED** [review]
Two nits, but otherwise LGTM

File: assets/src/edit-story/elements/shape/layer.js [hunk 3]
```diff
@@ -15,12 +15,76 @@
...
+
+const ShapePath = styled.path`
+  ${elementWithFillColor}
+`;
+
+function ShapeLayerContent({ element: { mask, backgroundColor } }) {
+  const maskDef = getMaskByType(mask.type);
+
+  const isTooBright = useMemo(() => {
+    const darkestDimension = Math.max.apply(
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/shape/layer.js]: This sounds like `lightestDimension`?

File: assets/src/edit-story/elements/shape/layer.js [hunk 4]
```diff
@@ -15,12 +15,76 @@
...
+      null,
+      Object.values(backgroundColor?.color || {})
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/shape/layer.js]: BTW, this includes `a` as well, I believe. Could you pls check if `a` is in 0-255 or 0-1 range? Also, I think a value close to `0` would also indicate a need for shadow.

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/elements/shape/layer.js (hunk 4 above)
Comment (wassgha) [reply assets/src/edit-story/elements/shape/layer.js]: Added a utility for getting brightness from any generic pattern, PTAL

**Comment by wassgha** [comment]
Added support for gradients which I noticed was missing, PTAL

Screen Shot 2020-03-30 at 3 24 26 PM

**Review by dvoytenko — APPROVED** [review]
