### PR TITLE
Make video poster generation more robust

### LINKED ISSUE #5190: Make video poster generation more robust
## Feature Description

Splitting this off from #5119. Video poster generation should be made more robust if the poster generation failed the first time around.

Needs investigation on why/where poster generation fails (timeouts maybe?) and how this can be mitigated (e.g. by a number of retries?)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Handles the race condition when user insert a newly upload video from the uploader.

## Relevant Technical Choices

Move the upload video posters logic from the uploader success listener to the onSelect listener on the `Insert into page` button.

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

1. On the left side bar, click on the `Upload` button.
2. Under `Upload files` tab, hit `Select Files`, select a video to upload.
3. Hit the button `Insert into page`. 
4. The video poster should always show up on the right side bar -> Accessibility.

---

Fixes #5190

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/media/local/mediaPane.js [hunk 1]
```diff
@@ -159,6 +167,9 @@ function MediaPane(props) {
         resource,
         mediaPickerEl.sizes?.medium?.url || mediaPickerEl.url
       );
+
+      // Update the video poster on the ride side bar (i.e. Accessibility)
```
Comment (swissspidy) [inline assets/src/edit-story/components/library/panes/media/local/mediaPane.js]:
```suggestion
      // Upload video poster and update media element afterwards,
      // so that the poster will correctly show up in places like the Accessibility panel.
```

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 2]
```diff
@@ -61,16 +57,16 @@ export default function useMediaPicker({
   });
   useEffect(() => {
     try {
+      // Handles the video processing logic from 3rd party.
```
Comment (swissspidy) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]:
```suggestion
      // Handles the video processing logic from WordPress.
```

**Review by swissspidy — APPROVED** [review]
Glad we were able to find the issue 🎉

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 3]
```diff
@@ -61,16 +57,16 @@ export default function useMediaPicker({
...
+      // The 'success' listener logic will be triggred once user uploaded a
+      // file from the uploader.
```
Comment (dreamofabear) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: "The Uploader.success callback is invoked when a user uploads a file."

Also please add details about the race condition for future reference. I.e. under what circumstances is it not called?

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js [hunk 4]
```diff
@@ -38,6 +38,10 @@ function useUploadVideoFrame({ updateMediaElement }) {
   }));
   const setProperties = useCallback(
     (id, properties) => {
+      // properties is a function in this case, which will carry the poster
+      // value in the return object.
+      // function updateElementsByResourceId is defined in
+      // reducers/updateElementsByResourceId.js
```
Comment (dreamofabear) [inline assets/src/edit-story/app/media/utils/useUploadVideoFrame.js]: This comment seems unnecessary.

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js [hunk 5]
```diff
@@ -38,6 +38,10 @@ function useUploadVideoFrame({ updateMediaElement }) {
   }));
   const setProperties = useCallback(
     (id, properties) => {
+      // properties is a function in this case, which will carry the poster
+      // value in the return object.
```
Comment (dreamofabear) [inline assets/src/edit-story/app/media/utils/useUploadVideoFrame.js]: I'm not sure what this is saying. `properties` is a function whose return value is the video poster image?

**Review by dreamofabear — COMMENTED** [review]
Nice sleuthing!

File: assets/src/edit-story/components/library/panes/media/local/mediaPane.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/library/panes/media/local/mediaPane.js]: Updated.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Updated.

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/app/media/utils/useUploadVideoFrame.js]: Sure, I will remove the first two lines, but I would prefer to keep the file pointer for the following engineers, as it will be hard to find without enough background knowledge.

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js (hunk 5 above)
Comment (zidianlyu) [reply assets/src/edit-story/app/media/utils/useUploadVideoFrame.js]: I am trying to describe this logic: 
```
({ resource }) => ({
        resource: {
          ...resource,
          posterId,
          poster,
          ...newSize,
        },
      })
```
as this is what properties really is😅. But I agree to remove these 2 lines of comments.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Updated the comment.

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js (hunk 4 above)
Comment (dreamofabear) [reply assets/src/edit-story/app/media/utils/useUploadVideoFrame.js]: Why was this hard to find? A simple text search in VSCode showed it.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 6]
```diff
@@ -61,16 +57,18 @@ export default function useMediaPicker({
   });
   useEffect(() => {
     try {
+      // Handles the video processing logic from WordPress.
+      // The Uploader.success callback is invoked when a user uploads a file.
+      // Race condition concern: please DO NOT upload video poster on this
+      // callback, becuase the video is not guarantee to be ready at the moment.
+      // We should only upload the video poster on the select event.
```
Comment (dreamofabear) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Let's make this race condition warning more generic (video posters is too specific).

"Race condition: the video content is not guaranteed to be available in this callback."

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 7]
```diff
@@ -99,6 +97,8 @@ export default function useMediaPicker({
     });
 
     // When an image is selected, run a callback.
+    // The onSelect logic is defined in mediaPane.js/onSelect, which handles the
+    // logic when user click on the button `Insert into page`.
```
Comment (dreamofabear) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: This is a confusing comment. Readers will wonder -- what does "onSelect" refer to?

A code pointer to mediaPane.js could be useful but it should be moved to the `Uploader.success` callback around line 65. Also use the full file path: `assets/src/edit-story/components/library/panes/media/local/mediaPane.js`.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 6 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Got it, updated.

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 7 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js:101]: Hmm...I am not sure why `the code pointer to mediaPane.js could be useful but it should be moved to the Uploader.success callback` as it is only related to the function `fileFrame.on('select',  ...)`

Comment (zidianlyu) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Got it.

**Review by dreamofabear — APPROVED** [review]
