### PR TITLE
Floating Menu: Color Opacity Focus

### LINKED ISSUE #11312: Floating Menu: Color Opacity Focus
## Bug Description

We had to get a little creative to make all of the floating menu items focusable. The result was a button to facilitate moving focus and not getting stuck in freeform inputs. The color opacity input proves a unique challenge because of its design. 

These are the 2 options initially found in #11273 
| | | 
| --- | --- | 
| Overriding width and wrapping around dash and input |  image | 
| Focus trap button wrapping only `OpacityInput` | Screen Shot 2022-04-19 at 3 27 42 PM | 

We want this though, it's just really hard to get the positioning and sizing right? I think fixing this is going to need to refactor the whole input. Need to make sure that any solution doesn't cause regression on the other use cases of color opacity.  
image

Relevant code is in `packages/story-editor/src/components/form/color/activeOpacity.js`

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by sblinde**
## Context

This PR should resolve an issue seen with the focus border around the color opacity in the design menus. 

## Relevant Technical Choices

Moved the `Space` out of the component and adjusted the width.

## User-facing changes

Before (image from original issue #11312):
Before Example Image

After:
Fix Image Example 1

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. On multiple browsers, please add a shape to the canvas area.
2. Click on the shape to see the floating menu.
3. Navigation through the floating menu (click on Opacity, click tab, and navigate through) and you should see the focus border around the opacity item look appropriately sized.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [X] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [X] I have tested this code to the best of my abilities
- [X] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [X] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11312

### CODE REVIEW

File: packages/story-editor/src/components/form/color/color.js [hunk 1]
```diff
@@ -131,6 +131,11 @@ const Color = forwardRef(function Color(
       ? TOOLTIP_PLACEMENT.BOTTOM
       : TOOLTIP_PLACEMENT.BOTTOM_START;
 
+  const Space = styled.div`
```
Comment (mflorida) [inline packages/story-editor/src/components/form/color/color.js]: This `styled.div` component should be defined outside of the `Color` component, otherwise a warning about 'dynamic' components shows in the browser console.

```
The component color__Space with the id of "color__Space-sc-c7i660-4" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
```
😶

Comment (sblinde) [reply packages/story-editor/src/components/form/color/color.js]: Ooh great feedback, thank you! I'll do just that!

**Review by mflorida — APPROVED** [review]
👊😎

**Review by mwritter — APPROVED** [review]
