### PR TITLE
Library: only render tabs when active

### LINKED ISSUE #4634: Library: Avoid rendering inactive tabs
## Bug Description

When opening the editor, we already load all text sets and templates (page layouts) despite those tabs not being open by default. That's **6MB** of data.

As per #4433, same goes for inactive media tabs. There's not much detail there but seems like a good performance win.

This also causes issues with tests. See #5945

## Expected Behaviour

Text sets and page layout chunks should only be loaded the first time they're being opened.

## Steps to Reproduce

1. Open Network tab in dev tools
1. Open the editor
2. Notice that all text sets and all templates are being loaded

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: macOS Catalina
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Context
- To enhance performance, do not execute the render of media, template, and text tabs.
- Can be tested by looking at the network tab. On main, the editor will load text set and template jsons before those tabs are selected. In this PR the editor does not load those until the tabs are selected.

## Summary
- add a reference to track which tabs have been rendered to determine when to render their content
- once the pane is rendered the first time, leave it rendered
- change the get text sets effect to check if the text pane has been rendered

## Relevant Technical Choices
- I only load the text sets once to reduce the network load. 
- Due to the high render time of the text sets, per Morten's comment on the ticket, we switch to manual activation for the tabs instead of selection follows focus if switching "over" the text tab (using keyboard) is too slow.
- However, from manual testing this seems to be faster

## To-do
- [x] fix unit tests

## User-facing changes
N/A

### QA
This is a performance enhancement.

- [ ] This is a non-user-facing change and requires no QA

1. Open a new story and observe the network tab in your inspector tools
2. Click on each of the library tabs
3. The templates and media should load (seen in network tab) after clicking on their respective library tabs
4. The templates and media should not re-load when clicking on the tabs a second time before refreshing
### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #4634

### CODE REVIEW

**Review by BrittanyIRL — APPROVED** [review]
looks good and works well!

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 1]
```diff
@@ -49,23 +49,40 @@ function LibraryProvider({ children }) {
...
   const insertElement = useInsertElement();
   const { insertTextSet, insertTextSetByOffset } = useInsertTextSet();
 
   const { showElementsTab } = useFeatures();
 
   // Order here is important, as it denotes the actual visual order of elements.
-  const tabs = useMemo(
-    () => [
+  const tabs = useMemo(() => {
+    return [
```
Comment (samwhale) [inline assets/src/edit-story/components/library/libraryProvider.js]: nit: we could keep this as an implicit return!

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 2]
```diff
@@ -49,23 +49,40 @@ function LibraryProvider({ children }) {
...
       SHAPES,
-      ...(showElementsTab ? [ELEMS] : []),
+      showElementsTab ? ELEMS : {},
       PAGE_LAYOUTS,
-    ],
-    [showElementsTab, tab]
-  );
+    ].reduce((accTabs, renderTab) => {
+      // for heavier tab content, avoid rendering the pane unless it is active
+      const isLazyTab = [MEDIA3P.id, TEXT.id, PAGE_LAYOUTS.id].includes(
```
Comment (samwhale) [inline assets/src/edit-story/components/library/libraryProvider.js]: 💭 nit: Maybe we should make `[MEDIA3P.id, TEXT.id, PAGE_LAYOUTS.id]` a global constant so we can keep a single source of truth and not re-create this every loop? It's not used anywhere else though so it's nbd

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 3]
```diff
@@ -49,23 +49,40 @@ function LibraryProvider({ children }) {
...
+
+      return renderTab.id
+        ? [
+            ...accTabs,
+            // remove the pane if it hasn't been rendered before or the tab is not active
+            isLazyTab && !isActiveTab && !hasBeenRendered
+              ? { id: renderTab.id, icon: renderTab.icon }
+              : renderTab,
+          ]
+        : accTabs;
```
Comment (samwhale) [inline assets/src/edit-story/components/library/libraryProvider.js]: fancy ✨

**Review by samwhale — APPROVED** [review]
This is excellent and very clever

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 4]
```diff
@@ -49,23 +49,40 @@ function LibraryProvider({ children }) {
...
-      ...(tab === TEXT.id ? [TEXT] : [{ icon: TextIcon, id: 'text' }]),
+      TEXT,
       SHAPES,
-      ...(showElementsTab ? [ELEMS] : []),
+      showElementsTab ? ELEMS : {},
       PAGE_LAYOUTS,
-    ],
-    [showElementsTab, tab]
-  );
+    ].reduce((accTabs, renderTab) => {
```
Comment (barklund) [inline assets/src/edit-story/components/library/libraryProvider.js]: Couldn't this be a `.map` instead? I don't really see the reduction that warrants a `.reduce`.

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 5]
```diff
@@ -49,23 +49,40 @@ function LibraryProvider({ children }) {
...
+      );
+      const isActiveTab = tab === renderTab.id;
+      const hasBeenRendered = renderedTabs.current[renderTab.id];
+
+      return renderTab.id
+        ? [
+            ...accTabs,
+            // remove the pane if it hasn't been rendered before or the tab is not active
+            isLazyTab && !isActiveTab && !hasBeenRendered
+              ? { id: renderTab.id, icon: renderTab.icon }
```
Comment (barklund) [inline assets/src/edit-story/components/library/libraryProvider.js]: I don't think we can render nothing though, as the tab still needs to refer to what it controls. But maybe we can create a dummy pane for the heavy panes if not rendered yet, so there's still a DOM element to point `aria-controls` to.

There's also a larger problem here with the tabs referring to themselves in `aria-controls`, but the same problem exists in main actually (should have been caught by AXE tests, but maybe they don't consider that an error):

Screen Shot 2021-02-18 at 15 50 35

Notice each tab has an `aria-controls` that refers to themselves. That's wrong. `aria-controls` must point to the `role="tabpanel"`, that they actually select.

So, we need all 5 panels to be in the DOM, but we can substitute for empty dummy panels for the heavy ones until activated.

**Review by barklund — COMMENTED** [review]
Looks good, but needs some aria fixes to be compliant.

File: assets/src/edit-story/components/library/libraryProvider.js (hunk 4 above)
Comment (embarks) [reply assets/src/edit-story/components/library/libraryProvider.js]: It could be a map but it would need a filter for tabs that are not feature-enabled, for example, like the elements tab. Before the array was statically defined and so things like the "Elements" tab would not be in the array like this:
```
SHAPES,
...(showElementsTab ? [ELEMS] : []),
PAGE_LAYOUTS
```

I liked this for its explicit reference to the tab order and the simple logical check for whether or not to include the tab. `.map.filter` is also explicit and maybe more readable, too, but with reduce I'm just iterating through the "tabs" array once to assign the content of the array in one callback. I chose that approach instead of repeating the way the text tab was conditionally rendered before:

```
...(tab === MEDIA3P.id ? [MEDIA3P] : [{ icon: Media3pIcon id: 'media3p' }]),
...(tab === TEXT.id ? [TEXT] : [{ icon: TextIcon, id: 'text' }])
```
etc.

So, I could do it with `.map.filter` or define it literally the way it was originally for the text pane if that's preferred. :)

Comment (embarks) [reply assets/src/edit-story/components/library/libraryProvider.js]:
```
[MEDIA, MEDIA3P, TEXT, SHAPES, showElementsTab && ELEMS, PAGE_LAYOUTS]
        .filter(Boolean)
        .map(...)
```
seems alright

File: assets/src/edit-story/components/library/libraryProvider.js (hunk 5 above)
Comment (embarks) [reply assets/src/edit-story/components/library/libraryProvider.js]: Great feedback, thank you. Now the aria-controls point to the tabpanels and I'm using the shared panel to create the empty panels.
Screen Shot 2021-02-19 at 11 23 48 AM

File: assets/src/edit-story/components/library/libraryProvider.js [hunk 6]
```diff
@@ -45,26 +46,37 @@ const PAGE_LAYOUTS = {
...
+    () =>
+      [MEDIA, MEDIA3P, TEXT, SHAPES, showElementsTab && ELEMS, PAGE_LAYOUTS]
+        .filter(Boolean)
+        .map(({ icon, Pane, id }) => {
+          const isLazyTab = LAZY_TABS.includes(id);
+          const isActiveTab = tab === id;
+          const hasBeenRendered = renderedTabs.current[id];
+          return isLazyTab && !isActiveTab && !hasBeenRendered
+            ? { id, icon, Pane: renderEmptyPane(id) }
+            : { id, icon, Pane };
```
Comment (barklund) [inline assets/src/edit-story/components/library/libraryProvider.js]: Excellent work here - just a minor suggestion to reduce duplicated code (and I **really** prefer positively named booleans):

```js
          const shouldRenderPane = !isLazyTab || isActiveTab || hasBeenRendered;
          return { id, icon, Pane: shouldRenderPane ? Pane : renderEmptyPane(id) };
```

**Review by barklund — APPROVED** [review]
🎉
