### PR TITLE
Fix duplicate fullbleed container landmark regions

### LINKED ISSUE #7578: Duplicate fullbleed container landmark regions
## Bug Description

On the canvas there are multiple containers in different sub trees with the same label: `[role=presentation][aria-label="Fullbleed area"]`

There might be others too beyond this one.

Generally speaking these should be unique on a page.

## Screenshots

Screenshot 2021-05-19 at 00 32 32

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

e2e accessibility check for unique landmarks had to be turned off because the fullbleed container was showing as duplicate. this fixes that and enables that rule. 

## Summary

Both the role of region and the aria-label of "fullbleed area" were hardcoded into the `PageArea` component.. Updated so that it can inherit a label to use on the fullbleed container which makes the implementations of the region unique. 

## User-facing changes

No user facing changes, if you run aXe in your dev tools you won't get a duplicate landmark region issue anymore.

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7578

### CODE REVIEW

File: packages/story-editor/src/components/canvas/framesLayer.js [hunk 1]
```diff
@@ -112,7 +112,15 @@ function FramesLayer() {
       aria-label={__('Frames layer', 'web-stories')}
     >
       {!isAnimating && (
-        <FramesPageArea onContextMenu={onOpenMenu} onScroll={onScroll}>
+        <FramesPageArea
+          role="region"
+          fullBleedContainerLabel={__(
```
Comment (miina) [inline packages/story-editor/src/components/canvas/framesLayer.js:116]: Should this be added for the Edit Layer as well?

**Review by miina — APPROVED** [review]
Thank you!

**Review by maxyinger — APPROVED** [review]

File: packages/e2e-tests/src/config/bootstrap.js [hunk 2]
```diff
@@ -221,7 +221,6 @@ async function runAxeTestsForStoriesEditor() {
       'color-contrast',
       // Because of multiple #_wpnonce elements.
       'duplicate-id',
-      'landmark-unique',
```
Comment (samwhale) [inline packages/e2e-tests/src/config/bootstrap.js:224]: 🔥

**Review by samwhale — APPROVED** [review]
Yay nice!!
