### PR TITLE
Fixed numeric sanitization logic so entering in values can be easier

### LINKED ISSUE #4595: Creator updating numerical entries are hindered by sanitization
## Bug Description

Currently, when a creator attempts to enter line-height manually (or any other number input), the sanitization starts working and it can be impossible to make corrections.

## Steps to Reproduce
1. Add a Text element
2. Resize the width to 300
3. Now try to delete the "3" in the width and replace it with "2"
4. See the sanitization getting in the way

Try the same with trying to change just the first number of the line-height (e.g. replacing "1" with "2" in "1.5")

## Screenshots
numbers

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

<!-- One or more bullet points for how to technically implement the feature. --

### LINKED ISSUE #4596: Line height can accept 2 decimal points
## Bug Description

I'm able to enter in values with 2 decimal in the line height input field. Steps to reproduce
1. enter a value
2. Select all
3. Type in value. Note that the previous value does not clear.

## Steps to Reproduce

1. I click to enter a value
2. I click again to change the value 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR removes validation from numeric input until the user manually triggers validation by: triggering `blur`, hitting `enter`, or hitting the `arrow up/down` keys.  If the user hits `esc` while editing a numeric field, the input value will revert to the last saved value.

NOTE: I'm holding off on writing tests, so the interactions can get approved.  Once approved, I'll write jest and karma tests to make sure our numeric interactions get coverage.

## User-facing changes

This PR affects all the numeric fields in the editor (e.g. Size & Position numerics inputs, text Style numeric inputs, etc...).

## Testing Instructions

1.) Open up a new or existing story in the Editor.
2.) Add a new element, or select an existing one to make active.
3.) Use the Style, Size & Position, and any other panel with numeric inputs, and type in anything you want and then trigger one of the saving/revert mechanism described below, confirm they work.  Confirm that you can type in anything in any way and if it ends up being valid... the value will be saved 😎 

- `Enter`: Validates and saves value.  If validation fails, reverts to previously saved value.
- `Esc`: Reverts value to previously saved value and removes focus from input.
- `Blur`: Validates and saves value.  If validation fails, reverts to previously saved value.
- `ArrowUp`/`ArrowDown`: Validates current value.  If validation fails, reverts to previously saved value and then increment/decrements value based on up/down arrows (also respects `alt` key for float numbers).

Fixes #4595
Fixes #4596 

## Screenshots

Type in anything:
type_in_anything

### CODE REVIEW

File: assets/src/edit-story/components/form/numeric.js [hunk 1]
```diff
@@ -160,42 +209,80 @@ function Numeric({
         value={
           isMultiple
             ? ''
-            : `${inputValue}${dot ? DECIMAL_POINT : ''}${focused ? '' : symbol}`
+            : `${inputValue.length > 0 ? inputValue : value}${
+                focused ? '' : symbol
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/form/numeric.js]: I noticed when typing before almost every time a character was typed the cursor would skip to the end of the input.  Wasn't really notice-able when typing from scratch, but modifying a number it was super apparent.

I was able to fix this by largely making `value` the source of truth.  Whenever we type something, `onChange` is called and the `value` that returns is what gets displayed.  However, for those moments that we have just a negative symbol ('-') or a bunch of zeroes, or some other input we don't yet want to parse, those values get stored locally in `inputValue`.  And once the input is parseable, then we parse it, send it down the `onChange` pipeline, reset `inputValue`, and then `value` returns to being the source of truth.

File: assets/src/edit-story/components/form/numeric.js [hunk 2]
```diff
@@ -140,6 +180,15 @@ function Numeric({
...
   const { focused, handleFocus, handleBlur } = useFocusAndSelect(ref);
 
+  useEffect(() => {
+    if (targetFormRef.current) {
+      submitForm(targetFormRef.current);
+      // Resetting to null after dispatch, it'll get
+      // re-assigned on component blur
+      targetFormRef.current = null;
+    }
+  }, [value]);
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/form/numeric.js]: In order to process a potential final update from `onBlur`,  have this useEffect that changes every time value changes from a call to `onChange`.  The targetFormRef only gets set within the blur method, so if it's set, that means we want to dispatch and then we immediately reset it so further updates won't trigger anything.

**Comment by carloskelly13** [comment]
So I think we might need to allow invalid values (or at least empty) as a ghost because I cannot backspace, aka clear, out the field to type something else. So if it's `300` I cannot backspace to put `100`. I have to select the text to put `300`.

Perhaps when typing in a value we see if it is valid, if so, apply it. Essentially there would be a state that stores what we see in the input, but then the last known value is either in the data model or another state that either gets updated when the visible input value is valid or onBlur if the input is invalid, we'd revert back to the last valid value.

File: assets/src/edit-story/components/form/numeric.js [hunk 3]
```diff
@@ -99,38 +99,84 @@ function Numeric({
...
-  useEffect(() => setInputValue(value), [value]);
+  const isIterimValue = useCallback(
+    (val) =>
+      // Allow a single "-" if negative values are allowed
+      (canBeNegative && val === '-') ||
+      // Allow string of 0s
+      /^[0]+$/.test(val) ||
+      // Allow starting and ending with decimal point if float
+      (float && (val.startsWith(DECIMAL_POINT) || val.endsWith(DECIMAL_POINT))),
+    [float, canBeNegative]
```
Comment (carloskelly13) [inline assets/src/edit-story/components/form/numeric.js]: I think here is where we'd want to allow an empty value as `interim` so we can fully backspace out the input.

File: assets/src/edit-story/components/form/numeric.js [hunk 4]
```diff
@@ -99,38 +99,84 @@ function Numeric({
...
+
+      const signedNumber = !canBeNegative
+        ? Math.abs(valueAsNumber)
+        : valueAsNumber;
+
+      return {
+        valueAsNumber,
+        signedNumber,
+        fixedPoint,
+      };
```
Comment (carloskelly13) [inline assets/src/edit-story/components/form/numeric.js]: If possible this feels like a function we could hoist and just pass in `float` and `canBeNegative` that way it's easier to test this in isolation. Also this is a lot of logic to memoize.

File: assets/src/edit-story/components/form/numeric.js (hunk 3 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: Good catch!  I think I have a way of getting this working again without introducing the other bugs the new pattern fixes 🤔

File: assets/src/edit-story/components/form/numeric.js (hunk 4 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: I can dig it, will hoooist it up!

File: assets/src/edit-story/components/form/numeric.js (hunk 3 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: Okay, I wanted to keep all the logic of `inputValue` and `value` clean, since I do believe it's working for all the other edge cases.  And I realized I could capture the specific state of a user deleting all the content by simply checking if `newValue`  (within the `onChange` handler) is empty or not.  If it's empty then we're in the "Empty" state, which _only_ changes display logic (not `inputValue` to `value` logic), and as soon as `newValue` has any value then the state becomes `Value` and everything works as expected... 

Here's a gif of all the delete and re-input action:
full_delete

**Comment by miina** [comment]
From testing:
In case of line-height, it doesn't seem to be possible to change `5` to `0.5` (etc.) easily.

To repro:
- Add `5` to line-height
- Now try to change it to `0.5` by placing the cursor in front of the value and typing in `0.`

File: assets/src/edit-story/components/form/numeric.js [hunk 5]
```diff
@@ -79,6 +79,49 @@ const Suffix = styled.span`
     `}
 `;
 
+const DisplayMode = {
+  Empty: 0,
+  Value: 1,
```
Comment (miina) [inline assets/src/edit-story/components/form/numeric.js]: Nit: perhaps `DISPLAY_MODE`, `EMPTY`, `VALUE` for consistency with constants used elsewhere.

**Comment by miina** [comment]
One more from testing:
When setting the cursor in the middle of an existing value and typing on invalid character, everything after the cursor is removed. Discovered by accidentally missing the correct key. Is this behavior intended?
E.g. type in `123`, place the cursor between `1` and `2`, type in `q` -> the result is `1`.

File: assets/src/edit-story/components/form/numeric.js [hunk 6]
```diff
@@ -79,6 +79,49 @@ const Suffix = styled.span`
...
+};
+
+function isIterimValue(value, isFloat, canBeNegative) {
```
Comment (miina) [inline assets/src/edit-story/components/form/numeric.js]: Would be great to split out parts of the logic (e.g. the helpers perhaps) to prevent the file from getting bloated.
Or, @barklund, is this something you would do anyway as part of #4104 ?

**Comment by carloskelly13** [comment]
To satisfy 
"Now try to change it to 0.5 by placing the cursor in front of the value and typing in 0."

Will be tricky since it will essentially require the input to support `05` as a valid value while the user puts the `.` in between. Currently you can put a `.` to start.

**Comment by barklund** [comment]
To clarify: We should **not** do any validation of the number while typing. You can type "0.00.5" or even "horse" and it's not replaced or manipulated or anything like that.

**Only** when you commit the number in some way (enter, blur or key up or down) is it validated and _if valid_, submitted, or _if not valid_, reverted.

Please see [my comment on the parent ticket on expected behavior](https://github.com/google/web-stories-wp/issues/4595#issuecomment-696221794).

I did not move it to the ticket definition as I wanted clarification first, but it seems to be the expectation of @pbakaus too.

**Comment by miina** [comment]
From testing:
Somehow, I ended up being able to insert invalid values as well, for example:
invalid-value

(Edit: tried to repro it for steps and it didn't happen anymore)

If I understood correctly from @barklund's comment then any invalid value should be reverted to previous, e.g. `2ndHelloWebStories` should not be converted to `2`. Thoughts?

**Comment by mariano-formidable** [comment]
Hmmm... that's a crazy bug, I'll see if I can repro it to see what's happening, definitely saving off an invalid number should not be allowed.

> If I understood correctly from @barklund's comment then any invalid value should be reverted to previous, e.g. `2ndHelloWebStories` should not be converted to `2`. Thoughts?

@miina I figure if whatever they type is parseable to a valid number, then we can just use the parsed valid number. If not, we'll have to do another series of checks just to see if the number they typed really is invalid.  For instance, `3.4.0` is an invalid number, but `parseFloat` extracts `3.4` from it and uses that as the valid number, I think that's okay instead of rejecting the entire input.  But if they type in something that cannot be (easily) parsed to a valid number, then the entire thing is rejected.

File: assets/src/edit-story/components/form/numeric.js [hunk 7]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
-      onChange(parseFloat(newValue.toString()));
     },
-    [isMultiple, float, onChange, max, value, min]
+    [value, handleUpDown]
   );
 
+  const handleKeyDown = useCallback(
+    (event) => {
+      if (event.key === 'Enter') {
+        validateAndSubmitInput();
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: I think we should select the entire input field contents here - it seems like fairly standard behavior, no?

File: assets/src/edit-story/components/form/numeric.js [hunk 8]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
         // Decrement value
         newValue =
           typeof min !== 'undefined'
-            ? Math.max(min, Big(value).minus(diff))
-            : Big(value).minus(diff);
+            ? Math.max(min, Big(newValue).minus(diff))
+            : Big(newValue).minus(diff);
+      }
+
+      setInputValue(newValue.toString());
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: I think we should submit the value here as well and select the entire input field contents. It does pollute the history quite a bit with a bunch of entries, but that also happens when you select an element and move it with arrow keys, so that's on par.

At least until we implement some history compacting logic previously postponed in #67.

File: assets/src/edit-story/components/form/numeric.js [hunk 9]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
+  }, []);
+
   useKeyDownEffect(
-    ref,
-    { key: ['up', 'alt+up', 'down', 'alt+down'], editable: true },
-    handleUpDown,
-    [handleUpDown]
+    inputRef,
+    {
+      key: ['up', 'alt+up', 'down', 'alt+down', 'escape'],
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: Why are these squashed into a single listener and not just two separate listeners? Then the switch in `handleKeyDownEffect` can go away.

File: assets/src/edit-story/components/form/numeric.js [hunk 10]
```diff
@@ -152,53 +242,27 @@ function Numeric({
...
-              onChange(valueAsNumber, evt);
-            }
-          }
-        }}
-        onBlur={(evt) => {
-          if (evt.target.form) {
-            evt.target.form.dispatchEvent(
-              new window.Event('submit', { cancelable: true })
-            );
+        onKeyDown={handleKeyDown}
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: Why is this not using `useKeyDownEffect`?

File: assets/src/edit-story/components/form/numeric.js [hunk 11]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
+
+  const handleKeyDownEffect = useCallback(
+    ({ key, altKey }) => {
+      switch (key) {
+        case 'Escape':
+          // Revert input value and exit input focus without
+          // triggering blur validation
+          setInputValue(value);
+          skipValidationRef.current = true;
+          inputRef.current.blur();
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: And here as well, I think we should select the entire input field contents after reverting.

File: assets/src/edit-story/components/form/numeric.js [hunk 12]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
+  const placeholder = isMultiple ? __('multiple', 'web-stories') : '';
+
+  const handleChange = useCallback((event) => {
+    setInputValue(event.target.value);
+  }, []);
+
+  const validateAndSubmitInput = useCallback(() => {
+    targetFormRef.current = inputRef.current.form;
+
+    const validValue = validateInput(inputValue, {
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: Alternatively, we could use `inputRef.current.valueAsNumber` here and do less parsing ourselves perhaps? It'll return `NaN` for both empty and invalid strings though.

File: assets/src/edit-story/components/form/numeric.js [hunk 13]
```diff
@@ -97,48 +111,124 @@ function Numeric({
...
       if (isMultiple) {
         return;
       }
 
-      let newValue;
+      const validValue = validateInput(inputValue, {
+        canBeNegative,
+        canBeEmpty,
+        float,
+      });
```
Comment (barklund) [inline assets/src/edit-story/components/form/numeric.js]: This (including `?? value`) is currently repeated a few times, could be moved to a common function.

File: assets/src/edit-story/components/form/numeric.js (hunk 7 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: Just to confirm, hitting enter will validate and submit the value, and then select all the input within the field.  No problem.

File: assets/src/edit-story/components/form/numeric.js (hunk 9 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: I tried separate handlers and 'escape' or 'enter' (in separate) handlers didn't register... but I may have done something wrong so I'll try again.

File: assets/src/edit-story/components/form/numeric.js (hunk 10 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: I couldn't get the `useKeyDownEffect` to trigger in the jest test, but I'll look again, I probably overlooked something.

File: assets/src/edit-story/components/form/numeric.js (hunk 11 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: Okay.  But there are existing Karma tests that specifically test that hitting escape on an input field should lose focus.  Currently, if you have an item selected in the editor and then put your focus on a numeric input field.  If you hit escape, the field would lose focus, and if you hit escape _again_ the selected element would be deselected.  

But with this change, things should work like this when a field is focused:
- Hit `esc` and value reverts, all input in field is selected.
- Hit `esc` again, and if all text is selected, then input loses focus.

Right?  Double `esc` to lose focus on input so we can continue the pattern of `esc` backing you out of your selections.

Comment (barklund) [reply assets/src/edit-story/components/form/numeric.js]: I can completely live with `esc` blurring the input field. That's actually fine with me - seems consistent with other editors.

File: assets/src/edit-story/components/form/numeric.js (hunk 12 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js]: If with `valueAsNumber` doing the parsing for us, wouldn't we still need to `parseInt` or `parseFloat` depending on the config flags?  And, as you pointed out, we'd have to still keep the logic to handle empty strings when they're allowed.  I think keeping the validation logic contained to one function keeps things clean.

File: assets/src/edit-story/components/inspector/design/designPanel.js [hunk 14]
```diff
@@ -102,8 +102,6 @@ function DesignPanel({
       (evt) => {
         if (evt) {
           evt.preventDefault();
-          // Reset.
-          setElementUpdates({});
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/inspector/design/designPanel.js]: This call was forces a re-render of the component before the updated element values come down the pipeline, thus for one cycle the panel child components are re-rendered with stale data.  This prevented the ability to hit `Enter`, save the data, _and_ select the contents of the input box (because the contents would go from new data, to stale data, back to new data, and that switch would force a deselect).  Removing this reset call, fixed the issue and doesn't seem to cause any other problems as the way `elementUpdates` is updated, previous update data gets overwritten by the new updates.  All the tests pass with this line taken out, and now the `Enter`, save, and select logic works... However, if it's too risky to just remove this reset logic, let me know and I'll try and figure out a work around.

**Comment by mariano-formidable** [comment]
@barklund @miina I believe I addressed all the feedback, this code is ready for a re-review 🎉

File: assets/src/edit-story/components/richText/karma/inlineSelection.karma.js [hunk 15]
```diff
@@ -358,6 +360,7 @@ describe('CUJ: Creator can Add and Write Text: Select an individual word to edit
       // Change line height to 5
       await data.fixture.events.click(lineHeight, { clickCount: 3 });
       await data.fixture.events.keyboard.type('5');
+      await data.fixture.events.keyboard.press('Enter');
       await data.fixture.events.keyboard.press('Escape');
```
Comment (miina) [inline assets/src/edit-story/components/richText/karma/inlineSelection.karma.js:373]: In the tests, was the `Escape` previously for submitting the changes? Could these be removed now, from here and elsewhere?

File: assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js [hunk 16]
```diff
@@ -308,10 +308,10 @@ describe('Link Panel', () => {
       // Verify remove button exists
       expect(linkPanel.addressClear).toBeTruthy();
 
-      // Force focus to input - has to move out and back for weird reasons
       linkPanel.address.focus();
-      linkPanel.addressClear.focus();
+      expect(document.activeElement).toEqual(linkPanel.address);
 
+      await fixture.events.sleep(2000);
```
Comment (miina) [inline assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js]: That's quite a long wait -- what's it for?

File: assets/src/edit-story/components/inspector/design/designPanel.js (hunk 14 above)
Comment (miina) [reply assets/src/edit-story/components/inspector/design/designPanel.js]: One thing I'm noticing currently is that the history seems to create entries for values even if these haven't changed.
For example:
- Add `23horse` to the input
- Now add `23bear` to the input

Even though the original value was really changed only once (from the initial value to `23`), there seem to be 2 history entries for that and getting the original value back needs two "Undo" clicks. Thoughts?

File: assets/src/edit-story/components/richText/karma/inlineSelection.karma.js (hunk 15 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/richText/karma/inlineSelection.karma.js:373]: Previously, `Escape` submitted the changes _and_ removed focus from the field, now `Enter` submits the changes and `Escape` removes focus from the field.

File: assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js (hunk 16 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js]: The test kept failing without it, not sure what it was waiting for.  I'll see if I can reduce it in length.

Comment (miina) [reply assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js]: Perhaps `waitFor` could be used here instead once it's clear what it's waiting for.

File: assets/src/edit-story/components/inspector/design/designPanel.js (hunk 14 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/inspector/design/designPanel.js]: Yup you're right Miina, this change does effect the history, it does seem to be adding in extra undo markers when it's not needed.  I'm going to revert this change.  But that means hitting enter and having the contents of the text input selected won't work again.  I'll see if I can figure out a workaround.

File: assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js (hunk 16 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js]: Good call, I'll investigate!

Comment (mariano-formidable) [reply assets/src/edit-story/components/panels/link/karma/linkPanel.karma.js]: After reverting the changes to `designPanel.js`, this test didn't need any changes, so I reverted these changes tooo.

File: assets/src/edit-story/components/form/numeric.js [hunk 17]
```diff
@@ -97,48 +114,177 @@ function Numeric({
...
+    if (selectInputContents.current) {
+      inputRef.current.select();
+
+      // When we want to select the content of the input
+      // we hold open the door for a slight moment to allow
+      // all the data to flush down the pipeline.
+      window.clearTimeout(selectContentsTimeout.current);
+      selectContentsTimeout.current = window.setTimeout(() => {
+        selectInputContents.current = false;
+      }, 10);
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/form/numeric.js]: This is the work-around I needed to implement so when you hit `Enter` and push up a new change, and then `value` fluctuates a bit (which causes a deselection), this timeout ensures that after the data flush, the final input is selected.  And now I don't need any changes to `designPanel.js`, so the history tracking should work like normal.

**Comment by mariano-formidable** [comment]
@miina Alrighty, I found a workaround to maintain the input selection without messing with any of the history tracking logic.  This PR is ready for a re-review again! :)

**Review by barklund — APPROVED** [review]
This is really good work and a great update on the tests. They still read very clearly and logically.

Edit: But please wait for @miina's input too.

**Comment by miina** [comment]
Works great now related to the previous issues!

There's one more note though -- not sure if we should create a follow-up issue or perhaps it could be a fix here since it seems to be a regression.

Using the arrow keys to change the values in the number inputs is lagging quite significantly, e.g.:
- Add a Text
- Go to the height field
- Increase the height by 4 clicking the arrow up four times quickly.
- Observe the lag.

**Comment by swissspidy** [comment]
@mariano-formidable FYI updated the PR description. The "Fixes" keyword needs to appear before every issue number. GitHub does not recognise `Fixes #123 #456`

**Comment by mariano-formidable** [comment]
> @mariano-formidable FYI updated the PR description. The "Fixes" keyword needs to appear before every issue number. GitHub does not recognise `Fixes #123 #456`

Oooh, good to know.  Thanks for the update!

File: assets/src/edit-story/components/form/numeric.js [hunk 18]
```diff
@@ -97,48 +117,195 @@ function Numeric({
...
+      setInputValue(validValue);
+
+      window.clearTimeout(submitOnChangeTimeout.current);
+      if (debounceOnChange) {
+        submitOnChangeTimeout.current = window.setTimeout(() => {
+          submitOnChange(validValue, { selectContentOnUpdate });
+        }, ONCHANGE_DEBOUNCE_DELAY);
+      } else {
+        submitOnChange(validValue, { selectContentOnUpdate });
+      }
```
Comment (mariano-formidable) [inline assets/src/edit-story/components/form/numeric.js:175]: @miina I added debounce logic so when a user uses the up/down arrow to quickly increment the value, instead of sending a complete `onChange` event per fast click (which is what caused the performance lag), it'll wait until the user stops rapid fire clicking and then send the last change down the pipeline.

**Comment by mariano-formidable** [comment]
@miina I think I fixed the lag issue, this PR is ready ready again again for your eyes :)

File: assets/src/edit-story/components/form/numeric.js (hunk 18 above)
Comment (miina) [reply assets/src/edit-story/components/form/numeric.js:175]: Works well now!

One note: should the timeout be canceled if it exists and the user types in something? If that's possible. Otherwise it might theoretically happen that the user uses arrows, and then types in something else, but due to debouncing, the "arrowed" value will be submitted and change the input value in the middle. Thoughts?

**Review by miina — APPROVED** [review]
LGTM pending one comment.

File: assets/src/edit-story/components/form/numeric.js (hunk 18 above)
Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js:175]: You're right!  It should be cancelled every time the user types in anything along with any time they submit a new value.  I'll add a `clearTimeout` call on the `handleChange` callback which triggers every time a user types in a new character in the input field (but doesn't trigger when they just hit the up/down arrows).  Nice catch!

File: assets/src/edit-story/components/form/numeric.js [hunk 19]
```diff
@@ -131,6 +131,11 @@ function Numeric({
   const placeholder = isMultiple ? __('multiple', 'web-stories') : '';
 
   const handleChange = useCallback((event) => {
+    // If the user types something in, clear timeout
+    // so onChange doesn't get triggered with possibly
+    // old value.
+    window.clearTimeout(submitOnChangeTimeout.current);
```
Comment (miina) [inline assets/src/edit-story/components/form/numeric.js:137]: Should this first check if the timeout is set and clear only if yes?

Comment (barklund) [reply assets/src/edit-story/components/form/numeric.js:137]: I don't think it can cause an issue to clear an unset timeout. Timeout IDs will never be reused and clearing an old or non-existing timeout is harmless.

Comment (mariano-formidable) [reply assets/src/edit-story/components/form/numeric.js:137]: I think it's okay to call regardless.  According to the mozilla docs it's okay to pass in an invalid ID, I assume they store them in a hash of some sort so the lookup would be quick (just as quick as an if statement).  Plus, I'd then have to add in more logic to make sure I set `submitOnChangeTimeout.current` to `-1` or something after each use (so more code).

From the docs:
```
Passing an invalid ID to clearTimeout() silently does nothing; no exception is thrown.
```

Comment (miina) [reply assets/src/edit-story/components/form/numeric.js:137]: Hah, was it different at some point in history? For some reason, I remember this requiring a value (`null` being invalid) but looks like not. Thanks for the info!
