### PR TITLE
Accessibility: Keyboard Shortcuts Menu Accessibility and I18N Improvements

### LINKED ISSUE #7478: Keyboard Shortcuts Menu Accessibility and I18N Improvements
## Bug Description

The keyboard shortcuts menu should be using the [`<kbd>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd) element. That'd remove the need for all those `aria-label` props due to the element's semantic meaning.

Also, the menu should avoid string concatenation for the actual menu items.

For example, "Hold CMD" would need to be translated to "CMD halten" in German, but that's currently not possible because the shortcut isn't one translatable string:

https://github.com/google/web-stories-wp/blob/06d921a7a7e1080a52cb3ff07c8fe7ad5493809f/assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js#L160-L161

This should be using something like:

```jsx
<TranslateWithMarkup
  mapping={{kbd: <kbd />}}
>
  {
    sprintf(
      /* translators: %s: Cmd/Ctrl key. */
      __('Hold <kbd>%s</kbd>', 'web-stories'),
      cmdOrCtrl
    )
  }
</TranslateWithMarkup>
```

## Screenshots

Screenshot 2021-05-11 at 10 19 58

## Additional Context

- Plugin Version: 1.7.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Improves translations and accessibility in keyboard shortcuts menu.

## Summary
The translation setup in keyboard shortcuts wasn't fully working because of scenarios involving keys in a statement like `hold ⌘`. Not every language here would put `hold` before `⌘`.

This PR is to create more context around the translations and markup so that statements involving keys are better translated. Also adds `kbd` element for semantic purposes which helps accessibility.

## Relevant Technical Choices
Decreased level of abstraction around rendering and declaring keyboard shortcut definitions. Makes declaring a keyboard shortcut a little more verbose, but much more explicit which removes a lot of logic when rendering. This also benefits translations by giving the translator a higher amount of context like: `hold ⌘` instead of `hold` and `⌘`

## To-do
NA

## User-facing changes
Should be no visual changes, just better translations into other languages and improved accessibility.

## Testing Instructions
Verify that there are no visual or functional changes to the keyboard shortcuts popup menu. Beyond that can try out other translations of try a screenreader on it if you so please.

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7478

### CODE REVIEW

File: assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js [hunk 1]
```diff
@@ -55,15 +77,33 @@ const shortcuts = {
...
         {
           label: __('Redo', 'web-stories'),
-          shortcut: [cmdOrCtrl, SPECIAL_KEYS.SHIFT, 'Z'],
+          shortcut: (
+            <kbd>
+              <kbd aria-label={cmdOrCtrl.title}>{cmdOrCtrl.symbol}</kbd>
+              <kbd aria-label={SPECIAL_KEYS.SHIFT.title}>
+                {SPECIAL_KEYS.SHIFT.symbol}
+              </kbd>
+              <kbd>{'Z'}</kbd>
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js:109]: Just double checking, these don't need translations because they are always the same value?

Comment (maxyinger) [reply assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js:109]: yea @swissspidy can probably verify better than I, but my understanding is that the translations are more for when there's some english involved with the keys. In this scenario, two keys doesn't mean anything more than two keys.

Also my assumption for alphanumeric character keys is that there's no need to translate them because the keyboard shortcut functionality is tied to the `Z` key explicitly and doesn't work with anything else.

**Review by BrittanyIRL — APPROVED** [review]
Well done, Max! I learned a lot from this and am going to take this and immediately go update the right click context menus that are also using keyboard shortcuts! 

Went ahead and created a follow up ticket to handle the keyboard navigation of this dialog since that is really out of scope here! https://github.com/google/web-stories-wp/issues/7912

File: assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js [hunk 2]
```diff
@@ -32,21 +32,43 @@ const optionOrAlt = isMacOs ? SPECIAL_KEYS.OPTION : SPECIAL_KEYS.ALT;
 const shortcuts = {
   header: {
     label: __('Keyboard Shortcuts', 'web-stories'),
-    shortcut: [cmdOrCtrl, '/'],
+    shortcut: (
+      <kbd>
+        <kbd aria-label={cmdOrCtrl.title}>{cmdOrCtrl.symbol}</kbd>
```
Comment (samwhale) [inline assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js]: 💭 I don't know if this would help at all, but maybe this could work as a component?

```js
const idkNamingIsHard = (key) => <kbd aria-label={key.title}>{key.symbol}</kbd>
```

But it's like all one line lol so 🤷. I don't really mind the repetition though, so whatever works!

File: assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js [hunk 3]
```diff
@@ -95,73 +155,186 @@ const shortcuts = {
...
+                  kbd: <kbd />,
+                  cmdOrCtrlSymbol: cmdOrCtrl.symbol,
+                  upSymbol: SPECIAL_KEYS.UP.symbol,
+                  downSymbol: SPECIAL_KEYS.UP.symbol,
+                }}
+              >
+                {sprintf(
+                  /* translators: 1: Cmd/Ctrl key. 2: Up key. 3: Down key. */
+                  __(
+                    '<kbd aria-label="%1$s"><cmdOrCtrlSymbol /></kbd><kbd aria-label="%2$s"><upSymbol /></kbd><span> or </span><kbd aria-label="%3$s"><downSymbol /></kbd>',
```
Comment (samwhale) [inline assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js]: wow this one is crazy 🔥

File: assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js [hunk 4]
```diff
@@ -23,77 +23,65 @@ import PropTypes from 'prop-types';
...
-  width: ${({ keySize }) => keySize};
-  padding: 0 5px;
-  height: 24px;
-  border-radius: ${({ theme }) => theme.borders.radius.medium};
-  border: 1px solid ${({ theme }) => theme.colors.border.defaultNormal};
-  color: ${({ theme }) => theme.colors.fg.primary};
+  kbd {
+    ${themeHelpers.expandTextPreset(
+      ({ paragraph }, { X_SMALL }) => paragraph[X_SMALL]
+    )}
```
Comment (samwhale) [inline assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js:35]: 👍

File: assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js [hunk 5]
```diff
@@ -23,77 +23,65 @@ import PropTypes from 'prop-types';
...
-            title={key.title}
-            keySize={
-              (key.symbol || key).length > 1 ? KEY_SIZE.LARGE : KEY_SIZE.NORMAL
-            }
-          >
-            {key.symbol || key}
-          </KeyboardKey>
-        )
-      )}
+      {keys}
```
Comment (samwhale) [inline assets/src/edit-story/components/keyboardShortcutsMenu/shortcutLabel.js:78]: This is way easier to read lol

**Review by samwhale — APPROVED** [review]
Looks great, works great, is great ✨. A question about the navigation when using assistive tech:

When navigating with left/right arrow keys through this, voiceover reads each character. But the `⌘` key (also others) are read, they read a group and then the key. Should it be ignoring the `command group`?

arrow-keys-through-characters

**Comment by maxyinger** [comment]
> When navigating with left/right arrow keys through this, voiceover reads each character. But the ⌘ key (also others) are read, they read a group and then the key. Should it be ignoring the command group?

Okay so looking into this a bit, it seems to happen if there's an `aria-label` on the key. We can remove the `aria-label` to remove the group announcement from voiceover, but might lose some of the translation benefits 🤷 . Not sure of other ways to escape that behavior beyond removing the `aria-label`?

Anyway, happy to go either way with it. Thoughts @samwhale @swissspidy ?

**Comment by BrittanyIRL** [comment]
> > When navigating with left/right arrow keys through this, voiceover reads each character. But the ⌘ key (also others) are read, they read a group and then the key. Should it be ignoring the command group?
> 
> Okay so looking into this a bit, it seems to happen if there's an `aria-label` on the key. We can remove the `aria-label` to remove the group announcement from voiceover, but might lose some of the translation benefits 🤷 . Not sure of other ways to escape that behavior beyond removing the `aria-label`?
> 
> Anyway, happy to go either way with it. Thoughts @samwhale @swissspidy ?

(Pascal's on PTO right now) 

Given we have a follow up for the ability to navigate the popup with a keyboard I'm not too worried about this right now. Voice over is a good first check but almost anyone relying on a screen reader isn't using voice over :)

**Comment by samwhale** [comment]
> > When navigating with left/right arrow keys through this, voiceover reads each character. But the ⌘ key (also others) are read, they read a group and then the key. Should it be ignoring the command group?
> 
> Okay so looking into this a bit, it seems to happen if there's an `aria-label` on the key. We can remove the `aria-label` to remove the group announcement from voiceover, but might lose some of the translation benefits 🤷 . Not sure of other ways to escape that behavior beyond removing the `aria-label`?
> 
> Anyway, happy to go either way with it. Thoughts @samwhale @swissspidy ?

Hmm yeah if it would remove the translation benefits then let's keep it. It's okay if it's announced twice.

File: assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js]: That‘s a lot of markup in a translatable string. Might be a tricky for translators. Not sure what would be best here though.

**Review by spacedmonkey — APPROVED** [review]
SGTM

File: assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js (hunk 3 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/keyboardShortcutsMenu/keyboardShortcutList.js]: 🤔 
We've got a follow up for the general popup to be announced better for SRs, let's return to this there - I don't think we need to hold the PR up for this.

**Comment by swissspidy** [comment]
@littlemilkstudio This now leads to translators having to translate strings like

```
<lkbd aria-label="%1$s"><cmdOrCtrlSymbol /></lkbd><kbd aria-label="%2$s"><shiftSymbol /></kbd><kbd aria-label="%3$s"><upSymbol /></kbd><span> or </span><kbd aria-label="%4$s"><downSymbol /></kbd>
```

Which obviously is super hard to read and prone to making mistakes.

Something like `%1$s%2$s or $3$s` seems easier, or probably even `translateToExclusiveList()` could be used.

There's also

```
<span>Hold </span><lkbd aria-label="%s"><cmdOrCtrlSymbol /></lkbd>
```

Which could be turned into

```
<span>Hold</span> %s
```

I'll try to whip up a PR.
