### PR TITLE
Fix selected stories and widget display options

### LINKED ISSUE #6788: Selected Stories: Carousel appears broken on first insertion
## Bug Description

Creating a box carousel block of selected stories doesn't present the preview of the carousel correctly in the post editor

## Expected Behaviour

The preview of the carousel should closely resemble what will be shown to the user in the post

## Steps to Reproduce

1. Add a web stories block presentation of selected stories to a post/page
2. Select the stories that you wish to include in the presentation
3. Note that the preview of the carousel does not closely match what is presented to users viewing the published post (only one story shown, no navigation arrows shown)

eg: Preview in editor 
image19

Presentation of carousel: 
Screen Shot 2021-03-16 at 2 16 57 PM 1

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6789: Selected Stories: Errors when rearranging stories
## Bug Description

If a user tries to use the "Rearrange Stories" button when they have selected a Selected Stories presentation, the block preview disappears and the user is presented with an error message.

## Expected Behaviour

The user should be presented with the ability to rearrange the order of the stories presented

## Steps to Reproduce

1. Create a new post/page and add a Web Stories block to it.
2. Select Recent Stories as the block type, and select a number of stories to use
3. Once selected and preview has updated, select the "Rearrange Stories" button 
Screen Shot 2021-03-16 at 2 28 10 PM
4. Note that the preview dissapears, and the user is presented with an error message which prevents and rearranging from occuring
Screen Shot 2021-03-16 at 11 12 29 AM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6791: Web Story widget display options don't work as expected
## Bug Description

As a user who has added the Web Stories block as a widget in the theme, there are a couple of issues with the display options.

1. Circle Carousel - Display Title - not working
2. Circle Carousel - Cannot select Display Title & Display Archive link concurrently (if this is intentional then the UI might be better as toggle/radio to telegraph this to user)
3. Circle Carousel - Display Archive link not working
4. Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
5. Grid Carousel - Display Archive link not working
6. Grid Carousel - Number of Columns - this doesn't work when the widget is used in the blog sidebar area
7. Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
8. List - Doesn't' display anything when used as a widget in the blog sidebar area
9. List - cannot select any of the display options concurrently

## Expected Behaviour

Options should work as expected.

## Steps to Reproduce

1. Add the block as a widget to a theme that supports this functionality
2. In the customizer, add the widget to a display area such as the blog sidebar area
3. Note the issues that are detailed above.

## Screenshots

**List view not working** 
Screen Shot 2021-03-16 at 3 32 41 PM

**Title display not working**
Screen Shot 2021-03-16 at 3 35 09 PM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

There were some issues related to the "selected stories" block type/view

## Summary

* Fixes styling issues with the "select stories" modal
* Fixes crashes in the "select stories" modal
* Fixes an issue where carousel where not appearing correctly upon first insertion

## User-facing changes

Screenshot 2021-03-16 at 19 44 14

Screenshot 2021-03-16 at 18 44 46

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Verify that rearranging stories in the "Selected Stories" mode works
2. Verify that carousel is displayed correctly when first inserting the block with a few selected stories

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6788
Fixes #6789
Fixes #6791

### CODE REVIEW

**Comment by spacedmonkey** [comment]
I am not sure these issues are related but I still see issues when switching between block types including. 

When switching to circle, this happens. 
Screenshot 2021-03-17 at 10 13 52

Sometimes I were seeing stories break the edge of the container. 
Screenshot 2021-03-17 at 10 14 56

File: assets/src/web-stories-block/block/components/storiesPreview.js [hunk 1]
```diff
@@ -137,7 +140,9 @@ function StoriesPreview(props) {
         {CIRCLES_VIEW_TYPE === viewType || CAROUSEL_VIEW_TYPE === viewType ? (
           <>
             <div className="web-stories-list__carousel" ref={carouselContainer}>
-              <div className="glider-track">{storiesLoop()}</div>
+              <div className="glider-track">
+                <StoriesLoop />
```
Comment (spacedmonkey) [inline assets/src/web-stories-block/block/components/storiesPreview.js:149]: 👍

File: includes/Widgets/Stories.php [hunk 2]
```diff
@@ -321,7 +321,6 @@ public function form( $instance ) {
 				'id'            => 'image_alignment',
 				'name'          => 'image_alignment',
 				'label'         => __( 'Image Alignment', 'web-stories' ),
-				'type'          => 'checkbox',
```
Comment (spacedmonkey) [inline includes/Widgets/Stories.php:324]: Maybe alignment options should be a dropdown / select menu?

Comment (swissspidy) [reply includes/Widgets/Stories.php:324]: This can be explored in a new ticket.  It's a radio button everywhere at the moment I think. Not changing this here, just removing some unused arg.

**Comment by spacedmonkey** [comment]
Screenshot 2021-03-17 at 10 56 00
Should the spacing between box should really be equal spacing?

**Comment by spacedmonkey** [comment]
Screenshot 2021-03-17 at 11 02 05
On sizing, I seeing some odd rendering some points.

File: packages/glider/src/index.js [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+      }
+    }
+
+    slide = Math.min(slide, this.slides.length);
+
+    this.slide = slide;
+    slide = this.itemWidth * slide;
+  }
+
+  this.scrollTo(
```
Comment (spacedmonkey) [inline packages/glider/src/index.js:114]: Some documentation would be useful here.

File: packages/glider/src/index.js [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+    slide,
+    this.opt.duration * Math.abs(this.ele.scrollLeft - slide),
+    function () {
```
Comment (spacedmonkey) [inline packages/glider/src/index.js:117]:
```suggestion
   () => {
```

File: packages/glider/src/index.js (hunk 3 above)
Comment (swissspidy) [reply packages/glider/src/index.js:114]: FWIW that's not new code, just moved to a different place so we can use it in two places (frontend + block)

File: packages/glider/src/index.js (hunk 4 above)
Comment (swissspidy) [reply packages/glider/src/index.js:117]: Don't think it will work due to usage of `this`.

Also, this is just existing code moved to a different place, not new code.

Comment (spacedmonkey) [reply packages/glider/src/index.js:117]: Okay never mind.

**Comment by swissspidy** [comment]
> When switching to circle, this happens.

Fixed now

> Sometimes I were seeing stories break the edge of the container.

Can't reproduce

> Should the spacing between box should really be equal spacing?

Fixed now

> On sizing, I seeing some odd rendering some points.

This warrants a new ticket, as it's glider.js doing something wrong and might require patching.

**Review by spacedmonkey — APPROVED** [review]
Looking good!

**Comment by swissspidy** [comment]
@csossi can you QA this one? Please move it to the QA column. Thanks
