### PR TITLE
Makes retrieving media from local api bypass preloaded cache when WP Upload modal closed.

### LINKED ISSUE #4109: Media library not refreshing after uploading via WP media modal
## Bug Description

A newly uploaded image is appearing immediately in "Images" media category, but not in "All" category

## Expected Behaviour

Expected newly uploaded image to appear under both "Images" and "All"

## Steps to Reproduce

- create new story
- select "Upload" from media panel
- browse for and upload an image
- insert this new image into page

- note that image isn't appearing under "All" category (even though it IS appearing in "Images" category

## Screenshots

Newly uploaded image is on the canvas here, but isn't in media "all" section:
image

However, you can see it here when viewing just "Images":
image

(Note: If I navigate away from editor and return, then the image WILL appear under "All")

## Additional Context

- Plugin Version: Testing in PR#4012
- Operating System: Win10
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ezxyz**
## Summary

the preloader is intercepting the request `web-stories/v1/media?context=edit&per_page=100&page=1&_web_stories_envelope=true`
Instead of using the request that is cached we should modify it by appending cache_bust=true when called via after upload media

## Relevant Technical Choices
using a cache_bust parameter for the api call from resetWithFetch (triggered onClose for the WP Media modal).

## User-facing changes

Local media pane refreshes properly when new media is uploaded via the wp media modal. (see #4109)

## Testing Instructions

Upload via local media pane "upload button". Close the modal. The pane should have the new media displayed. 

---

Fixes #4109

### CODE REVIEW

File: assets/src/edit-story/app/api/test/apiProvider.js [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+ * WordPress dependencies
+ */
+
+/**
+ * External dependencies
+ */
+import { act, renderHook } from '@testing-library/react-hooks';
+
+jest.mock('@wordpress/api-fetch');
+import apiFetch from '@wordpress/api-fetch';
```
Comment (cvolzke4) [inline assets/src/edit-story/app/api/test/apiProvider.js]: The import statement can still be added to the 'WordPress dependencies' section, the order jest.mock and import aren't significant.

File: assets/src/edit-story/app/api/test/apiProvider.js [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+import ApiProvider from '../apiProvider';
+import { ConfigProvider } from '../../config';
+import {
+  GET_MEDIA_RESPONSE_HEADER,
+  GET_MEDIA_RESPONSE_BODY,
+} from './sampleApiResponses';
+
+describe('APIProvider', () => {
+  beforeEach(() => {
+    apiFetch.mockImplementation(() => {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/api/test/apiProvider.js]: I think this can be simplified to:
```
apiFetch.mockImplementation(async () => ({
  body: GET_MEDIA_RESPONSE_BODY,
  headers: GET_MEDIA_RESPONSE_HEADER,
});
```

File: assets/src/edit-story/app/api/test/apiProvider.js [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+      return Promise.resolve({
+        body: GET_MEDIA_RESPONSE_BODY,
+        headers: GET_MEDIA_RESPONSE_HEADER,
+      });
+    });
+  });
+
+  it('when getMedia called with cacheBust:true, should call api with &cache_bust=true', () => {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/api/test/apiProvider.js]: So that the 'describe' description and 'it' description form a sentence, consider:
'getMedia should call api with &cache_bust=true when cacheBust:true'

File: assets/src/edit-story/app/api/test/apiProvider.js [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    const { result } = renderHook(() => useAPI(), {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/api/test/apiProvider.js]: Rendering of ApiProvider inline distracts the reader from what the test is trying to do. The renderHook part can be extracted to it's own function:

```
  renderApiProvider({ configValue }) {
    return renderHook(() => useAPI(), {
      // eslint-disable-next-line react/display-name
      wrapper: (props) => (
        <ConfigProvider config={configValue}>
          <ApiProvider {...props} />
        </ConfigProvider>
      ),
    });
  }
```

File: assets/src/edit-story/app/api/test/sampleApiResponses.js [hunk 5]
```diff
@@ -0,0 +1,215 @@
+/*
```
Comment (cvolzke4) [inline assets/src/edit-story/app/api/test/sampleApiResponses.js]: +1 for adding samples in its own file

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 6]
```diff
@@ -0,0 +1,263 @@
...
+ */
+import ApiContext from '../../../api/context';
+import useContextValueProvider from '../useContextValueProvider';
+import {
+  GET_MEDIA_RESPONSE_BODY,
+  GET_MEDIA_RESPONSE_HEADER,
+} from '../../../api/test/sampleApiResponses';
+import { ConfigProvider } from '../../../config';
+
+jest.mock('../../useUploadMedia');
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:32]: imports should still be listed in the right section, the ordering of jest.mock and import doesn't affect the test.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 7]
```diff
@@ -0,0 +1,263 @@
...
+      },
+    },
+    attribution: undefined,
+  },
+];
+
+describe('useContextValueProvider', () => {
+  let reducerState;
+  let reducerActions;
+  beforeEach(() => {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:176]: (nit): Add a space before beforeEach().

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 8]
```diff
@@ -0,0 +1,263 @@
...
+      setMediaType: jest.fn(),
+      setSearchTerm: jest.fn(),
+      setNextPage: jest.fn(),
+      setProcessing: jest.fn(),
+      removeProcessing: jest.fn(),
+      updateMediaElement: jest.fn(),
+      deleteMediaElement: jest.fn(),
+    };
+
+    const useUploadMediaResult = {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:200]: This can be applied inline (here and below):

```
useUploadMedia.mockImplementation(() => ({
  uploadMedia: jest.fn(),
  isUploading: jest.fn(),
}));
```

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 9]
```diff
@@ -0,0 +1,263 @@
...
+    const useUploadVideoFrameResult = {
+      uploadVideoFrame: jest.fn(),
+    };
+    useUploadVideoFrame.mockImplementation(() => useUploadVideoFrameResult);
+  });
+
+  it('resetWithFetch calls getMedia with cacheBust:true and then fetchMediaSuccess', async () => {
+    // Set up and make initial call to useContextValueProvider (which calls
+    // getMedia and fetchMediaSuccess once). Sets an empty media state.
+    const getMedia = jest.fn(() =>
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:215]: I think this can be written as:
```
const getMedia = jest.fn(async () => ({
  data: [],
  headers: GET_MEDIA_RESPONSE_HEADER,
}));
```

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 10]
```diff
@@ -0,0 +1,263 @@
...
+        getMedia,
+      },
+    };
+    const configState = {
+      api: {},
+      allowedMimeTypes: {
+        video: [],
+      },
+    };
+    const { result } = renderHook(
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js]: This can be extracted to a function.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 11]
```diff
@@ -0,0 +1,263 @@
...
+              {params.children}
+            </ApiContext.Provider>
+          </ConfigProvider>
+        ),
+      }
+    );
+
+    // This promise will only complete when the "done()" callback is called
+    // (see reducerActions.fetchMediaSuccess mock implementation in Promise).
+    await new Promise((done) => {
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:241]: Is this needed? It should be enough to 'await null' in the test for everything to finish, including the call to fetchMediaSuccess, something like:
```
getMedia.mockImplementation(() => ({
  data: GET_MEDIA_RESPONSE_BODY,
  headers: GET_MEDIA_RESPONSE_HEADER,
}));

result.current.actions.resetWithFetch();

await null;

expect(getMedia).toHaveBeenNthCalledWith(2, {
:
expect(reducerActions.fetchMediaSuccess).toHaveBeenNthCalledWith(2, {
:
```

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js [hunk 12]
```diff
@@ -0,0 +1,263 @@
...
+      });
+      reducerActions.fetchMediaSuccess.mockImplementation(() => {
+        done();
+      });
+
+      // Act:
+      result.current.actions.resetWithFetch();
+    });
+
+    // Assert after fetchMediaSuccess callback is called:
```
Comment (cvolzke4) [inline assets/src/edit-story/app/media/local/test/useContextValueProvider.js:256]: Swap the expect statements, to reflect the order in which fetchMediaSuccess then getMedia are called.

**Review by cvolzke4 — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 9 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:215]: Linter doesn't seem to like this "async arrow function with no await expression". So I'll just leave it as it is.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 12 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:256]: getMedia get's called first and then the fetchMediaSuccess get's called.

See `local/useContextValueProvider:84`. The "callback" is the fetchMediaSuccess function which is called after getMedia's promise is resolved via "then".

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 10 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js]: Done.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 11 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:241]: Done.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 6 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:32]: Done.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 7 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:176]: Done.

File: assets/src/edit-story/app/api/test/apiProvider.js (hunk 4 above)
Comment (ezxyz) [reply assets/src/edit-story/app/api/test/apiProvider.js]: Done.

File: assets/src/edit-story/app/api/test/apiProvider.js (hunk 3 above)
Comment (ezxyz) [reply assets/src/edit-story/app/api/test/apiProvider.js]: Done.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 9 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:215]: Makes sense

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 12 above)
Comment (cvolzke4) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:256]: I came to this conclusion after reading "Assert after fetchMediaSuccess callback is called".

**Review by cvolzke4 — APPROVED** [review]

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 12 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:256]: Hmm yeah thats a confusing/redundant statement. Removed.

File: assets/src/edit-story/app/media/local/test/useContextValueProvider.js (hunk 8 above)
Comment (ezxyz) [reply assets/src/edit-story/app/media/local/test/useContextValueProvider.js:200]: Done.

File: assets/src/edit-story/app/api/test/apiProvider.js (hunk 2 above)
Comment (ezxyz) [reply assets/src/edit-story/app/api/test/apiProvider.js]: Decided to use mockReturnValue after offline discussion.

File: assets/src/edit-story/app/api/test/apiProvider.js (hunk 1 above)
Comment (ezxyz) [reply assets/src/edit-story/app/api/test/apiProvider.js]: Done.
