### PR TITLE
Bug: Tooltip Text Wrapping & Improvements

### LINKED ISSUE #2343: Tooltips: tooltip with longer text goes out of the screen
## Bug Description
When longer text is added to the tooltip, it stays on one line causing the tooltip to go out of the screen.

## Expected Behaviour
Tooltip should wrap the text instead to always stay within the borders of the viewport.

## Steps to Reproduce
1. Add a tooltip with longer text to something in the Design Panel
2. See the tooltip partially not visible.

## Screenshots
Screenshot 2020-06-10 at 17 16 20

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
This PR fixes the following bugs:
- Sizes popover to size of contents
- Updates tooltip to have `max-width` of `180px` & allows for text wrapping after text exceeds `180px`. We can alter this to a different `px` value or use `em` if we'd prefer a max character length here.
- Adds dynamic arrow positioning for top and bottom positioned tooltips so that tooltips aren't extremely smooshed and still visually map to corresponding anchor element
- Corrects upper bounds of popover for both horizontal & vertical positioning
- Fixes when tooltips are spaced to be whenever body resizes instead of trying to infer this through a resize event & several other metrics. This should fix a flash that occasionally happens on first hover.
- Updates no opacity allowed text to requested text in comment above now that tooltip allows for wrapping

## Relevant Technical Choices
Updated popover positioning from resize & other metrics to a callback in a resize observer observing the body size changes. This primarily fixes a first render being off bug that was causing small flashes between popover positions on initial hover.

Also tried to alter existing approach as little as possible while still fixing a couple issues.

## To-do
NA

## User-facing changes
Popovers should no longer go off screen as describe in [the issue this addresses](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/2343). 
Also should see dynamic arrow for tooltip that doesn't only appear in the center of the tooltip when getting close to off screen.

## Testing Instructions
Follow steps described in [issue ticket](https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/2343) to reproduce tooltip going outside of screen. Verify that it doesn't go out of the screen anymore and looks nice.

In the story editor for any story, hover over grid view and see that the tooltip now lines up properly to the icon it's pointing to.

## Screenshots
Screen Shot 2020-08-25 at 5 31 09 PM
Screen Shot 2020-08-25 at 5 31 18 PM
Screen Shot 2020-08-25 at 5 31 24 PM

---

Fixes #2343

### CODE REVIEW

File: assets/src/edit-story/components/popup/index.js [hunk 1]
```diff
@@ -56,26 +51,26 @@ export const Placement = {
...
-      left: `${x}px`,
-      top: `${y}px`,
+      transform: `translate(${x}px, ${y}px) ${getTransforms(placement)}`,
       ...(fillWidth ? { width: `${width}px` } : {}),
       ...(fillHeight ? { height: `${height}px` } : {}),
     },
   })
 )`
+  left: 0px;
+  top: 0px;
```
Comment (maxyinger) [inline assets/src/edit-story/components/popup/index.js:63]: this allows the content to render at its proper size, before moving it to the proper position.

File: assets/src/edit-story/components/popup/index.js [hunk 2]
```diff
@@ -131,20 +126,18 @@ function Popup({
...
     return () => {
-      window.removeEventListener('resize', positionPopup);
       document.removeEventListener('scroll', positionPopup, true);
     };
   }, [positionPopup]);
 
-  useEffect(() => {
-    positionPopup();
-  }, [placement, spacing, anchor, dock, popup, isOpen, positionPopup]);
+  useLayoutEffect(positionPopup, [positionPopup, isOpen]);
```
Comment (maxyinger) [inline assets/src/edit-story/components/popup/index.js]: We need to run it an extra time when it opens because we don't have access to the popover DOM node to obtain size of the element and calculate its proper horizontal & vertical boundaries

File: assets/src/edit-story/components/popup/utils.js [hunk 3]
```diff
@@ -22,17 +22,17 @@ import { Placement } from '.';
 export function getXTransforms(placement) {
   // left & right
   if (placement.startsWith('left')) {
-    return `-100%`;
+    return -1;
```
Comment (maxyinger) [inline assets/src/edit-story/components/popup/utils.js:25]: changed these to pure values so it's easy to obtain transforms in other calculations

File: assets/src/edit-story/components/popup/utils.js [hunk 4]
```diff
@@ -144,10 +144,10 @@ export function getOffset(placement, spacing, anchor, dock, popup) {
     dockRect,
     bodyRect
   );
-  const maxOffsetX = bodyRect.width - spacingH;
+  const maxOffsetX = bodyRect.width - width - getXTransforms(placement) * width;
```
Comment (maxyinger) [inline assets/src/edit-story/components/popup/utils.js:147]: I wasn't sure what the `spacingH` was for, but this properly set the element to a max of the viewport edge. Happy to add `spacingH` back in if needed

File: assets/src/edit-story/components/tooltip/index.js [hunk 5]
```diff
@@ -49,8 +49,7 @@ const Tooltip = styled.div`
   justify-content: center;
   align-items: center;
   flex-direction: row;
-  white-space: nowrap;
-  will-change: transform;
+  max-width: 180px;
```
Comment (maxyinger) [inline assets/src/edit-story/components/tooltip/index.js]: We can change this to a different `px` breakpoint at which text wraps, or we can use `em` if we'd like to use a max amount of characters here instead

**Review by dmmulroy — APPROVED** [review]
This works well for me 👍

File: assets/src/edit-story/components/popup/index.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/popup/index.js]: Can't this line go in the other `useLayoutEffect` or does it not re-mount often enough (because `isOpen` isn't a dependency)?

File: assets/src/edit-story/components/panels/stylePreset/presets.js [hunk 6]
```diff
@@ -138,10 +138,8 @@ function Presets({
         (isText && presetHasGradient(color)));
     let tooltip = null;
     if (disabled) {
-      // @todo The correct text here should be: Page background colors can not have an opacity.
-      // However, due to bug with Tooltips/Popup, the text flows out of the screen.
       tooltip = isBackground
-        ? __('Opacity not allowed for Page', 'web-stories')
+        ? __('Page background colors can not have an opacity.', 'web-stories')
```
Comment (barklund) [inline assets/src/edit-story/components/panels/stylePreset/presets.js]:
```suggestion
        ? __('Page background colors cannot have an opacity', 'web-stories')
```

File: assets/src/edit-story/components/tooltip/index.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/components/tooltip/index.js]: Looking at this, I feel the multi-line text ought to be centered here and maybe have a smaller line-height - the gap seems a bit too big to me. I don't know if there's a design for this somewhere?

Screen Shot 2020-08-26 at 14 08 15

**Review by barklund — COMMENTED** [review]
A couple of comments (forgot to group the first ones in a review, sorry).

Edit: Works great by the way - good job! 🎉

**Review by mariano-formidable — APPROVED** [review]
Looks good to me and I tested in the editor (comparing `main` to this branch) and it all works nicely!

File: assets/src/edit-story/components/popup/index.js (hunk 2 above)
Comment (maxyinger) [reply assets/src/edit-story/components/popup/index.js]: yea doesn't remount often enough because `isOpen` isn't a dependency.

We can probably smoosh them together tho. might make sense to only have a scroll listener binded if popover is open. I'll check this out and make sure it doesn't cause any race conditions. Should be a little lighter weight to only update an the open popover on scroll too

File: assets/src/edit-story/components/tooltip/index.js (hunk 5 above)
Comment (maxyinger) [reply assets/src/edit-story/components/tooltip/index.js]: Yea, I'd agree with that. happy to make any and all design updates now that we see it wrapping. I wasn't looking at any designs when I was updating this, was just getting the functionality to work

Comment (maxyinger) [reply assets/src/edit-story/components/tooltip/index.js]: new update:
Screen Shot 2020-08-26 at 1 31 07 PM

Comment (miina) [reply assets/src/edit-story/components/tooltip/index.js]: [Design for the line-height](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Stories-Stable?node-id=736%3A1178) reference (the color has changed meanwhile for the new design for this specific tooltip apparently but might still be good reference for the line height):
Screenshot 2020-08-27 at 13 23 06

There's also [the general tooltip style in Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=549%3A15890).

Both one- and single-line seem to have 20px as line-height.
