### PR TITLE
Fix Color Picker: Saving text background color saves text color instead

### LINKED ISSUE #9891: Saving text background color saves text color instead
## Bug Description

When I want to save the text element's background color, it saves the text color instead.

## Expected Behaviour

The bg color should be saved.

## Steps to Reproduce

1. Insert text element
2. Change bg color
3. Try to save bg color

## Screenshots

https://user-images.githubusercontent.com/841956/144714656-96795a83-f5e4-44a5-81fe-2f772cd04dec.mov

## Additional Context

- Plugin Version: 1.16.0-alpha
- WordPress Version: 5.9 Beta
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by Trapsta**
## Context

Currently, when you click a text element's background color and try to save the background color to the local or global palettes, the element's text color is saved instead. 

## Summary

I am making use of the `changedStyle` prop in the `ColorPicker` component which is currently used for implementing changes in the element's attributes, to detect from which attribute the color picker was triggered from and save the correct color / background color accordingly. 

## User-facing changes

| Before | After |
|--------|-------|
|   144714656-96795a83-f5e4-44a5-81fe-2f772cd04dec |  Screen Recording 2021-12-19 at 22 33 05  |

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Insert text element
2. Change bg color
3. Try to save bg color
4. make sure the correct color is added to both the local and global colors.
5. Make sure saving the text color also works correctly.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9891

### CODE REVIEW

File: packages/story-editor/src/components/colorPicker/colorAdd.js [hunk 1]
```diff
@@ -51,9 +51,15 @@ const AddColorAction = styled.button`
...
-function ColorAdd({ isLocal = false, isGlobal = false, ...props }) {
+function ColorAdd({
+  isLocal = false,
+  isGlobal = false,
+  isBackground = false,
+  ...props
+}) {
   const { addGlobalPreset, addLocalPreset } = useAddPreset({
     presetType: PRESET_TYPES.COLOR,
+    getBackground: isBackground,
```
Comment (miina) [inline packages/story-editor/src/components/colorPicker/colorAdd.js]: Maybe `isBackgroundColor`? `getBackground` sounds like a function, not a bool.

File: packages/story-editor/src/components/colorPicker/basicColorList.js [hunk 2]
```diff
@@ -108,6 +109,9 @@ function BasicColorList({
   const colorType = isLocal
     ? __('local', 'web-stories')
     : __('global', 'web-stories');
+
+  const isBackground = changedStyle !== 'color';
```
Comment (miina) [inline packages/story-editor/src/components/colorPicker/basicColorList.js]: Wouldn't `changedStyle === 'background'` work here?

**Review by miina — APPROVED** [review]
Just 2 nits, otherwise looks good.

**Comment by miina** [comment]
@Trapsta Forgot to add that we should also add a new Karma test for it.

File: packages/story-editor/src/components/colorPicker/basicColorList.js (hunk 2 above)
Comment (miina) [reply packages/story-editor/src/components/colorPicker/basicColorList.js]: (Since there are other `changedStyle` values as well possible, such as "border-color", would be better if we would check directly if the `changedStyle` is `background`.)
