### PR TITLE
Fix DOMDocument issues with AMP boilerplate and encodings

### LINKED ISSUE #4140: Incompatibility with older libxml versions
## Feature Description

The `libxml` extension prior to version 2.8.0 has issues parsing `<noscript>` tags in the `<head>`, which means this part of the AMP boilerplate:

`<noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

This causes AMP validation errors.

Even though version 2.8 was released in 2012, PHP could still be compiled with an older version, i.e. one could be on PHP 5.6 with libxml 2.9, or on PHP 7 with libxml 2.7

## Additional Context

https://github.com/ampproject/amp-wp/pull/5097
http://xmlsoft.org/news.html

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #4166: Encoding of special characters broken on frontend
## Bug Description

Special characters like àòù'ì doesnt works after beta2 update

## Expected Behaviour

Show fonts special characters
## Steps to Reproduce

Open 1 webstory like https://claudia-makeup.com/stories/recensione-snap-shadow-cadet-webstory/

## Screenshots

Cattura

## Additional Context

Tested on windows10 chrome, windoes10 firefox, one plus 5t android 10 with chrome, and firefox

- Plugin Version: beta2

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

See #4140 for details. This is a somewhat hacky workaround for libxml < 2.8, but it's also what the AMP plugin does:

1. Remove `<noscript>` part from markup
1. Parse markup into DOMDocument
1. Re-add `<noscript>`

## Relevant Technical Choices

* Ensure UTF-8 encoding

## User-facing changes

N/A

## Testing Instructions

---

Fixes #4140
Fixes #4166

### CODE REVIEW

File: includes/Story_Renderer/HTML.php [hunk 1]
```diff
@@ -191,6 +193,49 @@ protected function replace_html_head( $content ) {
...
+			'<noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>'
+		);
+
+		$head = $this->get_element_by_tag_name( 'head' );
+
+		if ( ! $head ) {
+			return;
+		}
+
+		$head->appendChild( $this->document->importNode( $fragment, true ) );
```
Comment (westonruter) [inline includes/Story_Renderer/HTML.php]: Is importing necessary? The fragment was already created in this document, so I think you can just append the fragment as a whole.

**Review by westonruter — COMMENTED** [review]
I assume most of the HTML class here won't be necessary once the common lib from the AMP plugin is added as a dependency?

File: includes/Story_Renderer/HTML.php (hunk 1 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php]: Maybe not! I'll check

**Comment by swissspidy** [comment]
> I assume most of the HTML class here won't be necessary once the common lib from the AMP plugin is added as a dependency?

@westonruter Yeah we'd remove all redundant parts for sure.

File: includes/Story_Renderer/HTML.php [hunk 2]
```diff
@@ -67,12 +67,15 @@ public function __construct( Story $story ) {
 	 */
 	public function render() {
 		$markup = '<!DOCTYPE html>' . $this->story->get_markup();
+		$markup = mb_convert_encoding( $markup, 'HTML-ENTITIES', 'UTF-8' );
```
Comment (westonruter) [inline includes/Story_Renderer/HTML.php]: See also how the AMP plugin is doing this before parsing: 

https://github.com/ampproject/amp-wp/blob/dce58640f7c36befda67b145d00ec4f40c2278eb/lib/common/src/Dom/Document.php#L1052

File: includes/Story_Renderer/HTML.php [hunk 3]
```diff
@@ -191,6 +253,49 @@ protected function replace_html_head( $content ) {
...
+		$fragment = $this->document->createDocumentFragment();
+		$fragment->appendXml(
+			'<noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>'
+		);
+
+		$head = $this->get_element_by_tag_name( 'head' );
+
+		if ( ! $head ) {
+			return;
+		}
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php]:
```suggestion
		if ( $head ) {
		      $head->appendChild( $fragment );
		}
```

File: includes/Story_Renderer/HTML.php [hunk 4]
```diff
@@ -191,6 +253,49 @@ protected function replace_html_head( $content ) {
...
+	 *
+	 * The libxml extension prior to version 2.8.0 has issues parsing <noscript> tags in the <head>.
+	 * That's why we temporarily remove this fragment and re-add it later.
+	 *
+	 * @see https://github.com/ampproject/amp-wp/pull/5097
+	 * @see http://xmlsoft.org/news.html
+	 *
+	 * @return void
+	 */
+	protected function add_noscript_amp_boilerplate() {
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php:289]: Why doesn't this method return anything.

File: includes/Story_Renderer/HTML.php [hunk 5]
```diff
@@ -66,13 +100,16 @@ public function __construct( Story $story ) {
 	 * @return string The complete HTML markup for the story.
 	 */
 	public function render() {
-		$markup = '<!DOCTYPE html>' . $this->story->get_markup();
+		$markup = self::DEFAULT_DOCTYPE . $this->story->get_markup();
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php:110]: Why change this to a const?

File: includes/Story_Renderer/HTML.php [hunk 6]
```diff
@@ -51,6 +51,40 @@ class HTML {
...
+	const AMP_ENCODING = 'utf-8';
+
+	/**
+	 * Encoding identifier to use for an unknown encoding.
+	 *
+	 * "auto" is recognized by mb_convert_encoding() as a special value.
+	 *
+	 * @var string
+	 */
+	const UNKNOWN_ENCODING = 'auto';
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php:68]: What is this used for?

File: includes/Story_Renderer/HTML.php [hunk 7]
```diff
@@ -51,6 +51,40 @@ class HTML {
 	 */
 	protected $document;
 
+	/**
+	 * AMP requires the HTML markup to be encoded in UTF-8.
+	 *
+	 * @var string
+	 */
+	const AMP_ENCODING = 'utf-8';
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php:59]: Why is this a const, it is only used once?

File: includes/Story_Renderer/HTML.php [hunk 8]
```diff
@@ -51,6 +51,40 @@ class HTML {
...
+	/**
+	 * Encoding detection order in case we have to guess.
+	 *
+	 * This list of encoding detection order is just a wild guess and might need fine-tuning over time.
+	 * If the charset was not provided explicitly, we can really only guess, as the detection can
+	 * never be 100% accurate and reliable.
+	 *
+	 * @var string
+	 */
+	const ENCODING_DETECTION_ORDER = 'UTF-8, EUC-JP, eucJP-win, JIS, ISO-2022-JP, ISO-8859-15, ISO-8859-1, ASCII';
```
Comment (spacedmonkey) [inline includes/Story_Renderer/HTML.php:86]: Why is this a const, it is only used once?

File: includes/Story_Renderer/HTML.php (hunk 4 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:289]: Because it directly manipulates `$this->document`. There's nothing to return here.

File: includes/Story_Renderer/HTML.php (hunk 6 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:68]: Ah, I forgot to add it, but this would be the default of `$encoding` further down.

File: includes/Story_Renderer/HTML.php (hunk 8 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:86]: Copied those consts mostly from the AMP plugin. Makes comparing the code easier and might be expanded in the future

File: includes/Story_Renderer/HTML.php (hunk 5 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:110]: For consistency with the other consts

File: includes/Story_Renderer/HTML.php (hunk 3 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php]: Just a matter of preference I suppose?

Comment (spacedmonkey) [reply includes/Story_Renderer/HTML.php]: it is cleaner and improves test coverage. Also returning early to save one line seems a little crazy to me.

File: includes/Story_Renderer/HTML.php (hunk 6 above)
Comment (spacedmonkey) [reply includes/Story_Renderer/HTML.php:68]: Either remove it or use it.

File: includes/Story_Renderer/HTML.php (hunk 8 above)
Comment (spacedmonkey) [reply includes/Story_Renderer/HTML.php:86]: If that is the case, should you `@link` annotation.

File: includes/Story_Renderer/HTML.php (hunk 6 above)
Comment (swissspidy) [reply includes/Story_Renderer/HTML.php:68]: As I said, I forgot 😉 So yes, I'll add it.

File: includes/Story_Renderer/HTML.php [hunk 9]
```diff
@@ -191,6 +253,49 @@ protected function replace_html_head( $content ) {
...
+	 * That's why we temporarily remove this fragment and re-add it later.
+	 *
+	 * @see https://github.com/ampproject/amp-wp/pull/5097
+	 * @see http://xmlsoft.org/news.html
+	 *
+	 * @return void
+	 */
+	protected function add_noscript_amp_boilerplate() {
+		$fragment = $this->document->createDocumentFragment();
+		$fragment->appendXml(
```
Comment (westonruter) [inline includes/Story_Renderer/HTML.php]: Nice. I've never used `appendXml` before. Curious there is no `appendHtml`!

File: includes/Story_Renderer/HTML.php [hunk 10]
```diff
@@ -191,6 +253,49 @@ protected function replace_html_head( $content ) {
...
+	 *
+	 * @see https://github.com/ampproject/amp-wp/pull/5097
+	 * @see http://xmlsoft.org/news.html
+	 *
+	 * @param string $content Story markup.
+	 *
+	 * @return string Filtered content.
+	 */
+	protected function remove_noscript_amp_boilerplate( $content ) {
+		return str_replace( '<noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>', '', $content );
```
Comment (westonruter) [inline includes/Story_Renderer/HTML.php]: Minor thing: the string appears here and in `add_noscript_amp_boilerplate`. It could be put in a constant since the string literal is the same.

**Review by spacedmonkey — APPROVED** [review]
LGTM.

**Review by westonruter — APPROVED** [review]
LGTM, but I presume this will be very short-lived if we copy the `Document` class from the AMP plugin.
