### PR TITLE
Fix missing frame when selecting an element

### LINKED ISSUE #4857: Clicking an element selects it but doesn't show frame around it
## Bug Description
Sometimes, when clicking on an element, the frame around it doesn't show up even though the element is actually selected.

## Expected Behaviour
When an element gets selected, it should always display a selection frame around it.

## Steps to Reproduce
1. Add a story with a text element (or some)
2. Unselect the text (e.g. click on the page to select the page instead)
3. Now click once on the Text element
4. Repeat steps 2. and 3. until eventually you'll see the issue -- the element gets selected but frame won't show.
5. Additionally, sometimes it seems that a new history entry is created as well (See [Pascal's comment](https://github.com/google/web-stories-wp/issues/4857#issuecomment-706130418) below to reproduce this consistently.)

## Screenshots
lag

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Fixes setting an element being dragged.

## Testing Instructions
1. Add a Text element
2. Unselect it
3. Select it again by clicking once
4. Verify the selection lines show as expected.

---

Fixes #4857

### CODE REVIEW

File: assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js [hunk 1]
```diff
@@ -57,6 +58,9 @@ function useSingleSelectionDrag({
   );
 
   const onDrag = ({ target, beforeTranslate, clientX, clientY }) => {
+    if (!isDragging) {
+      setIsDragging(true);
+    }
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js]: I don't think the `if` is necessary here. If the `useState` is set to the same value it already has, nothing happens, so I don't think there's a problem with setting it to `true` every time it's moving around.

But it would be nice to make sure, that we don't get unnecessary re-renders, if this guard is removed.

**Review by barklund — APPROVED** [review]
This seems to work excellently - good find!

File: assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/singleSelectionMoveable/useDrag.js]: Looks like all good without it, will remove and send to QA, thanks!
