### PR TITLE
Dashboard: Allow sorting stories by author display names

### LINKED ISSUE #1744: Dashboard Stories on created_by sort should be alphabetical
## Bug Description

In the dashboard (https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/) when you sort stories by 'author' the current user's stories come first regardless of true alphabetization. 

## Expected Behaviour

This isn't so much a bug as updated specs. Now the story sort by author should just be a straight a - z (descending) or z -a (ascending). 

API for reference: **orderby=story_author** 
`wp/v2/web-story?context=edit&order=asc&orderby=story_author&page=1&per_page=10&status=publish%2Cdraft&_locale=user`

## Steps to Reproduce

Go to dashboard, sort stories by author. 

Reference PRs: 
- https://github.com/google/web-stories-wp/issues/1726
- https://github.com/google/web-stories-wp/pull/1737#issuecomment-627393762
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Verify that sorting stories on the dashboard by the author works, and that they're ordered by the displayed author name in the correct way (ascending and descending)

### PR DESCRIPTION
**Pull request by swissspidy**
## Relevant Technical Choices

Updates tests to actually test expected order.

## Testing Instructions

Open `wp-json/wp/v2/web-story/?orderby=story_author&order=asc` and `wp-json/wp/v2/web-story/?orderby=story_author&order=desc`

---

Fixes #1744

### CODE REVIEW

File: includes/REST_API/Stories_Controller.php [hunk 1]
```diff
@@ -157,26 +157,36 @@ public function get_item_schema() {
...
-			return $orderby;
+		// Usage of users/usermeta tables is highly discouraged in VIP context.
+		if ( defined( '\WPCOM_IS_VIP_ENV' ) && \WPCOM_IS_VIP_ENV ) {
+			return $clauses;
 		}
-		return $wpdb->prepare( 'wp_posts.post_author = %s DESC, wp_posts.post_author DESC, wp_posts.post_modified DESC', $current_user );
+
+		// phpcs:disable WordPressVIPMinimum.Variables.RestrictedVariables.user_meta__wpdb__users
+		$order              = strtoupper( $query->get( 'order' ) );
+		$order              = 'DESC' === $order ? 'DESC' : 'ASC';
```
Comment (swissspidy) [inline includes/REST_API/Stories_Controller.php]:
```suggestion
```

File: includes/REST_API/Stories_Controller.php [hunk 2]
```diff
@@ -157,26 +157,36 @@ public function get_item_schema() {
...
-		if ( ! $current_user ) {
-			return $orderby;
+		// Usage of users/usermeta tables is highly discouraged in VIP context.
+		if ( defined( '\WPCOM_IS_VIP_ENV' ) && \WPCOM_IS_VIP_ENV ) {
+			return $clauses;
 		}
-		return $wpdb->prepare( 'wp_posts.post_author = %s DESC, wp_posts.post_author DESC, wp_posts.post_modified DESC', $current_user );
+
+		// phpcs:disable WordPressVIPMinimum.Variables.RestrictedVariables.user_meta__wpdb__users
+		$order              = strtoupper( $query->get( 'order' ) );
```
Comment (swissspidy) [inline includes/REST_API/Stories_Controller.php]:
```suggestion
		$order              = $query->get( 'order' );
```

File: includes/REST_API/Stories_Controller.php [hunk 3]
```diff
@@ -157,26 +157,35 @@ public function get_item_schema() {
...
 		}
 		if ( 'story_author' !== $query->get( 'orderby' ) ) {
-			return $orderby;
+			return $clauses;
 		}
 
-		$current_user = get_current_user_id();
-		if ( ! $current_user ) {
-			return $orderby;
+		// Usage of users/usermeta tables is highly discouraged in VIP context.
```
Comment (spacedmonkey) [inline includes/REST_API/Stories_Controller.php]: If this not supported in VIP GO, then this option should be hidden in the UI. @BrittanyIRL Thoughts?

Comment (swissspidy) [reply includes/REST_API/Stories_Controller.php]: IMHO that's something for a separate issue to discuss, especially since  dashboard team lacks context here.

Why?

First of all, WP.com is currently far away and not really relevant. For now, this check is basically a failsafe to prevent breakage for the very unlikely event of someone trying this plugin on VIP.

Second, I assume that on WP.com / VIP there are other ways to achieve this kind of functionality. So once that platform becomes relevant, we can act as needed.

Third, we should not be disabling such a small UI  thing based on environment. We should much rather provide a fallback or alternative solution to achieve the same result.

Comment (swissspidy) [reply includes/REST_API/Stories_Controller.php]: Opened #2413 to track WP.com compatibility

**Review by spacedmonkey — APPROVED** [review]
LGTM
