### PR TITLE
Fix fullbleedRef console warning

### LINKED ISSUE #4042: Fix fullbleedRef console warning
## Task Description

Fix fullbleedRef console warning by adding the correct propTypes.

### PR DESCRIPTION
**Pull request by cvolzke4**
## Summary

Fix fullbleedRef console warning by adding a more specific PropTypes for ref.

Fixes #4042

### CODE REVIEW

File: assets/src/edit-story/components/canvas/layout.js [hunk 1]
```diff
@@ -240,7 +240,10 @@ PageArea.propTypes = {
   children: PropTypes.node,
   showSafeZone: PropTypes.bool,
   showOverflow: PropTypes.bool,
-  fullbleedRef: PropTypes.object,
+  fullbleedRef: PropTypes.oneOfType([
```
Comment (cvolzke4) [inline assets/src/edit-story/components/canvas/layout.js:243]: PropTypes.any may also be fine here

**Review by winterDroid — APPROVED** [review]

File: assets/src/edit-story/components/canvas/layout.js (hunk 1 above)
Comment (merapi) [reply assets/src/edit-story/components/canvas/layout.js:243]: How about [object + func](https://github.com/google/web-stories-wp/pull/3935#discussion_r470786239)? We use object for almost all refs.

Comment (cvolzke4) [reply assets/src/edit-story/components/canvas/layout.js:243]: I like that better, since it fits on one line and is more consistent with the rest of the codebase.
Updated here: https://github.com/google/web-stories-wp/pull/4070

Adding any kind of type is kind of futile, since it's unlikely a developer would pass anything other than a ref to a ref, since it's clearly labelled as a ref. I'm surprised PropTypes doesn't yet have its own type for refs though, perhaps we could add our own sometime for Story Editor.
