### PR TITLE
Save snapshots on e2e test failures

### LINKED ISSUE #7550: E2E Tests: take screenshots on failures
## Task Description

Taking screenshots when an e2e test fails on CI would make it much easier for us to debug.

Some prior art:

https://github.com/WordPress/gutenberg/pull/26664
https://github.com/WordPress/gutenberg/pull/28449

Just like for #7549, it would mean using `jest-circus` as the test runner due to the events it emits to make this easier.

We could try using Percy for the screenshots, but storing them as GitHub Actions artifacts is cheaper.

### PR DESCRIPTION
**Pull request by swissspidy**
## Relevant Technical Choices

Uses a similar approach than what Gutenberg ended up doing. Just without forking the `jest-environment-puppeteer` dependency.

## To-do

A PR comment with a link to the uploaded artifact could be nice, making it easier discoverable.

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7550

### CODE REVIEW

File: packages/e2e-tests/src/puppeteerEnvironment.js [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+const ARTIFACTS_PATH =
+  process.env.E2E_ARTIFACTS_PATH ||
+  (process.env.GITHUB_WORKSPACE || process.cwd()) + '/build/e2e-artifacts';
+
+class PuppeteerEnvironment extends OriginalEnvironment {
+  async setup() {
+    await super.setup();
+
+    try {
+      await mkdir(ARTIFACTS_PATH);
```
Comment (timarney) [inline packages/e2e-tests/src/puppeteerEnvironment.js]: Do you need need to pass  { recursive: true }  or does the build folder exist at this point and you only need `e2e-artifacts`

await mkdir(ARTIFACTS_PATH,  { recursive: true } );

Comment (swissspidy) [reply packages/e2e-tests/src/puppeteerEnvironment.js]: Yeah I forgot the recursive option

**Review by timarney — APPROVED** [review]
💯
