### PR TITLE
Background Audio: Fix video not loading

### LINKED ISSUE #11660: Background Audio: Video failed to play
## Bug Description

While testing something else I just noticed that background audio with captions was not loading anymore in the browser. Perhaps something has changed on the AMP side.

All I get when viewing the story is a "Video failed to play" message and no audio nor captions.

## Expected Behaviour

Audio should load, captions should display

## Steps to Reproduce

1. Add page background audio
2. Add captions
3. Preview story

## Screenshots

Screenshot 2022-06-09 at 14 46 11
Screenshot 2022-06-09 at 14 43 13

## Additional Context

- Plugin Version: 1.21.1
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome, Firefox, Safari

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

While testing something else I just noticed that background audio with captions was not loading anymore in the browser. Perhaps something has changed on the AMP side.

All I get when viewing the story is a "Video failed to play" message and no audio nor captions.

## Summary

Uses different layout for the “hidden” `<amp-video>` to ensure the audio file is properly loaded.

## User-facing changes

No more "Video failed to play" message displayed:

Screenshot 2022-06-09 at 14 43 30

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add page background audio
2. Add captions
3. Preview story
4. Verify that audio is played and captions are displayed

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11660

### CODE REVIEW

File: packages/output/src/utils/backgroundAudio.js [hunk 1]
```diff
@@ -44,7 +44,13 @@ function BackgroundAudio({ backgroundAudio, id }) {
     <amp-story-grid-layer template="fill">
       <amp-video
         autoPlay="autoplay"
-        layout="nodisplay"
+        // Not using nolayout here, because it might cause the audio to
```
Comment (swissspidy) [inline packages/output/src/utils/backgroundAudio.js]:
```suggestion
        // Not using "nodisplay" here, because it might cause the audio to
```

**Comment by spacedmonkey** [comment]
I am not seeing the camptions render at all. I am also seeing this attribute in the markup. `data-amp-unvalidated-attrs="src"` on the source attribute.

**Comment by swissspidy** [comment]
Can you share a screenshot or video or maybe the URL to the story that you've created? Otherwise I can't really help with that.

Did you upload the audio/caption or hotlink it?

What browser are you using?

**Comment by spacedmonkey** [comment]
Markup

```
<!DOCTYPE html>
<html amp="" lang="en-US" transformed="self;v=1" i-amphtml-layout=""><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,minimum-scale=1"><link rel="modulepreload" href="https://cdn.ampproject.org/v0.mjs" as="script" crossorigin="anonymous"><link rel="preconnect" href="https://cdn.ampproject.org/"><link rel="preload" as="script" href="https://cdn.ampproject.org/v0/amp-story-1.0.js"><style amp-runtime="" i-amphtml-version="012205270638000">html{overflow-x:hidden!important}html.i-amphtml-fie{height:100%!important;width:100%!important}html:not([amp4ads]),html:not([amp4ads]) body{height:auto!important}html:not([amp4ads]) body{margin:0!important}body{-webkit-text-size-adjust:100%;-moz-text-size-adjust:100%;-ms-text-size-adjust:100%;text-size-adjust:100%}html.i-amphtml-singledoc.i-amphtml-embedded{-ms-touch-action:pan-y pinch-zoom;touch-action:pan-y pinch-zoom}html.i-amphtml-fie>body,html.i-amphtml-singledoc>body{overflow:visible!important}html.i-amphtml-fie:not(.i-amphtml-inabox)>body,html.i-amphtml-singledoc:not(.i-amphtml-inabox)>body{position:relative!important}html.i-amphtml-ios-embed-legacy>body{overflow-x:hidden!important;overflow-y:auto!important;position:absolute!important}html.i-amphtml-ios-embed{overflow-y:auto!important;position:static}#i-amphtml-wrapper{overflow-x:hidden!important;overflow-y:auto!important;position:absolute!important;top:0!important;left:0!important;right:0!important;bottom:0!important;margin:0!important;display:block!important}html.i-amphtml-ios-embed.i-amphtml-ios-overscroll,html.i-amphtml-ios-embed.i-amphtml-ios-overscroll>#i-amphtml-wrapper{-webkit-overflow-scrolling:touch!important}#i-amphtml-wrapper>body{position:relative!important;border-top:1px solid transparent!important}#i-amphtml-wrapper+body{visibility:visible}#i-amphtml-wrapper+body .i-amphtml-lightbox-element,#i-amphtml-wrapper+body[i-amphtml-lightbox]{visibility:hidden}#i-amphtml-wrapper+body[i-amphtml-lightbox] .i-amphtml-lightbox-element{visibility:visible}#i-amphtml-wrapper.i-amphtml-scroll-disabled,.i-amphtml-scroll-disabled{overflow-x:hidden!important;overflow-y:hidden!important}amp-instagram{padding:54px 0px 0px!important;background-color:#fff}amp-iframe iframe{box-sizing:border-box!important}[amp-access][amp-access-hide]{display:none}[subscriptions-dialog],body:not(.i-amphtml-subs-ready) [subscriptions-action],body:not(.i-amphtml-subs-ready) [subscriptions-section]{display:none!important}amp-experiment,amp-live-list>[update]{display:none}amp-list[resizable-children]>.i-amphtml-loading-container.amp-hidden{display:none!important}amp-list [fetch-error],amp-list[load-more] [load-more-button],amp-list[load-more] [load-more-end],amp-list[load-more] [load-more-failed],amp-list[load-more] [load-more-loading]{display:none}amp-list[diffable] div[role=list]{display:block}amp-story-page,amp-story[standalone]{min-height:1px!important;display:block!important;height:100%!important;margin:0!important;padding:0!important;overflow:hidden!important;width:100%!important}amp-story[standalone]{background-color:#000!important;position:relative!important}amp-story-page{background-color:#757575}amp-story .amp-active>div,amp-story .i-amphtml-loader-background{display:none!important}amp-story-page:not(:first-of-type):not([distance]):not([active]){transform:translateY(1000vh)!important}amp-autocomplete{position:relative!important;display:inline-block!important}amp-autocomplete>input,amp-autocomplete>textarea{padding:0.5rem;border:1px solid rgba(0,0,0,0.33)}.i-amphtml-autocomplete-results,amp-autocomplete>input,amp-autocomplete>textarea{font-size:1rem;line-height:1.5rem}[amp-fx^=fly-in]{visibility:hidden}amp-script[nodom],amp-script[sandboxed]{position:fixed!important;top:0!important;width:1px!important;height:1px!important;overflow:hidden!important;visibility:hidden}
/*# sourceURL=/css/ampdoc.css*/[hidden]{display:none!important}.i-amphtml-element{display:inline-block}.i-amphtml-blurry-placeholder{transition:opacity 0.3s cubic-bezier(0.0,0.0,0.2,1)!important;pointer-events:none}[layout=nodisplay]:not(.i-amphtml-element){display:none!important}.i-amphtml-layout-fixed,[layout=fixed][width][height]:not(.i-amphtml-layout-fixed){display:inline-block;position:relative}.i-amphtml-layout-responsive,[layout=responsive][width][height]:not(.i-amphtml-layout-responsive),[width][height][heights]:not([layout]):not(.i-amphtml-layout-responsive),[width][height][sizes]:not(img):not([layout]):not(.i-amphtml-layout-responsive){display:block;position:relative}.i-amphtml-layout-intrinsic,[layout=intrinsic][width][height]:not(.i-amphtml-layout-intrinsic){display:inline-block;position:relative;max-width:100%}.i-amphtml-layout-intrinsic .i-amphtml-sizer{max-width:100%}.i-amphtml-intrinsic-sizer{max-width:100%;display:block!important}.i-amphtml-layout-container,.i-amphtml-layout-fixed-height,[layout=container],[layout=fixed-height][height]:not(.i-amphtml-layout-fixed-height){display:block;position:relative}.i-amphtml-layout-fill,.i-amphtml-layout-fill.i-amphtml-notbuilt,[layout=fill]:not(.i-amphtml-layout-fill),body noscript>*{display:block;overflow:hidden!important;position:absolute;top:0;left:0;bottom:0;right:0}body noscript>*{position:absolute!important;width:100%;height:100%;z-index:2}body noscript{display:inline!important}.i-amphtml-layout-flex-item,[layout=flex-item]:not(.i-amphtml-layout-flex-item){display:block;position:relative;-ms-flex:1 1 auto;flex:1 1 auto}.i-amphtml-layout-fluid{position:relative}.i-amphtml-layout-size-defined{overflow:hidden!important}.i-amphtml-layout-awaiting-size{position:absolute!important;top:auto!important;bottom:auto!important}i-amphtml-sizer{display:block!important}@supports (aspect-ratio:1/1){i-amphtml-sizer.i-amphtml-disable-ar{display:none!important}}.i-amphtml-blurry-placeholder,.i-amphtml-fill-content{display:block;height:0;max-height:100%;max-width:100%;min-height:100%;min-width:100%;width:0;margin:auto}.i-amphtml-layout-size-defined .i-amphtml-fill-content{position:absolute;top:0;left:0;bottom:0;right:0}.i-amphtml-replaced-content,.i-amphtml-screen-reader{padding:0!important;border:none!important}.i-amphtml-screen-reader{position:fixed!important;top:0px!important;left:0px!important;width:4px!important;height:4px!important;opacity:0!important;overflow:hidden!important;margin:0!important;display:block!important;visibility:visible!important}.i-amphtml-screen-reader~.i-amphtml-screen-reader{left:8px!important}.i-amphtml-screen-reader~.i-amphtml-screen-reader~.i-amphtml-screen-reader{left:12px!important}.i-amphtml-screen-reader~.i-amphtml-screen-reader~.i-amphtml-screen-reader~.i-amphtml-screen-reader{left:16px!important}.i-amphtml-unresolved{position:relative;overflow:hidden!important}.i-amphtml-select-disabled{-webkit-user-select:none!important;-ms-user-select:none!important;user-select:none!important}.i-amphtml-notbuilt,[layout]:not(.i-amphtml-element),[width][height][heights]:not([layout]):not(.i-amphtml-element),[width][height][sizes]:not(img):not([layout]):not(.i-amphtml-element){position:relative;overflow:hidden!important;color:transparent!important}.i-amphtml-notbuilt:not(.i-amphtml-layout-container)>*,[layout]:not([layout=container]):not(.i-amphtml-element)>*,[width][height][heights]:not([layout]):not(.i-amphtml-element)>*,[width][height][sizes]:not([layout]):not(.i-amphtml-element)>*{display:none}amp-img:not(.i-amphtml-element)[i-amphtml-ssr]>img.i-amphtml-fill-content{display:block}.i-amphtml-notbuilt:not(.i-amphtml-layout-container),[layout]:not([layout=container]):not(.i-amphtml-element),[width][height][heights]:not([layout]):not(.i-amphtml-element),[width][height][sizes]:not(img):not([layout]):not(.i-amphtml-element){color:transparent!important;line-height:0!important}.i-amphtml-ghost{visibility:hidden!important}.i-amphtml-element>[placeholder],[layout]:not(.i-amphtml-element)>[placeholder],[width][height][heights]:not([layout]):not(.i-amphtml-element)>[placeholder],[width][height][sizes]:not([layout]):not(.i-amphtml-element)>[placeholder]{display:block;line-height:normal}.i-amphtml-element>[placeholder].amp-hidden,.i-amphtml-element>[placeholder].hidden{visibility:hidden}.i-amphtml-element:not(.amp-notsupported)>[fallback],.i-amphtml-layout-container>[placeholder].amp-hidden,.i-amphtml-layout-container>[placeholder].hidden{display:none}.i-amphtml-layout-size-defined>[fallback],.i-amphtml-layout-size-defined>[placeholder]{position:absolute!important;top:0!important;left:0!important;right:0!important;bottom:0!important;z-index:1}amp-img[i-amphtml-ssr]:not(.i-amphtml-element)>[placeholder]{z-index:auto}.i-amphtml-notbuilt>[placeholder]{display:block!important}.i-amphtml-hidden-by-media-query{display:none!important}.i-amphtml-element-error{background:red!important;color:#fff!important;position:relative!important}.i-amphtml-element-error:before{content:attr(error-message)}i-amp-scroll-container,i-amphtml-scroll-container{position:absolute;top:0;left:0;right:0;bottom:0;display:block}i-amp-scroll-container.amp-active,i-amphtml-scroll-container.amp-active{overflow:auto;-webkit-overflow-scrolling:touch}.i-amphtml-loading-container{display:block!important;pointer-events:none;z-index:1}.i-amphtml-notbuilt>.i-amphtml-loading-container{display:block!important}.i-amphtml-loading-container.amp-hidden{visibility:hidden}.i-amphtml-element>[overflow]{cursor:pointer;position:relative;z-index:2;visibility:hidden;display:initial;line-height:normal}.i-amphtml-layout-size-defined>[overflow]{position:absolute}.i-amphtml-element>[overflow].amp-visible{visibility:visible}template{display:none!important}.amp-border-box,.amp-border-box *,.amp-border-box :after,.amp-border-box :before{box-sizing:border-box}amp-pixel{display:none!important}amp-analytics,amp-auto-ads,amp-story-auto-ads{position:fixed!important;top:0!important;width:1px!important;height:1px!important;overflow:hidden!important;visibility:hidden}amp-story{visibility:hidden!important}html.i-amphtml-fie>amp-analytics{position:initial!important}[visible-when-invalid]:not(.visible),form [submit-error],form [submit-success],form [submitting]{display:none}amp-accordion{display:block!important}@media (min-width:1px){:where(amp-accordion>section)>:first-child{margin:0;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}:where(amp-accordion>section)>:last-child{margin:0}}amp-accordion>section{float:none!important}amp-accordion>section>*{float:none!important;display:block!important;overflow:hidden!important;position:relative!important}amp-accordion,amp-accordion>section{margin:0}amp-accordion:not(.i-amphtml-built)>section>:last-child{display:none!important}amp-accordion:not(.i-amphtml-built)>section[expanded]>:last-child{display:block!important}
/*# sourceURL=/css/ampshared.css*/</style><meta name="amp-story-generator-name" content="Web Stories for WordPress"><meta name="amp-story-generator-version" content="1.22.0-alpha.0"><meta name="robots" content="max-image-preview:large"><meta name="description" content=""><meta property="og:locale" content="en-US"><meta property="og:site_name" content="Web Stories Dev"><meta property="og:type" content="article"><meta property="og:title" content=""><meta property="og:url" content="http://localhost:8899/web-stories/161"><meta property="og:description" content=""><meta property="article:published_time" content="2022-06-09T14:13:07+00:00"><meta property="article:modified_time" content="2022-06-09T14:18:33+00:00"><meta name="twitter:card" content="summary_large_image"><meta name="generator" content="WordPress 6.0"><link rel="dns-prefetch" href="[//s.w.org](http://s.w.org/)"><script async="" src="https://cdn.ampproject.org/v0.mjs" type="module" crossorigin="anonymous"></script><script async nomodule src="https://cdn.ampproject.org/v0.js" crossorigin="anonymous"></script><script async="" src="https://cdn.ampproject.org/v0/amp-story-1.0.mjs" custom-element="amp-story" type="module" crossorigin="anonymous"></script><script async nomodule src="https://cdn.ampproject.org/v0/amp-story-1.0.js" crossorigin="anonymous" custom-element="amp-story"></script><script async="" src="https://cdn.ampproject.org/v0/amp-story-captions-0.1.mjs" custom-element="amp-story-captions" type="module" crossorigin="anonymous"></script><script async nomodule src="https://cdn.ampproject.org/v0/amp-story-captions-0.1.js" crossorigin="anonymous" custom-element="amp-story-captions"></script><script async="" src="https://cdn.ampproject.org/v0/amp-video-0.1.mjs" custom-element="amp-video" type="module" crossorigin="anonymous"></script><script async nomodule src="https://cdn.ampproject.org/v0/amp-video-0.1.js" crossorigin="anonymous" custom-element="amp-video"></script><style amp-custom="">amp-story-page{background-color:#131516}amp-story-grid-layer{overflow:visible}@media (max-aspect-ratio: 9 / 16){@media (min-aspect-ratio: 320 / 678){amp-story-grid-layer.grid-layer{margin-top:calc(( 100% / .5625 - 100% / .66666666666667 ) / 2)}}}.page-fullbleed-area{position:absolute;overflow:hidden;width:100%;left:0;height:calc(1.1851851851852 * 100%);top:calc(( 1 - 1.1851851851852 ) * 100% / 2)}.page-safe-area{overflow:visible;position:absolute;top:0;bottom:0;left:0;right:0;width:100%;height:calc(.84375 * 100%);margin:auto 0}.mask{position:absolute;overflow:hidden}.fill{position:absolute;top:0;left:0;right:0;bottom:0;margin:0}amp-story-grid-layer.align-bottom{align-content:end;padding:0}.captions-area{padding:0 32px 0}amp-story-captions{margin-bottom:16px;text-align:center}amp-story-captions span{display:inline-block;margin:0;padding:6px 12px;vertical-align:middle;border-radius:15px;background:rgba(11,11,11,.6);color:rgba(255,255,255,1);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;font-size:calc(4 * var(--story-page-vw));line-height:1.4;word-break:break-word;word-wrap:break-word;overflow-wrap:break-word}._c84718f{background-color:#fff}._6120891{position:absolute;pointer-events:none;left:0;top:-9.25926%;width:100%;height:118.51852%;opacity:1}._89d52dd{pointer-events:initial;width:100%;height:100%;display:block;position:absolute;top:0;left:0;z-index:0}._dc67a5c{will-change:transform}

/*# sourceURL=amp-custom.css */</style><link rel="alternate" type="application/rss+xml" title="Web Stories Dev » Feed" href="http://localhost:8899/feed"><link rel="alternate" type="application/rss+xml" title="Web Stories Dev » Comments Feed" href="http://localhost:8899/comments/feed"><link rel="alternate" type="application/rss+xml" title="Web Stories Dev » Stories Feed" href="http://localhost:8899/web-stories/feed/"><title>Web Stories Dev</title><script type="application/ld+json">{"@context":"http:\/\/schema.org","publisher":{"@type":"Organization","name":"Web Stories Dev","logo":{"@type":"ImageObject","url":"http:\/\/localhost:8899\/wp-content\/uploads\/2019\/01\/cropped-vneck-tee-2-4-96x96.jpg","width":96,"height":96}},"@type":"Article","mainEntityOfPage":"http:\/\/localhost:8899\/web-stories\/161","headline":"","datePublished":"2022-06-09T14:13:07+00:00","dateModified":"2022-06-09T14:18:33+00:00","author":{"@type":"Person","name":"admin"}}</script><link rel="https://api.w.org/" href="http://localhost:8899/wp-json/"><link rel="alternate" type="application/json" href="http://localhost:8899/wp-json/web-stories/v1/web-story/161"><link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://localhost:8899/xmlrpc.php?rsd"><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://localhost:8899/wp-includes/wlwmanifest.xml"><link rel="prev" title="Previous Post" href="http://localhost:8899/web-stories/157"><link rel="canonical" href="http://localhost:8899/web-stories/161"><link rel="shortlink" href="http://localhost:8899/?p=161"><link rel="alternate" type="application/json+oembed" href="http://localhost:8899/wp-json/oembed/1.0/embed?url=http%3A%2F%2Flocalhost%3A8899%2Fweb-stories%2F161"><link rel="alternate" type="text/xml+oembed" href="[http://localhost:8899/wp-json/oembed/1.0/embed?url=http%3A%2F%2Flocalhost%3A8899%2Fweb-stories%2F161&amp;format=xml](http://localhost:8899/wp-json/oembed/1.0/embed?url=http%3A%2F%2Flocalhost%3A8899%2Fweb-stories%2F161&format=xml)"><script amp-onerror="">document.querySelector("script[src*='/v0.js']").onerror=function(){document.querySelector('style[amp-boilerplate]').textContent=''}</script><style amp-boilerplate="">body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate="">body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript><link rel="stylesheet" amp-extension="amp-story" href="https://cdn.ampproject.org/v0/amp-story-1.0.css"><script amp-story-dvh-polyfill="">"use strict";if(!self.CSS||!CSS.supports||!CSS.supports("height:1dvh")){function e(){document.documentElement.style.setProperty("--story-dvh",innerHeight/100+"px","important")}addEventListener("resize",e,{passive:!0}),e()}</script></head><body><amp-story standalone="" publisher="Web Stories Dev" publisher-logo-src="http://localhost:8899/wp-content/uploads/2019/01/cropped-vneck-tee-2-4.jpg" title="" poster-portrait-src="" data-amp-unvalidated-attrs="poster-portrait-src" class="i-amphtml-layout-container" i-amphtml-layout="container"><amp-story-page id="82cb6761-a05d-4636-a927-322d60ccdc62" auto-advance-after="7s" class="i-amphtml-layout-container" i-amphtml-layout="container"><amp-story-grid-layer template="vertical" aspect-ratio="412:618" class="grid-layer i-amphtml-layout-container" i-amphtml-layout="container" style="--aspect-ratio:412/618;"><div class="_c84718f page-fullbleed-area"><div class="page-safe-area"><div class="_6120891"><div class="_89d52dd mask" id="el-d89cb6b8-071b-45c3-b60f-07d920d35742"><div class="_dc67a5c fill"></div></div></div></div></div></amp-story-grid-layer><amp-story-grid-layer template="vertical" aspect-ratio="412:618" class="grid-layer i-amphtml-layout-container" i-amphtml-layout="container" style="--aspect-ratio:412/618;"><div class="page-fullbleed-area"><div class="page-safe-area"></div></div></amp-story-grid-layer><amp-story-grid-layer template="fill" class="i-amphtml-layout-container" i-amphtml-layout="container"><amp-video autoplay="autoplay" layout="fixed" width="1" height="1" poster="" loop="loop" id="page-82cb6761-a05d-4636-a927-322d60ccdc62-background-audio" captions-id="el-82cb6761-a05d-4636-a927-322d60ccdc62-captions" crossorigin="anonymous" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px" i-amphtml-layout="fixed"><source type="audio/mpeg" src="http://localhost:8899/wp-content/uploads/2022/06/sample-15s.mp3" data-amp-unvalidated-attrs="src"></amp-video></amp-story-grid-layer><amp-story-grid-layer template="vertical" aspect-ratio="412:618" class="grid-layer align-bottom i-amphtml-layout-container" i-amphtml-layout="container" style="--aspect-ratio:412/618;"><div class="captions-area"><amp-story-captions id="el-82cb6761-a05d-4636-a927-322d60ccdc62-captions" layout="fixed-height" height="100" class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined" style="height:100px" i-amphtml-layout="fixed-height"></amp-story-captions></div></amp-story-grid-layer></amp-story-page><amp-story-social-share layout="nodisplay" class="i-amphtml-layout-nodisplay" hidden="hidden" i-amphtml-layout="nodisplay"><script type="application/json">{"shareProviders":[{"provider":"twitter"},{"provider":"linkedin"},{"provider":"email"},{"provider":"system"}]}</script></amp-story-social-share></amp-story></body></html>

```

https://user-images.githubusercontent.com/237508/172870251-12493c45-baed-4c6c-b6e1-8866bd5821f8.mov

Chrome 102.0.5005.61 
WP 6.0. 
Mac OS 12.3

**Review by spacedmonkey — APPROVED** [review]
The issue was with a lack of SSL. Patch looks good to me.

**Review by timarney — APPROVED** [review]
