### PR TITLE
Redirect for child pages with stories slug

### LINKED ISSUE #5128: Redirect for child pages with stories slug
## Bug Description

Redirect from /stories to /web-stories redirects all pages that have slug _stories_. For example, _example.com/client/stories_ redirects to _example.com/web-stories_ 

## Expected Behaviour

_example.com/client/stories_ does not redirect to _example.com/web-stories_, _example.com/stories_ redirects to _example.com/web-stories_

## Steps to Reproduce

Create child page with the slug _stories_ under any parent page.
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Check to see it is just stories in only part of the slug 

## Relevant Technical Choices

`query` property is different from `query_vars`.

## Testing Instructions

---

Fixes #5128

### CODE REVIEW

File: includes/Story_Post_Type.php [hunk 1]
```diff
@@ -789,9 +789,9 @@ public function redirect_post_type_archive_urls( $bypass, $query ) {
 		if ( ! $wp_rewrite instanceof \WP_Rewrite || ! $wp_rewrite->using_permalinks() ) {
 			return $bypass;
 		}
-
+
```
Comment (swissspidy) [inline includes/Story_Post_Type.php]: This whitespace snuck in

```suggestion

```

**Comment by spacedmonkey** [comment]
Found another issue while working on this ticket. I have created a breakout issue. https://github.com/google/web-stories-wp/issues/5211

**Review by swissspidy — APPROVED** [review]
