### PR TITLE
Bug: Page should not advance until last animation is completed

### LINKED ISSUE #5416: Page should not advance until last animation is completed
## Bug Description

When page duration is set to auto, it should wait until the last animation is done before advancing to the next page

## Expected Behaviour

Last animation in queue should complete in entirety before the next page of the story is shown, even when auto-advance is set to true.

## Steps to Reproduce

1. Create a new story and set auto-advance to true
2. Create a page with a couple of animations that together are longer than the previously set auto-advance value
3. Note that on playback the page advances prior to completion of animations.
badAnimation_Timing

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Respects animation duration in calculating auto advance duration for amp-story generation.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
NA, Behind animation flag: Now respects animation duration on calculating page duration.

## Testing Instructions
- enable animation flag
- create new story in the editor with auto advance
- create page with no video & no animations -> click preview -> see that default duration is respected (7s)
- add an animation to page -> click preview -> see that page duration is duration of animation
- add a non looping video to page that's longer than longest animation -> click preview -> see that page duration is duration of video
- add a non looping video to page that's shorter than longest animation -> click preview -> see that page duration is duration of animation

---

Fixes #5416

### CODE REVIEW

File: assets/src/animation/utils/getTotalDuration.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+export function getTotalDuration({ animations = [] }) {
+  return animations.reduce(
+    (total, { duration = 0, delay = 0 }) => Math.max(total, duration + delay),
```
Comment (carloskelly13) [inline assets/src/animation/utils/getTotalDuration.js:19]: Could you imagine an instance where these values are not numbers?

**Review by carloskelly13 — APPROVED** [review]

File: assets/src/animation/utils/getTotalDuration.js (hunk 1 above)
Comment (maxyinger) [reply assets/src/animation/utils/getTotalDuration.js:19]: Nope. But I can add some checks if you'd like. This is where TS would be nice to ensure that

**Review by BrittanyIRL — APPROVED** [review]
LGTM! I like that you pulled the `getTotalDuration` into its own file. Tested a bunch of combos and tried updating the default timing too - works great!
