### PR TITLE
Embeds: Use native `<img>` instead of `<amp-img>`

### LINKED ISSUE #10213: Renderer: Use native `<img>` instead of `<amp-img`
## Feature Description

With `amp-img` being deprecated in favor of native `img` (https://github.com/ampproject/amphtml/issues/30442), we can now finally stop using `amp-img` by default.

The AMP plugin v2.3 (coming out soon) will make the switch as well. See https://github.com/ampproject/amp-wp/pull/6805

We're currently using `amp-img` here:

https://github.com/google/web-stories-wp/blob/e7cb5fe4dee961dbfc318dbc7b3c75b3373b6a02/includes/Renderer/Stories/Renderer.php#L594-L613

We should:

1. Remove that condition and use `img` only
2. Use `loading="lazy"` and `decoding="async"` for `img`
2. update any CSS targeting `amp-img` 
3. Verify that there are no regressions when viewing the AMP version  of a post

## Additional Context

**Note:** This does not apply to stories, i.e. `<amp-story>` remains unaffected.

### PR DESCRIPTION
**Pull request by RahiDroid**
## Context
- With the introduction of sandboxing levels (check https://github.com/ampproject/amp-wp/pull/6546) in [AMP 2.2.0 release](https://github.com/ampproject/amp-wp/releases/tag/2.2.0), it was noticed that the Web Stories' poster images weren't rendering properly.

## Summary
- The PR removes the `<amp-img/>` element from the markup so the native `` HTML element will be used on both AMP & Non-AMP pages.

## Relevant Technical Choices
- The issue of Poster images not rendering properly happened in the first place because the `amp-img` tag had some missing styles which were only given for the `img` tag (non-AMP page), and since there's no CSS processing happening on the `Loose` sandboxing level, the AMP plugin wasn't adding in the styles for `amp-img`.
- adding the missing styles could've also fixed the issue but since `amp-img` is going to be deprecated soon, it makes sense to remove the markup entirely.

## Testing Instructions
- Install latest (2.2.0) [AMP Plugin](https://wordpress.org/plugins/amp/) from the Plugins directory.
- Install latest (1.15.1) [Web Stories plugin](https://wordpress.org/plugins/web-stories/) from the Plugins directory.
- Enable the `Loose` experimental sandboxing level. You'll have to have the AMP running on `Standard` mode for this option to be visible.
Screenshot 2022-01-17 at 7 42 12 PM
- Add the `Web Stories` block on a post or a page. By default, if there's no AMP-invalid markup on a page, the AMP plugin will switch to higher/stricter sandboxing levels automatically, if that's the case, you can add a `Custom HTML` core block with some invalid AMP content (`<script></script>` will do the job).
- Visit the page/post on front-end and check the Poster images of the Web Stories block aren't being rendered properly.
- Make sure on the admin-bar, you see the sandboxing level is set to `Loose/1`.
Screenshot 2022-01-17 at 7 46 38 PM

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Checkout the branch and you can follow instructions mentioned above.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

## Screenshots
- Before
Screenshot 2022-01-14 at 11 21 26 PM

- After
Screenshot 2022-01-14 at 11 23 53 PM

Fixes #10213

### CODE REVIEW

File: includes/Renderer/Stories/Renderer.php [hunk 1]
```diff
@@ -591,26 +591,14 @@ protected function render_story_with_poster() {
...
-							height="<?php echo absint( $this->height ); ?>"
-						>
-					<?php } ?>
+					<img
+						src="<?php echo esc_url( $poster_url ); ?>"
+						alt="<?php echo esc_attr( $story->get_title() ); ?>"
+						width="<?php echo absint( $this->width ); ?>"
+						height="<?php echo absint( $this->height ); ?>"
+						loading="lazy"
+						decoding="async"
```
Comment (spacedmonkey) [inline includes/Renderer/Stories/Renderer.php:600]: These changes to reasonable to me, but just want to confirm adding these attributes is the right thing. CC @swissspidy

**Comment by spacedmonkey** [comment]
Should the following be removed as well. 
https://github.com/google/web-stories-wp/blob/663c75726e4baf410b9b4f52f737ba26abbea3b9/includes/KSES.php#L578-L596 

and references in [Sanitization_Utils.php](https://github.com/google/web-stories-wp/blob/663c75726e4baf410b9b4f52f737ba26abbea3b9/includes/AMP/Traits/Sanitization_Utils.php).

File: includes/Renderer/Stories/Renderer.php (hunk 1 above)
Comment (swissspidy) [reply includes/Renderer/Stories/Renderer.php:600]: Yes. Without these it would be invalid AMP. I explicitly mentioned these in #10213 as well.

**Comment by swissspidy** [comment]
Thanks for bringing this up.


We still need the `amp-img` references in KSES. That should be left untouched.

They are for single stories, not embeds.

Single stories remain unaffected by this, as they still require `amp-img`

File: includes/Renderer/Stories/Renderer.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/Renderer/Stories/Renderer.php:600]: Just confirming, no need to thumbs down 😢  . Should, implies some wiggle room, if it needs it, maybe you that wording.

Comment (swissspidy) [reply includes/Renderer/Stories/Renderer.php:600]: I swear this was meant to be a thumbs up

**Review by spacedmonkey — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
Works like a charm!
