### PR TITLE
Custom Fonts: Add error handling for duplicates

### LINKED ISSUE #10941: Custom Fonts: Error handling for duplicates
## Feature Description

The REST API returns an error if trying to add the same font twice, but the Settings page does not handle that.

Steps to reproduce:

1. Try to add font `https://overpass-30e2.kxcdn.com/overpass-regular.ttf`
2. See font being added
3. Try to add same font `https://overpass-30e2.kxcdn.com/overpass-regular.ttf`
4. See nothing happens

If the REST API returns a `rest_invalid_field` error, we should display a snackbar message with the text `A font with this name already exists`.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Errors when trying to add the same font again, are not currently handled. Show a error message when font is trying to be re-added. 

## User-facing changes

Screenshot 2022-03-21 at 12 20 51

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:
1. Enable custom font experiment. 
2. Login as admin and go to dashboard.
3. add font https://overpass-30e2.kxcdn.com/overpass-regular.ttf
4. See font being added
5. Add same font https://overpass-30e2.kxcdn.com/overpass-regular.ttf
6. See error message. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10941

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Screenshot 2022-03-21 at 12 20 51

@swissspidy Instead of using a snackbar message as recommended. I have used this input error before the text box. All other errors for this feature is handled this way. If we use snackbar here, we should change it other places that error, for consistency.

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js [hunk 1]
```diff
@@ -187,47 +187,57 @@ function CustomFontsSettings({
...
-      let canFetch = false;
       try {
         await fetch(urlWithProtocol, {
           method: 'HEAD',
         });
-        canFetch = true;
       } catch (err) {
         setInputError(
           __(
             'Please ensure correct CORS settings for allowing font usage on this site.',
```
Comment (timarney) [inline packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:214]: Not for this PR but the error handling here seems off i.e. a 404 will end up with `this could be any error not just a CORS error`

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js [hunk 2]
```diff
@@ -187,47 +187,57 @@ function CustomFontsSettings({
...
-                'Getting font data failed, please ensure the URL points directly to a %s file.',
-                'web-stories'
-              ),
-              translateToExclusiveList(ALLOWED_FONT_TYPES)
-            )
+            __('Something went wrong, please try again.', 'web-stories')
           );
+          return;
         }
+      } catch (err) {
```
Comment (timarney) [inline packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:232]: Do you need the `err` here?

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js [hunk 3]
```diff
@@ -187,47 +187,57 @@ function CustomFontsSettings({
...
+          )
+        );
+        return;
+      }
+
+      try {
+        await addCustomFont({ ...fontData, url: urlWithProtocol });
+        await fetchCustomFonts();
+        setFontUrl('');
+      } catch (err) {
```
Comment (timarney) [inline packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:251]: unused `err` here

**Comment by timarney** [comment]
Works well for the `duplicate font` use case.

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js (hunk 1 above)
Comment (swissspidy) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:214]: How so? 404s are not throwing errors to be caught AFAIK

Comment (timarney) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:214]: Tested use `https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.tt` vs `https://overpass-30e2.kxcdn.com/overpass-extrabold-italic.ttf`

Screen Shot 2022-03-22 at 6 10 36 AM

Comment (timarney) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:214]: Never mind --- it is catching for the CORS error

Tried direct in the browser

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js [hunk 4]
```diff
@@ -187,47 +187,57 @@ function CustomFontsSettings({
...
+        setInputError(
+          sprintf(
+            /* translators: %s: font name. */
+            __('A font with this name %s already exists.', 'web-stories'),
```
Comment (swissspidy) [inline packages/wp-dashboard/src/components/editorSettings/customFonts/index.js]:
```suggestion
            __('A font with the name %s already exists.', 'web-stories'),
```

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+  afterEach(async () => {
+    await removeCustomFont();
+  });
+
+  it('should show error on trying add font twice', async () => {
+    await addCustomFont(OPEN_SANS_CONDENSED_URL);
+    await addCustomFont(OPEN_SANS_CONDENSED_URL);
+
+    await expect(page).toMatch(
+      'A font with this name Open Sans Condensed Light already exists.'
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]:
```suggestion
      'A font with the name Open Sans Condensed Light already exists.'
```

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js (hunk 2 above)
Comment (swissspidy) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:232]: Theoretically no. But this code was just moved as-is.

Let's keep it, but add some `trackError('add_custom_font', err?.message)` while we're at it.

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js (hunk 3 above)
Comment (swissspidy) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:251]: Let's keep it, but add some `trackError('add_custom_font', err?.message)` while we're at it.

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js (hunk 2 above)
Comment (spacedmonkey) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:232]: Error tracking added.

File: packages/wp-dashboard/src/components/editorSettings/customFonts/index.js (hunk 3 above)
Comment (spacedmonkey) [reply packages/wp-dashboard/src/components/editorSettings/customFonts/index.js:251]: Fixed.

**Comment by spacedmonkey** [comment]
Rebased after #10918 was merged.

**Comment by swissspidy** [comment]
Just noting that the error message change was somehow reverted again. I fixed it myself now.

**Review by swissspidy — APPROVED** [review]
