### PR TITLE
Always display the design space guideline when an element is being transformed

### LINKED ISSUE #5134: Safe zone box randomly disappears
## Bug Description

1. The design safe zone (pink-purple box) do not always appear for me
2. Safe zone also randomly disappear as I build my story
3. Safe zone sometimes stay stuck on the page

## Expected Behaviour

The design safe zone is part of the snap guideline system and should also appear in accordance with snap guide rules

## Screenshots
Safe zone not showing up:

Safe zone stuck:

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6367: Safe zone should always be visible when moving/editing an element

### PR DESCRIPTION
**Pull request by miina**
## User-facing changes
The guideline now appears when doing any transformations with an element:
guideline

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Drag a shape from the shape library, verify the design space guideline is displayed while the element is being dragged
2. Verify the guideline disappears after finishing dragging.
3. Now move, resize, rotate the shape.
4. Verify that during these activities, the design space guideline is displayed again, even when not snapping to it.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6367 
FIxes #5134

### CODE REVIEW

**Comment by miina** [comment]
@barklund I _think_ this should fix the guidelines sometimes not appearing issue, too.

File: assets/src/edit-story/components/canvas/framesLayer.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ const DesignSpaceGuideline = styled.div`
   position: absolute;
   pointer-events: none;
   z-index: 1;
-  visibility: hidden;
+  visibility: ${({ isVisible }) => (isVisible ? 'visible' : 'hidden')};
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/framesLayer.js:50]: Hmm, can you check if S-C only uses two classes for this or generates a new class every time it toggles? If it's only ever two classes, this is fine. Otherwise, we should use `.attrs({ style: { ... } })` to avoid generating infinite classes.

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 2]
```diff
@@ -83,12 +83,25 @@ function LibraryMoveable({
...
+    pageContainer: state.state.pageContainer,
+    nodesById: state.state.nodesById,
+    designSpaceGuideline: state.state.designSpaceGuideline,
+  }));
+
+  const toggleDesignSpace = useCallback(
+    (visible) => {
+      if (designSpaceGuideline) {
+        designSpaceGuideline.style.visibility = visible ? 'visible' : null;
+      }
```
Comment (barklund) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:104]: Doesn't this clash with the class stuff? Or does it combine nicely always?

File: assets/src/edit-story/components/canvas/framesLayer.js [hunk 3]
```diff
@@ -65,6 +65,10 @@ function FramesLayer() {
     })
   );
 
+  const { isAnythingTransforming } = useTransform((state) => ({
+    isAnythingTransforming: state.state.isAnythingTransforming,
+  }));
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/framesLayer.js:69]: If you <kbd>esc</kbd> out of a transform (e.g. resize), this doesn't seem to reset:

resize-esc-bug

**Review by barklund — COMMENTED** [review]
Found a bug, sorry 🐛

File: assets/src/edit-story/components/canvas/framesLayer.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/framesLayer.js:50]: Good point, didn't think about that! Fortunately, it's smart and uses two classes only.

File: assets/src/edit-story/components/canvas/framesLayer.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/components/canvas/framesLayer.js:69]: Looks like you've found an issue with `isAnythingTransforming`, congrats! 🎺   It's not being properly reset when `clearSelection` is happening.

I'm actually not sure now -- should the `Esc` just cancel the Moveable action? Or should it clear the selection fully as it's doing now 🤔  (Probably not to be changed within this PR though)

What we could do now is checking if the selection changes and nothing is selected anymore, we clear the transformations (if that's possible generally without ID, have to check). Otherwise, we can hide the design space if nothing is selected but that's not fixing the root issue.

Comment (miina) [reply assets/src/edit-story/components/canvas/framesLayer.js:69]: Should be fixed now in 129c19e.

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:104]: Setting it to `null` makes it work together with the class.

File: assets/src/edit-story/components/canvas/framesLayer.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/framesLayer.js:69]: Wait, now I get an even weirder bug... where the frame is resized, but the display is not, so the frame and display are now mismatched:

shape-frame-resize-abort-bug

Comment (miina) [reply assets/src/edit-story/components/canvas/framesLayer.js:69]: Hm, looks like Moveable is not reset when this happens. Ugh, this is a bit more complicated issue than it seemed to be. Will investigate.

Comment (miina) [reply assets/src/edit-story/components/canvas/framesLayer.js:69]: Apparently using `Esc` while doing a transformation is buggy as it is:
The elements are deselected but Moveable transformation is not finished / cleaned up so it causes unexpected behaviour on `main`, too:
escing

This will need its own issue but since no one has flagged it I suppose not a lot of people are using `Esc` while transforming something.

**Review by barklund — APPROVED** [review]
