### PR TITLE
Layers Panel: constrain max height of layer panel

### LINKED ISSUE #9542: Layer panel: Remove scrollbar when the layer panel is max height
## Bug Description

Expanding the layer panel to its maximum height makes a scrollbar appear for no reason.

## Expected Behaviour

The layer panel should only show a scrollbar if there are too many layers to display on the screen.

## Steps to Reproduce

Expand the layer panel all the way up.

## Additional Context

- Plugin Version: 1.14.0-alpha
- WordPress Version: 5.8.1
- Operating System: MacOSX Sierra
- Browser: Chrome

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context
Expanding the layer panel to its maximum height makes a scrollbar appear. 

## Summary

This scroll bar was appearing because the actual height of the layers panel was set to `99999999`. An overriding `maxHeight` prop was set to the `MAX_HEIGHT_DEFAULT` from `./panel`

## Relevant Technical Choices

We want the max height to fill the space underneath the document/design tab bar. Since the document/design tab bar is 50px subtract that from the full height of the inspector and use this value as the `maxHeight` override prop. 

## To-do

n/a

### Old: 
Screen Shot 2021-10-29 at 2 25 39 PM

### New:

Screen Shot 2021-10-29 at 2 26 28 PM
## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. open the layers panel
2. drag to resize to the full height
3. notice the scroll bar no longer appears. 

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9542

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/layer/layerPanel.js [hunk 1]
```diff
@@ -56,6 +52,14 @@ const Divider = styled.div`
 function LayerPanel() {
   const layers = useLayers();
 
+  const {
+    state: { inspectorContentHeight },
+  } = useInspector();
+
+  // We want the max height to fill the space underneath the document/design tab bar.
+  // Since the document/design tab bar is 50px subtract that from the full height of the inspector.
+  const maxHeight = inspectorContentHeight - 50;
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/panels/design/layer/layerPanel.js]: 🤔   i'm trying to think there's a way we can pull in the height of the tab bar instead of assigning it by force here - just for when the designs update. It's set in components/tabview > `TabElement` and it's a combo of 32px height and 19px of vertical margin.

Comment (BrookeGraham) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js]: I could probably calculate it via `useInspector` -> `tabRef` in the `InspectorProvider` . I'll. look into it.

Comment (maxyinger) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js]: I think Brittany's thinking something much simpler. just making like `TAB_HEIGHT` & `TAB_MARGIN_VERTICAL` constants and using them both here and in the `TabElement`.

**Review by maxyinger — APPROVED** [review]
Looks good.

File: packages/story-editor/src/components/panels/design/layer/layerPanel.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js]: thanks, max - yup! keep it simple 😎

**Review by samwhale — APPROVED** [review]
Agree with the new way. This works well too, but the simpler approach will be easier ✅

File: packages/story-editor/src/components/panels/design/layer/layerPanel.js (hunk 1 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js]: oh duh! Cool

File: packages/story-editor/src/components/panels/design/layer/layerPanel.js [hunk 2]
```diff
@@ -56,6 +53,16 @@ const Divider = styled.div`
...
   const layers = useLayers();
 
+  const {
+    state: { inspectorContentHeight },
+  } = useInspector();
+
+  // We want the max height to fill the space underneath the document/design tab bar.
+  // Since the document/design tab bar has top and bottom margin in addition to a static
+  // height subtract sum from the full height of the inspector.
+  const tabHeight = 2 * TAB_VERTICAL_MARGIN + TAB_HEIGHT;
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/panels/design/layer/layerPanel.js:63]: ❤️  thank youuuu

**Review by BrittanyIRL — APPROVED** [review]

File: packages/story-editor/src/components/panels/design/layer/layerPanel.js [hunk 3]
```diff
@@ -57,8 +58,10 @@ function LayerPanel() {
   } = useInspector();
 
   // We want the max height to fill the space underneath the document/design tab bar.
-  // Since the document/design tab bar is 50px subtract that from the full height of the inspector.
-  const maxHeight = inspectorContentHeight - 50;
+  // Since the document/design tab bar has top and bottom margin in addition to a static
+  // height subtract sum from the full height of the inspector.
+  const tabHeight = 2 * TAB_VERTICAL_MARGIN + TAB_HEIGHT;
+  const maxHeight = inspectorContentHeight - tabHeight + 2;
```
Comment (samwhale) [inline packages/story-editor/src/components/panels/design/layer/layerPanel.js:64]: nit: could memoize this since these are all static (unless the user resizes the window). We don't save much by memoizing this though, it's only a couple calculations.

Comment (BrookeGraham) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js:64]: I think memoizing in this case would end up being more expensive than the simple math 🧐

Comment (samwhale) [reply packages/story-editor/src/components/panels/design/layer/layerPanel.js:64]: sounds good!
