### PR TITLE
Video Trimmer: Fix for blank frames in video trimmer frames strip

### LINKED ISSUE #9870: Video Trimmer:  Frames strip is offset by white space and some frames are missing from the rail strip
## Bug Description

In the video trim mode, the frames in the frames strip are offset by white space and some frames at the start of the video are not rendered.

See the original conversation here: https://github.com/google/web-stories-wp/pull/9759#discussion_r754260262

## Expected Behaviour

- The videos first frame should be rendered on the frames strip
- No whitespace offset on the frames-trip 

## Steps to Reproduce

- Add a video to a page
- Toggle to trim mode
- Observe the whitespace before the start of the frames in the frames strip

## Screenshots

Screenshot 2021-12-02 at 12 06 41

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser

### PR DESCRIPTION
**Pull request by Trapsta**
## Context

In the video trimmer framers strip, It looks like trying to grab the  frames after the `canplay` event fires creates mixed results with the frames successfully extracted in FF but failing in chrome which returns a blank/transparent frame.

## Summary

The least disruptive solution I found was to skip the first fraction of a ms  ~~by simply adding `#t=0.000001` at the end of the video file url~~. This works for both FF and Chrome. 

## User-facing changes

| Before | After |
|--------|-------|
|  Screenshot 2021-12-14 at 18 25 52  |  Screenshot 2021-12-14 at 18 22 48  |

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a video to a page in chrome.
2. Toggle video trim mode
3. Verify there are no blank frames (white space) at the start of the frames strip.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9870

### CODE REVIEW

File: packages/media/src/generateVideoStrip.js [hunk 1]
```diff
@@ -74,8 +74,8 @@ async function generateVideoStrip(element, resource, stripWidth, stripHeight) {
   // Calculate the offset between each frame to be grabbed
   const frameDistance = length / (frameCount - 1);
 
-  // Preload video and adjust size
-  const video = await preloadVideo(src);
+  // Preload video and adjust size. Skipping the first ms to prevent blank frames in chrome.
+  const video = await preloadVideo(`${src}#t=0.000001`);
```
Comment (swissspidy) [inline packages/media/src/generateVideoStrip.js]: Any advantage of this or general difference vs. the following?

```js
const video = await preloadVideo(src);
await seekVideo(video, 0.000001);
```

**Comment by miina** [comment]
@Trapsta There's still a black (empty) area above the frames, didn't realize the origin issue didn't include fixing that but would be good to fully fix the looks while we're at it. The frames should cover the whole strip area.

File: packages/media/src/generateVideoStrip.js (hunk 1 above)
Comment (Trapsta) [reply packages/media/src/generateVideoStrip.js]: None that I can see. This looks much cleaner and readable. Will update that part

**Comment by Trapsta** [comment]
> @Trapsta There's still a black (empty) area above the frames, didn't realize the origin issue didn't include fixing that but would be good to fully fix the looks while we're at it. The frames should cover the whole strip area.

@miina , the black strip is part of the video. Updated the description with screenshots of a different video that doesn't have any black strips to show the difference. I recall we did have an issue with some white parts at the top or sometimes at the bottom but not seeing that currently .

**Review by barklund — APPROVED** [review]
Looks good and works for me with resized video, scaled video, flipped video, rotated video, etc.

I wonder why the `seek(0)` worked for me when originally implementing this but not anymore? I'm sure it worked when I wrote it, but I can also see that it doesn't anymore... 🤷

**Comment by kkalarickal** [comment]
Tested on [stories-qa-server](https://stories-qa-wordpress-amp.pantheonsite.io/web-stories/9989-video-trimmer-fix-for-blank-frames-in-video-trimmer-frames-strip/) and confirmed fix ✔️ 

image

Verified on a flipped, scaled, rotated and resized video as well ✔️ 

image

Verified this on  Firefox / Chrome
