### PR TITLE
Text edit mode fixes and start on some tests

### LINKED ISSUE #386: Clicking twice into a text element should place a cursor into the text
## Bug Description

When clicking twice onto a text element, it puts the element into "edit" mode, but there's no blinking cursor. I have to click again to produce one. /cc @dvoytenko 

## Expected Behaviour

The second click that puts the element into "edit mode" should also immediately set the cursor to where I clicked.

## Steps to Reproduce

Create a text element. Click twice on text element.

## Screenshots

image

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dvoytenko**
Fixes: #386.

Changes:
* Focus management moved from `EditElement` to each element's `Edit` component, b/c the edit element wrapper has no actions of its own.
* `useEditingElement` is switched to use `reducer` for both editing ID and state to avoid any problems with sync flush.
* The `text/edit.js` is overhauled. Most of initializing side effects are replaces by the `useMemo` to calculate both: initial state and selection.
* The `text/frame.js` is changed in how it handles mouse and keyboard events. But changes are mostly insignificant.

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

File: assets/src/edit-story/components/canvas/frameElement.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ function FrameElement({ element }) {
         showTooltip={selectedElementIds.length === 1 && isSelected}
       >
         <WithElementMask element={element} fill={true}>
-          {Frame && <Frame element={element} box={box} />}
+          {Frame && <Frame wrapperRef={elementRef} element={element} box={box} />}
```
Comment (swissspidy) [inline assets/src/edit-story/components/canvas/frameElement.js]: Prettier wants to fix this

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/frameElement.js]: yep. bad merge. fixed now.
