### PR TITLE
Workspace: Font variant bug

### LINKED ISSUE #3259: Partially bold text is all bold in the output
## Bug Description

Partially bold text is all bold in the output. As noticed just weight 700 is fetched (no 400).
https://github.com/google/web-stories-wp/pull/2324 was related.

## Expected Behaviour

The output element should look like the one in the editor.

## Steps to Reproduce

Load attached story data or add text and bold just one letter then check the output.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:
- Story Data:
```
ewogICJjdXJyZW50IjogImE2YzM2YzMwLWY0NzktNDk5Zi1iMWZjLWU4MGVjZTRlM2RhZCIsCiAgInNlbGVjdGlvbiI6IFsKICAgICI0N2NmNjVlMy04MGY4LTRkY2UtYjE5MS1jOGRlMGQ5NTAxZTMiCiAgXSwKICAic3RvcnkiOiB7CiAgICAic3R5bGVQcmVzZXRzIjogewogICAgICAiY29sb3JzIjogWwogICAgICAgIHsKICAgICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICAgInIiOiAyNTUsCiAgICAgICAgICAgICJnIjogMjU1LAogICAgICAgICAgICAiYiI6IDI1NQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImNvbG9yIjogewogICAgICAgICAgICAiciI6IDAsCiAgICAgICAgICAgICJnIjogMCwKICAgICAgICAgICAgImIiOiAwCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAiY29sb3IiOiB7CiAgICAgICAgICAgICJyIjogMTM1LAogICAgICAgICAgICAiZyI6IDk3LAogICAgICAgICAgICAiYiI6IDE4MAogICAgICAgICAgfQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRleHRTdHlsZXMiOiBbXQogICAgfQogIH0sCiAgInBhZ2VzIjogWwogICAgewogICAgICAiZWxlbWVudHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm9wYWNpdHkiOiAxMDAsCiAgICAgICAgICAiZmxpcCI6IHsKICAgICAgICAgICAgInZlcnRpY2FsIjogZmFsc2UsCiAgICAgICAgICAgICJob3Jpem9udGFsIjogZmFsc2UKICAgICAgICAgIH0sCiAgICAgICAgICAicm90YXRpb25BbmdsZSI6IDAsCiAgICAgICAgICAibG9ja0FzcGVjdFJhdGlvIjogdHJ1ZSwKICAgICAgICAgICJiYWNrZ3JvdW5kQ29sb3IiOiB7CiAgICAgICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICAgICAiciI6IDI1NSwKICAgICAgICAgICAgICAiZyI6IDI1NSwKICAgICAgICAgICAgICAiYiI6IDI1NQogICAgICAgICAgICB9CiAgICAgICAgICB9LAogICAgICAgICAgIngiOiAxLAogICAgICAgICAgInkiOiAxLAogICAgICAgICAgIndpZHRoIjogMSwKICAgICAgICAgICJoZWlnaHQiOiAxLAogICAgICAgICAgIm1hc2siOiB7CiAgICAgICAgICAgICJ0eXBlIjogInJlY3RhbmdsZSIKICAgICAgICAgIH0sCiAgICAgICAgICAiaXNCYWNrZ3JvdW5kIjogdHJ1ZSwKICAgICAgICAgICJpc0RlZmF1bHRCYWNrZ3JvdW5kIjogdHJ1ZSwKICAgICAgICAgICJ0eXBlIjogInNoYXBlIiwKICAgICAgICAgICJpZCI6ICI4Y2ZlYzFjYy04NzEwLTQ4M2MtOTdiZi00NDU3MjYzNWMyMjMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAib3BhY2l0eSI6IDEwMCwKICAgICAgICAgICJmbGlwIjogewogICAgICAgICAgICAidmVydGljYWwiOiBmYWxzZSwKICAgICAgICAgICAgImhvcml6b250YWwiOiBmYWxzZQogICAgICAgICAgfSwKICAgICAgICAgICJyb3RhdGlvbkFuZ2xlIjogMCwKICAgICAgICAgICJsb2NrQXNwZWN0UmF0aW8iOiB0cnVlLAogICAgICAgICAgImJhY2tncm91bmRUZXh0TW9kZSI6ICJOT05FIiwKICAgICAgICAgICJmb250IjogewogICAgICAgICAgICAiZmFtaWx5IjogIlJvYm90byIsCiAgICAgICAgICAgICJ3ZWlnaHRzIjogWwogICAgICAgICAgICAgIDEwMCwKICAgICAgICAgICAgICAzMDAsCiAgICAgICAgICAgICAgNDAwLAogICAgICAgICAgICAgIDUwMCwKICAgICAgICAgICAgICA3MDAsCiAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJzdHlsZXMiOiBbCiAgICAgICAgICAgICAgIml0YWxpYyIsCiAgICAgICAgICAgICAgInJlZ3VsYXIiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJ2YXJpYW50cyI6IFsKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgMTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgMTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgMzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgMzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNDAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNDAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgICAgXQogICAgICAgICAgICBdLAogICAgICAgICAgICAiZmFsbGJhY2tzIjogWwogICAgICAgICAgICAgICJIZWx2ZXRpY2EgTmV1ZSIsCiAgICAgICAgICAgICAgIkhlbHZldGljYSIsCiAgICAgICAgICAgICAgInNhbnMtc2VyaWYiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJzZXJ2aWNlIjogImZvbnRzLmdvb2dsZS5jb20iCiAgICAgICAgICB9LAogICAgICAgICAgImZvbnRTaXplIjogMTYsCiAgICAgICAgICAiYmFja2dyb3VuZENvbG9yIjogewogICAgICAgICAgICAiY29sb3IiOiB7CiAgICAgICAgICAgICAgInIiOiAxOTYsCiAgICAgICAgICAgICAgImciOiAxOTYsCiAgICAgICAgICAgICAgImIiOiAxOTYKICAgICAgICAgICAgfQogICAgICAgICAgfSwKICAgICAgICAgICJsaW5lSGVpZ2h0IjogMS41LAogICAgICAgICAgInRleHRBbGlnbiI6ICJjZW50ZXIiLAogICAgICAgICAgInBhZGRpbmciOiB7CiAgICAgICAgICAgICJsb2NrZWQiOiB0cnVlLAogICAgICAgICAgICAiaG9yaXpvbnRhbCI6IDAsCiAgICAgICAgICAgICJ2ZXJ0aWNhbCI6IDAKICAgICAgICAgIH0sCiAgICAgICAgICAidHlwZSI6ICJ0ZXh0IiwKICAgICAgICAgICJjb250ZW50IjogIjxzcGFuIHN0eWxlPVwiZm9udC13ZWlnaHQ6IDcwMFwiPkY8L3NwYW4+aWxsIGluIHNvbWUgdGV4dCIsCiAgICAgICAgICAieCI6IDAsCiAgICAgICAgICAieSI6IC0yOCwKICAgICAgICAgICJ3aWR0aCI6IDE2MCwKICAgICAgICAgICJoZWlnaHQiOiAyNCwKICAgICAgICAgICJzY2FsZSI6IDEwMCwKICAgICAgICAgICJmb2NhbFgiOiA1MCwKICAgICAgICAgICJmb2NhbFkiOiA1MCwKICAgICAgICAgICJpZCI6ICI0N2NmNjVlMy04MGY4LTRkY2UtYjE5MS1jOGRlMGQ5NTAxZTMiCiAgICAgICAgfQogICAgICBdLAogICAgICAiYmFja2dyb3VuZENvbG9yIjogewogICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICJyIjogMjU1LAogICAgICAgICAgImciOiAyNTUsCiAgICAgICAgICAiYiI6IDI1NQogICAgICAgIH0KICAgICAgfSwKICAgICAgInR5cGUiOiAicGFnZSIsCiAgICAgICJpZCI6ICJhNmMzNmMzMC1mNDc5LTQ5OWYtYjFmYy1lODBlY2U0ZTNkYWQiCiAgICB9CiAgXQp9
```

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dmmulroy**
## Summary

This PR resolves the bug where not all variants were loading in preview when text contained more than one.

## Relevant Technical Choices

- Refactored `getVariants` and `getFontVariants` to ensure `[0,400]` is added if there is plain text.

## User-facing changes

- All font variants should load, render, and be visible in preview mode.

## Testing Instructions

1. Import the following base64 story data to a new story:
```
ewogICJjdXJyZW50IjogImE2YzM2YzMwLWY0NzktNDk5Zi1iMWZjLWU4MGVjZTRlM2RhZCIsCiAgInNlbGVjdGlvbiI6IFsKICAgICI0N2NmNjVlMy04MGY4LTRkY2UtYjE5MS1jOGRlMGQ5NTAxZTMiCiAgXSwKICAic3RvcnkiOiB7CiAgICAic3R5bGVQcmVzZXRzIjogewogICAgICAiY29sb3JzIjogWwogICAgICAgIHsKICAgICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICAgInIiOiAyNTUsCiAgICAgICAgICAgICJnIjogMjU1LAogICAgICAgICAgICAiYiI6IDI1NQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImNvbG9yIjogewogICAgICAgICAgICAiciI6IDAsCiAgICAgICAgICAgICJnIjogMCwKICAgICAgICAgICAgImIiOiAwCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAiY29sb3IiOiB7CiAgICAgICAgICAgICJyIjogMTM1LAogICAgICAgICAgICAiZyI6IDk3LAogICAgICAgICAgICAiYiI6IDE4MAogICAgICAgICAgfQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRleHRTdHlsZXMiOiBbXQogICAgfQogIH0sCiAgInBhZ2VzIjogWwogICAgewogICAgICAiZWxlbWVudHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm9wYWNpdHkiOiAxMDAsCiAgICAgICAgICAiZmxpcCI6IHsKICAgICAgICAgICAgInZlcnRpY2FsIjogZmFsc2UsCiAgICAgICAgICAgICJob3Jpem9udGFsIjogZmFsc2UKICAgICAgICAgIH0sCiAgICAgICAgICAicm90YXRpb25BbmdsZSI6IDAsCiAgICAgICAgICAibG9ja0FzcGVjdFJhdGlvIjogdHJ1ZSwKICAgICAgICAgICJiYWNrZ3JvdW5kQ29sb3IiOiB7CiAgICAgICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICAgICAiciI6IDI1NSwKICAgICAgICAgICAgICAiZyI6IDI1NSwKICAgICAgICAgICAgICAiYiI6IDI1NQogICAgICAgICAgICB9CiAgICAgICAgICB9LAogICAgICAgICAgIngiOiAxLAogICAgICAgICAgInkiOiAxLAogICAgICAgICAgIndpZHRoIjogMSwKICAgICAgICAgICJoZWlnaHQiOiAxLAogICAgICAgICAgIm1hc2siOiB7CiAgICAgICAgICAgICJ0eXBlIjogInJlY3RhbmdsZSIKICAgICAgICAgIH0sCiAgICAgICAgICAiaXNCYWNrZ3JvdW5kIjogdHJ1ZSwKICAgICAgICAgICJpc0RlZmF1bHRCYWNrZ3JvdW5kIjogdHJ1ZSwKICAgICAgICAgICJ0eXBlIjogInNoYXBlIiwKICAgICAgICAgICJpZCI6ICI4Y2ZlYzFjYy04NzEwLTQ4M2MtOTdiZi00NDU3MjYzNWMyMjMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAib3BhY2l0eSI6IDEwMCwKICAgICAgICAgICJmbGlwIjogewogICAgICAgICAgICAidmVydGljYWwiOiBmYWxzZSwKICAgICAgICAgICAgImhvcml6b250YWwiOiBmYWxzZQogICAgICAgICAgfSwKICAgICAgICAgICJyb3RhdGlvbkFuZ2xlIjogMCwKICAgICAgICAgICJsb2NrQXNwZWN0UmF0aW8iOiB0cnVlLAogICAgICAgICAgImJhY2tncm91bmRUZXh0TW9kZSI6ICJOT05FIiwKICAgICAgICAgICJmb250IjogewogICAgICAgICAgICAiZmFtaWx5IjogIlJvYm90byIsCiAgICAgICAgICAgICJ3ZWlnaHRzIjogWwogICAgICAgICAgICAgIDEwMCwKICAgICAgICAgICAgICAzMDAsCiAgICAgICAgICAgICAgNDAwLAogICAgICAgICAgICAgIDUwMCwKICAgICAgICAgICAgICA3MDAsCiAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJzdHlsZXMiOiBbCiAgICAgICAgICAgICAgIml0YWxpYyIsCiAgICAgICAgICAgICAgInJlZ3VsYXIiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJ2YXJpYW50cyI6IFsKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgMTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgMTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgMzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgMzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNDAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNDAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgNzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgNzAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAwLAogICAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICBbCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgOTAwCiAgICAgICAgICAgICAgXQogICAgICAgICAgICBdLAogICAgICAgICAgICAiZmFsbGJhY2tzIjogWwogICAgICAgICAgICAgICJIZWx2ZXRpY2EgTmV1ZSIsCiAgICAgICAgICAgICAgIkhlbHZldGljYSIsCiAgICAgICAgICAgICAgInNhbnMtc2VyaWYiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJzZXJ2aWNlIjogImZvbnRzLmdvb2dsZS5jb20iCiAgICAgICAgICB9LAogICAgICAgICAgImZvbnRTaXplIjogMTYsCiAgICAgICAgICAiYmFja2dyb3VuZENvbG9yIjogewogICAgICAgICAgICAiY29sb3IiOiB7CiAgICAgICAgICAgICAgInIiOiAxOTYsCiAgICAgICAgICAgICAgImciOiAxOTYsCiAgICAgICAgICAgICAgImIiOiAxOTYKICAgICAgICAgICAgfQogICAgICAgICAgfSwKICAgICAgICAgICJsaW5lSGVpZ2h0IjogMS41LAogICAgICAgICAgInRleHRBbGlnbiI6ICJjZW50ZXIiLAogICAgICAgICAgInBhZGRpbmciOiB7CiAgICAgICAgICAgICJsb2NrZWQiOiB0cnVlLAogICAgICAgICAgICAiaG9yaXpvbnRhbCI6IDAsCiAgICAgICAgICAgICJ2ZXJ0aWNhbCI6IDAKICAgICAgICAgIH0sCiAgICAgICAgICAidHlwZSI6ICJ0ZXh0IiwKICAgICAgICAgICJjb250ZW50IjogIjxzcGFuIHN0eWxlPVwiZm9udC13ZWlnaHQ6IDcwMFwiPkY8L3NwYW4+aWxsIGluIHNvbWUgdGV4dCIsCiAgICAgICAgICAieCI6IDAsCiAgICAgICAgICAieSI6IC0yOCwKICAgICAgICAgICJ3aWR0aCI6IDE2MCwKICAgICAgICAgICJoZWlnaHQiOiAyNCwKICAgICAgICAgICJzY2FsZSI6IDEwMCwKICAgICAgICAgICJmb2NhbFgiOiA1MCwKICAgICAgICAgICJmb2NhbFkiOiA1MCwKICAgICAgICAgICJpZCI6ICI0N2NmNjVlMy04MGY4LTRkY2UtYjE5MS1jOGRlMGQ5NTAxZTMiCiAgICAgICAgfQogICAgICBdLAogICAgICAiYmFja2dyb3VuZENvbG9yIjogewogICAgICAgICJjb2xvciI6IHsKICAgICAgICAgICJyIjogMjU1LAogICAgICAgICAgImciOiAyNTUsCiAgICAgICAgICAiYiI6IDI1NQogICAgICAgIH0KICAgICAgfSwKICAgICAgInR5cGUiOiAicGFnZSIsCiAgICAgICJpZCI6ICJhNmMzNmMzMC1mNDc5LTQ5OWYtYjFmYy1lODBlY2U0ZTNkYWQiCiAgICB9CiAgXQp9
```
2. Click preview
3. Verify that not all of the font is bold

---

#3259

### CODE REVIEW

**Review by miina — COMMENTED** [review]
Could we add an output test for that? To check that the correct font link is included in the story.

File: assets/src/edit-story/components/richText/getFontVariants.js [hunk 1]
```diff
@@ -45,34 +45,24 @@ function getFontStylesForCharacter(styles) {
...
-    const styleArray = getFontStylesForCharacter(styleSet);
-
-    if (!hasStyle(styleArray)) {
-      styles.push(styleArray);
-    }
+    return style;
   });
 
-  return [...styles];
+  return [...new Set(styles)];
```
Comment (embarks) [inline assets/src/edit-story/components/richText/getFontVariants.js:56]: this is a nice change. ✨

**Review by embarks — APPROVED** [review]

**Review by carloskelly13 — APPROVED** [review]
