### PR TITLE
Fix: 🐛 Add `Reset` button for scheduled stories

### LINKED ISSUE #13428: Calendar: Add Reset button for scheduled stories
## Feature Description
Add a reset button inside the calendar widget for stories that has already been scheduled for publishing.

Currently, there is no reset button in the editor's calendar widget for stories with scheduled publishing date.

Actual:
Screenshot 2023-07-19 at 9 36 14 AM

Expected:
Screenshot 2023-07-19 at 9 37 20 AM

### PR DESCRIPTION
**Pull request by AnuragVasanwala**
## Summary

The goal of the PR is to show `Reset` button for scheduled stories.

## User-facing changes

With this PR, `Reset` button will be shown in calendar for the scheduled stories. Clicking on the `Reset` button will enable user to publish story immediately.

Animated GIF:
WebStories-AddResetButtonForScheduledStories

## Testing Instructions

This PR can be tested by following these steps described in the issue #13428.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #13428

### CODE REVIEW

File: packages/wp-story-editor/src/components/documentPane/publish/publishTime.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ function PublishTime() {
 
   // Floating date means an unset date so that the story publish date will match the time it will get published.
   const floatingDate =
-    ['draft', 'pending', 'auto-draft'].includes(status) &&
+    ['draft', 'pending', 'auto-draft', 'future'].includes(status) &&
     (date === modified || date === null);
```
Comment (swissspidy) [inline packages/wp-story-editor/src/components/documentPane/publish/publishTime.js:106]: Is this condition ever true for scheduled posts? I think a post with status `future` will always have a non-null date, and the scheduled date will always be different from the modified date.
In other words, do we need this? Can we revert this change?

**Review by swissspidy — COMMENTED** [review]
Perfect 🥳

File: packages/wp-story-editor/src/components/documentPane/publish/publishTime.js (hunk 1 above)
Comment (AnuragVasanwala) [reply packages/wp-story-editor/src/components/documentPane/publish/publishTime.js:106]: A story will be marked as `future` whenever we schedule it. Thus, including it solved the issue!

Updating `floatingDate` will [display `"Immediate"` label](https://github.com/GoogleForCreators/web-stories-wp/blob/f50d7e2594692bd1e0e9f61ade540386b8ccdcba/packages/wp-story-editor/src/components/documentPane/publish/publishTime.js#L112) and [show `Reset` button](https://github.com/GoogleForCreators/web-stories-wp/blob/f50d7e2594692bd1e0e9f61ade540386b8ccdcba/packages/wp-story-editor/src/components/documentPane/publish/publishTime.js#L153-L156).

Comment (swissspidy) [reply packages/wp-story-editor/src/components/documentPane/publish/publishTime.js:106]: Well, I guess if it works it works! :-)

**Review by swissspidy — APPROVED** [review]
Works like a charm!
