### PR TITLE
Fix dropdown issue on document panel

### LINKED ISSUE #626: DropDown followup: Document tab crashing
## Bug Description

Opening the Document tag in the right sidebar crashes the editor.

## Expected Behaviour

Document sidebar should open as expected.

## Steps to Reproduce

1. Click on "Document" Sidebar tab.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ndev1991**
Fixes #626 

Summary
Bug on document panel, array of options should be supplied.
Update throttle-debounce with use-debounce. Some minor issues with dropdown when the value is empty string.

### CODE REVIEW

File: assets/src/edit-story/components/dropDown/index.js [hunk 1]
```diff
@@ -289,10 +295,11 @@ function DropDown({ options, value, onChange, disabled, ariaLabel }) {
   };
 
   useEffect(() => {
-    if (focusedValue) {
+    if (!isNullOrUndefined(focusedValue)) {
       const findIndex = options.findIndex(
         (item) =>
-          focusedValue && item.value.toString() === focusedValue.toString()
+          !isNullOrUndefined(focusedValue) &&
```
Comment (miina) [inline assets/src/edit-story/components/dropDown/index.js]: This is already checked above.

File: assets/src/edit-story/components/dropDown/index.js [hunk 2]
```diff
@@ -170,18 +170,25 @@ function DropDown({ options, value, onChange, disabled, ariaLabel }) {
   const [isOpen, setIsOpen] = useState(false);
   const [searchValue, setSearchValue] = useState('');
   const [focusedValue, setFocusedValue] = useState(null);
+  const isNullOrUndefined = (item) => {
+    if (item === null || item === undefined) return true;
+    return false;
```
Comment (miina) [inline assets/src/edit-story/components/dropDown/index.js]: This could be just `return item === null || item === undefined;`

File: assets/src/edit-story/components/dropDown/index.js [hunk 3]
```diff
@@ -194,7 +201,8 @@ function DropDown({ options, value, onChange, disabled, ariaLabel }) {
     (offset) => {
       const findIndex = options.findIndex(
         (item) =>
-          focusedValue && item.value.toString() === focusedValue.toString()
+          !isNullOrUndefined(focusedValue) &&
```
Comment (miina) [inline assets/src/edit-story/components/dropDown/index.js]: Looks like the same thing ( `!isNullOrUndefined` with `item.value.toString() === focusedValue.toString()` ) is repeated 3 times, should perhaps there be a helper for that instead?

File: assets/src/edit-story/components/dropDown/index.js (hunk 1 above)
Comment (ndev1991) [reply assets/src/edit-story/components/dropDown/index.js]: Yes, replaced by using foundIndex usememo

File: assets/src/edit-story/components/dropDown/index.js (hunk 2 above)
Comment (ndev1991) [reply assets/src/edit-story/components/dropDown/index.js]: Correct. Thank you

File: assets/src/edit-story/components/dropDown/index.js (hunk 3 above)
Comment (ndev1991) [reply assets/src/edit-story/components/dropDown/index.js]: Yes, used foundIndex useMemo replacement

**Review by miina — APPROVED** [review]
When opening the Document tab at first, `Select an Option` displays there for some time on two lines. I guess we can probably leave that for now, merging to fix the editor crashing ASAP.
