### PR TITLE
Editor: Fix broken links

### LINKED ISSUE #10428: Canvas: Links no longer show Tooltip on hover.
## Bug Description

While cleaning up karma test in #10194, found the design link karma test was disabled citing it being flakey. However I found that the test wasn't grabbing the correct "tooltip" element. Either while this test was disabled or due to it testing the wrong thing a regression occurred causing links to no longer show a `tooltip` when hovering on the link element on the canvas. 

## Expected Behaviour

Tooltip should appear when hovering an element with a link. Karma test `CUJ: Creator Can Add A Link: Apply a link to any element should display the link tooltip correctly'` should be updated to grab the tooltip, and it should pass. 

## Steps to Reproduce

Add text element. 
Click `Link` in design panel
Add url
Deselect the text element on the canvas
Hover the text element
`Tooltip` should appear but does not. 

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: 7.4
- Operating System: OSX
- Browser: Chrome Version 97.0.4692.99 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by merapi**
## Summary

I will enable the `xit` test after the first pass.

## Testing Instructions

In addition to fixing https://github.com/GoogleForCreators/web-stories-wp/issues/10428 (Steps to reproduce), it also fixes the element so it's fully functional - you can select and move it.

Add an element, add a link, deselect the element, and then verify the tooltip on hover and select/move actions.

- [ ] This is a non-user-facing change and requires no QA

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10428

### CODE REVIEW

File: packages/story-editor/src/components/elementLink/frame.js [hunk 1]
```diff
@@ -79,10 +79,6 @@ function WithLink({ element, active, children, anchorRef }) {
       </>
     ) : null;
 
-  if (!tooltipContent) {
-    return children;
-  }
```
Comment (barklund) [inline packages/story-editor/src/components/elementLink/frame.js:84]: Any idea what this bit of code was supposed to do? Is something else not working as it should now?

**Review by barklund — APPROVED** [review]
This seems to fix the issue.

File: packages/story-editor/src/components/elementLink/frame.js (hunk 1 above)
Comment (merapi) [reply packages/story-editor/src/components/elementLink/frame.js:84]: https://xwp.slack.com/archives/CCCAUAH6F/p1643723188141189?thread_ts=1643716364.949999&cid=CCCAUAH6F

**Review by swissspidy — APPROVED** [review]
