### PR TITLE
Editor: Fixed delay before trimming a new recording

### LINKED ISSUE #11987: Trimming UI takes a long time to appear
## Bug Description

It takes a while to show the trimming UI, sometimes it takes more time to show the trimming UI than to process the video - so that might be an even bigger issue than the final processing.
Here are the results:

<table>
<tr>
	<td><b>Video length
	<td><b>Computer
	<td><b>Time to process (insert)
	<td><b>Trim UI wait time
<tr>
	<td>10s
	<td>8yo 4c laptop
	<td>24s
	<td>3s
<tr>
	<td>10s
	<td>M1
	<td>7s
	<td>3s
<tr>
	<td>60s
	<td>8yo 4c laptop
	<td>80s
	<td>20s
<tr>
	<td>60s
	<td>M1
	<td>18s
	<td>54s
<tr>
	<td>120s
	<td>8yo 4c laptop
	<td>150s
	<td>43s
<tr>
	<td>120s
	<td>M1
	<td>25s
	<td>110s
</table>

## Expected Behaviour

Trimming UI needs to show instantly.

## Steps to Reproduce

Try on 1min+ video.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

This was surprisingly easy to fix by simply seeking to `MAX_SAFE_INTEGER` when trimming is entered with a video node with duration set to infinity (once seeking past the end, the DOM will be updated with the actual video duration).

## Testing Instructions

1. Start a video recording
2. Record at least a minute of video
3. As soon as the recording is stopped, press the scissor icon to go into trimming mode
4. Observe that trimming mode is entered instantly with (almost) no delay
5. Test this in a large combination of OS and browser

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11987

### CODE REVIEW

File: packages/story-editor/src/components/videoTrim/useVideoNode.js [hunk 1]
```diff
@@ -122,7 +122,8 @@ function useVideoNode(videoData) {
     if (isFinite(videoNode.duration) && startOffset === null) {
       onLoadedMetadata({ target: videoNode });
     } else if (!isFinite(videoNode.duration)) {
-      // Video is a blob of unknown length, wait until it finishes
+      // Video is a blob of unknown length, seek to infinity and wait until it's ready
+      videoNode.currentTime = Number.MAX_SAFE_INTEGER;
```
Comment (swissspidy) [inline packages/story-editor/src/components/videoTrim/useVideoNode.js:127]: Do we need to reset `currentTime` again in the `timeupdate` callback?

File: packages/story-editor/src/components/videoTrim/useVideoNode.js [hunk 2]
```diff
@@ -122,7 +122,8 @@ function useVideoNode(videoData) {
     if (isFinite(videoNode.duration) && startOffset === null) {
       onLoadedMetadata({ target: videoNode });
     } else if (!isFinite(videoNode.duration)) {
-      // Video is a blob of unknown length, wait until it finishes
+      // Video is a blob of unknown length, seek to infinity and wait until it's ready
```
Comment (swissspidy) [inline packages/story-editor/src/components/videoTrim/useVideoNode.js:125]: Let's link to https://bugs.chromium.org/p/chromium/issues/detail?id=642012 here for context

**Comment by merapi** [comment]
First round of testing: LG ~instant 😃 we just need to test it on different browser/os configurations.

File: packages/story-editor/src/components/videoTrim/useVideoNode.js (hunk 1 above)
Comment (barklund) [reply packages/story-editor/src/components/videoTrim/useVideoNode.js:127]: The video just restarts when looping if current time is set beyond duration, so there's no issue there.

File: packages/story-editor/src/components/videoTrim/useVideoNode.js (hunk 2 above)
Comment (barklund) [reply packages/story-editor/src/components/videoTrim/useVideoNode.js:125]: Yes, of course. Added in 616905e27f.

**Review by swissspidy — APPROVED** [review]
