### PR TITLE
Use new data when changing Link value

### LINKED ISSUE #6265: Link URL optional site icons are not updated when URL is changed
## Bug Description

Sometimes after changing the URL of an object's link, the optional brand logo is not updated with the new site's icon, and the old one appears to be retained. This may be problematic

## Expected Behaviour

If the updated URL doesn't have a site icon that can be used, I would expect that any existing site icon would be removed from the link and not shown to end users.

## Steps to Reproduce

1. Open the editor and select an object to apply a link URL to
2. Add the URL to the object - eg: TSN.ca
3. Preview the story - the brand icon is shown to the end users
4. Update the URL on the same object - eg: Bell.ca
5. Preview the story - the URL has been updated, but the previous site's icon remains in place

## Screenshots

Screen Shot 2021-02-08 at 1 29 18 PM

Screen Shot 2021-02-08 at 1 36 29 PM

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: Mac 11.2
- Browser:  Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Context
When changing a link value, previously, new metadata was used only when the new metadata was not empty. This caused odd results, e.g. having a non-matching description or wrong icon.

## Summary
This PR always uses the new values even if empty.

## Relevant Technical Choices
Disables the metadata fields while new are loading, to prevent allowing user to populate the fields and then those values to be overwritten.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add an element and open the link panel.
2. Type in a link, e.g. github.com, wait until the metadata populates.
3. Type in a new link now, e.g. bell.ca.
4. Verify that both Description and the Optional icon got overwritten (the icon was removed)

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6265

### CODE REVIEW

File: assets/src/edit-story/components/panels/design/link/link.js [hunk 1]
```diff
@@ -103,12 +103,12 @@ function LinkPanel({ selectedElements, pushUpdateForObject }) {
...
         'link',
-        (prev) =>
+        () =>
           url
             ? {
                 url,
-                desc: title ? title : prev.desc,
-                icon: icon ? toAbsoluteUrl(url, icon) : prev.icon,
+                desc: title ? title : '',
+                icon: icon ? toAbsoluteUrl(url, icon) : '',
```
Comment (barklund) [inline assets/src/edit-story/components/panels/design/link/link.js:111]: Yeah, makes sense - why should we keep the old title? It's for a different URL!

**Review by barklund — APPROVED** [review]
🎉
