### PR TITLE
Context Menu: Prevent auto focus when already focused

### LINKED ISSUE #11088: Floating Menu: Clicking the border input focuses the opacity input
## Bug Description

Clicking the border input focuses the opacity input in the floating bar for images.

## Expected Behaviour

Clicking the border input should focus the border input in the floating bar for images.

## Steps to Reproduce

1. add an image
2. click the border input

## Screenshots

click

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by samwhale**
## Summary

Clicking on the menu away from buttons and interactive elements no longer auto focuses the first focusable element.

## Relevant Technical Choices

`handleFocus` focuses the first focusable element in the context menu when the wrapper is focused. This is important when using keyboard, but if a user clicks the menu then it should not run.
https://github.com/GoogleForCreators/web-stories-wp/blob/90ca2edffaf12f1c9c4082b310d57eaf17d2addd/packages/design-system/src/components/contextMenu/menu.js#L131-L142

## To-do

n/a

## User-facing changes

|Before|After|
|--|--|
|before|after|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add an image to the canvas.
2. Click on the border input in the floating menu.
3. Click the menu or the icon in the input. The input should blur, but the opacity input should not be focused.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11088

### CODE REVIEW

File: packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js [hunk 1]
```diff
@@ -119,30 +119,27 @@ function BorderWidthAndColor() {
...
-              value={border.color || BLACK}
-              onChange={handleColorChange}
-              hasInputs={false}
-              hasEyeDropper={false}
-              allowsOpacity={canHaveBorderOpacity}
-            />
-          </>
-        )}
-      </Container>
-      <Separator />
```
Comment (samwhale) [inline packages/story-editor/src/components/floatingMenu/elements/borderWidthAndColor.js:144]: There was two separators here
image

**Review by maxyinger — APPROVED** [review]
