### PR TITLE
Design System: Datalist a11y

### LINKED ISSUE #10919: Design System: `DataList` dialog does not have `aria-label`
## Bug Description

I was getting some aXe errors on the font picker due to missing `aria-label` / `aria-labelledby` / `title` on the `<Container>` component.

Docs on `role="dialog"`: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

https://github.com/GoogleForCreators/web-stories-wp/blob/fe78d62bf89ef320638c1f66984a91c1291e521c/packages/design-system/src/components/datalist/container.js#L117-L123

## Expected Behaviour

`DataList` dialog should not cause aXe errors due to missing label / title.

It should be possible to pass a label for that container, e.g. "Font picker"

## Steps to Reproduce

1. Open font picker
2. Run aXe
3. See error

## Additional Context

- Plugin Version: 1.18.0
- WordPress Version: 5.9
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Datalists were getting flagged for missing accessibility role on their containers. 

## Summary

We use a shared `<Datalist>` component for three areas: FontPicker, Author, Publisher Logo. Recently aXe started flagging the missing title for the container role modal here, so just fixing that to appease our e2e test aXe validation. 

## Relevant Technical Choices

- Add a title prop to the data list so that the role="modal" container has a title and aXe is happy. 
- The passed in aria-label was a little confusing, it actually only labels the collapsed select button, so renamed that to make it clearer what it is labelling.

## User-facing changes

Now when you expand one of the above datalists, the div with the role 'modal' will have a title. 

And if you have aXe dev tools you can run it and make sure that this issue is resolved: 
Screen Shot 2022-03-21 at 3 26 39 PM

## Testing Instructions

Should not see this error anymore: 
Screen Shot 2022-03-21 at 12 34 28 PM

See that datalists for author, publisher logos, font family all have dialogs with a 'title'. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10919

### CODE REVIEW

File: packages/design-system/src/components/datalist/datalist.js [hunk 1]
```diff
@@ -243,6 +249,8 @@ Datalist.propTypes = {
   zIndex: PropTypes.number,
   containerStyleOverrides: PropTypes.array,
   listStyleOverrides: PropTypes.array,
+  title: PropTypes.string,
+  dropdownButtonLabel: PropTypes.string,
```
Comment (samwhale) [inline packages/design-system/src/components/datalist/datalist.js:253]: 🤔  should this be required?

**Review by samwhale — APPROVED** [review]

**Comment by samwhale** [comment]
This failing e2e test is getting fixed here: #11040 
image

**Review by BrookeGraham — APPROVED** [review]
👾
