### PR TITLE
Editor: ensure global variables are defined

### LINKED ISSUE #5964: Error: Minified React error
Hi,

I can create a new story. This is no problem:
https://one-million-places.com/web-stories

But it is not possible to open or edit an existing story!

1) I open the Story dashbord and I can see my stories
2) Then I click on "Open in Editor"
3) The main screen in the Editor is empty
4) When I click on an image or an button like "Document" I get the error: 

_Something went wrong!
The editor has crashed. Please try reloading the page and report the error using the button below.
Apologies for the inconvenience._

5) In the Console I get the error: **Minified React error #185**
6) This happens in Chrome and Firefox

screenshot

screenshot2

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

This fixes an incompatibility with a plugin mentioned in #5964, which somehow causes the global `$post` variable (and others) to be `null`.

I have not yet found the reason why said plugin does this, but explicitly defining the globals this way resolves the issue.

## Relevant Technical Choices

Explicitly define globals, suppressing PHPCS errors accordingly.

## User-facing changes

N/A

## Testing Instructions

N/A

---

Fixes #5964

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Without understanding the core issue here, I am not sure I want to merge this. This PR like a little bit of overkill to fix an issue that another plugin has created.

**Comment by swissspidy** [comment]
> Without understanding the core issue here, I am not sure I want to merge this. This PR like a little bit of overkill to fix an issue that another plugin has created.

@spacedmonkey Have you installed the test plugin I [shared on Slack](https://xwp.slack.com/archives/C013J2EGH8R/p1611063330019800)?

From what I've seen, the plugin does this:

1. `Affiliate_Links_Pro_Stats` initiates `Affiliate_Links_Pro_Report_Table`
2. `Affiliate_Links_Pro_Report_Table` extends `WP_List_Table`
3. The `WP_List_Table` constructor calls `convert_to_screen()`, which calls `WP_Screen::get()`
4. This in turn initiates quite some logic involving changing the current `WP_Screen` and calling `replace_editor`
5. We hook into  `replace_editor` to load our custom editor

Based on that testing, I think a better way to solve this would be this:

```diff
-if ( did_action( 'current_screen' ) ) {
+if ( null !== $GLOBALS['post'] && did_action( 'current_screen' ) ) {
```

This way we load our editor at the right moment, when the globals have been initialized already.

**Comment by swissspidy** [comment]
@spacedmonkey Updated the PR now based on my findings

File: includes/Story_Post_Type.php [hunk 1]
```diff
@@ -397,9 +397,9 @@ public function replace_editor( $replace, $post ) {
 		if ( self::POST_TYPE_SLUG === get_post_type( $post ) ) {
 
 			// Since the 'replace_editor' filter can be run multiple times, only load the
-			// custom editor after the 'current_screen' action when we can be certain the
+			// custom editor after the 'current_screen' action and when we can be certain the
 			// $post_type, $post_type_object, $post globals are all set by WordPress.
-			if ( did_action( 'current_screen' ) ) {
+			if ( null !== $GLOBALS['post'] && did_action( 'current_screen' ) ) {
```
Comment (spacedmonkey) [inline includes/Story_Post_Type.php]:
```suggestion
			if ( $post === $GLOBALS['post'] && did_action( 'current_screen' ) ) {
```

**Review by spacedmonkey — APPROVED** [review]
👍
