### PR TITLE
Embed block: fix embedding stories with plain permalinks

### LINKED ISSUE #5560: Embed block: not working for non-pretty permalinks
## Bug Description

As @kkalarickal just found out, the embed block does not work for URLs with non-pretty permalinks. The reason for that is a lack of URL-encoding.

While investigating this, I also realized that embedding local stories with plain permalinks did cause extra HTTP requests, even though we have some logic in place to avoid that (using `url_to_postid()`). Turns out `url_to_postid()` does not recognize plain permalinks like `https://example.com/?web-story=my-story`. It only looks for `https://example.com/?p=123` and pretty permalinks.

## Expected Behaviour

Embedding local stories with plain permalinks should work, and should not cause an extra HTTP request.

## Steps to Reproduce

1. Disable pretty permalinks in the settings
1. Add new embed block in Gutenberg and try to embed local story

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.6
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Fixes embedding local stories with plain permalinks.

## Relevant Technical Choices

1. Encodes URLs for transimission
1. Adds some custom logic to parse URLs because `url_to_postid()` does not recognize plain permalinks like `https://example.com/?web-story=my-story`.

## User-facing changes

N/A

## Testing Instructions

1. Disable pretty permalinks in the WordPress settings
1. Create a new blog post and insert a Web Stories embed block
1. Paste the URL of a web story on the same site
1. Verify that the embed is working

---

Fixes #5560

### CODE REVIEW

File: includes/REST_API/Embed_Controller.php [hunk 1]
```diff
@@ -168,15 +168,47 @@ public function get_proxy_item( $request ) {
...
 	 * @return array|false Story metadata if the URL does belong to the current site. False otherwise.
 	 */
 	private function get_data_from_post( $url ) {
+		$post_id = $this->url_to_post_id( $url );
+
+		if ( ! $post_id ) {
+			return false;
+		}
+
+		$post = get_post( $post_id );
```
Comment (spacedmonkey) [inline includes/REST_API/Embed_Controller.php]: How does this work it the post comes from another site on a multisite?

Think of this 
Main site: www.example.com and second site www.example.com/test. 
1. On www.example.com you embed, www.example.com/test/web-stories/test. 
2. Logic gets post id 123 on site 2. 
3. Get to this line, it would get post id from 123 from site 1. 

Am I missing something here?

File: includes/REST_API/Embed_Controller.php [hunk 2]
```diff
@@ -168,15 +168,47 @@ public function get_proxy_item( $request ) {
...
+	 * @SuppressWarnings(PHPMD.NPathComplexity)
+	 *
+	 * @see get_oembed_response_data_for_url
+	 *
+	 * @since 1.2.0
+	 *
+	 * @param string $url Permalink to check.
+	 * @return int|false Post ID, or false on failure.
+	 */
+	private function url_to_post_id( $url ) {
```
Comment (spacedmonkey) [inline includes/REST_API/Embed_Controller.php]: Wouldn't it be better if this method just returns the WP_Post object? The first thing that is done when is this post id is converted back to a post. Why not just cut out the middle man?

File: tests/phpunit/tests/REST_API/Embed_Controller.php [hunk 3]
```diff
@@ -237,4 +256,37 @@ public function test_removes_trailing_slashes() {
...
+
+		$expected = [
+			'title'  => '',
+			'poster' => 'https:/example.com/poster.png',
+		];
+
+		$this->assertEquals( 0, $this->request_count );
+		$this->assertNotEmpty( $data );
+		$this->assertEqualSetsWithIndex( $expected, $data );
+	}
```
Comment (spacedmonkey) [inline tests/phpunit/tests/REST_API/Embed_Controller.php:308]: Can we have some unit tests for multisite here to valid it also works.

File: includes/REST_API/Embed_Controller.php (hunk 1 above)
Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php]: There‘s some multisite switching already in place, I am not changing that. The only new part is the regex.

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
Unit tests do not pass.

**Comment by swissspidy** [comment]
@spacedmonkey I know, on it already

File: tests/phpunit/tests/REST_API/Embed_Controller.php [hunk 4]
```diff
@@ -237,4 +256,37 @@ public function test_removes_trailing_slashes() {
...
+
+	public function test_local_url_pretty_permalinks() {
```
Comment (spacedmonkey) [inline tests/phpunit/tests/REST_API/Embed_Controller.php:281]: Can we add a test for multisite here?

File: includes/REST_API/Embed_Controller.php (hunk 1 above)
Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php]: Again, the whole logic here for multisite already existed, and is mostly a copy of `get_oembed_response_data_for_url()`. I didn't change it here. It tries switching to the sub-site based on the URL, and get the post ID afterwards.

File: includes/REST_API/Embed_Controller.php [hunk 5]
```diff
@@ -222,30 +250,47 @@ private function get_data_from_post( $url ) {
...
-		$post = get_post( $post_id );
-		if ( ! $post instanceof WP_Post ) {
-			return false;
+		if ( $post_id ) {
+			$post = get_post( $post_id );
 		}
 
-		if ( Story_Post_Type::POST_TYPE_SLUG !== $post->post_type ) {
-			return false;
+		if ( ! $post_id ) {
```
Comment (spacedmonkey) [inline includes/REST_API/Embed_Controller.php:257]:
```suggestion
		else {
```

Doesn't it make more sense to use an else here?

File: tests/phpunit/tests/Discovery.php [hunk 6]
```diff
@@ -85,13 +85,16 @@ public static function wpTearDownAfterClass() {
 
 	public function setUp() {
 		parent::setUp();
+
 		$this->set_permalink_structure( '/%postname%/' );
 		$this->go_to( get_permalink( self::$story_id ) );
 	}
 
 	public function tearDown() {
+		$this->set_permalink_structure( '' );
```
Comment (spacedmonkey) [inline tests/phpunit/tests/Discovery.php:94]: Can you explain this change?

File: tests/phpunit/tests/Story_Post_Type.php [hunk 7]
```diff
@@ -76,6 +76,13 @@ public static function wpSetUpBeforeClass( $factory ) {
 		set_post_thumbnail( self::$story_id, $poster_attachment_id );
 	}
 
+	public function tearDown() {
```
Comment (spacedmonkey) [inline tests/phpunit/tests/Story_Post_Type.php:79]: Can you explain this / add a comment here.

File: includes/REST_API/Embed_Controller.php [hunk 8]
```diff
@@ -168,15 +168,39 @@ public function get_proxy_item( $request ) {
 	/**
 	 * Retrieves the story metadata for a given URL on the current site.
 	 *
-	 * @SuppressWarnings(PHPMD.NPathComplexity)
```
Comment (spacedmonkey) [inline includes/REST_API/Embed_Controller.php:171]: 🎉

File: includes/REST_API/Embed_Controller.php [hunk 9]
```diff
@@ -198,8 +222,12 @@ private function get_data_from_post( $url ) {
 
 			// In case of subdirectory configs, set the path.
 			if ( ! is_subdomain_install() ) {
+				// Get "sub-site" part of "http://example.org/sub-site/web-stories/my-story/".
+				// But given just "http://example.org/web-stories/my-story/", don't treat "web-stories" as site path.
+				// This differs from the logic in get_oembed_response_data_for_url() which does not do this.
+				// TODO: Investigate possible core bug in get_oembed_response_data_for_url()?
 				$path    = explode( '/', ltrim( $url_parts['path'], '/' ) );
-				$path    = reset( $path );
+				$path    = count( $path ) > 2 ? reset( $path ) : false;
```
Comment (spacedmonkey) [inline includes/REST_API/Embed_Controller.php:230]:
```suggestion
				$path    = count( $path ) > 2 ? reset( $path ) : '';
```
Why not default to an empty string?

File: tests/phpunit/tests/REST_API/Embed_Controller.php [hunk 10]
```diff
@@ -93,6 +116,9 @@ public function tearDown() {
 		$story_post_type = new Story_Post_type( $experiments, $meta_boxes );
 		$story_post_type->remove_caps_from_roles();
 
+		$this->set_permalink_structure( '' );
```
Comment (spacedmonkey) [inline tests/phpunit/tests/REST_API/Embed_Controller.php:119]: I would add a comment to explain this.

File: tests/phpunit/tests/Discovery.php (hunk 6 above)
Comment (swissspidy) [reply tests/phpunit/tests/Discovery.php:94]: This is just some regular cleanup for these tests. The `setUp` calls `$this->set_permalink_structure( '/%postname%/' );`, so it's important to reset that again; otherwise it will affect other tests in other files.

File: tests/phpunit/tests/Story_Post_Type.php (hunk 7 above)
Comment (swissspidy) [reply tests/phpunit/tests/Story_Post_Type.php:79]: This is just some regular cleanup for these tests. Some tests call `$this->set_permalink_structure( '/%postname%/' );`, so it's important to reset that again; otherwise it will affect other tests in other files.

File: includes/REST_API/Embed_Controller.php (hunk 8 above)
Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php:171]: The complexity is now just in the new method but psst :-)

File: includes/REST_API/Embed_Controller.php (hunk 9 above)
Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php:230]: Doesn't matter too much, just needs to be falsey for the check below.

File: includes/REST_API/Embed_Controller.php (hunk 5 above)
Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php:257]: The result is exactly the same, so just a matter of preference for coding style and readability.

Aside: PHPMD [by default](https://phpmd.org/rules/cleancode.html) complains about using `else` branches, but we've disabled that.

File: tests/phpunit/tests/REST_API/Embed_Controller.php (hunk 10 above)
Comment (swissspidy) [reply tests/phpunit/tests/REST_API/Embed_Controller.php:119]: I don't think a cleanup in `tearDown` for something `setUp` does necessarily warrants a comment.

**Review by spacedmonkey — APPROVED** [review]
Approved with a couple of nitpicks. 

Tested locally with multisite and seems to work.

File: includes/REST_API/Embed_Controller.php (hunk 9 above)
Comment (spacedmonkey) [reply includes/REST_API/Embed_Controller.php:230]: Empty string is a default value of get_networks.

Comment (swissspidy) [reply includes/REST_API/Embed_Controller.php:230]: Right, but `$path is only used below when `if ( $path && $network instanceof \WP_Network )` evaluates to true. So this won't make a difference.

I can change it though, no problem. Prevents accidental bugs in the future 👍  Just wanted to point that out :)
