### PR TITLE
Replace mime types with file extensions in error message

### LINKED ISSUE #976: Mime types instead of file extension used in upload texts
## Bug Description

When dragging images to the editor, we show the user which file types are allowed. This used to be a list of file extensions (png, jpeg, etc.), but seems to have regressed and now is a list of mime types (image/png, image/jpeg, etc.), which is not very user friendly.

## Expected Behaviour

We should only show file extensions to the user.

## Steps to Reproduce

Drag media on to the canvas or library.

## Screenshots

Screenshot 2020-04-02 at 14 16 48

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by joannag6**

### CODE REVIEW

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js [hunk 1]
```diff
@@ -87,10 +87,12 @@ function useUploadMedia({ media, pagingNum, mediaType, fetchMedia, setMedia }) {
             sprintf(
               /* translators: %s: list of allowed file types. */
               __('Please choose only <b>%s</b> to upload.', 'web-stories'),
-              allowedMimeTypes.join(
-                /* translators: delimiter used in a list */
-                __(', ', 'web-stories')
-              )
+              allowedMimeTypes
+                .map((type) => type.replace('image/', '').replace('video/', ''))
```
Comment (winterDroid) [inline assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Should this be extracted and used in all places? Should there be tests?
What about instead just splitting the mime type and using the second part if any?

**Comment by swissspidy** [comment]
@joannag6 Could you follow the CLA bot's advice above?

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Indeed looks like a great candidate to extract and add a quick unit test for it. Perhaps as its own `useAllowedFileTypes` hook in `assets/src/edit-story/utils`.

Should be quick to write with `split` and using the second part, as you suggest. We could probably even prefix the result with a dot so `image/png` gets turned into `.png`

Also, the way `allowedMimeTypes` is assembled throughout is different:

```js
const { allowedMimeTypes = {} } = useConfig();
const allowedFileTypes = Object.keys(allowedMimeTypes).reduce(
  (acc, cur) => [...acc, ...allowedMimeTypes[cur]],
  []
);

// vs.

const {
  allowedMimeTypes: {
    image: allowedImageMimeTypes,
    video: allowedVideoMimeTypes,
  },
} = useConfig();
const allowedMimeTypes = [...allowedImageMimeTypes, ...allowedVideoMimeTypes];
```

The first approach seems more future proof.

So the result could look something like (untested):

```js
function useAllowedFileTypes() {
  const { allowedMimeTypes = {} } = useConfig();
  const allowedFileTypes = Object.keys(allowedMimeTypes).reduce(
    (acc, cur) => [...acc, ...allowedMimeTypes[cur]],
    []
  );

  allowedMimeTypes
    .map((type) => '.' + type.split('/')[1])
    .join(
      /* translators: delimiter used in a list */
      __(', ', 'web-stories')
     );

  return allowedMimeTypes;
}
```

**Comment by spacedmonkey** [comment]
There is a number simpler way to get file types. There is a property in the config called `allowedFileTypes`, please just use that.

**Comment by swissspidy** [comment]
Huh, is that new? Even better!

**Comment by spacedmonkey** [comment]
@swissspidy Nope, that is the way it justed to be before it was changed.

**Comment by joannag6** [comment]
Thanks! Using allowedFileTypes instead.

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 1 above)
Comment (joannag6) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Using allowedFileTypes instead.

File: assets/src/edit-story/components/uploadDropTarget/message.js [hunk 2]
```diff
@@ -65,11 +65,8 @@ const Icon = styled(UploadIcon)`
 `;
 
 function UploadDropTargetMessage({ message, ...rest }) {
-  const { allowedMimeTypes = {} } = useConfig();
-  const allowedFileTypes = Object.keys(allowedMimeTypes).reduce(
-    (acc, cur) => [...acc, ...allowedMimeTypes[cur]],
-    []
-  );
+  const { allowedFileTypes = {} } = useConfig();
```
Comment (swissspidy) [inline assets/src/edit-story/components/uploadDropTarget/message.js]:
```suggestion
  const { allowedFileTypes = [] } = useConfig();
```

Only arrays have a `join` method, not objects. So the default value here should be an empty array.

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js [hunk 3]
```diff
@@ -40,13 +40,7 @@ import usePreventWindowUnload from '../../../utils/usePreventWindowUnload';
...
   const { uploadFile } = useUploader();
   const { showSnackbar } = useSnackbar();
-  const {
-    allowedMimeTypes: {
-      image: allowedImageMimeTypes,
-      video: allowedVideoMimeTypes,
-    },
-  } = useConfig();
-  const allowedMimeTypes = [...allowedImageMimeTypes, ...allowedVideoMimeTypes];
+  const { allowedFileTypes = {} } = useConfig();
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]:
```suggestion
  const { allowedFileTypes = [] } = useConfig();
```

Only arrays have a `join` method, not objects. So the default value here should be an empty array.

File: assets/src/edit-story/app/uploader/useUploader.js [hunk 4]
```diff
@@ -47,6 +47,7 @@ function useUploader(refreshLibrary = true) {
       video: allowedVideoMimeTypes,
     },
   } = useConfig();
+  const { allowedFileTypes = {} } = useConfig();
```
Comment (swissspidy) [inline assets/src/edit-story/app/uploader/useUploader.js]: This can be added to the `useConfig` call above. Also, use `[]` as the default.

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: That being said, adding a default value for `allowedFileTypes` might conceal potential bugs. It should always be set in the editor, and for tests it should be mocked.

For example, in `assets/src/edit-story/components/library/test/mediaPane.js`, the `should only display supported mimeTypes and not crash on unsupported` currently fails because `allowedFileTypes` isn't mocked.

**Review by swissspidy — CHANGES_REQUESTED** [review]
A few minor comments, but we're getting there 👍 🚀

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
`allowedFileTypes` needs to be mocked in tests, as the tests are currently failing. 

I know this is now a related to this exact bug, the gramma in this error never really made sense.

`Please choose only jpg, png, webm, mp4 to upload.` 
should read
`Please choose only jpg, png, webm or mp4 to upload.` 
or better
`Please choose a file with the extension of jpg, png, webm or mp4 to upload.`

**Comment by swissspidy** [comment]
> I know this is now a related to this exact bug, the gramma in this error never really made sense.

Agreed, but getting the `jpg, png, webm or mp4` part with the `or` before the last item right for internationalization is not super simple. It basically requires a JS implementation of [`wp_sprintf_l`](https://developer.wordpress.org/reference/functions/wp_sprintf_l/#source). I'd do this in a separate issue & PR that can be appropriately sized and tested.

**Comment by spacedmonkey** [comment]
I have create another issue for the gramma issue - https://github.com/google/web-stories-wp/issues/1347

File: assets/src/edit-story/components/uploadDropTarget/message.js (hunk 2 above)
Comment (joannag6) [reply assets/src/edit-story/components/uploadDropTarget/message.js]: Done

File: assets/src/edit-story/app/uploader/useUploader.js (hunk 4 above)
Comment (joannag6) [reply assets/src/edit-story/app/uploader/useUploader.js]: Done

File: assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js (hunk 3 above)
Comment (joannag6) [reply assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js]: Good point, removed the default value and mocked it in tests.

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
Merging latest master or rebasing should fix that one Travis CI issue.

**Review by spacedmonkey — APPROVED** [review]
LGTM
