### PR TITLE
Use correct input value for "Add color preset" from Color Picker

### LINKED ISSUE #1853: Clicking on add to color presets not working.
## Bug Description

Clicking on the "Add to color preset" option is not working. 

## Expected Behaviour

Expected new color to be added to the presets section. 

## Steps to Reproduce

Add text element to page
Change text element color to a new color
Click on "Add to color preset" in the color selector, note that nothing is added to presets. 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fix the link style.

## Summary

Fixes using incorrect value for rendering the footer of Color Picker.

Also restores the style of the link based on Figma.

## User-facing changes

- Adding as color preset from Color Picker works again.
- The color of the link is changed based on Figma.

## Testing Instructions

1. Add a Text (or a Shape)
2. Open the Color Picker for the text
3. Choose a Color
4. Click on "Add to Color Preset"
5. See the color appearing under Presets

---

Fixes #1853

### CODE REVIEW

File: assets/src/edit-story/components/colorPicker/colorPicker.js [hunk 1]
```diff
@@ -165,7 +165,7 @@ function ColorPicker({
             onChange={updateCurrentColor}
             showOpacity={hasOpacity}
           />
-          {renderFooter && renderFooter(generatedColor)}
+          {renderFooter && renderFooter(color)}
```
Comment (barklund) [inline assets/src/edit-story/components/colorPicker/colorPicker.js:168]: I'm not sure I understand how it partially worked before and fully works now? What's the essence of this change?

**Review by barklund — APPROVED** [review]
Looks good, just want to understand it.

File: assets/src/edit-story/components/colorPicker/colorPicker.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/colorPicker/colorPicker.js:168]: It looked like `generatedColor` was always `null` when the color picker rendered unless making any changes: `null` resulting in the preset action not working.

At least that's what it seemed that the issue was -- after you asked, I tested it more, and it looks like each change in the color picker causes quite a few re-renders, `console.log` output for `generatedColor` (outside of effects) is this:
Screenshot 2020-05-21 at 19 08 48
 
==> Result: Adding to color preset action will always receive `null` value by the time of clicking.

I'm not super familiar with the inner life of `generatedColor` vs `color` vs `currentColor` -- does it seem like something is not working as expected with the `colorPicker` and needs further investigation?

(I can look more into this tomorrow)

Comment (barklund) [reply assets/src/edit-story/components/colorPicker/colorPicker.js:168]: Well, if it works now, it works.
