### PR TITLE
E2E Tests: Fix flakey Publishing Flow test

### LINKED ISSUE #6062: E2E Tests: Fix flakey Publishing Flow test
## Task Description

Example: https://github.com/google/web-stories-wp/runs/1768135044?check_suite_focus=true#step:13:18

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Context

Improve  Publishing Flow test  by [copying](https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src/create-new-post.js#L37-L63) some of utils from gutenberg's [e2e-test-utils](https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src).

### QA

* [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

* [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6062

### CODE REVIEW

File: tests/e2e/specs/editor/publishingFlow.js [hunk 1]
```diff
@@ -69,6 +69,9 @@ describe('Publishing Flow', () => {
     await expect(page).toClick('a', { text: 'Add to new post' });
     await page.waitForNavigation();
 
+    // See https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src/create-new-post.js#L37-L63.
+    await page.waitForSelector('.edit-post-layout');
```
Comment (spacedmonkey) [inline tests/e2e/specs/editor/publishingFlow.js:73]: I think the issue, was we needed to wait for the gutenberg editor to load fully. Waiting on this selector will do that. Everything else is just extra, but can't hurt anything.

File: tests/e2e/specs/editor/publishingFlow.js [hunk 2]
```diff
@@ -78,6 +81,22 @@ describe('Publishing Flow', () => {
       await page.evaluate(() =>
         wp.data.dispatch('core/edit-post').toggleFeature('welcomeGuide')
       );
+
+      await page.reload();
```
Comment (swissspidy) [inline tests/e2e/specs/editor/publishingFlow.js:85]: Is the full page reload really needed? :/

Comment (spacedmonkey) [reply tests/e2e/specs/editor/publishingFlow.js:85]: It was copied from [here](https://github.com/WordPress/gutenberg/blob/c31555d4cec541db929ee5f63b900c6577513272/packages/e2e-test-utils/src/create-new-post.js#L37-L63). 

It is only one reload, it gutenberg is doing it, it must be for a reason.
