### PR TITLE
Use only one set of color presets for text, shape, page background

### LINKED ISSUE #2585: Color Presets: Text, Shape, Page should all share the same color presets
## Bug Description

Currently, the Text color presets are separated from the shape and page presets.

## Expected Behaviour
- Text, Shape, Page should share the same color presets
- When a preset includes gradient, it's grayed out and with a tooltip explaining that Text color can't have gradient.
- Text presets are for the text only, not for the Text background.

## Steps to Reproduce
1. Add a text element and a shape.
2. Click on the shape, add a preset.
3. Now click on the text -- the preset added via shape is not visible.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Uses single set of color presets for all elements.

## Relevant Technical Choices
- Removes `textColors` completely for now since these will likely not be used anymore.

## Testing Instructions
I
1. Add a Text element.
2. Add some color presets.
3. Add a Shape
4. Verify the same color presets are available for the Shape as well.

II
1. Add a Shape element.
2. Add a color preset with gradient
3. Add a Text element
4. Verify that the same color presets are present for the Text, however, the preset with gradient is grayed out and can't be used.

---

Fixes #2585

### CODE REVIEW

File: assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js [hunk 1]
```diff
@@ -57,11 +57,11 @@ const getThirdArguments = (calls) => {
...
 describe('stylePresets/PresetGroup', () => {
   it('should modify active index correctly with arrow keys', () => {
-    const { itemRenderer, getByText } = setupPresetGroup();
+    const { itemRenderer, getAllByRole } = setupPresetGroup();
     expect(getThirdArguments(itemRenderer.mock.calls)).toStrictEqual([0, 0, 0]);
 
-    const label = getByText('Colors');
-    const group = label.nextSibling;
+    const firstButton = getAllByRole('button')[0];
+    const group = firstButton.parentNode;
```
Comment (barklund) [inline assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js:65]: Hm, maybe a better way to get this would be to put a `role="listbox"` on the group?

Comment (barklund) [reply assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js:65]: And this group could even have a `aria-labelledby` pointing to the label element (_"Colors"_) before it making the query even cleaner.

File: assets/src/edit-story/components/panels/stylePreset/utils.js [hunk 2]
```diff
@@ -113,3 +108,7 @@ export function presetHasOpacity(preset) {
   }
   return opacityFound;
 }
+
+export function presetHasGradient({ type }) {
+  return Boolean(type && 'solid' !== type);
```
Comment (barklund) [inline assets/src/edit-story/components/panels/stylePreset/utils.js]:
```suggestion
  return Boolean(type) && 'solid' !== type;
```

**Review by barklund — APPROVED** [review]
Looks good - a couple of nits.

File: assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js:65]: "Colors" label was removed (for now) so can't really label it by it anymore unfortunately. About the listbox -- in this case the buttons would need to turn to options which also doesn't seem really accurate.

Perhaps we can leave it as-is until the final UX gets resolved for the presets?

File: includes/Database_Upgrader.php [hunk 3]
```diff
@@ -186,6 +187,31 @@ protected function remove_broken_text_styles() {
 		update_option( Stories_Controller::STYLE_PRESETS_OPTION, $updated_style_presets );
 	}
 
+	/**
+	 * Migration for version 2.0.3.
+	 * Color presets: Removes fillColor and textColor and unifies to one color.
+	 */
```
Comment (swissspidy) [inline includes/Database_Upgrader.php:193]:
```suggestion
	 *
	 * @return void
	 */
```

File: includes/Database_Upgrader.php [hunk 4]
```diff
@@ -186,6 +187,33 @@ protected function remove_broken_text_styles() {
 		update_option( Stories_Controller::STYLE_PRESETS_OPTION, $updated_style_presets );
 	}
 
+	/**
+	 * Migration for version 2.0.3.
+	 * Color presets: Removes fillColor and textColor and unifies to one color.
+	 *
+	 * @return void
+	 */
+	protected function unify_color_presets() {
```
Comment (miina) [inline includes/Database_Upgrader.php:194]: Hmm, the tests are now failing for DB Upgrader since the upgrades always run through all the scripts when running `init()` meaning that the results seem to be combined for all migrations combined and not just for one migration.

Since `textColors` is removed within this PR then the previous tests fail.

@swissspidy Thoughts? Is there a way to define the `'WEBSTORIES_DB_VERSION'` per test?

Comment (swissspidy) [reply includes/Database_Upgrader.php:194]: Hmm good question. Let me take a look.

/cc @spacedmonkey

Comment (swissspidy) [reply includes/Database_Upgrader.php:194]: Should each test just do `add_option( \Google\Web_Stories\Database_Upgrader::PREVIOUS_OPTION, 'VERSION_BEFORE_THIS_PARTICULAR_MIGRATION' );`?

edit: although that would run later migrations too...

Comment (spacedmonkey) [reply includes/Database_Upgrader.php:194]: We could filter the value of the option using `pre_option_web_stories_db_version` filter?

File: assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/stylePreset/test/presetGroup.js:65]: Sure, but maybe put a comment in somewhere with a todo.

File: includes/Database_Upgrader.php (hunk 4 above)
Comment (miina) [reply includes/Database_Upgrader.php:194]: > edit: although that would run later migrations too...

Yep, unfortunately.

> We could filter the value of the option using `pre_option_web_stories_db_version` filter?

The version would need to change before migration and right after the migration -- to prevent the following migrations running. Filtering with `pre_option_...` would still run the later migrations as well.

For testing purposes, we'd need only one single migration to work.

We could for example:
- Allow filtering the `$routines` (we could then remove all but the relevant routine while testing)
- Add a filter for the version where the version is checked per each routine, e.g. into `run_upgrade_routine` (We could then make the version mismatch for the routines that we're not testing)
- Make `run_upgrade_routine` public and allow running the migrations for a certain version.

Any other ideas? Thoughts?

Comment (swissspidy) [reply includes/Database_Upgrader.php:194]: I'd simply use reflection to make the individual routines public during tests, and call that routine directly instead of `init` or `run_upgrade_routine`.

Can copy https://github.com/ampproject/amp-wp/blob/1c5d7b23b018142d58caea37c223facf17953905/tests/php/src/PrivateAccess.php to `tests/phpunit/includes` for that

Comment (miina) [reply includes/Database_Upgrader.php:194]: Sounds much better, will check 👍

Comment (spacedmonkey) [reply includes/Database_Upgrader.php:194]: Can you just force the database version to `2.0.2` before the test runs?

Comment (spacedmonkey) [reply includes/Database_Upgrader.php:194]: I would also just reset the database version to not after every test for good messure.

Comment (miina) [reply includes/Database_Upgrader.php:194]: > Can you just force the database version to 2.0.2 before the test runs? 

`init` runs all the tests since version X. This means that it would run all the migrations since 2.0.2 if new ones are added, not just this one. We need a way to test only one migration at a time.

This needs to be changed for the previously existing tests, too.

E.g. if for the first test we force the version to be 2.0.0. then 2.0.1 and 2.0.2 would also run -- it's still not reliable.

File: tests/phpunit/includes/Private_Access.php [hunk 5]
```diff
@@ -0,0 +1,93 @@
+<?php
+/**
+ * Trait PrivateAccess.
+ *
+ * @package AmpProject\AmpWP
```
Comment (swissspidy) [inline tests/phpunit/includes/Private_Access.php]: Let's remove the whole docblock here. Not really necessary for a tests file

File: tests/phpunit/includes/Private_Access.php [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+use ReflectionClass;
+use ReflectionException;
+
+/**
+ * Trait Private_Access.
+ *
+ * Allows accessing private methods and properties for testing.
+ *
+ * @internal
+ * @since 1.5.0
```
Comment (swissspidy) [inline tests/phpunit/includes/Private_Access.php]:
```suggestion
```

**Review by swissspidy — APPROVED** [review]
