### PR TITLE
Fixed rtl placement for popups

### LINKED ISSUE #6804: Text Panel - With RTL the colour picker goes off screen
## Bug Description

When RTL is enabled the colour picker is cut off the screen. 

## Screenshots

image5

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

This fixes the popup placement calculation in RTL contexts by flipping some left and right logic in those cases.

As I fixed this, I noticed a bug in the color picker itself (which was never visible before as the color picker itself was never usable in RTL) with the pointer being wrongly aligned - I fixed this too.

## User-facing changes

| Before | After |
|-|-|
| Screen Shot 2021-05-04 at 16 56 51 | Screen Shot 2021-05-04 at 16 54 25 |
| Screen Shot 2021-05-04 at 17 08 26 | Screen Shot 2021-05-04 at 17 07 34 |

### QA

This PR can be tested by following these steps:

1. Flip WP admin to RTL
2. Select the background element
3. Open the color picker
4. Observe that it is correctly placed adjacent to but not overlapping the design panel
5. Use the color picker saturation selector to pick a color
6. Observe that the sample circle is correctly placed relative to the selection

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6804

### CODE REVIEW

File: assets/src/edit-story/components/colorPicker/pointer.js [hunk 1]
```diff
@@ -60,10 +66,9 @@ const Pointer = styled.div.attrs(({ currentColor, withAlpha }) => {
...
 `;
 
-Pointer.defaultProps = {
-  currentRGB: {},
-  currentRGBA: {},
-  currentColor: {},
-};
+function Pointer(props) {
+  const { isRTL } = useConfig();
+  return <PointerElement {...props} isRTL={isRTL} />;
```
Comment (swissspidy) [inline assets/src/edit-story/components/colorPicker/pointer.js:71]:
```suggestion
  return <PointerElement {...props} $isRTL={isRTL} />;
```

So we don't pollute the DOM with this prop. Of course need to update the styled component above as well.

File: assets/src/edit-story/components/colorPicker/pointer.js [hunk 2]
```diff
@@ -42,7 +47,8 @@ const Pointer = styled.div.attrs(({ currentColor, withAlpha }) => {
   width: ${POINTER_SIZE}px;
   height: ${POINTER_SIZE}px;
   transform: translate(
-    ${({ offsetX = 0, offsetY = 0 }) => `${offsetX}px, ${offsetY}px`}
+    ${({ offsetX = 0, offsetY = 0, isRTL }) =>
+      `${(isRTL ? 1 : 1) * offsetX}px, ${offsetY}px`}
```
Comment (miina) [inline assets/src/edit-story/components/colorPicker/pointer.js]:
```suggestion
      `${(isRTL ? -1 : 1) * offsetX}px, ${offsetY}px`}
```

**Review by miina — APPROVED** [review]
LGTM! (Pending the comments). Thanks for cleaning it up a bit, too.

**Comment by swissspidy** [comment]
Feasible to add some tests here?

File: assets/src/edit-story/components/colorPicker/pointer.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/colorPicker/pointer.js:71]: `isRTL` is never a valid HTML prop for any element, so it's not relevant. This prop will never pollute the DOM output as React will filter it out as an invalid DOM property.

Transient props are only important for attributes, that *are* valid HTML attributes, but just not used as such. E.g. `title`, `offset`, `background`, `x` etc.

Comment (barklund) [reply assets/src/edit-story/components/colorPicker/pointer.js:71]: One could argue that we should use transient naming for all props used only for S-C that aren't supposed to go into the DOM, as a rule, to avoid forgetting it when it's important, but I think that's overkill. I think we should just remember to do this for properties, where this is a problem - and try to remind each other if we forget.

File: assets/src/edit-story/components/colorPicker/pointer.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/colorPicker/pointer.js]: How did I manage to remove this before pushing? I clearly had this when creating the above screenshots? Weiiiiiird... 🤷‍♂️

**Comment by barklund** [comment]
> Feasible to add some tests here?

@swissspidy, good idea - I'll make sure to grab some screenshots of this.
