### PR TITLE
Prevent registering the same script module with different IDs

### LINKED ISSUE #14155: Duplicate script modules output to frontend when using embed block
## Bug Description

I created a story and then added an embed block to feature it. When I looked at the source or the page, I see two script modules being added to the page. They have different handles but the same `src`:

```html
<script type="module" src="http://localhost:10018/wp-content/plugins/web-stories/assets/js/web-stories-block-view.js?ver=4423b9fde557f8942d2c" id="web-stories-embed-view-script-module-js-module"></script>
<script type="module" src="http://localhost:10018/wp-content/plugins/web-stories/assets/js/web-stories-block-view.js?ver=4423b9fde557f8942d2c" id="web-stories-block-view-js-module"></script>
```

## Expected Behaviour

There should not be any duplicate script modules.

## Additional Context

- Plugin Version: 1.42.0
- WordPress Version: 6.8.1
- Operating System: MacOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #14155

### CODE REVIEW

File: includes/Renderer/Stories/Renderer.php [hunk 1]
```diff
@@ -356,7 +356,7 @@ public function render_single_story_content(): void {
 		}
 
 		$this->assets->enqueue_script_module(
-			'web-stories-block-view',
+			'web-stories-embed-view-script-module',
 			$this->assets->get_base_url( 'assets/js/web-stories-block-view.js' )
```
Comment (westonruter) [inline includes/Renderer/Stories/Renderer.php:360]: Come to think of it, with the change to the script module ID, is the src parameter even needed then? Won't it have been registered already with the block?

```suggestion
			'web-stories-embed-view-script-module'
```

Comment (swissspidy) [reply includes/Renderer/Stories/Renderer.php:360]: I register it here separately because the story might be embedded with a shortcode, not through the block.

**Review by swissspidy — APPROVED** [review]
Thanks a lot for your report & PR!

File: includes/Renderer/Stories/Renderer.php (hunk 1 above)
Comment (westonruter) [reply includes/Renderer/Stories/Renderer.php:360]: Wouldn't it still have been registered by WordPress? It would need to be enqueued here, but it wouldn't need to be registered, would it?
