### PR TITLE
Fix: Remove `WP_Post` type hint from `prefill_post_content`

### LINKED ISSUE #13405: Remove parameter type hints from `prefill_post_content`
## Task Description

Source: https://wordpress.org/support/topic/web-stories-plugin-fatal-error/

Apparently the `$post` object can be not just `WP_Post`, but also `null`.

Looks like that can happen when plugins implement the same `default_content`/`default_title` filters but don't actually provide the object 🙄 

For example https://wordpress.org/plugins/usc-e-shop/ does this.

(Source: https://wpdirectory.net/search/01H46AJV6MXJJF78VFZ3SN4A25)

### PR DESCRIPTION
**Pull request by AnuragVasanwala**
## Context

The goal of the PR is to fix fatal error when providing `null` value to the second parameter `$post` of the function `Google\Web_Stories\Admin\Admin::prefill_post_content()`.

## Summary

Supplying `null` value to the second parameter `$post` of the function `Google\Web_Stories\Admin\Admin::prefill_post_content()` causes fatal error as the respected parameter type is explicitly defined as `WP_Post`. Thus, removing `WP_Post` type and updating `phpdoc` resolves the issue.

## Relevant Technical Choices

Not applicable.

## User-facing changes

Not applicable.

## Testing Instructions

Not applicable.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #13405

### CODE REVIEW

**Comment by AnuragVasanwala** [comment]
@swissspidy Minimum PHP version requirement for `web-stories-wp` plugin is `7.4`. With version `7.1.x`, [nullable type](https://www.php.net/manual/en/migration71.new-features.php) is supported and thus, I have updated `WP_Post` type with nullable type support (commit ref: https://github.com/GoogleForCreators/web-stories-wp/pull/13430/commits/21fe4da21028d491d7e5be412ced4c9e0deafdc0) for the `prefill_post_content` function.

Also, would you please guide me for the failed test cases?

File: includes/Admin/Admin.php [hunk 1]
```diff
@@ -128,10 +128,15 @@ public function admin_body_class( $class ) {
...
-	 * @param WP_Post      $post    Post object.
+	 * @param WP_Post|null $post    Post object.
 	 * @return string|mixed Pre-filled post content if applicable, or the default content otherwise.
 	 */
-	public function prefill_post_content( $content, WP_Post $post ) {
+	public function prefill_post_content( $content, ?WP_Post $post ) {
+		// When $post is NULL, set -1 to suppress phpstan error: Parameter #1 $post of function use_block_editor_for_post expects int|WP_Post, WP_Post|null given.
+		if ( \is_null( $post ) ) {
+			$post = -1;
+		}
```
Comment (swissspidy) [inline includes/Admin/Admin.php]: Hmm let‘s do `if ( ! $post ) { return $content; }` to be on the safe side. Because if we don't have a proper post object, then there's something wonky going on and we should just abort.

```suggestion
		if ( ! $post ) {
			return $content;
		}
```

**Comment by swissspidy** [comment]
> @swissspidy Minimum PHP version requirement for `web-stories-wp` plugin is `7.4`. With version `7.1.x`, [nullable type](https://www.php.net/manual/en/migration71.new-features.php) is supported and thus, I have updated `WP_Post` type with nullable type support (commit ref: [21fe4da](https://github.com/GoogleForCreators/web-stories-wp/commit/21fe4da21028d491d7e5be412ced4c9e0deafdc0)) for the `prefill_post_content` function.
> 
> Also, would you please guide me for the failed test cases?

Ah yes, nullable works too I suppose. No need to add a test case.

File: includes/Admin/Admin.php (hunk 1 above)
Comment (AnuragVasanwala) [reply includes/Admin/Admin.php]: Seems like a good plan!

**Review by swissspidy — APPROVED** [review]
