### PR TITLE
Dashboard: Add Default View to Router

### LINKED ISSUE #11055: Accessibility: Skip to content link does not work
## Bug Description

When using keyboard navigation, a "Skip to content" link is shown. When pressing enter, the url changes and but nothing happens. Worse in dashboard, the content is cleared. See video. 

## Screenshots

https://user-images.githubusercontent.com/237508/159733308-af0bfb75-a879-424a-b856-2bf48da1ca12.mov

https://user-images.githubusercontent.com/237508/159733286-a288b33d-2b43-4c80-966d-7cfd05c2a4d8.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

This came up because when you skip to "main content" using `tab` when the dashboard loads as a keyboard user the Stories Dashboard doesn't actually allow the main content of the Dashboard  because the `Dashboard` has a path of `/` so it needs be an exact match otherwise it'll always show it since every other route has a path that will partially match `/`.

## Summary

Now `post_type=web-story&page=stories-dashboard#wpbody-content` will return the dashboard, as will `post_type=web-story&page=stories-dashboard#` and `post_type=web-story&page=stories-dashboard#/ajsdflkajdlkajsdfklasdf`.

## Relevant Technical Choices

Our router is an in-house solution because it is so minimal. I chose to add a new prop for `<Route>` called `isDefault`. This gave me the wiggle room necessary to have the dashboard base path of `/` be both `exact` and `isDefault` so that if it's exact it'll render and if it's not it will only render when no other routes also fit the criteria. I didn't want to mess with the base path for the entire dashboard. 

This means I also added complexity to the router provider and initial mount of the Dashboard. Now we track the available routes and tell the provider what the default path is so that we can use it when `<Route>` calls for it. 

## To-do

N/A

## User-facing changes

(note the `&page=stories-dashboard#wpbody-content` in the url path)

| Before | After | 
| --- | --- | 
| Screen Shot 2022-04-01 at 4 17 42 PM |  Screen Shot 2022-04-01 at 4 17 13 PM |

## Testing Instructions

Head to the Stories Dashboard and verify that Dashboard loads by default, that "Explore Templates" and "Template Details" still work as expected. 
Now use the keyboard to navigate to "Main Content" skip button (tab through WP admin toolbar, if you just loaded the page it'll be the first tab). Hit "Enter" on "Main Content" and you should still see the dashboard. 

Type in some wrong paths off of the dashboard base path `&page=stories-dashboard` like `&page=stories-dashboard#/jalkfjalkjflakdjflk` and see that the dashboard default view is still showing. 

Also test a user that has no stories yet. What happens there is on the first page load the user is sent to "Explore Templates", the user interacting with "Main Content" for keyboard user is no longer the initial load so it'll actually bring the user to Dashboard Stories instead. 

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11055

### CODE REVIEW

File: packages/e2e-tests/src/specs/dashboard/dashboard.js [hunk 1]
```diff
@@ -42,6 +42,27 @@ describe('Stories Dashboard', () => {
     await takeSnapshot(page, 'Stories Dashboard', { percyCSS });
   });
 
+  it('should be able to skip to main content of Dashboard', async () => {
+    await visitDashboard();
+
+    // If there are no existing stories, the app goes to the templates page instead.
+    // Account for both here, but then force-visit the dashboard.
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/dashboard.js]: To account for the "force-visit" part this is missing the

```js
await expect(page).toClick('[aria-label="Main dashboard navigation"] a', {
  text: 'Dashboard',
});
```

part

File: packages/e2e-tests/src/specs/dashboard/dashboard.js [hunk 2]
```diff
@@ -42,6 +42,27 @@ describe('Stories Dashboard', () => {
...
+    // When navigating to Dashboard, immediately use keyboard to
+    // tab to WordPress shortcut of "Main Content"
+    page.keyboard.press('Tab');
+    page.keyboard.press('Enter');
+
+    await expect(page).toMatchElement('h2', {
+      text: /(Dashboard|Explore Templates)/,
+    });
+
+    await takeSnapshot(page, 'Stories Dashboard on Main Content', { percyCSS });
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/dashboard.js]: A detail, but could we perhaps also test whether the skip link is visible and that the next Tab goes straight to the "Create New Story" link

**Review by maxyinger — APPROVED** [review]
nice catch

File: packages/e2e-tests/src/specs/dashboard/dashboard.js (hunk 1 above)
Comment (BrittanyIRL) [reply packages/e2e-tests/src/specs/dashboard/dashboard.js]: Thanks! Realized I actually don't want to force anything and we just want to see what happens with the navigation by keyboard once we're in the Stories Dashboard. Fixed this up and added better comments.

File: packages/dashboard/src/app/router/routerProvider.js [hunk 3]
```diff
@@ -34,6 +34,8 @@ function RouterProvider({ children, ...props }) {
   const [currentPath, setCurrentPath] = useState(
     history.current.location.pathname
   );
+  const [availableRoutes, setAvailableRoutes] = useState([]);
+  const [defaultRoute, setDefaultRoute] = useState();
```
Comment (samwhale) [inline packages/dashboard/src/app/router/routerProvider.js]: 💭 This is always `APP_ROUTES.DASHBOARD`, so I don't think the state is needed here. This could be passed into `matchParams` as `defaultRoute`

But lmk if I'm missing why this may need to be different

File: packages/dashboard/src/components/interfaceSkeleton/index.js [hunk 4]
```diff
@@ -87,6 +89,23 @@ const InterfaceSkeleton = ({ additionalRoutes }) => {
     });
   }, [addInitialFetchListener, push, currentPath, canViewDefaultTemplates]);
 
+  // Only set the available routes & default route on initial mount
```
Comment (samwhale) [inline packages/dashboard/src/components/interfaceSkeleton/index.js:92]: 💭 if it's only being set on initial mount, could this be set using a state hook rather than an effect?

Does this need to happen in an effect?

File: packages/dashboard/src/app/router/route.js [hunk 5]
```diff
@@ -67,22 +67,58 @@ export function resolveRoute(route) {
...
+  availableRoutes,
+  defaultRoute,
+  isDefault = false,
+  exact = false,
+}) {
   const match = new RegExp(`^${path}`).exec(currentPath);
-  if (!match) {
+
+  // allow paths through that don't match if they are default, not narrowed out yet.
+  if (!match && !isDefault) {
```
Comment (samwhale) [inline packages/dashboard/src/app/router/route.js:81]: So a route may not match but it could be the default?

File: packages/dashboard/src/app/router/route.js [hunk 6]
```diff
@@ -67,22 +67,58 @@ export function resolveRoute(route) {
...
+
+  // Find all available url matches
+  const matchUrl = match?.[0];
+
+  // Check if there is a default before looking for more exact matches
+  // If there is and the current path fits 1 or less
+  // of the available routes then render it as default
+  if (isDefault) {
+    const isValidDefaultRoute =
+      availableRoutes.filter((route) => currentPath.startsWith(route)).length <=
```
Comment (samwhale) [inline packages/dashboard/src/app/router/route.js:93]: 💭 if there's no match, should this show a 404 page? I guess it's weird because it's a nested app in the wordpress app.

Maybe going to an unregistered route should reset the url to the current route?

like going to `http://localhost:8899/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/not-a-place` should route to `http://localhost:8899/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/`?

**Review by samwhale — APPROVED** [review]
Works great for me! Some small questions

**Review by BrookeGraham — APPROVED** [review]

File: packages/dashboard/src/components/interfaceSkeleton/index.js (hunk 4 above)
Comment (maxyinger) [reply packages/dashboard/src/components/interfaceSkeleton/index.js:92]: I'm not sure if I'm 100% following. could you elaborate on the state hook approach?

I think another approach might be making `availableRoutes` a memoized value here and adding an `availableRoutes` prop to `Route`:
```js
const availableRoutes = useMemo(() => {
  // ...
  return [...Object.values(APP_ROUTES), ...additionalPaths];
}, [additionalPaths]);

...
<Route
  availableRoutes={availableRoutes}
    // ... whatever other props
/>
```

**Review by maxyinger — APPROVED** [review]

File: packages/dashboard/src/components/interfaceSkeleton/index.js (hunk 4 above)
Comment (samwhale) [reply packages/dashboard/src/components/interfaceSkeleton/index.js:92]: Oops yeah sorry, I had morning brain when I wrote this.

I now see why we need to be able to set this. `additionalPaths` may change.

Either way is fine with me, sorry!

File: packages/dashboard/src/app/router/route.js (hunk 5 above)
Comment (BrittanyIRL) [reply packages/dashboard/src/app/router/route.js:81]: yup! so `stories-dashboard#wpbody-content` comes back as `match = null` so `!match` is `true` - the thing is, that I want to find out if there's no match _and_ if it's default we want to check and see if the currentPath starts with one of our available routes. It means that there's no chance that this currentPath would be represented by another available path that would render instead.

File: packages/dashboard/src/app/router/route.js (hunk 6 above)
Comment (BrittanyIRL) [reply packages/dashboard/src/app/router/route.js:93]: I suppose that's an option, yes. Both work the same though. As soon as you navigate from some bogus route that's now defaulted to the Dashboard stories view you'll end up in a proper route. We handle routes this same way for detail template views so my current implementation is consistent.
