### PR TITLE
Use CORS Proxy for Link Icons

### LINKED ISSUE #9492: Use CORS Proxy for Link Icons
## Feature Description

For page attachments and links we automatically fetch the site's favicon to display it.

That works fine on the frontend, but in the editor, when video optimization is enabled (and thus cross-origin isolation), it often doesn't work because of lacking CORS headers:

Screenshot 2021-10-21 at 16 49 47
Screenshot 2021-10-21 at 16 49 33
Screenshot 2021-10-21 at 16 49 28

By using our new CORS proxy for that we could easily fix this.

Only needed when video optimization is enabled though. Otherwise it works fine.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Ensure that link / attachment icons are loaded via the cors proxy. 

## Relevant Technical Choices

Added new property of needsProxy to links, to "cache" the result of the head request, similar to how it currently works 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

#### Element links. 

1. Open story editor
2. Insert an image into page.
3. In documents side panel, under link, add a link to website. ( try different links )
4. See icons display. 

#### Page attachment links.
1. Open story editor
2. Click on canvas / page. 
3. In documents side panel, under page attachment, add a link to website. ( try different links )
4.  See icons display. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9492

### CODE REVIEW

File: packages/story-editor/src/components/panels/design/link/link.js [hunk 1]
```diff
@@ -201,6 +204,8 @@ function LinkPanel({ selectedElements, pushUpdateForObject }) {
     link.url,
   ]);
 
+  const linkIcon = getProxiedUrl({ needsProxy: true }, encodeURI(link.icon));
```
Comment (spacedmonkey) [inline packages/story-editor/src/components/panels/design/link/link.js]: @swissspidy In this PR, I am forcing all link icon request from through the proxy. But this may not be needed in some cases. We could add a new property to link object, called `needsProxy`. This maybe overkill. What do you think?

**Comment by spacedmonkey** [comment]
Submitting as draft for now, as https://github.com/google/web-stories-wp/pull/9702 is blocking this change.

File: packages/story-editor/src/components/panels/design/link/link.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/panels/design/link/link.js]: It may be overkill, but we went the same route with hotlinking as well. So let's do the same thing here for consistency and to avoid sending _everything_ through the proxy.

We can move the `checkResourceAccess` function from `useInsert.js` to `useCORSProxy.js` and then use that here.

File: packages/story-editor/src/utils/checkResourceAccess.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+ *
+ * Makes a HEAD request, which in turn triggers a CORS preflight request
+ * in the browser.
+ *
+ * If the request passes, we don't need to do anything.
+ * If it doesn't, it means we need to run the resource through our CORS proxy at all times.
+ *
+ * @type {function(): boolean}
+ */
+async function checkResourceAccess(link) {
```
Comment (swissspidy) [inline packages/story-editor/src/utils/checkResourceAccess.js]: My recommendation was to move this function within `useCORSProxy` hook as it's related to that. Whats' the rationale for making this a standalone util function?

Comment (spacedmonkey) [reply packages/story-editor/src/utils/checkResourceAccess.js]: You didn't make a recommendation. There is no comment on this PR. It makes sense a util, makes it re-usable.

Comment (spacedmonkey) [reply packages/story-editor/src/utils/checkResourceAccess.js]: To be clear, we need this as a function, as need to value from it to cache it, in the resource, link and page attachment.

Comment (swissspidy) [reply packages/story-editor/src/utils/checkResourceAccess.js]: > You didn't make a recommendation. There is no comment on this PR. It makes sense a util, makes it re-usable.

https://github.com/google/web-stories-wp/pull/9713#discussion_r750198995

Comment (swissspidy) [reply packages/story-editor/src/utils/checkResourceAccess.js]: > To be clear, we need this as a function, as need to value from it to cache it, in the resource, link and page attachment.

I don't understand how moving this function to a different file causes problems with any of this.

Comment (spacedmonkey) [reply packages/story-editor/src/utils/checkResourceAccess.js]: I don't see the point of it is living in that file. You just like it there?

Comment (swissspidy) [reply packages/story-editor/src/utils/checkResourceAccess.js]: Checking resource access for proxying and getting the proxy URL are coupled, you wouldn't use one without the other. It makes sense for this functionality to live together.

Comment (spacedmonkey) [reply packages/story-editor/src/utils/checkResourceAccess.js]: Moved.

**Review by swissspidy — APPROVED** [review]
Needs rebase and some QA instructions, otherwise looks good

**Review by swissspidy — APPROVED** [review]
