### PR TITLE
Canvas: Video poster not rendering in Safari

### LINKED ISSUE #10167: Canvas: Video poster not rendering in Safari
## Bug Description

Follow up https://github.com/google/web-stories-wp/issues/8449. Video poster are not being render of video elements on canvas. 

## Steps to Reproduce

1. Create a story. 
2. Insert video into canvas from media library. 
3. Save story. 
4. Reload story. 

## Screenshots

https://user-images.githubusercontent.com/237508/149138574-83b62b6c-b9b9-41d7-afaf-5214f49448f0.mov

## Additional Context

- Plugin Version: trunk
- WordPress Version: 5.9-RC2
- Operating System: Mac OS 12.1
- Browser: Safari 15.2

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary
While working on #11849, I found a quick fix for this issue. Setting background image for poster seems to work well here.  

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

This issues an issue in safari. Test in all browser but with a special focus safari. 
1. Create story. 
2. Insert video onto canvas. 
3. Add a custom video poster ( both upload file and link to file ). 
4. See poster render. 
5. Create another page, change to new page. 
6. Go back to original page. See poster. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10167

### CODE REVIEW

File: packages/element-library/src/video/trim.js [hunk 1]
```diff
@@ -30,14 +30,10 @@ import { StoryPropTypes, getTransformFlip } from '@googleforcreators/elements';
...
-import { getBackgroundStyle, videoWithScale } from './util';
+import { getBackgroundStyle, Video as _Video } from './util';
 import Captions from './captions';
 
-const Video = styled.video`
-  position: absolute;
-  max-width: initial;
-  max-height: initial;
-  ${videoWithScale}
+const Video = styled(_Video)`
```
Comment (swissspidy) [inline packages/element-library/src/video/trim.js]: We don't typically use underscore suffixes or prefixes.

We usually do `const StyledVideo = styled(Video)`

Note: when using `StyledVideo`, also need to update the `jsx-a11y/media-has-caption` config here to add it to the list:
https://github.com/GoogleForCreators/web-stories-wp/blob/5b29ef015ddc679812c0c7dcb00422a07738b520/.eslintrc#L91-L95

File: packages/element-library/src/gif/display.js [hunk 2]
```diff
@@ -27,24 +26,7 @@ import { StoryPropTypes } from '@googleforcreators/elements';
...
-const Image = styled.img`
-  position: absolute;
-  max-height: initial;
-  object-fit: contain;
-  width: ${({ width }) => `${width}px`};
-  left: ${({ offsetX }) => `${-offsetX}px`};
-  top: ${({ offsetY }) => `${-offsetY}px`};
-  max-width: ${({ isBackground }) => (isBackground ? 'initial' : null)};
-`;
+import { getBackgroundStyle, Video, VideoImage } from '../video/util';
```
Comment (swissspidy) [inline packages/element-library/src/gif/display.js]: Since these are shared between the gif and the video element, this is a good opportunity to move them to `media/util.js` instead.

File: packages/element-library/src/video/util.js [hunk 3]
```diff
@@ -34,3 +33,19 @@ export const getBackgroundStyle = () => {
     maxWidth: 'initial',
   };
 };
+
+export const Video = styled.video`
+  position: absolute;
+  max-width: initial;
+  max-height: initial;
+  height: ${({ height }) => `${height}px`};
+  background-image: ${({ poster }) => `${poster}`};
```
Comment (swissspidy) [inline packages/element-library/src/video/util.js]: IIUC this is the main change you've added?

Shouldn't this be like this though?

```suggestion
  background-image: ${({ poster }) => `url("${poster}")`};
```

File: packages/element-library/src/gif/display.js [hunk 4]
```diff
@@ -27,24 +26,7 @@ import { StoryPropTypes } from '@googleforcreators/elements';
...
-const Image = styled.img`
-  position: absolute;
-  max-height: initial;
-  object-fit: contain;
-  width: ${({ width }) => `${width}px`};
-  left: ${({ offsetX }) => `${-offsetX}px`};
-  top: ${({ offsetY }) => `${-offsetY}px`};
-  max-width: ${({ isBackground }) => (isBackground ? 'initial' : null)};
-`;
+import { getBackgroundStyle, Video, VideoImage } from '../media/util';
```
Comment (miina) [inline packages/element-library/src/gif/display.js:29]: Nit: Hm, should `Video` and `VideoImage` be in a constants file instead? Doesn't sound like these are utilities.
Although I can see that it was done so already before as well so feel free to ignore.

**Review by miina — APPROVED** [review]
Works great.

In other browsers now the poster is shown + the background image is displayed as well, I suppose that's ok.

File: packages/element-library/src/gif/display.js (hunk 4 above)
Comment (spacedmonkey) [reply packages/element-library/src/gif/display.js:29]: I don't feel strongly either way.

**Review by timarney — APPROVED** [review]

**Comment by spacedmonkey** [comment]
@swissspidy I have tested this with hotlinked poster and it works. Can you review on your end?

**Comment by swissspidy** [comment]
Not seeing any issues either. Though also having troubles to reproduce the original issue in the first place anyway.

Let's send this to QA

**Comment by felipebochehin87** [comment]
Safari (video below). Also checked on Firefox and Safari. I couldn't reproduce the issue locally, nor in [QA](https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/), but I checked the functionality and the fix didn't cause any negative impact.

[Uploading... Screen Recording 2022-07-12 at 06.24.00.mov]
