### PR TITLE
Reorganize video settings in design panel

### LINKED ISSUE #5340: Reorganize video settings in design panel
## Bug Description

IMO, the current structure of video settings in design panel doesn't make sense.

- Video settings
  - Loop / play once
- Captions
  - Upload captions
- Accessibility
  - Poster image selector
  - Title (text field)
  - Alt (text field)
  - "Text for visually impaired users." (label)

Issues:
- Captions is an A11Y feature
- Poster image and title are not A11Y features
- The sections should probably be merged

## Proposed Behavior

- Video
  - Playback
    - Loop / play once
  - Performance
    - "Poster:" (label)
    - Poster image selector
    - "Burned-in text:" (`title` and `alt` label)
    - "Enter burned-in text in the video (if any)"
  - Accessibility
    - "Captions:" (label)
    - Upload captions button

Not sure if there's precedence for double-nesting in these sections -- could also divide into "Video playback", "Video performance", "Video accessibility".

References:
- https://blog.amp.dev/2020/02/12/seo-for-amp-stories/

## Steps to Reproduce

N/A

## Screenshots

Screen Shot 2020-11-18 at 12 16 38 PM

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Re-organize the video settings in design panel by follow the structure:
**Playback**
    Loop / play once
**Poster**
    [Poster selector]
    "For improved loading experience on slower connections."
**Description**
    [Text field]
    "For indexability and accessibility. Include any burned-in text inside the video."
**Captions**
    [Captions selector]

## Relevant Technical Choices
1. Update the Video Options panel title to "Playback"
2. Add a Poster element
3. Update the VideoAccessibility panel title to "Description"
4. Clean up the captions panel

## To-do

N/A

## User-facing changes

Update designing panel

Screen Shot 2020-12-10 at 11 04 34 PM

## Testing Instructions

- Playback button should be switchable
- Should be able to upload poster
- Should be able to update description text
- Should be able to update captions

---

Fixes #5340

### CODE REVIEW

**Comment by zidianlyu** [comment]
Here is the screenshot for the new UI design:

Screen Shot 2020-12-10 at 11 04 34 PM

File: assets/src/edit-story/karma/fixture/containers/designPanel/poster.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ import { AbstractPanel } from './abstractPanel';
 /**
  * The video accessibility panel containing inputs for adding poster and title.
```
Comment (dreamofabear) [inline assets/src/edit-story/karma/fixture/containers/designPanel/poster.js]: Comment is out of date.

File: assets/src/edit-story/karma/fixture/containers/designPanel/index.js [hunk 2]
```diff
@@ -27,15 +27,14 @@ import { TextStyle } from './textStyle';
...
-import { VideoAccessibility } from './videoAccessibility';
 import { Layers } from './layers';
 import { TextStylePreset } from './textStylePreset';
 import { ColorPreset } from './colorPreset';
 import { SizePosition } from './sizePosition';
 import { BorderRadius } from './borderRadius';
 import { Border } from './border';
 import { Animation } from './animationPanel';
-
+import { Poster } from './poster';
```
Comment (dreamofabear) [inline assets/src/edit-story/karma/fixture/containers/designPanel/index.js]: Nit: Can we sort these?

File: assets/src/edit-story/components/panels/videoAccessibility.js [hunk 3]
```diff
@@ -28,12 +27,16 @@ import { __ } from '@wordpress/i18n';
...
  */
-import { Media, Row, usePresubmitHandler } from '../form';
-import { Note, ExpandedTextInput } from './shared';
+import { Row, usePresubmitHandler } from '../form';
 import { SimplePanel } from './panel';
 import { getCommonValue, useCommonObjectValue } from './utils';
+import { ExpandedTextInput, Note } from './shared';
+
+const DEFAULT_RESOURCE = {
+  poster: null,
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/videoAccessibility.js]: Still necessary now that poster is removed from this panel?

File: assets/src/edit-story/components/panels/poster/poster.js [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+ * Internal dependencies
+ */
+import { Row, Media } from '../../form';
+import { SimplePanel } from '../panel';
+import { getCommonValue, useCommonObjectValue } from '../utils';
+import { Note } from '../shared';
+
+const DEFAULT_RESOURCE = {
+  poster: null,
+  alt: null,
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/poster/poster.js]: Why "alt" here?

File: assets/src/edit-story/components/panels/index.js [hunk 5]
```diff
@@ -120,10 +136,8 @@ export function getPanels(elements, options = {}) {
     // If the selected element's type is video / image , display accessibility panel, too.
     if ('video' === elements[0].type) {
       panels.push({ type: VIDEO_OPTIONS, Panel: VideoOptionsPanel });
-      panels.push({
-        type: CAPTIONS,
-        Panel: CaptionsPanel,
-      });
+      panels.push({ type: POSTER, Panel: PosterPanel });
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/index.js]: Let's call this `VideoPosterPanel` to disambiguate with "story poster".

File: assets/src/edit-story/components/panels/index.js [hunk 6]
```diff
@@ -87,8 +90,21 @@ export const PanelTypes = {
 
 const ALL = Object.values(PanelTypes);
 
+function reorderPanels(panels) {
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/index.js]: What's the purpose of this function?

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: This function is for re-ordering the panels section, otherwise, basic on the current logic, the order will be:
...
- Poster
- Playback
- Captions
- Description
(mainly due to the `intersect` function.)

So I add this function to re-order the sections. Or should we just keep the previous order? Please let me know 🙂

File: assets/src/edit-story/karma/fixture/containers/designPanel/poster.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/karma/fixture/containers/designPanel/poster.js]: Updated.

File: assets/src/edit-story/components/panels/videoAccessibility.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/videoAccessibility.js]: Updated.

File: assets/src/edit-story/karma/fixture/containers/designPanel/index.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/edit-story/karma/fixture/containers/designPanel/index.js]: Done.

File: assets/src/edit-story/components/panels/poster/poster.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/poster/poster.js]: Cleaned up, this is unneeded

File: assets/src/edit-story/components/panels/index.js (hunk 5 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: Got it, updated.

File: assets/src/edit-story/components/panels/index.js (hunk 6 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: Updated a comment to explain WHY.

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: Actually figured this out, there is no need to add this helper function. The order logic can be controlled by the items order object `PanelTypes`. Just updated.

File: assets/src/edit-story/components/panels/index.js [hunk 7]
```diff
@@ -57,6 +58,7 @@ const SIZE_POSITION = 'sizePosition';
 const SHAPE_STYLE = 'shapeStyle';
 const TEXT = 'text';
 const TEXT_STYLE = 'textStyle';
+const VIDEO_POSTER = 'poster';
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/index.js]: Nit:

There's `VIDEO_OPTIONS = 'videoOptions'`, `VIDEO_ACCESSIBILITY = 'videoAccessibility'`, ... why not `VIDEO_POSTER = 'videoPoster'`?

File: assets/src/edit-story/components/panels/poster/videoPoster.js [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+          alt={__('Preview poster image', 'web-stories')}
+          type={'image'}
+          ariaLabel={__('Video poster', 'web-stories')}
+          canReset
+        />
+      </Row>
+      <Row>
+        <Note>
+          {__(
+            'For improved loadaing experience on slower connections.',
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/poster/videoPoster.js]:
```suggestion
            'For improved loading experience on slower connections.',
```

File: package-lock.json [hunk 9]
```diff
@@ -17985,15 +17985,6 @@
         "escape-string-regexp": "^1.0.5"
       }
     },
-    "file-entry-cache": {
```
Comment (swissspidy) [inline package-lock.json]: Let's undo all changes to this file

File: assets/src/edit-story/components/panels/index.js [hunk 10]
```diff
@@ -19,25 +19,26 @@
...
 import SizePositionPanel from './sizePosition';
+import StylePresetPanel from './preset/stylePreset';
 import TextStylePanel from './textStyle';
 import VideoAccessibilityPanel from './videoAccessibility';
-import NoSelectionPanel from './noSelection';
-import ElementAlignmentPanel from './alignment';
 import VideoOptionsPanel from './videoOptions';
-import StylePresetPanel from './preset/stylePreset';
-import ColorPresetPanel from './preset/colorPreset';
+import VideoPosterPanel from './poster';
```
Comment (barklund) [inline assets/src/edit-story/components/panels/index.js]: Are you using some kind of plugin to organize imports alphabetically? If we want to do this, we should either all do it or not at all - otherwise, it'll just cause needless diffs. Ping @swissspidy

File: assets/src/edit-story/components/panels/test/videoOptions.js [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+    type: 'video',
+    resource: { posterId: 0, poster: '', alt: '' },
+  };
+  function renderVideoOptions(...args) {
+    return renderPanel(VideoOptions, ...args);
+  }
+
+  beforeAll(() => {
+    localStorage.setItem(
+      'web_stories_ui_panel_settings:videePoster',
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/videoOptions.js]: `videe`?

File: assets/src/edit-story/components/panels/captions/captions.js [hunk 12]
```diff
@@ -82,18 +85,32 @@ function CaptionsPanel({ selectedElements, pushUpdate }) {
...
+    },
+    [tracks, pushUpdate]
+  );
 
   const UploadCaption = useMediaPicker({
     onSelect: handleChangeTrack,
     type: 'text/vtt',
     title: captionText,
-    buttonInsertText: __('Select caption', 'web-stories'),
+    buttonInsertText: __('Description', 'web-stories'),
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/panels/captions/captions.js]: Why was this changed? It is wrong. 

image

The button needs to be a call to action. Like `Select caption` or `Set captions`.

**Comment by spacedmonkey** [comment]
Not sure if it is related to this change, but the reset button on poster image doesn't work. Is this a new issue / bug?

File: assets/src/edit-story/components/panels/poster/videoPoster.js (hunk 8 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/poster/videoPoster.js]: Fixed typo.

File: assets/src/edit-story/components/panels/captions/captions.js (hunk 12 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/captions/captions.js]: Rollback change

File: package-lock.json (hunk 9 above)
Comment (zidianlyu) [reply package-lock.json]: Added back the missing part.

File: assets/src/edit-story/components/panels/index.js (hunk 7 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: Updated to 'videoPoster'.

**Comment by zidianlyu** [comment]
> Not sure if it is related to this change, but the reset button on poster image doesn't work. Is this a new issue / bug?

Tested on local, it works now:

Steps: 
- Click on a video -> click '...' button -> click 'Edit' -> choose an image
- Click on a video -> click '...' button -> click 'Reset'

The poster image reset to default.

**Review by swissspidy — APPROVED** [review]

**Review by barklund — APPROVED** [review]
Looks good to me with two minor comments.

File: assets/src/edit-story/components/panels/index.js (hunk 10 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/index.js]: No; Instead, I did this manually in response to Will's request to sort the import alphabetical order.

File: assets/src/edit-story/components/panels/test/videoOptions.js (hunk 11 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/test/videoOptions.js]: Fixed typo.

File: assets/src/edit-story/components/panels/index.js (hunk 10 above)
Comment (dreamofabear) [reply assets/src/edit-story/components/panels/index.js]: > I did this manually

You can also do this in VSCode in 2 seconds with `Command+Shift+P > Sort Lines Ascending`.

File: assets/src/edit-story/components/panels/test/captions.js [hunk 13]
```diff
@@ -46,7 +46,7 @@ describe('Panels/Captions', () => {
 
   beforeAll(() => {
     localStorage.setItem(
-      'web_stories_ui_panel_settings:caption',
+      'web_stories_ui_panel_settings:captions',
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/test/captions.js]: Why change this local storage key? Would this reset the stored collapse state of this panel for all users?

File: assets/src/edit-story/components/panels/test/videoOptions.js [hunk 14]
```diff
@@ -0,0 +1,55 @@
...
+    type: 'video',
+    resource: { posterId: 0, poster: '', alt: '' },
+  };
+  function renderVideoOptions(...args) {
+    return renderPanel(VideoOptions, ...args);
+  }
+
+  beforeAll(() => {
+    localStorage.setItem(
+      'web_stories_ui_panel_settings:videoPoster',
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/test/videoOptions.js]: Why are we setting "video poster" settings in "video options" panel?

**Review by dreamofabear — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/panels/test/videoOptions.js (hunk 14 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/test/videoOptions.js]: Sorry, this is a typo. Updated.

File: assets/src/edit-story/components/panels/test/captions.js (hunk 13 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/test/captions.js]: Got you. You are right, in this case, we should not change the stored state. Changed it back.

File: assets/src/edit-story/components/panels/index.js (hunk 10 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/index.js]: Did you at least manually bubble-sort it? 😲

**Review by dreamofabear — APPROVED** [review]

**Comment by swissspidy** [comment]
@zidianlyu there are some merge conflicts now FYI

**Comment by barklund** [comment]
> @zidianlyu there are some merge conflicts now FYI

Yeah, quite a few. Please try to follow the new structure in the panels post-merge of #5696 and place each panel in a separate folder with its own tests inside - and put the type in the relevant file as well. Oh, and the "get panels for selection" logic also moved, but is otherwise similar to the contents before.

**Comment by spacedmonkey** [comment]
This PR needs a refresh. Any chance you could do this @zidianlyu ?

**Comment by zidianlyu** [comment]
Keep receiving error like: 

Screen Shot 2020-12-19 at 3 08 32 PM
 
Any hints to resolve this?

**Comment by swissspidy** [comment]
> Keep receiving error like:
> 
> Screen Shot 2020-12-19 at 3 08 32 PM
> 
> Any hints to resolve this?

Undoing the changes to the package-lock.json file should resolve this.
