### PR TITLE
Color Picker: Hide rotation button for radial

### LINKED ISSUE #8916: Rotate Gradient action on a Radial Gradient shouldn't be presented
## Bug Description
Originally reported by @littlemilkstudio 
A rotate gradient action makes little sense for a radial gradient, as there are no visual changes from it.

image9

## Expected Behaviour

The rotate function might be removed for this specific use case

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by miina**
## Summary
Remove the rotation button for radial colors.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a shape.
2. Open the color picker for the shape background and add radial color type from the Custom view.
3. Verify that when Radial type is chosen, the icon for rotation is not available (see the screenshot below for locating the rotation icon)
4. Verify it's still available for linear gradient.

Rotation icon is this:
Screenshot 2021-09-10 at 15 32 19

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8916

### CODE REVIEW

File: packages/story-editor/src/components/colorPicker/customColorPicker.js [hunk 1]
```diff
@@ -116,6 +116,7 @@ function CustomColorPicker({
             onDelete={removeCurrentStop}
             onRotate={rotateClockwise}
             onMove={moveCurrentStopBy}
+            type={type}
```
Comment (barklund) [inline packages/story-editor/src/components/colorPicker/customColorPicker.js:119]: I'd probably have made this a boolean flag, like `canRotate={type !== 'linear'}`, but this works too. It's a matter of opinion for sure.

**Review by barklund — APPROVED** [review]
🛸
