### PR TITLE
Aspect Ratio changed after dragging video to upload as background

### LINKED ISSUE #360: When uploading video poster, also need to update video dimensions
When we upload the poster, it's also a great opportunity to update the video's size - we need to know it for use in the editor. An alternative approach would be, when poster is available, to use it's original size as the video's original size.

One important nuance: the size might be available later, once the video is already placed on the page. I think we have no choice but to jump-update it once the original size is available. We'd likely need to show some sort of "loading" indicator when original size is not available at the time of insertion.

Finally, a video with its width/height not available should be displayed as a square in the media panel. Defaulting to 150x80 will be wrong half the time when we don't know the video's orientation. So square is a safe default. Once original width/height are available, we should, of course, use those.

### LINKED ISSUE #615: Automatically update elements after poster generation.
## Feature Description
After video posters are generated, any existing elements using these videos should also be updated.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #703: Aspect Ratio Changed after Dragging Video to Upload as Background
## Bug Description

Dragged a video from Win Explorer onto page as background. Video appears like this, rather than taking up the entire background:
image

## Steps to Reproduce

1. Drag a video from local onto the page to upload it and set it as the background
2. On initial "load" on the page it appears as expected
3. Wait a few seconds and it changes from filling the background to a smaller size

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ndev1991**
Fixes #703
Fixes #360 
Fixes #615

Summary
Add resource for uploadVideoPoster will be used in uploadVideoFrame. To keep the radio we need resource width and height.
Screen Shot 2020-03-26 at 10 05 27 PM

### CODE REVIEW

**Comment by dvoytenko** [comment]
This is essentially the same problem as with the #360 and #615. We've delayed this resolution once and I don't think we should delay it again. We need to remove both `elementId` and `resource` arguments from that function and simply scan/update all known matching resources and elements that depend on them based on the `videoId`. The correct fix here is only a little more complicated than many partial fixes.

**Comment by ndev1991** [comment]
Now removed `elementId`, `resource` from `mediaProvider` and added `videoId` to resource instead. Also added `updateElementsByVideoId` to update existing element properties.

One concern here I added searching original media feature on `display.js`. Not sure if we better to have them as resource on element from here `processData`

**Comment by ndev1991** [comment]
> This is essentially the same problem as with the #360 and #615. We've delayed this resolution once and I don't think we should delay it again. We need to remove both `elementId` and `resource` arguments from that function and simply scan/update all known matching resources and elements that depend on them based on the `videoId`. The correct fix here is only a little more complicated than many partial fixes.

Now removed elementId, resource from mediaProvider and added videoId to resource instead. Also added updateElementsByVideoId to update existing element properties.

One concern here I added searching original media feature on display.js. Not sure if we better to have them as resource on element from here processData

**Review by spacedmonkey — APPROVED** [review]
LGTM

**Comment by swissspidy** [comment]
@ndev1991 FYI there's a merge conflict here

File: assets/src/edit-story/app/story/useStoryReducer/actions.js [hunk 1]
```diff
@@ -74,6 +74,12 @@ const updateElementById = (dispatch) => ({ elementId, properties }) =>
     payload: { elementIds: [elementId], properties },
   });
 
+const updateElementsByVideoId = (dispatch) => ({ videoId, properties }) =>
```
Comment (swissspidy) [inline assets/src/edit-story/app/story/useStoryReducer/actions.js:77]: The story reducers are thoroughly tested. `updateElementsByVideoId` needs test coverage too.

Comment (ndev1991) [reply assets/src/edit-story/app/story/useStoryReducer/actions.js:77]: Test cases are added!

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js [hunk 2]
```diff
@@ -54,11 +54,10 @@ function useUploadVideoFrame({ updateMediaElement }) {
         featured_media: posterId,
         post: storyId,
       });
-      if (elementId) {
-        // TODO Update all elements that use video.
-        const newState = { resource: { ...resource, posterId, poster } };
-        setProperties(elementId, newState);
-      }
+      const newState = {
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/utils/useUploadVideoFrame.js:57]: Would it not overwrite the useful pre-existing `resource` fields?

File: assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js [hunk 3]
```diff
@@ -44,17 +44,27 @@ import { intersect, objectWithout } from './utils';
  */
 function updateElements(
   state,
-  { elementIds, properties: propertiesOrUpdater }
+  { videoId, elementIds, properties: propertiesOrUpdater }
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/updateElements.js:47]: Ideally it'd have been a separate method. This kind of API expansion is harmful and does not save time. We can always have an `updateElements(elementIds, ...)` and the new `updateElementsByVideoId` that finds all related `elementIds` and calls the `updateElements`

File: assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByVideoId.js [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+  it('should update the elements with videoId', () => {
+    const { restore, updateElementsByVideoId } = setupReducer();
+
+    // Set an initial state with a current page and some elements selected.
+    const initialState = restore({
+      pages: [
+        {
+          id: '111',
+          elements: [
+            { id: '123', resource: { videoId: '10' } },
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/useStoryReducer/test/updateElementsByVideoId.js:32]: This is a good example of how a test could be more useful. For instance, an "existing" `resource.type` field, is likely will be overwritten here. Please try this ASAP. This could be a major bug.

File: assets/src/edit-story/elements/media/getMediaSizePositionProps.js [hunk 5]
```diff
@@ -26,7 +26,7 @@
  * @return {Object} Media properties.
  */
 function getMediaSizePositionProps(
-  resource,
+  resource = {},
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/media/getMediaSizePositionProps.js:29]: This default doesn't make sense and rather harmful. Please remove. Also, codestyle-wise the non-tail default args are always discouraged.

File: assets/src/edit-story/elements/media/getMediaSizePositionProps.js [hunk 6]
```diff
@@ -35,7 +35,9 @@ function getMediaSizePositionProps(
 ) {
   const ratio = width / height;
   const oRatio =
-    resource.width && resource.height ? resource.width / resource.height : 1;
+    resource.oWidth && resource.oHeight
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/media/getMediaSizePositionProps.js:38]: Resource does not have `oWidth` field.

File: assets/src/edit-story/elements/video/display.js [hunk 7]
```diff
@@ -64,8 +65,16 @@ function VideoDisplay({ previewMode, box: { width, height }, element }) {
     };
   }
 
+  const {
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/video/display.js:68]: This shouldn't be here.

File: assets/src/edit-story/app/media/utils/useUploadVideoFrame.js [hunk 8]
```diff
@@ -54,11 +54,10 @@ function useUploadVideoFrame({ updateMediaElement }) {
...
+        resource: { posterId, poster, videoId },
+      };
+      setProperties(videoId, newState);
```
Comment (dvoytenko) [inline assets/src/edit-story/app/media/utils/useUploadVideoFrame.js:60]: Can you pls confirm that the `updateMediaElement` below does the same to resources as the `setProperties` in this line: e.g. finds the video's resource(s) and updates them? I'm asking because I'm confused: this is an old code and I don't understand why you even tried to introduce `resource` argument here initially?

**Review by dvoytenko — COMMENTED** [review]
@ndev1991, @swissspidy, @spacedmonkey PTAL ASAP. I'm considering rolling back this pull request. It's in the right direction. But unless I'm wrong, it introduces a series of bad bugs in the code.

**Comment by swissspidy** [comment]
@ndev1991 Can you create a new PR to address the issues flagged by @dvoytenko above?

**Comment by ndev1991** [comment]
> @ndev1991 Can you create a new PR to address the issues flagged by @dvoytenko above?

@swissspidy I will create a following up PR for those issue! Thanks

**Comment by dvoytenko** [comment]
@ndev1991 To clarify: you can't do followup. You will need to roll-forward this pull request with fixes.
