### PR TITLE
Storybook: Media Gallery add needed providers

### LINKED ISSUE #10379: Storybook: Broken Stories Editor Media Elements + Gallery View
StoriesEditor/Components/MediaElement + Media Gallery views of storybook are broken. Should fix after knobs updated to controls.
https://user-images.githubusercontent.com/10720454/150880295-09d79d98-74b1-4319-9750-79bacb21ff8a.png

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

`Media Gallery` story in Storybook was broken. 

## Summary
The Media Provider and the Canvas Provider were missing around MediaGallery story. This adds them. 

## To-do
n/a

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Fire up Storybook, checkout `Stories Editor/Components/Media Gallery`

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Partially Fixes #10379 (Media Gallery) 
MediaElement fixed in #10499

### CODE REVIEW

File: packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js [hunk 1]
```diff
@@ -18,11 +18,14 @@
  * External dependencies
  */
 import styled from 'styled-components';
+import { noop } from '@googleforcreators/design-system';
 
 /**
  * Internal dependencies
  */
 import MediaGallery from '../mediaGallery';
+import { CanvasProvider } from '../../../../../../app/canvas';
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js:27]: This was the sneaky snake I was missing.

File: packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js [hunk 2]
```diff
@@ -290,9 +293,29 @@ const Container = styled.div`
...
+    },
+  };
+
   return (
     <Container>
-      <MediaGallery resources={resources} providerType={'unsplash'} {...args} />
+      <MediaContext.Provider value={mediaValue}>
+        <CanvasProvider>
+          <MediaGallery
+            resources={resources}
```
Comment (samwhale) [inline packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js]: Do the resources all have the same keys? Let's fix that :) 

image

**Review by samwhale — APPROVED** [review]
👍

File: packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js (hunk 2 above)
Comment (samwhale) [reply packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js]: Also - seems like the [units provider](https://github.com/GoogleForCreators/web-stories-wp/blob/296cf2e6abc39b8afb5d0420a3a0f734be2b336d/packages/units/src/unitsProvider.js#L35-L55) is missing here too 🤔

Comment (BrookeGraham) [reply packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js]: >Do the resources all have the same keys? Let's fix that :)

Yes they are. I had updated them along with some attempts to fix, but when those fixes didn't work I reverted and completely forgot about that. Nice catch!

Comment (BrookeGraham) [reply packages/story-editor/src/components/library/panes/media/common/stories/mediaGallery.js]: Needed the `LayoutProvider` as well. 🙌🏽

**Review by BrittanyIRL — APPROVED** [review]
