### PR TITLE
Fix blob URLs after elements manipulation while uploading

### LINKED ISSUE #2706: Images are sometimes broken (blob URLs)
## Bug Description

This story was created yesterday (so after blob URL fix where we disable preview and autosave while uploading) and contains blob URLs:
https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=9775&action=edit

Update:
While the image/video is uploading you still can: 
- Drop it on other elements (includes Set as BG button) .
- Duplicate  it (or page?).

All of these will cause onUploadedFile/onUploadFailure to not find and update the uploaded resource URL by id (which is originally created element id).

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
## Summary

This will fix the happy path (element was manipulated but the resource uploaded successfully) for the given [issue](https://github.com/google/web-stories-wp/issues/2706).
Failure case is still evaluated.

## Testing Instructions

1. Upload file (big enough so you have the time to duplicate it and set as BG).
2. Duplicate it and set it as BG.
3. After the upload is done, Save the story.
4. Reload the editor.
5. Both images should be fine.

---

### CODE REVIEW

File: assets/src/edit-story/components/canvas/useUploadWithPreview.js [hunk 1]
```diff
@@ -53,28 +64,37 @@ function useUploadWithPreview() {
...
-        ...element.resource,
-        ...keysToUpdate,
-      };
-      updateElementById({
-        elementId: element.id,
-        properties: {
-          resource: updatedResource,
+      updateElementsByResourceId({
+        // We want to update all resources without id (still uploading)
+        id: undefined,
```
Comment (merapi) [inline assets/src/edit-story/components/canvas/useUploadWithPreview.js:69]: This is quite creative but does the job. WDYT?

File: assets/src/edit-story/components/canvas/useUploadWithPreview.js [hunk 2]
```diff
@@ -53,28 +64,37 @@ function useUploadWithPreview() {
...
     },
-    [updateElementById, uploadVideoPoster]
+    [updateElementsByResourceId, uploadVideoPoster]
   );
 
   const onUploadFailure = useCallback(
     ({ element }) => {
       deleteElementById({ elementId: element.id });
+      showSnackbar({
+        message: __('Upload failed, preview was removed', 'web-stories'),
```
Comment (miina) [inline assets/src/edit-story/components/canvas/useUploadWithPreview.js]: Perhaps "the element was removed" would be better here? Not sure the user is aware at all that it's just the preview shown initially, for the user it likely seems the "real thing". Or is this from Figma?

Comment (merapi) [reply assets/src/edit-story/components/canvas/useUploadWithPreview.js]: I think there is only this in Figma: 
image

Will use the "element" for now. It will probably change after we agree on the failure case.

**Comment by merapi** [comment]
I think we should merge this ASAP and do a follow-up PR with failure case improvements since in most cases upload will succeed.

**Review by miina — APPROVED** [review]
Seems to work as expected!
