### PR TITLE
Animations: Add Tooltip to Disabled Options

### LINKED ISSUE #5514: Disabled Animations should have a tool tip to provide context on unavailability
## Bug Description

Add tooltip to any animation options that is disabled to make it clear to users why it’s disabled.

If an image/video is too small to support an animation direction (ie pan up or down), disable it and provide a tooltip, do not remove it. Users may not understand that the options are still available. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
- Adds tooltips to disabled background animations and directional options
- Updates styling of the directional selector to latest designs https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1923%3A424212

## Relevant Technical Choices
NA

## To-do
Accommodate for bg zoom when we update to designs.

## User-facing changes
Hover over a disabled animation and see a tooltip with a helpful message appear.

## Testing Instructions
Create or go to exisiting story in editor -> add some bg media -> go to add an animation to the media -> see that any disabled options have a tooltip -> click on a pan direction that's not disabled -> go to the directional selector and see that any disabled directions also have a tooltip

---

Fixes #5514

### CODE REVIEW

File: assets/src/edit-story/components/panels/animation/effectChooser.js [hunk 1]
```diff
@@ -346,76 +349,132 @@ export default function EffectChooser({
...
+            <WithTooltip
+              title={
+                disabledBackgroundEffects.includes(
+                  PAN_MAPPING[DIRECTION.LEFT_TO_RIGHT]
+                )
+                  ? disabledTypeOptionsMap[
+                      BACKGROUND_ANIMATION_EFFECTS.PAN.value
+                    ]?.tooltip
+                  : ''
               }
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/animation/effectChooser.js]: This appears to have the unfortunate side effect of killing the keyboard functionality because the tooltip's wrapping the button and the tooltip div isn't focusable. 
Screen Shot 2020-12-08 at 1 30 26 PM

Comment (maxyinger) [reply assets/src/edit-story/components/panels/animation/effectChooser.js]: Ahh great catch! will just move the tooltip wrapper inside the button as a quick fix for now

File: assets/src/edit-story/components/panels/animation/panel.js [hunk 2]
```diff
@@ -50,6 +50,11 @@ import EffectChooserDropdown from './effectChooserDropdown';
 
 const ANIMATION_PROPERTY = 'animation';
 
+const backgroundAnimationTooltip = __(
+  'The bg image is too small to animate. Double click on the bg & scale the image before applying the animation.',
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/animation/panel.js]: I doubt users and translators necessarily know what "bg" means here or how it could be translated. Let's write "background"

**Review by carloskelly13 — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
This works great! keyboard functions as it should, tooltips show on hover for disabled effects. 🚢
