### PR TITLE
Fixes element measuring relative to fullbleed (better)

### LINKED ISSUE #1545: Lasso selection coordinates inaccurate
## Bug Description

Lasso selection coordinates seem to be inaccurate and not following the cursor.

## Expected Behaviour
Lasso selection should be displayed based on the cursor coordinates and movement.

## Steps to Reproduce
1. Try lasso selecting
2. See the outline being created inaccurately

## Screenshots
lasso

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
Closes  #1545

### CODE REVIEW

File: assets/src/edit-story/components/canvas/canvasElementDropzone.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ function CanvasElementDropzone({ children }) {
           resource,
           offset: { x: offsetX, y: offsetY, w: offsetWidth, h: offsetHeight },
         } = JSON.parse(e.dataTransfer.getData('resource/media'));
-        const { x, y } = pageContainer?.getBoundingClientRect();
+        const { x, y } = fullbleedContainer?.getBoundingClientRect();
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/canvasElementDropzone.js]: I'd expect most of operations to be done against `safezoneContainer`. Why fullbleed here?

File: assets/src/edit-story/components/canvas/layout.js [hunk 2]
```diff
@@ -115,14 +115,14 @@ const PageAreaFullbleedContainer = styled(Area).attrs({
...
   align-items: center;
-  background-color: ${({ theme }) => theme.colors.fg.v1};
 `;
 
 const PageAreaSafeZone = styled.div`
   width: 100%;
   height: var(--page-height-px);
   overflow: visible;
-  position: relative;
+  position: absolute;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/layout.js]: If you still prefer `position: relative`, the `margin: auto 0` might work for you here. And it'd definitely work for `position:absolute` instead of `top`. Not sure if that's more useful in your case however. PTAL.

File: assets/src/edit-story/components/canvas/selectionCanvas.js [hunk 3]
```diff
@@ -150,8 +150,8 @@ function SelectionCanvas({ children }) {
   const onMouseUp = () => {
     if (lassoModeRef.current === LassoMode.ON) {
       const [lx, ly, lwidth, lheight] = getLassoBox();
-      const x = editorToDataX(lx - pageContainer.offsetLeft);
-      const y = editorToDataY(ly - pageContainer.offsetTop);
+      const x = editorToDataX(lx - fullbleedContainer.offsetLeft);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/selectionCanvas.js:153]: Hmm. I still don't get it. I'd expect all the coordinate system to work with pageContainer, not fullbleedContainer. LEt's discuss.

File: assets/src/edit-story/units/dimensions.js [hunk 4]
```diff
@@ -72,10 +75,12 @@ export function dataToEditorX(x, pageWidth) {
  *
  * @param {number} y The value to be converted.
  * @param {number} pageHeight The basis value for the page's height in the "editor" space.
+ * @param {boolean} useFullbleed Whether the value is relative to the fullbleed or the safezone of the page.
  * @return {number} The value in the "editor" space.
  */
-export function dataToEditorY(y, pageHeight) {
-  return editorPixels((y * pageHeight) / PAGE_HEIGHT);
+export function dataToEditorY(y, pageHeight, useFullbleed = false) {
```
Comment (dvoytenko) [inline assets/src/edit-story/units/dimensions.js]: I don't like it. We should really see if we can do it with one coordinate system.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/canvas/selectionCanvas.js (hunk 3 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/selectionCanvas.js:153]: Discussed offline

**Comment by wassgha** [comment]
@dvoytenko ready :)

**Review by dvoytenko — APPROVED** [review]
