### PR TITLE
Animation: Rotation UI Component

### LINKED ISSUE #3796: Effect Panel - Rotation UI Component
A rotation component that maps to our `ROTATION` constant (dashboard/animations/constants.js)

**Specs**
- It can be set to clockwise or counter-clockwise.

**UI Screenshots**
Clockwise:

Counter-clockwise:
Figma seems to only have clockwise examples, ask Sam for how counter-clockwise should be toggled on/off.

### LINKED ISSUE #4170: Effect Panel - Direction UI Component Internationalization
## Bug Description

Follow-up to #4143 / #3794

The direction placeholder is not translatable:

https://github.com/google/web-stories-wp/blob/4c21f03ca8fdebcf20f5725b925cca53b7734c69/assets/src/edit-story/components/panels/animation/directionRadioInput.js#L181-L183

See my comment at https://github.com/google/web-stories-wp/pull/4143#discussion_r474829348

There's currently no way for translators to translate `right to left` into their language.

Also, the `/* translators */` comment is incorrect, as possible directions include `right to left`, not `top` or `left`. I was not aware of this when I proposed that comment.

## Expected Behaviour

1. Change string to `__( 'Direction: %s', 'web-stories' )`
1. Add proper translations for all directions somewhere, for example:

```js
const rightToLeft: __( 'right to left', 'web-stories' )`
const leftToRight: __( 'left to right', 'web-stories' )`
// ...
```

(No, something like `__(direction, 'web-stories' )` does not work.)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds rotation option support to our directional radio select

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
none

## Testing Instructions
run storybook -> `Animations / Direction Radio Input / Rotation` -> click & up/down arrow through to options to validate keyboard accessibility.

Also fixed #4170 while I was in here.

---

Fixes #3796

### CODE REVIEW

File: assets/src/edit-story/components/panels/animation/directionRadioInput.js [hunk 1]
```diff
@@ -21,43 +21,49 @@ import styled, { css } from 'styled-components';
...
 
 const Direction = ({ className, direction }) => (
   <Icon className={className} direction={direction}>
-    <Svg viewBox="0 0 10 11">
-      <path d="M5 11L5 1M5 1L9 5M5 1L1 5" />
-    </Svg>
+    {Object.values(DIRECTION).includes(direction) ? (
+      <Svg size="10px" viewBox="0 0 10 11">
+        <path d="M5 11L5 1M5 1L9 5M5 1L1 5" />
+      </Svg>
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/panels/animation/directionRadioInput.js]: For legibility, it might be nice to store these SVGs as variables so that if one needs to be replaced or altered ever it's easier to tell the purpose behind the two direction/rotation icons just by reading through code.

**Review by BrittanyIRL — APPROVED** [review]
Looks good to me! Validated with keyboard and screen reader.

**Review by swissspidy — APPROVED** [review]

**Review by dmmulroy — APPROVED** [review]
