### PR TITLE
Keyboard navigation for media editor

### LINKED ISSUE #682: Keyboard Nav when Editing Masked Image
## Bug Description

When focused / editing the masked image position, the keyboard should move the image in terms of the mask itself. Currently the keyboard moves the shape on the page.

image

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Insert a media element
1. Press arrow keys to move the entire media element around
1. Press <kbd>enter</kbd> to enter edit-mode
1. Press <kbd>tab</kbd> to focus the image size slider and observe the slider handle have focus color
1. Press arrow keys to change size (leave it bigger than the minimum size)
1. Press <kbd>shift</kbd> + <kbd>tab</kbd> to return focus to image (no visible focus indication available unfortunately)
1. Press arrow keys to move the image inside the mask
1. Press <kbd>esc</kbd> to exit edit-mode
1. Press arrow keys to move the entire media element around

_Note_: you **can** end up in a state, where you are in edit-mode but the edited image does not have focus. In such a case pressing the arrow keys would do nothing. To be able to move the image inside the mask, make sure to focus it (it will be focused when entering edit-mode but focus does not magically return to it).

### PR DESCRIPTION
**Pull request by wassgha**
## Summary

Adds ability to move the cropped image/video using keyboard arrows.

## To-do

- [x] ~Fix warning while setting `framesLayer` ref~
- [x] ~Restore keyboard events for dragging after finishing (otherwise dragging by keyboard will be disabled)~
- [x] Refactor code to prevent duplication between drag callbacks and keyboard callbacks
- [x] Add integration testing

## Testing Instructions

- Insert a media element
- Double click on the element
- Resize the crop window to be smaller than the original element
- Use keyboard arrows to move the original element
- Press tab or click on the image size slider to focus it
- Press left-right arrow keys to change size
- Press image again (or press shift+tab) to return focus to image
- Press keyboard arrows to move the original element 
---

Fixes #682

### CODE REVIEW

File: assets/src/edit-story/elements/media/editPanMovable.js [hunk 1]
```diff
@@ -47,21 +51,62 @@ function EditPanMovable({
...
-  };
+  }, [croppedMedia, fullMedia, transformFlip]);
 
   // Refresh moveables to ensure that the selection rect is always correct.
   useEffect(() => {
     moveableRef.current.updateRect();
   });
 
+  useKeyDownEffect(
+    framesLayer,
```
Comment (wassgha) [inline assets/src/edit-story/elements/media/editPanMovable.js]: From discussion with @dvoytenko , this shouldn't be on the `framesLayer`, need to override some other way

Comment (dvoytenko) [reply assets/src/edit-story/elements/media/editPanMovable.js]: Really anywhere between the `editLayer` and the actual image editor container is fine for this. The closer the better, of course.

Comment (wassgha) [reply assets/src/edit-story/elements/media/editPanMovable.js]: It seems like the current behavior of `mousetrap` is to prevent the propagation of captured key events from child to parent, however I've tried using `EditElement`, `EditLayer` and `EditPageArea` to capture these events with no success, the only thing that seems to be working is strangely `framesLayer`. Any idea as to why that happens?

Comment (dvoytenko) [reply assets/src/edit-story/elements/media/editPanMovable.js]: Unfortunately no idea. But, IMHO, we should try to start with the `elements/image/edit` (or `elements/media/edit` I think) and debug it. If you'd like feel free to set a handler, push the pull request, and I can help debugging mousetrap.

**Comment by barklund** [comment]
So this PR fixes #1426 or?

And why is #1426 closed as a duplicate of itself by the way? 😮

File: assets/src/edit-story/elements/media/editPanMovable.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/elements/media/editPanMovable.js]: The reason for this is, that `document.activeElement` is the frame element, not the edit element. Thus the keyboard handler needs to be added somewhere above the frame element to be intercepted before getting to the global key handler and adding it to the edit frame or anywhere around that does nothing, as keyboard events aren't handled by this stack.

I'll try to add keyboard focus to the image or a relevant container for the image rather than the frame element.

File: assets/src/edit-story/elements/media/editPanMoveable.js [hunk 2]
```diff
@@ -47,21 +50,58 @@ function EditPanMoveable({
...
-  };
+  }, [croppedMedia, fullMedia, transformFlip]);
 
   // Refresh moveables to ensure that the selection rect is always correct.
   useEffect(() => {
     moveableRef.current.updateRect();
   });
 
+  useKeyDownEffect(
+    { current: croppedMedia },
```
Comment (barklund) [inline assets/src/edit-story/elements/media/editPanMoveable.js]: This isn't pretty. But I'm not sure of the consequences if any.

@dvoytenko, any comments about this fake inline reference?

**Comment by barklund** [comment]
@googlebot I consent.

File: assets/src/edit-story/elements/media/editPanMovable.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/elements/media/editPanMovable.js]: Managed to fix the focus issues by focusing the image itself (and refocusing it whenever the Moveable is invoked).

**Comment by miina** [comment]
From testing:
- Otherwise works great, just one detail: there doesn't seem to be a visual difference if the keyboard focus is on the image or not -- e.g. using Tab to move to the slider and then back to the image doesn't make a visual difference for the image outline. Perhaps that can be deferred to the future though.

**Comment by miina** [comment]
One more from testing:
While in edit mode and focusing away, e.g. clicking somewhere on the design panel, and then using arrow keys, the whole element is moved up/down even though it's in the edit mode. Should in edit mode the panned image move instead of the whole element?

element

**Comment by merapi** [comment]
@barklund @miina Can you confirm this issue on Safari?
When you enter the edit mode and press TAB it should focus on the slider but it doesn't work for me (I can also end up in a state where arrows move the thole element with edit mode).

File: assets/src/edit-story/elements/media/editPanMoveable.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/elements/media/editPanMoveable.js]: `useKeyDownEffect` should accept either ref or a node so it should be ok to just pass `croppedMedia` directly as well.

File: assets/src/edit-story/elements/media/editPanMoveable.js [hunk 3]
```diff
@@ -47,21 +49,54 @@ function EditPanMoveable({
...
+      let { dx, dy } = getKeyboardMovement(key, shiftKey);
+      if (flip?.vertical) {
+        dy = -dy;
+      }
+      if (flip?.horizontal) {
+        dx = -dx;
+      }
+      const panFocalX = getFocalFromOffset(width, mediaWidth, offsetX - dx);
+      const panFocalY = getFocalFromOffset(height, mediaHeight, offsetY - dy);
+      setProperties({
```
Comment (miina) [inline assets/src/edit-story/elements/media/editPanMoveable.js:80]: It seems to lag currently when not clicking the keys slowly -- would be good to create a follow-up issue for looking into that.

**Comment by miina** [comment]
> When you enter the edit mode and press TAB it should focus on the slider but it doesn't work for me

@merapi Confirmed -- indeed that focuses on the design panel items instead.

File: assets/src/edit-story/elements/media/editPanMoveable.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/elements/media/editPanMoveable.js:80]: Yeah, there's a lot of lag currently. It's beginning to be a problem 😢

File: assets/src/edit-story/components/canvas/useCanvasKeys.js [hunk 4]
```diff
@@ -135,17 +138,18 @@ function useCanvasKeys(ref) {
   useGlobalKeyDownEffect(
     { key: ['up', 'down', 'left', 'right'], shift: true },
     ({ key, shiftKey }) => {
-      const dirX = getArrowDir(key, 'ArrowRight', 'ArrowLeft');
-      const dirY = getArrowDir(key, 'ArrowDown', 'ArrowUp');
-      const delta = shiftKey ? 1 : MOVE_COARSE_STEP;
+      if (isEditing) {
+        return;
+      }
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/useCanvasKeys.js:143]: @miina, I've added this to address that under some circumstances, you could still move the whole element around rather than the masked image. I think it makes sense.

This also impacts text editing, where you could select some text in edit mode, click "nothing" in the design panel, and then use arrow keys to move the whole text field around. It was actually pretty weird, so now both of those are disabled.

I think that's a fair result.

File: assets/src/edit-story/elements/media/edit.js [hunk 5]
```diff
@@ -132,15 +138,27 @@ function MediaEdit({ element, box }) {
     ref: setCroppedMedia,
     draggable: false,
     src: resource.src,
-    alt: resource.alt,
+    alt: __('Drag to move media element', 'web-stories'),
     opacity: opacity / 100,
+    tabIndex: 0,
```
Comment (barklund) [inline assets/src/edit-story/elements/media/edit.js:146]: I really don't know how we can make it clear, that the image has focus, unfortunately. It already has a border. We could apply some sort of filter to it? Not sure what to do and I don't think it's important for this PR for now.

Comment (barklund) [reply assets/src/edit-story/elements/media/edit.js:146]: Oh, and regarding the fact that in Safari you cannot tab from the image to the slider, that is due to Safari's default of not actually using tab to navigate elements. You have to enable that in settings (which I assume all keyboard-using Safari users do):

Screen Shot 2020-08-20 at 11 56 03

**Comment by barklund** [comment]
@miina, @merapi, I addressed your comments inline. Please see these two threads on [disabling moving editmode elements at all](https://github.com/google/web-stories-wp/pull/2108#discussion_r474094820) and [focus management](https://github.com/google/web-stories-wp/pull/2108#discussion_r474095489).

File: assets/src/edit-story/elements/media/editPanMoveable.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/elements/media/editPanMoveable.js]: Ah, much better - thanks! 🎉 🙏 

Fixed in 5b7031ec4.

File: assets/src/edit-story/elements/media/edit.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/elements/media/edit.js:146]: > Not sure what to do and I don't think it's important for this PR for now.

Probably just something to flag Sam with at some point, let's ignore for now.

**Review by miina — APPROVED** [review]
Unit tests are failing currently, otherwise LGTM (let's create a performance-related follow-up issue, too).

**Comment by merapi** [comment]
> Oh, and regarding the fact that in Safari you cannot tab from the image to the slider, that is due to Safari's default of not actually using tab to navigate elements. You have to enable that in settings (which I assume all keyboard-using Safari users do):
> 
> Screen Shot 2020-08-20 at 11 56 03

Ok, that works, how about this one? (maybe it will surface in other places): 
on every other browser when you change the zoom (via mouse), the slider becomes focused (blue), on Safari - it's not (you can't adjust zoom via keyboard after that).
