### PR TITLE
Reordering page thumbnails and the grid view

### LINKED ISSUE #332: Use generalized reordering component for carousel and grid view
As discussed in #281:

> As we went through the UX review of this feature, there are some UX requirements that made native DND inapplicable. Specifically dragging only within the bounds/axis. I'm afraid that will also mean that we will have to revisit page carousel/grid once we are done with layers.

### LINKED ISSUE #517: Improve carousel drag indicators / separators
## Bug Description

While looking at #380 / #411 I noticed that the blue bars indicating the drop location while reordering are not appearing in the center anymore. Instead, they are attached to either the left or the right item. Sometimes they are not appearing at all.

This is a regression.

## Expected Behaviour

Indicators/Separators are always appearing in the middle of two items.

## Steps to Reproduce

Drag & drop pages in the carousel using the mouse.

## Screenshots

Screenshot 2020-03-10 at 13 30 49

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #746: Pages Grid View Reordering UX Issue on Drag
## Bug Description

Went into Grid view to reorder pages. When I clicked and dragged the first page, I can see a "transparent" version of it being dragged (fine):
image

but when I selected and dragged the 2nd image, it looks like I'm dragging the previous and next pages along with it:
image

Taken from Claudio on #583 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
Closes #746
Closes #332
Closes #517 

Uses the same generalized `<Reorderable/>` component in the layers panel, the page thumbnails and the grid view
/cc @dvoytenko

### CODE REVIEW

**Comment by wassgha** [comment]
@dvoytenko @barklund this is ready for review. It seems like we might have overcomplicated the scrolling behavior in #551 , a simple `separator.scrollIntoView()` works pretty well here!

File: assets/src/edit-story/components/reorderable/reorderableSeparator.js [hunk 1]
```diff
@@ -44,22 +44,31 @@ const Line = styled.div`
...
 function ReorderableSeparator({ position, ...props }) {
+  const separatorRef = useRef(null);
+
   const {
     actions: { setCurrentSeparator },
     state: { isReordering },
   } = useReorderable();
   const handlePointerEnter = useCallback(() => {
     setCurrentSeparator(position);
+    separatorRef.current.scrollIntoView({
```
Comment (swissspidy) [inline assets/src/edit-story/components/reorderable/reorderableSeparator.js]: Safari only supports `scrollIntoView` with boolean parameter, but not smooth behavior option.

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 2]
```diff
@@ -132,10 +140,23 @@ const List = styled(Area).attrs({
   }
 `;
 
-const Li = styled.li.attrs({
-  role: 'option',
-})`
+const PageSeparator = styled(ReorderableSeparator)`
+  margin-left: ${({ width }) => 3 - 10 - width}px;
+  margin-right: ${({ width }) => 3 - width}px;
```
Comment (merapi) [inline assets/src/edit-story/components/canvas/carousel/index.js]: Is this gap intentional?
image

It creates a "dead zone" in the middle:
https://drive.google.com/open?id=1JObfk8OUollS-rOEXnYggAsqo1FU1VD0

**Review by merapi — CHANGES_REQUESTED** [review]
Also, noticed 3 warnings in the console.

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 3]
```diff
@@ -132,10 +140,23 @@ const List = styled(Area).attrs({
   }
 `;
 
-const Li = styled.li.attrs({
-  role: 'option',
-})`
+const PageSeparator = styled(ReorderableSeparator)`
+  margin-left: ${({ width }) => 3 - 10 - width}px;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/carousel/index.js]: What do these constants mean: `3` and `10`?

File: assets/src/edit-story/components/canvas/gridview/index.js [hunk 4]
```diff
@@ -161,33 +186,62 @@ ThumbnailSizeControl.propTypes = {
...
-                  : sprintf(__('Page %s', 'web-stories'), index + 1)
-              }
-              isActive={isCurrentPage}
-              pageIndex={index}
-              width={zoomLevel * PREVIEW_WIDTH + THUMB_FRAME_WIDTH}
-              height={zoomLevel * PREVIEW_HEIGHT + THUMB_FRAME_HEIGHT}
-              dragIndicatorOffset={GRID_GAP / 2}
-            />
+            <PagePreviewContainer key={`page-${index}`}>
+              {index === 0 && (
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/gridview/index.js]: I don't quite understand why separators need to be inside the PagePreviewContainer. Could you pls clarify?

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 5]
```diff
@@ -73,7 +74,7 @@ const PreviewWrapper = styled.div`
   background-position: 0 0, 0 4px, 4px -4px, -4px 0px;
 `;
 
-function PagePreview({ index, forwardedRef, ...props }) {
+const PagePreview = React.forwardRef(({ index, ...props }, forwardedRef) => {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: Is `forwaredRef` still needed here at all? It seemed like a product of DND originally.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/canvas/gridview/index.js (hunk 4 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/gridview/index.js]: Because otherwise they'd be counted as a grid item and take up as much space as a page preview, so unless we change the css grid, this has to be one element

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/gridview/index.js]: Got it.

File: assets/src/edit-story/components/reorderable/reorderableSeparator.js (hunk 1 above)
Comment (wassgha) [reply assets/src/edit-story/components/reorderable/reorderableSeparator.js]: That should be alright, just a slightly worse experience. Otherwise we can revert back to @barklund 's approach which should work for all browsers

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 2 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Fixed

**Comment by wassgha** [comment]
If we're good with using `scrollIntoView` for the scroll behavior, this should be good to go

File: assets/src/edit-story/components/reorderable/reorderable.js [hunk 6]
```diff
@@ -19,75 +19,54 @@
  */
 import PropTypes from 'prop-types';
 import styled from 'styled-components';
+import React from 'react';
```
Comment (swissspidy) [inline assets/src/edit-story/components/reorderable/reorderable.js]: nit: `import { forwardRef } from 'react';`

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 7]
```diff
@@ -73,7 +74,7 @@ const PreviewWrapper = styled.div`
   background-position: 0 0, 0 4px, 4px -4px, -4px 0px;
 `;
 
-function PagePreview({ index, forwardedRef, ...props }) {
+const PagePreview = ({ index, ...props }) => {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: Any reason for this style?

**Review by dvoytenko — APPROVED** [review]
LG with one nit.

**Comment by dvoytenko** [comment]
> LG with one nit.

Though I don't have a strong opinion on `scrollIntoView`. IMHO it's ok, but @barklund might feel different.

**Comment by swissspidy** [comment]
There is a couple of related warnings in the console:

```
Received NaN for the `width` attribute. If this is expected, cast the value to a string.
    in div (created by reorderableSeparator__Wrapper)

...

Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Carousel`. See https://fb.me/react-warning-keys for more information.
...

**Comment by wassgha** [comment]
@swissspidy @merapi ready :)

**Comment by merapi** [comment]
The "dead zone" is still there?

image

**Comment by wassgha** [comment]
@merapi Sorry, I refactored and totally forgot about that. Should be fixed now :))

**Comment by merapi** [comment]
> @merapi Sorry, I refactored and totally forgot about that. Should be fixed now :))

Can you check the Grid view? I think we need a fix there too.

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 8]
```diff
@@ -191,19 +229,9 @@ function Carousel() {
...
 
   useLayoutEffect(() => {
-    if (hasHorizontalOverflow) {
-      const currentPageRef = pageRefs.current[currentPageId];
-
-      if (!currentPageRef || !currentPageRef.scrollIntoView) {
-        return;
-      }
-
-      currentPageRef.scrollIntoView({
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/carousel/index.js]: Where is this code now? Looks like it's still needed...

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 9]
```diff
@@ -134,9 +143,36 @@ const List = styled(Area).attrs({
...
+
+const ItemContainer = styled.div`
+  display: flex;
+  flex-direction: row;
+  position: relative;
+`;
+
+const ReorderablePage = styled(ReorderableItem).attrs({ role: 'option' })`
+  display: flex;
+  flex-direction: row;
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js]: `flex-direction: row;´ is default, so not necessary here.

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 10]
```diff
@@ -134,9 +143,36 @@ const List = styled(Area).attrs({
...
+  width: ${({ width, margin }) => width + margin}px;
+  height: ${({ height }) => height - THUMB_FRAME_HEIGHT}px;
+  display: flex;
+  justify-content: center;
+
+  &:first-of-type {
+    left: -${({ width, margin }) => (width + 2 * margin) / 2}px;
+  }
+
+  & > div {
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js]: I know we don't allow a way to style the `Line` inside the separator here as it is, but I'd definitely prefer a better way than this. We could pass in `lineStyle={css``}`. Or it could be a render prop as `renderLine={(Line) => styled(Line)``}` defaulting to identity function.

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 11]
```diff
@@ -134,9 +143,36 @@ const List = styled(Area).attrs({
   }
 `;
 
-const Li = styled.li.attrs({
-  role: 'option',
-})`
+const PageSeparator = styled(ReorderableSeparator)`
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js:147]: This separator is not always perfectly aligned between the pages.

It is kind of clear in this demo, where the separator between pages 1-2 and 2-3 are a tad too far right, whereas the following separators are perfectly aligned in the center between the pages.

separator-offset

**Review by barklund — DISMISSED** [review]
A few minor bugs.

**Comment by barklund** [comment]
A couple more bugs specifically related to grid view (but not directly related to any line of code as far as I can see):

1. You cannot scroll in the modal, even if you in the default view can't see the all the pages (I have 11):
no-scroll

2. Even without dragging anything, the reordering separators show up at the ends of the rows:
weird-hover

3. As you reorder, there's no separator before the first item in the second (and subsequent) rows:
missing-2nd-row-sep

I don't know if they're out of scope for this ticket, though. 1. is potentially a general modal bug (with a potentially simple fix).

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 11 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js:147]: Fixed

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 10 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Made it into a child

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 9 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Fixed

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 8 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js]: Reverted

**Comment by wassgha** [comment]
Did a refactor (went back to using @barklund 's scroller approach since it was smoother) and fixed all of those issues :)

File: assets/src/edit-story/components/canvas/carousel/index.js [hunk 12]
```diff
@@ -104,10 +113,10 @@ const OverflowButtons = styled.div`
   }
 `;
 
-const List = styled(Area).attrs({
+const PageList = styled(Reorderable).attrs({
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/carousel/index.js:116]: I'm still missing some space in the beginning of this container. I can't see the first separator before the first page - I can drop in the first position fine, but can't see the first separator, when the line carousel is scrollable.
no-first-separator

**Review by barklund — COMMENTED** [review]
This works really well now - great job. There's just a single bug with the first separator missing in the carousel when it's scrollable.

File: assets/src/edit-story/components/canvas/carousel/index.js (hunk 12 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/carousel/index.js:116]: Fixed

**Comment by merapi** [comment]
LG!

Just one thing:
I can see the scrollbar (when not needed) in Gridview (Chrome/FF) and I think its style should match other scrollbars.
image

**Review by merapi — APPROVED** [review]
