### PR TITLE
Fix duplicate element ids when duplicating page

### LINKED ISSUE #1131: Edits sometimes applied to a different page when switching pages
## Bug Description

When I switch pages (from **old** page to **new** page which is a duplicate of **old** page) in a story while editing a text element, the edits to the text element get applied to the **new** page I switch to, rather than the **old** page where I was making the edits. 

## Expected Behaviour

Edits should have been applied to the text element in the **old** page.

## Steps to Reproduce

1. Add a text element to Page 1 of a story, write anything in it. 
2. Duplicate Page 1 and edit the text field on Page 2 to say something else.
3. Start editing the text element of Page 2 and, while still in editing mode on Page 2 switch the page to Page 1 by clicking on Page 1 in the page selector (below the editor canvas)
4. You may see the text you were editing in Page 2 now applied to the text element in Page 1. If you click back to Page 2, should notice that Page 2 text element didn't get any edits applied to it, it kept its original value. This is unexpected.

## Screenshots

https://drive.google.com/a/google.com/file/d/1i9Te_yq1VrC1dKx4U8sPqzSEDwLOAHzB/view?usp=sharing

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
Ensure unique ids by recreating elements when duplicating a page.

Fully fixes #1131 (the other half not covered by #1139 as [mentioned](https://github.com/google/web-stories-wp/issues/1131#issuecomment-611766617).

### CODE REVIEW

File: assets/src/edit-story/elements/index.js [hunk 1]
```diff
@@ -44,9 +44,19 @@ export const createNewElement = (type, attributes = {}) => {
...
+    createNewElement(type, attrs)
+  );
+  const newAttributes = {
+    elements,
+    ...rest,
+  };
+
   // Enforce having background element for each Page.
-  if (!backgroundElementId) {
+  if (!newAttributes.backgroundElementId) {
```
Comment (dvoytenko) [inline assets/src/edit-story/elements/index.js:62]: Shouldn't there be an else here as well?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/elements/index.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/elements/index.js:62]: Oh yeah, the existing background element will have a new id as well, and I just changed it so it doesn't match. Well done, me.

I'll add some tests to make sure all the cases are covered here.

Comment (barklund) [reply assets/src/edit-story/elements/index.js:62]: Fixed in 5ad3bc17 with test.

File: assets/src/edit-story/elements/index.js [hunk 2]
```diff
@@ -34,7 +34,10 @@ import * as videoElement from './video';
 
 export const createNewElement = (type, attributes = {}) => {
   const element = elementTypes.find((el) => el.type === type);
-  const defaultAttributes = element ? element.defaultAttributes : {};
+  if (!element) {
+    throw new Error(`Unknown element type: ${type}`);
+  }
+  const { defaultAttributes } = element;
```
Comment (barklund) [inline assets/src/edit-story/elements/index.js:40]: I updated this to extend test coverage of `createNewElement` to 100%. If there's no element type found, we really shouldn't proceed here - that would cause all sorts of weirdness.

File: assets/src/edit-story/elements/index.js [hunk 3]
```diff
@@ -34,7 +34,10 @@ import * as videoElement from './video';
 
 export const createNewElement = (type, attributes = {}) => {
   const element = elementTypes.find((el) => el.type === type);
-  const defaultAttributes = element ? element.defaultAttributes : {};
+  if (!element) {
+    throw new Error(`Unknown element type: ${type}`);
```
Comment (miina) [inline assets/src/edit-story/elements/index.js:38]: Perhaps we should also throw an error if a Page is inserted without background element id? E.g if someone uses `createNewElement` directly instead of going through `createPage`. That would also cause all sorts of weirdness such as the history breaking ;)

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/elements/index.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/elements/index.js:38]: Hm, we could, but then we ought to check for all required attributes for all types of elements (non-pages without `x` or `y` would break stuff too). I think it's okay for now.
