### PR TITLE
Design Panel: Improve accessibility for panel headers

### LINKED ISSUE #4603: A11Y: Section expand/collapse in design panel
## Bug Description

For sections "Size & position", "Layer", "Style", and "Link" in the design panel:

1. Mouse users can click anywhere in a design panel section header to toggle expanded/collapsed state. Keyboard users, however, must navigate into A11Y subtree of the `<h2>` and select and activate the `v` or `^` button.
2. The button changes its A11Y name based on expanded/collapsed state instead of using `aria-expanded`.

## Expected Behavior

1. Announce each section header as a button that toggles expansion/collapse on click. Disable each header's A11Y subtree (don't allow navigating into children).
2. Add `aria-expanded` to each section header to convey expanded/collapsed state. 

## Steps to Reproduce

Enable VoiceOver, navigate into the design panel, and highlight a section header.

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS 10.15.6
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

For sections 'Size & position', 'Layer', 'Style', 'Link'
1.disable navigation to each header's A11Y subtree
2.Add aria-expanded to each section header

## Relevant Technical Choices

Move the aria-* labels from the nested button to the header

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

Testing Instructions
Enable VoiceOver
Open Web Stories and choose a Shape Element
Use the VO key to navigate the header
Make sure the voice will announce the status of the section header and skip over the nested button.
Sample announcement text could be Size & position panel, expanded, button

---

Fixes #4603

### CODE REVIEW

File: assets/src/edit-story/components/panels/panel/simplePanel.js [hunk 1]
```diff
@@ -28,8 +33,16 @@ import PanelContent from './shared/content';
...
   return (
-    <Panel name={name} {...rest}>
-      <PanelTitle>{title}</PanelTitle>
+    <Panel name={name}>
+      <PanelTitle
+        title={sprintf(
+          /* translators: %s: panel name. */
+          __('%s panel', 'web-stories'),
+          title
+        )}
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/panel/simplePanel.js]: Is this necessary? Why are we adding "panel" as a suffix here?

File: assets/src/edit-story/components/panels/panel/shared/title.js [hunk 2]
```diff
@@ -193,6 +185,11 @@ function Title({
       isPrimary={isPrimary}
       isSecondary={isSecondary}
       hasResizeHandle={isResizable && !isCollapsed}
+      aria-label={title}
+      aria-expanded={!isCollapsed}
+      aria-controls={panelContentId}
+      role="button"
+      onClick={onToggle}
```
Comment (dreamofabear) [inline assets/src/edit-story/components/panels/panel/shared/title.js:184]: Since we're turning `<Header>` into a button, is `<HeaderButton>` now obsolete? Can its CSS be merged into `<Header>`?

File: assets/src/edit-story/components/panels/panel/simplePanel.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/simplePanel.js]: Yup, we added this by purpose, because we want the voiceover to speak the text. 

Screen Shot 2020-11-30 at 4 01 53 PM

To confirm, should we keep the 'panel' in the label text?

File: assets/src/edit-story/components/panels/panel/shared/title.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/shared/title.js:184]: Right, we did turn `<header>` into a button, but we might still need to keep the style `<HeaderButton>`, which was a `div` and its styling is for its children `<Heading>` and `<HeaderActions>`.

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/shared/title.js:184]: And to clarify, `<HeaderButton>` is obsolete and is no longer a `button`, instead, it is merely a `div`, we are keeping this element for styling reason.

File: assets/src/edit-story/components/panels/panel/simplePanel.js (hunk 1 above)
Comment (dreamofabear) [reply assets/src/edit-story/components/panels/panel/simplePanel.js]: I think either "Size & position" or "Size & position panel" is fine.

File: assets/src/edit-story/components/panels/panel/shared/title.js (hunk 2 above)
Comment (dreamofabear) [reply assets/src/edit-story/components/panels/panel/shared/title.js:184]: Yea, see its definition above: https://github.com/google/web-stories-wp/pull/5342/files#diff-a54a124ac5a73d9a8cecd8ccfb719d1cf8bff8738fa127b72f8779ad7c36bf3aR63-R70

My question is whether we can remove `<HeaderButton>` by merging its CSS into `<Header>`. 

Minimally, we can rename `HeaderButton` to `HeaderLayout` and remove `{role: 'button'}` attribute.

Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/shared/title.js:184]: Got it! And agree to remove the unnecessary layer!

File: assets/src/edit-story/components/panels/panel/simplePanel.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/simplePanel.js]: Keep it short as "Size & position".

**Review by dreamofabear — APPROVED** [review]

File: assets/src/edit-story/components/panels/panel/simplePanel.js [hunk 3]
```diff
@@ -28,8 +28,8 @@ import PanelContent from './shared/content';
 
 function SimplePanel({ children, name, title, ...rest }) {
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/simplePanel.js:29]: `[no-unused-vars] 'rest' is defined but never used.`

File: assets/src/edit-story/components/panels/panel/simplePanel.js [hunk 4]
```diff
@@ -28,8 +28,8 @@ import PanelContent from './shared/content';
...
   return (
-    <Panel name={name} {...rest}>
-      <PanelTitle>{title}</PanelTitle>
+    <Panel name={name}>
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/simplePanel.js]: Why was this changed? Some panels rely on these props being passed down.

Change looks unrelated.

**Comment by swissspidy** [comment]
Note that there are quite a few failing tests now

File: assets/src/edit-story/components/panels/panel/simplePanel.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/simplePanel.js:29]: Ah, got it, this is from the conflict resolve. In this case, I should keep it.

File: assets/src/edit-story/components/panels/panel/simplePanel.js (hunk 4 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/simplePanel.js]: It was mistakenly deleted from resolving conflict. Added back.

**Review by swissspidy — COMMENTED** [review]
LGTM, but I'll defer to @barklund for final judgement due to his knowledge of the panels area :)

File: assets/src/edit-story/components/panels/panel/shared/title.js [hunk 5]
```diff
@@ -205,29 +202,26 @@ function Title({
...
-          )}
-        </HeaderActions>
-      </HeaderButton>
+      <Heading id={panelTitleId}>{children}</Heading>
+      <HeaderActions>
+        {secondaryAction}
+        {canCollapse && (
+          <Toggle
+            isCollapsed={isCollapsed}
+            aria-label={titleLabel}
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/shared/title.js]: I think you ought to remove this from here?

File: assets/src/edit-story/components/panels/panel/shared/title.js [hunk 6]
```diff
@@ -48,7 +48,7 @@ function getBackgroundColor(isPrimary, isSecondary, theme) {
   return 'transparent';
 }
 
-const Header = styled.h2`
+const Header = styled.h2.attrs({ role: 'button' })`
```
Comment (barklund) [inline assets/src/edit-story/components/panels/panel/shared/title.js:46]: I just want to say, that this seems extremely _unsemantic_ to me and want it to be reflected on the record, that I don't like it.

But if the a11y-team wants this, I'll approve it.

Oh, and this single line summarizes the _unsemanticness_ of this PR perfectly per my opinion.

**Review by barklund — APPROVED** [review]

File: assets/src/edit-story/components/panels/panel/shared/title.js (hunk 5 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/shared/title.js]: Removed the label, but need to keep isCollapsed for the component style reason.

File: assets/src/edit-story/components/panels/panel/shared/title.js (hunk 6 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/panels/panel/shared/title.js:46]: Acknowledged.

File: assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js [hunk 7]
```diff
@@ -81,10 +81,6 @@ export class TextStyle extends AbstractPanel {
     return this.getByRole('textbox', { name: /Font size/ });
   }
 
-  get collapse() {
-    return this.getByRole('button', { name: /Collapse panel/ });
```
Comment (swissspidy) [inline assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js:85]: Instead of removing this & its usage in `assets/src/edit-story/components/panels/karma/textStyle.karma.js`, would it be possible to replace this with

```js
get collapse() {
  return this.getByRole('button', { name: 'Style' });
}
```

?

Comment (zidianlyu) [reply assets/src/edit-story/karma/fixture/containers/designPanel/textStyle.js:85]: That's a good catch! Tested and verified!
