### PR TITLE
Editor: add focus styling to title input

### LINKED ISSUE #10849: Editor: Title input focus styles aren't correct
## Bug Description

The title input in the editor shows the old focus styles, but we want to see the new pretty focus styles.

## Expected Behaviour

Display correct styling when focused.

## Steps to Reproduce

Focus the title bar, tab away, and tab back. Should see the outline.

## Screenshots

input-focus-state

## Additional Context

- Plugin Version: 1.19.0-alpha.0
- WordPress Version: 5.9.1
- Operating System: MacOSX Big Sur 11.6.2
- Browser: Chrome

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

The title input was missing focus outline

## Summary

Adds the focus outline to title input.

## Relevant Technical Choices
I was going to grab `Input` from design system, but the styling is quite different from our basic input so this seemed the better choice. 

Added radius, the outline looked a little weird with square corners

## User-facing changes

title

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. tab to title input, you should see outline while the input is in focus

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10849

### CODE REVIEW

File: packages/story-editor/src/components/header/title.js [hunk 1]
```diff
@@ -43,6 +43,8 @@ const Input = styled.input`
   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;
+  ${({ theme }) => themeHelpers.focusableOutlineCSS(theme.colors.border.focus)};
```
Comment (samwhale) [inline packages/story-editor/src/components/header/title.js]: 🤔 I think `theme.colors.border.focus` is the default, so does the following work?
```suggestion
  ${themeHelpers.focusableOutlineCSS};
```

**Review by samwhale — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
