### PR TITLE
Document Panel: Improve Calendar accessibility

### LINKED ISSUE #4431: A11Y: Multiple issues with calendar widget
## Bug Description

- When opening the widget, keyboard focus is not shifted from the main window to the calendar popup
- After opening the widget, keyboard focus is not trapped inside this calendar popup (can jump out to background)
- There is no way to dismiss the popup unless the user selects a date
- Previous/next buttons do not have appropriate labels and are read as "buttons"
- Minor: Dates don't announce the day of the week
- No state information provided to AMP/PM toggle buttons

## Screenshots

Screen Shot 2020-09-09 at 5 35 16 PM

## Additional Context

- Plugin Version: 1.0.0-beta.2+fd68af7
- Operating System: macOS 10.15.6
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
- Adds aria labels to prev-next buttons
- Close the calendar when using "Esc"
- Focus when opening the popup
- state aria-pressed information for AM/PM toggle
- use the roving tab index for Calendar days.

## To-do

- [ ] Karma

## Testing Instructions
1. Open the calendar
2. Verify that the first input got focused
3. Tab into the dates
4. Use arrow keys to move the focus
5. Click "Esc" to close the calendar
6. Verify that the aria labels exist for forward/back arrows.

---

Fixes #4431

### CODE REVIEW

File: assets/src/edit-story/components/form/dateTime/dateTime.js [hunk 1]
```diff
@@ -52,6 +55,21 @@ function DateTime({
...
+      if (previousFocus.current) {
+        previousFocus.current.focus();
+      }
+      onClose(evt);
+    },
+    [onClose]
+  );
+
+  useKeyDownEffect(forwardedRef, 'esc', handleClose);
+  useRovingTabIndex({ ref: forwardedRef });
```
Comment (miina) [inline assets/src/edit-story/components/form/dateTime/dateTime.js:72]: Yes, this seems to just work! 🎉

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 2]
```diff
@@ -45,6 +50,10 @@ function DatePicker({ currentDate, onChange, onViewChange }) {
         value={value}
         onChange={handleOnChange}
         onViewChange={onViewChange}
+        nextAriaLabel={__('Next', 'web-stories')}
```
Comment (swissspidy) [inline assets/src/edit-story/components/form/dateTime/datePicker.js]: Needs `_x()` context to make it clear what "Next" and "Previous" refers to. Year, month, week, day.

Depending on that the translations will be different.

Comment (barklund) [reply assets/src/edit-story/components/form/dateTime/datePicker.js]: The label will be the same regardless of what it _next_'s to. So it should be a label, that'll work for both _next month_, _next year_, and _next decade_.

Otherwise we should request up-stream that this can be a function returning a label depending on the view, but that's a more complicated process.

File: assets/src/edit-story/components/form/dateTime/dateTime.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/form/dateTime/dateTime.js:72]: We need all the buttons in the calendar-display to have `tabIndex=-1` from the start except the first one. Otherwise, when you start combining arrows and tabbing, you'll get some very weird results.

File: assets/src/edit-story/components/form/dateTime/dateTime.js [hunk 3]
```diff
@@ -52,6 +55,21 @@ function DateTime({
     hours: is12Hour ? initialHours % 12 || 12 : initialHours,
     date: selectedTime,
   });
+
+  const previousFocus = useRef(document.activeElement);
+  const handleClose = useCallback(
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/dateTime.js:61]: We still need focus trapping - you can shift-tab out of the overlay and move focus to some random place in the editor (the overlay will close). Shift-tab should just tab to the last focusable element inside the component and vice-versa. We have this focus trapping in our dialog component, so you can probably steal the functionality from there.

**Review by barklund — CHANGES_REQUESTED** [review]
Looks good, just some weirdness when combining tabbing and arrow movement in the calendar display due to not all buttons having `tabIndex=-1` initially.

File: assets/src/edit-story/components/form/dateTime/datePicker.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/datePicker.js]: Yep, I'm not sure what could be a good label that would work for any. Maybe "Move to next" or "Move forward" or "Next dates" instead? These also don't sound quite right. Thoughts?

File: assets/src/edit-story/components/form/dateTime/dateTime.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/dateTime.js:61]: @barklund Using the Modal to use with all Popups didn't seem that straightforward currently, added a potential focus trapping util instead, that should fix the calendar accessibility as well, thoughts? https://github.com/google/web-stories-wp/pull/4677/commits/bd80e493d8e7cc00c7ae9020e913cdcdcea53e34

File: assets/src/edit-story/components/form/dateTime/datePicker.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/form/dateTime/datePicker.js]: Let's leave this worry as an exercise for the translator with an `_x()` context saying `"This label can apply to both next month, next year and/or next decade"` or similar.

File: assets/src/edit-story/utils/useFocusTrapping.js [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+    if (!node) {
+      return [];
+    }
+    return [
+      ...node.querySelectorAll(
+        'a[href], button, textarea, input[type]:not([type="hidden"]), select'
+      ),
+    ].filter((el) => {
+      return (
+        !el.hasAttribute('disabled') && el.getAttribute('tabindex') !== '-1'
```
Comment (barklund) [inline assets/src/edit-story/utils/useFocusTrapping.js]: We could do this in the selector query too, but that might be a bit much.

File: assets/src/edit-story/utils/useFocusTrapping.js [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+import { useKeyDownEffect } from '../components/keyboard';
+
+function useFocusTrapping({ ref }) {
+  const getFocusableElements = useCallback((node) => {
+    if (!node) {
+      return [];
+    }
+    return [
+      ...node.querySelectorAll(
+        'a[href], button, textarea, input[type]:not([type="hidden"]), select'
```
Comment (barklund) [inline assets/src/edit-story/utils/useFocusTrapping.js]: This is going to be a tricky selector. We'd at least also need `[role=button]`, `[role=link]` and `[role=option]`. But I'm okay with updating this on a _need-to-focus_ basis.

File: assets/src/edit-story/utils/useFocusTrapping.js [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+      ),
+    ].filter((el) => {
+      return (
```
Comment (barklund) [inline assets/src/edit-story/utils/useFocusTrapping.js]: You can lose the `{ return ...; }` and just use [implicit return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Basic_syntax:~:text=One%20param.%20With%20simple%20expression%20return%20is%20not%20needed%3A) here.

File: assets/src/edit-story/utils/useFocusTrapping.js [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+ * External dependencies
+ */
+import { useCallback } from 'react';
+/**
+ * Internal dependencies
+ */
+import { useKeyDownEffect } from '../components/keyboard';
+
+function useFocusTrapping({ ref }) {
+  const getFocusableElements = useCallback((node) => {
```
Comment (barklund) [inline assets/src/edit-story/utils/useFocusTrapping.js]: I'd put this function definition outside the hook - there's no need to define it inside nor memoize it there.

File: assets/src/edit-story/components/keyboard/index.js [hunk 8]
```diff
@@ -305,9 +315,9 @@ function createKeyHandler(
       return undefined;
     }
     callback(evt);
-    // The `false` value instructs Mousetrap to cancel event propagation
+    // The default `false` value instructs Mousetrap to cancel event propagation
     // and default behavior.
-    return false;
+    return allowDefault;
```
Comment (barklund) [inline assets/src/edit-story/components/keyboard/index.js:320]: You could also simply do `return callback(evt) ?? false;` and then you don't need the `allowDefault` config option - just return differently in the callback.

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 9]
```diff
@@ -39,12 +44,41 @@ function DatePicker({ currentDate, onChange, onViewChange }) {
...
+        ...nodeRef.current.querySelectorAll(
+          '.react-calendar__viewContainer button'
+        ),
+      ];
+      buttons.shift();
+      for (const btn of buttons) {
+        btn.tabIndex = '-1';
+      }
+    }
+  }, [nodeRef]);
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/datePicker.js]: This effect unfortunately has to run everytime the component switch view. If you switch to the month view (by clicking the month), all the month buttons now don't have `tabIndex=-1` and navigation breaks again. Clicking a month brings you back to the day view without `tabIndex=-1` and navigation is still broken. Similarly, if you switch to the next or previous month/year/decade.

If you move it to a `useCallback` to be called in both the `useEffect` on first render and then also as a callback on every [`onViewChange`](https://github.com/wojtekmaj/react-calendar#user-content-props:~:text=onViewChange)  and [`onActiveStartDayChange`](https://github.com/wojtekmaj/react-calendar#user-content-props:~:text=onActiveStartDateChange) reported from the component, I think it'll work correctly - but it's a bit fragile 😒 .

And maybe the initially selected button (the one without `tabIndex=-1`) shouldn't necessarily be the first one, but rather the currently highlighted one (e.g. current day/month/year) if any.

This is a... meh... but it might work?

**Review by barklund — COMMENTED** [review]
Still not there yet, but it has potential.

File: assets/src/edit-story/utils/useFocusTrapping.js (hunk 4 above)
Comment (miina) [reply assets/src/edit-story/utils/useFocusTrapping.js]: Yep, did that initially, seemed to be better this way.

File: assets/src/edit-story/utils/useFocusTrapping.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/utils/useFocusTrapping.js]: Let's add when actually needed.

File: assets/src/edit-story/components/keyboard/index.js (hunk 8 above)
Comment (miina) [reply assets/src/edit-story/components/keyboard/index.js:320]: That would require ensuring all the callbacks are returning/not returning anything for some reason. It seems to be more reliable by specifying explicitly if it should go with the default behavior. Thoughts?

File: assets/src/edit-story/components/form/dateTime/datePicker.js (hunk 9 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/datePicker.js]: Made some adjustments based on your recommendation, it seems to work as expected now, PTAL.

File: assets/src/edit-story/components/keyboard/index.js (hunk 8 above)
Comment (barklund) [reply assets/src/edit-story/components/keyboard/index.js:320]: Hm yeah, some callbacks might be shorthand arrow functions, that happen to return something (maybe a random promise). This is definitely a safer route, so good with me.

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 10]
```diff
@@ -39,12 +44,84 @@ function DatePicker({ currentDate, onChange, onViewChange }) {
...
+          } else {
+            btn.tabIndex = '0';
+            if (setFocus) {
+              // When changing view we need to explicitly set focus again,
+              // It seems to not be happening by default.
+              btn.focus();
+            }
+            foundActive = true;
+          }
+        }
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/datePicker.js]: This works really great now. Just two things, the former being the more important one:

* If you select a date that is not today, close the date picker and open it again and tab to the date view, then you don't notice that "today" has focus, as it does not have a focus styling. We should really do something here - maybe even make it the same gray as a normally focused day or just a (much) lighter or darker yellow.
* What if two buttons have the `react-calendar__tile--now` class? It would technically leave two buttons with `tabIndex=0`, but I guess it's not possible?

File: assets/src/edit-story/components/form/dateTime/datePicker.js [hunk 11]
```diff
@@ -39,12 +44,84 @@ function DatePicker({ currentDate, onChange, onViewChange }) {
...
+        // Dates / days.
+        const buttons = [
+          ...nodeRef.current.querySelectorAll(
+            '.react-calendar__viewContainer button'
+          ),
+        ];
+
+        let foundActive = false;
+        for (const btn of buttons) {
+          if (!btn.className.includes('react-calendar__tile--now')) {
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/datePicker.js]: You can use [`.classList.contains()`](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/contains) here.

File: assets/src/edit-story/components/form/dateTime/timePicker.js [hunk 12]
```diff
@@ -193,13 +194,21 @@ function TimePicker({ onChange, is12Hour, localData, setLocalData }) {
...
   };
 
+  const hours = useRef();
+  useEffect(() => {
+    hours.current.focus();
+  }, []);
+
+  const isAM = localData.am === 'AM';
+  const isPM = localData.am === 'PM';
   return (
```
Comment (barklund) [inline assets/src/edit-story/components/form/dateTime/timePicker.js:208]: It might just be me now, but - I could really use a "Today" button around here (it did end up in a completely wrong century though, so my bad):

Screen Shot 2020-09-28 at 19 16 21

**Review by barklund — APPROVED** [review]
This is really good work. Great job making this external component much more accessible in a cleaner interface.

Maybe @wojtekmaj would want to re-incorporate some of this back into [`react-calendar`](https://github.com/wojtekmaj/react-calendar)?

File: assets/src/edit-story/components/form/dateTime/timePicker.js (hunk 12 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/timePicker.js:208]: Yep, probably this could be implemented as part of #1391 although the calendar library itself would also benefit from that, didn't see the option in the props currently but perhaps I'm missing something.

File: assets/src/edit-story/components/form/dateTime/datePicker.js (hunk 10 above)
Comment (miina) [reply assets/src/edit-story/components/form/dateTime/datePicker.js]: Added global style for adding a different color for the current date being focused, PTAL.

On having two buttons with the same class -- yes, that really shouldn't happen, can't see a scenario where two dates would be selected at the same time -- AFAIK the calendar doesn't support choosing more than one date. For now at least.
