### PR TITLE
Execute focusout callback when element is removed (and was focused)

### LINKED ISSUE #1164: Text element change is sometimes not persisted
## Bug Description

The text element sometimes returns to its old value, e.g. when clicking on the workspace (works when clicking in elements/inspector panel).

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by merapi**
Fixes https://github.com/google/web-stories-wp/issues/1164

**Update: Fixing it at a different level.**

~~Actually it was not so trivial as callback in clean-up/unmount, because it would be nice if we only trigger it for elements that were actually focused, so I'm detecting that (all edge cases that I found, from simple inputs to text element editor).
Same code for Dashboard copy.~~

### CODE REVIEW

**Review by dvoytenko — CHANGES_REQUESTED** [review]
I'm coming back to the exactly the same conclusion on this as before. I think focus-out is a wrong path here entirely. Or at least it shouldn't be the only path. We have exactly the only path where the editor can be closed, and it's in the `useEditingElement`. It's due to new element ID or `clearEditing` is called. If we can just hook up sync "submission" before the editing element ID is changed - we should be all good. And this would be the most stable and targeted solution.

**Comment by dvoytenko** [comment]
As a hot fix, however, our best path is to bring back the unmounting callback.

**Comment by obetomuniz** [comment]
If you decide to revert to the old unmount approach as a hotfix, keep in mind that bug #922 will be enabled again. So, as a hotfix, we should use both: `useFocusOut` and `unmount`.

`const updateContent = useCallback(() => {...}, [...])`

`useFocusOut(textBoxRef, updateContent, [...])`

`useEffect(() => () => updateContent, [...])`

File: assets/src/dashboard/utils/useFocusOut.js [hunk 1]
```diff
@@ -29,23 +30,40 @@ function useFocusOut(ref, callback, deps) {
...
       const isInNode = node.contains(evt.target);
       if (!isInNode && isInDocument) {
+        isFocused = false;
         callback();
       }
+      // Handle text element editor case
+      const activeElementInNode = node.contains(document.activeElement);
+      if (activeElementInNode) {
+        isFocused = true;
+      }
```
Comment (obetomuniz) [inline assets/src/dashboard/utils/useFocusOut.js]: Is it only necessary for text element cases? Not sure if we should create specificities like this for hooks that can be reusable across the editor/dashboard. Instead, I would recommend adding the potential fix inside the text element codebase on the Editor.

File: assets/src/edit-story/utils/useFocusOut.js [hunk 2]
```diff
@@ -29,23 +30,40 @@ function useFocusOut(ref, callback, deps) {
...
       const isInNode = node.contains(evt.target);
       if (!isInNode && isInDocument) {
+        isFocused = false;
         callback();
       }
+      // Handle text element editor case
+      const activeElementInNode = node.contains(document.activeElement);
+      if (activeElementInNode) {
+        isFocused = true;
+      }
```
Comment (obetomuniz) [inline assets/src/edit-story/utils/useFocusOut.js]: Ditto.

**Comment by dvoytenko** [comment]
I think doing both onFocusOut and unmount is exactly right. But we need to fast follow with a complete asap as well. I assume adding back unmount would be a much faster step.

File: assets/src/dashboard/utils/useFocusOut.js (hunk 1 above)
Comment (merapi) [reply assets/src/dashboard/utils/useFocusOut.js]: Right now, just this case is "unique" - it's more complex than others because it involves 3P library with auto-focus and it was the cleanest (and working) way to handle it. But it can catch other more complex cases too.

**Review by barklund — APPROVED** [review]
Let's get this merged!

File: assets/src/edit-story/components/form/color/colorPreview.js [hunk 3]
```diff
@@ -160,8 +161,8 @@ function ColorPreview({
     previewText,
   ]);
 
-  // Always hide color picker on unmount - note the double arrows
-  useEffect(() => () => hideSidebar(), [hideSidebar]);
+  // Always hide color picker on unmount
+  useUnmount(hideSidebar);
```
Comment (barklund) [inline assets/src/edit-story/components/form/color/colorPreview.js:165]: 🙏

File: assets/src/edit-story/utils/useUnmount.js [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * External dependencies
+ */
+import { useEffect } from 'react';
+
+/**
+ * @param {function()} callback The callback to be executed on unmount
```
Comment (dvoytenko) [inline assets/src/edit-story/utils/useUnmount.js]: Please document that the callback MUST be stable.

**Review by dvoytenko — APPROVED** [review]
Approved with one request
