### PR TITLE
Block: Adjust margin for "Remove" button

### LINKED ISSUE #10164: Block: Remove button styling off
## Bug Description

The styling of the remove thumbnail button seems to be off. Being too close to the select button see screenshot. 

## Screenshots

Screenshot 2022-01-12 at 10 54 08

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by timarney**
## Context

Updates margin for poster image "remove button" 

## Relevant Technical Choices

Adds a 12px margin (left and right) 
This matches the spacing for other WP buttons i.e. preview & publish)

## User-facing changes

| **Before**   |      **After**    
|----------|:-------------:|
| before |  Screen Shot 2022-02-07 at 4 28 08 PM | 
|before-hover  |   hover   | 

**Right to left support**

Screen Shot 2022-02-07 at 5 09 15 PM

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Insert a Web Stories block, select displaying a single story
2. Insert a story URL, e.g. `https://preview.amp.dev/documentation/examples/introduction/stories_in_amp`
3. View button spacing for poster image

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10164

### CODE REVIEW

File: packages/stories-block/src/block/block-types/single-story/embedControls.js [hunk 1]
```diff
@@ -151,7 +151,11 @@ const EmbedControls = (props) => {
                       )}
                 </p>
                 {hasPoster && (
-                  <Button onClick={onRemovePoster} isTertiary>
+                  <Button
+                    style={{ margin: '0 12px' }}
```
Comment (spacedmonkey) [inline packages/stories-block/src/block/block-types/single-story/embedControls.js:155]: This button, should should have the same padding not margin as the button next to it. Is there way to make this `isPrimary` but have a white background?

File: packages/stories-block/src/block/block-types/single-story/embedControls.js [hunk 2]
```diff
@@ -151,7 +151,11 @@ const EmbedControls = (props) => {
...
+                    onClick={onRemovePoster}
+                    isTertiary
+                  >
```
Comment (spacedmonkey) [inline packages/stories-block/src/block/block-types/single-story/embedControls.js]:
```suggestion
                  <Button onClick={onRemovePoster}>
```

Just removing the `isTertiary` seems to do the trick.

Comment (spacedmonkey) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: See https://wordpress.github.io/gutenberg/?path=/docs/components-button--default

Comment (timarney) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: Pushed an update -- removed isTertiary + the hard coded margin on the button.

Comment (timarney) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: With the margin removed --- the buttons outline when focused still "bump" into each other when using the keyboard to navigate.

With "VoiceOver" on + keyboard nav
Screen Shot 2022-02-08 at 5 59 03 AM

Keyboard nav "VoiceOver" off
Screen Shot 2022-02-08 at 6 30 18 AM

Comment (swissspidy) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: In that case, maybe some left margin + removing isTertiary?

Comment (timarney) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: @spacedmonkey understand your concern about hard coding a margin but I'm not finding other examples in the code base for spacing.

The button group https://wordpress.github.io/gutenberg/?path=/docs/components-buttongroup--default 

Still hard codes a value --- but it applies to both buttons.

```
() => {
	const style = { margin: '0 4px' };
	return (
		<ButtonGroup>
			<Button variant="primary" style={ style }>
				Button 1
			</Button>
			<Button variant="primary" style={ style }>
				Button 2
			</Button>
		</ButtonGroup>
	);
}
```

Comment (swissspidy) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: We have a CSS file in our block for adding custom styling if necessary.

Comment (timarney) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: Re-added the margin here:

https://github.com/GoogleForCreators/web-stories-wp/pull/10510/commits/062fb080cbcfdd2ad9bcbe770e8175486aa7b969

I'm not a fan of hard-coding this either but moving it out to a stylesheet will likely make it harder to track down if / when it needs to be updated.

Open to other suggestions as you see fit.

Comment (swissspidy) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: > moving it out to a stylesheet will likely make it harder to track down if / when it needs to be updated.

Fair concern, but now it's an outlier because all our other styles are in a stylesheet.

Also, our stylesheet files are run through RTLCSS.

So you only need to write `margin-left: 12px` and it will be automatically changed to `margin-right: 12px` for RTL.

That can't be done for inline styles.


So I'd just add a className to the Remove button and style that in the CSS file.

File: packages/stories-block/src/block/block-types/single-story/embedControls.js [hunk 3]
```diff
@@ -151,7 +151,7 @@ const EmbedControls = (props) => {
                       )}
                 </p>
                 {hasPoster && (
-                  <Button onClick={onRemovePoster} isTertiary>
+                  <Button className="remove" onClick={onRemovePoster}>
```
Comment (swissspidy) [inline packages/stories-block/src/block/block-types/single-story/embedControls.js]: Nit: let's use `web-stories-embed-poster-remove` as the class name, in line with the `web-stories-embed-poster-label` class name above.

Comment (timarney) [reply packages/stories-block/src/block/block-types/single-story/embedControls.js]: Sounds good -- pushed a commit.

**Review by spacedmonkey — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
LGTM!

Really appreciate the detailed PR description including RTL screenshots too.
