### PR TITLE
Design System:  fix getoffset calculation for Popups

### LINKED ISSUE #10928: Popup's getOffset util calculation incorrect when using dock
## Bug Description

When moving the color picker popup to `dock` on the right of the new `sidebar` component it was discovered in #10883 that the `Popup`'s util function `getOffset` is [calculating the offset incorrectly](https://github.com/GoogleForCreators/web-stories-wp/blob/main/packages/design-system/src/components/popup/utils/getOffset.js#L28-L32). Currently, it check's for a truthy value for `dockRect?.left`. However, `dockReck.left` can be and now is a falsey value of zero. This means it unintentionally uses the anchor's left value instead of the dock's left value.  In this sidebar color picker use case, the dock element being passed into the `Popup` is a reference to the entire `inspector` element since we want it docked to right of the entire `sidebar`. Now that this element is on the left side of the screen, the dockRect's left value is zero. This is also the case for style presets.

We can not however simply change the check for dockRect since the it would still make the math for  `leftAligned` (and `rightAligned`) incorrect. When `dock`ing a popup, we shouldn't be adding the width of the anchor, as the anchor is no longer relevant to positioning. It should be noted however, that in the use case for tooltips, `rightAligned` would need to account for anchor width. 

It should also be noted that `leftAligned` and `rightAligned` mean something different when talking about where to `dock`, vs. `placement` of the popup -> tooltip. In addition to RTL mode. 

Currently, the  `Popup` component has 17 props, with another one being added to differentiate "normal popups" from the tooltip's implementation. While `Tooltip` _only_ sends down 8 to Popup, and yet has 16 of it's own props, trying to account for all use cases is getting problematic. Regressions are hard to manage since there are vastly different ui needs between Popups, Tooltips, and Dropdown. With so much complexity and the use cases diverging it may be time to split apart `Tooltip` from `Popup` and perhaps `Dropdown`as well.  

## Expected Behaviour

We expect the Popup to render in relation to the dock element whenever a dock ref is present. We also expect the offset calculations be based on the referenced element and that those calculations take into account whether we are docked on the right of an element or on the left. 
 
## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### LINKED ISSUE #11020: Popup Sidebar Regression: Overlap
## Bug Description

Seems a regression occurred somewhere in the sidebar work because these popups _were_ addressed. Now they are overlapping again. 

Text color is fine but now border and bg are overlapping. 

| Border | Text color | Background |
| --- | --- | --- | 
| Screen Shot 2022-03-22 at 10 52 21 AM | Screen Shot 2022-03-22 at 10 52 28 AM | Screen Shot 2022-03-22 at 10 52 35 AM | 

## Additional Context

PR that originally fixed: https://github.com/GoogleForCreators/web-stories-wp/pull/10883 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context

The background color picker popup is not respecting offset spacing in relation to it's docked element. 

## Summary
The background color picker popup was getting incorrect values for the inspector's `dock` `getXOffset`. Since those calculations were incorrect anyway, see #10928  I decided to fix the calculation instead of continuing to override spacing. 
If a Popup has an element it is docked against, the offset should be based on that dock regardless of it's values.

## Relevant Technical Choices
Updated the logic for calculating offset via `dock` element
Reset the spacing for color input and saves styles popups to only reflect expected margin from the docked element

### Before
| Border | Text color | Background |
| --- | --- | --- | 
| Screen Shot 2022-03-22 at 10 52 21 AM | Screen Shot 2022-03-22 at 10 52 28 AM | Screen Shot 2022-03-22 at 10 52 35 AM | 

### After 
| Border | Text color | Background |
| --- | --- | --- | 
|border|Screen Shot 2022-03-22 at 7 15 14 PM|background|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open each color picker; check if it is rendered in the correct spot. 
- background color
- shape color
- text color
- border color shape
- image filters
- image borders
- floating menus
2. Check Saved Styles popup is docked to the sidebar as well
3. Check for regressions on all tooltips in editor and on dashboard (Sorry it's a lot) 
4. Don't forget RTL

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11020 
Partially Fixes #10928

### CODE REVIEW

File: packages/design-system/src/components/popup/utils/getOffset.js [hunk 1]
```diff
@@ -25,15 +25,12 @@ export function getXOffset(
...
-  const rightAligned =
-    (dockRect?.left || anchorRect.left) + anchorRect.width + spacing;
-  const centerAligned =
-    (dockRect?.left || anchorRect.left) + anchorRect.width / 2;
+  // doctRect.left can have a valid value of zero, if dockRect exists, it takes precedence.
+  const leftAligned = (dockRect ? dockRect.left : anchorRect.left) - spacing;
+  const rightAligned = (dockRect ? dockRect.right : anchorRect.right) + spacing;
+  const centerAligned = dockRect
+    ? dockRect.left + dockRect.width / 2
+    : anchorRect.left + anchorRect.width / 2;
```
Comment (samwhale) [inline packages/design-system/src/components/popup/utils/getOffset.js:33]: 🥳

**Review by samwhale — APPROVED** [review]
Excelente

**Review by BrittanyIRL — APPROVED** [review]
🦈

**Review by maxyinger — APPROVED** [review]
💪
