### PR TITLE
3P MEdia: Small accessibility fixes

### LINKED ISSUE #4429: A11Y: Images/videos in media gallery not announced as clickable
## Bug Description

Images and videos in the media gallery should a clickable ARIA role e.g. `button` or similar.

## Screenshots

Screen Shot 2020-09-09 at 4 20 24 PM

## Additional Context

- Plugin Version: 1.0.0-beta.2+fd68af7
- Operating System: macOS 10.15.6
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #4430: A11Y: Images/Video/GIFs buttons in 3P media tab are not announced as clickable
## Bug Description

Images/Videos/GIFs buttons should have a clickable ARIA role like `button` or similar.

## Screenshots

Screen Shot 2020-09-09 at 4 37 05 PM

## Additional Context

- Plugin Version: 1.0.0-beta.2+fd68af7
- Operating System: macOS 10.15.6
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by diegovar**
Fixes #4429
Fixes #4430 

No visual changes.

### CODE REVIEW

**Review by cvolzke4 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js [hunk 1]
```diff
@@ -54,11 +54,15 @@ const Video = styled.video`
   object-fit: cover;
 `;
 
-const Container = styled.div.attrs((props) => ({
+const Container = styled.button.attrs((props) => ({
```
Comment (cvolzke4) [inline assets/src/edit-story/components/library/panes/media/common/mediaElement.js:57]: Would this have been reported as a violation by axe?
https://github.com/nickcolley/jest-axe

**Review by cvolzke4 — APPROVED** [review]

File: assets/src/edit-story/components/library/panes/media/common/mediaElement.js (hunk 1 above)
Comment (diegovar) [reply assets/src/edit-story/components/library/panes/media/common/mediaElement.js:57]: Mmm not sure, probably not because it has no way of knowing it's meant to be clicked?
