### PR TITLE
Story Editor: Carousel Page Preview Aria Labels

### LINKED ISSUE #4244: A11Y: Add relevant labels to thumbnails in carousel
## Bug Description

The buttons (with role=option) in the carousel do not have a proper label and thus their label is whatever is on the page they're displaying (including text fields and alt texts of images and videos).

This label should probably simply be `aria-label="Page ${num+1}"` instead.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Add multiple pages to a story, including text on pages
1. Press <kbd>tab</kbd> until the focus is on the current page indicator in the carousel below the canvas
1. Use the console to get the value of `document.activeElement` and `document.activeElement.ariaLabel`- observe that the former is a button element and the latter is the value `"Page X (current page)"` for X being the page number
1. Observe that this works correctly for both thumbnails and compact indicators.

_Example output (compact indicator first, thumbnail second):_

Screen Shot 2020-09-04 at 12 28 28

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Small one. aria labels were already getting created here, just weren't applied properly to the non collapsed page previews. This just fixes that real quick.

## User-facing changes
Page aria labels should now be on non-collapsed page preview thumbs in story editor carousel & grid view (they were already being applied to the collapsed ones, so didn't need to change anything)

## Testing Instructions
Open up a story in the story editor. Inspect the page preview buttons on the uncollapsed carousel & the grid view. See that they have aria-labels designating them as `Page <index>`.

---

Fixes #4244

### CODE REVIEW

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 1]
```diff
@@ -96,7 +96,13 @@ function PagePreview({ index, gridRef, ...props }) {
   return (
     <UnitsProvider pageSize={{ width, height }}>
       <TransformProvider>
-        <Page tabIndex={tabIndex} onBlur={onBlur} onFocus={onFocus} {...props}>
+        <Page
+          tabIndex={tabIndex}
+          onBlur={onBlur}
+          onFocus={onFocus}
+          aria-label={ariaLabel}
```
Comment (maxyinger) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: this is the only real change.

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 2]
```diff
@@ -78,7 +78,7 @@ function PagePreview({ index, gridRef, ...props }) {
   }));
   const page = pages[index];
   const { backgroundColor } = page;
-  const { width: thumbWidth, height: thumbHeight, isActive } = props;
+  const { width: thumbWidth, height: thumbHeight, isActive, ariaLabel } = props;
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: Since there's no need to keep it in `props` (I guess `<Page />` doesn't do anything about the `ariaLabel` prop), you can destruct it out above in the function definition:

```js
function PagePreview({ index, gridRef, ariaLabel, ...props }) {
```

Alternatively, you can make the parent component set `aria-label` rather than `ariaLabel` and it should probably work without any other changes.

Comment (maxyinger) [reply assets/src/edit-story/components/canvas/pagepreview/index.js]: yea absolutely. sounds good. will update

**Review by dmmulroy — APPROVED** [review]
lgtm 👍

File: assets/src/edit-story/components/canvas/pagepreview/index.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/pagepreview/index.js]: Looking further into this, you can simply [rename `ariaLabel` to `aria-label`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/carousel/index.js#L418) in the parent `<Carousel />` component. And then just let it pass through `...props` here without explicitly mentioning it.

With the renaming of `ariaLabel` to `aria-label` in `<Carousel />`, you can then completely delete the components  
`<CompactIndicatorWithRef />` and `<CompactIndicator />` in [the file `compactIndicator.js`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/carousel/compactIndicator.js#L30-L40) altogether and just make `Indicator` default export directly in that file (maybe rename it to `CompactIndicator` so it fits with the filename).

That'll reduce the complexity slightly of this file and significantly of `compactIndicator.js` - all the forward-ref and proptype-stuff in that one can just go out the door!

Comment (maxyinger) [reply assets/src/edit-story/components/canvas/pagepreview/index.js]: ooh yea. very nice

File: assets/src/edit-story/components/canvas/pagepreview/index.js [hunk 3]
```diff
@@ -114,6 +114,7 @@ function PagePreview({ index, gridRef, ...props }) {
 }
 
 PagePreview.propTypes = {
+  ariaLabel: PropTypes.string.isRequired,
```
Comment (miina) [inline assets/src/edit-story/components/canvas/pagepreview/index.js]: This doesn't seem to be required anymore since `aria-label` is used instead.

Comment (maxyinger) [reply assets/src/edit-story/components/canvas/pagepreview/index.js]: ope. yup. good catch

**Review by barklund — APPROVED** [review]

**Comment by csossi** [comment]
Verified in QA
