### PR TITLE
Media: Fix video drag an drop upload in Safari

### LINKED ISSUE #10098: Media: Drag and drop video in safari not working
## Bug Description

Dragging and dropping a video onto canvas in Safari does not upload the video. However dragging image into canvas does work. 

## Expected Behaviour

On dragging video into canvas, it should upload. 

## Screenshots

https://user-images.githubusercontent.com/237508/148226381-9693c062-a934-4bb1-97e7-30a6271df492.mov

## Additional Context

- Plugin Version: 1.15.1
- WordPress Version: 5.9-RC1
- Operating System: Mac OS 11.6
- Browser: 15.1

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

This change fixes the issue with video upload from safari. Change logic in seekVideo, use seeking and seeked events. canPlay is not fired in safari. 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. In safari. 
2. Open editor. 
3. Drag video into canvas. 
4. See it upload with preview. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10098

### CODE REVIEW

**Comment by swissspidy** [comment]
There's `preloadVideoMetadata` that should be used instead

File: packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js [hunk 1]
```diff
@@ -76,17 +75,25 @@ const getVideoResource = async (file) => {
...
 
-  const videoEl = await preloadVideo(src);
-  const canPlayVideo = '' !== videoEl.canPlayType(mimeType);
+  const videoEl = document.createElement('video');
+  videoEl.src = src;
+  videoEl.addEventListener('loadedmetadata', () => {
+    const lengthData = getVideoLength(videoEl);
+    length = lengthData.length;
+    lengthFormatted = lengthData.lengthFormatted;
+  });
```
Comment (swissspidy) [inline packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js]: This won't work because it's not in a promise. There's gonna be race conditions.

Hence I'd highly recommend using `preloadVideoMetaData` instead.

That said, I think this uses `preloadVideo` for a reason.

Need to ensure that the length information and the `canPlayVideo` value, as well as the `hasAudio` stuff below still works as expected.

Comment (spacedmonkey) [reply packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js]: But it was work.. Why does it have to be a promise here? We are loading a resource here, it is a source url. Why did it work before ( before it was a promise ) and why does it work?

Comment (swissspidy) [reply packages/story-editor/src/app/media/utils/getResourceFromLocalFile.js]: Then it was wrong before. It won't work **_reliably_** due to a possible race condition. If the `loadedmetadata` event fires only after 10 seconds the whole code below will have been executed already. Hence the need for `preloadVideoMetadata`

**Comment by swissspidy** [comment]
Need to ensure that the length information and the `canPlayVideo` value, as well as the `hasAudio` stuff below still works as expected.

Have you tested that in multiple browsers?

I do recall that this uses `preloadVideo` on purpose, to ensure as much information as possible (length, audio, can play, poster) is available in all browsers for a variety of video types. I just want to prevent regressions.

**Comment by spacedmonkey** [comment]
> Have you tested that in multiple browsers?

I did some testing on Friday. It seemed to work. However, doing more testing today it doesn't seem to work. 

> Then it was wrong before. 

I was unaware this. Can you explain exactly why this NEEDS to asyncly load?

**Comment by swissspidy** [comment]
> I was unaware this. Can you explain exactly why this NEEDS to asyncly load?

What I mean is that this code here does not work reliably:

```js
   let length;
  let lengthFormatted;

  const videoEl = document.createElement('video');
  videoEl.src = src;
  videoEl.addEventListener('loadedmetadata', () => {
    const lengthData = getVideoLength(videoEl);
    length = lengthData.length;
    lengthFormatted = lengthData.lengthFormatted;
  });

  return length; // This will still be undefined because there is no guarantee `loadedmetadata` has fired yet.
```

That's why this needs to be a Promise, which is why I asked you to change it.

**Comment by swissspidy** [comment]
Just making this a draft to avoid creating Percy snapshots unnecessarily while this is being worked on

File: packages/media/src/seekVideo.js [hunk 2]
```diff
@@ -29,19 +29,15 @@ function seekVideo(video, offset = 0.99) {
...
+    // If the seek takes longer 3 seconds, guess it timed out and error out.
+    video.addEventListener('seeking', (evt) => {
       const wait = setTimeout(() => {
         clearTimeout(wait);
         reject(evt);
       }, THREE_SECONDS);
     });
     video.addEventListener('error', reject);
-    video.addEventListener('canplay', () => resolve(video), { once: true });
+    video.addEventListener('seeked', () => resolve(video), { once: true });
```
Comment (spacedmonkey) [inline packages/media/src/seekVideo.js:40]: For reference https://github.com/google/web-stories-wp/blob/b051c770f668a88bd636787c19337e059349d44a/packages/media/src/preloadVideo.js#L32

This is how it used to be.

**Comment by swissspidy** [comment]
`seekVideo()` is used in lots of places, e.g. when taking frames from a video in the video trimming screen, and when doing audio detection. Do these still work as expected, even in Safari?

**Comment by spacedmonkey** [comment]
> seekVideo() is used in lots of places, e.g. when taking frames from a video in the video trimming screen, and when doing audio detection. Do these still work as expected, even in Safari?

Worked well in my testing, I tested, chroumium, safari, firefox and chrome. This also fixes issues with chroumium that can not play mp4s.

File: packages/media/src/seekVideo.js [hunk 3]
```diff
@@ -29,19 +29,15 @@ function seekVideo(video, offset = 0.99) {
...
-    // desired to reject on "suspend" straight away.
-    // Instead, delay rejection in the hopes that the "canplay" event fires
-    // in the meantime.
-    video.addEventListener('suspend', (evt) => {
+    // If the seek takes longer 3 seconds, guess it timed out and error out.
+    video.addEventListener('seeking', (evt) => {
       const wait = setTimeout(() => {
         clearTimeout(wait);
         reject(evt);
       }, THREE_SECONDS);
```
Comment (spacedmonkey) [inline packages/media/src/seekVideo.js:41]: @swissspidy why was this 3 seconds in the first place. Now it based on seeking, I would if this could fail quickly.

Comment (swissspidy) [reply packages/media/src/seekVideo.js:41]: The inline comment explained it.

The suspend event is potentially fired multiple times, even if the browser eventually loads the video.

It rejects the error if the video was „properly“ suspended and the browser really never loaded it. In my testing 3s was a reasonable time to wait.

What you have now is listening to the seeking event, which is immediately fired when the browser starts seeking, to start the timeout.
That seems odd to me. With this, I don‘t think it makes sense to set the timeout in there. Have you tried moving that out of there? No need to listen for seeking at all.

Comment (spacedmonkey) [reply packages/media/src/seekVideo.js:41]: Wasn't the question I asked here, why was 3 seconds? Just a random number?

Should I just remove this?

Comment (swissspidy) [reply packages/media/src/seekVideo.js:41]: > In my testing 3s was a reasonable time to wait.

Comment (swissspidy) [reply packages/media/src/seekVideo.js:41]: The `suspend` listener was added because `canplay` potentially never fired. Are you certain that `seeked` is always fired? I am a bit skeptical.

Need to ensure there's proper handling for when seeking doesn't happen.

You mentioned `stalled` and `aborted` on Slack as events to potential listen for.

Maybe you need to give that a try.

Comment (spacedmonkey) [reply packages/media/src/seekVideo.js:41]: Seeked event would always fire on success. See [docs](https://html.spec.whatwg.org/multipage/media.html#event-media-seeked). 

Hooking into seeking, makes sense as once the seek start, there is then 3 seconds for it to be fulfilled or it will be rejected.

**Comment by spacedmonkey** [comment]
After some more testing, here are my findings. 

1. Adding a promise reject on abort, does not make sense. This event is only fired when a user abort a video loading. 
2. Adding a promise reject on shalled might be problem, as I was seeing shalled events safari, even when video worked. 
3. Seek events, always fire when the currentTime is changed and success.
4. Keeping a timeout to seekVideo, to be overly careful and ensure that seekVideo will always timeout and error out. 

The PR works well in it's current form, let's leave it as it is.

**Review by swissspidy — APPROVED** [review]
If this doesn't cause any regressions then I guess it's fine
