### PR TITLE
Dashboard: Add a save button to the google analytics id form

### LINKED ISSUE #3843: Dashboard Settings: Unclear how to save analytics ID updates
_This is somewhere between a bug and a feature - I think it's just an implementation detail that didn't get communicated/lost in the shuffle._

## Bug Description
It is not clear how to save new analytics IDs in the UI 

## Expected Behaviour
It should be clear to all users how to submit an update in this input. The same issue will exist for updating story names in the dashboard since this is a shared form component. Do we want a button of some sort or are we to save automatically when the input has lost focus? 

## Steps to Reproduce
Dashboard > Settings > update the Google Analytics Tracking ID, now you have to hit enter. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dmmulroy**
## Summary

Add a save button to the google analytics id form

no-change

change

## User-facing changes

- Adds a button to the google analytics id form that becomes disabled under two exclusive conditions:
1. You supply an invalid GA id
2. You type in the currently saved GA id

## Testing Instructions
- Navigate to Editor Settings
- Type in a valid GA id (ua-#-#) and click save. Refresh the page and see that the GA id you entered is the value in the text box
- Edit the GA id to another valid GA id and press Enter.  Refresh the page and see that the GA id you entered is the value in the text box
- Delete the value from Input box and press Enter/Click Save.  Refresh the page to see that there is no GA id.

---

 #3843

### CODE REVIEW

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js [hunk 1]
```diff
@@ -28,14 +28,17 @@ import { __ } from '@wordpress/i18n';
 /**
  * Internal dependencies
  */
+import { useEffect } from 'react';
```
Comment (carloskelly13) [inline assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: Yeah sometimes VSCode does this.

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js [hunk 2]
```diff
@@ -55,47 +58,67 @@ export const TEXT = {
...
         />
+        {inputError && <ErrorText>{inputError}</ErrorText>}
         <TextInputHelperText>
           {TEXT.CONTEXT}
           <InlineLink href={TEXT.CONTEXT_ARTICLE_LINK}>
             {TEXT.CONTEXT_ARTICLE}
           </InlineLink>
         </TextInputHelperText>
+        <SaveButton isDisabled={disableSaveButton} onClick={handleOnSave}>
+          {'Save'}
```
Comment (carloskelly13) [inline assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: Let's use the WP `__()` i18n helper!

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js [hunk 3]
```diff
@@ -55,47 +57,67 @@ export const TEXT = {
...
+        <TextInput
           label={TEXT.ARIA_LABEL}
           id="gaTrackingId"
           value={analyticsId}
-          onEditCancel={handleCancelUpdateId}
-          onEditComplete={handleUpdateId}
+          onChange={handleUpdateId}
+          onKeyDown={handleOnKeyDown}
           placeholder={TEXT.PLACEHOLDER}
           error={inputError}
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: you can scrap this error prop, it was to render within the `InlineInputForm` element

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js [hunk 4]
```diff
@@ -55,47 +57,67 @@ export const TEXT = {
...
+        {inputError && <ErrorText>{inputError}</ErrorText>}
         <TextInputHelperText>
           {TEXT.CONTEXT}
           <InlineLink href={TEXT.CONTEXT_ARTICLE_LINK}>
             {TEXT.CONTEXT_ARTICLE}
           </InlineLink>
         </TextInputHelperText>
+        <SaveButton isDisabled={disableSaveButton} onClick={handleOnSave}>
+          {__('Save', 'web-stories')}
+        </SaveButton>
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: Sam left updated designs here: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Stable-Release?node-id=2%3A89741 on 9/1/2020 - https://github.com/google/web-stories-wp/issues/3843 

Since this does solve the issue of not knowing how to save the analytics ID and since the new button styles haven't been replaced in the dashboard I'm in favor of splitting the difference with what's in the designs and what's here and just moving the save button up above the helper text so when you tab out of the input it's the first thing you focus on. we can adjust the button styling and shared line as a follow next sprint.

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 5]
```diff
@@ -118,7 +119,7 @@ function Header({
 
   const [debouncedTypeaheadChange] = useDebouncedCallback(
     search.setKeyword,
-    300
+    TEXT_INPUT_DEBOUNCE
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/myStories/header/index.js:122]: 👏

**Review by BrittanyIRL — COMMENTED** [review]
Overall this is great and solves the issue of not knowing how to save the tracking ID. Few small things.

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js (hunk 3 above)
Comment (dmmulroy) [reply assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: `error` is actually used by `TextInput` and was being passed down to it through `InlineInputForm`

```javascript
export const TextInput = styled.input`
  ${TypographyPresets.Small};
  width: 100%;
  margin: 0;
  padding: 1px 8px;
  border-radius: 6px;
  border: ${({ theme, error }) =>
    error ? theme.borders.danger : theme.borders.gray100};
  &:active {
    border: ${({ theme, error }) =>
      error ? theme.borders.danger : theme.borders.action};
  }
`;
```

**Review by BrittanyIRL — APPROVED** [review]
Thanks for the updates!

File: assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js (hunk 3 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/editorSettings/googleAnalytics/index.js]: oh! my bad!

**Review by carloskelly13 — APPROVED** [review]
Works well and the screen reader + focus works too!

**Comment by csossi** [comment]
Verified in QA
