### PR TITLE
Hotlinking: Disable insert button for invalid/empty link.

### LINKED ISSUE #8921: Hotlinking - Invalid URL warning incorrectly presented.
## Bug Description
Originally reported by @aaskedall 
The ui is telling me the link is invalid but I can press insert and it works

After entering an invalid URL, the error message is not cleared when a new value is entered in that field.

image16

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by miina**
## Summary
Per Andrew's instructions, the Insert button should be disabled for Invalid link.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open the Hotlink Modal.
2. Verify the Insert button is disabled for empty link.
3. Add something Invalid to the input and click Insert
4. Verify the Insert button gets disabled when the Invalid link error shows.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8921

### CODE REVIEW

File: packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js [hunk 1]
```diff
@@ -106,6 +106,7 @@ function HotlinkModal({ isOpen, onClose }) {
       onPrimary={() => onInsert()}
       primaryText={__('Insert', 'web-stories')}
       secondaryText={__('Cancel', 'web-stories')}
+      primaryRest={{ disabled: errorMsg || !link }}
```
Comment (barklund) [inline packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js:109]: That's a terrible prop name! Is it used in many places? It really ought to be called `primaryProps` or even better `primaryButtonProps`.

**Review by barklund — APPROVED** [review]

File: packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js:109]: It's used in quite a few places, yes. There's also `secondaryRest` for the secondary button.

Comment (barklund) [reply packages/story-editor/src/components/library/panes/media/local/hotlink/hotlinkModal.js:109]: I've filed #8980.
