### PR TITLE
Disable guidelines for background and fill elements

### LINKED ISSUE #369: Cross hair guidelines appear on background image on selection
## Bug Description

Cross hair guidelines appear on background image on selection.

## Expected Behaviour

The guidelines should only appear on pointer down (drag).

## Steps to Reproduce

Add an image to the background, then click it.

## Screenshots

image

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
Avoids crosshairs effect

Fixes #369

### CODE REVIEW

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 1]
```diff
@@ -141,9 +141,9 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
     isTextElement && selectedElement.content.length && isResizingFromCorner;
 
   const { isMedia } = getDefinitionForType(selectedElement.type);
-  const actionsEnabled =
-    !selectedElement.isFill &&
-    selectedElement.id !== currentPage.backgroundElementId;
+  const isBackgroundElement =
+    selectedElement.id === currentPage.backgroundElementId;
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js]: This reminds me... We should probably add a `isBackground` property (maintained by the reducer) in the story provider - we often need this check and this way of doing it is rather annoying. And the reducer has full control of what element is and isn't background and already has a method for filtering out disallowed properties for new and updated elements (so no element tries to sneak in this property).

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: Yeah that would make sense to me!

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: I think we already have `isBackground` property there :)

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 2]
```diff
@@ -263,9 +263,11 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
       snapHorizontal={true}
       snapVertical={true}
       snapCenter={true}
-      horizontalGuidelines={[0, canvasHeight / 2, canvasHeight]}
-      verticalGuidelines={[0, canvasWidth / 2, canvasWidth]}
-      elementGuidelines={otherNodes}
+      horizontalGuidelines={
+        actionsEnabled && [0, canvasHeight / 2, canvasHeight]
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js]: I think we also should add `|| null`. Not great to pass `false` to a property that expects an array.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js [hunk 3]
```diff
@@ -263,9 +263,11 @@ function SingleSelectionMovable({ selectedElement, targetEl, pushEvent }) {
...
+      }
+      verticalGuidelines={actionsEnabled && [0, canvasWidth / 2, canvasWidth]}
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/singleSelectionMovable.js]: I think these changes are all correct one, but there's one more issue. The guidelines show up because of the `dragStart` call [above](https://github.com/google/web-stories-wp/blob/4afcdcba7610906c72d9537fbe4472204375be9b/assets/src/edit-story/components/canvas/singleSelectionMovable.js#L87). Let's also condition that call by `!isBackrgoundELement`.

**Review by dvoytenko — DISMISSED** [review]

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: Even better!

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: `Moveable` doesn't seem to crash with `null`. Passing an empty array now instead.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: I used the same `actionsEnabled` condition to also cover `isFill`. Didn't see a reason why not.

**Review by miina — APPROVED** [review]
LGTM

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 2 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: Pretty sure `null` is fine. I was commenting about the `false` value before.

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 3 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: 👍

File: assets/src/edit-story/components/canvas/singleSelectionMovable.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/components/canvas/singleSelectionMovable.js]: I mis-typed; `Movable` **does** seem to crash when I tested with `null`. That's why I went with this.
