### PR TITLE
Simple focus-to-canvas improvements

### LINKED ISSUE #738: Keyboard: default focus is broken in the editor
## Bug Description

Very often the active element in the editor ends up being top-level `<body>` element. We tried to keep away from adding too many shortcuts on the `<body>` element to avoid collisions with WP and to reduce the scope of overlapping shortcuts such as arrow keys. The typical issue is that many canvas shortcuts (e.g. "del" to delete the selected element(s), etc) are not handled.

The editor should either do a better job at defaulting the active area back to the canvas area. Or it should push key handlers deeper into the DOM.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

/cc @dvoytenko @barklund

### PR DESCRIPTION
**Pull request by dvoytenko**
Fixes #738.

### CODE REVIEW

File: assets/src/edit-story/components/canvas/useFocusCanvas.js [hunk 1]
```diff
@@ -22,8 +22,12 @@ import { useCallback } from 'react';
 function useFocusCanvas() {
   const focusCanvas = useCallback(() => {
     setTimeout(() => {
+      const doc = window.document;
+      if (doc.activeElement && doc.activeElement !== doc.body) {
+        doc.activeElement.blur();
+      }
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/useFocusCanvas.js:28]: If this happens, then we don't need the fake event, do we? Shouldn't we just return here?

**Review by barklund — APPROVED** [review]
Looks good and works great for all the cases covered. Just a minor optimization idea.

File: assets/src/edit-story/components/canvas/useFocusCanvas.js (hunk 1 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/useFocusCanvas.js:28]: I still want the blur event, at least when the active element is the body.
