### PR TITLE
Animations: honor `prefers-reduced-motion` setting

### LINKED ISSUE #7567: Broken animations with `prefers-reduced-motion`
## Bug Description

Not everyone likes decorative animations or transitions, and some users outright experience motion sickness when faced with parallax scrolling, zooming effects, and so on.

That's why users can express to prefer reduced motion on websites. See https://web.dev/prefers-reduced-motion/.

Unfortunately, our story animations currently break completely in that case, making elements disappear.

There are some ideas to fix this on the format side: https://github.com/ampproject/amphtml/issues/24821

Perhaps we can add some workaround on our end in the meantime?

## Expected Behaviour

Elements should still be visible, but not animated

## Steps to Reproduce

1. Reduce motion
2. Create a new story with some animated elements
3. Preview story
4. Notice elements are not appearing

To reduce motion:

In Windows 10: Settings > Ease of Access > Display > Show animations in Windows.
In macOS: System Preferences > Accessibility > Display > Reduce motion.
In iOS: Settings > General > Accessibility > Reduce Motion.
In Android 9+: Settings > Accessibility > Remove animations.

## Screenshots

Editor:

Screenshot 2021-05-18 at 15 38 21

Reduce Motion:

Screenshot 2021-05-18 at 15 38 04

No Reduce Motion:

Screenshot 2021-05-18 at 15 38 11

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7
- Operating System: all
- Browser: all

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Animated elements in a story are not visible at all when "Reduce Motion" setting is enabled in the OS settings.

## Summary

Changes an animated element's initial style (specifically, its `transform`) so that it's wrapped in a `@media (prefers-reduced-motion: no-preference)` media query, to prevent the animation from being placed outside the canvas and never getting moved (because animations are turned off).

## Relevant Technical Choices

* Uses `@media (prefers-reduced-motion: no-preference)` instead of `@media not (prefers-reduced-motion)` due to the JS AMP validator complaining
* Uses CSS custom properties for defining the initial transform in an inline style, and applying it in a media query in `<style amp-custom>`.

## To-do

N/A

## User-facing changes

Without Reduce Motion (unchanged behavior):

https://user-images.githubusercontent.com/841956/118848165-cacae380-b8ce-11eb-9e10-89bb00078380.mov

With Reduce Motion (no animation, but element visible):

https://user-images.githubusercontent.com/841956/118848154-c7375c80-b8ce-11eb-8614-6ffb81e43450.mov

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a few pages and elements to a story
2. Add animations to all of them
3. Preview story on frontend
4. Verify that animations play as expected, and that animated elements on next page aren't visible before animation starts
5. Turn on Reduce Motion in OS settings (see #7567 for steps)
6. Preview story again
7. Verify that elements are no longer animated, but visible at the some position they would be at after animations finish

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7567

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
Awesome, was just looking over the issue you posted for this earlier this morning.

Just want to clarify for my own understanding.

**Bug Before**
In the story preview `prefers-reduced-motion` was being respected, however since we set the initial keyframe as a style for some animations, and they weren't animating, the element would never appear on screen and would be stuck in the initial position we applied.

**Solution Here**
We only conditionally set the initial style on the element if the user doesn't have `prefers-reduced-motion` enabled.

Assuming my understanding above is correct, looks great! Thanks for walking me through this.

**Comment by dreamofabear** [comment]
Nice quick fix. Would be ideal if this could get addressed upstream in AMP though.

**Comment by swissspidy** [comment]
> Awesome, was just looking over the issue you posted for this earlier this morning.
> 
> Just want to clarify for my own understanding.
> 
> **Bug Before**
> In the story preview `prefers-reduced-motion` was being respected, however since we set the initial keyframe as a style for some animations, and they weren't animating, the element would never appear on screen and would be stuck in the initial position we applied.
> 
> **Solution Here**
> We only conditionally set the initial style on the element if the user doesn't have `prefers-reduced-motion` enabled.
> 
> Assuming my understanding above is correct, looks great! Thanks for walking me through this.

Yup, exactly 👍 

Any thoughts on dropping `opacity` from the initial style like I did here?
Seems like only the Twirl In animation uses it, and it seems to work fine with this change here.
It would mean I could simply remove `getInitialStyleFromKeyframes()`.

File: assets/src/animation/parts/simpleAnimation.js [hunk 1]
```diff
@@ -73,24 +73,32 @@ function SimpleAnimation(
   WAAPIAnimation.propTypes = WAAPIAnimationProps;
 
   const AMPTarget = function ({ children, style = {} }) {
-    const initialStylesFromKeyframes = targetLeafElement
+    // TODO: Support opacity as well?
```
Comment (maxyinger) [inline assets/src/animation/parts/simpleAnimation.js]: I'm not sure if opacity is needed. We initially put this on here to prevent a jump that would occasionally happen in the preview where even tho the animation fill was set to `both` the new page would initially appear without any keyframe styles applied, then a frame later actually apply the initial keyframe styles. This was a brute force approach to prevent that.

If we want to test out if support for opacity is needed here, we could:
-> set `prefers-reduced-motion` disabled
-> create a story with two pages
-> on the second page, add a fg element and give it a fade-in effect
-> preview the story
-> click to the next page
-> see if there's an initial frame where the element is completely visible before playing the fade-in animation

I'm not noticing it being an issue right now with your branch on my local

File: assets/src/edit-story/output/utils/styles.js [hunk 2]
```diff
@@ -102,6 +102,12 @@ function CustomStyles() {
                 bottom: 0;
                 margin: 0;
               }
+
+              @media (prefers-reduced-motion: no-preference) {
+                .animation-wrapper {
+                  transform: var(--ws-initial-transform);
+                }
+              }
```
Comment (maxyinger) [inline assets/src/edit-story/output/utils/styles.js]: I'm actually not seeing any initial frame issues if we remove setting the initial frame entirely. Maybe this was only needed with how the old amp previewer rendered a story and with the latest update is no longer needed.

Can you confirm on your local that if you remove this and preview a story with a bunch of animations that there's no flicker on initial frame issues where the element is set to the last keyframe style for the first frame, then plays the animation? @choumx @swissspidy

File: assets/src/animation/parts/simpleAnimation.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/animation/parts/simpleAnimation.js]: > see if there's an initial frame where the element is completely visible before playing the fade-in animation

There is 😞  You can see the second page here:

Screenshot 2021-05-19 at 19 40 58

Whereas on `main` it's not visible because of the opacity

Screenshot 2021-05-19 at 19 42 54

(both screenshots taken _without_ Reduce Motion)

Comment (swissspidy) [reply assets/src/animation/parts/simpleAnimation.js]: So in the "preview" of the second page the element is already visible, but there's actually an animation. Here's a screencast of what I mean:

https://user-images.githubusercontent.com/841956/118859718-d7553900-b8da-11eb-915a-9aa4a5fdb057.mov

So you basically see the element's end state in the preview now (due to the lack of opacity)

Edit: apologies for the bad contrast, but there should be a star visible on the second page at 0:01

File: assets/src/edit-story/output/utils/styles.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/output/utils/styles.js]: While I don't see any flickering, it causes the element to be visible in the preview (on desktop), see my comment above with a video.

File: assets/src/animation/parts/simpleAnimation.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/animation/parts/simpleAnimation.js]: Updated code to include opacity now as well.

File: assets/src/animation/parts/simpleAnimation.js [hunk 3]
```diff
@@ -73,24 +73,29 @@ function SimpleAnimation(
...
```
Comment (swissspidy) [inline assets/src/animation/parts/simpleAnimation.js]:
```suggestion
```

**Comment by swissspidy** [comment]
@littlemilkstudio mind reviewing this one again?

**Review by maxyinger — APPROVED** [review]
lgtm
