### PR TITLE
Editor: Fixed right-click in layer panel

### LINKED ISSUE #11717: Layers Panel: Support RCM on multi selection
## Feature Description

Currently, we don't support RCM for multiple layers selected, it will show a single item RCM (the one you clicked last).
It will be useful for grouping/locking multiple elements from the Layers Panel.

### PR DESCRIPTION
**Pull request by barklund**
Essentially just had to make sure that the reorderable only looks for regular left-clicks and ignores other mouse button clicks.

## Testing Instructions

This PR can be tested by following these steps:

1. Select multiple elements on stage in any possible way
2. Right-click (without pressing shift or meta at the same time) one of the layers in the layer panel and observe, that all the layers remain selected.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11717

### CODE REVIEW

File: packages/story-editor/src/components/reorderable/useReordering.js [hunk 1]
```diff
@@ -36,9 +36,10 @@ function useReordering(onPositionChange, numChildren) {
   const handleStartReordering = useCallback(
     ({ position: currentPos, onStartReordering = () => {} }) =>
       (evt) => {
-        // Only allow reordering with non-modified click on non-background element.
```
Comment (barklund) [inline packages/story-editor/src/components/reorderable/useReordering.js:39]: The "non-background element" part was left from before the _reorderable_ was generalized out of the layer panel, so this comment does not belong here anymore.

**Comment by timarney** [comment]
Should the functionality work for `Control-click` on a mac to display the RCM?

Tested with a mouse and works as expected.

**Review by merapi — APPROVED** [review]
I tested it on my integration branch too - works great 🎉 
I think it's safe to say that this doesn't need any additional QA now and can be merged, either way, another round of QA will be conducted on the integration branch on Monday.

**Review by timarney — APPROVED** [review]
Re-tested --- works great.
