### PR TITLE
Story Locking: Fix crash if there is no user avatar

### LINKED ISSUE #8588: Story Locking: Permission error
## Bug Description

I just encountered an issue with the story locking where an author user was not able to get the lock information for a story due to lack of permissions.

The reason for that is that we're getting the `wp:lockuser` information via `_embed` from the users controller. And since the `context` is `edit`, this requires `list_users` permission in WordPress, which only admins have.

Because of this, we don't actually get a user object in `wp:lockuser` but a 403 error due to lack of permissions.

I think the easiest way to solve this would be to not use `_embed` for getting the lock user, but instead make the user ID, name and avatar part of the lock response itself.

## Expected Behaviour

Authors should be able to see lock information from others, not risking issues because of `list_users` checks.

## Steps to Reproduce

1. Edit a story as an administrator
2. In a different browser or an incognito window, log in as an author user
3. Go to the dashboard
4. See that the dashboard does not load due to a JS error
5. Check preloaded API response to see that there's a 403 error.

## Additional Context

- Plugin Version: 1.10-alpha
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #8593: Story Locking: Dashboard crashes when there is no user avatar
## Bug Description
If avatars are disables with a lock post the dashboard errors.

## Steps to Reproduce

1. Disable Avatars, Settings > Discusssion > Show avatar
2. Go to dashboard.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

If avatars are disables with a lock post the dashboard errors.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Login as author, create story and save draft. 
2. In another browser, login as an admin. 
3. Disable Avatars, Settings > Discussion > Show avatar
4. Go to dashboard.
5. Should see lock icon and not avatar. 

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8593
Fixes #8588

### CODE REVIEW

File: assets/src/dashboard/app/serializers/stories.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ export default function reshapeStoryObject(originalStoryData) {
     lockUser: {
       id: lockUser[0].id,
       name: lockUser[0].name,
-      avatar: lockUser[0].avatar_urls['96'] || null,
+      avatar: lockUser[0].avatar_urls?.['96'] || null,
```
Comment (swissspidy) [inline assets/src/dashboard/app/serializers/stories.js]: Do we need the same in the editor as well?

Comment (spacedmonkey) [reply assets/src/dashboard/app/serializers/stories.js]: Nope

https://github.com/google/web-stories-wp/blob/0de09fdba2f5e96dce3d7467a5bf3568f61a8849/assets/src/edit-story/app/story/effects/useLoadStory.js#L89

https://github.com/google/web-stories-wp/blob/0de09fdba2f5e96dce3d7467a5bf3568f61a8849/assets/src/edit-story/components/postLock/postLock.js#L86

I tested avatar disabling in dashboard in original PR. I think something changed to break this. Either way, it is a simple fix.

**Review by swissspidy — APPROVED** [review]
Works as expected 👍 

Possible to add some tests?

Also, I think the QA instructions needs a little expanding to mention getting a lock first in a separate browser etc.

**Review by swissspidy — APPROVED** [review]
