### PR TITLE
Storybook: Fix Circular Dependencies and fast refresh

### LINKED ISSUE #10788: Storybook: Hot reload broken
## Bug Description

Hot reloading does not work post webpack 5 upgrade: #5792 

## Expected Behaviour

hot reloading should work with storybook + webpack 5.

## Steps to Reproduce

1. run storybook with `npm run storybook`
2. edit code that is used in any story
3. see warnings in logs.

## Screenshots

Saving a file that storybook is watching will flood the console with warnings like this:
image

## Additional Context

[Possibly a webpack issue](https://github.com/webpack-contrib/webpack-hot-middleware/issues/390). Verified that [this update](https://github.com/webpack-contrib/webpack-hot-middleware/issues/390#issuecomment-989805123) _sort of_ fixes the problem, but it involves updating `webpack-hot-middleware`. It's pretty slow and ends up logging other stuff to the console.
image

### PR DESCRIPTION
**Pull request by samwhale**
## Context

After #6304, storybook fast refresh stopped working. Saw some strange warnings, but ultimately think that it's due to circular dependencies.

This PR is a try at fixing those

[This issue on github looks similar to our problem](https://github.com/storybookjs/storybook/issues/13243)

## Summary

1. Fixes storybook fast refresh
<details>
<summary>2. Fixes these circular dependencies found in `/packages`:</summary>

```bash

Error: Circular dependency detected:
packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js
Error: Circular dependency detected:
packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js
Error: Circular dependency detected:
packages/story-editor/src/app/highlights/quickActions/index.js -> packages/story-editor/src/app/highlights/quickActions/useQuickActions.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/quickActions/index.js
Error: Circular dependency detected:
packages/story-editor/src/app/highlights/quickActions/useQuickActions.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/quickActions/index.js -> packages/story-editor/src/app/highlights/quickActions/useQuickActions.js
Error: Circular dependency detected:
packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js
Error: Circular dependency detected:
packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js
Error: Circular dependency detected:
packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js
Error: Circular dependency detected:
packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js
Error: Circular dependency detected:
packages/story-editor/src/components/canvas/pageSideMenu.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/canvas/pageSideMenu.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooSmall.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooSmall.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/imageElementMissingAlt.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/imageElementMissingAlt.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/imageElementResolution.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/imageElementResolution.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/component.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/index.js -> packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/component.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/index.js -> packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/component.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/pageBackgroundLowTextContrast/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/pageTooLittleText.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/pageTooLittleText.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/pageTooManyLinks.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/pageTooManyLinks.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/pageTooMuchText.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/pageTooMuchText.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/publisherLogoMissing.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/publisherLogoMissing.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/publisherLogoSize.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/publisherLogoSize.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/shared/index.js -> packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js -> packages/story-editor/src/components/checklistCard/index.js -> packages/story-editor/src/components/checklistCard/checklistCard.js -> packages/story-editor/src/components/checklist/checks/shared/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js -> packages/story-editor/src/components/checklistCard/index.js -> packages/story-editor/src/components/checklistCard/checklistCard.js -> packages/story-editor/src/components/checklist/checks/shared/index.js -> packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/shared/videoChecklistCard.js -> packages/story-editor/src/components/checklistCard/index.js -> packages/story-editor/src/components/checklistCard/checklistCard.js -> packages/story-editor/src/components/checklist/checks/shared/index.js -> packages/story-editor/src/components/checklist/checks/shared/videoChecklistCard.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/storyMissingExcerpt.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/storyMissingExcerpt.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/storyMissingTitle.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/storyMissingTitle.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/storyPosterAttached.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/storyPosterAttached.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/storyPosterSize.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/storyPosterSize.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/storyTitleLength.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/storyTitleLength.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/textElementFontSizeTooSmall.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/textElementFontSizeTooSmall.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoElementLength.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoElementLength.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoElementMissingCaptions.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoElementMissingCaptions.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoElementMissingDescription.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoElementMissingDescription.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoElementMissingPoster.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoElementMissingPoster.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoElementResolution.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoElementResolution.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/checks/videoOptimization.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/videoOptimization.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/checklist/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklistCard/checklistCard.js -> packages/story-editor/src/components/checklist/checks/shared/index.js -> packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js -> packages/story-editor/src/components/checklistCard/index.js -> packages/story-editor/src/components/checklistCard/checklistCard.js
Error: Circular dependency detected:
packages/story-editor/src/components/checklistCard/index.js -> packages/story-editor/src/components/checklistCard/checklistCard.js -> packages/story-editor/src/components/checklist/checks/shared/index.js -> packages/story-editor/src/components/checklist/checks/shared/thumbnailWrapper.js -> packages/story-editor/src/components/checklistCard/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/basicColorList.js -> packages/story-editor/src/components/colorPicker/colorAdd.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/basicColorPicker.js -> packages/story-editor/src/components/colorPicker/basicColorList.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/basicColorPicker.js -> packages/story-editor/src/components/colorPicker/header.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/basicColorPicker.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/colorAdd.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/basicColorPicker.js -> packages/story-editor/src/components/colorPicker/basicColorList.js -> packages/story-editor/src/components/colorPicker/colorAdd.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/header.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/header.js
Error: Circular dependency detected:
packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/multiple.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/multiple.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/shape.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/shape.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/sticker.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/sticker.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/text.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/text.js
Error: Circular dependency detected:
packages/story-editor/src/components/floatingMenu/menus/video.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/video.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js
Error: Circular dependency detected:
packages/story-editor/src/components/footer/secondaryMenu.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/secondaryMenu.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/color/colorInput.js -> packages/story-editor/src/components/colorPicker/index.js -> packages/story-editor/src/components/colorPicker/colorPicker.js -> packages/story-editor/src/components/colorPicker/customColorPicker.js -> packages/story-editor/src/components/colorPicker/currentColorPicker.js -> packages/story-editor/src/components/colorPicker/editablePreview.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/colorInput.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/color/opacityInput.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/form/color/opacityInput.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/filterToggle/filterToggle.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/filterToggle/index.js -> packages/story-editor/src/components/form/filterToggle/filterToggle.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/filterToggle/index.js -> packages/story-editor/src/components/form/filterToggle/filterToggle.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/filterToggle/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/link.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/link.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/select/index.js -> packages/story-editor/src/components/form/select/select.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/select/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/form/select/select.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/select/index.js -> packages/story-editor/src/components/form/select/select.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/media3p/index.js -> packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js -> packages/story-editor/src/components/library/panes/media/media3p/providerPanel.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/media3p/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js -> packages/story-editor/src/components/library/panes/media/media3p/providerPanel.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/media3p/index.js -> packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/media/media3p/providerPanel.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/media3p/index.js -> packages/story-editor/src/components/library/panes/media/media3p/media3pPane.js -> packages/story-editor/src/components/library/panes/media/media3p/providerPanel.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/shapes/index.js -> packages/story-editor/src/components/library/panes/shapes/shapesPane.js -> packages/story-editor/src/components/library/panes/shapes/shapePreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/shapes/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/shapes/shapePreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/shapes/index.js -> packages/story-editor/src/components/library/panes/shapes/shapesPane.js -> packages/story-editor/src/components/library/panes/shapes/shapePreview.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/shapes/shapesPane.js -> packages/story-editor/src/components/library/panes/shapes/shapePreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/shapes/index.js -> packages/story-editor/src/components/library/panes/shapes/shapesPane.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/shapes/stickerPreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/shapes/index.js -> packages/story-editor/src/components/library/panes/shapes/shapesPane.js -> packages/story-editor/src/components/library/panes/shapes/stickerPreview.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/fontPreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/fontPreview.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/fontPreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/fontPreview.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/textSets/textSet.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSetsPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSets.js -> packages/story-editor/src/components/library/panes/text/textSets/textSet.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/textSets/textSets.js -> packages/story-editor/src/components/library/panes/text/textSets/textSet.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSetsPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSets.js
Error: Circular dependency detected:
packages/story-editor/src/components/library/panes/text/textSets/textSetsPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSets.js -> packages/story-editor/src/components/library/panes/text/textSets/textSet.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/floatingMenu/index.js -> packages/story-editor/src/components/floatingMenu/layer.js -> packages/story-editor/src/components/floatingMenu/menu.js -> packages/story-editor/src/components/floatingMenu/menus/index.js -> packages/story-editor/src/components/floatingMenu/menus/selector.js -> packages/story-editor/src/components/floatingMenu/menus/image.js -> packages/story-editor/src/components/floatingMenu/elements/index.js -> packages/story-editor/src/components/floatingMenu/elements/more.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/text/index.js -> packages/story-editor/src/components/library/panes/text/textPane.js -> packages/story-editor/src/components/library/panes/text/textSets/textSetsPane.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/captions/captions.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/captions/index.js -> packages/story-editor/src/components/panels/design/captions/captions.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/captions/index.js -> packages/story-editor/src/components/panels/design/captions/captions.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/captions/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/imageAccessibility/index.js -> packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/imageAccessibility/index.js -> packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/imageAccessibility/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/animation/index.js -> packages/story-editor/src/components/panels/design/animation/animation.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/link/index.js -> packages/story-editor/src/components/panels/design/link/link.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/link/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/link/link.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/link/index.js -> packages/story-editor/src/components/panels/design/link/link.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/pageBackground/index.js -> packages/story-editor/src/components/panels/design/pageBackground/pageBackground.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/pageBackground/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/pageBackground/pageBackground.js -> packages/story-editor/src/components/checklist/index.js -> packages/story-editor/src/components/checklist/checks/index.js -> packages/story-editor/src/components/checklist/checks/elementLinkTappableRegionTooBig.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/pageBackground/index.js -> packages/story-editor/src/components/panels/design/pageBackground/pageBackground.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/shapeStyle/index.js -> packages/story-editor/src/components/panels/design/shapeStyle/shapeStyle.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/shapeStyle/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/shapeStyle/shapeStyle.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/shapeStyle/index.js -> packages/story-editor/src/components/panels/design/shapeStyle/shapeStyle.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/textStyle/index.js -> packages/story-editor/src/components/panels/design/textStyle/textStyle.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/textStyle/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/textStyle/textStyle.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/textStyle/index.js -> packages/story-editor/src/components/panels/design/textStyle/textStyle.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/videoAccessibility/index.js -> packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/videoAccessibility/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js -> packages/story-editor/src/app/highlights/index.js -> packages/story-editor/src/app/highlights/provider.js -> packages/story-editor/src/app/highlights/states.js -> packages/story-editor/src/components/library/constants.js -> packages/story-editor/src/components/library/panes/media/local/index.js -> packages/story-editor/src/components/library/panes/media/local/mediaPane.js -> packages/story-editor/src/components/library/panes/media/common/paginatedMediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaGallery.js -> packages/story-editor/src/components/library/panes/media/common/mediaElement.js -> packages/story-editor/src/components/library/panes/media/common/innerElement.js -> packages/story-editor/src/components/library/panes/shared/libraryMoveable.js -> packages/story-editor/src/components/canvas/index.js -> packages/story-editor/src/components/canvas/canvas.js -> packages/story-editor/src/components/canvas/canvasLayout.js -> packages/story-editor/src/components/canvas/navLayer.js -> packages/story-editor/src/components/footer/index.js -> packages/story-editor/src/components/footer/footer.js -> packages/story-editor/src/components/footer/footerLayout.js -> packages/story-editor/src/components/footer/primaryMenu.js -> packages/story-editor/src/components/footer/layers/index.js -> packages/story-editor/src/components/footer/layers/layers.js -> packages/story-editor/src/components/panels/design/index.js -> packages/story-editor/src/components/panels/design/videoAccessibility/index.js -> packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/panels/shared/index.js
Error: Circular dependency detected:
packages/story-editor/src/components/panels/shared/linkRelations.js -> packages/story-editor/src/components/form/index.js -> packages/story-editor/src/components/form/color/index.js -> packages/story-editor/src/components/form/color/color.js -> packages/story-editor/src/components/panels/shared/index.js -> packages/story-editor/src/components/panels/shared/linkRelations.js
Error: Circular dependency detected:
packages/wp-dashboard/src/components/editorSettings/editorSettings.js -> packages/wp-dashboard/src/effects/index.js -> packages/wp-dashboard/src/effects/useMediaOptimization.js -> packages/wp-dashboard/src/components/editorSettings/index.js -> packages/wp-dashboard/src/components/editorSettings/editorSettings.js
Error: Circular dependency detected:
packages/wp-dashboard/src/components/editorSettings/index.js -> packages/wp-dashboard/src/components/editorSettings/editorSettings.js -> packages/wp-dashboard/src/effects/index.js -> packages/wp-dashboard/src/effects/useMediaOptimization.js -> packages/wp-dashboard/src/components/editorSettings/index.js
Error: Circular dependency detected:
packages/wp-dashboard/src/effects/index.js -> packages/wp-dashboard/src/effects/useMediaOptimization.js -> packages/wp-dashboard/src/components/editorSettings/index.js -> packages/wp-dashboard/src/components/editorSettings/editorSettings.js -> packages/wp-dashboard/src/effects/index.js
Error: Circular dependency detected:
packages/wp-dashboard/src/effects/useMediaOptimization.js -> packages/wp-dashboard/src/components/editorSettings/index.js -> packages/wp-dashboard/src/components/editorSettings/editorSettings.js -> packages/wp-dashboard/src/effects/index.js -> packages/wp-dashboard/src/effects/useMediaOptimization.js
Error: Circular dependency detected:
packages/wp-dashboard/src/effects/useTelemetryOptIn.js -> packages/wp-dashboard/src/components/editorSettings/index.js -> packages/wp-dashboard/src/components/editorSettings/editorSettings.js -> packages/wp-dashboard/src/effects/index.js -> packages/wp-dashboard/src/effects/useTelemetryOptIn.js
```

</details>

## Relevant Technical Choices

Adding [webpack's `CircularDependencyPlugin`](https://www.npmjs.com/package/circular-dependency-plugin). Should help to track future circular deps.

## To-do

- [ ] Fix broken karma tests

## User-facing changes

n/a

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. App should still work - no functional changes.
2. Run storybook
3. Go to a story editor story. Edit something in the story or related component. After saving, wait for a little while after storybook has rebuilt. Should see the update in browser and no warnings in the console titled `Ignored an update to an unaccepted module`
4. Go to a dashboard story. Edit something in the story or related component. After saving, wait for a little while after storybook has rebuilt. Should see the update in browser and no warnings in the console titled `Ignored an update to an unaccepted module`
5. Go to a design system story. Edit something in the story or related component. After saving, wait for a little while after storybook has rebuilt. Should see the update in browser and no warnings in the console titled `Ignored an update to an unaccepted module`

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10788

### CODE REVIEW

File: .storybook/preview.js [hunk 1]
```diff
@@ -17,28 +17,28 @@
...
 import {
   DashboardGlobalStyle,
   DashboardKeyboardOnlyOutline,
   ConfigProvider as DashboardConfigProvider,
   ApiProvider,
 } from '@googleforcreators/dashboard';
+import {
+  GlobalStyle,
+  EditorConfigProvider,
+} from '@googleforcreators/story-editor';
```
Comment (samwhale) [inline .storybook/preview.js]: The problem continues - fast refresh does not work if this import exists.

Have fixed circular dependencies in all packages, but maybe there are circular dependencies still from this file? Not sure atm, but will keep digging.

They don't show up in the webpack circular dependency plugin, so wondering if it's due to something different.

File: .storybook/preview.js [hunk 2]
```diff
@@ -17,28 +17,29 @@
...
+// Disable reason:
+// Importing from the dashboard and story editor roots break fast refresh in storybook.
+// Prevented by importing the necessary providers and configs directly.
+/* eslint-disable import/no-relative-packages */
+import { GlobalStyle as DashboardGlobalStyle } from '../packages/dashboard/src/theme';
+import DashboardKeyboardOnlyOutline from '../packages/dashboard/src/utils/keyboardOnlyOutline';
+import DashboardConfigProvider from '../packages/dashboard/src/app/config/configProvider';
+import ApiProvider from '../packages/dashboard/src/app/api/apiProvider';
+import EditorConfigProvider from '../packages/story-editor/src/app/config/configProvider';
+/* eslint-enable import/no-relative-packages */
```
Comment (samwhale) [inline .storybook/preview.js:43]: The story editor and dashboard stories were not fast refreshing, and were logging warnings like this:

|Dashboard|Story Editor|
|--|--|
|image|image|

Importing directly from the modules here removes these warnings and fixes fast refresh.

Got the idea from [this thread](https://github.com/storybookjs/storybook/issues/13243)

File: packages/story-editor/src/components/library/paneIds.js [hunk 3]
```diff
@@ -14,5 +14,11 @@
...
-export { default as ThumbnailWrapper } from './thumbnailWrapper';
-export { default as VideoChecklistCard } from './videoChecklistCard';
+export const PANE_IDS = {
+  MEDIA: 'media',
+  MEDIA_3P: 'media3p',
+  TEXT: 'text',
+  SHAPES: 'shapes',
+  ELEMENTS: 'elements',
+  PAGE_TEMPLATES: 'pageTemplates',
+};
```
Comment (samwhale) [inline packages/story-editor/src/components/library/paneIds.js:24]: This is a weird diff. Two things happened here:

1. Broke a loop that involved the checklist cards and the thumbnail wrapper + video checklist cards: 566a1b3 and 083b38b. The file in red was deleted.
2. Broke a loop that involved the highlights provider: c5dd4c68. The file in green was added and [these imports](https://github.com/GoogleForCreators/web-stories-wp/pull/11161/files#diff-ed4b4a7647ac8a4bb4a9d16aaf241422d72b46cf0fc6af9bd2211cbb7bdc1c55L20-L25) were updated

These two are not related.

**Review by BrittanyIRL — APPROVED** [review]
Wow, great job deducing what was causing this. Thanks for the explanation. Tested locally and fast refresh for storybook is back. Not seeing any errors there and app works as expected locally as well.

File: .storybook/preview.js (hunk 2 above)
Comment (swissspidy) [reply .storybook/preview.js:43]: Interesting 🤔 

I guess storybook doesn't like npm workspaces where the packages are referenced from `node_modules` but actually symlinked.

**Review by swissspidy — APPROVED** [review]
Indeed, kudos for going down this rabbit hole!

The bundle size improvement is also a nice side effect

File: .storybook/preview.js (hunk 2 above)
Comment (samwhale) [reply .storybook/preview.js:43]: Maybe 🤷  but seems like finding these imports using relative paths seems to fix it. Luckily this change can be scoped to this one file.
