### PR TITLE
Send fake event when adding new element to page

### LINKED ISSUE #511: Delete key sometimes does not delete elements
## Bug Description
Sometimes when elements are inserted/added, the user currently has to unselect them and re-select them for the delete to trigger

## Expected Behaviour

Backspace key should delete the element whenever the element is in focus

## Steps to Reproduce

Insert an element from the media library and attempt to delete it (doesn't work), unfocus/re-focus and try deleting again (works).

### PR DESCRIPTION
**Pull request by barklund**
This fixes one case of #738 (and fixes #511).

As the canvas already [has some logic in place to detect focus changes and restore focus to currently selected element](https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/components/canvas/useCanvasKeys.js#L44-L68), I wanted to reuse that logic when adding a new element.

So I simply send a fake `focusout` event whenever a new element is added - and it magically works! It's very hacky, but hey 🤷‍♂.

It works both for:

* clicking an element in the media library
* dragging an element from the media library
* dragging an element from the local computer to the editor directly on page

### CODE REVIEW

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 1]
```diff
@@ -83,6 +83,11 @@ function useInsertElement() {
           }
         }, 0);
       }
+      // When done, send fake focusout event to document to force focus to new element
+      setTimeout(() => {
+        const evt = new window.FocusEvent('focusout');
+        window.document.dispatchEvent(evt);
+      }, 1);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/useInsertElement.js]: Why not just `0`?

File: assets/src/edit-story/components/canvas/useInsertElement.js [hunk 2]
```diff
@@ -83,6 +83,11 @@ function useInsertElement() {
           }
         }, 0);
       }
+      // When done, send fake focusout event to document to force focus to new element
+      setTimeout(() => {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/useInsertElement.js]: As much as I don't like setTimeout, but IMHO we won't get away from some ugliness with focus. My only request is to put this into a separate hook: `canvas/useFocusCanvas` and just call it here.

**Review by dvoytenko — APPROVED** [review]
LGTM with one request

**Review by wassgha — APPROVED** [review]

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/useInsertElement.js]: To be after the above `setTimeout`? Okay, I'll remove the argument (0 is default).

File: assets/src/edit-story/components/canvas/useInsertElement.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/useInsertElement.js]: Makes sense. Done in 33c21ddc and ef683a97.

File: assets/src/edit-story/components/canvas/useFocusCanvas.js [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import { useCallback } from 'react';
+
+function useFocusCanvas() {
+  const focusCanvas = useCallback(() => {
+    setTimeout(() => {
+      const evt = new window.FocusEvent('focusout');
+      window.document.dispatchEvent(evt);
+    });
+  }, []);
+  return focusCanvas();
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/useFocusCanvas.js]: Did you mean to call this function here? I'd just expect `return focusCanvas;`...

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/canvas/useFocusCanvas.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/useFocusCanvas.js]: 🤦‍♂

**Review by dvoytenko — APPROVED** [review]

**Comment by swissspidy** [comment]
Added to the alpha branch 👍
