### PR TITLE
Bug: Scroll To Top Button Visible When It Shouldn't Be

### LINKED ISSUE #8566: Dashboard: Inconsistent scroll to top button visibility
## Bug Description

(From Bugbash 1.10 reported by @spacedmonkey) 

After clicking up the scroll up button. It scroll up to the top and remains. But then I scroll with two fingers on my mac to top, once it gets to the top, the button is hidden. The behaviour should be same in both places. 

## Expected Behaviour

Scroll to top button should be hidden when user clicks on it and goes to top of page regardless of how it was clicked.

If a keyboard user hits 'enter' on the scroll to top, the button should be hidden once it's out of focus. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Bug found in bugbash 1.10

## Summary

Depending on how you click the scroll to top button in the dashboard it'll stay visible (because focus is retained). This was originally done to preserve sanity for using a keyboard because if you tab to the scroll to top button while at the top of the page your focus gets lost and if you tab to it while it is visible, click it, and then it would disappear you'd also get lost and sent back to the very top of the DOM which is very annoying because of all the WordPress nav you have to get through to go back to the Dashboard. 

History lesson as context, TLDR we can do better :) 

## Relevant Technical Choices

- Hide the scroll to top button when it's not visible so that it's not focusable. [Today I learned that not all browsers treat `aria-hidden` to mean don't focus](https://accessibilityinsights.io/info-examples/web/aria-hidden-focus/). Now we don't have the problem I described above where you tab at the top of the view and get lost because the button is invisible. 
-  Update button to be hidden after click regardless of cursor or keyboard. 
-  Set a new ref in the layout provider to find the first focusable element in the Dashboard. When `scrollToTop` is fired, focus there instead of the top of the grid - feels more consistent. We could possibly return it to the grid focus if we update to not use the same focus pattern as the grid view in the editor, for now focusing the first item in the Dashboard that's focusable seems more robust and uniform.

## User-facing changes

| Cursor Demo | Keyboard Demo | 
| --- | --- |
| scroll | tab |

Fun little bonus here, fixes an issue aXe has been grumpy about!

Screen Shot 2021-08-03 at 12 43 21 PM

## Testing Instructions

- Go to dashboard, scroll a bit and see the scroll to top button appear. Click it, see it goes away. 
- Navigate the grid with keyboard - as a refresher, tab to the grid (which is a list) and then use your keyboard arrows to navigate the actual grid items (list items). Once you've scrolled the page a bit, hit tab to escape the grid and land on the scroll to top button. Clicking this button will now refocus you to the first button or link (create new story) available on the dashboard. 
- Same behavior should be apparent for Explore Templates
- Should be consistent across browsers. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8566

### CODE REVIEW

File: assets/src/dashboard/components/layout/provider.js [hunk 1]
```diff
@@ -16,23 +16,32 @@
...
+  }, []);
+
   const scrollToTop = useCallback(() => {
-    const scrollFrameEl = scrollFrameRef.current;
     document.documentElement?.scrollTo?.({
       top: 0,
       behavior: 'smooth',
     });
-    scrollFrameEl?.children[0]?.focus();
+    firstFocusableContentRef.current?.focus();
```
Comment (maxyinger) [inline assets/src/dashboard/components/layout/provider.js]: wondering if it's better to grab the first focusable child at the time you call the scrollToTop function in case it ever changes throughout the lifecycle of the dashboard? not sure if this ever actually happens tho so might not add benefit 🤷 
```
  useEffect(() => {
    firstFocusableContentRef.current = document
      .getElementById('web-stories-dashboard');
  }, []);

  const scrollToTop = useCallback(() => {
    ...
    firstFocusableContentRef.current?.querySelector(['button', 'a'])?.focus();
    ...
```

**Review by maxyinger — APPROVED** [review]
Looks good!

I do have a `FOCUSABLE_SELECTORS` constant in the `edit-story/constants` but might be more pain than it's worth hoisting that up to the design-system for use in both packages.

File: assets/src/dashboard/components/layout/provider.js (hunk 1 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/components/layout/provider.js]: It only changes when the view is updated (say, from stories to templates) which at that point the useEffect will run and update.  Pretty sure this is a 6 of 12, half a dozen sitch. Happy to update if you feel it reads easier!

Comment (maxyinger) [reply assets/src/dashboard/components/layout/provider.js]: nope just wanted to verify. makes sense! no need to change

**Comment by BrittanyIRL** [comment]
> I do have a `FOCUSABLE_SELECTORS` constant in the `edit-story/constants` but might be more pain than it's worth hoisting that up to the design-system for use in both packages.

📝  - let's keep an eye on if we need it anywhere else in the dashboard too and then move it, feels a touch excessive for just this one spot, imo.

**Review by samwhale — APPROVED** [review]
