### PR TITLE
Absolute positioning of elements (Tooltips, Color picker, Link hints) + fixes

### LINKED ISSUE #540: Wrong color picker placement
## Bug Description

The color picker opens next to the color input in question when clicked.

However, if the color input is near the bottom of the viewport, the color picker should stay inside the viewport and not be partially hidden.

Furthermore, when the design panel is scrolled due to many options, the color picker does not follow the color input and can suddenly be far away.

## Expected Behaviour

Color picker should follow color input, but stay inside viewport.

## Steps to Reproduce

1.  Make a small viewport
2. Select a text element
3. Collapse the layers panel
4. Scroll the design panel, so text color is at the bottom of the visible panel
5. Click to open the color picker and see that it's partially hidden.
6. Scroll the design panel so text color input moves up and see that the color picker is not moving with it.

## Screenshots

| Initial opening  | Actual view after scroll | Expected view after scroll |
| ------------- | ------------- | ------------- |
| Screen Shot 2020-03-11 at 4 13 02 PM | Screen Shot 2020-03-11 at 4 13 09 PM |   Screen Shot 2020-03-11 at 4 13 18 PM |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #633: Link overlays in workspace should not be rotated
## Bug Description

Link overlays in the workspace get rotated, but probably shouldn't.

## Expected Behaviour

1. The link overlay should not rotate in the workspace.
2. The link overlay should not rotate in the final story (requires wrapping the element in a non-transformed wrapper div or something).

## Steps to Reproduce

Rotate an element. Add a link. Observe rotated link box.

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #731: Cleanup scrollbar UX in the visible mode
## Feature Description

When a mouse is connected on MacOS, the browser shows all the scrollbars. This mode can be triggered manually as "Scrollbar behavior" in MacOS settings like this:

The editor will show scrollbars which could be jarring.

The scrollbars standout in the color scheme:

Sometimes scrollbars get stacked up on top of each other making it hard to tell them apart:

Sometimes a presence of a scrollbar misaligns the UI, as is the case with some of the chevrons here:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #961: Colour Picker is Cutoff
## Bug Description

The Colour  picker is cut off
image

## Expected Behaviour

1. Colour Picker box should not be cut off. 
2. Colour Picker should move as you scroll in the design panel

## Steps to Reproduce

1. Add a textbox
2. scroll down in the design panel so that the text colour picker is at the bottom or barely showing
3. open the colour picker
4. Notice the colour picker box is cut off and doesn't move as you scroll up in the design panel

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by wassgha**
Closes #540 
Closes #633 
Closes #516
Closes #731  
Closes #961
Closes #1062

| Scrolling color picker  | New tooltips (scroll resilient) | Rotation-aware tooltips |
| ------------- | ------------- | ------------- |
| Scrolling color picker  | Tooltips  |  Rotating link tooltips |

Experimented with either using Popper or our own Popup component for absolutely positioning tooltips and other elements like the color/date pickers. Popper had a 2% bundle size increase (**Δ27Kb**), so I implemented my own positioning logic inside `Popup` for **Δ<1.5Kb**!

### Changes
- Adds a `placement` parameter to `Popup` which takes values of `top`, `left`, `right`, `bottom` as well as aligned variation of the previous values (e.g. `top-start`, `top` (centered) or `top-end`).
- Uses the `Popup` element to fix the alignment of the color picker when scrolling (deprecates the `Sidebar` component)
- Uses the `Popup` element to fix the link tooltip being in the wrong position when the window is scrolled/resized
- Adds more tooltips (for the design panel) as shown in Figma
- Adds a storybook story for the `Popup` component
- Various minor stylistic tweaks of the scrollbar to prevent it from resizing content (the scrollbar is now overlaid on top of the container.
- Fixes overflowing design panel where the alignment toggles did not fit in the smaller breakpoint (adds a horizontal scroll bar, not ideal but works)

### CODE REVIEW

File: assets/src/edit-story/app/layout/index.js [hunk 1]
```diff
@@ -18,6 +18,7 @@
  * External dependencies
```
Comment (wassgha) [inline assets/src/edit-story/app/layout/index.js]: Changes in this file are a bit unrelated, but contribute to less content shifting in the design panel by having the scroll bar be absolutely positioned.

File: package.json [hunk 2]
```diff
@@ -20,6 +20,7 @@
     "url": "https://github.com/google/web-stories-wp/issues"
   },
   "dependencies": {
+    "@popperjs/core": "^2.2.1",
```
Comment (swissspidy) [inline package.json]: Can be removed now that it's not being used?

**Comment by miina** [comment]
@wassgha Looks like this will also supersede #1062 and fix #961?

**Comment by wassgha** [comment]
@miina It partially fixes #961 by making the color picker scroll with the design panel but it doesn't prevent the overflow, however, I can incorporate your PR's min/max trick into this.

**Comment by miina** [comment]
@wassgha I guess it makes more sense to bring over since your PR seems to remove using the Sidebar component fully anyway, resolving merge conflicts would probably be more trouble than bringing that over.
(Assuming that this PR is expected to get merged for alpha)

**Comment by wassgha** [comment]
@miina Added :)) 

Limited color picker

File: assets/src/edit-story/components/form/color/colorPreview.js [hunk 3]
```diff
@@ -161,35 +142,54 @@ function ColorPreview({
...
+      >
+        <ColorPicker
+          color={isMultiple ? null : value}
+          onChange={onChange}
+          hasGradient={hasGradient}
+          hasOpacity={hasOpacity}
+          onClose={(evt) => {
+            setPickerOpen(false);
+            evt.stopPropagation();
+            evt.preventDefault();
```
Comment (merapi) [inline assets/src/edit-story/components/form/color/colorPreview.js]: Out of curiosity: why do we need them?

**Review by merapi — APPROVED** [review]
I tried to break it - no luck. 👍

File: assets/src/edit-story/components/form/color/colorPreview.js [hunk 4]
```diff
@@ -124,10 +103,12 @@ function ColorPreview({
   const editLabel = __('Edit', 'web-stories');
   const inputLabel = __('Enter', 'web-stories');
 
+  const togglePickerOpen = () => setPickerOpen(() => true);
```
Comment (miina) [inline assets/src/edit-story/components/form/color/colorPreview.js]: Should this be named something else if it's always opening and not a toggle?
Or should it actually close when the button is clicked again? Wondering what's the expected behavior here. As I understand then the focus out handling is closing the calendar when clicking on the button, and right after, the `togglePickerOpen` opens it again, so it would be closing and then opening again right away when clicking the button while the color picker is open already before? Perhaps that's expected though :)

Comment (miina) [reply assets/src/edit-story/components/form/color/colorPreview.js]: Okay, just tested it out.
It looks like there's a slight inconsistency: when clicking the button while the color picker is open, it blinks, however, when choosing a color first and then clicking the button again, it closes the color picker:
color picker

Also, as can be seen in the gif, the color picker is positioned partly on top of the sidebar currently. Looks like it should be right next to it but not covering, by design.

File: assets/src/edit-story/components/popup/index.js [hunk 5]
```diff
@@ -19,58 +19,168 @@
...
+    return '';
+  }
+  return `transform: ${xTransforms ? `translateX(${xTransforms})` : ``} ${
+    yTransforms ? `translateY(${yTransforms})` : ``
+  };`;
+}
+
+function getXOffset(placement, spacing = 0, anchorRect, bodyRect) {
+  switch (placement) {
+    case 'bottom-start':
```
Comment (miina) [inline assets/src/edit-story/components/popup/index.js]: Perhaps it would be good to add all these as constants?

File: assets/src/edit-story/components/panels/alignment/alignment.js [hunk 6]
```diff
@@ -54,6 +54,8 @@ const ElementRow = styled.div`
   align-items: center;
   padding: 10px 20px;
   border-top: 1px solid ${({ theme }) => theme.colors.bg.v9};
+  overflow-y: overlay;
+  overflow-x: overlay;
```
Comment (miina) [inline assets/src/edit-story/components/panels/alignment/alignment.js]: Is there a reason why just not to use `overflow`? Also, isn't `overlay` deprecated / not supported by FF?

File: assets/src/edit-story/components/popup/index.js [hunk 7]
```diff
@@ -19,58 +19,168 @@
...
+    case 'left':
+    case 'left-start':
+    case 'left-end':
+      return bodyRect.left + anchorRect.left - spacing;
+    case 'bottom-end':
+    case 'top-end':
+    case 'right':
+    case 'right-start':
+    case 'right-end':
+      return bodyRect.left + anchorRect.left + anchorRect.width + spacing;
```
Comment (miina) [inline assets/src/edit-story/components/popup/index.js]: Should probably ensure that the popup wouldn't be out of the screen from the left-right side, too?

Comment (miina) [reply assets/src/edit-story/components/popup/index.js]: Ah, looks like it might be resolved below already. _Will test in a bit_

File: assets/src/edit-story/components/popup/test/popup.js [hunk 8]
```diff
@@ -44,7 +44,6 @@ describe('Popup', () => {
 
     const popup = getByText('Hello World!');
     expect(popup).toBeDefined();
-    expect(popup).toHaveAttribute('width', '270');
```
Comment (miina) [inline assets/src/edit-story/components/popup/test/popup.js:37]: Could we perhaps add a new test with some params for it, now when it supports different positioning options.

File: assets/src/edit-story/components/tooltip/index.js [hunk 9]
```diff
@@ -70,84 +52,56 @@ const Tooltip = styled.div`
...
+  box-shadow: 0px 6px 10px ${({ theme }) => rgba(theme.colors.bg.v0, 0.1)};
+  ${({ placement, theme }) => {
+    switch (placement) {
+      case 'top':
+      case 'top-start':
+      case 'top-end':
+        return `
+          bottom: -6px;
+          border-top: 6px solid ${theme.colors.bg.v0};
+          border-left: 6px solid transparent;
```
Comment (miina) [inline assets/src/edit-story/components/tooltip/index.js]: Could the `6x solid transparent` be a constant perhaps?

**Review by miina — CHANGES_REQUESTED** [review]
Left some notes + 3 issues found that would be good to resolve before merging:
1. Console error when using Calendar in Document tab:
Screenshot 2020-04-07 at 14 05 53
Screenshot 2020-04-07 at 14 05 46

2. Tooltip goes out of the screen:
Screenshot 2020-04-07 at 14 13 51

3. Color picker partly on the sidebar:
Screenshot 2020-04-07 at 14 23 52

File: assets/src/edit-story/components/canvas/displayElement.js [hunk 10]
```diff
@@ -139,7 +139,7 @@ function DisplayElement({ element, previewMode, page }) {
 DisplayElement.propTypes = {
   previewMode: PropTypes.bool,
   element: StoryPropTypes.element.isRequired,
-  page: StoryPropTypes.page.isRequired,
+  page: StoryPropTypes.page,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/displayElement.js:142]: Can an element exist w/o a page?

File: assets/src/edit-story/components/canvas/frameElement.js [hunk 11]
```diff
@@ -85,32 +87,47 @@ function FrameElement({ element }) {
   const box = getBox(element);
   const isBackground = currentPage?.backgroundElementId === id;
 
+  useTransformHandler(id, (transform) => {
+    if (
+      transform &&
+      [transform.translate, transform.resize, transform.rotate].some(
+        (t) => typeof t !== 'undefined'
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/frameElement.js]: `t !== undefined`? Otherwise, maybe not for now, but we likely need to refactor to make simpler. What the "transform handler" does here is works with intermediate (uncommit) changes. Which could include (a) geometry updates (x/y/width/height/rotation), (b) replacement resource/element, (c) whatever. Each category should be easy, so the future API could be:

```
useIntermediateChangeHandler(id, ({transform, replacement}) => {
  if (transform) {
  }
  if (replacement) {
  }
});
```

Or it could be even more fine-grained to reduce number of `ifs`:

```
useIntermediateChangeHandler(id, 'transform', (transform) => {});
useIntermediateChangeHandler(id, 'replacement', (replacement) => {});
```

I don't think it'd be a good idea to do this in this pull request (or this phase). But if you agree - please file an issue for P1.

File: assets/src/edit-story/components/canvas/frameElement.js [hunk 12]
```diff
@@ -85,32 +87,47 @@ function FrameElement({ element }) {
...
-      }}
-      onFocus={(evt) => {
-        if (!isSelected) {
-          handleSelectElement(id, evt);
-        }
-      }}
-      tabIndex="0"
-      aria-labelledby={`layer-${id}`}
-      hasMask={isMaskable}
+    <WithLink
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/frameElement.js:97]: Does `WithLink` has no pointer events here or no real shape? Is it `display:inline`?

File: assets/src/edit-story/components/canvas/frameElement.js [hunk 13]
```diff
@@ -85,32 +87,47 @@ function FrameElement({ element }) {
...
+      element={element}
+      active={selectedElementIds.length === 1 && isSelected}
+      dragging={Boolean(activeDropTargetId)}
+      hasTransforms={hasTransforms}
```
Comment (dvoytenko) [inline assets/src/edit-story/components/canvas/frameElement.js]: Why not just put `useTransformHandler` into `WithLink`? It looks like the only reason we have it here is to pass `hasTransform` to this component.

File: assets/src/edit-story/components/colorPicker/colorPicker.js [hunk 14]
```diff
@@ -115,16 +115,19 @@ function ColorPicker({
...
-    }
-    onClose();
-  }, [onClose]);
+  const handleCloseAndRefocus = useCallback(
+    (evt) => {
+      // Ignore reason: In Jest, focus is always on document.body if not on any specific
+      // element, so it can never be falsy, as it can be in a real browser.
+
+      // istanbul ignore else
+      if (previousFocus.current) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/colorPicker/colorPicker.js:124]: The `useRef()` from above will only initialize once. So I don't think that's what we want here. It should either be switched to `createRef()` or simply do `previousFocus.current = document.activeElement`.

File: assets/src/edit-story/components/colorPicker/test/colorPicker/onclose.js [hunk 15]
```diff
@@ -41,7 +41,7 @@ describe('<ColorPicker /> as it closes', () => {
       return promise;
     });
 
-    expect(onClose).toHaveBeenCalledWith();
+    expect(onClose).toHaveBeenCalled();
```
Comment (dvoytenko) [inline assets/src/edit-story/components/colorPicker/test/colorPicker/onclose.js]: `toHaveBeenCalledWith(expect.anything())`

File: assets/src/edit-story/components/colorPicker/test/colorPicker/onclose.js [hunk 16]
```diff
@@ -61,7 +61,7 @@ describe('<ColorPicker /> as it closes', () => {
...
```
Comment (dvoytenko) [inline assets/src/edit-story/components/colorPicker/test/colorPicker/onclose.js]: ditto

File: assets/src/edit-story/components/form/color/colorPreview.js (hunk 4 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/form/color/colorPreview.js]: I agree: the name doesn't seem to reflect what it's actually doing.

File: assets/src/edit-story/components/form/color/colorPreview.js [hunk 17]
```diff
@@ -161,35 +142,54 @@ function ColorPreview({
...
+        placement={'left-start'}
+        spacing={{ x: 60 }}
+      >
+        <ColorPicker
+          color={isMultiple ? null : value}
+          onChange={onChange}
+          hasGradient={hasGradient}
+          hasOpacity={hasOpacity}
+          onClose={(evt) => {
+            setPickerOpen(false);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/color/colorPreview.js]: This seems a bit inverse. I.e. I'd expect popup to be fully in charge of open/close and the content coordinates with that internally, which would involve some sort of context. But I think we can live with this for now. Just lmk your thoughts on this.

File: assets/src/edit-story/components/form/media.js [hunk 18]
```diff
@@ -36,6 +36,7 @@ import MULTIPLE_VALUE from './multipleValue';
 
 const Container = styled.div`
   width: ${({ circle, size }) => (size && circle ? `${size}px` : '100%')};
+  min-width: ${({ circle, size }) => (size && circle ? `${size}px` : '100%')};
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/media.js:39]: What is this for given the `width` above? Is it in `display: flex`?

File: assets/src/edit-story/components/inspector/design/designInspector.js [hunk 19]
```diff
@@ -34,7 +34,8 @@ const Wrapper = styled.div`
 
 const TopPanels = styled.div`
   flex: 1 1;
-  overflow: auto;
+  overflow-y: overlay;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/inspector/design/designInspector.js]: This has been deprecated some time ago. If you still want it, please also keep the old `auto` above for cross-browser support. But I think since it's deprecated it might be best to avoid.

File: assets/src/edit-story/components/panels/shared/flipControls.js [hunk 20]
```diff
@@ -30,24 +30,29 @@ import { __ } from '@wordpress/i18n';
...
-      <Toggle
-        title={__('Flip vertically', 'web-stories')}
-        aria-label={__('Flip vertically', 'web-stories')}
-        icon={<FlipVertical />}
-        value={value.vertical === true}
-        onChange={(vertical) => onChange({ ...value, vertical })}
-      />
+      <WithTooltip title={__('Flip horizontally', 'web-stories')}>
+        <Toggle
+          title={__('Flip horizontally', 'web-stories')}
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/shared/flipControls.js]: IMHO we should just bake `WithTooltip` to be used internally inside `Toggle` component (and all similar) and use the same `title` prop for its content.

File: assets/src/edit-story/components/popup/index.js [hunk 21]
```diff
@@ -19,58 +19,168 @@
...
-        offset: {
-          x: bodyRect.right - anchorRect.right,
-          y: anchorRect.bottom,
-        },
+        offset: getOffset(placement, spacing, anchorRect, popupRect, bodyRect),
       });
-    }
-    positionPopup();
+    },
+    [containerRef, anchor, placement, spacing]
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: It looks like you construct new `spacing` for each render. You might need to use `useMemo()` above to make it stable.

File: assets/src/edit-story/components/popup/index.js [hunk 22]
```diff
@@ -19,58 +19,168 @@
...
+
+// note that we cannot use percentage values for transforms, which
+// do not work correctly for rotated elements
+function getTransforms(placement) {
+  const xTransforms = getXTransforms(placement);
+  const yTransforms = getYTransforms(placement);
+  if (!xTransforms && !yTransforms) {
+    return '';
+  }
+  return `transform: ${xTransforms ? `translateX(${xTransforms})` : ``} ${
```
Comment (dvoytenko) [inline assets/src/edit-story/components/popup/index.js]: Would this accommodate insufficient space correctly? E.g. "bottom" placement requested, but the element is at the bottom of the screen?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/components/canvas/displayElement.js (hunk 10 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/displayElement.js:142]: For testing, yes. But I don't think we should be passing in the page like this anyway. This was a quick fix for the linter to pass

Comment (dvoytenko) [reply assets/src/edit-story/components/canvas/displayElement.js:142]: For context: we did this to reduce dependencies and allow easier reuse for page preview display on the dashboard. I think this points that maybe something else is missing there w.r.t. background layer. But ok to keep this for now.

**Comment by Atomicios** [comment]
[]()

**Comment by Atomicios** [comment]
[]()

**Comment by jauyong** [comment]
Hey @wassgha do you have an update on this? #540 seems to be fixed by this PR and it is required for the current sprint and Beta

**Comment by miina** [comment]
@wassgha Note that we could still re-open https://github.com/google/web-stories-wp/pull/1062 for fixing #540 specifically in the current sprint if this PR will need some time. Let me know.

cc @jauyong

**Comment by jauyong** [comment]
Yes, #540 is part of this sprint and needs to be addressed

**Comment by wassgha** [comment]
Sorry I delayed this, I remember it introduced unnecessary re-renders that I could not pinpoint to a specific change. I'll look into it today.

File: assets/src/edit-story/components/canvas/frameElement.js (hunk 12 above)
Comment (wassgha) [reply assets/src/edit-story/components/canvas/frameElement.js:97]: It's a fragment, so no real shape

File: assets/src/edit-story/components/colorPicker/colorPicker.js (hunk 14 above)
Comment (wassgha) [reply assets/src/edit-story/components/colorPicker/colorPicker.js:124]: Hmm this is not new, are we sure about that?

**Comment by wassgha** [comment]
Ready

File: assets/src/edit-story/components/popup/index.js [hunk 23]
```diff
@@ -65,29 +66,155 @@ const Container = styled.div.attrs(({ x, y }) => ({
   }
 `;
 
-function Popup({ anchor, children, width = DEFAULT_WIDTH, isOpen }) {
+function getXTransforms(placement) {
+  // left & right
+  if (placement.startsWith('left')) {
```
Comment (swissspidy) [inline assets/src/edit-story/components/popup/index.js]: The tests currently fail because `placement` is undefined.

https://github.com/google/web-stories-wp/pull/1060/checks?check_run_id=646520216#step:8:22

**Comment by miina** [comment]
@wassgha It looks like the fonts dropdown is not the same width as the button anymore -- is that change intended?

Screenshot 2020-05-06 at 16 55 43

File: assets/src/edit-story/components/popup/index.js (hunk 22 above)
Comment (wassgha) [reply assets/src/edit-story/components/popup/index.js]: See the max/min statements above that take care of that behavior

**Comment by wassgha** [comment]
@miina added `fillWidth` and `fillHeight` attributes to allow taking the same dimensions as the anchor element

File: assets/src/edit-story/components/popup/index.js [hunk 24]
```diff
@@ -65,29 +92,166 @@ const Container = styled.div.attrs(({ x, y }) => ({
   }
 `;
 
-function Popup({ anchor, children, width = DEFAULT_WIDTH, isOpen }) {
+function getXTransforms(placement) {
```
Comment (miina) [inline assets/src/edit-story/components/popup/index.js]: Maybe create an `util.js` file for popup and move all the helpers there? Would make it possible to unit test better as well. Thoughts?

File: assets/src/edit-story/components/popup/test/popup.js [hunk 25]
```diff
@@ -34,7 +34,24 @@ describe('Popup', () => {
...
+
+    Object.values(Placement).map((placement) => {
+      const { getByText } = renderWithTheme(
+        <Popup anchor={anchor} isOpen={true} placement={placement}>
+          {`Hello ${placement}!`}
+        </Popup>
+      );
+
+      const popup = getByText(`Hello ${placement}!`);
+      expect(popup).toBeDefined();
```
Comment (miina) [inline assets/src/edit-story/components/popup/test/popup.js]: Should we test something more useful here? The placement has a default and a fallback so not sure how the placement would influence the popup not being defined.

This should perhaps test the actual placement then -- if it was set correctly.

Comment (miina) [reply assets/src/edit-story/components/popup/test/popup.js]: And also the fallback -- if there is not placement set or an incorrect placement is set for some reason.

File: assets/src/edit-story/components/tooltip/index.js [hunk 26]
```diff
@@ -163,34 +119,57 @@ function WithTooltip({
...
+        ref={ref}
+        {...props}
+      >
+        {children}
+      </Wrapper>
+      <Popup
+        anchor={ref}
+        placement={placement}
+        spacing={spacing}
+        isOpen={shown}
```
Comment (miina) [inline assets/src/edit-story/components/tooltip/index.js]: Probably shouldn't be shown if the tooltip doesn't have content (title/shortcut) set.

File: assets/src/edit-story/components/colorPicker/colorPicker.js (hunk 14 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/colorPicker/colorPicker.js:124]: Actually, no. Not sure. I think it might be returning focus to a previous element. Let's keep.

File: assets/src/edit-story/components/form/color/colorPreview.js [hunk 27]
```diff
@@ -161,36 +144,55 @@ function ColorPreview({
...
-          onBlur={handleInputBlur}
-        />
-      </Preview>
-    );
-  }
+  // Always hide color picker on unmount - note the double arrows
+  useUnmount(() => () => setPickerOpen(false));
+
+  const onClose = useCallback(() => setPickerOpen(false), []);
+  const spacing = useMemo(() => ({ x: 20 }), []);
```
Comment (dvoytenko) [inline assets/src/edit-story/components/form/color/colorPreview.js:151]: What's this for?

File: assets/src/edit-story/components/inspector/inspectorProvider.js [hunk 28]
```diff
@@ -113,6 +114,7 @@ function InspectorProvider({ children }) {
 
   const state = {
     state: {
+      inspectorRef,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/inspector/inspectorProvider.js]: WDYT if we had an agreement to place these to the `refs: {inspector: ...}` instead of `state`? Ok to skip for now.

File: assets/src/edit-story/index.js [hunk 29]
```diff
@@ -19,6 +19,7 @@
  */
 import Modal from 'react-modal';
 import { render } from 'react-dom';
+import React from 'react';
```
Comment (dvoytenko) [inline assets/src/edit-story/index.js]: Remove?

File: package.json [hunk 30]
```diff
@@ -20,7 +20,7 @@
     "url": "https://github.com/google/web-stories-wp/issues"
   },
   "dependencies": {
-    "@wordpress/api-fetch": "^3.14.0",
+    "@wordpress/api-fetch": "^3.13.1",
```
Comment (dvoytenko) [inline package.json]: Rolling back?

**Review by dvoytenko — APPROVED** [review]
LGTM on my side with a few nits. Please finish the review with others as well.

File: assets/src/edit-story/components/colorPicker/colorPicker.js (hunk 14 above)
Comment (barklund) [reply assets/src/edit-story/components/colorPicker/colorPicker.js:124]: Yes, it's returning focus to what it was just before the color picker was opened (treating it as a modal).

It's [best practice according to WAI-ARIA for modals](https://www.w3.org/TR/wai-aria-practices/#dialog_modal).

File: assets/src/edit-story/components/form/color/colorPreview.js (hunk 27 above)
Comment (wassgha) [reply assets/src/edit-story/components/form/color/colorPreview.js:151]: Hmm my understanding is that it prevents needless rerenders on the spacing object, but I might be wrong?

File: assets/src/edit-story/components/popup/test/popup.js (hunk 25 above)
Comment (wassgha) [reply assets/src/edit-story/components/popup/test/popup.js]: This test was mostly a placeholder. The issue here is that layout/boundingrect functions are unavailable in the jest environment which makes it hard to test for placement. I need to think a bit more about it but since this PR is critical, I added a TODO so that we do not block on this.

Comment (miina) [reply assets/src/edit-story/components/popup/test/popup.js]: Perhaps we should remove the tests in loop to not have the deceiving 100% test coverage for that part then?

We could leave just one test as the placeholder (instead of all the placements) + the TODO to ensure the coverage reflects the actual test coverage.

E.g. a test that adding a non-existing placement value does still render the popup which is actually useful.
And then leave the other placements out for accuracy. Thoughts?

Comment (wassgha) [reply assets/src/edit-story/components/popup/test/popup.js]: Done :)

**Review by miina — APPROVED** [review]
LGTM!
