### PR TITLE
Editor: Fix image src desync

### LINKED ISSUE #10192: Bug: Image element src not in sync when replaced with other media
Found in this thread here once we fixed some bugs with the animation provider:
https://github.com/google/web-stories-wp/pull/10024#issuecomment-1012362521

When replacing an image element with new media, the src remains on the old resource while the srcset updates to the new resource.

Visually there are no issues because the browser pulls the currentSrc from the srcset instead of the src, but src resource shouldn't get out of sync with the active resource. 

Completion of this ticket involves updating `story-editor/src/elements/media/imageDisplay.js` to maintain the active resource as its src and to re-enable these karma tests to make sure they're passing:
- should correctly copy image to page with existing image
- should correctly handle image dragged from library straight to edge replacing old image
- should correctly handle image dropped on edge replacing old image
- should replace top image when bg image is set and another one is on top
- should replace the top image when two images are in the same place on canvas

This behavior can't be seen on the canvas until this PR is merged, but you can view it on main right now in the carousel page preview after replacing media of an element:
https://github.com/google/web-stories-wp/pull/10024

### PR DESCRIPTION
**Pull request by merapi**
## To-do

- [ ] Enable tests

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10192

### CODE REVIEW

File: packages/story-editor/src/elements/media/imageDisplay.js [hunk 1]
```diff
@@ -108,6 +108,8 @@ function ImageDisplay({ element, box, previewMode }) {
           // Ignore
         }
       });
+    } else {
+      setSrc(resource.src);
     }
```
Comment (merapi) [inline packages/story-editor/src/elements/media/imageDisplay.js:113]: Previous code was only settings the `src` when the full-size image was not loaded (so it was preloading the image and then settings the `src`) and did nothing when we already had full-size in resourseList (and component was updated, the newly mounted component was ok), now, if we have the full-size image we just set the `src` (it's there because we first see the preview of it when dropping?).

Comment (maxyinger) [reply packages/story-editor/src/elements/media/imageDisplay.js:113]: > it's there because we first see the preview of it when dropping?

✅  Yea this is the behavior I was seeing when I was logging it out yesterday

**Review by maxyinger — APPROVED** [review]
Awesome. Thanks for the quick fix 🙌

**Review by barklund — APPROVED** [review]
Seems to do what it claims to. It's a weird issue given that it doesn't directly impact us, because we have duplicate information, but I guess that's just how it is.

**Review by miina — APPROVED** [review]
