### PR TITLE
Fix element links being removed incorrectly

### LINKED ISSUE #4318: Elements with links not working
## Bug Description

I added a link to an element but it gets removed when previewing the story.

I _think_ the issue is here:

https://github.com/google/web-stories-wp/blob/76cdad28a6897e1049f6a342e2a08d5edb3cb26f/assets/src/edit-story/output/page.js#L52-L62

This should probably be `! hasPageAttachment || !isElementBelowLimit(element)`

IMO this is a blocker for stable and definitely needs some unit tests.

## Expected Behaviour

Link should not disappear when previewing the final AMP output.

## Steps to Reproduce

1. Add a link to an element
1. Preview story
1. Notice that there's no link

## Additional Context

- Plugin Version: `main`
- Operating System: macOS
- Browser: Chrome 84

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Testing

I
1. Add a link
2. Verify that it shows up in the front-end (is clickable)

II
1. Add a link
2. Add a Page attachment
3. Ensure the link is outside of the Page Attachment area
4. Save and verify that the link shows up in the front-end as well

III
1. Add a link to the bottom of the page (needs to be in the Page Attachment area)
2. Add a Page attachment
3. Save and verify that the link is not clickable in the front-end

### PR DESCRIPTION
**Pull request by miina**
## Summary
- Adds unit tests to verify the links are output if there's no page attachment / if there is one but the element is out of its area
- Fixes the incorrect condition always removing links if page attachment is not present.

## Testing Instructions
I
1. Add a link
2. Verify that it shows up in the front-end (is clickable)

II
1. Add a link
2. Add a Page attachment
3. Ensure the link is outside of the Page Attachment area
4. Save and verify that the link shows up in the front-end as well

III
1. Add a link to the bottom of the page (needs to be in the Page Attachment area)
2. Add a Page attachment
3. Save and verify that the link is not clickable in the front-end

---

Fixes #4318

### CODE REVIEW

File: assets/src/edit-story/output/test/page.js [hunk 1]
```diff
@@ -532,7 +569,33 @@ describe('Page output', () => {
...
+        id: '123',
+        backgroundColor: { color: { r: 255, g: 255, b: 255 } },
+        page: {
+          id: '123',
+          elements: [
+            BACKGROUND_ELEMENT,
+            {
+              ...TEXT_ELEMENT,
+              link: {
+                url: 'http://shouldoutput.com',
```
Comment (barklund) [inline assets/src/edit-story/output/test/page.js:586]: Hey, [it's available](https://www.namecheap.com/domains/registration/results/?domain=shouldoutput.com)! 🎉

**Review by barklund — APPROVED** [review]
Links seem to work correctly now. @swissspidy, can you confirm that too?

**Comment by miina** [comment]
Moving to QA meanwhile to ensure it'll get tested in time.

**Review by swissspidy — APPROVED** [review]
