### PR TITLE
Use correct icons for radios.

### LINKED ISSUE #2337: Broken status & visibility options
## Bug Description

Currently, the selected visibility is not blue, while the unselected ones are blue.

## Expected Behaviour

It should be the other way around.

## Steps to Reproduce

1. Create new story

## Screenshots

Here "Draft" should be selected, not the other two options:

image (4)

## Additional Context

- Plugin Version: `master`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

The icons got switched at some point, this PR restores that.

## User-facing changes

- The icons now reflect the checked/unchecked state of radios.

## Testing Instructions
1. Open Document tab
2. Click on different statuses
3. Verify that the selected status looks "checked" and the others look unchecked.

---

Fixes #2337

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
Whoops looks like that was me 🙈  #2192

File: assets/src/edit-story/components/form/radioGroup.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ import { useMemo } from 'react';
 /**
  * Internal dependencies
  */
-import { Radio as Selected, RadioSelected as UnSelected } from '../../icons';
+import { Radio as UnSelected, RadioSelected as Selected } from '../../icons';
```
Comment (barklund) [inline assets/src/edit-story/components/form/radioGroup.js:29]: 😂😂😂
