### PR TITLE
Animations: Fix animation inheriting parent transform

### LINKED ISSUE #5534: Update animations to retain the animation direction and not the one set by the rotation
## Feature Description

A rotated item with a drop-animation “drops” in the rotated direction and not in the “natural” top-to-bottom direction. 

The above also goes for fly-in, whoosh-in, and rotate-in effect. If you rotate an element 90 degrees and apply “fly-in” ,”whoosh-in” or “rotate-in” from left, the element actually flies/whooshes/rotates in from the top.

As per discussion from @littlemilkstudio 

> Right now we're animating a wrapper element that's a child of, & taking up the full size of the top level static positioning container. This approach leads to these stacked transforms you're seeing.
> 
> I think fixing this will require rethinking our targeting approach for animation elements, but I want to be considerate in not causing regressions for composing animations in the future.
> 
> I think this requires some further discussion and would be happy to chat about it, but don't see an "easy" fix beyond disabling animation options when there is certain transforms present on the element

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #5601: Animations: Include element rotation in effects that necessitate off screen coordinate calculations
Right now effects that need to calculate offscreen coordinates don't take into account if the element has a top level rotation. This can lead to miscalculations leaving elements partially onscreen before their animation plays.

**Steps to reproduce:**
-> Create a new story or edit existing one
-> Add a square shape to the current page
-> Under the `size & position` panel, give the element a rotation of `34deg` and a height and width of `200x200`
-> Under the animation panel apply the `rotate` from the right effect
-> Add a `delay` to the animation of `5000ms`
-> click preview and see that the element doesn't start completely off the canvas

**Completion**
Completion of this task involves accounting for this rotation in all animation effects that need off screen coordinate such that the element starts off the page.

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Before this update, if you rotated an element, then applied an animation, the animation would take place under that rotation.

**example**
Rotate an element 35deg, then add animate on the elements y axis (with something like drop), the y axis it's animated along would be rotated 35 deg making it appear to animate in at an angle.

**solution**
This was a natural byproduct of how we set the animation wrappers in the DOM hierarchy. However, I thought of a neat little transform trick to opt out of this behavior without foundationally changing our animation setup or the DOM hierarchy.

This approach adds a counter transform to the element, then applies the animation in the net zero transform space, then reapplies the original transforms. Good news is this approach maintains composability and all that important shtuff, so we're 💯 

## Relevant Technical Choices
Just wrapped all transform & rotation values in the global space wrapper.

## To-do
NA

## User-facing changes
Now element rotation shouldn't influence any animations.

## Testing Instructions
Create a story -> add an element -> rotate the element 34 degrees -> go through applying all animations on the element -> see that the animations are unaffected by the elements rotation as they were previously before

---

Fixes #5601 
Fixes #5534

### CODE REVIEW

**Review by carloskelly13 — APPROVED** [review]
This looks great. Neat usage of the ttl for reseting the coordinate space for rotated elements.

File: assets/src/animation/utils/getGlobalSpace.js [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+ * @return {(s: string[], ...args: any[]) => string} template string tag that resets transform space.
+ */
+export function getGlobalSpace(element = {}) {
+  function global(...template) {
+    return `rotate(${-1 * element?.rotationAngle}deg) ${literal(
+      ...template
+    )} rotate(${element?.rotationAngle}deg)`;
+  }
+  return element?.rotationAngle ? global : literal;
+}
```
Comment (barklund) [inline assets/src/animation/utils/getGlobalSpace.js:63]: Neat! 🎉

**Review by barklund — APPROVED** [review]
This works amazingly well. Excellent effort, here - and neatly implemented!

**Comment by csossi** [comment]
Verified in QA
