### PR TITLE
Animations: Prevent malformed HTML output

### LINKED ISSUE #5763: Animations: Malformed HTML output (for authors)
## Bug Description

It appears that animations are currently stripped for authors because the `amp-story-animation -> script[type]` attribute is not in the KSES allowlist.

Also, `AnimationOutput` simply prints everything that is passed to it, including the animation part's `element` prop, which contains the whole element's information—even though it's completely unneeded on the frontend. Since `element.content` can contain HTML and double quotes, this can cause issues on the frontend due to malformed JSON output, further breaking animations. Example:

```json
[
  {
    "selector": "#anim-be44c124-65a8-4307-97de-6cef70a50c88",
    "keyframes": [
      {
        "transform": "scale(0)",
        "offset": 0
      },
      {
        "transform": "scale(1.27)",
        "offset": 0.18
      },
      {
        "transform": "scale(0.84)",
        "offset": 0.28
      },
      {
        "transform": "scale(0.84)",
        "offset": 0.29
      },
      {
        "transform": "scale(1.1)",
        "offset": 0.4
      },
      {
        "transform": "scale(1.1)",
        "offset": 0.41
      },
      {
        "transform": "scale(0.95)",
        "offset": 0.52
      },
      {
        "transform": "scale(0.95)",
        "offset": 0.53
      },
      {
        "transform": "scale(1.03)",
        "offset": 0.6
      },
      {
        "transform": "scale(1.03)",
        "offset": 0.61
      },
      {
        "transform": "scale(0.98)",
        "offset": 0.7
      },
      {
        "transform": "scale(0.98)",
        "offset": 0.71
      },
      {
        "transform": "scale(1.02)",
        "offset": 0.8
      },
      {
        "transform": "scale(1.02)",
        "offset": 0.81
      },
      {
        "transform": "scale(0.99)",
        "offset": 0.9
      },
      {
        "transform": "scale(0.99)",
        "offset": 0.91
      },
      {
        "transform": "scale(1)",
        "offset": 1
      }
    ],
    "fill": "both",
    "duration": 2800,
    "delay": 480,
    "direction": "normal",
    "element": {
      "x": 49,
      "y": 442,
      "width": 337,
      "height": 165,
      "opacity": 100,
      "flip": {
        "vertical": false,
        "horizontal": false
      },
      "rotationAngle": 0,
      "lockAspectRatio": true,
      "backgroundTextMode": "NONE",
      "font": {
        "family": "Bungee",
        "service": "fonts.google.com",
        "fallbacks": [
          "cursive"
        ],
        "weights": [
          400
        ],
        "styles": [
          "regular"
        ],
        "variants": [
          [
            0,
            400
          ]
        ]
      },
      "backgroundColor": {
        "color": {
          "r": 196,
          "g": 196,
          "b": 196
        }
      },
      "lineHeight": 1,
      "textAlign": "center",
      "scale": 100,
      "focalX": 50,
      "focalY": 50,
      "type": "text",
      "basedOn": "d886c844-5b5c-4b27-a9c3-332df2aed3f3",
      "id": "25b6f99b-3f69-4351-9e18-31b8ef1d1a61",
      "content": "<span style="
      font-weight: 400
      ;
      color:
      #
      fff
      ;
      letter-spacing: 0.09em
      ">FRESH\n<span style="
      font-weight: 400
      ;
      color:
      #
      fff
      ;
      letter-spacing: 0.09em
      ">&amp;&nbsp;\n<span style="
      font-weight: 400
      ;
      color:
      #
      fff
      ;
      letter-spacing: 0.09em
      ">BRIGHT",
      "fontSize": 55,
      "padding": {
        "horizontal": 0,
        "vertical": 0
      }
    },
    "easing": "linear"
  }
]
```

## Expected Behaviour

Authors should be able to use animations just fine

## Steps to Reproduce

1. Log in as author
1. Create new story from template (e.g. Beauty template)
1. Preview story on frontend
1. Notice that story appears broken, and no animated element is there

## Additional Context

- Plugin Version: 1.2.1
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Prevents animation markup from being stripped, especially for author users.

## Relevant Technical Choices

* KSES: Add required type attribute for animations. Added a unit test.
* Animations: Updates `AnimationOutput` to avoid printing `element` on the frontend for animations, avoiding potentially malformed HTML.

## To-do

Since there's also AMP sanitization happening later, we could think about extending our existing e2e test for author users.

## User-facing changes

No more broken animations for author users.

## Testing Instructions

1. Log in as author
1. Create new story from template (e.g. Beauty template)
1. Preview story on frontend
1. Verify that story & animation appears correctly

---

Fixes #5763

### CODE REVIEW

**Comment by swissspidy** [comment]
Hi @brianpetro, I think this PR addresses the animation issues your seeing. Could you perhaps give it a try & install it on your site (perhaps on a staging site if you have one). Download: https://github.com/google/web-stories-wp/suites/1706193109/artifacts/32155291

**Comment by brianpetro** [comment]
Thanks, @swissspidy .

The problem is still occurring with the above.

One change I noticed is that the following error now occurs when amp-wp plug-in is both enabled/disabled. 

> AMP optimization could not be completed due to the following:
  - CannotRemoveBoilerplate: Cannot remove boilerplate because of an unsupported layout: amp-story

Before this I had only noticed the above error when amp-wp was enabled.

**Comment by swissspidy** [comment]
> Thanks, @swissspidy .
> 
> The problem is still occurring with the above.

Just to clarify, did you install that ZIP and then try to create a new story with animations, and it‘s still not working? Could you share the story URL here?

> One change I noticed is that the following error now occurs when amp-wp plug-in is both enabled/disabled.
> 
> > AMP optimization could not be completed due to the following:
> >   - CannotRemoveBoilerplate: Cannot remove boilerplate because of an unsupported layout: amp-story
> 
> Before this I had only noticed the above error when amp-wp was enabled.

This informational message is always there, and does not indicate any issue with stories. It‘s mostly for debugging.

**Comment by brianpetro** [comment]
@swissspidy 

> Just to clarify, did you install that ZIP and then try to create a new story with animations, and it‘s still not working? 

That is correct.

> Could you share the story URL here?

https://wfhjobs.us/web-stories/37314190/

**Comment by swissspidy** [comment]
Strange. Only a few of these animations seem corrupt.

But I cannot reproduce this so far, neither on single site nor on multisite, as a user with "author" role. Not even when using a template with complex animations. Since you've used the beauty template for that test story, could you try from a blank story (creating one from scratch, without template)? And with all other plugins disabled (you can enable them again after saving)?

**Comment by brianpetro** [comment]
> But I cannot reproduce this so far, neither on single site nor on multisite, as a user with "author" role. Not even when using a template with complex animations. Since you've used the beauty template for that test story, could you try from a blank story (creating one from scratch, without template)? And with all other plugins disabled (you can enable them again after saving)?

I tried again to reproduce with all other plug-ins disabled and this is still an issue.

To reproduce this, have you tried using the templates located within the plug-in itself?

Yes, when you create a blank a completely blank canvas and try to animate a few elements the issue seems to disappear. But, it's those included templates that have been used as a starting point to create new stories. So starting with a blank canvas doesn't help in salvaging the work that has already been done there.

Additionally, when I go into a non-working story as a super admin, and then save the story, it works as expected. But, it stops working as soon as a user from any other permission level makes a change.

What is making this work for super-admins on the multisite? Is there a work-around?

**Comment by swissspidy** [comment]
As mentioned I tried with the built-in templates successfully, no issues there. I‘ll try again though.

Super admins basically have unrestricted access, whereas for other users some security protections kick in when saving posts/stories.

File: assets/src/animation/outputs/animationOutput.js [hunk 1]
```diff
@@ -33,9 +33,38 @@ function AnimationOutput({ config }) {
...
+                direction,
+                duration,
+                easing,
+                easingPreset,
+                endDelay,
+                fill,
+                iterationStart,
+                iterations,
+              })
+            )
```
Comment (swissspidy) [inline assets/src/animation/outputs/animationOutput.js]: Ideally we'd avoid this, ensuring `element` is never passed down here.

@littlemilkstudio Perhaps you can help here?

**Comment by swissspidy** [comment]
@brianpetro Heya, I think I was able to reproduce this now. Could you give this new version a try? Download: https://github.com/google/web-stories-wp/suites/1709771191/artifacts/32255015

**Comment by brianpetro** [comment]
hooray

@swissspidy Great, that seems to have done the trick.

Thanks for the help and all of your contributions to the project!

File: tests/phpunit/tests/KSES.php [hunk 2]
```diff
@@ -310,34 +310,38 @@ public function test_filter_kses_allowed_html( $html, $expected ) {
...
+			'AMP Animations'       => [
 				'<p id="foo" animate-in="fly-in-left" animate-in-delay="0.3s" animate-in-duration="0.5s" animate-in-layout="nodisplay">Hello World</p><p id="bar" animate-in="fade-in" animate-in-after="foo">Hello World</p>',
 				'<p id="foo" animate-in="fly-in-left" animate-in-delay="0.3s" animate-in-duration="0.5s" animate-in-layout="nodisplay">Hello World</p><p id="bar" animate-in="fade-in" animate-in-after="foo">Hello World</p>',
 			],
+			'AMP Story Animations' => [
+				'<amp-story-animation layout="nodisplay" trigger="visibility"><script type="application/json">[{"selector":"#anim-9d7bb1a9-8839-4629-b26c-d1863e675c36","keyframes":{"transform":["translate3d(-110.30303%, 0px, 0)","none"]},"fill":"forwards","duration":600,"delay":0,"easing":"cubic-bezier(0.4, 0.4, 0.0, 1)"}]</script></amp-story-animation>',
+				'<amp-story-animation layout="nodisplay" trigger="visibility"><script type="application/json">[{"selector":"#anim-9d7bb1a9-8839-4629-b26c-d1863e675c36","keyframes":{"transform":["translate3d(-110.30303%, 0px, 0)","none"]},"fill":"forwards","duration":600,"delay":0,"easing":"cubic-bezier(0.4, 0.4, 0.0, 1)"}]</script></amp-story-animation>',
+			],
```
Comment (maxyinger) [inline tests/phpunit/tests/KSES.php:344]: Awesome. Yea we're using this form to recreate the animation presets so there's no discrepancies between the editor and the output

File: assets/src/animation/outputs/animationOutput.js (hunk 1 above)
Comment (maxyinger) [reply assets/src/animation/outputs/animationOutput.js]: Yea absolutely! Not sure how the element was getting in there. pretty sure this is the only place we're using this component:
https://github.com/google/web-stories-wp/blob/f10acc692951ccca04c71287829035897661345a/assets/src/animation/parts/simpleAnimation.js#L105

Regardless, This looks good to me

**Review by maxyinger — APPROVED** [review]
Looks good! I think we can even shorten the list of properties getting passed through here.

File: assets/src/animation/outputs/animationOutput.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/animation/outputs/animationOutput.js]: Maybe I'll shorten the list a bit, but it would definitely be good to fix the root cause to  not pass down `element` in the first place.

Comment (maxyinger) [reply assets/src/animation/outputs/animationOutput.js]: yea completely agree. I don't think we're using `endDelay`, `animation` or `iterationStart` but those are all valid properties, so fine to leave in there. Ope, just noticed `easingPreset` is in there. That's just an internal property that maps to predefined bezier curves. Fine to remove that one
