### PR TITLE
Dashboard: Fixed bug that caused some animations to not play

### LINKED ISSUE #3223: Some animation parts don't play when certain delays are set.
It seems when an animation part is set to a 400ms delay (or some multiple) the animation part doesn't play.  But if you change the delay to 395, then everything works... not sure if this is a legit bug or just some freak thing on my computer so this ticket is to investigate the issue and hopefully come up with a fix or some resolution.

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR implements a "fix" (more like a workaround) to make sure all our animation parts play as expected.

When building out template animations, I noticed that certain combinations of `duration` and `delay` would cause the animation part _not_ to play 😱 But if I modified either value by just 1 (i.e. 1100 => 1101) then it suddenly worked.  

After a bit of sleuthing, I found out that the animation object itself calculates an internal value called `_holdTime` and hold time seems to be the sum of `duration` and `delay`.  Most of the time that `_holdTime` is a whole number, some times it comes out to something like 899.999999999 (which works just fine), however, when `_holdTime` is set to a number like 1700.0000000000002 (when `duration` is 800 and `delay` is 900) then... the animation part (in Chrome) simply won't play.

image

But, for whatever reason, calling `cancel` before executing `play` when trying to play all animations, fixes the issue.

## User-facing changes

None

## Testing Instructions

1.) Checkout `main` and go to our `story-anim-tool` and enable animations for dashboard.
2.) Choose a random story to test with.
3.) Apply a random animation to any element on the first page and set the duration to `800` and the delay to `400`.
4.) Play the animations, notice that the element you just applied an animation to should _not_ play 😱 
5.) Pull down this branch and switch to it (make sure to enable animations for dashboard).
6.) Go to our `story-anim-tool` and select the story and page you just applied an animation to.
7.) Play the animations, this time the `800/400` animation _should_ play 🎉 

---

Fixes #3223

### CODE REVIEW

File: assets/src/dashboard/components/storyAnimation/provider.js [hunk 1]
```diff
@@ -114,7 +115,16 @@ function Provider({ animations, children, onWAAPIFinish }) {
...
-      WAAPIAnimations.forEach((animation) => animation?.play());
+      WAAPIAnimations.forEach((animation) => {
+        // Sometimes an animation part can get into a
+        // stuck state where executing `play` doesn't
+        // trigger the animation. A workaround to avoid
+        // this is to first `cancel` the animation
+        // before playing.
+        animation?.cancel();
+
+        animation?.play();
```
Comment (mariano-formidable) [inline assets/src/dashboard/components/storyAnimation/provider.js:126]: This doesn't seem to have an adverse affect on playing other animations (long or short) and spamming the play button seems to work like before... however, feel free to double check and push back if you foresee this causing legit issues in the future.

File: assets/src/dashboard/app/views/storyAnimTool/index.js [hunk 2]
```diff
@@ -112,13 +112,16 @@ function StoryAnimTool() {
         saveActiveStoryUpdates(activeStory);
       }
 
+      // Deselect animation
+      setActiveAnimation({});
+
+      // Reset active page
+      setActivePageIndex(0);
```
Comment (mariano-formidable) [inline assets/src/dashboard/app/views/storyAnimTool/index.js:119]: I noticed that we weren't resetting the page index when switching stories.  This causes a crash of our little tool when we're on page 9 of a story and then switch to another story that is 8 pages or less 😱 But now resetting it, we'll always move to the first page when changing stories.

File: assets/src/dashboard/components/storyAnimation/provider.js [hunk 3]
```diff
@@ -114,7 +115,16 @@ function Provider({ animations, children, onWAAPIFinish }) {
 
   const WAAPIAnimationMethods = useMemo(() => {
     const play = () =>
-      WAAPIAnimations.forEach((animation) => animation?.play());
+      WAAPIAnimations.forEach((animation) => {
```
Comment (mariano-formidable) [inline assets/src/dashboard/components/storyAnimation/provider.js:118]: Console log this `animation` object if you want to see the object with the `_holdTime` prop.

File: assets/src/dashboard/components/storyAnimation/provider.js (hunk 1 above)
Comment (maxyinger) [reply assets/src/dashboard/components/storyAnimation/provider.js:126]: This works for me!

I think the only issue I can see in the future is if someone wants to scrub and play from the point they've scrubbed to, but this might not even be part of the product spec, so works for me for now. 

Got a good comment there too, so if it does become a case we need to handle, we know were to look and can figure out some other duct tape solution since we can't really fix the tool.

**Review by maxyinger — APPROVED** [review]
lgtm!
