### PR TITLE
Align flip buttons next to each other

### LINKED ISSUE #1212: Flip Buttons Placement Incorrect
## Bug Description

The placement of the flip buttons is off

## Expected Behaviour

When there are only two buttons, they should be next to each other and aligned to the left.
flip mocks

## Steps to Reproduce

1. Set image as background by dragging to mask area
2. See panel for flip buttons

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by joannag6**
Buttons float to the left with a set margin between them.

## Summary

Fixes incorrect flip button placement when image is set as background.

(For background images)
Screen Shot 2020-05-04 at 5 54 00 PM

(For non-background images - no change from before)
Screen Shot 2020-05-04 at 5 54 07 PM

Fixes #1212

### CODE REVIEW

File: assets/src/edit-story/components/panels/shared/flipControls.js [hunk 1]
```diff
@@ -31,30 +32,61 @@ import { ReactComponent as FlipHorizontal } from '../../../icons/flip_horizontal
...
 import Toggle from '../../form/toggle';
 
-function FlipControls({ value, onChange }) {
+const styledToggle = css`
+  width: 36px;
+  height: 36px;
+  display: flex;
+  justify-content: center;
+  align-items: center;
+  float: left;
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/shared/flipControls.js]: Let's try to avoid floats.

IMO we should be able to set 

```css
display: flex;
justify-content: left;
align-items: flex-start;
```

on `ControlsContainer`

Then, there's no real need for a separate `stylesToggle` variable. It can be inlined in `ToggleContainer`:

```
const ToggleContainer = styled.div`
  width: 36px;
  height: 36px;
  display: flex;
  justify-content: center;
  align-items: center;
`
```

File: assets/src/edit-story/components/panels/shared/flipControls.js [hunk 2]
```diff
@@ -31,30 +32,61 @@ import { ReactComponent as FlipHorizontal } from '../../../icons/flip_horizontal
...
+  width: fit-content;
+`;
+
+/**
+ * Get flip controls for flipping elements horizontally and vertically.
+ *
+ * @param {Object} value Element's flip object.
+ * @param {Object} onChange Callback to flip element.
+ * @param {number} margin Space between the two flip toggles (defaults to '8px').
+ * @return {*} Element or null if does not map to video/image.
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/shared/flipControls.js]: This component never really returns `null`.

Also, a docblock like this would be more accurate:

```js
/**
 * Displays flip controls for flipping elements horizontally and vertically.
 *
 * @param {Object} props Component props.
 * @param {Object} props.value Element's flip object.
 * @param {Object} props.onChange Callback to flip element.
 * @param {number} props.margin Space between the two flip toggles (defaults to '8px').
 * @return {*} Rendered component.
 */
```

Notice the `props.` prefix

File: assets/src/edit-story/components/panels/backgroundSizePosition.js [hunk 3]
```diff
@@ -68,6 +68,7 @@ function BackgroundSizePositionPanel({ selectedElements, pushUpdate }) {
         <FlipControls
           onChange={(value) => pushUpdate({ flip: value }, true)}
           value={flip}
+          margin={'36px'}
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/backgroundSizePosition.js]: Any way we can avoid passing down a specific style instruction?

Or at least call this `elementSpacing` or something?

File: assets/src/edit-story/components/panels/shared/flipControls.js (hunk 1 above)
Comment (joannag6) [reply assets/src/edit-story/components/panels/shared/flipControls.js]: Done.

File: assets/src/edit-story/components/panels/backgroundSizePosition.js (hunk 3 above)
Comment (joannag6) [reply assets/src/edit-story/components/panels/backgroundSizePosition.js]: Renamed.

File: assets/src/edit-story/components/panels/shared/flipControls.js (hunk 2 above)
Comment (joannag6) [reply assets/src/edit-story/components/panels/shared/flipControls.js]: Done.

File: assets/src/edit-story/components/panels/shared/flipControls.js [hunk 4]
```diff
@@ -31,30 +32,59 @@ import { ReactComponent as FlipHorizontal } from '../../../icons/flip_horizontal
...
+/**
+ * Get flip controls for flipping elements horizontally and vertically.
+ *
+ * @param {Object} props Component props.
+ * @param {Object} props.value Element's flip object.
+ * @param {function(boolean)} props.onChange Callback to flip element.
+ * @param {number} props.elementSpacing Space between the two flip toggles (defaults to 8).
+ * @return {*} Rendered component.
+ */
+function FlipControls({ value, onChange, elementSpacing = 8 }) {
```
Comment (ndev1991) [inline assets/src/edit-story/components/panels/shared/flipControls.js]: Let's use `FlipControls.defaultProps` as others do

Comment (joannag6) [reply assets/src/edit-story/components/panels/shared/flipControls.js]: Done.

**Review by swissspidy — APPROVED** [review]
