### PR TITLE
Checklist: Focus checklist when opened from the publish modal

### LINKED ISSUE #11196: Review Checklist/Story Details: Focus Lost
## Bug Description

If I am in the story details modal and I click on "review checklist" the focus stays on the publish button making keyboard navigation super annoying to get to the checklist I wanted to review. 

## Expected Behaviour

If I am in the story details modal and I click on "review checklist" the focus should shift to the expanded checklist (just like it does when you open from the checklist button in the footer. 

## Steps to Reproduce

Click "publish" to get to story details modal
Click "review checklist" 
See that the publish button is focused and tooltip (probably) present.

## Screenshots

Kapture 2022-04-05 at 15 57 30

## Additional Context

I did some discovery into this thinking it could be an easy fix - it looks like the publish button is rerendering _alot_ and I can't quite place why - there's so many hoops it jumps through from story-editor to wp-story-editor back to story-editor. Anyways, I think that's the reason the focus is getting hijacked. 

Updating an e2e test to confirm the focus pattern is correct would be cool too. 

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by samwhale**
## Context

This is a [React Modal](https://github.com/reactjs/react-modal/issues/680) issue. Focus is always returned to the element that lost focus when the modal was opened.

## Summary

Blur the button when opening the publish modal. This allows the checklist to steal focus when the checklist is opened from the publish modal.

## Relevant Technical Choices

n/a

## To-do

n/a

## User-facing changes

focus

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Open the publish modal
2. Use the keyboard to press the checklist button in the modal
3. Verify that the checklist has focus
4. Open the publish modal again
5. Press the `close` button with the keyboard
6. Verify that the `Publish` button in the editor has focus

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11196

### CODE REVIEW

**Comment by samwhale** [comment]
A consequence of this change is that closing the publish modal in other ways ends up focusing the canvas. I think that's also weird. Maybe we should add functionality to focus the publish button again if the checklist button isn't clicked?

**Comment by samwhale** [comment]
A consequence of this change is that closing the publish modal in other ways ends up focusing the canvas. I think that's also weird. Maybe we should add functionality to focus the publish button again if the checklist button isn't clicked?

**Comment by BrittanyIRL** [comment]
> A consequence of this change is that closing the publish modal in other ways ends up focusing the canvas. I think that's also weird. Maybe we should add functionality to focus the publish button again if the checklist button isn't clicked?

Will you add that functionality to focus the publish button if the checklist button isn't clicked?

**Review by maxyinger — APPROVED** [review]
Good find. Yea this is an interesting edge case with the current setup.

**Comment by samwhale** [comment]
Should be fixed now @BrittanyIRL

File: packages/story-editor/src/components/header/buttons/buttonWithChecklistWarning.js [hunk 1]
```diff
@@ -50,106 +50,120 @@ const Button = styled(DefaultButton)`
...
-  ...buttonProps
-}) {
+const InnerButton = forwardRef(function InnerButton(
+  { text, checkpoint, hasHighPriorityIssues = false, onClick, ...buttonProps },
+  ref
+) {
+  const handleClick = (evt) => {
+    // https://github.com/reactjs/react-modal/issues/680#issuecomment-413422345
+    // React Modal restores input on last focused element on close.
+    // Blur button so that it doesn't steal focus back when opening the checklist.
```
Comment (BrookeGraham) [inline packages/story-editor/src/components/header/buttons/buttonWithChecklistWarning.js:60]: Nice.

File: packages/story-editor/src/components/header/buttons/buttonWithChecklistWarning.js [hunk 2]
```diff
@@ -50,106 +50,120 @@ const Button = styled(DefaultButton)`
...
+    evt.currentTarget.blur();
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/header/buttons/buttonWithChecklistWarning.js:61]: thanks for this note

**Review by BrittanyIRL — APPROVED** [review]
Thank you for the update. 

Looks like a test is failing, do you have time today still to look at this? https://github.com/GoogleForCreators/web-stories-wp/runs/5993881371?check_suite_focus=true#step:7:842

**Review by BrookeGraham — APPROVED** [review]
🍉 Works nicely!
