### PR TITLE
3P Media: Fix attribution pill label

### LINKED ISSUE #7274: 3P provider logo does not have correct alt text
## Feature Description

The 3P media provider logo do not have any sort of alt text or screen reader text. Making them completely unaccessible to screen readers. 

Discovered as part of #7272

## Screenshot

Screenshot 2021-04-21 at 17 14 07
Screenshot 2021-04-21 at 17 14 12

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

the 3p media links that say "powered by" weren't announcing what they were powered by. 

## Summary

add aria-label to span or if not available the svg that is generated for tenor so that links have context.

## Relevant Technical Choices

Used `sprintf` for translations of 'powered by' and put organization names in an object as strings since they are organization names and shouldn't be translated. 

## User-facing changes

Visually things should look the same, but if you use a screen reader and focus on the 'powered by' links you should now here what they are powered by. 
| Images | Video | Gif |
| --- | --- | --- |
| Screen Shot 2021-05-03 at 10 10 08 AM | Screen Shot 2021-05-03 at 10 09 43 AM | Screen Shot 2021-05-03 at 10 09 17 AM | 

## Testing Instructions

use a screen reader and focus on the powered by blurbs on the 3p media panel. Hear a relevant announcement of "Powered by ___" either Unsplash, Coverr, or Tenor.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7274

### CODE REVIEW

File: assets/src/edit-story/app/media/media3p/attribution.js [hunk 1]
```diff
@@ -80,17 +80,30 @@ const coverrUrl =
...
   'https://tenor.com?utm_source=web_stories_wordpress&utm_medium=referral';
 
+const ORG_NAME = {
+  coverr: 'Coverr',
+  tenor: 'Tenor',
+  unsplash: 'Unsplash',
+};
+const getAriaLabel = (org) =>
+  sprintf(
+    /* translators: %s: name of organization media is pulled in from. */
```
Comment (swissspidy) [inline assets/src/edit-story/app/media/media3p/attribution.js]:
```suggestion
    /* translators: %s: media provider name. */
```

**Review by samwhale — APPROVED** [review]
:chefs_kiss:

File: assets/src/edit-story/app/media/media3p/attribution.js [hunk 2]
```diff
@@ -80,17 +80,30 @@ const coverrUrl =
...
+const MEDIA_PROVIDER = {
+  coverr: 'Coverr',
+  tenor: 'Tenor',
+  unsplash: 'Unsplash',
+};
+const getAriaLabel = (provider) =>
+  sprintf(
+    /* translators: %s: media provider name. */
+    __('Powered by %s', 'web-stories'),
+    MEDIA_PROVIDER[provider]
```
Comment (samwhale) [inline assets/src/edit-story/app/media/media3p/attribution.js]: I feel like we could just pass the provider name in instead of making this dictionary. If somebody misspells the property name then this returns `undefined`

Maybe we just do this?
```suggestion
const MEDIA_PROVIDER = {
  coverr: 'Coverr',
  tenor: 'Tenor',
  unsplash: 'Unsplash',
};
const getAriaLabel = (provider) =>
  sprintf(
    /* translators: %s: media provider name. */
    __('Powered by %s', 'web-stories'),
    provider
```

And then when we're passing the values in we could always do `MEDIA_PROVIDER.Coverr` and stuff?

**Comment by spacedmonkey** [comment]
I fixed this like this - https://github.com/google/web-stories-wp/blob/682517f50445da2ea7dd776cc02ec061df8ed1a1/assets/src/edit-story/app/media/media3p/attribution.js

Basically add a tenor icon svg and remove power by wording in svg.

**Comment by BrittanyIRL** [comment]
> I fixed this like this - https://github.com/google/web-stories-wp/blob/682517f50445da2ea7dd776cc02ec061df8ed1a1/assets/src/edit-story/app/media/media3p/attribution.js
> 
> Basically add a tenor icon svg and remove power by wording in svg.

Thanks, I guess somewhere between then and now the data-label came back on tenor. I've updated so it's all consistent and the aria label attaches to the anchor so it gets announced with the link.

File: assets/src/edit-story/app/media/media3p/attribution.js (hunk 2 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/app/media/media3p/attribution.js]: Thanks, @samwhale - should be better now. This was overkill on my part 🙃

File: assets/src/edit-story/app/media/media3p/attribution.js [hunk 3]
```diff
@@ -103,20 +116,26 @@ export function CoverrAttribution() {
...
 export function TenorAttribution() {
   return (
-    <a href={tenorUrl} target={'_blank'} rel={'noreferrer'}>
+    <a
+      href={tenorUrl}
+      target={'_blank'}
+      rel={'noreferrer'}
+      aria-label={getAriaLabel(MEDIA_PROVIDER.tenor)}
+    >
       <AttributionPill>
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/media3p/attribution.js:137]: I don't understand why tenor is different here? Why can't we keep it the same. Text "Powered by" and a tenor logo. The svg logo should have some kind of alt tag.

Comment (swissspidy) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: The Tenor logo is the only one that contains the text "powered by" in the image itself. See https://github.com/google/web-stories-wp/blob/7eb02795c5349585ea5083e382f924eb1f9e0188/assets/src/edit-story/icons/tenor_logo_white.svg

So there's no need for separate "Powered by" text.

But you're right, I think we should be able to set the SVG's `<title>` by doing

```jsx
<TenorLogo title={getAriaLabel(MEDIA_PROVIDER.tenor)} />
```

No need for `aria-label` and `aria-hidden` in this case.

But needs testing to confirm.

Comment (spacedmonkey) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: This is more a case of uniformity. Why is this different? Why does it need to be different?

Comment (swissspidy) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: That's the media3p provider attribution logo we were originally provided by Tenor. We can't just simply change it, so we have to stick with it.

Comment (spacedmonkey) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: Why can't it be changed?

Comment (swissspidy) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: Because this specific attribution is part of the terms of using that provider. I can reach out to see if it's OK to use another SVG and if they can provide that, but seems like way too much effort for this minor inconsistency.

Comment (BrittanyIRL) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: I guess I'm looking at this in a different way, just giving the anchor tag the info it needs without needing to know anything about the SVG at all. It announces better and feels more straight forward. Also allows implementation to be uniform in the component.

Comment (swissspidy) [reply assets/src/edit-story/app/media/media3p/attribution.js:137]: Works for me. Let's keep this as-is.

Anything beyond that is out of scope for this fix.

**Review by swissspidy — APPROVED** [review]

**Review by spacedmonkey — APPROVED** [review]

**Review by embarks — APPROVED** [review]

**Review by maxyinger — APPROVED** [review]
