### PR TITLE
Fix displaying whiteout in Text edit mode

### LINKED ISSUE #1883: Text element: Edit mode background not extending with new lines
## Bug Description

When adding a new line in editor, the edit mode background does not extend with it and stays transparent.

## Expected Behaviour

The text edit mode background should extend when adding new lines (and also reduce if removing lines)

## Steps to Reproduce

- Add a text element
- Go to edit mode
- Add a new line
- See the edit background area not updating.

## Screenshots
edit-mode

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary

- Adds whiteout to the part of the markup that changes its height when adding new lines.
- Also, adds whiteout only if the background mode is not Fill -- otherwise this might interfere with the true color of the background if there's opacity.

## User-facing changes

For edit mode only!
Change in case of media that has opacity: media with opacity now doesn't have whiteout and displays the actual color. In case of media without opacity, there is no change.
Before:
before

After:
after

## Testing Instructions
1. Add a text element (set the Page background to something red for visibility)
2. Go to edit mode
3. Add a new line
4. Verify the background whiteout is extending to the new lines, too

---

Fixes #1883

### CODE REVIEW

File: assets/src/edit-story/components/canvas/editElement.js [hunk 1]
```diff
@@ -31,14 +31,11 @@ import {
...
 import { useUnits } from '../../units';
 
-// Background color is used to make the edited element more prominent and
-// easier to see.
 const Wrapper = styled.div`
 	${elementWithPosition}
 	${elementWithSize}
 	${elementWithRotation}
 	pointer-events: initial;
-	background-color: ${({ theme }) => theme.colors.whiteout};
```
Comment (miina) [inline assets/src/edit-story/components/canvas/editElement.js:41]: Note: Since this is now moved to text edit only then the whiteout is not added to Media edit mode, however:
1. It's "behind" the media anyway and not visible.
2. It would be visible in case of media with opacity, however, that would interfere with how the image looks like, so IMHO it's not really necessary.

LMK if you think otherwise.

Comment (swissspidy) [reply assets/src/edit-story/components/canvas/editElement.js:41]: could you perhaps add some before/after screenshots in the "user-facing changes" section?

Comment (miina) [reply assets/src/edit-story/components/canvas/editElement.js:41]: Sure, added!

Comment (miina) [reply assets/src/edit-story/components/canvas/editElement.js:41]: Hmm, now looking at it, it looks like the image color is changing anyway when there's opacity -- with the grayout!

File: assets/src/edit-story/elements/text/edit.js [hunk 2]
```diff
@@ -64,6 +66,7 @@ const Wrapper = styled.div`
     border: 1px solid ${({ theme }) => theme.colors.mg.v1}70;
     pointer-events: none;
   }
+  background-color: ${({ theme }) => theme.colors.whiteout};
```
Comment (barklund) [inline assets/src/edit-story/elements/text/edit.js]: Could we move this line up to [line 57](https://github.com/google/web-stories-wp/pull/2554/files#diff-5f4f624867fd96363e2603afb736f301R57) in stead? It's a bit weird here at the bottom...

**Review by barklund — APPROVED** [review]
Seems to work fine - for both images and text.
