### PR TITLE
Work around KSES for users without unfiltered_html capability

### LINKED ISSUE #1121: Broken story markup for users without `unfiltered_html` capabilities
## Bug Description

I noticed this while debugging a story. Not sure how it happened, but in this case there was no closing `</strong>` tag on a text element.

**Why P0?**

This broken markup led to a completely broken layout on the frontend. It was impossible to read the story.

Possibly related: #413, #1007, #1093.

## Expected Behaviour

There should never be broken markup like this.

## Steps to Reproduce

Drafts:

1. Log in as user with role **Author**
1. Create a new story
1. Add a new text element
1. Make the text bold
1. Add a new image
1. Rotate image
1. Preview story
1. Notice how story is broken

Published stories:

1. Log in as user with role **Author**
1. Create a new story
1. Publish story
1. Add a new text element
1. Make the text bold
1. Add a new image
1. Rotate image
1. Preview story
1. Notice how story is broken

## Screenshots

Screenshot 2020-04-09 at 08 24 21

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

Drafts:

1. Log in as user with role **Author**
1. Create a new story
1. Add a new text element
1. Make the text bold
1. Rotate element
1. Add background color with opacity
1. Preview story
1. Verify story is displayed as expected

Published stories:

1. Log in as user with role **Author**
1. Create a new story
1. Publish story
1. Add a new text element
1. Make the text bold
1. Add a new image
1. Rotate image
1. Preview story
1. Story should be displayed as expected

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

This PR aims to solve the critical KSES bug for users without the `unfiltered_html` capability (authors on single site / editors and site admins on multisite).

The solution is loosely based on the one we came up with for the legacy stories editor in https://github.com/ampproject/amp-wp/pull/2691.

## Relevant Technical Choices

* Fully disables KSES for `post_content_filtered`, where we story our story data as a JSON blob. This JSON data is only ever used in the editor, and isn't directly displayed on the frontend or anything. Since we're in full control of it, it should be safe to remove.  
  Related core ticket: https://core.trac.wordpress.org/ticket/38715
* Copies over `safecss_filter_attr` from core with two big modifications:  
    1. Extends the list of allowed elements and attributes for KSES, and the list of allowed CSS properties so that our stories remain valid and unchanged.  
    **Note:** The extension is done via the `safe_style_css` filter so it's easier to maintain.
    1. Adds support for `transform` CSS property. Otherwise this would prevent inline styles like `transform: rotate(90deg);` because the function strips any parentheses.  
    **Note:** This could potentially be contributed upstream.
    1. Adds support for `rgb(a)` usage for colors. Otherwise this would prevent things like adding opacity to colors.  
    **Note:** This could potentially be contributed upstream (https://core.trac.wordpress.org/ticket/24157).
* Only applies these changes for the REST API context, to minimize risk affecting other parts of the site.
* Adds new `Stories_Autosaves_Controller` to make sure KSES changes also apply when creating autosaves (i.e. when previewing a published story)

## To-do

* [ ] Field Testing
* [x] Add E2E tests
* [ ] Investigate failing E2E tests on Firefox Nightly

## Testing Instructions

1. Log in as user with role Author
1. Create a new story
1. Add a new text element
1. Make the text bold
1. Rotate element
1. Add background color with opacity
1. Preview story
1. Verify story is displayed as expected

---

Fixes #1121

### CODE REVIEW

File: includes/Plugin.php [hunk 1]
```diff
@@ -75,135 +69,28 @@ public function register() {
...
+		$embed_controller->register_routes();
 
-		foreach ( $allowed_tags as &$allowed_tag ) {
-			$allowed_tag['animate-in']          = true;
-			$allowed_tag['animate-in-duration'] = true;
-			$allowed_tag['animate-in-delay']    = true;
-			$allowed_tag['animate-in-after']    = true;
-			$allowed_tag['layout']              = true;
-		}
+		$templates_autosaves = new Stories_Autosaves_Controller( Template_Post_Type::POST_TYPE_SLUG );
```
Comment (spacedmonkey) [inline includes/Plugin.php:89]: This is not required. Post type controllers are automatically registered. https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/rest-api.php#L208

**Review by spacedmonkey — APPROVED** [review]
LGTM
