### PR TITLE
Switch tab to design when selection is changing

### LINKED ISSUE #716: Add new elements and document sidebar
## Bug Description

After inserting a new element and the document sidebar is being displayed, design sidebar is not shown to user.

## Expected Behaviour

After a user inserts a new element, the design sidebar should be displayed. 

## Steps to Reproduce

- User inserts element 
- User navigates to document sidebar
- User insert a second element. 
- Document sidebar is still displayed. 

## Screenshots

Screenshot from 2020-03-23 13-01-59

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
Fixes #716

Switches Document tab back to Design tab.

The original issue covers adding a new element only, however, when the editor is manipulating the elements, it's likely that the Design panel is more beneficial.

### CODE REVIEW

**Comment by swissspidy** [comment]
> when the editor is manipulating the elements, it's likely that the Design panel is more beneficial.

That was my thinking as well 👍

**Comment by miina** [comment]
> That was my thinking as well 👍 

@barklund's recommendation :)

File: assets/src/edit-story/components/inspector/inspectorProvider.js [hunk 1]
```diff
@@ -52,6 +57,20 @@ function InspectorProvider({ children }) {
     setInspectorContentHeight(height)
   );
 
+  useEffect(() => {
+    if (selectedElementIds.length > 0 && tab === DOCUMENT) {
+      setTab(DESIGN);
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/inspectorProvider.js]: What's the complaint? Please add disable reason

Comment (barklund) [reply assets/src/edit-story/components/inspector/inspectorProvider.js]: Ah, it's the missing `tab`? Yeah, that definitely needs a comment to clarify, that it's very much on purpose. Or you could create a ref to hold current tab and avoid it - that might be a cleaner solution really.

File: assets/src/edit-story/components/inspector/inspectorProvider.js [hunk 2]
```diff
@@ -52,6 +57,20 @@ function InspectorProvider({ children }) {
...
+  }, [selectedElementIds]);
+
+  useEffect(() => {
+    if (tab === DOCUMENT) {
+      setTab(DESIGN);
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [currentPage]);
```
Comment (barklund) [inline assets/src/edit-story/components/inspector/inspectorProvider.js]: I don't know if I'd rather have a single effect or two different. I guess this duplication makes sense, as it's all about dependency triggering.

**Review by barklund — COMMENTED** [review]
Looks good, but maybe move current tab to a ref to avoid dep lint disabling.

File: assets/src/edit-story/components/inspector/inspectorProvider.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/inspector/inspectorProvider.js]: It's probably more clear this way since in the case of `currentPage` the change should happen even if no elements are selected.

File: assets/src/edit-story/components/inspector/inspectorProvider.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/inspector/inspectorProvider.js]: Done!

**Review by barklund — APPROVED** [review]
LGTM!

**Review by dvoytenko — APPROVED** [review]

**Comment by swissspidy** [comment]
Added to the alpha branch 👍
