### PR TITLE
Editor: Embed not working for scheduled story

### LINKED ISSUE #11371: Editor: Embed not working for scheduled story
## Feature Description

When I create a post from a scheduled web story the preview shows my home page at the editor because the web story is not published yet. I know that is not a big deal:
 
Screen Shot 2022-04-27 at 11 55 51

## Alternatives Considered

If the Web Story is not posted yet, display the Web Story, cover image as a placeholder

### PR DESCRIPTION
**Pull request by timarney**
## Context

When scheduling a web story the preview shows the website 404 vs the story preview

https://github.com/GoogleForCreators/web-stories-wp/issues/11371#issue-1217194875

## Summary

Removes esc_url from the $story->get_url()

**Before**
not-found

**After**
Screen Shot 2022-05-17 at 5 31 56 AM

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:
On current main

1. Create a story
2. Schedule for a future date
3. Embed from post using the dialog that pops up
4. Story shows as website 404 as the embed (http://localhost:8899/wp-admin/post-new.php?from-web-story=1333)

Using this branch 

1. Create a story
2. Schedule for a future date
3. Embed from post using the dialog that pops up
4. Story shows as the embed (http://localhost:8899/wp-admin/post-new.php?from-web-story=1333)

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11371

### CODE REVIEW

File: tests/phpunit/integration/tests/Admin/Admin.php [hunk 1]
```diff
@@ -118,6 +118,27 @@ public function test_prefill_post_content(): void {
 		$this->assertStringContainsString( $poster, $result );
 	}
 
+	/**
+	 * @covers ::prefill_post_content
+	 */
+	public function test_prefill_post_content_url_scheduled(): void {
```
Comment (swissspidy) [inline tests/phpunit/integration/tests/Admin/Admin.php:125]: This test is not currently working because

1. The post is missing a `post_date` in the future
2. It uses `get_post( $story_id )` instead of `get_post( self::$post_id )`
3. The assertions are not precise enough

This should work:

```php
/**
 * @covers ::prefill_post_content
 */
public function test_prefill_post_content_url_scheduled(): void {
	wp_set_current_user( self::$admin_id );

	$story_id = self::factory()->post->create(
		[
			'post_type'    => \Google\Web_Stories\Story_Post_Type::POST_TYPE_SLUG,
			'post_status'  => 'future',
			'post_date'    => ( new DateTime( '+1day' ) )->format( 'Y-m-d H:i:s' ),
			'post_title'   => 'Example',
			'post_content' => '<html><head></head><body><amp-story standalone="" publisher="Web Stories" title="Example" poster-portrait-src="https://example.com/image.png"></amp-story></body></html>',
		]
	);

	$_GET['from-web-story'] = $story_id;
	$result                 = $this->instance->prefill_post_content( 'current', get_post( self::$post_id ) );

	$this->assertStringNotContainsString( '"url":"http://example.org/?post_type=web-story&#038;p=7', $result );
	$this->assertStringContainsString( '"url":"http://example.org/?post_type=web-story&p=7', $result );
}
```

**Review by swissspidy — APPROVED** [review]
