### PR TITLE
KSES: Prevent markup removal when editing stories via "All Stories" page

### LINKED ISSUE #6076: KSES not applied when editing stories via "All Stories" page
## Bug Description

When a non-superadmin user causes a story to hit the WP save_post filter, the story HTML is aggressively sanitized, effectively deleting the story content.

## Expected Behaviour

Non-superadmin users should be able to make edits (such as changing the post status, applying categories, etc.) via the WP interface (i.e. 'quick edit', 'bulk edit' or 'bin' actions) in the 'All Stories' view of stories.

## Steps to Reproduce

1. When logged in as a non-superadmin user, make a change to a story via the 'All Stories' screen such as changing the post status, adding or changing a category, or moving a story to the bin (all actions that use the WP save_post filter).
2. The post's content is sanitised before it's inserted into the database, stripping the head off the content resulting in malformed HTML
3. The story displays no content either on the edit screen or on the preview/published URL

This problem does NOT occur when logged in as a superadmin.

A similar sanitization issue was noticed here: https://github.com/google/web-stories-wp/pull/5765

## Screenshots

https://d.pr/jVaqHq

## Additional Context

- We are on a multisite instance of WordPress
- Plugin Version: 1.3
- WordPress Version: 5.6

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Context

Fix KSES quick edit. 

## Relevant Technical Choices
 
Hook into admin ajax early and setup KSES class. 
Added E2E for publishing story as author and doing quick editor. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

Quick edit
----
1. Login as an author
2. Create a story. 
3. Check preview to see story looks as expected. 
4. Go All stories. 
5. Quick edit your story and change something, like the title. 
6. Preview story. 

Bulk actions
---------
1. Login as an author
2. Create a story. 
3. Check preview to see story looks as expected. 
4. Go All stories. 
5. Select all stories
6. Select bulk edit from actions dropdown
7. Change the status of the stories to draft ( or published if already published )
6. Preview story. 

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6076

### CODE REVIEW

File: tests/e2e/specs/wordpress/quickEdit.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+    const storyTitleNew = 'Test quick edit – updated.';
+
+    await expect(page).toMatch(storyTitleNew);
+    await Promise.all([
+      page.waitForNavigation(),
+      await expect(page).toClick(`a[aria-label="View “${storyTitleNew}”"]`),
+    ]);
+
+    await expect(page).not.toMatch('amp=""');
```
Comment (spacedmonkey) [inline tests/e2e/specs/wordpress/quickEdit.js]: @swissspidy Should I add a percy screenshot here?

**Comment by swissspidy** [comment]
@spacedmonkey Does this also fix the issue for bulk edit? Looking at the ticket again it mentions bulk edit in the screenshot: https://d.pr/jVaqHq

File: tests/e2e/specs/wordpress/quickEdit.js [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+    await expect(page).toClick('button', { text: 'Publish' });
+
+    await expect(page).toMatchElement('button', { text: 'Dismiss' });
+
+    await visitAdminPage('edit.php', 'post_type=web-story');
+
+    await expect(page).toMatch(storyTitle);
+
+    // Make row actions appear.
+    const elmId = await page.evaluate((filename) => {
```
Comment (swissspidy) [inline tests/e2e/specs/wordpress/quickEdit.js]: filename?

File: tests/e2e/specs/wordpress/quickEdit.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+describe('Quick Edit', () => {
+  beforeAll(async () => {
+    await loginUser('author', 'password');
+  });
+
+  afterAll(async () => {
+    await switchUserToAdmin();
+  });
+
+  it('save quick edit', async () => {
```
Comment (swissspidy) [inline tests/e2e/specs/wordpress/quickEdit.js]: More accurate would be something like "it should save story without breaking markup"

File: tests/e2e/specs/wordpress/quickEdit.js (hunk 1 above)
Comment (swissspidy) [reply tests/e2e/specs/wordpress/quickEdit.js]: I don't think this is a good assertion for this test.

If we have a better assertion (for example look for `amp-story` element—this would be removed without KSES), then we don't necessarily need a screenshot

File: tests/e2e/specs/wordpress/quickEdit.js [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  loginUser,
+  switchUserToAdmin,
+  visitAdminPage,
+} from '@wordpress/e2e-test-utils';
+/**
+ * Internal dependencies
+ */
+import { createNewStory } from '../../utils';
+
+describe('Quick Edit', () => {
```
Comment (swissspidy) [inline tests/e2e/specs/wordpress/quickEdit.js:29]: Nice test overall! Good idea.

File: includes/Admin.php [hunk 5]
```diff
@@ -191,4 +192,19 @@ public function prefill_post_title( $title ) {
...
+	 * @since 1.4.0
+	 *
+	 * @return void
+	 */
+	public function load_kses_before_inline_save() {
+		if ( ! isset( $_POST['post_type'] ) || Story_Post_Type::POST_TYPE_SLUG !== $_POST['post_type'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing
+			return;
+		}
+		$kses = new KSES();
+		$kses->init();
```
Comment (swissspidy) [inline includes/Admin.php]: We usually do `$kses->remove_filters();` afterwards to clean things up nicely again. Can we do that here as well? Is there a matching hook after saving?

If not, do we need to hook into something other than `wp_ajax_inline-save`?

`save_post` + `wp_after_insert_post` seems fitting, but the latter is 5.6 only...

**Comment by swissspidy** [comment]
By the way, the checklist is there to fill out :-)

File: includes/Admin.php (hunk 5 above)
Comment (spacedmonkey) [reply includes/Admin.php]: The function [wp_ajax_inline_save](https://developer.wordpress.org/reference/functions/wp_ajax_inline_save/), calls `wp_die` after `edit_post`. I don't see the issue here, about keeping these hooked.

File: tests/e2e/specs/wordpress/quickEdit.js (hunk 2 above)
Comment (spacedmonkey) [reply tests/e2e/specs/wordpress/quickEdit.js]: Fixed

File: tests/e2e/specs/wordpress/quickEdit.js (hunk 3 above)
Comment (spacedmonkey) [reply tests/e2e/specs/wordpress/quickEdit.js]: Fixed

**Comment by spacedmonkey** [comment]
@swissspidy I didn't see the part about bulk editing. There is going to be a problem, as bulk editing works very differently from quick edit. 

There are also no filters or works to play with [here](https://github.com/WordPress/wordpress-develop/blob/bcc26de235cea8d42ad295c4c5aa999379b84cca/src/wp-admin/edit.php#L181-L191). 

Either we refactor KSES class to hook in before and after save of post. Say `wp_insert_post_empty_content` filter and `wp_insert_post` action. But that is a very big change. But that would also fix if you save on say WP CLI as well. 

The larger question, why not just enable these filters / attributes everywhere. Why don't we do this in plugin call. 

```
		$this->kses = new KSES();
		add_action( 'init', [ $this->kses, 'init' ] );
```

**Comment by swissspidy** [comment]
> Either we refactor KSES class to hook in before and after save of post. Say `wp_insert_post_empty_content` filter and `wp_insert_post` action. But that is a very big change. But that would also fix if you save on say WP CLI as well.

Let's explore this route.

Maybe with actions `pre_post_update` and `wp_insert_post ` instead. Why?

Insertion of stories with AMP markup only happens through our editor, so we can keep current KSES logic in the REST API controller.

However, updates, can happen everywhere (quick edit, bulk edit, CLI).

> The larger question, why not just enable these filters / attributes everywhere. Why don't we do this in plugin call.
> 
> ```
> 		$this->kses = new KSES();
> 		add_action( 'init', [ $this->kses, 'init' ] );
> ```

Our KSES class should only run for stories, not for everything and every user.

**Comment by spacedmonkey** [comment]
> Maybe with actions pre_post_update and wp_insert_post instead. Why?

Doing this doesn't work 
```
$kses = new KSES();
add_action( 'pre_post_update', [ $kses, 'init'] );
add_action( 'wp_insert_post', [ $kses, 'remove_filters'] );
```

Pre post update fires on line [4039](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L4039). However `sanitize_post` is called on line [3713](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L3713). There is no filter or hook before `sanitize_post` is called.

We could use [wp_insert_post_data](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L4024). However `unsanitized_postarr` was only adding in 5.4.1

I think we may have to enable kses globally

**Comment by swissspidy** [comment]
> > Maybe with actions pre_post_update and wp_insert_post instead. Why?
> 
> Doing this doesn't work
> 
> ```
> $kses = new KSES();
> add_action( 'pre_post_update', [ $kses, 'init'] );
> add_action( 'wp_insert_post', [ $kses, 'remove_filters'] );
> ```
> 
> Pre post update fires on line [4039](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L4039). However `sanitize_post` is called on line [3713](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L3713). There is no filter or hook before `sanitize_post` is called.
> 
> We could use [wp_insert_post_data](https://github.com/WordPress/wordpress-develop/blob/e2bb95aa508ea4c630f3df1168479451874a4734/src/wp-includes/post.php#L4024). However `unsanitized_postarr` was only adding in 5.4.1
> 
> I think we may have to enable kses globally

Hmm looks like it :/ And there's no ideal filter in `sanitize_post_field` that passes the post ID or anything.

Let's give it a try then..

**Comment by spacedmonkey** [comment]
@swissspidy I have a really hacky workaround for bulk actions. Can you take a look at [this](https://github.com/google/web-stories-wp/pull/6077/commits/fbd691d213e1ed85a6570a06768783972dc18118). It worked in my testing, but not sure it will work 100% of the time. If you are happy with this workaround, i will add some tests to validate it.

**Comment by swissspidy** [comment]
> @swissspidy I have a really hacky workaround for bulk actions. Can you take a look at [this](https://github.com/google/web-stories-wp/pull/6077/commits/fbd691d213e1ed85a6570a06768783972dc18118). It worked in my testing, but not sure it will work 100% of the time. If you are happy with this workaround, i will add some tests to validate it.

Does this work for "Restore from trash" as well?

It wouldn't work for cases where one updates a story via WP-CLI (or some other ways I can't think of right now).

I'm just worried that we'll be constantly adding workarounds for every different scenario that pops up — like playing whac-a-mole

**Comment by spacedmonkey** [comment]
> I'm just worried that we'll be constantly adding workarounds for every different scenario that pops up — like playing whac-a-mole

I agree, there are just not the filters and actions in the right places to do this. I think we have to add it everywhere otherwise we get future bug reports. I will change this PR.

File: includes/KSES.php [hunk 6]
```diff
@@ -26,20 +26,46 @@
...
 	public function init() {
+
+		$create_posts     = false;
+		$post_type_object = get_post_type_object( Story_Post_Type::POST_TYPE_SLUG );
+		if (
+			$post_type_object instanceof WP_Post_Type &&
+			property_exists( $post_type_object->cap, 'create_posts' )
+		) {
+
+			$create_posts = current_user_can( $post_type_object->cap->create_posts );
```
Comment (swissspidy) [inline includes/KSES.php]: Would `$post_type_object->cap->edit_posts` be more correct?

File: includes/REST_API/Stories_Base_Controller.php [hunk 7]
```diff
@@ -155,7 +154,7 @@ public function prepare_item_for_response( $post, $request ) {
 	 */
 	public function create_item( $request ) {
 		$kses = new KSES();
-		$kses->init();
+		$kses->add_filters();
```
Comment (swissspidy) [inline includes/REST_API/Stories_Base_Controller.php]: These could keep using `init()`, no?

File: includes/KSES.php [hunk 8]
```diff
@@ -26,20 +26,46 @@
...
+		}
+
+		if ( $create_posts ) {
+			$this->add_filters();
+		}
```
Comment (swissspidy) [inline includes/KSES.php]: The confusing part about conditionally adding these filters is that we check whether the user can edit stories, but the filters actually apply to all post types.

Hmm 🤔

File: includes/KSES.php (hunk 6 above)
Comment (spacedmonkey) [reply includes/KSES.php]: This is what I did originally and it didn't work. `create_posts` maps to `edit_web-stories`, which both sub and author user levels have. 
https://github.com/google/web-stories-wp/blob/42ddafa62692caaeca3dd0859733e2363912fd7a/includes/Story_Post_Type.php#L265
https://github.com/google/web-stories-wp/blob/42ddafa62692caaeca3dd0859733e2363912fd7a/includes/Story_Post_Type.php#L257

File: includes/KSES.php (hunk 8 above)
Comment (spacedmonkey) [reply includes/KSES.php]: Why give a user that does have access to edit stories these capabilities? The reason we add these filter so you can publish web stories, if you can't create web stories, there is no point.

File: includes/REST_API/Stories_Base_Controller.php (hunk 7 above)
Comment (spacedmonkey) [reply includes/REST_API/Stories_Base_Controller.php]: We don't need to capability check here, the rest api does that for us. Also `add_filters` is what `init` used be. This logic is unchanged from before, just different method names.

File: includes/KSES.php (hunk 6 above)
Comment (swissspidy) [reply includes/KSES.php]: So said mapping is done here:

https://github.com/WordPress/wordpress-develop/blob/8d7e7d03ff8ad036678851f959792f76d9759025/src/wp-includes/post.php#L1624-L1627

If it maps to that, and both roles have it, why doesn't the check for it work then? 🤔 

Certainly `$post_type_object->cap->create_posts === $post_type_object->cap->edit_posts` in this case.

Comment (spacedmonkey) [reply includes/KSES.php]: For some reason that didn't work, but just tried again and seems to work. Changed in https://github.com/google/web-stories-wp/pull/6077/commits/4714be3059a6260c0fe274f4e3d24a93b01c3073

File: includes/KSES.php (hunk 8 above)
Comment (spacedmonkey) [reply includes/KSES.php]: Also it worth noting, init was poorly named in the first place. init methods normally map to add action init. Add filters is much cleaner. Now that init used to hook into add action, this is make sense to me. It just changing the name of the method to something clearer. I can revert if it is a problem, but what do you call the init function?

File: includes/KSES.php [hunk 9]
```diff
@@ -26,20 +26,46 @@
...
+
 /**
  * KSES class.
  *
  * Provides KSES utility methods to override the ones from core.
  */
 class KSES {
 	/**
-	 * Initializes KSES filters for stories.
+	 * Initializes KSES filters for stories only if capability check are met.
```
Comment (swissspidy) [inline includes/KSES.php]:
```suggestion
	 * Initializes KSES filters for all post types if user can edit stories.
```

File: includes/KSES.php (hunk 8 above)
Comment (swissspidy) [reply includes/KSES.php]: All I am saying is that this is confusing:

> If user can edit _stories_, allow user to use more markup in _all post types_

I am not saying it is _bad_ or anything. Just _confusing_, because there simply isn't another way (as we have found out).

> Also it worth noting, init was poorly named in the first place. init methods normally map to add action init.

FWIW this was named after `kses_init()`. I am not suggesting to rename the method now.

File: includes/REST_API/Stories_Base_Controller.php (hunk 7 above)
Comment (swissspidy) [reply includes/REST_API/Stories_Base_Controller.php]: Hmm actually, since `KSES` is now running on `init`, we don't need KSES here anymore, do we? We could just remove this code.

File: includes/REST_API/Stories_Autosaves_Controller.php [hunk 10]
```diff
@@ -142,7 +142,7 @@ public function register_routes() {
 	 */
 	public function create_item( $request ) {
 		$kses = new KSES();
-		$kses->init();
+		$kses->add_filters();
 		$response = parent::create_item( $request );
 		$kses->remove_filters();
 		return $response;
```
Comment (swissspidy) [inline includes/REST_API/Stories_Autosaves_Controller.php]: Same here. Since KSES now runs on `init`, no need to run it here too I think?

So we could just remove this entire method here.

**Comment by spacedmonkey** [comment]
@swissspidy I have done a big refactor, removing the remove_filter method and just trigger the init method once. This removes a lot of code, so you will need to re-review.

File: tests/e2e/specs/wordpress/quickEdit.js (hunk 1 above)
Comment (swissspidy) [reply tests/e2e/specs/wordpress/quickEdit.js]: I still think this not an ideal assertion, marking as unresolved.

**Comment by swissspidy** [comment]
Could you please add some thorough QA instructions?

Code looks good, but gonna do some preliminary testing too.

**Comment by spacedmonkey** [comment]
> Could you please add some thorough QA instructions?

Done

**Comment by swissspidy** [comment]
> > Could you please add some thorough QA instructions?
> 
> Done

Let's add the other scenarios to the testing instructions as well. Trashing & restoring, bulk edit, etc. Not just quick edit.

**Review by swissspidy — CHANGES_REQUESTED** [review]
Test are currently failing but otherwise looks good

**Comment by swissspidy** [comment]
Still failing

> PHP Fatal error:  Cannot use Google\Web_Stories\KSES as KSES because the name is already in use in /home/runner/work/web-stories-wp/web-stories-wp/tests/phpunit/includes/KsesSetup.php on line 6

Nit: `KSES_Setup.php` seems more readable than `KsesSetup`

**Review by swissspidy — APPROVED** [review]
