### PR TITLE
Library dragging: fix an issue where clone disrupts other functionality

### LINKED ISSUE #7154: Library: Draggable clone covers too much in case of large media.
## Bug Description
When the draggable media is large enough, it can cover some parts of the library making it non-functional, e.g. the "More" button.

## Expected Behaviour
1. More button should always be functional.

## Screenshots
See https://github.com/google/web-stories-wp/issues/6027#issuecomment-812669370

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Context
When dragging from library, the clone element can cover some other functionality and cause potential issues.

## Summary
This PR removes pointer events from the clone layer (thanks, @barklund, see https://github.com/google/web-stories-wp/issues/6027#issuecomment-812669370 )

## User-facing changes
N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.
# Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7154

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/shared/libraryMoveable.js [hunk 1]
```diff
@@ -283,7 +283,7 @@ function LibraryMoveable({
           <InOverlay
             ref={overlayRef}
             zIndex={1}
-            pointerEvents="initial"
+            pointerEvents="none"
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/shared/libraryMoveable.js:285]: Looks like this is causing some test failures...

File: assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js [hunk 2]
```diff
@@ -275,23 +270,4 @@ describe('TextSets', () => {
       'The possibilities for innovation are not, by any means, exhausted. Technological development is always offering new opportunities for innovative design. But innovative design always develops in tandem with innovative technology, and can never be an end in itself.'
     );
   });
-
-  it('should allow inserting a text set', () => {
```
Comment (miina) [inline assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js:279]: Removing this since we're relying on Moveable for adding a text set and that only displays when hovering over the text set -- can't really test it here.

Comment (barklund) [reply assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js:279]: Do we also rely on Moveable for just a click?

**Review by barklund — COMMENTED** [review]
Hm, not fully sure what this fixes and doesn't fix actually.

File: assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/components/library/panes/text/textSets/test/textSet.js:279]: Yes, previously it was a mix of Moveable vs not Moveable which was not correct really. Basically if was really only Moveable before as well, the non-Moveable was really a backup but it's not needed.

We do this on the element on canvas as well -- Moveable detects a click as dragging and we have to verify inside the Moveable that it's actually a click. If it's a click, we select the element.

**Comment by miina** [comment]
> Hm, not fully sure what this fixes and doesn't fix actually.

This fixes the issue you discovered with [the clone covering some areas in the library](https://github.com/google/web-stories-wp/issues/6027#issuecomment-812669370) and sometimes this disrupts dragging from the library and also the "More" menu.

**Review by barklund — APPROVED** [review]
