### PR TITLE
Text Sets A11Y

### LINKED ISSUE #6295: Text Sets A11Y
## Bug Description

Two observations at a glance

* `TextSetItem` uses `role=listitem`, but there's no parent with `role=list`
* Every text set has the same label `Insert Text Set` which is not helpful at all
* Category selection/deselection doesn't seem to get announced to screen readers (`useLiveRegion` might be helpful here)
* To screen readers it's not clear what the list of categories does. Need to announce their purpose, perhaps via `aria-label` or by using `VisuallyHidden`

[Complete list of text sets](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A30878)

## Expected Behaviour

* List items need to be in a proper list
* Each text set should be labelled with its individual name

## Additional Context

- Plugin Version: 1.3
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by embarks**
## Context
From the ticket:
- Category selection/deselection doesn't seem to get announced to screen readers
- To screen readers it's not clear what the list of categories does. 

## Summary
- add more descriptive aria-label to text set chip group 
- add an announcement when the filter is selected/deselected

## Relevant Technical Choices
- added `ariaLabel` prop to `chipGroup` to make the announcement of the filter list more descriptive
- used `useLiveRegion` to speak the deselection/selection of a filter

## To-do
NA

## User-facing changes
For users using a screen reader, focusing the filter chips on the text sets list now reads "Select filter for text sets list". Selecting a filter is now announced like "Selected text set filter `<filter name>`".

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Turn on your screen reader
2. Focus the the filter chips on the text sets (All, Cover, etc) list now reads "Select filter for text sets list" before announcing the name on the chip which is focused. 
3. Press enter or space to select a chip 
4. Screen readers should now announce "Selected text set filter `<filter name>`". Selecting all will read "Show all text sets"

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
NA

### Does this PR change what data or activity we track or use?
NA

### Does this PR have a legal-related impact?
NA

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6295

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 1]
```diff
@@ -139,12 +140,26 @@ function TextSetsPane({ paneRef }) {
...
-    });
-  }, []);
+  const speak = useLiveRegion('polite');
+
+  const handleSelectedCategory = useCallback(
+    (selectedCategory) => {
+      setSelectedCat(selectedCategory);
+      speak(
+        selectedCategory === null
+          ? __(`Deselected text set filter`, 'web-stories')
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]:
```suggestion
          ? __('Deselected text set filter', 'web-stories')
```

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 2]
```diff
@@ -139,12 +140,26 @@ function TextSetsPane({ paneRef }) {
...
+          : sprintf(
+              /* translators: %s: filter category name */
+              __(`Selected text set filter %s`, 'web-stories'),
```
Comment (BrittanyIRL) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]:
```suggestion
              __('Selected text set filter %s', 'web-stories'),
```

**Review by BrittanyIRL — APPROVED** [review]
LGTM!

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 3]
```diff
@@ -139,12 +140,26 @@ function TextSetsPane({ paneRef }) {
     [textSets]
   );
 
-  const handleSelectedCategory = useCallback((selectedCategory) => {
-    setSelectedCat(selectedCategory);
-    localStore.setItemByKey(`${LOCAL_STORAGE_PREFIX.TEXT_SET_SETTINGS}`, {
-      selectedCategory,
-    });
-  }, []);
+  const speak = useLiveRegion('polite');
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: nit:`'polite'` is the default so this isn't needed but I don't think it's a big deal so it's fine if we leave it too! Love seeing this used more though

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 1 above)
Comment (samwhale) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: 🤔 This is good. What do you think about making this be something like 'show all' or 'no filter applied'? I don't know which way I'm leaning for the announcement. I see two options:
1. The removal of a filter
2. How many text sets are being displayed

Not sure what is easier to understand, but I think what you have now is totally good too

**Review by samwhale — APPROVED** [review]
Looks great works great!

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 1 above)
Comment (embarks) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: I think I like `Show all text sets` best

**Review by maxyinger — APPROVED** [review]
