### PR TITLE
Workspace: Fix type guards to avoid crash when adding media

### LINKED ISSUE #12784: Editor crashes when uploading/inserting media
## Bug Description

The editor crashes when dragging an image file from Chrome's download bar onto an element. Here is the crash report:

TypeError: Cannot read properties of undefined (reading 'id')

    at StoryProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:21:12251)
    at https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:266057
    at SnackbarProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/1873.js?ver=62b94bdfd4d9753f46d0:9:54908)
    at https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:266057
    at HistoryProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:17:2986813)
    at https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:266057
    at Media3pApiProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:32:22270)
    at https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:266057
    at APIProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:17:2983692)
    at https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:266057
    at ConfigProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:17:2983397)
    at ErrorBoundary (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:21:16533)
    at Fe (https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:256831)
    at le (https://lucksany.com/wp-content/plugins/web-stories/assets/js/6071.js?ver=62b94bdfd4d9753f46d0:1:253875)
    at FlagsProvider (https://lucksany.com/wp-content/plugins/web-stories/assets/js/3371.js?ver=62b94bdfd4d9753f46d0:1:205038)
    at StoryEditor (https://lucksany.com/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=62b94bdfd4d9753f46d0:36:37777)

## Steps to Reproduce

1. in Chrome, download image from https://www.pexels.com/ 
2. Go to add a new story
3. Add an element
4. Drag file from download bar on to element

## Screenshots

https://user-images.githubusercontent.com/66372350/206223414-7522f4e0-34ab-47d5-b7c8-f4c3a254eef6.mov

## Additional Context

- Plugin Version: 1.28.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by barklund**
## Context

This fixes the `elementIs` usage inside immer produce functions, to use a draft-safe variant, that actually checks that the property does exist on the element in question.

## User-facing changes

_No bugs_

## Testing Instructions

See original issue

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12784

### CODE REVIEW

File: packages/elements/src/utils/elementIs.ts [hunk 1]
```diff
@@ -60,4 +66,44 @@ const elementIs = {
   sequenceMedia: isSequenceMediaElement,
 };
 
-export default elementIs;
+function isDraftMediaElement(e: Draft<Element>): e is Draft<MediaElement> {
+  return 'resource' in e && Boolean(e.resource);
```
Comment (swissspidy) [inline packages/elements/src/utils/elementIs.ts]: Wouldn't that `Boolean()` check also work for `isMediaElement` et al and then we don't need all these separate functions?

```ts
function isMediaElement(e: Element): e is MediaElement {
  return 'resource' in e && Boolean(e.resource);
}
```

Right now it's a bit repetitive and also makes `elements` depend on `immer` just for of these type guards.

Comment (barklund) [reply packages/elements/src/utils/elementIs.ts]: It would work yes, but the type of the function would be wrong, no? And we could probably change the dependency to be @types/immer instead?

Comment (barklund) [reply packages/elements/src/utils/elementIs.ts]: We could fix the type with an overload though. But that still comes with a dependency on the immer types.

Comment (barklund) [reply packages/elements/src/utils/elementIs.ts]: Cleaned it up a bit and simplified some usages of the filter (if you call filter with _just the guard_, TypeScript can do its magic)

File: package-lock.json [hunk 2]
```diff
@@ -46932,7 +46943,7 @@
         "@googleforcreators/patterns": "*",
         "@googleforcreators/react": "*",
         "draft-js": "^0.11.7",
-        "draft-js-export-html": "git+ssh://git@github.com/swissspidy/draft-js-export-html.git#366642f1c6e5090f24f7a66a357328115e4a6a62",
+        "draft-js-export-html": "https://github.com/swissspidy/draft-js-export-html",
```
Comment (barklund) [inline package-lock.json:46946]: @swissspidy, I have to update this file because I've added a package, but these changes seem unwanted?

Comment (swissspidy) [reply package-lock.json:46946]: Should be fine, npm sometimes likes to switch depending on git config and stuff.

File: packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts [hunk 3]
```diff
@@ -53,9 +51,8 @@ export const updateElementsByResourceId = (
 
   draft.pages.forEach((page) => {
     page.elements
-      .filter(
-        (element) => elementIs.media(element) && element.resource.id === id
-      )
+      .filter(elementIs.media)
+      .filter((element) => element.resource.id === id)
       .forEach((element) =>
         updateElementWithUpdater<MediaElement>(
```
Comment (swissspidy) [inline packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts]: This assertion is now unnecessary because TS correctly infers the type.

Comment (swissspidy) [reply packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts]: Weird that ESLint flagged this for me locally but it's not reported here on GitHub.

File: packages/elements/src/utils/elementIs.ts [hunk 4]
```diff
@@ -26,29 +32,45 @@ import type {
...
-  return 'isDefaultBackground' in e;
+  return 'isDefaultBackground' in e && Boolean(e.isDefaultBackground);
 }
 
+function isBackgroundable(e: Element): e is BackgroundableElement;
+function isBackgroundable(e: Draft<Element>): e is Draft<BackgroundableElement>;
 function isBackgroundable(e: Element): e is BackgroundableElement {
   // All media is backgroundable.
-  return 'isBackground' in e || 'resource' in e;
+  return ('isBackground' in e && Boolean(e.isBackground)) || isMediaElement(e);
```
Comment (swissspidy) [inline packages/elements/src/utils/elementIs.ts:59]: `setBackgroundElement` tests are now failing, presumably because of this change?

File: packages/elements/src/utils/elementIs.ts (hunk 1 above)
Comment (swissspidy) [reply packages/elements/src/utils/elementIs.ts]: Seems to do the trick 👍  Also with the dev dependency

File: packages/elements/src/utils/elementIs.ts (hunk 4 above)
Comment (barklund) [reply packages/elements/src/utils/elementIs.ts:59]: Fixed in 5fee6f4add.

File: packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts (hunk 3 above)
Comment (barklund) [reply packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts]: Fixed in 5fee6f4add. And this over-typing was actually why I noticed that the filter wasn't working correctly TS-wise, so yeah, this should of course be changed. But weird that ESLint didn't catch. Not locally with me either actually.

File: packages/elements/src/utils/elementIs.ts (hunk 4 above)
Comment (barklund) [reply packages/elements/src/utils/elementIs.ts:59]: Eh, I screwed up some commits, will fix this again.

**Comment by spacedmonkey** [comment]
Related https://github.com/GoogleForCreators/web-stories-wp/issues/12806

**Comment by spacedmonkey** [comment]
Unit tests failures seem valid.

File: packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts (hunk 3 above)
Comment (barklund) [reply packages/story-editor/src/app/story/useStoryReducer/reducers/updateElementsByResourceId.ts]: (actually fixed in 2bb37c3)

File: packages/elements/src/utils/elementIs.ts (hunk 4 above)
Comment (barklund) [reply packages/elements/src/utils/elementIs.ts:59]: Fixed in 2fc423d

File: packages/story-editor/src/app/story/useStoryReducer/test/setBackgroundElement.js [hunk 5]
```diff
@@ -29,7 +29,7 @@ describe('setBackgroundElement', () => {
           id: '111',
           elements: [
             { id: '000', isBackground: true },
-            { id: '123', opacity: 20, isBackground: false },
```
Comment (swissspidy) [inline packages/story-editor/src/app/story/useStoryReducer/test/setBackgroundElement.js:32]: Perhaps an opportunity/reason to convert the reducer tests to TS?

Comment (barklund) [reply packages/story-editor/src/app/story/useStoryReducer/test/setBackgroundElement.js:32]: They would have to become a lot more complex though, as they cheat and only use a tiny subset of the required properties. But they would also become a lot better, so it would be worth it for sure. It is however quite a task.

**Comment by kkalarickal** [comment]
@barklund - I verified this fix on the test instance https://dev-test-google-web-stories.pantheonsite.io/

- confirmed that with a sticker element on the page, dragging and dropping an image from downloads folder does not crash the editor
- confirmed that other ways of adding images: via media library, via linking from external website, taking a snapshot via recorder, adding an image from 3rd party service, etc. all work as expected.
- verified embedding jpegs/gifs/png/webp works as expected.

**Comment by kkalarickal** [comment]
@barklund @swissspidy - i verified this fix on Chrome 108, Safari 16, Firefox 107 and Opera 93 on win10 and Mac OS Ventura.

**Review by swissspidy — APPROVED** [review]

File: packages/elements/src/utils/elementIs.ts (hunk 4 above)
Comment (miina) [reply packages/elements/src/utils/elementIs.ts:59]: Hm, couldn't `isBackground` be `false` though in theory for a backgroundable element? This currently checks now if it already is `isBackground`, not if it's backgroundable. Thoughts?

Comment (swissspidy) [reply packages/elements/src/utils/elementIs.ts:59]: @miina You mean it should be `typeof e.isBackground !== 'undefined'` instead of `Boolean(e.isBackground))`?

Comment (miina) [reply packages/elements/src/utils/elementIs.ts:59]: Yep.
