### PR TITLE
Fix authors loading + Convert FontPicker to a general component.

### LINKED ISSUE #4749: Author Dropdown: huge performance issue with many users
## Bug Description

The author box seems to try to populate all the users, not just authors/editors/admins. In a site with ~200k subscribers it either times out because of cloudflare or takes a very very long time to load.

## Expected Behaviour

The author selection box should only include authors/editors/admins

## Steps to Reproduce

Try to create a new story on a site with many subscribers.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Backend
- [ ] Allow frontend to filter for only relevant users (editors and up?)

### Frontend
- [ ] Generalize font picker to generic enhanced dropdown component with the following props:
  - `selectedId` - currently selected option id.
  - `options` - full list of all options to display - must have an id property each.
  - `hasSearch` - boolean prop toggling whether search input is present.
  - `getOptionsByQuery`- if `hasSearch` and `primaryOptions` are available, `options` can be `null`, but if not given, then `getOptionsByQuery` must be given and can be an async function returning matching options.
  - `primaryOptions` - list prop of (fewer) primary options to display when not searching (if searching, all options are possible). Requires `hasSearch=true`.
  - `primaryLabel` - the label to display above the primary options. Requires `primaryOptions` to be non-empty.
  - `priorityOptions` - a short list (max 5) of options to display at the top of the dropdown before main options or primary options. Must function both with and without `hasSearch`. (to be used for "recent fonts" and similar).
  - `priorityLabel` - the label to display above the priority options. Requires `priorityOptions` to be non-empty.
  - `renderer` - component prop to use as custom option renderer. Receives whole option as `<renderer option={option} />`. If empty, use `option.label` as simple text child.
- [ ] Use this new generalized component to display the font picker (with all features enabled)
- [ ] Use this new generalized component to display the author list (with only `hasSearch` enabled)
- [ ] Load only the relevant users from the WP backend

### PR DESCRIPTION
**Pull request by miina**
## Summary
Fixes authors input loading all authors and displays only everyone with/above author rights only.
Display max 100 authors as visible options and allow searching among all.
Converts FontPicker to be a general component and use it for authors as well.

## To-do

- [x] Load only the first 100 authors as primary options.
- [x] Better naming instead of DropDown2
- [x] Tests

## Testing Instructions
- Add some subscribers as users.
- Add a story and open the document tab
- Verify that your current user is displayed as the author of the story.
- Click to change the author, verify that the subscribers are not visible in the user list
- Verify that it's possible to search among the authors.
- Verify that the author is changed correctly when changing.

---

Fixes #4749

### CODE REVIEW

**Comment by miina** [comment]
@barklund This still needs some changes (e.g. changing the name to something better than `DropDown2`) but it should be ready for initial review.

File: assets/src/edit-story/app/api/apiProvider.js [hunk 1]
```diff
@@ -227,7 +227,9 @@ function APIProvider({ children }) {
   );
 
   const getAllUsers = useCallback(() => {
-    return apiFetch({ path: addQueryArgs(users, { per_page: '-1' }) });
+    return apiFetch({
+      path: addQueryArgs(users, { per_page: '-1', who: 'authors' }),
```
Comment (swissspidy) [inline assets/src/edit-story/app/api/apiProvider.js]: -1 still means it's loading all authors

Comment (miina) [reply assets/src/edit-story/app/api/apiProvider.js]: True, but isn't this the expected behavior based on the description in https://github.com/google/web-stories-wp/issues/4749?

Ah, okay, read through the comments again and saw that the part about loading only the first 100 authors first was in the comments. Thanks for pointing that out.

File: assets/src/edit-story/app/api/apiProvider.js [hunk 2]
```diff
@@ -226,9 +226,15 @@ function APIProvider({ children }) {
...
   );
 
-  const getAllUsers = useCallback(() => {
-    return apiFetch({ path: addQueryArgs(users, { per_page: '-1' }) });
-  }, [users]);
+  const getUsers = useCallback(
+    (search = null) => {
+      // @todo per_page 10 is for testing, change later.
+      return apiFetch({
+        path: addQueryArgs(users, { per_page: '10', who: 'authors', search }),
```
Comment (miina) [inline assets/src/edit-story/app/api/apiProvider.js]: I'm thinking of sorting this so that the author of the current ~~user~~ story would always be the first, otherwise, the author might not be among the first X authors.

Comment (swissspidy) [reply assets/src/edit-story/app/api/apiProvider.js]: > author of the current user

author of the current _story_?

---

Does the current author really need to be the _first_ in the list? It needs to be somewhere in the list sure, but as long as it's the selected/current option, the position shouldn't matter.

https://github.com/WordPress/gutenberg/blob/2fdde1c7c14820f45b043724a4f73d7abd499a49/packages/editor/src/components/post-author/index.js#L42-L63 might help as reference.

Comment (miina) [reply assets/src/edit-story/app/api/apiProvider.js]: > author of the current story?

Yes!

> Does the current author really need to be the first in the list?

No, doesn't need to be always the first, was just an idea -- we can add it _if_ it doesn't exist as in Gutenberg.

File: assets/src/edit-story/app/api/apiProvider.js [hunk 3]
```diff
@@ -226,9 +226,23 @@ function APIProvider({ children }) {
     [link]
   );
 
-  const getAllUsers = useCallback(() => {
-    return apiFetch({ path: addQueryArgs(users, { per_page: '-1' }) });
-  }, [users]);
+  const getUsers = useCallback(
```
Comment (barklund) [inline assets/src/edit-story/app/api/apiProvider.js]: Should it then rightfully be called `getAuthors`?

File: assets/src/edit-story/components/form/advancedDropDown/container.js [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+        onExpandedChange={setIsExpanded}
+        focusTrigger={trigger}
+        onObserve={onObserve}
+        options={options || queriedOptions}
+        primaryOptions={primaryOptions}
+        primaryLabel={primaryLabel}
+        priorityOptions={priorityOptions}
+        priorityLabel={priorityLabel}
+        renderer={renderer}
+      />
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/container.js]: I really hate prop drilling like this (most of these props pass through the `OptionsContainer` component without being used). Could we perhaps use a render prop here, and just pass the props in the other direction?

So that would mean that this component can remove a lot of props and this render becomes:

```js
{children({searchKeyword,setIsExpanded,trigger,queriedOptions})}
```

And the parent invocation then changes from this:

```js
          <OptionsContainer
            isOpen={isOpen}
            value={selectedId}
            onSelect={handleSelect}
            onClose={debouncedCloseDropDown}
            getOptionsByQuery={getOptionsByQuery}
            hasSearch={hasSearch}
            onObserve={onObserve}
            options={options}
            primaryOptions={primaryOptions}
            primaryLabel={primaryLabel}
            priorityOptions={priorityOptions}
            priorityLabel={priorityLabel}
            renderer={renderer}
          />
```

To this:

```js
          <OptionsContainer
            isOpen={isOpen}
            onClose={debouncedCloseDropDown}
            getOptionsByQuery={getOptionsByQuery}
          >{({searchKeyword,setIsExpanded,trigger,queriedOptions}) => (
              <List
                value={value}
                keyword={searchKeyword}
                onSelect={onSelect}
                onClose={onClose}
                onExpandedChange={setIsExpanded}
                focusTrigger={trigger}
                onObserve={onObserve}
                options={options || queriedOptions}
                primaryOptions={primaryOptions}
                primaryLabel={primaryLabel}
                priorityOptions={priorityOptions}
                priorityLabel={priorityLabel}
                renderer={renderer}
              />)}</OptionsContainer>
```

I feel like that's a better result with a clearer separation of responsibility between the two classes. Makes sense?

File: assets/src/edit-story/components/form/advancedDropDown/container.js [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+  useFocusOut(ref, onClose, [onClose]);
+
+  const handleSearchInputChanged = useCallback(({ target }) => {
+    setSearchKeyword(target.value);
+  }, []);
+
+  const handleLoadOptions = useCallback(() => {
+    getOptionsByQuery(searchKeyword).then((result) => {
+      setQueriedOptions(result);
+    });
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/container.js]:
```suggestion
    getOptionsByQuery(searchKeyword).then(setQueriedOptions);
```

File: assets/src/edit-story/components/form/advancedDropDown/container.js [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+  const [searchKeyword, setSearchKeyword] = useState('');
+  const [queriedOptions, setQueriedOptions] = useState(null);
+  const [isExpanded, setIsExpanded] = useState(true);
+  const [trigger, setTrigger] = useState(0);
+
+  useFocusOut(ref, onClose, [onClose]);
+
+  const handleSearchInputChanged = useCallback(({ target }) => {
+    setSearchKeyword(target.value);
+  }, []);
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/container.js]:
```suggestion
  const handleSearchInputChanged = useCallback(
    ({ target: { value } }) => setSearchKeyword(value),
    [],
  );
```

File: assets/src/edit-story/components/form/advancedDropDown/container.js [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+  return (
+    <Container role="dialog" ref={ref}>
+      {hasSearch && (
+        <SearchInput
+          ref={inputRef}
+          value={searchKeyword}
+          onChange={handleSearchInputChanged}
+          onClose={onClose}
+          isExpanded={isExpanded}
+          focusFontListFirstOption={() => setTrigger((v) => ++v)}
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/container.js]: What's this for again? Seems dirty...

shouldn't it at least be `v+1` rather than actually changing the local value of `v` for no reason?

File: assets/src/edit-story/components/form/advancedDropDown/dropDown.js [hunk 8]
```diff
@@ -0,0 +1,231 @@
...
+  primaryLabel: PropTypes.string,
+  priorityOptions: PropTypes.array,
+  priorityLabel: PropTypes.string,
+  renderer: PropTypes.func,
+};
+
+DropDown.defaultProps = {
+  value: '',
+  lightMode: false,
+  placeholder: __('Select an Option', 'web-stories'),
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/dropDown.js]: Can we inline these in the definition instead? `defaultProps` will [be retired at some point anyway](https://twitter.com/dan_abramov/status/1133878326358171650).

File: assets/src/edit-story/components/form/advancedDropDown/list/index.js [hunk 9]
```diff
@@ -208,10 +206,10 @@ function FontList({
     <List
       ref={listRef}
       tabIndex={0}
-      id="editor-font-picker-list"
+      id="editor-dropdown-list"
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/list/index.js]: This id should be unique in the document.

File: assets/src/edit-story/components/form/advancedDropDown/list/index.js [hunk 10]
```diff
@@ -223,36 +221,49 @@ function FontList({
...
+                        getInset(filteredListGroups, i, j)
+                      ] = el)
+                    }
+                  >
+                    {value === option.id && (
+                      <Selected aria-label={__('Selected', 'web-stories')} />
+                    )}
+                    {option.name}
+                  </Option>
+                );
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/list/index.js]: Please move this to a separate component to clean this up a bit. And can't the `<OptionRenderer />` get a normal `ref` too, if you make it use `forwardRef()`?

File: assets/src/edit-story/components/panels/textStyle/font.js [hunk 11]
```diff
@@ -158,17 +170,67 @@ function FontControls({ selectedElements, pushUpdate }) {
...
+              MULTIPLE_VALUE === fontFamily
+                ? MULTIPLE_DISPLAY_VALUE
+                : fontFamily
+            }
+            hasSearch
             onChange={handleFontPickerChange}
+            onObserve={onObserve}
+            renderer={renderer}
+            disabled={!fonts?.length}
           />
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/font.js]: Hm, this was actually more compact than expected. But I was thinking that we kept a `<FontPicker />` component behind the scenes, but it was just a shortcut for `<AdvancedDropDown />` with most attributes fixed.

This however seems okay to me, but it could also be moved to its own component - mostly because of the renderer and the overhead in terms of line count required by that.

File: assets/src/edit-story/karma/textStyle.cuj.karma.js [hunk 12]
```diff
@@ -95,7 +95,7 @@ describe('Element: Text', () => {
 
     it('should display only the fonts from curated list by default', () => {
       const options = document
-        .getElementById('editor-font-picker-list')
+        .getElementById('editor-dropdown-list')
```
Comment (barklund) [inline assets/src/edit-story/karma/textStyle.cuj.karma.js]: That's a lot of reference by id. Can we use the label instead at least?

**Review by barklund — COMMENTED** [review]
This seems like a really great refactor - a few comments most importantly the one about the structure of information from dropdown through container to list.

File: assets/src/edit-story/app/api/apiProvider.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/app/api/apiProvider.js]: Wasn't sure since it gets the editors and admins, too. Although they are authors as well. Looks like Pascal also added a thumbs up so I guess you both prefer `getAuthors`, will change.

File: assets/src/edit-story/components/form/advancedDropDown/container.js (hunk 4 above)
Comment (miina) [reply assets/src/edit-story/components/form/advancedDropDown/container.js]: Used `renderContent` prop instead since we're doing this elsewhere as well instead of using `children` directly. Perhaps it's easier to read this way.

File: assets/src/edit-story/components/panels/textStyle/font.js (hunk 11 above)
Comment (miina) [reply assets/src/edit-story/components/panels/textStyle/font.js]: Moved `fontPicker` to a separate component in the `textStyles` panel. LMK if it makes more sense to you now.

File: assets/src/edit-story/components/inspector/document/publish/index.js [hunk 13]
```diff
@@ -112,12 +132,39 @@ function PublishPanel() {
...
-    (prop) => (value) => updateStory({ properties: { [prop]: value } }),
+  useEffect(() => {
+    if (users?.length) {
+      const currentAuthor = users.find(({ id }) => author === id);
+      if (!currentAuthor) {
+        getUserById(author)
+          .then(({ id, name }) => {
+            setVisibleOptions([{ id, name }, ...users]);
+          })
+          .catch(() => setVisibleOptions(users));
```
Comment (swissspidy) [inline assets/src/edit-story/components/inspector/document/publish/index.js]: Don't we have the full author information from the story object already? If not, we should fix that. (i.e. passing `?_embed=author` when loading the story in `useLoadStory` and in `edit-story.php`)

That avoids having to do an actual HTTTP request here and calling `setVisibleOptions`

Comment (swissspidy) [reply assets/src/edit-story/components/inspector/document/publish/index.js]: Happy to push some code to better explain my thoughts here if you'd like

Comment (miina) [reply assets/src/edit-story/components/inspector/document/publish/index.js]: I actually started doing with the `_embed` version at first, however, it's possible that the author changes to something without having the full information, and then we'd still need to request the new information. I figured that since it's not something that's used very often then requesting this is perhaps not that big of an influence.

The reason for adding this extra request was mainly for when the author is changed, the original we could indeed get from embedding author. Thoughts?

Comment (swissspidy) [reply assets/src/edit-story/components/inspector/document/publish/index.js]: How/when would the author change to something without having the full information?

Sounds like we should call

```
updateStory({
  properties: { author: id },
});
```

with more than just the ID?

Comment (miina) [reply assets/src/edit-story/components/inspector/document/publish/index.js]: > How/when would the author change to something without having the full information?

For example, when we have 200 users, and we're changing the author to be nr 200 in the list, then additional information about this author will not be available just by the ID (since it's not among the first 100 loaded authors), and also not in the embed, since the DB is not updated yet.

We could indeed update the story by passing forward both ID and the name from the dropdown option upon selection (where it is available!) instead of just the ID as it is now, however, then we would need to generally store the author as an object and not just an ID. Is that what you were thinking of -- storing the `author` as an object for the story instead of just the ID?

I suppose we could pass just the ID when saving the story to DB, and convert it to an object when it's received from the DB, getting the `name` from the embedded author.

Happy to apply this if you think it's a better option.

File: assets/src/edit-story/components/panels/textStyle/font.js [hunk 14]
```diff
@@ -75,30 +73,14 @@ function FontControls({ selectedElements, pushUpdate }) {
...
+  const { fonts = [], maybeEnqueueFontStyle, getFontByName } = useFont(
     ({
-      actions: {
-        addRecentFont,
-        ensureMenuFontsLoaded,
-        maybeEnqueueFontStyle,
-        getFontByName,
-      },
-      state: { fonts, recentFonts, curatedFonts },
+      actions: { addRecentFont, maybeEnqueueFontStyle, getFontByName },
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/font.js]: You're not using `addRecentFont` anymore, right?

File: assets/src/edit-story/components/form/advancedDropDown/list/list.js [hunk 15]
```diff
@@ -0,0 +1,281 @@
...
+                return renderer ? (
+                  <OptionRenderer {...optionProps} option={option} />
+                ) : (
+                  <Option {...optionProps}>
+                    {value === option.id && (
+                      <Selected aria-label={__('Selected', 'web-stories')} />
+                    )}
+                    {option.name}
+                  </Option>
+                );
```
Comment (barklund) [inline assets/src/edit-story/components/form/advancedDropDown/list/list.js]: Could this be done with a default value instead? So it's defined in the component as `function OptionList({ ..., renderer = DefaultRenderer, ... })` - then you can also inline all the props rather than define them in a props-object.

**Review by barklund — APPROVED** [review]
I'd like the state of this now. If you feel good about it, feel free to send to QA!

File: assets/src/edit-story/components/inspector/document/publish/index.js (hunk 13 above)
Comment (swissspidy) [reply assets/src/edit-story/components/inspector/document/publish/index.js]: > Is that what you were thinking of -- storing the author as an object for the story instead of just the ID?

yep!

> I suppose we could pass just the ID when saving the story to DB, and convert it to an object when it's received from the DB, getting the name from the embedded author.

I think this makes sense

File: includes/templates/admin/edit-story.php [hunk 16]
```diff
@@ -35,8 +35,9 @@
 
 // Preload common data.
 $preload_paths = [
-	sprintf( '/web-stories/v1/%s/%s?context=edit', $rest_base, $post->ID ),
+	sprintf( '/web-stories/v1/%s/%s?context=edit&_embed=author&_locale=user', $rest_base, $post->ID ),
 	'/web-stories/v1/media?context=edit&per_page=100&page=1&_web_stories_envelope=true',
+	'/web-stories/v1/users?per_page=100&who=authors&_locale=user',
```
Comment (miina) [inline includes/templates/admin/edit-story.php]: @swissspidy Could you double-check this since it's a PHP file?

**Comment by miina** [comment]
Hmm, looks like this PR is breaking the demo somehow, investigating...

File: assets/src/edit-story/app/api/apiProvider.js [hunk 17]
```diff
@@ -231,9 +236,23 @@ function APIProvider({ children }) {
     [link]
   );
 
-  const getAllUsers = useCallback(() => {
-    return apiFetch({ path: addQueryArgs(users, { per_page: '-1' }) });
-  }, [users]);
+  const getAuthors = useCallback(
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/api/apiProvider.js:240]: So you are now limiting the users to just getting 100 users? This doesn't make a lot of sense. Before it was getting all users by loading -1, which has a special bit of code to call the rest api recursively until it gets all users. Without that, you are limited to the first 100.

File: includes/templates/admin/edit-story.php [hunk 18]
```diff
@@ -35,8 +35,9 @@
 
 // Preload common data.
 $preload_paths = [
-	sprintf( '/web-stories/v1/%s/%s?context=edit', $rest_base, $post->ID ),
+	sprintf( '/web-stories/v1/%s/%s?context=edit&_embed=author&_locale=user', $rest_base, $post->ID ),
```
Comment (spacedmonkey) [inline includes/templates/admin/edit-story.php]: Pretty sure you do not need `&_locale=user`

File: assets/src/edit-story/app/api/apiProvider.js (hunk 17 above)
Comment (swissspidy) [reply assets/src/edit-story/app/api/apiProvider.js:240]: The idea is to load 100 users by default for performance reasons, and then use the search to find more users.

Loading all users with -1 is exactly what we want to prevent / stop doing

File: includes/templates/admin/edit-story.php (hunk 18 above)
Comment (spacedmonkey) [reply includes/templates/admin/edit-story.php]: Embed requests like this will not work in preload, until this is https://github.com/google/web-stories-wp/pull/5149. 

Was this tested that this preloaded data worked?

File: includes/templates/admin/edit-story.php (hunk 16 above)
Comment (spacedmonkey) [reply includes/templates/admin/edit-story.php]: First things, first, I do not think we should preload this data. Preloaded data is only for critical that stop editor from rendering. As the user dropdown is not on screen, that is the not case. We would stop the render of the story to load this data, that some users ( author level ) can't assign another user to a user, making it pointless to load. 

Second, as noted above, this would only get the first page of results for users. This is not what we want, we want all the users.

**Review by spacedmonkey — DISMISSED** [review]
This has a pretty serious breaking change in it, that needs to be fixed before it is merged. This PR also relays on https://github.com/google/web-stories-wp/pull/5149 before it can be merged.

File: includes/templates/admin/edit-story.php (hunk 18 above)
Comment (miina) [reply includes/templates/admin/edit-story.php]: It actually doesn't work without `&_locale=user` when I tested.

File: assets/src/edit-story/app/api/apiProvider.js (hunk 17 above)
Comment (miina) [reply assets/src/edit-story/app/api/apiProvider.js:240]: Yes, @spacedmonkey, as required, this now works in a similar way as the fontpicker -- the first 100 users a loaded by default and the rest of the users can be searched.

File: includes/templates/admin/edit-story.php (hunk 16 above)
Comment (spacedmonkey) [reply includes/templates/admin/edit-story.php]:
```suggestion
	'/web-stories/v1/users?per_page=100&who=authors',
```

In testing, I saw REST API requests. This fixed it.

File: includes/templates/admin/edit-story.php [hunk 19]
```diff
@@ -35,8 +35,9 @@
 
 // Preload common data.
 $preload_paths = [
-	sprintf( '/web-stories/v1/%s/%s?context=edit', $rest_base, $post->ID ),
+	sprintf( '/web-stories/v1/%s/%s?_embed=author&context=edit', $rest_base, $post->ID ),
```
Comment (spacedmonkey) [inline includes/templates/admin/edit-story.php]: `&_locale=user` is not needed. With it, it results in an REST API request. See this screenshot.

Screenshot 2020-11-11 at 10 54 19

**Comment by spacedmonkey** [comment]
Screenshot 2020-11-11 at 11 00 08

I have created 150 test users ( using WP CLI ). I am seeing a react error. Have you seen this @miina

**Comment by miina** [comment]
> I have created 150 test users ( using WP CLI ). I am seeing a react error. Have you seen this @miina

Can you specify the details? I have around 200 users created via WP CLI and not seeing the error.

1. Which users did you create? Authors? Subscribers? Editors? Mixed?
2. Does the error appear when just opening the panel or did you do anything else?

File: includes/templates/admin/edit-story.php (hunk 16 above)
Comment (spacedmonkey) [reply includes/templates/admin/edit-story.php]: @swissspidy 👆🏻

**Comment by miina** [comment]
> I have created 150 test users ( using WP CLI ). I am seeing a react error. Have you seen this @miina

Actually, I can now see that error.

@spacedmonkey @swissspidy -- it looks like removing the `_locale` in 0310517 is now causing an error and `_embedded` is not defined anymore. Thoughts?

Edit: Or is this expected for now and should work after Jonny's PR gets merged?

**Comment by swissspidy** [comment]
@miina, yeah let's wait for a moment until that other PR is merged to re-evaluate

**Comment by spacedmonkey** [comment]
I am seeing this error on author dropdown. 

Screenshot 2020-11-11 at 11 11 17

And the editor is broken. 

Screenshot 2020-11-11 at 11 10 26

File: includes/templates/admin/edit-story.php (hunk 16 above)
Comment (swissspidy) [reply includes/templates/admin/edit-story.php]: Removed the `_locale` bit now.

The preloading like this makes sense to me though, as it matches the editor behavior. We don't to load all users, just the initial set of data for the dropdown, which is 100 users.

**Review by swissspidy — APPROVED** [review]

File: assets/src/edit-story/app/api/apiProvider.js [hunk 20]
```diff
@@ -235,9 +237,23 @@ function APIProvider({ children }) {
...
+    (search = null) => {
+      return apiFetch({
+        path: addQueryArgs(users, { per_page: '100', who: 'authors', search }),
+      });
+    },
+    [users]
+  );
+
+  const getUserById = useCallback(
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/api/apiProvider.js]: What is function called? I can't see it used anywhere.

Comment (swissspidy) [reply assets/src/edit-story/app/api/apiProvider.js]: yeah I don't think it's needed anymore and can be removed

File: assets/src/edit-story/app/story/effects/useLoadStory.js [hunk 21]
```diff
@@ -41,37 +41,46 @@ function useLoadStory({ storyId, shouldLoad, restore }) {
...
           title: { raw: title },
           status,
-          author,
           slug,
           date_gmt,
           modified,
           excerpt: { raw: excerpt },
           link,
           story_data: storyDataRaw,
-          featured_media_url: featuredMediaUrl,
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/story/effects/useLoadStory.js:51]: If you are going to remove this @swissspidy, it should be removed from REST API all together.

https://github.com/google/web-stories-wp/blob/df38d616a7d6f410da5a86cd5c1e96d65411a444/includes/REST_API/Stories_Base_Controller.php#L127-L130

File: assets/src/edit-story/app/api/apiProvider.js (hunk 20 above)
Comment (miina) [reply assets/src/edit-story/app/api/apiProvider.js]: On it.

File: assets/src/edit-story/app/story/effects/useLoadStory.js [hunk 22]
```diff
@@ -41,37 +41,46 @@ function useLoadStory({ storyId, shouldLoad, restore }) {
...
+        if ('wp:featuredmedia' in embedded) {
           featuredMedia = {
-            id: featuredMediaData?.id,
-            height: featuredMediaData?.media_details?.height,
-            width: featuredMediaData?.media_details?.width,
-            url: featuredMediaUrl,
+            id: embedded['wp:featuredmedia'][0].id,
+            height: embedded['wp:featuredmedia'][0].media_details?.height,
+            width: embedded['wp:featuredmedia'][0].media_details?.width,
+            url: embedded['wp:featuredmedia'][0].source_url,
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/story/effects/useLoadStory.js:83]: @swissspidy Shouldn't we use the poster size here?

File: assets/src/edit-story/app/story/effects/useLoadStory.js (hunk 21 above)
Comment (swissspidy) [reply assets/src/edit-story/app/story/effects/useLoadStory.js:51]: @spacedmonkey yup 👍 I'll open a ticket for it

File: assets/src/edit-story/app/story/effects/useLoadStory.js (hunk 22 above)
Comment (spacedmonkey) [reply assets/src/edit-story/app/story/effects/useLoadStory.js:83]: I created another ticket for this - https://github.com/google/web-stories-wp/issues/5228

Comment (swissspidy) [reply assets/src/edit-story/app/story/effects/useLoadStory.js:83]: It doesn't matter too much for output as we override it in PHP. Let's handle this in #5228 as well

**Review by spacedmonkey — APPROVED** [review]
👍 Works for me.

**Comment by swissspidy** [comment]
@miina fyi there are some merge conflicts now
