### PR TITLE
Floating menu: Keyboard Navigation to Enter and Exit

### LINKED ISSUE #10872: Floating menu: Keyboard Navigation to Enter and Exit
## Feature Description
Generally, the floating menu is using roving index keyboard navigation as other context menus (navigating with arrow keys, tab moves to the next section), however, since we have a text input in the menu, this doesn't work exactly as expected.

Some thoughts from @barklund:

> Google Docs and others do this by allowing you to use arrow keys to move between the menu elements, including moving focus to an input field. But the input field acts like a menu item button, so you have to press enter when focus is on the input field menu item to actually go into typing in the input field. When there, arrow keys work as normal in a numeric input field, moving the cursor and stepping the value. Then you can press escape to move back out of the input field, moving focus back to the menu item and you can again use arrow keys to move between menu items.
>
> Note in this gif how the Google Docs menu bar works. I can use arrow keys to move between the elements in the menu, not tab. Using arrow keys, i just move over the font size input as if it was a button. Only once I press enter on the "input button", do I get to interact with the input.
>
> gdocs-menu-bar-input
>
> Google Docs then decides to always move keyboard focus back to the document whenever you select something in the menu (even when doing so with the keyboard), so as soon as I press enter inside the input field to commit my choice of font size, focus moves to the document.
>
> I'm not sure if we want to do the same. We could alternatively move focus back to the "input button" rather than the input itself, so arrow keys would once again work. We could then have <key>esc</key> work in the same way except that any input would be reset to the original state before moving focus back to the input button.
>
> Another related problem is, that the focus management handled by the menu does not follow actual focus. If I press a button and then press arrow keys to move to the next button, the arrow keys will take me to a different button because the arrow key focus and actual focus are not in sync.

See also the [comment thread and thoughts](https://github.com/GoogleForCreators/web-stories-wp/pull/10859#issuecomment-1063266518) from @BrookeGraham 

The current idea (as of 10th of March) is to change the role of the menu to "toolbar" and implement the relevant parts from [its spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/toolbar_role).

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Part of accessibility work on canvas and floating menu

## Summary
Adds `ctrl+alt+p` to enter into the floating menu when an element is focused and selected, `esc` to return focus back to the original element in the frames layer.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
User can now navigate into the floating menu with keyboard by pressing `ctrl+alt+p` while an element is selected. They can navigate out of the floating menu and back to the element by pressing `esc`.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. with an element selected & focused, press `ctrl+alt+p` and see that focus goes inside the floating menu
2. now press `esc` and see that focus leaves the floating menu

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10872

### CODE REVIEW

File: packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * Internal dependencies
+ */
+import { Fixture } from '../../../karma';
+import { useStory } from '../../../app/story';
+
+fdescribe('Canvas Element - keyboard navigation', () => {
```
Comment (BrittanyIRL) [inline packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js]: linter caught this too ^^

File: packages/design-system/src/components/contextMenu/menu.js [hunk 2]
```diff
@@ -102,178 +103,188 @@ function getFocusableChildren(parent, isSubMenu) {
...
+     * Clicking in the wrapper should not automatically focus the first
+     * focusable element.
+     */
+    const handleFocus = useCallback(
+      (evt) => {
+        onFocus(evt);
+        const menuChildren = menuRef.current.children || [];
+        if (
+          menuRef.current === evt.target &&
+          ![...menuChildren].some((child) => child.contains(evt.target))
```
Comment (samwhale) [inline packages/design-system/src/components/contextMenu/menu.js]: 🤔 for an empty array, doesn't `![...menuChildren].some((child) => child.contains(evt.target))` come out as `true`?

image

I guess it doesn't matter too much since there's no focusable children? Maybe there should be a length check to make sure that the rest of that logic isn't run?
```suggestion
          menuChildren.length && ![...menuChildren].some((child) => child.contains(evt.target))
```

File: packages/design-system/src/components/contextMenu/menu.js [hunk 3]
```diff
@@ -102,178 +103,188 @@ function getFocusableChildren(parent, isSubMenu) {
...
-    { key: ['esc', 'down', 'up', 'left', 'right'] },
-    handleKeyboardNav,
-    [handleKeyboardNav]
-  );
+    useKeyDownEffect(
+      menuRef,
+      {
+        key: dismissOnEscape
+          ? ['esc', 'down', 'up', 'left', 'right']
+          : ['down', 'up', 'left', 'right'],
```
Comment (samwhale) [inline packages/design-system/src/components/contextMenu/menu.js:261]: ✨

File: packages/story-editor/src/components/canvas/frameElement.js [hunk 4]
```diff
@@ -87,7 +97,17 @@ const EmptyFrame = styled.div`
 
 const NOOP = () => {};
 
+const FRAME_ELEMENT_MESSAGE = sprintf(
+  /* translators: 1: Ctrl Key 2: Alt Key */
+  __('To enter floating menu, press %1$s+%2$s+p.', 'web-stories'),
```
Comment (samwhale) [inline packages/story-editor/src/components/canvas/frameElement.js]: 💭 When chromevox is reading this out, it reads out the `+` symbol too. I think the `+` symbols could be removed

```suggestion
  __('To enter floating menu, press %1$s %2$s p.', 'web-stories'),
```

File: packages/story-editor/src/components/canvas/frameElement.js [hunk 5]
```diff
@@ -178,6 +199,16 @@ function FrameElement({ id }) {
...
   const handleMediaClick = useDoubleClick(NOOP, handleMediaDoubleClick);
 
+  /**
+   * Announce keyboard options on element.
+   *
+   * Using a live region because an `aria-label` would remove
+   * any labels/content that would be read from children.
+   */
+  const handleFocus = useCallback(() => {
+    speak(FRAME_ELEMENT_MESSAGE);
```
Comment (samwhale) [inline packages/story-editor/src/components/canvas/frameElement.js]: 💭 The background element does not have a floating menu, so I think this needs to be prevented for the background element.

File: packages/story-editor/src/components/floatingMenu/menu.js [hunk 6]
```diff
@@ -72,7 +93,10 @@ const FloatingMenu = memo(
             isHorizontal
             isSecondary
             isAlwaysVisible
-            disableControlledTabNavigation
+            tabIndex={-1}
+            ref={focusGroupRef}
+            dismissOnEscape={false}
+            onFocus={announceKeyboardControls}
```
Comment (samwhale) [inline packages/story-editor/src/components/floatingMenu/menu.js:99]: 👍

File: packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+    await fixture.events.click(rectangleShape);
+
+    // Click on one of the added shapes
+    const elementId = await fixture.renderHook(() =>
+      useStory(({ state }) => state.currentPage.elements[1].id)
+    );
+    const wrapperEl = getCanvasElementWrapperById(elementId);
+    await fixture.events.click(wrapperEl);
+    expect(document.activeElement).toBe(wrapperEl);
+
```
Comment (samwhale) [inline packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js]: 🤔 I think the shape element will be selected when you click on the button on line 49. This part of the test may not be necessary

**Review by samwhale — COMMENTED** [review]
This is looking good! A few things that need some small changes. Test is great!

**Comment by samwhale** [comment]
🤔 I think the failing js tests are [fixed in `main` already](https://github.com/GoogleForCreators/web-stories-wp/pull/11193/files#diff-bbead4800ca38928ee901c7b13d50185ce9e61084905a64d4b6c703ce6a4527dR104-R106). Merging that in should fix them

File: packages/design-system/src/components/contextMenu/menu.js (hunk 2 above)
Comment (maxyinger) [reply packages/design-system/src/components/contextMenu/menu.js]: ah good catch. thanks

File: packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js (hunk 7 above)
Comment (maxyinger) [reply packages/story-editor/src/components/canvas/karma/elementKeyboardNavigation.js]: yup. was able to remove it. good catch

**Review by BrittanyIRL — APPROVED** [review]

**Review by samwhale — APPROVED** [review]
Awesome!

**Comment by samwhale** [comment]
Note: exiting the floating menu focus group and going back to the canvas focus group will be done in a separate ticket.
