### PR TITLE
E2E Tests: Fix and skip flakey tests, improve debug output

### LINKED ISSUE #11803: Fix flakey e2e tests
## Task Description

Our e2e tests haven't been passing for quite some time.

See https://github.com/GoogleForCreators/web-stories-wp/actions/workflows/tests-e2e.yml?query=branch%3Amain

Let's fix them or skip them if we can't figure out the issues in reasonable time.

We have too many skipped tests already though, so I prefer addressing that instead.

### PR DESCRIPTION
**Pull request by timarney**
## Context

E2E test are having more test run failures.  We need to stabilize tests where we can.

Example test run timing out after 30 min

https://github.com/GoogleForCreators/web-stories-wp/runs/6965907754?check_suite_focus=true

## Summary

This PR addresses some of the issues with the flakey e2e tests 

Generally seeing better test runs now -- if failures do occur re-running tests in that shard seem to pass.

Example run good run:
https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2662886690

- Adds notes to skipped tests in this PR
- Updates shard count for WP 5.7 runs (speeds things up + help with test re-runs)
- Removes `runAxeTestsForStoriesEditor`
- Update Artifacts package to capture detailed stack track 
- Improves console output for unhandled errors

I would suggest merging this to move things forward and then re-looking at individual skipped tests.

## To-do

As a follow up we might want to look at automating failed steps with something like https://github.com/marketplace/actions/retry-step (to save manually re-running tests)

## Notes

Errors
Stuck on Media and or Loading screen
https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1179538205

Error: net::ERR_SOCKET_NOT_CONNECTED 
https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1181694948

Error: net::ERR_CONNECTION_RESET
https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1181943901

**Artifact package**
https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1174899872

**Helpful for debugging:**
Image capture using Base 64 -- was able to capture messages that didn't end up in the artifacts package
https://github.com/GoogleForCreators/web-stories-wp/pull/11782#discussion_r917173379

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11803

### CODE REVIEW

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js [hunk 1]
```diff
@@ -103,10 +100,14 @@ describe('Custom Fonts', () => {
     await addCustomFont(OPEN_SANS_CONDENSED_LIGHT_ITALIC_URL);
     await addCustomFont(OPEN_SANS_CONDENSED_BOLD_URL);
     await addCustomFont(OPEN_SANS_CONDENSED_LIGHT_URL);
-    const fonts = await getFontList();
-    await page.click('div[role=listbox] [role=option]:last-child');
-    const selected = await getSelectedFont();
-    expect(selected.name).toStrictEqual(fonts[2].name);
+
+    const font = await page.$("div[role=listbox] [role=option]:last-child");
```
Comment (timarney) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: Update to grab a reference to the font we want to work with and than look for  aria-selected = true.

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js [hunk 2]
```diff
@@ -79,8 +78,6 @@ describe('Custom Fonts', () => {
     await page.keyboard.press('ArrowDown');
     await page.keyboard.press('ArrowDown');
     await page.keyboard.press('ArrowUp');
-    const selected = await getSelectedFont();
```
Comment (timarney) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js:82]: Later in this test we tab to the delete button which will end up being the same as looking for the selected font (the font were currently on).

```
 await expect(page).toMatchElement(
      `button[aria-label="Delete ${OPEN_SANS_CONDENSED_LIGHT}"]`
    );
```

We also have a specific test looking for font selection.

File: packages/e2e-tests/src/specs/editor/saveStory.js [hunk 3]
```diff
@@ -63,13 +63,6 @@ describe('Saving Story', () => {
     mockResponse = undefined;
   });
 
-  it('should display published dialog', async () => {
-    await createNewStory();
-    await insertStoryTitle('Test story');
-    await publishStory();
-    await expect(page).toMatch('Story published.');
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/saveStory.js:70]: We already check for `Story published` inside of publishStory.

```javascript
await expect(page).toMatch('Story published.');
```

In which case this flow is already covered.

File: packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js [hunk 4]
```diff
@@ -82,7 +82,7 @@ describe('Publish panel in document tab', () => {
     await page.keyboard.type('auth');
 
     // wait for search results
-    await page.waitForTimeout(200);
+    await page.waitForTimeout(1000);
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js]: Need a more robust solution here vs adding more time to the timeout -- the search needs to catchup before the expectations.

File: packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js [hunk 5]
```diff
@@ -135,7 +135,7 @@ describe('Story Details Modal - Admin User', () => {
       await page.keyboard.type('auth');
 
       // wait for search results
-      await page.waitForTimeout(200);
+      await page.waitForTimeout(1000);
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js]: Same issue here

https://github.com/GoogleForCreators/web-stories-wp/pull/11782/files#r908347286

File: packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js [hunk 6]
```diff
@@ -82,7 +82,7 @@ describe('Publish panel in document tab', () => {
     await page.keyboard.type('auth');
 
     // wait for search results
-    await page.waitForTimeout(200);
+    await page.waitForTimeout(400);
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js:94]: Check out fbe4ed8585438fe734c8ab8a6b04d8bb8fb3f63b where I did something better than `waitForTimeout`

File: packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js (hunk 4 above)
Comment (timarney) [reply packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js]: https://github.com/GoogleForCreators/web-stories-wp/pull/11782#discussion_r908348908

File: packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js (hunk 5 above)
Comment (timarney) [reply packages/e2e-tests/src/specs/editor/storyDetailsModal/adminUser.js]: https://github.com/GoogleForCreators/web-stories-wp/pull/11782#discussion_r908348908

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js [hunk 7]
```diff
@@ -103,10 +100,14 @@ describe('Custom Fonts', () => {
     await addCustomFont(OPEN_SANS_CONDENSED_LIGHT_ITALIC_URL);
     await addCustomFont(OPEN_SANS_CONDENSED_BOLD_URL);
     await addCustomFont(OPEN_SANS_CONDENSED_LIGHT_URL);
-    const fonts = await getFontList();
-    await page.click('div[role=listbox] [role=option]:last-child');
-    const selected = await getSelectedFont();
-    expect(selected.name).toStrictEqual(fonts[2].name);
+
+    const font = await page.$('div[role=listbox] [role=option]:last-child');
+    await font.click();
```
Comment (timarney) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: Something is happening here where the fonts don't get cleared and we're trying to re-add 

Causing this issue.

should-select-font-when-clicked-2022-06-28T11-27-41

Comment (timarney) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: Testing locally --- adding duplicate fonts I can still get the test to pass (i.e. not with a clean list).

So while the duplicate fonts isn't helping this isn't the root cause of the error we're seeing.

https://github.com/GoogleForCreators/web-stories-wp/runs/7091391059?check_suite_focus=true

Comment (swissspidy) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: The `should select font when clicked` test for checking the `aria-selected` value seems better suited for Jest unit tests tbh

Comment (timarney) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: Yes - that's true.

Comment (timarney) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js]: Removed --- can follow-up with a Jest Test

File: packages/e2e-tests/src/specs/editor/backgroundAudio.js [hunk 8]
```diff
@@ -43,7 +43,7 @@ describe('Background Audio', () => {
   });
 
   describe('Story Background Audio', () => {
-    it('should allow adding background audio', async () => {
+    it('should allow adding background audio to story', async () => {
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/backgroundAudio.js]: Updated test name here --- to narrow down which test was failing.  Multiple tests had the same test description name.

Looks like it's this one --- looks like the file doesn't show up in the modal
should-allow-adding-background-audio-to-story-2022-07-04T11-25-14
should-allow-adding-background-audio-to-story-2022-07-04T11-25-17

Comment (swissspidy) [reply packages/e2e-tests/src/specs/editor/backgroundAudio.js]: Where is the error happening exactly? Which selector expects the file to be in the modal?

At first glance the `uploadFile` util only checks whether it's in the right column:

https://github.com/GoogleForCreators/web-stories-wp/blob/9adffbb993137d9f90c56657cf6cecbe42c31002/packages/e2e-test-utils/src/uploadFile.js#L33

As for the test names, we should update the screenshot names to include the name of the `describe` instead of changing the names here.

File: packages/e2e-tests/src/puppeteerEnvironment.js [hunk 9]
```diff
@@ -39,15 +40,54 @@ class PuppeteerEnvironment extends OriginalEnvironment {
 
   async handleTestEvent(event, state) {
     if (event.name === 'test_fn_failure') {
-      const testName = state.currentlyRunningTest.name;
-      await this.storeArtifacts(testName);
+      const testName = `${state.currentlyRunningTest.parent.name}  ${state.currentlyRunningTest.name}`;
+      const errors = state.currentlyRunningTest.errors;
+      let errorMessages = '';
```
Comment (timarney) [inline packages/e2e-tests/src/puppeteerEnvironment.js:46]: Captures errors to the artifacts package

File: packages/e2e-tests/src/specs/editor/backgroundAudio.js [hunk 10]
```diff
@@ -64,7 +64,7 @@ describe('Background Audio', () => {
         visible: true,
       });
 
-      const fileName = await uploadFile('audio.mp3');
+      const fileName = await uploadFile('audio.mp3', false);
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/backgroundAudio.js:68]: removed to test to see if the file check was causing these tests to fail --- this seems to be the case

File: packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js [hunk 11]
```diff
@@ -82,7 +82,16 @@ describe('Publish panel in document tab', () => {
...
+    await page.waitForResponse(
+      (response) =>
+        //eslint-disable-next-line jest/no-conditional-in-test
+        response.url().includes('web-stories/v1/users') &&
+        response.url().includes('search=auth') &&
+        response.status() === 200
+    );
+
+    // add small delay after we have results
+    await page.waitForTimeout(400);
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/publishPanel/adminUser.js:94]: Re-added a delay here to test if that clears this test issue (again we need a proper solve).

**Comment by timarney** [comment]
@swissspidy any thoughts on this one?

In the snapshot the input is there --- the check is after a page reload so possibly the page hasn't fully loaded when the check happens (but are ready by the time the snapshot happens)

> Administrator  should be able to add new categories::TimeoutError: Element input[placeholder="Add title"] not found
waiting for function failed: timeout 1000ms exceeded,Error


Administrator-should-be-able-to-add-new-categories-2022-07-05T09-17-57

**Comment by timarney** [comment]
@swissspidy @spacedmonkey 

Thoughts on maybe adding some retry logic for failed element matches ?

Given a bunch of errors are around timing 

--- what if we check for an element ... don't find it try again X times (this would be a param).

See https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1174927911 where the snapshots seems to have the elements we're looking for but the test don't find those elements.

File: packages/e2e-tests/src/puppeteerEnvironment.js [hunk 12]
```diff
@@ -39,15 +40,54 @@ class PuppeteerEnvironment extends OriginalEnvironment {
...
+    ];
+    if (!ignoredEvents.includes(event.name)) {
+      // eslint-disable-next-line no-console
+      console.log(
+        new Date().toString() +
+          ' Unhandled event(' +
+          event.name +
+          '): ' +
+          util.inspect(event)
+      );
```
Comment (swissspidy) [inline packages/e2e-tests/src/puppeteerEnvironment.js]: This output format was OK for debugging, but if we wanna keep this, we should probably change it. Don't need the date for example, and I don't think we need to check for other events.


```js
if (event.name === 'test_fn_failure') {
  console.log(...)
}
```

**Comment by timarney** [comment]
https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2619533647


Down to 2 consistent errors with the latest runs

> 200 OK  should not display error dialog::Exceeded timeout of 100000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.,Error


> Font Check Metrics  should receive updated font metrics and not alter history::Exceeded timeout of 100000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.,Error

File: packages/e2e-test-utils/src/visitAdminPage.js [hunk 13]
```diff
@@ -35,7 +35,10 @@ import {
  * @param {string} [query] String to be serialized as query portion of URL.
  */
 async function visitAdminPage(adminPath, query = '') {
-  await page.goto(createURL(join('wp-admin', adminPath), query));
+  await page.goto(createURL(join('wp-admin', adminPath), query), {
+    waitUntil: 'load',
```
Comment (swissspidy) [inline packages/e2e-test-utils/src/visitAdminPage.js]: That's the default, FWIW. Try other options to see if it makes a difference.

https://pptr.dev/api/puppeteer.page.goto

**Comment by timarney** [comment]
@swissspidy here's that one I mentioned the other day about the `en bundle not found`
Screen Shot 2022-07-08 at 7 10 24 AM

**Comment by timarney** [comment]
Another interesting case I'm seeing from time to time

Screen Shot 2022-07-08 at 8 51 16 AM

<hr>
Screen Shot 2022-07-08 at 8 52 03 AM

File: packages/e2e-tests/src/puppeteerEnvironment.js [hunk 14]
```diff
@@ -41,6 +41,11 @@ class PuppeteerEnvironment extends OriginalEnvironment {
   async handleTestEvent(event, state) {
     if (event.name === 'test_fn_failure') {
       const testName = `${state.currentlyRunningTest.parent.name}  ${state.currentlyRunningTest.name}`;
+      
+      const data = await this.global.page.screenshot({ type: 'jpeg', encoding: 'base64', quality: 1 	});
+      // eslint-disable-next-line no-console
+      console.log(`data:image/jpeg;base64,${data}`);
```
Comment (timarney) [inline packages/e2e-tests/src/puppeteerEnvironment.js]: Found this little trick here  - to output a base64 "image" to the console (in some cases we're not seeing screens captured in the artifacts package )
https://www.mixmax.com/engineering/maintaining-an-end-to-end-integration-test-suite

Testing this --- the timeouts look like we're getting stuck here


download

Note: you can use a tool like https://codebeautify.org/base64-to-image-converter to grab the console output ... see the resulting image.

**Comment by timarney** [comment]
The last few tests runs:
Seems to indicate getting stuck on these screens

| Media Library (beforeAll ?)     | Story Editor |
| ----------- | ----------- |
|      |       |




https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2640972332#artifacts

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2639264491#artifacts

**Comment by timarney** [comment]
Need to dig into this one further.

> Pending Stories  should be able to publish a pending story::Error: net::ERR_CONNECTION_RESET at http://localhost:8899/wp-admin/index.php,Error

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2642024547#artifacts

**Comment by timarney** [comment]
Passing run https://github.com/GoogleForCreators/web-stories-wp/pull/11782/commits/724365bb844786308528ebb0354c36dba96980d7

https://github.com/GoogleForCreators/web-stories-wp/runs/7279875976?check_suite_focus=true
Screen Shot 2022-07-11 at 6 18 33 AM

**Comment by timarney** [comment]
Another run where the connection gets reset

> Publishing Flow  should guide me towards creating a new post to embed my story with poster::Error: net::ERR_CONNECTION_RESET at http://localhost:8899/wp-admin/post-new.php?post_type=web-story,Error

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2656788032

**Comment by timarney** [comment]
https://github.com/GoogleForCreators/web-stories-wp/pull/11782/commits/c135b34c8c4fbeb9e793cccdd352cc830bb82ea7 Succeeded in 14min https://github.com/GoogleForCreators/web-stories-wp/actions/runs/2662886690

File: packages/e2e-tests/src/config/bootstrap.js [hunk 15]
```diff
@@ -101,6 +101,11 @@ const ALLOWED_ERROR_MESSAGES = [
 
   // See https://www.chromestatus.com/feature/508239670987980
   "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load",
+
+  // See https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1178865825
+  'Bundle not found for language en:',
+
+  'Failed to fetch',
```
Comment (timarney) [inline packages/e2e-tests/src/config/bootstrap.js:108]: https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1178956569

File: packages/e2e-tests/src/config/bootstrap.js [hunk 16]
```diff
@@ -121,13 +126,8 @@ const pageEvents = [];
 // The Jest timeout is increased because these tests are a bit slow
 jest.setTimeout(PUPPETEER_TIMEOUT || 100000);
 
-// Retry flaky tests at most 2 times in CI (off by 1).
-if ('true' === process.env.CI) {
```
Comment (timarney) [inline packages/e2e-tests/src/config/bootstrap.js:125]: This can't be set at the global level

https://jestjs.io/docs/jest-object#jestretrytimesnumretries-options

> This must live at the top-level of a test file or in a describe block.

File: packages/e2e-tests/src/jest.config.js [hunk 17]
```diff
@@ -44,10 +44,8 @@ export default {
   setupFilesAfterEnv: [
     'jest-extended/all',
     '<rootDir>/packages/e2e-tests/src/config/bootstrap.js',
-    '@wordpress/jest-puppeteer-axe',
     '@wordpress/jest-console',
     'expect-puppeteer',
   ],
   modulePathIgnorePatterns: ['<rootDir>/build', '<rootDir>/vendor'],
-  reporters: [['jest-silent-reporter', { useDots: true, showWarnings: true }]],
```
Comment (timarney) [inline packages/e2e-tests/src/jest.config.js:52]: Removed so we can see more detailed output in CI

File: .github/workflows/tests-e2e.yml [hunk 18]
```diff
@@ -130,8 +130,8 @@ jobs:
         browser: ['chrome']
         wp: ['5.7']
         snapshots: [false]
-        # We want to split up the tests into 2 parts running in parallel.
-        shard: ['1/2', '2/2']
+        # We want to split up the tests into 4 parts running in parallel.
+        shard: ['1/4', '2/4', '3/4', '4/4']
```
Comment (timarney) [inline .github/workflows/tests-e2e.yml:142]: Splits the WP 5.7 run into 4 shards --- this helps as it splits the number of test per shard up and in turn when re-running failed tests the number of test will be lower.   Also should speed up the 5.7 tests.

File: packages/e2e-tests/src/config/bootstrap.js [hunk 19]
```diff
@@ -214,31 +214,6 @@ function observeConsoleLogging() {
   });
 }
 
-/**
- * Runs Axe tests when the story editor is found on the current page.
- *
- * @return {?Promise} Promise resolving once Axe texts are finished.
- */
-async function runAxeTestsForStoriesEditor() {
```
Comment (timarney) [inline packages/e2e-tests/src/config/bootstrap.js:222]: We need to look at doing an a11y test run or something vs having this run after `afterEach`

File: packages/e2e-tests/src/jest.config.js [hunk 20]
```diff
@@ -44,10 +44,8 @@ export default {
   setupFilesAfterEnv: [
     'jest-extended/all',
     '<rootDir>/packages/e2e-tests/src/config/bootstrap.js',
-    '@wordpress/jest-puppeteer-axe',
```
Comment (timarney) [inline packages/e2e-tests/src/jest.config.js]: Removed `runAxeTestsForStoriesEditor` above.

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js [hunk 21]
```diff
@@ -99,16 +96,6 @@ describe('Custom Fonts', () => {
     await takeSnapshot(page, 'Custom Fonts Settings');
   });
 
-  it('should select font when clicked', async () => {
```
Comment (timarney) [inline packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js:102]: This should be replaced with a Jest test vs e2e.

File: packages/e2e-tests/src/specs/editor/backgroundAudio.js [hunk 22]
```diff
@@ -101,7 +101,7 @@ describe('Background Audio', () => {
...
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/backgroundAudio.js:105]: The file checking was failing here --- need to re-visit as to why.

File: packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js [hunk 23]
```diff
@@ -118,11 +118,15 @@ describe('Font Check Metrics', () => {
     mockResponse = undefined;
   });
 
-  afterAll(() => {
+  afterAll(async () => {
+    await page.setRequestInterception(false);
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js:122]: Was missing ` await page.setRequestInterception(false);`

File: packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js [hunk 24]
```diff
@@ -26,7 +26,8 @@ import {
   uploadFile,
 } from '@web-stories-wp/e2e-test-utils';
 
-describe('Inserting WebM Video', () => {
+// eslint-disable-next-line jest/no-disabled-tests
+describe.skip('Inserting WebM Video', () => {
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/media/insertWebMVideo.js:30]: Will re-visit --- this file was getting a 404.

File: packages/e2e-tests/src/specs/editor/statusCheck.js [hunk 25]
```diff
@@ -27,7 +27,8 @@ import {
  */
 import { addAllowedErrorMessage } from '../../config/bootstrap';
 
-describe('Status Check', () => {
+// eslint-disable-next-line jest/no-disabled-tests
+describe.skip('Status Check', () => {
```
Comment (timarney) [inline packages/e2e-tests/src/specs/editor/statusCheck.js:31]: There might be something going on here with Network requests -- need to narrow that down.

File: packages/e2e-tests/src/config/bootstrap.js [hunk 26]
```diff
@@ -101,6 +101,11 @@ const ALLOWED_ERROR_MESSAGES = [
 
   // See https://www.chromestatus.com/feature/508239670987980
   "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load",
+
+  // See https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1178865825
+  'Bundle not found for language en:',
```
Comment (swissspidy) [inline packages/e2e-tests/src/config/bootstrap.js]: The link does not really provide any additional value. Let's do something like this instead.

```suggestion
  // Sometimes the AMP viewer can fail to load translations when viewing a story.
  'Bundle not found for language en:',
```

File: packages/e2e-tests/src/config/bootstrap.js (hunk 15 above)
Comment (swissspidy) [reply packages/e2e-tests/src/config/bootstrap.js:108]: A bit unfortunate that this error message is quite generic. Do we now _anything_ about where this error message is coming from (stack trace)? Let's add a comment explaining that it's not clear where this is coming from.

File: packages/e2e-tests/src/jest.config.js (hunk 20 above)
Comment (swissspidy) [reply packages/e2e-tests/src/jest.config.js]: Don't think we need to remove it from here. Doesn't cause any harm + we should do a fast-follow with a couple of a11y tests anyway.

File: packages/e2e-tests/src/jest.config.js (hunk 17 above)
Comment (swissspidy) [reply packages/e2e-tests/src/jest.config.js:52]: So is the default output more useful than the dots for the e2e tests?

File: packages/e2e-tests/src/specs/dashboard/dashboard.js [hunk 27]
```diff
@@ -45,7 +45,8 @@ describe('Stories Dashboard', () => {
     await takeSnapshot(page, 'Stories Dashboard', { percyCSS });
   });
 
-  it('should be able to skip to main content of Dashboard for keyboard navigation', async () => {
+  //eslint-disable-next-line jest/no-disabled-tests -- https://github.com/GoogleForCreators/web-stories-wp/runs/7301628196?check_suite_focus=true#step:9:19
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/dashboard/dashboard.js]: Let's not link to individual runs. These logs disappear after a while.

Let's write a short explanation instead + create a ticket to fix these skipped tests.

File: packages/e2e-tests/src/puppeteerEnvironment.js [hunk 28]
```diff
@@ -39,15 +40,42 @@ class PuppeteerEnvironment extends OriginalEnvironment {
...
+
+      await this.storeArtifacts(testName, errorMessages);
+
+      if (eventError.includes('JestAssertionError')) {
+        // return already handled
+        return;
+      }
+
+      // eslint-disable-next-line no-console
+      console.log(' Unhandled event(' + event.name + '): ' + eventError);
```
Comment (swissspidy) [inline packages/e2e-tests/src/puppeteerEnvironment.js]: Hmm now this leads to duplicate output:

https://github.com/GoogleForCreators/web-stories-wp/runs/7356729173?check_suite_focus=true#step:8:86

Maybe not needed anymore?

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js (hunk 21 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js:102]: Let's create a ticket for it

File: packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js [hunk 29]
```diff
@@ -118,11 +118,15 @@ describe('Font Check Metrics', () => {
...
     stopRequestInterception();
   });
 
-  it('should receive updated font metrics and not alter history', async () => {
+  jest.retryTimes(3);
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js]: Maybe move this to the top of the describe block or to the top of the file?

Also, should we try `jest.retryTimes(3, {logErrorsBeforeRetry: true});`?

File: packages/e2e-tests/src/config/bootstrap.js (hunk 15 above)
Comment (timarney) [reply packages/e2e-tests/src/config/bootstrap.js:108]: For "Failed to fetch":
https://github.com/GoogleForCreators/web-stories-wp/runs/7257276613?check_suite_focus=true#step:9:23

Comment (timarney) [reply packages/e2e-tests/src/config/bootstrap.js:108]: Bundle not found --- lost the run # but ...

https://github.com/GoogleForCreators/web-stories-wp/pull/11782#issuecomment-1178865825

File: packages/e2e-tests/src/jest.config.js (hunk 17 above)
Comment (timarney) [reply packages/e2e-tests/src/jest.config.js:52]: Was finding it helpful to watch the tests in the CI runs to see where things we're hanging i.e. would get to text x or y and than hang vs the .... can swap back but that's my reasoning.

File: packages/e2e-tests/src/puppeteerEnvironment.js (hunk 28 above)
Comment (timarney) [reply packages/e2e-tests/src/puppeteerEnvironment.js]: Removed ---it's in the artifacts logs as needed.

File: packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js (hunk 29 above)
Comment (timarney) [reply packages/e2e-tests/src/specs/editor/fontCheck/fontCheckMetrics.js]: Moved ... I tried {logErrorsBeforeRetry: true} at one point.  Didn't seem to be working but worth another try.

File: packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js (hunk 21 above)
Comment (timarney) [reply packages/e2e-tests/src/specs/dashboard/settings/adminUser/customFonts.js:102]: https://github.com/GoogleForCreators/web-stories-wp/issues/11929

**Comment by swissspidy** [comment]
There are still some failing tests. If they're flakey let's skip them & create tickets to fix them.

It would be great if we could merge this PR with passing tests, otherwise it's a bit pointless.

**Comment by swissspidy** [comment]
Can we update Puppeteer here while we're at it? Our current version is a bit out of date.

**Comment by swissspidy** [comment]
@timarney we should not remove the patch but update it instead :-) or is it no longer needed?

**Comment by timarney** [comment]
> @timarney we should not remove the patch but update it instead :-) or is it no longer needed?

Trying a run without it .

Will update it after that.


https://github.com/puppeteer/puppeteer/blob/main/src/common/ExecutionContext.ts

File: package.json [hunk 30]
```diff
@@ -144,7 +144,7 @@
     "postcss-jsx": "^0.36.4",
     "postcss-syntax": "^0.36.2",
     "prettier": "^2.7.1",
-    "puppeteer": "^14.1.1",
+    "puppeteer": "^15.4.1",
```
Comment (swissspidy) [inline package.json]: They're moving fast, now at 15.5.0 with latest Chromium

Comment (timarney) [reply package.json]: Ya for sure

Comment (swissspidy) [reply package.json]: Let's update to that one while at it

**Comment by swissspidy** [comment]
One failing test `Shopify settings › should let me see and update shopping provider settings`

File: packages/e2e-tests/src/specs/editor/pendingStories.js [hunk 31]
```diff
@@ -24,7 +24,8 @@ import {
   editStoryWithTitle,
 } from '@web-stories-wp/e2e-test-utils';
 
-describe('Pending Stories', () => {
+// eslint-disable-next-line jest/no-disabled-tests -- net::ERR_CONNECTION_RESET
+describe.skip('Pending Stories', () => {
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/pendingStories.js]: Needs a ticket to address this.

Also, does `retryTimes` help for this particular test?

File: packages/e2e-tests/src/specs/editor/saveStory.js [hunk 32]
```diff
@@ -63,14 +63,16 @@ describe('Saving Story', () => {
     stopRequestInterception();
   });
 
-  it('should display published dialog', async () => {
+  //eslint-disable-next-line jest/no-disabled-tests -- error: TimeoutError: Navigation timeout of 10000 ms exceeded
+  it.skip('should display published dialog', async () => {
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/saveStory.js:67]: Let's create a ticket for these two skipped tests

File: packages/e2e-tests/src/specs/editor/statusCheck.js (hunk 25 above)
Comment (swissspidy) [reply packages/e2e-tests/src/specs/editor/statusCheck.js:31]: Let's create a ticket, updating the comment here to include the ticket number

File: packages/e2e-tests/src/specs/wordpress/archive.js [hunk 33]
```diff
@@ -146,7 +146,8 @@ describe.skip('Stories Archive', () => {
     describe('Widget', () => {
       withPlugin('classic-widgets');
 
-      it('should be able to add widget', async () => {
+      // eslint-disable-next-line jest/no-disabled-tests -- [TimeoutError: Element .widget-liquid-right .web-stories-field-wrapper not found
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/wordpress/archive.js]: Let's create a ticket, updating the comment here to include the ticket number

File: patches/puppeteer+15.4.1.patch [hunk 34]
```diff
@@ -0,0 +1,20 @@
+diff --git a/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js b/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js
```
Comment (swissspidy) [inline patches/puppeteer+15.4.1.patch]: Need to update the file name here now to `15.5.0`

File: packages/e2e-tests/src/specs/editor/shopping/productMenu.js [hunk 35]
```diff
@@ -41,8 +41,8 @@ describe('Shopping product', () => {
         return false;
       });
     }
-
-    it('should show a floating menu with product dropdown', async () => {
+    //eslint-disable-next-line jest/no-disabled-tests -- related #11976 failing "focus" in the beforeAll above setShoppingProvider('WooCommerce');
```
Comment (swissspidy) [inline packages/e2e-tests/src/specs/editor/shopping/productMenu.js]: Warrants its own ticket or not?

**Review by swissspidy — COMMENTED** [review]
You seem to have added a git submodule here by accident

Screenshot 2022-07-25 at 12 07 44

File: packages/e2e-tests/src/specs/editor/pendingStories.js (hunk 31 above)
Comment (timarney) [reply packages/e2e-tests/src/specs/editor/pendingStories.js]: Removed - didn't seem to.

**Comment by timarney** [comment]
Running into percy issues.

```
[percy] Encountered an error uploading snapshot: Story Background Audio
[percy] Error: Cannot create snapshot, the build is already finalized. If this happens frequently in a parallel test suite, you may want to use a "finalize all" step in CI: 
```

**Comment by swissspidy** [comment]
This can happen when re-running failing tests multiple times, shouldn't cause issues

**Comment by timarney** [comment]
Outside of the Percy noise I think all the skips etc... have issues assigned to them now.

**Comment by swissspidy** [comment]
I see two issues right now at first glance:

First of all, there are still some failing tests, see https://github.com/GoogleForCreators/web-stories-wp/runs/7520603772?check_suite_focus=true#step:10:165

Excerpt from logs:

```
FAIL packages/e2e-tests/src/specs/editor/prePublishChecklist/adminUser.js (22.544 s)
  ● Pre-Publish Checklist : Admin User › should focus on media button when poster image issue card is clicked

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"],["Failed to load resource: net::ERR_CONNECTION_CLOSED"]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)
          at runMicrotasks (<anonymous>)

FAIL packages/e2e-tests/src/specs/editor/editor.js (23.118 s)
  ● Story Editor › should preview story with development mode

    TimeoutError: Text not found "/Debug/i"
    waiting for function failed: timeout 2000ms exceeded

      76 |
      77 |     await expect(previewPage).toMatch(/Preview/i);
    > 78 |     await expect(previewPage).toMatch(/Debug/i);
         |     ^
      79 |     await expect(previewPage).toMatch(/Add device/i);
      80 |
      81 |     await previewPage.waitForSelector('amp-story-player');

      at Object.<anonymous> (packages/e2e-tests/src/specs/editor/editor.js:78:5)

```

If these fail consistently we need to skip them.

Second, the sharding does not seem to work for Percy runs 😬  So basically every one of the `chrome - WP latest (x/4)` groups runs the full test suite. Not very efficient 🙃 
Not a fault of this PR, but I just noticed it now.

Looks like it's because of how the arg is passed down to the command, see how the `--shard` arg is lost here:

```
Run npm run test:e2e:percy -- --shard=$SHARD

> test:e2e:percy
> percy exec --parallel --config=percy.config.yml -- npm run test:e2e "--shard=2/4"

[percy] Percy has started!
[percy] Running "npm run test:e2e --shard=2/4"

> test:e2e
> cross-env JEST_PUPPETEER_CONFIG=jest-puppeteer.config.cjs jest --runInBand --config=packages/e2e-tests/src/jest.config.js <--------------- missing shard
```

854c67b198743a3692652d58995cf60742b5ff08 should fix it.

**Comment by swissspidy** [comment]
Look how fast this is now with proper sharding:

Screenshot 2022-07-26 at 17 07 42

We should be able to reduce to just 2 shards with similar execution time

This one is still failing:

```
FAIL packages/e2e-tests/src/specs/editor/editor.js (29.372 s)
  ● Story Editor › should preview story with development mode

    TimeoutError: Text not found "/Preview/i"
    waiting for function failed: timeout 2000ms exceeded

      75 |     await previewPage.waitForSelector('.i-amphtml-story-dev-tools-header');
      76 |
    > 77 |     await expect(previewPage).toMatch(/Preview/i);
         |     ^
      78 |     await expect(previewPage).toMatch(/Debug/i);
      79 |     await expect(previewPage).toMatch(/Add device/i);
      80 |

      at Object.<anonymous> (packages/e2e-tests/src/specs/editor/editor.js:77:5)
```

Let's disable it & create a ticket for it.

We'd want to merge this PR with passing tests.

**Comment by timarney** [comment]
@swissspidy here's a passing run for the end to end tests with no retries 

https://github.com/GoogleForCreators/web-stories-wp/runs/7528661369?check_suite_focus=true


Screen Shot 2022-07-26 at 5 13 23 PM

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
Still passing!

@timarney Kudos for all your hard work on this!! 👏 👏 

Now on to the next challenge of addressing all these flakey tests...
