### PR TITLE
Fix Text sets related Karma tests

### LINKED ISSUE #9633: Fix flaky Karma test for Text Sets auto-styling
## Bug Description
Fix the following test in the `textSets.cuj.karma.js` file:
`should add text color based on background`

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by miina**
## Summary
Enables and/or fixes the following Karma tests in `textSets.cuj.karma.js` file:
- `should add text color based on background`
- `should allow user to drag and drop text set onto page`

## User-facing changes
N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9633

### CODE REVIEW

File: packages/story-editor/src/components/canvas/useInsertTextSet.js [hunk 1]
```diff
@@ -94,10 +94,10 @@ function useInsertTextSet(shouldUseSmartColor = false) {
         const allColorsEqual = textElementsContrasts.every(
           (contrast) =>
             contrast === null ||
```
Comment (miina) [inline packages/story-editor/src/components/canvas/useInsertTextSet.js:96]: If getting the image data fails from the generated image, it returns `{ color: null }` which was not considered here and failed when trying to get `r`, `g`, `b`, `a` from `null` in case it happened.

File: packages/story-editor/src/components/library/panes/text/karma/textSets.cuj.karma.js [hunk 2]
```diff
@@ -88,10 +88,7 @@ describe('CUJ: Text Sets (Text and Shape Combinations): Using Text Sets', () =>
     expect((await getSelection()).length).toBeGreaterThan(1);
   });
 
-  // Disable reason: flakey tests.
-  // See https://github.com/google/web-stories-wp/pull/6162
-  // eslint-disable-next-line jasmine/no-disabled-tests
-  xit('should allow user to drag and drop text set onto page', async () => {
+  it('should allow user to drag and drop text set onto page', async () => {
```
Comment (miina) [inline packages/story-editor/src/components/library/panes/text/karma/textSets.cuj.karma.js:91]: This test seems to work now (will rerun it a few times though) -- I think the failure came from always enabling the smart colors at that time and thus taking more time. If it's still flaky, will debug it more though.

**Review by barklund — APPROVED** [review]
If it works now, awesome!
