### PR TITLE
Fix various background inconsistencies

### LINKED ISSUE #1411: Inconsistencies in "set as background" option cropping image
## Bug Description

When I set an image as background by clicking "Set as background" in the Design panel vs. if I drag the image to the edges of the canvas, then "Remove as background" the behavior is different. Sometimes the image shows as cropped others as not. **Setting as background should NOT crop the image regardless of the method.** 

## Expected Behaviour

No matter how I "Set as background" (whether design panel or dragging to canvas edge) the "remove as background" result should be the same. 

## Steps to Reproduce

However, what I observe is the following: 
1. Set as background on Design panel -> remove as background -> image shows again and it is not cropped **(expected, OK)**
2. Drag to canvas edge to set as background -> remove as background -> image shows cropped as a square **(not expected)**

## Screenshots

Video: 
[Set as background crop vs. not.zip](https://github.com/google/web-stories-wp/files/4559002/Set.as.background.crop.vs.not.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions
See #1821.

### LINKED ISSUE #1821: Background Media behavior inconsistency
## Bug Description

The background behavior seems to be inconsistent/unexpected at times.

For example:
- Setting an overlay to a Page and then adding background media by dragging it directly from Library seems to keep the properties of the previous Overlay.
- Setting an overlay to a Page, then adding background from an existing Media Element by clicking "Set as background" removes the overlay.

Same goes for flipping: flipping seems to be stay when dragging and dropping to a background but not when using "Set as background".

## Expected Behaviour

It feels like Overlay should always remain for different background Media since the Overlay can be set for a Page separately.
It feels like Flipping should never remain for different background Media since flipping can be set per Media, not for a Page.

TBD by UX.

## Steps to Reproduce

1. Add a Page and set overlay
2. Drag and drop an image to be the background
3. See the overlay persisting.
4. Now click "Unset as background", see the overlay being unset
5. Add the Overlay again
6. Click "Set as background"
7. See the overlay being unset again whereas with drop targets it did not.

The same happens with Flipping.

## Screenshots
May-18-2020 12-43-27

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

#### Scenario 1
1. Set background image
1. Flip it
1. Drag image from library
1. Hover over background image edge and see new image **temp replacing background** with **no flip**
1. Drop new image over background image edge and see new image **replacing background** with **no flip**

#### Scenario 2
1. Set background image
1. Flip it
1. Click another image in library
1. Start dragging new image placed on canvas
1. Hover over background image edge and see new image **temp replacing background** with **no flip**
1. Drop new image over background image edge and see new image **replacing background** with **no flip**

#### Scenario 3
1. Set background image
1. Flip it
1. Click another image in library
1. Click the "set as background" button for new image and see new image **replacing background** with **no flip**

#### Scenario 4
1. Set background image
1. Assign linear overlay to background
1. Drag image from library
1. Hover over background image edge and see new image **temp replacing background** with **same overlay**
1. Drop new image over background image edge and see new image **replacing background** with **same overlay**

#### Scenario 5
1. Set background image
1. Assign linear overlay to background
1. Click another image in library
1. Start dragging new image placed on canvas
1. Hover over background image edge and see new image **temp replacing background** with **same overlay**
1. Drop new image over background image edge and see new image **replacing background** with **same overlay**

#### Scenario 6
1. Set background image
1. Assign linear overlay to background
1. Click another image in library
1. Click the "set as background" button for new image and see new image **replacing background** with **same overlay**

#### Scenario 7
1. Click an image in library
1. Start dragging new image
1. Drop new image over background image edge and see image **converted to background**
1. Press "unset as background" and see the image **restored to its original size**

#### Scenario 8
1. Click an image in library
1. Press "set as background" and see image **converted to background**
1. Press "unset as background" and see the image **restored to its original size**

### PR DESCRIPTION
**Pull request by barklund**
## Summary

Fix a number of inconsistencies reported about background setting and removing.

Note that this does not yet reflect the changes coming up after #1207 is merged - in particular for this PR overlay still belongs to and sticks with the page, not the individual background image.

## Relevant Technical Choices

For one, this makes sure to use `combineElements` when clicking "Set as background" to make sure same code path is followed.

Then make sure flip is also copied when combining elements, as the new element should not inherit the flip of the old element, but rather keep its own setting.

Finally, this fetches more info about currently dragged image when showing temp drop replacements. This required reworking some things in `DisplayElement` to make sure replacement mask is correctly flipped or not.

## User-facing changes

This makes sure, that no matter how you set an image as background, you get the same consistent behavior on a number of topics - whatever that is decided to be.

## Testing Instructions

--

Fixes #1411
Fixes #1821

### CODE REVIEW

File: assets/src/edit-story/components/canvas/displayElement.js [hunk 1]
```diff
@@ -119,14 +120,24 @@ function DisplayElement({ element, previewMode, page }) {
...
+              style={{
+                opacity: opacity ? opacity / 100 : null,
+              }}
+              previewMode={previewMode}
+            >
+              <Replacement element={replacementElement} box={box} />
+            </WithMask>
+          )}
+        </ReplacementContainer>
+      )}
```
Comment (barklund) [inline assets/src/edit-story/components/canvas/displayElement.js]: So there's  slight issue with this - when you hover over a blob with a different flip setting the dragging image has, the blob can be seen in both states at the same time. This can be fixed by wrapping the "real" display element in a container similar to `ReplacementContainer`, but it just fades "the other way".

@wassgha, WDYT here? I think you made this originally.

Comment (miina) [reply assets/src/edit-story/components/canvas/displayElement.js]: @barklund Note there's also an existing issue with flipped shapes: https://github.com/google/web-stories-wp/issues/1929

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js [hunk 2]
```diff
@@ -80,6 +80,7 @@ function combineElements(state, { firstId, firstElement, secondId }) {
     focalX = 50,
     focalY = 50,
     isFill = false,
+    flip = { vertical: false, horizontal: false },
```
Comment (miina) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Should we perhaps have a constant for these repeating default values?

**Comment by miina** [comment]
From testing:
Not directly related to this PR, however, it looks like currently, the first drop target of the page is used, however, actually the visually top target should be used -- the elements array should be reversed at some point when finding the active drop target.

Currently, it's not really possible to drop to `isFill` element since it just replaces the background instead -- the background gets activated as the drop target and not the top Fill element.

bg

Will create a new issue for it (unless you want to fix it here to make it work with `isFill` as expected for testing purposes).

**Comment by barklund** [comment]
> Currently, it's not really possible to drop to `isFill` element since it just replaces the background instead -- the background gets activated as the drop target and not the top Fill element.

I've reported that exact problem some time ago in https://github.com/google/web-stories-wp/issues/943.

**Comment by miina** [comment]
> I've reported that exact problem some time ago in #943.

Alright, note that the order of the drop targets activation is an issue with non-fill elements as well -- e.g. if there are 2 elements covering each other, the lower one gets priority.

Looks like `isFill` is becoming irrelevant: #1932

File: assets/src/edit-story/components/dropTargets/provider.js [hunk 3]
```diff
@@ -82,11 +82,25 @@ function DropTargetsProvider({ children }) {
         return;
       }
 
+      const {
+        scale = 100,
```
Comment (dvoytenko) [inline assets/src/edit-story/components/dropTargets/provider.js]: Can we get these from `elements/x/index.js` `defaultAttributes`?

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Done in 0994bb0 - though I'm not a huge fan of importing from elements here, I do think it's the best case. Alternatively we'd do this defaulting out where `combineElements` is called, but that's less nice.

File: assets/src/edit-story/components/dropTargets/provider.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/components/dropTargets/provider.js]: Done in 0994bb0 though indirectly.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Found a better solution in 9dfc2d2e (also the other solution didn't work because of circular dependencies).

**Review by miina — APPROVED** [review]
LGTM.

There's still the shapes + flipping issue but this might be a general issue instead: #1929

File: assets/src/edit-story/components/canvas/displayElement.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/components/canvas/displayElement.js]: I say we punt this to that one. Adding a mention there as well.

Comment (barklund) [reply assets/src/edit-story/components/canvas/displayElement.js]: Or actually in #1111.

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js [hunk 4]
```diff
@@ -0,0 +1,209 @@
...
+
+      // Verify new background element has the correct image
+      const bg = await getCanvasBackgroundElement(fixture);
+      const bgImg = bg.querySelector('img');
+      expect(bgImg).toHaveSource(imageData.resource.src);
+
+      // And verify that we no longer have a replacement element
+      const rep2 = await getCanvasBackgroundReplacement(fixture);
+      expect(rep2).toBeEmpty();
+    });
```
Comment (barklund) [inline assets/src/edit-story/components/dropTargets/karma/background.karma.js]: I feel this reads very well now, but it required quite a few helper functions and custom matchers to be this compact. This definitely has potential though - and runs quickly!

File: assets/src/edit-story/components/dropTargets/karma/background.karma.js [hunk 5]
```diff
@@ -0,0 +1,209 @@
...
+
+      // Drag the image element to the background
+      await dragToDropTarget(fixture, imageData.id, backgroundId);
+
+      // Verify that bg replacement is no longer empty
+      expect(rep1).not.toBeEmpty();
+
+      // Verify that replacement img has correct source
+      const replaceImg = rep1.querySelector('img');
+      expect(replaceImg).toHaveSource(imageData.resource.src);
```
Comment (barklund) [inline assets/src/edit-story/components/dropTargets/karma/background.karma.js]: Yeah yeah, this matcher is of course way too specific, but just wanted to test the syntax out.

Comment (barklund) [reply assets/src/edit-story/components/dropTargets/karma/background.karma.js]: A better matcher would be:

```js
      expect(replaceImg).toHaveProperty('src', imageData.resource.src);
```

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js [hunk 6]
```diff
@@ -76,10 +81,11 @@ function combineElements(state, { firstId, firstElement, secondId }) {
...
     resource,
-    scale = 100,
-    focalX = 50,
-    focalY = 50,
-    isFill = false,
+    scale = DEFAULT_ATTRIBUTES_FOR_MEDIA.scale,
+    focalX = DEFAULT_ATTRIBUTES_FOR_MEDIA.focalX,
+    focalY = DEFAULT_ATTRIBUTES_FOR_MEDIA.focalY,
+    isFill = DEFAULT_ATTRIBUTES_FOR_MEDIA.isFill,
+    flip = {},
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: What does empty `flip` mean?

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js [hunk 7]
```diff
@@ -76,10 +81,11 @@ function combineElements(state, { firstId, firstElement, secondId }) {
 
   const {
     resource,
-    scale = 100,
-    focalX = 50,
-    focalY = 50,
-    isFill = false,
+    scale = DEFAULT_ATTRIBUTES_FOR_MEDIA.scale,
```
Comment (dvoytenko) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Why not just `...DEFAULT_ATTRIBUTES_FOR_MEDIA`?

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 7 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Hm, yes, this could be done cleaner...

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: It's functionally the same as `flip: { vertical: false, horizontal: false }`, just simpler. Would you prefer it more explicit?

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 7 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Changed in dcc1ea85e.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Changed in dcc1ea85e (but essentially still the same).

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 7 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Ok. I guess it's ok. Just wanted to clarify. Didn't realize we allowed an empty object for that.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js (hunk 6 above)
Comment (dvoytenko) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/combineElements.js]: Ok. I guess it's ok. Just wanted to clarify. Didn't realize we allowed an empty object for that.

**Review by dvoytenko — APPROVED** [review]

**Comment by barklund** [comment]
@dvoytenko, I had some problems getting the karma tests involving dragging elements from library to canvas to work. I don't really know what the problem is, because it works in debug mode in karma run, just not in primary run. It fails both in headless and "headfull" (sometimes mouse tests fails in "headfull" mode because actual mouse interferes with puppeteer-controlled mouse). I have `xit`'ed the tests in this PR to get on with it.

**Comment by dvoytenko** [comment]
@barklund That's fine. I'll take a look at the text and what might be going on there. In the meantime, feel free to merge.

**Comment by barklund** [comment]
Hm, karma tests are now failing. Looking to fix...
