### PR TITLE
KSES: fix HTML attributes inadvertently being removed

### LINKED ISSUE #6540: KSES: width attribute removed for images in all post types
## Bug Description

As reported at https://wordpress.org/support/topic/bug-web-stories-1-4-0-removes-post-width-for-author/, there seems to be an issue with the allowlist in our KSES class.

I assume it's because how we merge our allowed tags with the [existing allowlist in WordPress](https://github.com/WordPress/wordpress-develop/blob/a280d5704b9265c528a4a04c5152e5fee18716d0/src/wp-includes/kses.php), as the attributes seem to be overridden. Ours doesn't contain the `width` attribute.

There's actually quite the mismatch:

https://github.com/WordPress/wordpress-develop/blob/a280d5704b9265c528a4a04c5152e5fee18716d0/src/wp-includes/kses.php#L227-L239

https://github.com/google/web-stories-wp/blob/a21c394d6c59b1290f4efad589823f164de74823/includes/KSES.php#L536-L551

That is probably the case for other tags as well, not just `img`. So need to check those too.

## Expected Behaviour

`width` attributes of images in other post types should not be removed.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

Use `array_merge_recursive`?

Tests?

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Context

Make sure existing kses attributes are note removed.

## Summary

Implement [array_merge_recursive_distinct](https://github.com/Yoast/wordpress-seo/blob/219014897b95465fa1cd4d23a72b0c74864f6dba/inc/class-wpseo-meta.php#L938-L983) in our codebase. Add some basic unit tests.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6540

### CODE REVIEW

File: includes/KSES.php [hunk 1]
```diff
@@ -564,13 +564,58 @@ public function filter_kses_allowed_html( $allowed_tags ) {
...
+	 * Difference with native array_merge_recursive():
+	 * array_merge_recursive converts values with duplicate keys to arrays rather than
+	 * overwriting the value in the first array with the duplicate value in the second array.
+	 *
+	 * array_merge_recursive_distinct does not change the data types of the values in the arrays.
+	 * Matching keys' values in the second array overwrite those in the first array, as is the
+	 * case with array_merge.
+	 *
+	 * Freely based on information found on http://www.php.net/manual/en/function.array-merge-recursive.php
+	 *
```
Comment (spacedmonkey) [inline includes/KSES.php:583]: Not sure what version to add here, as would go out in 1.5 or 1.4.1?

Comment (swissspidy) [reply includes/KSES.php:583]: 1.5

File: includes/KSES.php [hunk 2]
```diff
@@ -564,13 +564,58 @@ public function filter_kses_allowed_html( $allowed_tags ) {
...
+	 * @link https://github.com/Yoast/wordpress-seo/blob/219014897b95465fa1cd4d23a72b0c74864f6dba/inc/class-wpseo-meta.php#L938-L983
```
Comment (swissspidy) [inline includes/KSES.php]: Hmm... Yoast SEO is GPL, we cannot really just copy their code into ours as it's not compatible with Apache.

File: tests/phpunit/tests/KSES.php [hunk 3]
```diff
@@ -308,6 +332,25 @@ public function test_filter_kses_allowed_html( $html, $expected ) {
...
+				'width' => true,
+			],
+		];
+
+		$result = $kses->filter_kses_allowed_html( $allowed_tags );
+		$this->assertArrayHasKey( 'img', $result );
+		$this->assertArrayHasKey( 'width', $result['img'] );
+	}
+
 	public function data_test_filter_kses_allowed_html() {
```
Comment (swissspidy) [inline tests/phpunit/tests/KSES.php:369]: Let's add a test case to the data provider here with a simple `img` tag

File: includes/KSES.php (hunk 2 above)
Comment (spacedmonkey) [reply includes/KSES.php]: This pastebin is from 2012 - https://pastebin.com/tpSqBTc2

Comment (spacedmonkey) [reply includes/KSES.php]: @swissspidy So what do I do here, do I have write the code?

Comment (spacedmonkey) [reply includes/KSES.php]: Earliest reference I can see https://www.php.net/manual/en/function.array-merge-recursive.php#89684

Comment (swissspidy) [reply includes/KSES.php]: IANAL, but since php.net comments and documentation is under Creative Commons it should be OK.

File: tests/phpunit/tests/KSES.php [hunk 4]
```diff
@@ -326,6 +369,10 @@ public function data_test_filter_kses_allowed_html() {
 				'<div class="foo" id="bar" style="color: pink" role="main" title="Test"></div>',
 				'<div class="foo" id="bar" style="color: pink" role="main" title="Test"></div>',
 			],
+			'Img Attributes'       => [
+				'<img src="http://www.example.com/test.jpg" alt="Example" height="200" width="500" />',
+				'<img src="http://www.example.com/test.jpg" alt="Example" height="200" width="500" />',
+			],
```
Comment (swissspidy) [inline tests/phpunit/tests/KSES.php:390]: And just to be safe, this test fails without the change in this PR?

File: tests/phpunit/tests/KSES.php [hunk 5]
```diff
@@ -308,6 +332,25 @@ public function test_filter_kses_allowed_html( $html, $expected ) {
 		remove_filter( 'wp_kses_allowed_html', [ $kses, 'filter_kses_allowed_html' ] );
 	}
 
+	/**
+	 * Testing the filter_kses_allowed_html() method.
+	 *
+	 * @covers ::filter_kses_allowed_html
+	 * @covers ::array_merge_recursive_distinct
+	 */
+	public function test_filter_kses_allowed_html_filter() {
```
Comment (swissspidy) [inline tests/phpunit/tests/KSES.php]:
```suggestion
	public function test_filter_kses_allowed_html_uses_deep_merge() {
```

Otherwise the name is way too similar to the other test

File: tests/phpunit/tests/KSES.php [hunk 6]
```diff
@@ -308,6 +332,25 @@ public function test_filter_kses_allowed_html( $html, $expected ) {
...
+		$kses         = new \Google\Web_Stories\KSES();
+		$allowed_tags = [
+			'img' => [
+				'width' => true,
```
Comment (swissspidy) [inline tests/phpunit/tests/KSES.php:356]: Let's actually add `width` to the list of `img `attributes in the KSES class. That's the P0 concern.

And then use some other `$allowed_tags` value for this test of course.

File: includes/KSES.php (hunk 1 above)
Comment (spacedmonkey) [reply includes/KSES.php:583]: Fixed.

File: tests/phpunit/tests/KSES.php (hunk 6 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/KSES.php:356]: Done.

File: tests/phpunit/tests/KSES.php (hunk 4 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/KSES.php:390]: Both adding 'width' and `array_merge_recursive_distinct` fix the issue alone. I think we should add `array_merge_recursive_distinct` still, as it will fix other issues in the future.

File: tests/phpunit/tests/KSES.php (hunk 3 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/KSES.php:369]: Done

File: tests/phpunit/tests/KSES.php [hunk 7]
```diff
@@ -308,6 +332,32 @@ public function test_filter_kses_allowed_html( $html, $expected ) {
...
+	 * Testing the filter_kses_allowed_html() method.
+	 *
+	 * @covers ::filter_kses_allowed_html
+	 * @covers ::array_merge_recursive_distinct
+	 */
+	public function test_filter_kses_allowed_html_uses_deep_merge() {
+		$kses         = new \Google\Web_Stories\KSES();
+		$allowed_tags = [
+			'img' => [
+				'width' => true,
```
Comment (swissspidy) [inline tests/phpunit/tests/KSES.php:353]: PHPCS warning

File: includes/KSES.php [hunk 8]
```diff
@@ -564,13 +565,49 @@ public function filter_kses_allowed_html( $allowed_tags ) {
...
+	 *
+	 * Based on information found in http://www.php.net/manual/en/function.array-merge-recursive.php
+	 *
+	 * @since 1.5.0
+	 *
+	 * @param array ...$arrays [optional] Variable list of arrays to recursively merge.
+	 *
+	 * @return array An array of values resulted from merging the arguments together.
+	 */
+	public function array_merge_recursive_distinct( array ...$arrays ) {
```
Comment (swissspidy) [inline includes/KSES.php]: Let's make this protected. No reason for it to be public.

File: tests/phpunit/tests/KSES.php (hunk 4 above)
Comment (swissspidy) [reply tests/phpunit/tests/KSES.php:390]: Sure, yeah we can keep both.

Just wanted to make sure that this test works as expected, i.e. it should fail on `main`.

And I just confirmed that locally.

So all good 👍

File: includes/KSES.php (hunk 8 above)
Comment (spacedmonkey) [reply includes/KSES.php]: Fixed in https://github.com/google/web-stories-wp/pull/6542/commits/055bdbcac14e27cd8b382d8e5cd6c510262af304

File: tests/phpunit/tests/KSES.php (hunk 7 above)
Comment (spacedmonkey) [reply tests/phpunit/tests/KSES.php:353]: Fixed in https://github.com/google/web-stories-wp/pull/6542/commits/055bdbcac14e27cd8b382d8e5cd6c510262af304

**Review by swissspidy — APPROVED** [review]
