### PR TITLE
Dashboard: Implement new header designs 

### LINKED ISSUE #4960: Update dashboard header styles
Update header to new styles per https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=467%3A13745 

Heading and pills should be pulled in from the design system. Search to follow.

### LINKED ISSUE #4962: Update dashboard search styles
Use typeahead from design system and replace the custom one in the dashboard. 

https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

### LINKED ISSUE #5648: In RTL mode, clicking Published keyword results in All Stories being underlined and vice versa
## Bug Description

Setting the view mode from left hand side menu to right hand side shows a discrepancy in how the underline/highlight of Published / All Stories keyword within Stories Dashboard

## Expected Behaviour

When Published is clicked, the keyword Published should be underlined. Same with All Stories.

## Steps to Reproduce

- Go to My Stories Dashboard
- Click the “Switch to RTL” button to change the mode to right-to-left
- Click Published - note that the All Stories is underlined
- Click All Stories - note that the Published is underlined
- 

## Screenshots

image7

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Updates dashboard headers to new designs found in figma. 

## Summary

No new functionality. Updates the dashboard header to new designs, improves readability and adds minimum size on dashboard to avoid elements crashing into each other on smaller view ports. 

header demo

## Relevant Technical Choices

- Changes the shared `PageHeading` API so that `showSearch` is false by default, typeahead language is updated to be 'search' based and simplify the styles provided to `children` because now it'll always be centered and we don't have extra ✨  active styles to track. 
- Ripped out the old `typeahead` and `toggleButtonGroup`, as well as tragically out of date template filters that aren't in the new designs and just deadweight in the UI at this point. 
- Adjusted the min-width of dashboard in `PageStructure` to dashboard specific min-width (1098px) 
- Adds disabled color to pills when inactive and disabled. 
- Left aligns empty search w/ placeholder and search icon. No space shift anymore.

## To-do

- Design has made mention of possibly not disabling filters w/ 0 results but shifting the displayed message in the center content of the dashboard to new graphics. For now, no changes here. 
- Eventually it'd be nice to move the `shared/` directory in `views` out since they are pretty much all that will be left from the components, could combine the dashboard components with these since the logic there is minimum. Avoided moving things for the sake of the DIFF here. 

## User-facing changes

Design changes from this: 
Screen Shot 2021-02-18 at 1 28 42 PM

to this: 
Screen Shot 2021-02-18 at 1 28 50 PM

## Testing Instructions

Regression testing: 
- Clicking on filters on 'my stories' (all stories, drafts, published, private) limit the scope of the stories shown in the grid/list view 
- Search functionality still works the same (filtering as you type) 
- Also check that templates and settings views have updated heading style (just the heading is present, no search or filtering) 

New! 
- Try resizing the browser window and make sure that horizontal scroll is enforced when you drop to 1098px. Nothing should overlap anymore. 
- Swap to RTL, see that the header makes sense (this PR should fix #5648)

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #4960 
Fixes #4962

### CODE REVIEW

File: assets/src/dashboard/app/views/exploreTemplates/header/index.js [hunk 1]
```diff
@@ -22,102 +22,38 @@ import { __ } from '@web-stories-wp/i18n';
...
-        ariaLabel={__('Color Dropdown', 'web-stories')}
-        type={DROPDOWN_TYPES.COLOR_PANEL}
-        placeholder={__('Color', 'web-stories')}
-        items={selectedColors}
-        onClear={clearAllColors}
-        onChange={onNewColorSelected}
-      />
-    </HeadingDropdownsContainer>
-  ) : null;
-
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/exploreTemplates/header/index.js:105]: This is all tragically out of date. When it comes time to actually wire up filters I can't see this being that useful to have, it'll have to be redone. We need an API for the templates before this can happen at all. Taking it out to a) remove dead code and b) prevent further situations like the one last week where the in progress templates flag was turned on in staging and confused some newer team members :)

File: assets/src/dashboard/app/views/exploreTemplates/header/index.js [hunk 2]
```diff
@@ -22,102 +22,38 @@ import { __ } from '@web-stories-wp/i18n';
...
-        stories={templates}
-        showTypeahead={enableInProgressTemplateActions}
-        handleTypeaheadChange={
-          enableInProgressTemplateActions ? search.setKeyword : () => {}
-        }
-        typeaheadValue={search.keyword}
-      >
-        {TemplateFilters}
-      </PageHeading>
+      <PageHeading heading={__('Explore Templates', 'web-stories')} />
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/exploreTemplates/header/index.js:56]: Figma has heading of `Templates` updated to `Explore Templates` which makes sense because it matches the side nav.

File: assets/src/dashboard/app/views/exploreTemplates/header/index.js [hunk 3]
```diff
@@ -137,9 +73,7 @@ function Header({ filter, totalTemplates, search, templates, sort, view }) {
 
 Header.propTypes = {
   filter: FilterPropTypes.isRequired,
-  search: SearchPropTypes.isRequired,
   sort: SortPropTypes.isRequired,
-  templates: TemplatesPropType,
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/exploreTemplates/header/index.js:142]: templates were getting used by search, but search is never enabled here (we need an API first)

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 4]
```diff
@@ -44,13 +45,19 @@ import {
...
+import { Pill } from '../../../../../design-system';
+
+const StyledPill = styled(Pill)`
+  margin: 0 2px;
+  white-space: nowrap;
 
+  & > span {
+    padding-left: 8px;
+    color: ${({ theme }) => theme.colors.fg.tertiary};
+  }
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/myStories/header/index.js:60]: Pill count for stories updates the design from using parenthesis to basing it on color.

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 5]
```diff
@@ -66,6 +73,22 @@ function Header({
...
+      return [
+        ...acc,
+        {
+          label: story.title,
+          value: story.title,
+        },
+      ];
+    }, []);
+  }, [stories]);
+
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/myStories/header/index.js]: memoizing options here instead of in the old shared `typeahead` component. No changes in how this is getting reduced from before.

File: assets/src/dashboard/app/views/savedTemplates/header/index.js [hunk 6]
```diff
@@ -46,6 +46,22 @@ function Header({ filter, search, sort, templates, view }) {
     actions: { scrollToTop },
   } = useLayoutContext();
 
+  const searchOptions = useMemo(() => {
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/savedTemplates/header/index.js]: this is for posterity so we can turn on `in progress views` on the dashboard and avoid a crash. Same structure as stories.

File: assets/src/dashboard/app/views/shared/pageHeading.js [hunk 7]
```diff
@@ -18,100 +18,74 @@
...
-              handleChange={handleTypeaheadChange}
-            />
-          </SearchInner>
-        </SearchContainer>
+      {children && <HeadlineFilters>{children}</HeadlineFilters>}
+      {showSearch && (
+        <HeaderSearch>
+          <Search
+            placeholder={searchPlaceholder}
+            selectedValue={{ label: searchValue, value: searchValue }}
```
Comment (BrittanyIRL) [inline assets/src/dashboard/app/views/shared/pageHeading.js:80]: This is for the new search and what it expects to manage. Right now our typed input is also the value, but there's cases or potential for update where the value of the search isn't necessarily the string visible to the user.

File: assets/src/design-system/components/search/input/components.js [hunk 8]
```diff
@@ -136,9 +132,9 @@ const BaseDecorationContainer = css`
 export const ClearButton = styled.button`
   ${BaseDecorationContainer};
   display: ${({ isVisible }) => (isVisible ? 'flex' : 'none')};
-
+  outline: none;
   ${({ theme }) => themeHelpers.focusableOutlineCSS(theme.colors.border.focus)};
-  height: 32px;
+  height: 30px;
```
Comment (BrittanyIRL) [inline assets/src/design-system/components/search/input/components.js:137]: This is so that when a keyboard focus occurs the focus looks clean and tight against the input.

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 9]
```diff
@@ -90,38 +113,42 @@ function Header({
...
-            ) {
-              return null;
-            }
-            return {
-              handleClick: () => {
+      <>
+        {STORY_STATUSES.map((storyStatus) => {
+          if (
+            storyStatus.status === STORY_STATUS.PRIVATE &&
+            (!totalStoriesByStatus.private ||
```
Comment (embarks) [inline assets/src/dashboard/app/views/myStories/header/index.js]: let's make this check a positive boolean and not mix the logical operators in the conditional statement
```
const isStoryPrivate = storyStatus.status === STORY_STATUS.PRIVATE
// I think the following line can be updated to just be:
// !totalStoriesByStatus.private || !canReadPrivatePosts
// first part evaluates to true when totalStoriesByStatus.private is -1, 0, or undefined
const cantReadPrivate = !totalStoriesByStatus.private || totalStoriesByStatus.private < 1 || !canReadPrivatePosts
if (isStoryPrivate && cantReadPrivate) { ... }
```

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 10]
```diff
@@ -44,13 +46,18 @@ import {
...
 import { useDashboardResultsLabel } from '../../../../utils';
-import {
-  BodyViewOptions,
-  HeaderToggleButtonContainer,
-  PageHeading,
-} from '../../shared';
+import { BodyViewOptions, PageHeading } from '../../shared';
 import { useConfig } from '../../../config';
 
+const StyledPill = styled(Pill)`
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/header/index.js:53]: Seeing very faint lines near the edges before the focus box shadow. It may be an artifact of our box shadow too though 🤷 
image

File: assets/src/dashboard/app/views/myStories/header/index.js [hunk 11]
```diff
@@ -90,38 +113,42 @@ function Header({
...
+              }}
+              isActive={filter.value === storyStatus.value}
+              disabled={totalStoriesByStatus?.[storyStatus.status] <= 0}
+              aria-label={ariaLabel}
+            >
+              {label}
+              {labelCount && labelCount}
+            </StyledPill>
+          );
+        }).filter(Boolean)}
```
Comment (samwhale) [inline assets/src/dashboard/app/views/myStories/header/index.js:142]: nice

File: assets/src/dashboard/app/views/savedTemplates/header/index.js (hunk 6 above)
Comment (samwhale) [inline assets/src/dashboard/app/views/savedTemplates/header/index.js]: Nit: should we pull this out into a helper function since it's used in a couple places?

Tbh it's very readable so I'm not worried about repeating code. Adding an abstraction here doesn't win us anything.

File: assets/src/dashboard/theme.js [hunk 12]
```diff
@@ -132,17 +132,9 @@ const theme = {
...
-    borderRadius: 100,
-  },
   formatContainer: {
     height: 76,
   },
-  expandedTypeahead: {
-    borderRadius: 8,
-    boxShadow:
-      '0px 0.181152px 2.29372px rgba(0, 0, 0, 0.031357), 0px 0.500862px 5.15978px rgba(0, 0, 0, 0.045),0px 1.20588px 8.99337px rgba(0, 0, 0, 0.058643), 0px 4px 17px rgba(0, 0, 0, 0.09)',
-  },
```
Comment (samwhale) [inline assets/src/dashboard/theme.js:145]: excellent

File: assets/src/design-system/components/pill/index.js [hunk 13]
```diff
@@ -52,6 +52,7 @@ const StyledPill = styled.button(
 
     &:disabled {
       pointer-events: none;
+      color: ${isActive ? theme.colors.bg.primary : theme.colors.fg.disable};
```
Comment (samwhale) [inline assets/src/design-system/components/pill/index.js]: We could use the `:active` pseudo selector instead of the `isActive` prop if we'd like here 🤷. Easier since we leverage the browser functionality

I may be misunderstanding, but `isActive` may refer to a specific pill state rather than the button itself being active. In that case, I think we should rename this to something else 🤔. Maybe `isEnabled` or `isSelected`

**Review by samwhale — APPROVED** [review]
So so so dope how you got rid of so much dead code. It works great, and is keyboard accessible. Nice update!

File: assets/src/dashboard/app/views/myStories/header/index.js (hunk 10 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/header/index.js:53]: 🤔  I'll make a lil bug ticket to track.

File: assets/src/dashboard/app/views/savedTemplates/header/index.js (hunk 6 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/savedTemplates/header/index.js]: we could, i feel like it won't always be the same. savedTemplates is mostly just a shadow of my stories right now in an attempt to keep it "current"  so that when it's time to revisit and resurrect it, it isn't tragically out of date. That said, a helper doesn't hurt!

File: assets/src/design-system/components/pill/index.js (hunk 13 above)
Comment (BrittanyIRL) [reply assets/src/design-system/components/pill/index.js]: 🔑  renaming this is a good move, it's not actually when the pill itself is `:active` - you're right. that's confusing.

File: assets/src/dashboard/app/views/myStories/header/index.js (hunk 9 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/header/index.js]: yeah! thanks! completely looked over this as a potential area to get updated.

File: assets/src/design-system/components/pill/index.js (hunk 13 above)
Comment (BrittanyIRL) [reply assets/src/design-system/components/pill/index.js]: I'm actually going to leave this here because it is the _active_ state of the UI, the pill that is selected.

File: assets/src/dashboard/app/views/myStories/header/index.js (hunk 10 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/header/index.js:53]: https://github.com/google/web-stories-wp/issues/6537

File: assets/src/dashboard/app/views/myStories/header/test/header.js [hunk 14]
```diff
@@ -157,14 +160,27 @@ describe('My Stories <Header />', function () {
...
+    const draftsButton = getByRole('button', {
+      name: /Filter stories by Drafts/,
+    });
+    const publishedButton = getByRole('button', {
+      name: /Filter stories by Published/,
+    });
+
+    expect(allStoriesButton).toHaveTextContent('All Stories19');
+    expect(draftsButton).toHaveTextContent('Drafts9');
+    expect(publishedButton).toHaveTextContent('Published10');
```
Comment (maxyinger) [inline assets/src/dashboard/app/views/myStories/header/test/header.js:180]: wait... there's a `toHaveTextContent()` that filters out DOM tags?? 🤦 :the-more-you-know:

Comment (maxyinger) [reply assets/src/dashboard/app/views/myStories/header/test/header.js:180]: oh, but it's just to test an element with. I'm guessing there no prebuilt `getByTextContent` selector. nvmd

**Review by maxyinger — APPROVED** [review]
lgtm!

File: assets/src/dashboard/app/views/myStories/header/test/header.js (hunk 14 above)
Comment (BrittanyIRL) [reply assets/src/dashboard/app/views/myStories/header/test/header.js:180]: i think i got this from a PR you did last week 😝

**Comment by swissspidy** [comment]
@BrittanyIRL FYI there's now a merge conflict
