### PR TITLE
Fixed lasso selection

### LINKED ISSUE #6911: Fix lasso selection in new zoom canvas
## Feature Description

The new zoom implementation has broken canvas selection - both with and without zoom enabled.

This ticket should:

- [x] Fix lasso selection when zoom is disabled or zoom is set to fit
- [x] Fix lasso selection when zoom is enabled and the zoom is applied with scrollbars visible on screen
- [x] Make sure tests in `lasso.karma.js` work again and add extra tests for zoomed canvas

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Context

Fixes lasso selection by taking both the offsets of the full-bleed container and the page inside it into account.

Also re-enables tests, that know work as expected.

## User-facing changes

Lasso selection now works - even when zoomed!

### QA

This PR can be tested by following these steps:

1. Add an element
2. Lasso-select it in different ways and observe that the element is correctly selected or not whether it's inside the lasso or not.
3. Change zoom to 200%
4. Scroll down and right a bit
5. Repeat lasso selection and confirm that edges are found correctly.
6. Repeat for multiple elements and multiple zoom views

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6911

### CODE REVIEW

**Review by miina — APPROVED** [review]
Works great for the lasso.

It still feels like the fullbleed container should match the visible page area, or alternatively, the `PageAreaWithOverflow` should be used as the new reference everywhere (e.g. for all the tests etc.) instead of the fullbleed container - that change still seems to be the underlying cause for some issues (the tests that are still `xit`ted). WDYT?

File: assets/src/edit-story/components/canvas/layout.js [hunk 1]
```diff
@@ -360,6 +360,7 @@ const PageArea = forwardRef(function PageArea(
             background={background}
             isControlled={isControlled}
             isBackgroundSelected={isBackgroundSelected}
+            data-lasso-reference
```
Comment (miina) [inline assets/src/edit-story/components/canvas/layout.js]: Does this still need a separate lasso reference now when just the `fullbleedRef` could be used?

**Comment by miina** [comment]
@googlebot I consent.

**Comment by miina** [comment]
@googlebot I consent.
