### PR TITLE
Remove duplicate canonical links

### LINKED ISSUE #9010: Duplicate Canonical Links when using Yoast SEO plugins
## Bug Description

Tracking ticket to investigate issues with duplicate `rel=canonical` links being printed when Yoast SEO is active.

Yoast SEO issue: https://github.com/Yoast/wordpress-seo/issues/17419
Pinned post in the forums: https://wordpress.org/support/topic/known-issue-yoast-seo-compatibility-error/

## Additional Context

- Plugin Version: 1.11.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

While the original issue with duplicate canonical links has been fixed by Yoast SEO, it turns out there's room for improvement on our side as well to prevent duplicates at the AMP sanitization stage.

## Summary

This PR updates the canonical link sanitizer to remove duplicates.

## Relevant Technical Choices

Removes all but the first found canonical link

## User-facing changes

N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Install and activate Yoast SEO 17.2
2. Ensure your site is not discouraging search engines from indexing
3. Publish a story
4. Verify there is no `The tag 'link rel=canonical' appears more than once in the document.` AMP validation error

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9010

### CODE REVIEW

File: includes/AMP/Canonical_Sanitizer.php [hunk 1]
```diff
@@ -61,6 +61,16 @@ public function sanitize() {
 
 		$query = $this->dom->xpath->query( '//link[@rel="canonical"]', $this->dom->head );
 
+		// Remove any duplicate items first.
+		if ( $query instanceof DOMNodeList && $query->length > 1 ) {
```
Comment (spacedmonkey) [inline includes/AMP/Canonical_Sanitizer.php:65]: There seems to two checks for `$query instanceof DOMNodeList` now. Could we something like this.

```
$rel_canonical = null;
if ( $query instanceof DOMNodeList ) {
   $rel_canonical = $query->item( 0 );
   if ( $query->length > 1 ) {
```

Comment (swissspidy) [reply includes/AMP/Canonical_Sanitizer.php:65]: Nesting the `if` statements like this would decrease readability IMHO. And `instanceof` checks are cheap, so doesn't seem worth writing it like this.

**Review by spacedmonkey — APPROVED** [review]

**Comment by dreamofabear** [comment]
IIUC, this will also fix the Yoast issue without the mini-plugin?

**Comment by swissspidy** [comment]
yes!
