### PR TITLE
Element lock ratio for size and padding should be stored to data model

### LINKED ISSUE #1024: Element ratio lock and padding lock not persistent
## Bug Description

When I unselect an element and select it again (or reload the editor), I notice that the lock is enabled again.

## Expected Behaviour

When I disable padding lock, I expect this to be a persistent setting.
When I disable aspect ratio lock, I expect this to be a persistent setting.

## Steps to Reproduce

1. Create new text element
1. Disable padding lock
1. Add some horizontal padding, but no vertical one
1. Element updates as expected
1. (Continue editing other elements)
1. Edit text element again
1. Change horizontal padding
1. Notice how vertical padding now suddenly changes again

## Screenshots

lock-ratio-persist

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by ndev1991**
Fixes #1024 

Add aspectLockRation to element as true, and padding locked to text element as true. If multiple element selected with different ratio it will be as true.

### CODE REVIEW

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 1]
```diff
@@ -52,7 +52,9 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
     DEFAULT_PADDING
   );
 
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const [lockPaddingRatio, setLockPaddingRatio] = useState(
+    padding.horizontal === padding.vertical
+  );
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: It's better to do this in a `useEffect`. This will not rerun if the panel is re-rendered without being unmounted first. For instance, when having one text box selected and then selecting another text box with a different initial padding.

```js
  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
  useEffect(() => {
    setLockPaddingRatio(padding.horizontal === padding.vertical);
  }, [padding]);
```

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js:57]: @barklund In that case, the padding lock will update if the user input same padding on horizontal and vertical while editing without refresh or reselect

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: hmm... yes that's maybe the case of one issue. But if we use useEffect then we have another issue. Like opened padding lock and adjust horizontal and vertical same value then the padding lock will be enabled.

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: But it makes sense for me. And I think that will be the correct UX behavior.

**Comment by ndev1991** [comment]
@pbakaus @dvoytenko @miina  @barklund  When we select the element with same horizontal and vertical padding the initial padding lock is enabled. If we have different horizontal and vertical padding initially then the padding lock will be opened. One thing here is when the padding lock opened and we input the same value on horizontal and vertical then the padding lock enabled. 

Would you confirm if we need to keep padding lock open in this case?

**Comment by miina** [comment]
@ndev1991 I'd expect that the padding lock based on the padding value should be the default (e.g. on refresh), however, the user should still be able to unlock/lock the padding as they'd like, without it automatically changing the value.

Meaning that the initial padding lock state value could be set by `padding.h === padding.v`, however, if the user changes it manually, it shouldn't automatically change back.

Otherwise, the following could happen for example: if the user unlocks the padding, writes `1` to one field and starts typing `10` to the second field, then after typing the initial `1` to the second field, it already gets locked again.

**Comment by ndev1991** [comment]
> @ndev1991 I'd expect that the padding lock based on the padding value should be the default (e.g. on refresh), however, the user should still be able to unlock/lock the padding as they'd like, without it automatically changing the value.
> 
> Meaning that the initial padding lock state value could be set by `padding.h === padding.v`, however, if the user changes it manually, it shouldn't automatically change back.
> 
> Otherwise, the following could happen for example: if the user unlocks the padding, writes `1` to one field and starts typing `10` to the second field, then after typing the initial `1` to the second field, it already gets locked again.

@miina Actually it doesn't happen in that way. If the user unlocks the padding and the h is 10 and the input v 100 is fine. but if the user input the h as 10 and input 10 for v and click h again, then the padding locks

**Comment by miina** [comment]
@ndev1991 Just tested it out, it does happen this way currently:
padding

When there is `1` in one field and user starts typing `10` in the other field, then due to the first character of `10` being `1`, a match is found and the lock put on again.

In any case -- the user's choice should remain and not change back unexpectedly, the paddings being equal is relevant for the default only.

**Comment by pbakaus** [comment]
IMHO the padding lock should never lock itself on user input of values. Just because they temporarily appear to be the same (10, 10) does not mean the user indicated that she wants them locked.

**Comment by dvoytenko** [comment]
Hmm. Sounds like this was a horrible suggestion by me. But what should be the behavior? Do we want to make the lock persistent in the data model then?

**Comment by swissspidy** [comment]
That‘d be a possibility, yes.

**Comment by ndev1991** [comment]
@pbakaus @swissspidy @dvoytenko We need to add padding lock persistent in the data model. Would you confirm?

**Comment by ndev1991** [comment]
@miina @dvoytenko Added paddingLockOpen to element property so we can solve above problems.

**Comment by pbakaus** [comment]
yes, padding lock should be persistent in the data model. Thanks!

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 2]
```diff
@@ -45,14 +45,27 @@ const Space = styled.div`
...
+  selectedElements,
+  pushUpdateForObject,
+  pushUpdate,
+}) {
   const padding = useCommonObjectValue(
     selectedElements,
     'padding',
     DEFAULT_PADDING
   );
+  const isPaddingLockOpen = getCommonValue(selectedElements, 'paddingLockOpen');
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: Could we rename the stored value here? `paddingLockOpen` is a confusing name (it kind of reads like `padlock`, which has nothing to do with this). Maybe `paddingRatioLocked`, `hasFixedPaddingRatio` or something like that. Can't really come up with a good suggestion, though. @dvoytenko?

Comment (barklund) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Oh, and use the same name in the component as in the store - it's confusing if they're two different names.

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 3]
```diff
@@ -45,14 +45,27 @@ const Space = styled.div`
...
 
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const [lockPaddingRatio, setLockPaddingRatio] = useState(
+    isPaddingLockOpen === MULTIPLE_VALUE ? true : !isPaddingLockOpen
+  );
+
+  useEffect(() => {
+    setLockPaddingRatio(
+      isPaddingLockOpen === MULTIPLE_VALUE ? true : !isPaddingLockOpen
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: What's this doing? Setting it to the opposite if not multiple? Similarly above - why the `!`?

**Review by barklund — COMMENTED** [review]
Would prefer a rename, otherwise looks good.

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 2 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Used `lockPadding` and `isPaddingLock`. Let me know if you have any good suggestions for naming... 👍

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 3 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Predefined in `isPaddingLock` getting from getCommonValue

**Comment by miina** [comment]
@ndev1991 The same should also go for width/height ratio lock then, I assume.

cc @pbakaus

**Comment by ndev1991** [comment]
> @ndev1991 The same should also go for width/height ratio lock then, I assume.
> 
> cc @pbakaus

@swissspidy @dvoytenko @jauyong Can we confirm this one? If persistency width/height lock needed for data model?

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 4]
```diff
@@ -87,7 +100,10 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
         icon={<Locked />}
         uncheckedIcon={<Unlocked />}
         value={lockPaddingRatio}
-        onChange={setLockPaddingRatio}
+        onChange={() => {
+          pushUpdate({ lockPadding: !lockPaddingRatio });
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: Don't forget to update `StoryPropTypes.elements.text` in `assets/src/edit-story/types.js`

**Comment by swissspidy** [comment]
@ndev1991 If needed, width/height ratio lock can be done in a separate PR. Don't need to worry about it in this one.

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 4 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Add `lockPadding: PropTypes.bool` to StoryPropTypes.elements.text.

**Comment by ndev1991** [comment]
> @ndev1991 If needed, width/height ratio lock can be done in a separate PR. Don't need to worry about it in this one.

Got it. Now it's ready for review!

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Also set a proper default (`true`, I guess) in `elements/text/index`.

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Added default value as true and removed unnecessary condition from padding panel.

**Comment by miina** [comment]
@ndev1991 The tests seem to be failing.

>  If needed, width/height ratio lock can be done in a separate PR. Don't need to worry about it in this one

Alright, will create a follow-up issue.

**Comment by miina** [comment]
Actually, just realized that #1024 already includes the width/height ratio as well, so this PR is a partial fix.

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 5]
```diff
@@ -45,14 +45,26 @@ const Space = styled.div`
...
+    getCommonValue(selectedElements, 'lockPadding') === MULTIPLE_VALUE
+      ? true
+      : getCommonValue(selectedElements, 'lockPadding');
 
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const [lockPaddingRatio, setLockPaddingRatio] = useState(isPaddingLock);
+
+  useEffect(() => {
+    setLockPaddingRatio(isPaddingLock);
+  }, [isPaddingLock]);
```
Comment (barklund) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: I still think it's a bit weird we have three completely differently named variables here, that all talk about the same thing: `lockPadding`, `isPaddingLock`, and `lockPaddingRatio`. I actually don't even think we need the third one (local state) at all, and the two remaining can be named the same. Try this:

```js
const rawLockPadding = getCommonValue(selectedElements, 'lockPadding');
const lockPadding = rawLockPadding === MULTIPLE_VALUE ? true : rawLockPadding;
```

And then completely drop `lockPaddingRatio` and `setLockPaddingRatio` including the `useEffect` here - and also just [delete line 104](https://github.com/google/web-stories-wp/pull/1075/files#diff-276b8cf012e711e1e6d37e55f529ff49R104).

I think the value from the store will come back "fast enough" in order for the component to stay "controlled" - it's not debounced, right?

If you can't remove the local state, then e.g. rename the third variable to `lockPaddingLocal` (and `setLockPaddingLocal`), so it's clear it's the same thing, just locally in this component.

**Comment by ndev1991** [comment]
> Actually, just realized that #1024 already includes the width/height ratio as well, so this PR is a partial fix.

Correct. I missed one 🤦 Thank you Miina

**Review by barklund — COMMENTED** [review]
One final nit!

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 5 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Yes, we don't need third one. Updated!

**Comment by ndev1991** [comment]
@miina @barklund And aspect ratio added by using the same format and nits! 🍰

File: assets/src/edit-story/elements/text/index.js [hunk 6]
```diff
@@ -47,6 +47,8 @@ export const defaultAttributes = {
     vertical: 0,
     horizontal: 0,
   },
+  lockPadding: true,
+  lockAspectRatio: true,
```
Comment (miina) [inline assets/src/edit-story/elements/text/index.js]: This could probably be added to the `SHARED_DEFAULT_ATTRIBUTES` since all the elements can have that one, not just Text.

**Comment by miina** [comment]
Looks like tests are failing.

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (ndev1991) [reply assets/src/edit-story/elements/text/index.js]: Yes, I'm on it. Thank you

**Comment by ndev1991** [comment]
> Looks like tests are failing.

Regarding the tests, not sure if it's the best way. But since we don't have local state for lock state, and uses pushUpdate for update the lockratio I think we can avoid that click event to check unlock state. Instead we can use unlock element to test that. Any ideas on this @miina

**Comment by pbakaus** [comment]
Just to confirm: Yes, any lock in the design panel should be persisted in the data model (including width/height).

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (ndev1991) [reply assets/src/edit-story/elements/text/index.js]: @miina We can have lockAspectRatio on `SHARED_DEFAULT_ATTRIBUTES`, but lockPadding is supposed to be Text element only I think.

File: assets/src/edit-story/components/panels/test/textStyle.js [hunk 7]
```diff
@@ -274,8 +290,8 @@ describe('Panels/TextStyle', () => {
 
     it('should update multi padding without lock and different padding', () => {
       const { getByTestId, pushUpdateForObject } = renderTextStyle([
-        textElement,
-        textDifferentPadding,
+        unlockPaddingTextElement,
+        unlockPaddingTextDifferentPadding,
       ]);
       fireEvent.click(getByTestId('padding.lock'));
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/textStyle.js]: Does this still make sense? Does this actually click the lock and then shouldn't the test fail, because changing the lock at this point would toggle it to true, as it's inited with false?

All these tests (for both panels) really should be updated properly to correctly assert, that this new feature is:

* Correctly persisted to store
* Correctly used in calculations

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/elements/text/index.js]: Then we don't need it here also, do we?

**Review by barklund — CHANGES_REQUESTED** [review]
The tests don't really make sense anymore. Needs an overhaul to correctly test the new behavior.

**Comment by dvoytenko** [comment]
> @miina @barklund And aspect ratio added by using the same format and nits!

Did we confirm we need lock for aspect? Last time I asked @samitron7 she didn't want one. /cc @pbakaus  as well.

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 8]
```diff
@@ -79,7 +86,12 @@ function SizePositionPanel({
     const origHeight = getCommonValue(submittedSelectedElements, 'height');
     return origWidth / origHeight;
   }, [submittedSelectedElements]);
-  const [lockRatio, setLockRatio] = useState(true);
+  const rawLockAspectRatio = getCommonValue(
+    selectedElements,
+    'lockAspectRatio'
+  );
+  const lockAspectRatio =
+    rawLockAspectRatio === MULTIPLE_VALUE ? true : rawLockAspectRatio;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js:96]: This looks wrong to default `MULTIPLE` to true. At least for the purposes of calculations. We could certainly do it for the toggle itself. But then I'd rather do it where it's used.

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 9]
```diff
@@ -115,7 +127,7 @@ function SizePositionPanel({
       }
 
       // Fallback to ratio.
-      if (lockRatio) {
+      if (lockAspectRatio) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js:144]: We have `lockAspectRatio` for each element here. Do we need to pass it from above?

File: assets/src/edit-story/components/panels/sizePosition.js [hunk 10]
```diff
@@ -196,7 +208,7 @@ function SizePositionPanel({
           onChange={(value) => {
             const newHeight = value;
             let newWidth = width;
-            if (lockRatio) {
+            if (lockAspectRatio) {
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/sizePosition.js:222]: Specifically this is very problematic. But I also I think can be avoided. `pushUpdate` has a form with a per-element callback where you can read the current per-element value of `lockAspectRatio` and do the math.

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 11]
```diff
@@ -45,19 +45,23 @@ const Space = styled.div`
...
+}) {
   const padding = useCommonObjectValue(
     selectedElements,
     'padding',
     DEFAULT_PADDING
   );
-
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const rawLockPadding = getCommonValue(selectedElements, 'lockPadding');
+  const lockPadding = rawLockPadding === MULTIPLE_VALUE ? true : rawLockPadding;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: Same concerns as for the aspect ratio. We can use `common + MULTIPLE_VALUE` for the toggle itself. But for the padding itself, we should use per-element values.

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 12]
```diff
@@ -45,19 +45,23 @@ const Space = styled.div`
...
+  pushUpdate,
+}) {
   const padding = useCommonObjectValue(
     selectedElements,
     'padding',
     DEFAULT_PADDING
   );
-
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const rawLockPadding = getCommonValue(selectedElements, 'lockPadding');
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: Why shouldn't the `lockPadding` be instead `padding.locked`? It's slightly different from aspect ratio, but that's not critical.

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (dvoytenko) [reply assets/src/edit-story/elements/text/index.js]: `lockAspectRatio` doesn't make a lot of sense for text. Only width can be specified for text - height is auto-calculated.

**Review by dvoytenko — CHANGES_REQUESTED** [review]

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/elements/text/index.js]: @dvoytenko well, we currently allow users to enter width and height directly and font size will be adjusted accordingly. As long as we do that, locking aspect ratio makes sense, no?

File: assets/src/edit-story/components/panels/test/textStyle.js (hunk 7 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/test/textStyle.js]: I think we don't need `pushUpdate` function test for this panel test like other cases. `pushUpdate` function test already added on `designPanel` so I added test cases for lock ratio button called with correct value.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 8 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/sizePosition.js:96]: @dvoytenko Just for confirm. If we prefer to have separate calculation based on each element lock ratio, what would be the toggle status? Does it need to have disabled status?

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 10 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/sizePosition.js:222]: And also currently we're using common `origRatio` for the common values of width and height of selected elements. Do we need to go for individual elements?

**Comment by ndev1991** [comment]
@dvoytenko @pbakaus @swissspidy  Here is the current workflow of padding lock and aspect ratio.
Default element has lock aspect ratio status. Default text has lock padding status.
When there are multiple elements selected with different aspect ratio and padding ratio, assume it as true status and make the same changes for each size and padding calculation.

If we want to go for each element, lock toggle should be disabled status?
And also for sizePosition calculation, orgRatio is based on common values. Do we need to have separate calculation for each elements? /cc @samitron7

File: assets/src/edit-story/elements/text/index.js (hunk 6 above)
Comment (dvoytenko) [reply assets/src/edit-story/elements/text/index.js]: Yeah. Let's put it for now. It will be too much to address all text nuances for this.

**Comment by dvoytenko** [comment]
> @pbakaus @dvoytenko @miina @barklund When we select the element with same horizontal and vertical padding the initial padding lock is enabled. If we have different horizontal and vertical padding initially then the padding lock will be opened. One thing here is when the padding lock opened and we input the same value on horizontal and vertical then the padding lock enabled.

This is a good point. No matter how we approach this, from the data model point of view: it makes no sense to allow "padding lock" if H and V values are different - otherwise we won't be able to change them. And probably we just need to ensure there're no inconsistencies and it would be enough.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 10 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/panels/sizePosition.js:222]: The "simple" way to look at it is this: as much as possible we want to only change what's actually updated by the user directly. But if we decide to change more values, we need to make sure that they are consistent. E.g. for multiple selection, one with locked ratio and one with not locked ratio, and when a width is changed, we should either:
 1. Use per-element ratio lock. I.e. one element will have its height updated and one will not.
 2. Use common ratio lock. E.g. we'd update height for both elements, but we will also set the lock ratio to true for both elements.

TBH, I'm not yet super clear which of these is better. The main goal is to ensure the values are consistent and that'd already be good. Perhaps it'd be easier for us to start with the second option and see if that creates any UX weirdness?

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 8 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/sizePosition.js:96]: Based on discussion, go with second option and lock ratio should be true when multiple values.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 9 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/sizePosition.js:144]: Yes, we're using common lock ratio.

File: assets/src/edit-story/components/panels/sizePosition.js (hunk 10 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/sizePosition.js:222]: Based on second option, we need this and just need to pass the `lockAspectRatio`

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 11 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Same here!

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 12 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: `lockPadding` and removed instead used `locked` inside `padding` and update the tests based on that. And update the `locked` for multiple elements when they don't have common lock ratio.

**Comment by ndev1991** [comment]
@dvoytenko @barklund Following the second option, it uses the common lock ratio for padding and size. When there are multiple values, assume it as locked and update the lock ratio for element also.

**Comment by barklund** [comment]
@dvoytenko should this have a migration? If width/height are still proportional to originalWidth/originalHeight, we migrate to locked? And similarly, if paddings are still equal, we migrate to locked? Or should we just assume all old stories now to be unlocked, and it's not really a big issue?

**Comment by ndev1991** [comment]
> @dvoytenko should this have a migration? If width/height are still proportional to originalWidth/originalHeight, we migrate to locked? And similarly, if paddings are still equal, we migrate to locked? Or should we just assume all old stories now to be unlocked, and it's not really a big issue?

We can have basic thing on it. Like `rawLockRatio === undefined`, we can assume to be true?

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 13]
```diff
@@ -52,12 +52,12 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
     DEFAULT_PADDING
   );
 
-  const [lockPaddingRatio, setLockPaddingRatio] = useState(true);
+  const lockPadding = padding.locked === MULTIPLE_VALUE ? true : padding.locked;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: In this case I actually think we need the default of `false`. Otherwise, one could never even see that one of the paddings is different. For consistency I'm wondering if we need to make aspect ration false by default.

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Very close. But some questions. I'll also loop in Paul on this.

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 13 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: hmm... if we want single input in case of lock ratio, it makes sense to make ti false when there are multiple values available. But I think default ratio it true by default? @pbakaus

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: padding common lock ratio updated to false when multiple lock ratio combined. And added comment on padding and size panel.

File: assets/src/edit-story/components/panels/textStyle/padding.js [hunk 14]
```diff
@@ -66,10 +68,12 @@ function PaddingControls({ selectedElements, pushUpdateForObject }) {
           horizontal: commonPadding,
           vertical: commonPadding,
         };
+
+        if (padding.locked === MULTIPLE_VALUE) update.locked = lockPadding;
```
Comment (dvoytenko) [inline assets/src/edit-story/components/panels/textStyle/padding.js]: Nit: use `{}`. makes a lot easier to read.

/cc @swissspidy I thought we had a lint for this?

Comment (dvoytenko) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Actually, I believe this line is not quite correct. I think, once the padding is edited, we just want to set it two lines above to always be `true`. E.g. 

```
update = {
  horizontaol: commonPadding,
 ...
  locked: true
}
```

**Review by dvoytenko — CHANGES_REQUESTED** [review]
Just one update requested.

File: assets/src/edit-story/components/panels/textStyle/padding.js (hunk 14 above)
Comment (dvoytenko) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Also, I think this particular test is missing.

Comment (ndev1991) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: Removed and added locked to above. And add covering tests for different lock ratio elements combination, the lock ratio should be false. And in this case we will have locked sets for only true cases 😄

Comment (swissspidy) [reply assets/src/edit-story/components/panels/textStyle/padding.js]: @dvoytenko we did have a lint for this, but apparently `eslint-config-prettier` disables it and requires it to be set explicitly due to potential formatting conflicts. PR imminent...

**Review by dvoytenko — APPROVED** [review]

File: assets/src/edit-story/components/panels/test/sizePosition.js [hunk 15]
```diff
@@ -190,28 +200,53 @@ describe('Panels/SizePosition', () => {
...
+        unlockAspectRatioElement,
+      ]);
       const input = getByTestId('height');
       fireEvent.change(input, { target: { value: '' } });
       expect(pushUpdate).toHaveBeenCalledWith({ height: '', width: 100 });
     });
+
+    it('should update lock ratio to false for element', () => {
+      const { getByTestId, pushUpdate } = renderSizePosition([defaultImage]);
+      fireEvent.click(getByTestId('lockRatio'));
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/sizePosition.js]: Doesn't this toggle have a proper label? Use labels or other actually visible texts whenever possible - only use test-ids if nothing else is an option (and even then, rather add a label than using test ids).

File: assets/src/edit-story/components/panels/test/sizePosition.js [hunk 16]
```diff
@@ -315,5 +350,32 @@ describe('Panels/SizePosition', () => {
...
+    });
+
+    it('should update lock ratio to true for unlock aspect ratio elements', () => {
+      const { getByTestId, pushUpdate } = renderSizePosition([
+        unlockImageWithSameSize,
+        unlockImage,
+      ]);
+      fireEvent.click(getByTestId('lockRatio'));
+      expect(pushUpdate).toHaveBeenCalledWith({ lockAspectRatio: true });
+    });
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/sizePosition.js]: Great tests, but the descriptions are a bit complex. They could be named much simpler (don't refer to your variables, just refer to what actually happens):

 * _should disable aspect ratio lock if all elements had lock enabled._
 * _should disable aspect ratio lock if elements had different settings for aspect ratio lock._
 * _should enable aspect ratio lock only if all elements had lock disabled._

File: assets/src/edit-story/components/panels/test/textStyle.js [hunk 17]
```diff
@@ -273,11 +288,24 @@ describe('Panels/TextStyle', () => {
...
+      const input = getByTestId('padding.horizontal');
+      fireEvent.change(input, { target: { value: '11' } });
+      expect(pushUpdateForObject).toHaveBeenCalledWith(
+        'padding',
+        { horizontal: 11 },
+        DEFAULT_PADDING
+      );
+    });
+
+    it('should default padding lock ration should be false when multiple elements with different lock ratio and update only horizontal', () => {
```
Comment (barklund) [inline assets/src/edit-story/components/panels/test/textStyle.js]: Again, these descriptions are bit tricky (even with some spelling errors). Test descriptions are super important, because when they fail, someone else will have to understand what the purpose was 5 months from now!

* _should update only vertical/horizontal padding if elements had different padding lock settings_

**Review by barklund — COMMENTED** [review]
I just have a few comments about tests, otherwise things look really good. Please think about good simple test descriptions, that don't go into unnecessary technical details and try to use labels or visual texts rather than test ids whenever possible.

File: assets/src/edit-story/components/panels/test/sizePosition.js (hunk 16 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/test/sizePosition.js:379]: I think enabled or disabled are not correct options. It sounds like that ratio lock disabled to use?

File: assets/src/edit-story/components/panels/test/sizePosition.js (hunk 15 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/test/sizePosition.js]: Set the `aria-label` and used `getByLabelText` for aspect ratio lock and padding ratio lock.

File: assets/src/edit-story/components/panels/test/sizePosition.js (hunk 16 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/test/sizePosition.js]: Updated. But disabled sounds like the ratio lock toggle disabled to use. Maybe use turn on or off instead?

File: assets/src/edit-story/components/panels/test/textStyle.js (hunk 17 above)
Comment (ndev1991) [reply assets/src/edit-story/components/panels/test/textStyle.js]: Got it. Fixed! 👍

**Review by barklund — APPROVED** [review]
