### PR TITLE
Make editor ErrorBoundary more useful

### LINKED ISSUE #10374: Trying to report an editor crash using the Report Issue button returns an error.
## Bug Description

During the bug bash I crashed the editor, and attempted to use the "Report Error" button, but unfortunately, this failed, with the following Github error shown to me:

Screen Shot 2022-01-25 at 12 26 00 PM

<details>
<summary>Details</summary>

URL: https://github.com/googleforcreators/web-stories-wp/issues/new?labels=Type%3A+Bug&template=bug_report.md&title=TypeError:%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27x%27)&body=TypeError%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27x%27)%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20Popup%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3043236)%0A%20%20%20%20at%20PlayPauseButton.j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A56548)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20PlayPauseButton%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A55099)%0A%20%20%20%20at%20VideoControls%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A66982)%0A%20%20%20%20at%20WithLink%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A143%3A33563)%0A%20%20%20%20at%20FrameElement%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A143%3A35167)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20PageArea%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A83%3A11739)%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20section%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20Layer%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A83%3A8435)%0A%20%20%20%20at%20FramesLayer%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A143%3A46022)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20WithOverlay%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A143%3A3719)%0A%20%20%20%20at%20SelectionCanvas%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A169%3A10627)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20CanvasElementDropzone%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A169%3A13495)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20UploadDropTarget%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A87%3A6952)%0A%20%20%20%20at%20CanvasUploadDropTarget%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A169%3A12978)%0A%20%20%20%20at%20section%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20ce%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A29724)%0A%20%20%20%20at%20CanvasLayout%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A169%3A18804)%0A%20%20%20%20at%20Canvas%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A169%3A20673)%0A%20%20%20%20at%20O%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A5%3A26674)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20RichTextProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A199%3A8307)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20VideoTrimProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A199%3A12692)%0A%20%20%20%20at%20Workspace%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A199%3A14132)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20RightClickMenuProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A142)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20UnitsProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A272%3A63925)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20CanvasProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3020213)%0A%20%20%20%20at%20section%0A%20%20%20%20at%20j%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A34642)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20WithOverlay%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A143%3A3719)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20HighlightsProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A185%3A19779)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20ChecklistCheckpointProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A69%3A1436)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20LayoutProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A246%3A90126)%0A%20%20%20%20at%20SR%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A13125)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20MetaBoxesProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A264%3A3143)%0A%20%20%20%20at%20Layout%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20PageDataUrlProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A5%3A37219)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20HelpCenterProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3073348)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20DropTargetsProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3002711)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20TransformProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A226%3A35580)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20MediaProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A226%3A26006)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20FontProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3028550)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20CurrentUserProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3025849)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20TaxonomyProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A5%3A28040)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20StoryTriggersProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A99898)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20StoryProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A100692)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20SnackbarProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A262%3A30567)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20HistoryProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A2693686)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20Media3pApiProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A246%3A10954)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20APIProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A123808)%0A%20%20%20%20at%20https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A236%3A3033431%0A%20%20%20%20at%20ConfigProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A201%3A117414)%0A%20%20%20%20at%20O%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A5%3A26674)%0A%20%20%20%20at%20Fe%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A32705)%0A%20%20%20%20at%20ce%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A1%3A29724)%0A%20%20%20%20at%20FlagsProvider%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A226%3A31000)%0A%20%20%20%20at%20StoryEditor%20(https%3A%2F%2Fstories-new-wordpress-amp.pantheonsite.io%2Fwp-content%2Fplugins%2Fweb-stories%2Fassets%2Fjs%2Fwp-story-editor.js%3Fver%3Db02e34b5a6edbd4b2342b48df220248b%3A5%3A55854)
</details>

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

This is really a long overdue change

If the stack trace is too long, the GitHub URL  will be too long and it won't work.

Also, for support requests it's super important to have the error message visible so that they can just copy it and send it to us, or take a screenshot of it.

## Summary

Changes the report button to point to the forums

Adds a textarea with the error message

## User-facing changes

Screenshot 2022-01-25 at 18 50 31

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Trigger an error somewhere to make the error boundary appear

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10374

### CODE REVIEW

File: packages/story-editor/src/components/errorBoundary/errorActions.js [hunk 1]
```diff
@@ -47,8 +52,9 @@ const Wrapper = styled.div`
 `;
 
 function ErrorActions({ error, errorInfo }) {
-  const body = encodeURIComponent(`${error}${errorInfo.componentStack}`);
-  const reportUrl = `https://github.com/googleforcreators/web-stories-wp/issues/new?labels=Type%3A+Bug&template=bug_report.md&title=${error}&body=${body}`;
+  const textAreaContent = `${error}\n${errorInfo.componentStack}`;
+  const reportUrl =
+    'https://wordpress.org/support/plugin/web-stories/#new-topic-0';
```
Comment (miina) [inline packages/story-editor/src/components/errorBoundary/errorActions.js:57]: Should we update the text as well to specify to copy the error / take a screenshot of it for the support topic?

Comment (swissspidy) [reply packages/story-editor/src/components/errorBoundary/errorActions.js:57]: Was not sure about it; felt like it wasn't necessary because users usually provide any error message or take a screenshot anyway.

Comment (miina) [reply packages/story-editor/src/components/errorBoundary/errorActions.js:57]: > because users usually provide any error message or take a screenshot anyway.

For some reason I've generally had the opposite experience -- the users just say they did X and then something crashed 😛 
But perhaps it's different here if the error is visible like this and not in console only.

**Review by miina — APPROVED** [review]

File: packages/story-editor/src/components/errorBoundary/errorActions.js (hunk 1 above)
Comment (swissspidy) [reply packages/story-editor/src/components/errorBoundary/errorActions.js:57]: We'll see how it goes, we can always refine it. I think this is a great improvement already.
