### PR TITLE
Bug: Checklist intercepting pointer events when closed

### LINKED ISSUE #8846: Checklist is covering the thumbnails area
## Bug Description
When the "Video Optimization" setting is disabled, a portion of the checklist is covering the thumbnail's left arrow and first thumbnail making them unclickable.

## Expected Behaviour

All elements in the thumbnails area should be usable at all times.

## Steps to Reproduce

https://user-images.githubusercontent.com/21036224/131355543-9f7e054c-47a6-481c-a2b2-97e7e874813c.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Some pointer events around the carousel thumbnails were getting blocked by the checklist.

## Summary
This Fixes the pointer events from getting blocked when the checklist is closed.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
NA

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8846

### CODE REVIEW

**Review by BrittanyIRL — APPROVED** [review]
This test is failing now since it's not rendering always - otherwise looks good, thanks for fixing this so quickly. 

```
 VideoOptimizationCheckbox › should render the checkbox if auto video optimization is disabled and the user is able to upload media

 TestingLibraryElementError: Unable to find an accessible element with the role "checkbox"
```

File: packages/story-editor/src/components/checklist/videoOptimizationCheckbox/index.js [hunk 1]
```diff
@@ -76,7 +78,7 @@ function VideoOptimizationCheckbox() {
   const checked = currentUser?.meta?.web_stories_media_optimization;
   const showCheckbox = !checked && hasUploadMediaAction;
 
-  return showCheckbox ? (
+  return showCheckbox && isChecklistMounted ? (
```
Comment (samwhale) [inline packages/story-editor/src/components/checklist/videoOptimizationCheckbox/index.js:81]: 💭 `showCheckbox` is defined a little higher ups o we could combine those checks (if we wanted to make this one variable). Not really a big deal.

**Review by samwhale — APPROVED** [review]
Nice! Once that test is fixed it should be gucci
