### PR TITLE
Telemetry: Improve error tracking

### LINKED ISSUE #5714: Improve JS error tracking
### Background

After release of v1.2, there's been a coincident spike in "error" events in GA. 

Screen Shot 2020-12-16 at 2 29 50 PM

However, it's unclear how to fix these errors given currently available "error" event data in GA. We also don't know with certainty which plugin versions are causing the errors.

### Goals

Let's improve our GA usage for errors so we can easily:
1. Monitor and notify when error spikes occur
2. Debug and fix top errors (i.e. error names and stack traces)
3. Segment errors by plugin version/browser/etc.

### Notes 
- We track JS runtime errors with a GA event where name/action == "error"
  - Looks like this happens in `src/components/errorBoundary/index.js` and `src/tracking/trackEvent.js`
- The error name and stack trace (`error_info`) don't appear to be visible in GA dashboard 
- We should probably use GA's [exception tracking API](https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions) for this instead

/cc @swissspidy

### PR DESCRIPTION
**Pull request by zidianlyu**
## Summary

Implement Google Analytics to show better error logging.

## Relevant Technical Choices

- Setting up Google Analytics Customized Dashboard

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

---

Fixes #5714

### CODE REVIEW

**Comment by zidianlyu** [comment]
The customized dashboard looks like this:

104217695-90b57680-53f0-11eb-80ec-4f9ca77653d0

File: assets/src/edit-story/components/errorBoundary/index.js [hunk 1]
```diff
@@ -38,10 +38,7 @@ class ErrorBoundary extends Component {
 
   componentDidCatch(error, errorInfo) {
     this.setState({ error, errorInfo });
-    trackEvent('error', 'editor', '', '', {
-      error,
-      error_info: errorInfo,
-    });
+    trackError('error', 'catch error', errorInfo);
```
Comment (swissspidy) [inline assets/src/edit-story/components/errorBoundary/index.js]:
```suggestion
    trackError(error, errorInfo);
```

File: assets/src/tracking/trackError.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+ *
+ * @param {string} eventCategory The event category (e.g. 'editor'). GA defaults this to 'engagement'.
+ * @param {string} [description] The extra description.
+ * @param {Object} [errorInfo] The error info objecta.
+ * @param {boolean} [fatal] Report whether there is a fatal error.
+ * @param {Object<*>} [additionalData] Additional event data to send.
+ * @return {Promise<void>} Promise that always resolves.
+ */
+//eslint-disable-next-line require-await
+async function trackError(
```
Comment (swissspidy) [inline assets/src/tracking/trackError.js:40]: Let's add some tests for this method. At the very least want to ensure that `description` is formatted` correctly.

File: assets/src/tracking/trackError.js [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+import track from './track';
+
+/**
+ * Send an Analytics tracking error.
+ *
+ * @see https://developers.google.com/analytics/devguides/collection/ga4/exceptions
+ *
+ * @param {string} eventCategory The event category (e.g. 'editor'). GA defaults this to 'engagement'.
+ * @param {string} [description] The extra description.
+ * @param {Object} [errorInfo] The error info objecta.
```
Comment (swissspidy) [inline assets/src/tracking/trackError.js]:
```suggestion
 * @param {ErrorInfo} [errorInfo] The React error info object.
```

File: assets/src/tracking/trackError.js [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * Internal dependencies
+ */
+import { config } from './shared';
+import isTrackingEnabled from './isTrackingEnabled';
+import track from './track';
+
```
Comment (swissspidy) [inline assets/src/tracking/trackError.js:23]:
```suggestion

	/** @typedef {import('react').ErrorInfo} ErrorInfo */

```

Comment (zidianlyu) [reply assets/src/tracking/trackError.js:23]: Added into the documentation.

File: assets/src/tracking/trackError.js (hunk 3 above)
Comment (zidianlyu) [reply assets/src/tracking/trackError.js]: Updated.

File: assets/src/edit-story/components/errorBoundary/index.js (hunk 1 above)
Comment (zidianlyu) [reply assets/src/edit-story/components/errorBoundary/index.js]: I am a bit confused here, will `error` be the eventCategory? And also, do we allow customized description here?

Comment (swissspidy) [reply assets/src/edit-story/components/errorBoundary/index.js]: Ah sorry, I think I jumped the gun here.

The `eventCategory` should be `editor.

So with the current function signature:

```suggestion
    trackEvent('editor', error, errorInfo, true, );
```

Comment (zidianlyu) [reply assets/src/edit-story/components/errorBoundary/index.js]: As I understand `error` is the type Error, but I think we might need a eventCategory here.

Comment (zidianlyu) [reply assets/src/edit-story/components/errorBoundary/index.js]: updated.

File: assets/src/tracking/trackError.js (hunk 2 above)
Comment (zidianlyu) [reply assets/src/tracking/trackError.js:40]: Added test and ensure the description will be a string.

File: composer.lock [hunk 5]
```diff
@@ -8,16 +8,16 @@
     "packages": [
         {
             "name": "ampproject/amp-wp",
-            "version": "2.0.8",
+            "version": "2.0.9",
```
Comment (swissspidy) [inline composer.lock]: Please undo all changes to this file

File: assets/src/tracking/trackError.js [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+    return Promise.resolve();
+  }
+  const description = errorInfo
+    ? `${error.toString()}\n\n${errorInfo.componentName}\n${
+        errorInfo.componentStack
+      }`
+    : error.toString();
+  const eventData = {
+    send_to: config.trackingId,
+    event_category: 'error',
```
Comment (swissspidy) [inline assets/src/tracking/trackError.js]: That doesn't make sense I think? We already know it's an error because we track it as an exception below.

The event category should be something like "editor" or "dashboard" and be passed as an rgument to the function.

File: assets/src/tracking/trackError.js [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+  additionalData = {}
+) {
+  if (!isTrackingEnabled()) {
+    return Promise.resolve();
+  }
+  const description = errorInfo
+    ? `${error.toString()}\n\n${errorInfo.componentName}\n${
+        errorInfo.componentStack
+      }`
+    : error.toString();
```
Comment (swissspidy) [inline assets/src/tracking/trackError.js]: Should use `error.message` instead of `error.toString()`?

`error.toString()` will always add a "Error: "` prefix, which is a bit pointless and redundant for this.

**Comment by swissspidy** [comment]
**First:**
Some other places where we also could catch & track errors:

https://github.com/google/web-stories-wp/blob/321bc424321b6550c91c24318b73eb47ace903a0/assets/src/edit-story/utils/getMediaBaseColor.js#L68

https://github.com/google/web-stories-wp/blob/321bc424321b6550c91c24318b73eb47ace903a0/assets/src/edit-story/app/media/utils/useUploadVideoFrame.js#L94

These two are some good quick wins.

**Second:**

We need to change the function signature of `trackError()`.

1. `errorCategory` needs to be a function parameter, same as for all other tracking functions
1. `errorInfo` is only needed in React error boundaries, which we  only have 1 or 2 right now. So it's not used a lot.

Suggestion:

```js
async function trackError(
  eventCategory, // string
  error,  // Error object or string
  fatal = false, // bool
 additionalData // Object
)
```

Example 1, JS error:

```js
try {
  // ...
} catch(err) {
  trackError('editor', err);
}
```

```js
try {
  // ...
} catch(err) {
  trackError('video poster generation', err);
}
```

Example 2: React error boundary:

```js
try {
  // ...
} catch(err) {
  const msg = errorInfo
    ? `${err.message}\n\n${errorInfo.componentName}\n${
        errorInfo.componentStack
      }`
    : err;
  trackError('editor', msg, true);
}
```

**Third**

Per #5714 we want to have error tracking in a few more places:

* All console errors (`window.addEventListener('error', function(event) { ... })`)
* All unhandled promise rejections (`window.addEventListener('unhandledrejection', function(event) { ... })`)

Needs some logic to avoid duplicates, not sure if [the reasons](https://github.com/ampproject/amphtml/pull/10634#pullrequestreview-52428536) AMP uses this sentinel suffix still apply / apply to us.

**Note** This is something we would want to have in all our React apps (dashboard, editor, plugin activation, blocks), and perhaps requires a bigger effort that's best explored in a separate PR.

File: composer.lock (hunk 5 above)
Comment (spacedmonkey) [reply composer.lock]: ☝️

File: includes/Tracking.php [hunk 8]
```diff
@@ -104,6 +104,7 @@ public function get_settings() {
 		return [
 			'trackingAllowed' => $this->is_active(),
 			'trackingId'      => self::TRACKING_ID,
+			'appVersion'      => WEBSTORIES_VERSION,
```
Comment (spacedmonkey) [inline includes/Tracking.php:93]: Is the name of the key a little confusing. Is plugin version or webstories version.

**Comment by spacedmonkey** [comment]
Seems like a valid change to me.

File: includes/Tracking.php (hunk 8 above)
Comment (swissspidy) [reply includes/Tracking.php:93]: `app_version` is what GA uses, so I went with `appVersion` for consistency. Given the context I think it should be clear enough that this is the Web Stories plugin vesion.

File: assets/src/tracking/trackError.js (hunk 6 above)
Comment (zidianlyu) [reply assets/src/tracking/trackError.js]: Okay, thanks for clarifying, I think in the previous comment, you suggested only keep `error` and `errorInfo` from the passing arguments.

File: assets/src/tracking/trackError.js (hunk 7 above)
Comment (zidianlyu) [reply assets/src/tracking/trackError.js]: Got it! And right, this way will be cleaner.

File: composer.lock (hunk 5 above)
Comment (zidianlyu) [reply composer.lock]: Got it

File: includes/Tracking.php (hunk 8 above)
Comment (zidianlyu) [reply includes/Tracking.php:93]: So I will stay with `appVersion` for now

**Comment by spacedmonkey** [comment]
Some more places to add error tracking 

https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js#L102-L110

https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js#L144-L158


https://github.com/google/web-stories-wp/blob/34d6e7f2e49c32b6ca9a8759d6e65952d899f430/assets/src/edit-story/utils/localStore.js#L28-L30

https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/components/library/panes/media/local/deleteDialog.js#L60-L64

https://github.com/google/web-stories-wp/blob/9aa9766509d8680421e2120b67056f2faed05943/assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js#L169-L173

All places that use the following should be replaced 
```
trackEvent('error', 'editor', '', '', {
```

**Comment by swissspidy** [comment]
> Some more places to add error tracking
> 
> https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js#L102-L110
> 
> https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/app/media/useUploadMedia/useUploadMedia.js#L144-L158
> 
> https://github.com/google/web-stories-wp/blob/34d6e7f2e49c32b6ca9a8759d6e65952d899f430/assets/src/edit-story/utils/localStore.js#L28-L30
> 
> https://github.com/google/web-stories-wp/blob/9a31a26e740265b8dc27ca89448df4f0ad3b433c/assets/src/edit-story/components/library/panes/media/local/deleteDialog.js#L60-L64
> 
> https://github.com/google/web-stories-wp/blob/9aa9766509d8680421e2120b67056f2faed05943/assets/src/edit-story/components/library/panes/media/local/mediaEditDialog.js#L169-L173
> 
> All places that use the following should be replaced
> 
> ```
> trackEvent('error', 'editor', '', '', {
> ```

I am not sure about those actually. There doesn't seem to be much value in sending analytics exception events when a user uploads invalid/too large files, for instance. Need to be careful not to just place tracking all over the place just because we can.

Let's take this one step at a time.

**Comment by swissspidy** [comment]
Related: #5936

**Comment by swissspidy** [comment]
ugh, no idea how I ended up with this broken commit history

**Review by swissspidy — APPROVED** [review]
