### PR TITLE
AMP: De-duplicate inline styles

### LINKED ISSUE #6783: Excessive CSS output stripped by AMP sanitization
## Bug Description

Support topic: https://wordpress.org/support/topic/formatting-distorted-after-publishing/

Related: #5226

It appears that creating larger stories with tons of animations will result in lots of CSS. Enough to go beyond the 75k CSS limit in AMP and causing the built-in sanitizer to remove any excessive CSS before output to ensure AMP validation.

This can cause stories to appear broken as elements might not be positioned as expected.

## Expected Behaviour

No broken stories

No AMP invalidation

## Steps to Reproduce

Not sure, but seems caused by large stories with lots of animations.

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

While the AMP plugin's CSS sanitization helps a lot to de-duplicate inline styles, it also creates tons of selectors starting with `:root:not(#_):not(#_):not(#_):not(#_):not(#_)` and similar to ensure specificity when dealing with plugins/themes using `!important` in CSS.

See #6783 for detailed analysis.

## Summary

This PR changes the CSS sanitization to drastically increase the amount of CSS on a page.

When using a pre-existing template, CSS output is reduced by at least 1/3rd!

See https://github.com/google/web-stories-wp/issues/6783#issuecomment-846619292

## Relevant Technical Choices

This new sanitizer addition bypasses the AMP plugin's style sanitizer specificity handling which is not needed in Web Stories. All inline styles are added to a `<style>` tag before the AMP library gets to parsing the CSS, avoiding these long selectors.

## To-do

- ~Tests~

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6783

### CODE REVIEW

File: tests/phpunit/tests/AMP/Story_Sanitizer.php [hunk 1]
```diff
@@ -267,4 +267,22 @@ public function test_transform_a_tags_data_attributes() {
...
+		$args = [
+			'publisher_logo'             => '',
+			'publisher'                  => '',
+			'publisher_logo_placeholder' => '',
+			'poster_images'              => [],
+		];
+
+		$actual = $this->sanitize_and_get( $source, $args );
+
+		$this->assertContains( '<style>._a7988c6{color: blue;}._91f054f{color: blue; background: white;}._f479d19{color: red;}</style>', $actual );
```
Comment (westonruter) [inline tests/phpunit/tests/AMP/Story_Sanitizer.php:286]:
```suggestion
		$this->assertContains( '<style>._a7988c6{color: blue;}._91f054f{color: blue; background: white;}._f479d19{color: red;}</style>', $actual );
		$this->assertNotContains( 'style="', $actual );
```

File: includes/AMP/Traits/Sanitization_Utils.php [hunk 2]
```diff
@@ -198,4 +199,69 @@ private function add_poster_images( &$document, $poster_images ) {
 			$document->html->removeAttribute( 'amp' );
 		}
 	}
+
+	/**
+	 * De-duplicate inline styles in the story.
+	 *
+	 * Greatly reduce the amount of `style[amp-custom]` CSS for stories by de-duplicating inline styles
+	 * and moving to simple class selector style rules,avoiding the specificity hac
```
Comment (westonruter) [inline includes/AMP/Traits/Sanitization_Utils.php]:
```suggestion
	 * and moving to simple class selector style rules, avoiding the specificity hack
```

**Review by westonruter — APPROVED** [review]

**Review by spacedmonkey — APPROVED** [review]
