### PR TITLE
Avoid duplicate poster generation

### LINKED ISSUE #5541: Code Quality: Issues around poster generation
## Task Description

**`uploadVideoPoster`: async vs. not**

`uploadVideoPoster` is **not** an async callback:

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/app/media/local/useContextValueProvider.js#L139-L155

Yet, it is sometimes wrongly awaited:

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/app/media/local/useContextValueProvider.js#L166

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/components/canvas/useUploadWithPreview.js#L85

**Unnecessary props to `useUploadVideoFrame`**

It takes only one prop:

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/app/media/utils/useUploadVideoFrame.js#L30

Yet it is called with many more:

https://github.com/google/web-stories-wp/blob/c170896a31487c8c55a234f3f770baf5b5d076f6/assets/src/edit-story/app/media/local/useContextValueProvider.js#L109-L115

If you remove those, there will actually be some unused variables. This might be a flaw in the logic of said code.

### LINKED ISSUE #5675: Missing poster on inserting NEW video from Media Library
## Bug Description
If we upload a video, close the upload modal and insert the new video from. the Media Library, the video poster will not be able to show up.

## Expected Behaviour

The video poster should be able to show up as expected.

## Steps to Reproduce
1. Upload a video, then close the uploader modal.
2. Click on blue "Upload" button > "Media Library" tab in popup > select a video > "Insert into page"

## Screenshots
Screen Shot 2020-12-14 at 12 16 30 PM

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Refreshes media modal to ensure it has all the data about poster images etc.

## Relevant Technical Choices

* Refreshes media modal to ensure it has all the data about poster images etc.  
  See https://github.com/google/web-stories-wp/issues/5675#issuecomment-745591608 for explainer
* When inserting a video from the WordPress media modal, do not try to generate a poster image if the video already has a poster.

## User-facing changes

* Media modal refreshes when there's newly uploaded media

## Testing Instructions

1. In the WordPress media library (Media -> Add New), upload a video
2. Open dev tools and monitor network tab
2. Create a new story
3. See that video is available in media pane.
4. Optional: Verify that in the network tab you see some XHR requests to `web-stories/v1/media/..` -> a poster is being generated!
5. Click on "Upload" to open media dialog, switch to "Gallery"
6. See that the new video now has a poster, and both the video and the poster are in the list of media items that can be selected (so video + poster = 2 items)
7. Create a new story
8. Click on "Upload", switch to "Gallery"
9. Insert the "video" into page
10. Optional: See that there are _no_ new XHR requests to `web-stories/v1/media/..` -> no extra poster is being generated
11. Click on "Upload" again to open media dialog, switch to "Gallery"
12. See that the video still has a poster, and _no new poster_ has been added. So you still see the video + the poster in the list of selectable items, but not another new one (so video + poster = 2 items)

**Note:** In the WordPress media modal and the WordPress media library, you will see both the video and its poster image, whereas in the story editor the poster is not visible; only the video. This is currently expected.

---

Fixes #5675
Fixes #5541

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Can you explain this change? Wouldn't this result in many poster image be generated and uploaded. [This](https://storage.googleapis.com/percy-images/8d22df8a53e3f647fb502b4f5bb907f2d13b01daa6242e394dd0e940c82006b8) dialog from percy proves that multiple poster images have been generated.

**Comment by swissspidy** [comment]
> Can you explain this change? Wouldn't this result in many poster image be generated and uploaded. [This](https://storage.googleapis.com/percy-images/8d22df8a53e3f647fb502b4f5bb907f2d13b01daa6242e394dd0e940c82006b8) dialog from percy proves that multiple poster images have been generated.

The explanation is linked in the description. Poster generation logic is not touched by this PR. It solely refreshes the media modal, which just so happens to also improve the poster generation flow in one area. If anything, that Percy screenshot shows that poster generation is flawed in other areas as well.

**Review by zidianlyu — APPROVED** [review]

**Comment by spacedmonkey** [comment]
>The explanation is linked in the description.  

Yes, I read that thank you. I meant, can you explain why this change fixes the problem? One line doesn't really explain the code change. I don't for example, understand why changing functions from async to sync helps this problem. 

I honestly believe the recent changes to the poster generations have not made things better, they have made them worse. As the percy screenshots prove, multiple posters are being generated, which now posters are visual to users in the media library is an even bigger problem. I don't want to fill users media libraries with poster images. Not to mention how wasteful it is store these unused images.

File: assets/src/edit-story/app/media/local/useContextValueProvider.js [hunk 1]
```diff
@@ -156,17 +144,14 @@ export default function useContextValueProvider(reducerState, reducerActions) {
...
-          allowedVideoMimeTypes.includes(mimeType) &&
-          !local &&
-          !posterId &&
-          id
-        ) {
-          await uploadVideoPoster(id, src);
-        }
-      };
-      process();
+      if (
```
Comment (spacedmonkey) [inline assets/src/edit-story/app/media/local/useContextValueProvider.js:148]: Why does change this from async to sync help the issue?

Comment (swissspidy) [reply assets/src/edit-story/app/media/local/useContextValueProvider.js:148]: This part does not fix the issue itself, but fixes a code quality issue outlined in #5541

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ export default function useMediaPicker({
   useEffect(() => {
     try {
       // Work around that forces default tab as upload tab.
-      wp.media.controller.Library.prototype.defaults.contentUserSetting = false;
+      global.wp.media.controller.Library.prototype.defaults.contentUserSetting = false;
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js:65]: Can you explain why changing this to global helps here or is this a refactor?

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 3]
```diff
@@ -91,15 +91,22 @@ export default function useMediaPicker({
     });
 
     // When an image is selected, run a callback.
-    fileFrame.on('select', () => {
+    fileFrame?.once('select', () => {
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Again, why does once and conditionals help here?

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js [hunk 4]
```diff
@@ -91,15 +91,22 @@ export default function useMediaPicker({
...
 
     if (onClose) {
-      fileFrame.on('close', onClose);
+      fileFrame?.once('close', onClose);
     }
 
+    fileFrame?.once('content:activate:browse', () => {
+      // Force-refresh media modal contents every time
+      // to avoid stale data.
+      fileFrame?.content?.get()?.collection?._requery(true);
```
Comment (spacedmonkey) [inline assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Don't we also need to refresh media library if you drag an image/video into the editor?

Comment (swissspidy) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Yes, but this code already handles this, because it refreshes when opening the modal.

1. Drag video into editor to upload
2. Open media modal
3. Media modal refreshes automatically, and will include the new video

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 2 above)
Comment (swissspidy) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js:65]: Just a code quality refactor to make it clear that this is a global variable. Makes testing easier too.

Note that `global` in the browser will mean `window`, so `window.wp` as expected

File: assets/src/edit-story/components/mediaPicker/useMediaPicker.js (hunk 3 above)
Comment (swissspidy) [reply assets/src/edit-story/components/mediaPicker/useMediaPicker.js]: Just a safety measure to avoid inserting elements & generating posters multiple times should the event be fired more than once.

File: bin/local-env/install-wordpress.sh [hunk 5]
```diff
@@ -88,7 +88,8 @@ container chmod 767 \
 echo -e $(status_message "Import default set of media assets...")
 # TODO: use glob pattern to import items. See https://developer.wordpress.org/cli/commands/media/import/.
 wp media import /var/www/html/wp-content/e2e-assets/small-video.mov
-wp media import /var/www/html/wp-content/e2e-assets/small-video.webm
+WEBM_VIDEO_ID=wp media import /var/www/html/wp-content/e2e-assets/small-video.webm --porcelain
+wp media import /var/www/html/wp-content/e2e-assets/small-video-poster.jpg --post_id=$WEBM_VIDEO_ID
```
Comment (spacedmonkey) [inline bin/local-env/install-wordpress.sh]:
```suggestion
POSTER_ID=wp media import /var/www/html/wp-content/e2e-assets/small-video-poster.jpg --post_id=$WEBM_VIDEO_ID --porcelain
wp post meta set $WEBM_VIDEO_ID _thumbnail_id $POSTER_ID
```

Comment (swissspidy) [reply bin/local-env/install-wordpress.sh]: Ah! Good call. Can actually use the `--featured_image` arg though, so don't need an extra line.

Comment (spacedmonkey) [reply bin/local-env/install-wordpress.sh]:
```suggestion
wp media import /var/www/html/wp-content/e2e-assets/small-video-poster.jpg --post_id=$WEBM_VIDEO_ID --featured_image
``` 
So this? 

Didn't know that flag existed. Very cool

Comment (swissspidy) [reply bin/local-env/install-wordpress.sh]: Yep :) Just saw it in the docs too.

**Comment by spacedmonkey** [comment]
I am a little worried that these changes to set the featured image in sh script will make the poster generation tests in [insertWebMVideo.js](https://github.com/google/web-stories-wp/blob/main/tests/e2e/specs/editor/media/insertWebMVideo.js) a little pointless. We should also a `beforeAll` to a new video file and a `afterall` to remove that video.

**Comment by swissspidy** [comment]
> I am a little worried that these changes to set the featured image in sh script will make the poster generation tests in [insertWebMVideo.js](https://github.com/google/web-stories-wp/blob/main/tests/e2e/specs/editor/media/insertWebMVideo.js?rgh-link-date=2020-12-16T13%3A42%3A06Z) a little pointless. We should also a `beforeAll` to a new video file and a `afterall` to remove that video.

They _are_ already pointless, see #5540

**Comment by spacedmonkey** [comment]
> They are already pointless

If they are pointless, should we mark them as skip with a todo noting they need fixing?

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Comment by swissspidy** [comment]
@zidianlyu @spacedmonkey Oof! I think I finally cracked the last known issue with 878ec427232d0ff4934fca7f778c5049d5e3fe6a

**Review by spacedmonkey — APPROVED** [review]
In my testing, this seemed to work extremely well. The poster appears almost straight away now. Nice to see the test work better well. Happy this finally seems to be fixed. 👍

**Comment by zidianlyu** [comment]
Great work!👍
