### PR TITLE
Editor: Text Sets Panel Keyboard Navigation

### LINKED ISSUE #5878: Text Sets Keyboard Navigation
## Bug Description

Noticed while testing out missing keyboard functionality in page layouts that text sets also needs to get keyboard functionality added. 

## Expected Behaviour

Should be able to tab into text sets and then use my arrow keys to navigate them and tab again to exit text sets. See media keyboard functionality. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Previously the text sets were a tab trap, now you can use arrows to navigate through them.

## Summary

Enables users to tab to text sets and then use arrow keys (up, down, left, right) to go through options. Tab again to focus out of text sets onto the canvas (just like page layouts).

## Relevant Technical Choices

- Pulled the original solution for this out of pageLayouts and into a shared `virtualizedGridPanel` directory since they needed the same code. Figure we might have more virtualized lists in the future. 
- Cleaned code up to be more generic instead of for 'pageLayouts'.
- Updated a _few_ styles to the new design system but not everything. The ticket for that update is: #6214 - I wanted this a11y fix to go through without getting caught up in design. 

## To-do

- Came across a bug on the new toggle button for RTL, made a separate ticket:  #6548
- Unsure of proper aria labeling for text sets, ticket here: #6517 

## User-facing changes

Text Sets are now navigable by keyboard arrows 🎉  

text set keyboard nav
minor style updates

## Testing Instructions

- Go to editor and then the text panel. 
- Navigate to text sets with keyboard (`tab`), now use arrow keys to go through text sets. 
- Press `enter` to select a text set. 
- When you select a text set your focus will shift to the canvas with your new text set elements in focus. 

Regression tests: 
- Toggle text sets to 'match fonts from story'
- text set selection using cursor 
- page layout selection using keyboard 
- page layout selection using cursor

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #5878 
Partially addresses #6295 (TextSetItem uses role=listitem, but there's no parent with role=list, rest of that will follow naturally with pill group update)

### CODE REVIEW

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+
+/**
+ * This is a shared custom hook to enable keyboard arrow navigation on panels
+ * that use `useVirtual` to virtualize the contents. It takes over control of
+ * focus when keyboard is in play.
+ * Use the returned `handleGridFocus` as `onFocus` of the element that `containerRef` belongs.
+ * Use the returned `activeGridItemId` as a check in your map of gridItems against the id of
+ * each grid item to identify which grid item should get focus styles/behavior.
+ * Use the returned `handleGridItemFocus` as the gridItem `onFocus`, pass it the grid item's id as a param.
+ * Use the returned `isGridFocused` as a boolean to show focus styles or not.
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js:36]: ✨

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+    }
+  }, [activeGridItemId, currentAvailableRows, isGridFocused, gridItemRefs]);
+
+  useRovingTabIndex({ ref: containerRef });
+
+  const handleGridFocus = useCallback(() => {
+    if (!isGridFocused) {
+      const newGridItemId = gridItemRefs.current?.[activeGridItemId]
+        ? activeGridItemId
+        : gridItemIds[0];
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js]: Should we be defensive here incase there aren't any grid items?
```suggestion
        : gridItemIds?.[0];
```

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+      getTextSetsForFonts({
+        fonts: getInUseFontsForPages(storyPages),
+        textSets: selectedCat ? textSets[selectedCat] : allTextSets,
+      }),
+    [allTextSets, storyPages, selectedCat, textSets]
+  );
+
+  const addIdToTextSets = useCallback(
+    (sets) =>
+      sets.map((elements) => {
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: Probably not a big deal, but it may be confusing to see `sets` here since this is an `Array` and not a `Set`. Maybe we could change the name to something like `textSetsArray`?

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+    addIdToTextSets,
+    getTextSetsForInUseFonts,
+    showInUse,
+  ]);
+
+  const categories = useMemo(
+    () => [
+      ...Object.keys(textSets).map((cat) => ({
+        id: cat,
+        label: CATEGORIES[cat] ?? cat,
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: 💭 My preference is not to shorten variable names when we don't need to. I think it makes the code more readable 🐱 
```suggestion
      ...Object.keys(textSets).map((category) => ({
        id: category,
        label: CATEGORIES[category] ?? category,
```

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+      search_filter: showInUse ? 'show_in_use' : undefined,
+    });
+  }, [selectedCat, showInUse]);
+
+  const sectionId = useMemo(() => `section-${uuidv4()}`, []);
+  const toggleId = useMemo(() => `toggle_text_sets_${uuidv4()}`, []);
+  return (
+    <SectionContainer id={sectionId}>
+      <TitleBar>
+        <Headline size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.XX_SMALL}>
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: Getting a proptype error here:
image

Maybe to stay consistent with the `<Text />` api we could add a default

**Review by samwhale — CHANGES_REQUESTED** [review]
Code looks great, it is well organized and has helpful comments. Seeing a few weird things:

1. Seeing this warning in the console, not sure if it's a big deal:
```
Over 200 classes were generated for component displayElement__Wrapper with the id of "displayElement__Wrapper-sc-143lj7s-0".
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs(props => ({
    style: {
      background: props.background,
    },
  }))`width: 100%;`

  <Component /> 
    at displayElement__Wrapper (http://localhost:8899/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=b48b6458a018a1d84a04ce04b417014a:251908:19542)
    at DisplayElement (http://localhost:8899/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=b48b6458a018a1d84a04ce04b417014a:38655:3)
    at TextSetContainer (http://localhost:8899/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=b48b6458a018a1d84a04ce04b417014a:72790:3)
    at TextSetElements (http://localhost:8899/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=b48b6458a018a1d84a04ce04b417014a:72810:3)
    at div
    at textSet__TextSetItem (http://localhost:8899/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=b48b6458a018a1d84a04ce04b417014a:251908:19542)
```
2. There are some focus styles that are incorrect. It should be a quick fix but probably shouldn't do that in this pr. Maybe we could add an issue for that? 

3. When I hit the ⬅️ and ➡️ the screen jumps if the row that's being focused is not at the bottom of the page


4. In `RTL` mode both the ⬆️ and ⬇️ make the focus go `down` the list. 
5. Focusing an element further down in the list and then manually scrolling up makes you jump back down (unless you scroll all the way to the top of the panel)

**Comment by BrittanyIRL** [comment]
> Code looks great, it is well organized and has helpful comments. Seeing a few weird things:
> 
> 1. Seeing this warning in the console, not sure if it's a big deal:
> 
> ```
> Over 200 classes were generated for component displayElement__Wrapper with the id of "displayElement__Wrapper-sc-143lj7s-0"....```

This is from `<DisplayElement>` and happens a handful of spots! There's a ticket here: https://github.com/google/web-stories-wp/issues/5797 

> 
> 2. There are some focus styles that are incorrect. It should be a quick fix but probably shouldn't do that in this pr. Maybe we could add an issue for that?
> 

The github issue to redesign the text sets panel is #6214 - let's handle those there, was trying to keep this one contained to a11y as much as possible. 

> 3. When I hit the ⬅️ and ➡️ the screen jumps if the row that's being focused is not at the bottom of the page

I played with this for a while when initially implementing on page layouts : https://github.com/google/web-stories-wp/pull/5989#issuecomment-770093773 it's because scrolling in the virtualized hook is set to 'auto' to load more rows when the view shifts, but since using a keyboard arrow to go up/down is a bigger jump in the DOM than scroll it appears a little clunky. 


> 4. In `RTL` mode both the ⬆️ and ⬇️ make the focus go `down` the list.

This is known: https://github.com/google/web-stories-wp/issues/6108 because it's in this hook, it's actually not something that's specific to this use case and should be looked at as a whole. Good call out though. 

> 5. Focusing an element further down in the list and then manually scrolling up makes you jump back down (unless you scroll all the way to the top of the panel)

We're tracking the `active` (focused with keyboard) different from `hover` (cursor interaction) so that it's more performant. so the keyboard has no idea when the mouse is used to hover or scroll, it's still only aware of it's last left off actively viewed text set by keyboard.

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js (hunk 2 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js]: there should always be grid items here but being defensive is a good idea

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 3 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: good call, was so used to set as in textSet didn't realize that would be potentially confusing.

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 4 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: either works for me, i'll update it - shortening it doesn't do anything!

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 5 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js]: ah that was my bad, i made `as` mandatory in the headline so that you had pick where it went in the heading outline of the output html. 😂 so here i just forgot.

File: assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js [hunk 6]
```diff
@@ -44,13 +45,11 @@ export const PaneInner = styled.div`
   flex-direction: column;
 `;
 
-// padding-top is to help outlines on page layouts render
+// padding-top is to help outlines on page layouts
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/pageLayouts/pageLayoutsPane.js]: rm since padding-top is now defined in `virtualPaneContainer` ?

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js [hunk 7]
```diff
@@ -0,0 +1,188 @@
...
+          as="h3"
+          size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.XX_SMALL}
+        >
+          {PANE_TEXT.TITLE}
+        </Headline>
+        <TextSetsToggle>
+          <Text size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.SMALL}>
+            {PANE_TEXT.SWITCH_LABEL}
+          </Text>
+          <Toggle
```
Comment (samwhale) [inline assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js:159]: this is now gucci for RTL

**Review by samwhale — APPROVED** [review]
The code looks good! Thanks for letting me know that the other ux issues are being tracked

File: assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js (hunk 7 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/text/textSets/textSetsPane.js:159]: thank you so much for that quick fix!

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js [hunk 8]
```diff
@@ -0,0 +1,130 @@
...
+   * While it doesn't look like the DOM is updating, it is in fact updating.
+   * So the old refs get lost and the list gets new ones! By manually forcing focus and maintaining an object
+   * of gridItemRefs that are organized by gridItem id (those don't update) we can make sure the focus stays where it's supposed to be.
+   * Checking for a difference in currentAvailableRows and assigning the matching ref to any change is just so that the effect hook will run when the virtualized list
+   * updates and reattach focus to the new instance of an already selected layout.
+   */
+  useEffect(() => {
+    if (currentAvailableRows !== currentAvailableRowsRef?.current) {
+      currentAvailableRowsRef.current = currentAvailableRows;
+    }
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js:73]: Whats the purpose of the ref and assigning it on update? would just having `currentAvailableRows` in the dependencies provide us the same behavior?

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+
+      setActiveGridItemId(newGridItemId);
+      setIsGridFocused(true);
+      gridItemRefs.current?.[newGridItemId]?.focus();
+    }
+  }, [activeGridItemId, isGridFocused, gridItemIds, gridItemRefs]);
+
+  const handleGridItemFocus = useCallback(
+    (itemId) => {
+      if (activeGridItemId !== itemId) {
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js:96]: What does the checking against `itemId` here provide us?

File: assets/src/edit-story/components/library/panes/text/textSets/textSets.js [hunk 10]
```diff
@@ -17,209 +17,121 @@
...
-            );
-          })}
-        </TextSetContainer>
-      </UnitsProvider>
-    </SectionContainer>
+    <UnitsProvider
+      pageSize={{
+        width: TEXT_SET_SIZE,
+        height: TEXT_SET_SIZE / PAGE_RATIO,
+      }}
```
Comment (maxyinger) [inline assets/src/edit-story/components/library/panes/text/textSets/textSets.js]: Should we define this pageSize object outside the component?

**Review by maxyinger — APPROVED** [review]
Looks and works great! code reads well & good tests 🍻

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js (hunk 8 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js:73]: nope! this is the magic that holds the useRovingIndex together with the virtualized grid. we need a way to tell when the virtualized rows are updated behind the scenes because the DOM _looks_ the same but it's not. Otherwise keyboard nav gets focused. I tried to explain this in the comment above, i'll see if I can make it clearer.

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js (hunk 9 above)
Comment (BrittanyIRL) [reply assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/useVirtualizedGridNavigation.js:96]: ensures that the item asked to be in focus isn't already in focus. This isn't super relevant to text sets but it is for page layouts since there can be a confirmation dialog which means that when you return to the grid from that dialog you're already focused.

File: assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js [hunk 11]
```diff
@@ -164,68 +123,33 @@ function PageLayouts({ pages, parentRef }) {
...
-   * Checking for a difference in currentAvailableRows and assigning the matching ref to any change is just so that the effect hook will run when the virtualized list
-   * updates and reattach focus to the new instance of an already selected layout.
-   */
-  const currentAvailableRows = useMemo(() => rowVirtualizer.virtualItems, [
+  const {
+    activeGridItemId,
+    handleGridFocus,
+    handleGridItemFocus,
+    isGridFocused,
+  } = useVirtualizedGridNavigation({
```
Comment (embarks) [inline assets/src/edit-story/components/library/panes/pageLayouts/pageLayouts.js:137]: nice

File: assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/test/getVirtualizedItemIndex.js [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+ * limitations under the License.
+ */
+
+/**
+ * Internal dependencies
+ */
+import { getVirtualizedItemIndex } from '../getVirtualizedItemIndex';
+
+describe('getVirtualizedItemIndex', () => {
+  it.each`
```
Comment (embarks) [inline assets/src/edit-story/components/library/panes/shared/virtualizedPanelGrid/test/getVirtualizedItemIndex.js:23]: 🆒

**Review by embarks — APPROVED** [review]
🚢
