### PR TITLE
Safari text wrap hack

### LINKED ISSUE #6323: Text: Unexpected line wraps in Safari with Fill mode
## Bug Description

Original report: https://wordpress.org/support/topic/box-doesnt-wrap-text-correctly/
Story: https://www.acec.nl/web-stories/de-notenkrakerrrr/

There are unexpected line wraps on page 9 (the third to last one) in Safari, while the story displays correctly in Firefox and Chrome.

## Expected Behaviour

No line wraps, same behavior everywhere.

## Steps to Reproduce
1. Add a text that has at least two words, e.g. "Mal maken" from the link reported.
2. Set background mode to Fill
3. Unlock the text element width/height and set the width so that it would be as small width as possible but still allow the 2 words to be displayed in one line.
4. Save the story and open the story link to view it.
5. Grab the bottom right corner of the browser and start resizing it slowly to smaller. At some point, the text will be displayed in 2 lines:
Screenshot 2021-05-21 at 13 41 21
6. Leave the same window size and go to the editor. In testing, it seems to display 2 lines in the editor now, too, perhaps this will be helpful when debugging.

## Screenshots

Safari:
safari

Firefox:

firefox

Chrome:

chrome

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Context
"Fixes" the Safari text wrap issue by reducing the font size in Safari by 0.5px.
Based on conversation with Will (who also reached out to UX), potential underflow is a preferred bug compared to the overflow that was the origin of this issue.

Thus, the decision was to reduce the font size in Safari so that it would eliminate the overflow option.

## Summary
- Adds a hack for reducing the font size in Safari in the outout.

## Relevant Technical Choices
Adds an additional `span` wrapper to the `p` since otherwise it's not guaranteed there's a `span` inside.

## To-do

- [x] Test more thoroughly

## Testing Instructions
See the Steps to Reproduce in the description of https://github.com/google/web-stories-wp/issues/6323.
Verify it's not happening anymore.

### QA
See the steps above.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6323

### CODE REVIEW

File: assets/src/edit-story/output/utils/styles.js [hunk 1]
```diff
@@ -67,6 +67,14 @@ function CustomStyles() {
                 }
               }
 
+              @media not all and (min-resolution:.001dpcm) {
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js:81]: Please add a comment explaining what this Safari-only hack is for and reference the GH issue #.

File: assets/src/edit-story/output/utils/styles.js [hunk 2]
```diff
@@ -67,6 +67,14 @@ function CustomStyles() {
...
+                @media {
+                  p.text-wrapper > span:first-of-type {
```
Comment (dreamofabear) [inline assets/src/edit-story/output/utils/styles.js]: Is `:first-of-type` necessary? Is there more than one?

Comment (miina) [reply assets/src/edit-story/output/utils/styles.js]: Yes, there can be multiple, inline styling can use multiple spans for example.

Comment (dreamofabear) [reply assets/src/edit-story/output/utils/styles.js]: Are those multiple spans direct children of the `<p>`? Asking since we're using the `>` combinator.

File: assets/src/edit-story/output/utils/styles.js (hunk 1 above)
Comment (dreamofabear) [reply assets/src/edit-story/output/utils/styles.js:81]: Can we move the comment just above this line? 

```js
`...` 
/* ... */
+ `@media not all and (min-resolution:.001dpcm) {`
```

**Review by dreamofabear — APPROVED** [review]

File: assets/src/edit-story/output/utils/styles.js (hunk 2 above)
Comment (miina) [reply assets/src/edit-story/output/utils/styles.js]: Not really, now everything is wrapped to a single `span`. I mainly added this selector to ensure that only the required `span` gets the style to be extra sure since we can't really undo this change for the past stories -- it will be saved to post content statically.

I'll just remove it then since the way content is saved currently, it's not necessary.
