### PR TITLE
Floating Menu: Font Size, fix text element selection size

### LINKED ISSUE #10855: Floating Menu: Font Size not updating text selection box size
## Bug Description

 It looks like the text element size is not adjusting currently when changing the font size. When changing from the design panel (both when increasing / decreasing font size), it does change so it seems to be a bug with the floating menu logic only.

## Expected Behaviour

When the font size changes, the box that surrounds the text element should expand / contrast along with it. 
## Additional Context

In the design panel, `usePresubmitHandler` is the part that before submitting the values, makes sure the text element is adjusted properly as well, this only works in the design panel though together with pushUpdate.
Probably we'd need to use something like `getUpdatedSizeAndPosition` to update the size/position of the text element together with updating the font size (position is relevant if the element is rotated).

Might be worth refactoring to use the same component in both places, similar to the Font Family refactor ticket [#10628](https://github.com/GoogleForCreators/web-stories-wp/issues/10628)

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Context
When the font size changes, the box that surrounds the text element should expand / contrast along with it.

## Summary
This component can be used to replace the font size `StyledNumericInput` inside `FontControls`, but we would need to find a width for that input that works for both spots. The current width of `StyledNumericInput` is too narrow for 3 digit numbers. But this FontSize component is still a little wide. I am happy to chat with @agingoldseco to find a size that will allow us to pull this out and use it in both places. 

## Relevant Technical Choices
Grabbed `getUpdatedSizeAndPosition` thanks Miina. 

## User-facing changes
|before|after|
|--|--|
|font size|after|

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. select some text and change the font size. 
2. Check that the containing box size adjusts to fit the text. 

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10855

### CODE REVIEW

**Review by miina — APPROVED** [review]

File: packages/story-editor/src/components/floatingMenu/elements/fontSize.js [hunk 1]
```diff
@@ -36,18 +39,31 @@ function FontSize() {
...
-    });
+  const pushUpdate = useCallback(
+    (update) => {
+      updateSelectedElements({
+        properties: (element) => {
+          const updates = updateProperties(element, update, true);
+          const sizeUpdates = getUpdatedSizeAndPosition({
+            ...element,
+            ...updates,
+          });
```
Comment (samwhale) [inline packages/story-editor/src/components/floatingMenu/elements/fontSize.js:50]: oh nice, I didn't know this was a thing that existed 👍

**Review by samwhale — APPROVED** [review]

File: packages/story-editor/src/components/floatingMenu/elements/fontSize.js (hunk 1 above)
Comment (BrookeGraham) [reply packages/story-editor/src/components/floatingMenu/elements/fontSize.js:50]: Me either, Miina pointed me to it.

**Review by BrittanyIRL — APPROVED** [review]
