### PR TITLE
Properly implement default background element

### LINKED ISSUE #1191: History: Unsetting background media breaks the history
## Bug Description

When background media is removed, history stops working.

## Expected Behaviour
History should work as expected with any relevant action.

## Steps to Reproduce
1. Add background Media
2. Remove background Media
3. Try to use "Undo"
4. See nothing happening.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

We will change how background elements work in the reducer level.

New invariants:
* A page will always have a background element, which is the lowest-most element in the element list.
* A new page must come with a default background element.
* Whenever the background element is changed, if the old background element is the default background, it will be "moved" temporarily (with all attributes intact) to another property inside the page as a "default background element".
* Whenever the background element is unset, if it's the default background element, nothing happens. If it's not, there will be a "default background element" to restore as the new background element.
* The `backgroundElementId` property will be removed from the page, as it is now always similar to `elements[0].id` and can never be `null` anymore.

Consequences:

* `usePageBackground` can be removed.
* `createPage` will be split into `createPage` and `duplicatePage` as they're now rather different.
* `arrangeElement` can be simplified, as there will always be a background element to disregard (and not just sometimes as now).
* `selectElement`, `toggleElement` and `setSelectedElement` must be adapted to manually retrieve id of bottom-most element rather than just reading it from page.
* All other checks for `backgroundElementId` (mostly in canvas and output components) can be replaced by either checking `isBackground` property on element or position in `elements` list.
* A migration must be added.
* Tests and types must be updated.

### LINKED ISSUE #1405: Undo (CMD-Z) not restoring deleted background image
## Bug Description

Undo should revert my last update. If I delete the background of a page, this is not working. 

## Expected Behaviour

The background should be restored if I trigger an undo right after deleting the background. 

## Steps to Reproduce

1. Delete background image on a page
2. Trigger cmd+z (undo)

## Screenshots

Hard to show, as it's all keyboard stuff. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
## Summary

Implemented default background element as a single-step logic in stead of updating it to standard element when unset/deleted.

## Relevant Technical Choices

Did basically as described in #1191 in Implementation Brief.

## To-do

- [x] Implement, document and test new default background functionality removing `backgroundElementId`
- [x] Split `duplicatePage` from `createPage` and support new props
- [x] Changed story reducer to new background element structure including tests
- [x] Fix allowed properties per page and element
- [x] Added new migration for default background elements
- [x] Updated all references to background element ids in canvas and output components
- [x] Fixed new background element rules in `combineElements` and added tests
- [x] Fix some missing test coverage to bring it back up to 100% for story reducer

---

Fixes #1191 
Fixes #1405
Fixes partially #1411

### CODE REVIEW

**Comment by barklund** [comment]
I actually think this also fixes #1411.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js [hunk 1]
```diff
@@ -62,20 +62,20 @@ function arrangeElement(state, { elementId, position }) {
...
+  if (page.elements.length < 3) {
     return state;
   }
 
   const currentPosition = page.elements.findIndex(
     ({ id }) => id === idToArrange
   );
 
-  if (currentPosition === -1 || page.backgroundElementId === idToArrange) {
+  if (currentPosition === -1 || page.elements[0].id === idToArrange) {
```
Comment (wassgha) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js:74]: Would be cleaner if we hid this behind a `getBackgroundElement` util instead of accessing the `0`th element

File: assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js [hunk 2]
```diff
@@ -45,10 +47,12 @@ function addPage(state, { page, position }) {
 
   const { id } = page;
 
-  // Ensure new page has elements array and background id
+  // Ensure new page has at least one element
+  if (!page.elements?.length >= 1) {
+    return state;
```
Comment (wassgha) [inline assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js:52]: Is this right? Would we want to add the element if it doesn't exist?

**Comment by miina** [comment]
> I actually think this also fixes #1411.

Just tested it for confirmation: it looks like currently "Remove as background" doesn't work at all for media that has been dragged to canvas directly from the Library -> couldn't confirm yet if it fixes it or not. Does it work as expected for you?

**Review by wassgha — COMMENTED** [review]
Took a quick look, looks good but I'll give it a more thorough review

File: assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+          backgroundElementId: 'x',
+          elements: [{ id: 'x' }],
+        },
+      ],
+    });
+    const page = migrated.pages[0];
+    expect(page).not.toHaveProperty('backgroundElementId');
+  });
+
+  it('should mark existing background shapes as default background', () => {
```
Comment (miina) [inline assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js:36]: Nit: should mark only the first shape as default background

File: assets/src/edit-story/elements/index.js [hunk 4]
```diff
@@ -46,40 +46,40 @@ export const createNewElement = (type, attributes = {}) => {
...
+    isBackground: true,
+    isDefaultBackground: true,
+  };
+  const backgroundElement = createNewElement('shape', backgroundElementProps);
+
+  const newAttributes = {
+    elements: [backgroundElement],
+  };
+
+  return createNewElement('page', newAttributes);
```
Comment (miina) [inline assets/src/edit-story/elements/index.js:68]: Should `createNewElement` perhaps complain if a page is being created without a required value? To ensure `createNewElement` is not called directly for a page.

File: assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js [hunk 5]
```diff
@@ -39,6 +39,100 @@ describe('updateElementById', () => {
...
+          elements: [
+            { id: '123', isBackground: true, isDefaultBackground: true, x: 1 },
+            { id: '456' },
+          ],
+        },
+      ],
+      current: '111',
+    });
+
+    // only x=2 is allowed to be changed here
```
Comment (miina) [inline assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js:114]: Is there a reason why the default background element attributes should be allowed to be changed at all? Should this just be ignored then? Wouldn't it cause an additional history entry otherwise?

File: assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js [hunk 6]
```diff
@@ -100,19 +133,70 @@ describe('deleteElementsById', () => {
...
+            { id: '456' },
+            { id: '789' },
+          ],
+        },
+      ],
+      current: '111',
+      selection: [],
+    });
+
+    // 789 is selected, 456 is not
```
Comment (miina) [inline assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js]: ^ Hmm? What does this mean in this context?

File: assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js [hunk 7]
```diff
@@ -100,19 +133,70 @@ describe('deleteElementsById', () => {
...
+        {
+          id: '111',
+          elements: [{ id: '123', isBackground: true }, { id: '234' }],
+        },
+      ],
+      selection: ['234'],
+    });
+  });
+
+  it('should skip default background element if included', () => {
```
Comment (miina) [inline assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js:165]: Perhaps one for restoring the default background element as well if the non-default background element gets deleted?

Comment (miina) [reply assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js:165]: Just saw you have a test exactly for that in `deleteElementById`.

**Review by miina — CHANGES_REQUESTED** [review]
Awesome test coverage 🎉 

Two main things:
- It looks like `isDefaultBackground` remains on the background element if media is dragged directly from the library, making it not possible to remove. Or well -- basically it looks like dragging media to a background directly overwrites the default background element. Ideally, the default background element would be non-changeable. (Except for the ID perhaps)

- It's possible to duplicate a background by copy-paste. That issue existed before, too, though, but mentioning it in case you think it makes sense to adjust it here together with the general refactoring

**Review by wassgha — COMMENTED** [review]
Manually tested all the drop target interactions and everything looks good!

File: assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js (hunk 2 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/addPage.js:52]: It should never not exist. If you create the page via `addPage`, it'll come with one and you can never delete it. So it shouldn't happen.

File: assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js (hunk 1 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/reducers/arrangeElement.js:74]: I'm still considering something to this effect. Maybe both have `page.elements[0]` and `page.backgroundElement` point to the same object? It's stupid for serialization purposes of course, where we should remove one of them, but otherwise might make sense.

File: assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js (hunk 3 above)
Comment (barklund) [reply assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js:36]: Only one element _can_ be background, though?

File: assets/src/edit-story/elements/index.js (hunk 4 above)
Comment (barklund) [reply assets/src/edit-story/elements/index.js:68]: I don't think that's necessary. Where would that happen? I don't see someone extending the API and making such a mistake.

File: assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js:114]: Actually only one attribute of the background element can be "legally" changed: `backgroundColor` - which is how you change the color/pattern of said background. All other changes should be disallowed or actually turn it into a non-default-background element (and clone the previous element to the default).

This is how dropping a media element directly from library works - it simply merges all the properties from the media element into the background via `updateElementById` (and this is the cause of other problems).

File: assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js (hunk 6 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/test/deleteElementsById.js]: Copy-paste error. Fixed in ba7fdebe.

**Comment by barklund** [comment]
> * It looks like `isDefaultBackground` remains on the background element if media is dragged directly from the library, making it not possible to remove. Or well -- basically it looks like dragging media to a background directly overwrites the default background element. Ideally, the default background element would be non-changeable. (Except for the ID perhaps)

Yes, that's the cause of a series of inconsistencies. Basically direct-drag should work exactly as click-and-then-drag. I will look into how these can be combined.

> * It's possible to duplicate a background by copy-paste. That issue existed before, too, though, but mentioning it in case you think it makes sense to adjust it here together with the general refactoring

I think this belongs in a separate issue. I think it should basically be handled in the paste-handler just removing the `isBackground` (and potential `isDefaultBackground` attribute)  from any pasted element and thus paste a simple shape or image as inline object and not full-screen background element. It belongs elsewhere.

File: assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js (hunk 5 above)
Comment (barklund) [reply assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js:114]: I have now changed this, so that dragging an element from media library directly to an existing element will go through `combineElements` rather than `updateElement` which unifies this handling. Please re-review after 4594f129.

**Comment by barklund** [comment]
> > * It looks like `isDefaultBackground` remains on the background element if media is dragged directly from the library, making it not possible to remove. Or well -- basically it looks like dragging media to a background directly overwrites the default background element. Ideally, the default background element would be non-changeable. (Except for the ID perhaps)
> 
> Yes, that's the cause of a series of inconsistencies. Basically direct-drag should work exactly as click-and-then-drag. I will look into how these can be combined.

This has now been combined in `combineElements` in 4594f12.

File: assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js (hunk 3 above)
Comment (miina) [reply assets/src/edit-story/migration/migrations/test/v0018_defaultBackgroundElement.js:36]: Well, I know. It's just for the test description purposes, to clarify that the migration would only try to mark the first existing shape as the default background. Not that important though.

File: assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js (hunk 5 above)
Comment (miina) [reply assets/src/edit-story/app/story/useStoryReducer/test/updateElementById.js:114]: OK, I was wondering why "drag along" the `defaultBackgroundElement` if it's all static except for the `id` but looks like the background color needs changing, indeed.

**Review by miina — APPROVED** [review]

**Comment by miina** [comment]
@barklund:
 Ah, actually one more thing related to #1411 which is marked as fixed by this PR -- #1411 is for general inconsistencies, currently, there is still inconsistency when assigning background via "Set as background" compared to dragging to the background -- in case of Flipping.

To reproduce:
1. Drag a media to background
2. Flip it
3. Now drag new media to background
4. It's already flipped!
5. Now add a new Image to Page
6. Set that as background via "Set as background"
7. It's not flipped

==> Inconsistency.

That's something that #1411 was meant for and could be addressed separately, however, in this case we should mark this PR as partially fixing #1411 and not fully.

File: assets/src/edit-story/migration/migrations/v0018_defaultBackgroundElement.js [hunk 8]
```diff
@@ -0,0 +1,63 @@
+/*
```
Comment (miina) [inline assets/src/edit-story/migration/migrations/v0018_defaultBackgroundElement.js:1]: @barklund A bit late but I just realized that Dashboard templates would likely need updating as well -- these are currently still using the previous non-migrated elements (if I understand correctly). At least I can still see `backgroundElementId` being used in the templates. cc @carlos-kelly

Comment (barklund) [reply assets/src/edit-story/migration/migrations/v0018_defaultBackgroundElement.js:1]: Oh thanks, wasn't aware. @carlos-kelly, please chime in if we should keep templates updated as we migrate the data format?
