### PR TITLE
Color Picker: Propagate dimensions when switching mode

### LINKED ISSUE #8673: Color picker can overflow viewport when switching state
## Bug Description

When switching from custom color picker to basic color picker, the popup window extends and this can cause the popup to move slightly off-screen.

This can also happen if you add a new custom color in the custom view as the picker switches to the basic state, but the list of saved colors now extends by one more row.

## Expected Behaviour

Popup should always be inside the visible viewport area.

## Steps to Reproduce

1. Make sure to have 7+ saved global colors.
2. Open the new basic color picker
3. Switch to custom color picker mode
4. Scroll the design panel so the bottom of the color picker aligns with the bottom of the viewport
5. Switch to basic color picker mode

## Screenshots

propagation

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Ensures part of the color picker doesn't get hidden when switching views.

## User-facing changes
cpicker

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Make sure to have 7+ saved global colors.
2. Add a shape and assign radial color from the Custom picker mode.
3. Close the Color Picker
4. Scroll so that the Color Input in the design panel would be in the bottom part of the screen.
5. Now open the color picker for the radial color.
6. Switch to Basic Color Picker view 
7. Verify that all the lower parts of the Color Picker are visible (and not out of the screen), including the "Custom" button.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8673

### CODE REVIEW

File: packages/story-editor/src/components/colorPicker/colorPicker.js [hunk 1]
```diff
@@ -72,13 +72,20 @@ function ColorPicker({
   allowsSavedColors = false,
   onClose = () => {},
   changedStyle = 'background',
+  onDimensionChange = () => {},
```
Comment (barklund) [inline packages/story-editor/src/components/colorPicker/colorPicker.js:75]: Does it need a default? Isn't it always set (except maybe for some tests)?

**Review by barklund — APPROVED** [review]
🌕

File: packages/story-editor/src/components/colorPicker/colorPicker.js (hunk 1 above)
Comment (miina) [reply packages/story-editor/src/components/colorPicker/colorPicker.js:75]: Yep, it's not set in some tests. Probably doesn't harm, having a default.
