### PR TITLE
Story Editor: Preset Panel Height & Collapse Persistence

### LINKED ISSUE #825: UI settings don't persist between reloads
## Bug Description

UI settings such as collapsed panel states should persist across reloads. The following settings need to persist:

* Panel state (collapsed/open)
* Layer panel height
* Selected page (let's attach this as hash to the current URL, like Google Slides)

The following should not persist:

* Selected tab in design panel
* Selected tab in element panel

/cc @samitron7 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Persists height and collapsed state of all panels in story editor. Panels should remain collapse & height between reloads, element selection & switching stories now.

## Relevant Technical Choices
Persisted all panels height & collapsed state.

## To-do
NA

## User-facing changes
collapse/height state changes to all panels should now maintain between any actions in the editor.

## Testing Instructions
Go to edit a story.
- Click on an item & resize color preset panel. Click off that item so all panels disappear. Click back on the item and see that the color preset panel height is the same.
- Repeat these steps checking if collapse state maintains
- Repeat these steps but reload you page between checks
- See that other than this, design panels still behave as expected with respect to resize/collapse behavior.

---

Partially fixes #825

### CODE REVIEW

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 1]
```diff
@@ -43,13 +45,39 @@ function Panel({
   initialHeight = null,
   ariaLabel = null,
   ariaHidden = false,
+  persistenceKey,
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/panel.js]: Could we just use `name` for the key?

And then only use a prop for a boolean flag to toggle whether changes should persist?

File: assets/src/edit-story/components/panels/preset/presetPanel.js [hunk 2]
```diff
@@ -136,6 +136,7 @@ function PresetPanel({
       initialHeight={Math.min(initialHeight, window.innerHeight / 3)}
       resizeable={resizeable}
       canCollapse={canCollapse}
+      persistenceKey={title}
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/preset/presetPanel.js]: That's error prone because `title` is translatable. I'd suggest just using `name` here.

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 3]
```diff
@@ -43,13 +45,39 @@ function Panel({
...
-  const [expandToHeight, setExpandToHeight] = useState(initialHeight);
-  const [height, setHeight] = useState(initialHeight);
+  const persisted = useMemo(() => {
+    const stored = localStorage.getItem(
+      `${LOCAL_STORAGE_PREFIX}:${persistenceKey}`
+    );
+    return stored && JSON.parse(stored);
+  }, [persistenceKey]);
+  const [isCollapsed, setIsCollapsed] = useState(
+    persisted?.isCollapsed || false
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/panel.js]: Could probably just be this?

```suggestion
    Boolean(persisted?.isCollapsed)
```

File: assets/src/edit-story/components/panels/panel/panel.js (hunk 1 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/panel/panel.js]: This will cause conflicts between the style and color preset panel no? since they both have the same `name="stylepreset"` hardcoded

File: assets/src/edit-story/components/panels/preset/presetPanel.js (hunk 2 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/preset/presetPanel.js]: Yea, I figured this was such a small edge & would happen so infrequently it'd be fine for now. Happy to key off a different value tho if you see one that better suits it

File: assets/src/edit-story/components/panels/panel/panel.js (hunk 3 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/panel/panel.js]: yeaup. good call

File: assets/src/edit-story/components/panels/panel/panel.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/components/panels/panel/panel.js]: Hmm perhaps they should just pass 

```
name={`stylepreset-${presetType}`}
```

?

Comment (maxyinger) [reply assets/src/edit-story/components/panels/panel/panel.js]: maybe a prefixed `presetType` may be best for the key for now?

File: assets/src/edit-story/components/panels/preset/presetPanel.js (hunk 2 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/preset/presetPanel.js]: https://github.com/google/web-stories-wp/pull/4601#discussion_r492287834

Comment (swissspidy) [reply assets/src/edit-story/components/panels/preset/presetPanel.js]: It means the panel states will change whenever users change their preferred UI language or whenever the translation changes. The latter will probably be a bit more frequent especially after our initial release, as users will start to translate the plugin.

File: assets/src/edit-story/components/panels/panel/panel.js (hunk 1 above)
Comment (swissspidy) [reply assets/src/edit-story/components/panels/panel/panel.js]: @littlemilkstudio I think we just sent this at the same time? 😅

**Comment by carloskelly13** [comment]
@swissspidy Should we allow a partial panel open like this or size it to the closest color swatch? Doesn't have to be part of this PR, but from a UX standpoint this feels odd. At least for the first row.

Screen Shot 2020-09-21 at 2 29 35 PM

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 4]
```diff
@@ -35,6 +35,8 @@ const Wrapper = styled.section`
   position: relative;
 `;
 
+const LOCAL_STORAGE_PREFIX = 'web_stories_ui_settings';
```
Comment (carloskelly13) [inline assets/src/edit-story/components/panels/panel/panel.js]: Only thought here would be if the editor has a constants file.

**Review by carloskelly13 — APPROVED** [review]
This works well. Tested both the sizing of the saved presets and then the collapse states of the other design panels too.

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 5]
```diff
@@ -44,12 +45,34 @@ function Panel({
...
   ariaHidden = false,
 }) {
-  const [isCollapsed, setIsCollapsed] = useState(false);
-  const [expandToHeight, setExpandToHeight] = useState(initialHeight);
-  const [height, setHeight] = useState(initialHeight);
+  const persisted = useMemo(() => {
+    const stored = localStorage.getItem(
+      `${LOCAL_STORAGE_PREFIX.PANEL}:${name}`
+    );
+    return stored && JSON.parse(stored);
```
Comment (barklund) [inline assets/src/edit-story/components/panels/panel/panel.js]: I think we need to wrap this in a try-catch to make it less fragile. Users can edit this themselves, random plugins can impact it too - stuff happens.

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 6]
```diff
@@ -44,12 +45,34 @@ function Panel({
   ariaLabel = null,
   ariaHidden = false,
 }) {
-  const [isCollapsed, setIsCollapsed] = useState(false);
-  const [expandToHeight, setExpandToHeight] = useState(initialHeight);
-  const [height, setHeight] = useState(initialHeight);
+  const persisted = useMemo(() => {
+    const stored = localStorage.getItem(
+      `${LOCAL_STORAGE_PREFIX.PANEL}:${name}`
+    );
```
Comment (barklund) [inline assets/src/edit-story/components/panels/panel/panel.js]: I think adding a default value makes sense here:

```js
    const stored = localStorage.getItem(
      `${LOCAL_STORAGE_PREFIX.PANEL}:${name}`,
      'null',
    );
```

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js [hunk 7]
```diff
@@ -35,6 +35,9 @@ describe('Panel: Style Presets', () => {
   };
 
   beforeEach(async () => {
+    // Make sure panels are starting at initial state on every test
+    localStorage.clear();
```
Comment (barklund) [inline assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js:38]: Hm, this should probably go in some global reset. @swissspidy, suggestions?

**Review by barklund — COMMENTED** [review]
Looks good, just a few minor comments.

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js (hunk 7 above)
Comment (maxyinger) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js:38]: Yea let me know here. I'm not the most familiar with the Karma tests, but think this was causing the main issue

Comment (swissspidy) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js:38]: Yeah probably. `karma/fixture/init.js` has similar resets already.

**Comment by swissspidy** [comment]
> @swissspidy Should we allow a partial panel open like this or size it to the closest color swatch? Doesn't have to be part of this PR, but from a UX standpoint this feels odd. At least for the first row.
> 
> Screen Shot 2020-09-21 at 2 29 35 PM

@carlos-kelly Good catch! Sounds like an odd thing to allow. There's probably some UX definition for this already. I suggest opening an issue and tagging Sam there.

**Comment by pbakaus** [comment]
OMG amazing. Thank you!

**Comment by miina** [comment]
For considering later:
In case of presets, it might be good to reset the panel height if all the presets are removed meanwhile. Otherwise, a previous (and now emptied) panel setting could leave unexpected room, e.g.
panels

File: assets/src/edit-story/components/panels/panel/panel.js [hunk 8]
```diff
@@ -44,12 +45,41 @@ function Panel({
...
+  const persisted = useMemo(() => {
+    let parsed = null;
+    try {
+      const stored = localStorage.getItem(
+        `${LOCAL_STORAGE_PREFIX.PANEL}:${name}`,
+        'null'
+      );
+      parsed = JSON.parse(stored);
+    } catch (e) {
+      // @TODO Add some error handling.
```
Comment (swissspidy) [inline assets/src/edit-story/components/panels/panel/panel.js:56]: Hmm `setInitialBannerPreviouslyClosed` in `useTelemetryOptIn` should probably also wrap this in a try/catch

cc @dmmulroy

File: assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js (hunk 7 above)
Comment (swissspidy) [reply assets/src/edit-story/components/panels/preset/karma/stylePresets.karma.js:38]: Can be done in a follow-up ticket / PR too, FWIW

File: assets/src/edit-story/components/panels/panel/panel.js (hunk 8 above)
Comment (dmmulroy) [reply assets/src/edit-story/components/panels/panel/panel.js:57]: Sounds good, I'll update that right now - @littlemilkstudio what is the second argument in `getItem` for?  As far as I can tell `getItem` only accepts one argument?

Comment (dmmulroy) [reply assets/src/edit-story/components/panels/panel/panel.js:56]: I have no problem updating it, but what error is this catching? It seems like exceptions can be potentially thrown if the user has prevented a site from using Storage APIs, but none of our other `localstorage` uses are wrapped in try/catch (see just below).  Should we mandate that all `localstorage` access be wrapped, or a utility to check for access prior to using it?

Also, what is the second argument to `getItem`?  AFAIK it only accepts one and it will already return `null` by default if a key does not exists which is fine to pass to `JSON.parse`

**Comment by swissspidy** [comment]
@littlemilkstudio Looking at the Percy screenshots the default size for the layer panel seems to have changed.

Left is before, right is after:

Screenshot 2020-09-22 at 15 54 32

See how the background layer item disappears.

It's even more obvious when editing a template:

Screenshot 2020-09-22 at 15 55 18

Can you double check that?

**Review by dmmulroy — APPROVED** [review]
This works for me!

**Comment by dmmulroy** [comment]
> This works for me!

Just saw Pascal's comment about default size of the lay panel, once that's good I'm good with this 👍

**Comment by maxyinger** [comment]
> @littlemilkstudio Looking at the Percy screenshots the default size for the layer panel seems to have changed.
> 
> Left is before, right is after:
> 
> Screenshot 2020-09-22 at 15 54 32
> 
> See how the background layer item disappears.
> 
> It's even more obvious when editing a template:
> 
> Screenshot 2020-09-22 at 15 55 18
> 
> Can you double check that?

Ahh yea, I think Percy has the value persisted between tests. Must have a test on a story where there's only 1 layer initially, so these steps follow:
- Open story with 1 layer
- uses min of layers or 6 which is 1 layer here to compute initial height
- height gets set to persist
- open new story with 6 layers, initialHeight is ignored and goes with persisted height from earlier

Updated the behavior to now only cache the state values if the user has interacted with the panel. So it shouldn't persist until the user either adjusts height of the panel or collapses it. This implementation certainly comes with it's edge cases, but this is some UX we should fine tune for a later release and just include this simpler behavior for now imo
