### PR TITLE
Fix being able to add duplicate color presets

### LINKED ISSUE #5216: Clicked "add new saved color" with multiple text elements selected, added multiple instances of the same color
## Bug Description

Was editing the color for 4 different text elements, selected a new color. Clicked "Save color" button. 

## Expected Behaviour

Expected the color to be added once, since it was the same color. Instead, got 4 different color swatches saved. 

## Steps to Reproduce

1. add multiple text elements - i used a text set
2. select multiple text elements
3. apply a new color to all of the text elements
4. click on add new saved color

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Ensure that only unique color presets are added, even if selecting two elements with the same color and clicking to add presets.

## Testing Instructions
Test the following with different text styles / colors and also with shapes:
1. Add two or more elements that have identical color or style or background-color.
2. Select both/all elements and click `+` to add color preset.
3. Verify that only unique presets are added -- if two elements have the same background color then the color is not added twice.

---

Fixes #5216

### CODE REVIEW

**Comment by swissspidy** [comment]
@miina FYI there are some lint errors

File: assets/src/edit-story/components/panels/design/preset/utils.js [hunk 1]
```diff
@@ -129,41 +129,47 @@ function getTextInlineStyles(content) {
   };
 }
 
+function getUniquePresets(presets) {
+  const list = presets.map((preset) => JSON.stringify(preset));
+  return Array.from(new Set(list)).map((preset) => JSON.parse(preset));
+}
```
Comment (barklund) [inline assets/src/edit-story/components/panels/design/preset/utils.js:135]: Uh, this sounds a bit expensive. Are we sure it's performant? How often does this function run?

Comment (barklund) [reply assets/src/edit-story/components/panels/design/preset/utils.js:135]: Hm, can't really come up with a better solution though. But I really think we should performance test this with e.g. 50 objects and run it a couple of times a second and see if performance degrades.

**Review by barklund — APPROVED** [review]
Working solution, albeit perhaps a bit expensive.

File: assets/src/edit-story/components/panels/design/preset/utils.js (hunk 1 above)
Comment (miina) [reply assets/src/edit-story/components/panels/design/preset/utils.js:135]: This only runs when new presets are being added from elements (user clicks on the + sign while elements selected). Unlikely that someone will add 50 elements with different presets to add those at the same time. Could happen in theory 🤷  Thoughts?

Comment (miina) [reply assets/src/edit-story/components/panels/design/preset/utils.js:135]: Tested it out by adding tons of shapes (didn't really count how many but a lot) and visually it worked without any lag at all. From the profiler it looked like the click handler took almost the same time in the case of 2 elements vs 40+ elements (around 100-150ms).
